### PR TITLE
fix #38720

### LINKED ISSUE #38720: QGIS 3.10.10 and 3.14.16 report a python error on startup
Hi,
new releases report python error on startup

2020-09-13T22:30:44     WARNING    Python-Fehler : Ein Fehler trat bei der Ausführung von Python-Code auf: Mehr Details im Protokoll (Python-Fehler).

2020-09-13T22:30:44     WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 777, in _import
              new_path = os.environ['PATH']
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\os.py", line 675, in __getitem__
              value = self._data[self.encodekey(key)]
              File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\os.py", line 744, in encodekey
              return encode(key).upper()
             RecursionError: maximum recursion depth exceeded

BS: win10

### PR DESCRIPTION
**Pull request by jef-n**
removal of debug output apparently fixes the issue.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@jef-n I can confirm this -- thanks!!

**Comment by nyalldawson** [comment]
Won't we need to backport this to 3.14 for a fixed 3.14.16 release?

**Comment by jef-n** [comment]
> Won't we need to backport this to 3.14 for a fixed 3.14.16 release?

Re-add the tag?

**Comment by jef-n** [comment]
> Won't we need to backport this to 3.14 for a fixed 3.14.16 release?

cherry-picked in df27394

**Pull request merged**
