### PR TITLE
Refactor edit form configuration out of QgsVectorLayer

### PR DESCRIPTION
**Pull request by m-kuhn**
The class QgsVectorLayer is terribly overcrowded.

This commit refactors everything related to the edit form out.

Instead of accessing

```
layer.labelOnTop(1)
```

You will now do

```
layer.editFormConfig().labelOnTop(1)
```

Some methods have been renamed in their new incarnation, because their scope in the edit form is implicit:

E.g.
`editFormInit` -> `initFunction`

The old methods are still there as deprecated functions, so code will just continue to work.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Yes please!

**Comment by m-kuhn** [comment]
Suggestions about methods that could be renamed (to be more meaningful or shorter) are still welcome :)

**Comment by nyalldawson** [comment]
Actually this reminds me... I was planing on removing the layer transparency/blend mode stuff from QgsVectorLayer and moving it to the renderer (where it always should have been... oops!)

**Comment by m-kuhn** [comment]
I've given it another round of method renaming. I like it much more now.

**Comment by m-kuhn** [comment]
So, for the interested, here's a summary of the method name changes
https://github.com/m-kuhn/QGIS/commit/e2a1584538a0daa30fa94c69178f33c5faba6274

**Comment by 3nids** [comment]
good job, this will bring a bit of clarity in there!

**Comment by m-kuhn** [comment]
Merged

**Pull request closed without merging**
