### PR TITLE
Better GRASS r.series description to help workaround a limitation of Processing

### PR DESCRIPTION
**Pull request by gioman**
## Description
In Processing the different bands of a raster layer cannot be used as different inputs (when the module uses the "select input raster layers" widget), so we improve the description stating that the inputs/bands must be in separate datasources.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] Did not drink while coding

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]
FYI - I looked into what it would take to allow "None" values for this parameter type, but it's non trivial (would both min and max be none? Do we need to allow null min with forced non-null max? Etc)

**Comment by gioman** [comment]
> FYI - I looked into what it would take to allow "None" values for this parameter type, but it's non trivial (would both min and max be none? Do we need to allow null min with forced non-null max? Etc)

@nyalldawson Hi Nyall,

do you refer to this https://issues.qgis.org/issues/21452#note-6 , correct?

if yes, in general it would be needed to allow us set min/max (one or both) as empty or to set any default value the tool may need. In the specific case that is a optional parameter, as it is filled by default with "0" is passed as argument even if the user don't want (so actually it become non optional). Moreover the "0" default leads to wrong results (in 2.18 at least we could set better defaults when the tool opened) @luipir 

This affects also other tools, like r.in.lidar

**Comment by gioman** [comment]
> This affects also other tools, like r.in.lidar

i.e. https://issues.qgis.org/issues/17611#note-12

**Comment by nyalldawson** [comment]
@gioman 
> do you refer to this https://issues.qgis.org/issues/21452#note-6 , correct?

Yes. The reality is that the range parameter is currently only used inside grass algorithms and is rather undeveloped when compared to other parameter types. Would be good to fix this in future, but it'd be a good couple of hours work to do. So in the meantime, using the 2.18 approach for 21452 seems acceptable to me.

**Comment by gioman** [comment]
> > 
> 
> Yes. The reality is that the range parameter is currently only used inside grass algorithms and is rather undeveloped when compared to other parameter types. Would be good to fix this in future, but it'd be a good couple of hours work to do.

ok, I filed a feature request https://issues.qgis.org/issues/21558




> So in the meantime, using the 2.18 approach for 21452 seems acceptable to me.

sorry for the noob question, but I can't figure how to set min/max values of our choice in QgsProcessingParameterRange. Or maybe the suggestion it to use the QGIS 3 equivalent of the old "ParameterString"?

**Pull request merged**
