### PR TITLE
Fix a crash when rendering a raster outside of its extent

### PR DESCRIPTION
**Pull request by wonder-sk**
If QgsRasterLayerRenderer constructor exists prematurely because there is nothing to render, its internal pointers end up null, but forceRasterRender() was expecting that mPipe was always allocated.

The crash was introduced recently in #50382

The crash was happening at least in 3D rendering when generating 2D map texture, with a backtrace like this:
```
#0  0x00007ffff1c0858e in QMap<Qgis::RasterPipeInterfaceRole, int>::contains(Qgis::RasterPipeInterfaceRole const&) const
    (this=0x8, akey=@0x7fffffffb7b4: Qgis::RasterPipeInterfaceRole::Renderer) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmap.h:707
#1  0x00007ffff1c0644f in QgsRasterPipe::interface(Qgis::RasterPipeInterfaceRole) const (this=0x0, role=Qgis::RasterPipeInterfaceRole::Renderer)
    at /home/martin/qgis/git-master/src/core/raster/qgsrasterpipe.cpp:260
#2  0x00007ffff1c06559 in QgsRasterPipe::renderer() const (this=0x0) at /home/martin/qgis/git-master/src/core/raster/qgsrasterpipe.cpp:274
#3  0x00007ffff1bfeab4 in QgsRasterLayerRenderer::forceRasterRender() const (this=0x55555fa4d540)
    at /home/martin/qgis/git-master/src/core/raster/qgsrasterlayerrenderer.cpp:381
#4  0x00007ffff1a02b75 in QgsMapRendererJob::prepareJobs(QPainter*, QgsLabelingEngine*, bool)
     (this=0x55555ef10720, painter=0x55555ed119c0, labelingEngine2=0x0, deferredPainterSet=false) at /home/martin/qgis/git-master/src/core/maprenderer/qgsmaprendererjob.cpp:575
#5  0x00007ffff19f9864 in QgsMapRendererCustomPainterJob::startPrivate() (this=0x55555ef10720)
    at /home/martin/qgis/git-master/src/core/maprenderer/qgsmaprenderercustompainterjob.cpp:120
#6  0x00007ffff19ff2a9 in QgsMapRendererJob::start() (this=0x55555ef10720) at /home/martin/qgis/git-master/src/core/maprenderer/qgsmaprendererjob.cpp:149
#7  0x00007ffff1a192b2 in QgsMapRendererSequentialJob::startPrivate() (this=0x55555a154b30)
    at /home/martin/qgis/git-master/src/core/maprenderer/qgsmaprenderersequentialjob.cpp:76
#8  0x00007ffff19ff2a9 in QgsMapRendererJob::start() (this=0x55555a154b30) at /home/martin/qgis/git-master/src/core/maprenderer/qgsmaprendererjob.cpp:149
#9  0x00007fffef28f440 in QgsTerrainTextureGenerator::render(QgsRectangle const&, QgsChunkNodeId, QString const&)
    (this=0x55555da027a0, extent=..., tileId=..., debugText=...) at /home/martin/qgis/git-master/src/3d/terrain/qgsterraintexturegenerator_p.cpp:64
#10 0x00007fffef293275 in QgsTerrainTileLoader::loadTexture() (this=0x55555879d9c0) at /home/martin/qgis/git-master/src/3d/terrain/qgsterraintileloader_p.cpp:65
#11 0x00007fffef27fb8f in QgsDemTerrainTileLoader::onHeightMapReady(int, QByteArray const&) (this=0x55555879d9c0, jobId=17, heightMap=...)
    at /home/martin/qgis/git-master/src/3d/terrain/qgsdemterraintileloader_p.cpp:142
```

### CODE REVIEW

**Comment by nyalldawson** [comment]
Ouch! We better beg @jef-n to include this in the 3.28.0 release ....

**Review by nyalldawson — APPROVED** [review]
Could you add a test too? Looks like an important situation missing test coverage

**Comment by nyalldawson** [comment]
3.22 is unaffected

**Comment by wonder-sk** [comment]
Test added to check for the crash

**Pull request merged**
