### PR TITLE
fix project re-load missing layers (fixes #16560)

### PR DESCRIPTION
**Pull request by nirvn**
## Description
@nyalldawson , this fixes the project re-load regression introduced in your project close cleanup PR. Does this look good to you?

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Seems like an odd fix! I guess processEvents() strikes again...

**Comment by nirvn** [comment]
@nyalldawson , that was my guess too. I don't exactly know why that'd fix it, but moving closeProject() call to occur at the very beginning of the function did seem harmless (on top of it fixing the issue :) )

**Comment by nyalldawson** [comment]
Sure - if it works, merge it! But i'd love to know what actually gets called during that processEvents

**Comment by nirvn** [comment]
@nyalldawson , is there a way to debug that?

**Comment by nyalldawson** [comment]
You could put a breakpoint on the processEvents and step through what happens after - there'll probably be a lot of noise, but it should work

**Comment by m-kuhn** [comment]
Would it work to avoid the call to processEvent() and completely switch to an async API?

```
    QgisApp::addProject( proj )
    {
      closeProject();
      QTimer::singleShot( lambda call to loadProject( proj ) );
    }

private slots:
    QgisApp::loadProject( proj )
    {
      ... load here ...
      emit projectLoaded();
    }

**Comment by nirvn** [comment]
Applied the PR as is for now. We can revisit a more significant re-structuring if need be.

**Pull request merged**
