### PR TITLE
Do not switch to FormatUnknown when evaluating expression of picture item layout

### LINKED ISSUE #37804: Layout picture can not change SVG image to Raster image
**Describe the bug**

**How to Reproduce**

**QGIS and OS versions**

**Additional context**

QGIS 3.14 
windows and ubuntu 
Layout 

put picture and set Rater image.
after edit expression picture change SVG image.
when expression is active , picture mode can not change 'Raster image'.

image

expression is active

image

### LINKED ISSUE #38031: Print Layout Picture Box reverting to SVG
Whenever I load a print layout in to QGIS my company logo picture box displays a big red X and the control has turned back to SVG image when had been saved as Raster Image:

image

No matter how many times I revert the picture control back to raster image and save the template - every time it is loaded back from the layout manager the picture has reverted back to SVG.

I should mention that I'm using the latest release 3,14.1

### LINKED ISSUE #47981: Variable raster image source in composer not working
### What is the bug or the crash?

Creating an atlas output with an variable raster image per output file does not work.
The Item Properties of the image switches automatically from "Raster image" to "SVG image" when selecting an attribute field from the file as the image path and it cannot be changed back.

### Steps to reproduce the issue

Prerequisites:
A point layer with features for creating an atlas which contains an attribute field with a file path which points to an image related to this feature. (Actually it doesn't matter at this point, if this is a valid path to an image, since QGIS does not check if the images exists at this stage of the workflow)

Steps to reproduce:

1. Create a new print layout
2. Select Atlas > Atlas Settings
3. In the Atlas Settings select your point layer as coverage layer
4. Add a picture element to the layout
5. Select Raster Image for this element
6. For the source of the image choose the Attribute Field with the image path
7. Now the selection automatically switches from Raster image to SVG image and when trying to export the atlas files the error message "Picture source is missing or corrupt" appears and it is impossible to export them

### Versions

Tested with 3.22.1, 3.24.0 and 3.24.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #49165: Layout - expression for raster image keeps setting radiobutton to SVG image
### What is the bug or the crash?

When creating an expression for dynamically loading raster images in a QGIS from a local folder, on clicking OK, the radiobutton jumps to .SVG image and the raster image will not load.

### Steps to reproduce the issue

Insert placeholder for raster image.
Data defined override expression: concat(@project_folder, '\\H_ALIGNMENT\\' ,"plotboxID", '_MBES.png').
 Expression is valid 
Press OK
Radiobutton Raster image has now jumped to SVG image

### Versions

QGIS version
3.24.0-Tisler
QGIS code revision
6b44a42058
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
BezierEditing
version 1.3.2
DeepLearningTools
0.2.0
league_tools
0.1
openlayers_plugin
2.0.0
ParallelLineConstruction
0.2
plugin_reloader
0.9.1
pointsamplingtool
0.5.3
qchainage
3.0.1
slyr_community
4.0.1
SplitPolygonShowingAreas
0.13
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicogodet**
Fixes #49165
Fixes #47981
Fixes #38031
Fixes #37804

During expression evaluation, `mMode` was set to `FormatUnknown` causing gui to switch to SVG mode even if user click on raster radio button (as it evaluates the expression, switch to FormatUnknown, etc etc).

Need backport if it's okay.

ping @3nids

### CODE REVIEW

**Comment by nicogodet** [comment]
By doing this, we never enter in `else if` here
https://github.com/qgis/QGIS/blob/f261cc1f8b6549b1a5c37374a3c5aba45c92334c/src/core/layout/qgslayoutitempicture.cpp#L578-L604

But I don't understand well it's an `else if` and not just an `if`.

**Comment by nicogodet** [comment]
The logic is very weird to me.

I end up with : 
```diff
diff --git a/src/core/layout/qgslayoutitempicture.cpp b/src/core/layout/qgslayoutitempicture.cpp
index 72313dcba8..cb25754d14 100644
--- a/src/core/layout/qgslayoutitempicture.cpp
+++ b/src/core/layout/qgslayoutitempicture.cpp
@@ -497,10 +497,10 @@ void QgsLayoutItemPicture::loadPictureUsingCache( const QString &path )
     case FormatRaster:
     {
       bool fitsInCache = false;
-      bool isMissing = false;
-      mImage = QgsApplication::imageCache()->pathAsImage( path, QSize(), true, 1, fitsInCache, true, mLayout->renderContext().dpi(), -1, &isMissing );
-      if ( mImage.isNull() || isMissing )
-        mMode = FormatUnknown;
+      bool isMissingImage = false;
+      mImage = QgsApplication::imageCache()->pathAsImage( path, QSize(), true, 1, fitsInCache, true, mLayout->renderContext().dpi(), -1, &isMissingImage );
+      if ( mImage.isNull() || isMissingImage )
+        mIsMissingImage = true;
       break;
     }
 
@@ -526,7 +526,7 @@ void QgsLayoutItemPicture::loadPictureUsingCache( const QString &path )
       }
       else
       {
-        mMode = FormatUnknown;
+        mIsMissingImage = true;
       }
       break;
     }
@@ -578,7 +578,8 @@ void QgsLayoutItemPicture::loadPicture( const QVariant &data )
   {
     recalculateSize();
   }
-  else if ( mHasExpressionError || !mEvaluatedPath.isEmpty() )
+
+  if ( mHasExpressionError || mIsMissingImage )
   {
     //trying to load an invalid file or bad expression, show cross picture
     mIsMissingImage = true;
```

It seems that `mImage = QgsApplication::imageCache()->pathAsImage( path, QSize(), true, 1, fitsInCache, true, mLayout->renderContext().dpi(), -1, &isMissingImage );
` does not set `isMissingImage` to `true` in case of a non-existent/broken path

Currently, data defined picture path is always handled by "old API/project compatibility only" functions. By removing `mMode = FormatUnknown` from `refreshPicture` function, it will use `loadPictureUsingCache`. This function never change `mIsMissingImage`, it just change `mMode` to `FormatUnknown` in case of invalid image  and it has to enter in condition `mHasExpressionError || !mEvaluatedPath.isEmpty()` (it enters because mEvaluatedPath is not empty, weird test BTW) to set `mIsMissingImage` to True.

I will probably give up as I don't understand the logic behind this.

**Comment by nicogodet** [comment]
The latest test "isValid" works fine when I reproduce it in python console but fails here...

**Comment by nicogodet** [comment]
Side note: this might break some scripts/plugins

**Comment by nyalldawson** [comment]
@nicogodet 
> Side note: this might break some scripts/plugins

Unfortunately that's a no-go. We can't break api until QGIS 4.0, so the solution needs to work without impacting existing 3rd party code (that's incidentally why all this logic is such a mess!)

**Comment by nicogodet** [comment]
@nyalldawson I was afraid that all of this might end with this answer.

Scripts/plugins will be impacted like tests are impacted here. Not a big deal but still some lines change.

Since SVG selector has been introduced here, it is a real PIA in daily basis to work with layout picture item. Create a new item for SVG would have been a better idea.

@3nids Any idea how not to break existing behavior and still solves linked issues ?

I will do a separated PR for the correct SVG reset when path is empty. Currently, once `mSVG` loads an SVG, it's never deleted and SVG is still rendered even when path is cleared.

**Comment by roya0045** [comment]
Would it be doable to have a mode checker in a class (eval the static string or expression) then have it switch the mode and then render? I guess this would be a bigger refactoring though. I only checked the source file in diagonal though, so I may have missed something but  it just seemed like things were too interwoven.

**Comment by nicogodet** [comment]
It seems complex without API break.

But it would great to fix this annoying issue. One day 😊

**Pull request closed without merging**
