### PR TITLE
When only one feature is selected during a selection operation, show display expression in status bar

### PR DESCRIPTION
**Pull request by nyalldawson**
When only one feature is selected during a selection operation,
show the feature's display expression/field value in the
status bar as part of the "... features selected" message

Peek 2021-03-15 16-24

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , while you're at it, do you want to fix a UI/UX regression with regards to selected feature(s)? Following your super nice addition of pan distance info in the status bar, once a user pans, he/she loses the selected feature(s) info in the status bar, which is at times a bit frustrating.

**Comment by nyalldawson** [comment]
@nirvn 
>  Following your super nice addition of pan distance info in the status bar, once a user pans, he/she loses the selected feature(s) info in the status bar, which is at times a bit frustrating.

Not sure how to fix that one...

**Comment by nyalldawson** [comment]
There's many other transient status bar messages which clear the select status message though. You'd need a generic way to handle all of them...

**Comment by uclaros** [comment]
See related  #41562 for some proposed solutions, though I think the simplest would be to at least re display selected features on the status bar when active layer changed.

**Pull request merged**
