### PR TITLE
[FEATURE] Allow exploration of QGS project file contents directly within the browser

### PR DESCRIPTION
**Pull request by nyalldawson**
Allows QGIS project file items inside the browser to be expanded,
showing the full layer tree (including groups) contained within
that project. Layers are shown as normal layer items, allowing
them to be easily added to the current project via drag and drop
or double click. Additionally, because they are treated just
the same as any other layer items in the browser, they can be
drag and dropped within the browser to e.g. directly copy the
layer to a geopackage file!

TODO: apply layer symbology from project file when adding a
layer from a different project to the current project

### CODE REVIEW

**Comment by m-kuhn** [comment]
Nice one!

**Comment by nyalldawson** [comment]
@m-kuhn is that an approval to merge?

**Comment by m-kuhn** [comment]
With my limited knowledge of the QgsDataItem API, it looks good to me. Merge and let's see, there's plenty of time to test!

**Comment by wonder-sk** [comment]
Great stuff @nyalldawson - this has been on my wish list for a long time!

Sorry only found time to look at it now... Is there a reason why the new project item implementation is in src/app? It would be great to have it in the default implementation so we have consistent behavior of browser models if they are used elsewhere...

When I initially thought about this feature (and during QgsProject refactoring) I wanted to have an option for "lazy" reading of project files, so that map layers are not created immediately and thus reading of projects is nearly instantaneous which could make this use case faster to use. Another cool feature would be to use browser to add embedded groups/layers to the current project...

**Comment by nyalldawson** [comment]
> Sorry only found time to look at it now... Is there a reason why the new project item implementation is in src/app? It would be great to have it in the default implementation so we have consistent behavior of browser models if they are used elsewhere...

The only reason is my fear of stable API contracts ;). I'm happy for these to be moved to gui if there's a demonstrated need to do so. A couple of things to keep in mind:
- it's best practice not to create a new separate browser model, and instead reuse the shared model which is available from iface.browserModel(). If you do this you'll get all the inbuilt app providers anyway.
- there's still a fair amount of logic sitting within QgsBrowserDockWidget. I think some of this should be moved up to QgsBrowserTreeView itself, because at the moment you either get a complete dock (along with the full gui action handling) or you get just a basic tree view with none of the additions. So there's still work for us to do here.

> When I initially thought about this feature (and during QgsProject refactoring) I wanted to have an option for "lazy" reading of project files, so that map layers are not created immediately and thus reading of projects is nearly instantaneous which could make this use case faster to use. Another cool feature would be to use browser to add embedded groups/layers to the current project...

Funnily enough, I had the same thought this morning. I was thinking about how we could show project level metadata in the browser without the expense of completely loading a project (while avoiding a "direct read of the xml" hack... ewwww.... )

We could add flags to QgsProject::read, including one for "Don't load layers". 
@elpaso what do you think? I'd imagine this would be trivial for us to do after your recent bad layer handling rework is finalised?

**Comment by wonder-sk** [comment]
> The only reason is my fear of stable API contracts ;). I'm happy for these to be moved to gui if there's a demonstrated need to do so. A couple of things to keep in mind: [...]

Good point about sharing one model and a lot of extra logic in browser dock. I guess I was mainly worried about having two classes for project item doing different things which may be a bit confusing. Regarding API I would say the new data item class for projects could stay private. Anyway it's not a big deal and it can stay as it is...

> We could add flags to QgsProject::read, including one for "Don't load layers".

Yeah or something like "load on demand" - so when someone drags a map layer, we could request it from that project and get it loaded also layer properties?

**Comment by nyalldawson** [comment]
> Yeah or something like "load on demand" - so when someone drags a map layer, we could request it from that project and get it loaded also layer properties?

Actually what happens at the moment is that layer items (including those created as browser item children) only have a uri for a layer, so these aren't loaded until the drag and drop happens (or layer properties is open). But at the moment we do load the layer with the project just to create the layer item using the layer's source/provider key... so very inefficient! (at least this happens in a background thread, so no ui blocking)

**Comment by nyalldawson** [comment]
>  I guess I was mainly worried about having two classes for project item doing different things which may be a bit confusing

I'd say in 4.0 we remove the non-provider based handling (from all over browser), and it entirely up up to browser providers to populate the model...

**Comment by elpaso** [comment]
About lazy loading of layers this would be very welcome, but,  part of my recent work on bad layers was based on the assumption that layer validity cannot be taken as granted during the application session lifecycle and if we want to know if a layer is valid, we need to call the provider and load the layer, unless we make a new provider API call that can check validity without a full data load (I don't see how ogr/gdal will be able to do it though).

The fact is that we call `isValid` very early on project/layer load, and this would force the provider to load data.

In any event the separation from the `QgsMapLayer` and the `QgsDataProvider` is the foundation of a correct design and we should try to maintain and enforce it, by never assuming that:
- a layer is valid
- a provider instance exists


As a side note: the other big issues I've faced are:
- how to store layer properties information (styles etc.) for a bad layer (I've solved that by storing the XML in the layer itself, this can be eventually used to "reset" the style if we want to add that functionality)
- cross-layer dependencies (relations etc.), do not belong to the layers but to the project, they also need to be stored if they need to be restored when (if) the layer becomes valid (this was also solved for relations)
- the need of a project read write context when reading data from the stored XML: this makes impossible to implement style restore directly in `setDataSource`: we cannot access the project from within the `QgsMapLayer` instance (I'll check if storing a `QgsDomDocument` instead of the XML can solve this problem

**Comment by nyalldawson** [comment]
> About lazy loading of layers this would be very welcome, but, part of my recent work on bad layers was based on the assumption that layer validity cannot be taken as granted during the application session lifecycle and if we want to know if a layer is valid, we need to call the provider and load the layer, unless we make a new provider API call that can check validity without a full data load (I don't see how ogr/gdal will be able to do it though).

But in this case we just want a project with EVERY layer as invalid. All we care about is the layer's original source/provider key/original geometry type. Does that change things?

**Comment by elpaso** [comment]
Yes, I think that it does not have any impact on the bad layer handling, but generally speaking I think we should think about how to handle layer lazy loading and layer validity check in a better way, maybe we should discuss that in a QEP.

**Pull request merged**
