### PR TITLE
Fix tesselator z range calculation, bbox updates for simple 3d vector renderer

### PR DESCRIPTION
**Pull request by nyalldawson**
Together these two fixes partially address https://github.com/qgis/QGIS/issues/48295

### CODE REVIEW

**Comment by nyalldawson** [comment]
@wonder-sk mind taking a look?

**Review by wonder-sk — APPROVED** [review]
Ahh nice, good catch of those bugs!

I am only struggling a bit to follow the logic in QgsTessellator for max Z value calculation - why can't we have just zMax and instead we have both zMaxBase and zMaxExtruded? They both get assigned to mZMax anyway... I must be missing something :-)

**Comment by nyalldawson** [comment]
@wonder-sk 

The difference is in the second branch -- there one gets assigned the maximum base height, whereas the other is maximum height at top of extrusion. I agree it's a bit complex, but it's required to properly handle the way extrusion heights are added for the wall only branches

**Comment by nyalldawson** [comment]
@wonder-sk 

Here's the last part of the fix -- this is the part I'm not so sure about: https://github.com/qgis/QGIS/commit/62bdf59d5e069ec9c3bedc0a8b410ace4c4b20ba

**Comment by wonder-sk** [comment]
> Here's the last part of the fix -- this is the part I'm not so sure about: https://github.com/qgis/QGIS/commit/62bdf59d5e069ec9c3bedc0a8b410ace4c4b20ba

The logic looks correct to me. I wonder what other effects could such "tall" bounding boxes bring, hopefully no negative ones.

Without this commit, are you still getting some rendering issues in your test case, or is this mainly to make things more future-proof?

If you end up adding the commit here, then you'll need to adjust the bbox estimation logic in QgsRuleBased3DRenderer too...

**Comment by wonder-sk** [comment]
> The difference is in the second branch -- there one gets assigned the maximum base height, whereas the other is maximum height at top of extrusion. I agree it's a bit complex, but it's required to properly handle the way extrusion heights are added for the wall only branches

Right, I see... thanks for fixing it!

**Comment by nyalldawson** [comment]
> Without this commit, are you still getting some rendering issues in your test case, or is this mainly to make things more future-proof?

Without it there's an issue where the features don't initially appear, and you have to navigate around until the bounding boxes at 0 height are in the viewport. Then they appear and trigger the exact bbox calculation, which means they remain visible. So the issue is partially solved without this fix, but you still have to play around randomly to get them to appear in the first place.

> The logic looks correct to me. I wonder what other effects could such "tall" bounding boxes bring, hopefully no negative ones.

Me too! I'll probably lower those initial "worst case" z values a significant amount before finalizing that, just in case. (And add an explanation comment!). Maybe something like +/- 100000000.

**Comment by wonder-sk** [comment]
> Without it there's an issue where the features don't initially appear, and you have to navigate around until the bounding boxes at 0 height are in the viewport. Then they appear and trigger the exact bbox calculation, which means they remain visible. So the issue is partially solved without this fix, but you still have to play around randomly to get them to appear in the first place.

Ah right, good point.

> Me too! I'll probably lower those initial "worst case" z values a significant amount before finalizing that, just in case. (And add an explanation comment!). Maybe something like +/- 100000000.

How about something even smaller, like +/- 5'000'000 ? (I am assuming meters as the unit, so that's nearly as much as Earth's radius - if someone is using elevations greater/lower than that, it's definitely not suited for our flat earth 3d scene anyway :grin:  )

**Comment by nyalldawson** [comment]
> like +/- 5'000'000 

Sounds logical to me! 👍

**Comment by nyalldawson** [comment]
@wonder-sk here's the PR : https://github.com/qgis/QGIS/pull/48332

**Pull request merged**
