### PR TITLE
3D viewer zoom in behaviour implementation

### PR DESCRIPTION
**Pull request by NEDJIMAbelgacem**
## Description
Previously the scroll wheel zoom in behavior was to move the camera closer to the center of the scene.
This PR makes the scroll wheel zoom in on the mouse position not the center of the screen:
The previous behavior is still available by clicking the right mouse button and moving the cursor down/up to zoom in/out.

https://user-images.githubusercontent.com/29183781/128471079-0ba2018d-1d95-45cc-9acc-90d31f94d6a6.mp4

### CODE REVIEW

**Comment by uclaros** [comment]
Nice upgrade!
When *On-Screen Navigation* is visible, the zooming position is a bit off. The closest the cursor is to the right side of the viewport, the more apparent it gets.

**Comment by nyalldawson** [comment]
@NEDJIMAbelgacem @uclaros what's the status here? 

@wonder-sk any chance of a review of this one?

**Comment by wonder-sk** [comment]
There should be a revised implementation coming very soon - one which calculates exact 3D intersection of the mouse cursor with the scene (right now the code only uses a rough estimate of the 3D intersection which causes various issues with zoom/rotation).

**Comment by uclaros** [comment]
@nyalldawson Sorry, I haven't tested the latest commit to see if the noticed bug is fixed.

**Comment by wonder-sk** [comment]
@NEDJIMAbelgacem tested the latest commit:
- zoom in/out seems to work correctly
- the issue @uclaros mentioned about zooming being offset with navigation panel enabled is still there
- rotation drifts quite significantly and in the current iteration it is not very usable unfortunately

**Comment by wonder-sk** [comment]
> Does it also address #25551 ?

Not really, it was not planned to address it in this PR...

**Pull request closed without merging**
