### PR TITLE
Processing armaggeddon, pt 1

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR continues the ongoing work for porting parts of processing to c++. This part:

- moves the basis of parameters/outputs to c++
- provides a cleaner split between parameters/outputs
- move more algorithm code to c++
- adds enough code to begin creation of pure c++ algorithms
- adds a background QgsProcessingAlgRunnerTask task  (but not used anywhere yet)
- temporarily removes all existing algorithms (boooooo!)
- adds a native c++ buffer and centroid algorithm

### CODE REVIEW

**Comment by m-kuhn** [comment]
Yaaayyyy! Too cool!

**Comment by alexbruy** [comment]
Wow! Impressive work!

> adds a native c++ buffer and centroid algorithm

Does this mean that `OverlayAnalyzer` and `GeometryAnalyzer` can be removed in future, when geoprocessing algs will be reimplemented in Processing?

**Comment by m-kuhn** [comment]
> adds a native c++ buffer and centroid algorithm

Does this mean we should have one processing algorithm for each (geometry) expression function? With consistent naming for ease of use? And the boilerplate code in some template class? Since they would all be perfect candidates for pipelined processing algorithms and with a template base-class approach there would be one single place to introduce required code?

**Comment by nyalldawson** [comment]
> Does this mean that OverlayAnalyzer and GeometryAnalyzer can be removed in future, when geoprocessing algs will be reimplemented in Processing?

I think so. Those classes aren't used anywhere in master, aren't well tested, and have lots of shortcomings.

**Comment by nyalldawson** [comment]
> Does this mean we should have one processing algorithm for each (geometry) expression function?

There more or less is already, but most of these use python code. It remains to be seen how much benefit we'll get from porting them to pure c++ (beyond having them accessible in python less environments). So we'd need to benchtest and if there's good speed wins then yes, we'd port all the popular ones over to c++.

>  With consistent naming for ease of use? And the boilerplate code in some (template?) base-class? Since they would all be perfect candidates for pipelined processing algorithms and with a base-class approach there would be one single place to introduce required code?

That's still on my (distant) to do list. I think all algorithms which operate "feature-by-feature" should be have special handling to allow feature pipelines. My initial plan is to get standard algorithms working nicely with the new API first, and then we can add these other goodies later.

**Comment by nyalldawson** [comment]
Some more points to clarify this PR:

- This does bring breakage. Apart from the missing algs, it also breaks modeler, scripts and batch processing. The main focus here is on the new c++ code and API - when that is locked in I'll fix the breakages in the Python code. I originally tried to do this work without any of this temporary breakage, but found I was making compromises in the c++ API to workaround the existing Python code, and I didn't like this. I'd rather short term breakage with a strong future proof c++ API for 3.x.

- The disabled algs (and their accompanying tests) will be brought back online one-by-one after the refactoring is complete. Each will need to be ported in turn to the new API. This is mostly going to affect the non-QGIS algs - I suspect the QGIS ones should mostly be portable in bulk with some clever regex replacing.

- For reviewers: there's a lot of changes here. I'd suggest ignoring ALL the python changes, and focusing on the c++ headers alone. Having a look at the qgsnativealgorithms.cpp will also give a good example of how algorithms will be structured.

- The biggest change introduced here (apart from the language) is the shift from algorithms and parameters being mutable. Algorithms (and parameters) are now stateless. An algorithm's processAlgorithm method is passed a QVariantMap (python dict) of parameter values and the current execution context, and it must perform all its operations without modifying the state of the algorithm (processAlgorithm is const). An algorithm's inputs are now effectively "parameter definitions" - specifying the expected value types, ranges, etc for each of the parameters in this QVariantMap.

- Another big change is how outputs are handled. In 2.x processing outputs were used both as a method of specifying inputs to algorithms (file paths to destination layers created by the algorithm) AND pure outputs (such as statistics calculated by the algorithm). This is now split. The old input-type-outputs (destination layers) are now input parameters (since the parameter value IS an input to the algorithm). To differentiate them from parameters indicating pure input layers a new "isDestination()" method was added to QgsProcessingParameterDefinition. Output definitions are now purely indications of values CREATED by the algorithms. Suitable candidates are the existing calculated stats and actual file path/URI of any layers created by the algorithm. Moving forward we should ensure all algorithms output as much useful information as possible - e.g. number of features processed, number of skipped features, count null geometries encountered, etc... In short: parameters include EVERYTHING the algorithm needs to know to be able to run, outputs are extra stuff generated inside the algorithm which can be used in whatever way the algorithm's executor decides.

- What's left to do? Lots. Outputs apart from vector layer outputs aren't ported yet. There's all the algorithms to port. Modeler and scripts and such to resurrect. Accordingly I don't think this should be merged yet, but I would very much value any reviews or comments on the approach taken here before I proceed deeper with this work...

**Review by wonder-sk — APPROVED** [review]
Looked through the C++ part and it all looks good! One bit from our discussion with Nyall is that it may be useful to later add automatic creation of output definitions from destination parameters.

Go go go!

**Comment by alexbruy** [comment]
API looks good for me. +1 to merge when ready

**Comment by nyalldawson** [comment]
I've just added a bunch of new work here. Quick summary of the changes:

- Everything is abstracted away from source/destination layers to QgsFeatureSource/QgsFeatureSinks. This should give us lots of flexibility in future in allowing non-vector layer inputs/outputs for algorithms.
- Using the new QgsVectorLayerSelectedFeatureSource and QgsProcessingFeatureSource QgsFeatureSource subclasses allows us to hide all the yucky details away from algorithms. There's no longer a need for QgsProcessingUtils::getFeatures/featureCount/createSpatialIndex/uniqueValues, since these can all be directly retrieved from the sources without algorithms needing to have special handling for selections/etc.
- Two small new classes have been added to encapsulate all the extra settings processing uses for sources/sinks. E.g. for sources this includes only whether selected features should be used, for sinks it includes whether the result should be loaded into the project & any destination file encoding.
- The global setting for using selected features is gone. It's moved to a per-input setting.

Again, the best way to get a feel for these changes is to checkout both the c++ native algorithms and the 2 ported python algorithms. IMO it's all a lot nicer then the earlier version of this PR.

**Comment by nyalldawson** [comment]
https://github.com/qgis/QGIS/pull/4590/commits/448a55b264fe1d751c4c8fe5aef31b956b5ddb0d gives a good example of using the newer api

**Comment by nirvn** [comment]
> The global setting for using selected features is gone. It's moved to a per-input setting.

YAY!

**Comment by nyalldawson** [comment]
giphy

Merging after addressing changes from discussion with @wonder-sk... next step, the rebuild!

**Comment by pcav** [comment]
Great, thanks. First tests:
* option dissolve for buffer does not work
* Frequency analysis and Number of unique values both result in: This algorithm cannot be run :-( 
This script has a syntax errors. Problem with line: ##Fields=Field Input

**Comment by pcav** [comment]
Also error for centroids:
```
SystemError: returned a result with an error set 
Traceback (most recent call last):
  File "/usr/local/src/qgis/QGIS/build_qgis3/output/python/plugins/processing/tools/dataobjects.py", line 84, in raise_error
    'Features with invalid geometries found. Please fix these geometries or specify the "Ignore invalid input features" flag'))
processing.core.GeoAlgorithmExecutionException.GeoAlgorithmExecutionException: 

 Message:
  | Features with invalid geometries found. Please fix these geometries or specify the "Ignore invalid input features" flag

 Stack:

    None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/src/qgis/QGIS/build_qgis3/output/python/plugins/processing/gui/AlgorithmDialog.py", line 230, in accept
    result = executeAlgorithm(self.alg, parameters, context, self.feedback)
  File "/usr/local/src/qgis/QGIS/build_qgis3/output/python/plugins/processing/core/GeoAlgorithm.py", line 382, in executeAlgorithm
    result = alg.run(parameters, context, feedback)
SystemError:  returned a result with an error set


Versione Python: 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118] 
Versione di QGIS: 2.99.0-Master Master, exported 
```

**Comment by pcav** [comment]
I realize that it is too early for testing, but I note here what I find, in case it might be useful.
Adding an alg to a model throws:
```
AttributeError: 'QgsProcessingAlgorithm' object has no attribute 'getCustomModelerParametersDialog' 
Traceback (most recent call last):
  File "/usr/local/src/qgis/QGIS/build_qgis3/output/python/plugins/processing/modeler/ModelerDialog.py", line 552, in addAlgorithm
    self._addAlgorithm(alg)
  File "/usr/local/src/qgis/QGIS/build_qgis3/output/python/plugins/processing/modeler/ModelerDialog.py", line 555, in _addAlgorithm
    dlg = alg.getCustomModelerParametersDialog(self.alg)
AttributeError: 'QgsProcessingAlgorithm' object has no attribute 'getCustomModelerParametersDialog'
```

**Comment by nyalldawson** [comment]
Thanks for the testing @pcav! it's early days still, but very much appreciated.

> option dissolve for buffer does not work

Ah, thanks. That was something I meant to come back to fix but had forgotten to.

> Frequency analysis and Number of unique values both result in: This algorithm cannot be run :-(
> This script has a syntax errors. Problem with line: ##Fields=Field Input

The script based algorithm support hasn't been updated for the new api yet. It's on my list :)

> Also error for centroids:

I'll look into that. I suspect it's some code I temporarily commented out

> Adding an alg to a model throws:

Modeler is one huge work in progress... still lots to fix there.

What should be working so far is that the ported algorithms should run OK in the standalone mode (ie not run through models). All parameter/input options should function without errors. All input and output destinations for layers should work OK.
Aside from clicking the "batch" button in the dialog, you shouldn't be getting any errors here.

**Pull request merged**
