### PR TITLE
Expose choice of units for geometry generator symbol layers

### PR DESCRIPTION
**Pull request by nyalldawson**
Usually a geometry generator expression must return a geometry in the associated layer's CRS. But this doesn't work in situations where a geometry generator symbol is NOT associated with a layer, e.g. when used in a layout item.

So add a new option to allow users to specify which unit the expression will return geometries in, with choices of map units (the default, previous behavior), millimeters, pixels, inches and points.

~~When millimeters, points, inches or pixels is selected then the @map_geometry variable will be available for the expression,
and contain the feature's geometry in the specified units (relative to the map frame). (The $geometry variable remains available and still in layer CRS, in case an expression needs to calculate the original area, perimeter, etc in real-world units while returning
results in a different unit!)~~

When millimeters, points, inches or pixels is selected then the $geometry variable will be the feature's geometry in the specified units (relative to the map frame).

A step toward fixing #39159, but of interest in its own right !

Here's how it looks:

image

~~I'm interested in feedback regarding the "@map_geometry" variable and better names for this. I'm not happy with @map_geometry, but can't think of an alternative....!~~

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , code looks good, nice one. Also +1 to get rid of @map_geometry and serve a geometry that matches the unit type.

**Comment by nirvn** [comment]
For the sake of meeting expectations and having consistent behavior, should we also offer the combobox for the labelling geometry generator, or less important there?

**Comment by nyalldawson** [comment]
> should we also offer the combobox for the labelling geometry generator, or less important there?

Possibly, but given that it's not possible to use labelling outside of a vector layer I'd say it's a lower priority vs symbology

**Comment by nirvn** [comment]
@nyalldawson , yeah, I was thinking about scenarios such as: a geometry generated arc line (from a millimeter derived buffered area) to place a curved label around a marker.

In any case, not something we need addressing here, and likely no pressure to address full stop :)

**Review by nirvn — APPROVED** [review]

**Comment by LKajan** [comment]
This is great addition! Thanks @nyalldawson!
In the change log you asked suggestions for the name of the @map_geometry. I don't know if any better but how about @canvas_geometry?

**Pull request merged**
