### PR TITLE
[3d] More camera controls

### PR DESCRIPTION
**Pull request by wonder-sk**
New controls for more freedom!
- use page up / page down keys to move camera up/down vertically
- use ctrl + arrow keys to rotate camera, keeping the camera in one position (as opposed to shift + arrow keys when camera rotates around a point it is looking at)
- use ctrl + mouse (with left button pressed) to rotate camera like with ctrl + arrow keys

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@wonder-sk These new modes make navigation much nicer -- thanks!

I noticed a weird thing during testing. If you set the camera near the surface, and then use ctrl+up to point the camera up, it works to a certain stage where the camera is pointed near the horizon, and then the camera rotation changes somehow to a "increase elevation" change. I see the same effect with ctrl+left mouse drag - it works ok until the camera points over the horizontal, and then the altitude starts increasing.

**Comment by wonder-sk** [comment]
Yeah I think that's due to the check for max. tilt angle - I will try to fix it today...

**Comment by wonder-sk** [comment]
Fixed now in e35ec2dccb9b076057bb6ebb1b1d778d0250cec4

**Comment by nyalldawson** [comment]
@wonder-sk 

That does fix the elevation rise, but it also blocks "looking up". Shouldn't this be supported? E.g. to allow looking up at a building from ground level, looking up a mountain from the base, etc.

**Comment by nyalldawson** [comment]
Yeah, I'd go with allowing it by default, but we could add a button which "resets" the view so that it swings back up/down until the angle is within a "normal" range

**Pull request merged**
