### PR TITLE
Avoid startup error when project template folder does not exist

### PR DESCRIPTION
**Pull request by nyalldawson**
Without this patch I get a startup error about being unable to watch a non-existant folder

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nathanw2 ok to merge?

**Comment by nyalldawson** [comment]
gentle ping @NathanW2 ;)

**Comment by NathanW2** [comment]
Gentle hey :) 

Wonder if it's better to just make that folder. Then the user doesn't have to do it.

**Comment by nyalldawson** [comment]
check the changes ;)

**Comment by NathanW2** [comment]
Doh sorry missed the mkdir call. Yep that is good. Merge it.

**Comment by nyalldawson** [comment]
Thanks! Just trying to prune this PR queue a bit...

**Pull request merged**
