### PR TITLE
[server] Sanitize WMS exceptions

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

In this PR, an `ExceptionCode` enum is added, based on the WMS 1.1.0 and WMS 1.3.0 specifications to define standard exception codes. 

This way, exceptions are not raised with a string code (which may differ according to the author...), but thanks to the enum.

I added some unit tests accordingly.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by elpaso — APPROVED** [review]
big +1 !

**Comment by rldhont** [comment]
@dmarteau can you take a look, thanks.

**Review by rldhont — APPROVED** [review]

**Comment by dmarteau** [comment]
Good !

**Comment by pblottiere** [comment]
Thanks for your review @elpaso and @dmarteau!

**Pull request merged**
