### PR TITLE
[needs-docs] Add shortcut for paste to scratch layer (Ctrl+Alt+V)

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nirvn @Delazj do you think it's appropriate to change the current "add vector layer" shortcut to ctrl+alt+v (from ctrl shift v), and use instead ctrl+shift+v as paste to scratch layer?

Imo ctrl + shift+ v is so commonly used as a paste operation modifier across a whole range of apps that we should use it as a paste operation short cut  too. But I'm concerned about the impact of changing default shortcuts on users too.

What do you think?

**Comment by DelazJ** [comment]
Wouldn't that be weird to have all the other `Add xxx layer...`actions being shortcuted with `Ctrl+Shift+...` and not that tool?  
addvector

**Comment by nirvn** [comment]
@nyalldawson , sounds good to me. A creating a new geopackage layer has a shortcut set to ctrl+shift+n , so ctrl+shift+v to create a new memory layer from clipboard content is consistent.

**Comment by nyalldawson** [comment]
@DelazJ 
> Wouldn't that be weird to have all the other Add xxx layer...actions being shortcuted with Ctrl+Shift+... and not that tool?

Fair enough, that's a strong enough point.

**Pull request merged**
