### PR TITLE
use focal to build Docker images

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by nirvn** [comment]
Nice. 

Understanding this was triggered by the EOL of Ubuntu Disco, the one downside of us moving to Focal: we lose testing of QGIS PRs/commits under gdal 2/proj 5. It used to be travis -> gdal2/proj5 and azure -> gdal3/proj6.

We might be OK with it, I'm just verbalizing it so we're aware of that fact.

**Comment by nirvn** [comment]
I just saw the only other alternative is Eoan, which reaches EOL in July 2020. Focal it is then :)

**Comment by 3nids** [comment]
no, the PR are still tested against bionic.
Disco was introduced to have newer version of sip for the documentation.
I failed at upgrading the tests to disco on that time, so I kept the 2 in parallel, which will continue a bit.

**Comment by 3nids** [comment]
merging to test the build on cron jobs.

**Comment by 3nids** [comment]
if there is any issue, this can be reverted later on

**Comment by nirvn** [comment]
@3nids , oh great then. Sorry for the noise.

**Pull request merged**
