### PR TITLE
[SERVER] Server refactoring and Python bindings/tests

### PR DESCRIPTION
**Pull request by elpaso**
Refactoring of the server component, the
server is now wrapped into a new QgsServer class with
python bindings and an examples python test.

Build tested with/without python and with/without python plugins

### CODE REVIEW

**Comment by elpaso** [comment]
The following tests FAILED:

	141 - PyQgsSpatialiteProvider (Failed)
        143 - PyQgsDocCoverage (Failed)

but the new QgsServer test passes

**Comment by m-kuhn** [comment]
You can ignore the spatialite provider test, that's related to https://github.com/qgis/QGIS/pull/2055

Concerning the other one, while it was initially triggered by the abovementioned PR, it would be good to have some API documentation for the server as well, especially in public interfaces like qgsserverinterface.h.

**Comment by nyalldawson** [comment]
@elpaso just to clarify, I assume this is targeted to 2.12?

**Comment by elpaso** [comment]
@nyalldawson yes. Needs some review from @mhugent and @wonder-sk

**Comment by elpaso** [comment]
@m-kuhn I think that the plugin classes are already documented in 2.8: http://qgis.org/api/classQgsServerInterface.html

I also added the new classes (QgsServer) to doxygen template but forgot to add them in the commit, I'll re-add them.

**Comment by m-kuhn** [comment]
@elpaso I don't see much documentation there.

There is one doxygen comment on class level but nothing on method level.

See:
https://github.com/qgis/QGIS/blob/master/src/server/qgsserverinterface.h

**Comment by m-kuhn** [comment]
For comparison e.g. https://github.com/qgis/QGIS/blob/master/src/gui/qgisinterface.h#L121-L128

**Pull request merged**
