### PR TITLE
Use text renderer in layout legends 

### PR DESCRIPTION
**Pull request by nyalldawson**
This change allows use of the full text renderer capabilities for legend titles, subtitles, and item text. It allows buffers,
shadows, font spacing control, and all over options (including mixed HTML formatting!) which is permitted for use in text formats.

Sponsored by NIBIO

### CODE REVIEW

**Comment by nyalldawson** [comment]
This should be ready to go now!

**Comment by roya0045** [comment]
With mixed fonts and more complicated text displays, could it cause some issues when it comes the time to estimate the text size (for symbol set to the right, calculating legend or column dimensions,etc) ? I vaguely recall some edge cases but maybe those were only with the wms legend images.

**Comment by nyalldawson** [comment]
@roya0045 

> With mixed fonts and more complicated text displays, could it cause some issues when it comes the time to estimate the text size (for symbol set to the right, calculating legend or column dimensions,etc) ?

Hopefully not -- the text renderer class accounts for all that internally. And if it reveals issues here then the same issues will be present elsewhere that text renderer is used, so it's honestly a good thing :upside_down_face:

**Review by nirvn — APPROVED** [review]
Code looks good, and couldn't find a regression while stress testing a local build here.

**Comment by nyalldawson** [comment]
Thanks @nirvn!

**Pull request merged**
