### PR TITLE
fix building server without plugins

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by elpaso** [comment]
@3nids I don't get it: the landing page has nothing to do with plugins.

**Comment by elpaso** [comment]
BTW, there are three ways to get rid of the landing page if you don't want it:

1. don't install it (it's a separate package in debian/ubuntu)
2. set the undocumented env var QGIS_SERVER_DISABLED_APIS="Landing Page"
3. remove lib/qgis/server/liblandingpage.so

**Comment by 3nids** [comment]
it's not that I don't want to build it, but I cannot compile server without plugins:

```
Undefined symbols for architecture x86_64:
  "QgsServerFilter::sendResponse()", referenced from:
      vtable for QgsProjectLoaderFilter in qgslandingpage.cpp.o
  "QgsServerFilter::QgsServerFilter(QgsServerInterface*)", referenced from:
      QgsProjectLoaderFilter::QgsProjectLoaderFilter(QgsServerInterface*) in qgslandingpage.cpp.o
  "typeinfo for QgsServerFilter", referenced from:
      typeinfo for QgsProjectLoaderFilter in qgslandingpage.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

in `server/CMakeLists.txt`, qgsserverfilter.cpp is only added if built with plugins:

image

**Comment by elpaso** [comment]
I see, `WITH_SERVER_PLUGINS` was originally meant for server python plugins support, but now landingpage (which is not python) uses the qgsserverfilter interface for url manipulation (to generate a unique URL identifier for projects).

I think we need to build qgsserverfilter in any case and we should probably also rename `WITH_SERVER_PLUGINS` to `WITH_SERVER_PYTHON_PLUGINS` to make it clear that we are enabling/disabling python plugins support for the server (maybe open an issue for QGIS 4 though).

What do you think?

**Comment by 3nids** [comment]
This makes sense.
closing in favor of #40869

**Pull request closed without merging**
