### PR TITLE
[3d] Handle tilting and rotation of camera better

### PR DESCRIPTION
**Pull request by wonder-sk**
This will update camera's view center as the camera moves around.
Before the view center would be always at the zero elevation, which
means that with terrain further away from zero elevation tilting
and rotation of camera would feel weird due to the center point being
far away.

In order to update camera's view center we need to calculate intersection
of terrain with a 3D ray coming from the camera's position towards the center
of the viewport. This is done by going through the active terrain tiles
and checking whether their bounding box intersects the ray - if it does,
then we do an exact test of terrain tile's triangle mesh against the ray
to find the closest intersection point. When we have the intersection,
we update the view center to be at the terrain's surface.

Unfortunately raycasting in Qt3D is only available from 5.11 which has been
released only very recently. I have therefore ported some code from Qt3D
internals and added ray vs axis-aligned box from a different source
(Qt3D uses bounding spheres but they are not available in public API either)

### CODE REVIEW

**Comment by nyalldawson** [comment]
Code/rationale looks good to me!

**Comment by nirvn** [comment]
Exciting to see the next wave of 3D improvements starting :)

**Comment by wonder-sk** [comment]
... now including a fancy red sphere (camera view center) for those not afraid to look under the hood!
(a new option in config dialog)
image

**Comment by daniviga** [comment]
Hi @wonder-sk,

it looks like that after this has been merged it is not possible to compile QGIS with the GCC hardening flags set (which is the default in most distributions when building packages, at least it is on Fedora/RedHat). No problems when running a 'development' build with no hardening set (via classic, manual `ccmake` & `make`).

The error I get is
```
[ 70%] Linking CXX shared library ../../output/lib64/libqgis_3d.so
BUILDSTDERR: CMakeFiles/qgis_3d.dir/terrain/qgsdemterraintilegeometry_p.cpp.o: In function `intersectionDemTriangles':
BUILDSTDERR: /builddir/build/BUILD/qgis-3.3.0/src/3d/terrain/qgsdemterraintilegeometry_p.cpp:275: undefined reference to `operator*(QMatrix4x4 const&, QVector3D const&)'
BUILDSTDERR: /builddir/build/BUILD/qgis-3.3.0/src/3d/terrain/qgsdemterraintilegeometry_p.cpp:276: undefined reference to `operator*(QMatrix4x4 const&, QVector3D const&)'
BUILDSTDERR: /builddir/build/BUILD/qgis-3.3.0/src/3d/terrain/qgsdemterraintilegeometry_p.cpp:277: undefined reference to `operator*(QMatrix4x4 const&, QVector3D const&)'
BUILDSTDERR: collect2: error: ld returned 1 exit status
BUILDSTDERR: make[2]: *** [src/3d/CMakeFiles/qgis_3d.dir/build.make:846: output/lib64/libqgis_3d.so.3.3.0] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/qgis-3.3.0'
BUILDSTDERR: make[1]: *** [CMakeFiles/Makefile2:3253: src/3d/CMakeFiles/qgis_3d.dir/all] Error 2
make[1]: Leaving directory '/builddir/build/BUILD/qgis-3.3.0'
BUILDSTDERR: make: *** [Makefile:155: all] Error 2
```

It's always reproducible when hardening is enabled and it happens with both make -j20 and make -j1. I was able to reproduce it locally and on a remote builder, see https://copr-be.cloud.fedoraproject.org/results/dani/qgis-testing/fedora-28-x86_64/00772119-qgis/build.log.gz

I'm running Qt 5.10, cmake 3.11 and gcc 8.1.1 and the default hardening flags in Fedora/RedHat are:

```
export CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
export CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
export LDFLAGS='-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
```

Unfortunately the tests running here on Travis do not take into account hardening, but this is the default on many distribution (Fedora, Suse, and I guess Ubuntu/Debian too nowadays) and are usually required by the packaging policies.

Do you have any hint on how to workaround this issue?

**Comment by daniviga** [comment]
Hi @wonder-sk,
thanks for your great support and quick reply.

> Could you try to add #include <QMatrix4x4> to the top of qgsdemterraintilegeometry_p.cpp file and see if that helps?

It actually fixed the issue! I was able to complete the build applying that patch.

**Comment by wonder-sk** [comment]
Great to hear! Applied on master in e073a4cbb836886dadbfff4f6f319a752072a759

**Pull request merged**
