### PR TITLE
Adding &TRANSPARENT=true makes too big legend images look good

### PR DESCRIPTION
**Pull request by rduivenvoorde**
See http://hub.qgis.org/issues/15089 for screenshots & test service url

### CODE REVIEW

**Comment by luipir** [comment]
give a look to: 

https://github.com/rduivenvoorde/QGIS/blob/f7c1506973dbeee62f96ca65cb06201607877ea2/src/providers/wms/qgswmsprovider.cpp#L569

and test against jpeg with different map servers

**Comment by rduivenvoorde** [comment]
Though I'm ok with the test, in the specs of 1.3 they explicitly state: 

"If the picture format does not support transparency, then the server shall respond with a non-transparent image (in other words, it is not an error for the client to always request transparent maps regardless of format). When TRANSPARENT is set to FALSE, non-data pixels shall be set to the value of BGCOLOR (7.3.3.10)."

Page 38 of 1.3.0 OGC Specs

Are you aware of any service with jpeg legends?

**Comment by luipir** [comment]
perfect, go ahead :)

btw I'm not aware of legends served with jpeg format

**Comment by m-kuhn** [comment]
@elpaso , mr server ;)

**Comment by qgis-feature-tracker** [comment]
It's not about QGIS-server though, it is the QGIS WMS client-provider who is requesting legend images to use in QGIS layermanager

**Comment by m-kuhn** [comment]
@qgis-feature-tracker I don't know who maintains this but if it's safe to merge, I can do it when I come back tonight.

**Comment by rduivenvoorde** [comment]
sorry: qgis-feature-tracker was me :-)  Did not log out after some maintenance thingies.

I can even pull myself

**Comment by m-kuhn** [comment]
> sorry: qgis-feature-tracker was me :-) 

ah, really? :)

> I can even pull myself

Code looks good. If it works for you and if you don't expect side-effects, go ahead.

**Comment by luipir** [comment]
ok to merge (merged)... just an extra git info, we (richard and me) contacted the original financer of the legend graphic integration (Regione toscana) and for them there is no possible side effects (the option is not a standard option for GetLegendGraphic call) so it is generally ignored is server does not support it.

**Pull request merged**
