### PR TITLE
[qt5 tests] Workaround unpredictable composertable tests

### PR DESCRIPTION
**Pull request by m-kuhn**
QgsComposerAttributeTable::setDisplayAttributes takes a QSet<int> of attributes
to display. The tests previously expected that the attributes are displayed in a
specific order which cannot be guaranteed by a QSet. And apparantly Qt5 behaves
differently.

For flexibility it would be good to add another method which takes a
QVector<int> (or a QStringList to be less fragile to changes in the database
structure).

### CODE REVIEW

**Comment by m-kuhn** [comment]
The composertable test is "fixed" with the workaround.
The composertablev2 test is a bit more complex.

@nyalldawson what do you think, should we just disable the unreliable checks in there, make them less strict concerning the order of attributes or should new methods which take an ordered QList/QVector as attribute be added?

**Comment by nyalldawson** [comment]
> what do you think, should we just disable the unreliable checks in there, make them less strict concerning the order of attributes or should new methods which take an ordered QList/QVector as attribute be added?

I'll add the QStringList method  to QgsComposerAttributeTableV2, and update the tests. QgsComposerAttributeTable is deprecated and will be removed in QGIS 3.0, so I'd say we should just leave that test on the blacklist (or surround it by a `#if ndef (QGIS_DISABLE_DEPRECATED)` block

**Comment by nyalldawson** [comment]
Fixed in eb3a34cc9222348080cc305cb28bb0e3bd1c144d

**Comment by m-kuhn** [comment]
Great

> QgsComposerAttributeTable is deprecated and will be removed in QGIS 3.0,

That one no longer fails already with this PR, so this should be addressed already.

**Pull request closed without merging**
