### PR TITLE
Add icon for curved callout label

### LINKED ISSUE #42323: New icon required for curved line callout style
See https://github.com/qgis/QGIS/pull/42302

### PR DESCRIPTION
**Pull request by DelazJ**
Fixes #42323
image

### CODE REVIEW

**Comment by timlinux** [comment]
@DelazJ  Can you include screenshots in the PR description for stuff like this?

**Comment by DelazJ** [comment]
not stale and ready for review

**Comment by nirvn** [comment]
@DelazJ , looking at it now, better late than never? :wink:

**Comment by nirvn** [comment]
@DelazJ , thanks for the effort here, I've pushed the SVG through the finish line in #44234 .

**Comment by DelazJ** [comment]
Thanks @nirvn. May I also get your attention for #43952 and #43356 (have a pending doc PR for this one)? Thanks.

**Pull request closed without merging**
