### PR TITLE
Add qgis_core.h to with CORE_EXPORT macro

### PR DESCRIPTION
**Pull request by m-kuhn**
This removes complexity from the compiler flags because the default (empty) CORE_EXPORT macro happen in a standard input file. All the other magic is done by cmake.

### CODE REVIEW

**Comment by m-kuhn** [comment]
@dakcarto this fixes the QtCreator parser issues for the core classes.
If this looks like a good plan, we can add the same for the other libraries (will take a couple of hours to do...)

**Comment by m-kuhn** [comment]
@dakcarto I think this is ready (travis failure is unrelated)
Works like a charm for me.

**Comment by nyalldawson** [comment]
@m-kuhn I think you should merge this asap for wider testing

**Comment by m-kuhn** [comment]
Thanks for the feedback, let's see how it performs.

**Comment by dakcarto** [comment]
@m-kuhn Seems I missed the request for review. This is a much better approach. Thanks for taking the effort to fix. Testing now.

**Review by dakcarto — COMMENTED** [review]
@m-kuhn Works great on macOS! Thanks

**Comment by nyalldawson** [comment]
One of the best things about this... I no longer have to see those squiggly yellow lines in QtCreator!

**Pull request merged**
