### PR TITLE
Layouts, chapter III

### PR DESCRIPTION
**Pull request by nyalldawson**
Chapter III of the riveting ongoing saga....

Highlights this round:

- page collections! Layouts now support collections of mixed page sizes and orientations. Pages can be defined with sizes in different units.
- a brand new "add pages" dialog, for specifying properties of pages to insert into an existing layout
- right click menu for layouts, with options to edit page properties and remove pages when right clicking on a page

### CODE REVIEW

**Comment by nyalldawson** [comment]
Interesting changes from an architectural POV:

- QgsLayouts have a QgsLayoutPageCollection. QgsLayoutPageCollection is responsible for managing the existing QgsLayoutItemPages in the layout, and adding/inserting/deleting pages
- There's a new interface QgsLayoutViewMenuProvider - used for creation of right click menus in QgsLayoutViews. Right click menus are only shown if the current layout tool chooses to ignore a right mouse click.
- QgsLayoutAppMenuProvider implements a QgsLayoutViewMenuProvider for the designer dialog.

**Comment by nirvn** [comment]
@nyalldawson , fantastic progress. Few thoughts after trying this PR:

- Maybe a couple of wallpaper size presets should be added to the page size combobox
- Could we avoid disabling the width & height (and the unit type combobox) and instead switch to "custom" if the user enters a custom value there? 

Unrelated to page management per say, the layout window's status bar is such a nice improvement, well done.

**Comment by nyalldawson** [comment]
@nirvn 
> Maybe a couple of wallpaper size presets should be added to the page size combobox

Which would you suggest?

**Comment by nirvn** [comment]
Maybe a couple of the reportedly most-used ones here: http://gs.statcounter.com/screen-resolution-stats

Those should be in, IMHO:1920x1080, 1280x800, and 1024x768.

**Comment by nyalldawson** [comment]
@nirvn comments addressed

**Comment by nirvn** [comment]
@nyalldawson , thanks.

BTW, now that I've absorbed enough caffeine, I can be more appropriately excited about the main point of this PR: OMG, finally, multi-size / multi-orientation page layouts!!!

**Comment by nyalldawson** [comment]
Hey - I'm more excited about the presence of a right click menu :p

**Comment by nyalldawson** [comment]
Travis failure is unrelated

**Pull request merged**
