### PR TITLE
[processing] fix open script dialogs (fix #16347)

### PR DESCRIPTION
**Pull request by ghtmtt**
## Description
Small PR that fixes issue #16347. Ideas taken from b0dc9f8517fe22462341ec4e01eaeec9c7c3234e, thanks @nyalldawson :)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by alexbruy** [comment]
Wiping `~/.qgis3` fixes this issue without editing code. I think this is related to recent `QgsSettings` switch, so IMHO there is no sense in this fix.

**Comment by ghtmtt** [comment]
ah ok,  I saw the recent commit b0dc9f8 that fixed almost the same thing for the modeler and I thought it could be useful to fix also for scripts.
Feel free to dump the PR if you think it is useless

**Comment by alexbruy** [comment]
Sorry, not `~/.qgis3`, but QGIS settings.

**Comment by ghtmtt** [comment]
Ok, you are talking about this https://github.com/qgis/QGIS-Enhancement-Proposals/issues/82 right?
Anyway, no problem, if the PR is useless dump it without problems ;)

**Comment by ghtmtt** [comment]
@alexbruy can we close or merge this PR?

**Comment by ghtmtt** [comment]
@alexbruy sorry for writing again. But I freshly recompiled QGIS, opened with the ``--configpath`` options but I still get the same error fixed with this PR. 
I just don't understand what should I remove for fixing this without code writing. Thanks in advance!

**Pull request closed without merging**
