### PR TITLE
[FEATURE] Layer tree embedded widgets

### PR DESCRIPTION
**Pull request by wonder-sk**
This allows definition of widgets embedded into layer tree for individual layers in the layer properties dialog (in new Legend tab). The idea is to have a way to quickly access to some actions that are often used with a layer.

The implementation comes with transparency widget, in the future there may be more standard widgets coming, e.g. to setup filtering, selection, style or other stuff. The API allows plugins to register their own widgets, which will be useful for various domain specific plugins to assign custom widgets to layers they manage.

Here's an implementation of a simple combo box to switch current style of a layer:

qgis-embedded-widget

``` python

from PyQt4.QtGui import QComboBox

from qgis.core import QgsMapLayer
from qgis.gui import QgsLayerTreeEmbeddedWidgetProvider, QgsLayerTreeEmbeddedWidgetRegistry

class LayerStyleComboBox(QComboBox):

    def __init__(self, layer):
        QComboBox.__init__(self)
        self.layer = layer

        for style_name in layer.styleManager().styles():
            self.addItem(style_name)

        idx = self.findText(layer.styleManager().currentStyle())
        if idx != -1:
          self.setCurrentIndex(idx)

        self.currentIndexChanged.connect(self.on_current_changed)

    def on_current_changed(self, index):
        self.layer.styleManager().setCurrentStyle(self.itemText(index))


class LayerStyleWidgetProvider(QgsLayerTreeEmbeddedWidgetProvider):

    def __init__(self):
        QgsLayerTreeEmbeddedWidgetProvider.__init__(self)

    def id(self):
        return "style"

    def name(self):
        return "Layer style chooser"

    def createWidget(self, layer, widgetIndex):
        return LayerStyleComboBox(layer)

    def supportsLayer(self, layer):
        return True   # any layer is fine


provider = LayerStyleWidgetProvider()

QgsLayerTreeEmbeddedWidgetRegistry.instance().addProvider(provider)
```

If there are no objections, I would like to merge it for 2.16

### CODE REVIEW

**Comment by NathanW2** [comment]
Nice!

**Comment by nyalldawson** [comment]
Code and testing looks good. +1 to merge

Only one very minor thing : the transparency slider is much slower than the same one in the styling dock. @nathanw2 i think that uses a timeout to prevent trying to refresh the map too often, right? A similar approach should be used here. But it's not a blocker, since that widget isn't enabled by default anyway.

**Comment by NathanW2** [comment]
Yeah I use a 100ms delay on any updates for that reason.

**Comment by mhugo** [comment]
Very cool feature, thanks !

**Comment by wonder-sk** [comment]
Thanks for the review and hints guys - added the delayed update and the GUI indeed feels much snappier!

**Pull request merged**
