### PR TITLE
Make Regular Shape Digitizing Toolbar disabled by default / renamed Shape Digitizing Toolbar

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description
Requested by @SrNetoChan 

- Rename Regular Shape Digitize Toolbar to Shape Digitize Toolbar
- Homogenize this toolbar like the others
- Disabled by default

@DelazJ is the name good for you?

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [X] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [X] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by DelazJ** [comment]
Thanks for the fix @lbartoletti 
> @DelazJ is the name good for you?

I'd say no, sorry. With this name, we'd have imho too many "advanced [... ] Digitizing" tools.
Is digitizing something complex, uncommon in GIS so that we end up with 3 groups of advanced tools? And to be honest, the regular shape tools are not advanced tools imho; most of the users won't use it on a daily basis, reason why it's hidden by default, but using it requires nothing advanced; it's really intuitive.
If 'advanced' means that it helps to do a not recurrent task then:
1. maybe we should rename the advanced digitizing toolbar as nobody can do proper digitizing without the "merge features", and some other tools there
1. or we should rename the Labels toolbar as advanced (i can recall how many times i have used it). 

This toolbar helps do some (almost) single and particular type of task simply; let's not call it advanced and instead use it particularity. 
Sorry for this looong plaidoyer...

**Comment by lbartoletti** [comment]
"Regular .." is not usable, so why not remove "Advanced" and just name it "Shape Digitize Toolbar"?

**Comment by DelazJ** [comment]
LGTM. Thanks

**Comment by lbartoletti** [comment]
Mmm... I think that travis errors are not related to the PR

**Pull request merged**
