### PR TITLE
Add some German hardcoded localized variants of the strings

### PR DESCRIPTION
**Pull request by pathmapper**
~~and add "id" back to candidates of `QgsVectorLayerUtils::guessFriendlyIdentifierField` (seems like it was accidentally lost in https://github.com/qgis/QGIS/pull/41372).~~

### CODE REVIEW

**Comment by nyalldawson** [comment]
"id" definitely should not be included -- the intention is to pick a descriptive field, but most of the datasets I come across have some non-descriptive "id" field as the first field in the layer.

**Review by nyalldawson — APPROVED** [review]

**Comment by pathmapper** [comment]
Thanks @nyalldawson, regarding the failing spell check:

Is there a need for some action, e.g. add the file to https://github.com/qgis/QGIS/blob/970480fd3ce5aa178d24a579a469adae7024f6ec/scripts/spell_check/check_spelling.sh#L29

or just remove `titel` from the list of candidates?

**Comment by pathmapper** [comment]
OK, opted for removing `titel` from German candidates to make spell check happy. IMHO other candidates are more suitable anyway, so it's not worth making an exception for this one.

**Comment by DelazJ** [comment]
> Regarding the failing spell check (titel is correct in German): (...) Is there a need for some action

I think this is what `#spellok` is used for

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
