### PR TITLE
Use correct icon for elevation profile

### PR DESCRIPTION
**Pull request by DelazJ**
## Description

[Replace this with some text explaining the rationale and details about this pull request]

### CODE REVIEW

**Comment by nicogodet** [comment]
image

Would be better to have this icon instead ?
image
It would match 
image

**Comment by nyalldawson** [comment]
@nicogodet 100% correct!

**Comment by nicogodet** [comment]
@nyalldawson unfortunately I don't have the required skills to create this icon 😞

**Comment by DelazJ** [comment]
FYI I simply copied and pasted in place the cog symbol. Hope that is enough.
Looking to the other elevation profile icons, I wonder if the mActionElevationProfile should not be used in the layout, instead of [mLayoutItemElevationProfile](https://github.com/qgis/QGIS/blob/master/images/themes/default/mLayoutItemElevationProfile.svg). This is how other "add ..." to layout buttons look like (I don't have a recent QGIS here to check if mLayoutItemElevationProfile is actually used in layout though).
image

**Comment by nicogodet** [comment]
image

**Comment by nyalldawson** [comment]
Superseded by https://github.com/qgis/QGIS/pull/53141

**Pull request closed without merging**
