### PR TITLE
Load proc algorithms

### PR DESCRIPTION
**Pull request by rkanavath**
## Description   
If a provier is enabled then qgis reads all algorithm's during
startup. This involves reading descriptor files and doing all parsing
required to make gui when user actually open algorithm (click on
treeitem).
So If I have like three provider enabled it takes more time to start qgis than
usual. Even though, I might open one or two later at some point.

It is not necessary here to parse "all" data during startup.  name and
group name is only needed to fill provider-algorithm tree. This is
true for any provider which uses descriptor files (OTB, GRASS, SAGA etc..).

Issue is more about calling defineDescriptorFile() in Algorithm's
__init__ method. And ofcourse, one cannot avoid init when adding
algorithm and tree need to add an instance of algorithm. what can be
done?

There is canExecute() method in baseclass that providers can
override. so init method can read first two line or (single line?) to
fill algorithms tree. And canExecute() can do full parsing of
descriptor files.
## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [-] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
I think instead of re-using canExecute here we need a new method which is explicitly for "deferredInit". It's dangerous to hijack canExecute in this way, because e..g. this change:

   return mAlgorithm && mAlgorithm->canExecute() ? mAlgorithm.get() : nullptr;

will prevent users editing models when the canExecute check fails - which is designed to indicate only that the underlying application is available. But there's no reason we should prevent users editing models which use SAGA algorithms when SAGA itself isn't installed... those models should still be fully editable.

**Comment by rkanavath** [comment]
Agreed that it must be something other than canExecute. There is already a defineCharacteristicsFromFile() method which is used. How about adding this to base class and allow to override by each algorithm. ofcourse, qgis and gdal will do nothing.

If defineCharacteristicsFromFile name seems odd, defineAlgorithm is another option.

**Comment by m-kuhn** [comment]
Is the proposed approach in this pull request something that can be improved within the scope of this pull request or will a new one - with the design decisions under discussion taken into account - need to be opened anyway?

**Comment by rkanavath** [comment]
IMHO a new one must be opened based on changes proposed by @nyalldawson. I will update more on this weekend.

**Comment by m-kuhn** [comment]
Thanks @rkanavath I'll close this pull request in this case. Looking forward to seeing a new one later!

**Comment by rkanavath** [comment]
no problem. sorry that i haven't moved things further on this.

**Pull request closed without merging**
