### PR TITLE
[FEATURE][Plugin installer] Support for encrypted zips when installing plugins from local files

### PR DESCRIPTION
**Pull request by borysiasty**
zrzut_20180913_173246

I've also cleaned up the code a bit and made it more robust.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by borysiasty** [comment]
@alexbruy, I hope you'll like it :)

**Comment by nyalldawson** [comment]
I'm sure we've got a class somewhere for a nice password widget with a "show" icon, but can't find it right now! @elpaso @alexbruy?

**Comment by Gustry** [comment]
https://qgis.org/api/classQgsPasswordLineEdit.html ;-)

**Comment by borysiasty** [comment]
I knew the popup windo was a bad idea... ;p

**Comment by borysiasty** [comment]
Done. Still a popup window, as the Plugin Installer has very limited access to the Manager interface, but now it uses QgsPasswordLineEdit.

**Comment by nyalldawson** [comment]
Thanks! It's these little consistency touches which make the UI shine :)

**Pull request merged**
