### PR TITLE
Fix opening of GeoPackage datasets with foreign key violation

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by rouault** [comment]
Complementary to this, he default value of OGR_GPKG_FOREIGN_KEY_CHECK has been changed to NO in GDAL master (3.1dev), release/3.0 (post 3.0.0RC2, so likely for 3.0.1) and release/2.4 (for 2.4.2)

**Comment by m-kuhn** [comment]
Thanks for the quick fix

**Comment by elpaso** [comment]
@m-kuhn  @rouault am I wrong or this commit disables the FK constraints for all GPKG layers?
I am testing a GPKG with a foreign key constraint and the constraints are completely ignored.

**Comment by rouault** [comment]
> or this commit disables the FK constraints for all GPKG layers?

yes, it does. @m-kuhn had encountered situations where Geopackage datasets had failed constraints and that couldn't be opened at all due to that check.

**Comment by elpaso** [comment]
ok, thanks for clarifying, I'll open an issue.

**Pull request merged**
