### PR TITLE
Backport More intuitive relation reference widget text filter 

### PR DESCRIPTION
**Pull request by signedav**
Backport from #8114

### CODE REVIEW

**Comment by signedav** [comment]
Hi there

I rechecked @luipir s bug reported on https://issues.qgis.org/issues/20153)
The "NULL" values are not replaced on editing (or at least selected on mouseclick and then replaced on editing). Right?

We talk about three widgets:
- Relation Reference 
- Text Edit 
- Range

Since I concerned about the Relation Reference, this influenced the Text Edit. Because the bug was in `QgsFilterLineEdit` and this is used by the Text Edit Widget like by the Relation Reference. But not with the Range.

This means:
It's fine for Text Edit and Relation Reference but not for Range. Like in this demonstration:
luigis_bug

Possibly we could finalize this PR and I could fix it in another approach for the Range widget as well - but I didn't investigated yet, so it's probably similar case or probably not. @m-kuhn are there other widgets we should focus on?

Attached a simple project for testing:
[test_german.zip](https://github.com/qgis/QGIS/files/2537491/test_german.zip)

**Comment by m-kuhn** [comment]
Good job!

The range widget still looks scary. Fixing that one should be high priority too.

But let's not get sidetracked in this pull request here. I think that one is a very nice improvement and closed in itself.

**Comment by elpaso** [comment]
@signedav yes: good job here!

**Comment by signedav** [comment]
Thank you guys.

**Pull request merged**
