### PR TITLE
Make QwtPolar an optional external dependency

### PR DESCRIPTION
**Pull request by m-kuhn**
Removes all the qwtpolar sourcode

### CODE REVIEW

**Comment by m-kuhn** [comment]
Could it be provided in the ubuntugis and http://qgis.org/debian repository for a start?
This would be an easy ad-interim solution until the packages are accepted upstream.
@mach0 are you able to create such a package?

**Comment by jef-n** [comment]
Why is having qwtpolar in qgis a problem?

**Comment by m-kuhn** [comment]
What makes qwtpolar different from qwt/python/geos/qt/other dependencies?

Keeping it makes the code bigger (the next one will be the 3rd copy of it), slower to compile (may be the bit that triggers a travis timout at some point), requires us to maintain it and keeping it up-to-date (Currently I always get a "Internal QwtPolar does not support Qwt 6.1 and above" warning when I compile in a clean directory and need to manually switch to external qwtpolar) and other applications requiring qwtpolar will need to ship their own version as well instead of using a comon shared library (although, no idea who else might use it).

Bottomline: It's nothing serious but externalizing it would be in the spirit of package management.

**Comment by jef-n** [comment]
Sure, but there is no package.  Once there are packages for all platforms we build for, we can remove it.

**Comment by m-kuhn** [comment]
Which platforms are we talking about?
Ubuntu, Debian, Windows? Mac OS X?

And would it be a big pitty if one of them would have to live without until somebody jumps in and creates a package.

The point is that to build with Qt5 either it needs to be possible to build without QwtPolar, have external QwtPolar packages or include a newer internal QwtPolar. I am trying to avoid the last situation but don't care too much if it happens.

**Comment by jef-n** [comment]
All of them?  If we remove qwtpolar from qgis we loose it an all of the above.  And to me it's easier to maintain an internal qwtpolar instead of maintaining separated packages.   BTW PyQt for Qt5 with python2 is another obstacle that prevents a switch to qt5, isn't it?

**Comment by m-kuhn** [comment]
We could also make a compile time switch WITH_QWTPOLAR to turn off qwtpolar but leave the code in there. That would allow to build Qt5 painlessly on systems where the dependency is missing and buy some time to create packages. This will leave Qt4 builds unaffected.

https://wiki.python.org/moin/PyQt :
> PyQt is available in two editions: PyQt4 which will build against Qt 4.x and 5.x and PyQt5 which will only build against 5.x. Both editions can be built for Python 2 and 3.

Looks like the switches between Qt versions and python versions can be done independently. I think the Qt update will be rather painless since QtXml is back (but did not try).

The PyQt update on the other hand should be bundled with a python update (and an increment of the QGIS major version number).

**Comment by jef-n** [comment]
I was refering to packages for PyQt4 based on Qt5.  That don't exists in debian/ubuntu either. So Qt5 will only work without python bindings - and that's IMHO not an option.

**Comment by 3nids** [comment]
That would allow me to build custom widgets with Qt5 to deliver the designer plugin for Qt Creator 3...

**Comment by m-kuhn** [comment]
I don't think there is a reason to force update to Qt5 on systems where Qt4.7 or 4.8 are available.

But Qt4 support will be dropped sooner or later. I wonder if that also means that certain distributions (like the next debian release) will be shipped without PyQt4? In that case plugins would be broken because all the imports need to be updated and with that API break it's time for a major version increment.

Anyway, it would be nice to have at least the option to build without qwtpolar (but leave the code). Even better if it helps to build the designer plugin.

**Comment by 3nids** [comment]
What about:

* having a new git repo for Qwt polar source and use git submodule in QGIS source
* using Matthias' idea WITH_QWTPOLAR
?

**Comment by jef-n** [comment]
I don't see a problem with having qwtpolar in our repository.

**Comment by wonder-sk** [comment]
What about this approach (in two steps):
1. use simple QPainter-based drawing code (instead of QwtPolar) for the GPS satellites widget
2. remove QwtPolar completely

The first step should not take long as there is really just one place where QwtPolar is used.

**Comment by m-kuhn** [comment]
@jef-n Do you see a problem with keeping it in the repository and having an additional WITH_QWTPOLAR option?
@wonder-sk A leightweight solution would surely be the best idea. I just wonder who might want to do it.

**Comment by jef-n** [comment]
No, not at all.   If we use qwtpolar - and not miracously appears in all distributions we build for - we should have/keep it in our repository.   If we don't use it anymore, we should of course remove it.  It's also fine with me if code that still uses it is made optional.

**Comment by m-kuhn** [comment]
dbfe899194e9bf here we go.
In case anybody feels like writing a simple polar widget that we can include or wants to port the qwtpolar package, be assured that you have my full gratitude!

**Comment by nyalldawson** [comment]
@m-kuhn @wonder-sk do you have a screenshot available of how this widget should look?

**Comment by wonder-sk** [comment]
@nyalldawson this is how the widget looks currently:
http://docs.qgis.org/2.0/en/_images/gpstrack_polar.png

I suppose the appearance is not set in stone - personally I don't find the circles, lines and annotations for axes overly useful - and numbers are easier to read when inside satellite's dot). Here are some other examples:
http://activityworkshop.net/gps/grabs/vista-vistahcx.gif
http://www.laptopgpsworld.com/images/uploads/twelve-satellites-garmin-20081126.gif

**Pull request closed without merging**
