### PR TITLE
Collect attribute docstrings for PyQGIS documentation

### PR DESCRIPTION
**Pull request by nyalldawson**
Python doesn't support docstrings for class attributes, and since signals are an attribute, we lose the docstrings for both attributes AND signals.

The result is that the PyQGIS docs don't show anything for attributes (eg see https://qgis.org/pyqgis/master/core/QgsRasterHistogram.html) 
image

Or messed up signal document, eg https://qgis.org/pyqgis/master/core/QgsProject.html#qgis.core.QgsProject.cleared

image

We can patch around this in sipify! Now we collect the documentation from the header for class attributes and signals, and store them in a CLASS.__attribute_docs__ dictionary. When accompanied with changes in the pyqgis doc builder, we can then retrieve these docstrings and get them showing in the reference guide:

image

image

### CODE REVIEW

**Comment by DelazJ** [comment]
@nyalldawson this time https://github.com/qgis/QGIS/pull/50903 would be fixed, right? 😄

**Comment by nyalldawson** [comment]
@DelazJ 
>  this time https://github.com/qgis/QGIS/issues/50903 would be fixed, right?

mostly, but there's a signature issue i'd like to fix before closing that one off

**Comment by nyalldawson** [comment]
@3nids this should be ready to go now

**Review by 3nids — APPROVED** [review]
awesome!

**Comment by Gustry** [comment]
@nyalldawson @3nids 

Sorry if I'm out of topic, just asking quickly, do you know if it's possible to make something about the `QgsProcessingException` ?
image

Very minor issue, that's why I'm just asking on a PR

**Comment by nyalldawson** [comment]
@Gustry 
That's annoyed me in the past too. I'm not sure what's involved in fixing that though.

**Pull request merged**
