### PR TITLE
Add active python plugins in the about dialog

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This extra information is added with the hope it'll add value to issues reporting when people are pasting the content of the about dialog's text box.

Specifically, it'll allow people reviewing newly filed issues to know whether 3rd-party plugins were active or not without the need of asking: "did you deactivate plugins?".

This is how it looks when pasting the content of the about box into github:

QGIS version | 3.9.0-Master | QGIS code revision | 511826d502
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.4
Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 (Ubuntu 11.5-1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Ubuntu Eoan Ermine (development branch) | This copy of QGIS writes debugging output.
Active python plugins | go2streetview; timemanager; GroupStats; slyr; MemoryLayerSaver; DataPlotly; processing_r; processing; db_manager

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [x] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by gioman** [comment]
Hero.

**Comment by Gustry** [comment]
Nice!
Why not adding a button in the about dialog to copy the table in the clipboard? I see quite a few bug report with a wrong copy/paste.

**Comment by nirvn** [comment]
@Gustry , I don't think it'd nicely fit in the context. Do you have examples of filed issues with the wrong copy/pasted content?

**Comment by Gustry** [comment]
Some are doing screenshot: https://github.com/qgis/QGIS/issues/30636 It's not searchable in github and we might not see all information.

Copy/paste without the markdown formatting: https://github.com/qgis/QGIS/issues/31970

I think there are plenty of reports with a few information.

I think, if we want better bug report from our users, we need to simplify the bug report template. Providing a button is easier than following https://github.com/qgis/QGIS/blame/master/.github/ISSUE_TEMPLATE/bug_report.md#L35

BTW, is your information will be displayed in the crash bug report? It's a different one AFAIK.
Look https://github.com/qgis/QGIS/issues/31546 where we ask for a clean QGIS profile.

**Comment by nirvn** [comment]
@Gustry , yeah, the crash bug report is a different deal altogether, not addressed here.

**Pull request merged**
