### PR TITLE
Do not persist estimated GDAL metadata

### PR DESCRIPTION
**Pull request by m-kuhn**
GDAL saves metadata like min and max values into a .aux.xml sidecar file next to raster files.
It does this always, even when the calculated values are estimated. In subsequent runs of GDAL processing tools
it will use these values as if they were reliable.

This patch takes care of deleting newly written .aux.xml files if there is a risk that they include estimated data.

Fix #19517  https://issues.qgis.org/issues/19517

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
@rouault is that something that GDAL could/should take care of by itself?

**Comment by rouault** [comment]
In GDAL master, there has been a related change recently, where if stasistics have been computed in an approximate way a STATISTICS_APPROXIMATE=YES metadata item is added:

```
$ gdalinfo test.tif -approx_stats
Driver: GTiff/GeoTIFF
Files: test.tif
[...]
  Metadata:
    LAYER_TYPE=athematic
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=126.765
    STATISTICS_MINIMUM=74
    STATISTICS_STDDEV=22.928470838676
    STATISTICS_VALID_PERCENT=100

$ gdalinfo test.tif
Driver: GTiff/GeoTIFF
Files: test.tif
       test.tif.aux.xml
[...]
  Metadata:
    LAYER_TYPE=athematic
    STATISTICS_APPROXIMATE=YES
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=126.765
    STATISTICS_MINIMUM=74
    STATISTICS_STDDEV=22.928470838676
    STATISTICS_VALID_PERCENT=100

$ cat test.tif.aux.xml 
<PAMDataset>
  <PAMRasterBand band="1">
    <Description>Band_1</Description>
    <Metadata>
      <MDI key="LAYER_TYPE">athematic</MDI>
      <MDI key="STATISTICS_APPROXIMATE">YES</MDI>
      <MDI key="STATISTICS_MAXIMUM">255</MDI>
      <MDI key="STATISTICS_MEAN">126.765</MDI>
      <MDI key="STATISTICS_MINIMUM">74</MDI>
      <MDI key="STATISTICS_STDDEV">22.928470838676</MDI>
      <MDI key="STATISTICS_VALID_PERCENT">100</MDI>
    </Metadata>
  </PAMRasterBand>
</PAMDataset>
```

And if I recompute them in a non-approx ways, this item disappears:
```
$ gdalinfo test.tif -stats
[...]
  Metadata:
    LAYER_TYPE=athematic
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=126.765
    STATISTICS_MINIMUM=74
    STATISTICS_STDDEV=22.928470838676
    STATISTICS_VALID_PERCENT=100

$ cat test.tif.aux.xml 
<PAMDataset>
  <PAMRasterBand band="1">
    <Description>Band_1</Description>
    <Metadata>
      <MDI key="LAYER_TYPE">athematic</MDI>
      <MDI key="STATISTICS_MAXIMUM">255</MDI>
      <MDI key="STATISTICS_MEAN">126.765</MDI>
      <MDI key="STATISTICS_MINIMUM">74</MDI>
      <MDI key="STATISTICS_STDDEV">22.928470838676</MDI>
      <MDI key="STATISTICS_VALID_PERCENT">100</MDI>
    </Metadata>
  </PAMRasterBand>
</PAMDataset>
```

**Comment by m-kuhn** [comment]
Nice!

So should this all be inside a

```
#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(2, 3, 3)
```

**Comment by m-kuhn** [comment]
I'll update to 2.4.0

I'm not sure which tools inside QGIS use it. It's probably mostly processing algorithms calling gdal modules, but those shouldn't require any change on QGIS side I assume.

**Comment by rouault** [comment]
The GDAL utilities haven't been changed at all regarding this. If approximate statistics are available and they need statistics, they'll use them (can't really think of which one would use statistics at the moment...). This is a higher level policy to decide if that's good enough for you or not.

**Comment by m-kuhn** [comment]
I don't have much insight, I was just reading this issue report here: https://issues.qgis.org/issues/19517

> 11) For instance, if run r.quantile with "generate recode rules" flag, the output is [... wrong result here ...]

The effect right now is that if a dataset is loaded for the first time, the results don't use estimated metadata, whereas after closing and reopening it will apparently use the estimated metadata to calculate the results.

**Comment by nyalldawson** [comment]
> if run r.quantile

So with this specific report it isn't a GDAL OR QGIS bug -- it's an issue in GRASS, which would also need to be updated to ignore approximate statistics for GDAL >= 2.4

So given this, should we just *always* delete estimated metadata?

**Comment by m-kuhn** [comment]
@nyalldawson that sums up exactly what I was thinking after writing my last comment.

**Comment by PedroVenancio** [comment]
Hi @m-kuhn and @nyalldawson 

Do you think this fix can be backported to LTR (2.18.25)?

**Comment by m-kuhn** [comment]
@PedroVenancio I did the backport but it's not yet actually tested

**Pull request merged**
