### PR TITLE
[opencl] Add FindOpenCLhpp CMake module; vendor cl2.hpp; fixup includes

### PR DESCRIPTION
**Pull request by dakcarto**
## Description

CL/cl2.hpp, which the OpenCL support is based upon, is not always
included with OpenCL on some platforms, e.g. Mac, or not readily
available as a package. This work adds a CMake module specifically for
finding cl2.hpp, as installed by OpenCL-CLHPP project.

If not found, but standard OpenCL lib and headers are, the vendored
cl2.hpp in external/opencl-clhpp is used, as it needs no compilation.

- Only the cl2.hpp, license and README are vendored from OpenCL-CLHPP.

- Fix up referenced includes in other CMake targets, to ensure the
includes for OpenCL are specifically added (previously, they were
sometimes found in existing include directories of other dependencies).

- Fixup for standard FindOpenCL module not assinging proper framework
headers directory for Mac.

See also: http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-OpenCL-and-macOS-td5373954.html

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by dakcarto** [comment]
@telwertowski, if you get the chance, can you also verify this setup works for you?

**Review by elpaso — APPROVED** [review]
LGTM Thanks! 
I think that now we can also remove the special rule here:  https://github.com/qgis/QGIS/blob/master/CMakeLists.txt#L33 and switch opencl on by default on Mac too.

**Comment by dakcarto** [comment]
@telwertowski, thanks for the testing!

@elpaso wrote:
> I think that now we can also remove the special rule here: https://github.com/qgis/QGIS/blob/master/CMakeLists.txt#L33 and switch opencl on by default on Mac too.

I went back and forth on this before pushing PR. My feeling is that it _could_ be enabled now, by default for Apple, but I was unsure of why BSD was included in the conditional as well. @3nids, any insight there?

However, I did see an immediate crash when attempting to open the Options (Preferences on Mac) dialog, if the OpenCL device query call fails. This was after a valid compilation, with no relevant warnings. I suppose that's up to the person compiling to ensure the OpenCL setup is proper to begin with.

Additionally, Apple has deprecated OpenCL in macOS >= 10.14. I assume the `OpenCL.framework` will stick around for at least another year, but there is no indication from Apple. Maybe by the time it is removed, there is another viable approach for parallel processing on macOS, e.g. [POCL](http://portablecl.org/) or [Vulcan/SPIR-V](https://www.khronos.org/opencl/), etc.

I tried using `pocl` 1.2 via conda-forge, but it failed to work with the QGIS OpenCL code, or with macOS  in general (I'm too OpenCL illiterate to know which :smirk: )

+1 for enabling for Apple by default (for now).

**Comment by lbartoletti** [comment]
> but I was unsure of why BSD was included in the conditional as well

Sometimes Apple stayed close to the BSD :) For OpenCL it was the same misery, now we stay between BSDs with this bad support:) Thank you for leaving the condition for BSD

**Comment by dakcarto** [comment]
@elpaso or @3nids, anything further needed for this, or can I merge?

**Comment by elpaso** [comment]
LGTM, many thanks again for testing and fixing this issue.

**Comment by 3nids** [comment]
sorry did not have chance to test it yet, but LGTM.
Thanks a lot for tnis!

**Pull request merged**
