### PR TITLE
[needs-docs] KDE: Moved project properties menu item from settings into the projects menu

### PR DESCRIPTION
**Pull request by elpaso**
Make KDE behave like other OSs

### CODE REVIEW

**Comment by DelazJ** [comment]
Could you add [needs-docs] tag, please? This difference is documented in the User manual and would then need to be removed.
Do you also plan to move the `Panels` and `Toolbars` entries in Settings instead of View menu (as stated just above [this title](http://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_gui.html#layer) )? (_not a feature request, just asking_)

**Comment by elpaso** [comment]
@DelazJ sure I'll add the tag, I though all the snapshots were taken on gnome, my fault.

No, I'm not planning to move the other menu items, the only one that really IMHO didn't belong to the application settings was the projects properties.

**Comment by andreasneumann** [comment]
Good catch @DelazJ - the Panels and Toolbar menus are also different in KDE.

Would also deserve to be aligned.

**Comment by elpaso** [comment]
@andreasneumann why? 

The HIG still makes sense to me, it's just the project properties that do not belong to application settings.

**Comment by andreasneumann** [comment]
@elpaso - it is always a pain when teaching in a mixed environment (Windows, OSX, Linux/KDE) when menus are organized in a different way.

But I agree that the project properties are the more important items.

Personally, I would align everything on all platforms, but this is just my opinion.

**Comment by NathanW2** [comment]
I'm in the "make it the same on all camp".  IMO the guides for each
platform are just that guides, not hard rules.  Looking after our users on
every platform should be the main concern even if that means breaking OS
guides at times (find me an OS that follows their own HIG ;) )

**Comment by borysiasty** [comment]
+1! As a KDE user, I'll be happy with platform-independent QGIS much more than when sticking to the KDE HIG.

I guess the KDE HIG is mainly applicable for KDE-oriented apps, I can't imagine libreoffice or gimp complying with it ;) And no, being Qt-based is still not KDE-oriented. That's just my two cents.

**Comment by elpaso** [comment]
@borysiasty this is a small step in the right direction ... do we merge?

**Comment by borysiasty** [comment]
> @borysiasty this is a small step in the right direction ... do we merge?

Yes, please!

**Comment by elpaso** [comment]
One less in the queue ...

**Pull request merged**
