### PR TITLE
Add includemocs.py and create one moc file per cpp file

### LINKED ISSUE #59157: QGIS - Visual Studio build - Projects missing build options (/bigobj)
### What is the issue about the documentation?

I am working on building QGIS on Windows 11 using Visual Studio 2022.

The process from the updated install.md is working really well and finding subtle little things in the process I am working through.

One of the things is that 2 of the projects that were built in the Visual Studio solution were missing some build options.    I am not sure of where these would need to be set in the code to fix this issue, so wanted to bring this up here.

qgis_test
qgis_core

It was missing the "/bigobj" build option (see end pasted below) as this was reported by a build error.  Once I added this for these 2 projects, they built successfully.

%(AdditionalOptions) /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtCore" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtGui" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtXml" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtWidgets" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtSvg" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtNetwork" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtSql" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtConcurrent" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/QtCrypto" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtSerialPort" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtPrintSupport" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/share/Qt6/mkspecs/win32-msvc" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/geos" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/libxml2" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/minizip" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtCore5Compat" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtPositioning" /utf-8 -Zc:__cplusplus -utf-8 **/bigobj**

### PR DESCRIPTION
**Pull request by m-kuhn**
This creates an include moc file per source file, which is supposed to improve build times for incremental builds and have a few other positive effects.
https://planet.kde.org/friedrich-kossebau-2023-06-28-include-also-moc-files-of-headers/
It should also help to fix the requirement for `/bigobj` in some environments (not sure about the exact conditions under which this is required)

Copied from https://github.com/KDABLabs/KDToolBox/tree/master/qt/includemocs

Fixes https://github.com/qgis/QGIS/issues/59157

**What this does** (reviewer guide)

1. adds a helper script `scripts/includemocs.py` which can add moc include lines and detect missing ones (see link above for source)
2. add moc include lines (that's where all the files are affected)
3. adds include guards in various header files where they were missing
4. removes unused private variables
5. removes `qt_add_cpp` calls, they are not needed with automoc in place

### CODE REVIEW

**Comment by m-kuhn** [comment]
To reduce deviation from master and make future backporting easier, I'd propose to backport this too.

**Comment by m-kuhn** [comment]
Nice addition, for whatever reason, we now get warnings about unused private variables which were hidden before.

**Review by nyalldawson — APPROVED** [review]
Lgtm! will you resurrect the warnings as Error  flag?

**Comment by m-kuhn** [comment]
> Lgtm! will you resurrect the warnings as Error flag?

Thanks for the review @nyalldawson 
It's gone

**Comment by nicogodet** [comment]
@m-kuhn It still fails on my machine
`D:\QGIS_src\src\core\expression\qgsexpressionfunction.cpp : fatal error C1128: le nombre de sections a dépassé la limite du format de fichier objet : compilez avec /bigobj`
Same point as before

I compile with Ninja and ccache, should I delete my build folder and retry ?
Ninja compiles more than 3000 files so I suspect it will not change the outcome

**Comment by m-kuhn** [comment]
That's on a different file now (not the moc any more)

Can you add this file to the list that you cited before:

https://github.com/qgis/QGIS/blob/42a3bcf290e1a0ac24a83137878b7b5c2db1e16b/src/core/CMakeLists.txt#L2183-L2189

**Comment by nicogodet** [comment]
```diff
diff --git a/src/app/CMakeLists.txt b/src/app/CMakeLists.txt
index f64c6e76cb1..ed2f1ae7765 100644
--- a/src/app/CMakeLists.txt
+++ b/src/app/CMakeLists.txt
@@ -477,16 +477,21 @@ if(PEDANTIC)
 endif()

 if(MSVC)
-# -wd4091 Avoid 'typedef' ignored on left of '' when no variable is declared warning in dbghelp.h
-set_source_files_properties(
-  qgisapp.cpp
-  main.cpp
-  qgscrashhandler.cpp
-  PROPERTIES COMPILE_FLAGS -wd4091)
+  # -wd4091 Avoid 'typedef' ignored on left of '' when no variable is declared warning in dbghelp.h
+  set_source_files_properties(
+    qgisapp.cpp
+    main.cpp
+    qgscrashhandler.cpp
+    PROPERTIES COMPILE_FLAGS -wd4091
+  )
+  set_source_files_properties(
+    qgisapp.cpp
+    PROPERTIES COMPILE_FLAGS "/bigobj"
+  )
 endif()

 if(HAVE_OPENCL)
-    include_directories(SYSTEM ${OpenCL_INCLUDE_DIRS})
+   include_directories(SYSTEM ${OpenCL_INCLUDE_DIRS})
 endif()

 if(ENABLE_MODELTEST)
```

```diff
diff --git a/src/core/CMakeLists.txt b/src/core/CMakeLists.txt
index 808540650d2..0c1ad171c11 100644
--- a/src/core/CMakeLists.txt
+++ b/src/core/CMakeLists.txt
@@ -2183,7 +2183,9 @@ endif()
 if(MSVC)
   set_source_files_properties(
       ${CMAKE_CURRENT_BINARY_DIR}/qgsexpression_texts.cpp
+      expression/qgsexpressionfunction.cpp
+      textrenderer/qgsfontmanager.cpp
       proj/qgscoordinatereferencesystem.cpp
       PROPERTIES COMPILE_FLAGS "/bigobj"
   )
```
It builds with theses diffs
I can push them (with or without little formatting)

**Comment by m-kuhn** [comment]
Please do (with or without formatting)

**Pull request merged**
