### PR TITLE
Switch windows specific functions to wchar versions

### PR DESCRIPTION
**Pull request by m-kuhn**
I am not sure if it's a Qt6 thing (apparently `UNICODE` is now default there) or something else, but I failed to build and had to switch calls to wide strings.

Reading https://stackoverflow.com/questions/402283/stdwstring-vs-stdstring this seems to be the right thing to do

> Thus, if you work on Windows, you badly want to use wchar_t

Also replaces some failure messages with more meaningful content (using `errno` instead of `e.what()`see https://stackoverflow.com/questions/17337602/how-to-get-error-message-when-ifstream-open-fails)

CC @jef-n is this change backwards compatible?

### CODE REVIEW

**Comment by jef-n** [comment]
> CC @jef-n is this change backwards compatible?

I don't think so.  The .env file will be in UTF-16.

**Comment by m-kuhn** [comment]
@jef-n  Does it make sense to change this for qt6 only? Thinking about properly handling special chars in paths.

**Comment by m-kuhn** [comment]
@jef-n better like that, i.e. we only switch with Qt6?

**Comment by m-kuhn** [comment]
Ping @jef-n

**Pull request closed without merging**
