### PR TITLE
[needs-docs] Rename action in Layers panel contextual menu

### PR DESCRIPTION
**Pull request by DelazJ**
because it's how it's called in Layer menu

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'd be inclined to go the other way and change everything to "show in overview". It seems odd to me that an "add..." action is checkable and can be unchecked. @nirvn what do you think?

**Comment by nirvn** [comment]
Agreeing with @nyalldawson here, show is a better verb to go alongside a checkbox.

**Comment by m-kuhn** [comment]
Merging the accepted change in wording. Not sure what to do with the other issue you mentioned here, but this pull request is probably not the place to discuss this?

**Comment by DelazJ** [comment]
Thanks @m-kuhn 
For the rest, i'll try to open an issue report...

**Pull request merged**
