### PR TITLE
Fixes wrong placement of curved labels

### PR DESCRIPTION
**Pull request by fritsvanveen**

### CODE REVIEW

**Comment by nyalldawson** [comment]
@fritsvanveen you'll need create a new branch in your fork, push that to your github repo and then open a pull request from that branch

**Comment by fritsvanveen** [comment]
@nyalldawson I followed https://help.github.com/articles/syncing-a-fork/ exactly, but my local branch does not get updated. I worked with SVN myself. Github is quite different.
This is what girthub says:

**Comment by nyalldawson** [comment]
Ok - here's a couple of suggestions. Before you do any of this make sure you've committed any local changes (ie `git diff` shouldn't show any uncommitted work)

1. git it tricky to get your head around at first... so don't despair, we've all been through this! All of a sudden you'll "get it" and wonder how you ever lived with svn ;)

2. your upstream branch is still pointing to your fork - ie  https://github.com/fritsvanveen/QGIS.git. It should be pointing to the main qgis branch - https://github.com/qgis/QGIS.git. To fix this:

    git remote rm upstream
    git remote add upstream https://github.com/qgis/QGIS.git
    git remote update upstream

Basically we remove the old upstream, add the correct one and update it.

3. you're working on your master branch. that's not good practice as usually the master branch is kept as a copy of the upstream code. Better is to work on separate branches for each fix/feature you're working on. So - to fix this first copy your current master branch into a new 'label_fixes' branch:

   git checkout -b label_fixes

Then checkout the master branch again:

   git checkout master

... and reset it to be a pristine copy of upstream

    git reset --hard origin/master

4. now, to get your latest commit rebased on to master. To do this we'll make another branch, which is initially a copy of upstream (ie master):

    git checkout -b upside_down_labels

now the 'upside_down_labels' branch is a new working branch which is a copy of upstream. Grab your latest commits and add them to this branch:

    git cherry-pick fe108f3

Git will then complain about the merge conflicts. To fix this you'll need a merge tool - i'd suggest "meld". Installing and setting this up will differ depending on your environment (if you're using a linux distro most of this is automatic). So install meld, then type `git mergetool`. If everything goes correct you'll get a nice gui showing the merge conflicts and allowing you to manually address them. When done, save and exit. Type `git cherry-pick --continue` to kick things off again. You'll then need to cherrypick af762c7 and e704d34 as well. 

If everything goes well you'll have a nice clean branch which is a copy of master + your latest 3 commits. Push that branch up to github: `git push origin upside_down_labels` and then create a new pull request from that branch.



This all sounds horribly complex but it's the easiest way I can think of to clean up this branch. Not sure if anyone else has an alternative approach? @NathanW2 @m-kuhn @wonder-sk?

**Comment by nyalldawson** [comment]
@fritsvanveen maybe don't push it to github until tomorrow - I'll fetch a copy of your repo so even if things go totally wrong I'll have a version of this work

**Comment by fritsvanveen** [comment]
@nyalldawson I saved my work to a safe place. Not related to github at all ;-)

**Comment by fritsvanveen** [comment]
Closed in favor of https://github.com/qgis/QGIS/pull/3521

**Pull request closed without merging**
