### PR TITLE
Fix a bunch of warnings emitted by gcc11

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Review by rouault — APPROVED** [review]

**Comment by rouault** [comment]
Note in GDAL we have a cpl::down_cast<> ( https://github.com/OSGeo/gdal/blob/daf8a2abc014b937ac276c213cf26e843121f6cb/gdal/port/cpl_conv.h#L371 ) that is basically a static_cast<> in release mode, and a dynamic_cast<> with an assertion in debug mode. A similar qgis::down_cast<> could probably be useful to indicate the intent

**Comment by nyalldawson** [comment]
@rouault that sounds useful, but wouldn't it mean you still get flooded with these "nonnull" compile warnings when building in debug mode?

**Comment by rouault** [comment]
> wouldn't it mean you still get flooded with these "nonnull" compile warnings when building in debug mode?

I think those warnings are only emitted in optimized builds. https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html seems to confirm it:    "-Wnull-dereference: Warn if the compiler detects paths that trigger erroneous or undefined behavior due to dereferencing a null pointer. This option is only active when -fdelete-null-pointer-checks is active, which is enabled by optimizations in most targets. The precision of the warnings depends on the optimization options used."

**Comment by nyalldawson** [comment]
> I think those warnings are only emitted in optimized builds.

Hmm.... Since moving to fedora 34 I'm being flooded with these warnings on my debug build though...

**Comment by nyalldawson** [comment]
Actually sorry it's "nonnull", not "null-dereference". And there's no mention of nonnull being shown in optimised builds only.

**Comment by rouault** [comment]
ok, but I don't think the cpl::down_cast ported to use Q_ASSERT() instead of CPLAssert() should trigger them. The return of the function is a static_cast<>. The dynamic_cast<> is only done in an assertion.

**Comment by nyalldawson** [comment]
Ah, that makes sense!

**Pull request merged**
