### PR TITLE
[WIP] Migrate QRegExp to QRegularExpression

### PR DESCRIPTION
**Pull request by roya0045**
## Description

Simple PR to change as much remaining QRegExp to QRegularExpressions.

In some cases I'm not 100% sure about the proposed changes, mostly with old patterns/options. Tried to keep it as close to the original as possible.

Open for suggestions.

### CODE REVIEW

**Comment by roya0045** [comment]
As anchoredPattern are only in qt 5.12 and up, should I ifdef and leave the old solution in those cases? Otherwise I'm not sure how to go for exact match.

Curious to know if the same should be done with the ones requiring wildcard.

**Comment by PeterPetrik** [comment]
fix https://github.com/qgis/QGIS/issues/31594

**Comment by roya0045** [comment]
@PeterPetrik Yes this is why I started working on this. Though there are some dependencies issues and I'm not sure all can be transferred...

For instance using AnchoredPattern requires QT5.12 (to replace the exactMatch regexp)
And the 3 or 4 cases using wildcard require QT 5.15. Nyall suggested ifdef but I'm not sure if I should retain the full regexp or trying out QregularExp without the wildcard/anchored patterns.

**Comment by PeterPetrik** [comment]
yep, that is why i was keeping this in my backlog for maybe some future qgis grant...

**Comment by roya0045** [comment]
I'm in no rush to get this merged to be honest and I don't mind if the work is split up. I still need to fix my build now hat I need to change qt dependencies to something else than 5.9. If someone wants to take this as a base and rework it I have no opposition. I just wanted to give it a first pass.

**Comment by PeterPetrik** [comment]
i think this is bigger chunk of work, maybe suitable for larger project...

**Comment by nyalldawson** [comment]
@roya0045 this is fantastic stuff, and will be extremely valuable when it comes time for a qt 6  based release!

Could I trouble you to open individual prs for each part of the code you port? There's bits here which would be immediate merges, while other parts are quite involved. Unfortunately the size of this mega-pr (160+ files changed :scream: ) makes it hard to handle...

**Comment by roya0045** [comment]
@nyalldawson No trouble, I was thinking of doing such a thing already. Mostly splitting it in 3: What is ready to merge, Qt 5.12 + (anchoredpatterns) and qt 5.15+ (wildcards). Though some changes I'm not too sure and I couldn't get it to build fully yet (tried on linux and get some weird qt error right after compiling core).

**Comment by roya0045** [comment]
Closing temporarily to prevent tests. Will reopen with changes that should be mergeable currently.

**Pull request closed without merging**
