### PR TITLE
[server][bugfix] Cleaning GetCapabilities response

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

This PR fixes https://issues.qgis.org/issues/18197.

Actually, OGC tests for WMS are currently green, but owslib python package is not able to parse the `GetCapabilities` document due to an empty `MetadataURL` element defined for the root layer.

By removing this tag, OGC tests are failing because the root layer has a `Name` element. So this PR removes `Name` and `MetadataURL` elements for the root layer (`WMSRootName` parameter is still used for the `Title` tag).

This way, OGC tests are green and owslib is now able to parse the document.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rldhont** [comment]
@pblottiere if we removed the Name of the LayerRoot, the complet project can't be requested through 1 layerName ?

**Comment by rldhont** [comment]
@pblottiere is it possible to add owslib in tests ?

**Review by sbrunner — APPROVED** [review]
Nice, thanks, I will test it next week :-)

**Comment by pblottiere** [comment]
@rldhont 

> if we removed the Name of the LayerRoot, the complet project can't be requested through 1 layerName ?

Indeed... Another way is to avoid empty elements in the document. 

This way, the `Name` element would be added only if `WMSRootName` is defined or if the project's title is not empty. Same thing could be done for `Abstract` and `Title`.

What do you think?

> is it possible to add owslib in tests ?

Yes of course.

**Comment by pblottiere** [comment]
> It's the right way for me!

Thanks for your quick response @rldhont! I let you know :+1:

**Comment by pblottiere** [comment]
@rldhont I added a simple test to read `GetCapabilities` document with `owslib`. 

Let me know if you're agree with these changes. Thanks!

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
@pblottiere after merge can you backport it to release-3_0 ? Thanks

**Comment by sbrunner** [comment]
Thanks :-)

**Pull request merged**
