### PR TITLE
[Server] Removing method based on non-configurable options

### PR DESCRIPTION
**Pull request by rldhont**
Some options used by the server are not configurable in the QGIS project, so I remove the method and code associated.

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by mhugent** [comment]
I think those sia2045 methods are not used anymore, so it should be ok to remove them.
@andreasneumann : any objections?

**Comment by andreasneumann** [comment]
If someone wants to create an SIA2045 compatible WMS server, these would still be necessary.

Or are there alternative methods to fulfill such standards that are extensions on OGC WMS? E.g. would a custom Python plugin work in this case?

There are more such standards that have extra regulations, e.g. eCH0056 - see https://www.ech.ch/vechweb/page?p=dossier&documentNumber=eCH-0056&documentVersion=1.00

Where on top of OGC WMS there must be additional behaviors fulfilled in order to be eCH compliant.

Or how are the Europeans handling Inspire conformant OGC web services?

**Comment by andreasneumann** [comment]
Since these enhancements have been paid by my former employer, we would have to ask my successor if they are important to them.
Just removing it without asking, seems rude to me.

**Comment by mhugent** [comment]
>Or are there alternative methods to fulfill such standards that are extensions on OGC WMS? E.g a >custom Python plugin work in this case?

It would be possible to write  a python filter plugin to modify the GetFeatureInfo output accordingly

>Just removing it without asking, seems rude to me.

Yes, I agree (althout it happened a lot in the last 1-2 years)

**Comment by rldhont** [comment]
@andreasneumann I have open this PR to propose to remove these method, because I didn't find any way in the QGIS UI to edit th options associated.

**Comment by mhugent** [comment]
@rldhont : these options have been activated by editing the project file (adding content to the properties section).
We are currently contacting people who were involved in that project to ask if it is still in use. Please wait until we have confirmation

**Comment by mhugent** [comment]
I found out we are using the option to have featureInfo layer aliases in one of our projects. So please don't remove it. It would however be nice to have a GUI in future.

**Comment by elpaso** [comment]
@andreasneumann a server python plugin could easily inject missing XML elements into the getcapabilities response, if that's what you was asking for.

**Comment by nyalldawson** [comment]
Should we close this? Seems there's a strong use case/need for them to remain.

**Pull request closed without merging**
