### PR TITLE
[FEATURE]: consider settings from attribute drag and drop form in WMS feature info

### PR DESCRIPTION
**Pull request by mhugent**
With the drag and drop editor form, it  is possible to redorder attributes and/or add groups and subgroups  in the edit form. This  PR adds the feature that these settings can  also be used to  format the WMS GetFeatureInfo response. E.g. if we have Group1 with attributes 'id','text' and Subgroup1 with attribute 'description', the XML response will be:

GetFeatureInfoResponse&gt;
&lt;Layer name="test"&gt;
  &lt;Feature id="658"&gt;
    &lt;Group1&gt;
      &lt;Attribute name="id" value="658"/&gt;
      &lt;Attribute name="text" value="bla"/&gt;
      &lt;Subgroup1&gt;
        &lt;Attribute name="description" value="bla, bla, bla"/&gt;
      &lt;/Subgroup1&gt;
    &lt;/Group1&gt;
&lt;/Feature&gt;
&lt;/Layer&gt;
&lt;/GetFeatureInfoResponse&gt;

I'll also add a unit test later on.

### CODE REVIEW

**Comment by elpaso** [comment]
Did you check if is still conformant with the specifications?

**Comment by mhugent** [comment]
> Did you check if is still conformant with the specifications?

The WMS spec does not say anything about the content of the GetFeatureInfo response:

"The actual semantics of how a WMS decides what to return more information about, or what exactly to return, are
left up to the WMS provider."

**Comment by elpaso** [comment]
> > Did you check if is still conformant with the specifications?
> 
> The WMS spec does not say anything about the content of the GetFeatureInfo response:
> 
> "The actual semantics of how a WMS decides what to return more information about, or what exactly to return, are
> left up to the WMS provider."

And what about the clients? Do they play well with this new xml structure?

**Comment by mhugent** [comment]
>And what about the clients? Do they play well with this new xml structure?

The default setting is that the server still returns the default xml structure if the checkbox 'Use attribute form settings for GetFeatureInfo response' in the project properties is not checked

**Comment by mhugent** [comment]
Bad merge. Closing and make new PR in https://github.com/qgis/QGIS/pull/41031

**Pull request closed without merging**
