### PR TITLE
WEBKIT includes changed

### PR DESCRIPTION
**Pull request by gshegunov**
WEBKIT include changed.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Does it fail on your system with the QtWebkit prefix? I remember I had problems without that for some builds but I'd have to check for which system.

**Comment by gshegunov** [comment]
Yes, it fails on my system with Qt5. In general, using prefixes is not a
good practice, because the structure of the directories tree could be
changed in different versions, as in this particular case. INCLUDE
environment variable has to be set to properly directories.

**Comment by m-kuhn** [comment]
Qt5 uses prefixed includes in their own source files as can be seen e.g. here:

https://github.com/qtproject/qttools/blob/dev/src/linguist/linguist/batchtranslationdialog.h

It compiles fine for me with Qt5.
Can you compile the tests, their includes are prefixed as well?
What kind of system are you using?

**Comment by gshegunov** [comment]
I am on Qt5.4. QWebFrame is located in
c:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\include\QtWebKitWidgets\

Pay attention that now the directory is QtWebKitWidgets not QtWebKit.

The sources (qwebframe.h and private qwebframe_p.h) are in
c:\Qt\Qt5.4.2\5.4\Src\qtwebkit\Source\WebKit\qt\WidgetApi\

Yes, QT uses prefixes but only when they refer to their private directory
structure.

In our case directory tree is different in different version of QT, so
using of prefixes is not a good practice. Better to to set INCLUDE
environment outside of the sources.

**Comment by m-kuhn** [comment]
WebKit is a strange kid in the Qt block anyway and since Qt5 no longer supported on every platform. Looking forward to having QWebEngine in its place. It took me too much time 

> Yes, QT uses prefixes but only when they refer to their private directory structure.

`#include <QtWidgets/QDialog>` does not look very private, more like a system include ;)

But since your patches compile fine for my Qt5 system as well, I just merged it. I'll take care of it when I find the other system which complained.

Thank you very much.

**Pull request closed without merging**
