### PR TITLE
[db manager] Show error messages directly in place

### PR DESCRIPTION
**Pull request by m-kuhn**
The old behavior was to open up a new modal dialog. Each time way to small to read anything.
This version makes it much (!!) easier to iteratively improve a query until it's working.

Needs some fine tuning of the widget (horizontal scroll, word wrap)

image

### CODE REVIEW

**Comment by m-kuhn** [comment]
Looks like we have options for the error:

 - Show it with `<pre>`, will preserve linebreaks and things like the `^` pointer to the problematic position (see screenshot)
 - Show it with `<code>` will word wrap but looses linebreaks
 - Do some parsing for `[ERROR:`, will show postgis super nice, but very specific for postgres and probably even language specific
 - Do some preprocessing, show it with `<code>` and replace `\n` with `<br>` <-- likely a good solution, do we already have a plainTextToHtml utility method? (also someting @rduivenvoorde was recently looking for regarding message log IIRC)

**Comment by rduivenvoorde** [comment]
>     * Do some preprocessing, show it with `<code>` and replace `\n` with `<br>` <-- likely a good solution, do we already have a plainTextToHtml utility method? (also someting @rduivenvoorde was recently looking for regarding message log IIRC)

I don't now if we have it and yes, that was related to messages in the  QgsMessageLog widget in QGIS itself, see:
https://lists.osgeo.org/pipermail/qgis-developer/2020-November/062573.html

Is this the same widget component? If so: yes it would be very helpfull to 'sanitize' text just before it is put (as html) on the widget. As said: in the case of '<' and '>' signs, the rest of a text is just ignored.

**Comment by nyalldawson** [comment]
@m-kuhn does using the QgsSqlCodeEditor widget help at all?

**Comment by m-kuhn** [comment]
> @m-kuhn does using the QgsSqlCodeEditor widget help at all?

Nope, it's exactly the same. Just with some syntax highlighting.
Shall we merge and fixup down the road?

**Comment by rduivenvoorde** [comment]
@m-kuhn are you sure? QgsCodeEditorSQL is a QgsCodeEditor, is a QsciScintilla which has a lot of functionality for folding/showing stuff etc etc...

And IF we add something there (to escape characters), all other QgsCodeEditor benefit from it isn't it?

**Comment by m-kuhn** [comment]
@rduivenvoorde not completely sure, no. Do you have a hint which flag to set?

**Comment by m-kuhn** [comment]
Thanks for the hints @nyalldawson and @rduivenvoorde `setWrapMode(QsciScintilla.WrapWord)` did the trick

**Review by nyalldawson — APPROVED** [review]

**Comment by m-kuhn** [comment]
Should we backport this?
I think it's a massive usability improvement.

**Comment by nyalldawson** [comment]
Go for it

**Pull request merged**
