### PR TITLE
Deal with failure to create savepoint

### PR DESCRIPTION
**Pull request by m-kuhn**
I just ran into  a situation when no savepoint could be created. I am not completely sure how this happened, but the debug output said something like "savepoints can only be created in transaction context" (and it's a transactional project).

This pull request will put the information into the message log (where it's more accessible to deal with similar issues and iron out the sources of this in the future)
Plus it will not crash, by trying to access an inexistent savepoint.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Just a thought, the failure to start a transaction might have been related to timeouts caused by pausing in a debug session. Still, if something like this happens in a user scenario, it shouldn't crash.

**Comment by pblottiere** [comment]
> "savepoints can only be created in transaction context" 

Do you have some news on these errors?

**Comment by m-kuhn** [comment]
Nope

**Comment by m-kuhn** [comment]
@vmora / @pblottiere do you plan to merge/review this? I am unlikely to provide more information.
But it fixes a potential crash and pushes information about a critical situation to a visible place, so I think it's desirable, but totally open to your thoughts.

**Comment by pblottiere** [comment]
> But it fixes a potential crash 

Yes good catch!

> pushes information about a critical situation to a visible place

Indeed, good idea. It will help a lot in the future.

Can you rebase? Then I'll merge this PR.

Thank you Matthias!

**Comment by pblottiere** [comment]
@m-kuhn Can you fix the bad indentation in order to merge this PR?

**Comment by pblottiere** [comment]
Nice! Thank you @m-kuhn!

**Pull request merged**
