### PR TITLE
Add option to export elevation profiles

### LINKED ISSUE #52547: Elevation profile DXF export
### Feature description

Possibility to export to DXF in coordenates (2D & 3D) as the terrain profile pluging do.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
This adds a new entry to the elevation profile toolbar, with various options for exporting elevation profiles

You can export the profile as:

- 3D Features: exports the profile line as 3d cross sections, with z values taken from the elevation slices
- 2D Profile: exports the profile as a distance vs elevation chart (ie as shown in the elevation profile widget)
- Distance/Elevation Table: exports sample distance vs elevation values as a table

The results can be saved as DXF files, CSV files, or ANY of the standard writeable vector spatial formats (ie shapefile/geopackage)

Profiles are generated and exported in a background task to keep everything nice and responsive.

The underlying profile export code has been kept as generic as possible, so it can potentially be reused in future in Processing tools which generate profile lines too.

Fixes https://github.com/qgis/QGIS/issues/52547
Refs https://github.com/qgis/QGIS/issues/49961

### CODE REVIEW

**Review by wonder-sk — APPROVED** [review]
:tada:  well done! ...I am really struggling to nitpick anything :smile:

**Comment by nicogodet** [comment]
Wonderful ! 🥳

Reading your description, it seems hard to add a copy to clipboard function without freezing UI, isn't it ?

**Comment by nyalldawson** [comment]
@nicogodet 

> Reading your description, it seems hard to add a copy to clipboard function without freezing UI, isn't it ?

That's correct -- it's an awkward action to expose whenever we're doing background operations. We could delay the actual copy until the background task completes, but that would be rather odd behavior -- the user would trigger an action, then need to wait some unpredictable amount of time before they can safely paste in another application.

**Comment by nicogodet** [comment]
@nyalldawson Understood ! 
Glad to see this finally coming to core, I will finally drop python plugin.
Thanks again !

**Pull request merged**
