### PR TITLE
[tests] Skip app cleanup on WMS server test

### PR DESCRIPTION
**Pull request by m-kuhn**
Avoid crashing on cleanup

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by elpaso** [comment]
@m-kuhn can you give me some more context? 
Why the cleanup suddenly provoke a crash?
Maybe @pblottiere knows more (I've not been involved that much on the server development lately).

**Comment by pblottiere** [comment]
> Why the cleanup suddenly provoke a crash?

Yep, good question. 

@m-kuhn Do you think it's the origin of the flaky behavior?

**Comment by m-kuhn** [comment]
I've got no idea, just observed occasional crashes on travis. Given that all the tests have been completed at the time of the crash, I suppose it's something in cleanup.
This was the easiest way to have a chance to avoid this without disabling tests.
Might also be possible to investigate if some (spatialite) layers are owned by Python not deleted within the tests and crash on garbage collection after exitQgis... Or so...

**Comment by pblottiere** [comment]
I'm gonna take some time this week to stress these tests locally in order to detect the issue. I would like to end with these flaky WMS tests...

@m-kuhn In the meantime, I fully understand if you want to disable them...

**Comment by m-kuhn** [comment]
Ok, cool, I'm going to push this. I can very well imagine that this helps against their flakyness.

The question is, if the crash is caused by the test (e.g. layer owned by python) or by some actual underlying memory management issue.

As a note, the recent change to get stacktraces on abrt at least got us some hints that it's related to spatialite here.

**Comment by m-kuhn** [comment]
Not going to merge this, it's still crashing as can be seen in the result.

@pblottiere if it's of value to you: the stacktrace changed. It's now in QtSql (and no longer in spatialite).

**Pull request closed without merging**
