### PR TITLE
Fix missing include dir for untwine

### PR DESCRIPTION
**Pull request by m-kuhn**
Fixes the broken windows build.
Followup https://github.com/qgis/QGIS/pull/59160

CC @uclaros

### CODE REVIEW

**Comment by uclaros** [comment]
Does it actually fix it? `FatalError.hpp` is in `/external/untwine/untwine/` which is already in the include dirs

**Comment by uclaros** [comment]
Ah, I see, the file is included using it's parent folder too!

**Comment by uclaros** [comment]
It looks like I reverted a change from #58563 by pulling the latest untwine (we should have pushed that change to upstream untwine I guess).

Can you try changing again https://github.com/qgis/QGIS/blob/8f1a6e30482a7165d618da22eb3070604eafc6be/external/untwine/api/QgisUntwine_win.cpp#L31
to
```cpp
 STARTUPINFOA startupInfo; 
```
?

**Comment by m-kuhn** [comment]
Yes, exactly, feel free to push to this PR until it's green or start a new one and merge this.

**Comment by m-kuhn** [comment]
I think if we wouldn't vendor `untwine` and only keep the QGIS specific code, we'd be in a much better situation with respect to upstreaming things :-)

**Comment by m-kuhn** [comment]
Thanks looks like we are green again. Let's hope tests are working for the next version bump, so we are prepared.

**Comment by uclaros** [comment]
I'll push this change to upstream untwine so we're ok next time.
Any changes to our vendored copies should be somehow synced to their upstreams though, or we'll be dealing with such issues (I see #58563 also modified MDAL).


> I think if we wouldn't vendor `untwine` and only keep the QGIS specific code, we'd be in a much better situation with respect to upstreaming things :-)

Unfortunately, there are no packages for untwine, nor lazperf that we could use.

**Comment by m-kuhn** [comment]
> I'll push this change to upstream untwine so we're ok next time.

Thanks

#58563 you will see that it refs multiple previous iterations, with the vendored copy the path of this two-way-sync is not easy (i.e. we don't keep patches, we have a copy of the code).

> I'll push this change to upstream untwine so we're ok next time.
Any changes to our vendored copies should be somehow synced to their upstreams though, or we'll be dealing with such issues (I see https://github.com/qgis/QGIS/pull/58563 also modified MDAL).

I think if we wouldn't vendor untwine and only keep the QGIS specific code, we'd be in a much better situation with respect to upstreaming things :-)

> Unfortunately, there are no packages for untwine, nor lazperf that we could use.

I have tried to create packages and failed because of the architecture, see https://github.com/qgis/QGIS/pull/57414#issuecomment-2198276803 . As long as the code is like this, more packaging is unlikely to happen.

**Pull request merged**
