### PR TITLE
Fix(?) font dialog on OSX

### PR DESCRIPTION
**Pull request by nyalldawson**
Refs discussion and patch at https://issues.qgis.org/issues/20426

I can't test the original issue or this fix to know if it works. @3nids @PeterPetrik @timlinux @slarosa can you please test and merge if it's correct?

### CODE REVIEW

**Comment by nyalldawson** [comment]
^^ oh wow, it's nice to have so many OSX devs available to test and fix issues on the platform now! A great change from this time last year :smile:

**Comment by PeterPetrik** [comment]
it doesn't work for me with this patch (with opencl fix merged). I am unable to set font properties for label.

**Comment by nyalldawson** [comment]
Ok, closing then.

**Comment by nyalldawson** [comment]
Thanks for the test!

**Comment by iona5** [comment]
hi, i was coming up with the general idea where the problem is in the bug report https://issues.qgis.org/issues/20426.

this PR has the patch the other way round: the first option _does_ fix the issue for me, but is removed in this PR.

the problem is in essence that QT_MAC_USE_COCOA is never defined in my build environment so the preprocessor evaluates to the second option which i guess is not intended for a mac build.

i do not know if this should be fixed in the build environment or the code, though.

from my minimal understanding of Qt and CMake i guess QT_MAC_USE_COCOA was a Qt4 thing but Qt5 is always using Cocoa so just removing the check for it is fine??

**Comment by iona5** [comment]
and @nyalldawson i was just reading your commit comment. just to clarify: the native dialog is still broken on macOS as this bug shows. the conditional is still needed there. it currently is just evaluated the wrong way for a mac build, because QT_MAC_USE_COCOA is not set.

**Comment by nyalldawson** [comment]
@peterpetrik can you test the changes @iona5 describes?

**Comment by iona5** [comment]
created PR #8602 for this

**Pull request closed without merging**
