### PR TITLE
Allow QgsDateTimeEdit to support dates since Jan 1st 1 CE (instead of 100 CE) and avoid QDate and QDateTime field value triple conversion

### LINKED ISSUE #35574: QGIS 3.12 - Date Field does not go earlier than 1/1/100 AD in geopackage or shape file
QGIS3.12.0 (Mac Mojave 10.14.6, iMac - QGIS Website Download) - I am mapping radiometric dates from archaeological sites that date from 60000BC to 1950AD, but it appears that I can not set a date using the date field type in a geopackage or shapefile earlier than 1/1/100 AD.

I have searched the previous bugs, but did not find a similar issue. Note attached image shows the 'click earlier year' triangle button as being greyed out.

image

### PR DESCRIPTION
**Pull request by agiudiceandrea**
## Description

With PR #4842 the lower limit for values that can be entered in a field using the Date/Time widget was set to Jan 1st 100 CE (previously it was not possible to enter dates prior to Sep 14th 1752 CE).

The date of Jan 1st 100 CE was used only because QDateTimeEdit::setMinimumDateTime() doesn't support dates earlier than that.
https://github.com/qgis/QGIS/blob/d73eaa1d58ca6e7429d338ef42bcd16dcae6742a/src/gui/editorwidgets/qgsdatetimeedit.h#L196-L204

This limitation doesn't affect QDateTimeEdit::setDateTimeRange(), so it is possible to use it to allow entering dates also from 1 CE to 99 CE which previously where not allowed***.
```
    void setMinimumEditDateTime()
    {
      setDateTimeRange( QDateTime( QDate( 1, 1, 1 ) ), maximumDateTime() );
    }
```

Fixes #35574 (as far as possible).

This PR also avoids a triple conversion of QDate and QDateTime field value in QgsDateTimeFieldFormatter::representValue():
- QVariant-[toString]->QString
- QString-[fromString(format)]->QDateTime
- QDateTime-[toString(format)]->QString

while 
- QVariant-(toDateTime)->QDateTime
- QDateTime-[toString(format()]->QString

is enough for QDate and QDateTime fields.

#    
***It could be possible to go further and allow dates with negative years since they are supported by setDateTimeRange() and by QDate and QDateTime type fields for memory layers, but it seems they are not allowed in Date/Time field by some providers (e.g. Shapefile and GeoPackage).

Video_2020-05-23_234612

Dates with negative years could also be stored in text fields but they are not properly handled by the Date/Time widget until [QTBUG-84334](https://bugreports.qt.io/browse/QTBUG-84334) is fixed (QDateTime::toString() handles negative years while QDateTime::fromString() cannot parse them).

### CODE REVIEW

**Comment by nyalldawson** [comment]
Nice! Can you add some tests for this too?

**Comment by agiudiceandrea** [comment]
Hi @nyalldawson, I don't know if the added test is adequate. I think there is nothing special to test on dates between Jan 1st CE and Dec 31th 99 CE as they are not special...

What do you think about the possibility to allow also dates with negative year, although they can be used in memory layers, but not in Shapefiles or GeoPackages, for example?

**Comment by nyalldawson** [comment]
The test looks good to me!

**Comment by nyalldawson** [comment]
> What do you think about the possibility to allow also dates with negative year, although they can be used in memory layers, but not in Shapefiles or GeoPackages, for example?

Yes, I think we should support these. Ideally we'd do add a new QgsVectorDataProvider capability flag for "Supports negative year values", and correctly return this flag for memory/other (postgis?) providers. Then you'd restrict the date range for the widget based on whether the associated layer's provider supports negative years or not.

**Comment by agiudiceandrea** [comment]
Thanks. I shall have a try.
In the meanwhile I've found a bug #36715 about the Date/Time edit widget (it allows to store text into a numeric field) whose cause I can't find for now...

**Review by nyalldawson — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
The QT bug https://bugreports.qt.io/browse/QTBUG-84334 that prevented to correctly parse negative years has been fixed in Qt6 (https://codereview.qt-project.org/c/qt/qtbase/+/315029, https://github.com/qt/qtbase/commit/91140eb7268bc36efceef0459e7b124ce333829e).

**Pull request merged**
