### PR TITLE
Fix WMS Legend "meters at scale" sized symbols

### LINKED ISSUE #50366: WMS legend symbol missing for "Meters at Scale" symbology and projected CRS
### What is the bug or the crash?

The legend symbol of a vector layer having a meters at scale symbology and rendered as WMS via QGIS Server is missing if using a projected CRS. 

A workaround has been found when setting Project Properties > QGIS Server > WMS Capabilities > Default scale for legend as > 1, like 10:1. In that case, the legend symbol of the WMS layer is shown. 

Is this supposed to be normal behaviour? Standard scales that can be chosen from the dropdown do not include scales >1:1, so I guess it's not normal.

For WGS84, it's "Default map units per mm in legend" that can be defined. Is it possible that even when it's saying "Default scale for legend" for other CRS, the value entered is still translated as _map units per mm_? 

Screenshot 2022-09-27 at 10 59 12

### Steps to reproduce the issue

1. Open a new QGIS project with CRS = EPSG:2056
2. Add a vector layer (e.g. lines)
3. Draw a feature
4. Define Symbology > Stroke width = 5, Meters at Scale
5. Go to Project properties > QGIS Server > WMS capabilities, set Default scale for legend to 1:1000 or something else 1:>1
6. Run a local QGIS server (e.g. with docker)  
7. Open another QGIS project and add WMS layer from your project on the local server, add the line layer 
8. See that there is no legend symbol

Redo the same from point 5 on, setting the Default scale for legend to something >1:1

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.4-Białowieża | QGIS code revision | 3f4577ce6e
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 12.6
  |   |   |  
Active Python plugins
numericalDigitize | 0.4.7
firstaid | 2.1.5
lrs | 1.2.2
precipitation_plugin | dev
DataPlotly | master
quick_map_services | 0.19.29
vertex_compare | 0.0.1
linking_relation_editor | v1.0.0
QgisModelBaker | v7.1.7
HCMGIS | 22.9.9
qfieldsync | v4.1.1
swissgeodownloader | 2.0
document_management_system | 0.3.1
PointConnector | 2.0
qgis_resource_sharing | 0.16.0
plugin_reloader | 0.9.1
swiss_locator | 2.0.0
coordinate_capture | 0.2
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>QGIS version
3.22.4-Białowieża
QGIS code revision
[3f4577ce6e](https://github.com/qgis/QGIS/commit/3f4577ce6e)
Qt version
5.14.2
Python version
3.8.7
GDAL/OGR version
3.2.1
PROJ version
6.3.2
EPSG Registry database version
v9.8.6 (2020-01-22)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.31.1
PostgreSQL client version
12.3
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.4
OS version
macOS 12.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by signedav**
The bug was that the CRS (and with it the Map Units) have not been considered on `GetLegendGraphics` what leaded to invisible small symbol sizes on using Meters on Scale. It worked for EPSG:4326 since it was the default value, but not for CRS using meters (e.g. 2056). This here fixes https://github.com/qgis/QGIS/issues/50366 

It takes the MapUnits from the `QgsRenderContext::distanceArea()`, so this PR mainly sets the CRS there.

Since `QgsLegendSettings` is marked as deprecated I take the CRS from the `mapSettings` (if BBOX provided) or from the `mWmsParameters.crs()` (if no BBOX provided) in `QgsRenderer::getLegendGraphics`.

Another issue was, that as well the image size has not been calculated properly what leaded to "cropped" legends. Since the painter's image size should now be calculated according to the `QgsRenderContext` a slight rearrangement was needed:  `QgsRenderContext` needs to be defined before.

I then had the issue, that even when I `setPainter` to the context after I did not receive the expected results. So I tried it with a `tmpContext` to calculate the image size (and with it all the information the painter needs to initialize the context used to draw the legend).

- [x] One open point is, that before the (deprecated) LegendSettings used apparently always DPI 96 where in the workflow here other default values (like e.g. 88 or 91 are used). So I set it fix, but this should be resolved. 
  It would be nicer to be able to use this on BBOX:
  ```
  context.setMapToPixel( mapSettings.mapToPixel()`
  ```
  and this without BBOX:
  ```
  const double mmPerMapUnit = 1 / QgsServerProjectUtils::wmsDefaultMapUnitsPerMm( *mProject );
  context.setMapToPixel( QgsMapToPixel( 1 / ( mmPerMapUnit * context.scaleFactor() ) ) );
  ```
  but this breaks lots of tests (because all their graphics are calculated with the legendSettings DPI 96.

### CODE REVIEW

**Comment by signedav** [comment]
- [ ] needs cleaner structure
- [ ] needs to use `mapSettings.mapToPixel()` instead of calculate it from deprecated `LegendSettings`

**Comment by signedav** [comment]
I'm a little stuck here, since replacing the deprecated `LegendSettings::mmPerMapUnit()` by getting it from `QgsMapSettings` or from the `QgsWmsRenderContext::dotsPerMm()` leaded to different used dpi. 

`LegendSettings::mmPerMapUnit()` used per default 96 dpi. `QgsWmsRenderContext` uses  0.00028 meters per px what leads to ~90.714 dpi. As well the default dpi in functions of `QgsRenderContext` are 88.

Why's that different? And what dpi should be concerned here? If we keep 96, then we should this be set as the default somewhere. E.g. `mScaleFactor` of `QgsRenderContext`.

Do you have a hint @nyalldawson ?

**Comment by nyalldawson** [comment]
@signedav 

I might be missing something, but you can manually set the output dpi for QgsMapSettings, which will flow on to the render context. Maybe you can set that to match the Wms context?

**Comment by signedav** [comment]
Thanks @nyalldawson 

When it 'should' take the `outputDpi` from the `mapSettings` I can work with this information. But this will change symbol sizes slightly almost everywhere.

Because in the existing (deprecated) solution the `mapUnitsPerPixel` of the mapSettings where passed to `QgsLegendSettings::setMapUnitsPerPixel` where it calculated the `mMmPerMapUnit` according to the `legendSettings`'s `mDpi`. And this is default 96 what diverts to the `mapSettings`'s `outputDpi`:

```
mapSettings.outputDpi(): 90.7143
settings.dpi(): 96
```

**How comes?**

Here, the mapSettings are created according to the `QgsWmsRenderContext` where the DPI is (a) passed by WMS parameter or (b) defined as default `OGC_PX_M` what is 0.00028 and leads to DPI 90.714285714... 0.28 mm are the OGC standard https://docs.opengeospatial.org/is/17-083r2/17-083r2.html:

> [...] Frequently, the true pixel size is unknown and 0.28 mm has the actual size of a common display from 2005. This value is still being used as reference even if current display devices are built with pixel sizes much smaller.

and...

> NOTE: Since the 1980s, the Microsoft Windows operating system has set their default standard display pixels per inch (PPI) to 96. This value results in an approximated 0.264 mm per pixel. The similarity of this value with the actual 0.28 mm adopted in this standard can create some confusion.

So I agree, DPI of the `QgsWmsRenderContext` should be taken (what will be the same like the one from the mapSettings) as well because there the WMS parameter is considered (compared to before).

As well on having *no* BBOX passed and taking the `defaultMapUnitsPerMm` from the settings, the default 96 from the `legendSettings` is currently taken, means 96. Here I think the one from `QgsWmsRenderContext` would be appropriate as well.

**But as I said, it will change all the currently rendered symbols.**

**Comment by signedav** [comment]
Close this because this is opened #52015

**Pull request closed without merging**
