### PR TITLE
Add --json option to qgis_process tool

### PR DESCRIPTION
**Pull request by nyalldawson**
This allows external tools to more easily use the standalong qgis_process
tool without resorting to fragile string parsing of the outputs from
that tool.

Refs https://github.com/paleolimbot/qgisprocess/issues/21, and means
that we play nice with other tools who want to use QGIS algorithms!

### CODE REVIEW

**Comment by nyalldawson** [comment]
Ping @paleolimbot -- what do you think?

**Comment by nyalldawson** [comment]
Here's an example of the outputs:


qgis_process --json plugins

```
{
  "gdal_version": "3.0.4",
  "geos_version": "3.8.1-CAPI-1.13.3",
  "plugins": {
    "DataPlotly": {
      "loaded": false
    },
    "QuickOSM": {
      "loaded": false
    },
    "cartography_tools": {
      "loaded": true
    },
    "processing": {
      "loaded": true
    },
    "processing_js": {
      "loaded": false
    },
    "processing_r": {
      "loaded": true
    },
    "processing_saga_nextgen": {
      "loaded": false
    },
    "slyr": {
      "loaded": true
    }
  },
  "proj_version": "Rel. 6.3.2, May 1st, 2020",
  "qgis_code_revision": "5c8013df61",
  "qgis_version": "3.15.0-Master",
  "qt_version": "5.14.2"
}
```

qgis_process --json list

```
{
  "gdal_version": "3.0.4",
  "geos_version": "3.8.1-CAPI-1.13.3",
  "proj_version": "Rel. 6.3.2, May 1st, 2020",
  "providers": {
    "3d": {
      "algorithms": {
        "3d:tessellate": {
          "can_cancel": true,
          "deprecated": false,
          "group": "Vector geometry",
          "has_known_issues": false,
          "help_url": null,
          "name": "Tessellate",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "3d",
            "triangle"
          ]
        }
      },
      "can_be_activated": true,
      "default_raster_file_extension": "tif",
      "default_vector_file_extension": "gpkg",
      "is_active": true,
      "long_name": "QGIS (3D)",
      "name": "QGIS (3D)",
      "supported_output_raster_extensions": [
        "tif",
        "gen",
        "bmp",
        "bt",
        "byn",
        "bil",
        "ers",
        "gpkg",
        "grd",
        "grd",
        "gtx",
        "img",
        "mpr",
        "lbl",
        "kro",
        "ter",
        "mbtiles",
        "hdr",
        "mrf",
        "ntf",
        "gsb",
        "grd",
        "pix",
        "map",
        "pdf",
        "xml",
        "pgm",
        "rsw",
        "grd",
        "rst",
        "sdat",
        "rgb",
        "ter",
        "vrt",
        "nc"
      ],
      "supported_output_table_extensions": [
        "gpkg",
        "shp",
        "000",
        "bna",
        "csv",
        "dgn",
        "dxf",
        "geojson",
        "geojsonl",
        "geojsons",
        "gml",
        "gpx",
        "gxt",
        "ili",
        "itf",
        "json",
        "kml",
        "ods",
        "sql",
        "sqlite",
        "tab",
        "txt",
        "xlsx",
        "xml",
        "xtf"
      ],
      "supported_output_vector_extensions": [
        "gpkg",
        "shp",
        "000",
        "bna",
        "csv",
        "dgn",
        "dxf",
        "geojson",
        "geojsonl",
        "geojsons",
        "gml",
        "gpx",
        "gxt",
        "ili",
        "itf",
        "json",
        "kml",
        "ods",
        "sql",
        "sqlite",
        "tab",
        "txt",
        "xlsx",
        "xml",
        "xtf"
      ],
      "supports_non_file_based_output": true,
      "version": null
    },
    "cartographytools": {
      "algorithms": {
        "cartographytools:averagelines": {
          "can_cancel": true,
          "deprecated": false,
          "group": "General",
          "has_known_issues": false,
          "help_url": null,
          "name": "Average linestrings",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": []
        },
        "cartographytools:collapsedualcarriageway": {
          "can_cancel": true,
          "deprecated": false,
          "group": "Road networks",
          "has_known_issues": false,
          "help_url": null,
          "name": "Collapse dual carriageways",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": []
        },
        "cartographytools:removecrossroads": {
          "can_cancel": true,
          "deprecated": false,
          "group": "Road networks",
          "has_known_issues": false,
          "help_url": null,
          "name": "Remove cross roads",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": []
        },
        "cartographytools:removeculdesacs": {
          "can_cancel": true,
          "deprecated": false,
          "group": "Road networks",
          "has_known_issues": false,
          "help_url": null,
          "name": "Remove cul-de-sacs",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": []
        },
        "cartographytools:removeroundabouts": {
          "can_cancel": true,
          "deprecated": false,
          "group": "Road networks",
          "has_known_issues": false,
          "help_url": null,
          "name": "Remove roundabouts",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": []
        }
      },
      "can_be_activated": true,
      "default_raster_file_extension": "tif",
      "default_vector_file_extension": "gpkg",
      "is_active": true,
      "long_name": "Cartography tools",
      "name": "Cartography tools",
      "supported_output_raster_extensions": [
        "tif",
        "gen",
        "bmp",
        "bt",
        "byn",
        "bil",
        "ers",
        "gpkg",
        "grd",
        "grd",
        "gtx",
        "img",
        "mpr",
        "lbl",
        "kro",
        "ter",
        "mbtiles",
        "hdr",
        "mrf",
        "ntf",
        "gsb",
        "grd",
        "pix",
        "map",
        "pdf",
        "xml",
        "pgm",
        "rsw",
        "grd",
        "rst",
        "sdat",
        "rgb",
        "ter",
        "vrt",
        "nc"
      ],
      "supported_output_table_extensions": [
        "gpkg",
        "shp",
        "000",
        "bna",
        "csv",
        "dgn",
        "dxf",
        "geojson",
        "geojsonl",
        "geojsons",
        "gml",
        "gpx",
        "gxt",
        "ili",
        "itf",
        "json",
        "kml",
        "ods",
        "sql",
        "sqlite",
        "tab",
        "txt",
        "xlsx",
        "xml",
        "xtf"
      ],
      "supported_output_vector_extensions": [
        "gpkg",
        "shp",
        "000",
        "bna",
        "csv",
        "dgn",
        "dxf",
        "geojson",
        "geojsonl",
        "geojsons",
        "gml",
        "gpx",
        "gxt",
        "ili",
        "itf",
        "json",
        "kml",
        "ods",
        "sql",
        "sqlite",
        "tab",
        "txt",
        "xlsx",
        "xml",
        "xtf"
      ],
      "supports_non_file_based_output": true,
      "version": "1.0.0"
    },
    "gdal": {
      "algorithms": {
        "gdal:aspect": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Raster analysis",
          "has_known_issues": false,
          "help_url": null,
          "name": "Aspect",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "gdaldem"
          ]
        },
        "gdal:assignprojection": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Raster projections",
          "has_known_issues": false,
          "help_url": null,
          "name": "Assign projection",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "gdal_edit"
          ]
        },
        "gdal:buffervectors": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Vector geoprocessing",
          "has_known_issues": false,
          "help_url": null,
          "name": "Buffer vectors",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "ogr2ogr"
          ]
        },
        "gdal:buildvirtualraster": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Raster miscellaneous",
          "has_known_issues": false,
          "help_url": null,
          "name": "Build virtual raster",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "gdalbuildvrt"
          ]
        },
        "gdal:buildvirtualvector": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Vector miscellaneous",
          "has_known_issues": false,
          "help_url": null,
          "name": "Build virtual vector",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "vrt",
            "create"
          ]
        },
        "gdal:cliprasterbyextent": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Raster extraction",
          "has_known_issues": false,
          "help_url": null,
          "name": "Clip raster by extent",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "gdal_translate"
          ]
        },
        "gdal:cliprasterbymasklayer": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Raster extraction",
          "has_known_issues": false,
          "help_url": null,
          "name": "Clip raster by mask layer",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "gdalwarp"
          ]
        },
        "gdal:clipvectorbyextent": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Vector geoprocessing",
          "has_known_issues": false,
          "help_url": null,
          "name": "Clip vector by extent",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "ogr2ogr"
          ]
        },
        "gdal:clipvectorbypolygon": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Vector geoprocessing",
          "has_known_issues": false,
          "help_url": null,
          "name": "Clip vector by mask layer",
          "requires_matching_crs": true,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "ogr2ogr"
          ]
        },
        "gdal:colorrelief": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Raster analysis",
          "has_known_issues": false,
          "help_url": null,
          "name": "Color relief",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "gdaldem"
          ]
        },
        "gdal:contour": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Raster extraction",
          "has_known_issues": false,
          "help_url": null,
          "name": "Contour",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "gdal_contour"
          ]
        },
        "gdal:contour_polygon": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Raster extraction",
          "has_known_issues": false,
          "help_url": null,
          "name": "Contour Polygons",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "gdal_contour"
          ]
        },
        "gdal:convertformat": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Vector conversion",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert format",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "ogr2ogr"
          ]
        },
        "gdal:dissolve": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Vector geoprocessing",
          "has_known_issues": false,
          "help_url": null,
          "name": "Dissolve",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "ogr2ogr"
          ]
        },
        "gdal:executesql": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Vector miscellaneous",
          "has_known_issues": false,
          "help_url": null,
          "name": "Execute SQL",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "ogr2ogr"
          ]
        },
        "gdal:extractprojection": {
          "can_cancel": false,
          "deprecated": false,
          "group": "Raster projections",
          "has_known_issues": false,
          "help_url": null,
          "name": "Extract projection",
          "requires_matching_crs": false,
          "short_description": null,
          "tags": [
            "ogr",
            "gdal",
            "extractprojection"
          ]
        },
...
    },
    "slyr": {
      "algorithms": {
        "slyr:addlayersfrommxd": {
          "can_cancel": true,
          "deprecated": false,
          "group": "MXD documents",
          "has_known_issues": false,
          "help_url": null,
          "name": "Add layers from MXD to project",
          "requires_matching_crs": false,
          "short_description": "Adds layers from an MXD document to the current project, respecting their original symbology.",
          "tags": []
        },
        "slyr:avltoqml": {
          "can_cancel": true,
          "deprecated": false,
          "group": "AVL styles",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert AVL to QML",
          "requires_matching_crs": false,
          "short_description": "Converts an ESRI ArcInfo AVL file to a QGIS QML file",
          "tags": []
        },
        "slyr:convertannotations": {
          "can_cancel": true,
          "deprecated": false,
          "group": "Annotations",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert annotations (beta)",
          "requires_matching_crs": false,
          "short_description": "",
          "tags": []
        },
        "slyr:convertmxdanddatatoqgs": {
          "can_cancel": true,
          "deprecated": false,
          "group": "MXD documents",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert MXD/MXT to QGS and data to GPKG (beta)",
          "requires_matching_crs": false,
          "short_description": "Converts an MXD or MXT document file to a QGIS project file, and converts all referenced data to standard formats",
          "tags": []
        },
        "slyr:convertmxdtoqgs": {
          "can_cancel": true,
          "deprecated": false,
          "group": "MXD documents",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert MXD/MXT to QGS",
          "requires_matching_crs": false,
          "short_description": "Converts an MXD or MXT document file to a QGIS project file.",
          "tags": []
        },
        "slyr:convertpmftoqgs": {
          "can_cancel": true,
          "deprecated": false,
          "group": "PMF published maps",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert PMF to QGS",
          "requires_matching_crs": false,
          "short_description": "Converts a PMF document file to a QGIS project file.",
          "tags": []
        },
        "slyr:convertprojectdata": {
          "can_cancel": true,
          "deprecated": false,
          "group": "Data conversion",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert project data to GPKG (beta)",
          "requires_matching_crs": false,
          "short_description": "Converts all data referenced by the current project to standard formats",
          "tags": []
        },
        "slyr:convertsxdtoqgs": {
          "can_cancel": true,
          "deprecated": false,
          "group": "SXD documents",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert SXD to QGS (2D)",
          "requires_matching_crs": false,
          "short_description": "Converts an ArcScene SXD document file to a 2D QGIS project file.",
          "tags": []
        },
        "slyr:exporttojson": {
          "can_cancel": true,
          "deprecated": false,
          "group": "MXD documents",
          "has_known_issues": false,
          "help_url": null,
          "name": "Export document structure",
          "requires_matching_crs": false,
          "short_description": "Exports a JSON representation of the internal structure of an MXD (or LYR) document file.",
          "tags": []
        },
        "slyr:lyrtoqlr": {
          "can_cancel": true,
          "deprecated": false,
          "group": "LYR datasets",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert LYR to QLR",
          "requires_matching_crs": false,
          "short_description": "Converts an ESRI LYR file to a QGIS QLR file",
          "tags": []
        },
        "slyr:lyrtoqml": {
          "can_cancel": true,
          "deprecated": false,
          "group": "LYR datasets",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert LYR to QML",
          "requires_matching_crs": false,
          "short_description": "Converts an ESRI LYR file to a QGIS QML file (or files)",
          "tags": []
        },
        "slyr:lyrtostylexml": {
          "can_cancel": true,
          "deprecated": false,
          "group": "LYR datasets",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert LYR to QGIS style XML",
          "requires_matching_crs": false,
          "short_description": "Converts an ESRI LYR file to a QGIS style XML file",
          "tags": []
        },
        "slyr:stylefromlyr": {
          "can_cancel": true,
          "deprecated": false,
          "group": "LYR datasets",
          "has_known_issues": false,
          "help_url": null,
          "name": "Set style from LYR file",
          "requires_matching_crs": false,
          "short_description": "Sets a layer's settings and symbology from an ESRI LYR file",
          "tags": []
        },
        "slyr:styletogpl": {
          "can_cancel": true,
          "deprecated": false,
          "group": "Style databases",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert ESRI style to GPL color palette",
          "requires_matching_crs": false,
          "short_description": "Converts ESRI style database to a GPL format color palette file.",
          "tags": []
        },
        "slyr:styletoqgisxml": {
          "can_cancel": true,
          "deprecated": false,
          "group": "Style databases",
          "has_known_issues": false,
          "help_url": null,
          "name": "Convert ESRI style to QGIS style XML",
          "requires_matching_crs": false,
          "short_description": "Converts ESRI style database to a QGIS XML Style library",
          "tags": []
        }
      },
      "can_be_activated": true,
      "default_raster_file_extension": "tif",
      "default_vector_file_extension": "gpkg",
      "is_active": true,
      "long_name": "Converts ESRI Style and LYR files",
      "name": "SLYR",
      "supported_output_raster_extensions": [
        "tif",
        "gen",
        "bmp",
        "bt",
        "byn",
        "bil",
        "ers",
        "gpkg",
        "grd",
        "grd",
        "gtx",
        "img",
        "mpr",
        "lbl",
        "kro",
        "ter",
        "mbtiles",
        "hdr",
        "mrf",
        "ntf",
        "gsb",
        "grd",
        "pix",
        "map",
        "pdf",
        "xml",
        "pgm",
        "rsw",
        "grd",
        "rst",
        "sdat",
        "rgb",
        "ter",
        "vrt",
        "nc"
      ],
      "supported_output_table_extensions": [
        "gpkg",
        "shp",
        "000",
        "bna",
        "csv",
        "dgn",
        "dxf",
        "geojson",
        "geojsonl",
        "geojsons",
        "gml",
        "gpx",
        "gxt",
        "ili",
        "itf",
        "json",
        "kml",
        "ods",
        "sql",
        "sqlite",
        "tab",
        "txt",
        "xlsx",
        "xml",
        "xtf"
      ],
      "supported_output_vector_extensions": [
        "gpkg",
        "shp",
        "000",
        "bna",
        "csv",
        "dgn",
        "dxf",
        "geojson",
        "geojsonl",
        "geojsons",
        "gml",
        "gpx",
        "gxt",
        "ili",
        "itf",
        "json",
        "kml",
        "ods",
        "sql",
        "sqlite",
        "tab",
        "txt",
        "xlsx",
        "xml",
        "xtf"
      ],
      "supports_non_file_based_output": true,
      "version": "3.12.9 Beta 3"
    }
  },
  "qgis_code_revision": "5c8013df61",
  "qgis_version": "3.15.0-Master",
  "qt_version": "5.14.2"
}
```


qgis_process --help native:buffer --json

```

{
  "algorithm_details": {
    "can_cancel": true,
    "deprecated": false,
    "group": "Vector geometry",
    "has_known_issues": false,
    "help_url": null,
    "id": "native:buffer",
    "name": "Buffer",
    "requires_matching_crs": false,
    "short_description": null,
    "tags": [
      "buffer",
      "grow",
      "fixed",
      "variable",
      "distance"
    ]
  },
  "gdal_version": "3.0.4",
  "geos_version": "3.8.1-CAPI-1.13.3",
  "outputs": {
    "OUTPUT": {
      "description": "Buffered",
      "type": "outputVector"
    }
  },
  "parameters": {
    "DISSOLVE": {
      "default_value": false,
      "description": "Dissolve result",
      "is_advanced": false,
      "is_destination": false,
      "name": "DISSOLVE",
      "optional": false,
      "raw_definition": {
        "default": false,
        "description": "Dissolve result",
        "flags": 0,
        "help": null,
        "metadata": {},
        "name": "DISSOLVE",
        "parameter_type": "boolean"
      },
      "type": {
        "acceptable_values": [
          "1 for true/yes",
          "0 for false/no"
        ],
        "description": "A boolean parameter, for true/false values.",
        "id": "boolean",
        "metadata": {},
        "name": "Boolean"
      }
    },
    "DISTANCE": {
      "default_value": 10,
      "description": "Distance",
      "is_advanced": false,
      "is_destination": false,
      "name": "DISTANCE",
      "optional": false,
      "raw_definition": {
        "data_type": 1,
        "default": 10,
        "default_unit": 9,
        "description": "Distance",
        "flags": 0,
        "help": null,
        "max": 1.7976931348623157e+308,
        "metadata": {},
        "min": -1.7976931348623157e+308,
        "name": "DISTANCE",
        "parameter_type": "distance",
        "parent": "INPUT"
      },
      "type": {
        "acceptable_values": [
          "A numeric value"
        ],
        "description": "A numeric parameter representing a distance measure.",
        "id": "distance",
        "metadata": {},
        "name": "Distance"
      }
    },
    "END_CAP_STYLE": {
      "available_options": {
        "0": "Round",
        "1": "Flat",
        "2": "Square"
      },
      "default_value": 0,
      "description": "End cap style",
      "is_advanced": false,
      "is_destination": false,
      "name": "END_CAP_STYLE",
      "optional": false,
      "raw_definition": {
        "allow_multiple": false,
        "default": 0,
        "description": "End cap style",
        "flags": 0,
        "help": null,
        "metadata": {},
        "name": "END_CAP_STYLE",
        "options": [
          "Round",
          "Flat",
          "Square"
        ],
        "parameter_type": "enum"
      },
      "type": {
        "acceptable_values": [
          "Number of selected option, e.g. '1'",
          "Comma separated list of options, e.g. '1,3'"
        ],
        "description": "An enumerated type parameter.",
        "id": "enum",
        "metadata": {},
        "name": "Enum"
      }
    },
    "INPUT": {
      "default_value": null,
      "description": "Input layer",
      "is_advanced": false,
      "is_destination": false,
      "name": "INPUT",
      "optional": false,
      "raw_definition": {
        "data_types": [],
        "default": null,
        "description": "Input layer",
        "flags": 0,
        "help": null,
        "metadata": {},
        "name": "INPUT",
        "parameter_type": "source"
      },
      "type": {
        "acceptable_values": [
          "Path to a vector layer"
        ],
        "description": "A vector feature parameter, e.g. for algorithms which operate on the features within a layer.",
        "id": "source",
        "metadata": {},
        "name": "Vector Features"
      }
    },
    "JOIN_STYLE": {
      "available_options": {
        "0": "Round",
        "1": "Miter",
        "2": "Bevel"
      },
      "default_value": 0,
      "description": "Join style",
      "is_advanced": false,
      "is_destination": false,
      "name": "JOIN_STYLE",
      "optional": false,
      "raw_definition": {
        "allow_multiple": false,
        "default": 0,
        "description": "Join style",
        "flags": 0,
        "help": null,
        "metadata": {},
        "name": "JOIN_STYLE",
        "options": [
          "Round",
          "Miter",
          "Bevel"
        ],
        "parameter_type": "enum"
      },
      "type": {
        "acceptable_values": [
          "Number of selected option, e.g. '1'",
          "Comma separated list of options, e.g. '1,3'"
        ],
        "description": "An enumerated type parameter.",
        "id": "enum",
        "metadata": {},
        "name": "Enum"
      }
    },
    "MITER_LIMIT": {
      "default_value": 2,
      "description": "Miter limit",
      "is_advanced": false,
      "is_destination": false,
      "name": "MITER_LIMIT",
      "optional": false,
      "raw_definition": {
        "data_type": 1,
        "default": 2,
        "description": "Miter limit",
        "flags": 0,
        "help": null,
        "max": 1.7976931348623157e+308,
        "metadata": {},
        "min": 1.0,
        "name": "MITER_LIMIT",
        "parameter_type": "number"
      },
      "type": {
        "acceptable_values": [
          "A numeric value"
        ],
        "description": "A numeric parameter, including float or integer values.",
        "id": "number",
        "metadata": {},
        "name": "Number"
      }
    },
    "OUTPUT": {
      "default_value": null,
      "description": "Buffered",
      "is_advanced": false,
      "is_destination": true,
      "name": "OUTPUT",
      "optional": false,
      "raw_definition": {
        "create_by_default": true,
        "data_type": 2,
        "default": null,
        "description": "Buffered",
        "flags": 0,
        "help": null,
        "metadata": {},
        "name": "OUTPUT",
        "parameter_type": "sink",
        "supports_append": true,
        "supports_non_file_outputs": true
      },
      "type": {
        "acceptable_values": [
          "Path for new vector layer"
        ],
        "description": "A feature sink destination parameter.",
        "id": "sink",
        "metadata": {},
        "name": "Feature Sink"
      }
    },
    "SEGMENTS": {
      "default_value": 5,
      "description": "Segments",
      "help": "The segments parameter controls the number of line segments to use to approximate a quarter circle when creating rounded offsets.",
      "is_advanced": false,
      "is_destination": false,
      "name": "SEGMENTS",
      "optional": false,
      "raw_definition": {
        "data_type": 0,
        "default": 5,
        "description": "Segments",
        "flags": 0,
        "help": "The segments parameter controls the number of line segments to use to approximate a quarter circle when creating rounded offsets.",
        "max": 1.7976931348623157e+308,
        "metadata": {},
        "min": 1.0,
        "name": "SEGMENTS",
        "parameter_type": "number"
      },
      "type": {
        "acceptable_values": [
          "A numeric value"
        ],
        "description": "A numeric parameter, including float or integer values.",
        "id": "number",
        "metadata": {},
        "name": "Number"
      }
    }
  },
  "proj_version": "Rel. 6.3.2, May 1st, 2020",
  "provider_details": {
    "can_be_activated": true,
    "default_raster_file_extension": "tif",
    "default_vector_file_extension": "gpkg",
    "is_active": true,
    "long_name": "QGIS (native c++)",
    "name": "QGIS (native c++)",
    "supported_output_raster_extensions": [
      "tif",
      "gen",
      "bmp",
      "bt",
      "byn",
      "bil",
      "ers",
      "gpkg",
      "grd",
      "grd",
      "gtx",
      "img",
      "mpr",
      "lbl",
      "kro",
      "ter",
      "mbtiles",
      "hdr",
      "mrf",
      "ntf",
      "gsb",
      "grd",
      "pix",
      "map",
      "pdf",
      "xml",
      "pgm",
      "rsw",
      "grd",
      "rst",
      "sdat",
      "rgb",
      "ter",
      "vrt",
      "nc"
    ],
    "supported_output_table_extensions": [
      "gpkg",
      "shp",
      "000",
      "bna",
      "csv",
      "dgn",
      "dxf",
      "geojson",
      "geojsonl",
      "geojsons",
      "gml",
      "gpx",
      "gxt",
      "ili",
      "itf",
      "json",
      "kml",
      "ods",
      "sql",
      "sqlite",
      "tab",
      "txt",
      "xlsx",
      "xml",
      "xtf"
    ],
    "supported_output_vector_extensions": [
      "gpkg",
      "shp",
      "000",
      "bna",
      "csv",
      "dgn",
      "dxf",
      "geojson",
      "geojsonl",
      "geojsons",
      "gml",
      "gpx",
      "gxt",
      "ili",
      "itf",
      "json",
      "kml",
      "ods",
      "sql",
      "sqlite",
      "tab",
      "txt",
      "xlsx",
      "xml",
      "xtf"
    ],
    "supports_non_file_based_output": true,
    "version": null
  },
  "qgis_code_revision": "5c8013df61",
  "qgis_version": "3.15.0-Master",
  "qt_version": "5.14.2"
}
```

qgis_process run native:buffer --json --INPUT="/home/nyall/Downloads/curved_polys.gpkg" --DISTANCE=5 --OUTPUT="centroids.kml"

```

{
  "algorithm_details": {
    "can_cancel": true,
    "deprecated": false,
    "group": "Vector geometry",
    "has_known_issues": false,
    "help_url": null,
    "id": "native:buffer",
    "name": "Buffer",
    "requires_matching_crs": false,
    "short_description": null,
    "tags": [
      "buffer",
      "grow",
      "fixed",
      "variable",
      "distance"
    ]
  },
  "gdal_version": "3.0.4",
  "geos_version": "3.8.1-CAPI-1.13.3",
  "inputs": {
    "DISTANCE": "5",
    "INPUT": "/home/nyall/Downloads/curved_polys.gpkg",
    "OUTPUT": "centroids.kml"
  },
  "log": {},
  "proj_version": "Rel. 6.3.2, May 1st, 2020",
  "provider_details": {
    "can_be_activated": true,
    "default_raster_file_extension": "tif",
    "default_vector_file_extension": "gpkg",
    "is_active": true,
    "long_name": "QGIS (native c++)",
    "name": "QGIS (native c++)",
    "supported_output_raster_extensions": [
      "tif",
      "gen",
      "bmp",
      "bt",
      "byn",
      "bil",
      "ers",
      "gpkg",
      "grd",
      "grd",
      "gtx",
      "img",
      "mpr",
      "lbl",
      "kro",
      "ter",
      "mbtiles",
      "hdr",
      "mrf",
      "ntf",
      "gsb",
      "grd",
      "pix",
      "map",
      "pdf",
      "xml",
      "pgm",
      "rsw",
      "grd",
      "rst",
      "sdat",
      "rgb",
      "ter",
      "vrt",
      "nc"
    ],
    "supported_output_table_extensions": [
      "gpkg",
      "shp",
      "000",
      "bna",
      "csv",
      "dgn",
      "dxf",
      "geojson",
      "geojsonl",
      "geojsons",
      "gml",
      "gpx",
      "gxt",
      "ili",
      "itf",
      "json",
      "kml",
      "ods",
      "sql",
      "sqlite",
      "tab",
      "txt",
      "xlsx",
      "xml",
      "xtf"
    ],
    "supported_output_vector_extensions": [
      "gpkg",
      "shp",
      "000",
      "bna",
      "csv",
      "dgn",
      "dxf",
      "geojson",
      "geojsonl",
      "geojsons",
      "gml",
      "gpx",
      "gxt",
      "ili",
      "itf",
      "json",
      "kml",
      "ods",
      "sql",
      "sqlite",
      "tab",
      "txt",
      "xlsx",
      "xml",
      "xtf"
    ],
    "supports_non_file_based_output": true,
    "version": null
  },
  "qgis_code_revision": "5c8013df61",
  "qgis_version": "3.15.0-Master",
  "qt_version": "5.14.2",
  "results": {
    "OUTPUT": "centroids.kml"
  }
}
```

**Comment by m-kuhn** [comment]
I like.
I'd love to see something done on param side too

E.g.

```
qgis_process run native:buffer --json --params="{ INPUT:'/home/nyall/Downloads/curved_polys.gpkg', DISTANCE:5 OUTPUT:'centroids.kml' }"
```

or

```
qgis_process run native:buffer --json -- INPUT="/home/nyall/Downloads/curved_polys.gpkg" DISTANCE=5 OUTPUT="centroids.kml"
```

...

**Comment by m-kuhn** [comment]
If a parameter for a model / algorithm has the name `json` we already have a collision as soon as this pull request is merged.

**Comment by m-kuhn** [comment]
> If that's a problem one could require that `--json` is before `run`?

That would work for me. But it's the same for `--ellipsoid`, `--project_path`, ... already, so I wonder if it would be better to split off params in a new way.

**Comment by nyalldawson** [comment]
> Can the structure of the JSON be guaranteed for each stable release of QGIS? I don't mind interpreting it differently based on the QGIS version string but if this changes frequently I probably wouldn't be able to use it.

yes -- I'm happy to treat this as part of stable API and lock it down for the duration of 3.x!

**Comment by nyalldawson** [comment]
@m-kuhn 

> I'd love to see something done on param side too

I plan on doing this via stdin -- but I'll leave that to a follow up commit

**Comment by nyalldawson** [comment]
> If a parameter for a model / algorithm has the name json we already have a collision as soon as this pull request is merged.

Actually that's not the case -- the json switch has to be an exact "--json" string, not "--json=###" which would be required if a parameter was named json. There should be no breakage here.

**Comment by nyalldawson** [comment]
> That would work for me. But it's the same for --ellipsoid, --project_path, ... already, so I wonder if it would be better to split off params in a new way.

Yep -- those ones ARE potential clashes. But maybe we handle this through the json stdin option, e.g.

```
{
   'settings': {
        'ellipsoid': 'GRS80',
       'project_path': 'xxxx'
       'area_units': 5
      ...
},
'parameters': {
    'input' : 'xxxx',
    'ellipsoid': 'some other clashing parameter value',
    ...
   }
}
```
?

**Comment by nyalldawson** [comment]
For reference, there's a few other "global" settings we should expose alongside ellipsoid/unit settings:

- the method to use to handle invalid geometries (abort (current), skip, ignore)
- the method to use to handle transform errors (currently warnings are raised and the feature is skipped)
- default output encoding setting
- preferred vector/raster formats (used for some algorithms, e.g. split vector layer)

**Comment by m-kuhn** [comment]
> > That would work for me. But it's the same for --ellipsoid, --project_path, ... already, so I wonder if it would be better to split off params in a new way.
> 
> Yep -- those ones ARE potential clashes. But maybe we handle this through the json stdin option, e.g.
> 
> ```
> {
>    'settings': {
>         'ellipsoid': 'GRS80',
>        'project_path': 'xxxx'
>        'area_units': 5
>       ...
> },
> 'parameters': {
>     'input' : 'xxxx',
>     'ellipsoid': 'some other clashing parameter value',
>     ...
>    }
> }
> ```
> 
> ?

Or we just handle them like many other tools. (E.g. docker: positional (`docker run [run_args] executable [exec params]`, gdb: positional with extra param `gdb --args executable [exec params]`, git, bash built-ins: positional with dummy param: double dash `--`), IMHO easy to type and safe to use

**Comment by m-kuhn** [comment]
See #39349 - no reason to sidetrack any more

**Pull request merged**
