### PR TITLE
Different mAction icon, when action activated

### PR DESCRIPTION
**Pull request by signedav**
Change of the action icon on canvas scope when an action is active that do not have a specific icon
configured or associated. Before it still displayed the standard blue cogwheel with the arrow, so the user didn't saw if something will happens when clicking on it.

First the user does know a difference now if action selected or not and second and second there is less mixing up with the identify-icon right next to it. 

Looks like this:
action-icons

I preferred a normal yellow as color, but this dark yellow is much more assorts with the blue icon.

### CODE REVIEW

**Comment by nirvn** [comment]
I like the idea, it's a nice UX improvement. I'm not 100% sure about the yellow color. In QGIS (especially in the main window's toolbars), yellow represent selected features whereas feature actions aren't taking selected features into action.

What about using a green color instead?

**Comment by andreasneumann** [comment]
I don't have a strong opinion here - as long as it is clearly different from the "Identify features" tool. Either yellow is fine (as users also implictly select features prior to launching the action), or also green.

**Comment by DelazJ** [comment]
Actions do not necessarily require selection, do they? And there are different scopes based actions (feature, layer... ). I think we should keep the yellow for something that implies selection. No strong opinion however for the green.

**Comment by signedav** [comment]
screenshot from 2018-10-25 11-55-17
And it's green like the hope.

**Comment by NathanW2** [comment]
I like the green there.

**Comment by nirvn** [comment]
Good looking. No objection to settle on this.

**Pull request merged**
