### PR TITLE
use a QExplicitlySharedDataPointer for WFS shared data on the provider

### LINKED ISSUE #48465: [regression] New filter for duplicated WFS layer is also applied on source layer
### What is the bug or the crash?

Setting a new filter for a duplicated WFS layer affects also the source layer used for duplication. Also there's no filter symbol for the source layer, also all source features are still shown on the map.

### Steps to reproduce the issue

1. Add WFS connection https://geoservices.krzn.de/security-proxy/services/wfs_verb_grenzen
2. Add layer `gis:kreisgrenzen`
3. Rightclick on layer -> duplicate layer
4. Show feature count for both layers (if not already set)
5. Rightclick on new duplicated layer -> set filter -> `"KREIS" = 'Viersen'`
6. See error: Filter is applied also on source layer, see feature count and inspect attribute table. There's no filter symbol for the source layer, also all source features are still shown on the map.

### Versions

`master` (1eda8b21ae9c1b788807395ae41b615301cc7265) on Ubuntu 20.04.4 LTS

`3.24.2` on Windows 10

**No issue with 3.22.6 LTR on Windows 10**

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

According to `git bisect` this regressed in 3511158887cd331aa11af96a2385af87c4881bf7.

### PR DESCRIPTION
**Pull request by 3nids**
hence we can detach when setting the subset string since it's stored in the shared data

fixes #48465

### CODE REVIEW

**Comment by rouault** [comment]
As I raised in a previous comment, just detaching is probably not enough as the old and new instances of QgsWFSSharedData will share the same cache

**Comment by 3nids** [comment]
But detach is doing a deep copy
https://doc.qt.io/qt-5/qexplicitlyshareddatapointer.html#detach

Sorry if I am missing something.

**Comment by rouault** [comment]
> Sorry if I am missing something.

ok, I now see that before detaching we call QgsBackgroundCachedSharedData::invalidateCache() which removes the files of the cache and clear mCacheDbname, so the original and new QgsBackgroundCachedSharedData will have separate caches after detaching.

In case of layer duplication, this is probably a bit extreme, since it will invalidate the cache of the original layer. Probably that the right thing to do would be rather in handlePostCloneOperations to detach and do a QgsBackgroundCachedSharedData::invalidateCache(bDeleteFiles = false) that would skip the QFile::remove() calls done in it, but do all the rest.

**Comment by m-kuhn** [comment]
> In case of layer duplication, this is probably a bit extreme

Is this code executed during layer duplication?
The approach to detach when the subset string changes (and hence leaving any running iterators/other layers with unchanged subset untouched) sounds

**Comment by 3nids** [comment]
(if this is accepter, there a bit more code to write as we need to replace the `std::shared_ptr` by `QExplicitlySharedDataPointer` in a few places)

**Comment by rouault** [comment]
> Is this code executed during layer duplication?

Probably not, but I somehow wrongly assumed this PR was related as this was discussed recently

> The approach to detach when the subset string changes (and hence leaving any running iterators/other layers with unchanged subset untouched) sounds quite convincing to me.

yes, that makes sense. This PR LGTM

**Review by rouault — APPROVED** [review]

**Comment by pathmapper** [comment]
Just tried the fix and it's solving the regression for WFS reported in https://github.com/qgis/QGIS/issues/48465 🎉 

Some remarks:
The same issue as described in #48465 exists also for an OGC API Feature source, e.g. `https://ogc-api.nrw.de/inspire-us-kindergarten/v1`, so a similar fix might be needed there (maybe out of scope of this PR).

Didn't check if the issue exists also for _afs_, _mssql_ and _oracle_ provider which were also modified in https://github.com/qgis/QGIS/pull/46764/files (no sample service at hand to try it out).

**Comment by rouault** [comment]
I've continued this pull request in https://github.com/qgis/QGIS/pull/48998

**Pull request merged**
