### PR TITLE
Non-spatial layers shoudn't have a coordinate transform

### PR DESCRIPTION
**Pull request by gacarrillor**
## Description
Resolves a freeze for me when it tries to render non-spatial layers. 

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]
Looks good to me

**Comment by nyalldawson** [comment]
I'm curious as to how this eventuates. The fix is good, but that method shouldn't be called for non spatial layers in the first place..

**Comment by gacarrillor** [comment]
@nyalldawson It happens when we run a dialog from [Project Generator plugin](https://github.com/opengisch/projectgenerator/) for the second time! Let me know if you want to reproduce the issue to give you detailed indications.

**Comment by m-kuhn** [comment]
> The fix is good, but that method shouldn't be called for non spatial layers in the first place..

It was called somewhere within the rendering initialization.

**Comment by m-kuhn** [comment]
@gacarrillor can you verify what `non_spatial_layer.crs()` returns in your installation? I guess that should be an invalid crs, but to be sure...

**Comment by gacarrillor** [comment]
Right! Something strange happens there:

```
crs = my_geometryless_layer.crs()
crs.isValid() # True
crs.description() # WGS 84
```

**Comment by gacarrillor** [comment]
Could this be merged or closed?

**Comment by 3nids** [comment]
yes, this other PR was merged.
Thanks a lot for your contribution! Even if it didn't make it through, it was the starting point for a more global fix!

**Pull request closed without merging**
