### PR TITLE
[server] fix build without HAVE_SERVER_PYTHON_PLUGINS

### PR DESCRIPTION
**Pull request by 3nids**
no idea if it's the correct approach

### CODE REVIEW

**Comment by mbernasocchi** [comment]
probably needs more than just theese. adding `#include "qgsserverinterfaceimpl.h" also seems to help

**Comment by rldhont** [comment]
When the Server has been rewrite, `HAVE_SERVER_PYTHON_PLUGINS` can be removed around `QgsAccessControl *accessControl = serverIface->accessControls();` because `mAccessControls` returned by `accessControls()` is `nullptr` unless `HAVE_SERVER_PYTHON_PLUGINS`

Here is the code in `QgsServerInterfaceImpl`:

```
#ifdef HAVE_SERVER_PYTHON_PLUGINS
  mAccessControls = new QgsAccessControl();
  mCacheManager.reset( new QgsServerCacheManager() );
#endif
```

**Comment by mbernasocchi** [comment]
@rldhont so you are saying that we should just `#include "qgsserverinterfaceimpl.h"` because at the moment building with `WITH_SERVER_PLUGINS=OFF WITH_BINDINGS=OFF` does not work

**Comment by mbernasocchi** [comment]
@rldhont I get 
```
/home/marco/dev/QGIS/master/src/server/services/wms/qgswmsdescribelayer.cpp:136: error: invalid use of incomplete type ‘class QgsAccessControl’
       if ( accessControl && !accessControl->layerReadPermission( layer ) )
                                           ^~
In file included from ../src/server/services/wms/../qgsmodule.h:24:0,
                 from ../src/server/services/wms/qgswmsutils.h:26,
                 from ../src/server/services/wms/qgswmsdescribelayer.cpp:21:
```

**Comment by m-kuhn** [comment]
FYI: I started here https://github.com/qgis/QGIS/compare/master...m-kuhn:fixServerWithoutPlugins?expand=1 but gave up when I realized that there's much more left to do.

**Comment by rldhont** [comment]
I think so!

**Comment by mbernasocchi** [comment]
@rldhont including qgsserverinterfaceimpl.h in qgsmodule.h makes the compiler happy, but the linker is still unhappy as mentioned above. also have a look at #7514

**Review by rldhont — APPROVED** [review]
`HAVE_SERVER_PYTHON_PLUGINS` probably has to be added else where.

**Comment by 3nids** [comment]
is anyone willing to finalize this work?
@mbernasocchi @rldhont ?

otherwise, I'll close this isse

**Comment by rldhont** [comment]
@3nids I think this PR can be merged.
@mbernasocchi do some updates need to be done ?

**Comment by rldhont** [comment]
@3nids I hope to have time to verify `HAVE_SERVER_PYTHON_PLUGIN`

**Comment by mbernasocchi** [comment]
@rldhont yes this part is ok, but not enough yet. the linker will still complain, next week I'll try again

**Comment by mbernasocchi** [comment]
@rldhont in case you look into this, maybe related, also building with_gui=off breaks python support in server:`cmake /build/QGIS -GNinja -DWITH_STAGED_PLUGINS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DWITH_GRASS=OFF -DWITH_GRASS7=OFF -DSUPPRESS_QT_WARNINGS=ON -DENABLE_TESTS=OFF -DWITH_QSPATIALITE=OFF -DWITH_QWTPOLAR=OFF -DWITH_APIDOC=OFF -DWITH_ASTYLE=OFF -DWITH_DESKTOP=OFF -DWITH_SERVER=ON -DWITH_SERVER_PLUGINS=ON -DWITH_BINDINGS=ON -DWITH_QTMOBILITY=OFF -DWITH_QUICK=OFF -DWITH_3D=OFF -DWITH_GUI=OFF -DDISABLE_DEPRECATED=ON  -DSERVER_SKIP_ECW=ON -DWITH_GEOREFERENCER=OFF`

Couldn't load PyQGIS.<br>Python support will be disabled.</font><br><pre><br>Traceback (most recent call last):<br>&nbsp; File \"<string>\", line 1, in <module><br>ModuleNotFoundError: No module named 'qgis.gui'<br><br></pre>Python version:<br>3.6.7

**Comment by rldhont** [comment]
@dmarteau can you take a look ?

**Comment by dmarteau** [comment]
@rldhont About  PyQGIS disabled  when -DWITH_GUI=OFF, I do not think it is related to the original problem of this PR.

The main problem here come from the fact that wihthout  HAVE_SERVER_PYTHON_PLUGINS  then QgsAccessControl* is a forward declaration that do not resolve to any type. Usually, this should not lead to problem as long as  QgsAccessControl* should no be de-referenced nor any member accessed. Originally, this was an attempt to reduce the number of #ifdef/#endif directive in the code.

So one should be careful when introducing changes involving QgsAccessControl because any dereference or  member accesss will occur in compile/link error if not in HAVE_SERVER_PYTHON_PLUGINS  #ifdef/#endif directive.

**Comment by m-kuhn** [comment]
If utils.py or user.py is loaded, there are unguarded `import qgis.gui` in there (Compare to python/__init__.py, where the import is in a try-except block), that should be easy to check and fix on an existing installation.

However, have the problems reported in here ever been solved?

**Comment by dmarteau** [comment]
@m-kuhn  is your question about the HAVE_SERVER_PYTHON_PLUGINS problem ?

**Comment by m-kuhn** [comment]
> @m-kuhn is your question about the HAVE_SERVER_PYTHON_PLUGINS problem ?

Yes, https://github.com/qgis/QGIS/pull/7954#issuecomment-426272582 was the last message I've seen with respect to it.

**Comment by mbernasocchi** [comment]
@m-kuhn no it was never solved, it is still impossible to build qgis with those switches.

**Comment by dmarteau** [comment]
Mainly the errors that occurs when HAVE_SERVER_PYTHON_PLUGINS is not defined come from trying to access members of 'forward declaration' pointer.

**Comment by m-kuhn** [comment]
As far as I know it's not about runtime errors (by trying to access a pointer) but rather not being able to build at all.

**Comment by dmarteau** [comment]
I do not talk aboutr untime errors: If you try to compile a member access with a  forward declaration'pointer it fails.

**Comment by m-kuhn** [comment]
Ah sorry, I misread your statement.

> I do not talk aboutr untime errors: If you try to compile a member access with a forward declaration'pointer it fails.

Yes, that's exactly the problem introduced in https://github.com/qgis/QGIS/pull/7514, the question is more if a fix is still in the pipeline (https://github.com/qgis/QGIS/pull/7954#issuecomment-426273338).

**Comment by dmarteau** [comment]
I'm trying to fix the problem, I'm going to create a PR but it will need some discussion.

**Comment by m-kuhn** [comment]
Thanks a lot, if I can assist in the discussion, just ping me.

**Comment by dmarteau** [comment]
@m-kuhn Could you review https://github.com/qgis/QGIS/pull/9291 ?

**Pull request merged**
