### PR TITLE
[legend] improve multi-line label vertical placement & line spacing

### PR DESCRIPTION
**Pull request by nirvn**
Before:
untitled

Proposed:
untitled2

Is there _any_ reason not to want a nice middle vertical alignment here? :)

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , this is ready for you to review and (hopefully) merge :)

**Comment by nirvn** [comment]
So, fixing the vertical alignment was the kick I needed to handle a long-standing issue I've had with multi-line legend labels: the spacing in between line. With fonts / language relying on tall descent space (i.e. indic-based languages), the spacing was way too small.

Here's the current (top) vs. proposed (bottom):
untitled2

It also improves the spacing for latin-based languages with a number of fonts:

Current (left) vs. proposed(right):
untitled3

**Comment by NathanW2** [comment]
Nice work.

**Comment by nirvn** [comment]
@nyalldawson , looking into the code, I've realized that the multi-line spacing value (what used to be 1.5mm) was added to all labels - including single-line labels - due to a mistaken use of .end() instead of .last() in a couple of iterator loops.

I've fixed that, changed the default spacing values to match the (default) visual spacing to what we had before, and updated the expected test result images.

Note: the fix is required to be able to offer users the possibility to customize the spacing in-between lines, something I'm planning to address next when this PR is committed to master.

**Comment by nirvn** [comment]
@nyalldawson , it occurred to me last night that using last() was no appropriate, as that results in a string comparison where a non-last line could have the same string as the last (i.e. a QStringList {"2","3","4","3"} checking for last() would also match the 2nd line.

I've used end() - 1 instead.

**Comment by nyalldawson** [comment]
@nirvn Let's tackle this one at a time... I'm unsure about the change to vertical centering. I agree it looks better in your example, but looking at the change in https://github.com/qgis/QGIS/pull/3603/commits/15609f69c7b4aab578ecfc25f65450e6a9e363f1 to expected_legend_long_symbol_text I'm not sure that vertical centering is always going to be desired. How do you feel about exposing this choice to the user?

**Comment by nirvn** [comment]
@nyalldawson , I got overwhelmed here ;)

Ok, as for the expected_lgend_long_symbol_text, I was actually hoping you would address this :) I was split in half when it comes to this specific scenario (that is, symbol height < label height). 

What about reverting to the old behavior here, i.e. symbol being vertically centered to the label's first line? I'd rather avoid a [x] checkbox option here. The other scenario - symbol height > label height && multiline, the one I was hoping to address - IMO shouldn't require a setting, it looks unquestionably bad right now :)

**Comment by nirvn** [comment]
@nyalldawson , ok, here's a three-way comparison:

Current (left-most), current proposal which you have an issue with (middle), updated proposal which should make everyone happy 😄 (right-most):
untitled

The right-most proposal keeps the current rendering for symbol height < label height (which you are right to have pointed out is much better), while improves the symbol height > multi-line label. 

Looking at how the three-line label overflows into the next symbol's row in how QGIS currently renders things, I don't think we should have a checkbox here.

Thoughts?

**Comment by nirvn** [comment]
Closing this PR, will be superseded by two PRs to address the vertical-spacing and line-height separately.

**Pull request closed without merging**
