### PR TITLE
[Processing] GRASS Support multiple vector output file formats

### PR DESCRIPTION
**Pull request by ghost**
## Description
Add multiple vector output file formats with v.out.ogr:
* Supported output formats are based on Processing GdalUtils...
* ...which have been improved to support vector file formats discovering.
* 2 output options have been added: dsco and lco for v.out.ogr.
* v.external isn't the default import method (v.in.ogr used, thanks to @neteler).

New formats:
processinggrassoutputvectorformats

OGR output options:
processinggrassoutputvectoroptions

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
Nice

**Comment by nirvn** [comment]
For consistency, maybe place geopackage and shape file formats on top, followed by an alphabetical list of additional formats? That's what we now do elsewhere.

**Comment by neteler** [comment]
Nice, it is very important to avoid v.external being the default import method in favor of v.in.ogr (which got improved again in GRASS GIS 7.4.0)

**Review by alexbruy — COMMENTED** [review]
Looks good to me.

**Comment by alexbruy** [comment]
@medspx can you rebase? I will be happy to merge it after this

**Comment by alexbruy** [comment]
Superseded by #6996

**Pull request closed without merging**
