### PR TITLE
Test for write access mode for editing capabilities

### PR DESCRIPTION
**Pull request by mhugo**
Refers to ticket #11948

### CODE REVIEW

**Comment by m-kuhn** [comment]
It seems that the `ChangeAttributeValues` capability is already reported correctly now. With the demo dataset from the issue report it does not fail on save but it fails to update attributes even in the edit buffer (because of `ChangeAttributeValue` capability being reported as false).
So there seems to be another editing capability reported as true that turns the toggle edit button active.
So the question for me is, which editing capability is it and is the affected capability reported wrongly. In this case +1 for merging.
If not, I wonder if it's not rather the user interface that should be adopted to correctly handle the reported capabilities.

**Comment by mhugo** [comment]
Hi,
With the sample dataset, that's the "SequentialWrite" capability which is reported as true. But for this OGR driver, it is only possible to add new features on empty files, not when there is already some records. So, even if a the OGR driver level the capability is true, an actual opening in write mode may fail if the file is not empty.
So, QGIS side, we should only enable these capabilities if OGR succeeds to open the file in write mode (i.e. empty file)

**Comment by m-kuhn** [comment]
Sounds reasonable. Do you know if there are other OGR drivers affected by this as well?
I don't really know this side good enough to click the Merge button.

**Comment by jef-n** [comment]
There's also the problem that OGR datasource turn readonly when they get filtered (see [#11189](http://hub.qgis.org/issues/11189) & [Filtering a shapefile and editing](http://lists.osgeo.org/pipermail/qgis-developer/2014-September/034610.html)) - and that will still be an issue.  We would need to extent the capabilities (and add signals) to handle that.
But even it this PR not fully fixes [#11948](http://hub.qgis.org/issues/), it's still an improvement not to report any write capabilities, if the layer is opened readonly.

**Comment by m-kuhn** [comment]
Thanks @mhugo and @jef-n

**Pull request merged**
