### PR TITLE
More clear option text to "Modeless" dialog

### PR DESCRIPTION
**Pull request by SrNetoChan**
## Description

A bit more end-user-friendly wording for the option that makes the Data source manager a non-modal dialog.

### CODE REVIEW

**Comment by nirvn** [comment]
Is there a reason for this dialog to be modal these days?

**Comment by elpaso** [comment]
> Is there a reason for this dialog to be modal these days?

I've been using the modeless dialog since the day I created it and I haven't had any problems so far. 

I'm not sure if there are any windowing issues on other platforms than linux/KDE though.

**Comment by nirvn** [comment]
@nyalldawson , you read my mind.

**Comment by SrNetoChan** [comment]
Sounds good to me! Do you want me to open a ticket for that and close this pull request?

**Comment by nyalldawson** [comment]
Superseded by https://github.com/qgis/QGIS/pull/50146

**Pull request closed without merging**
