### PR TITLE
Ensure that non-spatial layers are never set as canvas layers

### PR DESCRIPTION
**Pull request by nyalldawson**
Refs https://github.com/qgis/QGIS/pull/6507

### CODE REVIEW

**Comment by m-kuhn** [comment]
Did you consider the option to do the filtering in `QgsMapSettings::setLayers`? I think the current one has some limitations on server, quick...

**Comment by nyalldawson** [comment]
>Did you consider the option to do the filtering in QgsMapSettings::setLayers? I think the current one has some limitations on server, quick..., no? 

Good point - I'll put the check there too. It could benefit scripts also.

**Comment by nyalldawson** [comment]
> Good point - I'll put the check there too. It could benefit scripts also.

Done

**Review by m-kuhn — APPROVED** [review]
Good job

**Pull request merged**
