### PR TITLE
Fix selective masking regression

### PR DESCRIPTION
**Pull request by mhugo**
## Description

Fix for regressions discussed in https://github.com/qgis/QGIS/pull/30747 and possibly in https://github.com/qgis/QGIS/issues/32791

Some regressions also existed in unit tests, which I fixed, but I am not sure why it happened : some recent changes in label placements ?

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by nyalldawson** [comment]
I had to update the test images recently - they seem very susceptible to labelling placement. Could they be updated to use centroid/fixed placement modes to avoid this?

**Comment by mhugo** [comment]
@nyalldawson Indeed, that seems better with a manual placement, thanks

**Comment by nyalldawson** [comment]
Thanks, that'll help a lot! (I've got more label placement engine tweaks inbound)

**Comment by nirvn** [comment]
I can confirm this PR fixes the canvas flashing (woupidou!) as well as the regression with non-Normal label blending.

Thanks for looking into those needed follow ups into your cool masking feature @mhugo .

**Review by nirvn — APPROVED** [review]

**Comment by mhugo** [comment]
@nirvn Thanks for your tests

**Comment by m-kuhn** [comment]
We just tested this on QField too where it fixes canvas flashes and missing labels.
Thanks @mhugo and @nirvn !

**Pull request merged**
