### PR TITLE
[bugfix] Crash when exporting (invalid) legend to qlr

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #18981 Save QLR crashes QGIS 3

This patch definitely prevents the crash but I'm not sure if
we should also introduce the same check in QgsLayerTree::isLayer
or even in QgsLayerTreeGroup::findLayers() or also when importing
a qlr that might lead to invalid layer (like in this
bug report).

### CODE REVIEW

**Comment by nyalldawson** [comment]
I think this fix is good, but I'd also like to see the check be done in QgsLayerTreeGroup::findLayers() in case this bug may be present elsewhere.

**Comment by nirvn** [comment]
@elpaso , commit 2f2221a led to this regression: https://issues.qgis.org/issues/19199

**Comment by elpaso** [comment]
Thanks. I'll have a look ASAP

**Comment by nirvn** [comment]
@elpaso , should we revert for now (to avoid shipping 3.2 with this regression), or will you be able to address this prior to June 22? :)

**Comment by elpaso** [comment]
I should make it in time. BTW my commit fixed a crash and this is not.

**Comment by nirvn** [comment]
@elpaso , that was fast :) cheers. 

Is there a way to add a test to safeguard the code from this specific regression?

**Comment by elpaso** [comment]
The regression was caused by the commit that you bisected.

For now I just reverted the offending commit and the regression is gone, the original bug targeted by this PR was indeed already fixed by my first commit: https://github.com/qgis/QGIS/pull/7195/commits/ec909b0aabb9ed66050130672b19af1c9c1f5338

**Pull request merged**
