### PR TITLE
Fix pasting linestring into polygon layer should auto convert to polygon

### PR DESCRIPTION
**Pull request by nyalldawson**
(And polygon->lines, lines->points, polygon->points, etc)

Fixes #21213

### CODE REVIEW

**Comment by chau-intl** [comment]
I didn't know that this worked in 2.x, but I think its both cool and convenient!

My concern is that it might be too clever for a _normal_ user?

**Review by luipir — APPROVED** [review]
approved from point of view of code... no strong idea as it's covenient or not as commented by @chau-intl . IMHO the implicit convertion makes sense

**Comment by nirvn** [comment]
+1. I can't see why pasting failure is a better UX than auto converting the features :)

**Comment by DelazJ** [comment]
> I didn't know that this worked in 2.x, but I think its both cool and convenient!

@chau-intl See the tip at https://docs.qgis.org/2.18/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#cutting-copying-and-pasting-features
@nyalldawson does this mean that the conversion is not only line <->polygon (as stated in the doc) but points can also be involved (and vice versa?)?

**Pull request merged**
