### PR TITLE
Add shadow rendering fixes

### PR DESCRIPTION
**Pull request by NEDJIMAbelgacem**
## Description
This PR includes bug fix and some small improvement to shadow rendering:
- Fix shadow rendering (fix light camera setting mistake)
- Add depth and shadow texture coordinates checking
- Improve performance by selecting front faces for forward pass and back faces for shadow pass

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'm curious - have you got a before/after pic available? I've never had much luck with shadows and am hoping this fixes things 👍

**Comment by nyalldawson** [comment]
@NEDJIMAbelgacem can we safely backport this one to 3.22?

**Comment by NEDJIMAbelgacem** [comment]
@nyalldawson here is a comparison with the latest commit:
Before:

https://user-images.githubusercontent.com/29183781/151873312-6bfc4204-92e9-49ca-8e02-35dc559e064a.mp4

After:
https://user-images.githubusercontent.com/29183781/151873404-77ff62a4-77a2-45c4-bd6f-652c2e83c166.mp4

**Comment by nyalldawson** [comment]
@NEDJIMAbelgacem 
Ahh that's much better! Those were the kinds of issues I've been seeing with the shadow 🎉

**Comment by nyalldawson** [comment]
@uclaros did you want to look over this one?

**Comment by uclaros** [comment]
> @uclaros did you want to look over this one?

I tested the changes and like the results!

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
