### PR TITLE
Backport of GDAL extractprojection reintroduction to 3.4 [needs-docs]

### PR DESCRIPTION
**Pull request by havatv**
## Description
Backport of pull request #8378 to 3.4
Fixes issue #20263, adds output parameters for the generated files and adds tests.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by DelazJ** [comment]
@havatv can you add a mention to remind to document this alg. Looks like its doc is not complete (eg, no output). See https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/gdal/rasterprojections.html#extract-projection. Thanks.

**Comment by havatv** [comment]
I did noticed that the documentation needs to be updated. I have it on my to-do list. Where would you like me to mention it?

**Comment by DelazJ** [comment]
@havatv  Better to use `Backport of GDAL extractprojection reintroduction to 3.4 [needs-docs]` that would instead automatically trigger a report. [needs-docs] and [feature] are special tags that generate an issue report in the doc repo.

**Comment by havatv** [comment]
Thanks.

**Comment by luipir** [comment]
tnx @havatv

**Pull request merged**
