### PR TITLE
Issue #39842 Identify plugin UI enhancement by moving "Help" button t…

### PR DESCRIPTION
**Pull request by imanhn**
…o top toolbar and merging QHBoxLayouts of "View" and "Mode"

## Description

[Replace this with some text explaining the rationale and details about this pull request]

### CODE REVIEW

**Comment by imanhn** [comment]
Do we have a linter for MSVC so I can use as pre-build process (I want to put it next to MOC).

**Comment by nirvn** [comment]
-1 to put the two combo box on same horizontal row. We actually moved away from that setup a while back because it was causing overly wide minimum width values for the panel on many localisations.

**Comment by imanhn** [comment]
I check it with right-to-left and it was fine. Still the values in combos have a lot of wasted space. which language do you believe could face a problem? 

Separating those combo boxes in to different QHBoxLayout is a waste of space, space that can be used by the Tree (features list).

**Comment by imanhn** [comment]
Hi Matthias (@m-kuhn ),

I was trying to fix some PR Check error and I rebased them to reduce commits history but I've been forced to pull from origin  and since I was in the middle of rebasing now @root676 changes are at this PR.

Is this gonna be a problem?

I can delete my fork and create a neat PR if this sounds helpful. Sorry to bother.

**Comment by nyalldawson** [comment]
@imanhn I think it'll be easier if you close this PR and re-open a new one with a clean branch. I'd suggest making one first with the help button change alone as that's an easy merge, and then following it up with a second pr with the combo box change (for wider discussion)

**Comment by nyalldawson** [comment]
(I'll close this PR for now in order to keep the growing PR queue cleaner!)

**Pull request closed without merging**
