### PR TITLE
use Ubuntu cosmic for base image

### PR DESCRIPTION
**Pull request by 3nids**
This will easily allow newer version of Qt but mainly SIP for auto build of the Python API docs.

WIP!

### CODE REVIEW

**Comment by 3nids** [comment]
@wonder-sk any about not finding Qt53DExtras?
https://travis-ci.org/qgis/QGIS/jobs/439317435#L5787

**Comment by wonder-sk** [comment]
Yeah since Ubuntu 18.10 getting QGIS 3D compiled takes few more CMake variables to set...

This could help: https://lists.osgeo.org/pipermail/qgis-developer/2018-October/054729.html

See also: https://github.com/qgis/QGIS/pull/7958

**Comment by 3nids** [comment]
thanks @wonder-sk

**Comment by 3nids** [comment]
self-reminder: don't forget release dockerfile

**Comment by 3nids** [comment]
two issues:
https://travis-ci.org/qgis/QGIS/jobs/439725936#L2176
https://travis-ci.org/qgis/QGIS/jobs/439725936#L2939

one issue at least seems related to GDAL:
* gdal_contour: fix GDAL 2.3 regression with fixed interval contouring that resulted in discontinuities in contour lines which should be fixed in 2.3.2 (already released but not in cosmic yet) see https://trac.osgeo.org/gdal/wiki/Release/2.3.2-News

**Pull request closed without merging**
