### PR TITLE
fix 3d.pyi install (followup da317dd8dea0)

### PR DESCRIPTION
**Pull request by jef-n**
```
$ find build -name "*3d*.pyi"
build/python/3d/build/_3d_p/_3d_p.pyi
```

From the nightlies:

```
-- Installing: /build/qgis-3.39.0+git20240903+b53968c771e+36jammy/debian/tmp/usr/lib/python3/dist-packages/qgis/_gui.so
-- Set runtime path of "/build/qgis-3.39.0+git20240903+b53968c771e+36jammy/debian/tmp/usr/lib/python3/dist-packages/qgis/_gui.so" to ""
CMake Error at python/cmake_install.cmake:134 (file):
  file INSTALL cannot find
  "/build/qgis-3.39.0+git20240903+b53968c771e+36jammy/debian/build/python/3d/build/3d_p/3d_p.pyi":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:69 (include)
```

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by jgrocha** [comment]
Hi @jef-n 

On my build, I don't get the `_3d_p.pyi` and so this PR breaks my `sudo cmake --build . --target install`.

I wrote the details on https://github.com/qgis/QGIS/pull/58534#issuecomment-2351835124

What is different in my setup?

**Comment by nyalldawson** [comment]
@jgrocha what version of sip are you using?

**Comment by nirvn** [comment]
I have the same issue, using sip 4.

**Comment by jgrocha** [comment]
> @jgrocha what version of sip are you using?

4.19.25

**Comment by jgrocha** [comment]
Ping @jef-n 

Is there anything we can do about this? Can we add an additional condition to `python/CMakeLists.txt` to both `3d_p.pyi` and `_3d_p.pyi`?

**Pull request merged**
