### PR TITLE
fix processing test in case data and tmp are in different filesystem

### PR DESCRIPTION
**Pull request by luipir**
## Description
Patch to fix test in case data and temp are in different filesystems
in this case, symlink is enough respect hard link

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by luipir** [comment]
@pblottiere this little path at least would fix my test fail due to my drive configuration.

**Comment by luipir** [comment]
@strk plese give a look to this patch and the reason why your test fails in other situations [1]... do you need to open and issue? 
[] https://github.com/qgis/QGIS/pull/5144

**Comment by strk** [comment]
Patch looks good to me.

**Comment by luipir** [comment]
@strk btw travis 2.18 and 2.18 fail on this test... seems something changed in gdal/ogr api?

======================================================================
FAIL: test_ogrLayerName (__main__.VectorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/qgis/QGIS/python/plugins/processing/tests/ToolsTest.py", line 81, in test_ogrLayerName
    self.assertEqual(name, 'a')
AssertionError: 'b' != 'a'

**Comment by strk** [comment]
Could be, the test checks for addressability of layers by index. @rouault ?

**Comment by luipir** [comment]
hmm @strk @rouault seems the error is in a uncorrect use of ogr apy here:
https://github.com/qgis/QGIS/blob/release-2_18/python/plugins/processing/tools/vector.py#L584
should be now:
ly = ds.GetLayerByIndex(layerid)
@alexbruy @volaya opinions?

but what I don't know is when this api is changed and what ogr version is using travis.

**Comment by rouault** [comment]
GetLayer() definition  is (and this hasn't changed in years)
```
    def GetLayer(self,iLayer=0):
        """Return the layer given an index or a name"""
        if isinstance(iLayer, str):
            return self.GetLayerByName(str(iLayer))
        elif isinstance(iLayer, int):
            return self.GetLayerByIndex(iLayer)
        else:
            raise TypeError("Input %s is not of String or Int type" % type(iLayer))
```

**Comment by luipir** [comment]
@rouault ha ok... I didn't find the api => so I don't understand why ProcessingToolTest started to fail :/

**Comment by luipir** [comment]
@strk ProcessingToolTest is failing, I can't understand the origin of the fail, it fail for any PR since:
https://github.com/qgis/QGIS/pull/5167 by @alexbruy  but that PR wasn't affecting that test => can you verify?

**Comment by luipir** [comment]
seems https://github.com/qgis/QGIS/pull/5176 give a more general fix of the failing test => I can close this PR

**Pull request closed without merging**
