### PR TITLE
Correct masking with SVG symbol and vector output 

### LINKED ISSUE #54926: Masking with SVG symbol doesn't work
### What is the bug or the crash?

When exporting to PDF and we want to use an SVG symbol to mask other symbols, it fails and no mask is applied

### Steps to reproduce the issue

1.Create a svg mask for a point layer
2. Apply mask to a line layer
3. Create a layout with a map
4. export to PDF
5. Line are not masked

### Versions

master, 3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

A fix is on its way

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #54926

We need to transform rendered mask QPainterPath to have the proper mask clipping path.

It was working for all others symbologies because we transform the symbol instead of transforming the painter

### CODE REVIEW

**Comment by nyalldawson** [comment]
@troopa81 

is there a vertical offset happening here?

image

**Comment by troopa81** [comment]
> It is there a vertical offset happening here?

I don't think so, I think it's just scaling at work. Here for instance the same svg scaled down in Inkscape with centers vertically and horizontally aligned. You observe the same thing

scaling

**Comment by andreasneumann** [comment]
For a perfect masking solution of more complex SVG symbols we would need to buffer rather then just scale the symbol outline. It is clear that the scaling approach has limitations here.

**Comment by troopa81** [comment]
> For a perfect masking solution of more complex SVG symbols we would need to buffer rather then just scale the symbol outline. It is clear that the scaling approach has limitations here.

You're completely right. Here it was just for the sake of the test and to have a masking symbol bigger/different so we can witness that everything works fine

**Comment by nyalldawson** [comment]
@troopa81 

> Here it was just for the sake of the test and to have a masking symbol bigger/different so we can witness that everything works fine

Ah -- got it! Sorry for the noise!

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
