### PR TITLE
follow-up refctoring settings for code editor

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@3nids do you think you could write up a summary of how we should all be handling settings now for the qgis-developer list (or even better, the qgis developer docs?) I must admit to being a bit lost in how we should be approaching these things now.

**Comment by 3nids** [comment]
it's already done here https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html#settings

**Comment by 3nids** [comment]
let me know if this could be clearer

**Comment by nyalldawson** [comment]
@3nids how about python guidelines?

**Pull request merged**
