### PR TITLE
treat PostgreSQL's "json" field type as string

### PR DESCRIPTION
**Pull request by rutsky**
Similar to #1890

### CODE REVIEW

**Comment by m-kuhn** [comment]
Should jsonp also be in there?

What would be great would be if it could directly be parsed into a data structure based on QVariantMap et al.

**Comment by rutsky** [comment]
@m-kuhn according to my tests `jsonp` is not covered by this `if`, probably condition `fieldTType == "b"` is not met for `jsonp`.

I would love to see JSON parsed and properly outputted in QGIS attributes tables (also being able to do queries on them would be great too), if this can be easily achieved and you can point me on how this can be done, please do so, I'll try to do it if I will have enough time.

**Comment by nyalldawson** [comment]
@rutsky QGIS master now natively supports arrays and hstore maps in the postgres provider, and has lots of expression functions for dealing with these. It may be relatively straightforward to adapt the current hstore handling to also handle json types now.

Are you likely to tackle this? Or should I merge this PR as is and at least get the text based conversion in place?

**Comment by rutsky** [comment]
@nyalldawson I'm not working with QGIS for some time and don't have time to work on this issue any more.

**Pull request closed without merging**
