### PR TITLE
Add a script that calls astyle.sh for every changed files

### PR DESCRIPTION
**Pull request by pvalsecc**
Just call scripts/astyle-changed.sh from anywhere in your clone's
directory. Takes every added or changed files regardless if they are
in the stagging area or not.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Yes please!!!

**Comment by NathanW2** [comment]
Yep!

**Comment by jef-n** [comment]
is there a difference to prepare-commit.sh - except that it works from anywhere, formats stuff that we didn't use astyle on before and doesn't show what was changed?

**Comment by pvalsecc** [comment]
Thanks @jef-n, I've not seen this one. Dropping the PR.

**Pull request closed without merging**
