### PR TITLE
[FEATURE] Allow easy styling of discrete rasters

### PR DESCRIPTION
**Pull request by nyalldawson**
## Description

This PR adapts the existing raster Paletted renderer to allow for easy styling of discrete raster layers, such as landcover or boolean rasters.

Currently, it is cumbersome to style these in QGIS, and users must resort to the pseudocolor renderer in "discrete" mode, and with manually added values. The Paletted raster renderer cannot be used unless the raster has an embedded color table.

With this PR, users can instead select the renamed "Paletted/Unique Values" renderer and click the "Add Unique Values" button to load all unique raster values from the layer. These are automatically assigned a color using the selected color ramp.

image

(The "Load from Layer" button is enabled only if the raster has an embedded color table, and clicking it will load the embedded color table for the current band)

Improvements include:
- unique value calculation is performed in a background thread to keep UI responsive for large rasters (or remote layers). The raster API calls for histogram/statistics now support cancellation/progress reports via QgsFeedback objects.
- use of a real model for the paletted raster renderer list. Classes can now be manually added. Supports multi-selection for deleting multiple classes at once, or for changing color/transparency/labels for multiple classes at once. The corresponding pixel value for each class can now be edited too. 
- color modification for a class no longer uses a modal blocking dialog when the style dock is used - allows immediate view of color changes! See https://www.youtube.com/watch?v=t3IaiU9kQqk&feature=youtu.be for an early demo. (...because modal dialogs are the enemy of cartography and @NathanW2 is a hero among cartographers for smashing this concept to dust).
- A new color ramp selector allows recoloring pixel classes
- Pixel classes can be drag and drop reordered
- Color palettes can be loaded from a text file (supports ESRI clr/gdal/grass color table formats)
- Color palettes can be saved to a .clr text file

## Sponsors

- Stéphane Henriod
- Satelligence (http://satelligence.com/)
- Bird's Eye View (https://www.birdseyeviewgis.com/)
- other anonymous backers

## Checklist
- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
Great work Nyall, and big thanks to all sponsors. I love how this started with an email on the dev mailing list and ended with sponsored feature addition. Yay to open source and collaboration.

Open question to all raster users: now that we have a read AND write paletted / unique value renderer, should we remove the singleband pseudocolor renderer's Exact interpolation mode? I'm pretty sure it's sole purpose was effectively to work around absence of a customizable paletted  renderer.

**Comment by nirvn** [comment]
@nyalldawson , for the sake of consistency, might be good to add a "Color ramp" label to the left of the color ramp widget, to mimic other renderers' UI.

**Comment by nyalldawson** [comment]
> for the sake of consistency, might be good to add a "Color ramp" label to the left of the color ramp widget, to mimic other renderers' UI.

Done

**Comment by nirvn** [comment]
K; as far as I'm concerned, this is good to go, no regressions spotted on my test build.

**Comment by gioman** [comment]
@nyalldawson Many thanks to  you and all the ones that supported this work! this was one of those things that we greatly missed in QGIS.

**Comment by m-kuhn** [comment]
👍

**Pull request merged**
