### PR TITLE
[browser] Correctly show drives inserted (or removed!) after QGIS launch

### PR DESCRIPTION
**Pull request by nyalldawson**
Adds a native platform interface for usb storage events, allowing native interfaces to send a signal when a USB storage device is inserted/removed. Implemented for Windows only.

Make the browser hook into this to correctly add/remove drive items as USB drives are added/removed. 

Fixes #14481, #9843

### CODE REVIEW

**Comment by nirvn** [comment]
There's a cross OS Qt-based library here: https://github.com/wang-bin/qdevicewatcher

Would it be worth relying on that instead?

**Comment by nyalldawson** [comment]
I don't really see this as a high priority outside of windows -- on OSX/Linux USB drives are mounted to a location already accessible. It's only on windows that you CAN'T access them without the drive item.

I think I'd rather stick with this simple approach then introduce another large external library of unknown code quality

**Comment by nirvn** [comment]
@nyalldawson , sounds good.

**Comment by Gustry** [comment]
Side note, it would be very nice to display network shared folders in the QGIS Browser too. (Samba, NFS...) I personally made a symlink in a homemade ~/mnt directory.

Indeed on Linux/Mac, everything is mounted somewhere on /, but the path is not well known.

For samba the link is something like:
`mnt/sig -> '/run/user/1000/gvfs/smb-share:server=192.168.179.5,share=sig/'`

screenshot from 2018-09-18 11-25-14

My 2 cents

**Comment by DelazJ** [comment]
@Gustry you mean something like https://issues.qgis.org/issues/16742, right?

**Comment by Gustry** [comment]
Yes exactly. Thanks for the ticket ;-)

**Pull request merged**
