### PR TITLE
[travis] Resurrect Processing grass and SAGA tests

### PR DESCRIPTION
**Pull request by nyalldawson**
(mostly - some failing ones are commented out). And fix a lot of identified issues as a result.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@3nids what do you think?

**Comment by 3nids** [comment]
Good job, +1 to merge

**Comment by m-kuhn** [comment]
I guess the modified `python/plugins/processing/tests/testdata/custom/circular_strings.gpkg` file is a side-effect of running the tests locally?

**Comment by nyalldawson** [comment]
@m-kuhn

Yes, I guess gpkg wasn't a suitable choice there. I'll find a other circular string format for those tests

**Comment by m-kuhn** [comment]
... or copy to a temporary location...

**Pull request merged**
