### PR TITLE
[Backport to queued_ltr_backports] Fix legend icon geom generator is involved

### LINKED ISSUE #33755: Wrong size of legend symbols when using Geometry generator symbology
Hello, 
I get really big symbols in the legend on a point layer with surface or line geometry generator when I choose categorized symbols.

For example : 
- I create a new point memory layer 
- I add a column "type"  (integer)
- For style, I choose categorized symbols on "type" column
- For symbols, I choose surface geometry generator (`buffer ($ geometry, 2)`)
- Then in legend I get really big symbols for each type.

I am working with QGIS 3.4.14 LTR on Windows 7 or 10.
I try with QGIS 3.10.1, I have the same behaviour.
Qgis_issue_categorized_symbols

### PR DESCRIPTION
**Pull request by troopa81**
Manual backport of #50200

Fixes #33755

### CODE REVIEW

**Comment by troopa81** [comment]
@elpaso As you approved the original PR, do you agree with the LTR backport ?

**Comment by nyalldawson** [comment]
@troopa81 can you rebase please?

**Comment by troopa81** [comment]
> @troopa81 can you rebase please?

Done

**Comment by troopa81** [comment]
@nyalldawson Can we merge ?

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
