### PR TITLE
Fix run script support for processing algorithms

### PR DESCRIPTION
**Pull request by nirvn**
## Description
This fix to QgisApp::runScript() function correctly detects processing algorithm python scripts, and launch the algorithm dialog.

This results in:
- drag n dropping a processing alg. python script onto the QGIS main window launches the algorithm
- selecting "run script" when right clicking on a processing alg. python script in the browser panel launches the algorithm

@nyalldawson , OK to backport this to 3.2?

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
Thinking about this drag and drop feature over lunch, I think we have a big security issue here, namely that people could be misled into dragging a malicious.py script file onto the canvas, and code would be executed arbitrarily without the user fully understanding what's happening.

I think we should either disable drag and drop altogether, or add a message box warning users of imminent code execution: "Warning: you are about to execute a python script, go ahead? [ yes ] [ no ]"

**Comment by elpaso** [comment]
@nirvn I'm not sure: people could be tricked to run `sudo rm -rf /` in a console too... and there is nothing much we can do about that ... but yes, a confirmation dialog might be the useful here, maybe with the option "[X] Don't ask me again"

**Comment by nirvn** [comment]
@elpaso , yeah, except the difference between the console (or the browser panel's right click "run script" action) and the drag-and-drop is that - IMHO - the latter looks possibly more "innocent" for the average user.

A spear phishing attack which would ask a user to open their python console and have them type in malicious commands is less likely to work than one that'd simply have the user drag and drop innocent-file-name.py :smile:

**Comment by nirvn** [comment]
@nyalldawson , PR updated with a security warning (which can't be switched off via a [x] don't show again checkbox.

IMHO, we'll need to backport this to 3.2, the security warning is needed there.

**Pull request merged**
