### PR TITLE
Properly quote the delimiter in the processing aggregate algorithm

### PR DESCRIPTION
**Pull request by suricactus**
If one tries to use the aggregate algorithm with `concatatenate` and puts single quotes as a delimiter, it causes a parse error when building the aggregate expression.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Looks good.
Can you add a test for this? Should be straightforward to do around here: https://github.com/suricactus/QGIS/blob/proper_quote_alg_aggr/tests/src/core/testqgsexpression.cpp#L2239 ?

**Comment by suricactus** [comment]
@m-kuhn I am afraid that this is not the right place to test it. This was a problem specific for the `QgsAggregateAlgorithm`, the aggregate expression function is working well.

Unfortunately I didn't find where is the test for `QgsAggregateAlgorithm`, I would love to add a testcase here.

**Comment by m-kuhn** [comment]
Ah yes. Sorry.
Look at the yaml files here https://github.com/qgis/QGIS/tree/master/python/plugins/processing/tests/testdata

**Review by m-kuhn — APPROVED** [review]
Yes sir, thanks for the tests

**Comment by suricactus** [comment]
@m-kuhn should we also backport this to 3.22 branch?

**Comment by m-kuhn** [comment]
As far as I can tell this only fixes things

**Comment by suricactus** [comment]
Thanks!

**Pull request merged**
