### PR TITLE
[FEATURE][API] New class QgsExifTools 

### PR DESCRIPTION
**Pull request by nyalldawson**
Contains utilities for retrieving the geotag from images and for setting an image's geotag.

Working with geotags (before this class!) is super-annoying and fiddly and relies on either parsing command line tools or depending on non-standard Python libraries which are not available everywhere, and often very difficult for users on certain platforms to get installed and working correctly.

With this class we have stable methods for geotag getting/setting which are universally available and can be used safely by plugins and scripts.

As background - yesterday I was trying to write a script which would take the coordinates from a point layer and apply them as geotags to a photo referenced in one of the columns in the table. Turns out this task was super annoying to do, especially because I had to do it in Windows and in a way which was portable and didn't require users to mess around with installing extra python packages manually. There's a lot of pre-made tools available for tagging images based on GPX files and time interpolation, but nothing I could find which worked directly with tables of coordinates/image paths. I briefly pondered writing a processing tool which would call out to external tools to manually apply the desired tags for each image, but honestly, the world needs less processing tools which rely on fragile subprocess commands, not more. So this was/is the solution -- providing a dependable, cross-platform way of working with image geotags.

If this PR is approved then I'll add a "geotag images" processing tool which exposes this functionality to Processing in a follow up PR.

Note: part of this PR is forward porting @manisandro's code from kadas-albireo and adapting to c++11/Qt5.

### CODE REVIEW

**Comment by rouault** [comment]
Are you aware that GDAL returns EXIF data for JPEG and TIFF images ?
```
$ gdalinfo data/albania.jpg 
Driver: JPEG/JPEG JFIF
Files: data/albania.jpg
Size is 361, 260
Coordinate System is `'
Metadata:
  EXIF_DateTimeDigitized=    :  :     :  :  
  EXIF_DateTimeOriginal=    :  :     :  :  
  EXIF_ExifVersion=0210
  EXIF_FlashpixVersion=0100
  EXIF_GPSLatitude=(41) (1) (22.91)
  EXIF_GPSLatitudeRef=N
  EXIF_GPSLongitude=(19) (55) (42.35)
  EXIF_GPSLongitudeRef=E
  EXIF_GPSVersionID=0x02 0x00 0x00 0x00
  EXIF_Make=
  EXIF_Model=
  EXIF_PixelXDimension=361
  EXIF_PixelYDimension=260
  EXIF_ResolutionUnit=2
  EXIF_XResolution=(96)
  EXIF_YResolution=(96)
```

**Comment by nyalldawson** [comment]
@rouault

Yes, we rely on that elsewhere in qgis. But there's no write support through gdal, is there?

**Comment by rouault** [comment]
>  But there's no write support through gdal, is there?

There's write support for EXIF in JPEG since GDAL 2.3.0 (on image creation, not on an existing image): see end of https://gdal.org/frmt_jpeg.html

**Comment by nyalldawson** [comment]
> There's write support for EXIF in JPEG since GDAL 2.3.0 (on image creation, not on an existing image): see end of https://gdal.org/frmt_jpeg.html

Ok, that's good to know.

I'm still inclined to push ahead with this PR for now, given that it's a lightweight dependency and it has benefits like supporting updating existing images in place (also since we don't require GDAL 2.3.0 yet).

**Pull request merged**
