### PR TITLE
[travis] fix grass7 plugin build by adding GRASS_PREFIX7

### PR DESCRIPTION
**Pull request by nirvn**
Travis builds should also have WITH_GRASS7=ON to insure the grass renderer symbology (et al) works. 

_Note: this PR should fail as it requires a follow up commit to 3b0486c; I'll add it to the PR after it initially fails to confirm the fix_

### CODE REVIEW

**Comment by nirvn** [comment]
@m-kuhn , success! The first commit enables travis to build the grass7 plugin.The second commit fixes the grass plugin build error, which travis will now be able to detect (wouhou).

**Comment by m-kuhn** [comment]
Thanks @nirvn 
CC @rduivenvoorde problem fixed and prevented to happen again by travis ;)

**Comment by rduivenvoorde** [comment]
@nirvn @m-kuhn thanks! .. my old problems disappeared, but now I have:

https://gist.github.com/rduivenvoorde/54decffaa2cc5ed39b270ea9efada3d7

Any idea?

**Comment by m-kuhn** [comment]
caused by qtermwidget which I think is an external dependency (copied into our code) with a horrible coding style.

**Pull request merged**
