### PR TITLE
[needs-docs] Refactor the New Shapefile dialog to mimic the GeoPackage sequence

### PR DESCRIPTION
**Pull request by DelazJ**
Follow-up https://github.com/qgis/QGIS/pull/5682#issuecomment-345994266. Review and advices welcome

newshapefile

### CODE REVIEW

**Comment by nirvn** [comment]
"Geometries with Z coordinate" -> "Include Z dimension"

**Comment by andreasneumann** [comment]
@DelazJ - thanks for these improvements.

Would it be possible to also address the issue of offering curve types? See also https://issues.qgis.org/issues/17594

Thanks for having a look at this issue as well - if possible ;-)

**Comment by m-kuhn** [comment]
Cool.
Adding icons to the point/line/polygon combobox would be a nice UX fix

**Comment by nirvn** [comment]
While we're here, let's change Line and Polygon to MultiLine and MultiPolygon.

**Comment by nyalldawson** [comment]
I wonder why there's no equivalent option for "Include M values" here... gdal supports them since 2.1, which is our minimum version.

**Comment by nyalldawson** [comment]
> I wonder why there's no equivalent option for "Include M values" here... gdal supports them since 2.1, which is our minimum version.

Actually support is all there behind the scenes - it's just missing the checkbox. I'll add it when this PR is merged.

**Comment by nirvn** [comment]
@DelazJ , great work here, thanks.

**Pull request merged**
