### PR TITLE
Adds new Icon for Data Manager

### PR DESCRIPTION
**Pull request by KentPorter-Boundless**
## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by KentPorter-Boundless** [comment]
miconadddata

**Comment by elpaso** [comment]
@KentPorter-Boundless thanks for the icon! 
Would you please add a snapshot of how it actually looks within context?

**Review by elpaso — CHANGES_REQUESTED** [review]
Sorry but this will not work: the easiest way would be to just replace the original icon `themes/default/mActionDataSourceManager.svg`
If your real intention was to give the new icon a new name you should: 
- remove the old icon from git
- find all string occourrences of the removed icon within the source code and replace them with the new icon name.

**Comment by nirvn** [comment]
While I like the shape, I'm not a fan of the tri-color arrangement. I would like to see a version of this icon which sticks to three shades of blue already established in all of our existing providers. 

In fact, I have on my to do list an item saying "remove yellow from geopackage provider" :)

**Comment by luipir** [comment]
@KentPorter-Boundless @elpaso or better git clone qgis and substitute the original mActionDataSourceManager.svg with the new one (maintaining the same name) and commit that.

**Comment by rouault** [comment]
@nirvn > I have on my to do list an item saying "remove yellow from geopackage provider" :)

Note: the yellow comes from the official icon: http://www.geopackage.org/. (although the one of the QGIS icon is more flashy than the one from geopackage.org). Anyway, this is just a remark; I don't care if the icon is modified

**Comment by elpaso** [comment]
@nirvn I'd be with you if it was another provider icon, but this is probably the most important icon in QGIS, for this reason I believe it's fine if it is more evident and visible than the others.

**Comment by luipir** [comment]
@nirvn I almost agree with @elpaso but also with you about a uniform style for providers (current PR is not a provider but the entry point for providers).
Is it possibile to create a style guide for provider icons as you specified "three shades of blue" ?

**Comment by luipir** [comment]
@KentPorter-Boundless is it possible to give a better description of the PR ading some snapshot showing the context when the icon is used?

**Comment by KentPorter-Boundless** [comment]
Got it. This was my first PR, and needless to say, it was less than optimal. I will re-clone the repo, substitute the original mActionDataSourceManager.svg with the new one maintaining the same name. I will also add a better description. My apologies. Going forward I will add PR per our guidelines and best practices.

**Comment by KentPorter-Boundless** [comment]
Hey guys, I'm going to close this pull request, and open another so I can set this up correctly.

**Pull request closed without merging**
