### PR TITLE
 NULL value absorbs others in some functions

### PR DESCRIPTION
**Pull request by DelazJ**
Because we sometimes forget that _NULL_ value can make function behave "weirdly", it could be nice to document this behavior
backport to 2.18?

### CODE REVIEW

**Comment by m-kuhn** [comment]
I wonder if this is actually a desirable behavior. Postgres ignores NULL values in max() calculations.

**Comment by rouault** [comment]
> I wonder if this is actually a desirable behavior. Postgres ignores NULL values in max() calculations.

I thought the same but it seems everyone behaves differently. For example Python2 min(1,2,None) returns None, but Python2 max(1,2,None) return 2. And Python3 returns ```TypeError: unorderable types: NoneType() < int()```

sqlite3 behaves weirdly:
```
sqlite> select min(1,2,NULL);

sqlite> select max(1,2,NULL);

```
so like QGIS, but
```
sqlite> create table foo(bar);
sqlite> insert into foo (bar) values (null);
sqlite> insert into foo (bar) values (1);
sqlite> insert into foo (bar) values (2);
sqlite> select min(bar) from foo;
1
sqlite> select max(bar) from foo;
2
```

**Comment by m-kuhn** [comment]
Pro ignore NULL:

* Postgresql behavior
* [Transact SQL documents the same as postgresql](https://docs.microsoft.com/en-us/sql/t-sql/functions/max-transact-sql)
* IMHO more often than not having max ignore NULLs is expected (admittedly a personal opinion)

Pro include NULL:
* Backwards compatibility, assuming people based their existing expressions consciously on this behavior

Other considerations:
* Expressions normally are based on SQL rather than Python - with all types of effects (compare 1-based indexes etc).
* Unconsisent behavior as in sqlite is a bad counselor ;)
* A duplicate function `max_with_null` or a named parameter `max(array, ignore_null=False)` may be introduced

**Comment by nyalldawson** [comment]
I'm all for following postgres here

**Comment by DelazJ** [comment]
If the functions behavior must change then it's over my skills. Should I open an issue report in Redmine?

**Comment by m-kuhn** [comment]
https://github.com/qgis/QGIS/blob/master/src/core/expression/qgsexpressionfunction.cpp#L416-L432

```
static QVariant fcnMax( const QVariantList &values, const QgsExpressionContext *, QgsExpression *parent, const QgsExpressionNodeFunction * )
{
  QVariant result;
  double maxVal = std::numeric_limits<double>::quiet_NaN();
  for ( const QVariant &val : values )
  {
    double testVal = val.isNull() ? std::numeric_limits<double>::quiet_NaN() : QgsExpressionUtils::getDoubleValue( val, parent );
    if ( std::isnan( maxVal ) )
    {
       maxVal = testVal;
    }
    else if ( !std::isnan( testVal ) )
    {
      maxVal = std::max( maxVal, testVal );
    }
  }

  if ( !std::isnan( maxVal ) )
    result = QVariant( maxVal );
  return result;
}
```

**Comment by DelazJ** [comment]
Should I close this?

**Comment by m-kuhn** [comment]
Superseded by #5946

**Pull request closed without merging**
