### PR TITLE
[processing][need-docs] In place editing triggers editing and select all

### PR DESCRIPTION
**Pull request by elpaso**
If the active layer is not editable, the executor will
try to switch editing on.

If there are no selected features, the executor will
select all features before running.

### CODE REVIEW

**Comment by DelazJ** [comment]
@elpaso does it mean that you no longer need to toggle editing a layer and have features selected before using that tool? Hence the icon is "always" actionable for vector (while it's currently disabled by default)?

**Comment by elpaso** [comment]
@DelazJ yes, there will be unique case in which the button is disabled: when there is no active vector layer in the legend.

**Comment by DelazJ** [comment]
Could you please add the [needs-docs] tag? Would help to fix the description I was writing until I faced [some misunderstandings](https://github.com/qgis/QGIS-Documentation/issues/3011#issuecomment-426353899). Thanks

**Comment by nyalldawson** [comment]
Tests well for me! The only thing I've noticed is this button:

image

Should change to "Modify All Features" if there's no selection in the layer

**Comment by elpaso** [comment]
@DelazJ @nyalldawson the last commit adds:
1. append layer name to dialog title
2. store active layer when dialog is created and use that one for all further operations

**Pull request merged**
