### PR TITLE
Assorted MinGW build work

### PR DESCRIPTION
**Pull request by manisandro**
- mingw-rsvg2 is not directly used by QGIS
- Fix mingw build with glibc-2.34 based rawhide docker image
- Fix authentication plugins name pattern to also handle MinGW library names on Windows

### CODE REVIEW

**Comment by nyalldawson** [comment]
@manisandro what's the status with this?

**Comment by manisandro** [comment]
@nyalldawson Took me a while to figure out it was failing due to clone3/glibc-2.34 [1]... The only available workaround for now appears to be to pass `--security-opt seccomp=unconfined` to docker run. CI should complete successfully now...

[1] https://www.gitmemory.com/issue/actions/virtual-environments/3812/889209453

**Comment by agiudiceandrea** [comment]
@manisandro I've tested this MinGW64 build on Windows 7 and it misses the Python support (`WARNING    Couldn't load Python support library: Cannot load library libqgispython`) probably due to the libpython3.10.dll missing dependencies (api-ms-win-core-*.dll).
In older MinGW64 builds using Python 3.9.4 the Python support is working without issues: libpython3.9.dll (mingw-python3-3.9.4-1.fc35) doesn't have the api-ms-win-core-*.dll dependencies.
It seems the change in the dependencies for the MinGW64 libpython changed since mingw-python3-3.9.5-1.fc35.
Is it possible to avoid these dependencies for libpython as in mingw-python3-3.9.4-1.fc35?

**Comment by manisandro** [comment]
@agiudiceandrea Python 3.10 dropped Windows 7 support. Sorry, there is no way around this...

**Comment by agiudiceandrea** [comment]
Thanks @manisandro, I know Python dropped Windows 7 support since 3.9.0, but I see that

- mingw-python3-3.9.4-1.fc35 doesn't have any api-ms-win-core-\*.dll dependencies and any api-ms-win-core-\*.dll dependencies
- python3-3.9.5 from OSGeo4W has only one api-ms-win-core-path-l1-1-0.dll dependency (which is simple to provide on Windows 7 systems) and a lot of api-ms-win-crt-*.dll (which are available by default on Windows 7)
- mingw-python3-3.9.5-1.fc35 has a lot of api-ms-win-core-*.dll dependencies and none api-ms-win-core-\*.dll dependencies

so I thought the api-ms-win-core-*.dll dependencies were related to some build procedure.

**Comment by agiudiceandrea** [comment]
Thanks @manisandro, I know Python dropped Windows 7 support since 3.9.0, but I see that

- mingw-python3-3.9.4-1.fc35 doesn't have any api-ms-win-core-\*.dll dependencies and any api-ms-win-crt-\*.dll dependencies
- python3-3.9.5 from OSGeo4W has only one api-ms-win-core-path-l1-1-0.dll dependency (which is simple to provide on Windows 7 systems) and a lot of api-ms-win-crt-*.dll (which are available by default on Windows 7)
- mingw-python3-3.9.5-1.fc35 has a lot of api-ms-win-core-*.dll dependencies and none api-ms-win-crt-\*.dll dependencies

so I thought the api-ms-win-core-*.dll dependencies were related to some build procedure.

**Comment by manisandro** [comment]
Unfortunately they are related to code added in python-3.10 which generates that dependency.

**Review by mhugent — APPROVED** [review]
Looks good to me

**Pull request merged**
