### PR TITLE
option to keep WFS dialog open after adding layer(s)

### PR DESCRIPTION
**Pull request by alexbruy**
Useful when you need to add multiple layers from different servers

### CODE REVIEW

**Comment by m-kuhn** [comment]
I didn't try this, so forgive me if the proposal does not make sense.

Would it be a possibility to make a button "Apply" and "Ok" instead of a checkbox?

**Comment by alexbruy** [comment]
I tried to follow existing approach, we already have checkbox in the Add PostGIS layer dialog.
In such dialogs we have "Add", "Close" and "Set Filter" buttons, not sure if "OK" and "Apply" will be right choise

**Comment by alexbruy** [comment]
Any objections for merging this?

**Comment by m-kuhn** [comment]
Ship it

**Pull request merged**
