### PR TITLE
Improve split lines with lines

### PR DESCRIPTION
**Pull request by bstroebl**

### CODE REVIEW

**Comment by m-kuhn** [comment]
The fix checks if the same layer is specified twice and avoids self-intersection, the test adds a new lines2 layer. Would it make sense to just check with the existing lines layer to test your just-provided fix?

**Comment by bstroebl** [comment]
Hi Matthias,
I thought the test should generally check the functioning of the algorithm and not just this particular fix. Normally you would run this with two different layers, therefore I added a second line layer. lines.gml is parameter 1 and lines2 is parameter 2. Besides that lines is not self intersecting thus running the algorithm with parameter 1 = lines & parameter 2 = lines would result in lines.

**Comment by m-kuhn** [comment]
You can also add two tests, one for the general case, one for the new case.

This will help to prevent us from fixing the same issue again if we end up refactoring this (in C++ or whatever way...)
If you also add a small comment about it on top of the test you will get a lot of good Karma :)

**Comment by bstroebl** [comment]
will redo the PR as I found another bug

**Pull request closed without merging**
