### PR TITLE
Fix unwanted side effect with QgsAccessControl filter cache

### PR DESCRIPTION
**Pull request by dmarteau**
Prevent leaking access control cache filter between
    requests.

## Description

On wms requests (GetMap/GetPrint) QgisAccessControl cache filter expressions  for reuse while processing the request. This cache is persistent during server execution and  filter's expressions  also apply to subsequent requests.

Such an example of unwanted side effect is illustrated in the implemented test: 
1. Execute a GetFeature WFS request without filter restriction
2. Execute a Getmap WMS with filter's restriction -> Filters are cached
3. Execute an unrestricted GetFeature WFS request again: If the cache is not cleared we got the result from applied filters from the previous requests which is definitively not what is expected.

## Fix

This PR implements `QgsAccessControl::unresolveFilterFeatures()` which clear the expression filter's cache. This method is called at the beginning of each requests for preventing side-effects from one request to another.

### CODE REVIEW

**Comment by rldhont** [comment]
@pblottiere the issue exists since https://github.com/qgis/QGIS/pull/3987 6 years ago.

**Review by elpaso — COMMENTED** [review]
LGTM, since you are here, would you please add some more information to the resolve/unresolve methods documentation? 

I must say (maybe it's just me) that "resolve" and "unresolve" does not seem clear, isn't it better to mention something like "cache" to make it clearer?

**Comment by rldhont** [comment]
@pblottiere do you remember why the method was named `resolveFilterFeatures` ?

**Comment by dmarteau** [comment]
>  must say (maybe it's just me) that "resolve" and "unresolve" does not seem clear

It's not clear but it's legacy,  renaming will be an API break. `unresolve` was simply named to indicate that it undo what `resolve` do.   `clearFilterCache` or similar could be better but loosing the the relation with  `resolve...`.

**Comment by elpaso** [comment]
> > must say (maybe it's just me) that "resolve" and "unresolve" does not seem clear
> 
> It's not clear but it's legacy, renaming will be an API break. `unresolve` was simply named to indicate that it undo what `resolve` do. `clearFilterCache` or similar could be better but loosing the the relation with `resolve...`.

That's why I asked to add some more details to the function documentation not to rename it.

Anyway, you could deprecate the resolve method and add a new one with a better name, that wouldn't be an API break.

**Comment by dmarteau** [comment]
Added details in `resolve`  and `unresolve` documentation.

**Review by elpaso — APPROVED** [review]

**Pull request merged**
