### PR TITLE
Symbol color variable for labeling

### PR DESCRIPTION
**Pull request by nyalldawson**
This adds new variables for @symbol_color and @symbol_angle for use in labelling. At render time, they will be filled with the matching value from the FIRST symbol rendered for the labelled feature (eg, for rule-based renderers, only the first match will be used for the variable values).

The @symbol_color variable can be used with data defined expression for label color (or buffer color, shadow color, etc) to return the matching color of the symbol used for rendering the current feature. This makes it really easy to match label colors to categorised/graduated class colors! (especially useful when combined with the set_color_part function)

@symbol_angle is possibly less useful (especially given that rotation for symbols and labels are in opposite directions! ;@ ), but it's easy enough to add and may be useful for someone.

Todo:
- add tests
- handle data defined colors/angles

### CODE REVIEW

**Comment by NathanW2** [comment]
nifty.

**Comment by nirvn** [comment]
Works nicely, and is most welcome.

On my build, the color is returned in HEX value, while most functions return an RGB value. Would it be possible to return an RGB value instead?

I'm thinking of writing a nice python function to test out whether a color is "dark" or "light" so I can use @symbol_color as an expression for the buffer color, and if( is_dark(@symbol_color) , '#FFFFFF', '#000000') as expression to define the label color.

**Comment by nirvn** [comment]
Something along the lines of what's explained here: http://www.nbdtech.com/Blog/archive/2008/04/27/Calculating-the-Perceived-Brightness-of-a-Color.aspx

**Comment by nirvn** [comment]
Teaser:
cooll

The label buffer uses the following expression: @symbol_color
The label color uses the following expression: if( color_part( @symbol_color, 'lightness') > 60, '0,0,0', '255,255,255' )

It'd be nice to have a darker() and lighter() function to refine the label color (ala QColor's darker and lighter ones). Instead of using black or white, it could render a darker (or lighter) variation of @symbol_color, that would be quite artful.

**Comment by m-kuhn** [comment]
Nice!

**Comment by nyalldawson** [comment]
Implemented a different way in an earlier commit

**Pull request closed without merging**
