### PR TITLE
Optimise memory provider

### PR DESCRIPTION
**Pull request by nyalldawson**
Previously, the memory provider would automatically recalculate the extent of the layer after new features are added by looping through the entire set of existing features and calculating the bounding boxes. This is very wasteful, as many code paths add features one-by-one, so with every new feature added to the provider every existing feature is iterated over. This caused memory layers to slow to a crawl after many features are added.

This commit improves the logic so that IF an existing layer extent is known, then it's updated on the fly as each individual feauture is added. Instead of looping through all features, we just expand the existing known extent with the added features bounds. If the extent isn't known, we just invalidate it when adding/deleting/modifying features, and defer the actual extent calculation until it's next requested.

Makes memory layers many thousands of magnitudes of orders faster when adding lots of features (e.g. when memory providers are used as temporary outputs in processing)

I've also swapped the provider to use a hash for feature storage instead of a map. This gives faster feature lookups, at the cost of unordered features. But no other provider guarantees that features are 
returned in the same order as added, so this is a safe trade off to make.

### CODE REVIEW

**Comment by m-kuhn** [comment]
LGTM

**Comment by nirvn** [comment]
"thousands of magnitudes of orders faster" sounds good ;)

**Comment by nyalldawson** [comment]
I've dropped the change to QHash - too many unit tests rely on consistent memory provider ordering and it's way too tedious to update these!

**Comment by nyalldawson** [comment]
Quick demo:

Before: https://youtu.be/AmRPd2zWSns (couldn't be bothered waiting for this to finish - it gets exponentially slower, so you can imagine how much longer it will take...)
After: https://youtu.be/G3yzydvDtz0

**Comment by m-kuhn** [comment]
Good catch.

**Comment by gioman** [comment]
> Quick demo:
is the dissolve algorithm usable so I can test it (with large and complex datasets) against other methods (like ogr2ogr)?

**Comment by nyalldawson** [comment]
> is the dissolve algorithm usable so I can test it (with large and complex datasets) against other methods (like ogr2ogr)?

A native c++ one is coming in https://github.com/qgis/QGIS/pull/4702

**Pull request merged**
