### PR TITLE
Update VoronoiPolygons.py

### PR DESCRIPTION
**Pull request by havatv**
First commit: Width and height for buffer were mixed up.  Simple fix.
Second commit: Fix to eliminate problems when buffer is used.  Should fix some reported issues with this processing algorithm.

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by havatv** [comment]
I have now done some heavier modifications to avoid problems when buffer is specified.  I have done a rather trivial fix by eliminating the handling of the "buffer" in the clip_voronoi and clip_line functions.  Instead I have just modified the extent before calling clip_voronoi (I have also removed the extra parameters to these functions).  This seems to work well for my test dataset.

**Comment by nyalldawson** [comment]
Nice work @havatv ! 

Your latest PR has tripped the existing unit test - see the end of https://dash.orfeo-toolbox.org/viewTest.php?onlyfailed&buildid=328229 . Can you verify if the new result or old result is correct please?

**Comment by havatv** [comment]
Travis fails because python/plugins/processing/tests/testdata/expected/voronoi_buffer.gml is created with the buffer bug.  It is easy to see that the current voronoi_buffer.gml is wrong by comparing the geometries to python/plugins/processing/tests/testdata/expected/voronoi.gml and python/plugins/processing/tests/testdata/points.gml.
I have uploaded a modified voronoi_buffer.gml that reflects the new (and hopefully correct) behaviour).

**Comment by havatv** [comment]
I did not update the voronoi_buffer.gfs file, since the points in the points.gml file have a square (8 by 8) extent (so it is not affected by one of the buffer issues that were fixed - mixing x and y).

**Comment by nyalldawson** [comment]
Thank you!

**Pull request merged**
