### PR TITLE
Update mActionOpenEdited icon using the edited status pencil

### PR DESCRIPTION
**Pull request by DelazJ**

### CODE REVIEW

**Review by elpaso — APPROVED** [review]

**Comment by DelazJ** [comment]
nothing that I need to do, bot.

**Comment by nirvn** [comment]
@DelazJ , what's the objective of this change?

**Comment by DelazJ** [comment]
@nirvn image is usually used to toggle the edit state of a layer whereas image is displayed when the layer is dirty, ie it has features being edited. I think that the tool to open a table and preview the features being edited is better served with the latter icon on it  than the former (hence image  --> image)

**Comment by nyalldawson** [comment]
My concern is that the orange version is heavily associated with a "risk" to users -- that orange means "watch out, you've got things to pay attention to" vs the neutral yellow icon. So my personal opinion is that the yellow icon is more suitable for an action which doesn't actually run any risk of data loss.

**Comment by nirvn** [comment]
Had similar concerns here. I'd prefer we need change the icon.

**Comment by DelazJ** [comment]
OK. Closing then.

**Pull request closed without merging**
