### PR TITLE
[processing] New algorithm "Add X/Y fields to layer"

### PR DESCRIPTION
**Pull request by nyalldawson**
Adds X and Y (or latitude/longitude) fields to a point layer.
The X/Y fields can be calculated in a different CRS to the
layer (e.g. creating latitude/longitude fields for a layer in
a project CRS).

Sponsored by SMEC/SJ

### CODE REVIEW

**Comment by nirvn** [comment]
Looking good.

**Comment by nyalldawson** [comment]
@nirvn is that an approval to merge?

**Comment by nirvn** [comment]
Yep.

**Comment by Gustry** [comment]
Nice addition. I often need to do that in my current organization but in DMS format. It would have be nice to have this option too, even if I understand it's adding complexity to the UI and only useful for geographic CRS.

**Pull request merged**
