### PR TITLE
azure pipelines: output on failure

### PR DESCRIPTION
**Pull request by m-kuhn**
## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by nyalldawson** [comment]
Thank you!!

**Comment by m-kuhn** [comment]
Hmmm... that doesn't help anything...

@jef-n any idea how to get to this output? Is windows also overwriting environment variables during tests?

**Comment by nyalldawson** [comment]
I suspect we also need the verbose mode switch passed to ctest -- but I can't see how that can be done (there's no variable for this one)

**Comment by jef-n** [comment]
> I suspect we also need the verbose mode switch passed to ctest -- but I can't see how that can be done (there's no variable for this one)

Not sure why it works on the nightlies - configuration should be almost the same and doesn't need CTEST_OUTPUT_ON_FAILURE either.   Trying CTEST_USE_LAUNCHERS.

**Pull request closed without merging**
