### PR TITLE
Add some utils functions for QgsPointV2 (distance3D, midpoint)

### PR DESCRIPTION
**Pull request by lbartoletti**
Just some utils functions.

I suggest to add 3D distance between two points into QgsPointV2 class. But, maybe we also need to clarify usage of sqrDistance, one method is in QgsPointV2 and an other in QgsGeometryUtils.

Midpoint will be used for some CAD method.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Looks good! Only thing I'm not sure about is the midpoint function. To me this is quite specialised and doesn't belong in QgsPointV2, and would better fit in QgsGeometryUtils.

**Comment by nyalldawson** [comment]
Thanks! I just pushed a change exposing QgsGeometryUtils to python, can you add this new method to the bindings too?

**Comment by lbartoletti** [comment]
Yes, of course. Thanks

**Comment by nyalldawson** [comment]
On the contrary - thank YOU! It's great to see well tested implementations of these handy functions being added to core.

**Comment by nyalldawson** [comment]
@lbartoletti not sure if you're aware of it, but there's a script which handles indentation and formatting automatically which should be run for each commit - see https://www.qgis.org/en/site/getinvolved/development/qgisdevelopersguide/codingstandards.html#indentation

That's what's leading to the formatting test failure

**Comment by nyalldawson** [comment]
Manually squashed and merged in https://github.com/qgis/QGIS/commit/e851b68c5371ebaec723f9315754f4d77fce7125 and https://github.com/qgis/QGIS/commit/3703bf7396ec955eb4a5b1e74cac023992f89429

**Pull request closed without merging**
