### PR TITLE
move function map to hstore into QgsHstoreUtils

### PR DESCRIPTION
**Pull request by Gustry**
Because it's useful in the API

Tests are already covered with the qgs expression 

CC @nirvn

### CODE REVIEW

**Comment by nyalldawson** [comment]
> Tests are already covered with the qgs expression

Can you please copy these to their own test suite? I don't think it's good practice to rely on higher level classes to test lower level functionality like this.

**Comment by nyalldawson** [comment]
Isn't it https://dash.orfeo-toolbox.org/viewBuildError.php?type=1&buildid=339074 ?

**Comment by Gustry** [comment]
Where did you get this link?
If  I go on travis from this here, I land on this link: https://travis-ci.org/qgis/QGIS/jobs/444848610#L1270 and it goes to a white page.

**Comment by nyalldawson** [comment]
There's something broken in dash blocking the filtering required for that direct link. I just go to https://dash.orfeo-toolbox.org/index.php?project=QGIS and look for the build manually.

**Pull request merged**
