### PR TITLE
Fix slow loading of PostgreSQL layers

### PR DESCRIPTION
**Pull request by wonder-sk**
This fixes a big performance issue when loading projects with PostgreSQL layers. In the last stage of project loading, code in QgisApp would run code to resolve broken layer dependencies, which in turn tried to find out best edit widget for all columns of all layers, and the enumeration widget tried to figure out all enum values, doing two SQL calls for each column for each layer.

We know what are types of columns when loading a layer, so enumValues() can leave early without doing the excessive queries when it's not necessary.

Testing on a real world QGIS project with 300+ layers (but not all PostgreSQL):
- before: ~35 minutes to load / ~8K PostgreSQL queries
- after: ~10 minutes to load / ~2K PostgreSQL queries

Also adds the time of resolution of broken layers / assignment of edit widgets to the project load timing, so that it shows up in timing.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Nice optimisation!

> which in turn tried to find out best edit widget for all columns of all layers

Why are we doing this when loading projects anyway? I can understand doing it when adding a new layer to a project, but when loading we should always be using the edit widget config stored in the project itself 🤔

**Comment by wonder-sk** [comment]
> Why are we doing this when loading projects anyway? I can understand doing it when adding a new layer to a project, but when loading we should always be using the edit widget config stored in the project itself

I was also confused by that, why it is happening on project load. But apparently field edit widget configuration can stay undefined in a saved project file - I can see many occurrences of this in my testing project:

```xml
        <field configurationFlags="None" name="dataset">
          <editWidget type="">
            <config>
              <Option/>
            </config>
          </editWidget>
        </field>
```

**Review by nyalldawson — APPROVED** [review]

**Comment by weca-theo** [comment]
I've been doing some QGIS project load comparison tests, as seen in: https://github.com/qgis/QGIS/pull/53069#issuecomment-1611688827

To then compare the number of SQL queries, I've compared 3.32.0 with 3.30.3. Both have the SQL query logger debug tool. For the 3.32.0 test, I've used a qgz file _saved using_ 3.32.0. Otherwise, both qgz files are the same, with around 100 remote PostgreSQL layers hosted on Azure.

3.30.3: **1070** SQL queries

3.32.0: **1188** SQL queries.

So not much difference in amount of SQL queries being fired, and as seen in the link, not much difference in terms of project load time.

**Comment by weca-theo** [comment]
Ok so after running some tests on QGIS 3.32.0, I see no difference in project load time. In previous versions, the bulk of the SQL call bloat was due to excessive amounts of these two SQL calls on layers which have `<editWidget type="">` against them in the .qgz xml:

`"SQL": "SELECT domain_name, domain_schema FROM information_schema.columns WHERE table_name='example_table_name' AND column_name='example_column_name'"`
and
`"SQL": "SELECT typtype FROM pg_type WHERE typname='example_data_type'"`

In 3.32.0, these queries have disappeared, but have been replaced by other excessive SQL queries in the shape of numerous:

`SELECT postgis_version()` (the PostGIS version should only be called once surely? If the data is in the same database).
`SELECT postgis_geos_version(), postgis_proj_version()`
`SELECT has_schema_privilege(n.oid, 'usage') AND has_table_privilege(t.oid, 'select') AND has_table_privilege(l.oid, 'select') FROM pg_namespace n, pg_class t, pg_class l WHERE n.nspname = 'topology' AND t.relnamespace = n.oid AND l.relnamespace = n.oid AND t.relname = 'topology' AND l.relname = 'layer'"`
`SELECT has_table_privilege(c.oid, 'select') AND has_table_privilege(f.oid, 'select') FROM pg_class c, pg_class f, pg_namespace n, pg_extension e WHERE c.relnamespace = n.oid AND c.relname = 'pointcloud_columns' AND f.relnamespace = n.oid AND f.relname = 'pointcloud_formats' AND n.oid = e.extnamespace AND e.extname = 'pointcloud'`

and more combinations of `SELECT has_schema_privilege` and `SELECT has_table_privilege` (these are the worst offenders).

**Comment by strk** [comment]
I think it's a problem with connection snot being reused from the pool. The version functions should be called only once per connection. Either the connection are kept busy or they are released too early or the connection pooling is defective.

**Comment by weca-theo** [comment]
> I think it's a problem with connection snot being reused from the pool. The version functions should be called only once per connection. Either the connection are kept busy or they are released too early or the connection pooling is defective.

totally thought connection 'snot' was a thing. Then I realised it's a typo 😆 

Anyway, is there anything that can be done to fix this?

**Comment by gioman** [comment]
> I've been doing some QGIS project load comparison tests, as seen in: [#53069 (comment)](https://github.com/qgis/QGIS/pull/53069#issuecomment-1611688827)

Also see my quick and dirt test: https://github.com/qgis/QGIS/pull/53069#issuecomment-1618710752 rather than an improvement I see a regression, But maybe this patch is not related to the project parallel loading one.

**Pull request merged**
