### PR TITLE
[processing] consider destination params as outputs when defining scripts

### PR DESCRIPTION
**Pull request by volaya**
## Description

Now it is not possible to define a script with, for instance,  just a feature sink, since that is not understood as an output by the script parser (although it behaves as such)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by NathanW2** [comment]
@volaya  Thanks.  Good find.

**Comment by nyalldawson** [comment]
Good catch! There's unit tests for the alg decorator, could you add this too?

**Comment by volaya** [comment]
@NathanW2, I am trying to document this way of writing Processing scripts and test it, provide examples, etc. If there is anything that you know it's missing in there that you would like me to work on, just let me know. This is a great feature, and I think it should be robust and well documented

**Comment by volaya** [comment]
@nyalldawson Test added

**Comment by nyalldawson** [comment]
Thanks!

If I can make a suggestion: one thing which is missing here is the ability to create algorithms which belong to a custom provider, instead of the default script provider. To me this is the biggest limitation with the decorator approach, but I'm sure it's solvable! I'd just like to see us work this one out before widely publicizing the new API, just in case we need to break it...

**Comment by NathanW2** [comment]
Can we just have a keyword arg to the @alg function for provider="name"?

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@volaya 

I should also add - I plan on expanding the recently resurrected "export model as python" functionality to have an option to also export the model as a decorated algorithm (wording to be refined!). I think we should also do this for the "Create script from template" action, and have a second template for the "simple" decorated approach.

**Pull request merged**
