### PR TITLE
Bugfix gh38755 expose project setinstance

### LINKED ISSUE #38755: Server API: current project is not settable anymore
See https://github.com/qgis/QGIS/pull/38488 for the discussion.

This bug affects all maintained branches!

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #38755

Needs forward porting to all active branches

### CODE REVIEW

**Comment by nyalldawson** [comment]
I realise this is a regression fix, but it also makes me nervous in that a plugin calling this (outside of server) will cause major breakage to qgis app. Is there any alternative approach?

**Comment by elpaso** [comment]
I expected this objection but I don't really see a big issue here, the advantage is that it adds some more flexibility to the singleton management, that IMO should eventually disappear completely (QGIS 4 maybe?).

I though about exposing it through a server specific API (`QgsServer::setProjectInstance()`?) but it doesn't really belong there: it is for server consumption but who knows: there might be other standalone scripts not related to serve that could benefit of that API.

Another alternative is expose it through the config cache with an other optional argument to `QgsConfigCache` `const QgsProject *project( const QString &path, QgsServerSettings *settings = nullptr )` or with a new method.

**Comment by dmarteau** [comment]
> there might be other standalone scripts not related to serve that could benefit of that API.

It might the best alternative, since restoring the setInstance call in the QgsConfigCache only does not solve the issue:  preventing to set the singleton breaks other behaviors (like expression evaluation) and has an impact on every python scripts that might use it.

 > that IMO should eventually disappear completely (QGIS 4 maybe?).

+1

**Comment by nyalldawson** [comment]
If you're going to expose it, please add a:

    \warn calling this method can have serious, unintended consequences, including instability, data loss and undefined behaviour. Use with extreme caution!

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Fixes regression introduced in LTR => immediate merge

**Pull request merged**
