### PR TITLE
[core] Rely on QgsColorUtils encoding/decoding to handle CMYK

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR migrates non-expression uses of QgsSymbolLayerUtils::{encodeColor,decodeColor} functions to the QgsColorUtils::{colorToString,colorFromString} equivalents, with the latter supporting CMYK saving/restoring.

### CODE REVIEW

**Review by troopa81 — COMMENTED** [review]
Shall we not deprecate the QgsSymbolLayerUtils methods encodeColor/decodeColor ?

**Comment by nirvn** [comment]
@troopa81 , yeah, planning to after addressing color handling within expressions in a separate PR.

**Review by troopa81 — APPROVED** [review]

**Comment by nicogodet** [comment]
Hi @nirvn, this PR seems to broke one of an old plugin I'm still using. The logic in the plugin is similar to the logic before the changes we made in this commit https://github.com/qgis/QGIS/pull/55718/commits/0bf5f90d6405f3d39db3d0c7f5546b6e3e622050.
https://github.com/Artelia/PostTelemac/blob/07d83e27ca49511c42a887367fd1ec9fa8afa0ab/PostTelemac/meshlayerrenderer/post_telemac_pluginlayer_colormanager.py#L74

It's just to let you know that this PR had a side effect but as the plugin is more or less deprecated, this is fine.

**Comment by agiudiceandrea** [comment]
@nirvn, it seems to me this https://github.com/qgis/QGIS/commit/673f0b198afc02c3c27e2c7a2d2649c6a46937d3 also broke the qgis2web plugin which expects a string like `190,178,151,255` in the color property (until 3.34), while now it is like `190,178,151,255,rgb:0.74509803921568629,0.69803921568627447,0.59215686274509804,1` (since 3.36).
https://github.com/qgis2web/qgis2web/blob/b7dc3d93f04bd2da0048d22fe6deb244eb42858a/utils.py#L633

**Comment by nirvn** [comment]
@agiudiceandrea , so it seems. 

In both instances, I feel like the plugins should rely on API calls vs. the properties map. We have an API promise that I do not think extends to properties map string representation :)

E.g., in the qgis2web plugin, using symbolLayer.fillColor() to retrieve the color will work all the time.

@nyalldawson , do you have thoughts on this?

**Comment by nyalldawson** [comment]
@nirvn imo it's an internal private string, and shouldn't be treated as stable api

**Pull request merged**
