### PR TITLE
Use system cache location instead of profile folder for network cache

### PR DESCRIPTION
**Pull request by m-kuhn**
Profile folders are often on network drives and shared among machines whereas the cache should be local (as fast as possible) and is disposable.

Is there a reason to have different caches for different profiles?
In this case, the profile name could still be added as a subfolder, but I can think of more advantages than disadvantages for a shared cache among profiles.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Good move, I believe this was always the intention, but it was just never hooked up.

> Is there a reason to have different caches for different profiles?

I think I recall the issue being that different user profiles may have different settings which could potentially give different results given the same cache keys. Don't know if this ever WOULD be an issue in reality though.

**Comment by m-kuhn** [comment]
I just gave this another thought.

This might be an issue, let's say when two different profiles use a different login for an account. But in this case it would also be a problem when a single profile changes the login, in this case it's actually a cache key deficiency and not a caching deficiency.
So unless there's a veto, I would merge this as is.

**Comment by wonder-sk** [comment]
Looks good to me. I think there should not be a problem with cache data mixing badly from different profiles. My assumption is that cache keys are based on the complete request, so if there would be just tiny bit of a difference, the keys would not match...

**Comment by m-kuhn** [comment]
Thanks for the reviews!

**Pull request merged**
