### PR TITLE
Fix UI issues in HANA provider

### PR DESCRIPTION
**Pull request by mrylov**
This change fixes the issue #41103 in connection dialog.
Furthermore, all HANA dialogs make use of QgsGui::enableAutoGeometryRestore to save and restore the position of a window.

### CODE REVIEW

**Comment by elpaso** [comment]
Better but there is still a glitch in the identifier combo.

immagine

**Comment by nyalldawson** [comment]
@mrylov you need to remove the "fixed" size constraints and the hardcoded min/max sizes in the ui files -- these don't play nice with hidpi displays.

**Comment by mrylov** [comment]
@nyalldawson, I've made necessary changes according to your suggestion.
@elpaso, Could you test it one more time?

**Comment by stefanuhrig** [comment]
@mrylov You can check the layout yourself by increasing the scale in the display settings as described here: https://www.omgubuntu.co.uk/2020/04/ubuntu-20-04-fractional-scaling-support-setting.

I could reproduce the layout issue (not yet applying your fix) by increasing the scale to 125%. I just used an Ubuntu 20.10 standard installation.

**Comment by mrylov** [comment]
@elpaso, I've tested this change using the approach suggested by @stefanuhrig and confirm that it fixes the issue.

**Pull request merged**
