### PR TITLE
Extend import geotagged photos to include exif_orientation

### PR DESCRIPTION
**Pull request by pellegoeg**
## Description

In the danish user group, the missing image rotation have been a topic. 

 "Import geotagged photos" is updated so the exif_orientation is extracted to the output table.

This will make it posible to get the rotation in maptips and other html widgets eg:

``

I have added at 8 new test fotos to the repos showing the letter F as used to descripe the orientation in exif documentation like: https://www.impulseadventure.com/photo/exif-orientation.html

This fixes 1 and 2 in issue: #34868

### CODE REVIEW

**Comment by pellegoeg** [comment]
Test failed, im fixing the code in a couple of hours

**Comment by nyalldawson** [comment]
Thanks @pellegoeg ! Given that the new files aren't actually being used in tests, can you remove these? May as well keep the git repo size as small as possible :smile: 

One thing I'm wondering -- do you think it would be worthwhile also adding a "rotation" field here, where we fill this in based on the orientation value? It would be easier for users that way, as they wouldn't have to lookup what the raw orientation codes mean. (I realise we can't handle flipped images by a rotation alone, but I think those would be extremely rare anyway!)

**Comment by pellegoeg** [comment]
Thank you for the comment @nyalldawson 

I actually started with the solution you mention by converting the exif_orientation code to a rotation, but thought, maybe there is some specialised use cases where they needed the flipped orientation and the qgis projected wanted a more true præsentation of the actual metadata?

In my latest commit, I have cleaned up the test images and I have converted the orientation to a rotation.

I have attached the photos so It can be manualy testet in this pull request.
[orientation_photos.zip](https://github.com/qgis/QGIS/files/5499873/orientation_photos.zip)

**Comment by pellegoeg** [comment]
and the code for maptips is now:

`

**Comment by pellegoeg** [comment]
Hi @nyalldawson 

Is there some work I have forgot to do, or should I wait for you or another maintainer to accept the pull request?

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Looks great, thank you!

**Pull request merged**
