### PR TITLE
fix using deprecated method for settings exclude fields from WMS/WFS

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by 3nids** [comment]
as pointed in https://github.com/qgis/QGIS/pull/38634#issuecomment-744914145

**Comment by Gustry** [comment]
Thanks !
I think I got this issue !

**Comment by Gustry** [comment]
Hi @3nids I'm coming late on this PR, but with PyQGIS, it seems impossible to read/set these new configurations flag for hiding fields from WMS or WFS, without using these deprecated functions `excludeAttributesWms` ... 

The "new" API, using `QgsVectorLayer::fields() → QgsFields::at(index) → QgsField::configurationFlags()` is not exposed in SIP bindings.

So wouldn't be possible to not mark these functions deprecated ?

**Comment by 3nids** [comment]
I preferred fixing the bindings https://github.com/qgis/QGIS/pull/54753
@Gustry ok like that?

**Pull request merged**
