### PR TITLE
Don't include revision in sources.

### PR DESCRIPTION
**Pull request by sebastic**
Prevent changes to files that weren't changed between releases.
This eases review of the changes between releases significantly.

### CODE REVIEW

**Comment by nyalldawson** [comment]
+1

**Comment by sebastic** [comment]
Should I provide additional PRs for the 3.6 & 3.4 backports?

**Comment by m-kuhn** [comment]
Normally only patches that qualify as "bugfix" are backported. Is there a particular pain-point that's big enough to justify a backport? I'm -0 (and 3.6 is retired anyway)

**Comment by sebastic** [comment]
Yes, every time I update the Debian package for the new LTR, I have to review the changes since the previous release which includes all these revision changes making the signal to noise ratio very painful.

**Pull request merged**
