### PR TITLE
A vector layer with z values present should default to "relative" clamping mode, not "clamped to terrain"

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by nicogodet** [comment]
Why not absolute ?

**Comment by nyalldawson** [comment]
@nicogodet my suspicion is that more datasets with z  are height from ground vs some absolute height. (Also absolute heights are rather limited in qgis since we don't have any vertical crs handling.)

**Comment by nicogodet** [comment]
All datasets I use with Z values, Z values represent absolute elevation (topographic points surveyed by a surveyor). But implicitly, Z values are linked to the local vertical CRS...

**Comment by nyalldawson** [comment]
Sure, that's still supported, you'll just need to manually change the setting to absolute (as you do on master now)

**Pull request merged**
