### PR TITLE
[hig] Show standard '*' prefix in application title bar when project

### PR DESCRIPTION
**Pull request by nyalldawson**
has unsaved changes

E.g.

    *my project - QGIS

### CODE REVIEW

**Comment by Gustry** [comment]
Thanks! Very nice!
BTW, I think we lost the version number in the title bar for the 3.0 package. In 2.X, I was used to check the version number on the title bar of my students. Is-it a feature?

**Comment by nyalldawson** [comment]
> BTW, I think we lost the version number in the title bar for the 3.0 package. In 2.X, I was used to check the version number on the title bar of my students. Is-it a feature?

**Comment by nyalldawson** [comment]
> BTW, I think we lost the version number in the title bar for the 3.0 package. In 2.X, I was used to check the version number on the title bar of my students. Is-it a feature?

Yes, there was discussion about this, but it's very very rare for applications to have a version number in the title bar like this, so it was deliberately dropped.

**Comment by nirvn** [comment]
@nyalldawson , +1, nice improvement. Should we do the same thing for layout designer window. Imagine you're editing a layout with the designer maximized, you wouldn't see the (*).

**Comment by nyalldawson** [comment]
> @nyalldawson , +1, nice improvement. Should we do the same thing for layout designer window. Imagine you're editing a layout with the designer maximized, you wouldn't see the (*).

Yes - good point

**Comment by nyalldawson** [comment]
> . Should we do the same thing for layout designer window. Imagine you're editing a layout with the designer maximized, you wouldn't see the (*).

done

**Comment by NathanW2** [comment]
Nice!

**Pull request merged**
