### PR TITLE
[processing] handle NULL values in the single to multi algorithm (fix #15822)

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
Fixes https://issues.qgis.org/issues/15822

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by alexbruy** [comment]
@m-kuhn any ideas why this passed now (as PR) and constanly failed when merged into main tree? See for example https://github.com/qgis/QGIS/commit/e3d79a1fe940b5d813b5f79c51b43393d085bb16

**Comment by m-kuhn** [comment]
Which test?
I think the ProcessingQgisAlgorithmtest is quite unstable recently.
Would be good to know what's going on there...

**Comment by alexbruy** [comment]
Test for "Singleparts to multipart" algorithm, https://travis-ci.org/qgis/QGIS/jobs/232743821#L752.
But I also have seen failures in other test which dissapear after restarting Travis. Probably we should temporarily blacklist ProcessingQgis test and/or carefully review all test which was massively added last few months.

**Comment by m-kuhn** [comment]
Ok to remove the singlepart to multipart one (or better review it actually if someone has the time).

For the segfaults: we don't have a hint which test is responsible (or if it's the framework itself).
However, it should be quite easy to split it up into different subsets of tests (multiple yaml files) and this way examine which one(s) is/are fragile.

If we blacklist it, I don't know which steps would be required to unblacklist it again. And in this case I see this as a dead end with a lot of work lost in vain.

**Comment by nyalldawson** [comment]
> I think the ProcessingQgisAlgorithmtest is quite unstable recently.
Would be good to know what's going on there...

I've seen this too. It's 90% likely related to my recent work - BUT - everytime i've seen the segfault it's being caused with QNetworkAccessManagerPrivate, which leads me to believe it could be unrelated and instead caused by an algorithm or something in processing misusing network requests.

> If we blacklist it, I don't know which steps would be required to unblacklist it again. And in this case I see this as a dead end with a lot of work lost in vain.

Let's not black list it please! I'm about to drop a large set of processing changes, and as part of this I'll (unfortunately) be disabling ALL algorithms temporarily. They'll each need to be upgraded in turn to the new c++ api. As part of this I'll comment out all the existing tests from yaml file, and will bring them back online one-by-one as the algorithms are ported.

As a side effect this should help narrow down what's causing the intermittent failures...

**Comment by alexbruy** [comment]
I temporarily disabled "Singleparts to multiparts" test to have this PR merged. Hope after Processing refactoring and reviewing tests it can be enabled again.

**Pull request merged**
