### PR TITLE
Only require QTWEBKIT for Qt4 when WITH_QTWEBKIT is true.

### PR DESCRIPTION
**Pull request by sebastic**
These changes are required to build QGIS 2.14 with Qt4 but without QtWebKit support, because WebKit support in Qt4 is pending removal as reported in [Debian Bug #784514](https://bugs.debian.org/784514), WebKit support in python-qt4 is [pending removal](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784513#51) too.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Merged in e888753577d1741410baade248275a1d230aef8d

**Comment by jef-n** [comment]
nuking my branch that has been waiting for the above transition to actually happen since january.

**Comment by m-kuhn** [comment]
What did that branch do?

**Comment by jef-n** [comment]
the above + limiting libqtwebkit-dev to were it will be still available, changing references to QWebView to QgsWebView

**Comment by m-kuhn** [comment]
Do you mind merging the extra logic you mentioned?

**Comment by jef-n** [comment]
Why? Webkit is still there.

**Comment by m-kuhn** [comment]
Ok, just hold back with the 💣

**Comment by sebastic** [comment]
It may be that the Qt maintainers will wait for the blocking issues to be fixed before uploading the qt4 packages without WebKit, if those don't get fixed before the freeze WebKit support in Qt4 may stay, but that seems highly unlikely as Qt4 is EOL making security support for the WebKit module problematic.

For the time being WebKit support is still available in the qt4 packages, but it will go away sooner or later. I wouldn't wait with merging changes to support building QGIS without WebKit support in Qt4 until it is actually removed, but there is also a good argument to stick to the current setup until it breaks.

**Comment by jef-n** [comment]
@m-kuhn they already do for long ;)

**Comment by jef-n** [comment]
@sebastic to me this is backwards.  If something breaks I'll fix it.  It's easier to fix something that is broken, than to anticipate a change and "fix" it beforehand.  So I don't know why this is held back forever.

**Comment by sebastic** [comment]
It was held back forever because QGIS isn't ready for the switch to Qt5, see: [Debian Bug #784513](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784513#68).

python-qt4 without WebKit support has been [uploaded to Debian unstable](https://tracker.debian.org/news/770803) today.

**Pull request closed without merging**
