### PR TITLE
Improve package upgrade path from QGIS 2 to QGIS 3 with RPM

### PR DESCRIPTION
**Pull request by daniviga**
## Description

Make the transition from QGIS 2 to QGIS 3 smoother on Fedora in the case of `qgis-python` has been installed as `python2-qgis` (which is also more correct)

In such case `python2-qgis` will be automatically replaced by new `python3-qgis` instead of raising a conflict and have to manually uninstall `qgis-python`:

```
================================================================================================================================================================================
 Package                                    Arch                                 Version                                       Repository                                  Size
================================================================================================================================================================================
Installing:
 python3-qgis                               x86_64                               3.0.0-2.fc27                                  @commandline                                10 M
     replacing  python2-qgis.x86_64 2.18.16-1.fc27
Upgrading:
 qgis                                       x86_64                               3.0.0-2.fc27                                  @commandline                                31 M

Transaction Summary
================================================================================================================================================================================
Install  1 Package
Upgrade  1 Package
```
Packages being built [here](https://copr.fedorainfracloud.org/coprs/dani/qgis3/) already have the fix applied.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [X] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [X] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [X] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
I'm not sure I understand this PR, so please bear with me :)

python2-qgis and python3-qgis can happily live side-by-side, will this be possible with this PR?

**Comment by daniviga** [comment]
Unfortunately `python2-qgis` (from 2.xx) and `python3-qgis` (from 3.xx) cannot live together on the same machine: `python2-qgis` depends on `qgis < 2.99` but it cannot be installed on the same system as QGIS3 (because QGIS2 and QGIS3 share sam  paths, like `/usr/bin/qgis` and many more).

The problem here is merely of packaging: both QGIS3 and QGIS2 provide the `qgis-python` package and during the upgrade from 2 to 3 this will be upgraded automatically. But `qgis-python` is the legacy name of the package: Fedora started to split python packages in `python2-<package>` and `python3-<package>`, so the proper way of installing it now is using `python2-qgis` (for QGIS2) and `python3-qgis` (for QGIS3).
Before this commit, having `python2-qgis` installed, trying to install QGIS3 and its python module would raise an error:

```
 Problem: package python2-qgis-2.18.16-1.fc27.x86_64 requires libqgis_analysis.so.2.18.16()(64bit), but none of the providers can be installed
  - cannot install both qgis-1519286773:2.99.0-git2973e85.fc27.x86_64 and qgis-2.18.16-1.fc27.x86_64
  - cannot install both qgis-2.18.16-1.fc27.x86_64 and qgis-1519286773:2.99.0-git2973e85.fc27.x86_64
  - cannot install the best update candidate for package qgis-2.18.16-1.fc27.x86_64
  - cannot install the best update candidate for package python2-qgis-2.18.16-1.fc27.x86_64
================================================================================================================================================================================
 Package                        Arch                             Version                                                      Repository                                   Size
================================================================================================================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 qgis                           x86_64                           1519286773:2.99.0-git2973e85.fc27                            dani-qgis-testing                            31 M

Transaction Summary
================================================================================================================================================================================
Skip  1 Package

Nothing to do.
Complete!
```


This happens because `python3-qgis` was able to upgrade `qgis-python` but not `python2-qgis`. With this fix we are telling that `python3-qgis` obsoletes and then replaces `python2-qgis` entirely. This is need also because the name of the package has changed, so dnf/rpm is not able to identify `python3-qgis` as an upgrade/replacement for `python2-qgis` 

```
 Package                                    Arch                                 Version                                       Repository                                  Size
================================================================================================================================================================================
Installing:
 python3-qgis                               x86_64                               3.0.0-2.fc27                                  @commandline                                10 M
     replacing  python2-qgis.x86_64 2.18.16-1.fc27
Upgrading:
 qgis                                       x86_64                               3.0.0-2.fc27                                  @commandline                                31 M

Transaction Summary
================================================================================================================================================================================
Install  1 Package
Upgrade  1 Package
```

**Comment by daniviga** [comment]
ping @m-kuhn

**Comment by m-kuhn** [comment]
While it would be great to have packages that can be installed into different prefixes side-by-side, this is probably the appropriate approach for most of the situations.

**Comment by daniviga** [comment]
Currently I'm using QGIS 3 from packages and QGIS 2 installed in `/opt` from sources: unfortunately it's hard (if not impossible) to have both QGIS 2 and QGIS 3 installed in the same system without breaking upstream packaging guidelines (i.e. a QGIS package that installs in /opt will be never be included in upstream Fedora).

Here I'm just following the approach that is being used for the Debian/Ubuntu packages: having two different repos, one with LTR and one with QGIS 3.

The final solution to this problem would be providing RPM packages _and_ a [flatpak](https://flatpak.org/) for each version. In this way you can have multiple versions at the same time also mixing the two technologies (i.e. QGIS 3 from RPM and LTR from a flatpak) This is something I'm working on, but it would require time...

**Pull request merged**
