### PR TITLE
[cmake] find SSH lib

### PR DESCRIPTION
**Pull request by 3nids**
When building on mac, it fails since it cannot find libssh.h which is included in exiv2 (depending if exiv2 has been built with SSH or not).
In the past, I had fixed this by manually setting exiv2 to be compiled withtou SSH but this is not the default case on Mac/Homebrew.
This PR allows defining `SSH_INCLUDE_DIR`, fixing the issue.

### CODE REVIEW

**Comment by jef-n** [comment]
> The SSH library might be required by EXIV2

Shouldn't `cmake/FindEXIV2.cmake` just include it in `EXIV2_INCLUDE_DIR`(s) if required?

**Comment by 3nids** [comment]
Is it supposed to find it automatically? Or do you mean move the content of findssh.cmake in findexiv.cmake

**Comment by jef-n** [comment]
> Is it supposed to find it automatically? Or do you mean move the content of findssh.cmake in findexiv.cmake

Yes, not sure if it's worth it, but even verify whether it's required or not.

**Comment by 3nids** [comment]
using `/usr/local/include` instead of `/usr/local/opt/exiv2/include` as include dir for exiv2 seems to fix the issue for me on mac.
sorry for the noise.

**Pull request closed without merging**
