### PR TITLE
Mark project as dirty when changing layer subset string

### PR DESCRIPTION
**Pull request by nirvn**
## Description
Let people know a bit of work might get loss before it's too late.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'm wondering if this should be in QgsQueryBuilder::accept() instead - there's other places where subsetStrings can be set, e.g .QgsLayerTreeViewFilterIndicatorProvider::onIndicatorClicked, QgsVectorLayerProperties::pbnQueryBuilder_clicked()

**Comment by nirvn** [comment]
@nyalldawson , done.

**Comment by m-kuhn** [comment]
Not totally convinced by this approach.

What about

 * Adding a signal `subsetStringChanged()`
 * `connect( mapLayer, subsetStringChanged, this, makeDirty )` in `QgsProject::addMapLayers`

or even a signal `QgsMapLayer::layerDefinitionChanged()` and `connect( this, subsetStringChanged, this, layerDefinitionChanged`.

**Comment by nirvn** [comment]
@m-kuhn , oups, sorry for this premature commit. The subsetStringChanged() approach sounds good -- @nyalldawson , opinion?

**Comment by nyalldawson** [comment]
@m-kuhn i thought this was an ok approach because it only catches subset string changes which are a result of user interaction (vs changes via code)

**Comment by m-kuhn** [comment]
A valid point. Do you think the normal expectation for triggering this API is to not have the project marked dirty? In this case isn't it counter-intuitive if the new configuration is still saved despite the project's `dirty` flag does not reflect this?

**Comment by nirvn** [comment]
IMHO, it makes more sense to dirty project whenever a layer's crs, name, subset filter, etc is changed, irrespective of whether it's done via GUI or via API.

For eg, there's a "set layer projection" algorithm which assigns a chosen projection for the selected layer. If we don't use the map layer's crsChanged signal, that user interaction doesn't dirty project, risking a user setting loss.

**Comment by nyalldawson** [comment]
I'd have to do some digging, but if I recall correctly there's some code which sets a subset string and then clears it after. (But now that I think about it, that may have been in server)

**Comment by nyalldawson** [comment]
@nirvn fair enough, I guess it's more harm to miss a dirty then have a non-valid dirty

**Comment by m-kuhn** [comment]
I noted the `QgsMapLayer::configChanged()` signal says in the docs 

> Emitted whenever the configuration is changed. The project listens to this signal to be marked as dirty.

Maybe QgsVectorLayer should just connect all signals that are sent out and are supposed to mark the project as dirty to this signal? This would encapsulate layer-mark-dirty code almost completely inside `Qgs[...]Layer` classes.

**Pull request merged**
