### PR TITLE
[azure] Switch osgeo mirror to osuosl

### PR DESCRIPTION
**Pull request by m-kuhn**
Because 🚀

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by nirvn** [comment]
How much of a speed gain are we talking about here?

**Comment by m-kuhn** [comment]
On QField it brought download time from 30 minutes to 6.5 minutes. So roughly a factor of 5.

**Comment by nirvn** [comment]
🤜🤛

**Comment by m-kuhn** [comment]
Seems to be only a factor of 1.5 to 2 here. But still 10-15 minutes down.

**Comment by m-kuhn** [comment]
Heh, I forgot to update the most important path. The last run was just faster by pure chance.
After doing the real change we are down from 20-30 minutes before to 6 minutes now.

**Comment by nirvn** [comment]
I'd call that an improvement.

**Pull request merged**
