### PR TITLE
Provide qgis.plugins as a module for 3rd party plugins to monkey-patch their stable API into.

### PR DESCRIPTION
**Pull request by nyalldawson**
Refs discussion in #9619 

This module will contain stable API added by QGIS plugins. It is provided
as a container for these plugins to monkey-patch their stable, external
API into.

An example of a plugin patching a function into the qgis.plugins library:

.. code-block:: python

       from qgis import plugins

       def my_function():
           print('Test')

       qgis.plugins.my_function = my_function

An example of a plugin patching a module into the qgis.plugins library:

.. code-block:: python

       from qgis import plugins
       from my_plugin import my_module

       qgis.plugins.my_module = my_module

Any API exposed through this module is 3rd party, and is not the
responsibility of the QGIS project. Bugs must be filed with the plugin
authors themselves, and not on the QGIS project issue tracker.

### CODE REVIEW

**Comment by nyalldawson** [comment]
So is this a yes? @elpaso @m-kuhn @NathanW2 ?

**Comment by NathanW2** [comment]
Is this so other plugins can call each other by a bridge module?

**Comment by nyalldawson** [comment]
It's so plugins which decide they want to provide some stable API for use by others plugins (and hold other API back as private) have a way to differentiate the stable from private API.

Any API patched into qgis.plugins by a plugin is considered "stable", and the plugin developer has implicitly made a commitment not to change this.

**Comment by NathanW2** [comment]
Are you rushed to push it. I would like to think about it a bit more. I am
just not sure I like things being patched into a single high-level module
like that without a extra module level for the plugin itself

I wonder if this should just go into the metadata as a public API endpoint
and QGIS registers it in the right place?

[API]
Mymodule
Myfunc
Myfunc2

Meaning it would be auto registered under

Qgis.plugins.myplugin.mymodule at load time.

**Comment by NathanW2** [comment]
[qgis_example.zip](https://github.com/qgis/QGIS/files/3027571/qgis_example.zip)

Here is an example of importing a module dynamically and adding into qgis.plugins under a new module for the given plugin.

**Comment by 3nids** [comment]
beside implementation details, I'd be in favor of enforcing `qgis.plugins.myplugin.mymodule` to register under the plugin name:
* cleaner: you always know where to look for the code
* safer: avoid name conflicts (2 plugins registering the same method)

**Comment by nastasi-oq** [comment]
Why not automate the registration procedure looking for a well-known module that expose, for each plugin, what should be public and stable ?
If this module doesn't  exists means: no public "things" are available.

**Comment by nyalldawson** [comment]
I'm happy for someone else to take this one on if they want to see it land -- I was originally thinking it'd be a quick fix, but I can't justify spending lengthy time on this one.

**Pull request closed without merging**
