### PR TITLE
[vertex tool] synchronisation of map tool and editor selections

### PR DESCRIPTION
**Pull request by 3nids**
This fixes the long standing issue of the non synchronisation of selection of the vertices in map tool and vertex editor tab. The two selections are now synchronized.

Also fixes an issue when right-clicking on an edge with previously selected vertices over several features, the selection was being kept despite the feature being locked.

I would love some review and/or testing from the vertex tool aficionados.

Needs backporting to 3.4 and 3.6.

### CODE REVIEW

**Comment by nirvn** [comment]
Niiicceeeee

**Review by wonder-sk — APPROVED** [review]
Looks good to me! (but have not tested)

**Comment by saberraz** [comment]
@3nids since this PR, locked features do not appear as locked.
disappearing_locked_feature

**Comment by wonder-sk** [comment]
I can confirm ... if I right-click on a feature (polygon), I can't see any markers for the locked feature so I don't even know which one I have locked (especially if there are multiple overlapping ones).

**Comment by 3nids** [comment]
OK, will fix this asap! Sorry.

**Comment by 3nids** [comment]
@wonder-sk @nirvn 

I have some UX and code concerns...

1) Shall we highlight the vertices in red (before they are selected in blue) or use a simple feature highlight?

2) if we stick to vertices highlighting, shall I code it as it was before (use VertexEntry to do the highlight from the QgsLockedFeature) or do it in QgsVertexTool?

**Comment by nirvn** [comment]
@3nids , no feature highlight please, just the red vertices highlight we had before.

**Comment by wonder-sk** [comment]
No strong opinions about the highlight.

Implementation-wise it would be nice to have all highlighting done within vertex tool code, and vertex editor only deals with its table.

**Pull request merged**
