### PR TITLE
Reverts parts of 35d62ab relative to raster layer properties

### PR DESCRIPTION
**Pull request by DelazJ**
refs #39693
35d62ab was fixing some [visual issues ](https://github.com/qgis/QGIS/pull/39075#issuecomment-703347291) that are worth a fix so I did not revert the whole commit but if required it's possible [here](https://github.com/qgis/QGIS/compare/release-3_16...DelazJ:bye_spinbox316?expand=1) (I didn't want to trigger an unnecessary(?) PR)

### CODE REVIEW

**Comment by nirvn** [comment]
@luipir , since you're able to replicate crash, can you confirm this partial revert is sufficient and the crash is gone?

**Comment by luipir** [comment]
> @luipir , since you're able to replicate crash, can you confirm this partial revert is sufficient and the crash is gone?

I'll do tomorrow...thanks

**Comment by luipir** [comment]
first test cherry-piking your two commits 634d8bf2c652894e398bac22989e94b3ef5838fd and e3e2577097e4507344c39e455ea52a09d4fb44e6 applied on fd9b11d8df8ab801b691ba806b528b164e42748b (upstream/release-3_16) does not solve the issue... I'll try to do a complete revert of that commit

**Comment by nirvn** [comment]
At this stage, I'd vote for a complete reversal for 3.16.1 (and master), then re-apply bits one by one to figure out what is wrong.

**Comment by luipir** [comment]
a compete revert of 35d62ab on fcafb2716bb4afebccb7f2db93eb9aac00fe120f (upstream/release-3_16) solve the issue :|

**Comment by alexbruy** [comment]
Were the same adjustments made in the Options dialog? I have repeated crashes when try to open Options dialog.

**Comment by luipir** [comment]
> Were the same adjustments made in the Options dialog? I have repeated crashes when try to open Options dialog.
> 
> Looks like #39075 should be reverted completely.

I tested opening option dialog and raster symbology in option dialog... after revert only of 35d62ab. Not idea why the other commit does not affect the crash

**Comment by nirvn** [comment]
@luipir , to avoid confusion, am I understanding you correctly in that by _only_ reverting https://github.com/qgis/QGIS/commit/35d62ab0d47fa309b2de8fdad3aab66836b32585 , the crashes are gone?

**Comment by luipir** [comment]
> @luipir , to avoid confusion, am I understanding you correctly in that by _only_ reverting [35d62ab](https://github.com/qgis/QGIS/commit/35d62ab0d47fa309b2de8fdad3aab66836b32585) , the crashes are gone?

correct... a complete revert not a partial one as proposed in your first PR

**Comment by luipir** [comment]
> Were the same adjustments made in the Options dialog? I have repeated crashes when try to open Options dialog.
> 
> Looks like #39075 should be reverted completely.

@alexbruy would be great if you were able to confirm that crash goes away with a total rever or with the new proposed PR. The reason is to be sure that crash is not due to some local effect of my setup.

**Comment by nyalldawson** [comment]
Closing given #39935 is a better fix

**Pull request closed without merging**
