### PR TITLE
Save legend expression

### LINKED ISSUE #35489: Layout legend expressions are not saved
I blame myself, bugfix is #35448

### PR DESCRIPTION
**Pull request by roya0045**
Fixes #35489 
## Description

Not sure if this is a bugfix or not but I initially forgot to implement this and expressions had to be reapplied each time the project was loaded.

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]
Thanks.
Does this need a backport?

**Comment by roya0045** [comment]
@m-kuhn This is a minor bugfix, up to know I don't think this will impact a lot of user as there are still functionality improvement that must be merged. Until those are in I don't think this is quite critical, but it could be nice.

I'll let you be the judge.

**Comment by m-kuhn** [comment]
Code wise it is very low risk. Storing capabilities are basic expectations for anything.
Two reasons for, pretty much none against (?)
Which versions?

**Comment by roya0045** [comment]
In this case both, 3.10 and 3.12 have the feature integrated at the same stage of development.

**Comment by m-kuhn** [comment]
Thanks

**Comment by roya0045** [comment]
Thank you Matthias!

**Pull request merged**
