### PR TITLE
 Fix extensions not automatically added to new filenames in QgsFileWidget

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes a UX regression introduced by swapping dialogs to use QgsFileWidget, where on some platforms the extension is not automatically added for selected file names

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , nice, good example of why it pays off to have qgsfilewidget in as many places as possible :)

**Comment by nirvn** [comment]
@nyalldawson , I'm wondering whether you should also trigger this via the QLineEdit::editingFinished signal when there's a single format attached to the widget.

**Comment by nyalldawson** [comment]
I considerer that, but it could be annoying too if the user has a good reason not to want an extension... Maybe a future follow up we could add this, so it happens once, but if user changes it back it doesn't happen again for that object...

**Comment by nyalldawson** [comment]
Unrelated test failure

**Pull request merged**
