### PR TITLE
[FEATURE] replace GDALTools plugin with Processing

### PR DESCRIPTION
**Pull request by alexbruy**
Tagged as feature to not forget mention in docs and changelog

### CODE REVIEW

**Comment by nyalldawson** [comment]
+1 from me

**Comment by nyalldawson** [comment]
I should have said: "Dropping 11,000 lines of duplicated code without unit tests? Heck yes!!"

**Comment by nirvn** [comment]
@alexbruy , +0.9 ! 😉 It'd still be nice to address this issue ( http://hub.qgis.org/issues/14341 ) as I feel many will raise this slight UX regression if left unaddressed prior to 3.0.

Great job with all those PRs.

**Comment by alexbruy** [comment]
@nirvn, I plan to address as much issues as possible during 3.0 development cycle. So IMHO, dropping GDALTools now will help us to identify such issues earlier and allow to fix them.

**Comment by gioman** [comment]
@nirvn new reference ticket http://hub.qgis.org/issues/14641 (also affects "merge vector layers", maybe others).

**Pull request merged**
