### PR TITLE
Run qstring fixup

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by vcloarec** [comment]
For my information, why QLatin1String is better? I've just made a quick benchmark, and, at least for QString constructor, QStringLiteral seems much much better (>x20) than QLatin1String

**Comment by nyalldawson** [comment]
> at least for QString constructor, QStringLiteral seems much much better (>x20) than QLatin1String

Yes, for pure QString construction QStringLiteral is faster. But some methods such as QString::contains have an optimised overload for QLatin1String arguments which is faster then the QString construction and compare combined.

Some reading:
https://doc.qt.io/qt-5/qlatin1string.html#details
https://woboq.com/blog/qstringliteral.html
https://www.kdab.com/qstringview-diaries-advances-qstringliteral/

**Comment by vcloarec** [comment]
Indeed, completed benchmark:
image

but for contains, QStringLiteral is better... with my non very rigorous benchmark...

**Comment by nyalldawson** [comment]
@vcloarec 
I can't explain that, but suffice to say I think we should follow upstream's advice and trust that in the general case this is faster... (I **think**...!)

**Pull request merged**
