### PR TITLE
[backport] GPKG: fix json map filewriter

### PR DESCRIPTION
**Pull request by elpaso**
Backport of https://github.com/qgis/QGIS/pull/52774

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
@elpaso, just a note: it seems that when a json map field is written to a GPKG layer by a processing algorithm, then the resulting field content is slightly different depending of the output type (being "Save to File" or "Save to GeoPackage").

Using DB Browser for SQLite to inspect the resulting GeoPackage files:
- when the output is set to "Save to File" and a GPKG file is set, then the content of the field is e.g.:
```
{"19":1}
```
- when the output is set to "Save to GeoPackage" and a GPKG file and layer name are set, then the content of the field is e.g.:
```
{
    "19": 1
}
```
The size of the resulting GeoPackage files is also different.

I've used the [layers](https://github.com/qgis/QGIS/files/13064193/output.zip) provided in https://github.com/qgis/QGIS/issues/55016 to make the test.

Is this behaviour expected or there is something to fix?

**Comment by elpaso** [comment]
> Is this behaviour expected or there is something to fix?

I'll have a look, I feel that I need to tweak the dump to json function to not do any indent.

**Comment by elpaso** [comment]
> * Save to GeoPackage"

Sorry, I cannot reproduce using current master (of both QGIS and GDAL).

It's not a bug anyway.

**Review by nyalldawson — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
> I cannot reproduce using current master (of both QGIS and GDAL).

Strange... I see the described behaviours even using QGIS 3.33.0-Master 0550941a7571f9e30be6c33d885ae21dac9a2905 and GDAL 3.8.0-dev [cd2a054](https://github.com/OSGeo/gdal/commit/cd2a054b0d7b881534baece69a8f52ddb69a53d9) on Windows (OSGeo4W).

**Comment by elpaso** [comment]
@agiudiceandrea I have probably missed how exactly to reproduce or verify it, maybe you could open a separate issue with detailed instructions.

**Pull request merged**
