### PR TITLE
 QgsDelimitedTextFile: fix parsing of files with CR end of line 

### LINKED ISSUE #36392: QGIS crashes/freezes when adding a large CSV file as delimited text layer
Operating system: Windows 10 Pro (Version 1909)
QGIS Version: 3.12
Attaching the xlsx version of the csv file as github doesnt support csv files.
I was not having this issue until today. Started using QGIS version 3.10 (more stable) last week and this morning was working fine until noon where it started crashing when uploading this delimited text layer. I restarted my pc, nothing, unistalled version 3.10 and installed version 3.12 but the problem persisted. Thanks for any type of help in advance.
[ATT.xlsx](https://github.com/qgis/QGIS/files/4619070/ATT.xlsx)

### PR DESCRIPTION
**Pull request by rouault**
*  QgsDelimitedTextFile: fix parsing of files with CR end of line 

Fixes #36392
Fixes #21976 
Fixes #17190

We are obliged to do 'at hand' parsing due to QT not handling CR-only
end of lines.
As we are at it, also limit each line to 1 MB to avoid potential denial
of service (which was what close to what happened here before the CR-only
parsing fix)

Add tests for parsing CR-only end of lines, and exercising the at-hand
buffering logic

*  QgsDelimitedTextSourceSelect: add a limitation to the number of fields
9d85148

Set to 10000 by default. Can be overriden through settings.

This is only for the preview in the source select dialog. (Attribute
table performs badly for much less columns)

---------------------

While being a bug fix, I'm not completely sure this is material for 3.10. At least not without being exercised a bit in master. The logic to parse lines at hand isn't completely trivial.

### CODE REVIEW

**Comment by nyalldawson** [comment]
I believe this also fixes https://github.com/qgis/QGIS/issues/21976 ?

**Comment by nyalldawson** [comment]
Also https://github.com/qgis/QGIS/issues/17190

**Review by nyalldawson — APPROVED** [review]

**Comment by rouault** [comment]
@nyalldawson any opinion if we should tag this for 3.10 backport ?

**Comment by nyalldawson** [comment]
I think it's fine to backport (with the time delay). It fixes a crash, so would be good to have in ltr. We could even delay two releases if you're concerned.

**Pull request merged**
