### PR TITLE
Improve colors assigned to new layers by default

### PR DESCRIPTION
**Pull request by nyalldawson**
Instead of randomly generating colors, use a predefined palette of "nice colors for map layers".

This PR implements to code to support this - we need to tweak the provided new_layer_colors.gpl palette and populate it with an awesome selection of nice mapping colors.

### CODE REVIEW

**Comment by nirvn** [comment]
Looking good all around. This is the kind of stuff that impacts of people's impression at the "subconscious level" 😉, glad to see it tackled.

**Comment by rduivenvoorde** [comment]
@nyalldawson nice!
Wanted to see what it looks like, left is this PR, right is master.
I added a point layer, then added new buffers layers:
Is this a possible outcome?

selection_300

**Comment by nyalldawson** [comment]
@rduivenvoorde 

> Is this a possible outcome?

Looks right to me --  the default palette included in the PR is far from great. We need an awesome one for change to really shine :)

**Comment by nyalldawson** [comment]
@rduivenvoorde 

I just realized the default palette was actually missing from this PR. Can you please retest? The results will be very different :)

**Comment by rduivenvoorde** [comment]
@nyalldawson where should the new_layer_colors.gpl file be installed? Searching for it after a compile/install here locally with me I can only find it in: 
<src folder>/resources/new_layer_colors.gpl
<src folder>/resources/palettes/new_layer_colors.gpl
resulting in: 
selection_310

Not sure if this is very different? I also tried to copy the new_layer_colors.gpl file manually to 
<install dir>/share/qgis/resources
But I think without a notable change?

I also copied it manually to <profile-folder>/profiles/default/palettes
And again (to me...) not a notable change.
I have to admit that I'm not so much of a color guy/cartographer, but I think I could see if colors change? But maybe I'm just plain wrong, OR I use the wrong test: open a point layer, and add quickly 15 layer by create a buffer or 10000 meter for it...

Can you share an example screenshot of yourself?

**Comment by nyalldawson** [comment]
@rduivenvoorde 

Try typing this in the python console:

     QgsApplication.pkgDataPath()

The .gpl file should be located in  QgsApplication::pkgDataPath() + '/resources/palettes/new_layer_colors.gpl'

You can test if it's working correctly by calling

    QgsApplication.colorSchemeRegistry().randomStyleColorScheme()

if it's working correctly, that will return an object -- if not you'll get None

**Comment by rduivenvoorde** [comment]
@nyalldawson thanks. I make/make install myself in dir in my homedir.
pkgDataPath is set to '/home/richard/bin/qgis_all/master/debug/share/qgis'

I'm do not have a dir resources/palettes in there though, will test later if it get's installed....

**Comment by rduivenvoorde** [comment]
Ok tested, if I copy the "palettes/new_layer_colors.gpl" file by hand to my QgsApplication.pkgDataPath()/resources then it works (looking at the codes in the gpl file and the colors):

selection_332

and

```
QgsApplication.colorSchemeRegistry().randomStyleColorScheme()
<qgis._core.QgsUserColorScheme object at 0x7f6f128e6ee8>
```

But, with me, it is not installed by 'make install'?

Another observation: in ALL profile folders there is also a 'palettes' directory. But putting the new_layer_colors.gpl file into there is NOT giving me a `QgsUserColorScheme`?

@NathanW2 is that supposed to copy stuff from the QgsApplication.pkgDataPath()/resources when the profile is created?

**Comment by nyalldawson** [comment]
@rduivenvoorde 
> Another observation: in ALL profile folders there is also a 'palettes' directory. But putting the new_layer_colors.gpl file into there is NOT giving me a QgsUserColorScheme?

You may need to give it a distinct name. Also it only scans this folder on startup.

**Comment by nyalldawson** [comment]
I'd like to merge this now. I think it's self-contained enough to be valuable, and will allow for wider testing for a long time before 3.2 release (and for us to make an awesome default color palette).

In future follow-up work I'd like to allow users to set custom color palette as the "new layer colors palette". This would allow users to create (or import) different sets of colors to randomly use for new layers.

**Comment by nirvn** [comment]
+1

**Comment by rduivenvoorde** [comment]
+1

**Comment by nyalldawson** [comment]
Thanks for the testing!

**Pull request merged**
