### PR TITLE
fix 3d mesh dataset rendering

### PR DESCRIPTION
**Pull request by vcloarec**
Issue in 3d mesh dataset rendering...

### CODE REVIEW

**Comment by nyalldawson** [comment]
Do we need some more test coverage here?

**Comment by vcloarec** [comment]
> Do we need some more test coverage here?

Yes, sure, it will be covered by tests added in  https://github.com/qgis/QGIS/pull/39307 that need this fix to not fail.

**Comment by PeterPetrik** [comment]
i think this need a backport...?

**Comment by vcloarec** [comment]
Actually it was already cover by a test, but with a dataset index (group = 0, index = 0). As the issue came from that group and index was inverted...
So the test is now fixed.


> i think this need a backport...?

It is a feature introduce in 3.14 release and the issue was introduced when implementing the new temporal framework in the same release.

**Pull request merged**
