### PR TITLE
do not build native test without gui

### PR DESCRIPTION
**Pull request by PeterPetrik**
I am not able to build qgsquick library on MacOS with this combination of flags
WITH_QUICK=TRUE, WITH_GUI=FALSE, WITH_DESKTOP=FALSE, WITH_BINDINGS=FALSE

Problem is that test for macnative links agains `qgis_qui` so it should be ON only when gui is requested.

```
[  2%] Generating ../output/i18n/qgis_zh-Hant.qm
In file included from /Users/peter/Projects/quick/QGIS/tests/src/native/testqgsmacnative.cpp:16:
In file included from /Users/peter/Projects/quick/QGIS/src/test/qgstest.h:20:
/Users/peter/Projects/quick/QGIS/src/core/qgsapplication.h:19:10: fatal error: 
      'QApplication' file not found
#include <QApplication>
         ^~~~~~~~~~~~~~
1 error generated.
```

### CODE REVIEW

**Comment by m-kuhn** [comment]
Explanation sounds good, but I am confused by the build log, is that related to linking to qgis_gui? That sounds more like a missing include_directory directive somewhere.

**Comment by 3nids** [comment]
I think I added this for the icon. This can be easily removed. Will do tomorrow

**Comment by PeterPetrik** [comment]
this is all in tests! The include file is not found, because we link agains `QT_INCLUDE_DIRS` which does not contain QT's widget includes when building without GUI

**Comment by m-kuhn** [comment]
Ignore my comment, it looks like @3nids is going to come up with anther fix.

**Comment by 3nids** [comment]
does this solve the issue?
https://github.com/qgis/QGIS/pull/8038

**Comment by PeterPetrik** [comment]
@3nids you meant your PR in combination with mine or as replacement? If as replacement, I doubt it work, since we still link to qgis_qui in mac native test CMakeLists.txt

**Comment by 3nids** [comment]
@PeterPetrik should be good now

**Comment by PeterPetrik** [comment]
closing, thanks @3nids

**Pull request closed without merging**
