### PR TITLE
Try to fix raster magnification

### LINKED ISSUE #45336: Magnifier Doesn't Magnify but Instead Just Changes Scale
### What is the bug or the crash?

Locking the scale and then changing the magnification doesn't lock the scale and then magnify the image. Instead, it just updates the scale. So, for instance, if you are trying to read street names on OSM and you want to zoom in, it fails to zoom in. Instead it appears to perform a network request for an updated image. For instance if you set the scale to 1:10000, lock it, and then magnify by 200% you get the same view as if you just selected 1:5000 scale. Very briefly, a magnified view appears but then it is replaced with a new view scaled as described.

If you install the QGIS Network Logger you can see the network requests going out as you increase the magnification.

The expectation is that there would not be any new network request, but only that the cached image be magnified.

### Steps to reproduce the issue

1. Start a new, clean project.
2. Add OpenStreetMap layer.
3. Add the QGIS Network Logger plugin
4. Click the QGIS Network Logger button. The logger appears.
5. Zoom to a city or town with some reasonably dense streets.
6. Set the scale to 1:10000
7. Click the lock scale.
8. Note the size of the street name text.
9. Click the "Clear" button in the QGIS Network Logger panel
10. Change the magnification to 200%
11. The canvas will briefly, magnify, increasing the text size, then go blank as then the Network Logger will show a request going out to update the canvas. The canvas will update and the text size will shrink again.
12. Take careful note of the extents and the sizes of objects displayed.
13. Now reset the magnification back to 100%
14. Unlock the scale.
15. Now select the 1:5000 scale.
16. Note the view is identical to the the locked 1:10000 scale at 200% magnification.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85be9
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
Compiled against PDAL | 1.8.0 | Running against PDAL | 1.8.0 (git-version: Release)
PostgreSQL Client Version | 11.11 (Debian 11.11-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | nominatim_locator_filter; QuickOSM; geometry_paster; quick_map_services; joinmultiplelines; profiletool; coordinates_converter; zoomview; qgisnetworklogger; latlontools; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Here is how the 3.16 documentation describes how the magnifier should work:

> On the right side of the scale display, press the lockedGray button to lock the scale to use the magnifier to zoom in or out. The magnifier allows you to zoom in to a map without altering the map scale, making it easier to tweak the positions of labels and symbols accurately. The magnification level is expressed as a percentage. If the Magnifier has a level of 100%, then the current map is not magnified. Additionally, a default magnification value can be defined within Settings ► Options ► Rendering ► Rendering behavior, which is very useful for high-resolution screens to enlarge small symbols.

Clearly, the scale is not staying unaltered as is described above.

Note: Some people (myself included) have a very difficult time reading text and discerning auto-scaling detail if we can't magnify it! It can be pretty frustrating.

Thanks for your consideration of this issue. QGIS is a brilliant piece of opensource software! The efforts of the QGIS team are not taken for granted!

### PR DESCRIPTION
**Pull request by elpaso**
Fix #45336

### CODE REVIEW

**Comment by elpaso** [comment]
> Could the existing dpi target property be used instead here? That's how a similar issue was fixed with print layout previews

mDpiTarget is not changed when magnification factor is set: it is always -1. Honestly I'm confused about it: it seems to be only used in layout in a single place.

The magnification factor changes mDpi directly (which is also confusing). I have no idea what is the **right** way to fix this, what I do know is that my patch works.

I'm leaving this to someone who actually knows how mDpi, mDpiTarget and magnificationFactor are supposed to work together.

**Comment by nirvn** [comment]
@elpaso , the target dpi is indeed only used in layout ATM, it was added (3.20 or 3.22, can't remember atm) to fix map item preview rendering in the layout designer when ppl zoom into the layout.

Magnification wasn't within the scope of what was requested, but I'm certain that it's a proper way to go at it for this. And it gives us a single solution/implementation we can further refine down the road.

**Comment by elpaso** [comment]
Ok, but I still cannot understand how to fix this issue without passing in the magnification factor: it is required to adjust the actual width and height of the raster to fetch: mDpi is already adjusted in the settings as you pointed out in https://github.com/qgis/QGIS/blob/master/src/core/qgsmapsettings.cpp#L63 and mTargetDpi is -1. Even if I set mTargetDpi to mDpi I'm still missing the information I need (the magnification factor) to adjust the raster size and I wonder what is the point of having mTargetDpi equals to mDpi anyway.

My feeling/guess is that when mTargetDpi was introduced the work wasn't really completed: it should have probably set in the mapsettings general case and not only for layouts, if mDpi was left unchanged from the magnification factor and mTargetDpi was indeed set to the adjusted dpi I would have a way to retrieve the magnification factor (by dividing the two) and I would not need the magnification factor in the renderer.

**Comment by elpaso** [comment]
Also, the documentation doesn't help much: what's the difference between outputDpi and dpiTarget? The latter mentions "Returns the target DPI (dots per inch) to be taken into consideration when rendering", does that imply that `outputDpi` is **not** taken into consideration when rendering?

**Comment by nyalldawson** [comment]
> Ok, but I still cannot understand how to fix this issue without passing in the magnification factor: it is required to adjust the actual width and height of the raster to fetch

That's exactly the mechanism which is already in place for the target dpi handling.

Here you'd set:
- outputDpi as the screen dpi * multiplication factor (which is already done), to get the large scaling
- targetDpi to screen dpi, so that rasters are fetched for the non-magnified screen dpi

**Comment by elpaso** [comment]
> > Ok, but I still cannot understand how to fix this issue without passing in the magnification factor: it is required to adjust the actual width and height of the raster to fetch
> 
> That's exactly the mechanism which is already in place for the target dpi handling.
> 
> Here you'd set:
> 
>     * outputDpi as the screen dpi * multiplication factor to get the large scaling (this is already done)
> 
>     * targetDpi to screen dpi, so that rasters are fetched for the non-magnified screen dpi

Ok, so I got it all wrong and `targetDpi` is not the DPI of the final image but that of the non-magnified canvas?

Anyway, your second point here is not correct, we need to fetch the raster image based on the magnified DPIs or we would get the current behavior (and the bug).

**Comment by elpaso** [comment]
@nyalldawson 

this patch on master apparently fixes it:

```diff
diff --git a/src/core/maprenderer/qgsmaprendererjob.cpp b/src/core/maprenderer/qgsmaprendererjob.cpp
index 7169637925..8e1f632c47 100644
--- a/src/core/maprenderer/qgsmaprendererjob.cpp
+++ b/src/core/maprenderer/qgsmaprendererjob.cpp
@@ -504,6 +504,10 @@ std::vector<LayerRenderJob> QgsMapRendererJob::prepareJobs( QPainter *painter, Q
     job.context()->setLabelSink( labelSink() );
     job.context()->setCoordinateTransform( ct );
     job.context()->setExtent( r1 );
+    if ( mSettings.magnificationFactor() != 1 )
+    {
+      job.context()->setDpiTarget( mSettings.outputDpi() / mSettings.magnificationFactor() );
+    }
     if ( !haveExtentInLayerCrs )
       job.context()->setFlag( Qgis::RenderContextFlag::ApplyClipAfterReprojection, true );
```

how does that look to you?

**Pull request closed without merging**
