### PR TITLE
Add test to ensure help examples are valid expressions, fix some examples

### PR DESCRIPTION
**Pull request by nyalldawson**
Ping @DelazJ

### CODE REVIEW

**Comment by DelazJ** [comment]
I can't speak for the code but 👏🏿 for the idea. Thanks Nyall.

**Review by troopa81 — APPROVED** [review]
Good idea!

**Comment by DelazJ** [comment]
@nyalldawson would this be auto backported or should we consider backporting the expression fixes manually?
Also, out of curiosity, I notice that the deprecated $page, $map and $rownum functions were deleted. Any idea why $scale survived?

**Comment by nyalldawson** [comment]
@DelazJ 
> would this be auto backported or should we consider backporting the expression fixes manually?

I think we should manually backport just the documentation fixes

> Also, out of curiosity, I notice that the deprecated $page, $map and $rownum functions were deleted. Any idea why $scale survived?

$scale still works, it's just hidden from the GUI. The others don't work at all anymore.

**Pull request merged**
