### PR TITLE
Fix wmts handling of static time lists

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes issues accessing https://datacube.services.geo.ca/ows/aerial?service=wms using the temporal framework, where previously the list of available times could not be parsed

### CODE REVIEW

**Comment by nyalldawson** [comment]
@Samweli can you take a look at this one?

**Comment by Samweli** [comment]
> @Samweli can you take a look at this one?

see this now @nyalldawson!

**Comment by Samweli** [comment]
Look goods @nyalldawson

**Comment by nyalldawson** [comment]
Thanks @Samweli !

**Pull request merged**
