### PR TITLE
Remove join field from join fields subset list

### PR DESCRIPTION
**Pull request by giohappy**
Remove the join field from the list (avoiding wrong header/column indexing reported in #12589

### CODE REVIEW

**Comment by 3nids** [comment]
I am not sure it's the best way to solve this.
We can imagine that the fields have different widgets, configuration, etc.

I would rather fix the code in the attribute table.

@m-kuhn any opinion?

**Comment by m-kuhn** [comment]
Are these values not already available from the field on the first table and therefore it's not necessary to show the field from the joined layer again?

For refernece:
http://hub.qgis.org/issues/12589

**Comment by 3nids** [comment]
I would say yes.
But just hiding the field from the list for the user is not really the safest way. 
Why not fixing the code directly?

Then we can still discuss if it makes sense or not to have this column but I would rather leave the choice to the user.

**Comment by m-kuhn** [comment]
@giohappy do you think this is feasible?
It would be great to have this fixed in 2.10.

Adding the milestone now...

**Comment by wonder-sk** [comment]
Fixed in the core in 78708159b28bcbfa94e53f8b93f91790fa43ec02

**Pull request closed without merging**
