### PR TITLE
add test to ensure scale lock is respected on canvas resize

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by nyalldawson** [comment]
@3nids what's the plan here?

**Comment by 3nids** [comment]
well, I think this needs somehow a redesign of the magnification ratio. 
I think it should rely in the map settings rather than in the map canvas. 
I don't have precise plan, let me maybe discuss this with Martin first.

**Comment by 3nids** [comment]
@nyalldawson ...have you fixed the issue in master? I originally failed at making the test fail to show the wring behavior of the map canvas.

1. lock the scale
2. resize the canvas
=> scale changes

**Comment by nyalldawson** [comment]
@3nids no, I just got the other test passing :p should we revert?

**Pull request merged**
