### PR TITLE
[grass] Add new -e -n flags to r.slope

### PR DESCRIPTION
**Pull request by PedroVenancio**
## Description
New features in GRASS 7.6: Add -n flag to create aspect as degrees clockwise from North (azimuth), with flat = -9999 (like gdaldem); new -e flag to compute values at edges (like gdaldem -compute_edges).

https://grass.osgeo.org/grass78/manuals/r.slope.aspect.html

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by nyalldawson** [comment]
What would happen if these arguments are added for earlier grass versions? There's no capability in this provider to enable parameters based on the grass version, so we'd have to make sure we don't break execution on grass < 7.6

**Comment by PedroVenancio** [comment]
Hi @nyalldawson 

I've tested in GRASS 7.4.2 shipped with QGIS 3.4.3 and in GRASS the behaviour is:

- Without flags -e and -n:
```
r.slope.aspect --verbose elevation=dem_srtm_80m@PERMANENT slope=dem_srtm_80m_slope aspect=dem_srtm_80m_aspect precision=CELL
Percent complete...
Elevation products for mapset <PERMANENT> in <dem_srtm_80m>
Min computed aspect 0.0000, max computed aspect 360.0000
Aspect raster map <dem_srtm_80m_aspect> complete
Min computed slope 0.0000, max computed slope 60.6259
Slope raster map <dem_srtm_80m_slope> complete
(Wed Jan 29 09:53:40 2020) Comando terminado (6 sec)
```

- With flags -e and -n:
```
r.slope.aspect --verbose -e -n elevation=dem_srtm_80m@PERMANENT slope=dem_srtm_80m_slope_n aspect=dem_srtm_80m_aspect_n precision=CELL
Generates raster maps of slope, aspect, curvatures and
partial derivatives from an elevation raster map.
Usage:
 r.slope.aspect [-a] elevation=name [slope=name]
[aspect=name]
   [format=string] [precision=string] [pcurvature=name]
[tcurvature=name]
   [dx=name] [dy=name] [dxx=name] [dyy=name] [dxy=name]
[zscale=value]
   [min_slope=value] [--overwrite] [--help] [--verbose]
[--quiet] [--ui]
Flags:
  -a   Do not align the current region to the raster
elevation map
Parameters:
   elevation   Name of input elevation raster map
       slope   Name for output slope raster map
      aspect   Name for output aspect raster map
      format   Formato para relatar a declividade
               opções: degrees,percent
               padrão: degrees
   precision   Tipo dos mapas de saída de direção e
declividade de encosta
               opções: CELL,FCELL,DCELL
               padrão: FCELL
  pcurvature   Name for output profile curvature raster map
  tcurvature   Name for output tangential curvature raster
map
          dx   Name for output first order partial
derivative dx (E-W slope) raster map
          dy   Name for output first order partial
derivative dy (N-S slope) raster map
         dxx   Name for output second order partial
derivative dxx raster map
         dyy   Name for output second order partial
derivative dyy raster map
         dxy   Name for output second order partial
derivative dxy raster map
      zscale   Multiplicative factor to convert elevation
units to horizontal units
               padrão: 1.0
   min_slope   Minimum slope value (in percent) for which
aspect is computed
               padrão: 0.0
ERROR: r.slope.aspect: Sorry, <e> is not a valid flag
ERROR: r.slope.aspect: Sorry, <n> is not a valid flag
(Wed Jan 29 09:54:55 2020) Comando terminado (0 sec)
```

- The same happen when using the flags in QGIS:
```
r.slope.aspect elevation=rast_5e315419cd03c3 format="degrees" precision="CELL" -e -n zscale=1 min_slope=0 slope=slope1971b91bde9a498686b222b81765955d aspect=aspect1971b91bde9a498686b222b81765955d pcurvature=pcurvature1971b91bde9a498686b222b81765955d tcurvature=tcurvature1971b91bde9a498686b222b81765955d dx=dx1971b91bde9a498686b222b81765955d dy=dy1971b91bde9a498686b222b81765955d dxx=dxx1971b91bde9a498686b222b81765955d dyy=dyy1971b91bde9a498686b222b81765955d dxy=dxy1971b91bde9a498686b222b81765955d --overwrite

Generates raster maps of slope, aspect, curvatures and partial derivatives from an elevation raster map.

Usage:
r.slope.aspect [-a] elevation=name [slope=name] [aspect=name]
[format=string] [precision=string] [pcurvature=name] [tcurvature=name]
[dx=name] [dy=name] [dxx=name] [dyy=name] [dxy=name] [zscale=value]
[min_slope=value] [--overwrite] [--help] [--verbose] [--quiet] [--ui]

Flags:
-a Do not align the current region to the raster elevation map

Parameters:
elevation Name of input elevation raster map
slope Name for output slope raster map
aspect Name for output aspect raster map
format Formato para relatar a declividade
opções: degrees,percent
padrão: degrees
precision Tipo dos mapas de saída de direção e declividade de encosta
opções: CELL,FCELL,DCELL
padrão: FCELL

pcurvature Name for output profile curvature raster map
tcurvature Name for output tangential curvature raster map
dx Name for output first order partial derivative dx (E-W slope) raster map
dy Name for output first order partial derivative dy (N-S slope) raster map
dxx Name for output second order partial derivative dxx raster map
dyy Name for output second order partial derivative dyy raster map
dxy Name for output second order partial derivative dxy raster map
zscale Multiplicative factor to convert elevation units to horizontal units
padrão: 1.0
min_slope Minimum slope value (in percent) for which aspect is computed
padrão: 0.0

ERROR: r.slope.aspect: Sorry, <e> is not a valid flag
ERROR: r.slope.aspect: Sorry, <n> is not a valid flag
```

So, when using the flags in QGIS with GRASS < 7.6, it just does not produce any result, and the log says that -e and -n flags are not valid.

But as they are as False in my PR, they should not break any process on GRASS < 7.6. 

- For instance, if I have a model or script created in QGIS with GRASS <7.6 (**without flags**), it works ok in QGIS with GRASS >=7.6. 

- If I have a model or script created in QGIS with GRASS >=7.6 (**without flags**), it works ok in QGIS with GRASS < 7.6.

- On the other hand, if I have a model or script created in QGIS with GRASS >=7.6 (**with flags**), it seems that it will also work in QGIS with GRASS < 7.6, because QGIS Modeler simply ignores the flags that does not exist.

**Comment by nyalldawson** [comment]
Ok - so the only risk here is user confusion if they try to enable the flags on older GRASS versions and just get the unhelpful message. That's ok with me!

**Comment by PedroVenancio** [comment]
Thank you very much @nyalldawson!

**Pull request merged**
