### PR TITLE
Server standalone threaded version

### PR DESCRIPTION
**Pull request by elpaso**
A threaded version of the standalone development server.

The threads were introduced to handle the incoming connections and serialize the server processing (which remains single-threaded) still avoiding the ugly sleep that we have in the current implementation.

According to my measurements, this version is slightly but consistently faster than the current one.

The core issue with event loops in WMS still remains.

### CODE REVIEW

**Comment by pblottiere** [comment]
@elpaso It works very well thanks :+1:. And I'm sure glad to see the `sleep_for` call going away :).

What do you think about merging this PR as is? I think it's a solid good step and I'd like to propose some improvement which are not directly related to the main subject of this PR (which is the thread support) like:

- adding a dedicated `standalone` directory and splitting the `qgis_mapserver.cpp` file
- adding documentation
- split the `TcpServerWorker` constructors with some methods
- change the output color according to the return code (red/green)
- ...

**Comment by elpaso** [comment]
@pblottiere I'm ok with that (once the spellchecker false positive is fixed). 

The documentation of the standalone is probably ok: https://docs.qgis.org/testing/en/docs/server_manual/development_server.html

The colorized output is also already implemented.

The documentation in the source code could be improved though.

**Comment by pblottiere** [comment]
> The documentation in the source code could be improved though.

Yes that's what I was thinking about.

> The colorized output is also already implemented.

I think I always have a green message even when the return code is 50X. But I'll check again.

**Comment by elpaso** [comment]
> I think I always have a green message even when the return code is 50X. But I'll check again.

well, maybe I've made a mistake in the color code.

**Pull request merged**
