### PR TITLE
Resize number selector widget in Processing

### PR DESCRIPTION
**Pull request by DelazJ**
To avoid this
number_selector

### CODE REVIEW

**Comment by nyalldawson** [comment]
@DelazJ is this still an issue on master?

**Comment by DelazJ** [comment]
Yes, I still get it on my osgeo4w build (8aeffdb457), and whatever Application Style I set (I'm on W10).
Note that I couldn't check whether my commit solves it as I can't build on windows.

**Comment by nyalldawson** [comment]
I can confirm that this PR... does **not** fix the issue in windows (or any variant of this pr which i've tested)

**Comment by DelazJ** [comment]
Ok thanks Nyall.

**Pull request closed without merging**
