### PR TITLE
fix open form button not always enabled in relation reference widget

### PR DESCRIPTION
**Pull request by 3nids**
when the underlying model has more feature than what the model fetches by default (100),
the feature is not fetched yet when the combobox has its index changed

the new signal allows to be aware when the feature is ready to be used

with unit-test 💪

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]
Code looks good.
As discussed, moving this to a signal in the model directly would be even nicer.

**Comment by 3nids** [comment]
thanks for the review, logic moved to the model

**Comment by 3nids** [comment]
better version in #42311

**Comment by 3nids** [comment]
After more thoughts, I think this version is better as it avoids extra signal emittance in the other PR

**Pull request merged**
