### PR TITLE
[PyQt6] Make PyQtcompat compatible with any Qt version

### PR DESCRIPTION
**Pull request by troopa81**

### CODE REVIEW

**Comment by nyalldawson** [comment]
Did you consider making a seperate copy of these files like we do for the sip ones? I'm thinking there's going to be a lot of compatibility patches in the pyqt6 ones and it might be cleaner to keep them seperated

**Comment by troopa81** [comment]
Well, actually there is an issue with this PR. It looks like that QVariant.Int is not exactly the same as QMetaType.Type.Int


```python
>>> QVariant(QVariant.Int) == QVariant(QVariant.Int)
True
>>> QVariant(QVariant.Int) == QVariant(QMetaType.Type.Int)
False
```

**Comment by troopa81** [comment]
> Well, actually there is an issue with this PR. It looks like that QVariant.Int is not exactly the same as QMetaType.Type.Int

Actually I think this is only an issue with the default constructed variant. I propose to fix it this [way](https://github.com/qgis/QGIS/pull/55611/commits/7305aa722b2c74da274c955e9bbd0e7516421bd1) for now

**Comment by nyalldawson** [comment]
> I think it's easier to maintain only one set of file with all the logic in it than 2 where you have to split the logic.

Ok, sounds good!

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
