### PR TITLE
More locale fixes

### PR DESCRIPTION
**Pull request by SrNetoChan**
## Description

There are lots of places, where if you try to use comma as the decimal separator (as expected from your locale settings), you get wrong results from text.toDouble()

I am searching for text.toDouble() references in the code, confirm that it has issues, fix them and confirm again.

Some cases I can't see the error, but I believe it still lead to problems.

### CODE REVIEW

**Comment by elpaso** [comment]
@SrNetoChan I think that you also need to add the QgsDoubleValidator to the edit widget when it's missing.

**Comment by SrNetoChan** [comment]
@elpaso do you mean like this:

https://github.com/qgis/QGIS/blob/6e941f13f8ecba6df207f60dc26810f4eb0203b2/src/gui/qgsrasterlayersaveasdialog.cpp#L706

**Comment by elpaso** [comment]
> @elpaso do you mean like this:
> 
> https://github.com/qgis/QGIS/blob/6e941f13f8ecba6df207f60dc26810f4eb0203b2/src/gui/qgsrasterlayersaveasdialog.cpp#L706

Yes. Give it a try.

**Comment by elpaso** [comment]
@SrNetoChan wait a minute: I think you must set a parent or it will leak, I see that there are other places in the code where it is used without a parent :/

```c++
lineEdit->setValidator( new QgsDoubleValidator( lineEdit ) );  // <- set lineEdit as parent
```

**Comment by elpaso** [comment]
... and ```new QIntValidator( nullptr )``` as well

**Comment by SrNetoChan** [comment]
But integers don't give problems with locales, or does it?

**Comment by elpaso** [comment]
You still have thousands separator

**Comment by nyalldawson** [comment]
@SrNetoChan is this still a draft? If so, can I close until it's ready for review and merge?

**Comment by SrNetoChan** [comment]
@nyalldawson sure. I need to find time to complete it. Meanwhile, there's no need for keeping it open.

**Comment by nyalldawson** [comment]
@SrNetoChan thanks!

**Pull request closed without merging**
