### PR TITLE
Improved point displacement fonts

### PR DESCRIPTION
**Pull request by roya0045**
## Description

Similarly to what has been done with the layout label, this PR aims to provide more control on the label generated by the displacement point render to improve with contrast.

To do this the label  data is now a QgsTextFormat and should support more effects. 

This handles existing project safely.

The only issue observed is when loading save symbology, but I'm unsure if this is related to the changes as the issue appears be related to the lack of name styled in the database, rather than unsupported settings.

### CODE REVIEW

**Comment by roya0045** [comment]
Not sure why the tests are failing or how my changes affected the storing of the subrender, how QgsTextFormat handles a QFont or how projects are read. Wiil try to figure it out.

**Comment by roya0045** [comment]
Need to figure out why test fail, locally thing behave fine.

**Comment by roya0045** [comment]
Still not sure what fails...

**Comment by roya0045** [comment]
Ok it seems that saving to xml style and loading it does lose the stylename but the style itself is properly loaded back. I'm unsure if the issue is rooted in `QgsTextFormat`, regardless I'm trying the new font util to see if that fixes the issue of losing the name, otherwise will have to find a workaround.

**Comment by roya0045** [comment]
Just noticed that setting the text colour in the textformat widget doesn't work when it's in the layer styling doesn't work and isn't handled when loading back the xml..though the colour is saved fine.

**Comment by roya0045** [comment]
No clue why Ming or server test failed, but finally all works fine now.

**Comment by roya0045** [comment]
works as intended.

**Comment by roya0045** [comment]
Failures are unrelated.

**Comment by roya0045** [comment]
Should be fine

**Comment by roya0045** [comment]
Pr works as intended

**Comment by roya0045** [comment]
updated test

**Comment by roya0045** [comment]
Unrelated test failure

**Comment by roya0045** [comment]
test failure are unrelated

**Comment by roya0045** [comment]
Unrelated test failure

**Comment by roya0045** [comment]
awaiting review

**Comment by roya0045** [comment]
awaiting review

**Comment by roya0045** [comment]
awaiting review

**Comment by roya0045** [comment]
need to rerun cli tests

**Comment by roya0045** [comment]
same as previous

**Comment by roya0045** [comment]
unchanged state

**Comment by nirvn** [comment]
@roya0045 , just close the PR for now, it's not useful to have open PRs that have zero momentum and in need of additional work.

**Pull request closed without merging**
