### PR TITLE
Second attempt to fix raster magnify

### LINKED ISSUE #45336: Magnifier Doesn't Magnify but Instead Just Changes Scale
### What is the bug or the crash?

Locking the scale and then changing the magnification doesn't lock the scale and then magnify the image. Instead, it just updates the scale. So, for instance, if you are trying to read street names on OSM and you want to zoom in, it fails to zoom in. Instead it appears to perform a network request for an updated image. For instance if you set the scale to 1:10000, lock it, and then magnify by 200% you get the same view as if you just selected 1:5000 scale. Very briefly, a magnified view appears but then it is replaced with a new view scaled as described.

If you install the QGIS Network Logger you can see the network requests going out as you increase the magnification.

The expectation is that there would not be any new network request, but only that the cached image be magnified.

### Steps to reproduce the issue

1. Start a new, clean project.
2. Add OpenStreetMap layer.
3. Add the QGIS Network Logger plugin
4. Click the QGIS Network Logger button. The logger appears.
5. Zoom to a city or town with some reasonably dense streets.
6. Set the scale to 1:10000
7. Click the lock scale.
8. Note the size of the street name text.
9. Click the "Clear" button in the QGIS Network Logger panel
10. Change the magnification to 200%
11. The canvas will briefly, magnify, increasing the text size, then go blank as then the Network Logger will show a request going out to update the canvas. The canvas will update and the text size will shrink again.
12. Take careful note of the extents and the sizes of objects displayed.
13. Now reset the magnification back to 100%
14. Unlock the scale.
15. Now select the 1:5000 scale.
16. Note the view is identical to the the locked 1:10000 scale at 200% magnification.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85be9
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
Compiled against PDAL | 1.8.0 | Running against PDAL | 1.8.0 (git-version: Release)
PostgreSQL Client Version | 11.11 (Debian 11.11-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | nominatim_locator_filter; QuickOSM; geometry_paster; quick_map_services; joinmultiplelines; profiletool; coordinates_converter; zoomview; qgisnetworklogger; latlontools; db_manager; MetaSearch; processing

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Here is how the 3.16 documentation describes how the magnifier should work:

> On the right side of the scale display, press the lockedGray button to lock the scale to use the magnifier to zoom in or out. The magnifier allows you to zoom in to a map without altering the map scale, making it easier to tweak the positions of labels and symbols accurately. The magnification level is expressed as a percentage. If the Magnifier has a level of 100%, then the current map is not magnified. Additionally, a default magnification value can be defined within Settings ► Options ► Rendering ► Rendering behavior, which is very useful for high-resolution screens to enlarge small symbols.

Clearly, the scale is not staying unaltered as is described above.

Note: Some people (myself included) have a very difficult time reading text and discerning auto-scaling detail if we can't magnify it! It can be pretty frustrating.

Thanks for your consideration of this issue. QGIS is a brilliant piece of opensource software! The efforts of the QGIS team are not taken for granted!

### PR DESCRIPTION
**Pull request by elpaso**
Fix #45336

### CODE REVIEW

**Comment by m-kuhn** [comment]
Nice, tested an works like a charm !

**Review by m-kuhn — APPROVED** [review]

**Comment by elpaso** [comment]
@m-kuhn thanks for testing, I just wonder if that's the right place to set it: wouldn't be better to set the target dpi it in the mapsettings directly?

**Comment by m-kuhn** [comment]
You mean a `targetDpi()` method that does the calculation inside mapsettings already? @nirvn ?

**Comment by m-kuhn** [comment]
Sidenote, I think it would also be nice to have a setting for individual raster layers that determines the layer dpi. So the user is free to mix and match normal and hidpi raster layers with vector layers in a project without ever touching the magnification factor.

**Comment by elpaso** [comment]
> You mean a `targetDpi()` method that does the calculation inside mapsettings already? @nirvn ?

Maybe here: https://github.com/qgis/QGIS/blob/master/src/core/qgsmapsettings.cpp#L49

In that function the `mDpi` is adjusted but the `targetDpi` is left untouched.

**Comment by elpaso** [comment]
Of course, the more up in the stack we move that setting the higher are the chances of side effects, we might be safer with my current approach.

**Comment by nyalldawson** [comment]
@elpaso @m-kuhn 

I propose the simpler approach instead used in https://github.com/qgis/QGIS/pull/46816

**Comment by elpaso** [comment]
Closed in favor of #46816

**Pull request closed without merging**
