### PR TITLE
Overwrite existing boundingBoxes with the same CRS in WMS capabilities.

### PR DESCRIPTION
**Pull request by Roel**
Override existing boundingBoxes (originating f.ex. from parent layers) with boundingBoxes from current layer, which are more specific.

### CODE REVIEW

**Comment by Roel** [comment]
I though about this some more and got to the point where I have some questions. Currently I overwrite all existing boundingBoxes with the same CRS when a new BoundingBox is found. Maybe it's cleaner to remove the previous boundingBoxes with that CRS rather than overwriting them, although that's less efficient because of resizing the vector.

Or it might be better to leave the boundingBoxes vector consistent with the appearance in the capabilities and loop through all of them further down in the code, rather than breaking at the first match.

Thoughts? Thanks!

**Comment by rduivenvoorde** [comment]
Hi Roel, still willing to merge this? 

I'm not sure why it Failed the Travic Cl build, but if I understand correctly your patch makes a wms layer have better bbox's because a more finegrained bbox can be available in the capabilities?

Do you maybe have an online example for that? So dev's can check?

And if you have a Pull Request like this and it is not picked up by anybody, please just ask on the dev list if people can have a look into it.

**Comment by Roel** [comment]
Hi Richard, off course, the patch still applies.

It is the implementation of the following excerpt from OGC's WMS implementation guide (1.3.0, page 27): 
> A Layer inherits any BoundingBox values defined by its parents. A BoundingBox inherited from the parent Layer for a particular CRS is replaced by any declaration for the same CRS in the child Layer."

An example can be found in the Mercator WMS: https://www.mercator.vlaanderen.be/raadpleegdienstenmercatorpubliek/wms?request=GetCapabilities

All layers are effectively sublayers of the main 'Mercator Publieke View Service' layer, which defines its own bounding box (which is the extent of the layers beneath it). If you add one of the sublayers in QGis, the first bounding box matching the CRS you're using is selected, in casu this is always the one of the 'Mercator Publieke View Service' layer. My patch fixes this by using the bounding box of the sublayer if there is one available (cfr. specs cited above).

Steps guide to reproduce:
* Set the CRS of your QGis project to EPSG:31370
* Add the WMS: https://www.mercator.vlaanderen.be/raadpleegdienstenmercatorpubliek/wms?request=GetCapabilities
* Add the layer ps:ps_duin
* Without the patch the first matching bounding box is used, showing the (yellow) map small in the center of the screen.
* With the patch applied the bounding box of the sublayer is used, showing the full extent of the layer on the screen.

**Comment by nyalldawson** [comment]
@wonder-sk @rouault You're both probably best placed to review this. Can you have a look and close if the fix isn't valid?

**Comment by m-kuhn** [comment]
Wait... can I write into a range based for loop?

```
for ( auto &bbox : myBboxes )
{
    bbox.crs = myCrs;
}
```

**Pull request closed without merging**
