### PR TITLE
[processing] Restore some gdal provider algorithms

### PR DESCRIPTION
**Pull request by nyalldawson**
Brings back support for GDAL algorithms, and ports the warp and points along lines algorithms.

### CODE REVIEW

**Comment by nirvn** [comment]
Wouhou!

**Comment by gioman** [comment]
@nyalldawson Hi Nyall, many thanks for this. As I make a point of trying to contribute/maintain those tools (and I have plans to add more), are the changes needed for QGIS 3 just those two lines  (1 change, 1 new line) I see in this commit?

**Comment by m-kuhn** [comment]
@nyalldawson is there anything left to discuss for this PR?

**Comment by nyalldawson** [comment]
I need to update the tests before I'm comfortable merging this. I'll work on it :)

**Pull request merged**
