### PR TITLE
Partially revert 596ffd06

### PR DESCRIPTION
**Pull request by nyalldawson**
Just to see if this is throwing off Travis...

### CODE REVIEW

**Comment by nyalldawson** [comment]
Hmm -- so it IS this change which has killed Travis.

**Comment by 3nids** [comment]
yeah, I was reading more info on QT5_ADD_RESOURCES...

**Comment by nyalldawson** [comment]
Maybe we could limit this inclusion to the single picture test it's required for?

**Comment by 3nids** [comment]
I think we should use autorcc
https://cmake.org/cmake/help/v3.15/prop_tgt/AUTORCC.html#prop_tgt:AUTORCC
will push to this branch

**Comment by nirvn** [comment]
@3nids , you should stream your struggle on twitch; man vs machine :wink:

**Pull request merged**
