### PR TITLE
[server][bugfix]  Fix parameter decoding with post method and urlencoded 

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

During its tests with QWC2, @elemoine reported another issue. 

Actually, when a POST request is sent with `Content-Type: application/x-www-form-urlencoded`, parameters are not correctly decoded and it leads to this kind of error coming from QGIS Server:

```
$ curl --request POST \
       -H "Content-Type: application/x-www-form-urlencoded" \
       "http://localhost/qgisserver?" \
       -d "...&LAYERS=Hello,Country&OPACITIES=125%2C125" 

<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc">
 <ServiceException code="Invalid WMS Parameter">OPACITIES ('125%2C125') cannot be converted into a list of int</ServiceException>
</ServiceExceptionReport>
```

This PR fixes this issue.

I took the opportunity to add some tests for `GetPrint` and `OPACITIES` parameters (there were none).

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rldhont** [comment]
@pblottiere in which order do your want to merge your PR ?
I am also working on QGIS Server and have some tests to add.

**Comment by pblottiere** [comment]
> in which order do your want to merge your PR ?

I don't care, I'll rebase if necessary :). I just want the approval of Matthias to merge the PR on flaky tests.

**Comment by pblottiere** [comment]
@rldhont Do you agree with this PR? Can I merge as soon as Travis is green again?

**Comment by pblottiere** [comment]
Travis is green! @rldhont do you agree to merge this PR?

**Review by rldhont — APPROVED** [review]

**Pull request merged**
