### PR TITLE
[FEATURE] New decoration type for showing composer map extents

### PR DESCRIPTION
**Pull request by nyalldawson**
Adds a new (disabled by default) decoration item for showing the extents of composer maps in the main canvas. When enabled, the extents of all maps within all composers will be shown using a lightly dotted border. The border symbol is configurable for improved legibility against different map backgrounds.

I was missing this a lot last week, while working on a labeling heavy map. I needed a way to see the actual visible page extents so that I could ensure that labels were nicely placed with respect to the map edges. This seems like an elegant approach as it avoids UI clutter and is totally opt-in.

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , this is great, good job.

**Comment by nirvn** [comment]
Working well:
nice

It'd be really useful to have some (optional?) label to know which composer is which.

**Comment by DelazJ** [comment]
Would be for sure useful. Thanks @nyalldawson 
Thinking out-loud too: c/would a next step be updating composer map extent by moving/resizing this new decoration from within the map canvas?

**Comment by nirvn** [comment]
I'd be reluctant to add any kind of interactivity to canvas decorators.

**Comment by timlinux** [comment]
Nice one @nyalldawson !

**Comment by 3nids** [comment]
Awesome! How does it work with atlas composers? It shows the last extent or is it discarded? 

What about being able to limit this to currently open composers? Or render those open differently?

**Comment by nyalldawson** [comment]
> It'd be really useful to have some (optional?) label to know which composer is which.

I'm not sure how to handle this. There's going to be many cases where projects have multiple composers which cover the same extents, so we'd end up with overlapping text (and it'd be overkill to add collision detection!). I guess if we limited it to open composers that might help....

> Awesome! How does it work with atlas composers? It shows the last extent or is it discarded?

It'll show whatever the current extent is for the map - so if you're paging through an atlas, it'll show whatever the current page extent is.

**Comment by nyalldawson** [comment]
Unrelated OSX test failure...

**Comment by nirvn** [comment]
@nyalldawson , brilliant stuff, thanks for adding labels.

On the test failure, should we not disable OSX build again? It pretty much fails 50% of the time, not very useful at this stage.

**Pull request merged**
