### PR TITLE
Add test for tesselated normals when input coordinates do not share same z value

### PR DESCRIPTION
**Pull request by nyalldawson**
@wonder-sk 

Been trying to work out why the top surfaces are missing for me - the results for this test look wrong for the first two triangle normals (e.g. those corresponding to the top surface)

I suspect we have an issue with the normal calculation in the non-planar situation too..

### CODE REVIEW

**Comment by wonder-sk** [comment]
Thinking more about this, I feel that handling this general case of polygons is going to be very tricky. While in this example we have still nearly planar polygon, what if we are asked to process polygons potentially spanning multiple planes, e.g. roof + wall? In those cases, we may need to subdivide such polygons until their pieces are not planar. Therefore I am wondering if this task is not ill-defined. While for planar polygon we do not need to worry about interpolation, here we probably should worry about that.

The question is - shall we try to do at least some effort to display such geometries - and is it worth it? (i.e. is it a common scenario that people would have this kind of input geometries?)

**Comment by nyalldawson** [comment]
> The question is - shall we try to do at least some effort to display such geometries - and is it worth it? (i.e. is it a common scenario that people would have this kind of input geometries?)

Depends which non-planar geometries you're referring to. If it's the ones generated by the "vertex" mode, then we definitely need to handle these correctly (or drop the vertex mode, which would be a shame). 

If it's non 2.5d input geometries, then I'd say we leave that as unsupported for now.

I think the problem here is that the normal for the "roof" is calculated once per input geometry, instead of once per triangle (ignoring the wall calculation, which is fixed now). I may be over-simplifying things, but I think fixing this is "just" a matter of calculating the normal for each roof triangle and ensuring it is upward facing.

**Comment by wonder-sk** [comment]
> I think the problem here is that the normal for the "roof" is calculated once per input geometry, instead of once per triangle (ignoring the wall calculation, which is fixed now). I may be over-simplifying things, but I think fixing this is "just" a matter of calculating the normal for each roof triangle and ensuring it is upward facing.

I am afraid with the current implementation it is a bit of a chicken-and-egg problem to calculate normal for each triangle, because first we need to compute at least approximate plane for the polygon and reproject coordinates to be able to do the triangulation.

Maybe what we could do is to check whether all vertices of a polygon are in just one plane, and only if they are, do the reprojection to the new base given by the new X/Y/Z base vectors (so that we can run the 2D triangulation). In case not all points are in one plane we could say it is "roof", do not do any reprojection, just run the 2D triangulation and as the final step calculate normals for each triangle separately? So we would end up with three cases for one polygon:
1. all points in horizontal plane - no reprojection, all normals straight up
2. all points in non-horizontal plane (wall or slanted roof) - find out the plane, reprojection, all normals according to the plane
3. points are not in a plane - no reprojection, normals calculated for each triangle

Would that approach make sense to you?

**Comment by nyalldawson** [comment]
Just rebased to check - this is still an issue on master

**Comment by nyalldawson** [comment]
Closing this... Can't remember if this test was finished or not. I'm not sure why it's passing now (when I don't think the underlying issue has been fixed), so I suspect I never finished the test correctly.

**Pull request closed without merging**
