### PR TITLE
Group layer items in map composer properties

### PR DESCRIPTION
**Pull request by DelazJ**
see https://github.com/qgis/QGIS/pull/3064#issuecomment-219948349
composermap

### CODE REVIEW

**Comment by nyalldawson** [comment]
@DelazJ what do you think about moving this new group out of the "main" group? I think nested groups get really confusing quickly. Otherwise +1 from me

**Comment by nirvn** [comment]
Agreeing with @nyalldawson , it should be moved out to be its own group.

Nice fix.

**Comment by DelazJ** [comment]
@nyalldawson Will do it given that I hesitated earlier to do so
Do you think that I should remove "for map item" text at the end of layer style options as suggested by @3nids

**Comment by DelazJ** [comment]
That said, wouldn't it be weird to have "Draw map canvas items" somehow isolated? They're also related to what could be shown in the map item.

**Comment by DelazJ** [comment]
group moved
composermap2

**Comment by DelazJ** [comment]
looks like https://github.com/qgis/QGIS/commit/9d1102207537d0766830e97ce435185b1d635587 does the job

**Pull request closed without merging**
