### PR TITLE
[ui] improve gps tools icon

### PR DESCRIPTION
**Pull request by nirvn**
untitled
_before (left), proposed (right)_

The GPS Tools icon was in need of a refresh to harmonize it with its toolbar siblings :smile:

### CODE REVIEW

**Comment by NathanW2** [comment]
The drop down arrow on the Create Layer one bugs the hell out of me.  (I know it's because of the button style)

**Comment by nirvn** [comment]
@NathanW2 yeah, that's a qt theme positioning, nothing can be done here. That said, it's not as bad for people who have that toolbar located horizontally.

**Comment by NathanW2** [comment]
True.

Won't be so bad when we get rid of the other icons.

**Comment by nyalldawson** [comment]
@nathanw2 can't click on the right button, so I will :P

**Comment by NathanW2** [comment]
@nyalldawson seems I can't click on anything right today. Lucky it's almost end of day.

**Pull request merged**
