### PR TITLE
[themes] Fix Night Mapping checkbox and radiobox not friendly to colour blindness

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR insures that the night mapping theme is friendly to/compatible  with people experiencing colour blindness by adding a glyph within the checkbox and radiobox in addition to the green color highlight shading.

In action:
image

@AlisterH , this achieves what you were aiming at in #52971 while trying to better match/respect the preexisting styling choices of Night Mapping which results in checkbox and radiobox widgets not taking over the attention too much.

(For background, see https://github.com/qgis/QGIS/issues/49775)

### CODE REVIEW

**Comment by nirvn** [comment]
Bonus: layer tree indicators are now clearly visible.

Before:
Screenshot from 2023-08-06 13-37-24

PR:
Screenshot from 2023-08-06 13-36-59

**Comment by nirvn** [comment]
@LorenAmelang , can you confirm this is an improvement for you?

**Comment by DelazJ** [comment]
> Bonus: layer tree indicators are now clearly visible.

@nirvn can you elaborate on the differences. Look like the same images to me.

**Comment by nirvn** [comment]
@DelazJ , look at the filter indicator for the "restricted areas" layer.

**Comment by LorenAmelang** [comment]
> @LorenAmelang , can you confirm this is an improvement for you?

Yes, I can see the bright white dot in "Qt default" and the white checkmarks in "Show news" and "Check version" and other options. Solves the issue I wrote about! Not sure what the "layer tree indicators" are about...  Guess I haven't used that in my projects. 

Thanks!

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
