### PR TITLE
Add an optional "Silent" flag for QgsTask, which hides the operating system level success/fail notifications for that task

### PR DESCRIPTION
**Pull request by nyalldawson**
And don't show these notifications for some non-important tasks, like the news feed fetching

### CODE REVIEW

**Comment by nyalldawson** [comment]
@3nids I'd love your insight here -- the test is failing because QgsTask.CancelWithoutPrompt | QgsTask.CanCancel returns an int value, not a QFlags value. I can't see why this is happening, and comparison with PyQt5 types like Qt::Alignment shows different behaviour (possibly because the Qt5 types aren't enum classes). 

Have we had to handle this elsewhere when moving flags to enum classes?

**Comment by nyalldawson** [comment]
Ping @3nids --  any ideas on this one?

**Comment by 3nids** [comment]
sorry for the delay, lost in notifications.

I think you are forced to call the constructor of the flags since there is no implicit conversion.

If that's not an acceptable API break, I see only these options:
* write a method code to call QFlags constructor on the argument (if it's an int it will convert it, if it's already a QFlag, it's not an issue)
* have an overloaded method with int argument using the QFlags constructor to call the other overloaded method. And tag the method as deprecated.
* write conversion code for int <-> flag. I am not sure if this would properly work.

I'd go for the second option since it's plain cpp.
The first one could be done with sipify....but it's not trivial, and I think it's not worth the effort.
The last one might be a valid alternative, but again it's writing sip(ify) code. Getting tired of that.

**Comment by nyalldawson** [comment]
@3nids I just rolled that part back -- I couldn't solve the api break, even with overloads for int (I can't add those in all circumstances due to default argument ordering etc)

**Pull request merged**
