### PR TITLE
Ensure that all classes derived from QObject have Q_OBJECT macro

### PR DESCRIPTION
**Pull request by nyalldawson**
Ok... just putting this one out there. I'm not 100% sure on it myself, but want to see what other's thoughts are.

What this does is ensures that EVERY class derived from QObject has the Q_OBJECT macro (+all the changes required to get QGIS to build again with these changes). I realise that Q_OBJECT is only strictly required when the class uses signals/slots, 

BUT

Missing Q_OBJECT macros have been the cause of at least 1 critical bug (http://hub.qgis.org/issues/13162). This caused 2.10 to be basically unusable on OSX, and the solution (https://github.com/qgis/QGIS/commit/9b9dbff13dd3ff20c3746fc175d59c29bf401c26) was adding the missing Q_OBJECT macro (even though signals/slots weren't used by the class). 

The fact that this bug was so severe, yet somehow remained dormant through a number of releases until some unrelated change (or possibly platform/qt change) triggered it makes me nervous. That's why I'm leaning toward just playing it safe and adding the Q_OBJECT macro to all derived classes.

I'm hoping maybe as a result we squash some of the weird OSX issues we have (eg http://hub.qgis.org/issues/13338). Worst case scenario this fixes nothing, but makes the code safer if q_object casting is ever used in future on these classes.

Opinions welcome ;)

### CODE REVIEW

**Comment by m-kuhn** [comment]
Not sure about all the implications, but looking at [the api doc](http://doc.qt.io/qt-5/qobject.html) it hints quite clearly that the `Q_OBJECT` macro should be use for all QObjects.

> Notice that the Q_OBJECT macro is mandatory for any object that implements signals, slots or properties. You also need to run the Meta Object Compiler on the source file. We strongly recommend the use of this macro in all subclasses of QObject regardless of whether or not they actually use signals, slots and properties, since failure to do so may lead certain functions to exhibit strange behavior.

**Comment by nyalldawson** [comment]
Ok, guess it's worth the time for me to fix the warnings then!

**Comment by nyalldawson** [comment]
@wonder-sk @jef-n What's your thoughts on this? 

Downsides:
- clutter in header (classes which were private or defined only in the cpp files have had to be moved to public classes in the header. That said, they still aren't being exported)
- slightly slower compilation as there's a handful of extra moc files to process

Upsides:
- hopefully fixes some obscure existing bugs (eg OSX issues like http://hub.qgis.org/issues/13338)
- potentially avoids future bugs if these classes are qobject casted or utilise signals/slots in future.

**Comment by m-kuhn** [comment]
@nyalldawson can't we keep them in .cpp? I think in the tests that also works.

**Comment by m-kuhn** [comment]
See e.g. here 
https://github.com/qgis/QGIS/blob/master/tests/src/core/testqgscomposerutils.cpp#L30
and here
https://github.com/qgis/QGIS/blob/master/tests/src/core/testqgscomposerutils.cpp#L719

**Comment by nyalldawson** [comment]
Merged in 08ab4d4b70907523cf67c9afa7aa6ded7184c757

**Pull request closed without merging**
