### PR TITLE
[FEATURE] Layer tree indicator for layers with joined fields

### PR DESCRIPTION
**Pull request by domlysz**
Shows a join icon in the layer tree for all layers that have joined fields. A tooltip display the names of the layers from which the joined fields come. This feature help the user to have a quick overview of layers that depends on others layers and should help having a better understnding of the project organization.

### CODE REVIEW

**Comment by nirvn** [comment]
@domlysz , interesting feature. Quick comment regarding the icon: indicator icons are outline only (ie no gray fill) and ideally 1px outline do aim at ideal pixel alignment.

**Comment by nirvn** [comment]
One UX suggestion: a left click on the join indicator should open the layer properties dialog with the join panel focused.

**Comment by domlysz** [comment]
Hi Mathieu, glad to see you here !

I must admit I dit not found how to open the properties dialog with a focus on a specificic tab, that's why I did not implement the onIndicatorClicked() function. Here the [showLayerProperties()](https://qgis.org/api/classQgisInterface.html#aaec54c2568f7416cf143c10222b4b631) signature.

I will update the icon. Thank you for the feedback.

**Comment by elpaso** [comment]
I think that  "filtered" indicator is very useful (not so sure about the "locked" indicator), but I totally agree with @3nids that we should not overcrowd that tiny space with too much information and we should try to stick to the most common use cases (that in absence of statistics and UX tests are hard to tell anyway).

**Comment by domlysz** [comment]
About my use case, I have some huge qgs projects with lot of layers that extensively rely on joins and it can be difficult to have a good overview of joins relations and layers inter-dependencies, even more if the project come from a third party. This kind of indicator can be usefull to quickly see what happen here without opening each layers properties dialog.

I seems to me that joining data is a very common operation, much more than defining action, relation or dependency. It can justify an indicator for joins and not for these others properties, but I must aggree that this feeling come only from my own experience.

**Comment by 3nids** [comment]
Thanks for your feedback. And yes I tend to think that is your use case.
We can wait for others to give feedback here. But I see these ways of integrating this:

* creating 2 categories of indicators: permanent and secondary. Secondary would be either visible on mouse over or in a collapsable row
* having optional indicators that user would choose (not a big fan of having too many options)
* adding your own indicator with a plugin

@wonder-sk thoughts?

**Comment by domlysz** [comment]
What about adding this kind of relationship informations in the layer tooltip ?

**Comment by domlysz** [comment]
What about adding this kind of relationship informations in the layer tooltip ?

**Comment by domlysz** [comment]
What about adding this kind of relationship informations in the layer tooltip ?

**Comment by domlysz** [comment]
What about adding this kind of relationship informations in the layer tooltip ?

**Comment by domlysz** [comment]
What about adding this kind of relationship informations in the layer tooltip ?

**Comment by domlysz** [comment]
What about adding this kind of relationship informations in the layer tooltip ?

**Pull request closed without merging**
