### PR TITLE
Feature: Add toolbutton to "Deselect Features from the Current Active layer"

### LINKED ISSUE #31598: deselect features of the active layer
hello,

it would be useful, if i could deselect features of the active layer (with an new button in the select menu?). at the moment i can do this only if i open the attributetable and click the deselect button. this is not a short way and for large tables painful.

and additional it would be cool if the select menu (from edit menu) also available in the layer contextmenu (right mouseclick). this is little bit inspired from A**GIS ;-)

i hope someone can implement this !? :-)

thank you very much

### PR DESCRIPTION
**Pull request by suricactus**
Pretty much the title.
Peek 2020-03-15 01-55

CODE NOTE: Only the three selection tools were using the `addActions` way of adding actions, so I rewrote them to be the same as the rest of the function.
```diff
- bt->addActions( actionsList )
+ bt->addAction ( singleAction )
```
The function is still extremely ugly and needs some love one day.

Fixes: https://github.com/qgis/QGIS/issues/31598

### CODE REVIEW

**Comment by suricactus** [comment]
I forgot to mention I moved the default `themes/default/mActionDeselectAll.svg` to `themes/default/mActionDeselectCurrentLayer.svg`, and created a new `themes/default/mActionDeselectAll.svg`, which resembles multiple layers. May need to change the icon at other places too.

**Comment by j-lippmann** [comment]
@suricactus thank you for implementing this Feature! It is also available in the layercontextmenu?

**Comment by suricactus** [comment]
I don't think it should be, as there is a dedicated toolbar button for that, as well in the menu "Edit->Select->Deselect Features from the Current Active layer".  For users who need that, they can always use a shortcut, much easier.

Which brings the discussion, as "Ctrl+A" selects all the features in the current layer, I believe "Ctrl+Shift+A" should do the opposite (deselect from the current layer only), not deselecting from all layers. This would be another breaking change, which the core developers should approve.

**Comment by nyalldawson** [comment]
Looks good to me! @nirvn any UI thoughts?

**Comment by nirvn** [comment]
I'm fine with it, I'm sure it'll please quite a few users out there :smile:

**Comment by DelazJ** [comment]
In the attribute table, the icon used should be the deselectActiveLayer and not the deselectalllayers
image

**Comment by pigreco** [comment]
Please add `GUI/UX` label

**Comment by DelazJ** [comment]
@pigreco, `gui/ux`, `temporal`and others are used to build the changelog? Or what are the reasons of your requests?

**Comment by pigreco** [comment]
> @pigreco, `gui/ux`, `temporal`and others are used to build the changelog? Or what are the reasons of your requests?

Exactly, to build and order changelogs faster, thanks

**Pull request merged**
