### PR TITLE
Make first layer selected on project load

### PR DESCRIPTION
**Pull request by elpaso**
just spare a click

### CODE REVIEW

**Comment by nyalldawson** [comment]
+1 million. I always get confused why a bunch of actions are disabled after loading a project for this very reason.

**Comment by rduivenvoorde** [comment]
Yes, yes, yes! Thanks @elpaso this kind of 'papercuts' make QGIS better!

.... can I add another idea: at this moment when you delete a layer from the layer tree, you loose 'currentlayer/selection': nothing else is selected/current anymore the. While often in my workflow, I for example have to delete a couple of layers
So it would be handy (and I think more intuitive, looking at other programs), to move the selection to the layer below the old selection, unless there is not layer below, then move the selection to the layer above (if available).
Others agree with this? Happy to make a separate FeatureRequest for it, but if I'm the only one having this, I'll rest my case :-)
I also can imagine that you open a can of worms with this, when you have a complicated layerlist with groups etc...

**Comment by elpaso** [comment]
@rduivenvoorde +1 for a separate feature request

**Comment by rduivenvoorde** [comment]
Ok, done: https://issues.qgis.org/issues/18564

**Pull request merged**
