### PR TITLE
Hide geometry validation dock

### PR DESCRIPTION
**Pull request by m-kuhn**
@nirvn @agiudiceandrea 

could you give this patch a try, I am failing to reproduce the visualization problem here, so I would be glad for a check from your side if possible.

Fix #20245 https://issues.qgis.org/issues/20245

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
Unfortunately for the moment I cannot test the patch before it's merged and a nightly release is built.

**Comment by m-kuhn** [comment]
Let's hope @nirvn can validate this. Unfortunately I cannot reproduce it on my system, so I have no idea if this patch actually works.

**Comment by nirvn** [comment]
@m-kuhn , building now.

**Comment by nirvn** [comment]
@m-kuhn , can't see the ghost window anymore with a build including this commit.

**Comment by agiudiceandrea** [comment]
@m-kuhn, thanks to your patch, the issues is now fixed in QGIS 3.4.1!

**Pull request merged**
