### PR TITLE
Convert CODING document to markdown

### PR DESCRIPTION
**Pull request by m-kuhn**
This enhances the CODING document with markdown elements. This gives a few enhancements.
- Directly is formatted when opened on github
- TOC with links
- Syntax highlighting

Apart from this, there are some small fixes here and there.

Two open questions:
- Should it be rst? @rduivenvoorde would like it to be translatable. However I didn't manage with a quick try.
- There are images linked in section 4 (QtCreator). This indicates that the previous document was compiled and included somewhere else. So this PR might break things. @timlinux might know more concerning this.

### CODE REVIEW

**Comment by m-kuhn** [comment]
@timlinux assigned you so you can give a feedback concerning the images.

**Comment by timlinux** [comment]
Hi @m-kuhn 

Sorry for the slow reply. The canonical source for this document is actually doc/CODING.t2t, so I would suggest rather replacing that with your .md file and generating CODING from it.

Regards

Tim

**Comment by m-kuhn** [comment]
True.
I'll happily move it there if others agree that we should switch from t2t to md (because it is so nice to use md on github :) )
@timlinux What about the images?

**Comment by rduivenvoorde** [comment]
@mhugent  @nyalldawson @timlinux @jef-n @NathanW2 

Hi, just try to stir up some of the PR's here...

to see the result of md in github:

https://github.com/m-kuhn/QGIS/blob/79d12ec219e41618aeee57bba61caa9d09617069/CODING.md#13-c++-files

compared to:

https://github.com/qgis/QGIS/blob/master/CODING

But may I raise the question if it would not be better to move to rst then? This is also rendered (and editable) in Github, AND can also contain images, see

https://github.com/rduivenvoorde/MetaSearch/blob/master/docs/howto.rst

as a plus: this would make it possible to generate html pdf etc from it OR incorporate it in the docs/website

it would also make the number of 'markdowns' used by our project smaller (minus t2t IF we also do the INSTALL file in rst),

AND in my opinion the t2t -> html creation and putting in the doc dir of an installation can be ommitted as we can just add a link to the github page then?

**Comment by timlinux** [comment]
I am +1 to replace t2t markup where needed .... t2t predated the popularity of md and can actually be used to make pdf, html etc. but happy to see it go in favour of markdown.

**Pull request closed without merging**
