### PR TITLE
[bugfix] Restore color picker from layer styling panel

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #17721

Successfully tested on Windows 10 and Linux with Qt 5.10

There might be differences on other platforms or with Qt < 5.10

### CODE REVIEW

**Comment by slarosa** [comment]
@elpaso the issue occurs even on macOS and this PR fixes the problem. Thanks!

**Comment by nyalldawson** [comment]
Works well for me on Windows 10!

While you're at it, I'd suggest removing the left button check when mPickingColor is true in QgsColorButton::mouseMoveEvent. I can't remember why I put that there (i think i was trying to emulate the behavior of GIMP), but I think it's better to always show the color preview when the mouse moves here...

**Comment by elpaso** [comment]
@nyalldawson sure, I wanted to do that but I  was afraid that it was a "feature", right now the two pickers have a complete different behavior.

**Comment by nyalldawson** [comment]
Do it! I'm really not sure what was going through my mind back then...

**Comment by nirvn** [comment]
@elpaso , thanks a million for this.

**Comment by geomenke** [comment]
Thanks @elpaso !

**Pull request merged**
