### PR TITLE
Doxygen Formatting

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR makes the pre commit script automatically convert multiline //! comments to multiline /** ... */ standard.

E.g. 

    //! Stop the rendering job - does not return until the job has terminated.
    //! Does nothing if the rendering is not active.

Becomes

    /**
     * Stop the rendering job - does not return until the job has terminated.
     * Does nothing if the rendering is not active.
     */

(This only applies to multiline comments - single line comments remain at the more compact //! )

Why?

- The /** standard is much more common in QGIS, so flipping everything the other way would be very disruptive.
- sipify doesn't handle multiline //!, dropping all but the last line. That's the main reason for all the added lines in this PR - they are docstrings which were missing from the Python bindings.

### CODE REVIEW

**Comment by 3nids** [comment]
you got some documentation homework for free ;)
https://dash.orfeo-toolbox.org/viewBuildError.php?type=1&buildid=293224

**Comment by nyalldawson** [comment]
This is a bit odd... the fix IS in my branch, see https://github.com/nyalldawson/QGIS/commits/formatting. And travis picked it up and processed it ok: https://travis-ci.org/qgis/QGIS/builds/283507281 !

**Comment by nyalldawson** [comment]
Let's see if a close/reopen fixes this

**Comment by 3nids** [comment]
but the last commit is not in the PR...how come?

**Comment by nyalldawson** [comment]
> but the last commit is not in the PR...how come?

It is if you go to the "commits" tab. Somethings gone screwy with the github frontend here...

**Comment by nyalldawson** [comment]
All green again...

**Comment by nyalldawson** [comment]
Travis failure is just spell check timeout.

Any objections to this change?

**Comment by 3nids** [comment]
not at all

**Comment by nyalldawson** [comment]
> not at all

Ok - given that you're the resident perl/sipify expert, I'll merge :) Thanks!

**Pull request merged**
