### PR TITLE
fix #12027 crash on prepared QgsDataDefined cpy

### PR DESCRIPTION
**Pull request by vmora**
Changed the raw pointer for a QSharedPointer to allow safe cpy.

### CODE REVIEW

**Comment by vmora** [comment]
qgis_ziplayertest fails on Travis, but seems unrelated.

**Comment by vmora** [comment]
@dakcarto can you take this one ?

**Comment by nyalldawson** [comment]
@vmora - I can tackle this. Any reason why you decided to use the shared pointer rather than making a copy of the expression in a copy constructor for QgsDataDefined? I think that would be a more predictable behaviour, since the expressions would not be linked and could then be changed independantly...

**Comment by vmora** [comment]
@nyalldawson I see your point, because the returned ptr from QgsDataDefined::expression is not const. I'd prefer making that a const ptr and keeping the shared internal ptr, but I'm not sure a const expression ptr is usable (because evaluate is not const).

So I guess you'll have to make it a QScopedPtr, code a private swap and implement operator= with cpy/swap. In this case, a prepared QgsDataDefined copy will not be prepared, but it's not a major issue.

Even better: make QgsDataDefined non copyiable, less code, less bugs and a clear statement of the design intend.

I'll let you judge of the desired behavior, but, please, no raw ptr anywhere anymore :)

**Comment by vmora** [comment]
ping @nyalldawson

**Comment by vmora** [comment]
@nyalldawson even if the fix is different, the test part is easy enought to review/merge.

**Comment by vmora** [comment]
ping @nyalldawson

**Comment by nyalldawson** [comment]
I've manually pushed a fix for this, which fixes the crash but means the copied expression is unprepared. It's not great, but better than nothing and can be revisited after QgsExpression is made implicitly shared.

**Pull request closed without merging**
