### PR TITLE
[bugfix] fix #19939: render mesh arrows also on the edge of the canvas

### PR DESCRIPTION
**Pull request by PeterPetrik**
fix #19939

vector arrows are renderer also when they have either start or end point in the extent.

@nirvn 

before:
expected_quad_and_triangle_vertex_vector_user_grid_dataset

after:
expected_quad_and_triangle_vertex_vector_user_grid_dataset

### CODE REVIEW

**Comment by nirvn** [comment]
Great job, very much how I envisioned it.

**Comment by nirvn** [comment]
@PeterPetrik , I've tested this PR last night, working well. It makes a huge difference. We need to make sure this is merged ASAP before it misses the 3.4 boat, it's an important mesh fix.

**Comment by PeterPetrik** [comment]
@wonder-sk @nyalldawson I would like to merge this this afternoon if there are no objections.

**Comment by nyalldawson** [comment]
Looks good to me

**Pull request merged**
