### PR TITLE
added missing country names and codes in world map geopackage

### PR DESCRIPTION
**Pull request by mstuyts**
## Description
Some country names and codes were missing in the world map geopackage. I added them for France, Tokelau and Norway.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by elpaso** [comment]
I downloaded the file but France/Norway names are still blank (or I did something wrong?).

**Comment by mstuyts** [comment]
@elpaso No, you didn't do anything wrong. I pushed the wrong version of the file apparently.  Sorry. I tried it again, so now it should be the corrected version.

**Comment by Gustry** [comment]
This file is the output of the Processing model provided in the same folder. Should we maintain a readme with these manual updates?

**Comment by mstuyts** [comment]
The islands that are in the countries layer in the QGIS world_map.gpkg file called Tokelau, are in the source data (Natural Earth Admin 0 – Countries v4.1.0) part of New Zealand. So the Geopackage was already changed manually in the past. 

The data for France & Norway is partially missing in the source data.

I found information to correct the missing data on:
- https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
- http://api.worldbank.org/v2/country/fr?format=json
- http://api.worldbank.org/v2/country/no?format=json

Should [Tokelau](https://en.wikipedia.org/wiki/Tokelau) be merged with New Zealand again in the geopackage?

**Pull request closed without merging**
