### PR TITLE
properly get layer from a QgsProcessingFeatureSourceDefinition

### LINKED ISSUE #40055: Expression widget does not list fields when Selected features only is checked
**Describe the bug**

In processing algorithms that use a `QgsProcessingParameterExpression`, the widget has a combobox populated with the available fields. If the *Selected features only* checkbox is checked, then the expression widget no longer shows the fields in the combobox.

**How to Reproduce**
- Load a vector layer with some features
- Run an algorithm that uses a `QgsProcessingParameterExpression`, for example *Order by expression*
- Click on the expression widget combobox button: the layer's fields are listed
- Go to the map canvas and select some features
- Back to the algorithm dialog, check *Selected features only*
- Click on the expression widget combobox button: the layer's fields are **not** listed

**QGIS and OS versions**
69faea8 on Debian testing

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #40055 : Complete the `QgsProcessingParameters::parameterAsLayer` method to deal with QgsProcessingFeatureSourceDefinition

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'm -1 to this approach -- a feature source isn't the same thing as a vector layer, and we run into risks of api abuse if we allow users to treat them as the same.

I think a better approach would be to create a new QgsProcessingParameters::parameterAsQgsFields method which can take a parameter definition and value and return the corresponding QgsFields associated with the value. So if the parameter definition is a QgsProcessingParameterVectorLayer then it gets the layer's fields, but if the definition is a feature source definition then it evaluates the source and gets the fields from the QgsProcessingFeatureSource instead.

That would give you a means of retrieving the fields for the parent parameter, and you could use them in the widget wrapper to update the widget accordingly.

**Comment by troopa81** [comment]
@nyalldawson I understand your point. `parameterAsLayer` is indeed not the best place to fix the issue.

I should have been more complete on the issue description. The issue is because of the [QgsMapLayerComboBox::value](https://github.com/qgis/QGIS/blob/master/src/gui/processing/qgsprocessingmaplayercombobox.cpp#L342) methods which returns a QgsProcessingFeatureSourceDefinition when the *only selected feature* is checked. 

I changed my PR to fix `QgsProcessingExpressionWidgetWrapper::setParentLayerWrapperValue`. If we agree on this I will add some tests and squash commits then.

> That would give you a means of retrieving the fields for the parent parameter, and you could use them in the widget wrapper to update the widget accordingly.

I need the layer object and not just the fields, so the expression builder could have the layer specific variable (layer_id, layer_name...)

**Comment by nyalldawson** [comment]
Ok, this approach looks good, thanks!

**Comment by cefect** [comment]
Did this change the 'source' behavior in Q3.16.6? 

This was working before in pyqgis:
`QgsProcessingFeatureSourceDefinition(source=vlay.id())`

and is now throwing 'Could not load source layer' when passed to processing.run

**Comment by troopa81** [comment]
> @troopa81 Did this change the 'source' behavior in Q3.16.6?

I'm pretty sure your issue is not related to this PR because it doesn't change the QgsProcessingFeatureSourceDefinition behavior, only the way `QgsProcessingParameterExpression` deal with it.

**Pull request merged**
