### PR TITLE
Add py-lxml

### PR DESCRIPTION
**Pull request by nicogodet**
## Description

Add the last remaining python dependency for VCPKG build.
No more error at opening a fresh build

### CODE REVIEW

**Comment by nicogodet** [comment]
@m-kuhn `--x-feature="3d" --x-feature="bindings" --x-feature="gui" --x-feature="opencl" --x-feature="quick" --x-feature="server" --allow-unsupported` should be added to https://github.com/qgis/QGIS/blob/f0a7b6367be83820ab00ac1c34d6ca2409983861/.github/actions/vcpkg_update_report/action.yml#L28 and https://github.com/qgis/QGIS/blob/f0a7b6367be83820ab00ac1c34d6ca2409983861/.github/actions/vcpkg_update_report/action.yml#L35 to report complete update

**Comment by m-kuhn** [comment]
We should add another input param, comma separated and set it to `3d,gui,bindings` in the workflow and then preprocess this somehow

AI suggests

```
formatted_features=$(echo "$features" | sed 's/\([^,]*\)/--x-feature="\1"/g' | sed 's/,/ /g')
```

This way we can later on externalize the action

**Comment by nicogodet** [comment]
Thanks for the additional nice touch 👌🏼

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
> Thanks for the additional nice touch 👌🏼

Thank you for the proactive testing

**Pull request merged**
