### PR TITLE
Slightly decrease contrast on field type icons to avoid too-visually heavy icons

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by nirvn** [comment]
Looking better already, but still quite dark. Have you tried using a gray that'd match the one we use in the geometry type icons?

**Comment by m-kuhn** [comment]
Screenshots? Too bad github doesn't render svg images.

**Comment by DelazJ** [comment]
@m-kuhn I think it does https://github.com/nyalldawson/QGIS/blob/058f499dee036fb202261c87e928ede296270403/images/themes/default/mIconFieldDate.svg but I fail to see the difference (compared to master preview)

**Comment by Gustry** [comment]
@m-kuhn @nirvn In the files changed tab -> `Display the rich diff` icon top right corner to display the diff between master and the PR.

I agree with @nirvn, it still dark IMHO

**Comment by nyalldawson** [comment]
New versions:

untitled

**Comment by nirvn** [comment]
Net improvement.

**Comment by nyalldawson** [comment]
So merge?

**Review by nirvn — APPROVED** [review]
Yep.

**Comment by nirvn** [comment]
Oh wait, compress the SVGs? :)

**Comment by nyalldawson** [comment]
Compressed

**Pull request merged**
