### PR TITLE
Bugfix gh48077 multi edit constraints issues

### LINKED ISSUE #48077: multiedit in attribute table not working properly in version >=3.22
### What is the bug or the crash?

**Issue A:**
When activating the `Toggle multi edit mode` in the Attribute Table for a generic database layer (e.g. a geopackage), Qgis raises the alert `Changes to this form will not be saved. One field doesn't meet their constraints.`,

**Issue B:**
Bypassing the issue by removing the unique identifier field from the Attributes Form fields list, by pressing the `Toggle multi edit mode` button Qgis says `Attribute changes for multiple features applied.`. Every subsequent change will apply to all the elements, not just the selected one.
**This bug will cause data losses, in a critically way for Postgis or other remote database layers.**
With QGIS 3.16 everything worked fine.
I found other threads online reporting the same problem, but no other issues here: e.g. https://gis.stackexchange.com/questions/417285/qgis-3-22-automatic-changes-by-multiedit-in-attribute-table

### Steps to reproduce the issue

0. Load a generic geopackage layer (e.g. the training_data.gpkg from https://docs.qgis.org/3.22/en/docs/training_manual/foreword/intro.html#data-downloadlink )
Issue A:
1. Open the Attribute Table for the selected layer in the geopackage
2. Toggle the `Toggle multi edit mode` button
Issue B:
3. Open the `Attributes Form` tab in the `Layer properties` dialog
4. Change the mode from `autogenerate` to `drag and drop designer`
5. Remove the `fid` field from the `Form layout` list
6. Open the Attribute Table for the selected layer in the geopackage
7. Toggle the `Toggle multi edit mode` button
8. Try to change one value for only some selected elements

### Versions

QGIS version
3.22.5-Białowieża
QGIS code revision
c27231782f
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 7 Version 6.1 (Build 22000)

Active Python plugins
AnotherDXF2Shape
1.2.3
Cxf_in
9.2
db-style-manager_MOD
0.9.0_MOD
GeofabrykaToolbox
0.5
GroupStats
2.2.5
idrostudi_toolbox
1.21
ImportEpanetInpFiles
1.6.3
joinmultiplelines
Version 0.4.1
mmqgis
2021.9.10
MultiEdit
1.1
multiple_layers_tools
1.2
nominatim
1.4.1
ntv2_transformations
0.20
plugin_reloader
0.9.1
QCopycanvas
0.5
qepanet
2.5
QGIS3_Delft3D_FM
1.0
QuickMultiAttributeEdit3
version 3.0.3
scriptrunner3
3.0.5
SpreadsheetLayers
2.0.1
StreetView
3.2
TerrainShading
0.9.3
wnt
1.3.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Various fixes to the multi edit  attr table form.

Possibly fixes #48077

### CODE REVIEW

**Comment by elpaso** [comment]
@paolomartinis can you please test this PR and check if that fixes #48077 ?

**Comment by paolomartinis** [comment]
i'll try, but it will take a bit of time (i have to recreate the developing environment in a new virtual machine, the last one is gone...)

**Comment by elpaso** [comment]
> i'll try, but it will take a bit of time (i have to recreate the developing environment in a new virtual machine, the last one is gone...)

If you are on windows you can just grab the pre-built mingw64 image associated with this PR: https://github.com/qgis/QGIS/suites/10905261268/artifacts/550924394

**Comment by paolomartinis** [comment]
seems to work, for both issues and both with geopackages and postgis tables. monday i'll make some more intensive tests in other pcs but i think you solved the problem. really thanks

**Comment by elpaso** [comment]
@paolomartinis thank you for your feedback!

**Review by troopa81 — COMMENTED** [review]
@elpaso The fix looks good, do you think it's possible to add some tests?

**Comment by elpaso** [comment]
> @elpaso The fix looks good, do you think it's possible to add some tests?

Possibly, but it would be very difficult and I'm not going to.

**Review by troopa81 — APPROVED** [review]

**Pull request merged**
