### PR TITLE
Include parameterselection dropdown contents in processing translations

### PR DESCRIPTION
**Pull request by arnaud-morvan**

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
@volaya @alexbruy 
Can you take a look at this pull request about processing translation ?

**Comment by slarosa** [comment]
@arnaud-morvan I guess there is also the FieldsCalculator.py which has need of these changes as well.

**Comment by volaya** [comment]
Looks good to me. I don't see anything that can be broken by this change. WIll wait to see if @alexbruy  has something to say. Otherwise, I will merge it.

As @slarosa says, there might be other algorithms that need similar changes( this PR doesn't solve the issue for SAGA, GRASS, etc algorithms), but it can be merged and more work can be done later to translate other selection parameters.

**Comment by slarosa** [comment]
@arnaud-morvan also, I would prefer to keep reference to the main class by using ```self.type_names```. In general it looks good to me too.

**Comment by arnaud-morvan** [comment]
@slarosa:
Do you tell that I should keep each list (*self.types_names*, *self.methods*, *self.modes*, ...) in subclasses instances, with :

    def defineCharacteristics(self):
        self.type_names = ...

Or do you tell that the *type_names* list should be set in the *GeoAlgorithm* class because it's used in several subclasses.

        def __init__(self):
            self.type_names = [self.tr('Integer'),
                               self.tr('Float'),
                               self.tr('String'),
                               self.tr('Date')]

Note that this can break some command line scripts, because command line take the index of the field type in the list. And actually this is not the same list (order differ) in each algorithms.

**Comment by slarosa** [comment]
@arnaud-morvan sorry for the delay to reply.
Yes, my comment was to keep the list in ```defineCharacteristics``` method, but a deeper investigation I don't see a big deal to keep your proposal. So +1 to merge as is.

Are you planning to add more translation to parameters?

**Comment by arnaud-morvan** [comment]
For the QGIS provider, I don't see other parameters to translate.
I haven't planned to apply translation on other providers (GRASS, Saga) in the next days, but it could be a good task, at the hackfest, to try to reproduce what J. Fisher have made for the names and groups in this category.

**Pull request merged**
