### PR TITLE
Added Datasources2Vrt processing alg

### PR DESCRIPTION
**Pull request by luipir**
Added Datasources2Vrt processing alg to merge different datasources in a single VRT

This is useful for that commands that have multiple inputs but that have to be contained
in a single vrt

Especially request to allow OGR commands with a specified SQL string. These set of commands accepts a single datasource in which specify all the layers pointed by the SQL string

Algorithm developed during QGIS Developer Meeting 2015 (Nodebo)

Documentation of the algoritmo pulled with: https://github.com/qgis/QGIS-Documentation/pull/529

### CODE REVIEW

**Comment by luipir** [comment]
I forgot to add some references to the work of Fank Warmerdam on which part of the code is based and modified to be be integrated in processing and to be useful for ogr commands... will be the next pull request to the algoritm when I'll come back. Thank you Victor for merging.

regards

**Comment by pcav** [comment]
What is the difference with the existing `Build virtual raster` tool? /buildvrt.py

**Comment by gioman** [comment]
This creates virtual *vectors* and will allow creating geoprocessing tools, based on ogr2ogr/spatial queries, to replace/complement  the ones from ftools (and create easily new ones), as this ones are often unreliable and slow.

**Comment by pcav** [comment]
OK, got it, thanks.

**Comment by luipir** [comment]
explication why th existence of the new command is available in the help of the command in the python doc of the function and in the comments of the code

**Pull request merged**
