### PR TITLE
Various Debian packaging improvements for 3.4

### PR DESCRIPTION
**Pull request by sebastic**
While reviewing the packaging changes in QGIS 3.4 I noticed that many of the packaging improvements present in Debian are not included in the upstream packaging.

The PR forwards the relevant changes for 3.4.

Related PRs:

 * QGIS 3.7: #9254
 * QGIS 3.6: #9255

### CODE REVIEW

**Comment by sebastic** [comment]
Note the discussion about the Breaks/Replaces version for the Python package renaming:

 https://github.com/qgis/QGIS/pull/9255#issuecomment-466762944

**Comment by nyalldawson** [comment]
Any objections @jef-n?

**Comment by nirvn** [comment]
@sebastic , allow me to be slightly opportunistic here and ask a semi-related question: are you aware of (or better, in a position to execute) a plan for the next version of Ubuntu to update its QGIS package to 3.4 LTR? It'd be unfortunate for Ubuntu 19.04 to ship with a QGIS package that's pass EOL.

**Comment by sebastic** [comment]
@nirvn, your question is offtopic for this PR. Better to ask such questions on the mailinglist of the packaging team: [debian-gis@lists.debian.org](https://lists.debian.org/debian-gis/).

That being said, the geospatial packages in Ubuntu are not actively maintained (as they are in the universe repository), Ubuntu just syncs the packages from Debian (unstable).

The qgis package in Debian was updated to 3.4.5, but is currently only available in the experimental repository because it's quite a large change not entirely appropriate at the current stage of the freeze in preparation of the buster stable release. The Debian release managers have been asked to consider QGIS 3.4 for buster, see: [#923184 - [pre-approval] unblock: qgis/3.4.5+dfsg-1](https://bugs.debian.org/923184).

If the Release Managers don't approve, the qgis package in buster will remain at 2.18.28 and the 3.4 releases will remain in experimental until the buster release. This implies that Ubuntu won't have a newer version to sync either (although they can sync from experimental on request).

If you care about the qgis package in Ubuntu and want to be in a position of influence, you need to get involved in the Debian GIS team where you'll maintain branches for Ubuntu, and use the processes in Ubuntu to do more than sync packages as-is from Debian.

**Comment by jef-n** [comment]
superceeded by ec02ea0ed437072e92b1295838206fdc731e4543

**Pull request closed without merging**
