### PR TITLE
Assorted set of fixes related to DateTime Z formatter

### PR DESCRIPTION
**Pull request by rouault**
I'm perhaps missing something but it seems Qt cannot handle the Z formatter and doesn't automatically perform conversion to UTC when the input datetime is in another time spec.

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
These incremental changes look good to me. 

(I do think we need a bigger rework of time zones at some stage, eg having some method to allow the utc datetime values in a GPKG to always be shown to the user in local time. )

**Comment by nyalldawson** [comment]
@rouault should we backport this?

**Comment by rouault** [comment]
> @rouault should we backport this?

I'm kind of nervous, as I'm not totally sure this will not cause backward compatibility problems.
For ex in https://github.com/qgis/QGIS/issues/57262, the user specified a default value as ``format_date(datetime_from_epoch(epoch(now())+3600000*4),'yyyy-MM-ddTHH:mm:ssZ')``, with probably the intent to shift its local time by 4 hours and have that computed value directly considered as UTC. Now this will *convert* that computed value (its local time + 4 hours) to UTC.

The commit in the OGR provider should be OK to backport.

**Comment by uclaros** [comment]
@rouault @nyalldawson 
Are you absolutely positive that geopackage _needs to store all date times in UTC_?

From what I read on the [spec](http://www.geopackage.org/spec140/index.html) (and previous versions of it):
> DATETIME
> ISO-8601 date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ with T separator character and Z suffix for coordinated universal time (UTC) encoded in either UTF-8 or UTF-16. Stored as SQLite TEXT (see TEXT above).

My interpretation of the above is that the Z suffix is optional, for when the time is UTC.

In previous versions of the spec (eg 1.3.1), it was explicitly stated that UTC must be used for _metadata tables_:
> Requirement 100
> Every gpkg_metadata_reference table row timestamp column value SHALL be in ISO 8601 [[I29]](http://www.geopackage.org/spec131/#I29) format containing a complete date plus UTC hours, minutes, seconds and a decimal fraction of a second, with a 'Z' ('zulu') suffix indicating UTC.[[K37]](http://www.geopackage.org/spec131/#K37)


The more I dive into this, the more I tend to agree that the intention is indeed to store all dates in UTC (eg in https://www.geopackage.org/spec/ the DATETIME definition _is different_ than the one in the 1.4.0 link:
> DATETIME
> ISO-8601 date/time string in the form YYYY-MM-DDTHH:MM[:SS.SSS]Z with T separator character, Z suffix for coordinated universal time (UTC), and encoded in either UTF-8 or UTF-16. Seconds and fractional seconds are OPTIONAL. Fractional seconds MAY have fewer or more than three digits. Stored as SQLite TEXT (see TEXT above).

by defining seconds as optional, one can now suppose that _Z is not optional_)

however, imho, the spec should state this explicitly and not leave room for interpretation.

**Pull request merged**
