### PR TITLE
[needs-docs] Update min and max functions

### PR DESCRIPTION
**Pull request by DelazJ**
In case of a null value, these functions will not always return null

### CODE REVIEW

**Comment by nyalldawson** [comment]
Can you please add some unit tests for this too? Have a look in testqgsexpression.cpp at the existing min/max tests - should be a copy/paste/adapt of the existing ones.

**Review by nyalldawson — COMMENTED** [review]
Looking good - just for completeness, can you add a test with a null as the first value?

**Comment by m-kuhn** [comment]
Glad those tests were added.
Expression functions by default assume that any parameter with NULL value will have NULL as a result. That needs to be specified manually for any function that doesn't follow this behavior.

**Comment by m-kuhn** [comment]
@DelazJ can you add an example to the function docs?

**Pull request merged**
