### PR TITLE
Ensure "dbname" is set in the uri, once again

### PR DESCRIPTION
**Pull request by strk**
Fixes https://issues.qgis.org/issues/16625 again after fixing it once as https://issues.qgis.org/issues/10600

### CODE REVIEW

**Comment by strk** [comment]
Maybe this time I'll be able to write a test for it ...
@elpaso have you ever seen an automated test for any classes of DBManager ?

**Comment by strk** [comment]
@elpaso I'm mentioning you as the author of the regressing commit 212b125a2c2eba93f2c8e3b991ea4be4fdc57623 - do you remember what usecase was that commit aiming at fixing ? Was it still only related to OGR ? Because I see OGR is still not getting the 'service' parameter..

**Comment by elpaso** [comment]
my commit was a fix for https://issues.qgis.org/issues/14436, and no, never seen a test for DB manager.

**Comment by strk** [comment]
What I see in the python code is that both service and other parameters are passed to `uri.setConnection`:
```
        if service:                                                             
            uri.setConnection(service, database, username, password, sslmode, authcfg)
        else:                                                                   
            uri.setConnection(host, port, database, username, password, sslmode, authcfg)
```

This ends up being a call to the QgsDatasourceURI class:
```
    //! Set all connection related members at once (for the service case)       
    void setConnection( const QString &aService,                                
                        const QString &aDatabase,                               
                        const QString &aUsername,                               
                        const QString &aPassword,                               
                        SslMode sslmode = SslPrefer,                            
                        const QString &authConfigId = QString() );           
```

Now the question is: why does that function takes *bot* a service name *and* parameters that may be specified in the service file ? Should the explicit parameters take precedence over the ones defined int the service ?

**Comment by strk** [comment]
So, libpq uses an explicit `dbname` in an dataosurce URI having both `service` and `dbname`, while it does NOT use the environment variable when `service` is given and does contain a dbname.

**Pull request merged**
