### PR TITLE
Server WFS3 fix rel=service_desc -> rel=service-desc

### LINKED ISSUE #32268: [SERVER] [WFS3] Wrong rel=service_desc
The landing page reports a rel=service_desc for the API endpoint. The value should rather be service-desc with a dash, not a underscore. See https://github.com/qgis/QGIS/pull/32262#issuecomment-542607819

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #32268

### CODE REVIEW

**Comment by elpaso** [comment]
@rouault wold you mind approving this too? I think we are safe to merge during the freeze since the specs were finalized just two days ago and OAPIF is a new and well insulated feature.

**Review by rouault — APPROVED** [review]
I'm OK with the changes themselves, but I'm not clear of what the consensus is about what should go or not go during this hard freeze period.

**Comment by elpaso** [comment]
AFAIK rules are not carved in stone, and I can't see the point in deliberately shipping a bugged WFS3 server.

My understanding is that a change might cause any regression (or introduce any issue) it should not be accepted during the freeze. 

But here we are talking about a server feature that is totally new and insulated and I don't see any possible impact on any other functionality.

**Comment by rouault** [comment]
Agreed that it seems safe to merge

**Comment by nyalldawson** [comment]
I also agree this is a significantly high impact issue (resulting in annoying workarounds being required by other libraries indefinitely) and the fix is very low risk.

**Pull request merged**
