### PR TITLE
Ensure correct expression context is used in map select tools

### LINKED ISSUE #42006: Qt: Retrying to obtain clipboard
OSGeo4W new "testing" build, 3.18 nightly release candidate (code revision 1bcdbdb6)

Periodically getting a critical log message (and red status bar) saying
```
2021-03-03T10:07:23     CRITICAL    Qt : Retrying to obtain clipboard.
```
It seems to occur at irregular intervals, when QGIS is open but its window is not in the foreground (i.e. I am using a different application). Functionality not impaired when I come back to QGIS, just stress-inducing :)

This did not occur on the 3.18.0 (now retired) release on "old" OSGeo4W, or on 3.19 master there as well too. I *think* the difference may be that here it is compiled and running against Qt 5.15.2 while the "old" ones had an earlier Qt.

BTW, I've also been getting apparently harmless critical Qt warnings regarding axes from the Raster Data Plotting plugin at load time (I filed a bug report at https://bitbucket.org/janzandr/rasterdataplotting/issues/24/axis-error-messages-on-startup ), but this is not at startup and I now have that plugin disabled. QGIS is in the background and it is doing nothing when this happens. But mentioning it here in case the issue is a broader one of Qt being too verbose with needless warnings, for instance.

** Update: it seems more likely to occur when I've actively been using the clipboard with other applications (like when filing this bug report), but not always. Sorry, hard to pinpoint exact trigger because you only see it coming back, and based on the timestamp are then trying to remember "what exactly was I doing 3 minutes 21 seconds ago?"

### LINKED ISSUE #42066: Cannot select objects when symbology rule uses expression containing variables
Using QGIS 3.18.0 for windows. When using rule based symbology and a rule that uses project variables (in my case, using a date variable to filter several layers by a certain date), the features display correctly, however I cannot select them using the select feature tool. If I clear the rule or use a rule that does not contain variables, selection works as expected. Features can still be selected via the attribute table.

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #42066

### CODE REVIEW

**Comment by DelazJ** [comment]
@nyalldawson, is #42006 the right target? Just asking because the report does not reveal anything obviously related to map select tools to me. I'm not aware of the background...

**Comment by nyalldawson** [comment]
@DelazJ thanks, I've fixed it

**Review by nirvn — APPROVED** [review]

**Comment by nyalldawson** [comment]
Thanks @nirvn!

**Comment by roya0045** [comment]
@nyalldawson Thanks a ton Nyall, this has been a nasty issue for a good while!

**Pull request merged**
