### PR TITLE
fix mesh calculator IF operator

### PR DESCRIPTION
**Pull request by vcloarec**
when IF operator of mesh calculator has left member ans right member non temporal, the result is set to non temporal even the condition is temporal.
That leads to non temporal virtual dataset group when formula is, for example : if ('"Depth">1 , 2 , 3). Even is Depth is temporal, as "2" and "3" are not temporal the result is static, that is wrong.
This PR fixes this issue

### CODE REVIEW

**Comment by PeterPetrik** [comment]
looks good, can we have test for this?

**Comment by vcloarec** [comment]
test added

**Review by PeterPetrik — APPROVED** [review]

**Comment by PeterPetrik** [comment]
I think we cannot backport this , since this is not crash/data corruption... right @nyalldawson ?

**Comment by nyalldawson** [comment]
@PeterPetrik 
> I think we cannot backport this , since this is not crash/data corruption... right @nyalldawson ?

We can (and should) put it in the queued backports branch

**Pull request merged**
