### PR TITLE
Fix plugin dependencies

### PR DESCRIPTION
**Pull request by elpaso**
@mbernasocchi give this a try please (no need to rebuild QGIS, it's just a two lines change in the python part)

### CODE REVIEW

**Comment by elpaso** [comment]
@jef-n you may also want to have a look.

**Comment by mbernasocchi** [comment]
@elpaso the very first time I tried it worked perfectly. any subsequent test (even after uninstalling my plugin and restarting QGIS) fails (the pluging gets installed without asking for dependencies)

**Comment by elpaso** [comment]
> @elpaso the very first time I tried it worked perfectly. any subsequent test (even after uninstalling my plugin and restarting QGIS) fails (the pluging gets installed without asking for dependencies)

I cannot reproduce this ^ (are you sure the dependencies are not satisfied?)

**Comment by mbernasocchi** [comment]
```

plugins_metadata_parser
{'hybridge': <configparser.ConfigParser object at 0x7f0f04994cc0>, 'processing': <configparser.ConfigParser object at 0x7f0f04994f60>, 'MetaSearch': <configparser.ConfigParser object at 0x7f0ef7ff35f8>, 'db_manager': <configparser.ConfigParser object at 0x7f0f0498d7f0>}
plugindependencies.find_dependencies('hybridge')
({}, {}, {})
parser = plugins_metadata_parser['hybridge']
parser.get('general', 'plugin_dependencies')
'GeoCoding,IPyConsole==1.9,DoesNotExist,lalaland'
plugindependencies.__get_plugin_deps('hybridge')
{}
```

**Comment by elpaso** [comment]
@mbernasocchi try my last commit. It works for me.

**Comment by mbernasocchi** [comment]
testing

**Review by mbernasocchi — APPROVED** [review]

**Comment by mbernasocchi** [comment]
seems to work now. I could never break it :)

**Pull request merged**
