### PR TITLE
Update build dependencies for vivid

### PR DESCRIPTION
**Pull request by nyalldawson**
Adds some missing build dependencies under Vivid:

python-gdal
python-psycopg2
python-autopep8
flip
libqca2-dev
libqca2-plugins
python-qt4-sql

Note that these probably also apply to other Ubuntu releases, and I'm also not sure that editing this file directly is the right approach (I suspect not). @jef-n Can you advise what approach I should take here?

### CODE REVIEW

**Comment by jef-n** [comment]
see 97a10d4

**Comment by nyalldawson** [comment]
@jef-n looks like python-psycopg2 is still missing (also flip and python-autopep8, but I guess these aren't strictly build dependencies)

**Comment by jef-n** [comment]
yes, that's why.  not a build dependency

**Comment by nyalldawson** [comment]
I'd say python-psycopg2 is still a dependency though - without it dbmanager is broken.

**Comment by jef-n** [comment]
fixed in 6a973d63

**Comment by nyalldawson** [comment]
@jef-n thanks!

**Pull request closed without merging**
