### PR TITLE
[FEATURE] allow customization of line spacing for legend item labels

### PR DESCRIPTION
**Pull request by nirvn**
This PR enables users to customize the spacing in-between lines for legend item {title, group, subgroup, symbol} labels. Consistent line spacing across a layout is quite important, and direly needed for the legend item.

For e.g., here's a before vs. after shot, with a subtly increased line spacing on the right side to better match the layout:
untitled

The PR also improves the way line spacing is calculated for symbol labels to take into account font descent values, which is crucial to prevent text overlap for indic-based languages:
007e82ce-92d3-11e6-90aa-8c2a1d3d3ba1

@nyalldawson , travis will be red, need to update a dozen control images.

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , any chance you could review this? I've rebased the PR following @wonder-sk 's great project refactoring and did the necessary control image updates.

**Comment by nirvn** [comment]
@nyalldawson , I just realized the screenshot in the PR's description is outdated (i.e. it was taken while I was working on another PR on legend symbol vertical alignment, part of which we tweaked some more).

This is an accurate before vs after:
untitled

**Comment by nyalldawson** [comment]
@nirvn 

Code all looks good. My reservations come from some of the changes to the test images, specifically:

- expected_composer_legend_noresize.png The whole legend looks displaced vertically here, ie there's a very large margin at the top of the legend now. Where has this come from?
- expected_legend_5_by_2_mask.png the text in the final row is effectively masked out now. I think you'll need to discard the existing mask and recreate a new one following the changes to the references image here. (also applies to the other 3 row legend images + expected_legend_diagram_attributes_mask.png)

**Comment by nirvn** [comment]
@nyalldawson , thanks for the review. Good point re masks; I've re-created masks for the row tests as well as diagram attributes.

**Pull request merged**
