### PR TITLE
Framework for context based expressions, version 3

### PR DESCRIPTION
**Pull request by nyalldawson**
Version 3 of context based expressions. Just need to replace the deprecated methods and this should be good to go...

### CODE REVIEW

**Comment by nyalldawson** [comment]
@wonder-sk Here's some additional pointers to help reviewing this (since it's become a mega patch). Basically the parts which need review are:
- The QgsExpressionContext, QgsExpressionContextScope and QgsExpressionContextUtils API from ad6a606
- The changes to qgsexpression.cpp in ad6a606 (generally quite straightforward, but a bit of juggling to maintain the existing API which I'd appreciate a second opinion on)
- The expression lexer/parser changes to allow @variable shorthand

Everything else is really just replacing existing use of expressions to make sure they are evaluated using the correct context, and all the flow-on changes required for this. Don't worry about reviewing that stuff.

**Comment by nyalldawson** [comment]
Should be good to go now, pending CI test results...

**Comment by nirvn** [comment]
@nyalldawson @wonder-sk very nice work. I've been testing a couple of context branches as you progressed, and this branch has reached a solid level of stability and implementation.

The data-defined button variables shortcut menu item is excellent too:
shortcuts

This deserves quite a lot of exposure via blog posts, etc. It's a (positive) game changer for many scenarios, from symbology to composers. Kudos.

**Comment by nirvn** [comment]
@nyalldawson should this be closed?

**Comment by nyalldawson** [comment]
manually merged

**Pull request closed without merging**
