### PR TITLE
 Use qgs project icon derivative for project home in browser

### PR DESCRIPTION
**Pull request by nyalldawson**
@nirvn, as discussed this changes the "Project home" browser directory to use a variant of the qgs project file icon. It's been slightly reworked to work better as a small icon in the browser (basically I've pulled the detail out and removed the page):

untitled

### CODE REVIEW

**Comment by nirvn** [comment]
All good. 

Before merging, it'd be good to compress the svg.

**Comment by nyalldawson** [comment]
Good point - got a recommendation?

**Comment by nirvn** [comment]
Try this online compressor: https://jakearchibald.github.io/svgomg/

I love it. I usually just paste svg content as input and paste the site's output back into the .svg

**Comment by nyalldawson** [comment]
> Before merging, it'd be good to compress the svg.

done

**Comment by nyalldawson** [comment]
Unrelated test failure

**Comment by NathanW2** [comment]
Nice!

**Pull request merged**
