### PR TITLE
Make QGIS 2.99 compatible with 3.0 plugins by introducing PyQGIS API version 

### PR DESCRIPTION
**Pull request by borysiasty**
Currently, the Plugin Installer is hardcoded to fetch plugins for QGIS 3.0 (due to commits 54f312fa and 7c01b7e64), but once downloaded, it only loads plugins compatible with 2.99. The two checks are simply not synchronised, so plugins have to be compatible with both qgis 2.99 and 3.0.

This PR introduces a **pyQgisVersion** concept, what can be considered API version. PyQGIS version is usually equal to the QGIS version, except QGIS x.99, when it's bumped up to the next major release: (x+1).0.0. That way pyQGIS would be now 3.0.0, and as soon as we reach 3.99, pyQGIS will be automatically 4.0.0. 

It looks perfectly reasonable to me to say 2.99 has 3.0 API. What are your thoughts?

All the 2.x plugins are marked compatible up to 2.99, what is obviously not true, and this PR legitimises their incompatibility. The only problem is we should either clearly state the upper range is not inclusive (the range is left-closed, right-open), or better just set the automatic qgisMaximumVersion to x.98. The latter looks perfectly clear and unambiguous to me.

### CODE REVIEW

**Comment by borysiasty** [comment]
Anybody interested in discussing this idea or can I close it and stay with the 'dual-range' plugins?
@elpaso @rduivenvoorde @pcav @wonder-sk

**Comment by luipir** [comment]
as far I can see in the PR, you are not introducing a new metadata tag, but automatically "force" x.99 min version tag to x+1.0.0.

I can't see any drawback => +1

**Comment by NathanW2** [comment]
+1 for me.  Merge and we can fix any issues before release anyway.

**Comment by borysiasty** [comment]
@luipir exactly. The pyQgisVersion is just a conceptual constant to keep in mind, so the only drawback would be increased complexity (while we all love to KISS).

**Comment by borysiasty** [comment]
Thanks @NathanW2. I'll merge it if there is no strong objections during the weekend.

**Comment by rduivenvoorde** [comment]
@borysiasty no objections, but I'm very much in KISS mode too. So why adding a fix when there is no (or only a temporarily small) problem?
But add it if you think it makes live easier in future :-)

**Comment by borysiasty** [comment]
@rduivenvoorde: the current situation is just a big mess. Plugins are told to be compatible with QGIS up to 2.99, but once 2.99 is released, we put a workaround to only download plugins for a different version (3.0). We don't apply the same workaround for plugin loading, so every plugin must be compatible with both 2.99 and 3.00 to be both downloaded and run on 2.99. And if you install some plugins manually, QGIS 2.99 will pick up and load those for 2.x and not 3.x.

The alternative to this PR is to set the automatic qgisMaximumVersion to x.98, so no plugin is automatically compatible with x.99 and plugin authors have to declare the compatibility explicitly. It's a smaller change in QGIS, but it forces authors to deal with yet more complicated compatibility ranges. With my solution, once x.99 is started, plugin authors just bump up the qgisMinimumVersion and start using the new API (I guess we can safely assume every major version breaks the API).

Otherwise (if we won't fix it at all), we'll need to: wait for the last minute before release, revert the existing workaround, bump up core plugin versions, tell plugin authors they can simplify their metadata (bump up minVer and remove maxVer), and finally don't forget to repeat it all again with 3.99 :-) 
Really, I don't think it's a KISS solution :D

As there are no strong objections, I'm merging it. We can revert it if any vetos come.

**Pull request merged**
