### PR TITLE
Allow generation of Qt QHP help files from doxygen

### PR DESCRIPTION
**Pull request by nyalldawson**
This adds a new cmake option GENERATE_QHP. If the api docs are set to being built (ie doxygen is available and WITH_APIDOC is true) then setting GENERATE_QHP to true will cause doxygen to create
a compiled Qt help file from the QGIS docs.

This QHP file can then be used by QtCreator to show the QGIS api directly within the QtCreator help (ie, press F1 on a class or member to see the docs).

To do this, you need to:
- make sure doxygen is installed, WITH_APIDOC is true and GENERATE_QHP is true
- build to generate the docs
- In QtCreator, go to Tools -> Options -> Help, switch to the "Documentation" tab and click "Add". Point it to your generate QHP file (should be in the build folder doc\api\qch folder)
- Restart QtCreator, wait a bit, and then you should have the api docs available under the "Help" tab and by pressing F1 on a QGIS class/method

Here's some screenshots:

qtcreator_help

qtcreator_help2

### CODE REVIEW

**Comment by NathanW2** [comment]
Nifty!

**Comment by NathanW2** [comment]
@nyalldawson good to merge? Could we also ship these with installs, would be very handy for doing applications.

**Comment by nyalldawson** [comment]
@NathanW2 I'd say ideally this would be generated by the nightly builds, and then distributed somewhere on qgis.org/api/.

@jef-n what are your thoughts?

**Comment by jef-n** [comment]
include it in the debian qgis-doc package and it will

**Comment by m-kuhn** [comment]
Merge it?

**Comment by nyalldawson** [comment]
@jef-n How's this? Are those debian packaging changes correct?

**Comment by NathanW2** [comment]
Nice!!

**Comment by 3nids** [comment]
awesome, thanks!

**Pull request merged**
