### PR TITLE
Fix georeference imprecision bug in VRT creation

### PR DESCRIPTION
**Pull request by gui2dev**
Bad geo-referencing bug fix

## Description

Using VRT with large coordinate system (like RGF93/CCxx) and high resolution raster, highest resolution tiles were shifted regarding original raster.
It seemed that when creating the VRT file, georeferencing is truncated while converted to text, leading to loss of precision.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Good catch! Can you add a unit test covering this too please?

**Comment by gui2dev** [comment]
@nyalldawson I just did that :)

**Comment by gui2dev** [comment]
Whoah, the test is not working because the tile I wanted to upload is too big.
Updating soon with a smaller tile (<25Mo)

**Comment by nyalldawson** [comment]
Superseded by #6975

**Pull request closed without merging**
