### PR TITLE
Backport pg bigint to 3.10

### PR DESCRIPTION
**Pull request by espinafre**
As requested by @m-kuhn on https://github.com/qgis/QGIS/pull/36063#issuecomment-621000317 , this PR is a cherry pick of the changes on the PostgreSQL provider regarding how it handles bigint columns, in order to avoid casting to text when writing to the database.

Locally, running `ctest -V -R PyQgsPostgresProvider` fails on a seemingly unrelated issue:

```
======================================================================
527: FAIL: testJson (__main__.TestPyQgsPostgresProvider)
527: ----------------------------------------------------------------------
527: Traceback (most recent call last):
527:   File "/home/jose/sw/qgis/QGIS/tests/src/python/test_provider_postgres.py", line 893, in testJson
527:     self.assertEqual(f.attributes(), [fid, attr, attr])
527: AssertionError: Lists differ: [3, [123], [123]] != [3, 123, 123]
527:
527: First differing element 1:
527: [123]
527: 123
527:
527: - [3, [123], [123]]
527: + [3, 123, 123]
527:
527: ----------------------------------------------------------------------
527: Ran 224 tests in 45.001s
527:
527: FAILED (failures=1)
527
```
I believe this might have something to do with the Python interpreter version (mine is Python 3.8.2), which I'm unable to change at this time.

### CODE REVIEW

**Comment by espinafre** [comment]
@m-kuhn , all green here.

**Comment by tudorbarascu** [comment]
@espinafre I just added a new bug to #36011 and.. this is related right?

**Comment by espinafre** [comment]
@tudorbarascu Yes, it is related; I'm working on it. I'm closing this PR and will open another when all is good. Thank you.

**Comment by espinafre** [comment]
@m-kuhn , all green. Some PostgreSQL provider tests fail here on my system (as I've mentioned on an earlier comment), but pass on Travis. I believe this is because of my Python version (3.8.2). Thank you very much!

**Comment by m-kuhn** [comment]
This will have to wait for the next point release to appear before it can be merged

**Comment by espinafre** [comment]
Great, I'm good with it.

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
