### PR TITLE
[composer] Backport fixes for true north handling to 2.14

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR backports the true north fixes from master_2 to 2.14.

It introduces new strings, so I'm not sure whether that makes it ineligible for backporting. Any opinions?

### CODE REVIEW

**Comment by DelazJ** [comment]
Are new strings really a problem? Looking at the About --> Translators dialog in QGIS, Among the 40 languages available, only german is 100% translated in 2.14.7 and 12 languages have reached 90%. So I'm not sure few new strings will bother user.
And pulling strings from the source code and using the old system of translation, it's always possible to fix the strings for those who want to reach/stay at 100%.

**Comment by m-kuhn** [comment]
Isn't there a translator mailing list? We could make an announcement there.

I remember in *the old days™* we had a string freeze some time before the release. But looking at the numbers by @DelazJ , not sure if it's valuable to reintroduce...

**Comment by jef-n** [comment]
@mach0 ping

**Comment by jef-n** [comment]
@m-kuhn qgis-tr@lists.osgeo.org is the translation mailing list.  IIRC we agreed to switch to the old scheme to update interim master_2 releases, while transifex is still following master for QGIS3

**Comment by nyalldawson** [comment]
Given that there's no strong objections I'm going to merge this

**Pull request merged**
