### PR TITLE
fix all-in-one bundle 

### PR DESCRIPTION
**Pull request by PeterPetrik**
this branch used in nightly2 nightly builds for changes required for https://github.com/qgis/QGIS-Enhancement-Proposals/issues/177

### CODE REVIEW

**Comment by nyalldawson** [comment]
@PeterPetrik is this still a wip? or is it ready for review?

**Comment by PeterPetrik** [comment]
still WIP for now

**Comment by PeterPetrik** [comment]
@nyalldawson ok ready...

**Review by nyalldawson — APPROVED** [review]
LGTM

**Comment by nyalldawson** [comment]
@PeterPetrik any idea why the macos on github build is so fragile at the moment?

**Pull request merged**
