### PR TITLE
Adds the -crop_to_cutline parameter as optional to fix the gdalwarp …

### PR DESCRIPTION
**Pull request by PedroVenancio**
…deviation described in #4530. Option added to Clipper tool from GdalTools and Processing. It also adds the -tr xres yres parameter to GdalTools Clipper tool.

### CODE REVIEW

**Comment by gioman** [comment]
assigned @brushtyler @volaya @alexbruy

**Comment by PedroVenancio** [comment]
In the second commit I propose the option to keep the original raster resolution. Please check if the implementation to get the original raster resolution is ok, because it could not be the best approach.

The set of tests I did, gave good results:

raster_extraction_clipper

but the code may not be the most clean.

**Comment by brushtyler** [comment]
AFAICT looking at the code, there's a missing check, whether the ```gdal.Open``` fails (e.g. the input file doesn't exists).
Furthermore, look at GdalTools_utils module, I'm quite sure there's already a function to get raster resolution there. If not, move your piece of code to that module, please.

**Comment by PedroVenancio** [comment]
Hi Giuseppe @brushtyler 
Thanks for your hints! A specific function to get raster resolution was not at GdalTools_utils yet, so I put one simple there. Please see if it is enough. I've made some tests and it seem work well.

**Comment by brushtyler** [comment]
I'm looking at it this evening.
@volaya or @alexbruy: could you please look at the processing part? It's just few lines, but I've never looked at the processing code.

**Comment by alexbruy** [comment]
Processing part looks good for me, feel free to merge

**Comment by brushtyler** [comment]
Hi Pedro, thanks, tested right now, it works as expected. BTW we must wait until the feature freeze ends to merge this PR so it won't be in the next release, I'm sorry.
Feature freeze started in September 2015, few weeks before you created this PR.

**Comment by PedroVenancio** [comment]
Hi Giuseppe,
No problem! Initially this PR was just to correct the deviation with the crop_to_cutline parameter, but then I added the -tr parameter, so I think you are right and we should wait until the end of feature freeze. Cheers!

**Comment by PedroVenancio** [comment]
I did a rebase on my local repository and created a mess in the pull request. So I will make a new pull request with these changes later. Sorry for the mess...

**Pull request closed without merging**
