### PR TITLE
[vectortile] Support the 'background' concept for vector tile rendering

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR adds a tile background awareness to the vector tile renderer, alongside a mapboxgl's conversion of the background layer. 

Practically speaking, here are a couple of before (top) vs. PR (bottom):

image

image

image

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
Are we gauranteed that this will be drawn below all the other layers?

**Comment by nirvn** [comment]
@nyalldawson , not if you move the background item away from being the first item in the styles list no.

**Comment by nyalldawson** [comment]
@nirvn but will it **start** there?

**Comment by nirvn** [comment]
@nyalldawson , I've updated the mapbox gl converter code to insure that the background layer is always added as the first (i.e. bottom) style, matching the wording of the spec and possibly work around flawed json files that wouldn't respect the spec ordering.

**Comment by nyalldawson** [comment]
@nirvn thanks!

**Comment by nirvn** [comment]
I'm flagging this as a bug as this implementation gap makes for bad renderings. I feel it should be backported to 3.22, but don't feel strong enough to fight any objections. @nyalldawson , thoughts? :)

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
