### PR TITLE
Extends color expression help to mention HEX color notation

### PR DESCRIPTION
**Pull request by SrNetoChan**
Which seems to be possible to use as well

### CODE REVIEW

**Comment by nyalldawson** [comment]
While you're at it, named colors ('red') are also supported.

**Comment by SrNetoChan** [comment]
@nyalldawson what do you think?

**Comment by nyalldawson** [comment]
FYI - data defined button isn't used anywhere anymore. I'm going to remove it when I push the GUI component of properties.

**Comment by SrNetoChan** [comment]
@nyalldawson thanks for the warning. We really need to put some effort on QGIS 3 Documentation. There will be so many changes that it's hard to keep track of them all.

**Comment by DelazJ** [comment]
> FYI - data defined button isn't used anywhere anymore. I'm going to remove it when I push the GUI component of properties.

An upcoming big bang in the documentation...

**Comment by nyalldawson** [comment]
@SrNetoChan 
>  thanks for the warning. We really need to put some effort on QGIS 3 Documentation. There will be so many changes that it's hard to keep track of them all.

Actually for end users there's no difference in behavior - the new button looks and acts the same. It's just a different class, and all the strings in QgsDataDefinedButton have been moved over to the property definition class. That's why there's currently the duplicate strings, but they'll soon go, and I was wanting to just give you a heads up not to waste time with the strings in that class.

When the properties gui component lands the button will still act the same, it'll just have many extra features in the assistant option. 

Hope that makes sense!

**Pull request merged**
