### PR TITLE
add "import only selected features" option to db manager

### PR DESCRIPTION
**Pull request by aroche**
I think DB manager was lacking this feature when importing vector layers into a database

### CODE REVIEW

**Comment by m-kuhn** [comment]
Merged in 2a5f262beb2911774c078781b60223e121b24a6f

Sorry for the long delay and thank you very much for the contribution

**Comment by brushtyler** [comment]
@m-kuhn: sorry, I didn't see this PR when I looked at DBManager's PR the last week. 

Anyway, looking at your commit I see that something (maybe your IDE) has split line 332 into 332-333, then the merge command has changed line 332 only, so surely we get an error when running that code.

**Comment by m-kuhn** [comment]
It looks like @dakcarto already fixed it in 1c0b6077f8bb2c84b317731f8d868eac3d03af02
Thx

**Comment by brushtyler** [comment]
Perfect! thanks. 
Probably @dakcarto has pushed the commit few seconds after I looked at commit history :)

**Comment by brushtyler** [comment]
No, I just was looking at the wrong place I guess...
I expected to see all the commits related to the changed file by pressing View->History when looking at your commit on master. But probably that wasn't the right way. :(

**Comment by m-kuhn** [comment]
If you look at the history of the file's state at a certain commit you will only see the commits which lead to this particular version.

Replacing the commit hash in the address line with `master` will show the history that leads to the `master` version. :)

**Pull request closed without merging**
