### PR TITLE
Fix #38473, forgetting CRS in a new project

### LINKED ISSUE #38473: QGIS forgets the project CRS (and set the project to "No CRS")
QGIS forgets the project CRS when creating new documents and set it to "No CRS". Here's how to reproduce the bug with a fresh profile:

1. Open QGIS and create a new empty project (by clicking on the icon in the toolbar or Project -> New or Ctrl-N).
2. Save the empty project (you can also add some layers, this doesn't matter).
3. Close QGIS and open again the freshly saved project.
4. The project CRS is gone.

Suprisingly, this doesn't happen if you open QGIS and directly save the document (without clicking on the new document icon first).

QGIS: 3.10.9 and 3.14.15
OS: Windows 10

### PR DESCRIPTION
**Pull request by suricactus**
Literally the title

### CODE REVIEW

**Comment by uclaros** [comment]
Nice, but this feels like a workaround... Why do we have `mCrs == crs` but no entry in `mProperties` in the first place? Maybe this is where the fix should be focused?

**Comment by m-kuhn** [comment]
Possibly from https://github.com/qgis/QGIS/blob/e5218df09a6ac30738221641f3cc267e89366c0f/src/core/qgsproject.cpp#L1505 ? Would replacing this with `setCrs` also fix it? Ideally a small unit test would help.

**Comment by suricactus** [comment]
Okay, I agree it was a hacky solution. The problem really is that the CRS is not really reset after clicking on the "New project" button.

**Review by m-kuhn — APPROVED** [review]

**Comment by nyalldawson** [comment]
@m-kuhn what do you feel about backporting this to the final 3.10 release? It's not something I'd really life to do, but I think the seriousness of the issue warrants it...

**Comment by m-kuhn** [comment]
IMO it's close to 0% risk

**Pull request merged**
