### PR TITLE
Fix leaked GDAL dataset handle when deleting layers

### PR DESCRIPTION
**Pull request by nyalldawson**
or the results won't be visible till QGIS close

### CODE REVIEW

**Comment by rouault** [comment]
> or the results won't be visible till QGIS close

with which driver is this necessary ? Maybe XLSX / ODS ? More generally, opening a new dataset handle whereas a dataset handle in update mode is opened could lead to unpredictable results. Closing & re-opening is the safest way.

**Comment by nyalldawson** [comment]
@rouault I saw the issue with a GML file.

But I think now the issue may be that hDS used to delete the layer is never cleaned up here..

**Comment by rouault** [comment]
> I saw the issue with a GML file.

hum, the GML driver doesn't implement DeleteLayer...

**Comment by nyalldawson** [comment]
Sorry, that was a typo. I meant kml!

**Comment by nyalldawson** [comment]
@rouault I can confirm that the actual issue was the unclosed dataset, not the flushing. PR updated.

**Review by rouault — APPROVED** [review]

**Pull request merged**
