### PR TITLE
Fix identify tool with rule renderer and nested else

### PR DESCRIPTION
**Pull request by m-kuhn**
See https://github.com/qgis/QGIS/pull/6679#issuecomment-381890447

Nested else rules would no longer work with the identify tool

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
Could we get a test for this?

**Comment by m-kuhn** [comment]
As soon as it no longer segfaults

**Comment by nyalldawson** [comment]
Thanks! I think this logic may be duplicated in rule based labelling too, so that may also need the fix.

**Comment by m-kuhn** [comment]
Can you point me to code?

**Comment by nyalldawson** [comment]
> Can you point me to code?

Ignore me - I'm wrong!

**Comment by pblottiere** [comment]
Hi @m-kuhn,

Sorry for the regression :confused:. 

I didn't test theses changes, but it LGTM, especially seeing unit tests.

Thank you!

**Comment by m-kuhn** [comment]
@pblottiere no worries, that can happen. Any of us would vastly overestimate the own capabilities by saying that he never caused a regression :)

**Comment by roya0045** [comment]
I think this fix should have also been applied to `QgsRuleBasedRenderer::Rule::legendKeysForFeature` as the issue fixed is still present in the layout legend.

**Pull request merged**
