### PR TITLE
Adds a file to hold a map from class/method to headerfile

### PR DESCRIPTION
**Pull request by 3nids**
This file will allow us to have direct links from PyQGIS API docs to cpp header to allow direct editing.

This partially tackles https://github.com/qgis/pyqgis/issues/37

https://github.com/qgis/QGIS/assets/127259/62640b1d-69f4-4150-a035-887c6f06c5c4

### CODE REVIEW

**Comment by nyalldawson** [comment]
Pretty cool! 🤩

**Comment by lbartoletti** [comment]
Woo, many thanks! Is it possible to also have a link to the C++ API page?

**Comment by 3nids** [comment]
> Woo, many thanks! Is it possible to also have a link to the C++ API page?

Not sure, I used an [extension](https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html#confval-linkcode_resolve) to show the link and it supports only one link.

**Comment by 3nids** [comment]
unrelated test failure
this is ready on my side :)

**Comment by troopa81** [comment]
I like the proposal. One thing that bother me is that the class map YAML files would be modified every time someone modifies the API. We have already the Qt5 and 6 sip files and all these generated files are not helping review.

Could we just generate those files when needed ? meaning when documentation is generated?

**Comment by 3nids** [comment]
@troopa81 indeed it might be a bit too much traffic. Just thinking that since we have the headers installed this would be possible. I will give it a try.

Or you rewrite sipify with clang-parser to we have this at build step only? 😁

**Comment by 3nids** [comment]
This is not that trivial in the end
* I need to install the dev packages to get the headers which is a bit painful as I need a specific version
* I need to pull sipify.pl + sipify_all.sh 
* We need to install sipify.yaml config (no big deal)

Possible solutions:
* also publish images with te dev package 
* fetch the QGIS source code to get sipify + headers

I'm not super happy with both approaches.

One thing is that we could easily drop the Qt6 map file, that would lower the noise by 2. Would this be acceptable?

**Comment by troopa81** [comment]
@3nids Not sure to understand how exactly the process of building the documentation work but could we not generate the yaml files when we build the python binding instead of just [installing them](https://github.com/qgis/QGIS/pull/58054/files#diff-005a07ca82fb46b215f58a3a8f4d6d6cc6ca088ade44e8f15cc2e6a51d1da6f4R446) ?

**Comment by 3nids** [comment]
>could we not generate the yaml files when we build the python binding 

So calling sipify_all from cmake? 
This would  add a significant time overhead when building the bindings. I'm not sure that's acceptable.

I'm trying to avoid extra complexity in the building process of the Python docs (I would like to avoid maintaining a new workflow to actually compile QGIS to build the API docs). 

When you add a method to a header, then you get the same number of modified lines in the map file than the number of following non-private methods in the header (due to the modification of line number for the methods). Let's say we talk about ~5-10 lines changes.

**Comment by 3nids** [comment]
Another approach would be to run this on master branch only and automatically so we don't get any noise in the PRs. This would auto-commit on master and release branches. Basically the same workflow than the one I just merged [here](https://github.com/qgis/QGIS/pull/58057)

**Comment by troopa81** [comment]
> So calling sipify_all from cmake?
> This would add a significant time overhead when building the bindings. I'm not sure that's acceptable.

Is it that slow if we run sipify_all.sh to generate only those map files ? maybe only when installing ?

> Another approach would be to run this on master branch only and automatically so we don't get any noise in the PRs. This would auto-commit on master and release branches. Basically the same workflow than the one I just merged https://github.com/qgis/QGIS/pull/58057

I would have prefer not to have another set of generated files in git but it might be a good middle ground regarding our actual doc workflow. Could it be done just after merge without mentioning anything in the PR?

**Comment by 3nids** [comment]
> I would have prefer not to have another set of generated files in git but it might be a good middle ground regarding our actual doc workflow. Could it be done just after merge without mentioning anything in the PR?

Yes it would be done in the branches only, so no traffic/noise in PRs.

**Review by troopa81 — APPROVED** [review]
Sounds good to me!

**Comment by 3nids** [comment]
@troopa81 thanks. Let's go like this and we can still revisit the approach if we're not happy.

**Comment by kannes** [comment]
This is really useful, thank you!

**Pull request merged**
