### PR TITLE
Revised "mActionDataSourceManager.svg" icon. Scaled up layers element…

### PR DESCRIPTION
**Pull request by KentPorter-Boundless**
This PR would update the new Data Source Manager icon with an improved, revised version that stands out better in the UI.

This is an updated version of the Data Source Manager icon we recently added. 

Changes: 

- scaled up the layer elements by a couple of pixels to increase the overall size by a couple of pixels in width and height

- added darker outlines to the elements to add a bit of contrast in order make the icon pop a little more in the ui. 

Here is side by side comparison.
comparison

### CODE REVIEW

**Comment by nirvn** [comment]
@KentPorter-Boundless , nice improvement. Can you run an SVG optimizer on the SVG file to save some KBs?

**Comment by KentPorter-Boundless** [comment]
Sure. Should I run the optimizer, and then re-do the PR?

**Comment by nirvn** [comment]
@KentPorter-Boundless , that, or you can optimize the SVG, git commit the branch to catch the updated SVG, git rebase to merge the initial and updated commit together.

**Comment by KentPorter-Boundless** [comment]
Ok, will do. Thanks for the feedback and help. I will optimize and re-commit asap.

**Comment by nirvn** [comment]
@KentPorter-Boundless , thanks, merged.

**Pull request merged**
