### PR TITLE
fix crash when a sink parameter definition is missing in a processing alg

### PR DESCRIPTION
**Pull request by 3nids**
when running an alg with a missing parameter sink definition, I got a crash.
this solves it.

here is a crashing alg: https://gist.github.com/3nids/01d57ea4ca15535094cd51cd2728520b

### CODE REVIEW

**Comment by nyalldawson** [comment]
I think you'll get a crash for any of these parameter types of they don't exist, not just this one.

Raising an exception here would be preferred I think -- it should be a fatal mistake to make

**Comment by 3nids** [comment]
It's indeed better, but the message is not shown:
Screenshot 2020-03-11 at 17 49 59

**Comment by 3nids** [comment]
much better, thanks @nyalldawson 

image

**Comment by nyalldawson** [comment]
Looking good! I'd just add the name of the sink in that error too - "No parameter definition exists for a sink named 'xxxx'"

**Comment by 3nids** [comment]
@nyalldawson you don't have access to the name in `QgsProcessingParameters::parameterAsSink`, I did a try catch in `QgsProcessingAlgorithm::parameterAsSink` to send the name.

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
