### PR TITLE
[travis] Disable non-local file download tests

### PR DESCRIPTION
**Pull request by m-kuhn**
@rouault thanks for raising the issue

### CODE REVIEW

**Comment by luipir** [comment]
leaving part of code without test is it safe for you?

**Comment by m-kuhn** [comment]
Are you sure you are asking this question the right person?

**Comment by m-kuhn** [comment]
It's important to have a high test coverage with tests that are bullet proof. I am more than convinced that this is a high priority, but the reality is, that resources are required to keep things going.

**Comment by luipir** [comment]
I'm asking to you because you disabled a working test (not a flaky one). I agree that would be better to have local server, but I'm suggesting to pass through a issue and assign to the proper resource instead of leave a downloader without ssl tests.
This is a voluntary work, so would be better to pass through a assigned issue.
p.s. I found two days ago a qgsfiledownloader issue that has been fixed thaw make qgis unusable on linux/mac (not on win)

**Comment by m-kuhn** [comment]
I have no plans or intentions to kill stable tests. Feel free to propose a better solution than this one.

This approach is based on the experience that relying on outside services is an unstable approach. This could be seen in various instances in the past with a lot of very different services (qgis.org, github, docker, bit.ly,  others, ...).

**Comment by luipir** [comment]
the approach (already wrote and proposed) to maintain the test and open an issue, please give an opinion on this.

**Comment by rouault** [comment]
> the approach (already wrote and proposed) to maintain the test and open an issue, please give an opinion on this.

I'd suggest a variation: disable the test as proposed in the PR for Travis since we don't want flaky tests + file a ticket linking to the commit that disabled it

**Comment by elpaso** [comment]
> I'd  suggest a variation: disable the test as proposed in the PR for Travis  since we don't want flaky tests + file a ticket linking to the commit  that disabled it

That seems a reasonable solution. 
Btw, it would be nice if we could get more broad statistics out of cdash: I mean kill the tests that fail above a certain % value.

**Comment by luipir** [comment]
an open issue allow resource allocation to work on it.. just disabling create more and great problems allocating paid and voluntary work.

**Comment by m-kuhn** [comment]
https://issues.qgis.org/issues/17437

**Pull request merged**
