### PR TITLE
Bump minimum Qt to 5.13

### PR DESCRIPTION
**Pull request by nyalldawson**
(Motivation: I require https://doc.qt.io/qt-5/qconcatenatetablesproxymodel.html, which is Qt 5.13+ only.)

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]
❤️

**Comment by 3nids** [comment]
Considering we will only build on top of 5.15 in the CI, shouldn't we move already to Qt 5.15?
It has been released for exactly 2 years now.

**Comment by nyalldawson** [comment]
> Considering we will only build on top of 5.15 in the CI, shouldn't we move already to Qt 5.15?

I'd be +1, but baby steps. I'm not sure this will be possible to get fully working as is with the broken cdash.

**Comment by lbartoletti** [comment]
> Considering we will only build on top of 5.15 in the CI, shouldn't we move already to Qt 5.15? It has been released for exactly 2 years now.

+1 but only IFF it's ok for distributions with stable packaging.

**Comment by nyalldawson** [comment]
I'm conceding defeat here :scream:

**Pull request closed without merging**
