### PR TITLE
Extend "smooth" rendering of map canvas to include vector layers, labeling

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR extends @PeterPetrik's recent work at enabling "smooth" redraws of raster layers from https://github.com/qgis/QGIS/pull/40960, by:

- Using previously rendered versions of vector layers during temporary composition ONLY if previous renders of the layers were relatively fast (<3 seconds). Otherwise we use the previously rendered version only until we've rendered at least one feature, after which we switch to the progressive update style of rendering.
- Unlock composition using transformed previewed cache image of labeling results as well as map layers. This extends the recent addition of smooth map updates for raster layers to also apply to map labels. Now you'll see a scaled/transformed
version of the previous map render's labels while the new labeling results are being generated in the background.
 (Avoids "flashy" redraws of map labels where the labels disappear and then reappear after moving the map)

### CODE REVIEW

**Comment by nyalldawson** [comment]
@PeterPetrik for your consideration!

**Comment by nirvn** [comment]
YAAAAAYYYYYYYYYYYY!

(This primal expression of joy is said to have been heard across the globe!)

**Comment by nirvn** [comment]
Tested, it's a major UX boost here, the canvas feels much, much smoother.

**Comment by nirvn** [comment]
QGIS canvas:

https://user-images.githubusercontent.com/1728657/105953188-54973c80-60a5-11eb-86de-4a04a15a7a64.mp4



QField canvas (i.e. QgsQuickMapCanvas):
Peek 2021-01-27 13-00

**Review by PeterPetrik — APPROVED** [review]
Thanks a lot @nyalldawson , really nice addition! Now when you did this yourself,  I have to fix mesh layers too, so users have greatest experience!

**Comment by nyalldawson** [comment]
>  I have to fix mesh layers too, so users have greatest experience!

We'll need to do point clouds too, but that should be super-simple :smile:

**Comment by kannes** [comment]
Yeeeeeeeeeeeeeeeeeees! This rocks! Seems to fix https://github.com/qgis/QGIS/issues/29574, right?

**Pull request merged**
