### PR TITLE
Added FTools dialog message at plugin load/reload

### PR DESCRIPTION
**Pull request by luipir**
The scope of this pull request have to be verified by people present during Grancanaria hackfest and PSC.
It is pulled as draft. A gentle message have to be set before merge.
Please evaluate the opportunity to merge and show the message.

The pull request is applied only to FTool plugin (not to FTool ported into processing framework).

The shown dialog is showned only if QGIS version > 2.10 and plugin is active or activated.

NEXT STEPS:
If the pull request is updated and accepted, a plugin package have to be  created with new plugin version to oveload current running plugin.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Who's got the lead on this?

**Comment by luipir** [comment]
@mach0 and Giovanni Manghi are aware of the Pull Requests (they asked for the meeting)

as we decided during the issue meeting, the text content and opportunity have to be checked => it would be managed by PSC... too generic?

**Comment by alexbruy** [comment]
Maybe I miss discussion... why we need such message? Is this preparation step before fTools removal?

**Comment by luipir** [comment]
fTools need to be reviewed with the new qgis geometry engine V2

**Comment by elpaso** [comment]
@alexbruy in Las Palmas we discussed about the fTools status: since when the new geometry classes were introduces, they produce seriously wrong results.

**Comment by alexbruy** [comment]
@luipir, @elpaso thanks for clarification.

In general code looks good for me and can be merged. Just one note: maybe instead of QMessageBox it is better to use QgsMessageBar or other QGIS class for showing messages, e.g. QgsMessageOutput?

**Comment by luipir** [comment]
@alexbruy you are right, but probably not in this case... BTW it will be a Psc Decision how to comunicate

**Comment by mach0** [comment]
sent the testcase to @alexbruy
let's keep this problem on top to be solved somehow soon.

**Comment by mach0** [comment]
I think it would be important to inform the users about results being displayed but actually being WRONG. IMHO we need to communicate it in an open way. and if nothing happens regarding the tools we should just deactivate them before the next LTR release. It would be bad to ship algorithms which produce wrong results..

**Comment by luipir** [comment]
The idea is:

1) add a warniong message in a "open way" as Marco @mach0 - step in charge to PSC I suppose
2) package a new versionof the plugin with the new warning message. The branch will be hosted and distributed in the same way as Processing. In this way all installations will update FTools with the new message. Metadata.txt min and max version would be min=2.10 and max=2.13.99
3) Disable FTool for current QGIS package

-------- when a new correct FTool will be available -----
4) package and activate the new version in the current QGIS release and master
5) package a new FTool fixed version and distributed as Processing. Metadata.txt min and max version would be min=2.10 and max=2.13.99

**Comment by luipir** [comment]
closing due to fix 594fafe73b80d91d94b962c2e51aea0b0168a08a

**Comment by anitagraser** [comment]
more info in http://lists.osgeo.org/pipermail/qgis-developer/2015-November/040445.html

**Pull request closed without merging**
