### PR TITLE
fix feature list combo box having identifier value further than fetching limit

### PR DESCRIPTION
**Pull request by 3nids**
see discussion in #37266

I believe the issue was introduced here: https://github.com/qgis/QGIS/pull/34943/files#diff-bee409cb02c75d3272f877c88ea1e86eR277

### CODE REVIEW

**Comment by andreasneumann** [comment]
I confirm that the issue is fixed with this branch in master. Just compiled and tested.

**Comment by 3nids** [comment]
After discussion with @m-kuhn, we will merge this in for 3.14, but wait for 1 cycle for 3.10.
Reasoning is that data corruption is involved but the risks involved with that piece of code are not negligible.

A better fix might follow-up (avoiding the addition of the new member), but some side effects with the chain filters in the relation reference widget are expected.

Waiting for Travis for the green light, and this will be merged before the release.

**Comment by nyalldawson** [comment]
> After discussion with @m-kuhn, we will merge this in for 3.14, but wait for 1 cycle for 3.10.
Reasoning is that data corruption is involved but the risks involved with that piece of code are not negligible.

:+1:

**Comment by troopa81** [comment]
@3nids Thank you for dealing with this and sorry to not answer sooner, I was afk. 

The fix looks good to me, and I think it's a wise decision to wait before backporting it in 3.10.

**Pull request merged**
