### PR TITLE
Make it possible to build just core lib and providers: -DWITH_GUI=FALSE

### PR DESCRIPTION
**Pull request by wonder-sk**
This is useful in some cases when working on a third party app/script
that only uses qgis_core. For example, I am working on qgis 3D project
and it is useful to be able to build QGIS core lib with custom Qt version
without having to spend too much time building what I do not need.
Also may be useful for QField to simplify the build of QGIS as a dependency
(no QScintilla, Qwt) and avoid bits of code in providers that would not
be used anyway.

No real source code changes, just configuration changes, mainly in providers.

### CODE REVIEW

**Comment by NathanW2** [comment]
Nice.  This could be very handy also for server?

**Comment by wonder-sk** [comment]
> Nice.  This could be very handy also for server?

That's right - although right now for some reason server links qgis_gui as well :scream: ... maybe something to sort out during the server refactoring (cc @rldhont @haubourg). It would nicely cut down dependencies of QGIS server.

**Comment by NathanW2** [comment]
Composer stuff I suspect.  I'm sure our man @nyalldawson can fix that issue ;)

**Comment by m-kuhn** [comment]
Love it!

**Comment by nyalldawson** [comment]
> Composer stuff I suspect. 

I can't see why - there's not much composer stuff in gui

**Comment by NathanW2** [comment]
I was stabbing wildly in the dark ;)

**Comment by m-kuhn** [comment]
editorwidgets used to be something, maybe it's just a leftover, checking...

**Comment by haubourg** [comment]
@mhugo @vmora @pblottiere  can you remind us why it is not possible to avoid a link to GUI in server?

**Comment by m-kuhn** [comment]
editorwidgets indeed, everything else works, should not be hard thanks to the work by @pvalsecc with QgsEditorWidgetSetup

**Comment by mhugo** [comment]
@wonder-sk nice !
For the server I think what would even be better is to avoid dependency on an X server. Which seemed really hard from [our last analysis](https://github.com/qgis/qgis3.0_api/issues/66): qgis_core links to QtGui or at least to components that require an X server (QFont for rendering labels for instance)

But a server without qgis_gui would definitively be a good thing :)

**Comment by wonder-sk** [comment]
Removal of X dependency in server would be nice too - but first things first - let's get rid of qgis_gui in server - volunteers needed :-)

**Comment by m-kuhn** [comment]
https://github.com/qgis/QGIS/pull/4824

**Pull request merged**
