### PR TITLE
[theme] fix invisible text in field expression widget in dark themes

### PR DESCRIPTION
**Pull request by 3nids**
only on MacOS at the moment

### CODE REVIEW

**Comment by nirvn** [comment]
@3nids , I'm -1; the proper fix is to set the text color to the widget's normal text color when the expression is valid and avoid arbitrary color (black or white) altogether.

**Comment by 3nids** [comment]
@nirvn good point, fixed

**Comment by nirvn** [comment]
Nice, thanks for implementing the alternative approach.

**Review by m-kuhn — APPROVED** [review]
LGTM

**Pull request merged**
