### PR TITLE
[Processing] Add the last GRASS7 r.* algorithms

### PR DESCRIPTION
**Pull request by ghost**
## Introduction

Here is a big PR which includes all the GRASS7 r.\* algorithms that are not already in Processing.
The only algorithms that are not included are:
- r.proj, because it uses only GRASS location and we already have an algorithm to make re-projection (qgis Reproject Layer).
- r.timestamp is incorporated into r.support.

For the list of algorithms, just read commit comments...
## Fixes

It should fix/implement the following bugs/feature requests:
- [Redmine #5724](https://hub.qgis.org/issues/5724) (the big one).
- [Redmine #6894](https://hub.qgis.org/issues/6894) about r.mapcalc.
- [Redmine #13003](https://hub.qgis.org/issues/13003) about r.drain.
## Tech

I have used the 'ext' mechanism (introduced with v.net algorithms) to deal with "non standard" Processing GRASS behavior.

I have tested every algorithm with different rasters and they are always able to produce something out. But I haven't tested all of the options for each of the algorithms...

Python code in ext directory could be factorized a little bit more but I will make this work after GRASS7 algorithms completion. It will be easier to regroup functions and methods when everything will be implemented.

For some algorithms, I had to use r.in.gdal (which duplicates the input raster into the temp directory) instead of r.external. r.colors and every algorithm that uses raster labels are affected (this is the only way for them to work).
## What can be modified/discussed before merging ?
- For r.li.\* algorithms, there was a real problem: the configuration files for the algorithms are imported from a fixed directory (~/.grass7/r.li) and this is the same thing for files that are produced by the algorithms. I have implemented a copy/remove operation. But I have made my tests only under GNU/Linux Debian (Stretch).
- r.li.\* algorithms can produce rasters or ASCII files, depending on the content of the configuration file. I have made two versions for each r.li.\* algorithm (perhaps is it too much ?):
  - r.li.xxxx for raster output.
  - r.li.xxxx.ascii for ascii output.
- For r.mapcalc, you are able to generate data from an expression (with the region extent) without any input raster.
- When you want to use raster names into r.mapcalc, use the basename of the raster file. I have chosen this behavior (instead of using QGIS layer names) because you can use r.mapcalc with external files (on batch mode for example). You have to know the raster name from its filename.
- r.mapcalc output is a directory because you can make raster calculations on a set of rasters. Each raster that has been used (and produced) by r.mapcalc is exported into this output directory. If you use 6 rasters to create 2 new rasters, you will have 8 rasters in the output directory.
- I have made very few tests under MS-Windows and there could be some problems with algorithms that have OutputDirectory (I am using shell commands to export into the output directory). I will make tests on them soon but feel free to test under this operating system or under Mac OSX.
## What about unit tests ?

Well, I am sorry but I haven't made Processing unit tests for those algorithms, mainly because I started to work on them before @m-kuhn published the framework. I think I will try to build all the unit tests for all rasters as soon as this PR will be merged (with a computer assisted test file generation).
## Why doing a big PR instead of separate smaller PRs ?

With time, PR "waiting for merge" list is growing. I have already written some smaller PRs for Processing GRASS7 (one per bug). But this time the PR is mainly for a (big) feature request. Less PR to merge means less administrative work for developers who have commit rights...
... but it requests much more time for code review (thanks to @volaya and @alexbruy for this work) !

Furthermore, there was no easy way to group algorithms together...
## What next ?

I intend to do the same work for vectors (v._) and images (i._) GRASS7 algorithms before QGIS 2.16 ;-)

### CODE REVIEW

**Comment by m-kuhn** [comment]
It will be cool to have unit tests one day but at the moment I'm happy to focus on the qgis algorithms (and some gdal ones) first.

But if you want to start unit-testing these as well, just ping me and I'll assist wherever required to get the grass infrastructure up and running as well.

**Comment by fsdias** [comment]
@volaya @alexbruy

**Comment by gioman** [comment]
@medspx one word... huge! thanks for this.

**Comment by alexbruy** [comment]
Indentation test failed, can you fix it?

**Comment by volaya** [comment]
thanks for this fantastic work! All sounds good to me, but there seem to be merge conflicts. Can you fix that? I will merge once that is done

Thanks again, this is really a great PR!

**Comment by medspx** [comment]
Ok, I've fix the merge conflict...

**Pull request merged**
