### PR TITLE
Update default toolbar arrangement to move short layer toolbar from left to top

### PR DESCRIPTION
**Pull request by nyalldawson**
Now that the layer toolbar is very short (following the data source manager changes), there's a LOT of wasted space by placing this toolbar vertically on the left. Instead move it to the top and gain a centimetre or two extra canvas space in the default arrangement.

@nirvn as discussed

### CODE REVIEW

**Comment by nyalldawson** [comment]
Here's the before -- note the wasted vertical space on the left

https://user-images.githubusercontent.com/1728657/36349275-4a1e05de-14b5-11e8-8696-c3483dcd6150.png

And the after:
screenshot from 2018-02-23 09-41-51

**Comment by nyalldawson** [comment]
Also has the side-effect of better balance between the two horizontal toolbars - before they were very unbalanced with the top one having many more icons.

**Comment by NathanW2** [comment]
Does it make more sense to be on the top toolbar?

**Comment by nirvn** [comment]
@nyalldawson , looking good.

**Comment by nirvn** [comment]
It's a bit difficult to review hex values ;) did you make your updated default based on a new profile to begin with, and opened the layout designer once? Not opening the designer once would lead to it's defaults gone.

**Comment by nyalldawson** [comment]
@nirvn I didn't touch the layout defaults - I omitted them from the commit.

@nathanw2 I tried that at first, but they are actually much more prominent by being on the left on the second row then somewhere in the middle of the top.

**Pull request merged**
