### PR TITLE
Move custom expression function help to group box

### PR DESCRIPTION
**Pull request by NathanW2**
Moves the custom expression help out of the function template and into a group box that the user can hide.  After you have done a few custom expressions you really don't need to see this help every time.

image

Final Screenshot
image

### CODE REVIEW

**Comment by nirvn** [comment]
What did it look like before?

**Comment by NathanW2** [comment]
image

@nirvn  like this

**Comment by nirvn** [comment]
Looking better indeed.

Few additional suggestions: 
- expand the label for the "load" button to make it less obscure
- move the new file button to be located below the file list

**Comment by NathanW2** [comment]
Update from feedback

image

**Comment by NathanW2** [comment]
Updated icons

image

**Comment by nirvn** [comment]
Looking good

**Comment by DelazJ** [comment]
Much better indeed with this big text out of the writing area but:
* what about using vertical frames (like the expression tab), allowing to see more lines of the code being written? coders don't really need such a wide writing area, I guess
* Isn't that weird to have the button to create the file at the bottom and the one to save it at the top?
* could the help be [translatable](https://issues.qgis.org/issues/19768)? It's just a blocker for non-english speaker

**Comment by NathanW2** [comment]
Help closed looks like this

image

**Comment by NathanW2** [comment]
@DelazJ 

>what about using vertical frames (like the expression tab), allowing to see more lines of the code being written? coders don't really need such a wide writing area, I guess 

Generally the help would be closed most of the time giving you more area to work with. 

> Isn't that weird to have the button to create the file at the bottom and the one to save it at the top?

Swapped it to the bottom to follow the conventions in the rest of the app at least for now.  

> could the help be translatable? It's just a blocker for non-english speaker 

It can be now yes

**Comment by NathanW2** [comment]
Another update to match style of add button 

image

**Comment by nyalldawson** [comment]
More requests:

- could the "save and load button" be moved below the script editor? that's the flow you need to do - edit the script, and THEN save
- should be "Save and Load Functions" (capitalization)

**Comment by NathanW2** [comment]
@nyalldawson nope. Merged. No more requests :P 

Yep I will get them fixed up now.

**Comment by DelazJ** [comment]
@NathanW2 Thanks. 
PS: This change would have required the [needs-docs] tag 😠

**Comment by NathanW2** [comment]
@DelazJ I have a follow up commit.  I can add it to that if you want

**Comment by DelazJ** [comment]
Please do. Other than having a doc inline with GUI, these small changes are a good way to attract new writers.
Next step would be a "minus" button here to delete test/wrong/unneeded python files from user profiles (see https://issues.qgis.org/issues/19688 - /me trying to sell new features ;) )

**Comment by NathanW2** [comment]
@DelazJ  yep I will be adding the delete button in the next PR, not being able to delete old files is a bit annoying.

**Pull request merged**
