### PR TITLE
 fix #18299 date time widget does not correctly set value from calendar

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by m-kuhn** [comment]
@gacarrillor would you have the chance to test this pull request?

**Comment by gacarrillor** [comment]
Yeap, I've just tested it, but still get random issues (on any of the three date time widgets of such form). 
dock_widget_20180307_1210

**Comment by 3nids** [comment]
I guess the issue is different now...the former random issue was from the click position on the button: if you clicked on the arrow symbol it was working as expected but not if you were clicking slightly off the icon. This doesn't seem to be the case anymore on your new screenshot (thanks for doing them!).
I will continue investigating!

**Comment by 3nids** [comment]
@gacarrillor can you try with the slightly updated version?

If that doesn't work (I couldn't reproduce with your data), can you see:
- if it depends on the click position on the button (bottom/top part of the button, inside/outside the arrow)
- if it depends on the chosen date (today/not today)

Can you tell me what is your Qt version? We suspect it could be an issue in an old version of Qt.

Thanks again for reporting and testing.

**Comment by gacarrillor** [comment]
The issue has always been choosing the current day, with other days we haven't found problems.
I use Qt v5.5.1.

I spent minutes trying to replicate the issue against https://github.com/qgis/QGIS/pull/6548/commits/f88edea3064bd58c3ff88118d6ab2b6f9c4c872d, but I couldn't :D So, it seems you've solved it! 
Since we regularly test the plugin on different environments (for instance in workshops we hold), I'll reopen the issue if it happens again. Let's hope it has gone!

_Just an aside note: If I open the widget and do nothing but pressing `ENTER` from the keyboard, I get the same behaviour that made me report this issue: the date is left in grey, but as soon as I change the focus to another field, the date is replaced by a `NULL` value. Don't know if that's the intended behaviour or if that helps you understand what's going on there._

Thanks for your patience!

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
