### PR TITLE
[ui] improve new geopackage layer window

### PR DESCRIPTION
**Pull request by nirvn**
## Description
While we should all celebrate the move to make geopackage the preferred new file-based layer (demoting shapefile as an alternative), IMHO it led to a UX regression for the average user: the new geopackage layer dialog is much more intimidating than the new shapefile layer dialog.

More specifically, some more advanced options - like feature id column, geometry column, spatial index - an less frequently used ones - layer identifier vs. table name, layer description - clutters the dialog and doesn't make it that welcoming at first glance.

This PR moves some elements around and put some fields under a collapsible "advanced options" group.

Before vs. proposed:
screenshot from 2017-11-21 16-27-28

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
+1

Can you also change the wording for "geometries with z/m coordinate"? It's rather awkward. I think better wording would be "include z dimension" and "include m values".

**Comment by Gustry** [comment]
+1 very good, thanks!

I would move Z and M options into the advanced group box too but not strong opinion.

**Comment by nirvn** [comment]
Reworked wording for Z dimension and M values (as well as a horizontal better placement):
screenshot from 2017-11-21 16-49-09

**Comment by nyalldawson** [comment]
@nirvn your screenshot above just revealed another UX issue :P those checkboxes should be disabled if the layer type is "non spatial"!

**Comment by nirvn** [comment]
@Gustry , I thought about it but decided against. We need to promote the fact that we're in 2017! ;-P

**Comment by nyalldawson** [comment]
Great changes!

**Comment by NathanW2** [comment]
Nice work.

**Comment by DelazJ** [comment]
Nice work @nirvn Less intimidating indeed 
Shouldn't we take this opportunity to harmonize the create new xxx layer dialogs? I see you tackled memory layer also but wonder if the main structure of the dialogs shouldn't be questioned:
 * In gpkg, user selects the DB, add information about the table (name then type - the (geometry) type is selected in a drop box), add fields..;
* In shapefile, the file name is added at the end of the process (in another dialog), geometry types are radio buttons
* In SpatiaLite, type (in radio buttons) is set before DB and layer name (at the middle of the dialog)
* In memory Layer, name is set at the bottom, with types in radio buttons

A unified structure (following the gpkg one) would be very nice imho

**Pull request merged**
