### PR TITLE
[Processing] Small fixes and additions

### PR DESCRIPTION
**Pull request by radosuav**
Please see commit messages for details.

### CODE REVIEW

**Comment by gioman** [comment]
assigned @volaya @alexbruy

**Comment by radosuav** [comment]
Hi, would it be possible to asses/merge this pull request before feature freeze? Thanks!

**Comment by volaya** [comment]
Looks good to me except for the sublayer stuff. I don't think it is a good idea to show the sublayer selector when calling the method in the parameters module. Everything in that module should have no UI elements at all. The UI code should be on the parameters dialog. You can remove those two commits and I will merge the rest, and then we can discuss how to better implement the support for sublayers. Is that ok?

**Comment by radosuav** [comment]
Hi Victor, thanks for looking at the code. I have now removed the sublayer commits and will create a new pull request just with those changes. I also agree that parameters module is not the best place for UI elements so I will try to move the code to InputLayerSelectorPanel. I hope to have that ready today to give you a chance to have a look at it before Friday.

**Comment by volaya** [comment]
Does the crs improvement work for you? The PArameterCRS class stores the EPSG code as value, not the CRS object, so it cannot use a custom CRS definition. Am i missing something?

**Comment by radosuav** [comment]
The important change is on lines 55-61. When the user selects a user defined projection (e.g. USER:100000) in the QgsGenericProjectionSelector then the ParameterCRS stores the proj4 string of the projection instead of its EPSG code. The reason for that is that user defined projections are stored in ~/.qgis/qgis.db so outside algorithm providers (e.g. GDAL or GRASS) are not able to translate USER:100000 into proj4 later on.

**Comment by radosuav** [comment]
Example with GDAL warp

1:
step1

2:
step2

3:
step3

**Comment by volaya** [comment]
ok, i get it. So then the value of the crs parameters is not the authid, but any string that can later be used to create a QgsCoordinateReferenceSystem object. Sounds good to me,

One little thing. Can you change this comment to reflect what i wrote above?

https://github.com/qgis/QGIS/blob/master/python/plugins/processing/core/parameters.py#L120

**Comment by radosuav** [comment]
Sorry I mixed something up with GitHub. The pull request is now here https://github.com/qgis/QGIS/pull/1852.

**Pull request closed without merging**
