### PR TITLE
Cleanup geometry validation dock before QgsApplication exit 

### PR DESCRIPTION
**Pull request by nyalldawson**
Refs #20283, possibly fixes it based on a crash report obtained by @NathanW2 
image

### CODE REVIEW

**Comment by NathanW2** [comment]
Thanks.  Sorry, my builds are busted so wasn't able to get a fix quick enough.

**Comment by nyalldawson** [comment]
Nah all good - I'm not 100% sure if this will fix the issue (I can't reproduce it myself), but it can't hurt. Fingers crossed!

**Review by m-kuhn — APPROVED** [review]
Thanks!

**Comment by NathanW2** [comment]
@nyalldawson If you get a sec would you be able to backport this into 3.4 for me.  I just don't have access to my build at the moment sorry.

**Pull request merged**
