### PR TITLE
fix translation problem when changing locale with not translated formula. Fixes #32753

### LINKED ISSUE #32753: Modeler and Raster Calculator fail to calc
Hi all,

context: Raster Calculator added in a Processing model + 1 rasters as input
Using the Raster Calculator module inside a Model I have an output always as float raster with [-1.7: 1.7]

This only happens if the interface is in Italian or Spanish.
Everything works correctly with the interface in English.
I have not verified with other languages

Maybe there's a related issue at
https://github.com/qgis/QGIS/issues/27130

Thanks

### PR DESCRIPTION
**Pull request by luipir**
## Description
This fix a #32753 locate translation problem. Probably not completly fix also #33317 on which I've to investigate more.
The fix try to do the do variable lookup inside translated formula less translation dependent => more robust

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by nyalldawson** [comment]
This all looks very fragile. I think we need to revisit the original fix here and try something more robust.

A possible approach could be to assign a uuid to all the ouputs. Immediately after the expression is built in the widget the strings displaying layer names in the expression are replaced with the uuid, and that's the version that is stored in the model. So we'd never be storing the translated strings as part of th expression...

**Comment by luipir** [comment]
> A possible approach could be to assign a uuid to all the ouputs

hmmm... I hadn't time to think all possible use cases, but I almost agree to refactor this part. IMHO a mechanism similar to gdal raster calculator, e.g associate symbolic name to variables but not related to UUID that can change for each run.
IMHO a refactoring would maintain the following characteristic:
1) formula should visualise reference to the source algorithm (as now). this is different solution respect gdal calculator
2) formula should have a shadow version that is translation independent and it is linked with the formula (=> we could loose the ability to have a simple cut&paste other then reintroducing remapping and translation problems)
3) visible and shadow formula should be saved in the model
4) shouldn't brake model where raster calculator is already used (sadly a remapping is still necessary :/ ) but probebly there is the original error I did to avoid a deep refactoring of the alg when I reintrodced.

any suggestion how to proceed @nyalldawson?

**Comment by luipir** [comment]
I'll reopen it later when I'll have time to do a refactoring of the calculator... it's a shame :/

**Comment by agiudiceandrea** [comment]
Hi @luipir, was this PR refactored elsewhere?

**Comment by luipir** [comment]
> Hi @luipir, was this PR refactored elsewhere?

no... I hadn't time to dig it more

**Pull request closed without merging**
