### PR TITLE
New 3d symbols. Blender files in: https://github.com/raymondnijssen/q…

### PR DESCRIPTION
**Pull request by raymondnijssen**
…gis_3d_objects

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Nice, do you have screenshots?

**Comment by m-kuhn** [comment]
No worries I'll ignore any nice rendering effects. I really like that the Q(GIS) logo is rounder than the tree.

Do we have animations? Like the bomb exploding?

**Comment by wonder-sk** [comment]
Like this?

giphy

**Comment by m-kuhn** [comment]
That might be an easter egg for the next release

**Comment by raymondnijssen** [comment]
Will anyone pull this or do I first need to please core committers in some way?

**Comment by m-kuhn** [comment]
> Will anyone pull this or do I first need to please core committers in some way?

Is that an offer?

**Comment by mach0** [comment]
ok @m-kuhn - what was the pleasing worth? ;)

**Comment by raymondnijssen** [comment]
tnx! :)

**Comment by NathanW2** [comment]
I wonder if we need to make a new repo for these to avoid blowing the size of the main code repo right out as more stuff is added?

**Comment by timlinux** [comment]
image

**Pull request merged**
