### PR TITLE
QgsSpatiaLiteProvider changes Part 1

### PR DESCRIPTION
**Pull request by mj10777**
Initial adding of SpatialiteDbInfo, SpatialiteDbInfo and QgsSpatiaLiteUtils without Provider changes.

## Description
Based on https://github.com/qgis/QGIS/pull/5033

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

This part add the SpatialiteDbInfo, SpatialiteDbLayer and QgsSpatiaLiteUtils classes, which read, analyses a Sqlite3 container to determine if the container contains data that can be used by a QQGisDataProvider.

The main use of this class is from inside a QgsSqliteHandle class which is used to make the connection.

The QgsSpatiaLiteConnection version used for this partial pull request contains many functions from the original version, that in the future will **not** be needed, but had to be added so that this could compile.

These functions are inside a '#ifdef 1' statement inside qgsspatialiteconnection.cpp and .h

`
#if 1
// BEGIN: remove everything inside '#if 1' for final new version with SpatialiteDbInfo

...

// END: remove everything inside '#if 1' for final new version with SpatialiteDbInfo
#endif
`

### CODE REVIEW

**Comment by mj10777** [comment]
For some reason 2 files from the testdata has been added to this pull request that are not a part of this request and should be ignored (and if possible deleted).

**Comment by m-kuhn** [comment]
Thanks @mj10777 

I still see plenty of rasterlite2 changes all over the place, can you remove them?

```
git reset --mixed HEAD^
git checkout -- tests
# Find any leftovers of the rasterlite 2 changes and remove them
git add src
git commit
git push -f
```

**Comment by m-kuhn** [comment]
By the way, just to be clear, the idea was not to split it into chunks by making pull requests for individual files. The idea is to split it into building blocks, parts that can be merged individually and make sense on their own.

**Comment by mj10777** [comment]
> I still see plenty of rasterlite2 changes all over the place, can you remove them?
It is part of what the class does: determine what the Database offers.
This for the upcoming Spatialite 4.5.0 of which RasterLite2 is a part of.

**Comment by mj10777** [comment]
> The idea is to split it into building blocks, parts that can be merged individually and make sense on their own.

Without these classes, which the other classes retrieve when needed.
(You can#t build the 2nd floor without the first.)

**Comment by m-kuhn** [comment]
If this is the second floor already, start with the first one.

**Comment by mj10777** [comment]
No, this is the first floor - the reading of the Database.

**Comment by m-kuhn** [comment]
So rasterlite is the garage ;)
And some parts can be regarded as furniture ;)

**Comment by mj10777** [comment]
RasterLite2 is only a small part of this.

But it is true that Vector and Raster are coming together.
GeoPackage is a good sample. PostGis (I believe) also.
More and more both must be supported in 1 place.

With the new QgsSpatiaLiteSourceSelect you can select and submit both in one step.

I do a lot of work with both and that experience has lead to simplifying of this work process.

**Comment by m-kuhn** [comment]
I'm just saying try to keep pull requests as small while still self-contained as possible. That does neither confirm nor critizise your statement. It just says: please let's discuss this separately.

**Comment by mj10777** [comment]
A real life scenario is may help to make this clear.

My main Database (Historical borders, streets of Berlin) contains about 170 SpatialViews for the good 20 Dates from 1750 to today.

When this project is loaded, the Database is read once and the Data contained in the QgsSqliteHandle and is shared through all 170 connections.

When I which to add something else, selecting QgsSpatiaLiteSourceSelect pops up because the Data is already there.

**Comment by mj10777** [comment]
I understand your problem, believe me.

The main part is this, this is what is different,
The rest simply remove the reading function that are no longer needed and the retrieving what they need from the new class.

**Pull request closed without merging**
