### PR TITLE
Update astyle to version 2.05

### PR DESCRIPTION
**Pull request by m-kuhn**
This updates astyle to version 2.05

C++11 Support
============

This has support for newer constructs (our code is now C++11) such as range based for loops
```cpp
for ( const auto& item : container )
```

which are not supported by the current version.

Indentation
========

It also changes indentation a bit:

E.g.

```cpp
     gdalShares << QCoreApplication::applicationDirPath().append( "/share/gdal" )
     << appResources.append( "/share/gdal" )
     << appResources.append( "/gdal" );
```

becomes

```cpp
     gdalShares << QCoreApplication::applicationDirPath().append( "/share/gdal" )
                << appResources.append( "/share/gdal" )
                << appResources.append( "/gdal" );
```

which I like

And

```cpp
QgsBench::QgsBench( int theWidth, int theHeight, int theIterations )
    : QObject()
    , mWidth( theWidth )
    , mHeight( theHeight )
    , mIterations( theIterations )
    , mSetExtent( false )
    , mUserStart( 0.0 )
    , mSysStart( 0.0 )
    , mParallel( false )
```

becomes

```cpp
QgsBench::QgsBench( int theWidth, int theHeight, int theIterations )
  : QObject()
  , mWidth( theWidth )
  , mHeight( theHeight )
  , mIterations( theIterations )
  , mSetExtent( false )
  , mUserStart( 0.0 )
  , mSysStart( 0.0 )
  , mParallel( false )
```

about which I don't care too much.

Break one-line-blocks
================

It also breaks one-line-blocks

So that e.g. 
```cpp
int count() { return mData.count(); }
```
will become

```cpp
int count()
{
    return mData.count();
}
```

Pointer and reference alignment
========================

Pointers and references are aligned to the type when used in declarations.

```cpp
QgsVectorLayer *layer;
QgsRasterLayer * rl;
const QgsRectangle &rect;
const QString & string;
```

becomes

```cpp
QgsVectorLayer* layer;
QgsRasterLayer* rl;
const QgsRectangle& rect;
const QString& string;
```

### CODE REVIEW

**Comment by 3nids** [comment]
This is in QGIS developer guide:
image
https://www.qgis.org/fr/site/getinvolved/development/qgisdevelopersguide.html

Therefore, it's a good point to force this!

**Comment by nyalldawson** [comment]
I've made changes to add support for various newer keywords - but I suspect they would be present in the newer astyle anyway

**Comment by m-kuhn** [comment]
I assume so.
That's also why I ran it on core/* so we can check directly in this PR if there's something that freaks it out.

**Comment by NathanW2** [comment]
+1 very nice

**Comment by m-kuhn** [comment]
Any objections to merge this?

**Comment by wonder-sk** [comment]
Personally I am not a big fan of curly braces for single line statements. I have never seen a bug caused by that, and the code is IMHO more compact without the extra braces.

The developer guide contains some outdated pieces so I would not follow it too strictly :-) (it also recommends Yoda conditions which we do not follow at all).

So for me -0

**Comment by 3nids** [comment]
Anyway, the developer guide you must respect :)

**Comment by m-kuhn** [comment]
> Personally I am not a big fan of curly braces for single line statements. I have never seen a bug caused by that, and the code is IMHO more compact without the extra braces.

Same for me, but I hate oneliners

    if ( a ) make ( b );

The curly braces are more of a side-effect.

**Comment by wonder-sk** [comment]
Then isn't there are way to just make the one-liners into two-liners without adding braces everywhere? :)

**Comment by m-kuhn** [comment]
I haven't found one

**Comment by wonder-sk** [comment]
14K of new lines of code just with extra braces... Hmmmm...

**Comment by nyalldawson** [comment]
There goes the 10k lines I saved with deleting deprecated stuff :p 

But we need more commits like this if anyone is every going to catch up to @jef-n's stats!

I also *hate* those one liners, but like unbracketed ifs. So +0 from me.

**Comment by jef-n** [comment]
Also looked into this once - didn't find a way to get rid of the oneliners without having to use braces and that IMHO took away a lot of the gain that killing the oneliners would have been.    Didn't I manually clean up lots of them?   Who likes them anyway?

**Comment by m-kuhn** [comment]
Updated without the forced curly brackets on oneliners.

What it still does is expand singlelines in headers.

    int count() { return mData.count(); }

will become

    int count()
    {
        return mData.count();
    }

but I think that's fine for readability.

**Comment by m-kuhn** [comment]
**Updated pull request description.**

After realizing that our requirements for breaking single-line-statements without introducing brackets cannot be put in place with astyle, I have listed what the current state does and rebased it against the latest master.

Please review the topmost post, which outlines the most important changes introduced by this pull request.

If there is no objection, I'd like to merge this soon.

**Comment by nyalldawson** [comment]
No objections here.

**Comment by m-kuhn** [comment]
Pointer and reference alignment added:

```cpp
QgsVectorLayer *layer;
QString & string;
```

becomes

```cpp
QgsVectorLayer* layer;
QString& string;
```

**Comment by romanzoller** [comment]
Have you considered using [Clang-Format](http://clang.llvm.org/docs/ClangFormat.html)? It seems to be more flexible than astyle (e.g. you can set [ConstructorInitializerIndentWidth](http://clang.llvm.org/docs/ClangFormatStyleOptions.html#configurable-format-style-options) if you want to keep the current style of constructors) and more up-to-date with C++11 features. Unless there is a problem with the current style, I think it's best to change it as little as possible, as this makes it easier to understand git history.

**Comment by m-kuhn** [comment]
Thanks for the hint, looks really nice.

**Comment by m-kuhn** [comment]
@romanzoller one thing I can't fix is the indentation following access modifiers:

```
 class QgsPointCompare
 {
-  public:
-    explicit QgsPointCompare( double tolerance )
-        : mTolerance( tolerance )
-    {  }
+public:
+  explicit QgsPointCompare( double tolerance )
+      : mTolerance( tolerance )
+  {
+  }
```

The `AccessModifierOffset` itself can be specified, but the declarations in between do not receive any extra indent.

**Comment by romanzoller** [comment]
Yes, indeed it seems that an option for that is missing...

All I found is someone with the same issue and screenshots: http://stackoverflow.com/questions/40178333/indent-members-in-header

**Comment by m-kuhn** [comment]
It's even worse in that it reformats the comments because of this which is an absolute no-go...
 
```
-    /**
+  /**
      * Default constructor
      * @param myLayer source vector layer
```

Too bad, I almost started to like it.

**Comment by romanzoller** [comment]
At least I think QGIS should qualify as a "large project", so if you add that to the [feature request](https://llvm.org/bugs/show_bug.cgi?id=19056) at llvm, they might eventually add it. (Which of course implies to keep using astyle for the time being...)

**Comment by jef-n** [comment]
On Tue, 22. Nov 2016 at 02:50:46 -0800, Matthias Kuhn wrote:
> Pointer and reference alignment added:
> 
> ```cpp
> QgsVectorLayer *layer;
> QString & string;
> ```
> 
> becomes
> 
> ```cpp
> QgsVectorLayer* layer;
> QString& string;
> ```

IMHO that's wrong.  It should be:

> ```cpp
> QgsVectorLayer *layer;
> QString &string;
> ```

blank between specifier and declarator - and not in the middle of the
declarator. As in

```cpp
foo *bar, *baz;
```

and not

```cpp
foo* bar, *baz;
```

**Comment by m-kuhn** [comment]
Yep, that's where it gets messy (and where I think the C standard took a bad decision).

I'd go for

```cpp
foo* bar;
foo* baz;
```

**Comment by jef-n** [comment]
And I'd go for
```cpp
foo *bar;
foo *baz;
```

**Comment by m-kuhn** [comment]
Only for the reason listed above or are there others (except for personal preference of course ;) )?

The main reason why I prefer it this is that the pointer is part of the type and not the name and writing it next to the type makes this explicit - and it also makes the different use of declaration vs. dereferencing clearer. It was also [shortly discussed recently here](https://github.com/qgis/QGIS/pull/3788#discussion_r88779995).

**Comment by nyalldawson** [comment]
My 2c: While I personally prefer pointer aligned to type (just looks more natural to me), I prefer consistency more. So I'm happy to see this move forward either way

**Comment by jef-n** [comment]
I used to see it that way - but that doesn't work when you use list (or more complex stuff like function pointers).   The specifier just isn't the type and there are cases, when you can't even make it look that way (eg. function pointers)  So I'd prefer "mine" as it's consistent in any case.

**Comment by jef-n** [comment]
> Anyway, the developer guide you must respect :)

No only code can be fixed ;)

**Comment by m-kuhn** [comment]
Thanks @jef-n, interesting information

> when you can't even make it look that way

out of curiosity, do you have an example for this?

**Comment by m-kuhn** [comment]
@romanzoller 

> New user self-registration is currently disabled. Please email llvm-admin@lists.llvm.org if you need an account.

No response in 10 days... Looks like we are still on the good side with our signup process on osgeo :tada:

**Comment by romanzoller** [comment]
> > New user self-registration is currently disabled. Please email llvm-admin@lists.llvm.org if you need an account.
> 
> No response in 10 days...

Same for me, I also emailed 10 days ago...

**Comment by 3nids** [comment]
a new option `break-one-line-headers` has been added in 2.06 (see [release notes](http://astyle.sourceforge.net/notes.html))

**Comment by 3nids** [comment]
superseded by #4202

**Pull request closed without merging**
