### PR TITLE
[Processing] Fix the "difference" tool in Processing

### PR DESCRIPTION
**Pull request by Gustry**
The first PR https://github.com/qgis/QGIS/pull/2192 was related to only one file in Processing about the "difference" tool.
This PR will fix in every Processing algorithm which uses difference.

It seems that the new geometry class doesn't raise an exception if the geometry is null.
However, the "difference" algorithm was skipping the feature only if it caught an exception.

If it's merged into master, is-it possible to cherry pick to 2.10 before the release ?

CC : @volaya @alexbruy

### CODE REVIEW

**Comment by timlinux** [comment]
Just for the record we also discussed an alternative option which is to raise an exception if the returned geometry is null (thus keeping the behaviour the same as in QGIS >2.10). But IMHO it is bad to raise an exception when the API user can rather check for null geometry returned.

**Comment by Gustry** [comment]
@mhugent Can you confirm that no exception is raised if the geometry is null after a difference in the new class ? A lot of tools were waiting for an exception to check if the geometry was null with the old geometry class.
If yes, @volaya @gioman, can you check this PR before 2.10.1 ?
Thanks

**Comment by volaya** [comment]
Looks good to me. If @mhugent confirms that behaviour, this can be merged.

**Comment by alexbruy** [comment]
@mhugent can you comment on this?

**Comment by alexbruy** [comment]
I think instead of raising exception it is better to check if geometry is empty/invalid and proceed accordingly.

**Comment by alexbruy** [comment]
Fixed in master using slightly different approach.

**Pull request closed without merging**
