### PR TITLE
Pseudocolor raster shader implemented.

### PR DESCRIPTION
**Pull request by gshegunov**
Pseudocolor raster shader implemented.

### CODE REVIEW

**Comment by m-kuhn** [comment]
@gshegunov it would be great if you could run `.scripts/prepare-commit.sh` before committing. There's a lot of noise because of non-standard formatting in this file. It will make it easier to review.
Also, it would be great if you could write a test or two that demonstrate what your changes do, how they work and check if they work correctly.

**Comment by gshegunov** [comment]
I had no idea so far about  the script prepare-commit.sh. OK, I will use
it. If you check the modifications I had made, you will see that there are
minor changes in the code. My idea was do not reformat the original sources
and to make as less as possible modifications of the code.  It seems that
this code had been neglected. The interfaces were old ones and there were
no implantations of them.

However, how to resolve the problem? To close this pull request, to merge
the current repository with the original one and to apply a new commit with
the reformatted sources for pseudocolor shader? I will prepare a test
program to show that the shader works but where shall I upload this program?

**Comment by m-kuhn** [comment]
The easiest thing will be:

    git checkout pseudocolor_shader
    git reset --mixed HEAD^
    ./scripts/prepare-commit.sh
    git add .
    git commit
    git push -f

**Comment by m-kuhn** [comment]
Please also make sure you fix the compiler errors and warnings before committing / pushing.

**Comment by gshegunov** [comment]
Yes, PseudoColorShader is like a subset of ColorRampShader. If we use
ColorRampShader with 2 colors: red and blue and linear interpolation we
will receive the same result as with PseudoColorShader. I agree that the
main question is: Shall exists PseudoColorShader in the repository?

Currently the situation is the following: there is some part of code for
PseudoColorShader, but with bad/old interfaces and with empty
implementations. In any case we have to resolve this problem.

   1. If we are going to remove PseudoColorShader from the repository it
   will effect not only over library but over the application and ui. (For
   example in the application is dialog with property for pseudocolorshader.)
   2. If we keep PseudoColorShader, the modification that I had made has to
   be reformatted and applied,

For me is easy to modify my application that uses PseudoColorShader to
ColorRampShader with 2 colors. If you are going to remove PseudoColorShader
from the repository, few changes have to be done in the library, app and
ui. In this case I think that is good time to move MapTools that are in the
application to the library. I am waiting for your suggestion.

**Comment by gshegunov** [comment]
I have closed the pull request, but I am waiting for comment:

Shall I open a new one with reformatted pseudocolor shader or to remove it
from the repository, using only color ramp shader in the future?

**Pull request closed without merging**
