### PR TITLE
Fix some issues with WFS connection dialog

### PR DESCRIPTION
**Pull request by dakcarto**
## Description
Fix WFS connection version-related GUI widget enabling/disabling:
- When saved with feature paging disabled, caused option to never be reenabled
- When loading settings, feature paging now constrained to WFS version
- WFS 2.0.0 capabilities are no longer constrained to just that version,
  allowing versions above as well.

Fix WFS connection's version Detect button, which did not support auth:
- Adds support for auth system to Detect button
- Adds QgsNewHttpConnection protected member to access auth settings

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rouault** [comment]
The restriction of paging to WFS 2.0 could prevent from using paging with older MapServer versions that had a paging extension for WFS 1.1, at the time MapServer didn't support yet WFS 2.0. That said, time has passed, and we might decide to drop that support. In which case, there is a bit of cleanup to do, like removing this branch of code : https://github.com/qgis/QGIS/blob/3bd5a49424ec8a7aad9f8a2fd3e6d1583f085631/src/providers/wfs/qgswfsfeatureiterator.cpp#L265

**Comment by dakcarto** [comment]
@rouault wrote:
> The restriction of paging to WFS 2.0 could prevent from using paging with older MapServer versions that had a paging extension for WFS 1.1, at the time MapServer didn't support yet WFS 2.0. ...

I see. Though, not sure how this relates to the changes I've made. The WFS version == 2.0.0 restriction was already applied in `wfsVersionCurrentIndexChanged` slot. I just reiterated it in `updateServiceSpecificSettings`, where the bug (paging never able to be re-enabled) was presenting, and ensured it wasn't constrained to just the 2.0.0 version (I'm assuming here that feature paging will not _go away_ in newer WFS versions).

If we wanted to keep that WFS 1.1 version feature paging support, then we might want to do:
```
(index|versionIdx) >= 2
```
Previously, if I understand your MapServer comment correctly, a user could put in the feature paging support at version 1.1. But, I think any change to the version selector would have disabled that widget.

**Comment by rouault** [comment]
>  then we might want to do:
> 
> ```
> (index|versionIdx) >= 2
> ```

that might be good then

**Comment by dakcarto** [comment]
@rouault, updated and pushed.

**Review by rouault — APPROVED** [review]

**Comment by dakcarto** [comment]
@rouault, thanks for taking the time to review!

**Pull request merged**
