### PR TITLE
New icons

### LINKED ISSUE #41040: 3.18 icon updates
Some newly introduced icons need rework prior to release:

- ~~Point cloud layer icon: wrong style compared with other layer types (color vs monochrome). Also needs a variant in the data source manager monochrome+dark blueish style for use in data source manager~~
- ~~Point cloud layer elevation properties: Reuse of poorly matching existing icon~~
- ~~SAP/hana provider icons: need reworking to ideally remove the text strings, which are unreadable at certain sizes and bad for localisation~~
- need dedicated icons for fly/terrain 3d navigation modes
- point cloud "extent only" renderer needs an icon
- point cloud 3d "single color" renderer needs an icon
- merged features renderer: needs a proper icon instead of using the inverted polygon icon

### PR DESCRIPTION
**Pull request by SrNetoChan**
## Description

New icons to fix #41040 

Merge features vector renderer:

Selection_346

Point cloud 3D single color style

Selection_345

Point cloud extent only renderer

Selection_344

### CODE REVIEW

**Comment by nyalldawson** [comment]
I love the merged features icon -- that's a perfect illustration!

**Comment by nirvn** [comment]
I love the merged features one, looks outstanding alongside the other icons there.

For extent-only renderer icon, I'd prefer if the icon was the dotted outline only with the rectangles in it removed. Easy :)

For the single color icon, there's not much we can do there, so the icon is fine. However, I'd have the darker green outline be 1px in width, that'll better match with what we have elsewhere.

**Comment by SrNetoChan** [comment]
@nirvn said:
> For extent-only renderer icon, I'd prefer if the icon was the dotted outline only with the rectangles in it removed. Easy :)

Maybe with the double of the width? Or 2 pixel long dashes? Otherwise it may be too thin and not visible.

> For the single color icon, there's not much we can do there, so the icon is fine. However, I'd have the darker green outline be 1px in width, that'll better match with what we have elsewhere.

Uhmm... I thought it was... I will check.

Thanks for the feedback.

**Comment by nirvn** [comment]
@SrNetoChan , look at the icon for no symbol (null) renderer. I'm pretty sure it's 1 pixel width there. Use the same width :)

**Comment by SrNetoChan** [comment]
Yes, yes, you are right. I thought I had it with 1 pixel wide, but I can confirm that it isn't. Besides it makes no sense to have a 1.1 width line when it will not be rendered properly in such a small icon. You taught me that in the past 😉

**Comment by roya0045** [comment]
Nice work!

**Comment by SrNetoChan** [comment]
New icon for extent only

Selection_347

**Comment by nyalldawson** [comment]
@nirvn are we ok to merge?

**Comment by nirvn** [comment]
Yep

**Review by nirvn — APPROVED** [review]

**Pull request merged**
