### PR TITLE
[server] parallel map rendering (bis)

### PR DESCRIPTION
**Pull request by mhugo**
Last PR about @pblottiere 's parallel rendering in server, just to trigger Travis.

### CODE REVIEW

**Comment by rldhont** [comment]
Is it the same as #3886 and replace it ?

**Comment by rldhont** [comment]
@dmarteau any review ?

**Comment by mhugo** [comment]
Yes it replaces #3886 which was already reviewed

**Comment by m-kuhn** [comment]
Exciting times!

👍  @pblottiere @mhugo 👍

**Pull request merged**
