### PR TITLE
Configure searchable flag for field in vector layer properties

### PR DESCRIPTION
**Pull request by 3nids**
image

### CODE REVIEW

**Comment by nyalldawson** [comment]
Instead of the growing list of columns here, could we try to use the checkable combo box widget instead and move the server related flags in there too? (Or push them away to a server tab, where they actually belong!)

**Comment by 3nids** [comment]
> Instead of the growing list of columns here, could we try to use the checkable combo box widget instead and move the server related flags in there too? (Or push them away to a server tab, where they actually belong!)

Good point, I'll do that.

**Comment by 3nids** [comment]
manually merged with 59ff51697663c41a79d34cfa2989f3aa00c57ac6 4544c9614fa54548373fd6b3212642e370df9b2c 14ef69f8a5b3fceaf415ab4e9e9ef6389fae3631

**Comment by 3nids** [comment]
I will do the UI work in a following PR

**Pull request closed without merging**
