### PR TITLE
Layer dependencies

### PR DESCRIPTION
**Pull request by mhugo**
Allow to declare dependencies between layers.
Main usage: allow to properly save and load back a project with virtual layers that have references to live layers. Virtual layers must be loaded after all their dependencies.

### CODE REVIEW

**Comment by SebDieBln** [comment]
:+1: for making dependencies explicit

We have a similar situation with __vector joins__, but the current solution there is to load all layers and only then create the joins, ignoring joins to missing layers.

I think virtual layers and vector joins should use the same approach. And I think it should be the explicit dependencies.

An interesting use for the explicit dependencies would be to warn the user, when _exporting to a QLR_ or _embedding from a project_ and not all dependencies are exported/embedded.

Be advised that `QgsProject::_getMapLayers()` is not the only place where layers are loaded. Layers from QLRs are loaded within `QgsLayerDefinition`. See #2617 fixing a bug that was introduced by only modifying `QgsProject` and not `QgsLayerDefinition`.

**Comment by mhugo** [comment]
Yes, you are right for the vector joins. Actually in _getMapLayers, code should ideally be simplified a bit to include vector joins in the dependency graph and avoid specific code for vector joins. I'll see if I have time to improve that part.

Thanks for mentioning the layer definition part. I forgot they can carry more than one layer and then have to resolve dependencies as well. I'll have a look

**Comment by m-kuhn** [comment]
It's actually the same for relations which also have dependencies and their way of triggering initialization code only after all layers have been loaded.

**Comment by mhugo** [comment]
@m-kuhn Yes, exact. And QLR support for relations would be nice.

**Comment by m-kuhn** [comment]
QLR support for relations is a tricky topic to get right. There may be QLRs for the other layers involved, multiple QLRs may reference the same datasource (but the same datasource may be loaded in multiple layers). I think this would be best solved on a higher level (project scope).

**Comment by mhugo** [comment]
@SebDieBln Do you know why IDs of layers in a definition file have to be changed on loading ?

**Comment by mhugo** [comment]
Ok, I guess this is to prevent two different layers from having the same ID

**Comment by NathanW2** [comment]
Yeah that is the reason. Or else you can't load the qlr more then once.
This is by design so you might have to find another way around this

**Comment by SebDieBln** [comment]
I guess so, too. E.g. when embedding layers, they currently retain their IDs from the original project, which can lead to duplicate IDs resulting in bugs, e.g. [Redmine #13913](http://hub.qgis.org/issues/13913) I think.

**Comment by SebDieBln** [comment]
@NathanW2
> Or else you can't load the qlr more then once.

Is that intended behaviour? You could load the qlr once and duplicate the contained layers...

**Comment by NathanW2** [comment]
Yes it's intended.  QLRs can have many layers and also groups. i guess you
could duplicate but the workflow is not nice.

**Comment by mhugo** [comment]
@NathanW2 @SebDieBln thanks for your answers.
Now dependencies should be resolved for layer definitions and for embedded layers

**Pull request merged**
