### PR TITLE
[cmake] Prefer pkgconfig for spatialite

### PR DESCRIPTION
**Pull request by m-kuhn**
and use a proper cmake target

hint: hide whitespace to review https://github.com/qgis/QGIS/pull/54626/files?diff=split&w=1

### CODE REVIEW

**Review by rouault — APPROVED** [review]

**Comment by jef-n** [comment]
Can you combine all of these?  I don't want to wait for all the PR to be merged before I can fix the nightlies ;)    SpatiaLite is already broken by this (no pkgconfig on windows/osgeo4w; so REQUIRED is bad).  That might be already fixed - or maybe not - removing SPATIALITE_LIBRARY / SPATIALITE_INCLUDE_DIR probably needs a clean rebuild to break - doing that now.  But any of these might break it again.

**Comment by m-kuhn** [comment]
Oh, missing PkgConfig is unexpected, `REQUIRED` can be removed.
I'm trying to keep fallback code for everything, but there's an inherent risk.
I'll add one more now for proj (and hope that I don't run into more linker problems in my ongoing build adventures ...)

**Comment by jef-n** [comment]
> Oh, missing PkgConfig is unexpected, `REQUIRED` can be removed. I'm trying to keep fallback code for everything, but there's an inherent risk. I'll add one more now for proj (and hope that I don't run into more linker problems in my ongoing build adventures ...)

PkgConfig isn't missing, but pkg-config.

**Comment by m-kuhn** [comment]
> > Oh, missing PkgConfig is unexpected, `REQUIRED` can be removed. I'm trying to keep fallback code for everything, but there's an inherent risk. I'll add one more now for proj (and hope that I don't run into more linker problems in my ongoing build adventures ...)
> 
> PkgConfig isn't missing, but pkg-config.

Is this affected by `REQUIRED` then? Only `PkgConfig` is required, which in turn can succeed to find spatialite (in which case this config will be used) or fail to find it, in which case we fallback to the behavior from before.

**Comment by jef-n** [comment]
just removing REQUIRED worked for me.

**Pull request merged**
