### PR TITLE
Sld read multiple featuretypestyles

### PR DESCRIPTION
**Pull request by m-kuhn**
Introduce a virtual FeatureTypeStyle to add support for reading SLD documents with more than one FeatureTypeStyle element.

Still supports SLD's with one FeatureTypeStyle, as well as SLD's with multiple FeatureTypeStyles, including empty FeatureTypeStyles (not breaking single symbol rendering in that case). Complies with SLD's painter's model for rendering, appending Rules from subsequent FeatureTypeStyles in order.

Should fix http://hub.qgis.org/issues/6413

### CODE REVIEW

**Comment by aaime** [comment]
Hi, just a quick note, the specificatio is not very clear on this, but at least on GeoTools based systems the FeatureTypeStyles, they are rendered in increasing z order, so whatever is painted by the second FTS is above everything in the first FTS, and so on. I believe this is the common approach at least.

**Comment by aaime** [comment]
Hi @m-kuhn, I believe it's better than before, just not totally correct yet. More improvements can be done later.

**Comment by m-kuhn** [comment]
Cool, in this case I'll leave it to whoever runs into this or feels like making things follow the standard :+1: 
Thanks @aaime

**Comment by jgrocha** [comment]
@m-kuhn @aaime I've tested the rendering order (with just two different `<FeatureTypeStyle>`) and the rendering order is preserved.

**Comment by m-kuhn** [comment]
@jgrocha thanks for the feedback, good to hear. would you be able to create a unit test for this?

**Pull request merged**
