### PR TITLE
[processing] Fixed UI bug with invalid button width.

### PR DESCRIPTION
**Pull request by sept-en**
Hello!

I just found small uI glitch with button (the width is too small to display text correctly).
Some screens (before and after attached).

Best regards,
Kirill Abramov.

qgis_modeler_bug
qgis_modeler_bug_fix

### CODE REVIEW

**Comment by NathanW2** [comment]
What does it look like if you remove the max size?  This will still
overflow with different font sizes.

**Comment by sept-en** [comment]
@NathanW2 if we remove the max size, then the button will fill have the same width, as the parent component. It would be better for the big window size, but looks not so good if we reduce window's width.
So that's why I leaved setMaximumWidth() there, but just increased max width available for this.

Best regards,
Kirill Abramov.

**Comment by alexbruy** [comment]
IMHO we shouldn't limit size of UI elements as this breaks layout and it still won't work with some themes/font setting. Better to drop maximum size limit and add spacer right to the button.

**Comment by sept-en** [comment]
@alexbruy okay, I fixed it according your advices.

**Pull request merged**
