### PR TITLE
Fix gdal_rasterize to accept -init with value of 0

### PR DESCRIPTION
**Pull request by suricactus**
## Description
Currently, the Rasterize (vector to raster) plugin was not accepting 0 (zero) as value for the `-init` argument of `gdal_rasterize`, because of mistaken if clause. This fix also needed to a changed default value in the dialogue for 'Pre-initialize the output image with value' parameter from 0 to None, to preserve the current behaviour and not introduce breaking change. No document

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Nice fix! Can you add a unit test covering this to https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/GdalAlgorithmsTest.py#L1988 ?

**Comment by suricactus** [comment]
Thanks, my first PR in the GIS world :) Also thanks for pointing me where are the tests.

There is an ambiguous situation when both `-a_nodata 0 -init 0` are provided, as zeroes will be treated as `Null`s and the visual result in QGIS is kinda confusing. I can fix this situation by ignoring the `a_nodata 0` when `-init` is not `None`. With or without this fix, it's not an obvious situation and should be documented. Do you think it's a good idea to fix it this way?

**Comment by nyalldawson** [comment]
@suricactus 
> There is an ambiguous situation when both -a_nodata 0 -init 0 are provided, as zeroes will be treated as Nulls and the visual result in QGIS is kinda confusing. I can fix this situation by ignoring the a_nodata 0 when -init is not None. With or without this fix, it's not an obvious situation and should be documented. Do you think it's a good idea to fix it this way?

These aren't the default values though, are they? I think it's feasible that someone may have a valid use case for that combination of values, so I wouldn't want to block it. A documentation change would need to be made https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/user_manual/processing_algs/gdal/vectorconversion.rst#rasterize-vector-to-raster (or in the GDAL docs themselves?) 

In any case, I'm going to merge this for now (so that the fix can be included in 3.4.4) and we'll leave the documentation/handling of that combination for follow up work

**Comment by suricactus** [comment]
Unfortunately `-a_nodata` has a default value of 0 in QGIS rasterize. I would suggest removing the default in the next release (3.6) and the ambiguity as default behaviour will be resolved. I'll make another PR for that soon.

There are valid use cases to have them both 0 for sure.

**Comment by suricactus** [comment]
Yes, for `-init` the default to non set. There is no problem for now.

The problem gets when you set `-init` to 0 (what people may do most of the time), `-a_nodata` defaults also to 0 (something people may oversee) and it takes time to realize what happened (especially for people not into GDAL). I wonder why `-a_nodata` defaults to 0 in the first place, as 0 is usually completely valid value and `nodata` breaks a lot of raster calculations.

**Comment by nyalldawson** [comment]
@suricactus 

yeah, -9999 or similar sounds like a much more reasonable default to me.

We could handle this by logic like:

- if NODATA is not present in the parameters map, use the previous default value of 0
- if it's there, but explicitly set to None, skip the -a_nodata argument
- change the default value of the parameter to -9999

This means someone running the tool from the toolbox will get the reasonable -9999 value, but an existing script which DOESN'T set the no data values explicitly will keep the older 0 default value (just in case changing that would break other stuff in that script).

**Comment by suricactus** [comment]
Sounds reasonable, I'll do the first two bullets. 

However, I think the default value was set to 0 because it's a safe value for almost any type (Int2/4/8/16/24/32, UInt2/4/8/16/24/32, Float, etc). Setting it to -9999 will break a lot of things (UInts, 2 to 8 bit Ints, etc). I would suggest going for no default value. Just omitting the arguments will use the already used value in the input layer, which is the safest for me.

**Pull request merged**
