### PR TITLE
db manager SQL window enhancements

### PR DESCRIPTION
**Pull request by mhugo**
This changeset brings QSpatialite's query builder (inspired by Mapinfo) dialog to the db manager "SQL" window.
It also allows to load non-spatial layers or layers without unique id (provided the PR #1970 is merged).
The creation of a view from the SQL window is also added.

### CODE REVIEW

**Comment by pcav** [comment]
Nice, thanks!

**Comment by mhugo** [comment]
@brushtyler are you still the person in charge for this part ? Do you think you can review it ?

**Comment by brushtyler** [comment]
Sure, I'll look at it asap.

**Comment by mhugo** [comment]
@brushtyler do you think you could have a look before the feature freeze ? I don't think it is really problematic, but would prefer to have your feedback and that would be cool to have it for the 2.10

**Comment by mhugo** [comment]
I'll merge it, to have it before the freeze. I will be available for fix during the feature freeze if needed

**Comment by brushtyler** [comment]
Sorry @mhugo, I was w/o internet connection in the last week... BTW the fix look good.

**Pull request merged**
