### PR TITLE
Don't add unnecessary points on intersection when tracing

### LINKED ISSUE #52935: Unwanted vertices when tracing
### What is the bug or the crash?

When tracing whilst digitising, vertices will be added to the traced feature where intersections with other features occur, despite no vertex existing on the feature being traced.

This is not desirable, particularly in situations where the absense of a common vertex implies a lack of network connectivity.

If the tracing does not follow intersecting features, then additional vertices should not be added.

### Steps to reproduce the issue

[Polylines_TracingBug.zip](https://github.com/qgis/QGIS/files/11355417/Polylines_TracingBug.zip)

1. Load the project embedded in the attached zipped GPKG
2. The red and green polylines are on the same layer (Polylines) and intersect either at vertices or not.
3. Digitise a new polyline following the green line into the TraceTest layer using tracing mode:
image

The newly digitised polyline has vertices at locations where other lines intersect it, but where there isn't a vertex on the green line that was traced.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.5-Firenze | QGIS code revision | 50adba36f2
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.3
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
GroupStats | 2.2.7
processing_r | 3.1.1
valuetool | 3.0.15
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.28.5-Firenze
QGIS code revision
[50adba36f2](https://github.com/qgis/QGIS/commit/50adba36f2)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
GroupStats
2.2.7
processing_r
3.1.1
valuetool
3.0.15
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #59041: Extra vertices form to all layers when using tracing
### What is the bug or the crash?

When snapping, topological editing and tracing is enabled extra vertices are created for when there are intersecting features even without vertices. If there are multiple layers sharing the boundary, extra vertices are formed for each layer.

tracing_2

### Steps to reproduce the issue

1. Open [tracing.zip](https://github.com/user-attachments/files/17324872/tracing.zip) project (open from - geopackage)
2. Enable editing for all three layers
3. Make sure topological editing is enabled
4. Make sure snapping on segment and all layers is enabled
5. Make sure tracing is enabled
6. Digitize new feature for **line2** layer
7. Snap to the upper corner of a polygon

Topological point is created for each layer in the point where existing line crosses the polygon

### Versions

<details>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.39.0-Master
-- | --
QGIS code revision | 666983c678b
 
Libraries
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
This copy of QGIS writes debugging output.
 
Active Python plugins
plugin_reloader | 0.14
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99
grassprovider | 2.12.99

</body></html>QGIS version
3.39.0-Master
QGIS code revision
[666983c678b](https://github.com/qgis/QGIS/commit/666983c678b)
 
Libraries
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.3 LTS
This copy of QGIS writes debugging output.
 
Active Python plugins
plugin_reloader
0.14
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
grassprovider
2.12.99

</details>

Also tested with 3.38.3.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This is related to https://github.com/qgis/QGIS/issues/52935, but since the topological point problem might have been introduced in https://github.com/qgis/QGIS/pull/57723, I created a new issue.

### PR DESCRIPTION
**Pull request by uclaros**
## Description
This fixes a longstanding issue with tracing, where points were being added where layers were intersecting.
This behavior only made sense on a graph theory context but not on a user digitizing context.

With this PR those intersection points are skipped by default. Anyone using the `QgsTracer` class can still enable the previous behavior by using `QgsTracer::setAddPointsOnIntersectionsEnabled( bool )`

Fixes: #52935
Fixes: #59041

### CODE REVIEW

**Review by troopa81 — COMMENTED** [review]
Code looks good! :+1: 

Just a question: Do we really want an API call to keep the old (reported as error) behavior? And if yes, shall we not have a widget to be able to configure it?

My guts feeling here is that nobody wants the intersection vertex (but I'm no digitizing expert), no?

**Comment by uclaros** [comment]
> My guts feeling here is that nobody wants the intersection vertex (but I'm no digitizing expert), no?

I believe so too. That's why I opted to not have that configurable in the gui. However, QgsTracer may be used as a general purpose graph solver in cases where the extra vertex does not really matter and it might not be worth the extra processing to have them removed, that's why I left it in the API.

**Comment by aharfoot** [comment]
> Just a question: Do we really want an API call to keep the old (reported as error) behavior? And if yes, shall we not have a widget to be able to configure it?

There is a certain logic (and simplicity) to honouring the 'Snap to Intersections' toggle as a mechanism to switch between the old and new behaviour.

Thank you very much for implementing the change.

**Comment by uclaros** [comment]
> There is a certain logic (and simplicity) to honouring the 'Snap to Intersections' toggle as a mechanism to switch between the old and new behaviour.

I have considered this, but rejected the idea eventually. These are two distinct functionalities, as one may want to start/end his trace on intersections. In this case he would need to constantly toggle the _Snap to intersections_ button to avoid having the extra points generated, which is arguably what pretty much everyone wants.
Do you think there are valid use cases where the old behavior would be needed and explicitly clicking on the intersections would not make it?

**Comment by aharfoot** [comment]
I think it's likely that any tracing that requires a start or end on an intersection without a vertex would accept the original behaviour at intermediate intersections and vice versa, and so your scenario of repeated toggling of _Snap to Intersections_ feels unlikely, however I'm not aware of specific use cases either way so can't back that up, sorry.

**Comment by agiudiceandrea** [comment]
Hi @uclaros, I've noticed various recent crash reports about trace digitizing running QGIS 3.40 and 3.42: https://github.com/qgis/QGIS/issues?q=is%3Aissue+QgsTracer%3A%3AinitGraph+created%3A%3E2024-10-24

**Pull request merged**
