### PR TITLE
[processing] improve in-place feature editing icon & toolbar position

### PR DESCRIPTION
**Pull request by nirvn**
## Description
@nyalldawson , @elpaso , a bit of UI polishing:
image

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
Sure I'll replace the gear with a pencil.

**Comment by DelazJ** [comment]
I wonder if it's not the yellow square that should be questioned.

**Comment by elpaso** [comment]
@DelazJ I think that the yellow square reminds of a selection (which is normally yellow), perhaps dotted stroke would be even clearer.

**Comment by DelazJ** [comment]
Maybe I misunderstand you @elpaso but I meant the yellow was too tied to the selection idea and as far as I know, this button is not only for selected features so we should maybe avoid that yellow square. (Sorry to not come with a better idea)
Btw, I'm unable to get the current pencil icon enabled (stays gray whatever alg I select, on Windows with cdd72e51)

**Comment by elpaso** [comment]
@DelazJ the in-place editing function is currently enabled only if there is a set of selected features (and the layer is editable)

**Comment by nirvn** [comment]
@DelazJ , the crucial part *is* the section reference, it's a requirement for feature to enable itself.

**Comment by DelazJ** [comment]
😕 Sorry. I should have read the "docs" better...

**Comment by nirvn** [comment]
Updated:
image

**Comment by nyalldawson** [comment]
Looks great to me!

**Pull request merged**
