### PR TITLE
When building on proj >= 6.2, show the full scope and remarks for coordinate operations

### PR DESCRIPTION
**Pull request by nyalldawson**
Gives much more useful information to users to allow them to make informed choices about suitable operations.

Depends on https://github.com/OSGeo/PROJ/pull/1537

### CODE REVIEW

**Comment by nyalldawson** [comment]
ping @rduivenvoorde 

Here's what you see now:

image


image


image

**Comment by rduivenvoorde** [comment]
THANKS @rouault @nyalldawson !! Nice work!

@nyalldawson I've seen this dialog popup now on a couple of incidents, and I think the average QGIS user is not aware of these details, and will have troubles deciding which Datum Transformation to choose. AND what all these 'words' mean...

What about adding Help button in that dialog pointing to:
https://docs.qgis.org/testing/en/docs/user_manual/working_with_projections/working_with_projections.html ?

Even better: if we add a chapter there which explains defines the differences between crs, projection, transformation, datum etc etc. Anybody a good primer for that? Personally I found the Esri page https://pro.arcgis.com/en/pro-app/help/mapping/properties/coordinate-systems-and-projections.htm a nice intro, though I do not know if we use the exact same definitions..

Still wonder if we should not remove the (1) (2), as I understand correct these will not respond to the order proj decides which is best... But grepping for it is maybe much...

**Comment by kbevers** [comment]
> Anybody a good primer for that?

Chapter 4 of the [EPSG Guidance Note 7-1](http://www.epsg.org/Portals/0/373-07-1.pdf) is a good source of information. It uses the same definitions as PROJ (well, ISO19111 really).

**Comment by nirvn** [comment]
@nyalldawson , a couple of UI/UX suggestions:
- might be worth transforming the label into a textbox to avoid long vertical dialogs when scope + remarks + proj strings are reflowing on too many lines.
- I'd suggest using gray (i.e. disabled palette) font color for at least the proj string, and possibly the remarks too, to balance the focus a bit to more important strings.
- Could you move the "[ x ] make default" checkbox to sit next to the [ OK ] button, it'd make it stand out a bit more as ATM it's kind of lost.

**Comment by nyalldawson** [comment]
@nirvn I've already tweaked this a bit since the screenshot. Specifically:
- i use a text browser now, so the text is selectable (i think that also adds scrollbars?)
- proj codes are rendered using <code> tags

**Comment by nirvn** [comment]
@nyalldawson , sounds good.

**Comment by nyalldawson** [comment]
@rduivenvoorde 
> What about adding Help button in that dialog pointing to:
https://docs.qgis.org/testing/en/docs/user_manual/working_with_projections/working_with_projections.html ?

Done

> Still wonder if we should not remove the (1) (2), as I understand correct these will not respond to the order proj decides which is best... But grepping for it is too much...

I think we should leave these -- they are the only unique identifiers for the entries, and if we removed them it would prevent people making in-house instructional docs like "always select .... (2)"....

**Comment by nyalldawson** [comment]
@nirvn 

> I'd suggest using gray (i.e. disabled palette) font color for at least the proj string, and possibly the remarks too, to balance the focus a bit to more important strings.

Done

>Could you move the "[ x ] make default" checkbox to sit next to the [ OK ] button, it'd make it stand out a bit more as ATM it's kind of lost.

Done

**Comment by rduivenvoorde** [comment]
Screenshot-20190703095907-712x566

Cool! Thanks for the Help button. The first option now even shows 'Preferred transformation', 
making it a lot easier to choose!
(@nirvn making it green or red is too much?). I keep nagging about this because I think a lot of users will have no clue when they see this kind of dialogs :-)

**Comment by nirvn** [comment]
I'd add the preferred transformation flag as an icon into the list view of all available transformation, and reuse that icon next to the preferred transformation text.

**Comment by rduivenvoorde** [comment]
@nirvn talking about (re)using icons: what do you think about using the CRS icon/button we have in the toolbar to use on all dialogs we have for online services (WMS/WFS/WCS/ArcGIS *Server etc)?
(I'm talking about the red circled button in the screenshot below).
The good thing about it is also that it shows BOTH the EPSG code and the crs Name (in the tooltip though). 
IF people agree, I wonder if we can make it a button which shows both code and name.
OR should it stay a 'Change' button? Instead of the 'Change...' button + crs name.
/me thinking about to make the ui a litte more consistent. 
Also because in courses I use the epsg code, while in eg the wms dialog you students see the crs name there (and both Google Mercator and latlon have WGS84 in the name... giving name issues with them).
I also wonder if Tile size and Request step size are actually dependent on the CRS (as it is in that group box)...

Screenshot-20190703104213-866x699

**Comment by nyalldawson** [comment]
@rduivenvoorde 

Looks like you've flipped back to a proj < 6 build in your screenshot. You'd need to build proj master in order to see the newly added remarks and scope. What you're seeing instead is the information from QGIS' old datum transform database (i.e. - interpret with extreme caution!).

An easy well to tell if you're using the shiny new stuff or the old dubious stuff is via the columns in this dialog. If you see two columns labeled "source transform" and "destination transform" - you're on the crufty old code path. If you see "transformation" and "accuracy" then you're on the new trustworthy path.

**Pull request merged**
