### PR TITLE
[FEATURE][3D][MESH] arrows for 3D mesh layer dataset rendering

### PR DESCRIPTION
**Pull request by vcloarec**
This PR adds the possibility to display arrows on mesh layer dataset 3D entity, depending on vector dataset.
The dataset used to render arrows is the one chosen for rendering vectors on 2D rendering.
In the same way, the color of arrows are defined in the 2D rendering settings for vector dataset.
In 3D settings, the user can define the spacing of arrows and if size is fixed or scaled on magnitude. 
This spacing setting defines also the max size of arrows because arrows can't overlap.
arrows_fixed_size
arrows_scaled_size

### CODE REVIEW

**Comment by PeterPetrik** [comment]
already pre-reviewed in https://github.com/vcloarec/QGIS/pull/7

**Review by PeterPetrik — APPROVED** [review]

**Comment by wonder-sk** [comment]
Looks good to me too!

(if interested - the arrow rendering technique has been prototyped here: https://github.com/wonder-sk/qt3d-experiments )

**Comment by nyalldawson** [comment]
Any chance of a test here? I realise the 3d rendering tests are tricky, but it makes me nervous seeing such as large feature with absolutely zero test coverage...

**Comment by vcloarec** [comment]
@nyalldawson, tests are done on rendering. Do you talk about more "core" test ?

**Comment by nyalldawson** [comment]
@vcloarec sorry, I missed that somehow!

**Pull request merged**
