### PR TITLE
[locator] Allow searching for short identifiers

### LINKED ISSUE #35418: Search for short feature identifiers in the locator bar
Currently, the locator feature filter only shows results once 3 or more characters have been typed.
This makes it impossible to find ids like 1, 20, 45, ab, etc.
By using a prefix, these are included but can be hidden because of the maximum result count of 6. (ie. 100, 1000, 2100, 111, 110, 3310 shown instead of 1).

Ideas:
 - order by relevance (ideally provider side for performance reasons)
 - for < 3 characters search for exact match only
 - introduce double quotes for exact match search `"1"` (not that intuitive)

### PR DESCRIPTION
**Pull request by m-kuhn**
When searching for 1 or 2 character strings, execute an exact match search.
This allows to search for very short identifiers which are otherwise hard to impossible to find.

This also adds forcing exact match search by quoting the search string.

Fix #35418

# Documentation

To search for very short identifiers and values with the "all features" or "active layer features" locator filters it is required to use the prefix (`f`, `af`) by default. When used with a prefix, these filters will perform an exact match search for 1 or 2 characters. For example `af 1` will find a layer with display string `1` on any layer, but it will not find `100`. `af 100` will find `100` and `1000`.

Searching for quoted strings will also perform an exact match search. E.g. `"Wil"` will find `Wil` but not `Wattenwil`.

Peek 2020-03-28 07-39

### CODE REVIEW

**Comment by 3nids** [comment]
Nice! It would be nice to add the quotes for exact match too. It would be quite handy

**Comment by m-kuhn** [comment]
On it already ;)

**Review by 3nids — APPROVED** [review]
Nice.
It would have been even nicer with some regex though 😉

**Comment by m-kuhn** [comment]
> It would have been even nicer with some regex though wink

Apart from reduced performance, what's the advantage ;)

**Comment by 3nids** [comment]
Code gets harder to read!

**Comment by roya0045** [comment]
@3nids what about #35083 ?

**Comment by uclaros** [comment]
So how are we going to search for features containing one or two character strings?
The problem of searching exactly for one or two character strings gets solved with the quoted for exact match mode. Imho you are breaking functionality, or I didn't get this right!

**Comment by m-kuhn** [comment]
Old behavior: typing 1 or 2 characters with prefix would not do anything.
New behavior: typing 1 or 2 characters with prefix will search for an exact match.

Can you clarify on what's broken?

**Comment by uclaros** [comment]
Sure, maybe this makes it clearer.

locator

**Comment by m-kuhn** [comment]
Sorry, my comment was indeed wrong. Search happened on short identifiers too with prefix.
But the issue is shown in the below video:

Peek 2020-03-28 12-17

**Comment by uclaros** [comment]
NP, but what you describe can be solved with the double quotes

**Comment by m-kuhn** [comment]
Technically yes. But I assume that in practice the intuitiveness of this approach is better
(quoting will require documentation which no one reads. I can only estimate the percentage of people using quotes on google but the figures I imagine are a very small portion of all searches).

**Comment by m-kuhn** [comment]
> ~NP, but what you describe can be solved with the double quotes~
> whoops, rushed to answer!.. What you show here is that it fails to get all matches with the single "2" character, it only gets some ("12")

What happens is that it fails to order by relevance and trims the results to a max of 6.
There would be a better solution to support "order by relevance" but this needs to be done provider side for efficiency and that's out of scope for a Saturday morning quarantine fun project ;)

**Comment by uclaros** [comment]
I see, but it's not good enough reason to not show my single result matching a one or two character string!

**Comment by m-kuhn** [comment]
> I see, but it's not good enough reason to not show my single result matching a one or two character string!

It fixes a real world problem, I find this reason quite compelling ;)

**Comment by uclaros** [comment]
I don't agree with your logic here, sorry.
Nobody will be able to do one or two character string 'contains' searches (a real world problem) because you don't want to reach for the double quotes (not a real world problem tbh).

**Comment by m-kuhn** [comment]
So sorry I have to close this.

It was for a fun project for someone who works a lot with small municipalities where double quotes are not an option.

**Pull request closed without merging**
