### PR TITLE
Double-clicking a mouse handle for a layout label resizes to fit text

### PR DESCRIPTION
**Pull request by nyalldawson**
Double-clicking a handle will auto-size the label to exactly fit
the contained text (growing or shrinking as needed). The opposite
side of the label will remaining fixed in place, so eg double-click
the bottom-right handle causes the bottom-right corner of the label
to move.

### CODE REVIEW

**Comment by YoannQDQ** [comment]
That's great! Unfortunately `sizeForText` seems a bit unreliable. It does not always compute the right size...

**Review by nirvn — APPROVED** [review]

**Comment by YoannQDQ** [comment]
@nyalldawson Any label really. 

[test_label_resize.zip](https://github.com/user-attachments/files/17991289/test_label_resize.zip)

Here is an example project with a single layout that contains 4 labelItems:
- label1 : no html rendering, single line
- label2 : no html rendering, multiline
- label3 : html rendering, single line, no `<br/>`
- label4 : html rendering, single line, with `<br/>`
- label5 : html rendering, multiline, no `<br/>`
- label6 : html rendering, multiline, with `<br/>`

I called `adjustSizeToText()` on each of them. Here's the result:

image

**Comment by nyalldawson** [comment]
@YoannQDQ Ah, I think that'll be improved by the fix in this pr already

**Comment by nyalldawson** [comment]
@YoannQDQ also, good point regarding HTML mode, I hadn't considered that. I've now set it so that no auto-sizing happens if the label is in HTML mode

**Pull request merged**
