### PR TITLE
Fix non caching behaviour for WFS

### PR DESCRIPTION
**Pull request by tomtor**
See https://hub.qgis.org/issues/9444

The original non caching implementation was commented out as a temporary fix for some crash issue:

https://github.com/tomtor/QGIS/commit/945be40a866265dbfe47e7ca500b0369684a570c

I believe the cause for the original bug is some kind of race condition, so I moved the freeing of data and simplified the original implementation.

### CODE REVIEW

**Comment by m-kuhn** [comment]
@jef-n I guess you are familiar with this topic... 945be40a866265

**Comment by m-kuhn** [comment]
@raymondnijssen are you able to test this?

**Comment by tomtor** [comment]
@Raymondnijssen I tested with PDOK wfs layers. Bag pand works fine but there is an issue sometimes which eg ligplaats in that it does not retrieve features because the feature type is not recognized. I plan to fix that issue soon. All NGR RIVM services work fine but those have no download limit.

Note that you may leave the cache feature option enabled. That is a no op when you select the  "just visble" option when adding a layer.

**Comment by raymondnijssen** [comment]
@tomtor Thanks for fixing this, many people were missing this broken functionality. I tested locally on the BAG (pand and ligplaats) on GeoServer and they both worked.

@jef-n Works properly, please pull.

**Pull request merged**
