### PR TITLE
update MDAL 0.7.91

### PR DESCRIPTION
**Pull request by PeterPetrik**
MDAL beta release for QGIS 3.18

- fix xmdf for hydro_as_2d 
- support for dynamic/external drivers (in the folder specified by MDAL_DRIVER_PATH env. var)
- bugfixes

### CODE REVIEW

**Comment by roya0045** [comment]
@PeterPetrik was there a plan to add a precompiled version to osgeo? I find it annoying and sometimes problematic to compile MDAL or find a precompiled version and sometimes fail when I want to test QGIS without ever coming close to using anything related to MDAL. Making it an optional thing would be nice in such cases but since its engrained in the core I'm not sure how doable this is. Thanks!

**Comment by PeterPetrik** [comment]
> precompiled version to osgeo 

you mean osgeo4w?

yeah, it is somehow on the plan to remove it from QGIS external folder and use system libs, but so far its API was evolving quite quickly...

**Comment by nyalldawson** [comment]
I actually like this tight binding between qgis and mdal. As soon as we lose it we'll be fighting with the messy situation where users have access to different mdal versions for a single qgis release depending on platform, and that just makes everything so much more complex....

**Comment by roya0045** [comment]
> you mean osgeo4w?
> 
> yeah, it is somehow on the plan to remove it from QGIS external folder and use system libs, but so far its API was evolving quite quickly...

Yes osgeo4w, sorry for the confusion. I'm glad to hear such a thing is planned eventually!

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
