### PR TITLE
Port map layer selection combobox widget to c++ 

### PR DESCRIPTION
**Pull request by nyalldawson**
And:

- fix enable state of selected features only after changing between map layers with/without selections
- fix state of selected features only when running an algorithm from the history list, e.g. respect original setting for selected features only (or not)
- ensure no duplicate changed signals are sent, and correctly emit changed signals in all applicable circumstances
- handle drag and dropped layers from browser panel and file explorer (UX fix)
- soak with unit tests, including adding tests for QgsMapLayerComboBox and fixing a signal issue identified in it

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , travis being green, should we merge this? I'd like an additional developer's opinion on this, but for me I'd be +1 to merge for 3.8.

**Comment by nyalldawson** [comment]
@nirvn it started as a bug fix anyway, and in my view all the added unit tests here gives me much more confidence in the C++ version then the current implementation (C++ compile time stability benefits aside)

**Comment by nirvn** [comment]
@nyalldawson I agree.

**Comment by nyalldawson** [comment]
@nirvn have you reviewed the code?

**Comment by nirvn** [comment]
@nyalldawson , yep, did so yesterday, everything looked fine, and definitively feels better seeing yet another part of processing get solidified through C++ port.

**Comment by nyalldawson** [comment]
Thanks!

**Pull request merged**
