### PR TITLE
Fix oracle provider and tests

### PR DESCRIPTION
**Pull request by troopa81**
## Description

This PR makes oracle provider and its tests stable and reliable. This is still WIP because I would like the tests to be launched by the CI. 

Some details about commits:
- e1b05b4 : Connections can be shared by different threads when using a transaction, so we need to protect members from concurrent access
- f6f25a6 : We have to compute exact extent when the boolean mUseEstimatedMetadata isn't set, not an estimated one
- 7a2ef62 : That's the main reason for the tests being flaky. If we don't delete the connection when closing the transaction, the QOCISpatialDriver::close is not called, the connection is not well closed, and so following tests will possibly deadlock.

All tests are now stable and OK when running with oracle-18.4.0(c) Express Edition.

FYI @mhugo @Jean-Roc 

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [x] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by nyalldawson** [comment]
Thanks -- looks good! Did you see the earlier discussion about connections not being closed when providers are deleted? I think that's also a cause of issues in these tests...

**Comment by troopa81** [comment]
> Did you see the earlier discussion about connections not being closed when providers are deleted?

You mean [this](https://github.com/qgis/QGIS/issues/27087#issuecomment-541568701) ? 

I agree that the QgsOracleProvider should have a mConnRO and mConnRW member in order to not call connectDB everytime we want to acess to the current connexion (like in disconnectDB for instance). But still, it should work the way it is (because of the QgsOracleConn::sConnections map).

With these modifications all tests pass. I would rather setup the CI correctly before going any further.

**Comment by troopa81** [comment]
@jef-n I squashed all continuous integration together, is that OK for you?

**Comment by troopa81** [comment]
I think the commit d32b942 may have its own PR because error happened when I disable cache for docker images. What do you think?

**Comment by nyalldawson** [comment]
@troopa81 what's the status with this?

**Comment by troopa81** [comment]
@nyalldawson The PR is complete and need to be reviewed.

**Comment by troopa81** [comment]
Looks like one microsoft CI job is stuck in queued state, while an other one is green.

**Comment by roya0045** [comment]
> Looks like one microsoft CI job is stuck in queued state, while an other one is green.

That seems to be the case for many other PR.

**Comment by troopa81** [comment]
@nyalldawson Thanks!

**Pull request merged**
