### PR TITLE
[server][bugfix] Fix OGC test getcapabilities:validate-using-schemaLocation

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

This PR fixes the OGC test verifying *schemaLocation* on GetCapabilities which is currently failing : http://37.187.164.233/ogc/09_06_2017_00_53_32_wms_1_3_0.html#beef2c3d-93c3-4344-9d1d-1f09c8341920/d1e17334_1/d1e17409_1/d1e1362_1/d1e1436_1

Actually, once QGIS Server is installed on the filesystem, a .xsd file describing extended operations (like *GetPrint* or *GetStyles*) is deployed in the same directory than **qgis_mapserv.fcgi** : 

````
<PREFIX>/bin/qgis
<PREFIX>/bin/qgis_mapserv.fcgi
<PREFIX>/bin/schemaExtension.xsd
````

But the file is currently searched at the wrong place depending on how **qgis_mapserv.fcgi** is run. 

For example:

````
$ cd /home/user/opt
$ spawn-fcgi -f /home/user/opt/qgis/bin/qgis_mapserv.fcgi
````

In this case, the next file is searched on the filesystem : */home/user/opt/schemaExtension.xsd*.

But if the running directory is different:

````
$ cd /home/user
$ spawn-fcgi -f /home/user/opt/qgis/bin/qgis_mapserv.fcgi
````

Then the next file is searched : */home/user/schemaExtension.xsd*

If the server is managed by a *systemd* service, the next file is searched : */schemaExtension.xsd*

In all cases, the xsd file is never found and the OGC test is failing. Moreover, the *GetSchemaExtension* request returns an error too (it's actually the underlying request used to find the xsd file when the schemaLocation from *GetCapabilities* is checked).

This PR fixes this issue by always searching the *schemaExtension.xsd* file in the same directory than **qgis_mapserv.fcgi**. 

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rldhont** [comment]
do you think to add a test ?

**Comment by pblottiere** [comment]
@rldhont I wanted to but I didn't find a way to do it considering that **qgis_mapserv.fcgi** doesn't run during unit tests. So I cannot retrieve the underlying *schemaExtension.xsd*.

Unless you have an idea in mind? Because I do not like to commit something without some tests...

**Comment by rldhont** [comment]
Why not tested the request `GetSchemaExtension` like others ?

**Comment by pblottiere** [comment]
> Why not tested the request GetSchemaExtension like others ?

Because `GetSchemaExtention` searches the file *schemaExtension.xsd* on the filesystem according to the position of the process currently running. But in case of unit tests, it's not *qgis_mapserv.fcgi* which is running. So the file *schemaExtension.xsd* is not searched at the right place and we have an error. By the way, it's probably why there's no tests at all for this request...

**Comment by rldhont** [comment]
so you can merge it without test.

**Comment by pblottiere** [comment]
I'll merge this PR tomorrow if I've no more comments in the meantime.

**Comment by m-kuhn** [comment]
If the file is expected to be placed next to the binary (which I'm not actually sure is the correct approach, possibly it should be on some QStandardPath), it could also be put there in the build directory (where the tests are run) using [configure_file](https://cmake.org/cmake/help/latest/command/configure_file.html)

**Comment by pblottiere** [comment]
>  If the file is expected to be placed next to the binary which (I'm not actually sure is the correct approach, possibly it should be on one of the QStandardPaths)

Good point! What do you think about installing the .xsd file in `<PREFIX>/share/qgis/resources/server/`?

And unit tests would be easily possible because we won't depend on the path of the process currently running anymore...

**Comment by m-kuhn** [comment]
Is that `AppDataLocation` http://doc.qt.io/qt-5/qstandardpaths.html?

**Comment by pblottiere** [comment]
I'm not sure that `AppDataLocation` is relative to the installation prefix...

But if we have `<PREFIX>/share/qgis/resources/server/schemaExtension.xsd`, then we're able to retrieve it in the same way as *customization.xml*, *srs.db*, ... files :

``
QFile myFile( QgsApplication::pkgDataPath() +  "/resources/server/schemExtension.xsd" );
``

We could even add a new path to QgsApplication to directly get `QgsApplication::pkgDataPath() +  "/resources/server/` like `QgsApplication::defaultThemesFolder()`.

What do you think?

**Comment by m-kuhn** [comment]
> I'm not sure that AppDataLocation is relative to the installation prefix...

Probably not, right.
The proper way would probably be to introduce a `QgsStandardPaths` class that also handles install prefixes but with all the nice goodies from `QStandardPaths`.

One of the big advantages of `QgsStandardPaths` is that it separates between vendor deployed files, sysadmin deployed files and user deployed files and makes it very easy for all these parties to introduce their configuration without overwriting configurations of the others.

I guess the `schemaExtension.xsd` file doesn't need to be changed ever, so I don't think I can ask you to do implement this here, feel free to do it the legacy way ;)

**Comment by rldhont** [comment]
@pblottiere will you add test ?

**Comment by pblottiere** [comment]
@rldhont As Matthias suggested, I firstly have to modify the installation path for `schemaExtension.xsd` (in share directory). Then I'll add some tests.

**Comment by pblottiere** [comment]
@m-kuhn I used the legacy way to retrieve the `schemaExtension.xsd` path from share directory. Any objections on how it's done?

**Comment by pblottiere** [comment]
@rldhont Now that `schemaExtension.xsd` is installed in share directory, I think that it should be the same thing for `admin.sld` and `wms_metadata.xml` files. It's not the place to do it in this PR, but what do you think about it?

**Review by m-kuhn — APPROVED** [review]
Nice

**Comment by rldhont** [comment]
@pblottiere the `admin.sld` and `wms_metadata.xml` files could probably be removed. Now that QGIS Server used  a QgsProject, they are probably no longer used.

**Comment by pblottiere** [comment]
>  they are probably no longer used

The `probably` worries me :)

**Comment by rldhont** [comment]
@pblottiere `rgrep` the QGIS Server code.
Some other options as to be cleaned too.

**Comment by pblottiere** [comment]
@rldhont OK I'll take a look to remove these files in another PR. 

Otherwise, do you approve this PR? Or do you want me to modify something?

**Review by rldhont — APPROVED** [review]
Go to merge

**Comment by pblottiere** [comment]
Corresponding OGC test is fixed now : http://37.187.164.233/ogc/10_10_2017_10_47_59_wms_1_3_0.html#33273edd-8d5f-447c-bf2c-e216cdc01862/d1e17334_1/d1e17409_1/d1e1362_1/d1e1436_1

**Pull request merged**
