### PR TITLE
Only filter legend nodes that are checked

### PR DESCRIPTION
**Pull request by mhugo**
See http://hub.qgis.org/issues/13959

For the "filter legend by map content" or "by expression", this allows to keep legend nodes that are unchecked in the legend, whatever the filter is.
@nyalldawson do you think it is better ?

### CODE REVIEW

**Comment by nyalldawson** [comment]
@mhugo I think the unchecked nodes should still be removed if "filter by map content" is enabled (given that they aren't shown on the map), so they should only be kept for the "by expression" filtering. What do you think?

Also, looks like this has tripped a test - http://dash.orfeo-toolbox.org/testDetails.php?test=35481442&build=210502

**Comment by mhugo** [comment]
I think I agree :) Unfortunately, I won't have time to work on it soon. I'll try to fix that before the 2.14 hopefully ...

**Comment by mhugo** [comment]
@nyalldawson That should now be as you suggested, but I am still not convinced by the difference of behaviour between "filter by map" and "filter by expression" ...
(tests not yet fixed btw)

**Comment by mhugo** [comment]
Merged with fixed unit tests. I will backport it to the 2.14 branch

**Pull request merged**
