### PR TITLE
SVG code for cursors a bit minimized

### PR DESCRIPTION
**Pull request by FelisPimeja**
**List of icons changed:**

- mCapturePoint.svg
- mCrossHair.svg
- mIdentify.svg
- mSampler.svg
- mSelect.svg
- mZoomIn.svg
- mZoomOut.svg

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Hi @FelisPimeja, just wondering I'm a curious guy, no offence please: what is the purpose of this? 

Is it just to have cleaner svg?
Is it because rendering becomes faster?

I just copied mCapturePoint.svg old and new svg to a file and opened these:

selection_336

Is the removal of the white ring by choice?

Maybe it is good to add screen shots of the icons like this, to make the PR more 'lively' :-)
And it is easier for people to (maybe) see the difference, and to help them to decide to pull or not?

**Comment by elpaso** [comment]
Wait, the white ring must not go away: it is essential when hovering on a dark background.

**Comment by FelisPimeja** [comment]
> Hi @FelisPimeja, just wondering I'm a curious guy, no offence please: what is the purpose of this?
> 
> Is it just to have cleaner svg?
> Is it because rendering becomes faster?

> Wait, the white ring must not go away: it is essential when hovering on a dark background.

Sorry friends - that was an error! @rduivenvoorde, @elpaso, thank you for catching it. Double checked and fixed it and also mSampler.svg

**Comment by nirvn** [comment]
This has been fixed, closing.

**Pull request closed without merging**
