### PR TITLE
Pass the full ogr data source URI as connInfo in qgsConnectionPool_ConnectionCreate

### PR DESCRIPTION
**Pull request by manisandro**
This fixes corrupt rendering when loading the same dataset twice with different options (i.e. layers), see issue #14560.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@manisandro probably good to add a test case for this too

**Comment by manisandro** [comment]
Mh yes, but not really sure how to best test this?

**Comment by nirvn** [comment]
@manisandro , thanks for the speediness with which you are fixing this issue. That regression will stop haunting me at night time :wink:

I'll confirm the regression is fixed as soon as this PR turns green. Thanks again!

**Comment by m-kuhn** [comment]
Could you start iterating on one layer and then open a feature iterator on the other layer and check if the first one still continues to serve features?

**Comment by manisandro** [comment]
The test failures seem once again caused by destruction ordering issues, so not directly related to this fix. One was easy to fix (60f346a), I'm still chasing the other one. Actually half of all tests (and qgis itself) segfault on exit here due to

    #0  0x00007ffff4041b5e in QBrush::~QBrush() () at /lib64/libQtGui.so.4
    #1  0x00007ffff53c77ac in QgsSimpleMarkerSymbolLayerV2::~QgsSimpleMarkerSymbolLayerV2() (this=
    0x12af600, __in_chrg=<optimized out>)
    #2  0x00007ffff53c7852 in QgsSimpleMarkerSymbolLayerV2::~QgsSimpleMarkerSymbolLayerV2() (this=0x12af600, __in_chrg=<optimized out>) at /home/sandro/Documents/Devel/QGIS/qgis-
    #3  0x00007ffff542e98f in qDeleteAll<QList<QgsSymbolLayerV2*>::const_iterator>(QList<QgsSymbolLayerV2*>::const_iterator, QList<QgsSymbolLayerV2*>::const_iterator) (begin=..., end=...)
    #4  0x00007ffff542e220 in qDeleteAll<QList<QgsSymbolLayerV2*> >(QList<QgsSymbolLayerV2*> const&) (c=...)
    #5  0x00007ffff542254a in QgsSymbolV2::~QgsSymbolV2() (this=0x7fff7651d0a0 <QgsCategorizedSymbolRendererV2::sSkipRender>, __in_chrg=<optimized out>)
    #6  0x00007fff75bcaeaa in QgsMarkerSymbolV2::~QgsMarkerSymbolV2() (this=0x7fff7651d0a0 <QgsCategorizedSymbolRendererV2::sSkipRender>, __in_chrg=<optimized out>)
    #7  0x00007fffedc756d8 in __run_exit_handlers (status=0, listp=0x7fffedffc5b8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true)
    #8  0x00007fffedc75725 in __GI_exit (status=<optimized out>)
    #9  0x00007fffedc5b0e8 in __libc_start_main (main=
    0x405d5a <main(int, char**)>, argc=1, argv=0x7fffffffde08, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffddf8)
    #10 0x0000000000405439 in _start ()

despite not seeing a marker symbol ever constructed at `0x7fff7651d0a0`, so it looks like there is some general memory corruption going on.

**Comment by m-kuhn** [comment]
I have seen this behavior before, it seems to depend on the platform (Fedora?).

On travis there are just two tests failing:

```
The following tests FAILED:
	 58 - qgis_labelingenginev2 (OTHER_FAULT)
	151 - PyQgsFeature (Failed)
```

**Comment by nirvn** [comment]
@manisandro , any luck working out the travis failures?

**Comment by manisandro** [comment]
@nirvn Haven't had much time to work on this, but as far as the crashes on exit are concerned, unfortunately not. But I'm writing a test for this specific fix, should be done pretty soon.

**Comment by manisandro** [comment]
I haven't managed to write a test which actually fails without the fix. The tests in 7fceaf8 attempt at parallelly fetching features from two different layers from the same dataset. But the tests also pass without 841bcd9.

**Comment by nyalldawson** [comment]
@manisandro I like those tests (even if they don't fail beforehand!), but I don't think we should add a 25mb binary to git.

**Comment by manisandro** [comment]
Yeah fair point, it was sort of to show what I tried. Removed it now.

**Comment by manisandro** [comment]
If there are no objections I'll merge this as is.

**Comment by nyalldawson** [comment]
@manisandro no objections here!

**Comment by luipir** [comment]
Hi Sandro,

give me some time to check if Uri expansion is not executed too early... seems all ok, but give me a short time to check.

**Comment by luipir** [comment]
Uri expansion is the implicit mechanism used to get credential from AuthManager using authcfg parameter. By defaut no URI expansion is executed before real use by provider.

**Comment by m-kuhn** [comment]
I have restarted the tests against current master to make sure their failing were really caused by other issues.

**Comment by luipir** [comment]
Hi Sandro

all seems ok from the point of view of Uri expansion... can be merged.

just a question from someone not so expert in this class raised reading them superficially... these are the questions:
1) seems ref and unref in QgsOgrConnPull are "similar" in function to the bease class (template) method of QgsConnPool acquireConnection() and releaseConnection()
2) if true the point 1) why not add ref() and unref() functionalities to the base class template?

please excuse me if I don't understand exactly the execution context of this class

**Comment by manisandro** [comment]
Hi @luipir 
The `acquireConnection` and `releaseConnection` methods will do just as they say, aquire and release a connection from the connection pool.
The `ref` and `unref` methods manage reference counting on a specific pool of connections (i.e. connections to one data source). This is used to ensure that all connections to a data source are released as soon as the last consumer of the data source is finished. The reason why this logic is only implemented for the OGR connection pool is that so far it is the only data source whose handles need this particular kind of logic to avoid file locking issues.
See also https://github.com/qgis/QGIS/pull/2755 for a more detailed explanation of the ref/unref logic.

**Comment by luipir** [comment]
@manisandro thank you let me dig more :)

no problems from me to merge

**Comment by manisandro** [comment]
@m-kuhn Can you confirm that the test failures are not new ones? (As stated above, on my system most tests fail due to the segfault on exit)

**Comment by m-kuhn** [comment]
These tests fail (segfault) only on this pull request, I assume there is a relation.

You can run them locally with

    ctest -R PyQgsFeature -V

and

    ctest -R qgis_labelingenginev2 -V

(hint, the labeling test can run from QtCreator with the debugger, the python test requires some environment variables setup to run from gdb)

**Comment by m-kuhn** [comment]
@manisandro what system are you using? I remember that I had a lot of troubles on fedora but meanwhile I have only few failing tests (and the two in question here pass).

**Comment by manisandro** [comment]
@m-kuhn Fedora rawhide. I suppose it is a taste for things to come on more conservative platforms ;)

**Comment by m-kuhn** [comment]
Or the experience of issues which will be ironed out in the dependencies before they hit more conservative platforms ;)

But if most of your tests "only" crash on exit, it should be possible to debug failures in the tests which likely happen before exit :)

**Comment by manisandro** [comment]
Okay, things are passing now.

**Comment by m-kuhn** [comment]
Thanks :+1:

**Comment by nirvn** [comment]
Yay thanks.

**Comment by nirvn** [comment]
@jef-n , @manisandro , this needs to be backported to 2.14, to prevent this significant regression from affecting users moving to 2.14 LTS.

**Pull request merged**
