### PR TITLE
[processing] other qgis test, clean commit

### PR DESCRIPTION
**Pull request by ghtmtt**
## Description
Clean commit of some more test for Processing. One with script and the others includes random algorithms, so the check is made to the algorithm run and not to the results (due to the randomness of the outputs)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks.

For the random points test, do you think a script could be written that generates random points and then counts points within the same bbox?

**Comment by ghtmtt** [comment]
you mean just counting the points in the bbox without checking if they are in the same location right?

**Comment by m-kuhn** [comment]
Yes exactly. Something like this:
https://github.com/ghtmtt/QGIS/blob/a289eb14fabc65aa90f8e183a94bba8c9a2413be/python/plugins/processing/tests/testdata/qgis_algorithm_tests.yaml#L198

**Comment by ghtmtt** [comment]
I see that travis complains for some selection. I'm sure that the `yaml` file does not check for results. I cannot figure out what is wrong.

**Comment by m-kuhn** [comment]
Let's take a short walk through the process, so next time you can do it yourself ;)

1. https://travis-ci.org/qgis/QGIS/jobs/215649028#L802
  * Note the file and line number
2. https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/qgis/RandomSelectionWithinSubsets.py#L78-L84
  * There is no output check involved here
3. What has gone wrong? Apparently we are trying to call `removeSelection()` on something that doesn't exist (`None`).
  * https://travis-ci.org/qgis/QGIS/jobs/215649028#L804
4. This *something that doesn't exist is...?
  * https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/qgis/RandomSelectionWithinSubsets.py#L78-L84
5. ... the input layer. Which apparently doesn't make it either into the script or from the script to the algorithm...

**Comment by ghtmtt** [comment]
Ok clearer now, thanks :)

**Comment by ghtmtt** [comment]
I removed the 2 tests with the selections so that this PR could be merged and we can deal with selection tests in a second moment

**Comment by ghtmtt** [comment]
@m-kuhn can this old PR be merged?

Thanks!

**Pull request merged**
