### PR TITLE
Interface and API for unified development/debugging tools

### PR DESCRIPTION
**Pull request by nyalldawson**
Adds interface hooks to allow plugins (and c++) to register "development/debugging" tools

These tools appear in a new Development/Debugging Tools dock, and provide a unified handling and place for these tools in the UI.

The intention here is that specialised development/debugging tools will be moved to this common interface, e.g.
- network logger
- first aid style Python local variables inspector
- startup time debugging tools
- layer load and rendering time debugging tools
... ?

Here's an example demo showing a "Python locals" dev tool:

image

Based heavily off @NathanW2's style dock work!

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nathanw2 would love your thoughts

**Comment by NathanW2** [comment]
Nice work.  This will be a good feature when building a plugin

**Comment by nirvn** [comment]
Really cool stuff @nyalldawson .

**Comment by alexbruy** [comment]
Nice addition!

**Comment by ymoisan** [comment]
@nyalldawson quick question : I thought network traffic visible in the development/debugging tools panel would also show /vsicurl/http:/ requests e.g. to a COG.  I guess QGIS can't trap HTTP get range requests because there aren't any to the extent that it is GDAL underneath that does the heavy lifting and QGIS just shows the result.  

I managed to see what I wanted, the actual range of bytes asked, using Wireshark but it would be nice if that were accessible in the development/debugging tools panel.  Or am I missing something ?

**Comment by nyalldawson** [comment]
You're not missing anything. We need to add hooks into gdal to allow custom callbacks on network activity, but that's a non trivial piece of work

**Comment by ymoisan** [comment]
Right.  Thanx Nyall.

**Comment by drnextgis** [comment]
@nyalldawson is there an open issue to keep track the status of that feature?

**Pull request merged**
