### PR TITLE
remove QgsSignalBlocker

### PR DESCRIPTION
**Pull request by 3nids**
Qt 5.3 offers QSignalBlocker

### CODE REVIEW

**Comment by 3nids** [comment]
hmmm, apparently Qt doesn't offer the `->` operator

**Comment by nyalldawson** [comment]
I'd also want to double check that it handles already-blocked signals and doesn't always restore to non-blocked on destruction.

**Comment by nyalldawson** [comment]
@3nids should we just close this?

**Comment by 3nids** [comment]
yep, doesn't worth the effort!

**Pull request closed without merging**
