### PR TITLE
[processing] correctly expose matrix and enum parameters to modeler

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
Add modeler GUI for matrix and enum parameters, allowing users to configure them (ref [#18734](https://issues.qgis.org/issues/18734))

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]
Looks good to me, very nice fix!

**Comment by nyalldawson** [comment]
@alexbruy a couple of notes after testing this:

- I get an error if I try to edit an existing enum option:

```
TypeError: setAllowMultiple() takes 1 positional argument but 2 were given 
Traceback (most recent call last):
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/modeler/ModelerGraphicItem.py", line 435, in mousePressEvent
    self.action()
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/modeler/ModelerGraphicItem.py", line 210, in editElement
    param=self.model.parameterDefinition(self.element.parameterName()))
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/modeler/ModelerParameterDefinitionDialog.py", line 83, in __init__
    self.setupUi()
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/modeler/ModelerParameterDefinitionDialog.py", line 285, in setupUi
    self.widget.setAllowMultiple(bool(self.param.allowMultiple()))
TypeError: setAllowMultiple() takes 1 positional argument but 2 were given
```
- I can set multiple default checks even when "allow multiple selection" is not checked. 
- If I check "allow multiple selection" and then check one or more default options, I get an exception when running the alg:
```
Traceback (most recent call last):
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/modeler/ModelerDialog.py", line 334, in runModel
    dlg = AlgorithmDialog(self.model)
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/gui/AlgorithmDialog.py", line 70, in __init__
    self.setMainWidget(self.getParametersPanel(alg, self))
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/gui/AlgorithmDialog.py", line 77, in getParametersPanel
    return ParametersPanel(parent, alg)
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/gui/ParametersPanel.py", line 81, in __init__
    self.initWidgets()
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/gui/ParametersPanel.py", line 110, in initWidgets
    wrapper = WidgetWrapperFactory.create_wrapper(param, self.parent)
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/gui/wrappers.py", line 1670, in create_wrapper
    return WidgetWrapperFactory.create_wrapper_from_class(param, dialog, row, col)
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/gui/wrappers.py", line 1734, in create_wrapper_from_class
    return wrapper(param, dialog, row, col)
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/gui/wrappers.py", line 160, in __init__
    self.setValue(param.defaultValue())
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/gui/wrappers.py", line 1001, in setValue
    self.widget.setSelectedItems(value)
  File "/home/nyall/dev/build-QGIS/output/python/plugins/processing/gui/MultipleInputPanel.py", line 64, in setSelectedItems
    self.tr('{0} elements selected').format(len(self.selectedoptions)))
TypeError: object of type 'int' has no len()
```
- I think the "clear" icon should be `console/iconClearConsole.svg` instead of the checkbox clear (and maybe a confirmation prompt should be added there?)

Matrix param:
- I also get an exception if I try to edit an existing matrix parameter
- I think the widget should default to one column - a zero column matrix isn't very useful :)
- If i enter a 2x2 matrix with values 1/2/3/4, then the last entered value is forgotten when clicking "OK", (unless you do some other step after entering it - like adding a new column)

But otherwise it's working very nicely!

**Comment by alexbruy** [comment]
@nyalldawson comments should be addressed now

**Comment by nyalldawson** [comment]
I'm still seeing a couple of outstanding issues:

Matrix param:

- I think the widget should default to one column - a zero column matrix isn't very useful :)
- If i enter a 2x2 matrix with values 1/2/3/4, then the last entered value is forgotten when clicking "OK", (unless you do some other step after entering it - like adding a new column)

Enum:

- I still get an error when trying to edit an existing enum parameter
- Default checkboxes are now checked when clicking an item (so e.g. double clicking to rename changes the default)
- In "allow multiple selection" mode, it's impossible to clear the checkbox for a row

**Comment by alexbruy** [comment]
> If i enter a 2x2 matrix with values 1/2/3/4, then the last entered value is forgotten when clicking "OK", (unless you do some other step after entering it - like adding a new column)

Do you have same issue with fixed table wrapper? Seems this is normal Qt's behavior, when cell is edited, action should be confirmed. I see the same in the existing Fixed table wrapper.

**Comment by alexbruy** [comment]
Fixed enum dialog and added a column to the matrix by default (IMHO this is still useless, but if users will be happy...)

**Comment by alexbruy** [comment]
IMHO this is ready for merge now. There is only one "issue" related to the matrix editing, but I see the same behavior in other places (e.g. Fixed table dialog) and for me it looks logical. And unfortunately I have not idea how we can fix it, already tried couple of workarounds, but they don't work for me.

**Comment by alexbruy** [comment]
@nyalldawson any objections to merge this?

**Comment by nyalldawson** [comment]
Looks great! I noticed one little issue, I'll push a follow up directly

**Pull request merged**
