### PR TITLE
Support negative short integer primary keys on PostgreSQL

### PR DESCRIPTION
**Pull request by strk**
See http://hub.qgis.org/issues/14262

NOTE: signed int64 keys would still fail

See also https://github.com/qgis/QGIS/pull/2797

### CODE REVIEW

**Comment by strk** [comment]
A solution that would always work is always using the map as done in  #2797

**Comment by m-kuhn** [comment]
Couldn't we just use a static_cast or a union to convert everything with up to 64 bits into a QgsFeatureId, possibly reinterpreting the real value but preserving the bit pattern?

    fid = static_cast<QgsFeatureId>( pgPrimaryKey );

**Comment by m-kuhn** [comment]
Actually... isn't it just a matter of passing it as signed or unsigned when creating the query string?

Isn't the information preserved when converting PK to FID already now and just conversion back from FID to PK fails?

**Comment by strk** [comment]
If I understood correctly a negative FID means "new feature"
for QGIS. Am I wrong ?

**Comment by strk** [comment]
For the record, @jef suggested using a map for int64 too

**Comment by m-kuhn** [comment]
Sorry, my bad. In this case my vote goes also to map for int64.

**Comment by jef-n** [comment]
@strk sure - if we wouldn't consider feature with negative ids new, there wouldn't be a problem.

**Comment by strk** [comment]
Ok, so with commit cbcc929feed532ba916d2155393e571c3e623df3 LongLong
fields are handled with FidMap, and the 64bit enum value is renamed
from pktInt64 to pktUint64 but NOT USED.

Rather than removing the 64bit type I renamed it in case we can
figure out (using check constraints, for example) that the values
in the pk field cannot be negative.

--strk;

**Comment by m-kuhn** [comment]
Instead of using `fid = attr + PKINT_OFFSET` could instead a `fid = static_cast<quint32>( i )` be used? That would not change the currently working 1:1 mapping of positive integers and only add new negative int support.

**Comment by strk** [comment]
I'm not sure you can count on lossless trip on update,
but anyway until this bug has a proper automated testcase
(and is run on enough architectures) any fix would be
an hazard.

**Comment by strk** [comment]
Branch rebased to master, will work on a testcase in a few hours

**Comment by strk** [comment]
One problem with the failing test is due to the tests expecting a specific FID value (1,2,3,4,5) while we'd be offsetting those values to allow them for taking negative values.

**Comment by strk** [comment]
Ok now I see what @m-kunh was saying in https://github.com/qgis/QGIS/pull/3036#issuecomment-216518241, the 1:1 mapping would fix the result form these tests. Not sure how static_cast<> output is predictable/stable, will look it up

**Comment by strk** [comment]
So now Travis pass, but features with negative identifiers in the database still cannot be edited.
We're back to needing a testcase for bug http://hub.qgis.org/issues/14262

**Comment by strk** [comment]
Alright now geometries can be edited again, and the only travis failures are in the signedIntIdentifier test, which was added by me while tacking a crash in signed identifiers handling, reading the test it does seem to be partially broken (expecting the wrong results) and partially catching a bug (loss of value in attribute table). This is GOOD as it means a test does exist :)

**Comment by strk** [comment]
Alright now existing tests should be good, but I think there are more problems with the test, as it tests (for example) that a table with int2 negative identifier retains the negative FID, which would mean you can not edit negative identifiers....

Also, I'd think the test needs to be improved to avoid relying on the actual implementation. All we really need to check is for the FID to not be considered NEW. FeatureID::isNew() exposed in python ? Need to check...

**Comment by strk** [comment]
Test is now improved but it still contains a wrong expectancy for int8 identifier.
An int8 should be still using a FidMap as that's the only way to ensure support for negative identifiers (other than stopping with the use of Fid sign as a mean to encode new vs. old records).

So this PR will be complete once int8 (bigint) identifiers are again being handled with a FidMap.
Do you agree about that @m-kuhn ?

Note that a "serial" type will not use a bigint field in PostgreSQL.

**Comment by m-kuhn** [comment]
If all types with less than 64 bits are mapped in a way that positive integers are handled equally as before, good job!
For 64 bits we will have to take some tradeoffs, so a FidMap is probably the best we can get.

**Comment by strk** [comment]
Alright, looking at the code the 64bit primary keys are already handled with a FidMap, so all is left here is to provide a proper testcase testing for the ability to EDIT a feature identified by suck negative identifier.

**Comment by strk** [comment]
With the latest commits, full signed integer ranges for int2, int4 and int8 are tested. I think it is enough for this round, so removing the "Required Tests" label.

**Comment by strk** [comment]
I've also manually testing editing layers with negative primary keys in int2, int4 and int8 layers.
Both modifying existing goemetries and adding new geometries (lines).

I think this is ready to be merged.

**Comment by strk** [comment]
Manually merged after a rebase with top-commit being d1cac842d323ffb13a606e8d598dd0d8af4ade72

**Pull request closed without merging**
