### PR TITLE
Use QNetworkAccessManager::setTransferTimeout

### PR DESCRIPTION
**Pull request by m-kuhn**
Available since Qt 5.15
Much more solid since it doesn't timeout if too many requests are queued in parallel

### CODE REVIEW

**Comment by nirvn** [comment]
Sweet.

**Comment by nyalldawson** [comment]
There's a lot of extra logic that the internal timer does though - eg it pauses the timeout if an auth dialog is shown.

**Comment by m-kuhn** [comment]
That should be shown before the transfer timeout is started?

**Comment by m-kuhn** [comment]
Tested, auth dialog timeout is an issue of this implementation.

However beware that the current implementation has some issues, demonstrated by the following code:

```
QgsNetworkAccessManager.instance().setTimeout(5000)
QgsNetworkAccessManager.instance().requestTimedOut.connect(lambda: print('timeout'))

for i in range(10):
    reply = QgsNetworkAccessManager.instance().get(QNetworkRequest(QUrl('https://codeload.github.com/qgis/QGIS/zip/master?{}'.format(i))))
    reply.finished.connect(lambda: print('finished'))
#    reply.downloadProgress.connect(lambda: print('progress'))
```

Only the first 6 requests work, the other 4 reuquests time out because they sit in the queue for too long.

**Comment by m-kuhn** [comment]
Opened an unintrusive #40628 as alternative is this one is not acceptable.

**Comment by m-kuhn** [comment]
> There's a lot of extra logic that the internal timer does though - eg it pauses the timeout if an auth dialog is shown.

@nyalldawson is this a blocker for you?

I don't think the pause is doable with the qt transfer timeout. And I don't think the other problem is fixable with the qgis timeout.

**Comment by nyalldawson** [comment]
It's a blocker for me -- many auth requests methods will take some time to handle. It's not inconceivable that an oauth2 authentication request will take 60 seconds, for instance (login page to load, user to enter details, get their password wrong once, reenter and wait for service to login...). So this change could easily result in broken requests which rely on oauth2, with no way to fix.

You could potentially use the older approach selectively if an auth method is set for the request, but there's other similar timeout pausing for other situations like ssl error handling which I can't see how to handle this way...

**Comment by m-kuhn** [comment]
Many auth requirements are only known at response time and not at request time, so I think we're on thing ice by having a conditional timeout mechanism.

If an oauth2 based request times out, what happens exactly? If it is just resent will the authentication still be valid (and no more user interaction required for the rest of the session)?
Also how risky is this actually, given that there's still some communication happening during the authentication.

In the ssl scenario the user has [60] seconds to confirm the dialog, where I think it's a reasonable assumption he does this.

Are we able to verify the impacts of the core qt implementations on these scenarios?
I'd be happy to give this a test in order to move to an upstream implementation.

**Comment by nyalldawson** [comment]
> Many auth requirements are only known at response time and not at request time, so I think we're on thing ice by having a conditional timeout mechanism.

Oh, we totally are. The whole current approach with request handling and auth/errors/timeouts is very fragile! I'm not denying that at all. :smile: 

> If an oauth2 based request times out, what happens exactly? If it is just resent will the authentication still be valid (and no more user interaction required for the rest of the session)?
> Also how risky is this actually, given that there's still some communication happening during the authentication.

The authentication should succeed, but the original request will have failed. It's hard to state the consequences of that -- in some cases it may just require a manual refresh action by a user, but in other cases it may result in some submission failure of a more serious nature. Given that oauth2 IS used by plugins (I've certainly deployed quite a few) I'm **extremely** nervous about the second situation breaking critical workflows. (especially given the enterprise leaning nature of this authentication type, any breakage just isn't something we cannot afford to allow).

> In the ssl scenario the user has [60] seconds to confirm the dialog, where I think it's a reasonable assumption he does this.

Hmmm... maybe. I suspect I'm not the only one who often triggers some action in an application and then flicks across to some other application and just trusts that the process proceeds ok in the background. I'd rather flick back in 10 minutes to a warning message and a chance to proceed then a warning message and a request which has already failed.

> Are we able to verify the impacts of the core qt implementations on these scenarios?
I'd be happy to give this a test in order to move to an upstream implementation.

I can test with some oauth2 services I regularly use, but not till next week...

**Comment by nyalldawson** [comment]
I wonder if using QNetworkRequest::setTransferTimeout wouldn't help avoid some of the issues, especially if we could potentially temporarily set the timeout to 0 on specific requests and then reset it later to achieve the same timeout pausing as we currently do...

**Comment by m-kuhn** [comment]
Thanks for the detailed answer.

I've had a look at it, I don't see how that would be possible (https://codereview.qt-project.org/c/qt/qtbase/+/278064). It's setup once in the request and once this is sent it is inside the private internals of qt. We'd need to patch Qt to offer something like `QNetworkReply::pauseTimeout()` to get on par.

**Pull request closed without merging**
