### PR TITLE
Fix assert with negative QVector size in transformBoundingBox

### LINKED ISSUE #32302: Crash on "zoom to layer" with global raster in EPSG:3031 (antarctic)
**Describe the bug**
QGIS crashes when I "zoom to layer" with a global raster in EPSG:3031 (antarctic).

**How to Reproduce**

1. Load HYP_50M_SR_W.tif from https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/raster/HYP_50M_SR_W.zip (I guess it happens on any raster with the same extents but did not test).
2. Set the OTF-CRS to EPSG:3031
3. Use "zoom to layer" on the raster layer
4. QGIS crashes

**QGIS and OS versions**

QGIS version | 3.9.0-Master | QGIS code revision | 1a7294bc7f
-- | -- | -- | --
Compiled against Qt | 5.13.1 | Running against Qt | 5.13.1
Compiled against GDAL/OGR | 3.0.1 | Running against GDAL/OGR | 3.0.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.30.0 | Running against SQLite | 3.30.1
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.2.0 | Running against PROJ | Rel. 6.2.0, September 1st, 2019
OS Version | Arch Linux
Active python plugins | quick_map_services; SelectByRelationship; GeoCoding; qconsolidate3; web2qgis; MemoryLayerSaver; QPackage; timemanager; nominatim; QuickWKT; pointsamplingtool; QuickOSM; DotMap; GeodesicDensifier; qgis2web; Qgis2threejs; qtiles3; local_dominance; db_manager; processing; MetaSearch

**Additional context**
This is master from a while ago. Got no debugging symbols compiled in so no backtrace, sorry.

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This fixes #32302 by insuring that the multilication of nXPoints and nYPoints doesn't result in overflown (and therefore negative) int value.

The gdb output of the crash was:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff2fa9899 in __GI_abort () at abort.c:79
#2  0x0000555555565c55 in qgisCrash(int) (signal=-1) at /home/webmaster/dev/cpp/QGIS/src/app/main.cpp:360
#3  0x000055555556608d in myMessageOutput(QtMsgType, char const*)
    (type=QtFatalMsg, msg=0x55555d0e2d78 "ASSERT failure in QVector::QVector: \"Size must be greater than or equal to 0.\", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h, line 487") at /home/webmaster/dev/cpp/QGIS/src/app/main.cpp:436
#4  0x00007ffff3433508 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff3433599 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff3402a80 in QMessageLogger::fatal(char const*, ...) const () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff3401f46 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff4cc0060 in QVector<double>::QVector(int) (this=0x7fffffffc3b8, asize=-1606247658) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qvector.h:487
#9  0x00007ffff51ea03a in QgsCoordinateTransform::transformBoundingBox(QgsRectangle const&, QgsCoordinateTransform::TransformDirection, bool) const
    (this=0x7fffffffc570, rect=..., direction=QgsCoordinateTransform::ForwardTransform, handle180Crossover=false)
    at /home/webmaster/dev/cpp/QGIS/src/core/qgscoordinatetransform.cpp:533
#10 0x00007ffff57de52b in QgsRasterLayerRenderer::QgsRasterLayerRenderer(QgsRasterLayer*, QgsRenderContext&) (this=0x55555cf92120, layer=
    0x55555993b190, rendererContext=...) at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgsrasterlayerrenderer.cpp:105
#11 0x00007ffff57c26f5 in QgsRasterLayer::createMapRenderer(QgsRenderContext&) (this=0x55555993b190, rendererContext=...)
    at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgsrasterlayer.cpp:245
#12 0x00007ffff5333c7a in QgsMapRendererJob::prepareJobs(QPainter*, QgsLabelingEngine*, bool) (this=0x55555cd4ea20, painter=0x0, labelingEngine2=
    0x7fffc2346e70, deferredPainterSet=false) at /home/webmaster/dev/cpp/QGIS/src/core/qgsmaprendererjob.cpp:359
#13 0x00007ffff5339a4a in QgsMapRendererParallelJob::start() (this=0x55555cd4ea20) at /home/webmaster/dev/cpp/QGIS/src/core/qgsmaprendererparalleljob.cpp:61
#14 0x00007ffff69c2422 in QgsMapCanvas::refreshMap() (this=0x5555565f41f0) at /home/webmaster/dev/cpp/QGIS/src/gui/qgsmapcanvas.cpp:563
#15 0x00007ffff69d640c in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (QgsMapCanvas::*)()>::call(void (QgsMapCanvas::*)(), QgsMapCanvas*, void**) (f=(void (QgsMapCanvas::*)(class QgsMapCanvas * const)) 0x7ffff69c20bc <QgsMapCanvas::refreshMap()>, o=0x5555565f41f0, arg=0x7fffffffcfa0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#16 0x00007ffff69d5bbc in QtPrivate::FunctionPointer<void (QgsMapCanvas::*)()>::call<QtPrivate::List<>, void>(void (QgsMapCanvas::*)(), QgsMapCanvas*, void**)
    (f=(void (QgsMapCanvas::*)(class QgsMapCanvas * const)) 0x7ffff69c20bc <QgsMapCanvas::refreshMap()>, o=0x5555565f41f0, arg=0x7fffffffcfa0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#17 0x00007ffff69d49da in QtPrivate::QSlotObject<void (QgsMapCanvas::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x555556719dc0, r=0x5555565f41f0, a=0x7fffffffcfa0, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:414
#18 0x00007ffff362e5c8 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff363b66b in QTimer::timeout(QTimer::QPrivateSignal) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff362ee55 in QObject::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff4016a86 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff401fe00 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff515b6ff in QgsApplication::notify(QObject*, QEvent*) (this=0x7fffffffd8c0, receiver=0x5555563d2190, event=0x7fffffffd340)
    at /home/webmaster/dev/cpp/QGIS/src/core/qgsapplication.cpp:418
#24 0x00007ffff3602a9a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff3659a00 in QTimerInfoList::activateTimers() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff365a2dc in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007fffec30084d in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
```

@nyalldawson , it'd be great if you could look into this. The fix is mostly a bandaid, the underlying series of events leading to insanely large nXPoints / nYPoints values aren't fully understood by yours truly :wink: 

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [x] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Review by nyalldawson — COMMENTED** [review]
Nice fix ! Any chance of a unit test?

**Comment by nirvn** [comment]
@nyalldawson , done.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@nirvn frozen? or merge?

**Comment by nirvn** [comment]
Considering it fixes a crash, and the fix is pretty straight forward, I'd be inclined to merge.

**Pull request merged**
