### PR TITLE
Throw IndexError on some QgsCurvePolygon methods when invalid interior ring index is requested [API]

### PR DESCRIPTION
**Pull request by nyalldawson**
Minor improvement to PyQGIS QgsCurvePolygon api.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@m-kuhn 

Should we just stop using [blah] tags in PR titles and rely on github labels instead?

**Comment by m-kuhn** [comment]
Yes, I think so. I don't know why those tags are used so heavily still in PR titles.
At least core devs with access to labels should prefer them IMO, on other pull requests we can convert tags into labels when we run into them first.

**Comment by elpaso** [comment]
IIRC the idea was to keep [labels] in git logs.

**Comment by m-kuhn** [comment]
Good point. What about putting them on another line than the subject line?

**Comment by nyalldawson** [comment]
I'm advocating for keeping them in commit messages, but dropping them from pr titles (which don't necessarily show in the log anyway)

**Pull request merged**
