### PR TITLE
[Server] Fix crach on WFS Insert

### PR DESCRIPTION
**Pull request by sbrunner**
## Description
See: #32202

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [x] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by Gustry** [comment]
You created a PR #32202 manually for the backport, so you don't need the label here, no?

**Comment by sbrunner** [comment]
@Gustry I just remove the label :-)

**Review by pblottiere — APPROVED** [review]

**Review by rldhont — APPROVED** [review]

**Comment by sbrunner** [comment]
@nyalldawson Why do you add the label frozen?
It's a bug fix that's already be merger in 3.4, then I think that should be in the release...

**Comment by elpaso** [comment]
@sbrunner the frozen tag is attached "by default" because we are in deep freeze mode, but I don't see any issue in merging this PR.

**Comment by sbrunner** [comment]
Thanks @elpaso, it's effectively what I suspected :-)

**Pull request merged**
