### PR TITLE
Implement proper gradient ramp based legends

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR implements a new QgsColorRampLegendNode class for creating nice color ramp based legend nodes. It's now used for raster layers when using a pseudocolor renderer with the linear interpolation type, or for the single band gray renderer, and for point clouds using a ramp based renderer. (Shown respectively below):

image

image

image

In a layout legend the ramp item inherits the default legend symbol width and height, but you also get the option to override this if needed:

Peek 2020-12-07 12-46

There's labels included for the minimum and maximum ramp value, which are rendered using the same font settings as other legend item text:

Peek 2020-12-07 12-48

Label alignment will follow the legend settings:

Peek 2020-12-07 12-49

And naturally, the items will work nicely with multi column legends:

Peek 2020-12-07 12-50

Further customisation options will be coming in follow up PRs.

Sponsored by Hans van der Kwast (https://www.youtube.com/c/HansvanderKwast)

### CODE REVIEW

**Comment by nyalldawson** [comment]
Fixes #27436 , Fixes #25579, Fixes #17844

**Comment by saberraz** [comment]
That has been in my wish-list for a long time. Thanks a lot @nyalldawson

**Comment by gioman** [comment]
Huge.

**Comment by roya0045** [comment]
Someone said legend? 👴

**Review by nirvn — APPROVED** [review]
Nice stuff.

**Comment by ffilipponi** [comment]
Thanks for this implementation!
I am wondering if it can be further extended with labels of intermediate values in the color ramp and the support of the raster logarithmic scale (already suggested here: https://github.com/qgis/QGIS/issues/15910)

QGIS plugin called "1 band color table" (available until QGIS 2.x) helped to create nice color ramps to be used in map layout, but it has not been further developed https://www.geoproc.com/be/bccscbar.htm

It would be nice to have these features implemented within the QGIS core functionalities.

**Comment by nyalldawson** [comment]
@ffilipponi yes, that would be possible! It would require funding though (unless you're able to do the coding of this and can submit a pull request?)

**Comment by ffilipponi** [comment]
@nyalldawson  thanks for rapid feedback.
I have further investigated the development of the "1 band color table" and just discovered its newer version:
https://github.com/BC-Consulting/geoprocalgos

My objective was solely related to propose a new feature as a user. Unfortunately I do not have specific programming skills on C++, so I will not able to submit a pull request. I hope that funding from the many sustaining members and donors will support the project in order to convert the many proposals into reality.

**Comment by nyalldawson** [comment]
>  I hope that funding from the many sustaining members and donors will support the project in order to convert the many proposals into reality.

Unfortunately this funding is only very rarely used for feature development, and instead is budgeted toward bug fixes and other general project maintenance tasks. It's left to the community to develop or fund feature requests directly.

Still, it's a relatively straightforward request, so fingers crossed it's implemented quickly now that all the framework for the ramp based legends is in place.

**Pull request merged**
