### PR TITLE
Have QgsGeometry::fromRect(NULL RECT) return null geometry

### PR DESCRIPTION
**Pull request by strk**
Rather than a Polygon with min/max ordinate values which doesnt' make much sense.
Spin-off of https://github.com/qgis/QGIS/pull/54646

### CODE REVIEW

**Comment by nyalldawson** [comment]
Hmm, do we really want a polygon with no exterior ring in that case? I'd lean toward a null geometry instead.

**Comment by strk** [comment]
I guess I should add a test. I'd want a `POLYGON EMPTY` which is an object known by other projects too, with clear semantic. The thing is that this change fixes the existing tests when QgsRectangle() default constructor changes from 0,0,0,0 to a null one so I know this change is effectively fixing a problem.

The concept of "null geometry" is not clear to me, and I hope there isn't really such concept other than a C null or C++ optional<> or something. In this case there's no unknown: we know exactly that we need to represent the EMPTY space, so IMHO `POLYGON EMPTY` would be the best, and I think it's what we're returning here (default-constructed Polygon is EMPTY)

**Comment by strk** [comment]
> > concept of "null geometry" is not clear to me
> 
> Null QgsGeometry objects are used extensively throughout qgis code. If you're not familiar with them then you need to do some reading ASAP. 😱😱😱

Could you point me to a good starting point ? What I'd like to know is how EMPTY != NULL, and this is also useful to grok for the QgsRectangle case as it's a source of a lot of confusion.

**Comment by strk** [comment]
I'll find out about Null and Empty as I add tests (spotted isNull and isEmpty)

**Comment by strk** [comment]
So I've now rebased and force-pushed again in this branch, this time with a testcase.
The testcase expects an EMPTY polygon being returned. I'll be happy to try a NULL geometry but will have to first find out how you construct it, and I would still be scared of hitting other test failures for the return not being a POLYGON type

**Comment by strk** [comment]
@nyalldawson returning a NULL geometry results in the null geoemtry .asWkt() printing horrible numbers, sounds like another pandora vase to open, why not just taking the POLYGON EMPTY as a good enough representation for now ? :)

```
FAIL!  : TestQgsGeometry::fromRect() Compared values are not the same
   Actual   (fromRect.asWkt())                 : "Polygon ((1797693134862315708145274237317043567980705675258449965989174768031572607800285387605895586327668781715404589535143824642343213268894641827684675467035375169860499105765512820762454900903893289440758685084551339423045832369032229481658"...
   Expected (QStringLiteral( "Polygon EMPTY" )): "Polygon EMPTY"
```

**Comment by strk** [comment]
Sorry, I was wrong, null geometry prints as empty string with asWkt, it's ok

**Comment by strk** [comment]
Rebased to master and had the NULL geometry be returned, instead of empty polygon

**Comment by strk** [comment]
I think this test was succeeding when we returned POLYGON EMPTY:
https://github.com/qgis/QGIS/actions/runs/6551411071/job/17798252800?pr=54954#step:13:725

But I could be wrong...

**Review by nyalldawson — APPROVED** [review]

**Comment by strk** [comment]
I confirm returning an EMPTY POLYGON rather than a NULL geometry fixes the test_core_labelingengine which is otherwise failing here: https://github.com/qgis/QGIS/actions/runs/6561420572/job/17826514832?pr=54646#step:13:297

Is it so important to you to return a NULL geometry instead of an EMPTY POLYGON ?

**Comment by strk** [comment]
> I confirm returning an EMPTY POLYGON rather than a NULL geometry fixes the test_core_labelingengine which is otherwise failing here: https://github.com/qgis/QGIS/actions/runs/6561420572/job/17826514832?pr=54646#step:13:297
> 
> Is it so important to you to return a NULL geometry instead of an EMPTY POLYGON ?

My guess is that handling of "null geometry" is more broken than handling of "empty polygon", I may follow the rabbit down the hole and fix more "null geometry" but the risk is that this is going to be a never ending path, remembering THIS pr was aimed at merging GH-54646

**Comment by strk** [comment]
QgsGeometry::boundingBox() is returning a default-constructed QgsRectangle, which is not-null. I guess an EMPTY POLYGON doesn't do this, but I could be wrong. The questino is WHERE to fix this as I already have so many PRs open that's being hard to manage

**Comment by strk** [comment]
The QgsPalLayerSettings::registerFeatureWithDetails method is very very dense but at some point checks for visible extent, which is the NULL rectangle for the testcase at hand. It converts it to a Geometry and then does a lot of other things with it. All I know is that en EMPTY POLYGON makes the test pass while a NULL GEOMETRY does not:

See how POLYGON EMPTY is handled better than NULL GEOMETRY:

```
QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:451 : (prepare) [2ms] Visible extent: Null
QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:452 : (prepare) [0ms] mapSetting extentBuffer: 0 
QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:454 : (prepare) [0ms] Grown visible extent: Null
QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:456 : (prepare) [0ms] Extent geom  
FAIL!  : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() Compared values are not the same
   Actual   (provider->mLabels.size()): 1
   Expected (0)                       : 0
   Loc: [/usr/local/src/qgis/qgis/src/rectangle-null/tests/src/core/testqgslabelingengine.cpp(955)]
```

vs.
```
90: QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:451 : (prepare) [2ms] Visible extent: Null
90: QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:452 : (prepare) [0ms] mapSetting extentBuffer: 0
90: QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:454 : (prepare) [0ms] Grown visible extent: Null
90: QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:456 : (prepare) [0ms] Extent geom  Polygon EMPTY
90: PASS   : TestQgsLabelingEngine::testRegisterFeatureUnprojectible()
```

**Comment by nyalldawson** [comment]
> QgsGeometry::boundingBox() is returning a default-constructed QgsRectangle, which is not-null. I guess an EMPTY POLYGON doesn't do this, but I could be wrong. The questino is WHERE to fix this as I already have so many PRs open that's being hard to manage

The difference is that the empty polygon results in a QgsRectangle( nan, nan, nan, nan ) being returned, as opposed to QgsRectangle.

I realise this will all ultimately be fixed when we're at a stage where we can merge your work improving this default, but it seems there's still a non-trivial amount of work left there.

What about introducing a temporary method:

```
    static QgsRectangle createNull()  SIP_SKIP {
      return QgsRectangle( std::numeric_limits<double>::quiet_NaN(),
        std::numeric_limits<double>::quiet_NaN(),
        std::numeric_limits<double>::quiet_NaN(),
        std::numeric_limits<double>::quiet_NaN() ); };
````

we could then use this in places like the null geometry case in QgsGeometry::boundingBox() to quickly get PRs like this merged. (Without resorting to approaches like returning an empty polygon which will likely burn us on the long run)

**Review by nyalldawson — APPROVED** [review]

**Comment by strk** [comment]
> What about introducing a temporary method

I've implemented this in a commit pushed to this branch ( a0856cc14ec350c6fb237a7bc2a1675ef85120f2 ) and then used that method to fix the QgsGeometry::boundingBox() method also in this branch ( 864edb035f24182025f6c52a6b33ccff8feb1db4 )

**Comment by strk** [comment]
Adding some debugging lines, the differences I see are:

When returning POLYGON EMPTY:
```
90: QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:451 : (prepare) [2ms] Visible extent: Empty
90: QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:452 : (prepare) [0ms] mapSetting extentBuffer: 0
90: QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:454 : (prepare) [0ms] Grown visible extent: Empty
90: QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:456 : (prepare) [0ms] Extent geom  Polygon EMPTY
```

When returning NULL GEOMETRY:
```
QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:451 : (prepare) [2ms] Visible extent: Null
QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:452 : (prepare) [0ms] mapSetting extentBuffer: 0
QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:454 : (prepare) [0ms] Grown visible extent: Null
QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() src/core/labeling/qgspallabeling.cpp:456 : (prepare) [0ms] Extent geom  Polygon ((179769313486231570814527423731704356798070
56752584499659891747680315726078002853876058955863276687817154045895351438246423432132688946418276846754670353751698604991057655128207624549009038932894407586850845513394230458323690322294816
5808559332123348274797826204144723168738177180919299881250404026184124858368 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514
38246423432132688946418276846754670353751698604991057655128207624549009038932894407586850845513394230458323690322294816580855933212334827479782620414472316873817718091929988125040402618412485
8368, -1797693134862315708145274237317043567980705675258449965989174768031572607800285387605895586327668781715404589535143824642343213268894641827684675467035375169860499105765512820762454900
90389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368 17976931348623157081452742373170435679807056752584499659891747680
31572607800285387605895586327668781715404589535143824642343213268894641827684675467035375169860499105765512820762454900903893289440758685084551339423045832369032229481658085593321233482747978
26204144723168738177180919299881250404026184124858368, -179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464
182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368 -179769313486231
57081452742373170435679807056752584499659891747680315726078002853876058955863276687817154045895351438246423432132688946418276846754670353751698604991057655128207624549009038932894407586850845
5133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368, 17976931348623157081452742373170435679807056752584499659891747680315726078002853876058
95586327668781715404589535143824642343213268894641827684675467035375169860499105765512820762454900903893289440758685084551339423045832369032229481658085593321233482747978262041447231687381771
80919299881250404026184124858368 -1797693134862315708145274237317043567980705675258449965989174768031572607800285387605895586327668781715404589535143824642343213268894641827684675467035375169
86049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368, 1797693134862315708145274237317043567
98070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222
948165808559332123348274797826204144723168738177180919299881250404026184124858368 1797693134862315708145274237317043567980705675258449965989174768031572607800285387605895586327668781715404589
53514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184
124858368))
```

**Comment by strk** [comment]
Ok the problem is that the QgsPallLabelling tries to fix the NULL geometry as it reports itself as being "invalid". Pretty lame thing to do. Whether a NULL geometry should be considered valid or not is an interesting question, and is exactly to avoid these questions that I'd rather reduce the number of "EMPTY" representations. If the geometry is empty, I'd say it's valid.

**Comment by strk** [comment]
Worse: QgsGeometry::isNull() is not returning true for a null geometry!
90: QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() prepareGeometry called with geometry  QVariant(QgsGeometry, )
90: QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() geometry typed  Qgis::GeometryType::Polygon  was not found null, going on with preparation

**Comment by strk** [comment]
The QgsPalLabeling::prepareGeometry returns a NULL geometry after trying to clip the incoming geometry with the "visible extent" which is either EMPTY or NULL.

Now, I could ask it not to clip but...  should we just directly skip adding a feature to the labeling engine if the visible extent is empty ? (nothing to see, why label at all ?)

**Comment by strk** [comment]
Now an interesting thing is that QgsPalLabeling::prepareGeometry is documented to  take a "null" clipGeometry parameter to mean "do not clip, thanks", while it still clips when given an EMPTY POLYGON, and the clipping results in the clipped geometry becoming EMPTY too, and then it never adds a label for it.

**Comment by strk** [comment]
The other "fun" thing is that by looking at the failing test, I don't really see why we're expecting no label. The test is called "unreprojectible" but that geometry seem to be reprojected just fine:

```
90: QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() Reprojecting geom  "Polygon ((0 0, 8 0, 8 -90, 0 0))"
90: QDEBUG : TestQgsLabelingEngine::testRegisterFeatureUnprojectible() Finally-reprojected geom  "Polygon ((0 0, 890555.92634618852753192 0, 890555.92634618852753192 -242528680.94374272227287292, 0 0))"
```

Those values are the same with both the working and non-working version (the thing that changes is whether or not the geometry is clipped and thus becomes EMPTY (resulting in no label being added) or if it's not clipped and (resulting in the label being added and the test failing).

I'm tempted to rework the test rather than the code

**Comment by strk** [comment]
The test was written for a crasher bug: #23431

**Comment by strk** [comment]
@rouault do you know what happened, and when, which made `SRID=4326;POLYGON((0 0,8 0,8 -90,0 0))` projectible to `EPSG:3857` ? I'm asking because it wasn't projectible in [September 2016](https://github.com/qgis/QGIS/issues/23431#issuecomment-495864734) but today both PostGIS and QGIS are transforms that to `SRID=3857;POLYGON((0 0,890555.9263461885 0,890555.9263461885 -242528680.94374272,0 0))`

**Comment by rouault** [comment]
> do you know what happened, and when, which made `SRID=4326;POLYGON((0 0,8 0,8 -90,0 0))` projectible to `EPSG:3857` ?

A change in PROJ a few years ago that is more numerically accurate, and relates to the fact that -90 degree converts to slightly less than M_PI/2 radians due to floating point computations, and thus can be converted in a finite northing due to tan(slightly_below_pi_over_2) being finite.

**Comment by strk** [comment]
Thanks @rouault -- I've filed https://github.com/qgis/QGIS/pull/55011 to make that point further unprojectible (-91 instead of -90 of latitude)

**Pull request merged**
