### PR TITLE
add new script dissolve with stats

### PR DESCRIPTION
**Pull request by juliepierson**
Turning plugin Dissolve With Stats into a processing plugin (UMR-PASSAGES/DissolveWithStats#2) (see https://github.com/qgis/QGIS-Processing/pull/70)

### CODE REVIEW

**Comment by nyalldawson** [comment]
Hi @juliepierson,

Thanks for this contribution! I'm wondering why there's a need to add a new algorithm here instead of extending the existing dissolve algorithm? In my opinion it would be better to avoid a second algorithm and instead have just a single algorithm with this extra option.

**Comment by alexbruy** [comment]
I agree with @nyalldawson, better to have single algorithm.

**Comment by juliepierson** [comment]
I agree too, but I did not feel comfortable messing with existing algorithms ;-) Do you want me to have a go, or would you prefer to do it ?

**Comment by arnaud-morvan** [comment]
Hi, I was working on similary algorithm in the same time, just created the pull request :
https://github.com/qgis/QGIS/pull/4210

**Comment by nyalldawson** [comment]
Closed in favour of #4210

**Pull request closed without merging**
