### PR TITLE
Add test for coverage of SIP bindings

### PR DESCRIPTION
**Pull request by nyalldawson**
Not perfect, but good for a quick warning if a new class or member has been added to the public API without Python bindings. The test only considers the name of members, since it seems to be impossible to test for the signature of a Python member. (So adding a new overloaded method without bindings will still unfortunately pass).

You can avoid the test where bindings are not applicable:
- for a whole class by placing "@note not available in Python bindings" in the class' Doxygen comments
- or by placing the @note inside a member's Doxygen comments for a specific member

Additionally, classes which aren't included in the API docs will not be tested.

### CODE REVIEW

**Comment by mhugo** [comment]
Thanks for this work, that will be very useful !

**Comment by mhugo** [comment]
I like the idea.
Using the doxygen XML tree seems a good idea.
I've tested your branch and get this : 
205 classes missing bindings, out of 199 allowed

I've had similar results on the DocCoverage test.
Could it be related to the version of Doxygen (1.8.6 here) or the compilation options ?

**Comment by mhugo** [comment]
I have this in the list of missing objects: 
'Bezier3D', 'CloughTocherInterpolator', 'CustomLayerOrderModel', 'DataDefinedRestorer', 'DualEdgeTriangulation', 'EffectItem', 'GEOSInit', 'GetNamedProjectColor', 'HalfEdge', 'ItemDelegate', 'LinTriangleInterpolator', 'Line3D', 'MyLine', 'Node', 'NormVecDecorator', 'ParametricLine', 'Point3D'

This is part of Geos (and maybe other libs) ... could it explain the count difference I have ? Would retaining only classes starting with 'Qgs' help?

**Comment by nyalldawson** [comment]
@mhugo do you build with server? I've tweaked the thresholds to match the Travis builds, which are set to build server...

**Comment by mhugo** [comment]
@nyalldawson Yes I build with server
Here is the content of missing_objects:
['Bezier3D', 'CloughTocherInterpolator', 'CustomLayerOrderModel', 'DataDefinedRestorer', 'DualEdgeTriangulation', 'EffectItem', 'GEOSInit', 'GetNamedProjectColor', 'HalfEdge', 'ItemDelegate', 'LinTriangleInterpolator', 'Line3D', 'MyLine', 'Node', 'NormVecDecorator', 'ParametricLine', 'Point3D', 'QgisPlugin', 'QgisVisitor', 'QgsAbstractFeatureIteratorFromSource', 'QgsAbstractLabelProvider', 'QgsAbstractVectorLayerLabeling', 'QgsActionMenu', 'QgsAdvancedDigitizingCanvasItem', 'QgsAdvancedDigitizingDockWidget::CadConstraint', 'QgsAnimatedIcon', 'QgsApplyDialog', 'QgsAttributeFormLegacyInterface', 'QgsAttributeTypeLoadDialog', 'QgsAuthConfigEdit', 'QgsAuthConfigIdEdit', 'QgsAuthCrypto', 'QgsAuthGuiUtils', 'QgsAuthMethodMetadata', 'QgsAuthMethodRegistry', 'QgsBrowserTreeView', 'QgsBrowserWatcher', 'QgsCategorizedSymbolRendererV2Model', 'QgsCategorizedSymbolRendererV2ViewStyle', 'QgsCheckBoxConfigDlg', 'QgsCheckboxWidgetFactory', 'QgsCheckboxWidgetWrapper', 'QgsClassificationWidgetWrapper', 'QgsClassificationWidgetWrapperFactory', 'QgsCodeEditor', 'QgsCodeEditorPython', 'QgsColorEffectWidget', 'QgsColorWidgetFactory', 'QgsColorWidgetWrapper', 'QgsComposerMouseHandles', 'QgsConnectionPool', 'QgsConnectionPoolGroup', 'QgsConstWkbPtr', 'QgsDataItemProviderFromPlugin', 'QgsDateTimeEditConfig', 'QgsDateTimeEditFactory', 'QgsDateTimeEditWrapper', 'QgsDatumTransformDialog', 'QgsDefaultSearchWidgetWrapper', 'QgsDiagramLabelFeature', 'QgsDial', 'QgsDummyConfigDlg', 'QgsDxfLabelProvider', 'QgsDxfPaintDevice', 'QgsDxfPaintEngine', 'QgsDxfPalLabeling', 'QgsEnumerationWidgetFactory', 'QgsEnumerationWidgetWrapper', 'QgsExpression::Function', 'QgsExpression::Interval', 'QgsExpression::Node', 'QgsExpression::NodeBinaryOperator', 'QgsExpression::NodeColumnRef', 'QgsExpression::NodeCondition', 'QgsExpression::NodeFunction', 'QgsExpression::NodeInOperator', 'QgsExpression::NodeList', 'QgsExpression::NodeLiteral', 'QgsExpression::NodeUnaryOperator', 'QgsExpression::StaticFunction', 'QgsExpression::Visitor', 'QgsExpression::WhenThen', 'QgsFeatureIteratorDataStream', 'QgsFeatureSelectionDlg', 'QgsFileNameWidgetFactory', 'QgsFileNameWidgetWrapper', 'QgsGenericFeatureSelectionManager', 'QgsGeometry::Error', 'QgsGeometryEditUtils', 'QgsGeometryFactory', 'QgsGeometryUtils', 'QgsGeos', 'QgsGraduatedHistogramEventFilter', 'QgsGraduatedSymbolRendererV2Model', 'QgsGraduatedSymbolRendererV2ViewStyle', 'QgsHiddenWidgetFactory', 'QgsHiddenWidgetWrapper', 'QgsLabelFeature', 'QgsLabelLayerRegistry', 'QgsLabelingEngineV2', 'QgsLegacyHelpers', 'QgsMapCanvas::CanvasProperties', 'QgsMapCanvasRendererSync', 'QgsMapCanvasSnappingUtils', 'QgsMapHitTest', 'QgsMapToolTouch', 'QgsMapUnitScaleDialog', 'QgsMasterPasswordResetDialog', 'QgsNetworkProxyFactory', 'QgsNetworkReplyParser', 'QgsOSMDatabase', 'QgsOSMDownload', 'QgsOSMElement', 'QgsOSMNode', 'QgsOSMNodeIterator', 'QgsOSMTags', 'QgsOSMWay', 'QgsOSMWayIterator', 'QgsOSMXmlImport', 'QgsObjectCustomProperties', 'QgsPalGeometry', 'QgsPanningWidget', 'QgsPhotoConfigDlg', 'QgsPhotoWidgetFactory', 'QgsPhotoWidgetWrapper', 'QgsPixmapLabel', 'QgsPluginLayerRenderer', 'QgsPointLocator_DumpTree', 'QgsPointLocator_Stream', 'QgsPointLocator_VisitorArea', 'QgsPointLocator_VisitorEdgesInRect', 'QgsPointLocator_VisitorNearestEdge', 'QgsPointLocator_VisitorNearestVertex', 'QgsQtLocationConnection', 'QgsRangeConfigDlg', 'QgsRangeWidgetFactory', 'QgsRangeWidgetWrapper', 'QgsRasterLayerRenderer', 'QgsRasterRendererRegistry', 'QgsRelation::FieldPair', 'QgsRelationAddDlg','QgsRelationEditorWidget', 'QgsRelationManagerDialog', 'QgsRelationReferenceConfigDlg', 'QgsRelationReferenceFactory', 'QgsRelationWidgetWrapper', 'QgsRenderResult', 'QgsRendererV2DataDefinedMenus', 'QgsRuleBasedLabelProvider', 'QgsRuleBasedLabeling', 'QgsRuleBasedLabeling::Rule', 'QgsRuleBasedRendererV2::Rule', 'QgsSLConnect', 'QgsSearchWidgetWrapper', 'QgsSlider', 'QgsSpatialIndexCopyVisitor', 'QgsSpatialIndexData', 'QgsSvgListModel', 'QgsTextEditConfigDlg', 'QgsTextEditWidgetFactory', 'QgsTextEditWrapper', 'QgsTextLabelFeature', 'QgsUniqueValueWidgetFactory', 'QgsUniqueValuesConfigDlg', 'QgsUniqueValuesWidgetWrapper', 'QgsUnitSelectionWidget', 'QgsUuidWidgetFactory', 'QgsUuidWidgetWrapper', 'QgsValueMapConfigDlg', 'QgsValueMapSearchWidgetWrapper', 'QgsValueMapWidgetFactory', 'QgsValueMapWidgetWrapper', 'QgsValueRelationConfigDlg', 'QgsValueRelationSearchWidgetWrapper', 'QgsValueRelationWidgetFactory', 'QgsValueRelationWidgetWrapper', 'QgsVector', 'QgsVectorFileWriter::BoolOption', 'QgsVectorFileWriter::HiddenOption', 'QgsVectorFileWriter::IntOption', 'QgsVectorFileWriter::Option', 'QgsVectorFileWriter::SetOption', 'QgsVectorFileWriter::StringOption', 'QgsVectorLayerDiagramProvider', 'QgsVectorLayerEditPassthrough', 'QgsVectorLayerFeatureSource', 'QgsVectorLayerLabelProvider', 'QgsVectorLayerRenderer', 'QgsVectorLayerSelectionManager', 'QgsVectorLayerSimpleLabeling', 'QgsVisibilityPresetCollection::PresetRecord', 'QgsWMSLegendNode', 'QgsWebViewWidgetConfigDlg', 'QgsWebViewWidgetFactory', 'QgsWebViewWidgetWrapper', 'QgsXmlUtils', 'SpinBoxDelegate', 'SymbolLayerItem', 'TreeFilterProxyModel', 'TriDecorator', 'TriangleInterpolator', 'Triangulation', 'Vector3D', 'pal::Feature', 'pal::PalGeometry']

**Comment by nyalldawson** [comment]
Here's the list from the Travis build:

http://dash.orfeo-toolbox.org/testDetails.php?test=33862451&build=203759

It's possible that this branch is a little behind master... maybe that's the difference? 

How do your build options compare with Travis'?
https://github.com/qgis/QGIS/blob/master/ci/travis/linux/install.sh

**Comment by mhugo** [comment]
Sorry, that was because my doc files was not correctly regenerated. Actually "make clean" does not clean the doc/api directory (and ... does not seem immediate to fix).

**Comment by nyalldawson** [comment]
Any objections if I merge?

**Comment by mhugo** [comment]
@nyalldawson no objections from me at least :)

**Comment by nyalldawson** [comment]
Manually merged in fc49f8dfa9b1076b8834a4c8f615e265153b088f

**Pull request closed without merging**
