### PR TITLE
Allow processing dialog to override default processing context settings

### PR DESCRIPTION
**Pull request by nyalldawson**
This adds a new "Algorithm Settings" action to the Advanced button. Selecting it shows a panel allowing users to control general processing settings which apply to that algorithm execution **only**. It's intended to be a place where a user can override their global processing settings on an ad-hoc basis without having to change their usual default settings.

Currently contains settings for:
- invalid geometry handling (Unlike the existing per-parameter setting override for this, setting the handling method here will apply to ALL inputs for the algorithm)
- distance unit and area units to use for distance/area measurements

https://user-images.githubusercontent.com/1829991/225210305-2c5daab0-6e40-453c-8260-996bf8cd5b75.mp4

### CODE REVIEW

**Review by alexbruy — APPROVED** [review]

**Comment by alexbruy** [comment]
Maybe we can also expose this functionality to Python, to allow 3rd party plugins add required entries to this panel?

**Comment by nyalldawson** [comment]
> Maybe we can also expose this functionality to Python, to allow 3rd party plugins add required entries to this panel?

I'm honestly not entirely sure how to do this cleanly. I think we'd first need some custom property storage in QgsProcessingContext (ie as a variant map), so that the algorithms could retrieve any custom settings. But then I'm stuck on a clean way to expose the ability to add widgets here, without going overboard with a widget factory class and registry... Any alternative ideas?

**Comment by alexbruy** [comment]
I was thinking about more or less the same approach with registry and factory. But let's not block this feature, what I was saying is that such fucntionality can be useful for plugins, but it can be added later if there will be a need for it.

**Comment by nyalldawson** [comment]
> it can be added later if there will be a need for it.

Sounds good to me!

**Pull request merged**
