### PR TITLE
[FEATURE][processing] New algorithm for offsetting lines

### PR DESCRIPTION
**Pull request by nyalldawson**
Implements another geometry operation which isn't easily doable with the existing providers/algorithms.

### CODE REVIEW

**Comment by alexbruy** [comment]
Maybe I'm wrong, but Processing has OGR algorithm which creates offset curves. GDAL/OGR → [OGR] Geoprocessing → Single sided buffers (and offset lines) for lines.

**Comment by nyalldawson** [comment]
> Maybe I'm wrong, but Processing has OGR algorithm which creates offset curves. GDAL/OGR → [OGR] Geoprocessing → Single sided buffers (and offset lines) for lines.

Heh, you're right. I'd missed that one. I'd still say there's value in this, because 
1. All the nice stuff Qgis native algorithms give us, like export to different formats
2. Much easier to set join styles, etc
3. A lot less confusing!

**Comment by alexbruy** [comment]
Sure, I completely agree with you. Just wanted to point out on existing tool with similar functionality.

**Comment by nyalldawson** [comment]
@alexbruy - great! good to see we're on the same page.

#3380 has some small follow ups. 

Question - can an algorithm in processing change name without breaking stuff? I want to change the "polygon centroids" tool so that it works for non polygons (ie linestrings, etc can have centroids too), but without breaking existing models which use this. Is that possible?

**Comment by alexbruy** [comment]
AFAIK this is not possible, as command-line name generated from provider and algorithm names. But as we are breaking API I think it is OK to change name.

There is also another approach: implement separate algs for different geometry types.

**Comment by luipir** [comment]
would make sense to introduce a command alias feature?

**Comment by nyalldawson** [comment]
What about if I just make a new, generic centroid algorithm and hide the old one from the toolbox? That would ensure no-ones models break...

**Comment by alexbruy** [comment]
Personally I think it is OK to break Processing API, as we will break it anyway sooner or later.

@volaya, what is your opinion?

**Comment by gioman** [comment]
> Heh, you're right. I'd missed that one. I'd still say there's value in this, because
> 1. All the nice stuff Qgis native algorithms give us, like export to different formats
> 2. Much easier to set join styles, etc
> 3. A lot less confusing!

Hi @nyalldawson and @alexbruy The tool in the OGR toolbox was added because at that time I was adding a few others vector geoprocessing tools based on ogr2ogr + SQL. The reason for adding such tools was that I was looking to add reliable geoprocessing tools, unlike a few of the QGIS native ones (we still have QGIS tools that return wrong results). Bonuses: this tools are generally faster than the qgis ones, they stop (with significative erros in log) if input geometries have errors and are based on functions (ST_Union, ST_Buffer, etc.) that are known to work as expected (of course the underlying query must be correct). Unitl now I added only tools that make use of 1 input layer, but since is possible to create virtual vectors in Processing it is also possible to add tools that make use of >1 input layer, and as soon as I will find time I plan to add them.

**Comment by nyalldawson** [comment]
I'd be interested if you tested the speed of this vs the ogr2ogr one. I would be surprised if ours isn't faster, since (I assume) OGR uses geos for the buffer op too, and our algorithm avoids the need to convert between formats. If there's bugs/slowness in the QGIS algs we should fix those algorithms ;)

**Comment by gioman** [comment]
@nyalldawson OGR: 2.5 min to dissolve (by "distrito") this http://www.dgterritorio.pt/ficheiros/cadastro/caop/caop_download/contaadcaop2015 The QGIS tool took 6 min. The OGR tool also computed a bunch of stats on dissolved fields, option that is missing in the QGIS tool.

**Comment by nyalldawson** [comment]
Looks like we've got some work to do then!

**Pull request merged**
