### PR TITLE
"Refactor fields" in modeler, no layer context

### PR DESCRIPTION
**Pull request by m-kuhn**
Inside the modeler, there is no knowledge (yet ;) ) about the context in which an algorithm will finally run. For example we don't know if we will have a layer as input or a feature source (well, actually we know this, but then we don't know which attributes the layer will have).

Some algorithms (like `relation_aggregate`) require a layer in the context or they will throw an eval error.

Still, the expression builder for the refactor fields algorithm (and probably others as well) is shown, but with a reduced expression context.

This commit adds the possibility to enter expressions with eval errors in this scenario, by not disabling the Ok button, while errors still show up.

# Future plans

In the long run it would be nice to allow configuring a "dummy layer" for layer inputs in the modeler. The modeler can then build expression contexts from an existing layer, for configuration purpose.

### CODE REVIEW

**Comment by m-kuhn** [comment]
@nyalldawson @arnaud-morvan any feedback from your side?

**Comment by m-kuhn** [comment]
@alexbruy @volaya any thoughts?

**Comment by nyalldawson** [comment]
I'll review this tomorrow

**Comment by alexbruy** [comment]
Looks like a reasonable approach until we update modeler.

**Comment by nyalldawson** [comment]
Good change! When using qgis I've also bumped into this problem before, where I should have been allowed to enter an expression which would have evaluation errors on some features only ... I just can't remember where now!

I think we could also allow parser errors in some places. Eg if I start entering a complex expression for a label, but mid way through need to check something outside the builder (eg a field name from another layer), I'm blocked from doing this. But really I should be allowed to enter invalid expressions here, and come back later to finish them off.

**Review by nyalldawson — APPROVED** [review]

**Comment by m-kuhn** [comment]
We could also change the color of the Ok button in such a scenario to be visually explicit.

**Comment by nyalldawson** [comment]
> We could also change the color of the Ok button in such a scenario to be visually explicit.

 Good idea!

**Comment by m-kuhn** [comment]
Ok, that can easily be done as a followup.
Let's see if it makes sense then to even make `allowEvalErrors = true` the default.

**Pull request merged**
