### PR TITLE
Move CODING document to rst

### PR DESCRIPTION
**Pull request by m-kuhn**
Replaces #1869

### CODE REVIEW

**Comment by m-kuhn** [comment]
See here for a rendered version:

https://github.com/m-kuhn/QGIS/blob/coding/doc/CODING.rst

Even includes pictures:

https://github.com/m-kuhn/QGIS/blob/coding/doc/CODING.rst#setting-up-your-project

And has syntax highlighting

**Comment by NathanW2** [comment]
+1

**Comment by m-kuhn** [comment]
With t2t a .txt and a .html file have been generated inside the source tree.

Do we want/need this or should this go to the build directory?

Should we also switch the other t2t files to rst and use sphinx for building?

@rduivenvoorde you may have good input as well

**Comment by jef-n** [comment]
The files are already created in the build directory (see doc/CMakeLists.txt and cmake/Txt2Tags.cmake)

**Comment by m-kuhn** [comment]
Are they updated manually in the source folder?

**Comment by rduivenvoorde** [comment]
I am in favour of moving to rst, but would even go further and move it outside of the source tree into documentation. In that way we can link to it and it is translatable.

I would not make sphinx a build prerequisite... (though in docutils there is a rst2pdf/html too).

BUT if moving it outside of the source tree would mean that it is not updated anymore I would leave it as rst there....

**Comment by jef-n** [comment]
@m-kuhn yes (or no, I have a toplevel makefile target for that)
@rduivenvoorde +1 for moving it to the documentation.  html, txt and pdf are redundant anyway. Pretty sure that they will get any less love there than in the source tree - as that is hardly possible and will take years to verify ;)

**Comment by jef-n** [comment]
But they are also installed - so that probably means we need drop them from the package and verify that the application itself doesn't point to any of them.

**Comment by m-kuhn** [comment]
+1 for moving them to the docs and drop them from the packages.

If you want to get involved you should have a look at github anyway and we can put some links into the readme on github.com/qgis/QGIS and the getinvolved part of the homepage. This link can then point to the most recent version of the coding doc.

**Comment by m-kuhn** [comment]
There is also the [BUGS](https://github.com/qgis/QGIS/blob/master/BUGS) file which I'm not sure if it's worth it. People who are not familiar with bugreporting will probably not look into the source tree anyway. There are also bug related information at:

 * https://hub.qgis.org/wiki/17/Bugreports
 * http://qgis.org/en/site/getinvolved/development/index.html#bugs-features-and-issues

What do you think about consolidating the two pages above into a single one (translatable at qgis.org) and 301 the first url (at the moment the first one is on top of google but I think the second one is maintained instead). Then removing the bugs file and adding a link to the qgis.org page to the readme.

**Comment by m-kuhn** [comment]
@rduivenvoorde do you have any inputs about where exactly this could be added? Is there already a development section somewhere? I couldn't see one with a short look through https://github.com/qgis/QGIS-Documentation

**Comment by rduivenvoorde** [comment]
@m-kuhn yes: here:

http://qgis.org/en/site/getinvolved/development/index.html#development

so you could create an 'install.rst' in that development directory?

**Comment by m-kuhn** [comment]
Hmmm... @rduivenvoorde I don't know the structure good enough. Is it all one big document or are there different chapters / books like admin/user/developer?
I guess install belongs to (sys)admin, coding to developer.

**Comment by rduivenvoorde** [comment]
ok, I pulled in the coding.rst plus the images into the website:

http://qgis.org/en/site/getinvolved/development/qgisdevelopersguide.html

you should be able to edit file at: 

https://github.com/qgis/QGIS-Website/blob/master/source/site/getinvolved/development/qgisdevelopersguide.rst

to me it is fine if we decide to drop coding.txt now

**Pull request closed without merging**
