### PR TITLE
[processing][FEATURE][needs-doc] load default script from template backport to 3.0

### PR DESCRIPTION
**Pull request by ghtmtt**
## Description
 Backporting #6678 to release-3_0 with commits cherry picked

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by ghtmtt** [comment]
@nyalldawson here we are. I cherry picked the useful commits (also your lasts). I hope I did not mess up branches ;)

**Comment by ghtmtt** [comment]
@nyalldawson sorry for the delay of this. I made a dummy commit to restart travis

**Comment by ghtmtt** [comment]
@m-kuhn any idea why travis is failing? Can I do something to restart it? Thanks!

**Comment by tudorbarascu** [comment]
@ghtmtt It seems the spell checker detects something. Maybe checking out the scripts in ``scripts/spell_check`` would help. I usually change a little the last commit message with the ``--amend`` option and force push to restart Travis.

**Comment by ghtmtt** [comment]
@tudorbarascu thanks for the hint. Actually that's strange because the code is cherry-picked from #6678 and there no spelling issued were detected. I ran the scripts you suggested but no errors were found so far.

**Comment by m-kuhn** [comment]
It doesn't detect anything, it just times out. Looks like the code to detect which files have changed is broken (it's run on way more file than actually have changed)

@3nids any idea?

**Comment by Gustry** [comment]
> Can I do something to restart it?

I do one of these:
* Close/reopen the PR
* git commit --amend (without changing something to recreate the last commit)
* git rebase master

**Comment by ghtmtt** [comment]
@Gustry thanks for the hint. Done, let's see ;)

**Comment by ghtmtt** [comment]
yeah! travis is happy!

**Comment by nyalldawson** [comment]
Thanks @ghtmtt!

**Pull request merged**
