### PR TITLE
Update r.regression.line.txt

### PR DESCRIPTION
**Pull request by neteler**
Update to current GRASS GIS 7 release branch

### CODE REVIEW

**Comment by jef-n** [comment]
Why are there 65 separate pull requests that only change one text file each?

**Comment by neteler** [comment]
I used the web editor.

Markus

**Comment by jef-n** [comment]
I applied and squashed all of them manually.  Hopefully I didn't miss anything.

**Comment by neteler** [comment]
Thanks and sorry for the mess. However, the next bulk update will be for
GRASS GIS 8 only...

**Pull request closed without merging**
