### PR TITLE
Add QtWebEngine re-exports to qgis.PyQt

### PR DESCRIPTION
**Pull request by dvdkon**
## Description

Now that QtWebEngine is working and we finally have a non-deprecated hopefully-secure webview, I think it makes sense to re-export it as `qgis.PyQt.QtWebEngine*`.

To support both Qt5 and Qt6, `qgis.PyQt.QtWebEngineQuick` imports either `PyQt6.QtWebEngineQuick` or `PyQt5.QtWebEngine` based on Qt version. There should AFAIK be no major changes that would further break this approach for simple plugins.

With Qt5, creating a `QtWebEngineView`, pointing it at a webpage and showing it with `.show()` works. I didn't build QGIS itself under Qt6 to test this, but the imports do work in a console with PyQt6.

### CODE REVIEW

**Comment by nyalldawson** [comment]
We don't have a hard dependency on webengine right now, so these imports will need to gracefully silently handle import exceptions if the library isn't available

**Comment by dvdkon** [comment]
> We don't have a hard dependency on webengine right now, so these imports will need to gracefully silently handle import exceptions if the library isn't available

I'm not sure it's possible to handle this silently (without a fatal error/exception). Wouldn't that require re-implementing the whole module? Sooner or later the script will want to use the classes it imported. 

Besides, `QtWebKit` has the same issue - importing it fails with an exception if it's not installed, and it's been unavailable in Linux builds for years now.

**Comment by m-kuhn** [comment]
If these modules are imported but the underlying `PyQt6` modules are missing an exception is expected.
If the `qgis.PyQt` modules are not imported, no exception will be raised.

I think this is safe to merge.

**Comment by nyalldawson** [comment]
Ah yeah, I misinterpreted this 👍

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
