### PR TITLE
New QgsImageOperation class for operations that modify QImages

### PR DESCRIPTION
**Pull request by nyalldawson**
Contains framework for multithreaded operations on QImages, and a method for converting QImages to grayscale.

Operations are multithreaded only if the image is sufficiently large to justify multithreading. From my tests, the multithreading speeds the operation up by 2/3x for large images.

Much more operations to come, but I'd appreciate a review of this framework before proceeding...

### CODE REVIEW

**Comment by nyalldawson** [comment]
@wonder-sk mind reviewing this for me?

**Comment by nirvn** [comment]
Could this be used by the raster symbology code to fasten brightness / contrast / saturation / grayscale there?

**Comment by nyalldawson** [comment]
@wonder-sk I've updated this PR - the new version uses functors and implements a number of effects, including effects which operate in blocks and in individual lines. How's this look now?

**Comment by wonder-sk** [comment]
Looks good to me!

**Comment by nyalldawson** [comment]
manually merged

**Pull request closed without merging**
