### PR TITLE
Set max tile buffer size to 1024. Fix #47324.

### LINKED ISSUE #47324: [server] Allow tile buffer to be > 99 pixels in wms
### Feature description

At present (master @ bbfa18f3a), tile buffer in WMS cannot be more than 99 pixels. Is it possible to accept a value more than 99?  When I enter a value greater than 99, it reverts to 99:
out

### PR DESCRIPTION
**Pull request by ismailsunni**
## Description

Set max tile buffer size to 1024. Fix #47324.

1024 is a random "interesting" number, I don't think people will use more than 1000 buffer. But, who knows.

As far as I check, there is no limit for the buffer on the server-side. Perhaps @elpaso has some idea about it.

### CODE REVIEW

**Review by troopa81 — APPROVED** [review]
1024 looks way enough! or I'm missing some strange use cases. 

Thanks for fixing this

**Comment by troopa81** [comment]
@ismailsunni Could you rebase on master to fix MinGW64 CI tests ?

**Comment by nyalldawson** [comment]
@troopa81 the mingw container is currently broken -- there's something wrong in Fedora's repos. (@manisandro are you aware of this one?)

**Comment by nyalldawson** [comment]
@manisandro yep, seems to have been resolved today 👍

**Pull request merged**
