### PR TITLE
Convert expression context help to json format

### PR DESCRIPTION
**Pull request by nyalldawson**
This changes the expression help from free form html files to structured json files. A new python script then parses these json help files into the html help contents, in a standardised manner. Previously, the function help was a bunch of different formats and structures.

Now, a custom stylesheet can be applied (and later tweaked (@nirvn :P? ) !) to format these help. Eg, this commit already colors variables and function names in the syntax section for greater readability:

expression_help

I'm also hoping to generate a small form of the syntax for use as a context-sensitive tooltip in the editor widget (eg, hover over function name in the expression to see expected syntax for the function).

The script could also potentially be adapted for generating an expression reference document for the QGIS manual.

### CODE REVIEW

**Comment by NathanW2** [comment]
Very nice. Good idea using json for that.

**Comment by pcav** [comment]
How nice. Perhaps this could be useful also for Processing documentation, on the Help tab for each command? @volaya @alexbruy @rduivenvoorde

**Comment by nirvn** [comment]
Very cool. It'll be interesting to experiment with a qgis-logo inspired
color scheme.

**Comment by m-kuhn** [comment]
Good stuff! :+1:

**Comment by rduivenvoorde** [comment]
While I like json :-) , I would prefer if we use rst for ALL help files: expression, processing, context etc etc be part of the normal online documentation (which could be packaged and downloaded locally).

As all these helpfile would be normal docs, they also would get translated and available online (or packaged)!

We talked (and yes I know... only talked about this), to generate some util class which:
- had one global ini/config file which matched id's to uri's (either a local file, or an online file)
- uri's can have anchors so for example the expression docs could be in one page or grouped in some groups
- help could be openen in a dialog, widget or browser via this util class
- some option to be able to either link to an (uptodate) online version, OR a (one language zipped) local doc.zip file

@wonder-sk I think that is what we discussed/planned isn't it? Maybe we can plan to work on this on next hackfest? 
@pka I understood you were planning something in that direction for a client contract too?
@timlinux something like this for Inasafe?

Let's try to get this lifted

**Comment by m-kuhn** [comment]
I like the json way because it adds semantics to it, we know which parameters there are and can determine a return type. This could be used e.g. for autocompletion and rst generation. Or is this possible with rst as well?

**Comment by rduivenvoorde** [comment]
I like the idea of 'metadata', 'semantics' , 'annotation' or whatever it is called for things like autocompletion
 :-)
Actually I just learned from @rouault on the qgis dev list that GDAL has this too:
  https://lists.osgeo.org/pipermail/qgis-developer/2015-August/038913.html
(but xml....)

But please do not add another 'documentation/html build system'. The json->rst route sounds ok for me. Although then probably it would be nicer if the documentation build scripts did that: pull json stuff, make rst from it etc etc..

**Comment by nyalldawson** [comment]
@rduivenvoorde as @m-kuhn said, we really need this to be in a semantic format so that we can format it up in a number of different ways. I'd be willing to move it to rst if that had flexible semantic support, but from my understanding it doesn't. That's actually why I went json for this... it's nice and flexible and being semantic will allow us to write scripts to output it in any way/format we later require.

**Comment by pcav** [comment]
For Processing, we have some additional problems:
* the help for some backends is already done (e.g. GRASS); rewriting it in json would be a mammoth task. Would it be feasible to convert it?
* for other backends it is missing; writing rst is feasible, json is far more difficult; I'm worried this will scare documenters away.
Anyway, unifying and semantifying the help would be a huge improvement (missing documentation is reported as a main disadvantage for QGIS users nowadays).

**Comment by nyalldawson** [comment]
@pcav it's quite different requirements between the expression help and the other context help and processing help (in my opinion). This PR just cleans up the current situation with the expression help... and in the process makes it possible for it to be reformatted and reused outside of the expression builder context.

**Comment by jef-n** [comment]
It there work underway to integrate it into scripts/update_ts.sh?  The context help is integrated (although cumbersome to translate, but also cumbersome to redo the translations).

**Comment by nyalldawson** [comment]
So what's the consensus? Merge or not? 

(Keep in mind that this PR is here ready to go now, AFAIK no-one is actively working on alternative approaches ;) )

**Comment by NathanW2** [comment]
IMO. Merge it because I personally don't see RST fitting in here and we can
use this to generate RST.

**Comment by rduivenvoorde** [comment]
Yes, I'm ok with merging to. For your purpose rst is of no help anyway. 
And as Nathan sais: we can easily rst from it (into documentation plz) so it will be part of documentation and can be translated.

**Comment by nyalldawson** [comment]
@m-kuhn thanks!

**Comment by m-kuhn** [comment]
@nyalldawson that should be me saying that ;)

**Pull request merged**
