### PR TITLE
[processing] Add dedicated "distance" parameter

### PR DESCRIPTION
**Pull request by nyalldawson**
Because I'm sick of trying to explain to users how the buffer distance parameter works!....

This is a subclass of QgsProcessingParameterNumber, but specifically
for numeric parameters which represent distances. It is linked
to a parent parameter, from which the distance unit will
be determined, and is shown using a dedicated distance widget
within the processing parameters panel. This widget shows
the distance unit.

This avoids the confusion when running algorithms which
use distances where the unit depends on a layer or CRS parameter -
e.g. the distance parameter in the buffer algorithm gives
the distance in layer units... so now we can show those units
directly within the dialog. Hopefully this leads to less
user confusion and accidental "1000 degree buffers"!

Additionally - if the unit is in degrees, a small warning
icon is shown next to the parameter. The tooltip for this
icon advises users to reproject data into a suitable
projected local coordinate system.

Initially implemented for the native buffer and single
sided buffer algorithm only - but more will be added.

Fixes #16290

peek 2018-04-19 22-44

### CODE REVIEW

**Comment by ghtmtt** [comment]
hell yeah! thanks for this!

**Comment by DelazJ** [comment]
Indeed, It might reduce confusion. Thanks.
Btw, what are the rules to set default numeric values in Processing algorithms? I mean, during algorithm documentation work, I notice that there were algs whose default distance/spacing values are kind of `0,0001` (see Create Grid), others `1,000` (see Snap points to Grid), others `10` (Buffer)... Depending on the units being used, these defaults are not all relevant. So should we choose a unit as default and align default values or have a set of defaults depending on units ?

**Comment by nyalldawson** [comment]
@DelazJ 

> Btw, what are the rules to set default numeric values in Processing algorithms? I mean, during algorithm documentation work, I notice that there were algs whose default distance/spacing values are kind of 0,0001 (see Create Grid), others 1,000 (see Snap points to Grid), others 10 (Buffer)... Depending on the units being used, these defaults are not all relevant. So should we choose a unit as default and align default values or have a set of defaults depending on units ?

We could possibly standardise some of these default distances - but we'd have to be careful, as e.g. the default distance for grids should be less than that for buffer. But it's important to keep in mind that these defaults are constant, regardless of the distance unit -- so they'll always be meaningless and we're probably best to just decide if we set reasonable defaults for meters or degrees (my vote goes to meters).

It's important to note that this unit display is READ ONLY, and users still cannot run a buffer in meters on a dataset in a geographic CRS. The reasons are all outlined in this thread: https://lists.osgeo.org/pipermail/qgis-developer/2017-March/047372.html

**Comment by nyalldawson** [comment]
I've reworked the warning icon to look smoother too:

nicer

**Comment by nirvn** [comment]
@nyalldawson , nice job. A few more algs could benefit from this:
- extent lines alg
- grid alg (i.e. grid spacing = distance)
- offset line alg
- segmentize by max distance alg

**Comment by nyalldawson** [comment]
@alexbruy how's this look to you?

**Review by alexbruy — APPROVED** [review]
Looks good to me.

**Pull request merged**
