### PR TITLE
Fix fill and select mixage

### PR DESCRIPTION
**Pull request by sbrunner**
Fix typo pointed here: https://github.com/qgis/QGIS/pull/2490#discussion_r47946428

### CODE REVIEW

**Comment by sbrunner** [comment]
Fix: http://hub.qgis.org/issues/14016

**Comment by m-kuhn** [comment]
git commit --amend

And add `Fix #14016` to the message :)

**Comment by sbrunner** [comment]
@m-kuhn done :-)

**Comment by dgoedkoop** [comment]
@sbrunner When you're at it, what about the line/pen color (and width) for the node tool rubber band?

**Comment by sbrunner** [comment]
@dgoedkoop Good idea, I just do it in a new commit :-)

**Comment by sbrunner** [comment]
Thanks @m-kuhn

**Comment by dgoedkoop** [comment]
@sbrunner Sorry to disturb again, but I've now been playing with the node tool a bit now that both our PR's have been merged, and I'm still not sure the result is 100% perfect.

The node tool has 2 rubber bands now. The line/pen style from the options is only applied to the old rubber band, which is shown while dragging a node. The brush/fill style from the options is only applied to the new rubber band, which is shown when not dragging / as a 'ghost' of the unedited geometry (depending on the option introduced in #2508).

(The normal digitizing rubber band has both the line and fill style from the options applied to it.)

To me it feels a bit random. I'd say that just only the node-dragging rubber band should follow both the line and fill style from the options, and the new rubber band should look differently. Or the other way around, I'm not exactly sure about that.

**Pull request merged**
