### PR TITLE
Container based Qt4 travis CI

### PR DESCRIPTION
**Pull request by m-kuhn**
Makes use of ccache to reduce build time to 10-20 minutes and avoid timeouts.

@nyalldawson do you have an idea about the failing tests? Seems they are related to you ;)

### CODE REVIEW

**Comment by m-kuhn** [comment]
@nyalldawson I conded the .cpp only template functions which caused binding and doc issues. The only thing to check is if the align raster differences look reasonable.

**Comment by m-kuhn** [comment]
Sorry @nyalldawson , seems you are not involved at all.

@wonder-sk any idea if the following highlights a problem?
I wonder if it's related to GDAL 2 (I get the same results on my machine)

```
119/203 Test #120: qgis_alignrastertest ....................***Failed    0.11 sec
********* Start testing of TestAlignRaster *********
Config: Using QTest library 4.8.1, Qt 4.8.1
QDEBUG : TestAlignRaster::initTestCase() Running from build directory!
QDEBUG : TestAlignRaster::initTestCase() - source directory: /home/travis/build/qgis/QGIS
QDEBUG : TestAlignRaster::initTestCase() - output directory of the build: /home/travis/build/qgis/QGIS/build/output
PASS   : TestAlignRaster::initTestCase()
PASS   : TestAlignRaster::testRasterInfo()
PASS   : TestAlignRaster::testClip()
PASS   : TestAlignRaster::testClipOutside()
PASS   : TestAlignRaster::testChangeGridOffsetNN()
PASS   : TestAlignRaster::testChangeGridOffsetBilinear()
PASS   : TestAlignRaster::testSmallerCellSize()
FAIL!  : TestAlignRaster::testBiggerCellSize() Compared doubles are not the same (fuzzy compare)
   Actual (out.identify( 106.2, -6.9 )): 10.8571
   Expected (11.5): 11.5
   Loc: [/home/travis/build/qgis/QGIS/tests/src/analysis/testqgsalignraster.cpp(182)]
FAIL!  : TestAlignRaster::testRescaleBiggerCellSize() Compared doubles are not the same (fuzzy compare)
   Actual (out.identify( 106.2, -6.4 )): 18.2857
   Expected (14.): 14
   Loc: [/home/travis/build/qgis/QGIS/tests/src/analysis/testqgsalignraster.cpp(204)]
PASS   : TestAlignRaster::testReprojectToOtherCRS()
ERROR 1: Too many points (441 out of 441) failed to transform,
unable to compute output bounds.
PASS   : TestAlignRaster::testInvalidReprojection()
PASS   : TestAlignRaster::testSuggestedReferenceLayer()
PASS   : TestAlignRaster::cleanupTestCase()
Totals: 11 passed, 2 failed, 0 skipped
********* Finished testing of TestAlignRaster *********
```

**Comment by rouault** [comment]
If testBiggerCellSize and testRescaleBiggerCellSize do down-sampling, yes it is expected that the result of GDAL 2 will be different (and more correct) than GDAL 1.X. In GDAL 1.X, bilinear was incorrectly only taking into account a 2x2 window of source pixels for each target pixel, whereas in 2.0 it takes a (2*scale_factor)*(2*scale_factor) window.

**Comment by nyalldawson** [comment]
@m-kuhn looks fantastic! My only concern is that like the qt5 builds we will lose the dart image display in cdash. This would be a big regression as we'd lose the ability to see why a rendering test is failing and have no way of fixing it!

I've asked on the cdash/cmake lists about this but those lists are FULL of unanswered questions, and the ctest/cdash docs are frankly terrible. I'm out of ideas on this one...

**Comment by m-kuhn** [comment]
@nyalldawson 
The rendering tests seem to work, see the [tests on the dash](http://dash.orfeo-toolbox.org/testDetails.php?test=39681395&build=224113)

Thanks for the potential fix, trying now

**Comment by nyalldawson** [comment]
@m-kuhn ah cool, so it's only the qt5 builds they are missing for? (or does it work now?). 

That commit should be safe to use... I only didn't merge it because it failed the qt4 travis build for some reason ;)

**Comment by m-kuhn** [comment]
Let's see how it does now. I'm trying to figure out what's going on with cdash and qt5

**Comment by m-kuhn** [comment]
Merged

**Comment by nyalldawson** [comment]
@m-kuhn seriously great work. Very much appreciated!!

**Pull request closed without merging**
