### PR TITLE
[mesh] [feature] 3Di support & fix mesh layer icon

### PR DESCRIPTION
**Pull request by PeterPetrik**
3Di format http://www.3di.nu/capabilities

- update MDAL to 0.0.7 (support for 3di format, bugfixes, projection in API)
- fix icon in browser panel for mesh layers

### CODE REVIEW

**Review by wonder-sk — APPROVED** [review]
I have already reviewed the MDAL code additions in the MDAL repository. The changes within QGIS code look good.

**Comment by nyalldawson** [comment]
I also had a quick look over this code and it looks good to me too!

**Comment by nyalldawson** [comment]
@wonder-sk @PeterPetrik do either of you build QGIS on windows using osgeo4w dependancies?  I always get a build error:

C:\OSGeo4W\bin\hdf5.dll:-1: error: LNK1107: invalid or corrupt file: cannot read at 0x2B0

and have to resort to just blunt force deleting all the hdf5 handling from src/providers/mdal/CMakeLists.txt . I'd love to know if there's some way to avoid this!

**Comment by PeterPetrik** [comment]
@nyalldawson you can simply do `-DWITH_HDF5=OFF` similar to https://github.com/lutraconsulting/MDAL/blob/master/.travis.yml#L39

**Comment by nirvn** [comment]
@PeterPetrik , ping (check your gitter :) )

**Pull request merged**
