### PR TITLE
QgsMapLayerModel: allow direct retrieval of map layer

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
The method `QgsMapLayerModel::roleNames` is only available for Qt5 and has bindings there. Travis still complains about missing bindings.

/**
 * @note not available in Python bindings
 */

Could be added to silence the warning, but it wouldn't be true.

@nyalldawson any idea?

**Comment by nyalldawson** [comment]
If you have a note with ANY mention of "python" in it the binding test will skip it. So you could say something like "available in Python if using Qt5 builds only", and it will be OK.

**Comment by m-kuhn** [comment]
I tried without success

    /**
     * Returns strings for all roles supported by this model.
     *
     * @note Available only with Qt5 (python and c++)
     */

https://github.com/qgis/QGIS/pull/2833/files#diff-ef30026d8c955a6605dbe05295fadcb0R67

Is it possible that the test/doxygen/something else has troubles caused by the #ifdef (The test message with `QgsMapLayerModel.@1` looks a bit strange)?

**Comment by m-kuhn** [comment]
@nyalldawson any chance that you could have a short look at this? I tried also with an `@cond` and `python` but I don't get the bindings checker to ignore this.

**Comment by nyalldawson** [comment]
@m-kuhn You'll need this commit: https://github.com/nyalldawson/QGIS/commit/d159998e74704909f9552fd77a19105fdc2c987e

There was two issues here:
- the enum had no name, that was causing the weird @1 member in the documentation (caused the sip test failure)
- the enum itself and the values were missing documentation strings (unrelated to the sip test failure)

With these changes the cond private stuff isn't required.

Hope that helps!

**Comment by m-kuhn** [comment]
ah, thanks a lot! was totally looking in the wrong place

**Comment by m-kuhn** [comment]
Manually merged

**Pull request closed without merging**
