### PR TITLE
Read qgz project when embedding layers/groups. Fixes #28280

### LINKED ISSUE #28280: Embedding layers does not work for projects saved as QGZ
Author Name: **A. Egberts** (A. Egberts)
Original Redmine Issue: [20460](https://issues.qgis.org/issues/20460)
Affected QGIS version: 3.7(master)
Redmine category:project_loading/saving

---
I try to embed a layer from a QGS file made in Qgis 3.14. layer is not loading, or not shown.
When I try to embed the same layer form a QGS file made with 2.18, I get that layer well!

What is going wrong?

---

- [Knipsel.JPG](https://issues.qgis.org/attachments/download/13743/Knipsel.JPG) (A. Egberts)

### PR DESCRIPTION
**Pull request by pblottiere**
Fixes https://github.com/qgis/QGIS/issues/28280

### CODE REVIEW

**Comment by nyalldawson** [comment]
Is this one ready for merge? Any chance of a unit test?

**Comment by pblottiere** [comment]
Hi @nyalldawson,

> Any chance of a unit test?

Yes, I take a look asap.

**Comment by nyalldawson** [comment]
Thanks @pblottiere -- would be great to get this one in 3.10.1!

**Review by nyalldawson — APPROVED** [review]
Just needs the indentation fix...

**Pull request merged**
