### PR TITLE
update MDAL to 0.6.91

### PR DESCRIPTION
**Pull request by PeterPetrik**

### CODE REVIEW

**Comment by nirvn** [comment]
Changelog?

**Comment by PeterPetrik** [comment]
> Changelog?

no this is just bugfix

**Comment by PeterPetrik** [comment]
note that this is already released in 3.14.1 release

**Review by wonder-sk — APPROVED** [review]

**Comment by PeterPetrik** [comment]
@nirvn 

I maybe misundestood, I thought you asking if it should go into QGIS changelog (label "changelog").
As for MDAL changes, this one fixes https://github.com/lutraconsulting/MDAL/issues/276

note that 0.x.9x releases are developlment releases, so there will always be a 0.x.0 release just before release of QGIS, with proper changelog of all fixed issues/enhancements done in MDAL between the production releases

**Comment by nirvn** [comment]
@PeterPetrik , I was indeed looking at what this MDAL upgrade was fixing :) thanks for the MDAL issue link.

**Pull request merged**
