### PR TITLE
in QgsFeatureFilterModel init the display expression when setting the layer

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Can you provide a description or link to an issue?

**Comment by 3nids** [comment]
When using a QgsFeatureListComboBox, I expect that the display expression is automatically set whenever I set the layer

**Comment by m-kuhn** [comment]
Can you move it up before the call to `reload()` and the signal?

**Comment by 3nids** [comment]
> Can you move it up before the call to reload() and the signal?

there is already a reload (but it's a timer) in the setDisplayExpression.
Also, I would expect that the layer change signal is emitted before the display expression change signal.

**Review by m-kuhn — APPROVED** [review]
ok

**Pull request merged**
