### PR TITLE
Constraint result not displayed in non editable mode

### PR DESCRIPTION
**Pull request by signedav**
- Constraint Result Indicator invisible when not in editable mode: The icon for the constraint result indicator cross/tipp disappears when not in editable mode. This is made by the new method setconstraintresult. 
- The background color on constraint fields reset on toggle edit: 
If editable, the backgroundcolor should be set according the constraint result. If not editable, the backgroundcolor should be empty anyway. So it has to be reseted when synchronizeEditableState.

image

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
I thought this was a desirable feature - in that it gave an indication of records which violate the constraints even in non-editing mode.

But @m-kuhn @3nids if you think this change is desirable than i'm happy with it -- you're our constraint/relation experts!

**Comment by andreasneumann** [comment]
@nyalldawson we don't think that it is desirable. All the other commercial GIS applications that I know only display such indicators in edit mode.

And fields that have constraints shouldn't have constraint violations anyway - when the table is not in edit mode.

**Comment by m-kuhn** [comment]
I was also 50/50 on this. I got used to think that it depends on the user in front if it's desirable or not.
If the user in front is actually in charge of maintaining the attribute values or doing reviews, it might be desirable.
If the user in front just wants to have a look at what's there, then it's a "not my focus right now" situation.

Being in edit mode is an indicator that the user is changing attribute values and interested in their validity. If we look at it this way, it should work for most of the users I guess.

**Comment by nyalldawson** [comment]
Ok, sounds reasonable to me!

**Comment by m-kuhn** [comment]
I think in the form embedded in the attribute table, the feature on a form can change when in readonly mode.
In such a scenario, I assume, the `editable` state needs to be cached and considered in `updateConstraintsWidget` or the constraints will suddenly reappear when changing the feature.

**Comment by signedav** [comment]
Made new commit with changes regarding the input of @m-kuhn

**Pull request merged**
