### PR TITLE
[DB Manager]Allow preset query combobox to expand

### LINKED ISSUE #17933: Tolerance (snapping) during analyses
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [9326](https://issues.qgis.org/issues/9326)

Redmine category:processing/qgis

---
In case of layers with essentially the same shapes, with different precision, the diff between these layers produces a number of virtually 0 width polygons.
These microareas are tricky and time consuming to remove (if they are isolated, a possible solution is to select and remove those smaller than an arbitrary threshold, but if they are linked to some "real" polygons, this will not work).

I suggest to add a parameter in analyses, to either snap original data within a threshold before running the analysis, or to clean up the results afterwards

### PR DESCRIPTION
**Pull request by DelazJ**
Fixes #17933
Also add some window title capitalisation and better align widgets
[needs-docs] because some GUI labels have changed

Before 
image
After
image

Questions:
1. Could we replace the "Load now!" label by "Load"?
1. The [DlgSqlLayerWindow.ui](https://github.com/qgis/QGIS/blob/c1cdfe860dcd5eace90f13a71f47ee15182eb79e/python/plugins/db_manager/ui/DlgSqlLayerWindow.ui/DlgSqlLayerWindow.ui) and [DlgSqlWindow.ui](https://github.com/qgis/QGIS/blob/c1cdfe860dcd5eace90f13a71f47ee15182eb79e/python/plugins/db_manager/ui/DlgSqlLayerWindow.ui/DlgSqlWindow.ui) files are almost the same (only a group container makes the difference). Any reason to not have a single file that we can reshape according to context or, maybe "easier/cleaner", two really different files ("with group container" vs content) that we import? It's weird to have to fix dialog twice. That said i couldn't find how to trigger DlgSqlLayerWindow dialog

### CODE REVIEW

**Comment by Gustry** [comment]
> Could we replace the "Load now!" label by "Load"?

Big big big plus 1 ! ;-) I'm always surprised to see this exclamation mark in a button! Thanks

> That said i couldn't find how to trigger DlgSqlLayerWindow dialog

Was it not when you update the SQL? With a quick look, I'm failing too this morning.

Side question, is-it not possible to use the QgsTaskManager on this SQL window? Some long running queries are blocking the UI and we can't cancel them. Or is-it the same problem with Python GIL and Python based algorithms in Processing? (cc @nyalldawson )

**Comment by nyalldawson** [comment]
@etiennesky 

> Side question, is-it not possible to use the QgsTaskManager on this SQL window? Some long running queries are blocking the UI and we can't cancel them. Or is-it the same problem with Python GIL and Python based algorithms in Processing? (cc @nyalldawson )

Should be fine now after https://github.com/qgis/QGIS/pull/6176. It may be an easy task to port this to a task, but I'm not sure if any of the dbmanager db plugins are thread safe....

**Comment by nirvn** [comment]
You could also rename the [ store ] button to [ save ], or rename the "saved query" to "stored query". I'd prefer the former.

**Comment by DelazJ** [comment]
Good catch @nirvn 
I think the PR is now ready!

**Comment by haubourg** [comment]
@Gustry  Hi, FYI @pblottiere is working on having dbmanager woork in a thread, with a magic "Cancel" button. The branch is here https://github.com/pblottiere/QGIS/tree/dbmanager_stop
We target 3.2 on behalf of French Ministry of ecology

**Comment by Gustry** [comment]
Wahou, what a news ! Having such a functionality will be awesome (like in PgAdmin)

**Comment by nyalldawson** [comment]
Cool, looks great! Love seeing task manager used in this way too!

**Comment by DelazJ** [comment]
Is there anything left to do here? Thanks.

**Pull request merged**
