### PR TITLE
Added a "path" tag to the "Lines to Polygons" processing algorithm. (qgsalgorithmpointstopaths.cpp)

### PR DESCRIPTION
**Pull request by MrChebur**
Added a "path" tag to the "Lines to Polygons" processing algorithm. (qgsalgorithmpointstopaths.cpp)

This change will allow finding this algorithm faster in the list of available algorithms (by analogy with the "Points to path" algorithm).

### CODE REVIEW

**Comment by uclaros** [comment]
What's the rationale behind typing `path` when searching for *Lines to Polygons*?

**Comment by MrChebur** [comment]
@uclaros 

Suppose we have the task of making a polygon out of points.
A non-English-speaking user can think of the following:

1. Convert points to lines using the "Points to path" tool (why this algorithm is called this way is a mystery to the non-English user, because the algorithm results in lines, not a path).

2. Now we need to turn a path (that's what we call it, right?) into polygons, but for some reason we don't find the "Path to polygons" algorithm in the toolbox (what a surprise).

**Comment by uclaros** [comment]
I really disagree with the term *path*, but you have a point there...
Hopefully in QGIS 4 we can get rid of the term *path* and use the proper term *line*!

**Comment by nyalldawson** [comment]
> I really disagree with the term path, but you have a point there...

Me too -- I always get confused trying to find this tool because of the non-standard "path" terminology!

**Review by nyalldawson — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
@MrChebur, it seems like this PR added the "path" tag to the "**Points to path**" (native:pointstopath) processing algorithm https://github.com/qgis/QGIS/blob/ad2a9c937b9c80a92caaceacb997538464dbd4b4/src/analysis/processing/qgsalgorithmpointstopaths.cpp#L48-L51 instead of the "**Lines to Polygons**" (qgis:linestopolygons) processing algorithm https://github.com/qgis/QGIS/blob/ad2a9c937b9c80a92caaceacb997538464dbd4b4/python/plugins/processing/algs/qgis/LinesToPolygons.py#L48-L57
Doesn't?

**Comment by MrChebur** [comment]
@agiudiceandrea Oh, my bad.

**Comment by agiudiceandrea** [comment]
@MrChebur, if you plan to file another PR in order to actually add the "path" tag to the "Lines to Polygons" algorithm, I would suggest to also remove the unnecessary "path" tag from the "Points to path" algorithm and to change the latter algorithm processing group from "Vector creation" to "Vector geometry" (like the "Lines to Polygons". "Polygons to lines" and "Extract vertices" algorithms).

**Pull request merged**
