### PR TITLE
[Qt6] Some test mask updates

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Review by nirvn — APPROVED** [review]
All masks appear sound, nothing visibly broken.

What's up with the expected_layoutscalerbar_textformat_mask.png and the huge white rectangle?

**Comment by nyalldawson** [comment]
@nirvn 

> What's up with the expected_layoutscalerbar_textformat_mask.png and the huge white rectangle?

Just a badly written test, with a huge unnecessary resampled raster layer in a map. It's not relevant for that actual test which is scalebar related.

**Review by nirvn — APPROVED** [review]
Can't spot any wrong in there.

**Comment by nyalldawson** [comment]
Unrelated test failure

**Pull request merged**
