### PR TITLE
Update server landing page sources

### PR DESCRIPTION
**Pull request by pathmapper**
## Description

- Replace Vue favicon with QGIS favicon from 
https://github.com/qgis/QGIS/blob/master/resources/server/api/ogc/static/landingpage/favicon.ico
- Remove assets folder with Vue logo
- Update sources url in static readme

### CODE REVIEW

**Comment by elpaso** [comment]
It looks like this PR only removes the old logos without adding the new ones.

**Comment by pathmapper** [comment]
The Vue favicon is replaced with the QGIS one, so there would be still a favicon after this PR:
https://raw.githubusercontent.com/qgis/QGIS/9dd5ad1a2b4c366c81f88bc047d8eb94e24ffc80/resources/server/src/landingpage/public/favicon.ico


Do we need a QGIS logo here?
https://github.com/qgis/QGIS/blob/master/resources/server/src/landingpage/src/assets/logo.png
For me it looks, like this one is not used anywhere but I might be missing something...

**Comment by elpaso** [comment]
No, it's fine actually, I was not looking a the right diff in the commit, forget my comment.

**Review by elpaso — APPROVED** [review]

**Comment by elpaso** [comment]
@pathmapper I'm very happy for your help on the landing page, I was the only contributor so far and I was feeling a little lonley :smile_cat:  

If you feel like spending more time on that, it would be nice to add print layout integration to the map browser. Also cmake build integration is something missing.

**Comment by roya0045** [comment]
@pathmapper Thanks for the contributions! Not everyone is at ease with server or web stuff, it's good to have more contributor familiar with that.

**Comment by pathmapper** [comment]
I'm a bit late here, thanks for your kind words @elpaso and @roya0045 :blush: 

> it would be nice to add print layout integration to the map browser. Also cmake build integration is something missing

:+1:  getting familiar with cmake is on my list.

**Pull request merged**
