### PR TITLE
Use reference rather than pointer for crs in QgsVectorFileWriter

### PR DESCRIPTION
**Pull request by nyalldawson**
Since QgsCoordinateReferenceSystem is implicitly shared, it's a safer approach. I'm going to try and remove all use of pointers to CRS objects. This change is also a prerequisite for changing QgsCoordinateTransform to implicitly shared.

I'm opening this as a PR for discussion, and also to discuss whether the included API break documentation is a suitable format for 3.0 api breaks.

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'd like to add an "api break" label, but seems I don't have permission to create new labels here...

**Comment by wonder-sk** [comment]
+1

It would be great to have a similar approach also with QgsCoordinateTransform class - instead of passing it as a pointer, it could be passed as a ref (with the possibility to have "no transform", so it is not necessary to check in the code whether the transforms are enabled or not).

**Comment by nyalldawson** [comment]
@wonder-sk that's what I'm moving toward, but there's a number of preliminary steps to get there

**Comment by nyalldawson** [comment]
Any objections if I merge?

**Comment by nyalldawson** [comment]
Manually pushed as fd42ed3

**Pull request closed without merging**
