### PR TITLE
Fix font dialog on OSX (https://issues.qgis.org/issues/20426)

### PR DESCRIPTION
**Pull request by iona5**
This PR fixes the broken font dialog on macOS in QGIS 3.4

on Qt5 (probably only 5.11.1 and .2) the QFontDialog is broken on macOS. There is already a check in place in QGIS to workaround a similar issue, but this check is also broken.

this PR restores the workaround which also applies here and fixes the bug.

see discussions in
- https://issues.qgis.org/issues/20426
- #8585 

upstream Qt bug:
  - https://bugreports.qt.io/browse/QTBUG-69878
  - https://successfulsoftware.net/2018/11/02/qt-is-broken-on-macos-right-now/

### CODE REVIEW

**Comment by PeterPetrik** [comment]
This patch works nicely. 

One thing (not sure if feature or bug or unrelated) is that the font should probably not be resized in the font description label?

screenshot 2018-12-04 at 13 51 45

**Review by PeterPetrik — APPROVED** [review]

**Comment by iona5** [comment]
@PeterPetrik, thanks for testing.

i just compared the button with the windows version, the problem is the inner padding on mac is larger, which does make it look extra weird. i guess nobody bothered to check on mac. ;)

i will make another PR for _that_ problem, as i am already there... :)

**Comment by PeterPetrik** [comment]
Thank you for solving these issues.

**Comment by PeterPetrik** [comment]
@iona5 maybe it would be good if you can backport this to LTR too.

**Comment by iona5** [comment]
sure.

i am not familiar with the workflow for backporting, would that be a new PR or is this done differently?

**Comment by PeterPetrik** [comment]
No problem, you need to make a new branch starting from "release-3_4" branch (not master). 
You apply your patch there and create a new PR with title starting with "[backport]" .

**Comment by nyalldawson** [comment]
@iona5 I've included a backport in https://github.com/qgis/QGIS/pull/8608

**Pull request merged**
