### PR TITLE
fix raster calculator widgets not expanding, vector layer digitizing geometry precision box truncating values

### PR DESCRIPTION
**Pull request by ViperMiniQ**
#58574 

Replaces old QgsScrollArea widget with QScrollArea to allow vertical scroll.
QScrollArea has grid layout for expanding widgets with the rest of the window.

#58351

Digitizing box still uses the same QLocale to show values, but instead of the default precision of 6, it now has a precision of 15. After 4 decimals, it changes to scientific notation, depending on the user set locale settings.
As the same object is used to convert values to and from, scientific notation is a valid representation, both for showing the actual values and for saving.

### CODE REVIEW

**Comment by nyalldawson** [comment]
> Replaces old QgsScrollArea widget with QScrollArea to allow vertical scroll.

Can you leave this as a QgsScrollArea, but just make the layout changes? QgsScrollArea has extra required fixes on top of the base QScrollArea class

**Comment by ViperMiniQ** [comment]
Hm, I tried, but I couldn't get it to scroll up and down once compiled. 
QScrollArea worked out of the box, but I'll look into finding the additional settings I need to adjust for QgsScrollArea, if that is the preferred option.

Or maybe I just missed something on the first try, will report later on it.

**Comment by ViperMiniQ** [comment]
Confirmed, I failed to include the header for the QgsAreaScroll and that's why it didn't work.
New commit changes QScrollArea to QgsScrollArea.

**Comment by nyalldawson** [comment]
Thanks!

Can you now split off the two unrelated fixes into separate PRs? Then they can each be reviewed and merged/backported individually.

**Comment by ViperMiniQ** [comment]
Thank you for the time and guidance! The two PRs are:

#58597
#58598

**Pull request closed without merging**
