### PR TITLE
Add odd integer constraint on neighborhood size in r.neighbors

### LINKED ISSUE #43707: Processing r.neighbors
Would be nice if user was given some notification that the size of the neighborhood needs to be odd prior to executing the tool.  Maybe to add in the description/help. Idea is to prevent user to fail to execute based on this fairly easy to overlook mistake

image

### PR DESCRIPTION
**Pull request by nicogodet**
## Description
Fixes #43707

This PR indicates to the user that the neighborhood size must be an odd integer and display a message box if the specified size is even preventing the user to run the alg.

image

### CODE REVIEW

**Review by alexbruy — APPROVED** [review]

**Comment by alexbruy** [comment]
Would be nice to have a test for this too.

**Comment by nicogodet** [comment]
image

Raw output of "Create test" from processing history:
```
  - algorithm: grass7:r.neighbors
    name: Test (grass7:r.neighbors)
    params:
      -a: false
      -c: false
      GRASS_RASTER_FORMAT_META: ''
      GRASS_RASTER_FORMAT_OPT: ''
      GRASS_REGION_CELLSIZE_PARAMETER: 0.0
      input:
        name: custom/grass7/float_raster.tif
        type: raster
      method: 0
      quantile: ''
      size: 3
      weight:
        location: '[The source data is not in the testdata directory. Please use data
          in the processing/tests/testdata folder.]'
        name: ''
        type: file
    results:
      output:
        hash: 7e78e8b556c9a39e07b2bf8edbd45c17fbd1897de974c52bc97009a8
        type: rasterhash
```

**Comment by nicogodet** [comment]
@alexbruy By test, you meant the test for r.neighbors that was missing or the test for this new "feature" ?
I look at other grass tests and I'm not sure I can add a fail test in the yaml. If it can be done somewhere else, could you give the correct file to add the test in ?

**Comment by alexbruy** [comment]
@nicogodet having simple test is nice, but you are right that it is good to have a test for this specific change (only odd values are valid) as well. It can be added for example to [Grass7AlgorithmsRasterTestPt1.py](https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/Grass7AlgorithmsRasterTestPt1.py)

**Comment by nicogodet** [comment]
@alexbruy Is that enough ?

BTW I learnt a lot doing this 😃

**Pull request merged**
