### PR TITLE
Fix rubberband refresh

### PR DESCRIPTION
**Pull request by strk**
See #12392.
Lacks a testcase.

### CODE REVIEW

**Comment by strk** [comment]
I meant see http://hub.qgis.org/issues/12392

**Comment by strk** [comment]
In trying to write a test for boundingRect I started from 2.6 and set expected results.
But I'm not sure those results gotten from 2.6 are correct:
```
void TestQgsRubberband::testBoundingRect()                                      
{                                                                               
  // Output size by default is 638, 478 (1 pixel border)                        
  mCanvas->setExtent( QgsRectangle( 0.0, 0.0, 638.0, 478.0 ) );                 
  QCOMPARE( mCanvas->mapUnitsPerPixel (), 1.0 );                                
                                                                                
  // Polygon extent is 10,10 to 30,30                                           
  QSharedPointer<QgsGeometry> geom( QgsGeometry::fromWkt(                       
      "POLYGON((10 10,10 30,30 30,30 10,10 10))"                                
  ) );                                                                          
  mRubberband = new QgsRubberBand( mCanvas, mPolygonLayer->geometryType() );    
  mRubberband->addGeometry( geom.data(), mPolygonLayer );                       
                                                                                
  // XXX why is this a 28x28 rectangle for a 20x20 extent at 1:1 scale ?
  QCOMPARE( mRubberband->boundingRect(), QRectF(QPointF(-1,-1),QSizeF(28,28)) );
  // XXX why is it anchored at 445 ? That's 38 pixel from bottom ...
  QCOMPARE( mRubberband->pos(), QPointF(7,445) );                               
                                                                                
  mCanvas->zoomIn();                                                            
                                                                                
  QCOMPARE( mRubberband->boundingRect(), QRectF(QPointF(-1,-1),QSizeF(54,54)) );
  QCOMPARE( mRubberband->pos(), QPointF(-305,651) );                            
}                       
```

**Comment by strk** [comment]
Alright, after cherry-picking @naihil fix to rect initialization the testcase I tested against 2.6 only fails after the zoomIn, which may be due to a different default zoom in factor (to be checked)

**Comment by strk** [comment]
The failure:
``
   Actual (mRubberband->boundingRect()): QRectF(-1,-1 48x48) (bottomright 47,47)
   Expected (QRectF(QPointF(-1,-1),QSizeF(54,54))): QRectF(-1,-1 54x54) (bottomright 53,53)
``

**Comment by strk** [comment]
The difference isn't due to different zoom factor, confirmed after changing the call to zoomByFactor(0.5). Must be something else (line tickness?)

**Comment by naihil** [comment]
QPointF is a floating point. Maybe try compare with qgsDoubleNear()?

**Comment by strk** [comment]
I'm actually thinking that 2.6 was bogus because at scale 1:1 we should have 20x20 as the extent, so since we get 28x28 instead we should assume that icon size + pen width gives 4 (per side = 8).
If that's correct, at scale 2:1 we should have 40x40 as the extent which becomes 48x48 (as obtained now) once pen size and icon width are added.

Getting 54x54, as happens in 2.6, would mean that pen/icon sizes changed with scale,
although 54 would be 14 (rather than 16) pixels bigger than expected geometry size (40x40).

**Comment by strk** [comment]
speaking of which... I'm seeing (in 2.6) that calling setWidth and setIconSize do not re-compute rectangle (another old bug...)

**Comment by strk** [comment]
Test pushed, I think we're good to go here. Please run a final test (once Travis is happy).

**Comment by strk** [comment]
Uhm, I just realized setRect _expects_ a "rectangle" in map units (not pixels) so 2.6 was right about scaling pen/icon width... Will fix that (and correct test to expect the same results as 2.6)

**Comment by strk** [comment]
Still, 8 pixels at scale 1:1 should be 16 at 2:1, not 14... that part is still not clear

**Comment by strk** [comment]
@naihil my time on this is over for today, maybe you can look at adding a failing test to your initially reported python snippet for the python console ? Something about setting a pen width (RubberBand->setWidth) and not getting proper refreshes at the borders ?

**Comment by strk** [comment]
Found: QgsMapCanvasItem always adds 2 pixels to the size, so pen+icon size is really 6 at 1:1 and 12 at 2:1, which become 8 and 14 (as found by 2.6). I really think all this should be cleaned up one day, but for the sake of stability I'd get to 2.6 compatibility for the 2.8 branch first.

**Comment by strk** [comment]
There, full compatibility now.

**Comment by strk** [comment]
Gah, scale is not 1:1 on travis:
https://travis-ci.org/qgis/QGIS/builds/56592329#L1215

I keep wondering how to set output size correctly, drives me nuts

**Comment by naihil** [comment]
You can try mCanvas->resize(w, h)

**Comment by strk** [comment]
I'll check assumption first, with a new commit checking outputSize.

**Comment by strk** [comment]
https://travis-ci.org/qgis/QGIS/builds/56602314#L1215-L1216
See, for some reason Travis has the Canvas size set to 636x476 rather than 638x478.
That's a 2 pixels border rather than 1 pixel border from 640x480 ...

I'll set the extent == the canvas size to tolerate any such difference.

**Comment by strk** [comment]
Now position is slightly different (probably due to the same problem):
https://travis-ci.org/qgis/QGIS/builds/56682389#L1214-L1216

NOTE: I did try mCanvas->resize(w,h) but it did not really change the size...

**Comment by strk** [comment]
I suspect travis-detected one is a real bug as there are assumptions in the code about window border being 1 pixel. For example here: https://github.com/qgis/QGIS/blob/final-2_8_1/src/gui/qgsmapcanvasitem.cpp#L111

**Comment by strk** [comment]
Extent of RubberBand is 10,10:30:30, we expect position to be 7,445, let's find out why.
Lower X would be 10-3 for pen & icon = 7;
Lower Y would be canvas_height - 30 - 3 for pen & icon. That's 478-30-3=445 on my system while it is 476-30-3=443 on Travis. Makes sense (kind of...)

**Comment by strk** [comment]
Pushed to master as:
d43d8bf59730ee2911dd141ef0bb5847e7b56d73
84d47c9cf020b0c038e1a371ea6efc52de2d4474
a844bfa17490391bcfac54700ace76afbeac90f0

**Pull request closed without merging**
