### PR TITLE
Show style name in layer properties dialog title

### PR DESCRIPTION
**Pull request by m-kuhn**
image

### CODE REVIEW

**Comment by Gustry** [comment]
Nice. Why not the same behavior for raster layer?

**Comment by m-kuhn** [comment]
Because I don't use different styles with raster layers :D

**Comment by m-kuhn** [comment]
@Gustry done

**Comment by Gustry** [comment]
Thanks ;-)

**Comment by nirvn** [comment]
@m-kuhn , can we merge this?

**Comment by DelazJ** [comment]
Is this information also shown somehow in the layer styling panel ( see https://issues.qgis.org/issues/17829  )?

**Comment by m-kuhn** [comment]
> Is this information also shown somehow in the layer styling panel ( see https://issues.qgis.org/issues/17829 )?

Not with this PR

**Comment by nirvn** [comment]
@m-kuhn , thanks.

**Pull request merged**
