### PR TITLE
clean up SVG files from unnecessary data

### PR DESCRIPTION
**Pull request by alexbruy**
This PR cleans all SVG files inside `images` directory with [svgcleaner](https://github.com/RazrFalcon/svgcleaner) tool. After cleanup folder size reduced from 44 Mb to 35 Mb.

### CODE REVIEW

**Comment by nirvn** [comment]
@alexbruy , nice. It appears the cleaning of the bundled svg image markers has resulted in slightly different rendering, mask for a couple of test images will need to be updated. 

It'd be great to graph out the speed gains in a/ app startup (assuming smaller SVG files = quicker read = quicker startup) as well as b/ drawing of svg list widget.

**Comment by nyalldawson** [comment]
Just a thought - have you checked that this doesn't affect the paramaterised svgs? Afaik param is not officially part of the svg spec.

**Comment by nirvn** [comment]
@nyalldawson , good point. It occurred to me yesterday then slipped off my mind. 

Looking at one random file, it seems to be fine: https://github.com/qgis/QGIS/pull/3861/files#diff-e71b3e6d7f5804ff19d2771beb1def33R2

**Comment by alexbruy** [comment]
> It'd be great to graph out the speed gains in a/ app startup (assuming smaller SVG files = quicker read = quicker startup) as well as b/ drawing of svg list widget.

@nirvn will look if I can come with something.

> Just a thought - have you checked that this doesn't affect the paramaterised svgs? 

@nyalldawson I'm aware about paramaterised svgs and this case was handled during clean up. All QGIS specific parameters were kept. I tested few random files after cleanup and seems all fine.

**Comment by alexbruy** [comment]
@nirvn according to built-in profiler, app startup time decreased to about 40-50%. Regarding SVG list widget, all my measurements give almost the same results in both cases (before and after).

**Comment by nirvn** [comment]
@alexbruy , cool. Looking at your PR, the app startup test time is 12.4 sec, while master app startup test averages at 16.3 sec. That's pretty cool.

**Comment by NathanW2** [comment]
Woot for built-in profiler, knew it would come in handy one day.

On Thu, Dec 15, 2016 at 11:18 AM, Mathieu Pellerin <notifications@github.com

**Comment by alexbruy** [comment]
Any objections to merge it?

**Comment by nirvn** [comment]
No, go ahead.

**Pull request merged**
