### PR TITLE
FindQGIS.cmake updates

### PR DESCRIPTION
**Pull request by dakcarto**
Various updates to `FindQGIS.cmake` module:

* Support for OSGeo4W subdirectories `qgis[-rel|-ltr][-dev]`, in `OSGEO4W_ROOT/apps/`
* Support for any macOS QGIS.app bundle, located anywhere on disk
* Add QGIS_UI_INCLUDE_DIR output variable for location of `ui_*` headers
* Preliminary (macOS-only) support for finding QGIS in its build directory
* Document some variables

**Discussion points**

* Could place all macOS searches in a totally separate APPLE section, instead of mixed with UNIX
* Missing Win and Linux support for QGIS_BUILD_PATH can be added, though I think this will require an additional variable for QGIS_SRC_PATH to find the headers.

These fixes came about after considerable work to get out-of-source builds for authentication method C++ plugins.

### CODE REVIEW

**Comment by dakcarto** [comment]
I cancelled Travis CI build, as it was unnecessary. At least, I don't think there are any tests for `FindQGIS.cmake`.

**Comment by dakcarto** [comment]
Hmm. May not need extra QGIS_SRC_PATH defined, if `${QGIS_BUILD_PATH}/output/bin/qgisbuildpath.txt` exists and is parsed, as it contains both paths.

**Comment by m-kuhn** [comment]
> I cancelled Travis CI build, as it was unnecessary. At least, I don't think there are any tests for FindQGIS.cmake

Travis sometimes still finds some side-effects. I only cancel the builds when I know that I have pushed an update to a branch and am no longer interested in the result of an outdated code. It has pointed me towards unexpected problems more than just once.

**Comment by dakcarto** [comment]
Ok, thanks. Restarted Travis build.

**Comment by dakcarto** [comment]
Any further comments on this work? @jef-n, does this make sense for OSGeo4W (works for me here)?

**Pull request merged**
