### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell`  
Again, apologize for not using the correct script to run before pushing a PR. I can't seem to get it to work.

### CODE REVIEW

**Comment by luzpaz** [comment]
Also pushed another commit (b5f30ec) that contains source typos, please review closely

**Comment by nyalldawson** [comment]
Nice work!

Note the there's also https://github.com/qgis/QGIS/blob/master/scripts/spell_check/spelling.dat 

If you add these errors to that file, they'll automatically be flagged by the CI if they occur again.

**Comment by luzpaz** [comment]
@nyalldawson I think qgis should stay in parity with 
https://github.com/lucasdemarchi/codespell/blob/master/codespell_lib/data/dictionary.txt

**Comment by nyalldawson** [comment]
Superseded by #6947

**Pull request closed without merging**
