### PR TITLE
Fix compilation with QT 5.15

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

Backport of https://github.com/qgis/QGIS/pull/37116

### CODE REVIEW

**Comment by pblottiere** [comment]
This PR should fixed your issue on 3.10 @rduivenvoorde.

**Comment by rduivenvoorde** [comment]
building this pr

**Comment by rduivenvoorde** [comment]
Ok (for me) this fixes my build problem. Thanks!!



QGIS version | 3.10.6-A Coruña | QGIS code revision | adb616f910
-- | -- | -- | --
Compiled against Qt | 5.12.5 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 3.1.0 | Running against GDAL/OGR | 3.1.0
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.3 (Debian 12.3-1+b1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.0.1 | Running against PROJ | Rel. 7.0.1, May 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid | This copy of QGIS writes debugging output.

**Comment by pblottiere** [comment]
> Ok (for me) this fixes my build problem. Thanks!!

Good news :). Thanks for testing Richard :+1:

**Review by nyalldawson — APPROVED** [review]

**Comment by sebastic** [comment]
Applying this to the 3.10.6 Debian package still fails to build:
```
usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::init()':
./debian/build/../../src/python/qgspythonutilsimpl.cpp:157: undefined reference to `Py_Initialize'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:159: undefined reference to `PyEval_InitThreads'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:163: undefined reference to `PyImport_AddModule'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:164: undefined reference to `PyModule_GetDict'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::finish()':
./debian/build/../../src/python/qgspythonutilsimpl.cpp:174: undefined reference to `PyEval_SaveThread'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::getTraceback()':
./debian/build/../../src/python/qgspythonutilsimpl.cpp:372: undefined reference to `PyErr_Fetch'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:373: undefined reference to `PyErr_NormalizeException'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:377: undefined reference to `PyImport_ImportModule'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:381: undefined reference to `PyObject_CallMethod'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:387: undefined reference to `PyImport_ImportModule'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:394: undefined reference to `_Py_NoneStruct'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:391: undefined reference to `PyObject_CallMethod'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:403: undefined reference to `PyObject_CallMethod'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:411: undefined reference to `PyUnicode_AsUTF8'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::getTraceback()':
/usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/bin/ld: /usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/bin/ld: /usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/bin/ld: /usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/bin/ld: /usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o:/usr/include/python3.8/object.h:478: more undefined references to `_Py_Dealloc' follow
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::runStringUnsafe(QString const&, bool)':
./debian/build/../../src/python/qgspythonutilsimpl.cpp:301: undefined reference to `PyGILState_Ensure'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:307: undefined reference to `PyRun_StringFlags'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:308: undefined reference to `PyErr_Occurred'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:316: undefined reference to `PyGILState_Release'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::runStringUnsafe(QString const&, bool)':
/usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::PyObjectToQString(_object*)':
./debian/build/../../src/python/qgspythonutilsimpl.cpp:496: undefined reference to `_Py_NoneStruct'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:504: undefined reference to `PyUnicode_AsUTF8'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:509: undefined reference to `PyObject_Str'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:512: undefined reference to `PyUnicode_AsUTF8'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::PyObjectToQString(_object*)':
/usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::getError(QString&, QString&)':
./debian/build/../../src/python/qgspythonutilsimpl.cpp:453: undefined reference to `PyGILState_Ensure'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:455: undefined reference to `PyErr_Occurred'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:466: undefined reference to `PyErr_Fetch'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:472: undefined reference to `_Py_NoneStruct'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:485: undefined reference to `PyGILState_Release'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::getError(QString&, QString&)':
/usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/bin/ld: /usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/bin/ld: /usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::getError(QString&, QString&)':
./debian/build/../../src/python/qgspythonutilsimpl.cpp:457: undefined reference to `PyGILState_Release'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::evalString(QString const&, QString&)':
./debian/build/../../src/python/qgspythonutilsimpl.cpp:527: undefined reference to `PyGILState_Ensure'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:529: undefined reference to `PyRun_StringFlags'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::evalString(QString const&, QString&)':
/usr/include/python3.8/object.h:478: undefined reference to `_Py_Dealloc'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::evalString(QString const&, QString&)':
./debian/build/../../src/python/qgspythonutilsimpl.cpp:540: undefined reference to `PyGILState_Release'
/usr/bin/ld: src/python/CMakeFiles/qgispython.dir/qgspythonutilsimpl.cpp.o: in function `QgsPythonUtilsImpl::finish()':
./debian/build/../../src/python/qgspythonutilsimpl.cpp:174: undefined reference to `PyEval_SaveThread'
/usr/bin/ld: ./debian/build/../../src/python/qgspythonutilsimpl.cpp:174: undefined reference to `PyEval_SaveThread'
collect2: error: ld returned 1 exit status
```

**Comment by rduivenvoorde** [comment]
@sebastic @jef-n this is not about compilation no? 

Because I can really compile/install in a Buster VM (I just tested again).

So this is about the packaging? In  which the newer make is creating havoc with '#''s?

**Comment by sebastic** [comment]
@rduivenvoorde, it is about compilation of the Debian package.

make-dfsg (>= 4.3-1) is only in unstable, not buster nor bullseye, see:

 https://tracker.debian.org/pkg/make-dfsg

To make the qgis package build successfully in a Debian unstable environment I needed both the changes from this PR and the `PYTHON_LIBRARY` changes, see:

 https://salsa.debian.org/debian-gis-team/qgis/-/commits/debian/3.10.6+dfsg-1

**Comment by buzo-ffm** [comment]
Still does not build on Arch Linux.
* `#include <QPainterPath>` is missing in a few places and
* I don't know how to handle this error:
```
[  0%] Building /build/qgis-ltr/src/build/doc/INSTALL from /build/qgis-ltr/src/qgis-3.10.6/doc/INSTALL.t2t
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/txt2tags.py", line 2026, in parse
    opts, args = getopt.getopt(cmdline, short, long_)
  File "/usr/lib/python3.8/getopt.py", line 93, in getopt
    opts, args = do_longs(opts, args[0][2:], longopts, args[1:])
  File "/usr/lib/python3.8/getopt.py", line 157, in do_longs
    has_arg, opt = long_has_args(opt, longopts)
  File "/usr/lib/python3.8/getopt.py", line 174, in long_has_args
    raise GetoptError(_('option --%s not recognized') % opt, opt)
getopt.GetoptError: option --toc-level not recognized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/txt2tags", line 11, in <module>
    load_entry_point('txt2tags==3.7', 'console_scripts', 'txt2tags')()
  File "/usr/lib/python3.8/site-packages/txt2tags.py", line 4865, in exec_command_line
    config, doc = process_source_file(infile)
  File "/usr/lib/python3.8/site-packages/txt2tags.py", line 4205, in process_source_file
    full_parsed = ConfigMaster(full_raw).parse()
  File "/usr/lib/python3.8/site-packages/txt2tags.py", line 2449, in parse
    self.add(key, value)
  File "/usr/lib/python3.8/site-packages/txt2tags.py", line 2338, in add
    raw_opts = CommandLine().get_raw_config(val, ignore=ignoreme)
  File "/usr/lib/python3.8/site-packages/txt2tags.py", line 2046, in get_raw_config
    options, arguments = self.parse(cmdline[:])
  File "/usr/lib/python3.8/site-packages/txt2tags.py", line 2028, in parse
    Error("%s (try --help)" % errmsg)
  File "/usr/lib/python3.8/site-packages/txt2tags.py", line 1833, in Error
    raise error(msg)
txt2tags.error: txt2tags: Error: option --toc-level not recognized (try --help)
make[2]: *** [doc/CMakeFiles/t2tdoc.dir/build.make:84: doc/INSTALL] Error 1
```

**Comment by sebastic** [comment]
@buzo-ffm, 

You'll need to patch `doc/INSTALL.t2t` & `doc/news.t2t` for this change in [txt2tags 3.7](https://github.com/txt2tags/txt2tags/releases/tag/3.7):
> * Remove `--toc-only` and `--toc-level` options (Jendrik Seipp).

**Comment by pblottiere** [comment]
Hi @buzo-ffm,

> Still does not build on Arch Linux.
> #include <QPainterPath> is missing in a few places and

Ah? I'm also on Arch and the compilation is OK here. My last upgrade is 1 week old, I take a look in the coming days.

**Comment by buzo-ffm** [comment]
@sebastic: Thanks, that worked.

@pblottiere: Nice, I am maintaining the [qgis-ltr package on Arch](https://aur.archlinux.org/packages/qgis-ltr/). You can find the includes which I added to fix the build [here](https://aur.archlinux.org/cgit/aur.git/diff/include-QPainterPath.patch?h=qgis-ltr&id=44222ab6377ac72b396ae4997b4327220eb0d99d).

**Comment by rduivenvoorde** [comment]
@pblottiere @sebastic @buzo-ffm Great cooperation!! Thanks for all these efforts!!

**Comment by rduivenvoorde** [comment]
Mmm, now 3.12 also fails with the same error... 
3.14 still not release ;-) 
Should we backport this to 3.12 too?

**Comment by pblottiere** [comment]
Hi @buzo-ffm,

> Still does not build on Arch Linux.

> #include <QPainterPath> is missing in a few places and

Strange, it still build without complaints even after my last upgrade. I don't think it will help but can you give me your `CMakeCache.txt` please? I'm curious :).

**Comment by pblottiere** [comment]
@rduivenvoorde 

> 3.14 still not release ;-)

Yes it is :).

**Pull request merged**
