### PR TITLE
Allow provider-level filtering on layers with joined fields

### PR DESCRIPTION
**Pull request by mhugo**

### CODE REVIEW

**Comment by mhugo** [comment]
Hi, is it possible to apply this patch ? It is very simple and other users seem interested (at least @olivierdalang)

**Comment by m-kuhn** [comment]
Can you describe what exactly it does and what the use-case is. That way it will be much easier to review and merge it.
Thank you.

**Comment by mhugo** [comment]
Hi. The use case is to allow to filter layers that have joins defined (on fields of the primary table at least).

The current state is inconsistent : a filter can be set through the "Layer" / "Query" menu, but is disabled from the right click "Filter" menu. And it also list joined fields that the provider is not aware of.

So the patch fix this : the QgsQueryBuilder do not list joined fields anymore and the filtering stay enabled if the layer has joins.

**Comment by m-kuhn** [comment]
Ah, filter as in subset string :)
Thank you, merged

**Comment by mhugo** [comment]
Thanks @m-kuhn !

**Comment by mhugo** [comment]
Yes sorry, subset string :)

**Pull request merged**
