### PR TITLE
Add external qt-unix-signals library

### PR DESCRIPTION
**Pull request by nyalldawson**
This library, original taken from https://github.com/sijk/qt-unix-signals (but a maintained fork exists at https://github.com/nyalldawson/qt-unix-signals), handles unix signal watching using the Qt libraries.

It allows for detection of signals like SIGINT and SIGTERM, and allows Qt applications to respond gracefully to these.

Included in external libraries for use in QGIS terminal applications.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Looks interesting.
Why not use them in the main application?

**Comment by nyalldawson** [comment]
@m-kuhn I'm planning to investigate that too

**Comment by m-kuhn** [comment]
Would be great to actually use the library before it's merged :)

**Comment by nyalldawson** [comment]
@m-kuhn it's used here -- https://github.com/nyalldawson/QGIS/blob/transform_tool/src/transform/qgstransform.cpp#L396

I'm trying to "drip feed" the parts of that branch in modular PRs to avoid a mega PR.

**Comment by m-kuhn** [comment]
> I'm trying to "drip feed" the parts of that branch in modular PRs to avoid a mega PR.

I like that :+1: 

Are there other, self-contained parts that can go first? 

What I am trying to minimize is the risk that after this merge we are left with this code but somehow the rest of the PR fails (because you find another better approach for the transform_tool, because you get hit by a bus or you decide that open source sucks and get a job at ESRI and abandon this PR, ...)

If this is the best way however, go ahead!

**Comment by nyalldawson** [comment]
@m-kuhn I've now enabled termination of the main QGIS app via sigint -- works well on Linux, I'll test on other platforms (win) after merge

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
