### PR TITLE
Add methods to QgsVectorColorRamp for directly retrieving QRgb values

### PR DESCRIPTION
**Pull request by nyalldawson**
Speeds up the shapeburst renderer by ~15%

### CODE REVIEW

**Comment by nyalldawson** [comment]
@wonder-sk mind reviewing this for me?

**Comment by wonder-sk** [comment]
Hi Nyall, the code looks good to me.
The only suggestion would be to have body of gradient color ramp's color() and rgb() implemented with (inline) template function which would be used by color() and rgb(). This would avoid the duplicated code (and leave that for compiler).

**Comment by nyalldawson** [comment]
@wonder-sk there's a version using templates here : https://github.com/nyalldawson/QGIS/compare/ramp_rgb2 . However, it's considerably slower than this implementation... do you have any idea why this would be the case?

**Comment by wonder-sk** [comment]
If you are running debug version then the template functions did not get inlined. I remember seeing great performance difference difference between debug and release with heavily templated code.

Also, maybe it is not necessary to have the templates as members of the class - they could be just defined in the .cpp file?

**Comment by nyalldawson** [comment]
turns out after testing a non-debug build that the speed difference was negligible. There seems little point complicating the code for such minimal results, so I'll close this.

**Pull request closed without merging**
