### PR TITLE
Fix WMS GetMap 8bit mode with transparency

### PR DESCRIPTION
**Pull request by troopa81**
## Description

There is some rendering problem on WMS GetMap when using `mode=8bit` with transparency. 

| before fix | after fix | on QGIS desktop |
| --- | --- | ---- |
| label_8bit_bug | label_8bit_nobug | on_qgis

This is because rendering is made with format  `QImage::Format_ARGB32_Premultiplied` and so we compute the color table with this format. But in this format, R,G,B value are multiplied with alpha and differs from their original value. And so, the resulting color table misses some colors.

This PR fixes this.

There is a problem with 8bits image testing. Indeed when we compare image, we compare QRgb [colors](https://github.com/qgis/QGIS/blob/a0f6ee7541f609c409551b8c9dbd5f5ab117f156/src/core/qgsrenderchecker.cpp#L402) , but the `constScanLine` methods returns color table indexes and not QRgb color when we have a 8 bits image. The issue exists for existing 8 bits test and we deal it with mask (that's why there is bottom white pixels in [mask](https://github.com/qgis/QGIS/blob/master/tests/testdata/control_images/qgis_server/WMS_GetMap_Mode_8bit/WMS_GetMap_Mode_8bit_mask.png) ).

I can fix this in this in this PR, or in another one, or continue dealing with mask. Any opinion?

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rldhont** [comment]
Thanks to work on it.

**Comment by troopa81** [comment]
> I can fix this in this in this PR, or in another one, or continue dealing with mask. Any opinion?

I finally choose to correct it in this PR, so the CI could work

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
@troopa81 do you want to fixup some commits (indentation and empty line) before merging ?

**Comment by troopa81** [comment]
> @troopa81 do you want to fixup some commits (indentation and empty line) before merging ?

@rldhont No that's ok, let's merge! Is it possible to squash and merge like it is described [here](https://github.blog/2016-04-01-squash-your-commits/) ? Is it what the label `Squash!` means?

**Comment by rldhont** [comment]
I have squashed and merged it. You probably have to manually backport.

**Comment by troopa81** [comment]
Thanks @rldhont , I fill backport this manually

**Pull request merged**
