### PR TITLE
[Bug] Don't impose format on arc map layer from browser

### LINKED ISSUE #41126: Transparency problem with no-data pixels in ArcGIS MapServer layer
We have been publishing ArcGIS Server map services since 2009.  It is important to us that our users have quality open source GIS software to access our map services.

**Bug Description**

No-data pixels in an ArcGIS Image service are not transparent.  The problem with the no-data pixels is dependant upon the method used to add the ArcGIS Image Service to the QGIS project.  Both methods *should* give the same result but they don’t.  Method 1 below will produce **opaque** no-data pixels.  Method 2 will produce **transparent** no-data pixels.

**How to Reproduce**
*METHOD 1*

1. Layer > Add Layer > Add ArcGIS MapServer Layer
2. Click the “New” Server connection button
3. Provide a Name for the connection and provide a URL.  **Use the URL for the root of the ArcGIS Server REST services**, e.g., [https://geonb.snb.ca/image/rest/services/](https://geonb.snb.ca/image/rest/services/)
4. Click the OK button to close the “Create a New ARCGISMAPSERVER Connection” dialogue box
5. Click the “Add” button in the Data Source Manager window.  An “ArcGISMapServer” item will appear in the Browser Pane:
qgis_browser_pane
6. Expand the ArcGISMapServer item to expose the desired MapServer layer:
qgis_browser_pane2
7.	Drag and drop the ArcGISMapServer layer onto the map.  The no-data pixels are opaque:
qgis_opaque_nodata
The layer properties show **format=’jpg’**.  JPEG does not support transparency:
qgis_layer_properties1

*METHOD 2*
1.	Layer > Add Layer > Add ArcGIS MapServer Layer
2.	Click the “New” Server connection button
3.	Provide a Name for the connection and provide a URL.  **Use the full URL for the desired Image Service**, e.g., [https://geonb.snb.ca/image/rest/services/Elevation/DEM_Hillshade_Multi_MNE_Ombrage_Multiple/ImageServer/](https://geonb.snb.ca/image/rest/services/Elevation/DEM_Hillshade_Multi_MNE_Ombrage_Multiple/ImageServer/) 
4.	Click the OK button to close the “Create a New ARCGISMAPSERVER Connection” dialogue box
5.	Click the “Add” button in the Data Source Manager window.  The new Image Service will be added to the map.  The no-data pixels are transparent:
qgis_transparent_nodata
The layer properties show **format=’’**. I presume this will allow ArcGIS Image server to return the default image format. The default format is “jpgpng”.  This format returns a JPG if there are no transparent pixels in the requested extent; otherwise, it returns a PNG (png32):
qgis_layer_properties2 png

**Summary**

- Method 2 correctly displays the transparent no-data pixels
- Method 1 returns opaque no-data pixels but will be far more convenient for users that will need to add many layers from our ArcGIS Servers.  
- Both methods should return the same results.

I am not a programmer but it seems to me this should be a very easy fix.  The API request that is sent to ArcGIS Server needs to be modified so the returned image is not in the JPG format.  If the "&format=" parameter is ommitted the default image format will provide transparency for nodata pixels.  [ArcGIS REST API Reference for "exportImage"](https://geonb.snb.ca/image/sdk/rest/index.html#//02ss00000075000000). 

**QGIS and OS versions**

- QGIS version - 3.10.13-A Coruña but also seen in 3.16
- Microsoft Windows 10 Enterprise, 64-bit

### PR DESCRIPTION
**Pull request by roya0045**
## Description

Fixes #41126 

Now, @elpaso I'm not sure if you are the one most familiar with this provider, but is there any downsides to not coercing and output format when making a request? It may be mandatory for WMS but for esri servers it seems to optimised the output or use any one. Which seems like a fine solution.

I tried to find a better way but the URI related code is all over the place and this was the easiest solution I could find.

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'll look at this one when I'm back from leave 👍

**Comment by roya0045** [comment]
@nyalldawson Sure thing Nyall! Enjoy yourself on leave and stop looking at your notifications!

**Comment by nyalldawson** [comment]
https://github.com/qgis/QGIS/pull/41253 supersedes this -- I've gone with a slightly different approach to ensure that we always have a valid list of supported formats available for the layer items

**Comment by roya0045** [comment]
@nyalldawson I knew you'd come up with a better approach!

**Comment by nyalldawson** [comment]
@roya0045 it's nothing personal -- it's just that I've dug into ArcMap services waaaaaaay more than I ever thought I'd have to :scream: :laugh:

**Comment by roya0045** [comment]
@nyalldawson No worries I don't take anything personnaly, though sometimes I feel like I'm pushing you to use your time to improve my attempts to fix a small bug. Not sure if that's the case and if its a bad thing. But yeah, I know we both want what's best for the program. ;)

**Pull request closed without merging**
