### PR TITLE
[processing] Remove parameter geometry predicate

### PR DESCRIPTION
**Pull request by arnaud-morvan**
Here I remove class ParameterGeometryPredicate and related widget by replacing it by ParameterSelection with multiple selection.

As replacing list of predicates by list of indexes will break models using impacted algorithms, I've added support for options as (text, value) in ParameterSelection. IMHO it seems mode sustainable to use fixed values (keys) instead of indexes. Command line also seems more understandable, and do not break with QGIS 2, example : 
```
processing.runalg("qgis:selectbylocation","file1.shp","file2.shp",['intersects'],0.0,0)
```
intead of : 
```
processing.runalg("qgis:selectbylocation","file1.shp","file2.shp",[1],0.0,0)
```
As a side effect, we need to open a dialog to see the selected values, maybe this could be improved later, displaying the values in selection widget until 3 values and count of values after that, or adding an option to selection widget for showing the checkboxes list directly in form.

Fix http://hub.qgis.org/issues/15784

### CODE REVIEW

**Comment by nirvn** [comment]
@arnaud-morvan I think this would fix the following issue too http://hub.qgis.org/issues/15784

(Long story short, the 3 algs relying on parameter geometry predicate are broken)

**Comment by nirvn** [comment]
That is, you would render it irrelevant.

**Comment by volaya** [comment]
I like the idea, but have a few questions:

- I dont understand why the widget has to be changed. We can still use a combo box with the descriptions of the values
- Any reason to use tuples instead of a dict? Sounds better to me. Maybe yu did that to keep the order, so they can still be called by number?
-Have you checked that algorithms are not called with hardcoded option numbers in the Processing code somewhere. If they are called like that, those calls will have to be fixed

Other than that, i like it very much, and I think it can be merged. Great work!

**Comment by alexbruy** [comment]
Why not use ``dict`` instead of list of tuples as proposed in http://hub.qgis.org/issues/7573?

**Comment by arnaud-morvan** [comment]
Yes, I've used list of tuples to keep the options ordering.

I've altered the widget first, and then, when tests were failing, I've seen that this should be done in Parameter. I'm trying to get tests passing, an I will finish widget after that.

Concerning calls with hardcoded numbers, ParameterGeometryPredicate also takes a list[str], so commandline argument stay the same, not broken.

**Comment by volaya** [comment]
Then is perfect. Let us know when the fixes are ready and tests passing, and I will merge it

Good work!

**Comment by volaya** [comment]
@arnaud-morvan Any news on this? thanks!

**Comment by arnaud-morvan** [comment]
I've encountered problems to reproduce test errors, but this should be good now.

**Pull request merged**
