### PR TITLE
DB Manager > Change logging :Fix behaviour of generated triggers when logging an existing layer

### PR DESCRIPTION
**Pull request by autra**
## Description

Adding logging to a layer with existing features and editing one duplicates this feature the first time.

Step to reproduce:

- have a postgis layer with some features
- use db manager to initiate logging/versioning
- edit one feature

The feature is duplicated in the `_current` view.

## Cause

When adding logging via db manager to an existing layer, all the
time_start of existing features are still null. When we modify one
feature for the first time, the update trigger fires and insert a row
for the past state of the feature. In turn, this fires the INSERT
trigger for this row, and the execution goes inside the `if
NEW.time_start is NULL`, which set the end timestamp to NULL, making the
old row still visible in the _current view.

In other word, the insert trigger makes the assumption that a null start
timestamp means now, which is not true in the case described above.

## Proposed solution

This commit fixes this assumption by initially setting it to `-infinity`
for existing rows.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Any volunteers to review this one?

**Review by troopa81 — CHANGES_REQUESTED** [review]
There is a comment in the dialog that says
> Table should be empty, with a primary key

What you are proposing improve the actual behavior, so the table could be not empty. I suggest you change this label.

The modification looks ok to me, I have tested it and it works!

Thanks @autra

**Comment by troopa81** [comment]
> @troopa81 I've updated the text in the ui file. What about all the translations?

Once merged, the new string to be translate will be pushed [here](https://www.transifex.com/qgis/QGIS/dashboard/) (with a little delay I think) and you would be able to translate them.

But that's not required for the PR to be merged

**Review by troopa81 — APPROVED** [review]
Thank you @autra, LGTM!

**Comment by troopa81** [comment]
unrelated test failure

**Pull request merged**
