### PR TITLE
Move pushbutton actions for map items up to new toolbar in item properties dock [ux][layouts]

### PR DESCRIPTION
**Pull request by nyalldawson**
This moves the
- refresh preview
- set to map canvas extent
- view extent in map canvas

buttons from being oversized push buttons within the item properties
panel up to a new toolbar at the top of this panel. Apart from looking
better, it means these important actions are always visible regardless
of the scroll position of the item properties panel itself.
Additionally, it makes it possible to add MORE actions here without
overloading the UI (e.g. "set canvas extent to item extent")

TODO: better icons

Thoughts? Good move? Bad move?

peek 2018-12-10 19-28

### CODE REVIEW

**Comment by nirvn** [comment]
I really like the idea of introducing a "shortcut" toolbar here, +1.

BTW, looking at your screenshot, do we know why there's an abnormal gap between the "Position and Size" and "Rotation" collapsible groups?

**Comment by nyalldawson** [comment]
Hmmmm, I'm not sure

**Comment by DelazJ** [comment]
@nyalldawson does it mean that the "map extent edit" action that currently is on the main "Toolbox" toolbar (as "move item content") is no longer at that place? Or is the 4th icon a duplicate shortcut? Because, currently you don't necessarily need the item properties panel to be active when interacting with a map item extent and I'm afraid this would be a requirement if the button is only at that place.
Unless the icons are misleading and it's another tool you are referring to.

**Comment by DelazJ** [comment]
Otherwise, Good to have these tools more visible

**Comment by iona5** [comment]
i am all for making the gui more there more space efficient. also the option to add more tools there is encouraging. (from my own user perspective a "lock canvas scale to map scale" would be a welcome addition... ;) )

the only thing i suggest to consider is that maybe the "map refresh"-button should be visually set apart from the other buttons which all do a "change extent"-kind of thing. i use the refresh-button way more often than the other ones, so imho it should be larger and more readily accessible, but maybe thats just me.

anyway good idea!

**Comment by nyalldawson** [comment]
Good point @iona5  -- I'll add separators in here between the logical action groups

**Pull request merged**
