### PR TITLE
Micro-optimisation: don't call geos for checking point geometry validity

### PR DESCRIPTION
**Pull request by nyalldawson**
Since a single-point will always be valid

### CODE REVIEW

**Comment by nyalldawson** [comment]
Can multipoints be invalid?

**Comment by jef-n** [comment]
Duplicate points in a multipoint?

**Comment by nyalldawson** [comment]
Is that invalid? Or permitted?

**Comment by rouault** [comment]
> Duplicate points in a multipoint?

This is valid:
```
$ ogrinfo pg:dbname=autotest  -sql "select st_isvalid(st_geomfromtext('MULTIPOINT(0 0,0 0)'))" -al -q
[...]
  st_isvalid (Integer(Boolean)) = 1
```

**Comment by jef-n** [comment]
> Is that invalid? Or permitted?

For `st_isvalid` in PostGIS it isn't.   OGC says only a MULTIPOINT with unique points is `simple` - but not that the other is invalid.   It's just the only way I could think of a case where a MULTIPOINT could be invalid.

**Comment by nyalldawson** [comment]
So we can shortcut for multipoint too? (Given that we call out to geos for isSimple, so that's unaffected)

**Pull request merged**
