### PR TITLE
[FEATURE] Background saving of vector layers

### PR DESCRIPTION
**Pull request by nyalldawson**
Switches the vector layer save operation to a background task using the task manager framework. Allows layers to saved without blocking the interface.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Obligatory screencast: https://www.youtube.com/watch?v=iBxR3wAn6qM&feature=youtu.be

**Comment by NathanW2** [comment]
Nice work. Could this lead to crashes with some formats at all?

**Comment by nirvn** [comment]
@nyalldawson , nice -- is editing of a layer being saved disabled during that background task?

**Comment by nyalldawson** [comment]
> Could this lead to crashes with some formats at all?

I can't see why... It's not all they different to the current approach. There is the potential that a user could edit the layer while the iterator is writing out the file, but I'm fairly certain that the vector layer iterators all handle this fine ( otherwise there'd be crashes if editing while rendering)

**Comment by nirvn** [comment]
@nyalldawson , might be worth having the task engine able to optionally "lock" layer(s) (which would disable some features such as editing) while a task running. That could be useful for processing algorithms too (esp. when we'll be able to apply algorithms on a dataset).

**Review by wonder-sk — APPROVED** [review]
Woohoo! The code looks great...

**Comment by nyalldawson** [comment]
For future reference - @wonder-sk and myself have also spoken off list about the need to expose running tasks more prominently in the gui. I'll start up a mailing list thread about this.

**Comment by nyalldawson** [comment]
Actually I've opened an issue here instead https://github.com/qgis/qgis3_UIX_discussion/issues/35

**Pull request merged**
