### PR TITLE
[processing][SAGA] Add setting to skip version check (off by default)

### PR DESCRIPTION
**Pull request by nyalldawson**
And with LOTS of warnings about the breakage which will occur!

### CODE REVIEW

**Comment by nyalldawson** [comment]
@alexbruy this ok for you?

**Review by alexbruy — APPROVED** [review]
I'm fine with it, although IMHO there is almost no sense in such option.

**Comment by nyalldawson** [comment]
I'm starting to realise that too... I thought it would help me test bugs on Fedora, which only has SAGA 2.2 (which segfaults almost all the time anyway), but I can't find a single algorithm which works.

Guess that's life with SAGA :P

**Comment by gioman** [comment]
(opinion from a Linux user here): we should always stick (and ship in OSGeo4W) with SAGA LTR even if in the meantime new shiny version of SAGA are shipped. The SAGA LTR is good enough for the *vast* majority of users. Users of other OSes will need to understand to get in their boxes SAGA LTR even if their package managers will propose more recent versions. Looking at the big picture here: Windows users.

**Pull request closed without merging**
