### PR TITLE
[BUGFIX] Filter Legend By Map Content doesn't maintain point displacement legend

### PR DESCRIPTION
**Pull request by rldhont**
Fixed #11572
Needs to be backported and adapted to version 2.14

### CODE REVIEW

**Comment by rldhont** [comment]
This bugfix complete 39e1f68ccc6dd4918614ac0df1e6bc0a92f6a725 Fix filtering legend content by map when renderer contains @nyalldawson 
After validation, I can backport the code

**Comment by nyalldawson** [comment]
Looks good, thanks!

**Comment by DelazJ** [comment]
> Needs to be backported and adapted to version 2.14

Only 2.14? 2.18 is still maintained, isn't it?

**Comment by rldhont** [comment]
Hi @DelazJ, for me if a backport to LTR is needed, the intermediate version has to be updated to and before the LTR.

When I cherry-pick a code, I do it like that: master -> version -> LTR.
You can view that it's what I have done for this bugfix.

Regards,

**Comment by DelazJ** [comment]
> Hi @DelazJ, for me if a backport to LTR is needed, the intermediate version has to be updated to and before the LTR.

Good then. Thanks for the fix and sorry for misunderstanding u.

**Pull request merged**
