### PR TITLE
[FEATURE][layouts] Add setting for label margin for map items

### PR DESCRIPTION
**Pull request by nyalldawson**
This setting allows per-map control of how close labels are permitted to be placed to the map item's edges.

Sizes can be set using mm/inches/pixels/etc, and data defined label margins are allowed. (Fixes #10314)

image

Additionally, this PR includes the raw API needed for both specifying a label edge margin to QgsMapSettings, AND the API for specifying arbitrary label blocking regions. This partly implements https://github.com/qgis/QGIS-Enhancement-Proposals/issues/113, with the exception of the ability to specify the obstacle factor for the additional blocking regions. In the end I decided that it was overkill to add this setting, which also caused many more obstacle checks to occur within the pal engine (vs the current approach of crafting a single allowable label geometry which is a union of all the blocking regions + edge margins).

In a follow up PR i'll be exposing a setting to (optionally) avoid placing labels under layout items which sit above a map item, e.g. "don't try to draw obscured labels below my scalebar".

### CODE REVIEW

**Comment by DelazJ** [comment]
I find weird the split label (not nice looking and hard to translate out of context). What about `minimal distance from map edges`, `margin for label placement`, and add the `Avoid placing labels within the set distance from map edges` as tooltip?

**Comment by nyalldawson** [comment]
@delazj

I don't like it either, but honestly, every other option I could think of is either much harder for users to understand or too long. It's ugly, but the current string IS very easy for someone to understand immediately without having to consult any tooltips or documentation.

**Comment by DelazJ** [comment]
You like none of my suggestions? :cry:
The matter, if any, is not to understand what is written in English GUI; it's to understand how and what is translated. Sorry to be language-community centered. In Transifex we end up with two separate strings (with no visual context). And there are languages (maybe, not in QGIS) that do not construct sentences in the same linearity as English, hence not easy for non English speaker.
Anyway...

**Comment by nyalldawson** [comment]
@DelazJ 
How's this variation:

image

**Comment by DelazJ** [comment]
@nyalldawson sorry for the late reply. Is "at least this far" a common expression? `No labels will be placed within this distance from map item edges`?
Anyway, I prefer this to the previous one. Thanks for having considered my comment.

**Comment by nyalldawson** [comment]
> Is "at least this far" a common expression?

Ok, adjusted again :)

**Pull request merged**
