### PR TITLE
Modeler - Show group in the algorithm dialog title

### PR DESCRIPTION
**Pull request by DelazJ**
Followup #57739

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]
Lgtm thx

**Comment by agiudiceandrea** [comment]
@m-kuhn, since https://github.com/qgis/QGIS/pull/57739 was backported to 3.34, shouldn't also this PR be backported to 3.34 (and 3.38 too)?

**Comment by DelazJ** [comment]
@agiudiceandrea 3.38 is eol

**Comment by agiudiceandrea** [comment]
@DelazJ, not yet: QGIS 3.38.3 will be released on 2024-09-13 according to the roadmap.

**Comment by DelazJ** [comment]
Indeed!!!!

**Pull request merged**
