### PR TITLE
Qt5py3 more mac fixes

### PR DESCRIPTION
**Pull request by dakcarto**
Further work to make discovery of dependent libs/includes simpler. Plus, one Processing fix.

These are the last updates for cleaner Homebrew dependency integration. @m-kuhn, please review when you get a chance.

### CODE REVIEW

**Comment by dakcarto** [comment]
@blazek, can you review the GRASS plugin CMake changes, to make sure I have the 'versioning' setup correct? Works here for just GRASS7, but I no longer build GRASS6, so can't test it or multiple GRASS installs.

Otherwise, if no one has concerns about these changes, I'll merge them.

**Comment by dakcarto** [comment]
Also, @blazek, is GRASS 6 support going to be stripped from QGIS 3?

**Comment by m-kuhn** [comment]
No objections from my side. Like last time, I'd just merge it with the option to react if we see that there are problems.

**Comment by blazek** [comment]
I'll look at it and test with GRASS 6, but I cannot say when, I am too busy these days.

> is GRASS 6 support going to be stripped from QGIS 3?

I would say so, but I'll ask on mailing list if there are objections.

**Comment by blazek** [comment]
Leaving GRASS_EXTRA_INCLUDE_DIRS6/7 empty, I have got:
`CMake Error at cmake/FindGRASS.cmake:139 (CHECK_GRASS_EXTRA_INCLUDE_DIRS):
   CHECK_GRASS_EXTRA_INCLUDE_DIRS Macro invoked with incorrect arguments for
   macro named: CHECK_GRASS_EXTRA_INCLUDE_DIRS`

There is general agreement on removing GRASS 6 support, so we can throw away all the related hacks.

**Comment by dakcarto** [comment]
> Leaving GRASS_EXTRA_INCLUDE_DIRS6/7 empty, I have got...

@blazek does changing line # 139 to this work?
```
CHECK_GRASS_EXTRA_INCLUDE_DIRS(${GRASS_FIND_VERSION})
```
Guessing that `$GRASS_CACHE_VERSION` may not be set at that point.

**Comment by blazek** [comment]
Yes it works.

**Comment by dakcarto** [comment]
Thanks for testing! Fixed in c42dad3.

**Pull request merged**
