### PR TITLE
[PostgreSQL] fix: always used type of first column of view as PK type

### PR DESCRIPTION
**Pull request by MorriganR**

### CODE REVIEW

**Comment by nyalldawson** [comment]
Could you add a test for this please?

**Comment by MorriganR** [comment]
Done, the result of the test on the Master (without the changes offered by this PR) is available here:
https://github.com/MorriganR/QGIS/runs/2903699627
test fails:
```
======================================================================
FAIL: testSingleMultiColumnPkSmallData (__main__.TestPyQgsPostgresProvider)
Test Single and Multi Column PK, `Small` Data
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/QGIS/tests/src/python/test_provider_postgres.py", line 2723, in testSingleMultiColumnPkSmallData
    test_for_pk_combinations(test_type_list, pk_col_set, 7)
  File "/root/QGIS/tests/src/python/test_provider_postgres.py", line 2661, in test_for_pk_combinations
    self.assertEqual(fids_get_count, len(fids2), "Get by fids " +
AssertionError: 7 != 0 : Get by fids from view with PK - id_uuid : expected 7, got 0

----------------------------------------------------------------------
```

**Comment by MorriganR** [comment]
@jef-n please review. Sorry for the stupid commit https://github.com/qgis/QGIS/commit/457165d7be57827be386c5f4a3000f3b19b9c77f

**Review by jef-n — APPROVED** [review]

**Comment by jef-n** [comment]
LGTM (followup to a7a0eefe720f)

**Comment by MorriganR** [comment]
> LGTM (followup to [a7a0eef](https://github.com/qgis/QGIS/commit/a7a0eefe720f216c0bf9791c4a91a4244c0ef4d9))

Thanks!

**Comment by nyalldawson** [comment]
@MorriganR you are on :fire: ! Thanks for all the effort you're putting in to your fixes and optimisations -- they are HUGELY appreciated!

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@MorriganR should this be backported?

**Comment by MorriganR** [comment]
I see no point in backport, since there is a hack to solve the problem.
https://github.com/qgis/QGIS/issues/37437#issuecomment-650577062

**Pull request merged**
