### PR TITLE
Strip space from end of methods in doc test

### PR DESCRIPTION
**Pull request by NathanW2**
Just a PR to test something.  Currently having issues with the local docs test showing tons of undocumented members when they are listed in the ignore list.  Tracked it down to spaces at the end of some of the of the members.  BIt odd that it passes on Travis but not local.

### CODE REVIEW

**Comment by NathanW2** [comment]
@3nids any thoughts?

**Comment by 3nids** [comment]
I never investigate why the doc test was failing locally...I'm glad to see I'm not the only one. No idea for Travis though. But this seems to fail on Travis...would be nice to have it working everywhere :)

**Comment by NathanW2** [comment]
This is super suspicious. Why would it be different local to Travis when it's the same code.   I'm going to add some more logging to print what Travis is seeing.

**Comment by m-kuhn** [comment]
Is it because of different doxygen versions maybe?

**Comment by nyalldawson** [comment]
Superseded by #7051

**Pull request closed without merging**
