### PR TITLE
qgsdockablewidgethelper: Prevent crash when closing dock

### PR DESCRIPTION
**Pull request by ptitjano**
## Description

When closing the dock, QGIS sometimes crash. It seems like the `mDialog::finished` slot sends `visibilityChanged` signal. However, the `QgsDockableWidgetHelper` may have been destroyed in the meantime. Hence, the crash.

I tried to solve this issue by ensuring to emit this signal if the object still exists. I cannot reproduce the issue anymore but I'm not sure this is the proper fix.

### CODE REVIEW

**Comment by nyalldawson** [comment]
> I tried to solve this issue by ensuring to emit this signal if the object still exists. I cannot reproduce the issue anymore but I'm not sure this is the proper fix.

I don't think it's the correct fix either. The lambda is already referencing mDialog directly on line 319, so that means the only time that mDialog is nullptr on line 321 is if some connection to the closed signal emitted on line 320 has done something bad.

My suspicion would be that the issue is in one of the connections to that closed signal. Where specifically did you see this crash?

**Comment by ptitjano** [comment]
> > I tried to solve this issue by ensuring to emit this signal if the object still exists. I cannot reproduce the issue anymore but I'm not sure this is the proper fix.
> 
> I don't think it's the correct fix either. The lambda is already referencing mDialog directly on line 319, so that means the only time that mDialog is nullptr on line 321 is if some connection to the closed signal emitted on line 320 has done something bad.
> 
> My suspicion would be that the issue is in one of the connections to that closed signal. Where specifically did you see this crash?

Thanks. To trigger the crash: 
- Create a new 2D view
- Click on the dock button
- Close the view
Sometimes, it crashes the first time, sometimes I need to do it 2 or 3 times but it always crashes at some point.

**Comment by ptitjano** [comment]
This should be the proper fix now.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
LGTM! thanks for the extra investigation !

**Pull request merged**
