### PR TITLE
Ensure canvas has focus if nothing else has 

### PR DESCRIPTION
**Pull request by nyalldawson**
Forward porting a useful fix from sourcepole's fork

### CODE REVIEW

**Comment by m-kuhn** [comment]
Under what circumstances is this triggered?

**Comment by nyalldawson** [comment]
When a focused widget is deleted. Eg. Open the python console and click inside, then close it.

**Comment by m-kuhn** [comment]
What happens when the focused widget was on a print composer dialog?

**Comment by nyalldawson** [comment]
The ` isActiveWindow()` check should protect against that (and also loss of focus due to changing active windows)

**Review by m-kuhn — APPROVED** [review]
LGTM

**Pull request merged**
