### PR TITLE
Make qgsRound more tolerant to large values

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #19844

### CODE REVIEW

**Comment by nyalldawson** [comment]
Ping @agiudiceandrea

**Comment by m-kuhn** [comment]
So the proper approach would be this?

1. merge this
2. deprecate qgsRound
3. remove internal usage of qgsRound
4. drop qgsRound with QGIS 4

**Comment by nyalldawson** [comment]
> did you test the qgsround() fix for a number of decimal places above 9?

There's a unit test for this. It looks ok to me.

I think we should merge and leave qgsRound, but remove its use from the formatDistance/area methods

**Comment by m-kuhn** [comment]
> I think we should merge and leave qgsRound, but remove its use from the formatDistance/area methods

It should definitely be merged, we need to keep it for the lifetime of QGIS 3, and therefore we better keep a fixed version.

But does it make sense to keep this method for QGIS 4, even if it's unused?

**Comment by nyalldawson** [comment]
> But does it make sense to keep this method for QGIS 4, even if it's unused?

Well, if it works and has tests, I'd say yes. And fcnRound should use it.

**Comment by nyalldawson** [comment]
Actually... grep for `std::pow( 10`. There's lots of code which should use this and which re-implements it.

**Comment by m-kuhn** [comment]
If there's a good reason to put it into use, the reasons for deprecation are obsolete.

**Pull request merged**
