### PR TITLE
move value group box under help area [Expression builder] [needs-docs]

### PR DESCRIPTION
**Pull request by 3nids**
otherwise the value group box might might be on top of the item
fix #17727

Other approaches I consider, which I did not like:
* using a single shot to display the value box 500ms later
* scroll to move the row to the top of the tree

image

### CODE REVIEW

**Comment by 3nids** [comment]
This would require a validation from a UX perspective
Ping @NathanW2 ?

**Comment by nirvn** [comment]
It's a hard one. I've been victim of the dbl clicking on field only to be obstructed by value list to want this fixed. 

I'd say move it below help, and in case the help area is claused expand it upon click (we'd end up sometimes with the same issue whereas the expanding help/value section will interfere with a dbl click but can't see another way here)

**Comment by m-kuhn** [comment]
> I'd say move it below help, and in case the help area is claused expand it upon click (we'd end up sometimes with the same issue whereas the expanding help/value section will interfere with a dbl click but can't see another way here)

or right click -> show values, unless we have a less obtrusive way?

**Comment by m-kuhn** [comment]
Should we merge this and deal with the problem of discoverability of help/proposed values in a separate followup?

**Comment by 3nids** [comment]
another option could be to integrate a button 'show values' in the row?

**Comment by m-kuhn** [comment]
yep, also a good idea.

to be sure: we all agree it should be moved back to the right?

**Comment by m-kuhn** [comment]
Are field values contextually not pretty similar to help?
I think it happens more often that novice users close the help area and wonder how to get it back than pro users close it on purpose and then are annoyed that it reopens when they need field values.

But as long as this is moved forward quickly I can live with most solutions.

**Comment by m-kuhn** [comment]
Just ran into someone else today who closed the help by accident and didn't even know it existed and was super happy to see it appear again. More and more convinced this needs to be more visible.

A "values" button on fields and a "help" button on functions where help exitst to open the panel?

**Comment by m-kuhn** [comment]
I'm feeling a bit lonely in here 

giphy

**Comment by 3nids** [comment]
I have added a new button to show the Help and Values area.
It is disabled when the Help is visible.
Text of the button changes (Show Help vs Show Values) depending on the current index
Help has now a minimum size of 250, the tree is not collapsible anymore (no sense to have help only).

image
image
image

**Comment by 3nids** [comment]
@nirvn @m-kuhn does it work for you guys?

**Comment by m-kuhn** [comment]
Works very well for me, thanks!

**Comment by 3nids** [comment]
if there is no objection, I'll merge this and would backport a bit later.

**Comment by nirvn** [comment]
Please do. I'm +1 too.

**Comment by DelazJ** [comment]
I think this [needs-docs]

**Pull request merged**
