### PR TITLE
Add new project3.qgs to testdata for testing qgis_server

### PR DESCRIPTION
**Pull request by uprel**
## Description

New qgis project file needed for testing qgis server

### CODE REVIEW

**Comment by elpaso** [comment]
In what tests is this used?

**Comment by uprel** [comment]
> In what tests is this used?

None, I just used it in issue report to generate test link

**Comment by gioman** [comment]
> None, I just used it in issue report to generate test link

@uprel just attach the sample data to the proper ticket. Closing this PR?

**Comment by uprel** [comment]
Done, yes we don't need this, closing.

**Pull request closed without merging**
