### PR TITLE
The order_expression parameter in Points to Path algorithm is not optional

### PR DESCRIPTION
**Pull request by DelazJ**

### CODE REVIEW

**Comment by nyalldawson** [comment]
It needs to be optional, or older scripts will break

**Comment by DelazJ** [comment]
but if I run it in the GUI without filling a value (I assume this is what is meant by optional), it asks me a value
https://github.com/qgis/QGIS/blob/788f71fc424765c27ee63e82a246e8bcb70f6a28/python/plugins/processing/algs/qgis/PointsToPaths.py#L125-L126

**Comment by roya0045** [comment]
Can we use rowid/fid as the default? Or just the first field available, if its not truly optional.

**Comment by nyalldawson** [comment]
Hmmmm, I think we need to remove that exception and just allow it to run without any order set

**Comment by DelazJ** [comment]
> Hmmmm, I think we need to remove that exception and just allow it to run without any order set

Would this not lead to some unpredictable results? Something that would be useless and people will anyway have to give an order if they want to control the output?

Is it not possible to have it mandatory and, given that the issue resides with old scripts, have a check that there's a order_field value provided and transfer that value to order_expression? Afaict, order_field was also mandatory so the scripts should have a field assigned. Not sure if I'm clear enough but the idea is to have some logic to assign order_field value to order_expression if the script runs an old call.

**Comment by nyalldawson** [comment]
No, that's not possible in current API. There's logic outside of the algorithm itself which tests that all mandatory parameters are filled. so making this parameter mandatory will break execution eg with the qgis_process tool. 

@m-kuhn any ideas here?

**Comment by uclaros** [comment]
How about deprecating the algorithm and creating a tidier c++ one with a proper *Points to lines* name?

**Comment by nyalldawson** [comment]
@uclaros win! Sounds like an ideal solution

**Comment by m-kuhn** [comment]
> but if I run it in the GUI without filling a value (I assume this is what is meant by optional), it asks me a value
> 
> https://github.com/qgis/QGIS/blob/788f71fc424765c27ee63e82a246e8bcb70f6a28/python/plugins/processing/algs/qgis/PointsToPaths.py#L125-L126

It's not intended to be run from the gui without this param.

But allows legacy mode
https://github.com/qgis/QGIS/blob/788f71fc424765c27ee63e82a246e8bcb70f6a28/python/plugins/processing/algs/qgis/PointsToPaths.py#L122-L126

**Comment by DelazJ** [comment]
> It's not intended to be run from the gui without this param.

But for an end user seeing optional, it is tempting... and then you realize it's a wrong optional
> But allows for legacy mode

Sorry. I miss these lines.
> How about deprecating the algorithm and creating a tidier c++ one with a proper Points to lines name?

Beyond my skills ;( so if someone wants to take the lead on this, feel free.
Thanks.

**Pull request closed without merging**
