### PR TITLE
Fix use of enum flags in older python/sip versions

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by 3nids** [comment]
this is such a pity, the docs of scoped enums just look much much nicer.

**Comment by nyalldawson** [comment]
We'll have to defer till we can bump the sip/python version requirement...

**Comment by m-kuhn** [comment]
> We'll have to defer till we can bump the sip/python version requirement...

to?

**Comment by m-kuhn** [comment]
@nyalldawson do you have more specific information about the system on which it failed?

**Comment by nyalldawson** [comment]
It fails on travis, works fine locally (fedora 31). I'll post version numbers tomorrow

**Pull request merged**
