### PR TITLE
[qgsquick] add missing function definition

### PR DESCRIPTION
**Pull request by PeterPetrik**

### CODE REVIEW

**Comment by PeterPetrik** [comment]
unrelated mingw fail

**Review by nirvn — APPROVED** [review]
Do you feel like making it a full fledged Q_PROPERTY with a transformContextChanged() signal too? No strong feelings.

**Comment by PeterPetrik** [comment]
ATM i just want to compile quick :)

**Comment by PeterPetrik** [comment]
hmm, can I hit merge even when mingw is broken?

**Comment by nirvn** [comment]
@PeterPetrik , :) an alternative here would be to remove the setter from the header altogether if that's not used.

**Comment by PeterPetrik** [comment]
I think we use it in Input

**Pull request merged**
