### PR TITLE
Check that source files are not overridden

### PR DESCRIPTION
**Pull request by strk**
This is a continuation of #31980 aimed at moving toward fixing #25830

### CODE REVIEW

**Comment by strk** [comment]
@manisandro it looks like the fedora rawhide GDAL packages for mingw64 are broken, see:

 - https://github.com/qgis/QGIS/runs/6569921610?check_suite_focus=true#step:6:68 (repo addition)
 - https://github.com/qgis/QGIS/runs/6569921610?check_suite_focus=true#step:6:82 (gdal-devel package 3.5.0-3.fc37)
 - https://github.com/qgis/QGIS/runs/6569921610?check_suite_focus=true#step:12:40 (cmake failure)

I've been suggested by @nyalldawson to ping you as the maintainer of that repo

**Comment by manisandro** [comment]
Thanks, I'm looking into it

**Comment by manisandro** [comment]
https://github.com/qgis/QGIS/pull/48726

**Comment by strk** [comment]
It was too good to be true, for CI to pass, indeed the git log checker is just being skipped:
```
   Test project /root/QGIS/build
        Start   1: logGitStatus
   1/35 Test   #1: logGitStatus ............................***Skipped   0.00 sec
```

Is there a way to ask `ctest` to print standard error or standard output for tests which are skipped ? It would help understanding WHY the test is skipped. I know in theory it would be skipped if `git` is not found in PATH, but I'm surprised this is the case as the post-checkout step seems to have git installed: https://github.com/qgis/QGIS/runs/6571648653?check_suite_focus=true#step:26:2

**Comment by strk** [comment]
I made the tests fail instead of be skipped, to check the reason of the failure. Reason is pretty clear:
> git is not found in PATH

I myself would make git available (in the docker image, I guess). Seems easier than implementing another way to check for files being changed after running the testsuite...

**Comment by strk** [comment]
@3nids can you understand why `git` is not available in the qgis3-build-deps-binary-image here: https://github.com/qgis/QGIS/runs/6636446064?check_suite_focus=true

It looks like the docker build step is completely skipping the part of the dockerfile starting with https://github.com/qgis/QGIS/blob/4e6ae602c02f5358ca469293b3f496f49b47f14c/.docker/qgis3-qt5-build-deps.dockerfile#L166 where git is supposed to be installed.

Could this have to do with the `binary-only` target being ambiguous as used for both the `binary-for-oracle` and the `binary-only` step ?

**Comment by strk** [comment]
Ok now that I made `git` available in all targets of the docker image CI is correctly running and showing that the check for source tree being changed is functioning. The fact it is still green is because not all tests are yet configured to require the fixture, I think. It may be good to merge this as-is to secure availability of the FIXTURE and securing of all the tests currently requiring it (ie: being checked for not changing source tree).

I'll nonetheless see to add missing tests to the set, in case the reason is different (could different versions of spatialite behave differently wrt the locking of .gpkg files?) \cc @rouault

**Comment by rouault** [comment]
> could different versions of spatialite behave differently wrt the locking of .gpkg files?)

different versions of GDAL, mainly given they are < or >= 3.4.2

**Comment by strk** [comment]
> > could different versions of spatialite behave differently wrt the locking of .gpkg files?)
> 
> different versions of GDAL, mainly given they are < or >= 3.4.2

The libgdal version in the docker image used by CI to run test seems to be 3.0.4 -- is that supposed to be modifying those gpkg files upon opening them ?

**Comment by strk** [comment]
I'm running 3.2.2 on my system and on my system I see those .gpkg files being changed

**Comment by rouault** [comment]
> The libgdal version in the docker image used by CI to run test seems to be 3.0.4 -- is that supposed to be modifying those gpkg files upon opening them ?

yes, GDAL 3.4.2 is needed to avoid the gpkg files to be changed upon being opened by QGIS

**Comment by strk** [comment]
I'm running 3.2.2 on my system and on my system I see those .gpkg files being changed

> > The libgdal version in the docker image used by CI to run test seems to be 3.0.4 -- is that supposed to be modifying those gpkg files upon opening them ?
> 
> yes, GDAL 3.4.2 is needed to avoid the gpkg files to be changed upon being opened by QGIS

Then I don't understand how can CI pass the test of source tree being unmodified.
I do see `tests/testdata/zip/landsat_b1.zip` modified by test_core_gdalprovider, in the docker container running gdal 3.0.4:
```
root@2a1ddba4a61d:/home/src/qgis/qgis/src/do-not-override-source-files/build-ci# xvfb-run ctest --output-on-failure -R test_core_gdalprovider
Test project /home/src/qgis/qgis/src/do-not-override-source-files/build-ci
    Start  1: logGitStatus
1/3 Test  #1: logGitStatus .....................   Passed    6.15 sec
    Start 73: test_core_gdalprovider
2/3 Test #73: test_core_gdalprovider ...........   Passed    1.73 sec
    Start  2: checkGitStatus
3/3 Test  #2: checkGitStatus ...................***Failed    0.19 sec
1d0
<       modified:   tests/testdata/zip/landsat_b1.zip
Source files (printed above) were modified. Diff follows:
diff --git a/tests/testdata/zip/landsat_b1.zip b/tests/testdata/zip/landsat_b1.zip
index b341559556a..4c3887b101f 100644
Binary files a/tests/testdata/zip/landsat_b1.zip and b/tests/testdata/zip/landsat_b1.zip differ


67% tests passed, 1 tests failed out of 3
```

The test *is* run by CI: 
https://github.com/qgis/QGIS/runs/6717755154?check_suite_focus=true#step:13:227

I've pushed a commit to print GDAL version as I don't understand this...

**Review by elpaso — APPROVED** [review]
LGTM but as I already mentioned I'm not the best person to review this stuff, it was mainly developed by other devs.

**Comment by strk** [comment]
Great, we finally got real failures from CI:
< 	modified:   tests/testdata/points_gpkg.gpkg
< 	modified:   tests/testdata/qgis_server/db.gpkg

https://github.com/qgis/QGIS/runs/6737341519?check_suite_focus=true#step:13:207

This proves the effectiveness of the test (not sure why it didn't work before, maybe the `safe.dir` option was missing and somehow git silently failed...

**Comment by strk** [comment]
Figured: the silent failure was due to the git invocation being part of a shell pipeline, I've pushed a different approach to catch it earlier

**Comment by strk** [comment]
Ok so the test now runs and shows some tests ARE leaving the source tree in a modified state.
Ways possible forward (having had this work staled out multiple times over the hears) are:

   1. Keep the testing script and the fixture, revert the requirement of the FIXTURE from tests known to be bogus
   2. Keep everything and have the checker honour some environment variable asking NOT to check, setting that env variable in CI
   3. Fix all tests

I know for a fact that 3 (fix all cases) will be too hard. I'll lean toward 2 (use an env variable).
Would you be ok with that @elpaso ? Then I could create a SEPARATE pull request to try at fixing the tests to a point in which we can unset that env variable...

**Comment by elpaso** [comment]
IMO this is what you should do:

- create a list of known modified files and put it in a file
- check that no new modified files are introduced with a PR and fail badly if there are

We should probably ask for a QGIS grant for cleaning up all the tests and remove the file with the known failures.

**Comment by strk** [comment]
> IMO this is what you should do:
> 
>     * create a list of known modified files and put it in a file
>     * check that no new modified files are introduced with a PR and fail badly if there are

This is exactly what this PR does.
The SOURCETREE fixture is initialized by the script that saves the list of currently modified files into a file and finalized by a script that compares the saved list to the NEW list, and bails (printing the list of unexpected modified files) to standard output.

See how it looks:
https://github.com/qgis/QGIS/runs/6753897591?check_suite_focus=true#step:13:1740

Additionally, you also get an actual DIFF (when the file is not a binary file).

Using the FIXTURE ensures that the test runs for *any* subset of tests, so locally you could bisect using the `-R` switch of `ctest` to find the culprit.

In order for new PRs to fail when the problem is introduced we'll need CI to actually run the test, but at the moment it would fail as you can see. I'm looking for a way to not LOOSE all the work I did here by the action of the stale-bot (and time, with git conflicts). The simplest way to not loose this work at the moment would be to have the CI not fail when modifications are found. Ideally it would still print the modified files but unfortunately I have not found a way to ask `ctest` to still print something, other than on failure (`--output-on-failure` switch), if you know of a way I'll be happy to do that.

> We should probably ask for a QGIS grant for cleaning up all the tests and remove the file with the known failures.

That's a good idea, but we're still talking about postponing that work and I'm looking for a way to complete this before the release so we all have a tool, locally, to hunt for those failures (hunt to be performed with a grant or any other way).

**Pull request merged**
