### PR TITLE
Temporarily disable missing llvm apt repo

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by nyalldawson** [comment]
@m-kuhn I tried the same thing about 24 hours ago with no luck. The default travis clang is just too old to build with.

**Comment by m-kuhn** [comment]
What about gcc?

**Comment by nyalldawson** [comment]
I didn't try that... but good idea now we use ccache!

**Comment by m-kuhn** [comment]
And the winner is... gcc. At least for now.

**Pull request closed without merging**
