### PR TITLE
Check boundaries when reading WKB for simplification

### PR DESCRIPTION
**Pull request by strk**
Fixes crash on simplifying mixed-dimension collections.
Data to reproduce is in ticket #12416

### CODE REVIEW

**Comment by strk** [comment]
See https://trac.osgeo.org/gdal/ticket/6332 for how the "malformed" WKB is created

**Comment by strk** [comment]
I don't understand how the build fails for travis, the travis build page mentions 3 build errors but doesn't show them to me. Can anybody help  ? @m-kuhn, @nyalldawson, @jef-n

**Comment by strk** [comment]
See https://travis-ci.org/qgis/QGIS/jobs/104678595#L855

**Comment by m-kuhn** [comment]
http://dash.orfeo-toolbox.org/viewBuildError.php?buildid=215739

See the link in the build log.

I was once advised not to use exception (I think the main point was that it's dangerous as long as we don't use RAII consequently) in the QGIS source code

Please also break lines after if's

**Comment by m-kuhn** [comment]
There is also QgsWkbPtr which takes care of memory alignment on different CPU architectures. Not sure if this applies to this PR as well.

**Comment by mhugo** [comment]
@m-kuhn I am a bit surprised about this no exception policy ... I've used some std::runtime_error in some previous commits. What are the arguments against ?

**Comment by m-kuhn** [comment]
@mhugent requested me to use exceptions. That was some years ago but I didn't use exceptions since.

As I said, main reasons as far as I remember, danger of memory leak due to lack of RAII, Qt doesn't use it.

**Comment by jef-n** [comment]
See also https://github.com/jef-n/QGIS/tree/wkb-bounds-check (work in progress)

**Comment by strk** [comment]
I'll be happy to port the code to use WkbPtr once it also checks for bounds (jef's work).
About exceptions, the standard library does use it so leaks are still possible if RAII is not enforced. I think QGIS should aim at proper RAII rather than avoid its own exceptions.

**Comment by m-kuhn** [comment]
I agree that QGIS should aim to consistently use RAII.
But I would add that fact is: at the moment it does not.

**Comment by strk** [comment]
In this specific case the exception could only be replaced by an early return, which would be affected by the same exact risk of leaks as the only caller of the private that was made possibly throwing was also made to catch an eventual exception.

**Comment by m-kuhn** [comment]
No strong opinion from my side, I just wanted to mention things to consider I have been told by the technical advisor of the project.

But please do add a line break after conditional statements, it's really odd to read one-line if's inside this particular blob of sourcecode ;)

**Comment by mhugent** [comment]
Regarding exceptions: it's also quite easy to introduce performance penalties using exceptions (see e.g. Scott Meyers 'Understanding the costs of exception handling).

**Comment by strk** [comment]
for this particular patch it's not  a big deal to avoid exception, but if you think about the core parser (currently not robust, see #2722) the usage pattern would make exception much more natural.

Example usage pattern:

```
 WkbPtr wkb(ptr, len);
 double x, y;
 x << wkb;
 y << wkb;
```

**Comment by strk** [comment]
Then, if the simplifier is finally turned to use WkbPtr (which I'd recommend, once bounds-checking), what happens if we want to return `false` rather than throw an exception is we need to catch the exception locally and turn it into a `false` return, rather than relying on RAII to just let the exception flow up to the actual caller (which would be much more elegant, IMHO).

**Comment by strk** [comment]
Uhm, the failures seem unrelated now ?
http://dash.orfeo-toolbox.org/viewTest.php?onlyfailed&buildid=215773

**Comment by strk** [comment]
@m-kuhn - styled and rebased, so we see if it was a temporary failure

**Comment by strk** [comment]
I checked locally, the failures are not unrelated:
```
ctest -R PyQgsGeometryGeneratorSymbolLayerV2
```

How can I print an error so that it is shown at ctest run time ?

**Comment by m-kuhn** [comment]
ctest -V -R GeometryGenerator

**Comment by strk** [comment]
I'm taking back the "it's easy to avoid exception in this case" because the parser for collections is using the return code to signify the current component cannot be simplified and thus continues to the next. In the case of a premature-WKB-end (as in this case) the loop would continue till all components have been scanned, rather than stopping at the first EOF condition.

**Comment by strk** [comment]
So the only thing left here is a specific testcase. Obtaining one would take running an old enough GDAL for reading the filegdb with the opengdb driver. Or how else could I force the "broken" WKB into a geometry for rendering purposes ?

**Comment by strk** [comment]
I'm post-poning the test as a good way would be to build a Geometry fromWkb, but that would currently fail on itself, see #2722

**Comment by strk** [comment]
Pushed as bc4d16e8d912d9f6a605daa02d2959cd8145e770

**Pull request closed without merging**
