### PR TITLE
make SAGA GIS descriptions 2.2.2 accessible

### PR DESCRIPTION
**Pull request by rhurlin**
Make version 2.2.2 descriptions available

### CODE REVIEW

**Comment by fsdias** [comment]
@volaya @alexbruy

**Comment by volaya** [comment]
is that correct? The name of the variable (DESCR220_FILES) is repeated

**Comment by rhurlin** [comment]
That is, what I also asked before ;)
Sorry, my skill are not good enough to decide, if we need a DESCR222_FILES here. But it seems reasonable to me.

**Comment by rhurlin** [comment]
I just tested with DESCR222_FILES instead of DESCR220_FILES and it fails. There is no directory 2.2.2 build in python/plugins/processing/algs/saga/description/.
So it seems, my patch is right and we have to use DESCR220_FILES, until newer description files are generated ...

**Comment by rhurlin** [comment]
1) I am not sure, if all is done here from my side for patch ded4c69 ? 
2) I am not clear, if 2312a93 is really deleted (it is obsolete).

Until now, I am not very familiar with GitHub, sorry.

**Comment by m-kuhn** [comment]
@rhurlin just click the "files" button on top, that will show you the sum of all changes. https://github.com/qgis/QGIS/pull/2408/files

**Comment by rhurlin** [comment]
Thanks for the tip. The changes in https://github.com/qgis/QGIS/pull/2408/files should be fine so far. ded4c69  is the one, which I suggest to commit.
Without this patch or something like this, QGIS processing can't handle SAGA GIS greater than 2.2.0.

**Comment by m-kuhn** [comment]
@volaya @alexbruy does that look ok to you?
I.e. use the 2.2.0 descriptions also for 2.2.2?

**Comment by gioman** [comment]
This is the diff file with differences between 2.2.0 and 2.2.2 http://hub.qgis.org/attachments/9210/saga_diff_2_2_0_vs_2_2_2.txt

**Comment by m-kuhn** [comment]
Merged as 0b0c413f3a19181fe219d4ac2e8b571158dc5b68

**Pull request closed without merging**
