### PR TITLE
Port heatmap plugin code to analysis, add processing alg

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR copies the heatmap code to the analysis lib (with lots of cleanups) and exposes it to the python bindings. It also adds a new processing algorithm for heatmaps.

Things which aren't ported:
- everything is done in layer units now. The old heatmap plugin had buggy support for distances in layer units or metres, but I don't consider this a big loss.
- the old heatmap plugin has a nicer ui for setting the output rows/columns/pixel size then the new processing algorithm. I need to fix this before this can be merged and the c++ plugin culled.
- no unit tests yet

### CODE REVIEW

**Comment by nyalldawson** [comment]
@alexbruy I'll move the processing ui discussion here:

What I'm wondering now is whether it makes sense to have a "output raster resolution" parameter in processing. This could then be attached to a parent layer with a nice gui widget allowing interactive changes of rows/cols/pixel size which respect the aspect ratio of the parent layer. Does that approach make sense or is it overkill?

**Comment by nirvn** [comment]
This possible output raster resolution parameter would also be very useful for the raster calculator being ported to processing in PR #3779 .

**Comment by alexbruy** [comment]
@nyalldawson, IMHO such parameter is quite specific and will be useful only in few algorithms, so adding it to the core Processing makes no sense. It can be added only to Heatmap algorithm similarly as Victor did with `ParameterExpression` in #3779.

@volaya what do you think?

**Comment by nyalldawson** [comment]
@alexbruy 

>  It can be added only to Heatmap algorithm similarly as Victor did with ParameterExpression in #3779.

Perfect - that looks like exactly what I need. Thanks!

**Comment by volaya** [comment]
@nyalldawson Yes, i think that the what @alexbruy says makes sense. Might be too specific. Also, notice that a number paramter will allow to use the expression dialog, so you can use the layer extent or the cellsie of another one to compute the cellsize you want for your output.

Feel free to merge this yourself once you have it ready, it looks good to me.

**Pull request merged**
