### PR TITLE
Add support for reading SLD's with multiple FeatureTypeStyle elements.

### PR DESCRIPTION
**Pull request by Roel**
Introduce a virtual FeatureTypeStyle to add support for reading SLD documents with more than one FeatureTypeStyle element.

Still supports SLD's with one FeatureTypeStyle, as well as SLD's with multiple FeatureTypeStyles, including empty FeatureTypeStyles (not breaking single symbol rendering in that case). Complies with SLD's painter's model for rendering, appending Rules from subsequent FeatureTypeStyles in order.

Should fix http://hub.qgis.org/issues/6413

### CODE REVIEW

**Comment by nyalldawson** [comment]
@luipir @jgrocha @aaime We need to clean up this PR queue - since you all have previously undertaken work on SLD, can you review and determine if there's value here?

**Comment by luipir** [comment]
you are right @nyalldawson. I'm not expert on all SLD available tags, so someone more used with "multiple FeatureTypeStyle" would be in better position to evaluate this PR (Please help  @jgrocha @aaime ). BTW I'll dig into the SLD specification and I'll check if this PR can introduce regression.
I suppose we can ask for unit tests to the author because of we forgot this PR since two years!

**Comment by luipir** [comment]
tested the PR and it works, btw the exported SLD from the style imported from a multiple FeatureTypeStyle is converted in a single FeatureStyle with rules.

the reimported (or the expoprted rules) does not follow the stroke size, but this error it's not related with this PR.

now checking the code

**Comment by luipir** [comment]
@nyalldawson I approve this PR
btw, probably because it's an old PR, I'm not able to start and approve the review

**Comment by luipir** [comment]
@nyalldawson any problem merging this PR?

**Comment by luipir** [comment]
@Roel are you able to add unit tests? later this PR, we introduced politics to add features only if with unit tests. I know this PR is really old, and was before this community changes. Btw would allow better and more reliable sw if you can add unit tests with this feature. You can be inspired by other SLD related unit tests in the current master.
Tnx

**Comment by m-kuhn** [comment]
@Roel what is the status of this, do you have the possibility to continue this work? Looks like there's a tiny change missing to resolve a merge conflict and a small sample to test the import. Would be a great new feature!

**Comment by m-kuhn** [comment]
Superseded by https://github.com/qgis/QGIS/pull/7125 (rebased version)

**Pull request closed without merging**
