### PR TITLE
[Feature][Processing] GRASS v.net modules

### PR DESCRIPTION
**Pull request by ghost**
This PR introduces GRASS7 v.net modules into QGIS Processing:
v_net_processing
## Things that work
- All modules can be used standalone: there is no need to use v.net before.
- Most of the cost columns for arcs or nodes can be used.
- Outputs can be dependent from algorithm parameter (for example: v.net.bridge can produce a layer with nodes when parameter method is 'articulation' and can produce a line layer when parameter method value is 'bridge').
- Most of the time, a v.net algorithm will use two inputs: a line layer for the graph and a node layer.
- Points integration is made with v.net -s option: if your points are not already on the network, they will be snapped on the graph and no new lines will be created. I've made this choice because, most of the time, new lines don't have values for arc cost columns and this breaks algorithm process.
- v.net.distance uses three layers: graph (lines), from layer (points), to layer (points).
- v.net.salesman produces two outputs: the main path (as a line layer) and the sequence of points (as a Table).
## Things to fix with other PRs
- I have just make the port for GRASS7 (because I am working on Debian testing) but I will make another PR for GRASS6 whenever this PR will be merged.
- v.net.steiner doesn't work due to a bug in GRASS7.
- v.net.timetable is not integrated because I haven't found a way to make it to work (I need a complete command list starting from empty data to be able to build the module for Processing, GRASS documentation for v.net.timetable is quite sparse).
- I've worked with GRASS7.0.2 (Debian version) and not with GRASS7.1 which introduces [turn tables](https://grasswiki.osgeo.org/wiki/Turns_in_the_vector_network_analysis). So there is no turn tables parameters.
## Main problem and code implementation

The major problem for this integration was the fact that a GRASS network map has at least two layers:
- a line layer for the graph.
- a point layer for nodes on which you want to launch the algorithm.

This data structure cannot be used directly into QGIS. When you read GRASS documentation of most of the v.net modules, you find that you always need to prepare the graph with the v.net command, mainly to import points into the graph.

This cannot be done with the actual GRASS Processing module which rely on only one command.

I've used the 'ext' mechanism for v.net modules. This is the easiest way I've found to be able to call dedicated commands for each v.net module. I could have used class hierarchy but I've found that I need to modify more files than with the 'ext' mechanism.

The 'ext' mechanism already implemented in Processing just try to find a python file in the grass7/ext directory for the current algorithm. The Python files are named like: v_net_alloc.py for v.net.alloc module. When the file exists, it is loaded and the local functions are executed instead of the Grass7Algorithm ones.

To make it work, I've broken Grass7Algorithm.py main process method (processAlgorithm) into three parts:
- processInputs: this method is used to load data from QGIS into a temporary GRASS database.
- processCommand: this method deals with GRASS commands to make the algorithm work with the previously imported data.
- processOutputs: this method handles all of the outputs of the algorithm.

For v.net modules I needed a way to be able to add v.net and v.db.connect commands to incorporate point layers before the main algorithm command. I also needed a way to deal with multiple outputs or outputs that depend on parameters. I use processCommand and processOutputs for this. I've also made the commands list a public attribute of Grass7Algorithm class.

The main code is in ext/v_net.py  which is imported into every v_net_*.py files (for factorization). Some modules have dedicated code. I have found that 'ext' mechanism is very simple to use and I've made few modifications to Grass7Algorithm to make it to work.

Feel free to read the code and tell me what needs to be changed to be merged into QGIS Processing code.

Well, now it's time to say it: Happy new year to all QGIS contributors !

### CODE REVIEW

**Comment by gioman** [comment]
assigned @volaya @alexbruy

**Comment by alexbruy** [comment]
IMHO outputs should not depend on algorithm parameters. It is better to provide two versions of algorithm for each output type or always generate two outputs.

**Comment by medspx** [comment]
@alexbruy 
Ok, there are few algorithms where output type is dependent from parameters:

* v.net.bridge
* v.net

I can break it into the following Processing algorithms:
* v.net.bridge => line output of v.net.bridge with 'bridge' method.
* v.net.articulation => point output of v.net.bridge with 'articulation' method.
* v.net.connect => 'connect' operation of v.net (network output).
* v.net.nodes => 'nodes' operation of v.net (points output).
* v.net.arcs => 'arcs' operation of v.net (network output).
* v.net.reports => 'reports' and 'nreports' operations of v.net (two tables output).

As a benefit, v_net.py variableOutputs could be deleted or simplified with such transformations.

Should I do this with the above new algorithms or is there anything else ?

**Comment by alexbruy** [comment]
I'm fine with solution you proposed, but let's wait for Victor's feedback. @volaya what do you think?

**Comment by volaya** [comment]
Code looks good to me. Haven't tested the rest of algorithms in GRASS, but I would like to confirm this doesnt affect algorithms in that provider

As Alex suggests, the output type should not depend on parameters, since that complicates the situation for the modeler. The semantic of the algorithm should be fixed and constant, so if you can do that change that he suggests, I think this would be ready for merging

Great works, thanks a lot!

**Comment by medspx** [comment]
Ok, I'll work on it as soon as possible...

**Comment by medspx** [comment]
@volaya @alexbruy 
Ok, I've made the changes... It seems to work because I've made lots of tests on v.net modules and I haven't found more bugs than previous. I've also made some tests with other v.* GRASS7 modules and the modifications in Grass7Algorithm.py don't seem to break anything. I could not test all GRASS7 modules so there could be new bugs but we've got one month after freeze to deal with them.

**Comment by alexbruy** [comment]
Thanks for contribution!

**Pull request merged**
