### PR TITLE
 [pyqgis] Ensure that multiline param tags are indented for additional lines

### PR DESCRIPTION
**Pull request by nyalldawson**
Should fix a number of the open issues with the PyQGIS documentation.

### CODE REVIEW

**Review by 3nids — APPROVED** [review]
why indenting rather than adding a new line?
I'm just afraid it will not look very nice when you type help() in the console.
If you think you can switch to new line, LGTM and if you think we cannot, well LGTM too :)

**Comment by nyalldawson** [comment]
I don't think a new line would work. There's almost zero docs on this, but all I could find was https://stackoverflow.com/q/32566466/1861260 which suggests that indentation is the correct approach

**Comment by 3nids** [comment]
ok, but then maybe use new lines after deprecated and since tags, sounds good to you?

**Comment by nyalldawson** [comment]
Do you mean indent multiline since/deprecated, but put a new line after the final line in them?

**Comment by 3nids** [comment]
I was thinking that we need indent in multiline parameters, but not just after since/deprecated. Isn't a new line sufficient there?

Also, give a look at my comment for the regex, I think it misses something

**Comment by nyalldawson** [comment]
Will definitely look into the regex.

To me it seems logical that if multiline Param/returns need to be indented, the same would apply to the other tags too. But let's try the newline approach first (if I can work out the sipify changes needed) and then just see what the result is :)

**Comment by nyalldawson** [comment]
@3nids Turns out there's no valid multiline versionadded/deprecated tags anyway. All deprecated tags are single line, and the only multiline versionadded tags are incorrect anyway (and are fixed by #7081)

So I've reverted the indentation change to versionadded/deprecated

**Pull request merged**
