### PR TITLE
0vars.cmake, FindSIP: Update to save new sip_module_dir variable

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
sip4 has changed sip_mod_dir to sip_module_dir.
Store the variable for later usage

followup PR after:
#7365
#7366

### CODE REVIEW

**Comment by 3nids** [comment]
as mentioned in #7366, you have to update https://github.com/qgis/QGIS/blob/master/cmake/FindSIP.py#L46 to reflect this.

**Comment by LocutusOfBorg** [comment]
done!

**Comment by 3nids** [comment]
Thanks a lot for this @LocutusOfBorg, but can you precise what you are trying to fix here?
To me, the situation before with the single variable was clearer. Maybe you want to remove and rename the old one to the new one.
But please precise your intention here.

**Comment by LocutusOfBorg** [comment]
yes, the intention was to make it clear, and probably in the future we will be able to drop the old mod_dir version, so better switch the default right now.
Does it look better now? I can merge the two commits together if you agree

**Comment by 3nids** [comment]
maybe in the future, we might be able to drop SIP itself, which would be even better ;)
thanks for this

**Comment by LocutusOfBorg** [comment]
:) thanks!

**Pull request merged**
