### PR TITLE
Some locator fixes

### PR DESCRIPTION
**Pull request by 3nids**
* fix display title expression not displayed anymore in the results
* active locator filter also search in display title
* optimize scale for point layers in QgsMapCanvas::zoomToFeatureIds

### CODE REVIEW

**Comment by nyalldawson** [comment]
https://github.com/qgis/QGIS/pull/38908/commits/2ae418da24616b1f1fb809796f17d0d9d599f566 looks like a feature to me!

**Comment by 3nids** [comment]
> 2ae418d looks like a feature to me!

That's a copy paste from the all layers filter.
I think it's quite an expected behavior.

But if preferred I can leave it aside.

**Comment by andreasneumann** [comment]
> [2ae418d](https://github.com/qgis/QGIS/commit/2ae418da24616b1f1fb809796f17d0d9d599f566) looks like a feature to me!

Yes, it's an edge case. It is a new feature - but it makes the search much more useful. The display attribute is normally the combination of attribute columns most interesting to the user. I could only test it very close to feature freeze and we couldn't make it before the freeze.

If not acceptable, let's move it to 3.18 then.

**Comment by nyalldawson** [comment]
It makes me slightly nervous, especially given there's no tests covering it (hint hint)

**Comment by 3nids** [comment]
test added

**Comment by 3nids** [comment]
I completed with test for the display expression part + added test for the completion.

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
