### PR TITLE
qgscurvepolygon: Fix clear in copy operator

### PR DESCRIPTION
**Pull request by ptitjano**
## Description

Clearing the cache is not enough, a full clear is needed.

Based on the discussion from https://github.com/qgis/QGIS/pull/58583#discussion_r1745634447

### CODE REVIEW

**Comment by rouault** [comment]
Can we have a C++ test showing that this is needed (so initializing a curvepolygon to non-empty, and then copy-assigning it another non-empty curvepolygon)

**Comment by ptitjano** [comment]
> Can we have a C++ test showing that this is needed (so initializing a curvepolygon to non-empty, and then copy-assigning it another non-empty curvepolygon)

I have added a new test this way but it does not fail with the `clearCache` call.
I did the same test for `QgsPolyhedralSurface` and it also does not fail. It looks like a call to `clearCache` is enough.

**Comment by rouault** [comment]
> Or maybe, my test is wrong?

I don't know. By just code inspection, it seems to me that clearCache() is not enough , since it doesn't reset mExteriorRing or mInteriorRing, and they should obviously be reset before appending the rings of the copied geometry
The other theory would be that == is wrong, but it looks sane to me.

**Comment by ptitjano** [comment]
> > Or maybe, my test is wrong?
> 
> I don't know. By just code inspection, it seems to me that clearCache() is not enough , since it doesn't reset mExteriorRing or mInteriorRing, and they should obviously be reset before appending the rings of the copied geometry The other theory would be that == is wrong, but it looks sane to me.

I think I understoord why it works: 
- The copy assigning operator calls `QgsSurface::operator=`
- `QgsSurface` does not override `operator=`, therefore `QgsAbstractGeometry::operator=` is called
- `QgsAbstractGeometry::operator=` calls `clear()`

In conclusion, I think this is not needed to call `clear()` or even `clearCache()` in `QgsCurvePolygon` or `QgsPolyhedralSurface` because it is already done by `QgsAbstractGeometry::operator=`

**Comment by rouault** [comment]
Thanks for the investigation. Yes removing the call to clearCache() might avoid any confusion. (I also see there's one in QgsCompoundCurve::operator=() and QgsGeometryCollection::operator=(), but I'm not asking you to clear all QGIS geometry code ;-))

**Comment by ptitjano** [comment]
> Thanks for the investigation. Yes removing the call to clearCache() might avoid any confusion. (I also see there's one in QgsCompoundCurve::operator=() and QgsGeometryCollection::operator=(), but I'm not asking you to clear all QGIS geometry code ;-))

Did that.
However, cppcheck now returns some false positives: https://github.com/qgis/QGIS/actions/runs/10725497032/job/29743455266?pr=58587
I have added a `cppcheck-suppress operatorEqVarError`

**Review by rouault — APPROVED** [review]

**Pull request merged**
