### PR TITLE
Fix massive memory leak in PyQGIS, pt 1

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes the first part of the NULL PyQGIS mother of all leaks

### CODE REVIEW

**Comment by wonder-sk** [comment]
Well done!

**Comment by NathanW2** [comment]
Merge it?

**Comment by nyalldawson** [comment]
> Merge it?

I'm not confident yet - I'm seeing a crash which may be related (or not)...

**Comment by nyalldawson** [comment]
I'm merging this, as triple-checked and the changes are correct.

It brings some instability with the Python bindings - it seems the created Python objects are sometimes being deleted internally by Python resulting in invalid reads, but that's a different issue and does not change this part of the fix.

**Pull request merged**
