### PR TITLE
Remove startup tips

### PR DESCRIPTION
**Pull request by nyalldawson**
Because:

1. They tend to be outdated and infrequently updated
2. They are a "dated" software concept. Most other applications have moved away from startup tips to a startup "welcome page" type approach.

### CODE REVIEW

**Comment by NathanW2** [comment]
+1

**Comment by DelazJ** [comment]
Hmmm I don't find them that outdated; i fixed a bunch of them lately.
But if you have another system in mind....

**Comment by nyalldawson** [comment]
@DelazJ 

What we are planning is to head towards an improved startup experience in future releases. In Nodebo we discussed tweaking the current "Recent Projects" panel to split it into multiple sections. One would contain a list of "project templates", and we'd ship out of the box with 2-3 existing templates which contain just a single XYZ OpenStreetMap background layer. This would mean that on startup new users would be the ability to instantly start with a map which is "ready to go".

We also discussed adding a curated news feed in this panel, so that we can push information about community events, releases, crowdfunding campaigns, and other important topics we need to communicate with ALL our users. (This would be "opt-out" - so shown by default, but if closed there would be an option to "never show QGIS news again").

The final part discussed was adding "one-off" startup news items, which would inform users of important changes once after installing a new version of QGIS.

With these changes we'd have a more modern startup experience which does a better job of gently guiding new users into using QGIS. I feel that removing the startup tips is an essential part of this, otherwise we risk presenting TOO much content to users immediately on startup.

**Comment by wonder-sk** [comment]
Yes please! A modal dialog to jump at you at the startup is not great...

**Comment by DelazJ** [comment]
@nyalldawson Thanks for your patience and the summary. Great plans, there; reason why people should not miss this kind of community meeting 😢

**Comment by nyalldawson** [comment]
@DelazJ so you're in favour of this approach? (and removing the startup tips?)

**Comment by nyalldawson** [comment]
Also keen for your thoughts @timlinux

**Comment by DelazJ** [comment]
@wonder-sk Startup tips are opt-out so if someone is bothered by this modal dialog, I guess he can deactivate it. Honestly these tips have been helpful to me when i began with QGIS (that doesn't mean it shouldn't be replaced by something better).

@nyalldawson I'm not sure the two systems can live together; it'll crowd the dialog for the users, I guess. What I do not like in current tips is that they are often big pieces of text in a sober dialog, without images (or some colorful things). But as said above I think these contain valuable materials that we should not lose.
And I miss them in the proposed solution. The "one-off" startup, the default map sound handy features. The feeds system will, I guess, help us get in touch with the wider community (though I'm not personally fan of features that make go out from the application I'm running; I'm afraid I spent time on reading news rather than using QGIS :). However it'll be inline with the help system).  But none of these options shows tips to the beginners (unfortunately, not everybody takes the time to consult documentation).
That said, I'm in favor of moving ahead with a more modern, helpful and inclusive system.

*Side note*: I hope that there'll be a possibility to manually remove projects from the recent projects list shown at startup (either because they no longer exist or for confidentiality as expressed in the list a while back).

**Comment by m-kuhn** [comment]
In my experience there are two kind of people.

* The ones who click the checkbox (some do curse, some don't)
* The ones who repeatedly click close on every launch (they never curse)

I've never observed someone actually read them. Maybe people read them only when they are alone. I should do a little survey on that.

The main problems I see with the current dialog (some have been mentionned before)

* Once opted out I cannot get them back easily
* As long as I want to keep them available I have to click an extra button every start
* They are often dated
* Too text oriented

IMO we should offer help in the first line closeby and context aware. In the second line we can also offer some get started or explore topics, but they should be on demand and not in your face.

I could very well imagine a welcome screen section with this. Especially on the empty first run screen. If it becomes too crowded there we can still tab (parts of) the screen. 

+1 from my side, and I like the move towards adding content to the welcome screen.

**Pull request merged**
