### PR TITLE
[PROCESSING] Speed up dissolve (esp. when using dissolve field)

### PR DESCRIPTION
**Pull request by bstroebl**
Change parameters to have a more consistent UI

### CODE REVIEW

**Comment by bstroebl** [comment]
Replaces old pull request #2263

**Comment by m-kuhn** [comment]
Good stuff.

**Comment by m-kuhn** [comment]
I realized that this is actually really a processing algorithm and different from the one in the vector menu. So we actually ship two different versions of this algorithm, I always thought that processing would use the ones that were already in place. That's not related to this PR, but I think we should consider to consolidate that.

**Comment by m-kuhn** [comment]
Merged in 116089e6

**Comment by bstroebl** [comment]
Hi Matthias, I seem to remember, that fTools (Vector menu stuff) is going to be replaced by Processing as soon as all algorithms have been ported to Processing. Therefore I did not consider implementing this in fTools. And as a user I would always assume that if the same function exists in both, Processing is what I am supposed to use.

**Comment by m-kuhn** [comment]
We could as well delete one of the two algorithms and use the same from
both the menu and the toolbox. Maintaining them both individually sounds
like an unnecessary overhead.

Having knowledge about which menuitems are provided by which plugin is
already a good portion of expert knowledge (that a user should not have
to care about).

**Comment by bstroebl** [comment]
So, this is a good reason to port what is left to Processing and get rid of fTools the sooner the better. Alternatively delete all menu items from fTools that contain algorithms already in Processing (but that is en effort better used for porting). Let's continue this discussion on the dev mailing list.

**Comment by m-kuhn** [comment]
Good idea. Can you raise the issue on the mailing list?

**Comment by bstroebl** [comment]
done :-)

**Pull request closed without merging**
