### PR TITLE
file writer metadata: add (Geo)Arrow and (Geo)Parquet drivers (fixes #51165)

### LINKED ISSUE #51165: Editing GeoArrow and GeoParquet geometries
### Feature description

I'm very happy to see that with the (experimental) inclusion of GeoArrow and GeoParquet support in GDAL 3.5, QGIS can read and visualize these files.

According to the GDAL driver page, the drivers supports creation:
https://gdal.org/drivers/vector/arrow.html
https://gdal.org/drivers/vector/parquet.html#vector-parquet

It looks like the QGIS OGR provider simply isn't aware of this yet. E.g. I cannot choose these formats when right-clicking a vector Layer, and choosing "Export > Save Features as ...", in QGIS 3.28.1. From a quick scan of the source code, it seems like drivers are provided to the driver metadata, and I don't see these formats listed.

I would guess no one has gotten down to creating the entries for GeoArrow/GeoParquet. Or it is much more complicated / is there a principled reason not to allow creation & editing?

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@rouault do you know the history behind this code? It strikes me as the wrong place for all this, and we should be querying it from gdal directly. But maybe I'm missing something, eg if this was all done for translation purposes or something...

**Comment by rouault** [comment]
> do you know the history behind this code?

not more than git blame pointing to f78af8bd3ba

> It strikes me as the wrong place for all this, and we should be querying it from gdal directly

I had exactly the same feeling when editing it... I suspect it dates back from a time where GDAL metadata might have been a bit lacking. Or perhaps the translation thing too. There are also a few tweaks like creating a Spatialite pseudo-format that is a "profile" of the generic SQLite with SPATIALITE=YES forced. It is also the opportunity to remove a few esoteric options too

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
IIRC metadata was not easily around from gdal (or I was missing it). But translation is a good reason to keep (at least parts of this)

**Comment by nirvn** [comment]
@rouault , do we need to have a `#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3,?,?)` somewhere here?

**Comment by rouault** [comment]
> do we need to have a `#if GDAL_VERSION_NUM >= GDAL_COMPUTE_VERSION(3,?,?)` somewhere here?

This isn't strictly needed. There is logic elsewhere that takes into account the dynamically loaded drivers to intersect this list with the list of available drivers.

**Pull request merged**
