### PR TITLE
[Backport release-3_28] [Fix] Server WFS: Date time with ISO Date time field format

### PR DESCRIPTION
**Pull request by rldhont**
Manually Backport https://github.com/qgis/QGIS/pull/49438
Authored by: @rldhont

### CODE REVIEW

**Comment by rldhont** [comment]
Not stale, just waiting for e review.

**Comment by rldhont** [comment]
@pblottiere can you review like you do for the master PR ?

**Review by pblottiere — APPROVED** [review]

**Comment by pblottiere** [comment]
(sorry for the delay)

**Comment by rldhont** [comment]
Thanks @pblottiere and @elpaso

**Pull request merged**
