### PR TITLE
Random Points on Lines algorithm followups

### PR DESCRIPTION
**Pull request by nyalldawson**
Some code cleanups and new features for the Random Points on Lines algorithm

### CODE REVIEW

**Comment by nyalldawson** [comment]
Ping @havatv

**Review by alexbruy — APPROVED** [review]

**Comment by havatv** [comment]
> Ping @havatv

Not "alive" at the time... (gone to bed).

Comments:
* Nice to make algorithm parameters data-definable!
* I still don't understand why the random algorithm had to be changed.
* I will check the logic of the progress reporting and the maximum number of tries.
* I found a "spelling mistake" in a variable name. Will make a PR to correct.
* After your updates, the algorithm "crashes" when there is a selection and one chooses "Selected features only":

>   WARNING    Traceback (most recent call last):
>               File "/home/tveite/apps/share/qgis/python/plugins/processing/gui/AlgorithmDialog.py", line 211, in runAlgorithm
>               if isinstance(parameters.get(param.name(), None), QgsProcessingFeatureSourceDefinition) and parameters[param.name()].flags & QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature:
>              TypeError: unsupported operand type(s) for &: 'Flags' and 'Flag'

**Comment by nyalldawson** [comment]
@havatv 

> I still don't understand why the random algorithm had to be changed.

It didn't **have** to be, but we are trying to use modern best-practice c++ everywhere possible in QGIS, and this is the recommended approach for c++11 and later.

> After your updates, the algorithm "crashes" when there is a selection and one chooses "Selected features only":

That's unrelated, but thanks for reporting!

**Comment by nyalldawson** [comment]
@havatv 
More details here: https://en.cppreference.com/w/cpp/numeric/random/rand

"There are no guarantees as to the quality of the random sequence produced. In the past, some implementations of rand() have had serious shortcomings in the randomness, distribution and period of the sequence produced (in one well-known example, the low-order bit simply alternated between 1 and 0 between calls).

rand() is not recommended for serious random-number generation needs. It is recommended to use C++11's random number generation facilities to replace rand(). (since C++11)"

**Comment by nyalldawson** [comment]
> WARNING Traceback (most recent call last):
File "/home/user/apps/share/qgis/python/plugins/processing/gui/AlgorithmDialog.py", line 211, in runAlgorithm
if isinstance(parameters.get(param.name(), None), QgsProcessingFeatureSourceDefinition) and parameters[param.name()].flags & QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature:
TypeError: unsupported operand type(s) for &: 'Flags' and 'Flag'

I can't reproduce this -- which sha is your build based on?

**Comment by havatv** [comment]
Random: I also found some web pages that warned about *rand* when I was checking how to generate seeded random number sequences with C++. Since I could not imagine that anyone would have problem with a non-perfect random number generator when using this algorithm, I decided to go for the simple solution (that looked much like Java, Python and Pascal random functions).  I have no problem with using more advanced techniques, but thought it would be overkill for this algorithm.

> I can't reproduce this -- which sha is your build based on?

I grabbed master through github and compiled.

**Comment by nyalldawson** [comment]
@havatv 
>  I have no problem with using more advanced techniques, but thought it would be overkill for this algorithm.

See, I'm of the opinion that we should due diligence to try to make sure that we give as-random-as-possible results from these algorithms. And as the change is relatively trivial, follow best practice guidelines, and doesn't add any maintenance burden, I can't see why we **wouldn't** do this! :smile: 

> I grabbed master through github and compiled.

Any chance of a screencast?

**Comment by havatv** [comment]
I am fine with the more advanced and flexible random number generator, even if the flexibility means that it is slightly more complicated and requires a few extra lines of code.

> Any chance of a screencast?

Not familiar with that.
Besides, I guess I should get some sleep soon.

**Comment by nyalldawson** [comment]
@havatv 
> Not familiar with that.

I use "peek" for this -- it's nice an simple to use. I just can't reproduce this locally to fix...

**Comment by havatv** [comment]
What I did was to build from master, start QGIS, select a line in a line layer (LineStringZ, geopackage, EPGS:32632), run the algorithm with default parameters.

Another strange thing was that when starting the algorithm, the line layer with the selected line was in the Input layer selection, but the "Selected features only" checkbox was disabled / grayed out. But when I used the pull-down to select it, the box became enabled, and I could check it.

**Comment by havatv** [comment]
> * 
> 
> * After your updates, the algorithm "crashes" when there is a selection and one chooses "Selected features only":

I am not happy with this issue. Perhaps we should wait with data-defining the parameters until this has been solved.  Running the algorithm on selected features would be one of the most common use-cases for it.  Creating a new layer with the features to generate points on is a bit clumsy.

I also tried setting "Limit features processed" to 10 in the "Advanced options" of the Input layer, and that resulted in a crash with the same error message.

**Comment by nyalldawson** [comment]
Come on @havatv -- work with me here. It's
1. unrelated to this work, completely
2. unreproducible locally. I need more details. I can't do ANYTHING till you provide them.

**Comment by havatv** [comment]
Of course I want to cooperate, but now it is time for some sleep.

**Comment by nyalldawson** [comment]
:smile: 

(and from my end - my kids have totally used up what patience I have left... so the internet gets grumpy me only these days)

**Comment by nyalldawson** [comment]
Can you confirm your python version and PyQt version tomorrow?

**Comment by havatv** [comment]
Sorry for not being more helpful.

Here are some details.

> $ python3
> Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
> [GCC 8.3.0] on linux

> QGIS version | 3.13.0-Master | QGIS code revision | 4136187fe3
> -- | -- | -- | --
> Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
> Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
> Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
> Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
> PostgreSQL Client Version | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
> QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
> PROJ.4 Version | 493
> OS Version | Ubuntu 18.04.4 LTS
> Active python plugins | pluginbuilder3; plugin_reloader; SDEllipse; qgisnetworklogger; QGIS-ResourceSharing-tree-gui; LineDirectionHistogram; processing_taudem; processing_r; MetaSearch; processing; db_manager

Regarding the screencast - I don't understand what additional information you can get from it. What can I do to make a screencast that is helpful for you?

**Comment by nyalldawson** [comment]
What happens when you enter 

    QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature & QgsProcessingFeatureSourceDefinition.Flags()

in the python console?

**Comment by nyalldawson** [comment]
and if that errors, does

    int( QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature ) & int( QgsProcessingFeatureSourceDefinition.Flags() )

work? (return 0)

**Comment by havatv** [comment]
> What happens when you enter
> 
> ```
> QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature & QgsProcessingFeatureSourceDefinition.Flags()
> ```
> 
> in the python console?

This is what happens:

> \>\>\> QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature & QgsProcessingFeatureSourceDefinition.Flags()
> TypeError: an integer is required (got type Flag)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/code.py", line 91, in runcode
>     exec(code, self.locals)
>   File "<input>", line 1, in <module>
> SystemError: <class 'qgis._core.Flags'> returned a result with an error set

------------------------------------------------------------------

> and if that errors, does
> 
> ```
> int( QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature ) & int( QgsProcessingFeatureSourceDefinition.Flags() )
> ```
> 
> work? (return 0)

This is what happens:

> \>\>\> int( QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature ) & int( QgsProcessingFeatureSourceDefinition.Flags() )
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/code.py", line 91, in runcode
>     exec(code, self.locals)
>   File "<input>", line 1, in <module>
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'Flag'

**Comment by nyalldawson** [comment]
Bah freaking PyQt!!! 

can you find any imaginative hack which makes this line work? If you do something silly like `int(str(....))` does it help?

**Comment by havatv** [comment]
The error seems to come from initAlgorithm. I tried to comment out everything else than the declaration of the data defined parameters (), and still got a crash.

**Comment by havatv** [comment]
> Bah freaking PyQt!!!
> 
> can you find any imaginative hack which makes this line work? If you do something silly like `int(str(....))` does it help?

Like this?:

> \>\>\> int( str( QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature ) & int( QgsProcessingFeatureSourceDefinition.Flags() ) )
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/code.py", line 91, in runcode
>     exec(code, self.locals)
>   File "<input>", line 1, in <module>
> TypeError: unsupported operand type(s) for &: 'str' and 'int'

**Comment by nyalldawson** [comment]
Actually try this:

    QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature.value & int(QgsProcessingFeatureSourceDefinition.Flags())

**Comment by havatv** [comment]
> \>\>\> QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature.value & int(QgsProcessingFeatureSourceDefinition.Flags())
> 0

In fact, I just looked up Python `enum` and found the `value` attribute. Tested it at the same time as you suggested this... :-)

**Comment by havatv** [comment]
The error disappeared when I modified AlgorithmDialog.py:

>                 if isinstance(parameters.get(param.name(), None), QgsProcessingFeatureSourceDefinition) and parameters[param.name()].flags & QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature:


to

>                 if isinstance(parameters.get(param.name(), None), QgsProcessingFeatureSourceDefinition) and parameters[param.name()].flags & QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature.value:

**Comment by nyalldawson** [comment]
Can you test if https://github.com/qgis/QGIS/pull/35504 fixes this?

**Comment by havatv** [comment]
I updated my master clone with  #35504 (did not pull master), but still crash:

> 2020-04-01T13:47:57     WARNING    Traceback (most recent call last):
>               File "/home/tveite/apps/share/qgis/python/plugins/processing/gui/AlgorithmDialog.py", line 211, in runAlgorithm
>               if isinstance(parameters.get(param.name(), None), QgsProcessingFeatureSourceDefinition) and parameters[param.name()].flags & QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature:
>              TypeError: unsupported operand type(s) for &: 'Flags' and 'Flag'

Using `value`(as I did in #35491) did get rid of the error, and the algorithm output looked fine.
I don't know if this is relevant: QGIS code revision 14d10cb943

**Comment by havatv** [comment]
@nyalldawson, it would be great to have this fixed. What are the disadvantages of using `value` as in this diff (python/plugins/processing/gui/AlgorithmDialog.py) - cut and paste from #35491:

```
-                if isinstance(parameters.get(param.name(), None), QgsProcessingFeatureSourceDefinition) and parameters[param.name()].flags & QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature:
+                if isinstance(parameters.get(param.name(), None), QgsProcessingFeatureSourceDefinition) and parameters[param.name()].flags & QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature.value: 
```

**Comment by nyalldawson** [comment]
@havatv checkout https://github.com/qgis/QGIS/pull/35515 -- I think the issues go deeper than that one line, as the test was giving unexpected results and I lost confidence in the behavior of enum class on older Python/sip versions. In the end it was safer to use the older approach

**Comment by havatv** [comment]
> @havatv checkout #35515 -- I think the issues go deeper than that one line, as the test was giving unexpected results and I lost confidence in the behavior of enum class on older Python/sip versions. In the end it was safer to use the older approach

Looks perfect to me. Thanks, @nyalldawson!

**Pull request merged**
