### PR TITLE
Increase max zoom level for landing page

### LINKED ISSUE #45768: QGIS server leaflet zoom after 19 and language
### What is the bug or the crash?

Impossible to change the language of qgis-server even after setting the environement variable in systemd service
And the webview seem unable to render wms layers after zoom 19.

server is deployed at igp.metrotopic.net is you want to test it 

### Steps to reproduce the issue

Opening a wms layer on wgis-server web and zoom

### Versions

3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cazitouni**
## Description

Override the max leaflet zoom of 18, fixes #45768

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]
Looks good to me
Cc @elpaso

**Comment by elpaso** [comment]
LGTM too but the compiled js files needs to be updates as well.

They are in https://github.com/qgis/QGIS/tree/master/resources/server/api/ogc/static/landingpage

**Comment by m-kuhn** [comment]
> LGTM too but the compiled js files needs to be updated as well.

Is the process to update documented somewhere?
Would it be good to open an issue to move this to the build process as generated artifacts?

**Comment by elpaso** [comment]
> > LGTM too but the compiled js files needs to be updated as well.
> 
> Is the process to update documented somewhere? 

Yes (just follow the links):  https://github.com/qgis/QGIS/tree/master/resources/server/src/landingpage

> Would it be good to open an issue to move this to the build process as generated artifacts?

Of course yes but it won't be easy: js development is a bit of an alien to QGIS building env, given the very low frequency of updates I'm not sure it worths it.

**Comment by m-kuhn** [comment]
> > > LGTM too but the compiled js files needs to be updated as well.
> > 
> > 
> > Is the process to update documented somewhere?
> 
> Yes (just follow the links): https://github.com/qgis/QGIS/tree/master/resources/server/src/landingpage

Ah right, sorry !

> 
> > Would it be good to open an issue to move this to the build process as generated artifacts?
> 
> Of course yes but it won't be easy: js development is a bit of an alien to QGIS building env, given the very low frequency of updates I'm not sure it worths it.

Done https://github.com/qgis/QGIS/issues/46040
The main reason for me is that generated files regularly give results for `git grep` that make the terminal overflow because of the line length and hiding any following search results.

**Pull request closed without merging**
