### PR TITLE
Layout map item grids

### PR DESCRIPTION
**Pull request by DelazJ**
Before
image

Because the interval x/y min/max elements are put under a stackedwidget, they are not aware of the alignment of the other features in the GUI. The PR removes the stackedwidget.
After

image

The fix works. Now is it the right/best way? And not sure also about the doc and methods/parameters naming.
Also @nyalldawson is the no margin in the widget deliberate? I can see it's also the case when setting the map item labeling properties

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by nyalldawson** [comment]
This was originally done to indicate that the x/y settings apply to the interval -- which is no longer immediately apparent.

**Comment by nirvn** [comment]
@nyalldawson , isn't the 'interval [ map unit ]' line a bit misleading since I assume offsets also use the unit type set there?

I propose:

```
Unit type ______ [ Map unit ]
                           [ X 0.000   ]
Interval
                           [ Y 0.000   ]
                           [ X 0.000   ]
Offset
                           [ Y 0.000   ]
```

**Comment by DelazJ** [comment]
>This was originally done to indicate that the x/y settings apply to the interval -- which is no longer immediately apparent.

Indeed, I did not remark the "indentation"; I was more focused on the spinbox size & alignment. Adding a horizontal spacer at the left of the interval subitems could do the trick, no?

**Comment by DelazJ** [comment]
@nirvn the dialog provides also this:
image

**Comment by DelazJ** [comment]
Edited the screenshot with the offset

**Comment by DelazJ** [comment]
Gone stale... 🙄

**Pull request closed without merging**
