### PR TITLE
Cleanup python libraries

### PR DESCRIPTION
**Pull request by m-kuhn**
Cleans up python libraries
Bumps python libraries to latest versions

- Removes an outdated `py-qscintilla` overlay port (is now consumed from open-vcpkg/python-registry)
- Removes `py-qgis-requirements` (no more pip installs) to unify the install process of shipped python libraries
- Add a `gdal` an updated to 3.9.3 overlay port (there were some troubles with setup.py / installation prefix, I'll try to upstream this later)
- `py-lxml2` is not detecting the `libxml2` and `libxslt` libraries, will need to look into that later

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by m-kuhn** [comment]
Package caching fails because we are reaching a spending limit, because packagess are flagged as "private". There is no need for these to be private, but I fail to change visibility manually, because "this has been disabled by organization admin"

E.g. "change package visibility" here https://github.com/orgs/qgis/packages/nuget/vcpkg-cmake-config_x64-windows-release/settings

Does anyone know if there is a reason for this and if it can be changed (I am not an organization admin)

**Comment by nyalldawson** [comment]
@m-kuhn ok, that's done!

**Comment by m-kuhn** [comment]
> @m-kuhn ok, that's done!

thanks, confirmed that new packages are now public

**Comment by nyalldawson** [comment]
@m-kuhn should we disable the broken workflow on master for now? Is a fix far away?

**Comment by m-kuhn** [comment]
@nyalldawson I am confident this can be fixed today

**Comment by m-kuhn** [comment]
The remainder is an issue introduced by https://github.com/qgis/QGIS/pull/59160

**Comment by m-kuhn** [comment]
let me merge this, the fix should be delivered somewhere else and it's easier to check if a fix is working with this code in place

**Pull request merged**
