### PR TITLE
Also install MIME type icon in hicolor theme.

### PR DESCRIPTION
**Pull request by sebastic**
The qgis-mime icon should also be installed in the hicolor theme in the same fashion as the [application icon](http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#install_icons).

Additionally the [Shared MIME-info](http://standards.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-latest.html) configuration is updated to reference the icon by name (without extension) like the [desktop](http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html) files.

### CODE REVIEW

**Comment by m-kuhn** [comment]
It's probably not directly related to this PR but it would be great to have the new QGIS logo used on this icon.

**Comment by mach0** [comment]
We do have a _new_ QGIS logo? ;)

**Comment by sebastic** [comment]
> [...] it would be great to have the new QGIS logo used on this icon.

Recreating `qgis-mime-icon.png` using `qgis_icon.svg` is probably a good idea to have an SVG icon for the `qgis-mime` icon too.

**Comment by m-kuhn** [comment]
Old
===

Old

Revamp
======

New

**Comment by sebastic** [comment]
I've played a bit with an SVG icon for qgis-mime: [qgis-mime-icon.svg](https://github.com/sebastic/QGIS/blob/qgis-mime-icon-svg/images/icons/qgis-mime-icon.svg)

License is GPL-2+ for qgis_icon.svg & qbrowser_icon.svg and LGPL-3+ for the file image taken from the Oxygen theme.

**Comment by m-kuhn** [comment]
Nice!
Can you make the QGIS icon bigger (especially for small icons that would be great)?

**Comment by sebastic** [comment]
I've increased the logo size in https://github.com/sebastic/QGIS/commit/5deaf55586c5a76b8a5ee87892ad3e413493b3e0, please take it from here for any further changes you'd like. I was just playing with the icon, with no actual intention to propose a new qgis-mime-icon. I rather leave that up to people with actual graphics skills. The license mix is not very desirable, so creating a new qgis-mime-icon is probably better done from scratch.

**Comment by jef-n** [comment]
manually merged as fd6bec4

**Pull request closed without merging**
