### PR TITLE
Fix Qt5Core.so error in Singularity containers

### LINKED ISSUE #46841: Qt5 error in containerized version of QGIS
### What is the bug or the crash?

I am trying to run containerized version of QGIS on a high-performance computing cluster.  Docker is not supported on the cluster (due to elevated privileges), but Singularity containers are embraced - so I am using Singularity's built-in feature to pull down QGIS container from DockerHub and convert it to Singularity format.

Conversion goes without a hitch, but execution throws a weird Qt5 error:
```
$ singularity pull qgis-3.16.sif docker://qgis/qgis:release-3_16     # generates qgis-3.16.sif
$ singularity exec qgis-3.16.sif qgis
/usr/bin/qgis: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

Which is clearly not true:
```
$ singularity exec qgis-3.16.sif find /usr -name 'libQt5Core.so.5*' -ls
   122133      0 lrwxrwxrwx   1 root     root           20 Jan  5 13:54 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 -> libQt5Core.so.5.12.8
   122134      0 lrwxrwxrwx   1 root     root           20 Jan  5 13:54 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12 -> libQt5Core.so.5.12.8
   122135   5391 -rw-r--r--   1 root     root      5519624 Jan  5 13:54 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.8
```
(note that these are inside of the container, just as they should).

It appears that this very error when running Qt5 applications in some kind of virtualized environment (Docker, Virtualbox, WSL1) is a fairly known thing.  E.g.:
  * https://stackoverflow.com/questions/63627955/cant-load-shared-library-libqt5core-so-5
  * https://github.com/linuxserver/docker-qbittorrent/issues/103
  * https://askubuntu.com/questions/1034313/ubuntu-18-4-libqt5core-so-5-cannot-open-shared-object-file-no-such-file-or-dir

For all of them, the (very bizarre, but working) solution seems to add one extra command to the Dockerfile:
```
strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```
and the problem disappears.

I was wondering if you'd be willing to add such a line to the QGIS container script.

### Steps to reproduce the issue

(assuming you have Singularity installed)
```
$ singularity pull qgis-3.16.sif docker://qgis/qgis:release-3_16
$ singularity exec qgis-3.16.sif qgis
/usr/bin/qgis: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

Observed the same for 3.22 as well.

### Versions

3.16 and 3.22 (per Docker tags)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lgorenstein**
## Description

Hopefully fixes #46841 with bizarre error when converting QGIS docker image into a Singularity container.

Sorry, I do not have suitable Docker infrastructure to test the build.

### CODE REVIEW

**Comment by m-kuhn** [comment]
This depends on the kernel version of the host os.
IMO this is to be fixed in the individual deployment and not in here.

**Comment by lgorenstein** [comment]
@m-kuhn To the best of my knowledge, stripping this section from the library will not be harmful for any kernel.  If you could make a test image with a custom Docker tag, I'd be certainly happy to test on our clusters (CentOS 7 and 8, kernels 3.10 and 4.18 series).

As for where to do it best... Note that regular HPC users have _very_ little control over deployment, and for them the whole idea of containerization is to take a pre-made image and just run it as is.  They can not use Docker.  All they can do is pull an existing docker image from DockerHub (one that you have built) - and use it with their Singularity or CharlieCloud command.  In other words, 'singularity pull' _is_ their deployment ... and as I described in #46841, this currently produces a non-functional image.

**Comment by m-kuhn** [comment]
You could write your own dockerfile that builds from this image, patches qt binaries and push it to a registry. That would create a pre-made image that your users can then pull from the registry.

**Comment by 3nids** [comment]
side remark, I think that the image we produce is not really meant to be used in production environment but rather for development and testing of the master branch.

For production, I would rather use something very simple as https://github.com/opengisch/qgis-docker/blob/master/Dockerfile (https://hub.docker.com/r/opengisch/qgis/tags)

**Comment by lgorenstein** [comment]
@m-kuhn Matthias, yes, that's fair, people certainly could do this.  OTOH, my thinking was that if I have to do it, and someone else might have to do it, then maybe it'd be better if the automatically-built image already had this incorporated in it?  This would save people effort and time of learning their way around Docker registries, containers, cyberinfrastructure and all that - and just be more productive in their main job as GIS practitioners?  I mean, _"Never send a human to do a machine's job"_ (C) Agent Smith

@3nids Thank you for pointing me out to the `opengisch` registry, Denis.  I tried, and unfortunately, it gives me the same problem: 
```
$ singularity pull qgis-opengisch_focal-3.22.sif docker://opengisch/qgis:focal-3.22
$ singularity exec qgis-opengisch_focal-3.22.sif  qgis
/usr/bin/qgis.bin: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

> I think that the image we produce is not really meant to be used in production environment

I did not realize that.  TBF, "not for production use" is not the first thing that comes to mind when seeing an image that is tagged `release-3.22` in an official registry :)

**Comment by m-kuhn** [comment]
> @m-kuhn Matthias, yes, that's fair, people certainly could do this. OTOH, my thinking was that if I have to do it, and someone else might have to do it, then maybe it'd be better if the automatically-built image already had this incorporated in it? This would save people effort and time of learning their way around Docker registries, containers, cyberinfrastructure and all that - and just be more productive in their main job as GIS practitioners? I mean, _"Never send a human to do a machine's job"_ (C) Agent Smith
> 

@lgorenstein I can see where you are coming from, you are not the first to experience this, and probably some people have failed to run qgis in their cluster because of this in the past which admittedly is a pity.
Still, I am hesitant to patch system libraries in packages that are used by qgis. The benefits are clear, but the side effects and risks involved are hard to estimate (at least for me). I have skimmed through https://github.com/microsoft/WSL/issues/3023 and if I read this correctly this leads to [invalidation of debug information](https://github.com/microsoft/WSL/issues/3023#issuecomment-424927551). This might or might not be a problem for someone out there, but it highlights the risks we are taking when embarking on this ship.
If someone wants to ship a patched, general purpose qgis image with patched qt libraries, this would certainly appreciated by the community, but I am not convinced it is a maintenance responsibility to be taken by qgis core.
Others may have different opinions on this, I'm happy to have my mind changed.

**Pull request closed without merging**
