### PR TITLE
Updated what's new with Link to changelog of 3.4

### PR DESCRIPTION
**Pull request by shivareddyiirs**
## Description
Whats new now:
image

But after this changes it would show the link to changelog.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
This file is generated from `news.t2t` can you put the update there?

**Comment by jef-n** [comment]
news.t2t is updated by scripts/update-news.pl which in turn downloads from http://changelog.qgis.org/en/qgis/version/3.4.0/gnu/ - which apparently is currently broken.

**Comment by m-kuhn** [comment]
Looks like the link is

http://changelog.qgis.org/en/qgis/version/3.4-LTR/gnu/

**Comment by jef-n** [comment]
Why was the scheme changed?

**Comment by jef-n** [comment]
@rduivenvoorde  does that also break the update of the website?

**Comment by m-kuhn** [comment]
I chose the name in Zanzibar, I wasn't aware that this is fixed and external services depend on it.

**Comment by rduivenvoorde** [comment]
@jef-n Yeah, I do not know why the changed the naming scheme. But for the website we only have a link to the projecta site. Which I already fixed.

**Comment by shivareddyiirs** [comment]
Can anybody suggest where is the source code of changelog.qgis.org hosted?
I guess its django project.

**Comment by rduivenvoorde** [comment]
@shivareddyiirs see github link in footer

**Comment by jef-n** [comment]
Fixed in f396ab3709131cec176c46b769905f8089200ea4

**Comment by shivareddyiirs** [comment]
@rduivenvoorde ,It redirects me the https://github.com/kartoza/prj.app. 
Moreover If I try to raise any issue in http://changelog.qgis.org/ , it is again raising issue to the above project. 
I understands that above application is used to create visual changelog for various projects (one of them is QGIS). But we should be able to get actual deployment source code for http://changelog.qgis.org.

Correct me If I am wrong.

**Comment by rduivenvoorde** [comment]
@shivareddyiirs https://github.com/kartoza/prj.app IS the application running for changelog.qgis.org
Please contact @timlinux if you want to know more

**Pull request closed without merging**
