### PR TITLE
rework server test to use geopackage and qgz

### PR DESCRIPTION
**Pull request by tudorbarascu**
@elpaso I think it's better to rework some of the current tests to use ``.qgz`` and ``gpkg`` files then to add an extra explicit test.

### CODE REVIEW

**Comment by elpaso** [comment]
@tudorbarascu that's fine for me, just make sure we test both `qgs` and `qgz`, `shp` and `gpkg`

**Comment by tudorbarascu** [comment]
That's how it is right now.
I have spotted a regression using geopackage. I'm documenting it right now.

**Comment by tudorbarascu** [comment]
@elpaso Added disabled test for GetFeatureInfo with filter on project with gpkg datasource.
The output should be:
```
...
 <Layer name="testlayer èé">
  <Feature id="2">
   <Attribute value="2" name="id"/>
   <Attribute value="two" name="name"/>
   <Attribute value="two àò" name="utf8nameè"/>
...
```
but the server outputs:
```
...
 <Layer name="testlayer èé">
  <Feature id="2">
   <Attribute value="0" name="id"/>
   <Attribute value="2" name="name"/>
   <Attribute value="two" name="utf8nameè"/>
...
```

**Comment by elpaso** [comment]
@tudorbarascu maybe I misread your comment https://github.com/qgis/QGIS/pull/7279#issuecomment-398703388 : if is there a problem I haven't had time to look into that, if that's not a problem and you feel confident that we can merge as it is, let's do that.

**Comment by tudorbarascu** [comment]
The failing tests are disabled so we can merge as it is.
I will create issues for the failing tests so they're easier to track.

**Pull request merged**
