### PR TITLE
Fix mistake in docstring for `QgsProjectMetadata`

### PR DESCRIPTION
**Pull request by mfisher87**
## Description

I believe the first sentence here was copied from `QgsLayerMetadata`.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Hm, not sure why the pre-commit workflow refuses to run here! @mfisher87 Can you run the pre-commit hook locally to get that test passing?

**Comment by mfisher87** [comment]
On it!

**Comment by mfisher87** [comment]
All good! Regenerated the SIP files too.

```shell
$ git rev-parse HEAD
f33d2ba9347bda000a389c72e4d419c00e0b0022
(base) (0) robatt@mrpl-gaming01:~/Projects/QGIS
$ pre-commit run -a
clang-format.............................................................Passed
pyupgrade................................................................Passed
black....................................................................Passed
isort....................................................................Passed
prepare_commit...........................................................Passed
```

**Comment by mfisher87** [comment]
The pre-commit.ci failure must be due to throttling by GitHub? I'm not able to shallow clone this repository in 30 seconds on my very fast connection, and I see earlier builds passing the clone step in ~12 seconds. My local test just now took 189 seconds wall time, average speed 1MiB/s.

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
