### PR TITLE
Add temporary output option to model output contextmenu

### LINKED ISSUE #39754: Not possible to set default output value to "Create Temporary Layer" for model output
**Describe the bug**
In a QGIS model it's not possible to set the default output value to **Create Temporary Layer** for the output of _Unjoinable features from first layer_ of the `Join attributes by field value` algorithm.

**How to Reproduce**

1. Open the following model [default_output_value.zip](https://github.com/qgis/QGIS/files/5475302/default_output_value.zip)
2. Click on the `unjoinable_features` output and try to set the default value to **Create Temporary Layer**.
3. See error: This is not possible

grafik

**QGIS and OS versions**

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.11.3 | Running against Qt | 5.11.3
Compiled against GDAL/OGR | 2.4.0 | Running against GDAL/OGR | 2.4.0
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.27.2 | Running against SQLite | 3.27.2
PostgreSQL Client Version | 11.9 (Debian 11.9-0+deb10u1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Debian GNU/Linux 10 (buster)
Active python plugins | ClipMultipleLayers; quick_map_services; scriptrunner3; LAStools; canvas_clipper; savedialog; loadthemall; clipper; kmltools; qgis-maptiler-plugin; MapsPrinter; mmqgis; pluginbuilder3; vector_tiles_reader; layerGroupFilter; plugin_reloader; realcentroid; mask; MetaSearch; db_manager; processing

**Additional context**
- When running the model, it's possible to choose **Create Temporary Layer** as output value for `unjoinable_features`.
- For the `joined_layer` output it's possible to choose **Create Temporary Layer** as default output value.
grafik

### PR DESCRIPTION
**Pull request by pathmapper**
## Description

This is an attempt to fix https://github.com/qgis/QGIS/issues/39754 by adding temporary output option to model output contextmenu, so that it's now possible to overwrite the default `[Skip output]` of algorithms with e.g. `[Create temporary layer]`.

image

image

Not sure if this is the proper way to fix the issue though `[Create temporary layer]` is the default output value for many algorithms anyway and I didn't find any negative side effects while testing this change.

### CODE REVIEW

**Comment by pathmapper** [comment]
> add a description of workflows which this pull request fixes

Before this PR, for a model with many output layers having `[Skip output]` by default but which should be added as temporary layers, a user must change them all manually to `[Create temporary layer]` output option using the model UI.

With this PR, model authors could set `[Create temporary layer]` as default for these layers.

**Comment by pathmapper** [comment]
ready for review

**Comment by pathmapper** [comment]
Rebased to `master`, all tests are passing.

**Comment by Koyaani** [comment]
Is there a reason not to move "Skip Output" action outside the `!mDefaultSelection` condition ? Because, if we set the output to "Create Temporary Layer", we can't revert to "Skip Output". 

I haven't found a case where `mDefaultSelection` is important in processings... I have the impression that `mDefaultSelection` in models is never set to false.

**Comment by pathmapper** [comment]
I left "Skip Output" action inside the `!mDefaultSelection` condition because otherwise "Skip Output" setting is not kept after closing the dialog with "OK":

skip_output

**Comment by Koyaani** [comment]
I looked again. `mDefaultSelection` is always true in the dialog for defining output properties in models and always false in the processings... Considering its limited use, there must be a way to simplify the code by removing `mDefaultSelection` but think it is not in the scope of this PR 😅

So, I think by changing the condition:
```c++
  if ( !mDefaultSelection )
    if ( !mParameter->flags() & QgsProcessingParameterDefinition::FlagOptional )
```
to this one:
```c++
  if ( !mParameter->createByDefault() )
```
This solves the 2 problems.

**Comment by pathmapper** [comment]
> This solves the 2 problems.

Works great, thanks a lot @Koyaani!

**Comment by Koyaani** [comment]
My idea was to put only the "Skip Output" action in this condition. But there is a problem in the processing...

Actually:


Your solution:
yours

The solution I thought:
mine

Perhaps finally use `mDefaultSelection` as it separates the 2 cases, or perhaps this is an issue:

> I left "Skip Output" action inside the `!mDefaultSelection` condition because otherwise "Skip Output" setting is not kept after closing the dialog with "OK":

 and should work.

**Comment by pathmapper** [comment]
Thanks @Koyaani changed the condition again so now it's possible to set the output to "Create Temporary Layer" and revert to "Skip Output" (for model outputs with default value "Skip Output").

There's currently no option in the contextmenu to set "Skip Output" if the default value is "Create Temporary Layer", because otherwise the mentioned issue 

> "Skip Output" setting is not kept after closing the dialog with "OK"

appears again. It might have to do something with `QgsProcessingLayerOutputDestinationWidget::setValue`.

But I would like to keep the scope of this PR  on "Add temporary output option to model output contextmenu".


change_back_to_skip

**Comment by Koyaani** [comment]
Now all output destination parameters in the processings can be set to skip. `mDefaultSelection` is always false in processings. So the condition `!mDefaultSelection || !mParameter->createByDefault()` will always be true. I must admit that my knowledge is showing signs of weakness... I don't know if this behavior change is good or bad.

**Pull request closed without merging**
