### PR TITLE
[bugfix] remember and revert crs change on cancel

### PR DESCRIPTION
**Pull request by roya0045**
## Description

Proposal , Fixes ##39556

The layer crs is copied in the dialog at initiation time. 

On apply the backup is refreshed on the current crs.

On cancel if the backup conflicts with the current crs, the backup will be applied to the layer.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Looks good! Does the same change need applying to the raster/mesh/point cloud properties too?

**Comment by roya0045** [comment]
> Looks good! Does the same change need applying to the raster/mesh/point cloud properties too?

Might be worth doing for safety. Usually only vectors tend to be handled that way, but it might prevent some frustration. I'll look into it.

**Comment by nyalldawson** [comment]
Don't forget point cloud and annotation layers too!

**Comment by roya0045** [comment]
> Don't forget point cloud and annotation layers too!

PC I couldn't find the widget, I'll recheck tomorrow, but I forgot about the annotations yes.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Thanks, looks good to me!

**Pull request merged**
