### PR TITLE
Build PyQt6 with c++ 17

### PR DESCRIPTION
**Pull request by troopa81**
On my way to split #52739 in small chunks

The hack is no longer needed in Qt 6, as this last requires c++17

### CODE REVIEW

**Comment by nyalldawson** [comment]
Do you know what happens with "throw" in pyqt6? Is it treated like it should be and just a hint to sip now? Previously it was needed to correctly get a proper exception raised instead of a generic one. (Ie QgsCsException vs exception)

**Comment by troopa81** [comment]
@nyalldawson Thanks for the hints. I'll try those when it comes to fix more things. 

First I would rather move toward a first working version, so do you mind merging this one?

**Comment by nyalldawson** [comment]
@troopa81 

Looks like my first guess was right, and newer sip gives an explicit warning when a generic exception is handled before more specialised exceptions. See https://github.com/qgis/QGIS/issues/55481#issuecomment-1849001802

I've hopefully addressed this in https://github.com/qgis/QGIS/pull/55576 . I'd love to hear if this fixes things in PyQt6!

**Review by nyalldawson — APPROVED** [review]

**Comment by troopa81** [comment]
> I've hopefully addressed this in https://github.com/qgis/QGIS/pull/55576 . I'd love to hear if this fixes things in PyQt6!

It does fix the exception issue in PyQt6 :+1: 

I will try to remove the throw directive from the sip files in PyQt6 as there are probably ignored.

**Comment by gdt** [comment]
There are many fixes to sip beyond the 6.8.0 tag, and one of them is restoring exception code that was mistakenly not generated in some circumstances.   So if you are testing with 6.8.0, things are messy.   6.8.0 should not be used at all.

**Comment by troopa81** [comment]
@gdt I am testing with PyQt 6.6.0 and sip 6.7.12 shipped with fedora:38

With those versions I don't have the same issues, but the modification in #55576 fixed a few things with PyQt6.

**Pull request merged**
