### PR TITLE
Massive speed boost to 2d point cloud renders

### PR DESCRIPTION
**Pull request by nyalldawson**
We'll need to selectively enable this optimisation when we add control
over the point shape, but for now this gives orders of magnitude faster
2d point cloud renders

### CODE REVIEW

**Comment by PeterPetrik** [comment]
looks interesting. why we need to selectively enable it?

**Comment by nyalldawson** [comment]
> why we need to selectively enable it?

I would like to add an option for controlling the shape of points, with choices of square or circle

**Comment by PeterPetrik** [comment]
> > why we need to selectively enable it?
> 
> I would like to add an option for controlling the shape of points, with choices of square or circle

what about kittens?

**Comment by nyalldawson** [comment]
Well, we could have an option "using marker symbol", which would make that possible 😝

**Comment by nyalldawson** [comment]
Unrelated test failure

**Pull request merged**
