### PR TITLE
Reimplement QgsNetworkContentFetcher test with a local server

### PR DESCRIPTION
**Pull request by m-kuhn**
Reduces false alarms in unit tests due to network problems

### CODE REVIEW

**Comment by m-kuhn** [comment]
@nyalldawson I assigned you because you have written the original test. I think it works pretty well, just wanted to get a feedback about local test vs. network-based test, so no in-depth review required :)

**Comment by nyalldawson** [comment]
@m-kuhn looks good to me, thanks! There's also a test which fetches remote content in TestQgsComposerPicture::pictureRemoteUrl() , I've noticed that one fails a few occasionally too.

**Comment by nyalldawson** [comment]
@m-kuhn looks good to me, thanks! There's also a test which fetches remote content in TestQgsComposerPicture::pictureRemoteUrl() , I've noticed that one fails occasionally too.

**Comment by m-kuhn** [comment]
Manually merged in 06180fe34d77

**Pull request closed without merging**
