### PR TITLE
[server][bugfix] Fixes OGC test on getmap:each-format mode for 1bit/8bit/16bit

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

This PR fixes the OGC test on GetMap PNG formats (1 bit, 8 bit and 16 bit) which is currently failing : http://37.187.164.233/ogc/08_29_2017_00_52_09_wms_1_3_0.html#9630801b-086d-408a-8640-e54ecd237cda/d1e17334_1/d1e17416_1/d1e3465_1

I tried to add some tests but as soon as a mode is used (1 bit, 8 bit or 16 bit), generated images are not equivalent between two run on the the same machine. However, images are valid and differences are invisible to the naked eye. A diff example from https://dash.orfeo-toolbox.org/testDetails.php?test=60325612&build=288453 :

diff

I could introduce a tolerance margin in unit tests but the number of different pixels is quite a lot and could hide a real issue. Let me know what you think.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
@pblottiere you can use test masks to handle this situation. They are a ##_mask.png file which sits alongside the reference image, where each pixel value is the max tolerance that pixel can have. There's a script https://github.com/qgis/QGIS/blob/master/scripts/generate_test_mask_image.py which can used to generate these (or alternatively https://github.com/qgis/QGIS/blob/master/scripts/parse_dash_results.py for a gui based version).

Hopefully the differences are stable enough that updating the mask from a couple of results will give a suitable mask which still allows the test to function correctly.

**Comment by pblottiere** [comment]
@nyalldawson Yes I know the tests masks mechanism but differences does not seem very stable, that's what bothers me.

I'll try several successive runs to build the mask, just to see.

**Comment by pblottiere** [comment]
> https://github.com/qgis/QGIS/blob/master/scripts/parse_dash_results.py

Oh! However, I didn't know this script... Thanks for sharing that!

**Comment by nyalldawson** [comment]
One thing the parse results script offers which may be useful is the ability to "multiply" the test mask differences. Depending on what the differences look like, I usually bump this up a few factors to make the mask more robust.

**Comment by nyalldawson** [comment]
Ouch... That makes IS pretty horrible. It's so inclusive I'm not sure it's actually going to fail when needed :( not sure what to do here - I guess the test is still useful, and I can't think of an alternate approach offhand.

**Comment by pblottiere** [comment]
> Ouch... That makes IS pretty horrible. It's so inclusive I'm not sure it's actually going to fail when needed :( not sure what to do here - I guess the test is still useful, and I can't think of an alternate approach offhand.

Yes, fully agree! That's what I was afraid of... And it's not even succeeding yet...

**Comment by pblottiere** [comment]
I gave up on masks... The mask was ugly and it wasn't even working...

Instead, I set a big *mismatchCount* value when comparing images. To be sure, it is not the ideal situation, but I don't see a workaround in this specific case. And at least, tests may be kept...

@nyalldawson  do you agree with this solution? If so, I clean the history and merge this PR.

**Comment by nyalldawson** [comment]
Yep, it's better than no test at all!

**Comment by pblottiere** [comment]
I'll merge this PR tomorrow if I've no more comments in the meantime.

**Comment by pblottiere** [comment]
Tests are fixed now : http://37.187.164.233/ogc/09_06_2017_14_46_48_wms_1_3_0.html#84c4283f-56e5-4dff-a700-41188f024824/d1e17334_1/d1e17416_1/d1e3465_1

**Pull request merged**
