### PR TITLE
more love to offset tool

### LINKED ISSUE #18115: add manual entry to coordinate capture
Author Name: **Gavin Fleming** (@gubuntu)
Original Redmine Issue: [9525](https://issues.qgis.org/issues/9525)

Redmine category:unknown

---
I often need to project single coordinate pairs (as in cs2cs or gdaltransform). I cannot find an equivalent in QGIS. To me the obvious place to put this would be to have the option of manual input coordinate entry into the coordinate capture panel.

### PR DESCRIPTION
**Pull request by 3nids**
* handle rings
* allow selecting polygons by area
* avoid having empty options in the user widget
* test geom before applying
* fix weird behavior of offset calculation based on map mouse position

fix #18115

### CODE REVIEW

**Comment by lbartoletti** [comment]
@3nids Thanks, I'll test it.

**Comment by 3nids** [comment]
@lbartoletti thanks let me know!

**Comment by nyalldawson** [comment]
> This tool doesn't honor Z (cf @pblottiere works #5823)

That's because geos buffering doesn't support z. But more generally, how do you buffer z coordinates? The best approach I can think of is to buffer in 2d, then for every vertex in th new geometry set the z to the z value of the nearest vertex in the original geometry. But that's quite rough...
https://issues.qgis.org/issues/17530 relates

**Comment by lbartoletti** [comment]
Hi Nyall,
I know the limitation of GEOS, but I put myself in the shoes of an user who doesn't know the limitations of GEOS, and who doesn't care about GEOS, to be surprised to have a deleted Z.

We may just need to display a message or not activate the tool if it is a 3D layer? The only case where I think it's usable is when all the points of the geometry has the same Z.

Maybe it can be done later, like on ArcGis with tools like SFCGAL/CGAL (@mhugo) ?

**Comment by nyalldawson** [comment]
@lbartoletti

But it's not so much a geos limitation, as a fundamental question about the buffer algorithm itself. What *is* a 2.5d buffer even?

**Comment by lbartoletti** [comment]
As I know, for 2.5D, other CAD tools provide the offset tool only if the points of the geometry are on the same plane (sorry I maybe edit my post after yours).

To clarify, I do not doubt the tool, on the contrary, but I like it when the user knows what he is going to use (Documentation, icon indicating that it is not possible to use the tool, etc.). :)

@3nids I like your widget with join, miter, etc. I think it would have been useful to integrate this into the "advanced digitize panel" to be used by the other tools (CircularString, Circle, Ellipse, (other?)). (Thoughts @haubourg ?)

**Comment by 3nids** [comment]
Indeed the message for z is a good idea also testing if it's in the same
plane, makes sense.

I will look at other issues asap, I tested area selection successfully.

Regarding geometry validation, I have no clear opinion but I think we
should be consistent. What do we prefer? The point is that geopoackage
provider seems to allow saving these features.

Do you think we should perform union and intersection with the rings /
part?
Indeed maybe do not check geometry and let user modify the geometry
afterwards?

For the crashes, any chance to have a trace or some reproduction steps?

Thanks again for testing and reporting.

Le dim. 18 févr. 2018 à 04:45, lbartoletti <notifications@github.com> a
écrit :

**Comment by 3nids** [comment]
selecting by area should be fixed by #6374

**Comment by lbartoletti** [comment]
Hi @3nids 
Yes please, document the Z. For the plane, it should be done after the feature freeze, maybe with [QEP 106](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/106)

> Regarding geometry validation, I have no clear opinion but I think we should be consistent. What do we prefer? The point is that geopoackage provider seems to allow saving these features.

For me, GEOS is right.  From OGC:
Polygon: 
> A Polygon is a planar Surface defined by 1 exterior boundary and 0 or more interior boundaries. Each interior boundary defines a hole in the Polygon.

MultiPolygon: 
> The interiors of 2 Polygons that are elements of a MultiPolygon may not intersect.

Maybe is an issue of the "Add part" tool?

> Do you think we should perform union and intersection with the rings / part?
Not yet, it's only my suggestion. And I think that it's should be discuss with GEOS team.

**Comment by 3nids** [comment]
limits has been adapted (min 1 for miter and quad segments)
selecting y area fixed too
a message is now displayed for Z/M values. Although the message is a bit hidden under the user input widget, but that's another issue!

**Pull request merged**
