### PR TITLE
[bugfix] unreported crash on load style

### PR DESCRIPTION
**Pull request by elpaso**

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]

**Comment by lbartoletti** [comment]
Thanks @elpaso now, load/save style open a window. But, if you right click on a layer there is a new crash (was not present before this PR) :(

**Comment by elpaso** [comment]
@lbartoletti I'll have a look, thanks for checking

**Comment by lbartoletti** [comment]
You're welcome. I opened an issue https://issues.qgis.org/issues/19870

**Comment by elpaso** [comment]
I think it's fixed by #7927 but let's wait if Denis can have a look.

**Pull request merged**
