### PR TITLE
drop project backward compatibility for symbology with QGIS 3.16 and older

### PR DESCRIPTION
**Pull request by 3nids**
This part of the codes writes the symbology with backward compatibility so the project can be **open** under QGIS 3.16 and older
This is making the XML code much bigger.

Since next release will become the new LTR, I would be in favor of dropping this.
But I have no strong opinion if we should wait one more cycle.

This was added in #40716

### CODE REVIEW

**Comment by nyalldawson** [comment]
I thought 3.16 was going to be supported for 2 years?

**Comment by 3nids** [comment]
I think this can safely be merged

**Comment by 3nids** [comment]
I think this makes sense to land in 3.28 to avoid having this for one more year in the LTR

**Comment by 3nids** [comment]
@nyalldawson tests are fixed. Can we merge it?
(no regression possible, it only breaks backward compatibility)

**Review by nyalldawson — APPROVED** [review]

**Comment by Gustry** [comment]
@zacharlie and @3nids I'm not sure to understand.

This PR has been merged in september, so it landed in QGIS 3.28. Even Github is showing tags it belongs in the link below :
https://github.com/qgis/QGIS/commit/fc80d24f9a1444629cf2d789dfc4dad1cfd321ec

But it is mentioned in the 3.30 changelog https://changelog.qgis.org/en/qgis/version/3.30/ and the video https://blog.qgis.org/2023/03/07/qgis-3-30-s-hertogenbosch-is-released/

@3nids Can you clarify which situations it really affects ? QGIS symbology made with 3.16 (or lower 3.14 etc) can't be read properly with QGIS 3.28 ?

**Comment by Gustry** [comment]
When I added the label on October 18th, it was maybe too late for the release of 3.28 if I understand (October 21th)

**Comment by 3nids** [comment]
no, it's a backward compatibilty. So a symbology made on 3.30+ will not be able to be open on 3.16 and older anymore.

**Comment by Gustry** [comment]
Ok, thanks, way better on that side !

**Comment by zacharlie** [comment]
I was under the impression that it was implemented for the LTR release of 3.28 (changelog was published at 3.28.0 but the LTR release is 3.28.4). I see someone else in the community cleaned up the changelog entry (thank you), but the release blurb still includes a line `This change has been ported to the release of 3.28 LTR as well.`.

I figure we should then remove that line from the changelog to prevent confusion. I've made a pr https://github.com/qgis/QGIS-Website/pull/1131 for the website @rduivenvoorde

**Comment by agiudiceandrea** [comment]
@3nids I'm a bit confused from the discussion here and at https://github.com/qgis/QGIS-Website/pull/1131 and your comment: "So a symbology made on 3.30+ will not be able to be open on 3.16 and older anymore". Is it only a symbology made on **3.30+** that will not be able to be open on 3.16 and older anymore or it is actually also a symbology made on **3.28+**?

**Pull request merged**
