### PR TITLE
Fix leak in sqlite unique_ptrs

### PR DESCRIPTION
**Pull request by nyalldawson**
Seems that reusing an existing database pointer leaks when trying to free any statements associated with it afterwards.

(We may be doing this elsewhere too)

### CODE REVIEW

**Comment by m-kuhn** [comment]
Does this mean, we need to discard any open prepared_statements when the database is closed?
If I understood correctly, I think we should enforce this one way or the other (either by keeping track of ongoing statements in the db connection or by listening to close "signals" in the statement).

This whole implementation only makes sense if it's easy and bulletproof to use.

**Comment by rouault** [comment]
Use sqlite3_close_v2() if you free statements after closing the DB. See https://sqlite.org/c3ref/close.html : """If sqlite3_close_v2() is called with unfinalized prepared statements and/or unfinished sqlite3_backups, then the database connection becomes an unusable "zombie" which will automatically be deallocated when the last prepared statement is finalized or the last sqlite3_backup is finished. The sqlite3_close_v2() interface is intended for use with host languages that are garbage collected, and where the order in which destructors are called is arbitrary."""

**Comment by m-kuhn** [comment]
I was never sure about those open(_v2) and close(_v2) calls, maybe I just didn't find the correct pointers to the docs. Are the non-v2 versions legacy or are they still required in some cases?

**Comment by m-kuhn** [comment]
Thanks @rouault , at least with the new implementation we can adjust this in one single place 👍

**Comment by m-kuhn** [comment]
Superseded by #5678 ?

**Pull request closed without merging**
