### PR TITLE
Rework GPS add track point icon

### PR DESCRIPTION
**Pull request by nyalldawson**
I've added the "+ overlay to the "Add track point" icon so that the meaning of this action is clearer:

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
(@nirvn i've never noticed before that the + overlay and * overlays are different sizes!)

**Comment by nirvn** [comment]
There's something off with the size of either the [*] or [+] badge, they should have the same size.

**Comment by nyalldawson** [comment]
@nirvn there's definitely a size mismatch -- 9x9 (+) vs 11x11 (star) for the 24x24 px icon sizes

**Comment by nirvn** [comment]
@nyalldawson , wow, can't believe we missed this for that long :)

**Review by nirvn — APPROVED** [review]

**Pull request merged**
