### PR TITLE
[FEATURE] Show field values in autocompleter in form filter mode

### PR DESCRIPTION
**Pull request by nyalldawson**
This adds a new gui widget QgsFieldValuesLineEdit which includes an autocompleter populated with current field values.

The autocompleter is nicely updated in the background so that the gui remains nice and responsive, even if there's millions of records in the associated table.

It's now used as a search widget for text fields, so can be seen in the browser window if you set the filter to a text field, or if you launch the form based select/filter by selecting a layer and pressing F3.

(also some unrelated enhancements to QgsFloatingWidget due to an abandoned approach to this PR)

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , it's great; should be used in the attribute table's Field Filter line edit too.

**Comment by nyalldawson** [comment]
@nirvn yep, that's what I meant by browser. Oops.

**Comment by nyalldawson** [comment]
I added a bonus feature I've wanted for a long time - a zoom to features shortcut in select by form dialog. This allows very quick navigation to features which match the criteria in the form. It's a nice companion to the completer because now it's super quick and easy to zoom to some matching value.

**Comment by nyalldawson** [comment]
Obligatory screencast: https://www.youtube.com/watch?v=Kr7Y9qUn8SA&feature=youtu.be

**Comment by NathanW2** [comment]
Holy heck that is impressive

**Comment by nyalldawson** [comment]
Would love a second opinion if someone can review this!

**Pull request merged**
