### PR TITLE
Use a standardized size for icons

### PR DESCRIPTION
**Pull request by DelazJ**
in Options --> Authentication dialog (they are oversized, compared to their equivalent in other tabs)

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nirvn Another one for you!

**Comment by nirvn** [comment]
@DelazJ , it's nice to see you spending time tweaking the UI for consistency. 

Could you update the PR to remove the <size></size> element? if you look at the qgsoptionsbase.ui, you'll notice the QToolButtons there don't define a width and height. Since they share the same .svg file (which are 16 x 16 pixels), leaving the width and height undefined will insure that if we ever update the .svg and increase the size, it'll increase across the board.

**Comment by DelazJ** [comment]
Thanks for the hint, @nirvn 
Does it mean that any QToolButton that has (icon) size matters should be cleaned up?

**Comment by DelazJ** [comment]
I extended the cleanup to the other dialogs of the authentication system.
I wonder if `qgsauthservereditor.ui`, `qgsauthidentitieseditor.ui`, and `qgsauthauthoritieseditor.ui` (and  `qgsauthtrustedcasdialog.ui`) should not be merged in a single dialog (with conditional visibility for some buttons)

**Comment by nirvn** [comment]
@DelazJ , the size shouldn't be "blindly" removed without checking the SVG's width and height as well as looking into UI context within which the button is placed.

**Comment by nirvn** [comment]
@DelazJ , looking good, merged. BTW, if you feel like it, I've noticed two bitmap icons (namely mActionRefresh.png and symbologyEdit.png) which would be nice to vectorize.

**Comment by DelazJ** [comment]
Thanks @nirvn
Yes, I always try to open the dialog in Qt Designer and QGIS before making changes to be sure I understand the context.
About mActionRefresh.png, there's a mActionDraw.svg which can be used instead, imho. Yes, double icons is also an issue we need to fix. Will add it to the ui/ux repo

**Pull request merged**
