### PR TITLE
[Server] Use correct schema URL for WFS 1.1.0 GetFeature response

### PR DESCRIPTION
**Pull request by pathmapper**
## Description
Replaces #45124

This PR fixes the schema URL for WFS 1.1.0 GetFeature response:
http://schemas.opengis.net/wfs/1.0.0/wfs.xsd -> http://schemas.opengis.net/wfs/1.1.0/wfs.xsd

image

### CODE REVIEW

**Review by rldhont — APPROVED** [review]

**Review by sbrunner — APPROVED** [review]

**Comment by pblottiere** [comment]
Hello,

I know it's my fault because I'm not very reactive lately (:cry:), but any PR related to OGC conformity should be checked with TeamEngine before merging (because unlike OGC API F, the WFS 1.X protocol is not part of the CI).

But considering that QGIS Server is not  WFS 1.X compliant, it's not that dramatic ^^.

**Comment by pathmapper** [comment]
Hi @pblottiere,

> any PR related to OGC conformity should be checked with TeamEngine before merging

thanks for the info, this applies to https://github.com/qgis/QGIS/pull/45235 as well.

> QGIS Server is not WFS 1.X compliant

Oh, that's surprising, from https://docs.qgis.org/3.16/en/docs/server_manual/faq.html#

grafik

This could have something to do with an issue regarding NULL values in the WFS 1.1.0 response I came across recently:
https://lists.osgeo.org/pipermail/qgis-developer/2021-September/064054.html

If you're having any insight on that topic, I'd be happy if could share them.

Also any more details about why QGIS Server is not WFS 1.X compliant would be appreciated.

**Comment by pblottiere** [comment]
> Oh, that's surprising, from https://docs.qgis.org/3.16/en/docs/server_manual/faq.html#

grafik

It's implemented but not 100% compliant :). 


> Also any more details about why QGIS Server is not WFS 1.X compliant would be appreciated.

We have daily tests on QGIS Server master for WFS 1.X. Reports are available here: http://test.qgis.org/ogc_cite/wfs_110/

On the contrary, we're fully compliant with the OGC standard for WMS 1.3.0 and OGC API F (see http://test.qgis.org/ogc_cite/wms_130 and http://test.qgis.org/ogc_cite/ogcapif).

**Comment by pblottiere** [comment]
> This could have something to do with an issue regarding NULL values in the WFS 1.1.0 response I came across recently:
https://lists.osgeo.org/pipermail/qgis-developer/2021-September/064054.html

> If you're having any insight on that topic, I'd be happy if could share them.

I'll take a look in the coming days. Can you create an issue and assigned it to me please?

**Comment by pathmapper** [comment]
Thanks for the information @pblottiere ! I'll take a look.

> I'll take a look in the coming days. Can you create an issue and assigned it to me please?

Issue opened in https://github.com/qgis/QGIS/issues/45243, but I can't assign it to you. Maybe you can assign it to yourself?

**Pull request merged**
