### PR TITLE
Redesigned interactive gradient editor

### PR DESCRIPTION
**Pull request by nyalldawson**
See https://www.youtube.com/watch?v=0UuZWTArKj0&feature=youtu.be for a preview!

Features:
- easier to directly edit colors
- drag to move color stops
- double clicking to add a new stop
- pressing delete will remove the selected stop
- pressing arrow keys will move the selected stop, with shift+arrow keys = larger move
- drag and drop a color onto the widget to add a new stop at the dropped position

Possible TODO:
- add graphs and auto-correction as described here https://t.co/lOfpiFdpG3

### CODE REVIEW

**Comment by NathanW2** [comment]
Man you are quick from idea to done in a day.

**Comment by nyalldawson** [comment]
Here's version 2 - now with an interactive hue/saturation/lightness/alpha plot!

https://www.youtube.com/watch?v=v0mkqUXeOnc&feature=youtu.be

**Comment by NathanW2** [comment]
Holy heck that bloody great!

**Comment by nirvn** [comment]
Nyall, very nice, like the way you colored the plot nodes with the respective colors.

I look at all this amazing work, and I still feel like color 1 and color 2 button should go :smile:

**Comment by nirvn** [comment]
@nyalldawson tested the branch, _huge_ UX improvement, it makes tweaking gradients actually fun (which it wasn't really in the past).

My main comment would be that too many things are stacked one above the other and that makes it a bit cumbersome. How crazy of an idea would it be to implement the cool plot stuff on top of the gradient preview area? Maybe it wouldn't be practical nor ascetic, just throwing an idea here.

If the plot area sticks around, would be worth adding a "legend" attached to the hue saturation lightness alpha checkboxes (i.e. to indicate that the hue line is red, saturation line is blue, etc. etc.)

Also, try this: shrink the window vertically so you can see the gradient preview and the "Current" (i.e. the part at the bottom) color section of the color chooser widget, then go to the "color picker" tab, you'll notice the panel increases by quite a lot vertically, due to the overly long sample color preview area. That'd be worth fixing, maybe. :smile:

That said, this all rocks!

**Comment by anitagraser** [comment]
Great work! 

Some thoughts about the UI layout: 

- The gradient preview area wouldn't need to be that high.
- For me, it would make more sense to move the gradient preview and the plot closer together instead of having the color picker in the middle. 
- I agree with nirvn that the color 1 and color 2 inputs could go. I don't think they have any real use anymore.

**Comment by pierstitus** [comment]
I played a bit with it and like the plot very much. Interesting to see how the RGB interpolation messes up the lightness and saturation curves.

I would love to see a HCL plot as explained in http://vis4.net/blog/posts/avoid-equidistant-hsv-colors/. In the HSL plot dragging the node to a smooth curve still doesn't give the desired color ramp. It is a challenge to treat the non-existent colors well, but definitely a challenge worth taking.

Very nice work!

**Comment by nyalldawson** [comment]
Manually merged for wider testing

**Pull request closed without merging**
