### PR TITLE
Expose through iface methods to copy/paste features between given layers

### PR DESCRIPTION
**Pull request by gacarrillor**
That is, no need to load layers into the layer tree nor make them active to use copy/paste functionality (such as with `iface.actionCopyFeatures().trigger()`), which means that we'll have an alternative to cover (to some extent) the missing "append to layer" functionality.

## Checklist
- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by luipir — APPROVED** [review]
good idea, tnx

**Comment by nyalldawson** [comment]
What's the target here? 3.0? 3.2?

**Comment by gacarrillor** [comment]
May it be 3.0?

**Comment by luipir** [comment]
ok, the PR arrived after feature freeze, but it does not introduce any breack, just expose two already available features. 
Btw also wait to 3.2 it's ok for me.

**Comment by m-kuhn** [comment]
I'd possibly include a bit more context in the method names and make them self-explanatory. Does `copySelectedToClipboard` / `pasteFromClipboard` sound good to you?

**Comment by gacarrillor** [comment]
Yeap, they sound good. Should we change the corresponding names in QgisApp as well?

**Comment by m-kuhn** [comment]
> Should we change the corresponding names in QgisApp as well

Yes, please, that will make it easier to maintain

**Comment by gacarrillor** [comment]
Done, the failing test is not related to this PR :)

**Pull request merged**
