### PR TITLE
Show a label in layout designer for report sections

### PR DESCRIPTION
**Pull request by nyalldawson**
This should further help improve the UX of the report designer... here's a quick screencast:

peek 2018-01-05 17-43

### CODE REVIEW

**Comment by nirvn** [comment]
Nice.

**Comment by nirvn** [comment]
If you want to prioritize the field name due to worries an overly long layer name could chop the field name out of the visible list area in the panel, you could put the layer name after the field name within brackets: "Group: name (protected_area)" 👍

**Comment by nirvn** [comment]
One last thought: the label could also be used when a layout atlas is activated, showing the atlas feature name (which currently is visible only in the atlas toolbar, which users might have switched off). 

Ok, enough idea spam for now ;-P

**Comment by elpaso** [comment]
Looks good!

**Comment by nyalldawson** [comment]
@nirvn all fixed!

**Pull request merged**
