### PR TITLE
[OGR provider] Fix issue when writing a multi-part multipolygon in a shapefile with GDAL >= 3.7 (fixes #54537)

### LINKED ISSUE #54537: qgis cannot find/identify a polygon feature by clicking a newly created (multi)polygon part
### What is the bug or the crash?

in a new polygon shapefile, after adding a feature, subsequently adding a part to this feature and ending the editing session, the newly added part will not be found by either the (mouse) information tool or the (mouse) selection tool.
Before leaving editing mode, these action still work as expected.
First found in Lima, then did fresh install of LTR Firenze to check. Both showed the same unwanted behavior.
A new profile in Firenze did not solve the issue.

### Steps to reproduce the issue

Open  Qgis (3.28.10 LTR or Lima, presumably other versions as well).
`Layer->Create Layer->New Shapefile Layer` (the type of layer, e.g. geopackage rather than shapefile, is probably irrelevant)
Dialog:
choose a (new) shapefile filename, set geometry type to polygon, crs (in my case) to EPSG:28992 (projected), click OK.
Select the layer in TOC and toggle editing.
`Digitizing toolbar -> Add Polygon Feature`. Create a single, simple (e.g. triangular) polygon, ending digitizing with right click. Fill in an unused ID value and click ok.
Select the new feature.
`Advanced Digitizing -> Add part`. Create a simple part outside the (first part of the) feature, ending again with right click.
Now use information tool on the second part. The new feature with both parts will show up correctly.
End editing session, save results.
Try identifying the feature by clicking the second part. This will fail. Try identifying through clicking the first part; this will work, both parts show up as identified.
Try `properties->Source-> update extents`; this will not help.
`Vector->data management tools->create spatial index`: will not help either.
Save project and reload: will not help.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.10-Firenze | QGIS code revision | e2edb9c468
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
GeoCoding | 2.19
go2streetview | 8.6
moving_feature | 2.0
nominatim_locator_filter | 0.2.4
pdokservicesplugin | 4.1.5
pdok_locatieserver_locator_filter | 0.2.1
quick_map_services | 0.19.33
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.10-Firenze
QGIS code revision
[e2edb9c468](https://github.com/qgis/QGIS/commit/e2edb9c468)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
GeoCoding
2.19
go2streetview
8.6
moving_feature
2.0
nominatim_locator_filter
0.2.4
pdokservicesplugin
4.1.5
pdok_locatieserver_locator_filter
0.2.1
quick_map_services
0.19.33
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99
----------------------------------------------
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.2-Lima | QGIS code revision | c0b8833964
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
GeoCoding | 2.19
go2streetview | 8.6
moving_feature | 2.0
nominatim_locator_filter | 0.2.4
pdokservicesplugin | 4.1.5
pdok_locatieserver_locator_filter | 0.2.1
quick_map_services | 0.19.33
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.32.2-Lima
QGIS code revision
[c0b8833964](https://github.com/qgis/QGIS/commit/c0b8833964)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
GeoCoding
2.19
go2streetview
8.6
moving_feature
2.0
nominatim_locator_filter
0.2.4
pdokservicesplugin
4.1.5
pdok_locatieserver_locator_filter
0.2.1
quick_map_services
0.19.33
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by nirvn** [comment]
@rouault , thanks for looking into this.

**Comment by agiudiceandrea** [comment]
I think this fix should go directly in release-3_28 branch.

**Comment by rouault** [comment]
> Does the fix also works well with QGIS using GDAL/OGR < 3.7?

yes

**Comment by rouault** [comment]
Workaround submitted for GDAL 3.7.3 shapefile reader to detect & autorepair wrong multipolygons: https://github.com/OSGeo/gdal/pull/8483

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
