### PR TITLE
 Fix uuid() function returns the same uuid 

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #18130

### CODE REVIEW

**Comment by NathanW2** [comment]
Why does this make it generate a new one each time? Shouldn't the function just make new one each time it is called?

**Comment by nyalldawson** [comment]
> Why does this make it generate a new one each time? Shouldn't the function just make new one each time it is called?

Because expressions are now compiled when they are prepared - functions which are "static" and always return the same result for the same input are squashed down and replaced with a literal node. 

By flagging it as a static function it meant that prepare was evaluating it once and replacing the function node with a literal node... hence always the same value.

**Comment by NathanW2** [comment]
Ah right that makes sense.  So really "const" is a better word I think we
should have used but such as life.

**Comment by nyalldawson** [comment]
It's not too late to change!

**Pull request merged**
