### PR TITLE
Standardize shebangs (was Usr bin env)

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description
New attempt. see #6072 

Is scripts/redirects.pl still in use?

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [X] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [X] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by lbartoletti** [comment]
@3nids @nyalldawson I identified the last problem, I was able to replicate the errors and I think it's OK now. I've made other tests and "seems" OK.

Please, can you made some tests too :) 

Thanks in advance.

**Comment by 3nids** [comment]
can you detail the changes?

**Comment by lbartoletti** [comment]
In astyle.sh: 
 inverse arguments for unify_includes.pl (was `perl scripts/unify_includes.pl -i.sortinc -n "$modified"` is `perl -i.sortinc -n scripts/unify_includes.pl "$modified"`)
and I let `scripts/doxygen_space.pl "$modified"`

**Comment by 3nids** [comment]
@nyalldawson was that the only you observed?

**Comment by nyalldawson** [comment]
Looks good to me - tested and working well!

**Comment by lbartoletti** [comment]
Great!

**Pull request merged**
