### PR TITLE
Enable save icon for embedded relations in same transaction group

### LINKED ISSUE #43061: Save icon not enabled with many to many relationship and transaction group enabled
**Describe the bug**
The save icon is not enabled when editing links in many to many relationship with layer form.

**How to Reproduce**
Prepare a simple Postgres schema :

```sql
create schema mtom_test;
create table mtom_test.a (
	id serial primary key
);

create table mtom_test.b (
	id serial primary key
);

create table mtom_test.a_b (
	id serial primary key,
	id_a integer references mtom_test.a on delete cascade,
	id_b integer references mtom_test.b on delete cascade
);

insert into mtom_test.a values (1), (2);
insert into mtom_test.b values (1), (2);
```

Parametrize the many to many relationship

1.  Add the 3 tables to a new QGIS project
1.  In the project properties
    1. add the relations with the discovery tool
    2. activate the transaction groups in the datasource section
1. In layer `a` set up the form to be drag and drop
1.  Add the relation to the form
1.  Configure the relation to have a cardinality on table b (id)
1.  Apply and OK
1.  Repeat steps 4 to 7 on layer `b`
1. Activate edit mode on layer `a` (the edit mode is activated for all layers)
2. Open the attribute table of layer `a` and choose a feature
3. Link this feature with a feature of layer `b`

image

A new link has been created in `a_b` and appears in the form, but the main save icon is disabled:

image

image

**QGIS and OS versions**

Version de QGIS | 3.16.6-Hannover | Révision du code | bfd36fddc9
-- | -- | -- | --
Compilé avec Qt | 5.15.2 | Utilisant Qt | 5.15.2
Compilé avec GDAL/OGR | 3.2.2 | Utilisé avec GDAL/OGR | 3.2.2
Compilé avec GEOS | 3.9.0-CAPI-1.16.2 | Utilisé avec GEOS | 3.9.0-CAPI-1.16.2
Compilé avec SQLite | 3.34.1 | Fonctionne avec SQLite | 3.34.1
Version du client PostgreSQL | 13.2 (Ubuntu 13.2-1) | Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.4 | Version de QScintilla2 | 2.11.6
Compilé avec PROJ | 7.2.1 | Fonctionne avec PROJ | Rel. 7.2.1, January 1st, 2021
Version de l'OS | Ubuntu 21.04
Extensions Python actives | plugin_reloader; remotedebug; shapefile_encoding_fixer; MetaSearch; processing; db_manager

**Additional context**

When we use the transaction group, the save and edit icons of the relation disapears:

#### Without transaction group:

image

#### With transaction group:

image

So we must rely on the main save icon which is not enabled then.

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #43061

### CODE REVIEW

**Comment by 3nids** [comment]
corrected the issue number, merge with squash so the commit message is corrected too

**Comment by elpaso** [comment]
@3nids I've rebased and corrected the commit msg.

**Comment by elpaso** [comment]
Anyone to review this? It's a bugfix and not a feature.

**Review by domi4484 — APPROVED** [review]
It looks good to me!

**Comment by elpaso** [comment]
@domi4484 thank you for reviewing!

**Pull request merged**
