### PR TITLE
Fix curved labels

### PR DESCRIPTION
**Pull request by fritsvanveen**

### CODE REVIEW

**Comment by nyalldawson** [comment]
Test failures where not important here - just some tiny differences in the rendered images. I've updated the masks so let's see how this goes now...

**Comment by nyalldawson** [comment]
Thanks @fritsvanveen ! This should also be backported to master_2, right?

**Comment by fritsvanveen** [comment]
It would be nice for 2.17 to have a complete working set of curved labels, yeah.
I had a long session yesterday with Tudor Barascu on Skype and TeamViewer and he helped be wonderfully. I know a lot more about Github now. We tested the code briefly on his system. Can you confirm, that the wrong labels on your dataset are ok now?
I can no longer build the code as Qt5 is mandatory now and OSGEO4W does not (yet) install those libraries. Tudor suggested to get in touch with Jürgen or Nathan as they work with DevStudio also.

**Comment by tudorbarascu** [comment]
@fritsvanveen Only the master branch is with qt5. You can build on all the other branches, including master_2.

**Comment by fritsvanveen** [comment]
@tudorbarascu Yes, but I like to develop some more on the master.

**Pull request merged**
