### PR TITLE
[processing] Fix create constant raster layer modifies pixel size

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #18446

### CODE REVIEW

**Comment by nyalldawson** [comment]
@alexbruy do you know what the +1 here was for?

**Comment by alexbruy** [comment]
I'm afraid, I don't know. Maybe to prevent creating raster containing just single pixel?

**Comment by nyalldawson** [comment]
The `max(..., 1)` should do that. Are you OK with this change?

**Comment by alexbruy** [comment]
Hmm, if `ceil()` returns 1 this will be 1 even after `max(..., 1)` isn't it? But this is kind of edge case.
+1 to merge

**Comment by nyalldawson** [comment]
Ah, sorry, I misunderstood. I thought you meant a raster containing 0 pixels. But I don't personally see an issue with a single pixel raster (if someone wants to do that!).

**Pull request merged**
