### PR TITLE
New QgsSymbolButton widget

### PR DESCRIPTION
**Pull request by nyalldawson**
Just like the color and font buttons, this PR implements a new standard QgsSymbolButton widget. 

Button widgets for configuring symbol properties were reimplemented multiple times throughout the codebase. The new class QgsSymbolButton widget which should be used whenever a button for configuring symbol properties is required.

Features include:
- automatic use of inline panels whenever possible
- dropdown menu with shortcuts to color settings, copy/pasting colors
- accepts drag and dropped colors to set symbol color
- a common widget so that future enhacements to the button will benefit all symbol selectors across the UI...

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nirvn @3nids This should be ready to merge now.

Remaining tasks would be:
- port remaining composer widgets to use this button (but seems pointless since they are going away anyway - the whole reason I made this PR was to avoid copying the old duplicated symbol button code from composer -> layout!)
- extend the button with new functionality. E.g. show favourite symbols in a submenu? Show recent symbols in a submenu? Drag and drop of symbols? Copy and paste of symbols? etc.....

**Comment by nirvn** [comment]
@nyalldawson , building now. Very happy to see this, it's been in my mind since I worked out the color ramp button. That'll make the UX so much more consistent across the board.

Big +1 to show favorites, possibly even within the main menu (ala color ramp button). The symbol list widget could simply be embedded there, similarly to what you've done with the color wheel with the color button.

Review coming in soon.

**Review by nirvn — APPROVED** [review]
@nyalldawson , looking good over here, fantastic improvement.

It'd be useful to have a "copy symbol" / "paste symbol" pair of actions with this button, that'd rely on the symbol's XML settings.

**Comment by nirvn** [comment]
While looking into this button, I noticed a bit of an issue with the font button. I think using "Font" as the preview string on the button is not ideal, it's a bit messy visually:
screenshot from 2017-07-24 09-41-36

Read quickly, you feel like "font" is repeated twice in a string (label font [ font ] ). What about using the font name as preview string? To make it consistent with the symbol button, I'd also _center_ the preview text on the label button.

**Comment by nyalldawson** [comment]
> While looking into this button, I noticed a bit of an issue with the font button. I think using "Font" as the preview string on the button is not ideal, it's a bit messy visually:
screenshot from 2017-07-24 09-41-36

That's actually already configurable - it just defaults to "font" if nothing else is set (based on some dialogs which don't use a label before the button). So probably for the displacement renderer we should use "label" instead?

> I'd also center the preview text on the label button.

Wouldn't that look out of line with the "label attribute" setting above it?

**Comment by nyalldawson** [comment]
@nirvn thanks for the review!

Copy/paste is inbound soon...

**Comment by nirvn** [comment]
@nyalldawson , re "font", yeah, changing it to "label" would improve things here. On the alignment thing, I see your point.

**Review by 3nids — APPROVED** [review]
Great job.
Didn't compile but had a quick look at the implementation.
Looking forward to having copy/paste (and recent symbols?) and of course using it :)

**Comment by nyalldawson** [comment]
Copy/paste is done.

**Pull request merged**
