### PR TITLE
sort and remove duplicates in includes

### PR DESCRIPTION
**Pull request by 3nids**
testing with travis to see if everything's fine!

### CODE REVIEW

**Comment by jef-n** [comment]
Hm, what's the point of sorting the includes?  Order might be significant (spatialite.h might not be the only case).

**Comment by 3nids** [comment]
well, I find it makes the code clearer.
but I can revert then.

**Comment by jef-n** [comment]
Argh, I was just asking.  I see that duplicate includes are useless - but not really why the lexical order is clearer.  Eg. if you include a base class first and then derived classes - makes more sense to me than the lexical order.  Of course that's a a bad example as the derived headers already include the  base classes' header anyway - but still.   And as order might be significant, if includes don't include what they need themselves, it might cause problems when using the lexical order.   But appearently QGIS and Qt have very little or none header files that need others they don't already include.

**Comment by 3nids** [comment]
yep, I thought it would be quite trivial at first.
But it seems there's other trouble in the server part.
So, let's forget about this :(
Thanks for your help.

**Pull request merged**
