### PR TITLE
[Processing] None is the default value for parameters also for string

### PR DESCRIPTION
**Pull request by rldhont**
It's a fix for regression between 2.14.

### CODE REVIEW

**Comment by m-kuhn** [comment]
looks good code wise. can you be more specific about the regression / a ticket number?

**Comment by nyalldawson** [comment]
Looks like this reverts d7bd5dc50705eec3f37ef82fc819b5bc47cce0f0 - @volaya can you comment on this?

**Comment by rldhont** [comment]
It's not a complete revert. It reverts the default default value for string.

In python, an empty string or None are false value for test. But in R, empty string and Null are not falsz value. So with default value changes to empty string, R scripts has to be updated. I revert this to reuse the same scripts in 2.14 and 2.18.

**Comment by rldhont** [comment]
Any objection to merge ? Ping @volaya

**Pull request merged**
