### PR TITLE
Partially fix broken server labeling test

### PR DESCRIPTION
**Pull request by nyalldawson**
@dakcarto I've been struggling trying to get the failing server labeling tests functional. I think these changes are required to initially get the tests to run, but I'm not confident. Can you take a look?

The tests fail even with these changes - for me the fcgi instance crashes after the first test. This may be exposing a bug in QGIS or something in the Debian scripts, but never having touched QGIS server it's all a bit over my head...

### CODE REVIEW

**Comment by nyalldawson** [comment]
@dakcarto - gentle ping. Any thoughts on this?

**Comment by dakcarto** [comment]
@nyalldawson Sorry for the delay. I can look into this later this week. If I forget, please ping me again on Friday.

**Comment by nyalldawson** [comment]
@dakcarto any luck?

**Comment by nyalldawson** [comment]
manually merged

**Pull request closed without merging**
