### PR TITLE
New icon for Data Source Manager button

### PR DESCRIPTION
**Pull request by KentPorter-Boundless**
## Description
This PR replaces the current icon for the Data Source Manager button. I deleted my 1st attempt at a PR for this new icon in order to better comply with our PR best practices. This PR has a better description and an updated screen cap of the new icon in QGIS.

I’ve been working with Alessandro Pasotti and the Boundless Desktop team on the revised icon. Our objective is to create an appropriate icon that stands out, but still adhere to the established QGIS icon style. 

Attached is an image of what the icon will look like in QGIS. I have highlighted the new icon with a red circle.

icon-in-application

### CODE REVIEW

**Comment by luipir** [comment]
much betetr, tnx @KentPorter-Boundless

**Comment by nyalldawson** [comment]
I'm not convinced about the use of the "side on" 3d style, given that we don't use this in any other icons. What about instead having the 3 layers viewed "from above" and sightly offset from each other (like 3 pieces of paper), with a very subtle shadow to convey the depth effect?

**Comment by nirvn** [comment]
@KentPorter-Boundless , as mentioned in the original PR, I'd really like to see a shades-of-blue version of this icon to maintained the color association we have on individual providers.

Re @nyalldawson 's comment, I'm also not convinced about the 3D style.

**Comment by elpaso** [comment]
@nirvn why? We don't have the other provider icons anymore. 
I believe that because this icon is probably the most important in the whole QGIS application is should really stand out. 

If it was on we I would make it bright yellow, pulsing and blinking :)

**Comment by KentPorter-Boundless** [comment]
Hey Guys, the first icon was the original concept using a angle or perspective that is not unlike the openlayers logo, which is why we thought another arrangement might be better. Nyall: take a made a couple of attempts at you concept. Let me know if any of these are close to what you have in mind. I think we should nail the layout first, and then finalize colors. These are just to illustrate layout, not final color choices. 

[](url)
icon-1
icon-2
icon-3
icon-4

**Comment by nyalldawson** [comment]
Hi Kent!

While all those icons look fantastic (I love the second) I think to match existing qgis style we should focus on the last one (flat top-down one).

**Comment by NathanW2** [comment]
+1 for the last one.

**Comment by nirvn** [comment]
Nice, all of these are improvements :)

I also give my +1 to the last one.

**Comment by elpaso** [comment]
Thanks @KentPorter-Boundless  for the updates!
I also like the last one.
Can you please update the PR so that we can merge?

**Comment by luipir** [comment]
UAO! I didn't imagine there were a "consensous" on the last one... +1 for me too :) btw I like all of them!

**Comment by KentPorter-Boundless** [comment]
Great. I will output the last icon option I presented to SVG, and then update the PR. Thanks for the feedback guys.

**Comment by KentPorter-Boundless** [comment]
Our group looked at the new icon once placed, and decided it needed just a bit of adjustment. I scaled up the layer elements by a couple of pixels, and added darker outlines to the elements to add a bit of contrast, and make the icon pop a little more in the ui. Attached images shows old vs. new icon.
comparison

**Pull request merged**
