### PR TITLE
Fix signed 32bit integer overflow in PostgreSQL provider

### LINKED ISSUE #14262: Making url's in WMS Query response clickable
Author Name: **Tim Couwelier** (Tim Couwelier)
Original Redmine Issue: [4325](https://issues.qgis.org/issues/4325)

Redmine category:web_services_clients/wms

---
In follow-up of this thread on the QGis forums (http://forum.qgis.org/viewtopic.php?f=2&t=9317&sid=5685153a6922412e5102f781eb1bd81f)

Some WMS servers give responses through the info tool that hold url information.
Whereas on user created vector datasets, one can make this possible through 'Actions', this is not possible for WMS layers.

This could be an enhancement to the information tool.

PS: I do hope I put this up in the right spot, as this is a first for me.

### PR DESCRIPTION
**Pull request by strk**
Fixes #14262

### CODE REVIEW

**Comment by strk** [comment]
@jef-n what's the best way to test this ? do we already have a framework using a PostrgreSQL dataset ?

**Comment by strk** [comment]
@m-kuhn I'm adding tests to test_provider_postgres.py, how can I run the single test I'm adding for quick checking ? I tried `ctest -R testSignedIdentifiers` and `ctest -R TestPyQgsPostgresProvider` with no luck...

**Comment by strk** [comment]
Is it expected that the postgresql python test is not running ? 
```
$  grep test_provider.*py check.log 
-- Running /usr/bin/python2 /usr/src/qgis/qgis-master/tests/src/python/test_provider_shapefile.py
$
```

**Comment by strk** [comment]
No traces of tests/src/python/test_provider_postgres.py being run

**Comment by strk** [comment]
Found: ENABLE_PGTEST  OFF                                                                                                             
What determines it being ON or OFF ?

**Comment by strk** [comment]
Found, it's documented in tests/README.md.
See also #2779 for making it work on my local system.
I've pushed a test, let's see if Travis is happy with it.

**Comment by strk** [comment]
NOTE to self: the test also passes in master, so I guess it's not a good test, needs more work to prove the fix is needed.

**Comment by strk** [comment]
The test was indeed bogus. Now fixed, will fail in master and only succeed in this branch.

**Comment by strk** [comment]
@jef-n what do you think about latest commit ? it's an hack, but the idea is basically always using the indirection (map type) for all primary keys.

**Comment by strk** [comment]
Only, we're now back to not having a proper test for the main bug (the crasher)

**Comment by jef-n** [comment]
What's the performance penalty?

**Comment by strk** [comment]
Is there any performance test to check it out ? I'm checking it by loading a millions edge topology and don't see the fid mapping being a bottleneck

**Comment by strk** [comment]
Actually, after checking, the test for signed attributes is still good (still fails on master) -- only a test for editing the feature is missing

**Comment by strk** [comment]
Signed int fix pushed, editing patch moved to #2797

**Pull request closed without merging**
