### PR TITLE
When interactively moving a callout line, holding shift will cause the callout to snap to 15 degree angle increments

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by roya0045** [comment]
How does it deal with rotated maps?

**Comment by nyalldawson** [comment]
@roya0045 
> How does it deal with rotated maps?

It didn't, but I've reworked the code now to handle that!

**Comment by roya0045** [comment]
@nyalldawson That saved you a bug report 😆 Though what I was curious was to know if the intended behaviour was to have them at a right hangle in relation to the POV or the map crs.

 Sorry causing you more work.

**Comment by nyalldawson** [comment]
>right hangle in relation to the POV

I think this is the "correct" behaviour -- the intention is for nice cartography, so we should respect the map rotation here

> Sorry causing you more work.

Not at all! I'd just completely overlooked the whole map-rotation question!

**Review by nirvn — APPROVED** [review]

**Pull request merged**
