### PR TITLE
Prepare expression before checking for eval errors

### PR DESCRIPTION
**Pull request by strk**
otherwise failing with:

QFATAL : TestQgsExpression::represent_value() ASSERT: "expression4.hasEvalError()" in file
              /usr/src/qgis/qgis-master/tests/src/core/testqgsexpression.cpp, line 436

See https://issues.qgis.org/issues/17722

### CODE REVIEW

**Comment by strk** [comment]
@m-kuhn that test was added by you with 050119c2baf5c72630791edaee7c62dfa6c2cf7a - was there any reason to skip the prepare call ? Or it looks like the evalerror status is dependent on uninitialized memory state (succeeded on travis, failed on my machine)

**Comment by m-kuhn** [comment]
I think QgsExpression should have a safe way to handle unprepared evaluation. So far this way of using QgsExpression is supported.
Any idea why this isn't triggered on travis?

**Comment by strk** [comment]
No idea why travis doesn't trigger the failure, can it have to do with mRootNode not being initialized in the QgsExpressionPrivate initialization list but only in the class definition, as if it was a static ? It sounds like some new syntax which may be unsupported or threated differently in the different compilers ? I'm using GCC 6.3.0 here, while Travis uses CLANG ?

Can you reproduce my failure on your side ?

**Comment by m-kuhn** [comment]
```
build-Desktop-debug $ ctest -R QgsExpression$
Test project /home/mkuhn/dev/qgis/build-Desktop-debug
    Start 239: PyQgsExpression
1/1 Test #239: PyQgsExpression ..................   Passed    0.34 sec
```

**Comment by strk** [comment]
What compiler are you building with ?

**Comment by m-kuhn** [comment]
CMAKE_CXX_COMPILER:STRING=/usr/lib64/ccache/clang++

but I would be surprised if gcc wouldn't support default member initializers if that's what you suspect.

**Comment by strk** [comment]
I get many similar failures from `output/bin/qgis_expressiontest evaluation` too:
```
FAIL!  : TestQgsExpression::evaluation(unary minus text) Compared values are not the same
   Actual   (exp.hasEvalError()): 0
   Expected (evalError)         : 1
--
FAIL!  : TestQgsExpression::evaluation(unary minus null) Compared values are not the same
   Actual   (exp.hasEvalError()): 0
   Expected (evalError)         : 1
--
FAIL!  : TestQgsExpression::evaluation(plus invalid) Compared values are not the same
   Actual   (exp.hasEvalError()): 0
   Expected (evalError)         : 1
--
FAIL!  : TestQgsExpression::evaluation(minus nan) Compared values are not the same
   Actual   (exp.hasEvalError()): 0
   Expected (evalError)         : 1
...
```

**Comment by strk** [comment]
Could it be QString.isNull vs. QString.isEmpty, used in `QgsExpression::hasEvalError()` ? I'm linking against libpq 5.7.1 here, how about there ?

**Comment by strk** [comment]
checking for isEmpty makes no difference :(

Are you building with DEBUG on ? How about Travis ?

**Comment by m-kuhn** [comment]
I was wrong. I can reproduce this locally, I was running the wrong test above.

Could you add some debug statements to get the evalErrorString() so we know what is actually triggered here exactly on travis and verify why this isn't triggered also locally.

Something like this on travis:

```
qDebug() << expression.evalErrorString();
Q_ASSERT( false );
```

**Comment by strk** [comment]
See 965eb3b9c4
Logs should have "xxx" prefix for you to look at, in travis output

**Comment by m-kuhn** [comment]
Looks like you missed a line there.

**Comment by strk** [comment]
Did you figure out what the problem was ?

**Comment by strk** [comment]
Was it d01f94f7ef8761f0a477c2b323756e5f8d493049 ?

**Comment by m-kuhn** [comment]
Yes. It qas this one. A mix of different issues. Q_ASSERT only triggering in debug, the test was actually nonsense and fixing it properly revealed a potential crash.

**Comment by strk** [comment]
Cool, I'm glad this was useful! Thank you for trusting me :)

**Comment by m-kuhn** [comment]
Thank you for digging into this!

**Pull request closed without merging**
