### PR TITLE
Base default image cache size on system memory

### PR DESCRIPTION
**Pull request by nyalldawson**
Instead of always defaulting to 100mb, then base the cache size
on the system memory:

- > 32gb, use 500mb
- 16-32gb, use 250mb
- else 100mb

The larger sizes can make a big difference to rendering speed for
complex projects, so let's let powerful systems utilise all that
memory!

(Only supported on linux for now)

## Description

[Replace this with some text explaining the rationale and details about this pull request]

### CODE REVIEW

**Review by nirvn — APPROVED** [review]
Looks good to me.

This QgsApplication::systemMemorySizeMb() function should move to a core QgsNative class whenever we implement one.

**Comment by 3nids** [comment]
It would be better in QgsNative, yes
can you implement Windows and Mac as detailed here: https://stackoverflow.com/a/8123087/1548052 ?

**Comment by nyalldawson** [comment]
@3nids 
> It would be better in QgsNative, yes

It can't, as QgsNative is in gui and we need this from a core class

> can you implement Windows and Mac as detailed here: https://stackoverflow.com/a/8123087/1548052 ?

I'm trying the Windows implementation now. I'll leave mac to someone who can test that!

**Comment by 3nids** [comment]
wouldn't it be time to introduce a core QgsNative? it would be much cleaner. Mostly a copy/paste from the gui classes?

**Comment by nyalldawson** [comment]
> wouldn't it be time to introduce a core QgsNative? it would be much cleaner. Mostly a copy/paste from the gui classes?

I think it's overkill for this function at this stage. (The big reason we needed QgsNative in the first place was to get cocoa code available for macos if I recall correctly.)

**Comment by 3nids** [comment]
okay, agreed!

**Pull request merged**
