### PR TITLE
Atlas scope variables are all static

### PR DESCRIPTION
**Pull request by nyalldawson**
These won't be changed in the lifetime of the scope, which will
only ever be used for a single atlas feature only

Marking them as static means that the expression preparation
of atlas related expressions can replace any use of @atlas* vars
with static precalculated nodes, resulting in a nice performance
boost when working with complex atlas setups.

### CODE REVIEW

**Comment by roya0045** [comment]
Let's say if I have a rule based render using the geometry of the current atlas feature or one if its attribute, will the canvas still update normally when the atlas feature is changed in the layout? I just want to be sure of what making them 'static' entails.

**Comment by nyalldawson** [comment]
> Let's say if I have a rule based render using the geometry of the current atlas feature or one if its attribute, will the canvas still update normally when the atlas feature is changed in the layout?


Yep, that'll still work as intended (because all the expressions are reconstructed with the new map render which occurs after the Atlas feature changes).

**Comment by roya0045** [comment]
@nyalldawson Excellent news! I'm glad we're getting all the optimization for 3.18. BTW I'm trying to convert all the qregex to QregularExpressions, I think that would also improve things, let me know if this is a good idea as I have done quite a bit but must finish some others.

**Comment by nyalldawson** [comment]
>  all the qregex to QregularExpressions

Just a tip -- if you conditionally ifdef this in only for qt 5.15 then you'll be able to use the wildcard flags which were added in that version to make porting away from qregexp easier. That's my recommendation!

**Pull request merged**
