### PR TITLE
[processing] polygon from layer extent test

### PR DESCRIPTION
**Pull request by ghtmtt**

### CODE REVIEW

**Comment by ghtmtt** [comment]
My local computer (maybe not only mine) is stuck when running ProcessingQGIS test.
I tried also to see the building output of the fork as suggested here https://lists.osgeo.org/pipermail/qgis-developer/2017-January/046466.html but it fails.

Hoping the build will go straight with the PR

**Comment by nyalldawson** [comment]
@ghtmtt test looks good to me - can you please rebase this to fix the merge conflicts?

**Comment by ghtmtt** [comment]
conflict fixed

**Comment by ghtmtt** [comment]
@nyalldawson no idea why the test now fails, I just fixed the small conflicts..

**Comment by m-kuhn** [comment]
The following algorithm misses a `type: vector` after the conflict fix

    algorithm: qgis:polygonfromlayerextent

**Comment by ghtmtt** [comment]
@m-kuhn @nyalldawson any chance to merge this? Thanks!

**Comment by m-kuhn** [comment]
Can you rebase on master to get it into a mergable state?

**Comment by ghtmtt** [comment]
I tried to fix the conflicts, but now the test fails and it returns also a segmentation fault... Really no idea what it's happening there...

**Comment by m-kuhn** [comment]
git checkout good_test2
    git fetch origin # adapt repository name to local config
    git rebase origin/master # same as above
    # fix your conflicts
    git push -f

**Comment by ghtmtt** [comment]
@m-kuhn I get a huge mess with the other branch during the rebasing, so I created a new and clean PR #4149 
This PR can be closed

**Comment by m-kuhn** [comment]
Yeah, solving conflicts is a PITA. I never managed to completely avoid failures in the process.

**Comment by ghtmtt** [comment]
Ahaha glad that I'm not the only one that become crazy with the conflicts ;) thanks Matthias!

**Pull request closed without merging**
