### PR TITLE
Move clear T attr on windows before tmp file is renamed

### LINKED ISSUE #32118: Why would .qgz files need a temporary (T) attribute (Windows)
**Describe the bug**

I just discovered that project files (.qgz) on our Win Server are not backed up by our Synology backup application. The reason for this behaviour is the T attribute which is added to the file in the moment it is saved. It occurs both on the windows server and on my local windows computer. Only if I save the project file as .qgs it doesn't get that T attribute. Since project files are not truely temporary files, and I'm not aware of a configuration option I suspect it to be a bug.
(The phenomenon was described earlier on gis.stackexchange, but there was no answer whatsoever:
https://gis.stackexchange.com/questions/306458/qgz-files-and-replication-thereof)
**How to Reproduce**

**QGIS and OS versions**
OS: Win 10 Pro, Win Server 2019
QGIS: At least all versions since April 2019 including 3.8.3

**Additional context**

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #32118

### CODE REVIEW

**Comment by elpaso** [comment]
@RudiU like this?

**Comment by RudiU** [comment]
Yes, thank you -I'd expect the second attribute deletion as not being 
necessary, but I could be mistaken...

Have a nice day

Rudi

Dipl.-Biol. Rudolf Uhl
FÖA Landschaftsplanung GmbH

Auf der Redoute 12
D-54296 Trier

Telefon ++49 +651 91048-20 (Durchwahl), -0 (Zentrale)
Email rudi.uhl@foea.de
Web www.foea.de


--------------------------------------------------
Geschäftsführung:
    Dipl.-Ing. Ute Jahns-Lüttmann
    Dr. Jochen Lüttmann
    Dipl.-Ing. Werner Zachay
Sitz der Gesellschaft:
    Trier, AG Wittlich, HRB 40305

Am 10.10.2019 um 09:38 schrieb Alessandro Pasotti:

**Comment by elpaso** [comment]
> Yes, thank you -I'd expect the second attribute deletion as not being necessary, but I could be mistaken... 

Which one is the "second"?

**Comment by RudiU** [comment]
#ifdef Q_OS_WIN
   else
   {
     // Clear temporary flag (see GH #32118)
     DWORD dwAttrs;
     dwAttrs = GetFileAttributes( filename.toLocal8Bit( ).data( ) );
     SetFileAttributes( filename.toLocal8Bit( ).data( ), dwAttrs & 
~FILE_ATTRIBUTE_TEMPORARY );
   }
#endif // Q_OS_WIN

I'd expect the attribute not being changed by rename


Dipl.-Biol. Rudolf Uhl
FÖA Landschaftsplanung GmbH

Auf der Redoute 12
D-54296 Trier

Telefon ++49 +651 91048-20 (Durchwahl), -0 (Zentrale)
Email rudi.uhl@foea.de
Web www.foea.de


--------------------------------------------------
Geschäftsführung:
    Dipl.-Ing. Ute Jahns-Lüttmann
    Dr. Jochen Lüttmann
    Dipl.-Ing. Werner Zachay
Sitz der Gesellschaft:
    Trier, AG Wittlich, HRB 40305

Am 10.10.2019 um 11:41 schrieb Alessandro Pasotti:

**Comment by elpaso** [comment]
> #ifdef Q_OS_WIN   else   {     // Clear temporary flag (see GH #32118)     DWORD dwAttrs;     dwAttrs = GetFileAttributes( filename.toLocal8Bit( ).data( ) );     SetFileAttributes( filename.toLocal8Bit( ).data( ), dwAttrs & ~FILE_ATTRIBUTE_TEMPORARY );   } #endif // Q_OS_WIN I'd expect the attribute not being changed by rename 

that's not in the code anymore,  I moved it up a couple of lines and removed the else.

**Pull request merged**
