### PR TITLE
Add linux native progress report API

### PR DESCRIPTION
**Pull request by nirvn**
## Description
Joy, GIF:
peek 2018-08-07 10-07

Works on: unity, gnome-shell (with dash to dock), kde plasma.

@nyalldawson , approval requested from you :)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]
Looks great!

**Comment by nyalldawson** [comment]
(I'd tag this a feature too :P)

**Comment by nirvn** [comment]
@nyalldawson , I had to change the way we go at it to rely on a hardcoded desktop file name (i.e. "qgis.desktop", the desktop file name we use in our official .deb packages).

It's not ideal, but as far as I understand, there is no way to automatically retrieve an associated .desktop file of a running executable.

**Comment by nirvn** [comment]
I will leave this open for 24 hours for anyone to comment on this approach. If I don't see any objections by then, I'll merge. 

@jef-n , will `qgis.desktop` remain our desktop file name for the foreseeable future?

**Comment by jef-n** [comment]
@nirvn I don't see a need to change it

**Comment by nirvn** [comment]
@jef-n , good, I don't see a reason why we'd want to change it either.

**Pull request merged**
