### PR TITLE
Reorganize Polygon symbol dialogs

### LINKED ISSUE #41: Vector Style: Reorganize polygon symbol layers options
A proposal to reorder options provided in symbol layer dialog
### Simple Fill
1. Fill
1. Fill style
3. Stroke
4. Stroke Width
5. Stroke Style
6. Join Style
8. Offset

### SVG Fill
1. Texture width
1. Fill
3. Stroke
4. Stroke Width
5. Rotation
8. SVG Groups / Symbols

### PR DESCRIPTION
**Pull request by DelazJ**
Group parameters that look alike for a better sequence (Fill --> Stroke --> Join --> placement)
also modify color widgets label
Fix https://github.com/qgis/qgis3_UIX_discussion/issues/41

Before (left) vs after (right) screenshots

image

image

not sure about `Texture width` placement below
image

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by 3nids — APPROVED** [review]

**Comment by nyalldawson** [comment]
> not sure about Texture width placement below

I think I'd move that to the top - just like size in the  point symbol dialogs and image width in the raster fill dialog. On that note - is there a common label we could use for "texture width"/"image width" ?

**Comment by DelazJ** [comment]
> is there a common label we could use for "texture width"/"image width" ?

How about size?

**Comment by nirvn** [comment]
+1 to move texture width to the top.

**Comment by DelazJ** [comment]
and about the label?

**Comment by nirvn** [comment]
@DelazJ , @nyalldawson , I personally don't mind if the label stays as is. Can we merge this now, and change the label later if we settle on a better alternative?

**Comment by DelazJ** [comment]
Updated the Texture width placement in the dialog.

**Comment by m-kuhn** [comment]
Much more intuitive

**Pull request merged**
