### PR TITLE
[Feature] Symbol to expression

### PR DESCRIPTION
**Pull request by roya0045**
## Description
This PR aims to convert symbologies to expression in order to use them later. This is a step towards @m-kuhn 's approach instead of storing fids ( I need to do timing comparison between the two approaches  for layers of varying size), see [ this comment](https://github.com/qgis/QGIS/pull/30727#issuecomment-534149312.).

Otherwise in general this can be an utility thing.

This mostly leverage existing code and add minimal functions to allow the storage and transfer of information.

This is related to #33594 

The use of this expression is twofold:

- to add a way for the user to properly display the full expression (mostly with nested symbology)
- to allow the user to use said expression as a filter in functions.

## Example
symbol_exp

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [x] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by nirvn** [comment]
@roya0045 , please read the instructions (https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) to set up the pre commit hook in your dev. environment. As you can see with the travis failure, you have indentation issues which would have been caught when you git commit your change when the pre commit check runs locally. 

Don't check the "I have run the scripts/prepare-commit.sh" item if you have not run the script.

**Comment by roya0045** [comment]
> @roya0045 , please read the instructions (https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) to set up the pre commit hook in your dev. environment. As you can see with the travis failure, you have indentation issues which would have been caught when you git commit your change when the pre commit check runs locally.
> 
> Don't check the "I have run the scripts/prepare-commit.sh" item if you have not run the script.

The scripts has issues on my windows VM. It tends to simply error, I'll try to debug it.

**Comment by roya0045** [comment]
Unsure as to why the test fails, the expression worked when I tested it locally. Forcing caching does not seem to help either in the travis tests.

**Comment by nirvn** [comment]
@roya0045 , a functional dev. environment includes having the pre-commit script run flawlessly, continue to focus on getting your dev. environment up and running as a priority.

I haven't reviewed the code of this PR; that said, my gut feeling here is that you'll have a hard time getting it reviewed as the goals and _practical uses_ of the proposed changes aren't clearly stated.

**Comment by roya0045** [comment]
@nirvn I debugged the bash code and adapted it to my need in order to get it to work. One problem was that the EOL were converted to windows style instead of unix.

I have also added more details to the description, let me know if this is clearer.

**Comment by roya0045** [comment]
Ok found the issue, the hash generated by the converted symbology is not the same value as the one generated by other symbologies. I'll try to find a way to deal with this.

**Comment by roya0045** [comment]
@m-kuhn @nyalldawson The tests that I did locally are all good. If you have some time for a review it would be appreciated.

**Comment by roya0045** [comment]
I have added code to handle else conditions.

**Comment by roya0045** [comment]
Added example to showcase formatting/conversion.

**Comment by roya0045** [comment]
Azure test failure does not appear to be related.

**Comment by roya0045** [comment]
Symbol_expression doesn't seem to work as a filter, this is curious.

**Comment by roya0045** [comment]
@m-kuhn @nyalldawson I forgot that double evaluation was not possible with expressions. To make this functionnal and as an alternative to my other approach (using fids and a new expression parameter) I would need to evaluate this expression twice, once to get the string and the other time to evaluate the condition.
I have two ways to do this:
1) evaluate only the variable first in the legend to replace in the expression before evaluation. 
2) implement a way to evaluate an element more than once in the expression engine/parser.

Both can be done sequentially, but the first might be more safe.

**Comment by roya0045** [comment]
Reviews would be appreciated

**Comment by roya0045** [comment]
@nyalldawson any hopes for a review when you got some time?

**Comment by roya0045** [comment]
@nyalldawson simple ping if you could look at this, it shouldn't break anything.

**Comment by roya0045** [comment]
Now that the freeze is over, could someone review this?

**Comment by roya0045** [comment]
This should be safe to merge, can we do a dry run?

**Comment by roya0045** [comment]
Not stale, awaiting review.

**Comment by roya0045** [comment]
Closing this as #33819 contains the same code, will reopen if needed to merge only this part of the code.

**Pull request closed without merging**
