### PR TITLE
[FEATURE][processing] Import geotagged photos algorithm

### PR DESCRIPTION
**Pull request by nyalldawson**
There's a bit here.

Starting with the algorithm: This implements a work-in-progress "import geotagged photos" algorithm for processing. It allows selection of a folder which it will scan for jpg files which have been geotagged and creates a PointZ layer with the result, with attributes for photo path, altitude, direction and timestamp. Optionally the scan can be recursive and you can create an optional table of photos which could not be read or which were missing geotags.

(There's a bit left todo here - unit tests, proper handling of the timestamp, adding support for TIF?) 

I realise there's a few great plugins for handling geotagged photos out there, yet I feel that there's a need for a reliable core algorithm for handling this import too. Mostly because the plugins rely on 3rd party libraries which aren't always available (this one uses gdal -- so it's always going to work). I don't feel like this removes the need for the plugins -- they are still much more powerful and feature filed.

The second part is an addition to the processing API to allow algorithms to set hints for the editor widget setup for layers created by that algorithm, which are applied if the layer is loaded back into qgis on completion of the algorithm execution. This is used by the import photos algorithm to automatically set the "photo" field to use the attachment resource so that photos are shown within the feature forms by default. @alexbruy I know you've been against this support in the past, but maybe the way this is unobtrusively handled in the API is acceptable for you?

### CODE REVIEW

**Comment by alexbruy** [comment]
@nyalldawson do you think we should also add similar API to set layer styling/labeling? And probably expose these settings to user somehow, so they can adjust them.

**Comment by alexbruy** [comment]
Looks good to me.

**Comment by nyalldawson** [comment]
@alexbruy

> do you think we should also add similar API to set layer styling/labeling?

I think so - I'm just not sure on the best approach. It'd be easy to add a similar method to set the QML style for the layer (since it's just a string), but that's only going to work for existing qml. It's almost impossible to create QML from scratch - so this wouldn't work for e.g. an algorithm to create a categorised renderer for a layer.

Maybe we need some little QgsProcessingLayerPostprocessor class, which algs can implement and set for the result layers in the context... Actually... Maybe that's a better approach then what's done here anyway...

**Comment by nyalldawson** [comment]
@alexbruy 

https://github.com/qgis/QGIS/pull/6606 implements a much more flexible approach for the post processing - it will allow layer styling, metadata changes, etc...

**Comment by NathanW2** [comment]
Yes!

**Pull request merged**
