### PR TITLE
Build grass on travis to get build warnings

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by blazek** [comment]
Adding GRASS on Travis is welcome. Thanks.

**Comment by m-kuhn** [comment]
Should be good to ship, it passed on linux and mac os x builds are unchanged.

Anyway, it will only check for compiler warnings, writing tests will still be a manual task ;)

Implementing the base tests for the provider (like e.g. here https://github.com/qgis/QGIS/blob/master/tests/src/python/test_provider_postgres.py) would be straightforward, just copy the dataset, copy one of the existing provider tests and update the code for loading the data.

**Comment by blazek** [comment]
Please merge the pull request once you think its ok.

There is already provider test: tests/src/providers/grass/

**Comment by m-kuhn** [comment]
Nice. The grass6 test now appears in the travis log, so that should be good.

The nice thing about the provider tests is that they verify that the different providers have the same behavior.
Anyway, glad to have compiler checks and your already existing tests run on travis now :+1:

**Comment by blazek** [comment]
Thank you Matthias!

**Comment by blazek** [comment]
BTW, QGIS may be compiled with both GRASS 6 and 7 in one build, but it would be probably too heavy and too much work to install GRASS 7 from source on Travis.

**Comment by m-kuhn** [comment]
Is there a ppa for precise which provides grass 7 dev packages and can be installed in parallel?

**Comment by blazek** [comment]
There is 7.0.1-2~ubuntu12.04.1 on https://launchpad.net/~grass/+archive/ubuntu/grass-stable.

**Comment by m-kuhn** [comment]
Let's see https://github.com/qgis/QGIS/pull/2321

**Pull request closed without merging**
