### PR TITLE
[qt6] QRegExp is gone

### PR DESCRIPTION
**Pull request by m-kuhn**
For good

All we can do is remove this deprecated method with Qt6.

### CODE REVIEW

**Comment by roya0045** [comment]
@m-kuhn just to be sure, are you aware of #42431

**Comment by m-kuhn** [comment]
Yes, this work actually originates there.
Integrated in #42431

**Comment by roya0045** [comment]
@m-kuhn ah good, I wanted to save your some time in your flurry of PR.

**Comment by m-kuhn** [comment]
Thanks for the hint @roya0045 

would be really good to get get over with this regex story

**Pull request closed without merging**
