### PR TITLE
fix: replace referer http header by dedicated class QgsHttpHeader

### PR DESCRIPTION
**Pull request by nyalldawson**
Supersedes https://github.com/qgis/QGIS/pull/45055

### CODE REVIEW

**Comment by nyalldawson** [comment]
@benoitdm-oslandia 

I took a look at the sip error -- it was caused because there was default values specified for both the QVariantMap and QgsHttpHeaders arguments. So when neither was specified when called from Python there was the ambiguity. Solution is to remove the default value from the older version.

**Comment by benoitdm-oslandia** [comment]
@nyalldawson Thanks a lot! I will never find the cause of this SIP compilation error!

**Comment by agiudiceandrea** [comment]
Hi @nyalldawson, it seems to me this PR is involved in the regression described in https://github.com/qgis/QGIS/issues/48532.

**Comment by agiudiceandrea** [comment]
It seems to me also the bug reported at https://github.com/qgis/QGIS/issues/51409 may be introduced as a side effect of this PR.

**Pull request merged**
