### PR TITLE
[tr] Fixing conflict in spanish translation

### PR DESCRIPTION
**Pull request by cdavila**
## Description
This pull request fixes the conflict created in previous Spanish translation update (#5834).

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
This pull request looks strange, it adds the "untranslated" flag to some translated texts.
Which (how many) translations did you want to update?

**Comment by cdavila** [comment]
I don't remember now, but according to the old files I keep it could be 89

**Comment by m-kuhn** [comment]
El cambio del string "nice" to "agradable" es lo unico que queda, cierto? Si es posible borrar los "unifinished" podemos avanzar y mergearlo.

**Comment by cdavila** [comment]
¿Cómo puedo comprobar lo que queda y borrar los "unfinished"?
De todas formas, no sé si ya es importante hacer el merge para release-2_18

**Comment by m-kuhn** [comment]
Probablemente sería más facil reempezar y simplemente traducir el termino nice. QGIS 2.18 recibe patches hasta el release 3.4, así que más que nada depende de si tu quieres invertir tiempo.

**Comment by jef-n** [comment]
superceeded by 6c06421aee

**Pull request closed without merging**
