### PR TITLE
[Backport 3.10] Fix performance issue when splitting polygons

### PR DESCRIPTION
**Pull request by wonder-sk**
Backport of #37295 to 3.10.x

### CODE REVIEW

**Comment by wonder-sk** [comment]
How does it work with the 'not for merge' label? (I haven't seen it used before)

**Comment by nyalldawson** [comment]
@wonder-sk 

We're now delaying all non-critical backports (non crash, non data corruption fix) to LTR by 1 point release, so that the change has at least one month's worth of testing in a stable release prior to inclusion in LTR. It's to reduce risk of introducing regressions mid-LTR cycle.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Moved to https://github.com/qgis/QGIS/pull/36812

**Comment by wonder-sk** [comment]
Ah ok cool that makes sense :+1:

**Pull request closed without merging**
