### PR TITLE
Fix issue with plugin tests 

### LINKED ISSUE #41181: running tests insider Docker does not work with tags later then 3_14
I came across this issue while working on [Processing R Provider Plugin](https://github.com/north-road/qgis-processing-r). Running the command `docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh processing_r.test_suite.test_package"` returns `ERROR: no output from the test runner! (exit code: 0)` with never release versions while working fine with older versions (it seems that anything before 3_16 works). The issue can be seen in the  [log from Travis](https://travis-ci.org/github/north-road/qgis-processing-r/builds/735898967). With 3_4 version everything works but the latest version fails with the described issue.

I did some testing and come across couple of issues in `/QGIS/.docker/qgis_resources/test_runner/qgis_testrunner.py` which I can provide details for. This cause some of the problems but not all of them. And while i got the `qgis_testrunner.py` to work, I am not able to figure out why `qgis_testrunner.sh` does not receive any output.

If possible I would like to discuss the issue and help to solve it :-)

### PR DESCRIPTION
**Pull request by JanCaha**
Fixes #41181 (maybe a partial fix)

- add missing python module for running tests

- fixes situation if variable `out ` is in `bytes` which causes problems

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Thanks @JanCaha !

**Comment by JanCaha** [comment]
I am not 100% sure if this will solve the issue completely. There maybe other minor fixes that need to be done. I will see if the tests start to work now.

**Comment by Gustry** [comment]
@JanCaha I will try to give it a try soon, if it's not enough.
@strk Do you have any idea ? (read #41181 ) Related to #36189 ?

I tried on one plugin and indeed it's failing now.

**Comment by JanCaha** [comment]
I played with it yesterday a bit. It seems that there is one system dependency was still missing. It was hard to figure out, because I played with the docker container a lot.

But #41230 should provide a final fix that makes the test runnable.

**Pull request merged**
