### PR TITLE
Cleaning unused png files and respective folder 

### PR DESCRIPTION
**Pull request by SrNetoChan**
This PR aims to fix the problem presented here:

https://github.com/qgis/qgis3_UIX_discussion/issues/12

The method was:

- Delete all png files with a corresponding svg file
- Check for existing png files in the themes/default folder that were not used anywhere in the code, except in the resources file:

    find ./images/themes -type f -name "*.png" -printf "%f\n" | sort -u > all_pngs.txt
    grep -r -hof all_pngs.txt src/* python/* tests/* --exclude="*.qrc" | sort -u > found.txt
    grep -vf found.txt all_pngs.txt
    
- Make sure that those png files were not used in the code
- Delete their entry in the resources.qrc file

In another commit I have deleted themes_old and themes_original folder

@nyalldawson Can you give a look please?

### CODE REVIEW

**Comment by nirvn** [comment]
@SrNetoChan , nice! I'll have a look too when travis confirms this PR to be green.

**Comment by nyalldawson** [comment]
@SrNetoChan Great stuff! I'll let @nirvn handle this one.

**Comment by nirvn** [comment]
@SrNetoChan , quick question, when searching for PNG files being used in the code, did you check only in the src/ directory, or did you also check in python/ ?

**Comment by SrNetoChan** [comment]
src/, python/ and tests/

**Comment by SrNetoChan** [comment]
But before each delete, I confirmed in the all repository (skipping the build master one)

**Comment by DelazJ** [comment]
Great! Very nice work, @SrNetoChan I think it'd also fix https://github.com/qgis/qgis3.0_api/issues/51
Btw It'd be nice if we can also clean image files in documentation repository (unfilled point in https://github.com/qgis/QGIS-Documentation/issues/793)- but I guess i may be taking advantage. Sorry

**Comment by nirvn** [comment]
@SrNetoChan , good work, cheers.

**Comment by SrNetoChan** [comment]
@DelazJ I was thinking about that. Now that I found the right find/grep commands, it should not be that hard.

**Comment by DelazJ** [comment]
@SrNetoChan Ok, thanks.
I wonder if svg icons would work for replacement (and avoid generating png files). @rduivenvoorde is that possible to use svg files for replacement in the conf.py file? Any news on the move to sphinx 1.3?

**Comment by SrNetoChan** [comment]
AFAIK, SVGs work fine for HTML, but not for PDF.

**Pull request merged**
