### PR TITLE
fix autofinder

### PR DESCRIPTION
**Pull request by nyalldawson**
Supersedes https://github.com/qgis/QGIS/pull/40674

(I found it easier to review after replacing the raw userrole + ... values with descriptive values!)

### CODE REVIEW

**Comment by roya0045** [comment]
If you want to change those I don't mind. Though I'm not sure if the new abstraction makes things easier.. but it doesn't matter as long as it works once again.

**Comment by roya0045** [comment]
@nyalldawson any chances this can be integrated in 3.16.2?

**Comment by nyalldawson** [comment]
@roya0045 done!

**Comment by roya0045** [comment]
@nyalldawson Thanks a ton!

**Pull request merged**
