### PR TITLE
fix #12876

### PR DESCRIPTION
**Pull request by vmora**

### CODE REVIEW

**Comment by nyalldawson** [comment]
@vmora fix looks good, but can you amend the commit message to be more descriptive? Otherwise people either need to visit hub or read the code to work out what is fixed by this..

**Comment by vmora** [comment]
Done.

**Comment by vmora** [comment]
@nyalldawson I also found something strange: the features with NULL field in their size definition are drawn, I don't think it's wanted.

I'm looking into that, I think I remember a PR on that allow dispay of legend/preview of symbls with DD props. If it's along the lines of what I tryied in #1856, it may be the cause of the problem.

Do you rebember the PR that does that (I can't find it).

**Comment by vmora** [comment]
@nyalldawson the problem may be in QgsSymbolLayerV2::evaluateDataDefinedProperty where you are defaulting if the evaluation of the expression is not OK, which is probably the case if a NULL field is used.

What do you think ?

**Comment by nyalldawson** [comment]
@vmora basically if the value is null then the symbol falls back to the value specified by the user... This is how labeling/composer behaves with respect to data defined properties, and the intention is that data defined properties are "overrides" of the specified value.

It also has the nice side effect that if a feature isn't available (eg in the legend) then the legend symbols are shown with correct values still.

**Comment by vmora** [comment]
@nyalldawson but is it responsible for the mentionned problem (feature with NULL field are drawn) ?

**Comment by nyalldawson** [comment]
Well, if the value for size is null then the feature will be drawn with the default symbol size.

**Comment by vmora** [comment]
This yields a very different result as 2.8 because the feature are drawn were they used not to be.

**Comment by jef-n** [comment]
We haven't updated [QgsProjectFileTransform](http://qgis.org/api/classQgsProjectFileTransform.html) for a while.  Would setting the default size to 0 where ddp exists when transforming to 2.9 work?

**Comment by vmora** [comment]
Replacing the old size expression with:

     CASE WHEN myField IS NOT NULL THEN sqrt(symBolsize * (myField)) ELSE 0 END

Also works. 

In this case the symbol preview and legend are ok, because the feature doesn't exist, and the NULL features are excluded. It may have some perf cost though, and it's an huglier expression, but at least it's quite clear what it's done.

**Comment by vmora** [comment]
Maybe this discussion should go to the ML (which one?) to let users decide.

**Comment by vmora** [comment]
@nyalldawson BTW how is the default size configured ?

**Comment by nyalldawson** [comment]
@vmora it's just the static size field - so the same size as would be used if the data defined control is described. The expression you've posted looks like a good approach, I think that's the way to go.

**Comment by nyalldawson** [comment]
Oops, described = disabled

**Comment by vmora** [comment]
@nyalldawson Can you merge this PR plz, I'll make another one for the fix.

**Comment by jef-n** [comment]
coalesce(ddp,0) ?

**Comment by vmora** [comment]
@jef-n beautiful !

**Pull request merged**
