### PR TITLE
Show field type icons on attribute table headers

### PR DESCRIPTION
**Pull request by uclaros**
## Description
I really miss having this info on the attribute table after getting used to other database managers.

Screenshot_20200206_212933
If it is on purpose not there, in order not to clutter the view, then maybe there could be a settings entry to enable / disable it.
Any other reason not to have this?

### CODE REVIEW

**Comment by roya0045** [comment]
Good move @uclaros !

**Comment by nyalldawson** [comment]
@nirvn thoughts?

For reference -- this information is currently available by hovering over the column header

**Comment by nirvn** [comment]
-0.5, I'm not a big fan of this for two reasons:
1/ this takes up horizontal space away from actual column name, which will be problematic for datasets with a large nb of attributes;
2/ it's not dark theme friendly.

**Comment by uclaros** [comment]
1. What about adding a settings entry, defaulting to false? I know I would disable it too under certain circumstances.
2. Most icons are not designed to be dark theme friendly, being either too bright, having white background, low contrast with the dark background etc. Those specific icons don't look too bad on the attribute table imo. They are almost invisible though on the field drop-down when calculating fields...

**Comment by gioman** [comment]
> -0.5, I'm not a big fan of this for two reasons:
> 1/ this takes up horizontal space away from actual column name, which will be problematic for datasets with a large nb of attributes;
> 2/ it's not dark theme friendly.
> 
> Edit: it also risks unnecessarily "stealing focus". Header should not get in the way visually.

While I understand this points, this is still of great help/utility for the vast majority of common users.

**Comment by roya0045** [comment]
I think adding a setting would be good, though I think it should default to true as most users would benefit from it. @uclaros I didn't check but could a right click in the header provide the option to display or hide those icons? I feel like a right click would be optimal for this as having a dedicated option would be annoying to toggle.

**Comment by nirvn** [comment]
I'd challenge the assertion made here that this is something "most users" / "common users" are in need of. 

Field type is mostly something you'd need to know when modifying the field. In this case, we have the calculator bar which shows field type, as well as edit widgets hinting at type.

**Comment by gioman** [comment]
> I'd challenge the assertion made here that this is something "most users" / "common users" are in need of.
> 
> Field type is mostly something you'd need to know when modifying the field. In this case, we have the calculator bar which shows field type, as well as edit widgets hinting at type.

sure, but maybe your experience of users is different from mine. Most of the users I meet/woork with have little to no idea of what data types are the columns they are working with, they usually (mostly) overlook the hover on the column header and ends up looking at data type in vector properties.

**Comment by SrNetoChan** [comment]
I think it's useful for most users as well. As useful as in any other place that the icons now appear. No one remembers all field types in their data.

Besides, if there's a setting to turn it of, why not?

**Comment by uclaros** [comment]
@nirvn A use case is having, among others, three fields which are a(int), b(str), c(str). You open the calculator bar, select a (you see it's int) and type *b+c* and you get `1 + 1 = 11`. 
Getting the datatypes of all fields at a glance solves this and helps you know your data better.

ps. IMO we also need those to show on delete fields and reorder fields spartan dialogs

**Comment by nirvn** [comment]
Big +1 on adding icons on the delete n reorder fields dialogs. 

As for expressions, we could add the field type in the auto complete tooltip as users type in the field.

**Comment by uclaros** [comment]
@nirvn I'll open a feature request for that!

Is there a simple way to disable showing the icons in the table view instead of the model? I think it would be preferred, but I couldn't find one.

**Comment by 3nids** [comment]
I'm also -0 on having the field type in the attribute table as a header icon. I'd rather have it as a tooltip. But no big deal to me.
But most important to me, please avoid adding a new setting. I think it is best to try to keep settings to critical things and that you have a continuum when you switch between work stations.

**Comment by nyalldawson** [comment]
I'm -1 too - there's just too much happening in that screenshot. One possible solution would be to only show these icons while in edit mode for the layer, where they are arguably much more useful to see..

**Comment by gioman** [comment]
> One possible solution would be to only show these icons while in edit mode for the layer, where they are arguably much more useful to see..

arguably, but I'll take it (just in edit mode rather than nothing).

**Comment by uclaros** [comment]
@nyalldawson There's too many NULLs in the screenshot making it look like there's too much going on! Dbeaver database manager also has icons for filter and sort and it still does not look too congested to me, you get used to it fast.

@3nids As a user, I was thinking that settings are ideal for this kind of ux customization. After all, there are already such settings that can make switching workstations confusing, like changing the ui theme, changing the locator prefixes, or snapping on invisible features to name a few. Type icons are nowhere near that big a change.

**Comment by roya0045** [comment]
@uclaros could the icons be semi transparent in the background of the header? Though this might make things unclear...

**Comment by 3nids** [comment]
@uclaros don't get me wrong, settings are good when they affect some substantial behaviors. They are already a lot of settings, and adding more just brings too much distraction.

More generally, I think we should have a procedure to deal with these kind of UX changes where there is no direct consensus (I don't think the QEP is the approach here). @nirvn ?

**Comment by uclaros** [comment]
Did this hit a dead end by not wanting to add a new setting?
Could there be another way to enable this? In the (small) sample of 10 people involved in the conversation 7 find it useful, it's not insignificant.

**Comment by gioman** [comment]
> it's not insignificant.

agree

**Comment by roya0045** [comment]
It got lost in limbo, that happens.

**Pull request closed without merging**
