### PR TITLE
Fix proc modeler

### PR DESCRIPTION
**Pull request by ghtmtt**
## Description
Resurrect some missing parameters from Processing Modeler (Expression, MapLayer, RasterBand). Small changes but for MapLayer some more eyes are welcome ;)

Sorry for the firsts 2 useless commit, just ignore them

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'm unsure how this relates to modeler - getParameterFromString is only used by the GRASS and SAGA providers. What am I missing here?

**Comment by nyalldawson** [comment]
@ghtmtt 

Well... this allows those parameters to be used by GRASS/SAGA, so I think it could be valuable anyway :)

I believe those other widgets are missing from the modeler because they don't implement a widget to configure them as inputs yet. See the giant mash of logic at https://github.com/qgis/QGIS/blob/master/python/plugins/processing/modeler/ModelerParameterDefinitionDialog.py#L104 ... that's where the change needs to be made.

**Comment by ghtmtt** [comment]
@nyalldawson I see.. So my last commit has nothing to do with that? I thought that the missing parameters should also be added to the processingregistry.. sorry for the noise, I thought I found what was wrong but it seems I'm mixing up things ;)

**Comment by ghtmtt** [comment]
@nyalldawson ok Travis is happy, but I'm unsure this is fixing the problem ;)

**Comment by m-kuhn** [comment]
> @nyalldawson ok Travis is happy, but I'm unsure this is fixing the problem ;)

well... did you try it? ;)

**Comment by ghtmtt** [comment]
yes :) seems working

processing modeler_036

**Comment by ghtmtt** [comment]
it is worth to do this for all parameters?

**Comment by m-kuhn** [comment]
it would certainly be added value.

**Comment by m-kuhn** [comment]
Thanks a lot. Tiny detail, they need to be strings `QgsApplication.processingRegistry().parameterType('raster')`

**Comment by ghtmtt** [comment]
and strings are.. ;)

**Comment by nyalldawson** [comment]
Nice fix, thanks!

**Comment by nyalldawson** [comment]
By the way - if you're looking for a related fix, the "Enum" input type is totally useless in modeler at the moment ;) We either need to add a way to allow definition of the available choices or hide this parameter type from the modeler.

**Comment by ghtmtt** [comment]
@nyalldawson yes I tried to imagine an use case of Enum in the modeler ;) actually I also for MapLayer I couldn't find an algorithm that accepts this input..

**Comment by nyalldawson** [comment]
> yes I tried to imagine an use case of Enum in the modeler ;) 

maybe just remove this one from the modeler then?

> actually I also for MapLayer I couldn't find an algorithm that accepts this input..

"Convert map to raster" does

**Comment by ghtmtt** [comment]
> maybe just remove this one from the modeler then?

done in #6929 

> "Convert map to raster" does

Oh I see, thanks!

**Pull request merged**
