### PR TITLE
[FEATURE] Interactive curve editing for property overrides

### PR DESCRIPTION
**Pull request by nyalldawson**
This adds a new interactive "curve" to the assistant widgets.
It allows you to fine tune exactly how input values get
mapped to output sizes/colors/etc.

Think GIMP or Photoshop curves, but for your data...

Obligatory screencast:
https://www.youtube.com/watch?v=LI4G5aJJLQg&feature=youtu.be

### CODE REVIEW

**Comment by NathanW2** [comment]
Holy crap! Pure win.  I think MapBox has something like this and it was
pretty cool.

**Comment by nirvn** [comment]
@nyalldawson , fantastic work, as always.

Few comments / suggestions:
- It'd be nice to get a "value at dot" label when mouse hovering a dot on the curve.
untitled
- It'd also be nice to have a couple of curve "presets" below the curve graph, which a user could click to quickly apply a standard curve progression.

**Comment by nirvn** [comment]
@nyalldawson , oh, also, might be worth harmonizing the gradient editor graph with the transform curve graph:
untitled
- The dots could be of same size, upsize the curve dots?
- I like the "#" grid in the transform curve graph,  maybe add a grid in the gradient editor?

**Comment by luipir** [comment]
impressive feature @nyalldawson!

**Comment by nyalldawson** [comment]
> oh, also, might be worth harmonizing the gradient editor graph with the transform curve graph:

Done!

**Comment by nyalldawson** [comment]
Bonus feature round!!

image

A matching histogram populated in a background thread for a nice responsive GUI....

**Comment by nyalldawson** [comment]
> It'd be nice to get a "value at dot" label when mouse hovering a dot on the curve.

I'll give this a shot at a later stage... there's only so much QWT api wrangling one can handle at a time....

**Comment by nirvn** [comment]
@nyalldawson , brilliant! :)

**Comment by nyalldawson** [comment]
Screencast demo: https://www.youtube.com/watch?v=CwFqaFHQOdI&feature=youtu.be

**Comment by wonder-sk** [comment]
Pure awesomeness :tada:

**Pull request merged**
