### PR TITLE
add colors in the log panel for critical and warning levels

### PR DESCRIPTION
**Pull request by Gustry**
## Description

Easier to debug when you have a long list of debug messages:

screen shot 2018-03-07 at 16 57 40

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by luipir** [comment]
make sense to have them configurable to allow better visualization for e.g. daltonics ? btw wonderful :)

**Comment by NathanW2** [comment]
Yes! Nice work @Gustry

**Comment by nyalldawson** [comment]
Good move!

I'm a -1 on making this a config option. A hidden setting key could be used, but I don't think this needs a new widget in options (too much clutter)

**Comment by Gustry** [comment]
Maybe I can add at least one option in the "advanced" panel? I doubt someone will go and change there. But one of our client is daltonics and I keep asking this client about QGIS logs when the plugin we are working on is crashing. So I would feel bad after this PR ... ;-)

**Comment by NathanW2** [comment]
Yeah I think we need a mode for the while UI.

**Comment by luipir** [comment]
> why not make a boolean key for switching on a daltonic mode

because daltonism is not a 0/1 feature! color patterns can be differtent. BTW I like the idea to have boolean switch on a configured (hidden) set of settings.

**Comment by nyalldawson** [comment]
> because daltonism is not a 0/1 feature! color patterns can be differtent. BTW I like the idea to have boolean switch on a configured (hidden) set of settings.

Fair enough. I think it's time we split this discussion out to a different area -- either a QEP "brainstorm" about approaches or a thread on the dev list? Let's get some good global plans for how to handle this instead of tackling it bit by bit in an ad-hoc manner.

In the meantime, I'd suggest merging this PR but flagging this change as something to address in the grand-plan.

**Comment by luipir** [comment]
I agree @nyalldawson, but the PR is still with colors set in the code and not configurable (hidden or not), may I review to request this change?

**Comment by Gustry** [comment]
Yes it was my plan @luipir. I will update it

**Comment by Gustry** [comment]
screen shot 2018-03-15 at 18 25 10

@luipir @nyalldawson Is-it ok like this?

**Comment by nyalldawson** [comment]
Maybe just "colors/info" (no "logs" group) would be better? Like I've mentioned, I'd like to keep this more generic and reusable in other areas too.

**Comment by Gustry** [comment]
Yes indeed. Code updated.

**Comment by luipir** [comment]
great :)

**Comment by NathanW2** [comment]
Are we all ok with this?  Looks like it's in a merge state now.

**Comment by nyalldawson** [comment]
Yep, done

**Pull request merged**
