### PR TITLE
[Bugfix] Avoid using copyStyle() / pasteStyle() within duplicateLayers()

### PR DESCRIPTION
**Pull request by SebDieBln**
When duplicating layers, the style was applied to the new layers by means of `copyStyle()` and `pasteStyle()`. This is considered ~~poor programming~~ a bug as the clipboard may only be used when the user specifically commands it.
While fixing this, a few other things popped up:
- `pasteStyle()` checked the geometry type on vector layers, but `loadNamedStyle()` did not
- `copyStyle()` and `pasteStyle()` contained pretty much the same code as `importNamedStyle()` and `exportNamedStyle()`, which already led to [bug # 13746](https://hub.qgis.org/issues/13746) because a new feature was only added to one of them

To make it easier for the reviewer I did not squash all commits into one. But I can do it, if it is favored.

### CODE REVIEW

**Comment by SebDieBln** [comment]
@NathanW2 With only a week left until feature freeze, is there anything I can do to help you review and merge this PR?

**Comment by NathanW2** [comment]
@SebDieBln sorry I was off over xmas and needed a break.  Can review now.

**Comment by nyalldawson** [comment]
Looks good, thanks!

**Comment by SebDieBln** [comment]
@nyalldawson 
Yes! I just saw you merging this, live!

**Pull request merged**
