### PR TITLE
More verbose message when deleting a layout page

### PR DESCRIPTION
**Pull request by DelazJ**
## Description
Relates to #26618 (i think a proper fix would be to keep the items where they are but at least now people are aware of what's about to happen)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by DelazJ** [comment]
Incidentally, I realized that you can delete all the pages in a layout. No crash afaics, but should it be?

**Comment by nyalldawson** [comment]
I'm a -1 here. We should just fix the real issue, the new text is rather messy.

**Comment by DelazJ** [comment]
And what would be the neat fix here? remove the contents also, or move them to the next/previous/selected page? I made suggestions in the issue report and followed the feedback I got.

**Comment by nyalldawson** [comment]
> And what would be the neat fix here? remove the contents also, or move them to the next/previous/selected page? I made suggestions in the issue report and followed the feedback I got.

I don't think the items should be moved at all -- they should remain in place (i.e. floating after the final page)

**Comment by DelazJ** [comment]
> I don't think the items should be moved at all -- they should remain in place (i.e. floating after the final page)

Euh... `they should remain in place`<> `(i.e. floating after the final page)`. Depending on the page you removed (the last one or else), you might be moving the items.
I will give it a try though this sounds beyond my c++ skills.

**Comment by nyalldawson** [comment]
My advice: don't try to fix this one in C++ - it's not a trivial fix at all.

First, we need to lock down the correct logic. Maybe we should just delete all items *with* the page? @nirvn?

**Comment by nirvn** [comment]
@nyalldawson , yep, +1 to delete items connected to page being removed.

**Comment by m-kuhn** [comment]
What's the consensus here? Move to issue tracker?

**Comment by DelazJ** [comment]
So do we agree with deletion of the items when their page is deleted?

**Comment by nyalldawson** [comment]
Yes - let's go that approach. I'll close this PR since that fix is unrelated to this approach.

**Pull request closed without merging**
