### PR TITLE
renamed algorithm_tests.yaml

### PR DESCRIPTION
**Pull request by anitagraser**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thank you for updating.

There is also algorithm_tests_gdal.yaml (and probably more in the future), it would be good to mention that as well.

**Comment by m-kuhn** [comment]
@anitagraser does this change sound ok for you to do?

**Comment by anitagraser** [comment]
@m-kuhn sure can add algorithm_tests_gdal.yaml to the text as well, if that's what you mean.

**Comment by m-kuhn** [comment]
That's the idea, yes. It has been moved from a monolithic file to one per provider.

**Comment by anitagraser** [comment]
ok, added reference to algorithm_tests_gdal.yaml

**Comment by m-kuhn** [comment]
Manually merged,

thanks a lot

**Pull request closed without merging**
