### PR TITLE
Order map keys by length before using in replace function

### LINKED ISSUE #42940: Expression Editor: Replace Map Function Does Not Match Two-Digit Numeric Key to Value Properly
**Describe the bug**
In a replace(map()) function, the replacing/mapping does not function properly when the key is numeric and more than one digit.

For instance, if the key were to be 1 and the value Paved - Asphalt, it will work properly, but if the key were to be 11 and the value Curb - Stone, it will simply put Paved - AsphaltPaved - Asphalt.

**How to Reproduce**

`replace("CAMPRS_SHOULDER_ID",map('0','NULL','1','Paved - Asphalt','2','Gravel','3','Earth','4','Vegetation','5','None','6','Curb - Asphalt','7','Curb - Concrete','8','Curb - Granite','9','Paved - Concrete','10','Gutter - Concrete','11','Curb - Stone','12','Gutter - Paved'))`

**QGIS and OS versions**

QGIS version
3.18.2-Zürich
QGIS code revision
515138c171
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.2.2
Running against GDAL/OGR
3.2.2
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
Compiled against PDAL
2.2.0
Running against PDAL
2.2.0 (git-version: 24dd45)
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.0.0
Running against PROJ
Rel. 8.0.0, March 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
CalculateGeometry; 
cartography_tools; 
ClipMultipleLayers; 
MemoryLayerSaver; 
project_colors_dock; 
slyr; 
toggle_labels_widget; 
zoom_level; 
db_manager; 
MetaSearch; 
processing

**Additional context**
Example screenshot:  
image

### PR DESCRIPTION
**Pull request by uclaros**
## Description
In the `map` variant of `replace` function make longer keys be replaced first since they may contain smaller keys in whole, eg. keys '1' and '11'

Fix #42940

### CODE REVIEW

**Comment by roya0045** [comment]
Can you add a test with the 1, 11 case and something like 11111 for the input?

**Comment by roya0045** [comment]
And also change the doc. ;)

**Comment by uclaros** [comment]
I added the test, but I don't think this needs to be noted in the doc. The expected behavior is to replace full matches first, then partial ones.

**Comment by roya0045** [comment]
When I meant doc what I had in mind was to add an examples and/or explanation in https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/resources/function_help/json/replace#L15

Thanks for the test!

**Comment by agiudiceandrea** [comment]
Does rhis also change the behaviour of the ´array´ variant?

**Comment by uclaros** [comment]
@roya0045 ok, on second thought I updated the description and added an example.

@agiudiceandrea This only affects the map variant, where the implicit sorting of the map keys may change the user's expectations. The array variant is unchanged, keys are replaced in the order they are found in the array, allowing the user to fine tune by rearranging the array contents.

**Comment by Saijin-Naib** [comment]
Thank you all for helping me understand what was going on, and for working so quickly to adjust this.

Truly, thanks a ton!

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
