### PR TITLE
Misc 3.12 backports

### PR DESCRIPTION
**Pull request by nyalldawson**
Cleaning up backport bot's leftovers :)

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]
Looks good to me.
Thanks for going over this, we really need the backport bot working again !!
Do you want to integrate them still before patch release or give them a month cool down time?

**Comment by nyalldawson** [comment]
These are low risk commits + the higher risk, but serious issue fix for #34926. Given the severity of #34926 I'd rather merge before the patch release.

**Comment by m-kuhn** [comment]
Go for it then :+1:

**Comment by nyalldawson** [comment]
Thanks @m-kuhn !

**Pull request merged**
