### PR TITLE
Move maptools to gui library

### PR DESCRIPTION
**Pull request by m-kuhn**
- [x] Moves the base code for advanced digitizing to the gui library. This makes it possible to write CAD maptools in plugins.
- [x] The canvas mouse events provide a QgsMapMouseEvent which enhances the default QgsMouseEvent with map coordinates and snapping utils.
- [x] The inheritance order of MapToolEdit and MapToolAdvancedDigitizing is reversed: MapToolAdvancedDigitizing is a MapToolEdit, not vice versa.
- [x] The cursor is properly set
- [x] Verify snapping works
- [ ] Verify other tools than QgsMapToolAddFeature
- [x] Verify perpendicular and parallel work

### CODE REVIEW

**Comment by m-kuhn** [comment]
Update which still needs to be tuned a lot

**Comment by 3nids** [comment]
is this ready for testing?

as it was discussed for the node tool, do you see a way to set the snapping to the current layer of the map tool? i.e. snap to single layer.

open question: rename advanced digitizing to cad (tools)?

**Comment by m-kuhn** [comment]
No, it's not ready at all.

"snap to single layer": would that be a new option?

For me, cad tool would be preferable since it's shorter but IIRC you told me that there was some hesitation because of possible confusion with existing plugins/tools?

**Comment by 3nids** [comment]
yep snap to single layer would be perfect.

for the naming, indeed it was to avoid name conflict with existing plugins:

* cad tools
* cadinput (deprecated)
* CADDigitize

What about technical drawing? technical digitizing?
@NathanW2 opinion on the naming?

**Comment by m-kuhn** [comment]
It is pretty much complete now.

Will need to verify snapping. When I enable snapping on my demo project it is constantly re-indexing, but that also happens on master. Probably a bug.

**Pull request closed without merging**
