### PR TITLE
Attempt to fix crash when adding fields to existing table

### PR DESCRIPTION
**Pull request by nyalldawson**
Refs #32819

Needs further testing before merge

### CODE REVIEW

**Comment by m-kuhn** [comment]
What leads to the assumption that it's this call which is broken? The docs seem clear to me.

https://doc.qt.io/qt-5/qabstractitemmodel.html#beginResetModel

> You must call this function before resetting any internal data structures in your model or proxy model.

**Comment by nyalldawson** [comment]
@m-kuhn 

A couple of things:

1. I reproduced the crash from #32819 and the stacktrace related to the model reset
2. the code surrounded by the begin/end reset model correctly uses begin/end inserting rows. This leads me to believe that the reset is redundant, and I'm unsure whether nesting begin reset/insert calls like this is allowed by Qt
3. These lines were added in fccd8e58cda97c2a11a1ad4c113ada3a21318870 as an attempt to fix https://github.com/qgis/QGIS/issues/21012, which was later fully closed by 6215f773e22cb55dac694ae6b213cd1f9ac39c53 . So possibly they are redundant in any case given the follow up commit.

That said, removing them has resulted in many failing tests, so there's clearly more at play here...!

**Comment by roya0045** [comment]
Is this issue present on master? I tried to replicate with my partial table loader branch and could not replicate it (neither on my old 3.4.0 which should still have that behavior I assume).

**Comment by nyalldawson** [comment]
@m-kuhn I think this is safe to merge now. The situation is:

1. I can sometimes reproduce https://github.com/qgis/QGIS/issues/32819 , but it's very temperamental and I couldn't write any unit tests which reliably triggered it.

2. With this commit I don't see the crash... but I'm not 100% sure it's fixed, because even without the commit I'd only see the crash sometimes.

3. There **is** an issue with this code, because we're making calls to beginRemoveRows while a beginResetModel is still active. I can't find any documentation describing this as a bad thing, but my suspicion (and the stack traces I get from the crash lead me to believe) that it is...

4. We don't need to reset the model here -- the rest of the function is (now) correctly signalling the atomic row based changes. And that's a better approach generally vs resetting the model anyway...

What do you think?

**Comment by m-kuhn** [comment]
It's a public method, if it's called from outside, it won't be wrapped in begin/end modification calls?

Would it be more appropriate to add this as an internal method and have the public one trigger the internal one within reset commands?

**Comment by nyalldawson** [comment]
> It's a public method, if it's called from outside, it won't be wrapped in begin/end modification calls?

No, they happen internally within the method

**Review by m-kuhn — APPROVED** [review]
All good then :+1: 
Thanks

**Pull request merged**
