### PR TITLE
Fix crash when opening CSV with wrong codec

### LINKED ISSUE #46219: QGIS crashed opening projects with csv files and "System" encoding
## User Feedback

Hello,

I found the following problem: I have a fairly complex project that involves various sources of information (gpkg, shp, csv). When I try to open it, QGIS gives an error and closes.

I debugged the project by opening it by segments until I found where the error was and apparently it is associated with the encoding of the csv files: in my project the files have “System” encoding, but when I looked for it in QGIS I can't find it.

To check this I manually modified the encoding in the qgs file and was able to open it correctly.

In summary, since there is no "System" encoding, QGIS gives an error when opening the project as it tries to open the csv with that encoding and cannot.

Thank you

## Report Details

**Crash ID**: [d1f7afe8399d52daab504182ca4d3f9b8b3ed3c1](https://github.com/qgis/QGIS/search?q=d1f7afe8399d52daab504182ca4d3f9b8b3ed3c1&type=Issues)

**Stack Trace**
<pre>
QTextCodec::toUnicode :
providerMetadataFactory :
providerMetadataFactory :
providerMetadataFactory :
QgsVectorLayer::setDataProvider :
QgsVectorLayer::readXml :
QgsMapLayer::readLayerXml :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
QgsTemporalControllerDockWidget::temporalController :
QObject::qt_static_metacall :
QAbstractItemView::activated :
QAbstractItemView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Only I open the project and in some point QGIS crashes. 
As I mentioned in the bug/crash report I think that is related with the lack of "System" encoding option

### Versions

3.22.0 and 3.22.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I can open the project in QGIS 3.16.14 without problems.

### PR DESCRIPTION
**Pull request by elpaso**
Fix #46219

### CODE REVIEW

**Comment by nyalldawson** [comment]
This looks good to avoid the crash, but what's the actual underlying issue here? Why is the "system" encoding missing from the osgeo4w builds? (ping @jef-n )

**Review by nyalldawson — APPROVED** [review]

**Comment by elpaso** [comment]
> This looks good to avoid the crash, but what's the actual underlying issue here? Why is the "system" encoding missing from the osgeo4w builds? (ping @jef-n )

Actually I can reproduce on my Linux machine and there is definitely something wrong going on because `System` codec returns 0x0:

```python
In [1]: QTextCodec.codecForName('utf8')
Out[1]: <PyQt5.QtCore.QTextCodec at 0x7f4989db44c0>

In [2]: QTextCodec.codecForName('system')

In [3]: QTextCodec.codecForName('System')
```

**Comment by elpaso** [comment]
The same applies to 3.16.

**Comment by elpaso** [comment]
and : https://bugreports.qt.io/browse/QTBUG-72183, I'm wondering if falling back to  `QTextCodec.codecForLocale()` is a viable option.

**Comment by nyalldawson** [comment]
> QTextCodec.codecForLocale() is a viable option

I think that's a good move!

**Pull request merged**
