### PR TITLE
[FEATURE] Support secondary geometry columns in PostGIS layers

### PR DESCRIPTION
**Pull request by nyalldawson**
Before, any additional geometry columns would have their values converted to an ewkt string and stored in a string field type.

This was not ideal, as it has some significant issues:
- complex geometries convert to a very long string, causing the attribute table to suffer lengthy hangs while trying to show the ewkt representation
- there is no easy way to convert a ewkt string back to a real geometry value (ie, no expression function or similar), making these additional geometry columns effectively unusable

Now, any additional geometry columns will have their values stored as QgsGeometrys. This allows easy use of these values within expressions (just reference the field and use with all the existing geometry functions, eg area("secondary_geom") ), field calculator (update the main geometry based on the
attributes of a secondary geometry!), and also a super-cool bonus is that these geometries can now easily be used within geometry generator symbol layers (eg draw the line strings stored in a secondary line geometry column in addition to the main point geometry*)

* Will be even more useful when we get labelling geometry generators!

Questions:
- is this the best approach? Could we somehow avoid the metatype requirements (maybe via https://github.com/qgis/qgis3.0_api/issues/49)? Or is this an acceptable requirement for handling non-default qt field types?
- how best to handle secondary geometries with a different CRS to the main geometry...
- why didn't I add unit tests? (answer:I'm still kind of on holidays, so I will, I just want feedback first!)
- who can raise their hand to fund labeling geometry generators? (contact me!!)

### CODE REVIEW

**Comment by haubourg** [comment]
ref: https://github.com/qgis/qgis3.0_api/issues/21

**Comment by vmora** [comment]
+1 for crs in QgsField, returning null if not applicable, not sure about the union idea, we already store length and precision in QgsFieldPrivate even when not required, crs should be the same IMO.

the code looks good to me otherwise.

**Comment by m-kuhn** [comment]
> we already store length and precision in QgsFieldPrivate even when not required, crs should be the same IMO.

length and precision are not mutually exculsive, while (length/precision) and crs are. But no big deal, I'm happy to accept whatever the one who gets his hands dirty prefers :)

**Comment by nyalldawson** [comment]
QgsCoordinateReferenceSystem is small - the only member is the QExplicitlySharedDataPointer. And given that QgsField is also implicitly shared I don't think the extra memory required by not using a union is a significant issue.

--- However ----

I'm still partial to having the crs within QgsGeometry. Again, the only extra cost would be a small implicitly shared QgsCoordinateReferenceSystem member. But the advantage would be that the CRS for geometries would always be available, without requiring any knowledge of the source layer. It also allows these "referenced geometries" to be used for cases when no fields are applicable, eg something like creating a geometry representing the canvas extent, or a layer's bounds.

I can also potentially see the use for data formats which do not mandate that all features share a common crs.

**Comment by m-kuhn** [comment]
I also think that a QgsGeometry with CRS builtin can be useful for certain tasks.

I just wonder if it makes sense to handle the main geometry and an attribute geometry differently?

**Comment by m-kuhn** [comment]
@nyalldawson what's the status of this?

My personal view is

* By default layers have a main geometry column and a CRS and a `QgsGeometry` in `QgsFeature::geometry()`
* Geometry columns maintain geometry information including CRS in `QgsField::geometryInformation` and deliver a `QVariant` wrapped `QgsGeometry`.
* There is a special `class QgsReferencedGeometry : public QgsGeometry` with an additional property `QgsReferencedGeometry::crs`. This will be a separate `QgsField` type, any code working on this will need to be adjusted to handle this kind of geometry.

**Pull request closed without merging**
