### PR TITLE
Fix typo in contributors list

### PR DESCRIPTION
**Pull request by DelazJ**
## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by nyalldawson** [comment]
@root676 can you comment on whether this is correct?

**Comment by DelazJ** [comment]
@nyalldawson off course he knows his name better than I could. My fix was not on the name; it's my phone that "corrects" it.

**Comment by nyalldawson** [comment]
@DelazJ I must admit I was quite confused!

**Comment by Gustry** [comment]
Isn't committer for the commit right access?

**Comment by DelazJ** [comment]
@Gustry yes afaik and thus is what I'm fixing unless I miss some information. Nyall's doubt is related to my first commit.

**Comment by Gustry** [comment]
Arf yes, sorry. Ok.

**Comment by root676** [comment]
@nyalldawson sorry, I have missed this message - yes Clemens Raffler is correct.

**Comment by root676** [comment]
@DelazJ thanks for fixing the commiter status, I must have mixed this up when I added myself to contributers.

**Pull request merged**
