### PR TITLE
[OTB] Improve parameter selection

### PR DESCRIPTION
**Pull request by troopa81**
## Description

Follows #39939

This PR proposes to improve the parameter selection for OTB algorithm. It's related to this OTB [MR](https://gitlab.orfeo-toolbox.org/orfeotoolbox/otb/-/merge_requests/768).

QGIS-OTB interface needs to be modified on both side, and I hope these modifications could land in both next stable/LTR versions: OTB 7.3 and QGIS 3.16.

That's why I would like to backport it in 3.16

### CODE REVIEW

**Comment by nyalldawson** [comment]
LGTM!

**Comment by troopa81** [comment]
> LGTM!

Thanks for quick review, but please wait before merging, I want to better test the whole thing before merging

**Comment by nyalldawson** [comment]
What's the status with this pr? is it ready for re-review/merge?

**Comment by troopa81** [comment]
> What's the status with this pr? is it ready for re-review/merge?

Yes! thanks

**Comment by nyalldawson** [comment]
This looks good to me. @rkanavath  are you happy for merge?

**Comment by troopa81** [comment]
@rkanavath are you ok for merging this PR?

**Comment by nyalldawson** [comment]
Let's do this...

**Comment by nyalldawson** [comment]
Manually backported to https://github.com/qgis/QGIS/pull/40712

**Comment by troopa81** [comment]
Thanks @nyalldawson  for merging and backporting

**Pull request merged**
