### PR TITLE
Expose control over strength of ambient/diffuse/specular contributions to 3d phong materials

### PR DESCRIPTION
**Pull request by nyalldawson**
Gives users control over these, allowing for easy configuration of nicer looking 3d materials:

Peek 2024-01-04 08-20

### CODE REVIEW

**Comment by nyalldawson** [comment]
Ping @wonder-sk

**Comment by wonder-sk** [comment]
@nyalldawson I am not sure if I like this actually :see_no_evil: 

If I understand this correctly, for any of the three colors (ambient / diffuse / specular), the new slider works as a darkening factor (given it is in range [0,1]):
```
final_color = coefficient * original_color
```
So e.g. red 255,0,0 with coefficient 1.0 will stay the same, with coefficient 0.5 it will be equivalent of setting dark red (128,0,0) while keeping coefficient 1.0.

If my understanding is correct then:
- do we need this at all? if it is just another means to make the original color darker, user could do that in color widget... with all the new sliders the GUI gets a bit busy...
- wouldn't it be better to move this kind of coefficient to the color button widget? In the popup of the color button, there could be another slider before/after the transparency slider, which would set how dark the color is? Something like this: 
image
- if we want to keep the functionality and GUI as it is proposed, why not keep the shaders unmodified, and apply the coefficients when passing the color to the material? This would avoid extra complexity in the shader code...

**Comment by nyalldawson** [comment]
@wonder-sk 

> I am not sure if I like this actually 🙈
> If I understand this correctly, for any of the three colors (ambient / diffuse / specular), the new slider works as a darkening factor (given it is in range [0,1]):
> final_color = coefficient * original_color
> So e.g. red 255,0,0 with coefficient 1.0 will stay the same, with coefficient 0.5 it will be equivalent of setting dark red > (128,0,0) while keeping coefficient 1.0.

Mostly correct, but see my answer below:

> do we need this at all? if it is just another means to make the original color darker, user could do that in color widget... with all the new sliders the GUI gets a bit busy...

One issue that this addresses is that we currently store colors using only 0-255 ints. This effectively makes it impossible to darken the color manually without losing the hue/saturation of the color -- as you darken the color the ratio of the individual components approaches 1:1:1 and any darker color approaches black/grey. By exposing the factor control it allows us to choose more brighter and more saturated colors for ambient/specular while still having a way to dial back the strength of those effects. 

The other issue is that it's not obvious to users that you can eg decrease the amount of specular reflection by making the color darker. Without knowledge of the maths happening behind the scenes, my initial gut feeling would be that making a dark grey specular color would result in a ... dark grey highlight. Indeed until I dug into shaders and the theory behind Phong I just assumed a lot of the settings were kind of broken -- I'd try to make the shine on a material less prominent by decreasing the "shininess" control, but that would just have the effect of showing MORE shine color :rofl: I'd never thought that what was actually required was setting a darker color for the specular.

> wouldn't it be better to move this kind of coefficient to the color button widget? In the popup of the color button, there could be another slider before/after the transparency slider, which would set how dark the color is? Something like this:

Well, that slider is already there if you click the color button, so I'd probably avoid putting it in the menu (regardless of the above considerations!)

> if we want to keep the functionality and GUI as it is proposed, why not keep the shaders unmodified, and apply the coefficients when passing the color to the material? This would avoid extra complexity in the shader code...

That's a fair point!

**Comment by wonder-sk** [comment]
Yeah I agree with you that the setup of colors and shininess in Phong shading is very, very confusing. That's also why I would prefer not to add more widgets to control the material settings, as it may as well make things even more complicated for users.

If the implementation will not touch shaders, I can live with it :slightly_smiling_face:   ... and I hope we will switch to PBR as the default, so nobody will care about Phong material anyway :smile:

**Comment by nyalldawson** [comment]
@wonder-sk 
> If the implementation will not touch shaders, I can live with it 

Ok, done

**Comment by DelazJ** [comment]
The dialog in <3.35
image
in 3.35
image

@nyalldawson am I  correct in assuming that the first slider in terrain shading (refers to diffuse property, btw) shouldn't be there?

**Pull request merged**
