### PR TITLE
Use correct enum type for enum with negative values

### PR DESCRIPTION
**Pull request by nyalldawson**
Alternative to https://github.com/qgis/QGIS/pull/56079

### CODE REVIEW

**Review by nirvn — APPROVED** [review]

**Comment by troopa81** [comment]
It's a shame that we have to add an extra macro declaration when the flag declaration is just few lines later in the same file. Maybe we could have preprocessed the file to check if there is flag declaration and stores them in a dictionnary so we can decide wether its best to have a int or a flag, no?

**Comment by nyalldawson** [comment]
@troopa81 that'd be good, and was my first preference too. But sipify is entirely designed around a line by line read and my perl skills aren't good enough to do any major rewrites there 🤣

**Comment by troopa81** [comment]
> @troopa81 that'd be good, and was my first preference too. But sipify is entirely designed around a line by line read and my perl skills aren't good enough to do any major rewrites there 🤣

Yes, I've been there too and I don't even know how to create a dictionnary so ... ok

**Comment by DelazJ** [comment]
Hi Nyall,
I wonder if this is not the PR that broke the PyQGIS docs build (#56313). The dates match and it seems to modify some formatting in the docs, and from my understanding of the errors, formatting is (one of?) the root cause of the failure.

**Pull request merged**
