### PR TITLE
[processing] Rework 'singlepart to multipart' algorithm

### PR DESCRIPTION
**Pull request by nyalldawson**
As discussed in http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Processing-3-0-Possible-change-to-the-Singlepart-to-Multipart-algorithm-td5325595.html

This PR refactors the "Singlepart to Multipart" algorithm, by:

1. Implementing a 'Promote to multipart' algorithm. This algorithm purely upgrades geometry types from 
single part to multipart, without adding any extra parts or collecting geometries. (So basically the algorithm upgrades single parts to collections containing just a single part - the equivalent of PostGIS' 
ST_Multi function)

2. Adds a new algorithm "Collect geometries" which does what the 'field' option in Singlepart to Multipart used to do. This algorithm collects all features with matching fields (you could select more than one field -  unlike the current Singlepart to Multipart option) and outputs collection features containing these geometries. Just like dissolve (in fact, most of the code is shared with the optimised dissolve alg), but without the dissolving of overlapping parts.

3. Drops the now redundant 'Singlepart to Multipart' python algorithm.

The motivations here are:

1. simplicity of algorithms - keeping the Singlepart to Multipart as  just a straightforward 'make this geometry multipart type' algorithm, without the extra complexity and code inefficiency which comes with 
the current 'unique ID field' support. (Complying with the goal of keeping algorithms modular and focused on one particular task) 

2. unlocking future performance gains. Ideally we want algorithms to operate feature-by-feature whenever this is possible. This will allow us (in some future piece of work) to implement feature pipes where features pass through models having operations performed to each feature in a chain (instead of the current approach of multiple temporary output layers). This isn't planned work (yet), but making 
the 'Promote to multipart' algorithm operate feature-by-feature now, while we have the luxury of API and model break, will allow it to use these optimisations in a future 3.x release. The "unique ID field" support in 'Singlepart to Multipart' prevents this algorithm from operating feature-by-feature.

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , should we rename the "multipart to singleparts" algorithm? "Demote to Singleparts"?

**Comment by alexbruy** [comment]
Looks good to me.

**Comment by m-kuhn** [comment]
Can you add a "see also" section to the alg docs?

**Comment by nyalldawson** [comment]
> Can you add a "see also" section to the alg docs?

Which docs? the short help?

**Comment by nyalldawson** [comment]
> @nyalldawson , should we rename the "multipart to singleparts" algorithm? "Demote to Singleparts"?

"Demote" doesn't convey splitting to me - just discarding. "Split to singleparts"? (I don't have an issue with the current name however)

**Comment by m-kuhn** [comment]
> Which docs? the short help?

Wait... is the processing help still not on par with the expression help? Sorry...

**Comment by nyalldawson** [comment]
> Wait... is the processing help still not on par with the expression help? Sorry...

Processing documentation is a heavy work in progress. (Ping @ghtmtt !)

I can add a simple text string to the short help easily enough though. What do you think it should mention?

**Comment by m-kuhn** [comment]
*Promote to multipart* should mention the *Collect geometries* and vice versa.

**Pull request merged**
