### PR TITLE
[feature] Add ScaleBar and MessageLog components to QgsQuick library.

### PR DESCRIPTION
**Pull request by PeterPetrik**
This pull request is a subset of  [(#6490)](https://github.com/qgis/QGIS/pull/6490)
This adds ScaleBar and MessageLog components to QgsQuick library with related classes.
For background information see the associated [QEP](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/109).

### CODE REVIEW

**Comment by nyalldawson** [comment]
Not being up to scratch with these components - where is the scalebar rendering actually done?

**Comment by PeterPetrik** [comment]
@nyalldawson, the actual rendering is done [qgsquickscalebar.qml](https://github.com/qgis/QGIS/pull/6983/files#diff-b290921b227dca48af5a9339ebe2dffdR19). QML [Item](http://doc.qt.io/qt-5/qml-qtquick-item.html#details) is basic block for all of this stuff, similar to QWidget in the qgis_gui library

**Comment by nyalldawson** [comment]
> the actual rendering is done qgsquickscalebar.qml. QML Item is basic block for all of this stuff, similar to QWidget in the qgis_gui library

Ok, so it's done from scratch? There's no way to re-use QgsScaleBarRenderer here?

**Comment by PeterPetrik** [comment]
It would be (probably) possible to use `QgsScaleBarRenderer` inside [QQuickPaintedItem](http://doc.qt.io/qt-5/qtquick-customitems-painteditem-example.html). The problem I see is that this approach would first paint image and then use the image on QML canvas. The current implementation uses the native QML rendering, which gives some [rendering benefits](http://doc.qt.io/qt-5/qtquick-visualcanvas-scenegraph.html) and better user experience. And I am not sure how much code could be used from the `QgsScaleBarRenderer` to keep the QML rendering benefits.

**Comment by nyalldawson** [comment]
> A QQuickPaintedItem and rasterized widget rendering is not something I'd want to introduce here. Not sure how easy it would be to factor out common code to determine unit / segment number / segment size / ...

I understand that - I guess I'm just seeing that there's a huge functionality gap between the QML scale bar here and the functionality exposed by QgsScaleBarRenderer.

**Comment by PeterPetrik** [comment]
True. I think that for first few releases the applications will implement their own QML scalebar and just use the ScaleBarKit to be able to easily access all required input. The QML scale bar in the QgsQuick library is now just a little more than "example" how to properly create customized scale bar with any design.

**Comment by nyalldawson** [comment]
Yep, go ahead

**Pull request merged**
