### PR TITLE
[3d] If feature altitude is exactly coincident with terrain, add a tiny "tie breaker" amount

### PR DESCRIPTION
**Pull request by nyalldawson**
to avoid geometry planes coinciding exactly with terrain planes and the rendering
artefacts which happen as a result of this...

I.e. if planes are exactly coincident you get this:

image

By adding a tiny tie breaker we get:

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
@wonder-sk keen to hear your thoughts on this ~~hack~~ genius code

**Comment by timlinux** [comment]
Thank you for this, it will definately help. What happens if two other layers are coincident? Wont we get the same issue?

**Comment by wonder-sk** [comment]
@nyalldawson  oops sorry I have missed this PR...

To be honest, I am not a big fan of this kind of solution :smile: 

The problem is that as soon as you zoom just a little bit more, the [Z-fighting](https://en.wikipedia.org/wiki/Z-fighting) effect is back due to the limited precision of depth buffer... At the same time I do not have a good solution. Maybe we could automatically use polygon offset OpenGL feature (https://doc.qt.io/qt-5/qt3drender-qpolygonoffset.html) on entities where there is risk of Z-figthing - but I do not have experience with dealing with that and setup of the parameters... see also https://stackoverflow.com/questions/7836208/how-to-correctly-render-coincident-polygons-in-opengl-es

**Comment by nyalldawson** [comment]
@wonder-sk ok, I concur with your thoughts -- polygon offset seems like a much cleaner approach!

**Pull request closed without merging**
