### PR TITLE
Ensure dialog focus is returned after saving files on mac

### LINKED ISSUE #54332: Popup appears hidden behind QGIS
### What is the bug or the crash?

After selecting a target for a file, the popup disappears behind QGIS.

### Steps to reproduce the issue

1. Open the “Save vector features to file” popup.
2. In “Saved features” click “...” , then “Save to File...“
3. Select your favourite GeoPackage
4. The popup disappears in the background and QGIS has focus.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.9-Firenze | QGIS code branch | Release 3.28
-- | -- | -- | --
Qt version | 5.15.10
Python version | 3.11.4
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.42.0
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.3
OS version | macOS 13.4
  |   |   |  
Active Python plugins
QuickOSM | 2.2.3
profiletool | 4.2.6
processing_saga_nextgen | 0.0.7
Serval | 3.10.5
valuetool | 3.0.17
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.28.9-Firenze
QGIS code branch
[Release 3.28](https://github.com/qgis/QGIS/tree/release-3_28)
Qt version
5.15.10
Python version
3.11.4
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.42.0
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.3
OS version
macOS 13.4

Active Python plugins
QuickOSM
2.2.3
profiletool
4.2.6
processing_saga_nextgen
0.0.7
Serval
3.10.5
valuetool
3.0.17
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This is a widespread bug. In many cases the popup window gets placed behind the QGIS window.

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #54332

### CODE REVIEW

**Review by nirvn — APPROVED** [review]
Blah Qt -- is the behavior improved on Qt6 without the need of this extra code?

**Comment by nyalldawson** [comment]
> Blah Qt -- is the behavior improved on Qt6 without the need of this extra code?

:shrug: 

I've no access to a mac to test...

**Comment by dlejay** [comment]
> I've no access to a mac to test...

Then, how do you know the changes actually fix the issue? 😯

**Comment by nyalldawson** [comment]
@dlejay 

From years ago, when a similar fix was applied to elsewhere in the qgis codebase.

**Pull request merged**
