### PR TITLE
Processing: v.net.alloc add 'method' parameter

### LINKED ISSUE #44877: v.net.alloc missing 'method' option in Processing
### Feature description

I'm aware that v.net.alloc is labeled
"Allocates subnets for nearest centers _**(direction from center)**_"
in the processing toolbox.

But it would be great if the additional `method` parameter could be added:

https://grass.osgeo.org/grass78/manuals/v.net.alloc.html#parameters
> method=string
> * Use costs from centers or costs to centers
> * Options: from, to
> * Default: from

This change would be a great addition as I've found no other tool that integrates with QGIS and allows for calculations "to-centers".
Neither in the default processing toolbox, nor a plugin (QNEAT3, ORS Tools, ...), or pgRouting.

### Additional context

I want to automate which areas can reach services centers, not which areas can be reached from services centers.
This makes a big difference in the resulting area when considering one way streets or service centers close to highway links.

An alternative for my use case would be if the `GRASS shell` could be reached somehow via Python so I can execute the GRASS commands myself.
But I haven't found an API for that.

### PR DESCRIPTION
**Pull request by wilhelmberg**
## Description

Add the [`method` parameter](https://grass.osgeo.org/grass78/manuals/v.net.alloc.html#parameters) to `v.net.alloc` in the Processing Toolbox.
This allows for routing "from-centers" (current default) as well as routing "to-centers".

Background and screenshots of "from/to-centers" routing in https://github.com/qgis/QGIS/issues/44877

I'm not sure if the last part of the new line is correct: `|False|0|False`
I copied that from another description file.
Tried to figure out what these parameters mean exactly, but couldn't find any docs and [Grass7Algorithm.py](https://github.com/qgis/QGIS/blob/1906e19899c59a691968bdd2a27d7e88909d16f6/python/plugins/grassprovider/Grass7Algorithm.py) didn't provide any insights (for me).

No compilation needed for this change, I tested with an already installed QGIS 3.20.2 on Lubuntu 20.04.

Backporting would be nice, but I'm not sure if this is necessary as it is not a bug fix.

Closes https://github.com/qgis/QGIS/issues/44877

### CODE REVIEW

**Comment by nicogodet** [comment]
Based on https://qgis.org/pyqgis/master/core/QgsProcessingParameterEnum.html, it shoul correspond to `allowMultiple|defaultValue|optionnal`.

Parsing of the line is handle here 
https://github.com/qgis/QGIS/blob/1906e19899c59a691968bdd2a27d7e88909d16f6/python/plugins/processing/core/parameters.py#L169-L181

I believe that tests will be requested.
HOW TO : https://docs.qgis.org/3.16/en/docs/developers_guide/processingtesting.html

Tests should be added in https://github.com/qgis/QGIS/blob/master/python/plugins/grassprovider/tests/testdata/grass7_algorithms_vector_tests.yaml

**Comment by BergWerkGIS** [comment]
Could one of the maintainers please approve the workflows to be run?

----

@nicogodet thanks for the hints, links and explanations - these were very helpful.

* Updated the `method` parameter to be optional
* Added columns for forward and backward costs to the existing network test data
* Added two expected fixtures
* Added two tests
  * One for to-routing (with the `method` parameter)
  * One for from-routing (without the `method` parameter, as this is the default)

**Comment by nyalldawson** [comment]
@BergWerkGIS looks like the new tests are failing unfortunately!

**Comment by BergWerkGIS** [comment]
Thanks for the  ping @nyalldawson, I noticed the failing tests as well.
Seems they are more involved than I had anticipated. 
Any hints on what's wrong/missing would be very appreciated.
Unfortunately I only have time to work on this during the weekends, so it will be a few days until my next push. 
Seems there's no way around setting up a full build system locally?

In the meantime it turned out that I need the `method` parameter for `v.net.iso` as well.
And the `-u` flag for `v.net.alloc` and `v.net.iso`.

https://grass.osgeo.org/grass78/manuals/v.net.alloc.html#flags
> `-u`
> Create unique categories and attribute table
> Default: same category like nearest center

Ok to bundle all these changes into this PR? 
If/when I get the tests working.

**Comment by alexbruy** [comment]
Superseded by #45221

**Comment by BergWerkGIS** [comment]
@alexbruy thanks a lot for taking over 🙏 
I ran out of time setting everything up to be able to run the tests locally ☹️

**Pull request closed without merging**
