### PR TITLE
QGis class rename and cleanup

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR implements some API breaks for the QGis class:
- renamed the class to "Qgis". The current naming does not follow any standard capitalization, and a rename to "Qgis" follows the naming of other classes. Other options were "QGIS" or "qgis", but "Qgis" seems our best option.
- moved some non-deprecated static methods out of the class to global functions, and renamed with a "qgs" prefix. I think it makes sense for this class to just contain enumerations and constants.
- removed some deprecated constants

### CODE REVIEW

**Comment by nyalldawson** [comment]
See also https://github.com/qgis/qgis3.0_api/issues/22

**Comment by nyalldawson** [comment]
Any objections if I merge this before #3325 so @m-kuhn can deal with the merge conflicts? ;)

**Comment by m-kuhn** [comment]
Hehe, I was prepared for that ;)

**Comment by m-kuhn** [comment]
Please proceed if you feel comfortable. The reasoning sounds good and I'm not going to review 513 file changes in detail ;)

**Comment by wonder-sk** [comment]
:+1:

My secret choice would be just ```Qgs``` instead of ```QGis```, but ```Qgis``` also works fine :-)

A bit off-topic, what do you think about classes with odd ```Qgis``` prefix, like ```QgisApp``` or ```QgisInterface``` - shall we change their prefix to ```Qgs``` or keep them as they are?

**Comment by nyalldawson** [comment]
> A bit off-topic, what do you think about classes with odd Qgis prefix, like QgisApp or QgisInterface - shall we change their prefix to Qgs or keep them as they are?

I'm very much in favour of renaming them to the Qgs* standard.

**Pull request merged**
