### PR TITLE
fix server issue for double devicePixelRatio leading to DPI requests with decimals

### PR DESCRIPTION
**Pull request by tudorbarascu**
Some requests created with OpenLayers send the DPI parameters with decimal due to
devicePixelRatio and QGIS Server doesn't cope with that. This fixes it.

If not, a request with ``DPI`` ``112.5`` (my screen has 1.25 devicePixelRatio) will receive
```
<ServiceExceptionReport version="1.3.0"><ServiceException code="Invalid WMS Parameter">DPI ('112.5') cannot be converted into int</ServiceException></ServiceExceptionReport>
```
I think/hope it's the right fix. @pblottiere Care to take a look, please?
@manisandro  This should fix an issue encountered with Chrome on QWC2

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by rldhont — COMMENTED** [review]
Thanks for this fix.
Can you add a test ?

**Comment by tudorbarascu** [comment]
@rldhont Will try!

**Comment by pblottiere** [comment]
@tudorbarascu Thanks, LGTM!

As @rldhont suggested, a test would be nice. Let me know if you need help!

**Comment by pblottiere** [comment]
Nice, thank you for adding a test @tudorbarascu!

**Review by pblottiere — APPROVED** [review]

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
Thnaks for adding test

**Comment by tudorbarascu** [comment]
@pblottiere @rldhont Thanks for reviewing guys!

**Pull request merged**
