### PR TITLE
[ci] Run shellcheck as part of code_layout build

### PR DESCRIPTION
**Pull request by nyalldawson**
Inspired by @bje-'s work for gdal: https://github.com/OSGeo/gdal/pull/654

### CODE REVIEW

**Comment by nyalldawson** [comment]
:tada:  a billion shell script warnings!

**Comment by m-kuhn** [comment]
@nyalldawson I hope you don't mind if I push a commit or two ;)

**Comment by 3nids** [comment]
@m-kuhn I would advice to push these to master directly. That would avoid any rebase issue since I believe it's gonna take some time to fix this one.

**Comment by nyalldawson** [comment]
@m-kuhn please do! I had some local ones too, but I'll start pushing them to master so we don't overlap

**Comment by bje-** [comment]
Keep in mind that you don't want to use bash-isms if you want portability. If your scripts have `#!/bin/sh` at the top, Shellcheck should warn about using non-portable constructs.

**Comment by nyalldawson** [comment]
@m-kuhn I cherry-picked your commits onto master

**Comment by nyalldawson** [comment]
In the interest of moving this PR forward and not blocking the queue, I've excluded all the checks which currently fail. We can address them one-by-one in follow up work.

**Pull request merged**
