### PR TITLE
[mesh] update to MDAL 0.0.9 (NetCDF Support)

### PR DESCRIPTION
**Pull request by PeterPetrik**
Ability to open NetCDF files in MDAL, based on GDAL provider. Should be super-safe since it is almost 1-1 with crayfish 2.0 code and the change does not touch other file formats readers.

cc @rduivenvoorde

### CODE REVIEW

**Comment by saberraz** [comment]
Nice addition @PeterPetrik. This will allow users to read grids from NOAA/NASA directly in QGIS:
https://mirador.gsfc.nasa.gov/

**Comment by rduivenvoorde** [comment]
@saberraz would it be an idea to do a direct link to some (nice) example dataset?
@PeterPetrik 
I do have some nc files, which load fine, but I'm not sure how exactly it should behave.
For example (some test, but it COULD be related to my dataset??), I get this netcdf : ECMWF_ERA-40_subset.nc which is an official netcdf example file from https://www.unidata.ucar.edu/software/netcdf/examples/files.html
- I can load/see a grid fine. But moving the time slider, I do not see changes, not even if I'm clicking Apply button (in old crayfish plugin there is a live view)
- viewing a grid ok, but clicking the 'Native Mesh Rendering' (which I think should hide the mesh grid?) removes everything after clicking apply (OR does it mean: via gdal)? Something is going wrong there: if you do 
- Question: in the 'Groups' list, what is the difference between clicking on the name and clicking on the little icon on the right? It seems unrelated: if you click on the icon it get colored, but you also (using the arrow-buttons) can move the selection line (title gets a blue background then), but that does not change the metadata?

image

**Comment by rduivenvoorde** [comment]
Would it be an idea to show the MDAL version in the about dialog? Just like we do with Qt, GDAL and GEOS version? (or should I create a separate feature request for this :-) )

image

**Comment by PeterPetrik** [comment]
@rduivenvoorde 
I have also added recognition of the wind speed as vector. 
The dataset you mentioned is working nicely on my computer. Maybe it is just a matter of waiting, since the rendering speed may not be the best if you are not zoomed to some smaller area.

For your question about the contours icon vs the selection. You need to click on one of the contrours/vector icons similarly to crayfish2.x to select which contours and vector dataset you want to render. Then follow in contours/vector tab to modify the rendering settings. 

For MDAL in about dialog, feel free to add new PR for that :) If I remember correctly, it was not so simple to find out "compiled against version", but it would be easy to add "running agains version" for beginning. 

screen shot 2018-10-04 at 16 09 46

**Comment by rduivenvoorde** [comment]
@PeterPetrik thanks, vector wind is working nicely now :-)

One thing which happens both when you load the netcdf with the gdal-raster provider AND with current mdal provider is that when you have a dataset which has it's longitude variable data running from 0-360 (instead of from -180 to 180) that (In QGIS) you'll end up with a map which is actually ok, but when combined with a normal shapefile wraps around the world (and half of the world of both datasets do not touch...).
You can see in below image, where I loaded that same dataset as mentioned above both in the free netcdf viewer 'Panoply' (https://www.giss.nasa.gov/tools/panoply/) and in QGIS (combined with a world shape).
In planoply you can see that the longitude array goes from 0-360...
I know from @rouault that he has the same problem in GDAL, and I do not know if there is a proper solution for this (or if Even has fixed this already):

image

(will look into the mdal version number in the about box... I think it is a good idea to at least show the running version... Any hint on how to get this from the .so from within the code?)

**Comment by saberraz** [comment]
@rduivenvoorde this is a very annoying and I have come across it several times. I usually transform it using CDO from terminal:

`cdo sellonlatbox,-180,180,-90,90 INPUT.nc OUTPUT_shifted.nc`

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
