### PR TITLE
[FEATURE] Search widget for relations using aggregates

### PR DESCRIPTION
**Pull request by m-kuhn**
For each child relations, the subform is visible.

Each attribute of the children has a tool button option to define to which
aggregate the specified value should be compared. This allows for searching
things like

 * Each city where the highest building is more than 300 m
 * Each sensor where the median value is lower than 50 ppm
 * Each feature with a child with a missing value
 * ...

Find all *wastewater structures* with where the mean level (m.a.s.l.) of all associated covers is lower than 395 meters

screenshot from 2017-11-02 16-52-13

Note: performance is an issue on big datasets since it's using expression relation functionality.

### CODE REVIEW

**Comment by andreasneumann** [comment]
Very cool! Can't wait for this ;-)

It's a long standing request from some of our users to enhance filtering and selecting with relation and aggregate support.

**Comment by haubourg** [comment]
This is AWESOME.

**Comment by nyalldawson** [comment]
Got a screencast?

**Comment by m-kuhn** [comment]
> Got a screencast?

Coming soon

**Comment by m-kuhn** [comment]
Apparently first screenshots have been leaked by trustworthy sources

**Comment by nyalldawson** [comment]
@m-kuhn I noticed that this breaks QgsAttributeFormEditorWidget API. Are you targeting this to 3.2? If so, will you port just the api break to 3.0?

**Comment by andreasneumann** [comment]
If it could land in 3.0, it would be great.

**Comment by m-kuhn** [comment]
Correct, this will slightly break the API.
Separating the API breaks from the rest is possible but not trivial (especially due to the changes on the form itself). I would also feel comfortable with merging this altogether after fixing two minor issues I still found (1. wrong mapping of aggregate functions, meaning string functions are available for number fields and vice versa; 2. the "exclude field" button is also visible for relations).

**Comment by m-kuhn** [comment]
Proposed improvements are implemented, so this is ready to merge.

I just did some tests on a local postgres database with 30000 features and it took about 5 minutes to filter, so I wonder if a warning would be appropriate on big datasets (e.g. >1000 features).

To overcome this, the aggregates will need to be compiled, which will be a task on its own.

Apart from this, I think this is ready to be merged.

**Comment by nyalldawson** [comment]
FYI There is support for compiling aggregates - it's just not implemented in any providers yet. See https://qgis.org/api/classQgsVectorDataProvider.html#a62af062a018df89926e9847bbc6975fc

**Comment by m-kuhn** [comment]
I'm not sure that would help a lot here, what we would need is the possibility to send JOINs to the server.

**Pull request merged**
