### PR TITLE
Add snapping support to scale feature tool

### PR DESCRIPTION
**Pull request by uclaros**
## Description
Followup of #42383 , the scale features map tool now supports snapping too!

After testing it, I now want a combined scale + rotate = Align tool!

### CODE REVIEW

**Comment by Saijin-Naib** [comment]
> After testing it, I now want a combined scale + rotate = Align tool!

Your recent work has been stellar, this is no exception!

**Comment by roya0045** [comment]
@uclaros  Thanks pal! Always good to have you contributing and consolidating things. Though I think that a combined too would be too finnicky, though don't forget that I have #41386  pending, so that is be a good way to transform geometries in more than one dimension with the help of Nyall's work.

**Comment by uclaros** [comment]
Hey, thank you both!
Maybe a shift modifier to align instead of scale could make sense? Your vector georeferencer is a different beast, this is just for quick and easy alignment of a feature ... or two ... or a few anyways!

**Comment by roya0045** [comment]
For the georef I was thinking of adding a way to add/import a selection of feature from an active layer as a potential followup at some point.

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
