### PR TITLE
[WFS provider] [FEATURE] Allow user to enable/disable paging and specify page size (fixes #18935)

### PR DESCRIPTION
**Pull request by rouault**
The 'maximum number of features' settings is now always the maximum number of
features requested, even in WFS 2.0 with paging.
For WFS 2.0, we add a checkbox to enable/disable paging and a text entry to
specify the page size (if let to empty, server default is used)
We also add a Detect button so that the WFS version is autodetected.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Is this for 3.4?

**Comment by nyalldawson** [comment]
By that, I mean... do you consider this a feature or a bug fix? I'd say it could go either way, so if you're comfortable with classifying it as a bug fix I'd be happy to see it land in 3.2.

**Comment by rouault** [comment]
Depends on the point of view and how strict we are regarding feature freeze. This doesn't fix any crash or some big usability issue. This resolves some ambiguity regarding to what "maximum number of features" meant. This also adds new translatable strings.

**Comment by nyalldawson** [comment]
Ok. I'm a +0 here (pending review). @elpaso what do you think?

**Comment by palmerj** [comment]
Any chance for a review @elpaso?

**Pull request merged**
