### PR TITLE
Vectorized remaining propertyicons

### PR DESCRIPTION
**Pull request by FelisPimeja**
**List of icons:**

- gdal.png
- network_and_proxy.png
- locale.png
- join.png
- transparency.png
- pyramids.png
- overlay.png
- map_tools.png
- histogram.png
- digitizing.png
- attributes.png

image

**+ optimized:**

- diagram.svg
- gdal.svg

### CODE REVIEW

**Comment by FelisPimeja** [comment]
By the way, it seems that **locale** icon isn't used any more. I've found a link only in
_images/images.qrc_
If so, can we remove it?

**Comment by nyalldawson** [comment]
Looking great!! One thing I'm not sure about is the join icon. I've never been certain if the original is an arrow pointing to the dot, OR a triangle fanning out from the dot (e.g. the dot is "joining" to many other features). 

@nirvn any ideas?

**Comment by FelisPimeja** [comment]
@nyalldawson, I think in our case it's certanly an arrow pointing to the dot. But your second guess is also interesting.

**Comment by nyalldawson** [comment]
@nirvn - can you take a look at this please?

**Comment by nirvn** [comment]
@FelisPimeja , nice work. The vectorized pyramid icon is a real improvement from its bitmap ancestor.

Few comments:
- I'd avoid 2-pixel border outlines (for e.g., attribute table, join arrow). It makes it look like we're expanding a smaller 24 x 24 px icon or something
- could you make sure that the icons with a map element (rolled up on its left side) has a bit of shadow. If you look at the main window's toolbar, or the layout designer, you'll see what I mean
- regarding the 3 connected computer icon, I'm wondering whether it would better suit our overall theme without the reflection color in the monitors

**Comment by m-kuhn** [comment]
Just discovered this pull request, looks really great @FelisPimeja  :+1: 
Do you think we can merge this before 3.2?

**Comment by nirvn** [comment]
I'd really like to see this merged before 3.2 too. @FelisPimeja , what's the status on recommended changes?

**Comment by nirvn** [comment]
Superseded by #6956

**Pull request closed without merging**
