### PR TITLE
[FEATURE] Allow paint effects for label buffers & backgrounds

### PR DESCRIPTION
**Pull request by nyalldawson**
Allow paint effects for label buffers & backgrounds.

... no I have not gone symbology crazy! This allows a very important cartographic tool - the ability to apply blurs to label buffers to reduce the halo effect (and similarly for background rectangles used to increase label readability)

Here's what's possible using this - a very subtle blurred halo, using the darken blend mode to provide readable labels with no obvious halo effects:

image

Reusing paint effects seems like the cleanest approach here - it avoids clogging up the label buffer/background settings with a bunch of extra widgets, avoids duplicate code (the actual changes to the rendering code are very minimal - most of the changes relate to storing/restoring the effects), and if someone *really* wants to apply a hypercolor color ramp based outer glow to their label background shapes.... now it's possible.

### CODE REVIEW

**Comment by nirvn** [comment]
Who wouldn't want to be able to produce this type of labelling:
wouou

Wouhou! ;)

Joking apart, this is really nice.

**Comment by m-kuhn** [comment]
Thanks for the framework @nyalldawson
And thanks for showing the **real** power of @nirvn

**Comment by nyalldawson** [comment]
@nivrn what's happening with the "Cao Su Ea h'leo BM" label above? is that a bunch of separate labels? Any idea why the "o"s are rendering oddly?

**Comment by nirvn** [comment]
@nyalldawson , it's only one label. Some time ago I noticed large buffers were failing with a couple of characters (for eg the dot for the letter "i" fails to enlarge and instead expands. Must be a similar issue affecting the "o" (aggravated by the presence of a space after it, which prevents neighboring letter from overlapping it's buffer).

It's probably a Qt issue.

**Pull request merged**
