### PR TITLE
Updates saving passwords warning messages

### PR DESCRIPTION
**Pull request by SrNetoChan**
to suggest using a authentication method

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@elpaso Not sure how can review, and eventually merge this.

**Comment by NathanW2** [comment]
I think unsecured is a better word here.

**Comment by SrNetoChan** [comment]
@NathanW2 Thanks, I was actually looking for a better word.

**Comment by SrNetoChan** [comment]
@NathanW2 Better?

**Pull request merged**
