### PR TITLE
Fix issues with custom CRS dialog

### PR DESCRIPTION
**Pull request by nyalldawson**
Also clean up and modernize the code in this dialog a lot.

I'd love to use the new sqlite3 unique_ptrs introduced here elsewhere, as we have a lot of messy code sitting around trying to cleanly handle sqlite3 errors and cleanups. So I'd love a review on that part before it gets moved out of the dialog cpp file to core and re-used elsewhere.

### CODE REVIEW

**Comment by jef-n** [comment]
QSQLITE?

**Comment by nyalldawson** [comment]
@jef-n

Damn... I was rather proud of my little wrappers! But you're right, the end result is almost identical to qsqlite. (I suspect the unique_ptr approach is lighter weight, but compared to the actual cost of the database access it's not gonna have impact).

Is there any reason you know why we have such widespread use of the raw sqlite3 API instead of using qsqlite?

**Comment by jef-n** [comment]
The "my first c++ program" tutorial doesn't mention QSQLITE  ;)

**Comment by nyalldawson** [comment]
Been thinking about this... What's everyone's thoughts here? Is the better approach to stick with the (mostly) raw sqlite3 API or use the qt interface instead?

In general my current preference goes something like:
- use std implementations
- use qt classes only when they save us work or there's no alternative

I'm just slightly dubious of qt upstream's current ability to maintain the qt core and gui libraries, and would prefer to lessen our dependence on them (where it makes sense.. i.e. isn't causing us more work!)

@m-kuhn @wonder-sk @Nathanw2 @elpaso @m-hugo @everyone else too......?

**Comment by m-kuhn** [comment]
I feel the same, unless there's some real added value in Qt classes (didn't look at qsqlite), the std-approach seems to be more sustainable.

**Comment by NathanW2** [comment]
Generally I prefer Qt class for this stuff.  I think it generally provides quite a nice wrapper over all the logic you need and the API is pretty good. I'm happy to follow what ever everyone else wants though.

On this note though, I do feel like we need to have out own "database" wrapper that can be used for everything database related in QGIS, sqlite, sql server, postgres.  Under the hood it can use different methods but I think we need a higher level wrapper so devs don't have to think about different APIs all the time and it also gives us a single entry point for logging and debugging etc.

**Comment by nyalldawson** [comment]
I'm going to merge this without porting to QSqlDatabase for now - I tried porting quickly and hit a segfault, so I figure it's less risk to keep things closer to the current code and we can address in a future commit if desired.

**Comment by m-kuhn** [comment]
Snip from the trace in [[Travis] Crash in PyQgsServerWMS
](https://issues.qgis.org/issues/17447)

```
/usr/lib/x86_64-linux-gnu/libspatialite.so.7(gaiaOutBufferReset+0x11)[0x7f3e8b6f5bc1]
/usr/lib/x86_64-linux-gnu/libspatialite.so.7(+0x33d8d2)[0x7f3e8b9d68d2]
/usr/lib/x86_64-linux-gnu/libspatialite.so.7(spatialite_cleanup_ex+0x22)[0x7f3e8b767412]
/root/QGIS/build/output/lib/libqgis_core.so.2.99.0(_ZN12QgsSLConnect13sqlite3_closeEP7sqlite3+0x4d)[0x7f3e91bd704d]
/root/QGIS/build/output/lib/qgis/plugins/libspatialiteprovider.so(+0x57cac)[0x7f3e65f09cac]
/root/QGIS/build/output/lib/qgis/plugins/libspatialiteprovider.so(+0x57b18)[0x7f3e65f09b18]
```

Assumption: we've got an issue with memory management in the spatialite provider.
Proposal: use this implementation also there.

Opinions?

**Comment by nyalldawson** [comment]
> Assumption: we've got an issue with memory management in the spatialite provider.
Proposal: use this implementation also there.

+1 from me

Alternative proposal: drop spatialite provider and use GDAL instead ;)

**Comment by m-kuhn** [comment]
> Alternative proposal: drop spatialite provider and use GDAL instead ;)

Are we on a par concerning functionality?

Considering https://github.com/qgis/QGIS/pull/5510, I'd like to introduce join / aggregate support in the expression compiler some day. Do we have the possibility and context to run multi-table queries using GDAL?

**Pull request merged**
