### PR TITLE
MSSQL provider fixes

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes for 2.18 for a number of MSSQL provider issues. The big one here is the revert of  57dc3c7, which is causing extreme performance regressions on the provider (see https://issues.qgis.org/issues/15752)

@NathanW2 is this ok with you? I'd say reverting that commit is safe to do because no other providers transparently handle feature validation - they all leave this up to users to fix.

### CODE REVIEW

**Comment by NathanW2** [comment]
Umm leave the is valid check that should be fast but the make valid would
be the slow.  If the layer has invalid geometries we need to still need to
be able to get stats on it

**Comment by palmerj** [comment]
In regards to the is_valid check we need to consider this: https://issues.qgis.org/issues/14590. IMHO nothing showing up is more important that small performance loss.

**Comment by nyalldawson** [comment]
> Umm leave the is valid check that should be fast but the make valid would be the slow.  If the layer has invalid geometries we need to still need to be able to get stats on it

Unfortunately that's not the case - the is valid check is causing the regression here. 

> In regards to the is_valid check we need to consider this: https://issues.qgis.org/issues/14590. IMHO nothing showing up is more important that small performance loss.

It's not a small performance loss - it's effectively made the mssql provider unusable for many users. So we've traded handling invalid geometries (something users *should* fix) for always forcing a slow provider, even for users with well managed databases. I agree it's a tricky balance, but I think we've gone the wrong way here.

**Comment by NathanW2** [comment]
Are you 100% sure it's the IsValid?  It's only a bit check on the geometry
and from my testing should be fast.

We have other options here. Not showing anything is annoying because fixing
invalid geometries in the database is a crap process so we can't really
show nothing to a user because of 1 bad geometry.

The Filter method might work here as per the ticket.

**Comment by nyalldawson** [comment]
> Are you 100% sure it's the IsValid?  It's only a bit check on the geometry
and from my testing should be fast.

yes - my test was done just by iterating over all features:

    for f in vl.getFeatures(QgsFeatureRequest(QgsRectangle(-80581,-100968, 85418,59157))):
            pass

and it's definitely caused by 57dc3c7 - the makevalid part of that commit isn't hit during a getFeatures call

**Comment by nyalldawson** [comment]
@palmerj @NathanW2 does 79d297b avoid your concerns with reverting the validity check?

**Comment by NathanW2** [comment]
Provided it's fast and still shows valid geometries it's fine with me.

**Comment by gioman** [comment]
> and it's definitely caused by 57dc3c7 - the makevalid part of that commit isn't hit during a getFeatures call

@nyalldawson  @NathanW2 hi, just out of curiosity, there are other providers (postgis?) in qgis that implement "is_valid/makevalid" checks/mechanisms?

**Comment by nyalldawson** [comment]
> Provided it's fast and still shows valid geometries it's fine with me.

Do you mean invalid geometries?

**Comment by nyalldawson** [comment]
> hi, just out of curiosity, there are other providers (postgis?) in qgis that implement "is_valid/makevalid" checks/mechanisms?

No - this is left to users to fix their data ;)

**Comment by palmerj** [comment]
> > Provided it's fast and still shows valid geometries it's fine with me.
> Do you mean invalid geometries?

This is ok by me. I would also want it to show the invalid geometries as well

**Comment by nyalldawson** [comment]
> This is ok by me. I would also want it to show the invalid geometries as well

Can you give a dump of a table which demonstrates this?

**Comment by gioman** [comment]
> No - this is left to users to fix their data ;)

well... I was on your camp for a long... not anymore. I really think that especially were possible (i.e. postgis > is_valid + makevalid) an *option* to allow users "fix" on the fly their geometries is necessary (because QGIS still frequently does not shows at all invalid geometries... I don't want to speak about geoprocessing them in this context). Now this case tell us that -of course- users must be warned clearly this has potentially a big performance. 

Another plus could be an option to allow run a "makevalid" immediately after a newly saved digitized feature.

**Comment by gioman** [comment]
> Can you give a dump of a table which demonstrates this?

cannot speak for mssql server data, but examples for other datasources can be found in the the bug tracker. I can dig into it of necessary.

**Comment by NathanW2** [comment]
Issue with running makevalid is that it can change the geometry on people,
or even make wrong geometry types e.g geometry collections.  So that is
something to consider if ever using it.

**Comment by palmerj** [comment]
Issue 14590 has a dump with invalid data

**Comment by nyalldawson** [comment]
@gioman

> option to allow users "fix" on the fly their geometries is necessary

I just can't see how we could implement this in a way that fixes the problem. If we made this an option I'd be very strongly arguing against it being on by default, because the performance hit is just too costly and most users will never know that this option exists and to switch it off. But on the other hand, a non default option to fix geometry on the fly will also never be discovered by the users whose data is mangled and who need this option!

If the validity checking/repairing was inexpensive then yes, I'd be in favour of this option (on by default). But as evidenced by https://issues.qgis.org/issues/15752 the checks are just too expensive to always run.

I can't see a third option. Any ideas?

**Comment by palmerj** [comment]
I also don't see a nice third option, due to expected usability and performance. 

As mentioned in https://issues.qgis.org/issues/14590 I vote for using Filter instead or STIntersect for the spatial filtering function as Filter can operate on invalid geometries and is faster. 

Doesn't look like https://issues.qgis.org/issues/15752 has done any performance testing with that option. Maybe a benchmark can confirm what the docs say: https://docs.microsoft.com/en-us/sql/t-sql/spatial-geometry/filter-geometry-data-type. One implement issue might be any issue is if the table does not have a spatial index. See docs:

> In cases where an index is not available, or is not used, the method will return the same values as STIntersects() when called with the same parameters.

But I guess that could be worked around with a catalogue query to check if the table has a spatial index. If it doesn't then revert to `geom.STIsValid() = 1 AND geom.STIntersects`?

**Comment by gioman** [comment]
> I can't see a third option. Any ideas?

@nyalldawson @palmerj thanks for the answers. I was kind thinking out loud here, thinking about two knf of problems I believe we still have in QGIS: 1) when in come to invalid geometries and canvas rendering QGIS frequently shows behaviors like not showing the whole laye or worst not showing the just invalid geometry... This is bugging me as power user (that I know I can look at the log) as much as the vast majority of normal users, that will never look at the log, nor what do afterwards.

2) the second is not much as a problem as a wish... unfortunately something that I have seen on proprietary gis is the ability of having geometry errors fixed while editing (as option of course). Usually we speak of simple things like fixing the auto-intersections and removing the duplicate nodes, but if I'm not wrong on other packages is possible to set a few of this type of constraints. Of course the power user could do this with Postgis, by setting the constraints in the DB, but again this is out of reach of the most (QGIS warns you about this stuff while you edit before you save, and this mitigates the problem of course).

**Comment by wonder-sk** [comment]
I am with Nyall that providers should not do validity check automatically (and try to repair geometries). The performance hit (especially with more complex polygons) is just too high in order to deal with corner cases such as invalid geometries. I would suggest having an action somewhere in GUI for layer diagnostics (something like Scandisk :wink:) that people would run explicitly if they want to be 100% sure everything is correct. The diagnostics could have various levels - e.g. geometry validity checks, detection of incorrect CRS and so on.

As for making geometries valid - even that can fail and leave users with invalid geometries (or as Nathan said with different geometry type) so it is not something that should be run automatically.

**Comment by gioman** [comment]
I think you are focusing on the word "automatically" and missing my point: I didn't asked to automatically do anything. I just exposed a problem: invalid geometries are often "missed" by qgis while rendering. Also an *easy* way for common users to fix their geometries is kind missing (or better, an easy work-flow is missing like for example: "warning! your layer contains invalid geometries, do you want fix them, if yes click here").

**Comment by NathanW2** [comment]
Also remember the people viewing the layer might not have the time/know
how/power to fix the data. So we should always show what we can, maybe warn
on stuff we can't and hopefully provide a way to fix it, but never error
out the full layer like before.

The Filter method should help us in this case so this is ok.

**Comment by nyalldawson** [comment]
Right, so here's a refined PR. I've had to bring back the IsValid call in the iterator, since SQL
server will transparently fall back to STIntersects if it decides there's no suitable spatial indexes available, and then throw an exception on invalid geometries. So we still require the STISValid check even when using Filter.

I think this is as good as we'll get... but let's merge, and then hopefully get verification that https://issues.qgis.org/issues/15752 is fixed...

**Comment by palmerj** [comment]
@nyalldawson so you think it would be possible to only include the isvalid check if a spatial index is not present for the table. Would have though this should he easy enough. This should then provide a further performance again for most cases.

**Comment by nyalldawson** [comment]
> so you think it would be possible to only include the isvalid check if a spatial index is not present for the table. Would have though this should he easy enough. This should then provide a further performance again for most cases.

I'm not sure - there's also the possibility that for some internal reason sql server decides NOT to use the spatial index for a query. I'm not familiar enough with sql server to know if this can happen, but I do know that the postgres query planner will sometimes do this if it decides that the scan is going to be faster then the index lookup.

I say we merge this, test it further, and then add more refinements only if required.

**Comment by palmerj** [comment]
> I say we merge this, test it further, and then add more refinements only if required.

Ok great.

**Comment by nyalldawson** [comment]
@nathanw2 you happy with this approach?

**Comment by NathanW2** [comment]
Yes that's cool

**Pull request merged**
