### PR TITLE
fix locator crash with all layers filter

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]
Wouldn't it be better to use a struct?

**Comment by 3nids** [comment]
> Wouldn't it be better to use a struct?

yep done in https://github.com/qgis/QGIS/pull/44977 for master

**Comment by agiudiceandrea** [comment]
Does this fix https://github.com/qgis/QGIS/issues/44960?

**Comment by 3nids** [comment]
yes, thanks!

**Pull request merged**
