### PR TITLE
Vectorized console icons

### PR DESCRIPTION
**Pull request by FelisPimeja**
image

**List of icons:**

- iconUncommentEditorConsole.png
- iconClassBrowserConsole.png
- iconClassConsole.png
- iconClassTreeWidgetConsole.png
- iconClearConsole.png
- iconCodepadConsole.png
- iconCommentEditorConsole.png
- iconFileTabsMenuConsole.png
- iconFunctionTreeWidgetConsole.png
- iconHelpConsole.png
- iconHideToolConsole.png
- iconMethodTreeWidgetConsole.png
- iconNewTabEditorConsole.png
- iconOpenConsole.png
- iconProcessingConsole.png
- iconQtCoreConsole.png
- iconQtGuiConsole.png
- iconResetColorConsole.png
- iconRestoreTabsConsole.png
- iconRunScriptConsole.png
- iconSaveAsConsole.png
- iconSaveConsole.png
- iconSearchEditorConsole.png
- iconSearchNextEditorConsole.png
- iconSearchPrevEditorConsole.png
- iconSettingsConsole.png
- iconShowEditorConsole.png
- iconSyntaxErrorConsole.png
- iconTabEditorConsole.png

### CODE REVIEW

**Comment by FelisPimeja** [comment]
By the way, I haven't found any links to _iconProcessingConsole_ and _iconClassConsole_ icons. Are they still used?

**Comment by slarosa** [comment]
@FelisPimeja thank you very much for all these graphic improvements.
> By the way, I haven't found any links to iconProcessingConsole and iconClassConsole icons. Are they still used?

they are no longer used in version 3, the same for ```iconQtGuiConsole``` and ```iconQtCoreConsole```

just a note: what you think if we use a spanner icon for options?
Also, I am not sure about the clear icon although I like it, maybe we could let it like it is now, with a vectorized broom or brush icon??

**Comment by nyalldawson** [comment]
Lovely work as usual!

Some comments:
- iconClassBrowserConsole.svg: I think the english "obj" text should be dropped here. The icon standsalone and the tooltip can provide the extra (translated) details
- iconCommentEditorConsole.svg/iconUncommentEditorConsole.svg: we don't usually use totally black colors in the icons as they have too high contrast and don't fit well with the rest of the icon theme. Can you lighten this to a "near-black"? (You could grab the exact color from a similar existing icon)
- iconHelpConsole.svg: could we just reuse the existing help icon here? I don't think console needs it's own one
- iconRunScriptConsole.svg: this icon looks very busy too me. Maybe just a simple "play" icon would work?
- iconSearchEditorConsole.svg/iconSettingsConsole.svg: again, I think we've got a standard icons we could reuse here?

As a hi-dpi user I'm really happy to see these icons get some love! Thank you!

**Comment by FelisPimeja** [comment]
Ok, so I turned it up a little bit.
@slarosa 
- [x] Spanner icon for options (there's still some mix-up with it, cause it's assosiated with actions, but it's also used for settings as I can see)
- [x] Vectorized broom for clear icon (I wasn't shure aboun my new one, so maybe you are right)
- [ ] Still can not figure out what to do with unused icons - do I need to remove them or save for later?

@nyalldawson 
- [x] iconClassBrowserConsole.svg: I think the english "obj" text should be dropped here. The icon standsalone and the tooltip can provide the extra (translated) details
- [x] iconCommentEditorConsole.svg/iconUncommentEditorConsole.svg: we don't usually use totally black colors in the icons as they have too high contrast and don't fit well with the rest of the icon theme. Can you lighten this to a "near-black"? (You could grab the exact color from a similar existing icon). 
_Still I can see lots of icons using solid black color. Do we need to fix this?_
- [x] iconHelpConsole.svg: could we just reuse the existing help icon here? I don't think console needs it's own one
- [x] iconRunScriptConsole.svg: this icon looks very busy too me. Maybe just a simple "play" icon would work?
- [ ] iconSearchEditorConsole.svg/iconSettingsConsole.svg: again, I think we've got a standard icons we could reuse here? 
_Here's a little problem. We've got only `search.svg` as a defaut search icon. And it was made for 16x16 resolution. So I don't think it's a good idea to use it._

**Comment by nyalldawson** [comment]
>  Still can not figure out what to do with unused icons - do I need to remove them or save for later?

We have to leave them - even if qgis itself doesn't use them, a plugin might rely on them and they are sort-of part of the fixed api.

But maybe a list of "icons to remove in 4.0" would be a handy addition!


> Here's a little problem. We've got only search.svg as a defaut search icon. And it was made for 16x16 resolution. So I don't think it's a good idea to use it.

Fair enough. It *is* ugly when 16/24 px icons are used in the other size.

If I can suggest one more tweak -- to me the green used in the circle+plus and circle-down-arrow icon is too bright, and inconsistent with other QGIS icons. I think this should be replaced with the standard blue we use elsewhere (e.g. the same blue as the play and search back/forward icons).

Love your work -- this is looking great!

(Assigning to @nirvn as theme/ux maintainer for final approval)

**Comment by nirvn** [comment]
Re circle + icon, please use our standard + icon. For the circle arrow-down, I'd go for a dark arrow-down, and no circle shield. I'm inclined not to use our blue arrow there as in most (all?) uses within QGIS indicates an item moving downwards.

This will make many folks happy.

BTW, IMHO, the comment / uncomment sharp icons are too attention-grabbing (i.e. fat lines, all black). Could you reduce the line width a bit, and maybe use a dark gray color instead? Cheers.

**Comment by FelisPimeja** [comment]
> We have to leave them - even if qgis itself doesn't use them, a plugin might rely on them and they are sort-of part of the fixed api.
> 
> But maybe a list of "icons to remove in 4.0" would be a handy addition!

@nyalldawson I see now, thank you for the explanation!
@nirvn , here's the fixed icons if I heard you correctly:
image

But what do you mean by _standard + icon_? Is it `mActionAdd.svg`?

**Comment by nirvn** [comment]
@FelisPimeja , I'd go with `symbologyAdd.svg`.

Comment icons much better. IMHO, the un-comment should use our "remove shield" (i.e., the lower-right shield in e.g. `mActionDeselectAll.svg`.

**Comment by FelisPimeja** [comment]
@nirvn , see now. Fixede that.

**Comment by nyalldawson** [comment]
@nirvn ok to merge?

**Comment by nirvn** [comment]
@FelisPimeja , brilliant, thanks.

**Pull request merged**
