### PR TITLE
Fix PyQGIS 3D module patching

### PR DESCRIPTION
**Pull request by nyalldawson**
The module patching for _3d was not working at all, because the same logic which works for other modules with a private _module copy clashed with the approach of exposing the public 3d module as qgis._3d

Work around this by renaming the private internal module as _3d_p, so that the monkey patching logic from sip is correctly run when the module is loaded.

Fixes broken API in 3d module for renamed enums, and fixes the broken PyQGIS doc for the 3d module

### CODE REVIEW

**Review by troopa81 — APPROVED** [review]

**Comment by jgrocha** [comment]
Hi @nyalldawson 

When I try to install after default QT5 build, I get:

```
CMake Error at python/cmake_install.cmake:94 (file):
  file INSTALL cannot find
  "/home/jgr/dev/cpp/build-qgis/output/python/qgis/_3d_p.pyi": No such file
  or directory.
Call Stack (most recent call first):
  cmake_install.cmake:68 (include)
```

My build doesn't have `output/python/qgis/_3d_p.pyi`. I do have an `output/python/qgis/3d_p.pyi`.

```
jgr@dragon:~/dev/cpp/build-qgis$ ls -l output/python/qgis/
total 267036
drwxrwxr-x 3 jgr  jgr       4096 set 15 22:24 _3d
-rw-rw-r-- 1 jgr  jgr      47904 set 15 21:37 3d_p.pyi
-rwxrwxr-x 1 jgr  jgr   13642192 set 15 22:07 _3d_p.so
```

```
jgr@dragon:~/dev/cpp/build-qgis$ ls -l output/python/qgis/_3d/
total 24
-rw-rw-r-- 1 jgr jgr 18897 set 15 21:33 __init__.py
drwxrwxr-x 2 jgr jgr  4096 set 15 22:24 __pycache__
```

My Cmake options are:

```
cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=ON -DENABLE_PGTEST=ON -DWITH_CUSTOM_WIDGETS=TRUE -DWITH_SERVER=TRUE -DWITH_QSPATIALITE=TRUE -DWITH_3D=TRUE -DGDAL_CONFIG=/usr/local/bin/gdal-config -DPROJ_INCLUDE_DIR=/usr/local/include -DPROJ_LIBRARY=/usr/local/lib/libproj.so -DWITH_PDAL=TRUE -DWITH_EPT=TRUE ../QGIS
```

My SIP version is 4.19.25

The CMakeLists.txt logic in this PR does not work in my case. Am I missing some compile option? May I propose another test before trying to deploy `_3d_p.pyi`?

**Comment by nyalldawson** [comment]
@jgrocha try completely deleting your build folder and doing a complete rebuild

**Comment by jgrocha** [comment]
> @jgrocha try completely deleting your build folder and doing a complete rebuild

I did it again. This happens after a fresh build + install.

**Comment by nyalldawson** [comment]
What if you revert https://github.com/qgis/QGIS/commit/640f2801f2fb765b33aaedd0da2b969f4bb64326 ?

**Comment by jgrocha** [comment]
Work like a charm!

**Comment by nyalldawson** [comment]
Ok, can you comment on https://github.com/qgis/QGIS/pull/58562 then?

**Pull request merged**
