### PR TITLE
Disable PG flacky test case

### PR DESCRIPTION
**Pull request by elpaso**
test fails on Travis without a reason

### CODE REVIEW

**Comment by elpaso** [comment]
CC @nyalldawson

**Comment by m-kuhn** [comment]
Can you provide a link to a failing test for reference?

**Comment by elpaso** [comment]
@m-kuhn like this? https://travis-ci.org/qgis/QGIS/jobs/643991374#L2987

**Comment by m-kuhn** [comment]
Yes, I think this should be mandatory for flaky tests :+1:

**Pull request merged**
