### PR TITLE
[server] Default scale/mupmm on GetLegendGraphics

### PR DESCRIPTION
**Pull request by signedav**
Backport from #9775
With manual GUI fixes...

### CODE REVIEW

**Comment by signedav** [comment]
Cannot take the created images at the moment because CDash Error reports are not created.

**Comment by pblottiere** [comment]
> Cannot take the created images at the moment because CDash Error reports are not created.

It seems that CDash is back and I restarted your build on Travis. So you should be able to retrieve images.

**Comment by signedav** [comment]
Thanks @pblottiere

**Review by pblottiere — APPROVED** [review]

**Comment by pblottiere** [comment]
Good work @signedav :+1:

**Comment by signedav** [comment]
Thanks a lot @pblottiere

**Pull request merged**
