### PR TITLE
[opencl] Raster calculator goes opencl

### PR DESCRIPTION
**Pull request by elpaso**
... and runs much faster!

qgis-opencl-raster-calc

### CODE REVIEW

**Review by songb2 — APPROVED** [review]

**Comment by luipir** [comment]
the reason to duplicate processCalculation code related to initial parsing? Is it because we should move definitively to a more modern code implementation?

**Comment by NathanW2** [comment]
Holy heck yes!

On a different note I would love to see if we could make QgsExpression work on raster cells but not sure how much work that is.

**Comment by elpaso** [comment]
> the reason to duplicate processCalculation code related to initial parsing? Is it because we should move definitively to a more modern code implementation?

@luipir  At what part of my PR are you referring to?

**Comment by luipir** [comment]
> @luipir At what part of my PR are you referring to?

ho, bnothing important... I checked agaoina and the only duplicated part is https://github.com/qgis/QGIS/blob/5ef87371aa62ff2e1abec90d460c38ba1faaf0a7/src/analysis/raster/qgsrastercalculator.cpp#L318 I remeber that following layerRef filling part was from original code, but I was wrong.

**Comment by elpaso** [comment]
@luipir you are right, I could have passed the calcNode to the GPU function, I will do that, thanks.

**Pull request merged**
