### PR TITLE
update to MDAL 0.2.0 

### PR DESCRIPTION
**Pull request by PeterPetrik**
(friendly release for QGIS 3.6)

### CODE REVIEW

**Comment by m-kuhn** [comment]
Obligatory question, what's the status of moving mdal into a standalone package :stuck_out_tongue_winking_eye:

**Comment by PeterPetrik** [comment]
I would like to get the ball slowly rolling after 3.6 release

**Comment by nyalldawson** [comment]
I wouldn't be in a hurry to remove this code from qgis and become reliant on a 3rd party to keep the library up to date. It's nice having the flexibility to immediately take advantage of new mdal API, instead of waiting 2+ years for slow moving distros to upgrade the library.

I'm actually all in favour of moving more library copies to reside within qgis source, specifically geos and libspatialindex. Those two are so heavily utilised by QGIS, yet we have lots of bug reports and crashes which are only fixed by new versions of the libraries.

This also means we could be better open source citizens and fix things in geos itself, instead of hacking in workarounds on the qgis side...

**Comment by m-kuhn** [comment]
I'm a bit more hesitant there, we risk ending up with forked code that is not pushed upstream and incompatible with upstream changes (see astyle, pal).
Luckily on OSGeo4W we control the version, same on macOS. While Linux packagers will still disable the builtin version and stick to external deps (hasn't this happened to ext serial port on Debian).

I'm open to discuss that MDAL becomes an integral part of QGIS, but then this should be made clear and pull requests made per feature / issue and not for complete new versions.

**Comment by wonder-sk** [comment]
by the way, PAL project outside of qgis source code has been dead for nearly 10 years now - so by adopting it in our codebase I think we kind of saved it :-)

**Comment by m-kuhn** [comment]
Yes, PAL is the kind of project we adopted and no longer give it separate version numbers or treat it as an external dependency :)

**Comment by nyalldawson** [comment]
> I'm open to discuss that MDAL becomes an integral part of QGIS, but then this should be made clear and pull requests made per feature / issue and not for complete new versions.

I'm ok with the current approach, given the mdal upstream has extensive unit tests and Martin/Peter consistently review each others PRs.

**Pull request merged**
