### PR TITLE
[needs-docs] qgz set as the default format

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

This PR follows a previous discussion about considering the `.qgz` format like the one proposed as a default.

See: http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Discussing-qgd-files-td5356740.html

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
+1

**Comment by nyalldawson** [comment]
Before we do this, it's probably worth doing a quick grep through the source to see if there's any other hardcoded .qgs strings which need to be upgraded too? (Maybe you've already done this)

**Comment by NathanW2** [comment]
Are we ready for this yet? I think there are still bugs from what I
understand.  We need the format to be solid before changing it.

**Comment by nyalldawson** [comment]
@NathanW2 
I'm only aware of https://issues.qgis.org/issues/18477 and https://issues.qgis.org/issues/17870 -- are there others you've encountered?

**Comment by pblottiere** [comment]
@NathanW2 @nyalldawson 

> I'm only aware of https://issues.qgis.org/issues/18477 and https://issues.qgis.org/issues/17870 

BTW, it's about auxiliary storage (and I didn't succeed in reproducing these issues), not about `.qgz` format directly.

**Comment by nyalldawson** [comment]
What's the status here?

**Comment by nyalldawson** [comment]
Ping @pblottiere

I think we should merge before 3.2, and the sooner the better for more testing and feedback. Do you have any objections?

**Comment by pblottiere** [comment]
Hi @nyalldawson!

> I think we should merge before 3.2, and the sooner the better for more testing and feedback. Do you have any objections?

I don't have any objections, but considering that it's not a micro tiny change, I'd prefer not to merge this PR myself :).

And do not hesitate to ping me if there's underlying issues, I'll take a look asap!

**Comment by nyalldawson** [comment]
Done... let's see what happens! Easy enough to back out if serious issues arise.

**Pull request merged**
