### PR TITLE
Feature request 50829 move layer tree nodes up down

### PR DESCRIPTION
**Pull request by benwirf**
## Description

This PR addresses [feature request 50829](https://github.com/qgis/QGIS/issues/50829), adding two default actions
to the layer tree view menu provider and two action buttons with keyboard shortcuts to the layer tree view toolbar to
move a single selected layer tree node up or down.
When moving a node up, if the sibling node above is a group, the node is placed at the bottom of that group,
otherwise, the node is moved up one position within it's parent.
When moving a node down, if the sibling node below is a group, the node is placed at the top of that group,
otherwise, the node is moved down one position within it's parent.
Both actions are disabled if multiple nodes are selected;
The move up action is disabled if the selected node is the top item in the layer tree
and the move down action is disabled if the selected node is the bottom item in the layer tree.
When using the buttons or keyboard shortcuts, the selection index is updated to the new node     
position.

See the short screencast 

https://user-images.githubusercontent.com/47767794/213913241-746b7393-e5d6-4527-bbbb-6699159398c0.mp4

### CODE REVIEW

**Comment by troopa81** [comment]
Just few UI remarks
- Looks like you select boundary_KNP last but this AERONET which is moving (do we want to move the selected items or the current one?
- Do you plan to make it work with several items (I would say no according to the code) ? with group ?
- I find it a little bit odd when you move up/down, and the layer doesn't actually move up/down but it's just changing group. I would say that if you call move up/down action, the current layer HAS to change its position in the layer order after the action call, no wonder group are involved or not. But maybe that's just me.

**Comment by 3nids** [comment]
I am a bit concerned by adding 2 more buttons to an already packed toolbar for something which is not related to actually working.

We are indeed mixing 2 types of actions in the toolbar: building/modifying the layer tree and actually working with it.

One option would be to have an edit button for the legend which would show the editing actions (add group, remove item, move up, move down).

ping @nirvn

**Comment by troopa81** [comment]
> We are indeed mixing 2 types of actions in the toolbar: building/modifying the layer tree and actually working with it.

What are the  *working with it* actions ? All actions modify the content/behavior of the layer tree except the one that open the symbology panel

**Comment by 3nids** [comment]
symbology, map themes, filtering are the actions I am referring to as "working with the legend".

Using a keyboard shortcut might be a better approach? CTRL + arrows up/down or something like this?

**Comment by benwirf** [comment]
Thanks for the feedback so far.

@troopa81, in this situation, I think it makes more sense to move the _selected_ node. Because, if you have multiple selections, you can deselect them by ctrl+click. Say you have 2 nodes selected. You hold ctrl and click on one to deselect it. Now the one you want to move is selected, but the last item clicked is the current one. For that reason, I think that moving the selected node is the correct behaviour (maybe I'm wrong though).
Regarding your second point, it does work with groups! It works on any selected layer tree node. But yes, only a single item at the moment. I think it would get complicated and confusing (both the implementation and usage) for many separate nodes of different parents. I had a separate discussion via email with @nyalldawson, who suggested restricting to multiple items when they are in consecutive positions in the layer tree, and that this addition could be added later (I would be happy to work on that as well).
Regarding your third point, I'm not sure I understand. The behaviour implemented here is that a layer tree item will ascend/ descend sequentially through the whole layer tree structure, moving into, through and out of groups and subgroups on the way. I think that is the idea that was expressed in the feature request. Maybe I'm missing something though.

@3nids, I take your point about adding more buttons to the toolbar. But, just to clarify, this PR _does_ include keyboard shortcuts (the second part of the screencast where the layer node moves down is done all with the keyboard). I used **Alt+Up** and **Alt+Down**, because Ctrl+Up/Down is already in use for changing the _current_ node and Shift+Up/Down is already in use for selecting multiple consecutive nodes. So maybe just not adding the action buttons to the toolbar would be an improvement. Additionally, in this PR I added corresponding actions to the right-click context menu. The only difference is that when using the actions in the context menu, the selected index is not updated (mimicking the drag and drop behaviour). When using the toolbar buttons or the Alt+Up/Down shortcuts, the selection is updated. So, with the Alt key modifier added here, plus the existing key shortcuts, it allows to move nodes freely but sequentially throughout the entire layer tree without using any mouse clicks. Again, I think that is in line with the accessibility enhancements expressed in the original feature request.

Sorry for the lengthy comment here. I think perhaps I didn't explain the proposed functionality very well in the original PR comment. I will try to add some additional screenshots/ screencasts later. Or maybe I am just on the wrong track, and this isn't really a useful addition.

Again, I appreciate the feedback.

Kind regards,

Ben

**Comment by troopa81** [comment]
Regarding the selected/current node, I have no strong opinion, but it seems to me that most of the time (always?) when action can deal with only one item, its the current one. If it can deal with several item, it's the selected ones.

I'm wondering if it is a really bad thing to be able to select several items, and move them all up. What would be the issue with this behavior? 

> Regarding your third point, I'm not sure I understand. The behaviour implemented here is that a layer tree item will ascend/ descend sequentially through the whole layer tree structure, moving into, through and out of groups and subgroups on the way. 

I'm talking about the behavior you see at 0'11 of your video, you have to click 3 times on move up so AERONET move on top of fire_plot, I would prefer it moves up/down regardless groups

> I think that is the idea that was expressed in the feature request. Maybe I'm missing something though.

I'm not sure, feature request says

> In my opinion the layer(s) should be moved to the next position in a linear order, so they would enter any group and "climb" through them, row by row.

But anyway, you can propose something different from what is described in the feature request

> Sorry for the lengthy comment here. I think perhaps I didn't explain the proposed functionality very well in the original PR comment. 

No problem here, it was clear enough to me :+1:

**Comment by troopa81** [comment]
> symbology, map themes, filtering are the actions I am referring to as "working with the legend".

IMHO it modifies the legend as well, you can create/remove/change the current map theme for instance. It, indeed, doesn't change the very content of the layers or its order, but I'm wondering if it would make a different for the user.

> Using a keyboard shortcut might be a better approach? CTRL + arrows up/down or something like this?

Not sure if all users use shortcut, or are aware they exist without button.

I'm not a UI/UX expert, so I'm not completely sure about what I am proposing :grimacing:

**Comment by benwirf** [comment]
> I'm talking about the behavior you see at 0'11 of your video, you have to click 3 times on move up so AERONET move on top of fire_plot, I would prefer it moves up/down regardless groups

I see what you are saying, but IMHO when AERONET is immediately above boundary_KNP, there are 2 available positions in the layer tree where user may want to place a node _before_ it gets to fire_plots. One is at the bottom of the kakadu group, the next is at the bottom of the kakadu_points subgroup. And, in my experience and testing, this is precisely where drag and dropping nodes becomes a bit fiddly, so in that sense I can't see the logic in skipping over those 2 positions and moving above the fire_plots layer.

> But anyway, you can propose something different from what is described in the feature request

Yes, sure- I spent quite a bit of time thinking about this and testing while working on it. This is just what made the most sense to me. But maybe it still needs some more consideration :confused:

Cheers

**Pull request closed without merging**
