### PR TITLE
Fix remaining cppcheck warnings, add scripts/cppcheck.sh and corresponding GH workflow jobs

### PR DESCRIPTION
**Pull request by rouault**
* Fix remaining cppcheck issues in the "warning" category, as spotted by cppcheck of Ubuntu 16.04 and 18.04. There are a lot in other categories that should deserve fixing...
* Add scripts/cppcheck.sh that fails if issues in the "warning"  category are raised, and reports other categories in non failing way
* Add 2 GH workflow with cppcheck of Ubuntu 16.04 and 18.04

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Question: what's the benefit in running the older cpp check from 16.04?

**Comment by rouault** [comment]
> what's the benefit in running the older cpp check from 16.04?

I found cppcheck versions are not always monotonically increasing in quality. Some older versions detect issues that some later won't, and vice verca. Some might have quite annoying bugs too, but for the 'warning' category 16.04 and 18.04 are reasonable enough

**Comment by nyalldawson** [comment]
> I found cppcheck versions are not always monotonically increasing in quality. Some older versions detect issues that some later won't, and vice verca. Some might have quite annoying bugs too, but for the 'warning' category 16.04 and 18.04 are reasonable enough

Ok, thanks for the clarification!

This looks great, by the way!

**Comment by m-kuhn** [comment]
I've implemented these checks on QField too (thanks for the workflow files, @rouault )

FYI:
My impression was, that 18.04 (cppcheck 1.80) reports everything that 16.04 (cppcheck 1.70) reports as well - and more.
On the other hand 20.04 (cppcheck 1.90) seemed to perform worse. There we'll stick to 1.80 (18.04) only for now.

**Pull request merged**
