### PR TITLE
Handle expression variables visibility

### PR DESCRIPTION
**Pull request by Samweli**
Follow up changes from https://github.com/qgis/QGIS/pull/49869

Adds functions inside the QgsExpressionContextScope that handles showing and hiding of the expression variables.
This provides a robust way for handling expression variables visibility.

### CODE REVIEW

**Comment by m-kuhn** [comment]
What exactly are hidden/visible variables? I think it would also be worth mentioning in the api docs.

**Comment by Samweli** [comment]
> What exactly are hidden/visible variables? I think it would also be worth mentioning in the api docs.

@m-kuhn the hidden variables approach is what I'm suggesting to use for cases where a new QGIS version needs to remove an expression variable introduced in past QGIS versions without risking breaking past QGIS projects. 

When such case rise, we will be able to remove the variable from user access and view by calling `QgsExpressionContextScope:addHiddenVariable( variable)`.

**Comment by m-kuhn** [comment]
Reading https://github.com/qgis/QGIS/pull/49869 I assume it hides them from the expression builder dialog and widget. Is that correct? Can you write that to the docstrings?

**Comment by Samweli** [comment]
> Reading #49869 I assume it hides them from the expression builder dialog and widget. Is that correct?

yes that correct.

> Can you write that to the docstrings?

sure.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
