### PR TITLE
[Oracle] Implement Oracle connection API

### PR DESCRIPTION
**Pull request by troopa81**
This PR implements *QgsAbstractDatabaseProviderConnection* for the Oracle provider.

#41117 and #41121 need to be merged before this one. 

Few details ...

### Schemas

I disabled Schema capabilities because of the following issues: 

- When you logged as user `A` and create a schema, you actually create new user `B`. 
    If you create then a table with geometry, you'll have to insert this table in the view *user_sdo_geom_metadata*. That's the recommended way and the only one accepted (see [documentation](https://docs.oracle.com/database/121/SPATL/geometry-metadata-views.htm#SPATL545)). But when you do that, the view use the current logged user `A` as the one associated with the new table instead of `B`. 
    
    I failed to see any way to bypass that and it's impossible to insert in *all_sdo_geom_metadata*. If somebody has a hint, please let me know. 

    Failing to insert in the metadata table make the whole thing works poorly and cause later issues (you cannot create index, you loose the srid info...)

- There is no official/proper way to rename a schema. Some [workwaround](http://dirknachbar.blogspot.com/2016/03/alter-user-rename-half-official-option.html) exists but it's discouraged to use it in production. Looks like the better way it to create a new user, copy everything and delete the old one. The copy could be hard to implement in pure SQL without breaking anything. It seems the best way to achieve that is to use the import/export tools.

For the sake of consistency I disabled all related schema capabilities. I kept the associated commits in the timeline in case somebody would reset these feature.

**EDIT** I set the *Schemas* capabilities because Oracle support them (it's the owner) and you can write

```sql
select * from QGIS.SOME_DATA; 
```

### Table name upper case

I updated the base test because geometry table and field name needs to be uppercase (see #41121)

### Related PRs

Related PRs fix : #40890, #40944, #41079, #41117, #41121

Funded by Metropole de Lille 
cc @Jean-Roc

### CODE REVIEW

**Review by elpaso — APPROVED** [review]
LGTM

**Review by rldhont — APPROVED** [review]
LGTM

**Comment by troopa81** [comment]
I added the *Schemas* capabilities because of this comment 

>  Schemas = 1 << 12,            //!< Can list schemas (if not set, the connection does not support schemas)

But Oracle support schema (=owner) even if you cannot create/rename them. 

Contrary to spatialite for instance, you can write something like

```sql
select * from QGIS.SOME_DATA; 
```

**Comment by elpaso** [comment]
> I added the _Schemas_ capabilities because of this comment
> 
> > Schemas = 1 << 12,            //!< Can list schemas (if not set, the connection does not support schemas)
> 
> But Oracle support schema (=owner) even if you cannot create/rename them.
> 
> Contrary to spatialite for instance, you can write something like
> 
> ```sql
> select * from QGIS.SOME_DATA; 
> ```

I think it makes sense. If you need additional capabilities to fine-tune the behavior feel free to add them but I think that with

```c++
      CreateSchema = 1 << 6,        //!< Can CREATE a schema
      DropSchema = 1 << 7,          //!< Can DROP a schema
      RenameSchema = 1 << 8,        //!< Can RENAME a schema
```

you should be good already.

**Comment by nyalldawson** [comment]
@elpaso 

Do you think a freeze exemption is appropriate for this? I'd be in favour, given:

- it's isolated code, which doesn't break or affect any other existing functionality
- all the known bugs in dbmanager which were the motivation behind the connections api in the first place, and which this would help resolve for oracle connections...

**Comment by elpaso** [comment]
> @elpaso
> 
> Do you think a freeze exemption is appropriate for this? I'd be in favour, given:
> 
>     * it's isolated code, which doesn't break or affect any other existing functionality
> 
>     * all the known bugs in dbmanager which were the motivation behind the connections api in the first place, and which this would help resolve for oracle connections...

Yes, I see no harm and I think we should merge immediately.

**Comment by nyalldawson** [comment]
@troopa81 can you rebase this one now? All the pre-requisites are merged

**Comment by troopa81** [comment]
> I think it makes sense. If you need additional capabilities to fine-tune the behavior feel free to add them but I think that with

Like I said in the PR description, I prefer not enable Create/Drop/Rename Schema for all the issues that would bring. Oracle isn't really OK with these.

 I rebased the PR, better wait the CI before merging though.

@elpaso @nyalldawson Thank you for accepting this feature during feature freeze

**Pull request merged**
