### PR TITLE
Report fields from polygons to generated points

### PR DESCRIPTION
**Pull request by ThomasG77**
## Description

When you generate the random points in `qgis:randompointsinsidepolygons` processing algorithm, you can't track back for which polygon the generated points have been created if there are overlapped polygons. This PR is for addressing this requirement (see https://gis.stackexchange.com/questions/361885/qgis-random-points-in-polygon-preserving-atrribute-table where the idea is coming from)

I had to rename `f` to `f_point` as there was a conflict with scope between the `f` from polygon (in loop `for current, f in enumerate(source.getFeatures()):`) and the one from `f = QgsFeature(nPoints)`

See the demo in action below

fields-support-for-randompointsinsidepolygons

### CODE REVIEW

**Comment by ThomasG77** [comment]
Related to https://github.com/qgis/QGIS/pull/35745 that could superseded this PR (Port of algorithm to C++)
Up to QGIS PSC to make choice about this.

**Comment by nyalldawson** [comment]
@ThomasG77  does https://github.com/qgis/QGIS/pull/35745 make this redundant?

**Comment by ThomasG77** [comment]
Yes, was not sure due to some remaining bug on the other opened issue. Already mentioned just two comments above ;) https://github.com/qgis/QGIS/pull/36479#issuecomment-638512495

**Comment by ThomasG77** [comment]
Superseeded by #35745

**Pull request closed without merging**
