### PR TITLE
Add "octagon" and "square with corners" shapes to simple marker

### PR DESCRIPTION
**Pull request by nyalldawson**
These reproduce two of the default marker shapes which are provided by ArcGIS, and as a result they are used heavily in projects and map styles created by ArcGIS users. Lack of these shapes makes it harder for users to transition their existing styles to QGIS, and I'm aware that this a roadblock for at least one large govt organisation who want to start supplying their data with QGIS style files which exactly match the existing ArcGIS style files they currently supply.

Here's what the new shapes look like:

image

Given the triviality of the patch (when you exclude all the new unit tests I've included) I'd like to have this included in 3.18.0, and ideally backported to 3.16.5 too. But I'll let someone else make the call on that!

To sweeten the deal I've extended the test coverage of the existing simple marker symbol layer code to include some areas which weren't previously tested :+1: 

Sponsored by SLYR

### CODE REVIEW

**Comment by nyalldawson** [comment]
For reference -- here's what the default simple markers supplied in a ArcMap install look like:

image

image

image

image

image

image

image

image

image

image

image

image


The octagon/rnd square/asterisk 2-4 and Dam Lock symbols are the only ones which can't be reproduced in QGIS by stacking simple or ellipse markers. So after this PR there's only the asterisk and dam lock ones which can't be reproduced. I may add the asterisk ones, but I feel like Dam Lock is rather specialised and better handled as an SVG...

**Comment by nirvn** [comment]
+1 to be added in 3.18 -- I added a bunch of simple markers a while back and I'd have added those then.

Also, big +1 to add this asterik too:
image

As for the dam lock, I don't have strong feelings, but I'd welcome it too.

**Comment by nyalldawson** [comment]
@nirvn Ok I've added an asterisk too

**Comment by nirvn** [comment]
Merge at will

**Comment by roya0045** [comment]
Can't the asterisk be done be stacking x and + to some extent? The dam lock one is a nice pointer type to identify elements on maps. I would appreciate its eventual inclusion.

**Comment by nyalldawson** [comment]
> Can't the asterisk be done be stacking x and + to some extent?

To some extent, but not if you want an outline for the symbol

**Pull request merged**
