### PR TITLE
Average line angles for marker and hashed line symbology

### PR DESCRIPTION
**Pull request by nyalldawson**
Previously, when marker or hash lines were rendered using interval
or center point place placement, the symbol angles were determined
by taking the exact line orientation at the position of the symbol.

This often leads to undesirable rendering effects, where little
jaggies or corners in lines which occur at the position of the
symbol cause the marker or hash line to be oriented at a very
different angle to what the eye expects to see.

With this new option, the angle is instead calculated by averaging
the line over a specified distance either side of the symbol. E.g.
averaging the line angle over 4mm means we take the points along
the line 2mm from either side of the symbol placement, and use these
instead to calculate the line angle for that symbol. This has the
effect of smoothing (or removing) any tiny local deviations from
the overall line direction, resulting in much nicer visual
orientation of marker or hash lines.

Like all symbol settings, the average angle smoothing distance
can be set using mm/pixels/map units/etc, and supports data-defined
values.

Closed rings also correctly consider wrapping around these average
angles from the start/end vertex.

(Sponsored by an anonymous corporate backer)

Apologies for the almost completely un-reviewable PR. The logic here ends up extremely complex, when trying to handle all the different possibilities and existing options.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Showcase images:

Marker line, before: Pay specific attention to the 3rd and last arrow, which seem completely random oriented due to the little shifts in line direction:
image

With new default of 4mm smoothing distance this is fixed:
image

The impact is MUCH greater with hash lines.

Before: (ewwwww)
image

After:
image


An interesting effect is cranking the smoothing distance RIGHT up - this means the angle gets taken over the entire length of that line, so you get symbols oriented to the overall complete line direction.

image

More showcase showing increasing smoothing distance:
0mm (old default):
image

4mm (new default):
image

12mm 
image

26mm
image

**Comment by roya0045** [comment]
Nice feature to compliment the hash symbols!

**Comment by 3nids** [comment]
nice!

**Comment by nirvn** [comment]
@nyalldawson , great work.

**Comment by lbartoletti** [comment]
@nyalldawson impressive!
Did you think that these options could be adapted (or merged in)to transect algorithm (in processing)?

**Comment by nyalldawson** [comment]
@nirvn 7d9b403 fixes the crash you reported yesterday

**Comment by nyalldawson** [comment]
@lbartoletti 

> Did you think that these options could be adapted (or merged in)to transect algorithm (in processing)?

It's possible that QgsTemplatedLineSymbolLayerBase::collectOffsetPoints could be reused for this (and I'd encourage reuse here rather than copying the code... the logic is stupidly complex. It could be simplified greatly if we just interpolated every single point individually, but that would be extremely inefficient and slow. So... complex logic it is :yum: I guess the closed ring handling would also be useful for transects too). What could be done here is to move collectOffsetPoints out to some private class (maybe QgsInternalGeometryEngine) and make it accept lambda functions for retrieving the points on the ring (so that transect can use QgsPoint instead of QPointF). You'd also probably want to split the transect algorithm into two -- the current "transect at vertices" and a new "transect by interval"* algorithm. So it's not a trivial job, but definitely possible and desirable.

\* which reminds me -- I'd really like to see processing numeric parameters gain a "allow multiple" setting and also be able to take arrays of numbers which are returned by expressions. This would be super-useful for the "interpolate by distance..." type algorithms, as we could then accept an array of distance values to create points at non-regular distances (5, 10, 17.6, 18.1, etc). Would be very handy for linear referencing!

**Comment by nirvn** [comment]
@nyalldawson , thanks. I couldn't find any other issue, this PR is good to go :)

**Comment by nyalldawson** [comment]
Thanks @nirvn!

**Pull request merged**
