### PR TITLE
Disble layer rendering to 3D terrain texture for 3D rendered layers

### PR DESCRIPTION
**Pull request by NEDJIMAbelgacem**
## Description
When the 3D rendering is enabled for a layer, the rendering to the 3D terrain texture will be disabled automatically because it is a bit confusing to users.
If you want the 3D viewer to appear on 3D terrain texture and as 3D objects, duplicating the layer should do the work.
 
Funded by QGIS.org grant (https://github.com/qgis/QGIS-Enhancement-Proposals/issues/215)

### CODE REVIEW

**Comment by nyalldawson** [comment]
I wondering -- instead of exposing this as an option, why don't we just ALWAYS disable the layer rendering to terrain whenever the layer has a 3d renderer set? I think that would match user expectations better.

**Comment by NEDJIMAbelgacem** [comment]
> I wondering -- instead of exposing this as an option, why don't we just ALWAYS disable the layer rendering to terrain whenever the layer has a 3d renderer set? I think that would match user expectations better.

That can be done, I can't think of a reason to not do it the way you're suggesting.
I will try it

**Comment by wonder-sk** [comment]
> @nyalldawson  I wondering -- instead of exposing this as an option, why don't we just ALWAYS disable the layer rendering to terrain whenever the layer has a 3d renderer set? I think that would match user expectations better.

I have suggested to Belgacem to introduce this option so that we do not break existing QGIS projects where the users may be expecting this behavior. But I am happy if we do not keep that as an option not to clutter the GUI and force users to create a duplicate of layer without 3d renderer if they want to have layer rendered as a map texture...

**Comment by uclaros** [comment]
A tooltip describing the functionality to those unaware would be nice!

**Review by wonder-sk — APPROVED** [review]

**Pull request merged**
