### PR TITLE
Add heuristic to not simplify geometries for nothing

### PR DESCRIPTION
**Pull request by pvalsecc**
Tested with a release binary and Swiss OSM roads in PostGIS at several zoom
levels (the higher, the less features), values in ms (average over at
least 100 queries):

| Level | Before | After | % improvement |
| --- | --- | --- | --- |
| 7 | 37 | 36 | 2.7 |
| 6 | 41 | 38 | 7.32 |
| 5 | 48 | 46 | 4.17 |
| 4 | 70 | 64 | 8.57 |
| 3 | 114 | 109 | 4.39 |

Not much improvement (I'm quite dispointed, here), but not much change in
the code.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@ahuarte47 you're probably the most familiar with this area, do you mind reviewing this?

**Comment by ahuarte47** [comment]
My apologies, I am not able to see if exist dangerous implications of this change.

**Comment by m-kuhn** [comment]
@ahuarte47 are you worried about something in particular?

I think it's just an early exit from the simplification which results in unsimplified rendering which looks quite safe to me and the worst that could happen is that under some conditions a small performance impact caused by disabled simplification was triggered.

**Comment by ahuarte47** [comment]
ok, no problem, you are right, the worst situation don't seem dangerous :-)

**Comment by sbrunner** [comment]
OK, than it should be re-based and merged :-)

**Comment by m-kuhn** [comment]
Sounds good to me :+1:

**Comment by m-kuhn** [comment]
Thanks @pvalsecc and @sbrunner

**Pull request merged**
