### PR TITLE
[travis] Use docker to run test

### PR DESCRIPTION
**Pull request by m-kuhn**
## Description

This uses a docker image based on Ubuntu 16.04.
This makes dependency management easier, because we can use the main repositories (which is not possible currently because travis ships very old ubuntu versions).

Some tests have been made more stable and issues fixed.

The future of this hopefully is automated deployment of docker images / other setup binaries from the builds.

Some tests are still failing.

### CODE REVIEW

**Comment by 3nids** [comment]
@rouault qgis_rastersublayertest is [failing](https://travis-ci.org/qgis/QGIS/jobs/279820514#L2526) with  `ERROR 1: NETCDF:"/root/QGIS/tests/testdata/landsat2.nc":Band1, band 1: Failed to compute statistics, no valid pixels found in sampling`

`gdalinfo tests/testdata/landsat2.nc ` returns:
image

Coordinate system is weird, does that speak to you?
Cheers!

**Comment by m-kuhn** [comment]
Does anyone know what's up with the CRS **NZGD49 (27223)**?

It's reported by `QgsCoordinateReferenceSystem::validSrsIds()` but the CRS returned by `QgsCoordinateReferenceSystem::fromSrsId(27223)` is not valid. (CC @rouault )

**Comment by 3nids** [comment]
@m-kuhn didn't you have to use `fromEpsgId` ?
see difference between `createFromSrsId` and `createFromSrid`

**Comment by m-kuhn** [comment]
Looks like `fromEpsgId` uses `createFromSrsId` internally. And I'm actually also wondering why this test that worked before no longer works now...

**Comment by m-kuhn** [comment]
@rouault WFS10 tests are failing here (introduced in 9040ec1ba)
https://travis-ci.org/qgis/QGIS/jobs/280342684#L2319-L2328

```
======================================================================
FAIL: testWFST10 (__main__.TestPyQgsWFSProvider)
Test WFS-T 1.0 (read-write)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/QGIS/tests/src/python/test_provider_wfs.py", line 764, in testWFST10
    self.assertTrue(ret)
AssertionError: False is not true
----------------------------------------------------------------------
```

Do you have any idea what's going wrong there? I enabled some additional debug output, but could not discover yet what's going on.

**Comment by rouault** [comment]
I guess the issue is that none of the 2 expected request URL at https://github.com/qgis/QGIS/blob/87a58f02d94af7c014f0e35727095bd93d3ce742/tests/src/python/test_provider_wfs.py#L745 and below is emitted
It would help if we could see the output of the debug messages at https://github.com/qgis/QGIS/blob/master/src/providers/wfs/qgswfsrequest.cpp#L70 and https://github.com/qgis/QGIS/blob/master/src/providers/wfs/qgswfsrequest.cpp#L99

**Comment by 3nids** [comment]
@rouault sorry to hassle, have you seen my first message in the thread?

**Comment by rouault** [comment]
@3nids  No I hadn't seen your message

I can reproduce
```
$ gdalinfo  NETCDF:"/home/even/qgis/QGIS/tests/testdata/landsat2.nc":Band1 -mm
[...]
Band 1 Block=200x1 Type=Byte, ColorInterp=Undefined
ERROR 1: NETCDF:/home/even/qgis/QGIS/tests/testdata/landsat2.nc:Band1, band 1: Failed to compute statistics, no valid pixels found in sampling.
 Value=240
  Metadata:
    grid_mapping=transverse_mercator
    long_name=GDAL Band Number 1
    NETCDF_VARNAME=Band1
    valid_range={0,255}
    _FillValue=-16
    _Unsigned=true
```

Looking the content of this raster shows that all pixels are at the nodata value, 240, hence this failure, since the statistic computations ignore pixels which are at the nodata value.

**Comment by 3nids** [comment]
@rouault thanks for your quick answer. Was there any change in this domain (explaining the test is not failing today on master with older gdal)?

**Comment by m-kuhn** [comment]
... and is the test actually well-defined and meaningful?

**Comment by rouault** [comment]
> Was there any change in this domain (explaining the test is not failing today on master with older gdal)?

There was a bug in the netCDF driver where it didn't retrieve correctly the nodata value for Byte bands (and thus only saw valid values). Was fixed per https://trac.osgeo.org/gdal/ticket/6175 in GDAL 2.1.0

**Comment by 3nids** [comment]
good question....

@blazek was this intended to check stats on a completely null raster (nodata only)?
https://github.com/qgis/QGIS/commit/482a007fb195d2c47b9f4cb5f5b0752207a7af5d

**Comment by m-kuhn** [comment]
@rouault

> It would help if we could see the output of the debug messages at https://github.com/qgis/QGIS/blob/master/src/providers/wfs/qgswfsrequest.cpp#L70 and https://github.com/qgis/QGIS/blob/master/src/providers/wfs/qgswfsrequest.cpp#L99

Here they are:

https://travis-ci.org/qgis/QGIS/jobs/280401207#L7066

**Comment by rouault** [comment]
Regarding the WFS failure, the interesting line is
```
"Get http:///tmp/tmps4sblvw4/fake_qgis_http_endpoint_WFS1.0?SERVICE=WFS&POSTDATA=<Transaction xmlns=\"http://www.opengis.net/wfs\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:gml=\"http://www.opengis.net/gml\" xsi:schemaLocation=\"http://my http://fake_qgis_http_endpoint?REQUEST=DescribeFeatureType&amp;VERSION=1.0.0&amp;TYPENAME=my:typename\" xmlns:my=\"http://my\" version=\"1.0.0\" service=\"WFS\"><Insert xmlns=\"http://www.opengis.net/wfs\"><typename xmlns=\"http://my\"/></Insert></Transaction>"
```
So 2 issues: the order of attributes in the serialized XML is different than the order known for QT4 and QT5 currently. More serious the inserted feature is empty (no child for <typename xmlns="http://my">). That could mean that for some reason the WFS provider couldn't get or parse correctly the DescribeFeatureType response

**Comment by m-kuhn** [comment]
I guess we'll find a way to fix the first one (Qt5 is quite picky concerning the attribute order in XML, but it should be possible to have stable values https://stackoverflow.com/questions/27378143/qt-5-produce-random-attribute-order-in-xml)

Do you have any idea what to do about the second one? This PR shouldn't have touched any of this code, it's just a dependency and environment update...

**Comment by rouault** [comment]
> Do you have any idea what to do about the second one?

Unfortunately not

**Comment by m-kuhn** [comment]
Shall we just turn it off?

**Comment by 3nids** [comment]
@m-kuhn congrats for the short list of failing tests...

 * 103 - qgis_rastersublayertest (Failed) : blacklist for the moment?
 * 291 - PyQgsShapefileProvider (Failed) : should be fixed b https://github.com/qgis/QGIS/pull/5231#issuecomment-332196774 ?
  * 328 - PyQgsWFSProvider (Failed) : is that the one you propose to disable?

**Comment by m-kuhn** [comment]
I'm proposing to disable (affected parts of) all 3 of them. All of them are 

* either unstable and
* or expose issues with newer dependencies which are good to be fixed but I don't think do fall into the responsibility of the work done in this PR (apart from even being aware of them)

CC @rouault @manisandro @blazek

**Comment by m-kuhn** [comment]
Are there objections to merging this? I'd be happy to get this merged soon, but a bit preoccupied for disabling tests. In case anyone has got a good strategy, please say so.

**Comment by nyalldawson** [comment]
Can you ping the dev mailing list about the broken test removal? 

I'd also only disable the raster sublayer test on Travis, so it still fails locally

**Comment by blazek** [comment]
rastersublayertest: landsat2.nc is not empty, it was converted from landsat.tif and the data are there (I checked with ncdump), but gdal somehow does want to read it. 

@rouault I have GDAL 2.1.3 which should be fixed(?) but it does not read landsat2.nc which has _FillValue=-16, _Unsigned=true, are you sure the fix is correct?

@m-kuhn Can you re-create landsat2.nc with `gdal_translate -of NETCDF landsat.tif landsat2.nc` and try to reanable the test including min/max check? It should create landsat2.nc with _FillValue=0, _Unsigned=true which is readable for GDAL.

**Comment by rouault** [comment]
> I have GDAL 2.1.3 which should be fixed(?) but it does not read landsat2.nc which has _FillValue=-16, _Unsigned=true, are you sure the fix is correct?

What do you mean with "it does not read" ? Do you mean it doesn't manage to open it (it should), or that statistics computation fails ? The later is expected and the proper behaviour. This dataset has only null values, so no statistics can be computed.

**Comment by blazek** [comment]
It tells "Failed to compute statistics, no valid pixels found in sampling." as mentioned above. If I run
`
ncdump landsat2.nc
` 
from http://www.unidata.ucar.edu/downloads/netcdf/index.jsp it prints
`
Band1 = 125, 125, 125, 125, 126, 126, 126, 126, 126, 125, 127, 127....
`
values in expected range, apart that over 127 the values are negative.

**Comment by nyalldawson** [comment]
>  You're right. There was a bug in the netCDF driver with that particular type of dataset.

Wheee QGIS unit tests to the rescue!

**Comment by blazek** [comment]
> Perhaps this test could be modified to use another format like GeoTIFF to avoid running into this issue ?

I suggested to recreate the file
`
gdal_translate -of NETCDF landsat.tif landsat2.nc
`
The test was written for sublayers, it should be a format with sublayers.

**Comment by 3nids** [comment]
I guess recreating the file won't change anything if gdal has just been fixed now.
We could maybe just disable the part of test when GDAL < 2.2.3

**Comment by rouault** [comment]
"gdal_translate -of NETCDF landsat.tif landsat2.nc" will not work as expected since the driver doesn't support creating subdatasets. I have used ncdump + manual changing of _FillValue to 0 + ncgen to recreate it. Hopefully it should work (untested) Result attached

**Comment by m-kuhn** [comment]
Thanks @rouault and @blazek , the updated version works (the failing test is a different, flaky one)

**Pull request merged**
