### PR TITLE
Redesign expression function editor.

### PR DESCRIPTION
**Pull request by NathanW2**
Turns out I wasn't really happy with how I built the first version of the function editor.  Here is redesigned version.

Main features:
- Clear new file function. New File -> Enter Name -> Gives you new file.
- Removed scratch file. Was confusing really. 
- File list on the side
- Auto saving files (save label fades in/out when saved)
- Clearer button labels
- Function test area

screenshot from 2015-10-27 23 39 55

Still more to do and clean up but open for review.

### CODE REVIEW

**Comment by NathanW2** [comment]
@nyalldawson @nirvn

**Comment by nirvn** [comment]
@NathanW2 few comments:
* the Test label / input box is where you can enter an expression to test out your custom function(s), is that right? If so, maybe the label could be more explicit, if not, help me :smile: 
* do we really need a save button? I'd prefer for the function editor to simply automatically save the file by itself (I can't think of a scenario where you would _not_ want it saved automaticall)
* what about putting the file list box to the right of the edit box? that would better link with the expression builder UI

**Comment by NathanW2** [comment]
> the Test label / input box is where you can enter an expression to test out your custom function(s), is that right? If so, maybe the label could be more explicit, if not, help me :smile:

Yeah haven't fleshed that bit out yet.  Idea was just to have something to test the functions without needed to swap back and forth.

> do we really need a save button? I'd prefer for the function editor to simply automatically save the file by itself (I can't think of a scenario where you would not want it saved automaticall)

I did have it on a timer but not that it saves on each edit I think that the save button can go.  No overhead on the save on edit it seems.

> what about putting the file list box to the right of the edit box? that would better link with the expression builder UI

Will try and see what it looks like.

**Comment by NathanW2** [comment]
Tried on the right side.  Wasn't really a fan because it didn't flow right, but open to changing it if others feel the same.

**Comment by NathanW2** [comment]
image

**Comment by NathanW2** [comment]
Rebased and merged

**Pull request closed without merging**
