### PR TITLE
[plugin manager] fix sending plugin votes

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
Fixes sending votes for plugins which seems broken in master.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by alexbruy** [comment]
BTW, I also noticed that votes does not update after sending one.

**Review by borysiasty — APPROVED** [review]

**Comment by elpaso** [comment]
@alexbruy server side there are some checks to prevent a user votes multiple times ... maybe you're hitting those

**Comment by borysiasty** [comment]
As I understand, after that fix the only problem left is refreshing the plugin details view. @alexbruy, you use the webkit version (voting embedded into the QgsWebView), don't you?

**Comment by alexbruy** [comment]
@borysiasty how I can check this? As I can see Webkit version should not use Python code to send vote, it has some JS code which does the job. So I assume I use non-webkit version. Although I have WebKit installed.

**Comment by alexbruy** [comment]
@borysiasty then I use WebKit version, there is no slider, I see stars not slider.

**Comment by borysiasty** [comment]
Ok, anyway I'm pulling this one.

**Comment by borysiasty** [comment]
> As I can see Webkit version should not use Python code to send vote, it has some JS code which does the job. 

@alexbruy: Ok, the uri you see in JavaScript is handled by manager's slot and finally both versions call the same Python code, so it works properly.

I'll look at refreshing the plugin details (now you need to reload the repo xml to get the score updated).

**Pull request merged**
