### PR TITLE
[DB Manager] Add the ability to update SQL Layer

### PR DESCRIPTION
**Pull request by rldhont**

### CODE REVIEW

**Comment by NathanW2** [comment]
So this lets you tweak the query of the layer?

**Comment by rldhont** [comment]
@NathanW2 yes it is made for

**Comment by NathanW2** [comment]
Nice work.

**Comment by rldhont** [comment]
It probably needs to update ts.
And I'd like to backport it to release 2_16 and 2_14

**Comment by rldhont** [comment]
Can I merge and backport to master_2 ?

**Comment by jef-n** [comment]
Is it a fix?

**Pull request merged**
