### PR TITLE
[Feature] Adds the $m, $z_at and $m_at expressions

### PR DESCRIPTION
**Pull request by Koyaani**
## Description

This PR adds the `$m` (`$z` has already been added), `$z_at()` and `$m_at()` functions in the expressions.

Sponsored by: Métropole Européenne de Lille, cc @Jean-Roc

### CODE REVIEW

**Comment by roya0045** [comment]
I thought the use of the $ was to have them as a variable/property and not a function.

**Comment by nyalldawson** [comment]
I'm -1 to this. The $x/$y syntax is the old method, kept around predominantly for project compatibility. You can instead use something like `z($geometry)`

**Comment by Koyaani** [comment]
@nyalldawson so all `$` functions (with and without parameter) except `$feature` and `$geometry` will be removed (in QGIS 4)? And are currently deprecated? I have the impression that there is no indication for the user in the documentation and for the developer in the code about this. Maybe we should mention this?

**Comment by nyalldawson** [comment]
> so all $ functions (with and without parameter) except $feature and $geometry will be removed (in QGIS 4)? 

No, they won't be removed in QGIS 4. There's no harm in leaving them in place so that old projects still work (and breaking old project compatibility should be something we only do in extreme circumstances).

> And are currently deprecated? I have the impression that there is no indication for the user in the documentation and for the developer in the code about this. Maybe we should mention this?

It's more that the underlying code for them has never been ported to the expression context framework and exposed as expression variables like they should be. Ideally ALL the existing "$xxx" functions should be instead replaced by context-dependent "@...." versions, and then the "$" form just used as an alias for the context variable versions. (And over time we could then hide the "$" forms from the dialog help and suggestions so that users are gently pushed to the @ variable versions)

**Comment by nyalldawson** [comment]
Sorry -- just to give some more context here:

We have two uses for the older "$" notation at the moment. One is for retrieving the current feature ($currentfeature), and the other is to retrieve properties of that current feature (eg. $x, $area, etc). 

All those property-type $ should instead be functions which can apply to any feature/geometry value. Then you could use them for a whole range of uses, including evaluating them on the atlas feature, on a feature retrieved using get_feature, get_feature_by_id, etc.

So your $z, $m, "$z_at" and "$m_at" should instead be functions "z(some geometry)", "m( some geometry) ",  "z_at( some geometry )", "m_at( some geometry )". That offers the most flexibility for their use.

**Comment by Jean-Roc** [comment]
Hi, I didn't knew these expressions where deprecated, our usecase and base for this pull request is to display Z values of linestring's nodes using a font marker and `$z_at(@geometry_point_num)` as we used for x/y. Following your advice, we can replace it by `z(point_n($geometry,@geometry_point_num))`.

@Koyaani is there anything we can salvage from this PR ?

**Comment by Koyaani** [comment]
@nyalldawson ok, so, shouldn't the user be informed that the use of functions is preferred to properties (like `$x`, `$area`)? That the user doesn't end up with a mix of `$x_at()` and `z(point_n($geometry, ...))` (since `$z_at()` doesn't exist)? Then is there a place where we can explicitly write that we should stop adding $ functions? Maybe it's already done?

@Jean-Roc With `z()` and `m()`, the 3 functions of this PR currently have an equivalent in QGIS. I'm not sure about the interest of adding `x/y/z/m_at($geoemtry)`. PR can be closed.

**Comment by roya0045** [comment]
> > so all $ functions (with and without parameter) except $feature and $geometry will be removed (in QGIS 4)?
> 
> No, they won't be removed in QGIS 4. There's no harm in leaving them in place so that old projects still work (and breaking old project compatibility should be something we only do in extreme circumstances).
> 
> > And are currently deprecated? I have the impression that there is no indication for the user in the documentation and for the developer in the code about this. Maybe we should mention this?
> 
> It's more that the underlying code for them has never been ported to the expression context framework and exposed as expression variables like they should be. Ideally ALL the existing "$xxx" functions should be instead replaced by context-dependent "@...." versions, and then the "$" form just used as an alias for the context variable versions. (And over time we could then hide the "$" forms from the dialog help and suggestions so that users are gently pushed to the @ variable versions)

This is a sidetrack but regarding the "@" , I was looking at the filter by expression in the layer panel and was thinking that it was missing a way to address the layers to do comparison (to filter by data type or else).

Might be a good place to implement this pattern if it's not done elsewhere.

**Comment by nyalldawson** [comment]
@Koyaani 
> ok, so, shouldn't the user be informed that the use of functions is preferred to properties (like $x, $area)? That the user doesn't end up with a mix of $x_at() and z(point_n($geometry, ...)) (since $z_at() doesn't exist)?

Well, that's where things get murky. We really need to ensure a replacement for ALL the $ functions is available before we try to get users to adapt existing projects.

@Jean-Roc 
> is there anything we can salvage from this PR ?

It'd be great to rework the $z_at/$m_at to proper functions z_at(...), m_at(...). Most of the hard work was already done in this PR.

**Pull request closed without merging**
