### PR TITLE
[processing] restore "random" algorithms

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
Restore algorithms to generate random points

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]
Looks good! The only thing I'm unsure about is the new addZ/M parameters. Since these are only used to set whether a 0 value Z/M is present, I think they're better left to the existing dedicated addZ/M algorithms. Otherwise we'd potentially need to add these same controls to every algorithm which creates geometries. What do you think?

**Comment by nirvn** [comment]
Unless the Z and M parameters are there to add random values to Z and/or M when the random point algorithm runs, I think @nyalldawson is right, better leave that action to the existing algs.

**Comment by nirvn** [comment]
(BTW, I do think random points with random Z would come in handy, with a pair of min / max value parameters)

**Comment by NathanW2** [comment]
That would be very handy.

**Comment by nyalldawson** [comment]
> (BTW, I do think random points with random Z would come in handy, with a pair of min / max value parameters)

I kinda wondered that too - and was wondering whether the z should be limited to the range of min/max z from the original geometry. But honestly it's probably overkill.

**Comment by nirvn** [comment]
@nyalldawson , @alexbruy , what about automatically adding random Z values if the algorithm detects that the original geometry (layer bound / polygon / line) has Z values? I'd also go with @nyalldawson 's suggestion to determine a range based on min and max Z value of original geometry.

**Comment by alexbruy** [comment]
@nyalldawson agreed. I've removed Z/M addition from algorithms.

**Pull request merged**
