### PR TITLE
Updated and vectorized several icons

### PR DESCRIPTION
**Pull request by FelisPimeja**
image
image

**List of icons:**
grass_location.svg
grass_mapset.svg
grass_mapset_open.svg
grass_mapset_search.svg
mActionMoveVertex.svg
mActionProjectProperties.svg
mActionSelectPan.svg
mIconCritical.svg
mIconJoinedLayerNotEditable.svg
mIconJoinHasNotUpsertOnEdit.svg
mIconJoinNotEditable.svg
pluginDeprecated.svg
symbologyEdit.svg
mIconFavourites.svg
mIconListView.svg
mIconNoPyramid.svg
mIconPyramid.svg
mIconTimerContinue.svg
mIconTimerPause.svg
mIconTreeView.svg
vector_grid.svg

### CODE REVIEW

**Comment by nyalldawson** [comment]
Looking great -- thanks!

My 2c: a number of these icons here need aligning to the pixel grid, as they look blurry on my (lo dpi) screen. I'd also love to see a different approach taken with the pyramid icons as the current "3d" approach looks very out of place with the rest of the QGIS icon set.

@nirvn what do you think?

**Comment by nirvn** [comment]
Regarding mIconListView.svg and mIconTreeView.svg, it'd be great if those could better match the color scheme / style of a similar icon found in the layers panel as well as the identify results panel.

Indeed, the 3D pyramid would be worth flattening to better fit in.

**Comment by FelisPimeja** [comment]
Got it. I'll have a look.

**Comment by FelisPimeja** [comment]
@nyalldawson, I've corrected icons to pixel grid. Could you have a look, please? At first I wanted just to trace current icons, not trying to redesign anything, but if you don't mind I'll try to look at it closer.

By the way, @nirvn, I can't find mIconListView and mIconTreeView in the interface (cannot understand it from code either) :). Can you tell me where are they located?

**Comment by nirvn** [comment]
@FelisPimeja , I don't build QGIS with the GRASS plugin over here, so can't produce screenshots. That said, while the icons are only used within the GRASS plugin for now, having those align with our general theme will allow others to make use of it in the future.

Great effort on vectorization BTW, _very_ appreciated.

**Comment by nyalldawson** [comment]
Looks good to me! If @nirvn approves then I'm +1

**Review by nirvn — APPROVED** [review]

**Comment by blazek** [comment]
Great, thanks.

**Pull request merged**
