### PR TITLE
[feature] User expressions followup

### PR DESCRIPTION
**Pull request by elpaso**
Followup https://github.com/qgis/QGIS/pull/33437

- renamed the group to "User expressions"
- added help text for the group
- added QgsSettings Expressions namespace
- reworded tooltips for store/remove actions

user-expressions

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@elpaso are the custom functions created in python also stored in here? In qgis 3.10 they seem to appear in a "custom" group. I am wandering if we shouldn't keep that name only for the functions and not stored expressions.

**Comment by elpaso** [comment]
What do you mean? The name here is "User" not "Custom".

**Comment by SrNetoChan** [comment]
Bu the help says it stores custom functions. And then there can be a "custom" group that where the custom python functions will show.

That's why I asked. When, in that group help, you say it contains "custom functions" what do you mean with that?

**Comment by elpaso** [comment]
What do you suggest? Drop "custom" to avoid confusion?

**Comment by SrNetoChan** [comment]
If there's no functions in there, I wouldn't mention custom fuctions. Just "user's saved expressions"

**Comment by m-kuhn** [comment]
Did you consider ["User Expressions" as discussed in the original PR](https://github.com/qgis/QGIS/pull/33437#issuecomment-566592702)?

**Comment by elpaso** [comment]
Using "expressions" in an expression list seemed redundant to me.

**Comment by SrNetoChan** [comment]
Actually, the list is of functions, not expressions :-p.

But the same happen with the "recent" group

**Comment by elpaso** [comment]
ok, let's settle back to "User expressions"

**Comment by m-kuhn** [comment]
I wouldn't mind "recent expressions", but the term *recent* has less ambiguity than the term *user*.

**Comment by roya0045** [comment]
What about "Saved expressions"? It is what they are, recent implies that they are the latest, whereas saved expression is straightforward as those have been explicitly saved by the user. (Unless this is not related to the work in the other PR).

**Comment by pigreco** [comment]
@roya0045 

> What about "Saved expressions"?

in the [QEP ](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/135#issuecomment-558108289)it is really so

**Comment by roya0045** [comment]
> @roya0045
> 
> > What about "Saved expressions"?
> 
> in the [QEP ](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/135#issuecomment-558108289)it is really so

I guess we could have one named 'saved expression' and the other 'stored expression', where one would refer to expressions explicitly saved by a user whereas stored expressions would be expression stored in a project.This would ensure that people don't mix up either if we consider the other implementation discussed in the other PR.

**Pull request merged**
