### PR TITLE
added buffer tests

### PR DESCRIPTION
**Pull request by anitagraser**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks @anitagraser 

Was there no .xsd file produced next to the gml file?

**Comment by anitagraser** [comment]
sorry, added them now

**Comment by m-kuhn** [comment]
Seems gdal does not detect the geometry type if the file is missing...

**Comment by m-kuhn** [comment]
No reason to merge master in ;)

**Comment by anitagraser** [comment]
mhm, that was not the plan ... github trying to be too clever now ...

**Comment by anitagraser** [comment]
just getting worse now ...

**Comment by anitagraser** [comment]
tried to work with github desktop ... took me two hours to clone QGIS but just minutes to screw it up :-P

**Comment by m-kuhn** [comment]
I found "tortoise git" to be a good GUI git management tool on windows.

**Pull request closed without merging**
