### PR TITLE
Don't crash the projection selection widget when world_map.shp fails to load

### PR DESCRIPTION
**Pull request by nirvn**
## Description
I believe this PR fixes a number of duplicate crashers reported recently (#17711, #17662, #17610, #17589, possibly more I haven't spotted).

QGIS was crashing while loading our projection selection tree widget when world_map.shp failed to load (missing from the system or no read access). The vector layer, invalid due to failure to load world_map.shp, would be added to the canvas and trigger an underlying issue when creating a QgsVectorLayerFeatureSource.

@nyalldawson , sounds good to you? The reason why the layer's mExpressionFieldBuffer is null is because the QgsVectorMap::setDataProvider(...) function would return due to its invalid status before the variable is init'ed to on qgsvectorlayer.cpp line 1558 (`mExpressionFieldBuffer = new QgsExpressionFieldBuffer();`). I wasn't sure whether we should also fix that or not by moving that line up the code so its init'ed prior to the early return.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
@NathanW2 , the crasher did end up revealing that on some systems, the world_map.shp isn't installed. Might be worth investigating why.

**Comment by elpaso** [comment]
@nirvn thanks! I also had a quick look to that bug[1] before the holidays and I was about to propose a fix similar to yours. In my TODO there was also a check about the assumption that `layer->mExpressionFieldBuffer` is never a `nullptr` in other parts of the code. 

[1] https://issues.qgis.org/issues/17610

**Comment by nirvn** [comment]
@elpaso , one way we could make the assumption true is to move qgsvectorlayer.cpp line 1558 a few lines above, so that even if a vector layer returns early to to an invalid state, mExpressionFieldBuffer will never be a nullptr.

**Comment by elpaso** [comment]
> one way we could make the assumption true is to move qgsvectorlayer.cpp line 1558 a few lines above, so that even if a vector layer returns early to to an invalid state, mExpressionFieldBuffer will never be a nullptr.

That makes sense, but I'd really like to see `mExpressionFieldBuffer` initialized in the constructor.

**Comment by m-kuhn** [comment]
I believe it would make sense to have the buffer initialized in the constructor and deleted in the destructor.

**Comment by nirvn** [comment]
@m-kuhn , would we then remove the null check I added in the initial commit? That'd become obsolete.

**Comment by m-kuhn** [comment]
Yes

**Comment by nirvn** [comment]
@m-kuhn , done.

**Pull request merged**
