### PR TITLE
return a closed iterator for a feature request with a rectangle on a non-spatial layer

### PR DESCRIPTION
**Pull request by 3nids**
https://github.com/qgis/qgis3.0_api/issues/79

### CODE REVIEW

**Comment by wonder-sk** [comment]
Looks good - but maybe it would be worth doing that also for individual provider iterators for consistency?

**Comment by wonder-sk** [comment]
... and a unit test to confirm the behavior would be great ;-)

**Comment by 3nids** [comment]
will do the test. 
something I don't understand about individual provider iterators: I did the change only here and did the test with a PG layer and worked as expected. Is there really a need to implement this everywhere?

**Comment by m-kuhn** [comment]
Looks good to me, same comments apply
For the dataprovider, consider the following snippet

    layer.dataProvider().getFeatures(rect)

**Comment by 3nids** [comment]
hmmm isSpatial is not implemented at provider level and doesn't seem that easy to implement (for QgsAfsProvider for instance).

**Comment by m-kuhn** [comment]
Maybe this works:

    QgsWkbTypes::geometryType( mDataProvider->wkbType() ) == QgsWkbTypes::NullGeometry

or something like this:

    QgsWkbTypes::geometryType( afsIterator->sharedData()->mGeometryType )  == QgsWkbTypes::NullGeometry

**Comment by nyalldawson** [comment]
Yeah - definitely needs a test added to the provided test suite here.

**Comment by nyalldawson** [comment]
> Yeah - definitely needs a test added to the provided test suite here.

I realised this comment was wrong - the test belongs in the feature source test suite, so that all feature sources (including providers) are tested.

**Pull request closed without merging**
