### PR TITLE
Enable automatic high DPI scaling and fix incorrect map scale calculation

### PR DESCRIPTION
**Pull request by jbp35**
This PR enables automatic high DPI scaling which is not set by default in QT5. As this is not currently enabled, QGIS uses the default DPR of 1 on all devices (except if a custom environment variable is set at the OS level). This causes multiple UI scaling issues on high DPI screens.

Fixes (tested):
https://github.com/qgis/QGIS/issues/49764

Possibly also fixes:
https://github.com/qgis/QGIS/issues/40274
https://github.com/qgis/QGIS/issues/52643
https://github.com/qgis/QGIS/issues/25669
https://github.com/qgis/QGIS/issues/25673
https://github.com/qgis/QGIS/issues/52291

### CODE REVIEW

**Comment by nirvn** [comment]
For the record, +1 to merge this; we should do it as soon as possible so it can be thoroughly tested prior to releasing 3.32.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
I've tested this, and while there's some regressions the end result is considerable better then the current state.

Regressions I've spotted:

- marker symbol rendering is pixelated in canvas and in symbol preview widgets
- color ramp legend items are oversized
- symbol preview icons in the style manager are pixelated

We also need to check if the default icon size calculation for new installs is still appropriate, or whether this should be hardcoded to 24 pixels now.

**Comment by jbp35** [comment]
> I've tested this, and while there's some regressions the end result is considerable better then the current state.
> 
> Regressions I've spotted:
> 
> * marker symbol rendering is pixelated in canvas and in symbol preview widgets
> * color ramp legend items are oversized
> * symbol preview icons in the style manager are pixelated
> 
> We also need to check if the default icon size calculation for new installs is still appropriate, or whether this should be hardcoded to 24 pixels now.

Thank you for looking into this! I am facing the same regressions but have not yet been able to figure out what's causing these issues.
Regarding hard-coding the toolbar icon size, I think this is a better approach since the current code only considers the primary display when guessing the best icon size . I assume this could cause issues with dual displays having different DPR. I tried to hard-code, and it works fine in my environment. here is a follow-up PR with the changes :
https://github.com/qgis/QGIS/pull/53077

**Comment by jbp35** [comment]
Another potential regression I spotted:
- Color picker is pixelated in layer panel context menu and in layer properties

**Comment by jbp35** [comment]
@nyalldawson Probably another one to fix: the 3D Map view looks blurry and could probably get some attention.

**Pull request merged**
