### PR TITLE
don't allow field precision greater than field width (fix #14019, #5154)

### PR DESCRIPTION
**Pull request by alexbruy**

### CODE REVIEW

**Comment by medspx** [comment]
Is it the same thing than #2572 ?

**Comment by SebDieBln** [comment]
Note that 11081f8ffe683e4e6bf74780c8861d079ba39918 fixes the issue Travis CI [complains about](http://dash.orfeo-toolbox.org/viewBuildError.php?type=1&buildid=214638) in your build. Rebasing should make it happy.

**Comment by medspx** [comment]
Hello,

I have closed my old PR #2572 because its code has been incorporated into this PR.
@m-kuhn or @nyalldawson , I know you are very busy but is there a developper with commit rights who could merge this PR before release ? it is just bugfixing and I am pretty sure that it doesn't break anything...

**Comment by nyalldawson** [comment]
Looks good to me - thank you!

**Pull request merged**
