### PR TITLE
processing: add gdal tileindex

### PR DESCRIPTION
**Pull request by gioman**
Contributed by Pedro Venâncio.

### CODE REVIEW

**Comment by gioman** [comment]
assigned @volaya @alexbruy

**Comment by gioman** [comment]
Hi Alexandre, thanks. Would you mind also committing my other 3 PR https://github.com/qgis/QGIS/pulls/gioman ? they are about new tools for processing. Thanks!

**Comment by alexbruy** [comment]
I already look on them and will commit ASAP

**Comment by gioman** [comment]
Thanks Alexander!

**Pull request merged**
