### PR TITLE
Fix geojson mixed type data loss

### LINKED ISSUE #51911: Some versions of QGIS can't parse mixed-dtype-columns in GeoJSON
### What is the bug or the crash?

GeoJSON allows to put any JSON value (string, number, object, array, true, false, null) as the value of a property. If a property with the same name appears in multiple GeoJSON features, GDAL maps that onto a column. Depending on the version of GDAL (I guess) and what dtype is encountered first,
* either the column only preserves JSON objects and null values but converts strings, numbers, arrays, true and false to NULL. (Looses almost all information)
* or coerces everything to strings. (Looses only type information)

In detail, I have seen two cases how QGIS deals with mixed types of JSON values:

1. **GDAL version is 3.6.2 AND the first value is NOT a string**
  - According to Layer/Properties/Fields, the Type name of the field becomes JSON.
  - This is incorrectly mapped to the Type QVariantMap which can only represent JSON object but not any other type of JSON value (i.e. string, number, array, true, false, null).
  - Consequently, only JSON objects and null values are correctly read into the attribute table. Arrays show as empty. Strings, numbers, true, false and null are mapped to NULL.

2. **GDAL version is 3.0.4 OR the first value is a string**
  - According to Layer/Properties/Fields, the Type name of the field becomes String.
  - This is mapped to QString.
  - Consequently, all types of JSON values are coerced to a string representation.

### Steps to reproduce the issue

Create the following file with a text editor:

`test.geojson`

```
{ "type": "FeatureCollection",
  "features": [
    { "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
      "properties": {"prop0": 42}
      },
    { "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
      "properties": {"prop0": "astring"}
      },
    { "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
      "properties": {"prop0": {"nested": 75}}
      }
    ]
  }
```

and load it in QGIS. Look at the Attribute table. On the newest QGIS version on Windows the values `42` and `"astring"` are lost and replaced by NULL. On a fresh install of QGIS on Linux Mint 20.1, all values are present but converted to strings.

Edit the GeoJSON to have a string in the first feature, close and reopen, and everything is converted to string on Windows too.

##### **NULL** values on Windows & QGIS 3.28:

QGIS version
3.28.3-Firenze
QGIS code revision
c12bcb2f76c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

##### **NULL** values on Windows & QGIS 3.22

QGIS version
3.22.16-Białowieża
QGIS code revision
6f08e4d7
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

##### **string** values:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdad
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.12 (Ubuntu 12.12-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Linux Mint 20.1
  |   |   |  
Active Python plugins
QPackage | 1.5
quick_map_services | 0.19.26
mapswipetool_plugin | 1.2
qconsolidate3 | 0.2.0
openlayers_plugin | 2.0.0
qgis2web | 3.16.0
qgis-maptiler-plugin | 2.0.0
QuickOSM | 2.0.0
grassprovider | 2.12.99
db_manager | 0.1.20
sagaprovider | 2.12.99
processing | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.26.3-Buenos Aires
QGIS code revision
[65e4edfdad](https://github.com/qgis/QGIS/commit/65e4edfdad)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.12 (Ubuntu 12.12-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Linux Mint 20.1

Active Python plugins
QPackage
1.5
quick_map_services
0.19.26
mapswipetool_plugin
1.2
qconsolidate3
0.2.0
openlayers_plugin
2.0.0
qgis2web
3.16.0
qgis-maptiler-plugin
2.0.0
QuickOSM
2.0.0
grassprovider
2.12.99
db_manager
0.1.20
sagaprovider
2.12.99
processing
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #51911

### CODE REVIEW

**Comment by m-kuhn** [comment]
Can you explain with some words the impact of this?
I assume it's a loss in functionality of https://github.com/qgis/QGIS/pull/43164 and @andreasneumann should review it.

Is a change in the gdal provider correct or is it actually a problem of the widget?

**Comment by elpaso** [comment]
> Can you explain with some words the impact of this? I assume it's a loss in functionality of #43164 and @andreasneumann should review it.
> 
> Is a change in the gdal provider correct or is it actually a problem of the widget?

Can you check https://github.com/qgis/QGIS/issues/51911 for some context and in-depth analysis?

This PR fixes the wrong assumption that any field reported by GDAL as subtype `OFSTJSON` is a kvp and treated by QGIS as a QVariantMap.

This PR probably breaks the kvp key-value widget selection for JSON fields.

There is a related issue in GDAL which does not set the OFSTJSON subtype if the first occurrence of a JSON field is a string but fixing it does not resolve #51911.

**Comment by m-kuhn** [comment]
> Can you check #51911 for some context and in-depth analysis?

I did

> This PR fixes the wrong assumption that any field reported by GDAL as subtype OFSTJSON is a kvp and treated by QGIS as a QVariantMap.
> 
> This PR probably breaks the kvp key-value widget selection for JSON fields.
> 
> There is a related issue in GDAL which does not set the OFSTJSON subtype if the first occurrence of a JSON field is a string but fixing it does not resolve #51911.

Thank you for replying

**Comment by elpaso** [comment]
Let's put this on hold in favor of an upstream enhancement that will make it easier to fix the issue in QGIS without breaking existing workflows.

**Pull request closed without merging**
