### PR TITLE
Swap display_expression parameters order

### PR DESCRIPTION
**Pull request by DelazJ**
Because the commented expression below instead works
image

### CODE REVIEW

**Comment by Gustry** [comment]
According to the test, it depends on the number of arguments.
https://github.com/qgis/QGIS/blob/master/tests/src/core/testqgsexpression.cpp#L2146

If a single argument is provided, it's a feature.
If two arguments, first it's the layer and then the feature.

It's the same for `is_selected` https://github.com/qgis/QGIS/blob/master/resources/function_help/json/is_selected and `maptip` https://github.com/qgis/QGIS/blob/master/resources/function_help/json/maptip

**Comment by DelazJ** [comment]
So only the example is wrong? I should keep the parameters order.
Having to switch parameters order depending on their number looks confusing, that said.

**Comment by Gustry** [comment]
> Having to switch parameters order depending on their number looks confusing, that said.

I agree now. I took example on the `is_selected` expression.
We could add the logic to manage both order in each expression.

**Comment by nyalldawson** [comment]
The is_selected help was recently updated to fix a similar situation. I suggest modelling the help for display_expression on the new is_selected help format.

**Comment by DelazJ** [comment]
I did something, and it renders as below (feeback welcome as i'm not quite comfortable wit this function)
image

**Comment by nyalldawson** [comment]
Looks good to me! @gustry?

**Comment by Gustry** [comment]
Yes, LGTM, thanks @DelazJ !

**Comment by DelazJ** [comment]
Great; maptip is now also aligned with them

**Pull request merged**
