### PR TITLE
Fix user selector icon size #53548

### LINKED ISSUE #53548: Changing user profile icon size does not work
### What is the bug or the crash?

Changing icon size in Settings does not update size upon restarting QGIS, in the user profile selector dialog

### Steps to reproduce the issue

In Settings --> Options --> User profiles:
1. change the startup profile to "Let user choose profile at start up"
2. Modify the "Icon size"
3. Restart QGIS
4. You are prompted to select the user profile to use. Look at the icon size; whatever size you selected in point 2, it seems to render the same (i.e; redo the process selecting another size and you should get the same size)

### Versions

3.31 on debian bullseye (sorry I'm not on the machine to report the other properties)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fixes #53548

### CODE REVIEW

**Comment by DelazJ** [comment]
@YoannQDQ should we not move to the new QgsSettingsTreeNode?

**Comment by YoannQDQ** [comment]
I'm not sure. Those are special settings in the sense they aren't linked to any specific profile, and are sorted in the profiles.ini file at the profiles root.

**Review by nyalldawson — APPROVED** [review]

**Comment by DelazJ** [comment]
If these are two different types of settings then I guess we'll have to live with two different lists (and structure). And I don't feel that the GUI makes it clear enough. Reading the checkbox below I simply understood that there is a new structure for showing the settings and I should expect that not all are there yet. It does not imply it is another list, with specific scope. Probably some clarification/rewording is needed...?
image

**Comment by DelazJ** [comment]
Well, I played a bit with the checkbox and afaics the QGIS3.ini file is the same except the `settings\use-new-widget` being true or false.
And now I reread your message, I see that you were referring to profile.ini file, which contains "User Pofile" tab settings but the `selection/iconSize`. This one is in QGIS3.ini but not in the new tree structure in Advanced tab (afaics) and my initial comment referred to it.

**Comment by nyalldawson** [comment]
I think this one is an expectional case -- the settings used here aren't stored in any profile and HAVE to be treated differently to other settings.

**Pull request merged**
