### PR TITLE
Store cached layer render results based on whether each individual job finished, not whether the whole map render finished

### PR DESCRIPTION
**Pull request by nyalldawson**
This means that we will store cached results of layers which are faster to render and had already completed while a slower layer
was still rendering and then the map render job was canceled.

In this case we've already got a nice complete render of some layers ready for caching, so it's wasteful to discard these results and
then redraw from scratch next time.

Further boosts fluidity of map canvas renders

### CODE REVIEW

**Comment by nyalldawson** [comment]
Not for merge yet -- there's some outstanding issues introduced here!

**Comment by nyalldawson** [comment]
> Not for merge yet -- there's some outstanding issues introduced here!

Ok, all fixed and ready for merge!

**Comment by nyalldawson** [comment]
@PeterPetrik ok for you?

**Comment by nirvn** [comment]
@nyalldawson , working well here, it does make a nice subtle difference.

**Comment by PeterPetrik** [comment]
this also adds the smarter maps redraws to PointClouds!

**Review by PeterPetrik — APPROVED** [review]
Code looks good, my only question is if we want to keep the deprecated QgsMapRendererCache API at all or remove it... 

also there will be some conflicts with https://github.com/qgis/QGIS/pull/41228 for sure

**Comment by nyalldawson** [comment]
(skipping the travis run on this one -- it had already passed that before the last couple of cosmetic commits were added)

**Comment by nyalldawson** [comment]
> deprecated QgsMapRendererCache API at all or remove it...

Well - we can't remove it yet... we've gotta wait till 4.0 rolls around.

**Pull request merged**
