### PR TITLE
Adds better Layer panel indicator for noCRS

### PR DESCRIPTION
**Pull request by SrNetoChan**
## Description

Adds a new icon for the NoCRS Layer indicator in the layers panel as requested by @nyalldawson  in #32140.

It intends to be a cleaner version of the one used now. This is how it looks:

image

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by nirvn** [comment]
Can you provide a before vs after shot?

**Comment by SrNetoChan** [comment]
@nirv

Before on the bottom, after on the top

image

looking at the icons in more detail.

Before

image

After

image

This icons are shown at a very small size, which makes it hard to create clear images. I wanted to keep the CRS icon reference, but I am not usre it's intuitive enough.

**Comment by nirvn** [comment]
The question mark is pretty hard to decipher in-place. Could you try to make it bigger?

**Comment by SrNetoChan** [comment]
I made it a bit bigger, but I am not sure you notice much diference.

**Comment by SrNetoChan** [comment]
image

**Comment by roya0045** [comment]
Could you make the outline of the CRS symbol more apparent?
 In your initial choices I felt the outline was too apparent and was strange with the ?, but having a third shade of grey might help make the outline of the underlying symbol clearer.

**Comment by SrNetoChan** [comment]
@roya0045 I am trying to keep the same color "pallete" as the other indicators, which only have dark gray and soft gray.. with this icon size, I am thinking if I shouldn't simply fill the CRS symbol with the soft gray. Besides, the question mark kinda overlaps the the CRS outline. Here's a zoomed version:

image

**Comment by roya0045** [comment]
What would it look as a small icon like if you inverted the two grays?

**Comment by SrNetoChan** [comment]
@roya0045 Does not work well

image

**Comment by roya0045** [comment]
Indeed, I think this is why the previous icon had more shades of grey. I feel like the issue is that one symbol is too simple and the other too complex, and using only two tones highlights one or the other.

**Comment by SrNetoChan** [comment]
The previous icon was designed by me, but for another context. Those shades won't be visible in such small icon size. 

@nirvn do we really need those boxes around the icons? I understand that the original idea was to make it opaque so its no confused with the background, but the icons get soo small...

**Comment by nyalldawson** [comment]
Merging as is for hard freeze - can be tweaked in follow up prs

**Pull request merged**
