### PR TITLE
[server] OGC WMS 1.3.0

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

The OGC certification tests for WMS 1.3.0 are currently failing (see http://test.qgis.org/ogc_cite/wms_130/2018_11_26_06_00/report.html) due to an issue in `schemaLocation` attribute within the WMS `GetCapabilities` document.

And actually, it seems that `http://www.qgis.org/wms` is at the origin of the problem. The address is not valid anymore (404 Not Found), so an exception is raised by the test environment.

@rduivenvoorde Do you have any information on this?

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
@pblottiere for what I know there is now, but also has never been a http://www.qgis.org/wms directory.
You should be redirected to httpS anyway.
Also I've never seen some schemadoc (xsd?) there.

I'm added a /wms to the webserver (note that you ARE being redirected) happy to place a schema there, but somebody has to provide some xsd then?

Is it possible that the testing environment became a little more strict (as in that it tries to check the schema's now while earleer it didn't?)?

**Comment by pblottiere** [comment]
Hi @rduivenvoorde,

Thanks for your response.

So, either the testing environment is little more strict as you suggested, or I missed something and it's not the root cause...

Anyway, I think that the URL should be removed from the `GetCapabilities` document considering that it has never existed.

@rldhont what do you think?

**Review by rldhont — APPROVED** [review]

**Review by sbrunner — APPROVED** [review]
Looks good event if I am also not an XML expert

**Comment by pblottiere** [comment]
We'll see tomorrow if OGC tests are green again...

**Pull request merged**
