### PR TITLE
Pdf with clickable links

### PR DESCRIPTION
**Pull request by domi4484**
Add an option in Layout's HTML frame to use QTextDocument to render HTML content. HTML links exported in PDF with QTextDocument are clickable in opposition as with WebKit.
But QTextDocument can render only a subset of HTML, so a new option was added.

Note: I think the optimal solution would be to replace WebKit with WebView but it is not possible at the moment to use it parallel to Qt 3D (https://github.com/qgis/QGIS/issues/49512#issuecomment-1221632895)

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
Honestly, from a user's point of view I'm not a fan of this approach. It adds a very confusing option with a lot of trade offs and we should definitely avoid this kind of UI 

Have you considered implementing this in a plugin instead?

**Comment by domi4484** [comment]
I agree that this solution is not elegant, I tried to implement this replacing WebKit wit WebEngine but doesn't seem to be doable in near future.
From the user point of view, some are really missing the possibility to click the link they exports in PDF documents. They would be happy to trade off some fancy HTML formatting with that.

No, I did not thought about a plugin yet. Is the functionality to add custom layout widget already there, or something must be built into qgis?

**Comment by nyalldawson** [comment]
> From the user point of view, some are really missing the possibility to click the link they exports in PDF documents.

Totally agree -- I've had to hack around this in the past with a gross approach using transparent qtextdocuments overlaid in the layout 😂

 
> No, I did not thought about a plugin yet. Is the functionality to add custom layout widget already there, or something must be built into qgis?

Yes -- it's possible. Check the QR code plugin for a nice clean example of how to do this. (Might be even simpler in this case because you could potentially subclass the existing label item in the plugin!)

A good longer term solution is definitely needed. I'd push for this to be implemented in qt itself though, eg with some means for us to manually create hyperlinked regions of a graphics item/scene which we could hook into...

**Comment by nirvn** [comment]
It would be nice to find an acceptable approach here to avoid the need for a plugin to merely get clickable hyperlinks in PDF exports. That said, the PR's introduction of an additional checkbox is definitively a UX we'd want to avoid as it is likely going to confuse the vast majority of users. 

What about this alternative approach: instead of offering an obscure checkbox for users, we actually do simple string search and pick best renderer (i.e. QTextDcoument or Webkit). Basically, if the string only has style-less <a>,<b>,<i>, we go for QTextDocument, otherwise we go for Webkit. 

It'd definitively be a huge win to get working hyperlinks out of the box, let's try to find a way :)

**Comment by nyalldawson** [comment]
> What about this alternative approach: instead of offering an obscure checkbox for users, we actually do simple string search and pick best renderer (i.e. QTextDcoument or Webkit). Basically, if the string only has style-less < a >,< b >,< i >, we go for QTextDocument, otherwise we go for Webkit.

That's honestly a nightmare for users -- they'll have nice hyperlinked outputs, until they go and change a little bit of their html and then all of a sudden all the hyperlinks will stop working for some unknown reason. Guaranteed to lead to user frustration and wasted time 😱

Here's an alternative idea:

We make ALL newly created labels use text document. Old ones (ie those created when resorting an old project) remain with webkit rendering. We add big warnings in the release notes that the behaviour of html enabled label items has changed, and a limited subset of html tags is now supported for newly created label items. Users who require full html support should use the dedicated HTML item instead.

**Comment by domi4484** [comment]
@nyalldawson @nirvn thanks for your suggestions!

> We make ALL newly created labels use text document. Old ones (ie those created when resorting an old project) remain with webkit rendering. We add big warnings in the release notes that the behaviour of html enabled label items has changed, and a limited subset of html tags is now supported for newly created label items. Users who require full html support should use the dedicated HTML item instead.

This approach sounds good, I'll change the PR this way.

> A good longer term solution is definitely needed. I'd push for this to be implemented in qt itself though, eg with some means for us to manually create hyperlinked regions of a graphics item/scene which we could hook into...

Longer term it would be good if we could use QWebEngine, as it should solve this problem. WebKit has already left some linux distributions and as I understood in Qt6 will disappear completely.

**Pull request closed without merging**
