### PR TITLE
[FEATURE] Paint effects for layers and symbol layers

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR adds a new framework for implementing paint effects, which modify the results of QPainter operations to apply visual effects such as drop shadows and blurs.

The initial implementation allows for effects to be applied to entire layers and individual symbol layers.

Included are a drop shadow, blur, inner glow, outer glow. A "stack" effect is also implemented which allows other paint effects to be combined in various ways.

You can see some early versions of this PR in action here:
https://www.youtube.com/watch?v=2cQ7rBGgoq0
https://www.youtube.com/watch?v=Kafn8W24XF0

### CODE REVIEW

**Comment by nyalldawson** [comment]
PS - sorry for the mega commit! The important changes are in QgsPaintEffect, QgsEffectStack, QgsPaintEffectRegistry,  and the renderering changes in QgsVectorLayerRenderer, QgsSymbolLayerV2.

**Comment by carolinux** [comment]
https://www.kickstarter.com/projects/41633306/a-christmas-gift-for-qgis-live-layer-effects-for-q relevant Kickstarter project

**Comment by nirvn** [comment]
I've tested Nyall's effect branch for nearly two weeks now, nothing bad to report. Effects are cool.

**Comment by mhugent** [comment]
Cool feature!
For large prints (A0, 600dpi), the images in the effects can get very big and consume much memory. Not a big problem, but maybe it is possible to draw the QPictures to image in several parts in such cases.

**Comment by nyalldawson** [comment]
@mhugent good point. That should probably be tackled seperately as there's many other potential uses for splitting up the rendering into tiles. For instance, vector layers with whole layer transparency are always rendered as images so they would also suffer from large memory requirements.

It's out of scope of this current work, but something to add to our TODO list!

**Comment by nyalldawson** [comment]
manually merged in 742f3233eed8170f7ba47e3eaadfdca24621c0a3

**Pull request closed without merging**
