### PR TITLE
Fix  Unresponsive "Add record" button in non-geometry record creation

### LINKED ISSUE #55092: Unresponsive "Add record" button in non-geometry layer editing
### What is the bug or the crash?

When editing a non-geometry layer (table-only) in QGIS, the "Add record" button in the main interface becomes unresponsive after accepting or canceling changes in the corresponding form. The button remains in a pressed state, preventing users from clicking it again to add a new record. To add a new element to the table, users have to cancel the editing process and re-activate it. Only then can the "Add record" button be clicked again. 

### Steps to reproduce the issue

- Create a new project in QGIS.
- Add a non-geometry layer (e.g., Temporal, Geopackage, Shapefile).
- Activate the editing mode for the layer.
- Click the "Add record" button in the interface.
- If the layer has attributes, accept or cancel the changes made in the form.
- Notice that the "Add record" button remains pushed and unclickable.
imagen

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

Versión de QGIS | 3.34.0-Prizren | Revisión del código de QGIS | ffbdd67881
-- | -- | -- | --
Versión Qt | 5.15.3
Versión de Python | 3.9.5
Versión de GDAL/OGR | 3.7.2
Versión de PROJ | 9.3.0
Versión del registro de base de datos EPSG | v10.094 (2023-08-08)
Versión de GEOS | 3.12.0-CAPI-1.18.0
Versión de SQLite | 3.41.1
Versión de PDAL | 2.5.5
Versión del cliente de PostgreSQL | 15.2
Versión de SpatiaLite | 5.1.0
Versión de QWT | 6.1.6
Versión de QScintilla2 | 2.13.4
Versión del SO | Windows 10 Version 2009
  |   |   |  
Complementos activos de Python
coordinate_capture | 0.2
DigitizingTools | 1.5.2
MemoryLayerSaver | 5.0.1
processing_fusion | 3.5
processing_saga_nextgen | 1.0.0
profiletool | 4.2.6
qad | 3.0.4
qgis_resource_sharing | 1.0.0
quick_map_services | 0.19.33
searchlayers | 3.0.14
SLD4raster | 1.0
Spanish_Inspire_Catastral_Downloader | 2.0
StreetView | 3.2
VectorBender | 0.2.1
wfsclient | 0.9.11
db_manager | 0.1.20
otbprovider | 2.12.99
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This issue was not present prior to at least QGIS version 3.30.1, as far as I know. The first version in which it appeared was 3.32.

### LINKED ISSUE #56152: Add a new record in a table enable the snapping tool
### What is the bug or the crash?

After adding a new record in a table, the snapping tool is enabled

### Steps to reproduce the issue

1. Insert a table layer (without geometry)
2. Activate the edit mode for the layer
3. Turn on pan navigation (to highlight the existing issue)
4. Click on "Add a new record"
5. Confirm or close the form
6. Observe that the snapping tool becomes active (the cursor persists as the pan tool, even though panning functionality is not enabled)

*(The snapping square displayed in the animation should be purple instead of white)*

snapping

### Versions

3.28.13

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benwirf**
Fix 'Add Record' action remains toggled/not enabled after accepting or cancelling the add feature dialog for a no geometry layer.

Fixes #55092
Fixes #56152

## Description

This PR fixes the reported bug and also fixes some undesirable UX/ UI behaviour in relation to the digitizing cursor when switching between non-spatial & spatial vector layers (all in edit mode) in the TOC.

- The cursor used when the Add Feature tool was active when adding records to a non-spatial layer was identical to the Pan cursor, but not responsive- potentially leading to confusion/ frustration. This PR replaces it with a generic Qt::ArrowCursor.
- When switching from a non-spatial table layer to a spatial vector layer with both in edit mode and the Add Feature tool active, the cursor would remain on the open hand cursor, making accurate digitizing more difficult. This PR also attempts to fix that behavior.

The two screencasts below show the current behavior.

Unresponsive Add Record action:

unresponsive_action

Incorrect digitizing cursor:

wrong_map_tool_cursor

The two screencast below show the improved behavior implemented by this PR.

Responsive Add Record action:

responsive_action

Set correct digitizing cursor:

set_correct_cursor

Screencasts below show fixes to snapping behavior when snapping is active/activated with add feature tool set via Add Record action.

fix_snap_on_add_record

fix_activate_snapping_with_add_record_tool

### CODE REVIEW

**Comment by benwirf** [comment]
I've converted this to a draft as I need to do a bit more work on this. I've discovered an issue with this approach, and more broadly, some other existing issues with map tools/ cursors when switching between spatial and non-spatial vector layers (all in edit mode) in the TOC. I will try to resolve these then update & re-open this PR.

**Comment by benwirf** [comment]
OK, should be ready for review. I'm happy with the fixes and behavior achieved here, though I'm not not sure if there's a better way to implement the proposed logic.

**Comment by benwirf** [comment]
Still testing & working on this. Will add some screencasts to the description when I get a chance.

**Comment by benwirf** [comment]
Hi @agiudiceandrea, thanks for alerting me to that! It is definitely part of the same related UI behavior which I think I can fix in this PR. I have a (mostly working) solution to that other (snapping) issue which I will try to finish off tomorrow, then hopefully update and re-open this PR.

**Comment by benwirf** [comment]
Branch is working locally, fixes the reported issues and seems stable. I'm hoping (though not sure) there are not any potential issues with this approach.

**Comment by agiudiceandrea** [comment]
@benwirf I suppose you need to rebase the branch.

**Comment by benwirf** [comment]
Hi @agiudiceandrea, I tried to rebase the branch but having some difficulty resolving a conflict in qgisapp.h (my command of git is a bit lacking!). I will try again after work tomorrow.

**Comment by agiudiceandrea** [comment]
Maybe it would be simpler to create a new branch from an up to date master and create a new PR.

**Comment by benwirf** [comment]
@agiudiceandrea, OK- sounds good, I will try that. Thanks for the advice.

**Comment by benwirf** [comment]
Closing and replacing with #56283.

**Pull request closed without merging**
