### PR TITLE
upgrade OWSLib to 0.11.2

### PR DESCRIPTION
**Pull request by tomkralidis**
This PR updates the OWSLib installation to 0.11.2.  Note that OWSLib 0.11.2 introduces the following additional dependencies:
- requests: is included this in the PR
- pyproj: is **not** included pyproj in this PR because the codepath that requires it is not utilizied in QGIS at all

### CODE REVIEW

**Comment by alexbruy** [comment]
It would be good to switch to system-wide libs in QGIS 3

**Comment by pcav** [comment]
Agreed, a long standing issue

**Comment by tomkralidis** [comment]
is master branch QGIS 3 bound at this point?

**Comment by alexbruy** [comment]
Current master will be a QGIS 3.0

**Comment by tomkralidis** [comment]
Ref: http://osgeo-org.1560.x6.nabble.com/MetaSearch-OWSLib-upgrade-td5278220.html.

**Pull request merged**
