### PR TITLE
[api][auth] Removed get prefix from all getters in auth manager

### PR DESCRIPTION
**Pull request by elpaso**
## Description
Removed `get` form `QgsAuthManager` getters.

### CODE REVIEW

**Review by dakcarto — APPROVED** [review]
Code changes look fine to me. The docstrings might need a bit more work after merging.

**Comment by elpaso** [comment]
@jef-n can we merge this too? It was just 30 minutes late ... it doesn't change bit in the logic, it's just a cosmetic API change to be more Qt-style.

**Comment by jef-n** [comment]
Are you saying it's a fix and not a feature?  In that case there's no need to ask. ;)

**Comment by elpaso** [comment]
Yeah, sure it's an API fix :) 
... and one less in the queue

**Pull request merged**
