### PR TITLE
Update TRANSLATORS

### PR DESCRIPTION
**Pull request by RucioTozzy**
Specify zh-Hans&zh-Hans to fit RFC 4646

### CODE REVIEW

**Comment by nyalldawson** [comment]
Who is qualified to review this one?

**Comment by nirvn** [comment]
In the options dialog, zh-Hant uses the flag proposed in this PR. If nothing else, the PR will harmonize our use of flags :)

**Comment by nyalldawson** [comment]
@nirvn so that's a yes?

**Comment by RucioTozzy** [comment]
@nirvn @nyalldawson 
Sorry, I made noob mistake. This File is created by scripts/tsstat.pl.
I've check scripts/tsstat.pl and tested.
If mark the line 115&119 in scripts/tsstat.pl, "qrc:/images/flags/zh-Hans.svg"&"qrc:/images/flags/zh-Hant.svg" could be specified.
Could you mod that file and merge to 3.4 ltr branch? 
Thank you for all your assistance.

**Comment by jef-n** [comment]
See also a6f261826a55522ab6b75122cb026fe2bda4b876

**Pull request merged**
