### PR TITLE
[FEATURE][API] KDBush spatial index

### PR DESCRIPTION
**Pull request by nyalldawson**
A very fast static spatial index for 2D points based on a flat KD-tree, using https://github.com/mourner/kdbush.hpp

Compared to QgsSpatialIndex, this index:
 - supports single point features only (no multipoints)
 - is static (features cannot be added or removed from the index after construction)
 - is much faster!
 - supports true "distance based" searches, i.e. return all points within a radius from a search point

### CODE REVIEW

**Comment by nyalldawson** [comment]
@wonder-sk can you take a look please?

**Comment by nirvn** [comment]
@nyalldawson , I'm curious, what's your end game for this?

**Comment by nyalldawson** [comment]
@nirvn 

That would be implementing a https://en.wikipedia.org/wiki/DBSCAN algorithm

**Comment by luipir** [comment]
@nyalldawson is this (another) case where to plan sub module dependency instead of copying the kdbush source tree?

**Comment by nyalldawson** [comment]
@luipir

In future I think so, yes

**Review by wonder-sk — APPROVED** [review]
Nice! The code looks good.

Do you have any comparison of the performance to QgsSpatialIndex?

- maybe one other difference to QgsSpatialIndex worth mentioning is that QgsSpatialIndexKDBush also keeps a hashtable id -> geometry
- the hashtable mIdToPoint could also use reserve() to avoid reallocations
- if we wanted to save some memory, mIdToPoint could be actually a mapping from fid to index in points/ids array (and it would be created after the initial sortKD() call)
- maybe we don't need mIdToPoint at all if intersect() and within() would return a set of QPair<QgsFeatureId, QgsPointXY> ?
- shall we remove the empty qgsspatialindexkdbush_p.cpp file?

**Comment by nyalldawson** [comment]
> maybe one other difference to QgsSpatialIndex worth mentioning is that QgsSpatialIndexKDBush also keeps a hashtable id -> geometry

ok, will do. (FYI the whole motivating factor here is to avoid the extra feature requests which would be required otherwise)

> if we wanted to save some memory, mIdToPoint could be actually a mapping from fid to index in points/ids array (and it would be created after the initial sortKD() call)
> maybe we don't need mIdToPoint at all if intersect() and within() would return a set of QPair<QgsFeatureId, QgsPointXY> ?

Yes, very true. Should be some performance benefit from this too. I was ideally trying to avoid modifying the external kdbush code at all (all I've done here is change private -> protected), but there's quite a valid justification for tweaking the code here.

> shall we remove the empty qgsspatialindexkdbush_p.cpp file?

Probably should :yum:

**Comment by nyalldawson** [comment]
@wonder-sk ok, done. mIdToPoint is gone!

**Comment by wonder-sk** [comment]
Cool! I thought that the kdbush implementation would stay untouched (with separate points/ids arrays) but this is probably even better - just one array to deal with :-)

**Comment by nyalldawson** [comment]
@wonder-sk 

Requested benchmarks:

##Benchmark intersect

### 50k features:

QgsSpatialIndex: 23 msecs per iteration
QgsSpatialIndexKDBush: 10 msecs per iteration

### 500k features:

QgsSpatialIndex: 273 msecs per iteration
QgsSpatialIndexKDBush: 103 msecs per iteration

### 5 million features

QgsSpatialIndex: 4.4 secs per iteration
QgsSpatialIndexKDBush: 1.1 secs per iteration

### 50 million features

QgsSpatialIndex: > 300  secs (timed out)
QgsSpatialIndexKDBush: 1.6 secs per iteration

## Index construction 

### 50k features from memory layer:

QgsSpatialIndex: iter only: 19 ms, bulk load: 45 ms
QgsSpatialIndexKDBush: iter only: 10 ms, bulk load: 12 ms

### 500k features from memory layer:
QgsSpatialIndex:  iter only: 106 ms, bulk load: 440 ms
QgsSpatialIndexKDBush: iter only: 80 ms, bulk load: 122 ms

### 5 million features from memory layer:
QgsSpatialIndex:  iter only: 1009 ms, bulk load: 12481 ms
QgsSpatialIndexKDBush: iter only: 851 ms, bulk load: 1344 ms

### 50 million features from memory layer:
QgsSpatialIndex:  ---- (timed out)
QgsSpatialIndexKDBush: iter only: 8314 ms, bulk load: 15647 ms

**Comment by nyalldawson** [comment]
Unrelated test failure

**Comment by wonder-sk** [comment]
Thanks for the benchmark! Interesting that bulk loading actually takes longer for both indices - I would have thought the opposite...

**Comment by nyalldawson** [comment]
Sorry, it wasn't very clear. Iter only is the cost of just iterating over the layer alone, so the index should subtract the iteration cost.

**Pull request merged**
