### PR TITLE
fix clipping for geocentric projections

### PR DESCRIPTION
**Pull request by nyalldawson**
Supersedes https://github.com/qgis/QGIS/pull/44941 -- optimises the changes to clipping logic to avoid the considerable overhead of using QgsPoint/QgsPointSequence objects by replacing those with raw coordinate arrays instead.

### CODE REVIEW

**Comment by benoitdm-oslandia** [comment]
> I've profiled the 2d symbol rendering code and geometry code heavily and any conversion of geometries to point sequences is very slow. Using QgsPoint is also considerably slower vs just raw doubles.

Ok! Thanks for the refactor!

**Comment by benoitdm-oslandia** [comment]
@nyalldawson 

I think there are some regressions (but not linked to yours modification). By the time I created this PR, I have made a sphere in epsg:4978 and I was able to see it in 3D when qgis projection was set to 4978. But now, in the same configuration I see a flatten sphere:

image

By the way, I can not see the result I was expecting to see in epsg:3857. I obtain:

image

The 2D map seems correct but now there is an issue with 3D view... this is endless :)

So for the 2D part: I am agree to merge.

Thanks.

**Comment by nyalldawson** [comment]
@benoitdm-oslandia thanks for the feedback!

Would you be able to add a unit test for the rendering component of this change? I'm concerned that it will regress without one (like you've just discovered!)

Btw did you set your 3d layer renderer to the simple lines mode?

**Comment by benoitdm-oslandia** [comment]
> Btw did you set your 3d layer renderer to the simple lines mode?

Raahhh indeed I forgot this "step"!

**Comment by nyalldawson** [comment]
I think we should make that setting the default for linestringz layers. What do you think @wonder-sk ?

**Comment by benoitdm-oslandia** [comment]
@nyalldawson This is ok, meaning, in 4978 I see the sphere and in 3857 I have the "strange" results (ie flatten sphere) as before (but even worse):

earth_size_4978_sphere_in_3D

I will look for doing a test for the 2D view in 4978 and 3857.

**Comment by nyalldawson** [comment]
I'll merge this and then you can open a new pr!

**Comment by wonder-sk** [comment]
> I think we should make that setting the default for linestringz layers. 

@nyalldawson I don't have a strong preference. It seems to me that relatively often people end up having linestringz layers without even knowing that there's Z dimension as well (e.g. all Z coords being zero), and the data may get badly rendered in 3D in such case (probably Z-fighting with terrain)... So my vote is 0 :-)

**Comment by nyalldawson** [comment]
@wonder-sk 

> . It seems to me that relatively often people end up having linestringz layers without even knowing that there's Z dimension as well (e.g. all Z coords being zero),

I've seen that too. We could potentially "sniff" the first feature to check if all z values are zero in this case. But, on the other hand,... is there really any issue with a layer defaulting to 3d symbol on, render as simple lines if all z values are 0? The end result will be basically identical to what you'd currently get with the lines rendered on the flat plane/terrain.

**Comment by wonder-sk** [comment]
> I've seen that too. We could potentially "sniff" the first feature to check if all z values are zero in this case.

Yeah that could help...

> But, on the other hand,... is there really any issue with a layer defaulting to 3d symbol on, render as simple lines if all z values are 0? The end result will be basically identical to what you'd currently get with the lines rendered on the flat plane/terrain.

Hmm not really - if 3d symbol is not on, the layer will get rendered as a part of the terrain texture and it may use all the bells and whistles of 2d rendering, while with 3d symbol it's just a single color and constant width. I guess the other issue is that user may not even realize that 3d symbol got turned on automatically, wondering why the 3d appearance is not matching what was set for the 2d renderer.

I agree though that for "real" linestringZ data it may be a nice thing to do by default - fewer clicks to set up the 3D view!

**Comment by nyalldawson** [comment]
@wonder-sk 
> Hmm not really - if 3d symbol is not on, the layer will get rendered as a part of the terrain texture and it may use all the bells and whistles of 2d rendering, while with 3d symbol it's just a single color and constant width. I guess the other issue is that user may not even realize that 3d symbol got turned on automatically, wondering why the 3d appearance is not matching what was set for the 2d renderer.

What we really need is a data defined color option for the simple lines, with an option for "follow 2d colors". That should solve this reservations... (Admittedly it doesn't solve the situation of a user using thematic dotted/dashed lines, but I think with colors alone we'd be covering 99% of cases sufficiently well)

**Comment by benoitdm-oslandia** [comment]
@wonder-sk 

> By the way, rendering of the whole earth in 3D view may bring a whole bunch of new challenges. Mainly around the fact that GPUs normally use single-precision floats (doubles are often not supported at all by hardware). Right now we generally assume that a 3D scene is "small", so the float precision is good enough (as long as the scene is less than ~100km wide).

This is just an example to show by using geocentric coordinates, we are near the single precision float limits. Across all our client projects, none is that big but some of them may be 100km wide which may hurt a bit with the current 3d developments.

**Pull request merged**
