### PR TITLE
Select mesh elements by expression UI

### PR DESCRIPTION
**Pull request by vcloarec**
Following #44786, this PR implements:
 - a contextual expression function "$face_area" that returns the area of a mesh face_area
 - a user interface to select mesh element during mesh editing.
 
This user interface is inspired by the vector layer select feature by expression dialog.
 In the mesh element selection by expression dialog, we have:
 - the same expression builder
 - almost the same buttons above the widget : "Zoom to selected" "Select/Add to current selection/Remove from current selection" and "close". 
 - on the top of the widget, a combo box that allows the user to choose the mesh element type to select: vertex or face.

I am not sure about the position of the combo box to choose the mesh element type, but I don't have other idea for now...
 
 Other point, the preview widget: for now, this widget is not adapted to mesh layer, so I am thinking to add a method to `QgsExpressionBuilderWidget` to hide the expression preview widget.

selectByExpression

### CODE REVIEW

**Comment by vcloarec** [comment]
> is this different from showing line functions while viewing a polygon layer? The function will return NULL and that's fair.

Not exactly. With mesh layer, we have faces AND vertices. With vector layers, we have polygons OR lines OR points. So, if the user uses the wrong function, it is clearly an error. It is more ambiguous with mesh layer. By the way, not the subject here, but it could be an improvement to display only functions related to the geometry type of the vector layer, no?

> Up to the users to read the function help and know what they are doing.

With this combo box (or anything else to choose between vertices/faces), we force the user to choose, making the user think about this choice. I think if the UI helps the user not make some mistakes and understand the logic, it improves the user experience.

> Maybe unavailable now, but can't we imagine that people select faces based on vertices properties?

Sure! But this will be done, not through a current vertex function (like $vertex_z), but with a "general" function with a "current face " function, for example:
z(point_n($face_as_geometry,2)) will return the Z value of the third vertex of the current face.

Further more, selections of faces and vertices are linked, that is: a face are selected only if all its vertices are selected, and, if a face is selected, that leads to all its vertices selected.

**Comment by nirvn** [comment]
My 2 cents: I wish/hope this duplication of a select by expression dialog could be avoided altogether here. The constant flow of mesh improvements and new features implemented in QGIS is *super* exciting, however its UI additions have had the tendency to not integrate super well with the rest of QGIS (whether it be the looks or the functionality). I think we'd win to try and better integrate mesh UI into pre-existing QGIS UI.

One way to implement this functionality into the pre-existing dialog here would be to get rid of the awkward 'element type to select' combo box in favor of showing/hiding relevant actions in the [ select XXX |V]  drop-down push button. When opening the dialog against the selected layer, it'd check whether the layer is mesh or vector and show appropriate actions.

As for face vs vertex, I'd just offer both actions in the drop down push button instead of a combo box. 

Understanding that it might involve adding a layer of complexity to the dialog code, IMHO it still out-weights the cost of dialog duplication.

That would also allow you to eventually make use other select tools (e.g. invert selection, de-select all would be useful I'm sure), which would feel very 'natural' to users.

**Comment by vcloarec** [comment]
> however its UI additions have had the tendency to not integrate super well with the rest of QGIS (whether it be the looks or the functionality). I think we'd win to try and better integrate mesh UI into pre-existing QGIS UI.

Sorry for that, I can ensure you that all efforts are made to integrate as much as possible mesh UI into prexisting QGIS UI. But as mesh are not vector either raster, meshes have to have their own UI answering needs of mesh users. Maybe you can point to cases to discuss about? Maybe it could be better to open issues about?

About the current UI for selection by expression, I think good words are not "Select faces" or "Select vertice", but "Select **by** faces" or "Select **by** vertices". My bad here. Indeed, when you make a selection with mesh layer, you have together faces and vertices selected. An action of selecting only vertices can leads to also select faces, and selecting faces always leads to also select vertices.

So, I think expressing this idea in the UI, in the same way as I wrote in the previous post, will help the user to think about and understand this concept. That is done by forcing the user to choose the way to select (**by** faces or **by** vertices) before using the related expression functions.

That's why I would like to keep a way to make this choice in this widget, and no matter if this is a combo box or other stuff. 
Further more, I don't like a lot the idea to have both face and vertices in the proposed actions of the drop-down push button, we would have 6 or 8 possible actions, IMHO too much.

The difficulties here is to integrate the stuff to make the choice in this "Selection By Expression' widget, that is a widget quasi similar at the one for vector layer (in a effort to have widget as similar as possible with pre-existing QGIS UI).

About sharing code with vector layer, if it the UI file, maybe it is possible, but it seems you talked about the implementation of the widget, and I think it is a bad idea for the following reasons:
- indeed it could be a mess,
- in the application, the selections related to mesh and vector layer doesn't have the same mechanism, and mixing the two mechanisms in the same widget could be quite confusing for the user of the GUI API
- the vector layer dialog is in the GUI API, the mesh layer is in the APP API for now. As, I think, mesh layer selection leak of maturity (because very new) and could change a lot, letting it in the APP API is quite reasonable to avoid breaking the GUI API later
- the duplicate code with two different dialogs is not big

However, it could be a good idea to add support of mesh layer by QgsExpressionBuilder widget, but it could not be so simple, and why not later.

**Comment by PeterPetrik** [comment]
I agree that the user should have same or at least as similar as possible experience when working with any type of layer in QGIS. On the same time I understand that the mesh layer users have very different workflows than other users. We had this problem with widgets duplication many times (e.g. with mesh calculator, contrours color shader). Usually with meshes you need a bunch of extra options. The best option I think is to:
 - have separate root widget for vector & mesh layers
 - where possible, extract the widget parts (components) to separate reusable widgets (for example see the raster styling and the mesh contours styling)
 - reuse the same component in both mesh and vector (raster) dialogs. 
 - if possible and reasonable have some kind of "base" abstract widget base class that can be extensible for both layer types (where components are not efficient)
 
For this particular widget:
 - I think the selector to select by face or vertex should be part of bottom menu, between "Zoom" button and "Select" combobox.
 - Looking at the code, it looks like it is the case (?), e.g QgsExpressionBuilderWidget is used etc, but the preview should be hidden. I suggest to add option to the builderwidget to hide preview.

**Comment by vcloarec** [comment]
in the last commit:
- "Select by Vertices"/"Select by Faces" combo box at the bottom
- Remove the mention of element type in the drop-down push button
- hide the preview widget in the expression builder

selectByExpression_widget

**Review by PeterPetrik — DISMISSED** [review]

**Comment by DelazJ** [comment]
> however its UI additions have had the tendency to not integrate super well with the rest of QGIS (whether it be the looks or the functionality). I think we'd win to try and better integrate mesh UI into pre-existing QGIS UI.

I can't speak code wise but if I may, I think parts of the [UI fixes](https://github.com/qgis/QGIS/pulls?q=is%3Apr+author%3ADelazJ+is%3Aclosed+mesh+) I provided to mesh are motivated by that feeling. That said, I thought I'd have found many "problematic issues" fixes among them, but... So maybe my feeling is stronger than the reality. Or your efforts for coherence are paying. Thanks.
_Generally speaking, I unfortunately find that mesh PRs do not seem to attract many of the active QGIS devs_ \me running away

Moving the "select by ..." widget makes indeed the GUI look more like what users are used to. Thanks.
But I'm still unconvinced by the functions filtering it triggers. IMHO This is inconsistent with the user experience of functions list (i.e., provide all the functions that can be used in this context, context being selection, edition, layout, symbology...). Not only you always get the same list, but it helps you discover/test various combinations.
Out of curiosity, what is the issue we want to avoid by not showing the three functions all the time? What happens if someone writes `$face_area >50` while "select by vertices" is active/switched on? Also, is the "Meshes" group hidden when the item that triggers the expression-based dialog is a vector/raster/layout element? And if not, which mesh functions are then exposed? I'm asking because I'm afraid we are "curbing" users possibilities with expressions.

**Comment by vcloarec** [comment]
> what is the issue we want to avoid by not showing the three functions all the time?

pollute the list with unusable functions


> What happens if someone writes `$face_area >50` while "select by vertices" is active/switched on?

$`face_area` will return always NULL if we have "Select by vertices" or with another expression context


> Also, is the "Meshes" group hidden when the item that triggers the expression-based dialog is a vector/raster/layout element?

yes, for now because there is no yet general function for mesh layer, only function related to the current element.

**Comment by PeterPetrik** [comment]
I would like to propose this change

1. extent button in the main toolbar to have context switcher (similar to for example measure tool or other) to switch between "select by faces/select by vertices" context
2. remove context selector from the "Select Mesh Elements by Selection" dialog
3. in the expression list in the dialog, only show relevant functions for the given context


select_mesh

how does this sounds to you @DelazJ @nirvn @vcloarec  ?

**Comment by vcloarec** [comment]
@PeterPetrik  IMHO, I find this solution less user friendly, and that will add some stuff in the main tool bar.

About filtering the function depending of vertices/faces, if it is the only way to have this PR merged, I am agree to not filter the function if @DelazJ is not convinced by my last post, but I am really not convinced why we don't have too...

**Comment by DelazJ** [comment]
A late reply but @vcloarec for what it's worth, I'm OK with your GUI and explanation. No stopper (if ever) from me  to merge.

**Comment by saberraz** [comment]
@vcloarec I vote to go with https://github.com/qgis/QGIS/pull/44835#issuecomment-912398404

**Comment by PeterPetrik** [comment]
Let me merge this functionality to get into 3.22. I will try to do proper testing and evaluation or UX of all-new mesh layer frame editing tools in the following weeks and propose some changes to consolidate the tools more with the existing tools (in vector layer, etc.)

**Review by PeterPetrik — APPROVED** [review]

**Pull request merged**
