### PR TITLE
fix ridiculous number of idle connections on PostgreSQL

### LINKED ISSUE #53621: QGIS 3.32 reserves ridiculous number of idle connections on PostgreSQL 11.12
### What is the bug or the crash?

There seems to be an issue with QGIS 3.32 when connecting to large projects that have data stored on PostgresSQL (tested version 11.12). QGIS reserves a very large number of idle connections, making it impossible to load even an entire project, as if it made a separate connection for each individual layer instead of loading them all in one go.

### Steps to reproduce the issue

When trying to load projects that work just fine in 3.30 or older versions of QGIS, in larger projects a connection error will appear saying that there are too many connections. The default for PostgreSQL seems to be 100. We've never reached 100 before.

image

Below you can see the connection activity chart. It begins with a large program loaded in 3.32, then a smaller project loaded in 3.32, another large project in 3.32, a period of pause while 3.28 loaded and then a tiny imperceptible bump in connections when the largest project was loaded in 3.28.

problems

### Versions

QGIS version
3.32.0-Lima
QGIS code revision
311a8cb8a6
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
azimuth_distance_measurement
0.4
contour
2.0.12
coordinates_converter
1.0
deactivate_active_labels
0.5
FreehandRasterGeoreferencer
0.8.3
GeometryShapes
0.7
GroupPointsWithinDistance
0.0.2
HCMGIS
23.2.1
inspireatomclient
0.8.1
joinmultiplelines
Version 0.4.1
kmltools
3.1.29
latlontools
3.6.10
pickLayer
3.9.4.post0
postgisQueryBuilder
2.0.1
profiletool
4.2.6
qfieldsync
v4.5.0
Qgis2threejs
2.7.1
qgis_hats
1.8
SelectWithin
0.4
StreetView
3.2
turbo_volume
0.1
volume_calculation_tool
0.4
wnt
1.3.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MorriganR**
fix #53621

ping @vcloarec

### CODE REVIEW

**Review by vcloarec — CHANGES_REQUESTED** [review]
Thanks for this. The approach is quite similar to what I was thinking to fix the issue, but not exactly.

Not sure the connexion will be thread safe. Using a mutex like this will not make the connection itself thread safe, as the connection could be shared between thread. 

After the provider creation, it could be preferable to create the provider connection in the main thread to avoid any problem. The connection could be created in the private method  `connectionRO(`) if `mConnectionRO` is `nullptr`, so created in the main thread.

But in that case, we could loose a bit of performance by reconnecting the database in the main thread.

**Comment by MorriganR** [comment]
Thanks for the comment!
> Thanks for this. The approach is quite similar to what I was thinking to fix the issue, but not exactly.
> 
> Not sure the connexion will be thread safe. Using a mutex like this will not make the connection itself thread safe, as the connection could be shared between thread. 

You're right, the original limitation was introduced by commit - https://github.com/qgis/QGIS/commit/670ded3d0622811f8e0ba50b3f3fd5e783742044 and related to this problem
https://issues.qgis.org/issues/13141

It was then reinforced by a commit - https://github.com/qgis/QGIS/commit/0f2643174db9d75456c68653b9f8859d627bc933

Both commits prevent non-main threads from monopolizing the shared connection, which can cause the main thread to freeze. Therefore, indeed, the restriction:
https://github.com/qgis/QGIS/blob/65d40ee0ce59e761ee2de366ca9a963f35adfcfd/src/providers/postgres/qgspostgresconn.cpp#L170-L175 cannot be removed.

But, in my opinion, this does not prevent you from creating a connection in a non-main thread and adding it to `QMap<QString, QgsPostgresConn *> sConnectionsRO` and binding it to `mConnectionRO` in the provider.

> After the provider creation, it could be preferable to create the provider connection in the main thread to avoid any problem. The connection could be created in the private method `connectionRO(`) if `mConnectionRO` is `nullptr`, so created in the main thread.

Although the approach proposed by you looks safer! but both looks like hack :)

> But in that case, we could loose a bit of performance by reconnecting the database in the main thread.

I do not think that this will lead to a significant loss of productivity, because in reality one connection will be created for each group of `connInfo`.

**Comment by MorriganR** [comment]
PR is ready...
unfortunately it finally kills - mUri.param( "session_role" )

**Comment by vcloarec** [comment]
@MorriganR , here another fix for this issue that should make the job: #53812

**Comment by nyalldawson** [comment]
Is this made redundant by https://github.com/qgis/QGIS/pull/53812 ?

**Pull request closed without merging**
