### PR TITLE
improve import handling

### PR DESCRIPTION
**Pull request by mach0**
first small part to get rid of import *

### CODE REVIEW

**Comment by jef-n** [comment]
why do we need to get rid of star imports for qgis.core?  Are there plans to split our libraries?

**Comment by mach0** [comment]
AFAIK to better handle travis errors and make the transition Qt4/5 Python2/3 clearer.
Beside the fact that I learned that "import *" is very bad python practice

https://pythonconquerstheuniverse.wordpress.com/2011/03/28/why-import-star-is-a-bad-idea/
@m-kuhn can surely say more here :)

**Comment by m-kuhn** [comment]
That was probably more an effect of a generic job description than on purpose.

At least I don't have any plans to split the libs, not sure about @mach0 .

**Comment by mach0** [comment]
no plans on my side to split any libs :)

**Comment by m-kuhn** [comment]
Thanks Werner

**Pull request merged**
