### PR TITLE
fix crash when opening layer properties

### PR DESCRIPTION
**Pull request by 3nids**
avoid adding an empty page to layer properties

### CODE REVIEW

**Comment by 3nids** [comment]
I had this crash with memory layers coming out of processing

**Comment by 3nids** [comment]
This doesn't seem correct as I have plugin pages floating on top of other pages now.

**Comment by rduivenvoorde** [comment]
@3nids I tried to force a crash, but I'm (not yet) able to. 

The 'last used' open tab is 'remembered' by QGIS. Is it possible that you had a 'tab' open from a layer (type?) which has more tabs then the memory layer? Could this be the problem? Trying to open a tab(type) which is not there?

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@3nids 

> This doesn't seem a proper fix as I have plugin pages floating on top of other pages now.

I suspect that's a bug in the plugin(s), which are creating the page using the dialog as a parent and then not returning this page.

**Pull request merged**
