### PR TITLE
Fix geos_c.h not found

### PR DESCRIPTION
**Pull request by dmarteau**
src/providers/geonode include core headers that
    depends on src/core//geometry/qgsgeometry.h.

    The latest include 'geos_c.h'; if geos headers are not installed
    in standard location, the compilation failed with: 'geos_c.h not
    found'

### CODE REVIEW

**Comment by Gustry** [comment]
Duplicate of https://github.com/qgis/QGIS/pull/5192

**Comment by rldhont** [comment]
@Gustry @dmarteau which one is the best implementation ?

**Comment by Gustry** [comment]
I don't know. We are working on MacOS but we didn't meet this problem while we were coding the geonode client.

**Comment by telwertowski** [comment]
Since geos_c.h is a system include, the CMake SYSTEM option should be used. This is consistent with other providers and plugins.

**Comment by dmarteau** [comment]
@Gustry I compile with macport and  geos_c.h is located in /opt/local/include. Otherwise CMake detect  the geos_config package and all variables are setted correctly.

**Comment by m-kuhn** [comment]
#5192 won ;)
Thanks everyone

**Pull request closed without merging**
