### PR TITLE
transform only one vertex

### PR DESCRIPTION
**Pull request by vcloarec**
This PR is an extension of transform mesh vertices by expression (PR #44873)
A new mode allows the user to import the coordinates of one vertex when this vertex is selected.

Clicking on the tool button on the top right allows to enter this mode and if only one vertex is selected, fill the expression line edit with the coordinates value.
Once in this mode, each time the user will choose only one vertex, the coordinates will be sent to the expression line edit, allowing the user to adjust the coordinates.

displayedVertex

### CODE REVIEW

**Comment by m-kuhn** [comment]
Looks nice
what is the reason to be able to disable this mode, isn't that something that we'll always want to be enabled?

**Comment by vcloarec** [comment]
If the mode is disable, we can keep the expression. This mode do not keep the expression if the selection change.

**Comment by nyalldawson** [comment]
I'm a little concerned that this further expands the mesh/other layer types divide. From my interpretation this is intended to allow users to enter a specific X/y/z for a mesh vertex. But that same requirement could be satisfied via the advanced digitising dock (if z is added there), and then we'd get the benefit of a consistent approach for vector/mesh. @vcloarec thoughts?

**Comment by vcloarec** [comment]
good point @nyalldawson 
I also think it could be satisfied by the advanced digitizing and not have the Z entry will not block. Indeed, with mesh we can enter Z in a dedicated input widget.
Advanced digitizing could work with mesh editing, even if, I think there are some issue to fix. The main problem is the way the vertex mesh are moved, by press -> drag -> release. Maybe it was a bad idea as it is not like for vertex tool of vector layers. I have to dig a bit to see if we could have the same behavior. Maybe I had some reasons...

Anyway, I think it is  compatible with this PR. If we have two different ways to modify a vertex value that have not exactly the same workflow. IMHO, I find this one easier than the advanced digitizing one, and this one work with geographic coordinate. What do you think about?

**Comment by PeterPetrik** [comment]
So you have only added that one button to this existing widget?

**Comment by vcloarec** [comment]
> So you have only added that one button to this existing widget?

and handle the importation of the coordinates when needed (after activate the option or when selection changes).

**Comment by vcloarec** [comment]
@nyalldawson good news, I start to modify the mesh edit map tool to have same behavior that vector layer vertex tool (no press->drag->release to move element, but click ->move -> click,) so we could have the same requirement via the advanced digitizing dock, but with not the same workflow.
I hope this edit map tool modification could be considered as a fix, to be integrated after the freeze time.

**Comment by PeterPetrik** [comment]
Let me merge this functionality to get into 3.22. I will try to do proper testing and evaluation or UX of all-new mesh layer frame editing tools in the following weeks and propose some changes to consolidate the tools more with the existing tools (in vector layer, etc.)

**Review by PeterPetrik — APPROVED** [review]

**Comment by DelazJ** [comment]
Question: should we generate an issue report in docs for this one or skip it considering that upcoming changes may review the implementation? The idea is to have enough reports to help writers understand the bigger puzzle and not miss any important thing but not generate reports that they would be confused with (because things have changed a lot in the meantime).

**Comment by PeterPetrik** [comment]
as for changelog, I would go for one bigger-picture entry with some description of the new functionality as whole. Maybe something for docs would be suffient for start too.

**Pull request merged**
