### PR TITLE
Accept 2d box extent when estimating metadata

### LINKED ISSUE #56541: 3.36 PostGIS layers have no spatial extent
### What is the bug or the crash?

Layers loaded from a PostgreSQL / PostGIS database have no spatial extent.
Extent in Information tab of layer is set to Null.
Zoom to layer functionality throw this warning :  
WARNING    result of extents query invalid: BOX(144881.046875 200921.21875,505398.1875 515061.03125)

The issue is 3.36 specific ; the same layers works in 3.32 and 3.28.
No issues with a Geopackage layer.

### Steps to reproduce the issue

Load a layer from a PostGIS database.

### Versions

QGIS version
3.36.0-Maidenhead
QGIS code revision
09951dc0
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
fms_cycles
0.1
sln_acquire
0.1
string_importer
0.1
db-style-manager
0.8
firstaid
3.1.0
HouseNumbering3
version 0.0.5
lizmap
4.2.2
pg_metadata
1.3.0
plugin_reloader
0.9.3
plume
1.1.1
processing_saga_nextgen
1.0.0
profiletool
4.2.6
qfieldsync
v4.7.1
Qgis2threejs
2.7.3
qgis2web
3.18.2
QGISSortAndNumber-master
1.0
quick_map_services
0.19.34
StyleLoadSave
1.0
ViewshedAnalysis
1.8
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

PostgreSQL 15.3
PostGIS 3.3 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

### PR DESCRIPTION
**Pull request by strk**
Fixes GH-56541

I tried the least change fix

### CODE REVIEW

**Comment by strk** [comment]
It's to be noted that also for PostGIS < 2.0.0 so the problem is not just with "estimated metadata"

**Review by benoitdm-oslandia — APPROVED** [review]
Simple and efficient ;)!

**Comment by strk** [comment]
What's the label to add to have this backported to all relevant branches ? We know at least 3.36 is affected.

**Comment by strk** [comment]
I did not test 3.4, did you @Komz0 ?

**Comment by Gustry** [comment]
The ticket (and others) were saying 3.36.X.

@strk Your message https://github.com/qgis/QGIS/issues/56541#issuecomment-2091089484 is quoting a commit in 3.36 if I'm not wrong.

**Comment by strk** [comment]
Ok, labels updated. I need a valid approval before this can be merged. @elpaso ?

**Review by rouault — APPROVED** [review]

**Comment by strk** [comment]
Thank you @rouault

**Pull request merged**
