### PR TITLE
[Postgresql Provider] Fix crash in discoverRelations() on invalid layer (fixes #31213)

### LINKED ISSUE #31213: crash in discover relations for postgresql layers
## User Feedback

clicked "discover relations" in relations tab of project properties

## Report Details

*Crash ID*: 73667ad2d480d253f0d002f41b7ef114a92d7222

*Stack Trace*
<pre>
QMutex::lock :
sourceSelectProviders :
QgsRelationManager::discoverRelations :
QgsDiscoverRelationsDlg::QgsDiscoverRelationsDlg :
QgsRelationManagerDialog::mBtnDiscoverRelations_clicked :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::projectProperties :
QgisApp::identifyMapTool :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
TranslateMessageEx :
TranslateMessage :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Review by nyalldawson — COMMENTED** [review]
Can you revert the world map changes?

**Comment by rouault** [comment]
> Can you revert the world map changes?

Sure... This is annoying: each time I start QGIS it modifies the file... Likely WAL, but I didn't check

**Comment by nyalldawson** [comment]
Yeah it's the wall/gpkg issue raising its head. Do you know if https://github.com/qgis/QGIS/pull/31401 would help with this?

**Comment by rouault** [comment]
> Do you know if #31401 would help with this?

Not by itself. GeoPackage will still be opened in WAL mode in the event there would be a writer elsewhere (already existing, or to come). We would rather need a "this file is immutable" flag to be able to safely disable WAL. I'd wish there would a SQLite mechanism that would offer WAL-like guarantees but without touching the file. Would be a bit messy to implement that in an external way to SQLite (either in GDAL or QGIS) and wouldn't be robust to other software using plain SQLite.

**Comment by nyalldawson** [comment]
What if another flag was added for an immutable state? Is there any missing bits elsewhere which would block this work?

**Comment by rouault** [comment]
> What if another flag was added for an immutable state?

That should work I think

**Comment by jef-n** [comment]
work around: `git update-index --assume-unchanged resources/data/world_map.gpkg`

**Pull request merged**
