### PR TITLE
Handling Python installations in custom prefixes for both 32bit and 64bit

### PR DESCRIPTION
**Pull request by jarl-dk**

### CODE REVIEW

**Comment by SebDieBln** [comment]
I would really like to see this PR merged, because I always have to enter the path to _python.lib_ manually when running CMake on Windows (with all dependencies coming from OSgeo4W).

See also my PR #2486 which I made before being pointed to this one.

**Comment by m-kuhn** [comment]
I've got no idea about the risks involved in merging this.
Can somebody elaborate on the pros and cons?

**Comment by nyalldawson** [comment]
@dakcarto @jef-n should we merge or close this? Not much point in leaving it open if there's no intention to merge.

**Comment by dakcarto** [comment]
@nyalldawson not sure. Seems many others by now would have had issues if this wasn't working right, i.e. not finding Python; and, the file has advanced considerably since this PR. This appears to affect those looking to target builds for non-64bit, which I'd guess is not very prevalent anymore.

@jarl-dk is this still needed?

+1 to close.

**Comment by nyalldawson** [comment]
@jef-n thoughts? close or merge?

**Pull request closed without merging**
