### PR TITLE
Add GEOS single sided buffer operation to QgsGeometry

### PR DESCRIPTION
**Pull request by giohappy**
I've reopend a new pull request because I switched this pull to a branch.
I keep it open for the day QGIS will be only built against GEOS >=  3.3.8

### CODE REVIEW

**Comment by strk** [comment]
@giohappy are you planning to rebase this to master ? I guess a testcase would also help getting this merged.

**Comment by strk** [comment]
Sorry, I see the PR already contains a test. So I guess this is waiting for the capabilities query and a rebase.

**Comment by nyalldawson** [comment]
I'm going to rework this PR - turns out most of the discussion here was not required since the single sided buffer was introduced in GEOS 3.3.0 (https://trac.osgeo.org/geos/browser/tags/3.3.0/NEWS), and we already rely on > 3.3

**Comment by nyalldawson** [comment]
Superseded by #3391

**Pull request closed without merging**
