### PR TITLE
Fix pasting features - only a single insert operation, no unnecessary (failing) updates

### PR DESCRIPTION
**Pull request by suricactus**
When pasting features from another layer, the current implementation calls both `QgsVectorLayer::addFeatures` and `QgsVectorLayer::changeAttributeValue`. This results in both `INSERT` and `UPDATE` operations, but the latter is unnecessary, especially updating a feature with not yet known feature id. 

The error has not been caught yet, because in case of invalid feature ID for `UPDATE`, it results in a query `UPDATE ... WHERE fid = 0`, which is executes and does nothing (unless someone is unlucky enough). However, the error was caught with the PostGIS provider and `int64` id column, because the `WHERE` clause remains empty string, which causes a SQL error.

I am currently investigating the possibility to have a test case, but I am done with the fix itself.

### CODE REVIEW

**Comment by gioman** [comment]
@suricactus was this also the cause of the slowness when copy/pasting features between tables/layers?

**Comment by suricactus** [comment]
@gioman there is a fair performance improvement, but it still feels slow to me.

@signedav can you have a look on this fix?

**Review by signedav — APPROVED** [review]
Looks reasonable. Thanks a lot.

**Comment by m-kuhn** [comment]
@suricactus can you run astyle on the changed files?

**Pull request merged**
