### PR TITLE
[processing] Unify duplicate grid creation algorithms

### PR DESCRIPTION
**Pull request by nyalldawson**
Condenses the duplicate grid algorithms into single algorithms (one for line, one for polygon), taking the best bits from both and adding tests

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , why hide the deprecated algorithms instead of simply removing them? Since this is part of upcoming Q3.0, can we not afford to remove algs?

**Comment by Gustry** [comment]
This PR makes me think there are two algorithms "fill holes" and "remove holes" which should be the same. We can maybe add new tags to one. I wanted to remove one, but I wasn't sure about which one is the best. Any thoughts?

**Comment by nyalldawson** [comment]
@Gustry You'd want to keep the non-script one, so keep DeleteHoles.py. But the other alg has the option to set a hole size, so you'd want to copy that across. Actually I think the "max size" parameter is wrongly named and it's actually a "minimum size"...!

**Comment by alexbruy** [comment]
I also think that for QGIS 3 we can safely remove all deprecated algs. This is kind of API break

**Comment by m-kuhn** [comment]
what's the connection to https://github.com/qgis/QGIS/pull/3547 and #3546 ?

**Comment by nyalldawson** [comment]
They'll need rebasing to merge into this. But currently there's no tests for these algs which makes me nervous about changes like those other PRs. That's why this should merge first.

**Comment by nyalldawson** [comment]
> I also think that for QGIS 3 we can safely remove all deprecated algs. This is kind of API break

Kind of, but it impacts users rather than developers. How does processing react if a model uses an algorithm which is no longer available? We'd need to be careful not to break existing models in such a way that they can no longer be opened and upgraded.

I think this discussion should probably be raised on the dev/user lists for feedback. In the meantime we can push this forward by making one "ultimate" version of each of these duplicated algorithms and marking the others as deprecated. Then at a later stage we can remove/..? all the deprecated ones.

**Comment by Gustry** [comment]
Yes we can remove old algorithm, but having a migration tool would be very appreciated. As a final user, I don't want my models to be broken by having a python error. A tool saying "this algorithm doesn't exist anymore in QGIS, what would you like to do ?" is needed.

**Comment by nyalldawson** [comment]
Thanks @alexbruy !

**Comment by pcav** [comment]
Agreed. I think we do not need anything very sophisticated:
* making it clear a model is broken, before running it
* let the user replace the missing alg with the model editor

**Comment by nirvn** [comment]
We'll definitively have to address this. Leaving unmaintained algorithms behind is ultimately a disservice to users. An unmaintained algorithm part of a model could eventually lead model to still work but give erroneous outputs, which would be much more difficult to a/ be aware of, and b/ debug.

**Pull request merged**
