### PR TITLE
Few more UX improvements [vertex tool]

### PR DESCRIPTION
**Pull request by wonder-sk**
### Do not keep highlight when locking/unlocking feature
    
It was a bit strange effect when locking feature... when moving mouse over a feature it would have highlight, then on right click it would also get vertex editor square markers in addition to the highlight, but then immediately after mouse move the original highlight would be gone. Now it's simplified so that feature highlight on right click gets removed.

### Continue loop of locked features after mouse move
    
A small UX improvement: after right click in a location with feature A and B, we would do a loop A - B - nothing - A - B - nothing ... But if after first click to get A locked user would move the mouse a bit, the loop would get broken and would end up with A - nothing - B - nothing - A - B - nothing. The fix is to identify where we are in the cycle and set the index correctly after mouse move.

### Fix an issue with vertex selection when a feature is locked

See https://issues.qgis.org/issues/21283 for the description

### CODE REVIEW

**Comment by nirvn** [comment]
+1. Just in time :)

**Comment by PhDGeomatic** [comment]
For the "locked" feature the issue [#21283](https://issues.qgis.org/issues/21283) also occurs.
It makes editing the vertices difficult when they are in common with other "unlocked" features.

**Comment by wonder-sk** [comment]
@m-kuhn just wondering why do you edit the titles to put the topic in brackets to the back? I find it much more useful to have the topic in brackets in the front - like that I can visually filter PRs without reading the whole title to the end

**Comment by m-kuhn** [comment]
First I wanted to get rid of `[FEATURE][needs-docs]` which don't help to filter at all and just take space away from useful information.

Then there were the `[Fixes #123456]` tags which also don't help much to filter, so I started to move them to the back.

I wouldn't mind keeping topic specific established ones like `[processing]` in the beginning, I just move them for consistency with the `fixes` tags and to keep track of which ones I've already done.

**Comment by wonder-sk** [comment]
@PhDGeomatic the issue you reported should be fixed now

@m-kuhn agreed the other pieces of info are not helpful in the front of the title, but I would vote for keeping topics like `[layouts]`, `[server]` at the title start

**Comment by nyalldawson** [comment]
Alternatively we add GitHub labels for these, but my preference would be to keep them purely for organisational purposes

**Comment by nirvn** [comment]
@wonder-sk , @m-kuhn , I also would much prefer to have keywords like [themes], [ogr], etc. stay at the front. In fact, while I don't have a strong feeling about the position of the [FEATURE] tag, I tent to like it at the beginning as it does a great job at getting people's attention when reading the log. 

The [needs-docs] tag can definitively be moved at the end, it's very much a tag to trigger a script, not that helpful to log readers (very similar to the fixes #..., which we all put at the end these days).

**Comment by m-kuhn** [comment]
I like that, putting a single `[context]` label at the front sounds good and useful.

* What about `[FEATURE]` and `[needs-docs]`, do they belong into the pull request title at all or are they better put into a commit message?
* Do we need `[bugfix]`?
* And finally, everyone ok with deleting fixes # issue number from the title? these should be
  - put into the commit message (to trigger closing the issue)
  - with a link into the message body for a reviewer to quickly get more context without having to browse through the issue queue himself

**Comment by nyalldawson** [comment]
> * What about `[FEATURE]` and `[needs-docs]`, do they belong into the pull request title at all or are they better put into a commit message?

No - the don't belong in the PR title. It's redundant info better exposed through the github labels.

> Do we need `[bugfix]`?

Ditto - no need, the github labels show this.

> And finally, everyone ok with deleting fixes # issue number from the title? these should be
+1

**Comment by wonder-sk** [comment]
... and thanks for the discussion about PR titles! :-)

**Comment by nirvn** [comment]
@wonder-sk , quick, quick, 3.4! :)

**Comment by wonder-sk** [comment]
@nirvn it's coming! https://github.com/qgis/QGIS/pull/9227

**Pull request merged**
