### PR TITLE
FEATURE/FIX?? Support for parameterized SVG files in composer

### PR DESCRIPTION
**Pull request by nyalldawson**
This adds support for parameterized SVG files in composer.

It fixes the regression http://hub.qgis.org/issues/14385 and allows for changing fill/border color and border width for parameterized svg, such as those included with the QGIS install.

TODO:
- add unit tests
- backport to 2.14???

### CODE REVIEW

**Comment by nyalldawson** [comment]
@jef-n What's your thoughts here? Should I backport this to 2.14 so that http://hub.qgis.org/issues/14385 is fixed?

I honestly don't personally see this as a huge issue, so would be happy to wait for people to test this in master until 2.14.2 or something. But what's your thoughts?

**Comment by nyalldawson** [comment]
On the other hand: given that the original bug was present in master for 4 months before release... I'm not really sure how much testing this will get in master before backporting!

**Comment by nyalldawson** [comment]
One last thing... since this switches the composer picture to use the SVG cache for rendering svg files, it opens the composer up to http://hub.qgis.org/issues/13565. I'm not sure if that's an issue or not.

**Comment by nirvn** [comment]
@nyalldawson beautiful, working great here. Nice to see more code shared (IMO, issue 13565 isn't going to be a big problem in this context, and shared code means increased chances of getting it fixed eventually :smile: ).

BTW, it would be nice to increase the height of the the search directories' preview area (similarly to what you did for the legend item last week).

**Comment by nyalldawson** [comment]
Merged to master, but will keep this PR open until I've backported

**Comment by nyalldawson** [comment]
Backported to 2.14

**Pull request closed without merging**
