### PR TITLE
Fix wrong list of layers in Rasterize alg (Convert map to raster)

### PR DESCRIPTION
**Pull request by wonder-sk**
When not using a map theme nor explicit list of layers, the list of layers
is taken from the project. However the algorithm took a list of all layers
in the project, including the ones that were not visible, and the rendering
order was rather arbitrary (sorted by layer IDs I think).

It seems this has been broken since the port from Python to C++ in QGIS 3.12

New logic copied from the "Generate XYZ tiles" alg:
https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/qgis/TilesXYZ.py#L188

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
> It seems this has been broken since the port from Python to C++ in QGIS 3.12

Any chance of a new test to cover this then?

**Comment by wonder-sk** [comment]
> Any chance of a new test to cover this then?

Yeah I will add one - just too tired/lazy yesterday to do it :-)
Let's wait with the merge...

**Comment by DelazJ** [comment]
>  including the ones that were not visible, 

@wonder-sk Is this an issue? Otherwise, it'd mean that if I want to rasterize a layer, I first need to make it visible before proceeding. I may have layer(s) that take(s) time to render and to avoid this rendering time, just take the right extent and pick them in the provided list. Or am I misunderstanding your suggestion?

**Comment by wonder-sk** [comment]
> Is this an issue? Otherwise, it'd mean that if I want to rasterize a layer, I first need to make it visible before proceeding. I may have layer(s) that take(s) time to render and to avoid this rendering time, just take the right extent and pick them in the provided list. Or am I misunderstanding your suggestion?

@DelazJ There are in total three different cases handled in the algorithm:
1. map theme is selected -> It will use the layers as defined in the map theme
2. map layers are explicitly selected -> It will use those layers
3. none of the above applies -> It will use project layers (how the project is currently configured)
My fix only modifies (fixes) the third case - and I think you had the second case in your mind - that should keep working as it is and you won't need to make those layers visible before running the algorithm if you explicitly picked them...

**Comment by DelazJ** [comment]
Right, I thought you were referring to point2 (since you mentioned layer name order). Thanks for the explanation.

**Comment by wonder-sk** [comment]
It seems like `qt5-image-formats-plugins` is not installed in the docker image and so QImage is unable to load a `tif` file for comparison...

**Comment by nyalldawson** [comment]
@wonder-sk try adding it here: https://github.com/qgis/QGIS/blob/master/.docker/qgis3-build-deps.dockerfile#L96

**Comment by wonder-sk** [comment]
:tada: that worked - thanks Nyall... should be ready for merge!

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
