### PR TITLE
Enable snapping to grid for models in designer

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR implements two "snapping" features in the Processing model designer:

1. Users can enable a new "Enable Snapping" option from the view menu, which will cause all component moving or resizing operations to automatically snap to grids

2. After selecting some components, users can select Edit -> Snap Selected Components to Grid to manually snap just those selected components.

Additionally, I've added a helpful "select all" action for quickly selecting all components in a model.

Refs NRCan Contract#3000707093

### CODE REVIEW

**Comment by nirvn** [comment]
Cool.

I'm not sure we should switch off snap to grid. I feel that, contrary to the layout designer, the model designer should have it on by default.

**Comment by nyalldawson** [comment]
@nirvn I originally had this thought too, but in practice it just "felt" wrong. Would you mind revisiting this after merge? (It's an easy true->false change)

**Comment by nirvn** [comment]
@nyalldawson , sure. I think for it to work well, we'd need default item size to correlate with grid, ie item width is 8 × grid spacing, height is 2 × grid spacing.

**Comment by nyalldawson** [comment]
Yeah, that's a good point!

**Review by alexbruy — APPROVED** [review]

**Pull request merged**
