### PR TITLE
[processing] Make 'Line Intersections' able to keep all attrs

### PR DESCRIPTION
**Pull request by gacarrillor**
The current Processing algorithm _Line Intersections_ cannot keep all fields from input and/or intersect layers. Moreover, it also cannot manage to keep single fields from both layers if the fields have the same name. This PR fixes these issues.

If the user wants to keep all fields, no selection should be made from the field list.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Can you open this PR against master? master_2 is a dead branch now.

**Comment by gacarrillor** [comment]
Do you think there won't be upcoming minor releases (e.g., 2.18.1)?
But, yeah, I think it's time to switch to QGIS 3 anyways. I'll try to build it and see how different it is.

**Comment by nyalldawson** [comment]
2.18.1, .2, etc will come from the release-2_18 branch, not master_2. There's no plans for 2.20 so master_2 is dead and should really be made read only.

**Comment by jef-n** [comment]
Automatically closed on removal of the master_2 branch.

**Pull request closed without merging**
