### PR TITLE
Expression icon improvements

### PR DESCRIPTION
**Pull request by timlinux**
Use QGIS icon blue for expression icon and remove glossy effect from the symbol which is inconsistent with the rest of QGIS design language (which generally uses flat objects) and also makes the E symbol harder to discern, especially on dark mode.

Addresses https://github.com/qgis/QGIS/issues/47065#issuecomment-1026701264

These are the icons I changed:

Before my change:

imagem

After my change:

imagem

### CODE REVIEW

**Comment by nirvn** [comment]
@timlinux , I'll have a look tomorrow. One tip: use save copy as optimized SVGs in inkscape to strip SVGs from anything other than what's required. Makes for smaller files, micro optimization et al

**Comment by timlinux** [comment]
> @timlinux , I'll have a look tomorrow. One tip: use save copy as optimized SVGs in inkscape to strip SVGs from anything other than what's required. Makes for smaller files, micro optimization et al

Busy doing that now .... note that Inkscape gives this warning on each save:

image

Not sure if it impacts the output or not....

**Comment by timlinux** [comment]
Here is the pre-optimised vs optimised listing:

<pre>-rw-rw-r--. 1 timlinux timlinux 3,2K fev  1 18:44 <font color="#A347BA"><b>mActionAddExpression.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux  291 abr  7  2021 <font color="#A347BA"><b>mActionHandleStoreFilterExpressionChecked.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux  326 abr  7  2021 <font color="#A347BA"><b>mActionHandleStoreFilterExpressionUnchecked.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 4,1K fev  1 18:44 <font color="#A347BA"><b>mActionMeshSelectExpression.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 3,4K fev  1 18:44 <font color="#A347BA"><b>mActionMeshTransformByExpression.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 2,9K fev  1 18:44 <font color="#A347BA"><b>mIconDataDefineExpressionError.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 2,6K fev  1 18:44 <font color="#A347BA"><b>mIconDataDefineExpressionOn.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 2,5K fev  1 18:44 <font color="#A347BA"><b>mIconDataDefineExpression.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 3,3K fev  1 18:44 <font color="#A347BA"><b>mIconExpressionFilter.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 4,1K fev  1 18:44 <font color="#A347BA"><b>mIconExpressionPreview.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 3,0K fev  1 18:44 <font color="#A347BA"><b>mIconExpressionSelect.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 2,9K fev  1 18:44 <font color="#A347BA"><b>mIconExpression.svg</b></font>
</pre>

Optimised:

<pre><span style="background-color:#12488B"><font color="#FFFFFF"><b> timlinux </b></font></span><span style="background-color:#2A7BDE"><font color="#12488B"></font></span><span style="background-color:#2A7BDE"><font color="#FFFFFF"><b> crest </b></font></span><span style="background-color:#FFFFFF"><font color="#2A7BDE"></font></span><span style="background-color:#FFFFFF"><font color="#5E5C64"><b> ../themes/default </b></font></span><span style="background-color:#5E5C64"><font color="#FFFFFF"></font></span><span style="background-color:#5E5C64"><font color="#D0CFCC"><b> expressions-icon □ </b></font></span><font color="#5E5C64"></font> <font color="#00D7FF"><b>ls -lah *pression*</b></font>
-rw-rw-r--. 1 timlinux timlinux 2,0K fev  1 18:46 <font color="#A347BA"><b>mActionAddExpression.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux  291 abr  7  2021 <font color="#A347BA"><b>mActionHandleStoreFilterExpressionChecked.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux  326 abr  7  2021 <font color="#A347BA"><b>mActionHandleStoreFilterExpressionUnchecked.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 2,3K fev  1 18:46 <font color="#A347BA"><b>mActionMeshSelectExpression.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 1,9K fev  1 18:46 <font color="#A347BA"><b>mActionMeshTransformByExpression.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 1,6K fev  1 18:46 <font color="#A347BA"><b>mIconDataDefineExpressionError.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 1,5K fev  1 18:46 <font color="#A347BA"><b>mIconDataDefineExpressionOn.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 1,5K fev  1 18:46 <font color="#A347BA"><b>mIconDataDefineExpression.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 1,9K fev  1 18:46 <font color="#A347BA"><b>mIconExpressionFilter.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 2,3K fev  1 18:46 <font color="#A347BA"><b>mIconExpressionPreview.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 1,7K fev  1 18:46 <font color="#A347BA"><b>mIconExpressionSelect.svg</b></font>
-rw-rw-r--. 1 timlinux timlinux 1,5K fev  1 18:46 <font color="#A347BA"><b>mIconExpression.svg</b></font>
</pre>

**Comment by timlinux** [comment]
Also here is how my changes look in dark mode:

Before:

image


After:


image

**Comment by timlinux** [comment]
With a light theme:

Before

image


After

image

**Comment by nyalldawson** [comment]
@timlinux I wonder if this isn't the perfect opportunity to start moving things towards a proper system for handling dark mode icons. The current approach will always run into issues somewhere, and we'll never be able to make a full icon set which works nicely for both light/dark themes without some responsive in the icons.

So.... what I propose is that we reuse the "param" method for parameterizing the SVG icons! We start working towards a set of "standard" color names to use in the svgs, e.g. here you'd parameterise the "e" fill color to use "expression-icon-color". Then in QgsApplication::getThemeIcon we modify the call to QgsApplication::svgCache()->svgContent so that it specifies the "parameters" variant map argument, which would be set to a map of desired colors for the current desktop. ie.

    { "expression-icon-color": "#xxxxxx", "new-plus-icon-overlay-color": "#xxxxxx", "create-star-icon-overlay-color" :"#xxxxxx" }

(where the plus icon/star icon correspond to the little overlay bits in these icons:

image

)

Does that make sense? @nirvn what's your thoughts?

**Comment by timlinux** [comment]
> @timlinux I wonder if this isn't the perfect opportunity to start moving things towards a proper system for handling dark mode icons. The current approach will always run into issues somewhere, and we'll never be able to make a full icon set which works nicely for both light/dark themes without some responsive in the icons.
> 
> So.... what I propose is that we reuse the "param" method for parameterizing the SVG icons! We start working towards a set of "standard" color names to use in the svgs, e.g. here you'd parameterise the "e" fill color to use "expression-icon-color". Then in QgsApplication::getThemeIcon we modify the call to QgsApplication::svgCache()->svgContent so that it specifies the "parameters" variant map argument, which would be set to a map of desired colors for the current desktop. ie.
> 
> ```
> { "expression-icon-color": "#xxxxxx", "new-plus-icon-overlay-color": "#xxxxxx", "create-star-icon-overlay-color" :"#xxxxxx" }
> ```
> 
> (where the plus icon/star icon correspond to the little overlay bits in these icons:
> 
> image
> 
> )
> 
> Does that make sense? @nirvn what's your thoughts?

It does for me - I was thinking similar things last night. Maybe we should also rope in Robert Szczepanek (original developer of the icon set) and see if this could be bubbled upstream. For some nostalgia, see https://qgis-developer.osgeo.narkive.com/r8Y5vBh0/cast-your-vote-default-icon-theme-for-qgis-2-0

**Comment by timlinux** [comment]
Above comment notwithstanding, it would still be good to merge this PR  in the interim as that expressions icon sticks out like a sore thumb....

**Comment by nirvn** [comment]
+1 to what @nyalldawson is proposing.

@timlinux , I have some reservations here. I rather liked to have a purple color as a visual hint to indicate "expressions" (instead of using the neutral blue we have in other places). One way to keep the purple color and make it compatible with black themes is to add a light gray semi transparent aura around the E much like is done with labeling icons:
image

Ultimately, if we expose colors the way Nyall is suggesting, we can do what blender did and give generic color themes (ie "dataset" blue, "expression" purple, etc.) and have those customizable via themes as well as having lighter versions for dark themes, etc.

Beyond the bigger argument around purple, a few other smaller points:
- you removed the nice highlight areas from the E, I think that should stick
- the single E icon looks slightly oversized now, I'd reduce it a tiny bit
- for the mIconDataDefinedExpressionError.svg, IMO, we should keep the light red background instead of white

@nyalldawson , thoughts of the purple and those other points?

**Comment by roya0045** [comment]
I just noticed that the icon that I made is the only one without the 'light' effect on the epsilon. Though it's not noticeable in daily use.

**Comment by timlinux** [comment]
> +1 to what @nyalldawson is proposing.
> 
> @timlinux , I have some reservations here. I rather liked to have a purple color as a visual hint to indicate "expressions" (instead of using the neutral blue we have in other places). One way to keep the purple color and make it compatible with black themes is to add a light gray semi transparent aura around the E much like is done with labeling icons: image
> 
> Ultimately, if we expose colors the way Nyall is suggesting, we can do what blender did and give generic color themes (ie "dataset" blue, "expression" purple, etc.) and have those customizable via themes as well as having lighter versions for dark themes, etc.
> 
> Beyond the bigger argument around purple, a few other smaller points:
> 
>     * you removed the nice highlight areas from the E, I think that should stick
> 
>     * the single E icon looks slightly oversized now, I'd reduce it a tiny bit
> 
>     * for the mIconDataDefinedExpressionError.svg, IMO, we should keep the light red background instead of white
> 
> 
> @nyalldawson , thoughts of the purple and those other points?

Hi @nirvn 

I have pretty much the contrary opinion on all your thoughts below, sorry :-P

>     * you removed the nice highlight areas from the E, I think that should stick

These highlights really break up the letter and make it hard to distinguish, especially when it is small. Further, it is also inconsistent with the rest of the icon set which portray flat objects or directional light via gradients rather than reflective bubbles.

imagem


> 
>     * the single E icon looks slightly oversized now, I'd reduce it a tiny bit

Yes, I intentionally enlarged it as my old eyes can't make it out easily. 

> 
>     * for the mIconDataDefinedExpressionError.svg, IMO, we should keep the light red background instead of white

For me, I would go the other way and remove the backgrounds from the other two similar icons - they cause the E symbol to look blurry and reduce the icon contrast.

imagem

For the purple colour, it is really inconsistent with the rest of the icon set (there are no other icons using that purple colour) and reduces the feeling of cohesion from the UI. I think we should be moving in the direction of less colours in our icon palette, rather than more. I'm also not a fan of the buffered letter approach like in the lables dialog. They make sense there because they allude to the actual functionality of the tab area, but as a general design metaphor for QGIS, I think it is nice to keep things simple and crisp, which my approach offers.

Anyway, as designated design guru, I leave it to you @nirvn to make the call, with the humble request that whatever you come up with looks good in dark mode, because as currently implemented, the icon is unreadable.

**Pull request closed without merging**
