### PR TITLE
Avoid saving a file in database without table name

### PR DESCRIPTION
**Pull request by DelazJ**
Also allow to create the path when saving new file (directory could not already exist)

### CODE REVIEW

**Comment by NathanW2** [comment]
Bug fix?

**Comment by nirvn** [comment]
It is a bug fix. I would however like to see the checkOk() part of it reverted before merging.

**Comment by NathanW2** [comment]
@nirvn all good I'm just setting some tags and stuff to clean up the PR list

**Comment by DelazJ** [comment]
@nirvn 
> On my machine, if no layer name is provided, the created dataset uses the file name as layer name.

On mine, also
> I don't see why we'd want to block filename-only scenarios here.

Not sure I understand the issue. But let me try to explain what i'm fixing: as said above, when selecting a filename, the layer name is also populated. But you don't always want to name the layer like the database or the proposed name does not match the data you are saving, so you'd like to rename it. I had a case where i cleared the layer name field and push the OK button without renaming it --> I created a layer without name in my db. 
This PR disables the OK button when the layername is enabled and empty.

**Comment by nirvn** [comment]
@DelazJ , which format was that? I've checked with KML and geopackage, and with a manually emptied layer name field, both datasets successfully saved using the filename as layer name.

**Comment by DelazJ** [comment]
Indeed, I neither could reproduce "my issue". I might have confused the dialog but i'm pretty sure there's a dialog that outputs db with empty layername. Will need to investigate more. I'll revert the checkOk() part tonight

**Comment by DelazJ** [comment]
should be good, @nirvn

**Comment by nirvn** [comment]
@DelazJ , merci.

**Pull request merged**
