### PR TITLE
[layout] Fix max map grid intervals and offsets values

### LINKED ISSUE #43039: Map composer grid intervals does not allow values above 9999999
# Problem

In map composer a user cannot define grid intervals greater than 9999999 when using projected CRS like `EPSG:3857`

Screenshot 2021-04-30 at 11 27 50

OS: Mac Mojave
QGIS Version: 3.18.1

### PR DESCRIPTION
**Pull request by agiudiceandrea**
## Description

Increases the number of digits in order to define grid intervals and offsets for CRSs like e.g. EPSG:3857.

Fixes https://github.com/qgis/QGIS/issues/43039

It also adds the missing "minimum" property to mOffsetXSpinBox and mOffsetYSpinBox in order to allow the use of negative values for the map grid offset.

The fixed issue also affects 3.16 and 3.20 branches.

(maximum value taken from https://github.com/qgis/QGIS/pull/43831/files#diff-f554bbf37d4fbbb1d4dd79782e54ae6017f127d66e73fd0d9dcfea56c20a544a)

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
I see now that the grid decoration has higher max value:
https://github.com/qgis/QGIS/blob/896bab450e3af8a460b6c89daed8a5d8e67801da/src/ui/qgsdecorationgriddialog.ui#L270-L273

Better to use here the same max value?

**Comment by nyalldawson** [comment]
> Better to use here the same max value?

Sounds good!

**Review by nyalldawson — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
What about backporting to 3.16/3.20?

**Comment by agiudiceandrea** [comment]
@nyalldawson what about backporting to 3.16/3.20?

**Pull request merged**
