### PR TITLE
PG fix relation discovery with table/schema that require quotes

### LINKED ISSUE #39036: erroneous postgis query when trying to discover relations
When I try to discover relations between my tables, I get this warning in the PostGIS message log:

Erroneous query: WITH foreign_keys AS ( SELECT c.conname, c.conrelid, c.confrelid, unnest(c.conkey) AS conkey, unnest(c.confkey) AS confkey, (SELECT relname FROM pg_catalog.pg_class WHERE oid = c.conrelid) as referencing_table, (SELECT relname FROM pg_catalog.pg_class WHERE oid = c.confrelid) as referenced_table, (SELECT relnamespace::regnamespace::text FROM pg_catalog.pg_class WHERE oid = c.confrelid) as constraint_schema FROM pg_constraint c WHERE contype = 'f' AND c.conrelid::regclass = '.'::regclass ) SELECT fk.conname as constraint_name, a.attname as column_name, fk.constraint_schema, referenced_table as table_name, af.attname as column_name, fk.confkey as ordinal_position FROM foreign_keys fk JOIN pg_attribute af ON af.attnum = fk.confkey AND af.attrelid = fk.confrelid JOIN pg_attribute a ON a.attnum = conkey AND a.attrelid = fk.conrelid ORDER BY fk.confrelid, fk.conname ; returned 7 [ERROR: invalid name syntax
             LINE 1: ...ERE contype = 'f' AND c.conrelid::regclass = '.'::regcl...
              ^
             ]

QGIS version | 3.15.0-Master | QGIS code revision | 3119eb7de2
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.2.0dev | Running against GDAL/OGR | 3.2.0dev
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 7.2.0 | Running against PROJ | Rel. 7.2.0, November 1st, 2020
OS Version | Windows 10 (10.0) | This copy of QGIS writes debugging output.
Active python plugins | SpreadsheetLayers; db_manager; MetaSearch; processing

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #39036 #39025  (temptative, because I could not reproduce the
exact issue without project and data)

### CODE REVIEW

**Comment by elpaso** [comment]
@3nids I need a little help here: I added `sql` to the badlist here  https://github.com/qgis/QGIS/pull/39043/commits/dfb8527810a5e2bfb6e6801cec60170cba7e5e5a but apparently it has no effect.

**Comment by 3nids** [comment]
Rather than removing check for all sql files, you can add a #spellok on the concerned line (in a comment)
I'd prefer keeping spell check on as many files as possible.

**Comment by elpaso** [comment]
@3nids On all lines? It's not even one of my files. Besides that it is an sql test data. Is there at least a file block list?

**Comment by 3nids** [comment]
Here you go https://github.com/qgis/QGIS/blob/master/scripts/spell_check/.agignore

**Comment by elpaso** [comment]
@3nids thank you!

**Pull request merged**
