### PR TITLE
New class for blocking (non-async) network requests [FEATURE][API]

### PR DESCRIPTION
**Pull request by nyalldawson**
First this PR adds a new class: QgsNetworkReplyContent.

From the dox:

"Encapsulates a network reply within a container which is inexpensive to copy and safe to pass around between threads. The default Qt QNetworkReply class is a QObject, which prevents it from being copied and passed between threads. This class grabs all the useful information from a QNetworkReply, allowing the reply's content to be stored indefinetly without concern for the lifetime of the QNetworkReply object itself."

And then the main attraction: A new class, QgsBlockingNetworkRequest, which is designed for
performing SAFE blocking requests. It is thread safe and has full support for QGIS proxy and authentication settings.

This class should be used whenever a blocking network request is required. Unlike implementations
which rely on QApplication::processEvents() or creation of a QEventLoop, this class is completely
thread safe and can be used on either the main thread or background threads without issue.

Redirects are automatically handled by the class.

After completion of a request, the reply content should be retrieved by calling getReplyContent().
This method returns a QgsNetworkReplyContent container, which is safe and cheap to copy and pass
between threads without issue. 

The guts of this class have been copied from QgsWfsRequest (which has been using the same approach since 3.2)

Using this class for blocking requests should fix a lot of fragile code/crashes/unpredictable behaviour in QGIS, where the current approaches are triggering main thread processEvents calls.

It also will be of a lot of value to Python scripts, where lack of a blocking PyQt network method has meant that plugins and scripts tend to fall back on the built-in python requests libraries, which lack support for QGIS' proxy settings and authentication handling.

### CODE REVIEW

**Comment by elpaso** [comment]
Much needed! Finally :+1:

**Comment by 3nids** [comment]
wow cool, thanks for tackling this!

**Comment by nyalldawson** [comment]
I ported the AFS provider to use this class, and instantly I'm seeing an improvement in the provider's stability. Before I'd get occasional hangs due to interaction between the local event loop and the auth system, now there's none. Win!

**Comment by nyalldawson** [comment]
Anyone want to review this code? it's horribly complex stuff yet mission critical, so I'd love at least 2 reviews before merge.

@m-kuhn you especially, since you wrote this stuff in the first place, and I'm assuming as a result take full legal responsibility for the code in perpetuity. ;)

@wonder-sk you're our resident threading expert... care to spare some blood pressure and sacrifice approximate 4-8 weeks life expectancy by reading over this?

**Comment by nyalldawson** [comment]
@wonder-sk

> I will have two shots of rum and start reading

... that sounds very wise!

**Comment by m-kuhn** [comment]
AFAICT it's as good as it gets...

It's quite complex threading code.
Main thread creates a downloader thread and waits.
Downloader thread needs auth information and blocks and continues the main thread.
Main thread executes `processEvents()` (:fearful:) and hands over credentials to downloader thread and waits for it to finish (or ask for more credentials).

...

Yes, it works. But it's still a dangerous thing to do. processEvents() can still crash and we still run a risk of deadlocks. And the UX of a slow network request is terrible anyway.

I'd say proceed and merge, but let's keep the final goal on the radar, that providers and other code should be able to deal with async network requests rather than using this semi-stable workaround to get something that behaves as if it was synchroneous.

**Comment by wonder-sk** [comment]
I have a suspicion there is a possible deadlock when resuming main thread... as far as I read the code:
- main thread: get lock, check for finished, wait for condition (= unlock, wait, lock), ...
- worker thread - for resume: get lock, wake, unlock, get lock, wait for condition, unlock

When resuming, after the "first lock, wake, unlock" group in worker thread we hope that main thread reacts immediately and acquires the lock and does processEvents(). But isn't it possible that main thread is not as fast to acquire the lock again... and the resumeMainThread function acquires the lock again - and starts to wait forever? (lines 148-150)

[I have some more comments to add but this seemed like the most important one so far]

**Comment by nyalldawson** [comment]
@wonder-sk sorry, can you elaborate? I'm having trouble following the sequence you describe...

**Comment by nyalldawson** [comment]
@wonder-sk 
Specifically, by:

> when resuming, after the "first lock, wake, unlock" group in worker thread

are you referring to lines 146-148?

>  But isn't it possible that main thread is not as fast to acquire the lock again... 

If I'm interpreting correctly, I think this is covered by QWaitCondition. Unfortunately the QWaitCondition docs are sub-par and there's a lot of ambiguity here.

**Comment by wonder-sk** [comment]
Sorry I was in a hurry last night :)

So what I meant was that we are expecting something like this:
```
MAIN
downloaderThread->start();
waitConditionMutex.lock();
waitCondition.wait( &waitConditionMutex );   // unlocks mutex + start waiting
```

```
WORKER
... start request, enter event loop, then at some point auth is requested ...
waitConditionMutex.lock();
waitCondition.wakeAll();
waitConditionMutex.unlock();

waitConditionMutex.lock();  // blocks here because main thread has the mutex now
```

Main thread is woken up from the wait and it can process events:

```
MAIN
waitConditionMutex.unlock();
QgsApplication::instance()->processEvents();
```

But I am wondering if it is not easily possible that the worker thread is quick enough to immediately acquire the mutex that should have been acquired by main thread.

When I look into implementation of QWaitCondition::wait(QMutex *mutex, unsigned long time), it boils down to this:
```
mutex->unlock();
bool returnValue = d->wait(time);
mutex->lock();
```

There isn't something like atomic wake up + mutex acquisition, so when the main thread gets woken up, both main thread and worker thread race for the mutex. I mayb be wrong though...

I think what we have here is essentially the classical producer/consumer problem with a buffer of size 1... worker thread produces an item (auth request) that needs to be processed by main thread, which then signals back to worker thread to resume. For that scenario people use two different wait conditions with one mutex (to protect shared data - here there are no shared data since the auth request goes through the Qt signals/event system).

**Comment by nyalldawson** [comment]
Get lost stalebot. Or write your own thread safe blocking network request api, and then come back here to complain.

**Comment by nyalldawson** [comment]
@wonder-sk 

Thanks for the extra pointers here -- I've added https://github.com/qgis/QGIS/pull/8440/commits/e3d78489d9e5f6a5f1d62405d1a674ac89609781 which follows the consumer/producer pattern correctly.

**Comment by nyalldawson** [comment]
@wonder-sk are you OK if I merge this now?

**Comment by nyalldawson** [comment]
I'm going to merge this for wider testing (and because I'm tired of the hangs I get in the AFS provider without this change ;) ) But I'm still keen on further review and feedback if more improvements are possible!

**Comment by wonder-sk** [comment]
Oh sorry only now I have exited my dark cave to have a look at the PR queue - the changes look good anyway :-)

**Comment by nirvn** [comment]
@wonder-sk , for the record, it was subsequently reverted.

**Pull request merged**
