### PR TITLE
[Postgres] Fix estimate row on table

### LINKED ISSUE #40162: Estimated row count from PostgresSQL might quite wrong
**Describe the bug**

Since #32114, QGIS is using `Plan Rows` from an `EXPLAIN` query to have the estimated row count.

The `Plan Rows` makes quite different results and is not following the `VACUUM ANALYSE` that people might run on their database.

Look this example:

```sql
-- What is done by QGIS 3.10
EXPLAIN (FORMAT JSON) SELECT 1 FROM pgmetadata.contact
-- QUERY PLAN [{'Plan': {'Node Type': 'Seq Scan', 'Parallel Aware': False, 'Relation Name': 'contact', 'Alias': 'contact', 'Startup Cost': 0.0, 'Total Cost': 15.1, 'Plan Rows': 510, 'Plan Width': 4}}]
-- > 'Plan Rows': 510

VACUUM ANALYSE pgmetadata.contact;
SELECT reltuples as approximate_row_count  FROM pg_class WHERE oid = 'pgmetadata.contact'::regclass;
-- 0.0

SELECT COUNT(*) FROM pgmetadata.contact;
-- 0

EXPLAIN (FORMAT JSON) SELECT 1 FROM pgmetadata.contact;
-- Still 510
```

**QGIS and OS versions**

QGIS version | 3.10.11-A Coruña | QGIS code branch | Release 3.10
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 13.1 (Ubuntu 13.1-1.pgdg20.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS | This copy of QGIS writes debugging output.
Active python plugins | quick_map_services; trackable_project_files; lizmap; changeDataSource; firstaid; plugin_reloader; veloroutes_voies_vertes; pg_metadata; coretests; cadastre; qgistester; valuemap_2_lizmap-main; db_manager; processing

CC @troopa81

### PR DESCRIPTION
**Pull request by troopa81**
## Description

Fixes #40162

Restore old code for estimating rows on table using *reltuples* from *pg_class* because it appears more close to the true than the *plan rows* estimation used for views (reltuples is always 0 in views). Especially when we delete massively rows like pointed in the issue. 

This PR also lazily request and store the relation kind attribute to avoid requesting it every time we need it.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Backports required?

**Comment by troopa81** [comment]
> Backports required?

yes for 3.16, no for 3.10 (I would say too critical too backport). I added the tags

**Comment by Gustry** [comment]
Thanks for this fix !

**Comment by Gustry** [comment]
Hum, it seems the bot is smarter now, it stopped doing the PR with the bad merge ? :)

Thanks @m-kuhn for the merge!

**Comment by m-kuhn** [comment]
> Hum, it seems the bot is smarter now, it stopped doing the PR with the bad merge ? :)

Not really, we've had that before. I think it's connected to a condition if shapefile did make a tweet on the same day.

**Pull request merged**
