### PR TITLE
[docs] Add python3-pyqt5.qtmultimedia dependency for debian based-distros

### PR DESCRIPTION
**Pull request by pathmapper**
ref https://lists.osgeo.org/pipermail/qgis-developer/2023-January/065488.html

### CODE REVIEW

**Comment by jef-n** [comment]
If this is a build dependency add it to debian/control.in. INSTALL.md is updated by running scripts/scandeps.pl.

**Comment by Gustry** [comment]
Yes, it seems it has been updated recently already #51627 from @DelazJ

**Comment by DelazJ** [comment]
Hi,  no @Gustry I actually added qtmultimedia5-dev so both should be added to debian/control.in (which answers my question in #51627)

**Comment by pathmapper** [comment]
@jef-n thanks for the hint! Added it only to `debian/control.in` and run the mentioned script.

**Review by jef-n — APPROVED** [review]

**Pull request merged**
