### PR TITLE
Add const_iterator and iterator methods to QgsFields

### PR DESCRIPTION
**Pull request by m-kuhn**
Because using Q_FOREACH is so much easier to write than an index-based loop.

### CODE REVIEW

**Comment by m-kuhn** [comment]
@nyalldawson not sure about the tests, I think this file should have 100% coverage. Do we have the measurements for this somewhere?

**Comment by nyalldawson** [comment]
Looks good to me. Will be great to have... just yesterday I was wishing we could do this! I'm a bit hazy here - more changes would be required to allow iteration in python, right?

Re coverage - see http://dash.orfeo-toolbox.org/viewCoverageFile.php?buildid=220338&fileid=345770

There's a few lines not hit, eg operator<, <=, -= etc. Not sure how important these are or when they will ever get called anyway.

This is how I get that report:
- grab qgis-test-coverage.ctest from https://github.com/nyalldawson/QGIS/commit/8b33f9266af32dbbc981626d140c2784741ed8ca and dump it in your source folder. Tweak the directories at the start of that script to match yours.
- If you haven't already set the ENABLE_COVERAGE cmake option on, clean out your build folder and rebuild with that option. Make sure you are building with gcc and not clang. 
- from your build folder run `ctest -V -R "fieldstest|fieldtest|Field" -S ../QGIS/qgis-test-coverage.ctest --output-on-failure`

That will run the matching tests, process the coverage report and upload the result to http://dash.orfeo-toolbox.org/index.php?project=QGIS for viewing.

**Comment by m-kuhn** [comment]
Thanks, I'll see if I can roll some tests for them.

Not sure about python, isn't it already converted to a list there?

**Comment by m-kuhn** [comment]
Manually merged

**Pull request closed without merging**
