### PR TITLE
[BUGFIX][Server] GetPrint request renders layers from group in wrong order

### PR DESCRIPTION
**Pull request by rldhont**
fixes #16769

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rldhont** [comment]
Any objection to merge ? @pblottiere @sbrunner

**Comment by tudorbarascu** [comment]
@rldhont I think @pblottiere is on vacation for 2 weeks (@haubourg wrote in a pull request)

**Comment by mdouchin** [comment]
Tested with one of my projects. I confirm this PR fixes the bug

**Comment by rldhont** [comment]
Thanks @mdouchin

**Pull request merged**
