### PR TITLE
Fix crash in rendering on proj 6 builds (3.10 backport of #33939)

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Review by nirvn — APPROVED** [review]
Good to go.

**Comment by jef-n** [comment]
Building qgis-3.10.2-2…

**Comment by nyalldawson** [comment]
Thanks @jef-n.... Fingers crossed!

**Comment by luipir** [comment]
@jef-n will be qgis-3.10.2-2 or 3.10.3 ? because of fixed release roadmap?

**Comment by jef-n** [comment]
> @jef-n will be qgis-3.10.2-2 or 3.10.3 ? because of fixed release roadmap?

qgis-3.10.2-2 in OSGeo4W

**Pull request merged**
