### PR TITLE
Make turning segments into curve less undiscoverable

### PR DESCRIPTION
**Pull request by DelazJ**

### CODE REVIEW

**Comment by m-kuhn** [comment]
... make it more discoverable by adding it to the tooltip of the node tool.
+1

**Review by m-kuhn — APPROVED** [review]

**Comment by DelazJ** [comment]
Thanks @m-kuhn. Looks like using "O" is enough, no need for the shift key but not sure if it is worth a fix....

**Comment by m-kuhn** [comment]
It should be easy enough to do a fix, I would support a new PR

**Comment by DelazJ** [comment]
Leaving for holidays...

**Pull request merged**
