### PR TITLE
Replace png by svg

### PR DESCRIPTION
**Pull request by SrNetoChan**
Replaces PNG icons by SVG files

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@nirvn can you please review?

travis seems to be complaining about spellchecking deleted files.

**Comment by m-kuhn** [comment]
> travis seems to be complaining about spellchecking deleted files.

I hope to have that fixed in #3836 with https://github.com/qgis/QGIS/pull/3836/commits/4c43c1f364909adc587aab2377a773101e8d0d22 waiting for results right now...

**Comment by SrNetoChan** [comment]
@m-kuhn thanks!

**Comment by nirvn** [comment]
@SrNetoChan , I'll review this today. In preparation to giving some feedbacks, may I know which vector program you are using to create/edit SVGs?

**Comment by nirvn** [comment]
@SrNetoChan , ok, there are a couple of issues with the icons that need addressing.

First, you should avoid using clipping paths, they usually fail to render properly. In this case, the three cap style SVGs and the join style SVGs draw black background due to the clipping path:
untitled

Also, when vectorizing icons, to avoid blurring when Qt renders the icons, it's important to:
- have the vector elements snapping to a 1px x 1px grid
- try avoiding pixel unit fractions (i.e. an outline of 0.8 pixel)

If your using Inkscape, you can add a grid to your SVG files which will greatly help spot grid alignment issues:
untitled2

Hope this helps.

**Review by nirvn — CHANGES_REQUESTED** [review]
(See above comments)

**Comment by SrNetoChan** [comment]
Thanks for your review.

I am using Inkscape, but I passed them through a SVG cleaner to make it smaller, to follow Alex Bruy's previous work.
Not sure if that introduced the black background problem.

Those symbols already existed in SVG, but in a single file. I will have a look and try to snap them to the grid. In that case, I believe the final size matters, no? We have icons with 16x16, but others with 24x24.

**Comment by nirvn** [comment]
Regarding icon size, I'd keep it consistent with the PNG icon being replaced. So a 16×16 PNG would be replaced by a SVG of same size.

Using the svgcleaner tool is great.

**Comment by SrNetoChan** [comment]
@nirvn I have corrected the clip path problem. Following your suggestions on snapping the lines to the grid, I decided to propose some improved (IMO) icons for Join and Caps. Can you please review?

**Comment by nirvn** [comment]
@SrNetoChan , can you post a screenshot of your proposed improvements?

**Comment by SrNetoChan** [comment]
new_join_cap_icons

**Comment by nirvn** [comment]
That's great looking! Also, fixing the blur makes a big difference.

**Comment by SrNetoChan** [comment]
Replaced by #3896

**Pull request closed without merging**
