### PR TITLE
Fix las test dataset name

### LINKED ISSUE #40673: git pull error
An unrecognized file name,
tests/testdata/point_clouds/las/cloud%!* _*čopy.las

### PR DESCRIPTION
**Pull request by roya0045**
Changing the name to fix this error 
image

Hopefully the filename is not critical.

Fixes #40673

### CODE REVIEW

**Comment by roya0045** [comment]
Please squash history, forced to use github web to resolve this, thus the many commits.

**Comment by nyalldawson** [comment]
@PeterPetrik was there a particular reason for this name?

**Comment by PeterPetrik** [comment]
tried to test if untwine can index non-ascii filename...

**Comment by nyalldawson** [comment]
Ok, that's a valid reason!

**Comment by nyalldawson** [comment]
@roya0045 can we close? it's an intentional part of the test

**Comment by roya0045** [comment]
@nyalldawson That's a hard no from me, this name makes it impossible to switch to any branches containing this file on windows. This is problematic. @PeterPetrik Now that it has been confirmed that non-ascii characters can we switch to a name that doesn't block git. I'm assuming only the * are offending here but this name should be safer and I doubt we need to be constantly checking for untwine's handling of non-ascii. Otherwise I would suggest only having non * wildcard in the names to prevent any issues.

**Comment by nyalldawson** [comment]
@roya0045 can you just remove the * then? There's other similar tests/test files used for unicode filename testing which don't seem to be problematic...

**Comment by roya0045** [comment]
@nyalldawson confirmed that the * were the issue, I can switch to this branch on git for windows.

**Comment by nyalldawson** [comment]
Great, thanks for the tests!!

**Comment by PeterPetrik** [comment]
thanks for sorting it out, I am already in christmas-mode.

**Comment by roya0045** [comment]
@PeterPetrik No worries, enjoy your vacations!

**Comment by 3nids** [comment]
I have some strange things happening since this commit.
On a freshly fetched repo:
 
image

and if I delete the file:

image

This prevents me from doing any work currently.
(I am on mac os)

Could this be reverted?

**Comment by roya0045** [comment]
@3nids and before this the name didn't cause any issues? The c was still present previously and should still cause the same issue.

**Comment by roya0045** [comment]
@3nids is it fine if you checkout commit 62ed2191b71966cc95802a00c68b69c18c2dc5cc ?

**Comment by 3nids** [comment]
@roya0045 yes I get a clean status if I checkout 62ed219

**Comment by roya0045** [comment]
@nyalldawson @PeterPetrik @3nids so either we revert this and break git for windows and solve the encoding issue on mac, or we can remove the c.

**Comment by PeterPetrik** [comment]
lets remove the test , not that critical

**Pull request merged**
