### PR TITLE
[FEATURE] [needs-docs] classify symmetric

### PR DESCRIPTION
**Pull request by pierreloicq**
Hello,

This PR is the following of https://github.com/qgis/QGIS/pull/5161.

The goal is to have symmetric colors and hence classes around a value. It works for equal interval, s.d. method and pretty breaks.
For equal interval and s.d. methods, there is box for the user to put the pivot value. On my system, typing the dot . doesn't work, probably because comma , is used in my locale language (french). Searching on the net refers to the "bug" so I didn't try to correct  that for the moment. Please tell me if it works correctly on your non-french systems.
I used the word "astride" to describe when the pivot point is inside a class. I think it's easy to understand but maybe you will have a better word.

Thank you

capture du 2017-10-16 00-35-27

### CODE REVIEW

**Comment by kannes** [comment]
Awesome!

I believe you can set QGIS to use any other locale for testing in the options menu somewhere.

Not sure about the "astride", that is not a basic word so I am not sure how intuitive it would be. Maybe "around"?

**Comment by pierreloicq** [comment]
Thank you kannes. 
Yes, but "around" does not seem precise about if its astride or not :-D.
A feedback from a native maybe ?

**Comment by Gustry** [comment]
Hi Pierre,
Nice feature, I wanted to give it a try but I got a compilation error:
```
/Users/etienne/dev/cpp/QGIS/src/gui/symbology/qgsgraduatedsymbolrendererwidget.cpp:501:12: error: use of undeclared identifier 'cbxSymmetricAroundZero'
```

Also, you need to move from `qMin`, `qMax` to `std::min/max` and also `qAbs`

**Comment by Gustry** [comment]
You will need to fix the code layout by running the scripts/prepare-commit.sh and also the failing tests

**Comment by pierreloicq** [comment]
Hi all,
I am almost sure everything worked well but yesterday I realized that my checkboxes did not keep their states when I close the Layer Properties window and then reopen it. All the rest is ok. 
Did I understood correctly that I have to put these states as class members of core/symbology/qgsgraduatedsymbolrenderer to retrieve them in gui/symbology/QgsGraduatedSymbolRendererWidget::updateUiFromRenderer() ?
When doing this and for the moment, it does not work better. I often get a random result when I check the "symmetric around" checkbox, click ok, close, reopen. My manipulation is always the same, I don't understand why I have this random behaviour.
It looks like the constructor of QgsGraduatedSymbolRendererWidget is ran when I close the window (why ?) and at that moment, the state of my checkbox seem random but not the same as the state I will get when I reopen. Maybe there are 2 instances of qgsgraduatedsymbolrenderer ? 
I will push in some hours.

**Comment by pierreloicq** [comment]
Hello,
I found and resolved some lacks this week-end.
I still have to add the capability to save and load this new information in the qml/sld files.

**Comment by pierreloicq** [comment]
Hello,
Seems good now. The QgsDoubleSpinBox to enter the pivot value behave strangely sometimes (you have not finished to type the number that it is filed automatically). It crashes if I load a 2.14 project but I does not seem to come from my part: 
"Warning: Loading a file that was saved with an older version of qgis (saved in 2.14.11-Essen, loaded in 2.99.0-Master). Problems may occur."

**Comment by pierreloicq** [comment]
The test output the answer below. Am I supposed to document the setters and getters ?  (Others are not)
If yes, how ? Just some text in a multiline comment placed before the function ? 
Thank you

`
Unacceptable missing documentation:


Class [NON-XML-CHAR-0x1B][33mQgsGraduatedSymbolRenderer[NON-XML-CHAR-0x1B][0m, 29/55 members documented

[NON-XML-CHAR-0x1B][1m[NON-XML-CHAR-0x1B][33m  astride()[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][1m[NON-XML-CHAR-0x1B][33m  listForCboPrettyBreaks()[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][1m[NON-XML-CHAR-0x1B][33m  setAstride(bool astride)[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][1m[NON-XML-CHAR-0x1B][33m  setSymmetryPoint(double symmetryPoint)[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][1m[NON-XML-CHAR-0x1B][33m  setUseSymmetricMode(bool useSymmetricMode)[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][1m[NON-XML-CHAR-0x1B][33m  symmetryPoint()[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][1m[NON-XML-CHAR-0x1B][33m  setListForCboPrettyBreaks(QStringList listForCboPrettyBreaks)[NON-XML-CHAR-0x1B][0m
[NON-XML-CHAR-0x1B][1m[NON-XML-CHAR-0x1B][33m  useSymmetricMode()[NON-XML-CHAR-0x1B][0m
`

**Comment by Gustry** [comment]
> The test output the answer below. Am I supposed to document the setters and getters ? (Others are not)

AFAIK, all new members since QGIS 3.0 require documentation. That's why some previous members haven't documentation yet

**Comment by pierreloicq** [comment]
Hello,
I wanted to resolve the conflict online. I did the modifications then clicked on "commit merge". Looks like it merged master into my branch. But the conflict is still there (I guess because resolving a conflict needs to be able to master ?)
Is there any way to cancel this merge ?
Or I pull the changes on my local prettyBreaksAroundZeroByTickingBox branch and push again ?
Or an authorized person can resolve the conflict ?
Thank you

**Comment by elpaso** [comment]
I've never used the online way, but you can revert the merge locally and push -f to go back to your previous state.
To resolve a conflict locally you normally have to rebase from origin/master (if the  official qgis repo is named origin) and resolve conflicts manually, then commit and push -f

**Comment by pierreloicq** [comment]
Ho, it looks like there is not conflict anymore. But the tests didn't launch. Is it possible to launch the Travis test manually ? 

if the answer is "commit again", I need to ask you about my git problems:

The merge master-> prettyBreaksAroundZeroByTickingBox occurred here on the website, and after correcting the conflict on my local branch, it didn't want me to push because there was more work here than on my local branch. So, while staying on the prettyBreaksAroundZeroByTickingBox branch, I did:

- git pull origin: it downloaded 2080 commits + python/core/symbology/qgsgraduatedsymbolrenderer.sip (modified on both sides)
- I solved the conflict in python/core/symbology/qgsgraduatedsymbolrenderer.sip
- git add python/core/symbology/qgsgraduatedsymbolrenderer.sip

now, if you tells me it's ok, I can add the 2080 supplementary commits, commit and push.
Thank you

**Comment by Gustry** [comment]
You can close/reopen the PR, it should retrigger travis

**Comment by pierreloicq** [comment]
test output: "The job exceeded the maximum time limit for jobs, and has been terminated."
I wanted to update master and rebase. Should I be in my local master to pull master, or we don't care ?

```
git checkout master
    Déjà sur 'master'
    Votre branche est à jour avec 'origin/master'. (origin = my repo, upstream = qgis repo)
git pull upstream --rebase
    Vous avez demandé de tirer depuis le dépôt distant 'upstream', mais sans indiquer
    la branche. Comme ce n'est pas le dépôt distant par défaut dans la configuration
    pour la branche actuelle, vous devez spécifier la branche avec la commande.
git pull upstream/master --rebase
    fatal: 'upstream/master' does not appear to be a git repository
    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.
```

**Pull request closed without merging**
