### PR TITLE
Attribute form warn on uncommitted changes

### PR DESCRIPTION
**Pull request by m-kuhn**
When a user wants to commit changes and has an unconfirmed attribute editor open, he will be asked if he wants to accept or dismiss these changes before the commit.

The old behavior was to keep the changed values visible in the form but disabling the form which was very misleading.

### CODE REVIEW

**Comment by 3nids** [comment]
This is indeed much better.

Small issue to me, the reset button will reset to before committing values, so if you modify the values from another form you get out of snyc.

In general, it is quite an issue that the form is not kept up to date. While playing a bit with opening 2 forms, there are many cases where you loose information.

Thoughts?

**Comment by m-kuhn** [comment]
If you have 2 forms open in parallel and edit both of them, at what point should they be synchronized (with each other and with the layer)?

 * While typing in form A, should the same keystrokes be replayed "live" on form B and also applied to the layer (seems quite heavy to me, and constraints will be quite hard to impossible to handle correctly)
 * When confirming a feature on form A (or modifying it with a script), should form B be updated to reflect these changes? Wouldn't it be surprising in some scenarios to be typing in a field which gets changed because a script decides to write to that layer?
 * When form A is confirmed, should each field on form B be checked for changes and only unchanged fields be updated?
 * Something else?

**Comment by 3nids** [comment]
I would say that you don't do anything until something really changed on the layer (by applying form changes or by any other mean on the layer).

Once you get a change, the open form detects it and ask if it should update the changed fields (and all its fields), so this means it will erase any change in the form, but the user is aware of this.

**Comment by m-kuhn** [comment]
In a situation where you save a project with 3 forms open and all of
them with different changes (which is a quite silly situation, but I
guess that's what we are discussing after all...) wouldn't this become a
pretty messed up orgy of warning dialogs on saving?

**Comment by m-kuhn** [comment]
I think there's now a functionality in place that [prevents users from re-opening the form for the same feature repeatedly](https://github.com/qgis/QGIS/commit/20197c2fa31e454b095be6b68771274ec5540c39). Is this still required?

**Pull request closed without merging**
