### PR TITLE
Move editor tools into editors folder

### PR DESCRIPTION
**Pull request by NathanW2**
## Description

Adds a Qt Creator template for a test
Also, moves some of the Qt creator styles and licence to editors\QtCreator\ to clean up folders a bit

Copy templates folder into %APPDATA%\QtProject\qtcreator to use.

image

### CODE REVIEW

**Comment by NathanW2** [comment]
@nyalldawson @m-kuhn

**Comment by nyalldawson** [comment]
Looks great - should be a massive time saver!

**Comment by nyalldawson** [comment]
Could we make others for core/gui/app/analysis class too?

**Comment by NathanW2** [comment]
@nyalldawson we could pretty easy yep.

**Comment by NathanW2** [comment]
Some code snippets might also be a also be a good idea.

**Comment by m-kuhn** [comment]
neat

**Pull request merged**
