### PR TITLE
Fix plugin loading from zip (dependencies followup)

### PR DESCRIPTION
**Pull request by elpaso**
See: https://github.com/qgis/QGIS/pull/9619#issuecomment-481237418

### CODE REVIEW

**Comment by m-kuhn** [comment]
I still get this on latest master

```
An error occurred during execution of following code:
pyplugin_installer.instance().installFromZipFile(r'/home/mkuhn/dev/layer_protector_plugin/LayerProtector.zip')


Traceback (most recent call last):
  File "", line 1, in 
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/pyplugin_installer/installer.py", line 611, in installFromZipFile
    self.processDependencies(pluginName)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/pyplugin_installer/installer.py", line 642, in processDependencies
    to_install, to_upgrade, not_found = find_dependencies(plugin_id)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/pyplugin_installer/plugindependencies.py", line 68, in find_dependencies
    plugin_deps = __get_plugin_deps(plugin_id)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/pyplugin_installer/plugindependencies.py", line 32, in __get_plugin_deps
    parser = metadata_parser[plugin_id]
KeyError: ''


Python version:
3.7.2 (default, Mar 21 2019, 10:09:12) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]

QGIS version:
3.7.0-Master 'Master', a0a8e49e8f

Python path:
['/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python', '/home/mkuhn/.local/share/QGIS/QGIS3/profiles/default/python', '/home/mkuhn/.local/share/QGIS/QGIS3/profiles/default/python/plugins', '/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/plugins', '/usr/lib64/python37.zip', '/usr/lib64/python3.7', '/usr/lib64/python3.7/lib-dynload', '/home/mkuhn/.local/lib/python3.7/site-packages', '/usr/lib64/python3.7/site-packages', '/usr/lib/python3.7/site-packages', '/home/mkuhn/.local/share/QGIS/QGIS3/profiles/default/python', '/home/mkuhn/dev/stupid_project']
```

**Comment by m-kuhn** [comment]
Turns out the plugin zip was not standard-compliant (but that still shouldn't result in an exception probably) (i.e. file called `LayerProtectormetadata.xml` instead of `LayerProtector/metadata.xml`)

**Comment by elpaso** [comment]
@m-kuhn thanks, I'll handle the exception by skipping the dependencies handling altogether, even if I think that if the metadata could not be found we should probably abort earlier.

**Comment by m-kuhn** [comment]
Yes, that sounds very true!

**Comment by elpaso** [comment]
@m-kuhn Would you mind sending me the broken plugin to reproduce the issue?

**Comment by m-kuhn** [comment]
Sorry, I already deleted it.

But basically, go to any plugin git and do `git archive --prefix=xxx --format=zip > broken.zip`

**Comment by elpaso** [comment]
You meant `metadata.txt` and not `.ini` did you?

**Comment by m-kuhn** [comment]
Yes. In fact I'm not even sure it's the metadata file or some other borken structure.

**Comment by elpaso** [comment]
Funny: you can install a plugin without `metadata.ini` without any issue (after I handled the exception) ...
all you get is a red "missing metadata " when you browse for it in the manager.

**Comment by elpaso** [comment]
for reference: https://github.com/qgis/QGIS/pull/9780

**Pull request merged**
