### PR TITLE
Asyncronously render composer map previews 

### PR DESCRIPTION
**Pull request by nyalldawson**
Found this interesting commit floating away on Sourcepole's fork, and thought that upstream could benefit from this improvement too.

I'd say this is a risky change, but we've got a lot of time before release to iron out any bugs. I've tested quite extensively and it's a big improvement, and verified with valgrind that there's no leakage involved.

### CODE REVIEW

**Comment by nirvn** [comment]
Working quite nicely on my machine. Great to have the freeze-on-composer-opening gone.

**Comment by nyalldawson** [comment]
> Working quite nicely on my machine. Great to have the freeze-on-composer-opening gone.

Thanks for the test run!

**Comment by nyalldawson** [comment]
@nirvn 
Mind giving this another test run? I've refined it somewhat, so now the last complete map render is always drawn until a new render is finished. This avoids the map blanking out during refresh operations.

**Comment by nirvn** [comment]
@nyalldawson , using the cache prior to completion of a new rendered cache is working well. Actually, it works so well I think we should remove the "cache" render mode for map item (as well as the [ update preview ] button), and replace that with a [x] render map content, which if de-activated would == rectangle mode. 

That said, the only tiny UX issue I have (which should *not* hold off merging this PR) is the initial "blank" map item, which can take 5-10s to fill. Could we not have a "map rendering..." fat text label into the map item when there's no cache available yet? That would only occur once after opening the composer window.

**Comment by nyalldawson** [comment]
> @nirvn using the cache prior to completion of a new rendered cache is working well. Actually, it works so well I think we should remove the "cache" render mode for map item (as well as the [ update preview ] button), and replace that with a [x] render map content, which if de-activated would == rectangle mode.

Agreed, except that render mode is rather flaky and doesn't always refresh. We need to fix that first. (e.g. https://issues.qgis.org/issues/10971)

> That said, the only tiny UX issue I have (which should not hold off merging this PR) is the initial "blank" map item, which can take 5-10s to fill. Could we not have a "map rendering..." fat text label into the map item when there's no cache available yet? That would only occur once after opening the composer window.

Can you try the latest commit?

**Comment by nirvn** [comment]
@nyalldawson newly added maps now work; can't spot any more issues.

**Comment by nyalldawson** [comment]
#4504 is a prerequisite to avoiding a crash on exit with this work

**Pull request merged**
