### PR TITLE
Remove unnecessary instance() calls

### PR DESCRIPTION
**Pull request by Koyaani**
The static `instance()` method is used to retrieve the class singleton. However, some methods of these classes are also static, making the `instance()` call useless. This PR deletes these calls.

I didn't remove all of them because in some cases, it could potentially create a little confusion. For example, with this line:
`const QSet<QString> groups = qgis::listToSet( QgsProject::instance()->bookmarkManager()->groups() << QgsApplication::instance()->bookmarkManager()->groups() );`
`QgsApplication::bookmarkManager()` is static, but `QgsProject::bookmarkManager()` is not. So I left the line in this state. But maybe it's an unnecessary worry?

It is in the continuation of the PR #46453. I use the same tool : `readability-static-accessed-through-instance` in Clang-tidy. Another PR will follow this, with more various warnings.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks again!

> QgsApplication::bookmarkManager() is static, but QgsProject::bookmarkManager() is not. So I left the line in this state. But maybe it's an unnecessary worry?

I think it's fine to change them as well in this case. (I still hope we can remove `QgsProject::instance()` one day)

**Review by m-kuhn — APPROVED** [review]

**Comment by nyalldawson** [comment]
> I think it's fine to change them as well in this case.

+1

**Comment by Koyaani** [comment]
Ok I do this!

> I still hope we can remove QgsProject::instance() one day

@m-kuhn Does that mean you want to turn all methods into static?

**Comment by m-kuhn** [comment]
> Ok I do this!

Great

> 
> > I still hope we can remove QgsProject::instance() one day
> 
> @m-kuhn Does that mean you want to turn all methods into static?

It means passing the project through a context / dependency injection in every call stack, so there is no more need for the `instance()` method.
See https://github.com/qgis/qgis4.0_api/issues/117.

**Pull request merged**
