### PR TITLE
fix NULL field in size expression beeing drawn

### PR DESCRIPTION
**Pull request by vmora**
the expression generated by the assistant was causing symbol with size
expr evaluated to NULL to be drawn with default size, wich is not what
the default should be.

The generated size expression is now composed with coalesce(...,0)
so the symbol is not drawn when the size expression is NULL

The expression is still recognized without the coalesce to allow the
legend to be drawn even in the absence of coalesce: this can be used
to have the default size for NULL expression and use a conditional expr
fro color to highlight symbols where value is NULL.

### CODE REVIEW

**Comment by vmora** [comment]
@nyalldawson, @haubourg with the last commit, everybody should be happy, the assistant as a field to specify the size when the expression evaluates to null.

**Comment by haubourg** [comment]
Perfect for me!

**Comment by haubourg** [comment]
@vmora @nyalldawson Hi guys, we have some interesting feedback in redmine on scaling implementation here http://hub.qgis.org/issues/13033  Opinions?

**Comment by vmora** [comment]
@haubourg I replied on http://hub.qgis.org/issues/13033

@nyalldawson I see that you put the assistant at the symbol level, great ! Also, I don't see where to connect QgsLayerPropertiesWidget::changed() to QgsSymbolsListWidget::updateDataDefinedMarkerSize(), or something like that, to update symbols expressions when the size changes or a symbol is added. What do you think of that, and do you know how I can do it ?

**Comment by nyalldawson** [comment]
@vmora give me an hour or so and i'll look into it, i'll let you know!

**Comment by nyalldawson** [comment]
merged manually, thank you!

**Comment by nyalldawson** [comment]
@vmora I think it would need to be done in QgsSymbolV2SelectorDialog::addLayer() A possible approach (just thinking out load... there might be issues ;) ) would be:
 add a "applyDataDefinedOverrides( QgsSymbolLayerV2* layer)" to QgsSymbolV2. This method would check for any symbol level data defined properties (size/rotation/width) and then call setDataDefinedProperty for the layer to copy that property to the new layer. Then in QgsSymbolV2SelectorDialog::addLayer() you'd just need to insert a

    parentSymbol->applyDataDefinedOverrides( newLayer )

at around line 412

**Comment by vmora** [comment]
@nyalldawson  but this would not fix the loss of scale expression when changing one of the symbol sizes, would it ?

**Pull request closed without merging**
