### PR TITLE
porting to 3.0 of fix #15803

### LINKED ISSUE #15803: Preview in expression builder not always showing
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [6616](https://issues.qgis.org/issues/6616)
Affected QGIS version: 3.0.0
Redmine category:gui

---
The preview in the field calculator expression builder is often missing. This happens because the expression text is evaluated against the first feature in the layer. If the expression doesn't evaluate for the first feature there will be no text. 

Thanks Nathan for the explanation.

### PR DESCRIPTION
**Pull request by luipir**
## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
What's the content of # 15803?

**Comment by luipir** [comment]
@m-kuhn  https://hub.qgis.org/issues/15803

**Comment by luipir** [comment]
port to 3 of the 2.18 pr https://github.com/qgis/QGIS/pull/4306

**Comment by m-kuhn** [comment]
ah yeah, thanks. Sorry, it's hard to guess the content from an issue number only ;)

**Comment by luipir** [comment]
ok, I'll reformulate commit

**Pull request closed without merging**
