### PR TITLE
[ui] Reduce visual attention grab of the authentication settings wiget's warning label

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR addresses the UI issue #37070 .

Before vs. PR:
image

image

### CODE REVIEW

**Comment by elpaso** [comment]
Looks good, but from bold red to light grey it's a big jump, did you try to make it black (fully saturated)?

**Comment by nirvn** [comment]
@elpaso , the color is left to the OS or theme to decide. That said, I've removed the disabled state for the label, so it'll be black on default theme. Glad you like the change overall.

@elpaso , BTW, there's another UI/UX change which I would like to push. I think the tabs' order should be reversed, i.e. the "basic" tab comes before the more advanced "configurations" tab. It's an order that's to me a bit more logic IMHO. Also UX-wise, we can move from the basic -> to -> the configuration via the [ convert to configuration ] button, and not the other way around, which means we're better with the basic panel showing first.

**Comment by elpaso** [comment]
> @elpaso , the color is left to the OS or theme to decide. That said, I've removed the disabled state for the label, so it'll be black on default theme. Glad you like the change overall.
> 

Thank you.

> @elpaso , BTW, there's another UI/UX change which I would like to push. I think the tabs' order should be reversed, i.e. the "basic" tab comes before the more advanced "configurations" tab. It's an order that's to me a bit more logic IMHO. Also UX-wise, we can move from the basic -> to -> the configuration via the [ convert to configuration ] button, and not the other way around, which means we're better with the basic panel showing first.

That change was deliberate and I''m -1 on changing that.

What we were trying to do was to avoid/prevent/discourage as hard as we could the use of plain text unencrypted credentials stored in the project file XML (people tend to share these .qg[sz] files).

That request came explicitly from large (mainly government) organizations.

The big red warning was part of that effort, but I agree that a big red warning was a punch in the eye from a UX/UI point of view.

**Review by m-kuhn — APPROVED** [review]
Much better

**Comment by m-kuhn** [comment]
Regarding the advance vs. basic discussion.

I think whatever 80% of the people use should come first.
Is this authentication configuration meanwhile?
I find that many people still struggle to get the concept and set it up or that they explicitly want to bundle credentials in the project.
My feeling is that auth manager is still lacking some UX / quick start / functionality to deserve being the number one choice for everyone.

**Comment by elpaso** [comment]
> Regarding the advance vs. basic discussion.
> 
> I think whatever 80% of the people use should come first.

Mind sharing the source of your statistics?

> Is this authentication configuration meanwhile?
> I find that many people still struggle to get the concept and set it up or that they explicitly want to bundle credentials in the project.
> My feeling is that auth manager is still lacking some UX / quick start / functionality to deserve being the number one choice for everyone.

May be true, there is always margin for a better UX. Do you have anything in mind to make the process smoother?

The point here is that the default setting that allows people to store credentials in plain text in the project was a blocker for QGIS adoption in these large government organizations (we are talking about hundreds or thousands of users). 

Maybe the current warning is now sufficient but I doubt it.

**Comment by m-kuhn** [comment]
> Do you have anything in mind to make the process smoother?

- Initial configuration of an authid requires going through the authmanager dialog
  - If a project is opened with an unconfigured authid, the system asks for the password every time. Current situation is, the user has to copy the authid, go the the authentication manager, and create a new matching configuration. It would be good if it was possible to directly create this authid when asked for login credentials.
  - For an organisation wide setup of authids, the current possibilities are:
    - Copying an auth database to every user
    - Providing users with installation instructions including entering a cryptic id
    - It would be good if the authid could be specified in global_settings and the user guided in setting up login credentials for this authid.
    - Introduction of a global "default" authid, so generally this one would be used everywhere unless someone explicitly wants a "special" authid.
- It's currently not possible to share authentication credentials with a project (which usually ends up with the fact that it's sent by mail instead)

**Pull request merged**
