### PR TITLE
WIP: have CI not accept non-provider tests modifying source tree

### PR DESCRIPTION
**Pull request by strk**
See also GH-48904

References GH-25830 - repository files modified by `make check`

### CODE REVIEW

**Comment by strk** [comment]
And my commenting here does not seem to trigger a REMOVAL of the "stale" label from this issue, is this normal/expected/wanted behavior ? I'm talking here, why does the bot pretend there's no action ?

**Comment by nyalldawson** [comment]
>How can I solve this problem, without figthing with robots ?

Participate more often?

**Comment by strk** [comment]
> > How can I solve this problem, without figthing with robots ?
> 
> Participate more often?

I'm here, I'm partecipating, I'm commenting in this ticket, I'm describing a problem introduced by the use of Stale Bot, but the bot will close this ticket anyway unless I do the burocratic-only action of removing the "Stale" label from this ticket. It doesn't sound like a useful partecipation, if not in a war against the robots

**Comment by strk** [comment]
Still relevant, it's a reminder for me to work on this on next bugfixing drive. @nyalldawson would you consider it a bug in the stalebot if this comment of mine does NOT remove the "Stale" label?

**Comment by strk** [comment]
I'm pretty sure I won't even remember what was this about
on next bugfixing drive. Oh how useful it would be for this ticket
to remain open so when I search for open issues assigned to me I find
it. Or maybe someone with more experience than me about lifes with
bots will be so nice to add a link to the spreadsheet to directly
get the list of unfinished pull requests opened by us and closed by
the bot ?

**Comment by strk** [comment]
Interesting, removing the "stale" label does NOT reopen the pull request automatically, so what you are left with is a closed PR with NO "stale" label. Not easy to find it when you're looking for things to continue...

**Comment by nyalldawson** [comment]
@strk

Can I politely ask you to focus your efforts this cycle on fixing user facing bugs in qgis rather then focusing only on the test suite and ci? We have thousands of issues which affect end users, and fixing those is why we get funded bug hunts from these users in the first place...

**Comment by strk** [comment]
> Can I politely ask you to focus your efforts this cycle on fixing user facing bugs in qgis rather then focusing only on the test suite and ci? We have thousands of issues which affect end users, and fixing those is why we get funded bug hunts from these users in the first place...

Yes, you may of course ask but focusing on user facing bugs means trying to reproduce them in the first place and securing their fix means writing a testcase reproducing the bug and make sure it runs on every commit. Writing a testcase requires being able to run it to tell if it's working as expected. When working on an actual fix, we want NOT only to verify that the new test from failing become succeeding but also that no other pre-existing test is broken by the code change. Doing so requires either waiting for the Microsoft donated hardware to run the CI (in a very long queue of things such hardware is loaded with) or running the testsuite locally. Running the testsuite locally in turn currently changes a lot of source files so it's hard to tell which changes were made by you to fix the user-facing bug OR by the bogus testsuite.

If focusing on a user facing bug means pretending the above story does not exist, fixing a bug will continue costing much more time (and money) and thus make it less accessible to anyone, and QGIS will keep being so unstable. I believe a good testsuite is what keeps the number of user-facing bugs lower.

**Comment by nyalldawson** [comment]
@strk 

I understand how unit tests work already. 

> I believe a good testsuite is what keeps the number of user-facing bugs lower.

Completely agree, there's no argument there.

What I fail to comprehend is how there's any value for qgis.org in a never ending project consuming thousands and thousands of euros and years of time, just for one developer to get to their "ideal" setup. How come every other qgis funded bug hunter is able to just dive in and start solving real tickets right away, without any mucking around?

This effort really **isn't** a justifiable use of the big fixing money. I don't want to have to do this, but in all good conscious if you keep proceeding down this path then I'll have no alternative but to raise my objections formally with the PSC.

**Comment by strk** [comment]
> This effort really isn't a justifiable use of the bug fixing money

My opinion is that fixing bugs before having fixed the testsuite isn't a justifiable use of bug fixing money. Please raise your objection to the PSC. If the PSC consensus is that the testsuite serves its purpose I'll act consequently (either accepting to work in suboptimal conditions or giving up on wasting my time fighting with a CI bot run by a proprietary software on someone else's computer).

**Comment by m-kuhn** [comment]
@strk as a long-time contributor of countless volunteer hours to fighting windmills on CI and testing, I can understand why you are working on improving this.
There may be some things that are not *perfect* in this CI setup, but there's also a *balance* to keep between the required effort and the level of perfectness.
QGIS' financial resources are limited and should be spent on what a wider audience agrees on. I think it's fair to the rest of the developer community and the sponsors to follow the community lead here and to spend bug fixing time and budget on fixing bugs.
If you think it is worth improving the testing system or CI setup, there are processes in place to get extra funding (QEP to get to an agreement on the *what* and grant proposals for the coins).

I really like the end goal of this pull request, but the point is that the bug-fixing budget is earmarked for fixing bugs.

**Comment by strk** [comment]
> what a wider audience agrees on

This is a risky statement. QGIS is supposed to have a _steering_ committee which decides on the direction of the project. What is the "audience" you are referring to ? Is that the audience of QGIS core committers ? The audience of PSC ? The audience of users ?

I'm being granted a fixed number of hours to partecipate in a "bugfixing initiative" which is payed by the "QGIS Foundation" so I think I should respond to the PSC for what concerns what bugs I can spend time on and what bugs I can't. This is why I recommended to bring this up with the PSC.

**Comment by m-kuhn** [comment]
I was referring to reactions from several core developers on a [comment](https://github.com/qgis/QGIS/pull/49124#issuecomment-1249168980) in this pull request. This is the widest audience I could witness related to this topic and also one which I trust to have technical and community expertise in this matter. 

Bringing this up with the PSC for a generally trusted authoritative answer is an option to explore, especially given it has been raised multiple times now.

**Comment by strk** [comment]
> This effort really **isn't** a justifiable use of the big fixing money. I don't want to have to do this, but in all good conscious if you keep proceeding down this path then I'll have no alternative but to raise my objections formally with the PSC.

Please do so.

I find fixing bugs without an offline way to verify the fix
does not introduce regressions is not a justfiable use of project
money, but if the PSC decides that's how they want to spend the money
I'll put the time spent on this (and similar) tickets on my own
expenses

**Comment by mbernasocchi** [comment]
Dear all, thanks for raising this with the PSC,
We have discussed this issue at length and published guidelines for the bug-fixing program at https://lists.osgeo.org/pipermail/qgis-psc/2022-October/009883.html

As a result, the PSC does not support the use of QGIS Bug Fixing funds being used to resolve this issue. The appropriate way to ask for funding if you wish to work further on this issue is to propose a grant proposal.

**Comment by strk** [comment]
Reopening to check if https://github.com/qgis/QGIS/commit/fe410ec92051b5be1d73b5753f05a7cfdc004112 really fixes https://github.com/qgis/QGIS/issues/23991

**Comment by strk** [comment]
According to the commit log it takes GDAL-3.4.2 or higher for the fix to be in effect, so we might need to wait for CI to use a newer distribution OR introducing a blacklist for files that we accept being changed IFF gdal < 3.4.2

**Comment by strk** [comment]
Why is the "Reopen and comment" button disabled for me ? Did the policy about who can re-open pull request change ? Is "github-actions" bot gained more power than me ? Shall I seek for asylum ?

**Comment by strk** [comment]
PR moved to #52510

**Pull request closed without merging**
