### PR TITLE
[i18n] integrate esperanto translation

### PR DESCRIPTION
**Pull request by sikmir**
Esperanto translation gots over 35% (_minimum_perc_ threshold), so it's time to integrate.

### CODE REVIEW

**Comment by jef-n** [comment]
Please separate code changes from translation.  The translations are pulled from transifex.

**Comment by sikmir** [comment]
Rebased, translation file removed.

**Comment by sikmir** [comment]
> The translations are pulled from transifex.

@jef-n Hi Jürgen, there are no translation updates since 2.16.0 (Jul 8, 2016). So new translations are still not available. Could you please pull them from Transifex?

**Comment by jef-n** [comment]
We don't maintain the translations for older releases in transifex - only current master.

**Comment by sikmir** [comment]
@jef-n I say about current master. There are no translation updates in the master. Latest release 2.18.9 does not include new translations as well.

**Comment by jef-n** [comment]
I don't understand what you're saying.  I obviously can't pull anything from transifex, that is not there.

**Comment by mach0** [comment]
My guess is that there is no esperanto entry in the tsstats page yet and therefore probably no language that is in the about page. The limit of 35% is there and the language should be pulled in and available in the GUI.
next question would be which flag to choose for esperanto?

**Comment by saberraz** [comment]
@mach0 how about this :)
https://en.wikipedia.org/wiki/Esperanto#/media/File:Flag_of_Esperanto.svg

**Comment by mach0** [comment]
@saberraz yes - I was too early with my comment ..
Everything is available in master including the flag - so no problem and everything is as it should be .. 
Issue can be closed ..

**Comment by jef-n** [comment]
"Merged" is closed, isn't is?

**Comment by mach0** [comment]
I hope so ;) . Didn't take a look - I only saw "comment" ;)

**Pull request merged**
