### PR TITLE
[needs-qa]Usr bin env

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description

I'm testing to configure a CI with Jenkins for FreeBSD.

I have good results for compilation (and execution) but tests fail because of scripts with "linuxisms".
In addition, some contributing scripts are also not "portable".

Git error from previous PR...
History for the previous PR:

@landryb Do you have an opinion/review/help? :)

> Since /usr/bin/perl, /usr/bin/python or /bin/bash are not "portable" I suggest to replace it to /usr/bin/env XX.
> This requires a thorough check.
> 
> > @m-kuhn 
> > That's the kind of pull request which normally noone wants to take responsibility for because everything works right now and it could potentially break some scripts.
> > So it would be great if you could bring forward some good real world use cases as arguments that justify this move.
> 
> Hello,
> 
> I do not obviously want to break everything, that's why I propose a thorough review. My message is indeed lacking explanations.
> 
> Why, I propose it?
> I try to be able to compile (and contribute) from FreeBSD. I always sent my commits from a debian VM, but I noticed problems by trying a commit from FreeBSD. On *BSD (and maybe others), bash is not the default shell and is not in /bin but in /usr/local/bin just like perl and python. We have already made the modifications to compile on BSD, this proposal continues in this way with the hope to be able to contribute directly from BSD. Here is my real world use case.
> Besides, there are already many scripts, using the portable shebang "/usr/bin/env".
> 
> For the flags after the shebang (unify_includes.pl and doxygen_space.pl), I noticed that Linux ( debian ) does not know how to interpret them that's why I removed them and include in the astyle.sh script.
> 
> If you agree in the initiative, there will be other modifications to be brought but I have to continue my tests, for example:
> BSD can also use GNU tools for sed and split because the used options are not compatible with the BSD tools, except for egrep...
> 
> Regards.
> 
> > @m-kuhn 
> > I see, sounds good to me, I'd be in for giving it a try. Would you also want to add it to the spellchecker to make it futureproof?
> 
> For python, I noticed (and read for other systems) that " /usr/bin/env python " can cause problems because python must be an alias for python2 or python3 or does not exist (my case for one of my installations...).
> Also, the most portable is to add directly the version of python aka "/usr/bin/env python2" or "/usr/bin/env python3".
> 
> Also, we could adapt the Shebangfix (manual script) from FreeBSD in the scripts?
> It will apply the "most compatible" practice in new scripts.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by landryb** [comment]
`env bash` or `env python2`/`env python3` is also the recommended way to set a shebang for scripts on OpenBSD.

**Comment by 3nids** [comment]
yes, please!
what about using python3 everywhere?

**Comment by lbartoletti** [comment]
@3nids yes, I will put python3 everywhere

**Comment by 3nids** [comment]
any chance to handle the gnu coreutils on mac?
i.e. using gsed, g* instead of sed or whatever?

**Comment by lbartoletti** [comment]
I'm looking at this right now, it's a pain...
Can we merge this first?

**Comment by 3nids** [comment]
Yes, there is just a conflict now

**Comment by lbartoletti** [comment]
I reinvestigated, it's possible to make scripts available on more platforms, like your works [here](https://github.com/qgis/QGIS/blob/be8d1d77825a1387d309b62fe75095dec3ac3362/tests/code_layout/test_sipfiles_uptodate.sh), but I prefer to do it on another PR

**Comment by 3nids** [comment]
I guess using `alias sed=gsed` would be more clever than what I did....

**Comment by lbartoletti** [comment]
As far as I know, this is the best method, because if you set an alias you can have other conflicts.
Another way is to create script for GNU and another for BSD (POSIX?) but it's too heavy...
Since, all scripts are GNUed, the easiest way is to use coreutils which is available on Mac, *BSD and cygwin.

**Comment by lbartoletti** [comment]
Can the packagers check the qa of this PR (@jef-n for windows? who else on linux?)?

**Comment by lbartoletti** [comment]
Latest reviews and qa?

We need it for tests/CI and contributions.

Thanks.

**Comment by 3nids** [comment]
as written a few days ago, you need to rebase on master

**Comment by lbartoletti** [comment]
Isn't good with the last PR?

**Comment by 3nids** [comment]
nope, there are conflicts

**Comment by Gustry** [comment]
Only if you use the 'Rebase option' in github. You might be able to use the 'merge button' @3nids

**Comment by nyalldawson** [comment]
I've had to revert this - it's broken the linux builds and will need to be reworked.

**Pull request merged**
