### PR TITLE
Follow up 1f8708f, fix src / scheme detection

### PR DESCRIPTION
**Pull request by nirvn**
## Description
@elpaso , here's a follow up fix to your OGR remove / file PR. Without this, all local data sources are flagged as remote because of the broken isVsiCurl conditional check.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by elpaso** [comment]
@nirvn are you sure? It looks to me that this PR does not change anything. What was broken exactly?

**Comment by elpaso** [comment]
@nirvn compiler?

**Comment by nyalldawson** [comment]
The QLatin1String brackets are different

**Comment by elpaso** [comment]
@nyalldawson ouch, got it. It's not the initializer list, it's the misplaced bracket.

**Comment by elpaso** [comment]
@nirvn I'll fix it.

**Comment by elpaso** [comment]
@nirvn there was any particular reason to drop the inizializer list in favor of the assigment initializer?

**Comment by elpaso** [comment]
Fixed in master

**Comment by elpaso** [comment]
> A note on that: switching to a more traditional assignment init. had the compiler throw an error because of the missing parenthesis. I hope compilers will be more sensitive with initiatizer list in the future :)

That's a good point indeed, I started using them extensively after reading this article: 

https://isocpp.org/blog/2016/05/quick-q-why-is-list-initialization-using-curly-braces-better-than-the-alter

but now I might reconsider my decisions.

**Pull request closed without merging**
