### PR TITLE
[processing] Add test & adjust handling of negative distance value for multi ring (constant) algorithm

### PR DESCRIPTION
**Pull request by nirvn**
## Description
@nyalldawson , turns out the algorithm needs dedicated logic for negative buffer values. This PR fixes that, and adds a test for negative value.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
@alexbruy , as you are the original author of this algorithm, I’m seeking your opinion on the negative distance value output here. At the moment, this PR adjusts (fixes really, since it wasn't enabled/supported before) the negative distance value output to match the right part of the screenshot below:

image

In the shot above, I'm comparing positive distance (+X) output (left) vs. negative distance output (-X) right) using the same nb. of rings (2). 
- on the left, the orange polygon has a ringId value of 1 and a distance value of X, and the green polygon has a ringId value of 2 and a distance value of X*2;
- on the right, the orange polygon has a ringId value of 1 and a distance value of -X, the green polygon has a ringId value of 2 and a distance value of X*-2, and the gray polygon has a ringId and distance set to 0.

You'll notice the negative distance output has an extra polygon (gray). We could have negative distance value output match the same behavior as positive distance value output, which would result in:

image

That said, it'd result in a less-than-ideal (arguably problematic) output when the nb. of rings of set to 1, when a negative distance value output would end up equating the input layer:

image

Are you OK with the way this PR handles negative distance value output?

**Comment by nirvn** [comment]
I should have added that my preference - after giving it a lot of thinking - is to go with the current proposed output coded in this PR (i.e., the one with a gray polygon). 

In fact, for QGIS 4.0, I'd suggest re-visiting the output of the positive distance value output to match the behavior of the negative distance value output:
image

To me, the output on the left side makes more sense and better matches the algorithm's description (i.e., multi-ring donut buffers). That output can then be used to do statistical analysis. For e.g., counting the nb of overlapping points in the 0 to X distance buffer area, X to X*2 distance buffer area, etc.

**Comment by DelazJ** [comment]
> 
image
> on the right, the orange polygon has a ringId value of 1 and a distance value of -X,

Is it not the same as the original feature (with ring)? With a distance of -X I would expect it to be at X distance from the original feature edges ( ie at the green one place). And so on. In which case, using a single negative ring would output a different feature than the original.

**Comment by nirvn** [comment]
@DelazJ , no, the polygons don't overlap, those are donuts.

**Comment by DelazJ** [comment]
@nirvn Indeed was mixing with negative buffer.
Sorry I don't test the existing alg and don't know how it'd break things (maybe this is why you suggest 4.0) but what about a "Fill inner/interior{?} ring" checkbox parameter? If i ask a single ring of X or -X, I really get a *donut* of that distance. And if the option is checked i get a second feature which represents the initial feature for X>0 and an interior buffer feature for X<0? This way we always output donuts unless user asks something else (fill the interior).

**Comment by havatv** [comment]
I support @DelazJ in that a checkbox parameter would be a good solution. Since we can't know what the users want to achieve, it is better to provide flexibility (if it does not cost us too much).
I suggest that we use "Rings only" or "Only rings" as the name of the checkbox.  It does not matter to me if the default is *on* or *off* by.

**Comment by nirvn** [comment]
@DelazJ , I'd still argue that a `[x] fill inner` option should create a separate polygon instead of dissolving the inner area with the 1st outer donut. It's therefore a QGIS 4 TODO :). I'll keep this on my radar.

**Comment by havatv** [comment]
@nirvn , since the question of dissolving the inner area or creating a separate polygon for the inner area is discussed here, I think it deserves a separate checkbox.

**Comment by nirvn** [comment]
OK, no matter what we decide on this option, I'll need to merge this commit (which is a fix-only, no new feature) separately in order to backport to 3.4.

I'm still blind to the benefits of such an option here really, so I might need some more talking :)

**Comment by nirvn** [comment]
@DelazJ , so we're essentially saying the same thing / describing the same wanted behavior. It can't happen without modifying the way we output positive distance value results for filled ring.

Something to look forward to in Q4.0 :)

**Comment by nirvn** [comment]
@havatv , @DelazJ ,

[X] include input area
[X] dissolve input area

?

**Comment by havatv** [comment]
These two options are only relevant for polygons.
"[X] include input geometry" is fine
"[X] dissolve input geometry" needs some more explanation or be changed to something like
"[X] combine input geometry with inner ring"
The last option is not useful if the first buffer distance is negative

**Pull request merged**
