### PR TITLE
Set minimal supported distribution to xenial in build doc

### PR DESCRIPTION
**Pull request by DelazJ**
## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Can you add some reasoning?

**Comment by DelazJ** [comment]
My understanding was that the required dependencies are not all available in an old release like precise. Am I wrong?

**Comment by m-kuhn** [comment]
I don't know.
Where did you get this information from? Is there a particular dependency that you are referring too?

**Comment by DelazJ** [comment]
Where? I guess it'd be something I inferred from a discussion on a list. Which one? _Non lo so piu'._ And probably because we do not [support it](https://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu) (maybe because it's EOL also) nor provide dependencies list in the [INSTALL file](https://htmlpreview.github.io/?https://github.com/qgis/QGIS/blob/master/doc/INSTALL.html#toc6) (I realize that xenial is no longer in the list btw).
Anyway, this is a commit I made months ago after the _unknown_ thread and finding it in my repo today I just rebased and pushed online. So if it's not relevant/correct, we can simply scratch it. No harm.

**Comment by jef-n** [comment]
Better yet avoid references that tend to outdated - as in c5c6877513

**Comment by DelazJ** [comment]
OK. Thanks @jef-n 
Just from my personal knowledge, was my understanding about precise being somehow incompatible (or too hard to compile?) wrong?

**Comment by jef-n** [comment]
The [download page](http://localhost/~fischer/qgis/en/site/forusers/alldownloads.html#debian-ubuntu) has footnote on why some of the distributions (like xenial) have limited support.  But elder dists that are not supported are not listed at all.   precise probably doesn't have a recent enough Qt and GDAL.  Xenial's GDAL already is too old for 3.4 (therefore ubuntugis is neede), but it's Qt is also too old for 3.6 and above.

**Comment by DelazJ** [comment]
Thanks.

**Pull request closed without merging**
