### PR TITLE
Add API to determine which environment the QGIS libraries are running in

### PR DESCRIPTION
**Pull request by nyalldawson**
The new

    Qgis.environment()

call will return an Environment enum, reflecting whether the code is running under the Desktop application, server, qgis_process, external scripts or mobile applications

This is designed to allow plugins to adapt their behavior depending on what environment they are running under.

### CODE REVIEW

**Comment by nyalldawson** [comment]
The initial use case here is to fix https://github.com/qgis/QGIS/issues/45935, be providing a way for processing to determine if it's running from outside of the qgis desktop application (in which case the grass and saga plugin providers should also be initialised when calling Processing.initialize())

**Review by elpaso — APPROVED** [review]

**Comment by 3nids** [comment]
would it make sense that qgis_platform variable returns this?
or to avoid any compatibility issue, create a QGIS function returning this?

**Comment by nyalldawson** [comment]
@3nids 

> would it make sense that qgis_platform variable returns this?

Good point -- I should just adapt QgsApplication::platform instead

**Comment by nyalldawson** [comment]
@3nids alternative version here: https://github.com/qgis/QGIS/pull/46300

**Pull request closed without merging**
