### PR TITLE
[Qt6][Oracle] Fix oracle provider for Qt6

### PR DESCRIPTION
**Pull request by troopa81**
include #51153

### CODE REVIEW

**Comment by 3nids** [comment]
@troopa81 do you plan to switch the base Docker image from Fedora to Ubuntu for the CI with Qt6?
Could you by any chance share the Dockerfile?

**Comment by troopa81** [comment]
> @troopa81 do you plan to switch the base Docker image from Fedora to Ubuntu for the CI with Qt6?
Could you by any chance share the Dockerfile?

Not really for now, not sure what's the strategy is here, continue with fedora or go back to ubuntu. It looks like people are working to make PyQt work on fedora  #51060

For now, I just added the needed instruction in qt6 fedora dockerfile so provider could compile, but tests (like all other python tests) won't be run.

**Comment by troopa81** [comment]
unrelated protobuf error

**Comment by nyalldawson** [comment]
@troopa81 where is this sitting? Could you fix the conflicts so we can merge?

**Comment by troopa81** [comment]
> @troopa81 where is this sitting? Could you fix the conflicts so we can merge?

Just waited someone to review. Conflicts fixed

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
