### PR TITLE
Layout chapter IV: snapping and guides

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR revolutionizes(!) snapping within layouts.

Highlights are:
- a new snapping marker indicator showing when/where snapping will occur
- snapping to guides now happens when drawing new layout items (this didn't work in composer - only snapping to grids happened while drawing new items)
- snapped cursor position is shown in status bar whenever a snapped point will be used
- New dock widget showing snap guides for current page - allows creation of snap lines at specific locations, and adjusting position of existing guides to exact coordinates
- Unlike in composers in 2.x, Layouts in 3.0 adopt the standard UX of dragging out rulers to create guide lines (instead of clicking on a ruler position to create a guide)
- better feedback in the ruler when a guide can be dragged
- New button in guide manager to apply current page's guides to all other pages. This allows resetting all other pages to use the guide configuration for the current page. Since guides are now single page only (required to handle mixed page size/orientation layouts), this is a shortcut to allow guide configuration to be setup on a single page and then easily transferred to all other pages in the layout.
- New right click context menu on rulers (with guide/ruler related options)
- Refined snapping logic: Previously grids would always take precedence when both a grid
and guide were within tolerance of a point. Now, guides will always take precedence - since they have been manually set by users we make the assumption that they have been explicitly placed at highly desirable snapping locations, and should be selected over the general grid. Additionally, grid snapping was previously only done if BOTH x and y could be snapped to the grid. We now snap to the nearest grid line for x/y separately. This means if a point is close to a vertical grid line but not a horizontal one it will still snap to that nearby vertical grid line.
- 4,833 new lines of beautifully refactored and cleaned up code and unit tests ;)

### CODE REVIEW

**Comment by nirvn** [comment]
> New dock widget showing snap guides for current page - allows creation of snap lines at specific locations, and adjusting position of existing guides to exact coordinates

Yay!

**Comment by nyalldawson** [comment]
Some screenshots:

Guide marker indicators in the ruler:

ruler_markers

Ruler right click menu:

guide_menu

Guide manager! Woo! Perfectly positioned guides are now a thing!

guide_manager

Snapping location indicator while creating items:

snapping_marker

**Comment by nyalldawson** [comment]
BTW - if anyone wants to test run this, it's not exposed in the main UI yet. You need to enter something like:

```
l=QgsLayout(QgsProject.instance())
l.initializeDefaults()
iface.openLayoutDesigner(l)
```

in the python console

**Comment by nirvn** [comment]
@nyalldawson , I'm being abusive here, but I'll go ahead anyways 😉 what about offering users to style the color of guides via the shiny new guides panel? It's actually a very useful feature to have, I use it all the time in inkscape et cie.

**Comment by nyalldawson** [comment]
@nirvn style individual guides?

**Comment by nirvn** [comment]
@nyalldawson , yeah. Inkscape does it, and it can be quite useful to visually distinguish different guide roles:
screenshot from 2017-07-27 10-21-40

**Comment by nyalldawson** [comment]
Ok. I've added it to my mental list - it's out of scope here but I could add it to the next campaign.

**Comment by nirvn** [comment]
@nyalldawson , 👍

**Comment by DelazJ** [comment]
Wow promising features. Thanks @nyalldawson 
Giving a look to the screenshot you provide, how about using the plus and minus icons instead of Add and Delete labels. I think it'll be consistent with many dialogs in QGIS.

**Comment by m-kuhn** [comment]
Lovely!

**Pull request merged**
