### PR TITLE
Add lpad truncate test

### PR DESCRIPTION
**Pull request by DelazJ**
Fixing some unfinished copy-paste

### CODE REVIEW

**Comment by nirvn** [comment]
Interesting, your PR revealed some issues with the implementation of rpad n lpad. 

We should fix the functions to mimic PostgreSQL's behavior:
- https://www.techonthenet.com/postgresql/functions/lpad.php
- https://www.techonthenet.com/postgresql/functions/lpad.php

**Comment by DelazJ** [comment]
After min/max, lpad and rpad... Maybe 3.0 is the right time to review our functions and align them with PostgreSQL...

**Comment by nirvn** [comment]
So, lpad() behaves OK, but the test needs updating. As for rpad(), to match PostgreSQL, I believe behavior has to be inverted. Ie, rpad('hello',4) would return 'ello'.

**Comment by DelazJ** [comment]
Actually I don't think this PR is right nor there's an error in QGIS (neither in function nor in test afaics).
See screenshots below from QGIS and PGAdmin (they both return same results which are coherent with what are expected in our tests).

image

image

Improvements should instead focus on the description (which is the same for both functions - if any english speaker want to take the lead) and add an example with truncate case.

**Comment by DelazJ** [comment]
Actually there was no error but a missing test.

**Comment by nirvn** [comment]
@DelazJ , thanks.

**Pull request merged**
