### PR TITLE
[BUGFIX][Oracle] Force Geometry to WKB

### PR DESCRIPTION
**Pull request by rldhont**
## Description
In some cases, the one this PR has been done, the geometry provided by the database is not a Well Known Binary as the QGIS Oracle Provider is waiting for.
In my  case the database is oracle 11g, the geometry is point, and the result is not well located point when the feomerry is not cobverted to WKB. The coordinate are not well extracted from the oracle Binary.

So this PR le done to force Oracle to provide WKB. 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by jef-n** [comment]
Which problem does this fix?

**Comment by elpaso** [comment]
@rldhont would you mind deleting the template in the PRs text and add a few lines to explain the purpose of it?
Some of us will read the notifications via email and the template itself is not very informative.

**Comment by nyalldawson** [comment]
Can you also confirm that you've run the Oracle provider test suite with this change? It's not enabled on travis because we don't have OCI available (or a test database!)

**Comment by nyalldawson** [comment]
@rldhont I gave this a try to see if it fixes the missing curve geometry support in Oracle, but from my tests:

- it's VERY slow - a line layer with a couple of hundred features regresses from loading in 2 seconds to 20+ seconds
- seems Oracle don't play by the rules and generate standard wkb... at least for curved geometries. :(

**Comment by jef-n** [comment]
@nyalldawson That's why the ocispatial driver produces WKB from oracle's native format internally.  Apparently Oracle didn't meanwhile improve - and back then `SDO_UTIL.TO_WKBGEOOMETRY` was even restricted to Oracle Spatial (ie. not working/allowed on Oracle Locator).
@rldhont So the question still is, what is this supposed to fix?

**Comment by rldhont** [comment]
@jef-n this PR le supposés to force Oracle to provide WKB and not an oracle geometry Binary. My case is point that the coordinate is not well parsed from Binary.

@nyalldawson I have not launch the oracle test suite. I have only tested with the table provided by my customer.

**Comment by jef-n** [comment]
@rldhont looks like it should be fixes in the ocispatial drivers - can you provide testdata?

**Comment by nyalldawson** [comment]
Ok - I think this should be closed and instead opened as a bug report with test data (or a PR fixing the ocispatial WKB generation). 

For reference, I'm currently refactoring the ocispatial WKB creation code to add (read-only) support for curved geometry types, and as part of this I'm adding a bunch of test geometries to valid the provider's geometry handling. I'd suggest waiting till this lands and then revisiting, since we'll have a good geometry test suite we can run any changes against.

**Comment by jef-n** [comment]
@rldhont testdata?

**Comment by rldhont** [comment]
@jef-n I have the information. The Point Geometry has been created with `sdo_elem_info_array` and `sdo_ordinate_array` not with `sdo_point_type`.

**Comment by rldhont** [comment]
@nyalldawson how do you run the oracle provider test suite ? Do you use a docker image ? how to create qgis user in the oracle database ?

**Comment by nyalldawson** [comment]
@rldhont I use the Oracle "big data" virtual machine: 

http://www.oracle.com/technetwork/database/bigdata-appliance/oracle-bigdatalite-2104726.html

It's a bit of a pain to setup- after getting the VM up make sure you follow the instructions they give for recompiling proj, or you don't get proper spatial support.

Ping me if you get stuck, I've got some rough notes I made while doing this which might help.

**Comment by rldhont** [comment]
@nyalldawson I'm running oracle provider test suite with docker wnameless/oracle-xe-11g

I'm able to run `PyQgsOracleProvider` test after manually creating `QGIS` user and running `testdata_oracle.sql`. Only one test failed `testGetFeaturesFilterRectTests`, with `[2, 5, 4]` instead of `[2, 4]`.

**Comment by nyalldawson** [comment]
@rldhont 

That needs a backport of: https://github.com/qgis/QGIS/commit/2d7632fc1a3eff716da06b71c7b29da720f0d1d4#diff-1e2c1a5166c2554f1a483a41989a5940

**Comment by rldhont** [comment]
@nyalldawson The tests you have added in #6814 do not pass because, the method `SDO_UTIL.FROM_WKTGEOMETRY` do not build right `SDO_GEOMETRY`. Do you have the `SDO_GEOMETRY` configurations corresponding to the WKT ?

**Pull request closed without merging**
