### PR TITLE
[tr] spanish translation update

### PR DESCRIPTION
**Pull request by cdavila**
## Description
New translations for the 3.0 release

### CODE REVIEW

**Comment by m-kuhn** [comment]
@mach0 did you verify that the travis failure is unrelated?

**Comment by mach0** [comment]
@m-kuhn the latest I could see is that travis managed to get it and everything was green ..Could not see any failure anymore..

**Comment by mach0** [comment]
strange - on my side everything was green - while it was red yesterday..
thats why I thought it's ok to merge. No chance to manually check during worktime ;)
hopefully master will not be affected by a pull to release-3_0

**Comment by m-kuhn** [comment]
the commit above is still red, strange that the PR status is different than the status of the last commit within the PR.

>  hopefully master will not be affected by a pull to release-3_0

heh, good point :)

**Comment by mach0** [comment]
Seems I need a remote server for testing pull requests .. but this is travis isn't it? ;)

**Pull request merged**
