### PR TITLE
Don't show -0 in axis labels

### LINKED ISSUE #48421: [profile tool] Chart displays `-0` should be `0`
### What is the bug or the crash?

Minor issue
export9

It displays `-0` if there is no other negative value

### Steps to reproduce the issue

.

### Versions

Master [a840402c14](https://github.com/qgis/QGIS/commit/a840402c14)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #48421

### CODE REVIEW

**Comment by uclaros** [comment]
How about also adding some scientific notation when numbers get really big. At the moment, if I keep scrolling out the screen is filled with digits and the plot canvas is forced to shrink.
Or/and maybe some limit so than one cannot zoom in/out until the scale gets 0/inf

**Comment by nyalldawson** [comment]
> How about also adding some scientific notation when numbers get really big. At the moment, if I keep scrolling out the screen is filled with digits and the plot canvas is forced to shrink.

It's a good idea, but I've got to limit the feature creep here sorry :wink:

**Comment by uclaros** [comment]
No problem, this is just polishing your already great implementation anyway!

**Comment by nyalldawson** [comment]
@uclaros 

That said, it's worth noting that the number formatting is coming directly from the QgsNumericFormat subclasses and that the plot api already exposes option to control all this (including defining signficant figures to show, etc). So if/when we get layout items for elevation profiles this will all be exposed for user control :+1:

**Comment by nyalldawson** [comment]
(... and maybe in this case it's as simple as modifying the default numeric format used in the plot to use the significant figures option !)

**Review by nirvn — APPROVED** [review]

**Pull request merged**
