### PR TITLE
[PROCESSING] Undo recent changes to Dissolve

### PR DESCRIPTION
**Pull request by bstroebl**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Is that a complete revert or a partial revert?

**Comment by bstroebl** [comment]
Hi Matthias,

this is a complete revert, my change to speed up the processing are reverted, too as it is based on only keeping the dissolve field

**Comment by m-kuhn** [comment]
Sorry to hear

**Comment by bstroebl** [comment]
Anything else would break feature freeze, wouldn't it?
Besides I am not sure if I could manage to get it running until release and that would be even worse (also depends on what Victor proposed on the mailing list)

**Comment by m-kuhn** [comment]
The feature freeze is here to fix issues with previously merged features. So a bugfix pull request would definitely be evaluated.

An implementation as discussed on the ML would qualify as more than a simple bugfix and therefore should be postponed to 2.14.

**Comment by bstroebl** [comment]
that's what I thought, therefore we have a revert

**Pull request merged**
