### PR TITLE
 create scope based enum for QgsMapLayer::LayerType >> QgsMapLayerType

### PR DESCRIPTION
**Pull request by 3nids**
the enum is moved out of the class
this will allow forward declaration more easily since the enum is not nested in the class

everything is also handled in sipify, including the monkey patching for API compatibility.

would like some feedback :)

### CODE REVIEW

**Comment by nyalldawson** [comment]
> this will allow forward declaration more easily since the enum is not nested in the class

I'm struggling to find a definitive answer -- is forward declaring an enum class allowed?

**Comment by m-kuhn** [comment]
Should we...

... move global enums to Qgis, so it would be Qgis::MapLayerType, that would be aligned with Qt, no?

**Comment by 3nids** [comment]
@m-kuhn this makes sense, but that would mean we cannot forward declare anymore.

**Comment by m-kuhn** [comment]
In this case, no advantage to move it to `Qgis`.
Would it change anything if it was a namespace instead of a class?

**Comment by 3nids** [comment]
I don't think so.

**Comment by m-kuhn** [comment]
It should work to do this in forward declaration

```
namespace Qgs {
    enum class myEnumProcessState: unsigned int;
}
```

**Pull request merged**
