### PR TITLE
processing/gdal: remove output formats that are not supported by qgis

### PR DESCRIPTION
**Pull request by gioman**

### CODE REVIEW

**Comment by gioman** [comment]
assigned @volaya @alexbruy

**Comment by alexbruy** [comment]
I think it is better to keep this data types available. One may want to create raster to use it with other software. Also in future QGIS may have support for this data types too. Just my opinion. If others will agree that it is better to merge it — no objections from me.

**Comment by gioman** [comment]
Hi Alexander, I see your point about other sw. About qgis is not that this formats are just not supported (like a format that when added to qgis causes like a "format not supported" error), they do not show on the map but the values are there (not sure what happens if you use them in a raster operation, for example). One of them (cint16) causes qgis to crash immediately. We can leave them and then file a ticket about this formats, but the last time I did it the ticket was closed because it was said that there was no use for such formats. So... merge or close this one, it is ok for me! :)

**Comment by gioman** [comment]
Note: if it may help in the decision, the gdal raster calculator does not support this formats.

**Pull request merged**
