### PR TITLE
Move profiler instance to QgsApplication

### PR DESCRIPTION
**Pull request by NathanW2**
Remove the `::instance()` method and move it to QgsApplication for the main profiler instance.  Uses can still make their own just using the class standalone.

### CODE REVIEW

**Comment by NathanW2** [comment]
@m-kuhn @jef-n does this look ok?  

(Tests will fail due to missing docs)

**Comment by m-kuhn** [comment]
If it is static I think there's not much difference to the approach of having an in-class static instance()-method.
I'd rather go for a member varaible so it's lifetime can be controlled.

**Comment by NathanW2** [comment]
Isn't `QgsApplication` and `QApplication` just a really big global class anyway though with static variables.

**Comment by m-kuhn** [comment]
It is a really big global (singleton) class but I don't think it needs to consist of only static variables.

**Comment by nyalldawson** [comment]
Pushed a cleaned version as 311f482

**Pull request closed without merging**
