### PR TITLE
GRASS plugin: fix deprecation warnings

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Comment by roya0045** [comment]
Should support for qt 5.11 still be a thing? I recall that using an old qt version was responsible for issues, even with 5.12.

**Comment by rouault** [comment]
> Should support for qt 5.11 still be a thing?

I believe our Travis-CI config to be still based on Ubuntu 18.04 and thus qt 5.9

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@roya0045 
> Should support for qt 5.11 still be a thing? I recall that using an old qt version was responsible for issues, even with 5.12.

We'd planned to drop it for 3.18, but didn't get the CI upgraded in time to allow this. Hopefully for 3.20!

**Comment by roya0045** [comment]
@nyalldawson Ah thanks, at least I wasn't too far off in the rhubarb.

**Pull request merged**
