### PR TITLE
[VertexTool] fixes avoid intersections

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description

Followup #41424 vertex tool doesn't honor the avoid intersections settings.

before:

overlap_vertextool_before mkv

after:
overlap_vertextool_after mkv

Sponsored by: Métropole Européenne de Lille @Jean-Roc

### CODE REVIEW

**Comment by uclaros** [comment]
Avoid intersections is very sneaky and dangerous, we should **inform** the user when his geometry is automatically modified. I know it is like that in all places where avoid overlaps is handled, but I grasped the opportunity to highlight this need!

Apart from that, there are two major issues with this proposed approach:
1. Silent multipart geometry generation in singlepart layers. The user should be warned on creation so he can fix it (if allowed at all to generate multiparts in singlepart layers).
2. Topological editing mayhem. Topological editing has already been handled when 'applyEditsToLayers()` is called. This means that unneeded topological points might have already been added while other needed ones will not be added.

**Comment by roya0045** [comment]
I had the same worries as @uclaros, would it be better to create a new standalone feature on non-multipart layers?

**Comment by lbartoletti** [comment]
>     1. Silent multipart geometry generation in singlepart layers. The user should be warned on creation so he can fix it (if allowed at all to generate multiparts in singlepart layers).

It's been years since the return code on the geometry type was removed in avoidIntersections method. I agree with you it's an interesting piece of information -- but not always necessary -- and I [reinstate this code](https://github.com/qgis/QGIS/pull/41424/files#diff-08789a83813c83fdba446c6ac938c962d1d26de41a1f235628e2caad0ede2762R2614).
I will add a warning message as for the other tools.

> * Topological editing mayhem. Topological editing has already been handled when 'applyEditsToLayers()` is called. This means that unneeded topological points might have already been added while other needed ones will not be added.

If I enable topological editing, I will only get points on the snapped coordinates, but the moved geometry will not add points to the snapped geometry.
This is consistent with what is already in place. Discussions about the topology that we have on another ticket are for me out of the scope of this fix -- But I'm always interested to discuss and improve together the way qgis works :wink:

**Comment by uclaros** [comment]
> If I enable topological editing, I will only get points on the snapped coordinates, but the moved geometry will not add points to the snapped geometry.
> This is consistent with what is already in place.

This is not consistent with how avoid overlap with topological editing works in other tools.
Take feature creation for example in conjunction with avoid overlap, topological editing and snap to segment. This is how it works right now:
Peek 2021-02-18 19-55
No vertex is added to the snapped location since that part of the geometry is removed by overlap avoidance. Topological points are added at the two vertices where the new geometry intersects the old one.

This is not what happens with the proposed solution, since topological points have already been added when the avoid overlap logic kicks in:
Peek 2021-02-18 19-56
An unneeded vertex is added at the snap point while the two new geometry vertices have no corresponding topological points on the old geometry.

Furthermore, you get the following unwanted behavior when moving topologically created vertices:
Peek 2021-02-18 19-58

**Comment by lbartoletti** [comment]
@uclaros you're right, I misread your first comment and forgot this case... I'll fix it.

**Comment by lbartoletti** [comment]
overlap_vertextool_after mkv

@uclaros here a video with the latest commits

**Comment by uclaros** [comment]
@lbartoletti I tested your latest changes and the unwanted topological point is indeed not added :+1:
However, it seems that no topological points are added whatsoever, as seen in your example too, but even not at the snap point when simply snapping to segment (without overlapping).
Furthermore, the weird behavior in my third screencast is still present (it seems like one of the two geometries used for avoid overlaps on the other does not take into account the vertex that has moved, giving this strange clipping). Here is a better example: 
Peek 2021-03-01 22-19


It kind of scares me that none of those two regressions was caught by the existing tests. We definitely need more tests!

**Comment by lbartoletti** [comment]
@uclaros Thanks. 
I rewrite the avoid Intersection part and fix the add topological points part. 

overlap_vertextool_after-(2) mkv

**Comment by uclaros** [comment]
I briefly tested and the hick-ups seem cured! :+1: 
I believe that topological points should also be added to all new vertices, not only at the snapped point, similarly to how the Create Polygon tool works as in my first screencast. Otherwise topological integrity will be lost when those new vertices are moved.

**Comment by lbartoletti** [comment]
> I believe that topological points should also be added to all new vertices, not only at the snapped point, similarly to how the Create Polygon tool works as in my first screencast. Otherwise topological integrity will be lost when those new vertices are moved.

I tried something like this (was commented in one of my PR IIRC).
In [`moveVertex`](https://github.com/qgis/QGIS/pull/41658/files#diff-2b5689cf92009403c1752885360323bc0a4abc6faa01bfd4f49293b9747d6254R2169-R2170) maybe we should write:
```
            layer->addTopologicalPoints( g ); // instead of layerPoint
            mapPointMatch->layer()->addTopologicalPoints( g );
```

@uclaros Can you tell me if it's ok for you?

**Comment by uclaros** [comment]
@lbartoletti I am afraid this will not suffice since at the moment the topological points logic is handled only when the locator matches segment or midpoint. When avoid overlaps kicks in, we want to always add topological points regardless of snapping. Also, if the geometry if huge but we only want to add a couple of topo points this would be wasteful.

My suggestion would be to introduce a private `QVector<QgsPoint> mTopologicalPoints` that gets populated inside `applyEditsToLayers()` when *avoid overlaps* takes place and if topological editing is enabled, containing all the modified points of the action (vertices moved plus vertices created by avoid overlaps).
Then, we can call the parent tool's `QgsMapToolEdit::addTopologicalPoints( mTopologicalPoints )` instead of the `vlayer`'s, so that in the future we can change it to add points to all editable layers, for all tools, in one place.
Then clear `mTopologicalPoints` to be ready for next action.

On second thought, it would be tidier if `mTopologicalPoints` was handled within `QgsMapToolEdit` and automatically emptied when `QgsMapToolEdit::addTopologicalPoints()` is called.

Regardless of the above, the weird behavior in my last screencast should be fixed, where sometimes, some topological points are added 0, 1 or 2 times and not by `addTopologicalPoints` but by `avoidIntersections` within `applyEditsToLayers()`

**Comment by lbartoletti** [comment]
> Edit: Tested a little more and it seems weird again. Topological points are added in a non deterministic way! Sometimes added, sometimes skipped, sometimes added duplicates.

As you can see on this video, I tried to replicate the problem, but seems ok (c)(tm)

fix_vertextool mkv

The main difference is that I move only a vertex (one can see you move three segments attached at one vertex on your video).

**Comment by lbartoletti** [comment]
I think the RP has reached its limit for the given scope. Thanks for the tests and feedback.
I would suggest to merge this PR if tests pass.

**Comment by uclaros** [comment]
I'm sorry, I somehow missed notification for recent replies.

> As you can see on this video, I tried to replicate the problem, but seems ok (c)(tm)

In your video you don't demonstrate the changes of this PR. Avoid overlaps and topological points are added by the add feature tool instead, hence stuff seem ok. Try creating the second triangle disjoint first, then move one vertex with the vertex tool so that avoid overlaps and topological points are handled by the changes in this PR and see that things are not ok!

> I think the RP has reached its limit for the given scope. Thanks for the tests and feedback.
> I would suggest to merge this PR if tests pass.

I wouldn't merge it, not without an explicit message that it breaks topological editing.

**Comment by lbartoletti** [comment]
> I'm sorry, I somehow missed notification for recent replies.
> 
> > As you can see on this video, I tried to replicate the problem, but seems ok (c)(tm)
> 
> In your video you don't demonstrate the changes of this PR. Avoid overlaps and topological points are added by the add feature tool instead, hence stuff seem ok. Try creating the second triangle disjoint first, then move one vertex with the vertex tool so that avoid overlaps and topological points are handled by the changes in this PR and see that things are not ok!

Here is a fixed version, I hope. I also added this as a test.

vertextool mkv

**Comment by uclaros** [comment]
I tested the new approach and the topological issues seem resolved!
Now the only not addressed issue seems:
>     1. Silent multipart geometry generation in singlepart layers. The user should be warned on creation so he can fix it (if allowed at all to generate multiparts in singlepart layers).


I feel obliged to notice that this combination of tools (vertex tool + avoid overlaps) is pretty dangerous and can have unexpected results for some users, as moving a simple vertex on a huge polygon will still remove all its overlapping segments which might not even be on the visible canvas! And in case of identical geometries, one of them will be completely gone, though using *avoid overlaps* and having duplicate geometries is probably not common!

An unreported bug that is kind of augmented with this PR is that adding the topological points take a place on the undo log with a blank name, requiring two undos to properly undo the vertex move. This is clearly visible on the added test where you need to call undo twice. The thing is that with this PR an extra entry is added for each geometry causing an overlap avoidance and topological points to be added, making the undo queue weird when multiple overlaps are handled.

**Comment by roya0045** [comment]
@uclaros I think a warning is fair on the geometry change. Though regarding the rest, I think creating an issue and then dealing with it afterward would be good. Even though the proposed work may exacerbate an existing issue, fixing that issue seem to require a rework of a different aspect.

**Comment by lbartoletti** [comment]
Thanks @uclaros !

> @roya0045 Though regarding the rest, I think creating an issue and then dealing with it afterward would be good. Even though the proposed work may exacerbate an existing issue, fixing that issue seem to require a rework of a different aspect.

+1

@uclaros @roya0045 When you talk about warning, do you mean a messageBar (when to activate it?) or rather a good description in the documentation (which seems to me to be preferable cc @SrNetoChan )?

**Comment by uclaros** [comment]
I think a messageBar warning would be suitable here. If a vertex moved caused the geometry part count to change it should kick in right away saying either that avoid overlaps generated extra parts which might not be supported by the layer, or that parts were completely removed.
Warnings in the docs about the tool's risk of unintended consequences would be welcome too.

Both of the above are more about the avoid overlap functionality but this PR makes it way way easier to generate unwanted results!

**Comment by SrNetoChan** [comment]
> @uclaros @roya0045 When you talk about warning, do you mean a messageBar (when to activate it?) or rather a good description in the documentation (which seems to me to be preferable cc @SrNetoChan )?

I would say that a description in the documentation is kind of mandatory, but I agree that a warning message informing the user that the operation resulted in an eventually unwanted result would be good too.

**Comment by lbartoletti** [comment]
@SrNetoChan @uclaros Done.

image

The message bar appears when you change the avoid intersections mode.
I'm not sure about the wording. I'll let you tell me what you think is best.

We must add a note in the documentation too.

thanks

**Comment by SrNetoChan** [comment]
> @SrNetoChan @uclaros Done.
> 
> image
> 
> The message bar appears when you change the avoid intersections mode.
> I'm not sure about the wording. I'll let you tell me what you think is best.
> 
> We must add a note in the documentation too.
> 
> thanks
> 

I am not very keen of having too many warning messages unless it's strictly necessary. I think, having a message pop every time someone turns on avoid intersection or topological editing will scare people. For this PR I would not even bother about the topological editing, that's another issue.

For the avoid intersections option, I think there are two major issues:

When editing a vertex in one place removes overlaps all over a large geometry. (This was an existing issue already). 

When, editing a single part layer, someone ends up creating a multipart geometry that will be impossible to save.

For the first issue, I think a good tooltip  on the option action and a mention on the documentation would be enough. Something like:

"Beware that this option will be applied on all vertexes of the edited geometries, even if outside the current view extent."

For the second issue, if a multi-part feature is created, I would ignore the change and throw an warning message.

"Couldn't apply the change, it's not possible to create a multipart geometry in a singlepart layer."

**Comment by uclaros** [comment]
@lbartoletti sorry, this is not what I meant! The warning should only kick in when a vertex move has caused the geometry's part count to change by *avoid overlaps* as @SrNetoChan mentioned above.
Furthermore, it is *avoid overlaps* especially in combination with the vertex tool that may have unwanted results, not topological editing.

**Comment by lbartoletti** [comment]
I don't like the popup either, it suits me, I thought that was what you were suggesting @uclaros @roya0045 

I have reverted my commit and I suggest that we do other RPs and discussions on those RPs rather than this one for this particular topic.

**Comment by lbartoletti** [comment]
> @lbartoletti sorry, this is not what I meant! The warning should only kick in when a vertex move has caused the geometry's part count to change by _avoid overlaps_ as @SrNetoChan mentioned above.

Done.

**Comment by lbartoletti** [comment]
Can a kind committer please merge this PR? :blush:

**Review by 3nids — APPROVED** [review]

**Comment by uclaros** [comment]
There are still issues with this implementation.
1. *Avoid overlaps on Active Layer* ignores actual active layer and avoids overlaps on *same layer*
2. Topological points are not added to layers set to *Avoid overlaps* using the advanced configuration
3. Geometry parts may still unintentionally be deleted silently.

**Pull request merged**
