### PR TITLE
[pointclouds] Add an elevation tab in layer properties, and allow users to set a manual offset to apply to point cloud z values

### PR DESCRIPTION
**Pull request by nyalldawson**
This allows for adjustment of the elevation of point clouds, eg so that:
1. They match nicely with point clouds from other datasources
2. Users can use point clouds from sources with arbitrary z values,
eg. a point cloud made by opendronemap without any actual reference
z values available

### CODE REVIEW

**Comment by nyalldawson** [comment]
@wonder-sk @NEDJIMAbelgacem as discussed.

Needs a few clean ups and some tests, but I'm after feedback on whether the approach here is acceptable.

**Comment by nyalldawson** [comment]
Also utilises a totally inappropriate icon as a hint to @nirvn :wink:

image

**Review by wonder-sk — APPROVED** [review]
Looks good to me!

What do you think we should do when identify map tool is used? Display the original Z coordinate or the adjusted one? :-)

**Comment by nyalldawson** [comment]
I thought about that, and had no conclusion 🤣. Maybe we should just go full explicit: "54 (105 with +51 z offset)"? Or "z (original): 54", "z (adjusted): 105"?

**Comment by nyalldawson** [comment]
@wonder-sk the other thing I'm on the fence about is whether we should always keep this as a seperate offset (as done here), or instead alter the offset vector from the index to include this in classes like QgsPointCloudRenderContext. Do you have any preference?

**Comment by roya0045** [comment]
@nyalldawson I think displayying the two distinctly may be better, though instead of 'adjusted' '+offset' to prevent any confusion and possibly alluding to another process.

**Comment by wonder-sk** [comment]
Yeah I like the idea with explicit info about z offset, ideally as two separate items.

As for separate elevation offset, I am in favor of how you did it instead of mixing that with offset coming from data - it seems cleaner as the two come from completely different "sources" - and there may be places where we need to know the elevation offset explicitly for some reason...

**Pull request merged**
