### PR TITLE
Widget size handling in status bar

### PR DESCRIPTION
**Pull request by signedav**
## Description
**Fix: Only the scale line edit has the minimum size instead of the whole scale widget.**
When minimizing the window there was only the scale label not minimized before.
image
Now the lable scale is minimized like the other lables:
image

**Improvement: Coordinates line edit size is now dynamic depending on the coordinate value**
Since having more widgets in the statusbar than in the 2.18 the coordinate-lineedit is mostly much smaller than before. I thought about minimum size but then I decided to make it dynamic according to the content.
Before it was mostly too small:
image
Now it's dynamic:
image
image
image

### CODE REVIEW

**Comment by m-kuhn** [comment]
@DelazJ what's your opinion on this?

**Comment by Gustry** [comment]
If we want to earn some spaces, can't we reduce the two spin boxes on the right?

**Comment by DelazJ** [comment]
With the dynamic resizing, wouldn't that look really big when switched to Extent mode (for example using the last CRS coordinates in the PR message or a RGF93/Lambert-93)?

**Comment by signedav** [comment]
@Gustry You are right. But in most cases, the space is not the problem. Anyway I thought about to make the spin boxes dynamic too. But then it would be a lot of movement there without getting that much space. If we make it fix, we cannot really reduce them:


image

**Comment by signedav** [comment]
@DelazJ It could get big in fact, but not that much I think. I switched to the extend-mode and activated the RGF93/Lambert-93 and it looks like this:

**Comment by signedav** [comment]
Are you fine with the solution @DelazJ ?

**Comment by m-kuhn** [comment]
@DelazJ, what's your opinion, does this need something changed or is the chance for real-world problems small enough to merge and see?
Would be nice to move forward with this.

**Comment by slarosa** [comment]
@signedav I tested your PR and works fine, the only side effect I see is the flickering of the coordinates widget on coordinates update (see image).

flickering_coordinates

Sorry, I submitted #6127 but I was not aware of this one.

**Comment by nyalldawson** [comment]
Look at the above screencast - I think we need some extra logic here to prevent the frequent size changes - e.g. we don't lower the size if the new size is < 4 characters width different to the old size.

**Comment by signedav** [comment]
Thanks for testing @slarosa 
@nyalldawson Yes, this sounds reasonable.
I will care about.

**Comment by signedav** [comment]
@slarosa fixed it with the flickering - can you approve it?
@DelazJ your concern seems to be solved here #6126

**Comment by slarosa** [comment]
@signedav just tested it but unfortunately I still see the size changes for the widget. :-(
I am guessing that it works fine for you thus I don't know if this occurs only under macos.

Anyway, working on it and the following patch (basically based on your code) work fine for me:
```diff
diff --git a/src/app/qgsstatusbarcoordinateswidget.cpp b/src/app/qgsstatusbarcoordinateswidget.cpp
index 45bf845ee0..11224c16ae 100644
--- a/src/app/qgsstatusbarcoordinateswidget.cpp
+++ b/src/app/qgsstatusbarcoordinateswidget.cpp
@@ -224,14 +224,7 @@ void QgsStatusBarCoordinatesWidget::showMouseCoordinates( const QgsPointXY &p )
 
   mLineEdit->setText( QgsCoordinateUtils::formatCoordinateForProject( p, mMapCanvas->mapSettings().destinationCrs(),
                       mMousePrecisionDecimalPlaces ) );
-
-  //ensure the label is big (and small) enough
-  int width = mLineEdit->fontMetrics().width( mLineEdit->text() ) + 10;
-  if ( mLineEdit->minimumWidth() + 4 < width || mLineEdit->minimumWidth() - 4 > width )
-  {
-    mLineEdit->setMinimumWidth( width );
-    mLineEdit->setMaximumWidth( width );
-  }
+  ensureCoordinatesVisible();
 }
 
 
@@ -246,10 +239,13 @@ void QgsStatusBarCoordinatesWidget::showExtent()
   QgsRectangle myExtents = mMapCanvas->extent();
   mLabel->setText( tr( "Extents:" ) );
   mLineEdit->setText( myExtents.toString( true ) );
+  ensureCoordinatesVisible();
+}
 
-  //ensure the label is big (and small) enough
+void QgsStatusBarCoordinatesWidget::ensureCoordinatesVisible()
+{
   int width = mLineEdit->fontMetrics().width( mLineEdit->text() ) + 10;
-  if ( mLineEdit->minimumWidth() + 4 < width || mLineEdit->minimumWidth() - 4 > width )
+  if ( mLineEdit->minimumWidth() < width || ( mLineEdit->minimumWidth() - width ) > 10 )
   {
     mLineEdit->setMinimumWidth( width );
     mLineEdit->setMaximumWidth( width );
diff --git a/src/app/qgsstatusbarcoordinateswidget.h b/src/app/qgsstatusbarcoordinateswidget.h
index 988087d922..e891525969 100644
--- a/src/app/qgsstatusbarcoordinateswidget.h
+++ b/src/app/qgsstatusbarcoordinateswidget.h
@@ -59,6 +59,7 @@ class APP_EXPORT QgsStatusBarCoordinatesWidget : public QWidget
     void validateCoordinates();
     void dizzy();
     void showExtent();
+    void ensureCoordinatesVisible();
 
   private:
     void refreshMapCanvas();
```

**Comment by nyalldawson** [comment]
If i read this correctly it's using a threshold of 4 pixels - so won't work for hidpi screens. It should be a character width based threshold, e.g. the width of 2 "O" characters. Use fontMetrics to calculate in the constructor.

**Comment by m-kuhn** [comment]
> If i read this correctly it's using a threshold of 4 pixels - so won't work for hidpi screens. It should be a character width based threshold, e.g. the width of 2 "O" characters. Use fontMetrics to calculate in the constructor.

:+1: I was just about to start typing this

**Pull request merged**
