### PR TITLE
improve server SELECTION test with multiple id's

### PR DESCRIPTION
**Pull request by tudorbarascu**
The current test takes into account only 1 id and in the master
a regression has slipped (it works only for one id, not for more)

This actually needs forward porting but the Master server has a regression.

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x ] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by pblottiere** [comment]
@tudorbarascu May I ask you to update the test such as `"SELECTION": "Country: 4,1;Hello: 2,5"` in order to test a selection on multiple layers too?

Otherwise, LGTM! Thanks!

**Comment by tudorbarascu** [comment]
@pblottiere Done! Thanks also!

**Comment by pblottiere** [comment]
@tudorbarascu Thanks for updating the test. 

However, Travis is green whereas it should not. With `"SELECTION": "Country: 4,1;Hello: 2,5"`, we should have something like:

image


Do you agree?

**Comment by tudorbarascu** [comment]
@pblottiere Sure! It's fixed! Thanks a lot + congrats for the keen eye!

**Pull request merged**
