### PR TITLE
[processing][needs-docs] always use SAGA shipped with QGIS (refs #16422)

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
As now we support only SAGA LTR and SAGA shipped with OSGeo4W, therre is no sense in having option to choose external SAGA installation. Moreover this option will lead to confusion and complains if user installs non-supported SAGA version.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by mach0** [comment]
While I am a big fan of having the combined projects working all together I'd like to also probably prepare for the next release of SAGA.
How to switch and test (or is this now done automatically?) for newer releases when I cannot set the path anymore?

**Comment by alexbruy** [comment]
We now support *only* SAGA LTR, so provider will update to new SAGA version when new LTR is out. API withing single LTR release (now this is 2.3.x) is the same so no need to set path.

**Comment by volaya** [comment]
Looks good to me

That was the behaviour not long ago, but it was reverted because some users wanted to use their own versions of SAGA and be able to choose. Now that only LTR is supported, that makes no sense, so this is a much safer way of dealing with the dependency

+1 from me to merge

**Comment by alexbruy** [comment]
Test failure unrelated.

**Pull request merged**
