### PR TITLE
Add build-essential tool in instruction to install

### PR DESCRIPTION
**Pull request by trngbich**
Add missing step: install compiler

## Description

build-esstial tool installation is missing

### CODE REVIEW

**Comment by nicogodet** [comment]
Compilers should be installed with provided apt-get command here : https://github.com/qgis/QGIS/blob/master/INSTALL.md#33-install-build-dependencies
What was missing in your case ?

**Comment by trngbich** [comment]
> Compilers should be installed with provided apt-get command here : https://github.com/qgis/QGIS/blob/master/INSTALL.md#33-install-build-dependencies What was missing in your case ?

The error when running "ccmake .." is "Could not find compiler g++"
> CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCXXCompiler.cmake:53 (message):                                     The C++ compiler                                                                                                                                                                                                                                  "/usr/local/bin/g++"                                                                                                                                                                                                                          is not able to compile a simple test program.                                                                                                                                                                                                   It fails with the following output:                                                                                                                                                                                                               Change Dir: /root/dev/cpp/QGIS/build-master/CMakeFiles/CMakeTmp                                                                                                                                                                                 Run Build Command(s):/usr/bin/make cmTC_1b1e2/fast && /usr/bin/make -f CMakeFiles/cmTC_1b1e2.dir/build.make         CMakeFiles/cmTC_1b1e2.dir/build                                                                                             make[1]: Entering directory '/root/dev/cpp/QGIS/build-master/CMakeFiles/CMakeTmp'                                       Building CXX object CMakeFiles/cmTC_1b1e2.dir/testCXXCompiler.cxx.o                                                     /usr/local/bin/g++     -o CMakeFiles/cmTC_1b1e2.dir/testCXXCompiler.cxx.o -c                                        /root/dev/cpp/QGIS/build-master/CMakeFiles/CMakeTmp/testCXXCompiler.cxx                                                     ccache: error: Could not find compiler "g++" in PATH                                                                    make[1]: *** [CMakeFiles/cmTC_1b1e2.dir/build.make:66: CMakeFiles/cmTC_1b1e2.dir/testCXXCompiler.cxx.o] Error 1         make[1]: Leaving directory '/root/dev/cpp/QGIS/build-master/CMakeFiles/CMakeTmp'                                        make: *** [Makefile:121: cmTC_1b1e2/fast] Error 2  

After installing build-essential, the issue was solved

**Comment by nicogodet** [comment]
The apt-get command provided should install it. Did you run the provided command for your distrib ?

**Review by m-kuhn — APPROVED** [review]
I experienced the same with a plain `ubuntu:22.04` container following the referenced dependency build commands, the compiler is missing.

@nicogodet do you see any package in particular that should bring in a compiler?

**Comment by nicogodet** [comment]
Weird
Tried these exact commands one or two years ago without particular issues
Just tried on clean debian and ubuntu and g++ is missing while gcc is installed after running given apt-get command

Should `build-essential` be added to each of them instead of proposed solution ?

**Comment by m-kuhn** [comment]
These commands are generated (from the debian control files) according to @jef-n so this approach here is the easiest one to get

**Comment by nicogodet** [comment]
Fixed with bb4d23c

**Pull request closed without merging**
