### PR TITLE
Fix extension detection for raster processing output

### LINKED ISSUE #49147: Batch processing: Clip raster by mask layer (GDAL)
### What is the bug or the crash?

QGIS adds the Y resolution with a - that makes the batch file not to run because there is no option -2.0. See the code shows `-tr 2.0 -2.0` when I think it should be `-tr 2.0 2.0`.

`GDAL command:
gdalwarp -overwrite -s_srs EPSG:7856 -t_srs EPSG:7856 -of -tr 2.0 -2.0 -tap -cutline F:/path_to_raster/Clean_raster.shp -cl Clean_raster -crop_to_cutline F:/path_to_raster/Differences_wd.asc F:\path_to_raster\Differences_wd
GDAL command output:
Process returned error code 1
ERROR 6: Unknown option name '-2.0'
Usage: gdalwarp [--help-general] [--formats] 
[-s_srs srs_def] [-t_srs srs_def] [-to "NAME=VALUE"]* [-vshift | -novshift] 
[[-s_coord_epoch epoch] | [-t_coord_epoch epoch]] 
[-order n | -tps | -rpc | -geoloc] [-et err_threshold] 
[-refine_gcps tolerance [minimum_gcps]] 
[-te xmin ymin xmax ymax] [-tr xres yres] [-tap] [-ts width height] 
[-ovr level|AUTO|AUTO-n|NONE] [-wo "NAME=VALUE"] [-ot Byte/Int16/...] [-wt Byte/Int16] 
[-srcnodata "value [value...]"] [-dstnodata "value [value...]"] -dstalpha 
[-r resampling_method] [-wm memory_in_mb] [-multi] [-q] 
[-cutline datasource] [-cl layer] [-cwhere expression] 
[-csql statement] [-cblend dist_in_pixels] [-crop_to_cutline] 
[-if format]* [-of format] [-co "NAME=VALUE"]* [-overwrite] 
[-nomd] [-cvmd meta_conflict_value] [-setci] [-oo NAME=VALUE]* 
[-doo NAME=VALUE]* 
srcfile* dstfile 

Available resampling methods: 
near (default), bilinear, cubic, cubicspline, lanczos, average, rms, 
mode, max, min, med, Q1, Q3, sum.
Algorithm Clip raster by mask layer correctly executed…
Execution completed in 0.19 seconds
Results:
{'OUTPUT': 'F:\\path_to_raster2\\Differences_wd'}

Loading resulting layers
Batch execution completed in 1.51 seconds`

### Steps to reproduce the issue

Use the tool with two file (Raster ascii) and click on run

### Versions

QGIS version
3.22.6-Białowieża
QGIS code revision
b6f33b1a
Compiled against Qt
5.15.2
Running against Qt
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.4.2
Running against GDAL/OGR
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
AusMap
1.1
concavehull
2.0
icsm_ntv2_transformer
1.1.1
MapsPrinter
0.9
mmqgis
2021.9.10
profiletool
4.2.2
quick_map_services
0.19.29
tuflow
3.3
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### LINKED ISSUE #50288: Algorithm can't be executed if `.` in filename
### What is the bug or the crash?

image

It fails to determine the extension

### Steps to reproduce the issue

Try to output to a file with a `.` in filename

### Versions

3.22.11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nicogodet**
## Description

Fixes #50288 
Fixes #49147

I'm not confident enough to extend this to vector layer and point cloud layer as described in https://github.com/qgis/QGIS/issues/49147#issuecomment-1165477524.

Alternative for #50426

### CODE REVIEW

**Comment by nicogodet** [comment]
Unrelated failure

**Review by troopa81 — APPROVED** [review]

**Comment by troopa81** [comment]
@nicogodet Could you change the commit message so it includes the "Fixes #XXX" ?

**Comment by nicogodet** [comment]
@troopa81 Let me see how but why ?
It's already in PR message.

**Comment by nicogodet** [comment]
@troopa81 
> It close the connected ticket automatically on merge without human procedure

It's done by message PR (here, it will close 2 issues).

> You don't have to go to Github to find out what issue is fixed by the commit, it's already avalaible in Git

That's the main reason, I think !


Done !

**Comment by troopa81** [comment]
> It's done by message PR (here, it will close 2 issues).

Indeed, I was not aware of this! Thanks @nicogodet

**Pull request merged**
