### PR TITLE
Add QgsProject::ReadFlag::FlagSkipSnappingConfiguration

### PR DESCRIPTION
**Pull request by elpaso**
This little optimization gives a ~1-2% speed gain in the server's cold start with the "monster" project (~1000 PG layers) to the first getCapabilities call.

I'm not really happy with the implementation because I need to set `mReadFlags` in the `QgsProject` instance, I did that because the `QgsProject::onMapLayersAdded` is connected immediately in `QgsProject` ctor where we have no information about the flags.

I'm open to proposals for a better way to implement this.

### CODE REVIEW

**Comment by nirvn** [comment]
@elpaso , great to see you working on nailing some of the speed regression which have crept into /src/ :) 

Thinking out loud here: I think there's one pitfall we want to avoid. Whenever possible, we should look into optimizing QGIS vs. disable some parts of it to speed up server. The reward is much greater achieving the former as it impacts all of our user base.

It is not to say that disabling is never appropriate :smile:

**Comment by elpaso** [comment]
> @elpaso , great to see you working on nailing some of the speed regression which have crept into /src/ :)
> 
> Thinking out loud here: I think there's one pitfall we want to avoid. Whenever possible, we should look into optimizing QGIS vs. disable some parts of it to speed up server. The reward is much greater achieving the former as it impacts all of our user base.
> 
> It is not to say that disabling is never appropriate smile

Yeah, we are well aware of that. 

We are focusing on project load times and some of the improvements are generic (see: https://github.com/qgis/QGIS/pull/40420) but some other are mostly server-focused, like this PR that skips configurations that are not used in the server. It may be worth noticing that this flag as well as the other one I've added a few days ago are used in the QGIS Application data items too, so they do have an impact on the desktop application, not to mention the standalone application based on QGIS core libraries such as the processing standalone runner.

**Comment by nyalldawson** [comment]
> I'm not really happy with the implementation because I need to set mReadFlags in the QgsProject instance, I did that because the QgsProject::onMapLayersAdded is connected immediately in QgsProject ctor where we have no information about the flags.

> I'm open to proposals for a better way to implement this.

What about adding a `int mBlockSnappingUpdates = 0` member to QgsProject, and then changing onMapLayersAdded/onMapLayersRemoved to be:

```
  if ( mSnappingConfig.addLayers( layers ) && !mBlockSnappingUpdates )
    emit snappingConfigChanged( mSnappingConfig );
```


```
  if ( mSnappingConfig.removeLayers( layers ) && !mBlockSnappingUpdates )
    emit snappingConfigChanged( mSnappingConfig );
```


Then you'd just wrap readProjectFile with something like:

```
    mBlockSnappingUpdates++;

    ... existing code ...

    mBlockSnappingUpdates--;
    emit snappingConfigChanged( mSnappingConfig );
```

(Bonus points if you want to make a nice little RAII class which temporarily increments an int& reference for the lifetime of the object!!)

(probably we should also wrap QgsProject::removeAllMapLayers in a similar mBlockSnappingUpdates++/-- sandwich so we speed up project unload too) 

I think that would mean you could totally remove the new read flag, and desktop would also get the benefit of it (I've noticed a HUGE regression in project opening speed recently on master, and it's caused by snappingConfigChanged calling QgsSnappingLayerTreeModel::onSnappingSettingsChanged() which resets the model for every layer added/removed, and this seems much more expensive now that we use the proxy layer tree model (for whatever reason).

(It's generally quite horrible that we have this QgsSnappingLayerTreeModel hanging around which triggers all this expensive work even when the user isn't even using snapping. This could maybe be fixed by lazy updating the model as a result of snappingConfigChanged, but at least with the above suggestion we'd save a bunch of work during project load/unload)

**Comment by elpaso** [comment]
@nyalldawson I followed your advice with the RIIA blocker. Please have a look.

**Comment by nyalldawson** [comment]
https://github.com/qgis/QGIS/pull/40505 is more what I had in mind -- can you test that branch?

**Comment by elpaso** [comment]
@nyalldawson I tested your branch and it looks good: we've got ~250 ms speed gain on the "monster" project.

**Comment by NathanW2** [comment]
Just a question. How do you time your runs and knowing if you gained on a
change.

**Comment by elpaso** [comment]
@NathanW2 we are setting up the perf suite for more scientific results and to spot regressions, for now I'm running tests locally on a 32GB RAM 16 core Ryzen with something like:

```
QUERY_STRING='SERVICE=WMS&REQUEST=GetCapabilities&MAP=/home/Maps/coldstart/postgis/postgis.qgs' ./server_time.sh
```

Where server_time.sh is something like 

https://github.com/pblottiere/QGIS-Server-PerfSuite/blob/unified-builder-tests/docker/assets/server_time.sh

and  precision time is:

https://github.com/pblottiere/QGIS-Server-PerfSuite/blob/unified-builder-tests/docker/assets/precision_time.sh

But that's only part of the job, we also run hotspot to see if the changes have really made one of the flamegraph's peaks disappear as we expected.

**Pull request closed without merging**
