### PR TITLE
[settings] allow read-only access to the tree and the settings from Python

### PR DESCRIPTION
**Pull request by 3nids**
While looking at #51733, I realized that we needed a correct approach to access settings from Python.

I had a bit of a hack for the plugin manager (by creating a fake plugin) which I was not really willing to replicate for the console.

We cannot use a simple const getter in the API since sip is basically discarding the constness of the object.
Instead, I created a copy/clone method, used to clone the tree and allow access to all its children (nodes + settings).

### CODE REVIEW

**Comment by m-kuhn** [comment]
As far as I can see, the copy logic is mostly added to protect app settings.

I wonder if this is worth the price of
 - more code to maintain
 - the hard to read `copyNode`
 - no errors when writing to the throwaway copies

On the other hand with python it's already now possible to cause havoc and devs should be careful.

**Comment by 3nids** [comment]
> no errors when writing to the throwaway copies

That's easily done, since we know if this is a copy or not. So I could just throw an error.
Would that turn the balance or you'd still be in favor of opening everything to Python?

**Comment by m-kuhn** [comment]
what's the risk involved with opening it?

**Comment by m-kuhn** [comment]
Hmm... I think this all belongs into the category of things that we risk with python in general, so I would just leave it and not try to create a sandbox. So I'm still in favor of keeping this as simple as possible.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
