### PR TITLE
New icon for opening attribute table for visible features only  #42122

### LINKED ISSUE #42122: Better icon required for open attribute table in visible features mode
Refs https://github.com/qgis/QGIS/pull/42026

### PR DESCRIPTION
**Pull request by raymondnijssen**
## Description

New icon for tool: Open Attribute Table (Visible Items). This PR only contains a new svg file.

Fixes https://github.com/qgis/QGIS/issues/42122

### CODE REVIEW

**Comment by raymondnijssen** [comment]
image


image

**Comment by nyalldawson** [comment]
Ping @nirvn

**Comment by nirvn** [comment]
@raymondnijssen , I'm not 100% convinced the eye's the right symbol to have here, but since I don't have a better suggestion, you win by default? :wink:

One thing, can you take the eye symbol we already use in several of our symbols (e.g. https://github.com/qgis/QGIS/blob/master/images/themes/default/mActionShowAllLayers.svg). Thanks.

**Comment by raymondnijssen** [comment]
Thanks @nirvn 

Yes I found it hard to decide on a good symbol as well, and asked around a bit. If anyone ever gets a better idea it can be changed, right?

The current eye symbols (there are at least 2 different) are very detailed with the eyebrow. I planned to make a small and simple eye symbol for using in the right bottom corner, hence the new eye. But @SrNetoChan suggested to make it bigger.

Here's a screen shot of what I've been testing. The current eye symbols in QGIS are on the left side:

image

I also tried to get rid of the color which in my opinion distracts from the main icon. (And the blue felt a bit "white supreme" to me, but that is maybe too personal)

**Comment by nirvn** [comment]
I'd go for the blue eye with eyebrow that we use in the layers panel. +1 to share symbols across icons when we can.

**Comment by raymondnijssen** [comment]
image

Ok, here's the new one with the existing eye. I don't like it myself, but whatever... ;)

**Pull request closed without merging**
