### PR TITLE
Fix make link to pre-commit

### PR DESCRIPTION
**Pull request by ismailsunni**
## Description

Small fix on command to make a link

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]

**Comment by ismailsunni** [comment]
@m-kuhn it seems so. I think my change is working unless the filesystem is mounted. Perhaps it's better to revert my change :), sorry for the noise

**Comment by m-kuhn** [comment]
How is it related to a mounted filesystem? I'd first like to understand the reasoning before proceeding to ask for a revert :-)

**Comment by ismailsunni** [comment]
so, by using the relative path, we can mount the QGIS source directory to somewhere, and the symlink will still work[1]. 

But, if we use the absolute path (my change), the symlink will probably not work if we mount the QGIS source directory to somewhere.

This mounting is not a common case I guess, but perhaps when someone moves the whole directory, it will still work (the absolute path will not work for sure). Example, it was `/home/ismail/dev/cpp/QGIS` to `/home/ismail/new-dev/cpp/QGIS`

[1] https://unix.stackexchange.com/questions/10370/make-a-symbolic-link-to-a-relative-pathname

**Comment by m-kuhn** [comment]
What's the advantage of the absolute path?

**Comment by jef-n** [comment]
> What's the advantage of the absolute path?

Good question - I don't see one either or why an extra `./` needed.

**Comment by ismailsunni** [comment]
@m-kuhn I don't think it has any advantage now. Perhaps, at that time I couldn't create the symlink properly, then I thought it must be an absolute path. But after seeing your https://github.com/qgis/QGIS/pull/38290#issuecomment-678253847, I tried again with a relative path and it works. That's why I suggest this PR is reverted.

**Comment by m-kuhn** [comment]
:+1: Can you do a PR?
Sorry I was a bit fast with approving that fast, I had the impression that you introduced relative paths, must have been confused :-)

**Pull request merged**
