### PR TITLE
Fix convertToCurve not converting CURVEPOLYGON

### PR DESCRIPTION
**Pull request by olivierdalang**
## Description

Currently, the convertToCurve algorithm ignores geometries whose type is curved.

While there's some logic behind this behavior (one could argue a curved geometry should have been converted to curves already), it causes issues with some data providers that silently promote the features to curved types.

Is it OK to just remove the check ? Or are there some valid use cases where the current behavior is required ?

In the latter case, we can just add an `alsoConvertCurvedTypes` argument. If we do that, should we default to false (backwards compatible) or to true (IMO better choice for reliable results due to silent promotion mentioned above).

### CODE REVIEW

**Comment by olivierdalang** [comment]
@nyalldawson You left a comment foreseeing that exact change :
> In future we may want to allow this, and convert additional candidate segments in an already curved geometry to curves

Do you remember if there was a reason for still leaving that check ?

**Comment by nyalldawson** [comment]
@olivierdalang 
> Do you remember if there was a reason for still leaving that check ?

From memory it was just a note of a situation I hadn't tested at all, and wasn't handled in postgis' functionality which I based the port off. If you've tested and verified it works safely, then I'm in favour of the change.

**Review by m-kuhn — APPROVED** [review]
For context, this fixes an issue where it's possible to recreate arcs for edited geometries, but only as long as they are not saved to the provider. Once they are saved to the provider, they are (silently) promoted and can't be handled after.
@signedav knows more about the provider (gpkg?)

In unit tests I trust.

backport?

**Comment by signedav** [comment]
Yes. I encountered it on GPKG.

**Comment by signedav** [comment]
Would be great having it backported. I think mostly the user saves before running this algorithm. So it seems to be a bug.

**Pull request merged**
