### PR TITLE
Fix #16528 mix of Qgis and qgis as root in settins

### PR DESCRIPTION
**Pull request by rduivenvoorde**
On Linux the use of Qgis and qgis as root for connection settings
makes it currently impossible to add a new WCS connection

Fixes #16528

## Description

See https://issues.qgis.org/issues/16528

There was a mix of 'Qgis' and 'qgis' as root for ows/cws connections. Without the fix on a clean config, after adding a wcs connection called 'aa' you would end up with (in QGIS3.ini):

```
[Qgis]
connections-wcs\aa\referer=
connections-wcs\aa\url=http://geodata.rivm.nl/geoserver/wcs
connections-wcs\selected=aa
...
[qgis]
WCS\aa\authcfg=
WCS\aa\password=
WCS\aa\username=
connections-wcs\selected=
```
And always an empty dropdown, on Windows it apperently was ok (case-insensetive?)
While NOW you get:

```
[qgis]
WCS\aa\authcfg=
WCS\aa\password=
WCS\aa\username=
connections-wcs\aa\referer=
connections-wcs\aa\url=http://geodata.rivm.nl/geoserver/wcs
connections-wcs\selected=aa
symbolsListGroupsIndex=0
```

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [X ] Commit messages are descriptive and explain the rationale for changes
- [ X] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ X] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ X] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [X ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Grepping on /Qgis/ also reveals:

```
python/pyplugin_installer/installer_data.py:reposGroup = "/Qgis/plugin-repos"
python/pyplugin_installer/installer_data.py:settingsGroup = "/Qgis/plugin-installer"
python/pyplugin_installer/installer_data.py:seenPluginGroup = "/Qgis/plugin-seen"
python/pyplugin_installer/installer_data.py:    ("Barry Rowlingson's Repository", "http://www.maths.lancs.ac.uk/~rowlings/Qgis/Plugins/plugins.xml"),
python/pyplugin_installer/installer.py:        lastDirectory = settings.value('/Qgis/plugin-installer/lastZipDirectory', '.')
python/pyplugin_installer/installer.py:        settings.setValue('/Qgis/plugin-installer/lastZipDirectory',
python/qsci_apis/PyQGIS-2.0.api:qgis.gui.QgsNewHttpConnection?1(QWidget parent=None, QString baseKey="/Qgis/connections-wms/", QString connName=QString.null, Qt.WindowFlags fl=QgisGui.ModalDialogFlags)
python/qsci_apis/PyQGIS-2.0.api:qgis.gui.QgsNewHttpConnection.__init__?1(self, QWidget parent=None, QString baseKey="/Qgis/connections-wms/", QString connName=QString.null, Qt.WindowFlags fl=QgisGui.ModalDialogFlags)
python/qsci_apis/PyQGIS-2.2.api:qgis.gui.QgsNewHttpConnection?1(QWidget parent=None, QString baseKey="/Qgis/connections-wms/", QString connName=QString.null, Qt.WindowFlags fl=QgisGui.ModalDialogFlags)
python/qsci_apis/PyQGIS-2.2.api:qgis.gui.QgsNewHttpConnection.__init__?1(self, QWidget parent=None, QString baseKey="/Qgis/connections-wms/", QString connName=QString.null, Qt.WindowFlags fl=QgisGui.ModalDialogFlags)
python/gui/qgsnewhttpconnection.sip:    QgsNewHttpConnection( QWidget *parent /TransferThis/ = 0, const QString &baseKey = "/Qgis/connections-wms/", const QString &connName = QString::null, const Qt::WindowFlags &fl = QgsGuiUtils::ModalDialogFlags );
python/plugins/MetaSearch/dialogs/maindialog.py:        # stype = human name,/Qgis/connections-%s,providername
python/plugins/MetaSearch/dialogs/maindialog.py:            self.settings.beginGroup('/Qgis/connections-%s' % stype[2])
python/plugins/MetaSearch/dialogs/maindialog.py:            self.settings.beginGroup('/Qgis/connections-%s' % stype[1])
python/plugins/MetaSearch/dialogs/maindialog.py:            self.settings.beginGroup('/Qgis/connections-%s' % stype[2])
python/plugins/MetaSearch/dialogs/maindialog.py:            self.settings.beginGroup('/Qgis/connections-%s' % stype[1])
```

I think MetaSearch and pyplugin_installer are easily 'fixed' too.

I'm not sure about those api and sip files???

**Comment by m-kuhn** [comment]
@rduivenvoorde can you point to a place in the api and sip files where you are unsure?

**Comment by rduivenvoorde** [comment]
@m-kuhn the ones in the list above that text:

```
python/qsci_apis/PyQGIS-2.0.api:qgis.gui.QgsNewHttpConnection?1(QWidget parent=None, QString baseKey="/Qgis/connections-wms/", QString connName=QString.null, Qt.WindowFlags fl=QgisGui.ModalDialogFlags)
python/qsci_apis/PyQGIS-2.0.api:qgis.gui.QgsNewHttpConnection.__init__?1(self, QWidget parent=None, QString baseKey="/Qgis/connections-wms/", QString connName=QString.null, Qt.WindowFlags fl=QgisGui.ModalDialogFlags)
python/qsci_apis/PyQGIS-2.2.api:qgis.gui.QgsNewHttpConnection?1(QWidget parent=None, QString baseKey="/Qgis/connections-wms/", QString connName=QString.null, Qt.WindowFlags fl=QgisGui.ModalDialogFlags)
python/qsci_apis/PyQGIS-2.2.api:qgis.gui.QgsNewHttpConnection.__init__?1(self, QWidget parent=None, QString baseKey="/Qgis/connections-wms/", QString connName=QString.null, Qt.WindowFlags fl=QgisGui.ModalDialogFlags)
python/gui/qgsnewhttpconnection.sip:    QgsNewHttpConnection( QWidget *parent /TransferThis/ = 0, const QString &baseKey = "/Qgis/connections-wms/", const QString &connName = QString::null, const Qt::WindowFlags &fl = QgsGuiUtils::ModalDialogFlags );
```

And I'm wondering (talking to @NathanW2 @elpaso too) about cleaning up the settings, and forcing to use one of the sections, see discussion
https://lists.osgeo.org/pipermail/qgis-developer/2017-May/048526.html
and for sections:
https://qgis.org/api/classQgsSettings.html#aba2f174ee000905cac8aff26665ed7c7

**Comment by m-kuhn** [comment]
The sip files should be adjusted, but that should happen automatically when you adjust the .h files (so `src/gui/qgsnewhttpconnection.h` for the sip file above). You can skip the api files, they are generated on release and are not meant to be modified (they refer to past versions indicated in the file name).

**Comment by m-kuhn** [comment]
This looks good to me so far.
Thanks @rduivenvoorde , if you want to open another PR for MetaSearch and pyplugin, please go ahead :)

**Comment by timlinux** [comment]
Just a side note: II have been on a silent campaign to stop references to QGIS as Qgis - it would be nice if we could standardise on QGIS or qgis but not QGIS.

**Comment by NathanW2** [comment]
Yeah I agree. If we need to change the settings keys again now is the time
to do it. Nothing in QGIS 3 should be considered prod yet and we can
translate between the versions now.

**Pull request merged**
