### PR TITLE
Virtual layer: use expression filters

### PR DESCRIPTION
**Pull request by mhugo**
For info.
This should fix some performance problems (at least on providers that have an expression compiler, like the problem reported by @nyalldawson in #2642).
This also fixes an issue in the postgres SQL expression compiler

### CODE REVIEW

**Comment by nyalldawson** [comment]
@mhugo really nice - can't wait to test the effect this has.

Great catch on the Postgres quotedValue bug too. I'll merge that separately along with corresponding fixes for the other compilers (likely this will fix http://hub.qgis.org/issues/14030). 

But otherwise, feel free to merge the virtual layer fix - you know this stuff better than anyone else!

**Comment by nyalldawson** [comment]
OK, I've merged the postgres fix manually

**Comment by mhugo** [comment]
@nyalldawson thanks for your review, and for the other quotedValue fixes, I forgot to check the other compilers ...
I'll merge my part then :)

**Comment by mhugo** [comment]
@nyalldawson join() with a QChar is QT5 only.

**Comment by nyalldawson** [comment]
@mhugo ahh - sorry. Ignore that comment then!

**Comment by mhugo** [comment]
manually merged in 26ae3234

**Pull request closed without merging**
