### PR TITLE
Expand range of colors available for new layers

### PR DESCRIPTION
**Pull request by nyalldawson**
Here's the rules if you want to add more here (developed by
@nirvn and myself)

- Keep colors in the "middle" - avoid too light or too dark colors,
too light colors will make line layers invisible on the
default white background, too dark colors are too visually heavy
for polygon areas

- Avoid over saturated/pure colors, which are too visually heavy. E.g.

- No blues! Blues have a single meaning on maps (water) and we're
almost never going to fluke that a randomly assigned blue color
is given to a water feature layer. So we just avoid blues altogether
as users are almost always going to have to change layers away
from blue anyway.

- Avoid yellow. Yellow is used as the default selected feature color
in QGIS, so keep colors well away from this yellow to avoid confusion
between selected/unselected yellow layers

- Keep things "happy", "positive" and "friendly". No baby puke green/browns

Here's the current set of available colors:

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
On this topic... I think we should come up with a nice set of paint color names for these colors, as an easter egg to users.

E.g. we could do hackfest locations ("Light Essen salmon"), but those are already used for release names. We could also go prominent community members ("Sutton sunset" has a nice ring to it!)... but that could potentially cause issues (or are we grown up enough to take it as a fun community joke and not a reflection of the real world value of contributions?). Other ideas?

**Comment by nirvn** [comment]
Nice

**Comment by NathanW2** [comment]
Super nice.

**Comment by m-kuhn** [comment]
Nice.
Are the same colors used for fill and border?

**Comment by nyalldawson** [comment]
Just the fill color (or stroke for lines). Border remains the same dark grey it currently is.

**Comment by m-kuhn** [comment]
Would it be possible / reasonable to choose darker / desaturated border colors with the same hue? Either automatically by reducing value and saturation or by selecting matching colors for each fill color. Thinking of [material design palettes](https://material.io/tools/color/#!/?view.left=0&view.right=0) with different variants of each color.

**Comment by nyalldawson** [comment]
@m-kuhn this has been explored, but is not advisable. The reason is that if we set the border color automatically to match the random fill, then if the layer is switched to graduated/categorized renderer all the categories will have the same coloured border, regardless of the fill color. So you end up with dark red borders for green fills, etc. 

Potentially the default outline color could have a data defined `darker(@symbol_color)` expression set to overcome this, but I don't think it's advisable to set a data defined expression by default. 99% of users (at least in my experience) have no idea about what data defined settings are and how they work, and they'll just get confused why they can no longer change the border color and see the map change as a result...

Ultimately, I don't think this is possible without a ton of complicated logic and new API calls.

**Comment by m-kuhn** [comment]
> Potentially the default outline color could have a data defined darker(@symbol_color) expression set to overcome this

why not...

> why they can no longer change the border color and see the map change as a result.

is there a good reason not to disable dd overrides automatically when a user selects another color via the color button?

**Comment by nyalldawson** [comment]
Because that would break existing projects/workflows which use null field/expression values as "color from the button", and expressions which utilise @value. 

I've thought long on this - I think ultimately it's just something which needs to be done manually, and something which differentiates good cartographers from unskilled ones.

**Comment by nyalldawson** [comment]
If you're looking for an easy way to dramatically improve default cartography in qgis, have a think about how we can avoid defaulting to "ms shell dialog" for labels all time ;) that's the biggest low hanging fruit with qgis cartography.

**Comment by m-kuhn** [comment]
I want a `QgsSettings.value("/qgis/default_line_color")` in this case ;P

And that font really needs fixing, right!

**Comment by nyalldawson** [comment]
Both left as exercises for the reader.

Now back to more important matters... What can we name these colours?

**Comment by nyalldawson** [comment]
Also.. how can we close 13 pull requests in a couple of days? Hmmm?

**Pull request merged**
