### PR TITLE
[processing] Regroup executed algorithms under meaningful groups in the history dialog

### PR DESCRIPTION
**Pull request by nirvn**
## Description

Instead of putting all executed algorithms under a meaningless "ALGORITHM" group, let's create meaningful temporal groups to help people find what they are looking for.

https://user-images.githubusercontent.com/1728657/113497138-0d0cb100-952b-11eb-907d-004347d5f751.mp4

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by gioman** [comment]
@nirvn this is very cool and useful! this kind of reminds me a GRASS feature that it would be very cool to have in QGIS. While working with a GRASS location/mapset each layer is saved with some kind of metadata that allows to see 1) when a layer was created and 2) how it was created (so what tool and parameters were used). What would be the best way to have something like that at a project level in QGIS (and speaking of layers generated by Processing)? saving this infos in the project? using auxiliary storage?

**Comment by nirvn** [comment]
@gioman , @nyalldawson had a vision along those lines, laid down in a QEP (https://github.com/qgis/QGIS-Enhancement-Proposals/issues/130).

**Comment by gioman** [comment]
Thanks for the heads up.

**Comment by nyalldawson** [comment]
@gioman unfortunately I'm still looking for a funder for that one -- that original sponsor didn't take it up

**Pull request merged**
