### PR TITLE
Fix a crash when trying to removeMapLayer a null pointer

### PR DESCRIPTION
**Pull request by mhugo**

### CODE REVIEW

**Comment by nyalldawson** [comment]
LGTM! How about including a unit test though?

**Comment by m-kuhn** [comment]
@elpaso are you going to write a test for it?

**Comment by elpaso** [comment]
@m-kuhn why not? But do we really need tests for each null pointer we find?

**Comment by mhugo** [comment]
Hi I have a test coming ...

**Comment by elpaso** [comment]
@mhugo me too :) https://github.com/qgis/QGIS/pull/2536
 https://github.com/elpaso/QGIS/commit/3b48421d93e064b692f6be04b29307f721bb0a0e

**Comment by m-kuhn** [comment]
@elpaso not necessarily, but this is a quite central part of the API. Plus your merge just after the question was interpreted as a yes ;)

**Comment by mhugo** [comment]
@elpaso sorry for the lag. And thanks for the test

**Comment by elpaso** [comment]
For the record, the bug was introduced with https://github.com/qgis/QGIS/commit/4d679511fb6a164554e66f9496621e716c887fda and unfortunately no tests were asked at that time.
I would recommend that when a critical bug that provokes a segfault is found, it is merged in no time: this avoid other developers the waste of time to debug it just to discover that a PR is pending waiting for tests. This is particularly true when the bug is so obvious and requires a two lines change for a null pointer check.

**Pull request merged**
