### PR TITLE
Consistently use datasource instead of filepath when ref/unref-ing

### PR DESCRIPTION
**Pull request by manisandro**
Followup bugfix for pull #2991, see [QGIS #14764](http://hub.qgis.org/issues/14764).

### CODE REVIEW

**Comment by rouault** [comment]
There are also QgsOgrConnPool::instance()->invalidateConnections() that would need to be updated

**Comment by manisandro** [comment]
Very  true.

**Comment by m-kuhn** [comment]
I can't assign to @rouault but I trust he's the most knowledgeable with the topic. So I guess it's best if the two of you handle merging.

**Comment by rouault** [comment]
@m-kuhn The changes looks good to me. Not sure why you mean by "handle merging" ?

**Comment by m-kuhn** [comment]
@manisandro has push rights

**Pull request merged**
