### PR TITLE
always show constraints description, not only when they fail

### PR DESCRIPTION
**Pull request by tudorbarascu**

### CODE REVIEW

**Comment by tudorbarascu** [comment]
Would also like to backport this to 3.4 as I think users expect to see the constraint description on hover (tooltip) regardless of the constraint validity status.

**Comment by m-kuhn** [comment]
I think the *user* himself will probably not be interested in why a constraint succeeded, but it will also not hurt. I guess it's mostly interesting for a project administrator (like you ;) )

What would be much more important IMO is that the tooltip shows exactly which of the constraints succeeded and which failed.

**Comment by tudorbarascu** [comment]
@m-kuhn Sure! Will look into it.

**Comment by tudorbarascu** [comment]
@m-kuhn Thanks a lot! I'll surely try to fix the issue you found, a little busy this week, sorry!

**Pull request merged**
