### PR TITLE
[Oracle] Mixing SDO_GEOMETRY Point definition

### PR DESCRIPTION
**Pull request by rldhont**
## Description
Instead of using 'SDO_UTIL.FROM_WKTGEOMETRY' to generate `SDO_GEOMETRY` object
for Point, the `testdata` generate Point and MultiPoint with `SDO_POINT_TYPE`
or `SDO_ELEM_INFO_ARRAY` and `SDO_ORDINATE_ARRAY`.

With this way of creating Point and MultiPoint, we can test the way Point and
MultiPoint are converting to WKB.

If a layer has mixed `SDO_GEOMETRY` Point definition, `SDO_POINT_TYPE`
or `SDO_ELEM_INFO_ARRAY` and `SDO_ORDINATE_ARRAY `, `QOciSpatial`replaced points defined by `SDO_POINT_TYPE` by the preceding point defined with `SDO_ELEM_INFO_ARRAY` and `SDO_ORDINATE_ARRAY`. It seems that `QOCISpatialResultPrivate.sdoobj` is not well cleared between rows.

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
@rldhont The failure seems to be a legitimate issue (and the test case is much appreciated!) but I have no idea how to fix that. Maybe @jef-n has some ideas?

**Comment by rldhont** [comment]
@nyalldawson @jef-n I have found how to fix this issue!

**Comment by rldhont** [comment]
@nyalldawson can you test this fix ?
@jef-n can you review it ?

**Comment by nyalldawson** [comment]
Sure, will test tomorrow and report.

**Pull request merged**
