### PR TITLE
[Backport release-3_28][Server] Fix WFS GetFeature featureid && exp access control

### PR DESCRIPTION
**Pull request by rldhont**
Manually Backport https://github.com/qgis/QGIS/pull/51713
Authored by: @rldhont

### CODE REVIEW

**Comment by rldhont** [comment]
No more conflicts

**Comment by rldhont** [comment]
@pblottiere @elpaso all tests are green

**Comment by rldhont** [comment]
Waiting for review.

**Review by pblottiere — APPROVED** [review]

**Comment by rldhont** [comment]
Thanks @pblottiere

**Pull request merged**
