### PR TITLE
PG raster: fix Access window out of range in RasterIO errors

### PR DESCRIPTION
**Pull request by jgrocha**
## Description

Fix https://github.com/qgis/QGIS/pull/34033#issuecomment-578551028

This is not a real improvement of the code. It just ensure that we use valid tile sizes before calling `GDALRasterIO`.

## Checklist

- [X] Commit messages are descriptive and explain the rationale for changes
- [X] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [X] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [X] New unit tests have been added for core changes
- [X] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [X] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by elpaso** [comment]
@jgrocha can you please share your failing test case? Your patch does certainly prevent the issue but I would like to check if there is a way to fix the (probably rounding) error in the tile formula.

**Comment by jgrocha** [comment]
The error is pretty common with several rasters. I've upload one map from [1870](http://webgis.di.uminho.pt/~jgr/QGIS/carta_1870Planta.tif) that I used to check the tile algebra.

### Replicating the error

The raster can be loaded with:
```bash
raster2pgsql -s 3763 -d -I -C -M `pwd`/carta_1870Planta.tif  -F -t 256x256 public.carta_1870planta256x256 | psql ortos
```
```bash
raster2pgsql -s 3763 -d -I -C -M `pwd`/carta_1870Planta.tif  -F -t 1000x1000 public.carta_1870planta1000x1000 | psql ortos
```
With this raster, if I try to add them (first the 256x256 tiled, then the 1000x1000): I got these errors:
```text
ERROR 5: Access window out of range in RasterIO().  Requested
(2560,0) of size 77x256 on raster of 2636x3533.
src/core/qgsmessagelog.cpp:29 : (logMessage) [1092ms] [thread:0x561886c076d0] 2020-01-27T09:31:03 PostGIS[2] Unable to write tile to temporary raster from "public"."carta_1870planta256x256": Access window out of range in RasterIO().  Requested
(2560,0) of size 77x256 on raster of 2636x3533.
--
ERROR 5: Access window out of range in RasterIO().  Requested
(1536,3328) of size 256x206 on raster of 2636x3533.
src/core/qgsmessagelog.cpp:29 : (logMessage) [2ms] [thread:0x561886c076d0] 2020-01-27T09:31:03 PostGIS[2] Unable to write tile to temporary raster from "public"."carta_1870planta256x256": Access window out of range in RasterIO().  Requested
(1536,3328) of size 256x206 on raster of 2636x3533.
--
ERROR 5: Access window out of range in RasterIO().  Requested
(1536,3328) of size 256x206 on raster of 2636x3533.
src/core/qgsmessagelog.cpp:29 : (logMessage) [1ms] [thread:0x561886c07760] 2020-01-27T09:31:03 PostGIS[2] Unable to write tile to temporary raster from "public"."carta_1870planta256x256": Access window out of range in RasterIO().  Requested
(1536,3328) of size 256x206 on raster of 2636x3533.
ERROR 5: Access window out of range in RasterIO().  Requested
(1536,3328) of size 256x206 on raster of 2636x3533.
src/core/qgsmessagelog.cpp:29 : (logMessage) [0ms] [thread:0x561886c076d0] 2020-01-27T09:31:03 PostGIS[2] Unable to write tile to temporary raster from "public"."carta_1870planta256x256": Access window out of range in RasterIO().  Requested
(1536,3328) of size 256x206 on raster of 2636x3533.
--
ERROR 5: Access window out of range in RasterIO().  Requested
(1536,3328) of size 256x206 on raster of 2636x3533.
src/core/qgsmessagelog.cpp:29 : (logMessage) [2ms] [thread:0x561886c07760] 2020-01-27T09:31:03 PostGIS[2] Unable to write tile to temporary raster from "public"."carta_1870planta256x256": Access window out of range in RasterIO().  Requested
(1536,3328) of size 256x206 on raster of 2636x3533.
--
ERROR 5: Access window out of range in RasterIO().  Requested
(1536,3328) of size 256x206 on raster of 2636x3533.
src/core/qgsmessagelog.cpp:29 : (logMessage) [2ms] [thread:0x561886c07760] 2020-01-27T09:31:03 PostGIS[2] Unable to write tile to temporary raster from "public"."carta_1870planta256x256": Access window out of range in RasterIO().  Requested
(1536,3328) of size 256x206 on raster of 2636x3533.
--
ERROR 5: Access window out of range in RasterIO().  Requested
(2000,0) of size 637x1000 on raster of 2636x3533.
src/core/qgsmessagelog.cpp:29 : (logMessage) [982ms] [thread:0x7fd6740505c0] 2020-01-27T09:31:08 PostGIS[2] Unable to write tile to temporary raster from "public"."carta_1870planta1000x1000": Access window out of range in RasterIO().  Requested
(2000,0) of size 637x1000 on raster of 2636x3533.
--
ERROR 5: Access window out of range in RasterIO().  Requested
(2000,0) of size 637x1000 on raster of 2636x3533.
src/core/qgsmessagelog.cpp:29 : (logMessage) [2ms] [thread:0x7fd6740505c0] 2020-01-27T09:31:08 PostGIS[2] Unable to write tile to temporary raster from "public"."carta_1870planta1000x1000": Access window out of range in RasterIO().  Requested
(2000,0) of size 637x1000 on raster of 2636x3533.
--
ERROR 5: Access window out of range in RasterIO().  Requested
(2000,0) of size 637x1000 on raster of 2636x3533.
src/core/qgsmessagelog.cpp:29 : (logMessage) [1ms] [thread:0x7fd6740505c0] 2020-01-27T09:31:08 PostGIS[2] Unable to write tile to temporary raster from "public"."carta_1870planta1000x1000": Access window out of range in RasterIO().  Requested
(2000,0) of size 637x1000 on raster of 2636x3533.
```

**Comment by elpaso** [comment]
@jgrocha thanks for sharing the test case, this PR fixes the issue for me: https://github.com/qgis/QGIS/pull/34053 can you please test it?

**Comment by jgrocha** [comment]
Fixed in #34053, thanks to @elpaso 

No need to merge.

**Pull request closed without merging**
