### PR TITLE
[server] Support FILTER values with colons

### PR DESCRIPTION
**Pull request by elemoine**
## Description

Currently QGIS Server returns an error when attempting to use a FILTER with a value including one or multiple colons.  For example the FILTER

```
FILTER=layer1:"name" = 'foo:bar'
```

results in this error:

```
<ServiceExceptionReport version="1.3.0">
  <ServiceException code="Invalid WMS Parameter">
    FILTER ('layer1:"name" = 'foo:bar'') is not properly formatted
  </ServiceException>
</ServiceExceptionReport>
```

The problem is related to the [way](https://github.com/qgis/QGIS/blob/fcb572e64efe15f309a87b87027ae2c2fb2bf388/src/server/services/wms/qgswmsparameters.cpp#L1362) filters are parsed in the QGIS Server code.

In particular this bug makes it impossible to have timestamps in filters. For example:

```
FILTER=layer1: "date" >= '2017-10-23 00:00:00'
```

This PR fixes that bug.

Note: this PR includes a new control image for the tests, but I don't know how to generate the companion mask image.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by elpaso** [comment]
@elemoine can you also add a test case that do actually return something instead of a blank image?
I.e. instead of "do:not:exists"  make a real filter with a colon that returns at least one feature?

**Comment by elemoine** [comment]
> @elemoine can you also add a test case that do actually return something instead of a blank image?
> I.e. instead of "do:not:exists" make a real filter with a colon that returns at least one feature?

I guess this implies changing the data. No?

**Comment by elpaso** [comment]
@elemoine Not really, you can also make a brand new test project for this particular test.
My point is that your test does actually test only a part of your changes: it does not test if the filter works.

**Comment by elemoine** [comment]
> My point is that your test does actually test only a part of your changes: it does not test if the filter works.

I understand your point. At the same time the added test fails without my changes, and succeeds with my changes. So it is still a valid test from my point of view.

That being said I can come up with a new project and a new dataset for this test if you think it's better.

**Comment by elpaso** [comment]
> > My point is that your test does actually test only a part of your changes: it does not test if the filter works.
> 
> I understand your point. At the same time the added test fails without my changes, and succeeds with my changes. So it is still a valid test from my point of view.

Sorry if I wasn't clear, I didn't mean that to say that the current test is not valid, I just said that it isn't complete.

> 
> That being said I can come up with a new project and a new dataset for this test if you think it's better.

Thanks!

**Comment by elemoine** [comment]
@elpaso I've amended my commit to add a new project and a new gpkg file for the test.

WMS_GetMap_Filter6.png is now a non-empty image.

**Review by elpaso — APPROVED** [review]
Thanks

**Comment by elemoine** [comment]
@elpaso do you know if I need to add a WMS_GetMap_Filter6_mask.png file alongside WMS_GetMap_Filter6.png? And do you know where to get this file from?

**Comment by elpaso** [comment]
@elemoine see: https://docs.qgis.org/testing/en/docs/developers_guide/unittesting.html#comparing-images-for-rendering-tests

**Comment by elemoine** [comment]
> @elemoine see: https://docs.qgis.org/testing/en/docs/developers_guide/unittesting.html#comparing-images-for-rendering-tests

Thanks!

**Comment by elemoine** [comment]
@elpaso Travis is green. My understanding is that I don't need to provide a mask image in this case.

**Comment by pblottiere** [comment]
Thanks @elemoine, it looks good to me :+1:

**Review by pblottiere — APPROVED** [review]

**Comment by elemoine** [comment]
See https://github.com/qgis/QGIS/pull/10032 for the backport to 3.4.

**Pull request merged**
