### PR TITLE
Resurrect old qt6 workflow

### PR DESCRIPTION
**Pull request by nyalldawson**
A slow qt6 build is better than no build at all...

### CODE REVIEW

**Comment by 3nids** [comment]
sorry I was away.
There was no difference within the old and new workflow in terms of process, they were just integrated.

I see different approaches:
* We could try to build on the CI machine directly and installing Qt with jurplel/install-qt-action@v2 (it's not really clear if it supports Qt6).
* retry a bit later with the fedora builds
* wait for Ubuntu release to come up with packages (I couldn't find any evidence of an inclusion of Qt 6 in upcoming 21.10)

I didn't spend so much time developping these ideas though.
I'd say we're just a bit early, and things would get much easier soon.
In the mean time, let's add QRegExp to banned keywords in core/gui/etc. ?

**Comment by nyalldawson** [comment]
@3nids 

It's really odd, because:

1. it used to work
2. it works locally (which defeats the whole purpose of docker :angry: )

I can only assume it's some new flag or limitation which github actions is applying to the containers?

**Comment by 3nids** [comment]
Wasn't there a change in Fedora Rawhide? 
I haven't tried locally.

**Comment by nyalldawson** [comment]
Works perfectly locally for me...

**Pull request closed without merging**
