### PR TITLE
[ui] add a dedicated icon for style manager & align toolbar icons

### PR DESCRIPTION
**Pull request by nirvn**
## Description
Here we go:
image

It's not the most inspired icon, but it's already an improvement IMHO.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
Screenshot of the saved symbol widget:
image

**Comment by nyalldawson** [comment]
> It's not the most inspired icon, but it's already an improvement IMHO.

Agreed, definitely an improvement.

I wonder if this would better convey the "manager dialog" aspect of the action if it included some notion of a "dialog" here. Like you had in this earlier incarnation:

image

I'm also wondering if using an approach like this:

image

and stacking the symbols on top of each other might better convey the "manager" aspect?

**Comment by nirvn** [comment]
@nyalldawson , I went over these points, let me share my thoughts

1. Re including a visual reference to a dialog, I had two issues with it. For one, we don't really add dialogs into our icons, even though we have plenty of such instances (for e.g. the layout manager). But more importantly, adding a dialog forces the symbols to be much smaller, and it just doesn't look create for the saved symbols widget's style manager button.

2. On the alternative approach of stacking symbols, I thought the gridded placement of the symbols within the icon was useful in conveying the "management" aspect.

**Comment by nirvn** [comment]
After further discussion with @nyalldawson on hangout, I've updated the icon some more:
image

- icon now avoids using selection yellow to avoid confusion, instead uses a nice green color
- a fourth item was added, the letter "a", to balance the icon and hint at the eventual addition of saved text presets

**Comment by nyalldawson** [comment]
Looks great!

**Pull request merged**
