### PR TITLE
QgsCoordinateTransform::transformCoords(): do not convert elevations to radians

### PR DESCRIPTION
**Pull request by rouault**
Fixes #14702

### CODE REVIEW

**Comment by nyalldawson** [comment]
Hmm... the fix looks correct, thanks. But I'm wondering if we even should be converting the z coordinates to begin with. There's no guarantee that they represent heights relative to the ellipsoid, and could instead represent any height unit/relative measure. So my gut feeling would be that we should leave these as is and never attempt to transform them. What do you think?

**Comment by rouault** [comment]
> But I'm wondering if we even should be converting the z coordinates to begin with
That's a good point and a recurrent problem indeed. The issue only arises when datum changes are involved. One could argue that QgsCoordinateTransform::transformCoords() should be supposed to do what is instructed to do, ie convert a (x,y,z) from a CRS to another one, and thus assume that the provided z is consistant with the CRS defintion. Even if in most cases the z is probably not relative to the ellipsoid but to some geoid. Proj.4 CRS strings can include an explicit +geoidgrids parameter, so potentially you could have a CRS definition that is WGS84 for 2D + EGM2008 for heights.

**Comment by rouault** [comment]
@nyalldawson I think we should merge this as it fixes something obviously wrong before, right ? The question about the vertical datum is a tougher one.

**Comment by nyalldawson** [comment]
+1 to merge. I'm working on the other fix now

**Pull request merged**
