### PR TITLE
 List more geometry types in New Memory Layer dialog

### PR DESCRIPTION
**Pull request by DelazJ**
Fixes [#17594](https://issues.qgis.org/issues/17594)

@andreasneumann suggested in the issue report to use ogc terms like Linestring (or LineString/Line string?) instead of Line. Not enough knowledge on what is desirable to have a strong opinion, here... and whether this should be applied to other providers....

### CODE REVIEW

**Comment by lbartoletti** [comment]
Hi,

According to [SFA](http://www.opengeospatial.org/standards/sfa) for me it's LineString.

> A LineString is a Curve with linear interpolation between Points. Each consecutive pair of Points defines a Line segment.
> A Line is a LineString with exactly 2 Points.

**Comment by nyalldawson** [comment]
+1 for LineString

**Comment by DelazJ** [comment]
So LineString and MultiLineString? For other providers (shapefile, gpkp, spatiaLite) also?

Btw, @nyalldawson would that make sense to use expression like ˋQgsWkbTypes::displayString( QgsWkbTypes::LineString )ˋ (used in save vector as... dialog) to avoid different translated spelling from a dialog to another (i saw in French different spellings for these types so would be nice to have something uniform.)?

**Comment by nirvn** [comment]
+1 from me.

@nyalldawson , OK to merge?

**Pull request merged**
