### PR TITLE
Fix MXE builds after protobuf

### PR DESCRIPTION
**Pull request by elpaso**

### CODE REVIEW

**Comment by nyalldawson** [comment]
Yay!

**Comment by wonder-sk** [comment]
Thanks @elpaso !

**Comment by roya0045** [comment]
@elpaso Thanks a ton! I'm not sure if you needed to update the image but when I tried to simply add protobuf as you did it always failed :(

**Comment by roya0045** [comment]
I confirm that MXE builds now! But it also runs out of space and cannot compile.

**Comment by elpaso** [comment]
@roya0045 I see, I don't know what we can do about it ...

**Comment by roya0045** [comment]
@elpaso Its fine, I'll try to find a way to make the build lighter. I was just curious if anyone else also had that issue.

**Comment by elpaso** [comment]
My local build went just fine.

**Comment by elpaso** [comment]
I wrote an email to github support, let's see if/what they answer.

**Comment by roya0045** [comment]
@elpaso That's strange, it might be something related to the windows pipeline or maybe I need to trigger it again.

**Comment by roya0045** [comment]
@elpaso I have found a way to get it to build. I remove the source dir and cache before zipping. Do you want me to make a PR with those tweaks?

**Comment by elpaso** [comment]
Sure, thank you.On Apr 9, 2020 23:06, Alex <notifications@github.com> wrote:
@elpaso I have found a way to get it to build. I remove the source dir and cache before zipping. Do you want me to make a PR with those tweaks?

**Pull request merged**
