### PR TITLE
Ensure that orig_ogc_fid field is only ever used internally

### PR DESCRIPTION
**Pull request by nyalldawson**
We don't want to expose this field to users, or include it in layer exports or copies

And rename internal field to __orig_ogc_fid to avoid clashes with existing datasets which have been exported before this fix and which now contain a orig_ogc_fid field

### CODE REVIEW

**Comment by nyalldawson** [comment]
@rouault look OK to you?

**Comment by nirvn** [comment]
@nyalldawson , @rouault , I've tested a build with this PR and PR #7091 , and I'm happy to report things appear to work flawlessly. The UI freeze when iterating through selected features on a filtered OGR layer is gone, and the attribute table / identity tool / etc. are working properly.

**Comment by rouault** [comment]
LGTM

**Comment by nyalldawson** [comment]
Thanks @nirvn, @rouault!

**Pull request merged**
