### PR TITLE
3.6 backports

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by nyalldawson** [comment]
@3nids do you know what the docker issues are with the 3.6 branch?

**Comment by 3nids** [comment]
https://travis-ci.org/qgis/QGIS/builds/497891210
a spelling error and a failing test?

**Comment by nyalldawson** [comment]
@3nids the original error is:

"Unable to find image 'qgis/qgis:release-3_6' locally
docker: Error response from daemon: manifest for qgis/qgis:release-3_6 not found."

**Comment by 3nids** [comment]
the cron job was not yet activated, hence no image were produced and pushed. I added the job, this should be fixed in next couple of hours.

**Comment by nyalldawson** [comment]
Thanks!

**Pull request merged**
