### PR TITLE
Migrate remaining(*) uses of QRegExp in src/providers and tests/

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR migrates the remaining(*) uses of QRegExp in src/providers to QRegularExpression.

For those keeping track of the score, QRegExp is gone from:
- src/core (pending #44170)
- src/providers (pending this)
- src/auth
- src/analysis

_(*) the stagnant GRASS provider hasn't been ported, no interest on my side._

### CODE REVIEW

**Comment by nirvn** [comment]
Also, that'll be it for me, hopefully someone can pick up the torch and go through remaining uses in src/gui and src/app :)

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
(For reference, the test sources also need updating)

**Comment by nirvn** [comment]
@nyalldawson , oh yeah, completely forgot about tests. Fortunately, very few uses:
image

**Comment by nyalldawson** [comment]
Looks like we'll be able to revive https://github.com/qgis/QGIS/pull/42536 soon!

**Comment by nirvn** [comment]
@nyalldawson , I sure hope so.

**Comment by nirvn** [comment]
@nyalldawson , here, tests done.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Argh - just saw that there's also a handful of uses in db manager too!

**Pull request merged**
