### PR TITLE
backport german translation fixes

### PR DESCRIPTION
**Pull request by jef-n**
Done with:

```
scripts/update_ts.sh update $BUILDDIR de
mv i18n/qgis_de.ts i18n/orig.ts
tx pull -l de
mv i18n/qgis_de.ts i18n/pull.ts
lconvert -i i18n/orig.ts -i i18n/pull.ts -o i18n/qgis_de.ts
rm i18n/orig.ts i18n/pull.ts
scripts/update_ts.sh update $BUILDDIR
git add doc/TRANSLATORS i18n/qgis_de.ts
git checkout i18n
git commit
```

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by m-kuhn** [comment]
Is this something to apply on other languages too?

**Comment by jef-n** [comment]
> Is this something to apply on other languages too?

not directly - they probably don't have any typos in the translations ;)

**Comment by DelazJ** [comment]
@jef-n i don't understand all the commands but is this something that can help to avoid double translation (3.4 and 3.8) of all the new processing strings recently loaded. I mean, translate only in Transifex and backport with your receipe to 3.4 branch? Safer?

**Comment by jef-n** [comment]
@DelazJ yes.

```
scripts/update_ts.sh update $BUILDDIR de
mv i18n/qgis_de.ts i18n/orig.ts
```

updates the `de` ts file to match the current state of the release branch (ie. add strings that were changed or introduced by backports) and moves it out of the way afterwards.

```
tx pull -l de
mv i18n/qgis_de.ts i18n/pull.ts
lconvert -i i18n/orig.ts -i i18n/pull.ts -o i18n/qgis_de.ts
rm i18n/orig.ts i18n/pull.ts
```
fetches that current `de` translation state  for master, merges it with the old (only overwriting new stuff) and removes the merged files.

At this point you would also run _Linguist_ to update uncovered translations - not necessary this time.

```
scripts/update_ts.sh update $BUILDDIR
```

syncs the translations  removing the translations from `de` that belong to strings not in the release branch and updating the stats in `doc/TRANSLATORS` (therefore not restricted to `de`).

```
git add doc/TRANSLATORS i18n/qgis_de.ts
git checkout i18n
git commit
```

caches the wanted changes to `TRANSLATORS` and `de`, removes the changes to other languages and commits them.

**Comment by DelazJ** [comment]
Great! thanks. It will definitely make the process smoother (I hope - no more need to have both linguist and transifex open and doig search and copy-paste of strings in one or other direction). We'd prioritarily just focus on cleaning transifex.
Would that be worth saving it somewhere (see https://github.com/qgis/QGIS-Website/issues/592)?

**Pull request merged**
