### PR TITLE
[processing] Initial work on porting base GUI classes to c++

### PR DESCRIPTION
**Pull request by nyalldawson**
- Add abstract base class for Processing widget wrappers to c++
- Add wrapper factory interface to c++
- Make QgsProcessingGuiRegistry also register widget wrapper factories, and be responsible for creation of new c++ processing widget wrapper instances
- Start on private c++ implementation of boolean widget wrapper, including unit tests

Mostly, this is a direct port of the existing Python WidgetWrapper class to c++, but with some methods renamed to avoid clashes with WidgetWrapper (which will need to hang around for the lifetime of 3.x). As much as possible this won't break any existing Python code, but there is a chance that if plugins have been relying on private members and behavior in these classes then they will need to be adapted. (That's on them -- private members were never part of stable API!)

The biggest change from the original Python classes is that widget wrappers now require a QgsProcessingContext when setting their value. This allows us to reuse the various QgsProcessingParameters::valueAs* methods to convert a parameter value to the corresponding object type. The advantage with this is that it ensures parity between the values acceptable by a parameter, and those which can be set for the parameter's widget (without a ton of duplicate code). This is probably the biggest source of bugs in Processing widget's -- they get passed a specific value which they don't know how to deal with (e.g. a map layer parameter may get passed a map layer id string, a map layer name string, a direct map layer reference, a QgsProcessingFeatureSourceDefinition, etc.... ). The QgsProcessingParameters::valueAs* methods know how to interpret ALL these values, so it makes sense to reuse them here.

Why port to c++? Well, the second biggest source of bugs in these widgets has been Python's inevitable tendency to break as other code is tweaked... By porting to c++ we ensure the additional stability guarantee which comes with compiled code.

TODO:
- handle parameters in modeler dialogs
- port the remaining parameters one-by-one, soaking each in unit tests as we go

### CODE REVIEW

**Comment by elpaso** [comment]
Nice! Just curious here, are you planning to reuse any of the form  widgets code and logic here?

**Comment by pblottiere** [comment]
> the second biggest source of bugs in these widgets has been Python's inevitable tendency to break as other code is tweaked... By porting to c++ we ensure the additional stability guarantee which comes with compiled code.

:heart_eyes:

**Comment by luipir** [comment]
> This allows us to reuse the various QgsProcessingParameters::valueAs* methods to convert a parameter value to the corresponding object type. The advantage with this is that it ensures parity between the values acceptable by a parameter, and those which can be set for the parameter's widget (without a ton of duplicate code). This is probably the biggest source of bugs in Processing widget's -- they get passed a specific value which they don't know how to deal with (e.g. a map layer parameter may get passed a map layer id string, a map layer name string, a direct map layer reference, a QgsProcessingFeatureSourceDefinition, etc.... )

yes please

**Comment by nyalldawson** [comment]
@elpaso I looked into that, but we can't deviate too far from the current python processing API without breaking it. It's also quite mature and well suited to processing's requirements.

Maybe something to revisit in 4.0 though...

**Comment by nyalldawson** [comment]
Superseded

**Pull request closed without merging**
