### PR TITLE
[3.12] Restore inspection of non-PostGIS enabled PostgreSQL databases

### PR DESCRIPTION
**Pull request by strk**
See #34966

### CODE REVIEW

**Comment by gioman** [comment]
@strk I can't review code, but I can test it when it is merged on master.

**Comment by m-kuhn** [comment]
Is this a backport?

**Comment by strk** [comment]
Yes. Well, actually I first wrote it for 3.12, then I forward-ported (version for master is https://github.com/qgis/QGIS/pull/35019) ... Why does it matter ?

**Comment by m-kuhn** [comment]
Thanks.
Because I had in mind that I reviewed something similar recently and wanted to lookup what I left there as comment - if any.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
