### PR TITLE
New algorithm "Geodesic line split at antimeridian" [processing] 

### PR DESCRIPTION
**Pull request by nyalldawson**
Ports the similar algorithm from the shape tools plugin to c++, and utilises
built in QgsDistanceArea ellipsoidal calculations to split the lines.

This algorithm splits a line into multiple geodesic segments, whenever the
line crosses the antimeridian (±180 degrees longitude)

Splitting at the antimeridian helps the visual display of the lines in some
projections. The returned geometry will always be a multi-part geometry.

Whenever line segments in the input geometry cross the antimeridian,
they will be split into two segments, with the latitude of the breakpoint
being determined using a geodesic line connecting the points either side
of this segment. The current project ellipsoid setting will be used when
calculating this breakpoint.

If the input geometry contains M or Z values, these will be linearly
interpolated for the new vertices created at the antimeridian.

Supports in-place edit mode also.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Ping @hamiltoncj

**Comment by hamiltoncj** [comment]
I'm glad to see this. Thanks! With these additions is there the more general case in which you have two points with headings and you find were they intersect?

**Comment by nyalldawson** [comment]
@hamiltoncj not yet unfortunately -- the maths because considerably more complex for that!

**Comment by suztomo** [comment]
@nyalldawson Hi, is this "[Geodesic line split at antimeridian](https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#geodesic-line-split-at-antimeridian-36)" available in QGIS 3.6.2 GUI? I'm thinking your algorithm may be the solution to my question below:

(In my hobby, I'm learning how to use QGIS) 
https://gis.stackexchange.com/questions/321347/oblique-mercator-distorts-edges-of-map

**Pull request merged**
