### PR TITLE
Update  default windows state and geometry for QGIS 3.0

### PR DESCRIPTION
**Pull request by nirvn**
## Description
This PR updates (in the case of layouts, restores) the default state and geometry of QGIS' main window and the layout designer. To do so, the mkuidefaults.py script had to be updated a bit.

This allows us to ship QGIS 3.0 with a presentable default look 😉 

@nyalldawson , for the layout designer, I've decided to use the same default geometry as the main window (namely, 80% of the screen), it's much nicer than a fixed width and height.

I've kept the defaultUIgeometry[] and defaultLayoutDesignerUIgeometry[] static variables in there in case we want to ever revert to that.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
Main window, before (top) vs. proposed (bottom):
screenshot from 2018-02-18 14-04-54
screenshot from 2018-02-18 14-05-56

Layout designer window, before (top) vs. proposed (bottom):
screenshot from 2018-02-18 14-05-08
screenshot from 2018-02-18 14-06-19

**Comment by nirvn** [comment]
Travis failure unrelated, ready to merge.

**Comment by nyalldawson** [comment]
+1, much cleaner

Looking at these screenshots, How would you feel about renaming "command history" to "undo history"? "Command history" sounds very techy and I doubt most users associate things like moving an item as a "command".

**Comment by nirvn** [comment]
@nyalldawson , good idea. That'll align the terminology with what's being used in gimp and inkscape too.

**Comment by Gustry** [comment]
Thanks, much better! !

I'm also wondering about the label toolbar. Should it be displayed by default too? I sometimes ask some students to hide it to have less icons on their interface (for beginners)

**Pull request merged**
