### PR TITLE
[Feature] Make layout item labels us the full font formatting options

### PR DESCRIPTION
**Pull request by roya0045**
## Description

This is a work in progress, I'm not sure if this is feasible at the moment. I'm setting the PR as a draft for suggestions or blockers.

Some elements still need to be addressed and I moved some function for reusability.

Comments are appreciated.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@roya0045 just a heads up: there's one big limitation in the text renderer which has blocked this work till now, which is that the text renderer doesn't yet support the "justify" horizontal alignment mode. This mode is an existing option for layout labels, so we need to implement it in the text renderer before we can do the switch.

I think to do this properly we'll need to dig into qt source and see how they've implemented it, and copy the logic to text renderer.

**Comment by roya0045** [comment]
@nyalldawson [This code?](https://github.com/qt/qtbase/blob/d79a9b1a4f694a227ce62ccab9b44685a9755916/src/gui/text/qtextengine.cpp#L2435) 
Do we need support for the arabic fancy stuff also or just base latin text?

**Comment by nyalldawson** [comment]
@roya0045 

I'd love to assist here, as it's a much needed feature! Can I request that you:
1. Close this PR for the moment (leave the branch on your fork though!)
2. Open a new PR with just the implementation of justify mode in QgsTextRenderer, when that's ready for review
3. We'll get the underlying justify handling merged first, and then you can re-open the work which migrates the layout items to QgsTextRenderer

Otherwise I'm concerned that this branch/PR will become too large and difficult to review

**Comment by nyalldawson** [comment]
Actually... I must have already done this at some stage, and then totally forgotten about it!!! 445beba9b6ac1c5b58a3cf14b238e2f0056575fc

**Comment by roya0045** [comment]
> Actually... I must have already done this at some stage, and then totally forgotten about it!!! [445beba](https://github.com/qgis/QGIS/commit/445beba9b6ac1c5b58a3cf14b238e2f0056575fc)

So instead of spacepadding as I was looking into you went with `QFont::setWordSpacing`, I wasn't sure if rendering effects would have an effect on whitespace, but if not with the base I already have it shouldn't be too hard to just change the setwordspacing of the font in the format, but I'm not sure if there is an independent way to render the effects and the spacing by rendering lines one by one with varying space. I don't mind closing this in the meantime.

**Comment by roya0045** [comment]
The rending works, though I get some crashes that I need to solve, and the alignment ( including justification) behaves anormaly (alighr right move text out of box to the left, same with down and center to a lesser extent...) Things are progressing.

**Comment by nyalldawson** [comment]
@roya0045 are you referring to the table change or label change? I think you can revert most of the table changes -- there's already support for QgsTextRenderer there

**Comment by roya0045** [comment]
@nyalldawson  The layout item label. The changes made to the table were to move the existing justification functions to a more centralised space as this was how justification was carried out.

**Comment by roya0045** [comment]
Crashes are solved. Though the alignment behaviour is still totally wrong. Now that the build is fixed I only need to focus on why things are badly rendered and the rest should be relatively smooth sailing, I hope. We'll see what I can solve this weekend.

**Comment by roya0045** [comment]
label_effects_current
@nyalldawson Here is a gif of the current behavior with only only adding support for rendering. As you can see the current behaviour of qgstextrenderer behaves strangely, now I am not too sure if I fix this I may break something else. Should I do label specific handling from the onset or you do have in mind another element that uses qgstextrenderer and the placement flag. This way I could validate if I broke anything elsewhere.

**Comment by roya0045** [comment]
Part of the issue come from here:; https://github.com/qgis/QGIS/blob/fd7406cb08e7ec745cd6eeb3657f20616221c026/src/core/textrenderer/qgstextrenderer.cpp#L1515

Though, the units don't match, one use render units and the other layout units I would guess.

**Comment by roya0045** [comment]
Ok solved it, though there is a random margin in the layout box, but justification is fine once I convert the render mm to dots, as expected.

**Pull request closed without merging**
