### PR TITLE
world_map.gpkg fix (fixes #46810)

### LINKED ISSUE #46810: Crimea should be not a part of Russia in world_map.gpkg
### What is the bug or the crash?

The bug is about the "world_map.gpkg" located in the https://github.com/qgis/QGIS/tree/master/resources/data.

This GeoPackage contains data incorrectness: Crimea is a part of Russia.
I believe you understand why it is wrong.

Therefore, I am kindly asking you to apply the corresponding changes.
Please, make Crimea a part of Ukraine.

### Steps to reproduce the issue

I was able to observe it here: https://gis.stackexchange.com/a/420610/99589

### Versions

QGIS 3.20 Odense

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jef-n**
update states_provinces set iso_a2='UA',sov_a3='UA',adm0_a3='UA',admin='Ukraine',gu_a3='UKR' where name IN ('Crimea','Sevastopol');
update countries set geom=st_union(geom, (select st_union(geom) from states_provinces where name IN ('Crimea','Sevastopol'))) where name='Ukraine';
update countries set geom=st_difference(geom, (select st_union(geom) from states_provinces where name IN ('Crimea','Sevastopol'))) where name='Russia';

Fixes #46810

### CODE REVIEW

**Comment by Gustry** [comment]
Maybe you should update `resources/data/README_world_map.md` ?

**Comment by nyalldawson** [comment]
Shouldn't this step be added to https://github.com/qgis/QGIS/blob/master/resources/data/world_map_generalize.model3 ?

**Comment by nyalldawson** [comment]
(fwiw i'm in favour of this change, and I don't think we need to be bound by the same decision as upstream natural earth made)

**Comment by anitagraser** [comment]
+1 for merging this

**Comment by Symbian9** [comment]
+1 for merging this too

**Comment by m-kuhn** [comment]
Technical ones
https://github.com/qgis/QGIS/pull/48120#issuecomment-1092106542 and subsequent

**Pull request merged**
