### PR TITLE
Add QgsProcessingAlgorithm::parameterAsBoolean

### PR DESCRIPTION
**Pull request by m-kuhn**
For consistency

Alias to QgsProcessingAlgorithm::parameterAsBool(), because the parameter class is called
QgsProcessingParameterBoolean

### CODE REVIEW

**Comment by nyalldawson** [comment]
Looks, good, just add a unit test and you're good to merge

**Comment by m-kuhn** [comment]
@nyalldawson does that look good to you like that?

**Comment by m-kuhn** [comment]
Actually I was wondering if we should move all our own implementations to this interface to have a consistent interface we use. Opinions? Anyone attached to the shorter version?

**Comment by luipir** [comment]
> Anyone attached to the shorter version

is it planned for 4.0 api break?

**Comment by m-kuhn** [comment]
No, it's gonna coexist, but if there's a consensus we can deprecate it for 4.0.

**Comment by luipir** [comment]
> we can deprecate it for 4.0.

I'm ok to start deprecating short version

**Comment by nyalldawson** [comment]
I'm -0 on deprecating. I think Processing plugin authors have been through enough hurt with 3.x that I'm reluctant to deprecate stuff unless we have absolutely no other choice.

**Comment by m-kuhn** [comment]
I originally wasn't proposing deprecation for exactly this reason.
The question is, should we promote the longer "new" version by updating our code (which should be seens as sample to communicate best practice)?

**Comment by nyalldawson** [comment]
In that case I'm +0

**Comment by luipir** [comment]
> enough hurt with 3.x that I'm reluctant to deprecate

ok

**Pull request merged**
