### PR TITLE
Drag'n'drop improvements backport to 3.10

### PR DESCRIPTION
**Pull request by 3nids**
backport of #34411, #34433, #34479 and 34503
it will live for a month in 3.12 before reaching next release of 3.10, so this sounds safe enough to me

### CODE REVIEW

**Comment by 3nids** [comment]
is there any objection to backporting this to 3.10?

**Comment by nyalldawson** [comment]
I guess I'm -0, but not a strong -. Does this fix any bugs or is it just a UX improvement?

**Comment by 3nids** [comment]
@nyalldawson mainly a UX improvement. It's mainly code moving around and it's very contained. No issue has been reported on 3.12.

**Comment by m-kuhn** [comment]
+0 from my side
It's not super high priority, but a *very* nice UX enhancement.

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
