### PR TITLE
Upgrade OGCAPIF testsuite to 1.4

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

A new Docker image is available for the OGC API Features testsuite (cf https://hub.docker.com/r/ogccite/ets-ogcapi-features10/tags) but some tests newly added are failing.

I'm going to take a look.

### CODE REVIEW

**Comment by pblottiere** [comment]
@elpaso fyi

**Comment by pblottiere** [comment]
@elpaso fyi

**Comment by elpaso** [comment]
> @elpaso fyi

Rather cryptic... :/

**Comment by pblottiere** [comment]
>> fyi @elpaso fyi

> Rather cryptic... :/

Sorry ^^. It was just to let you know that QGIS Server is failing on the latest OGC testsuite version for OGC API Features (Docker image `ogccite/ets-ogcapi-features10:1.4-teamengine-5.4.1`).

But actually, we're facing some issues in the testsuite itself (https://github.com/opengeospatial/ets-ogcapi-features10/issues/125 and https://github.com/opengeospatial/ets-ogcapi-features10/issues/185). So I'm waiting for a new release of the testsuite to proceed further.

So I'm closing this MR for now.

**Comment by elpaso** [comment]
> > > fyi @elpaso fyi
> 
> > Rather cryptic... :/
> 
> Sorry ^^. It was just to let you know that QGIS Server is failing on the latest OGC testsuite version for OGC API Features (Docker image `ogccite/ets-ogcapi-features10:1.4-teamengine-5.4.1`).
> 
> But actually, we're facing some issues in the testsuite itself ([opengeospatial/ets-ogcapi-features10#125](https://github.com/opengeospatial/ets-ogcapi-features10/issues/125) and [opengeospatial/ets-ogcapi-features10#185](https://github.com/opengeospatial/ets-ogcapi-features10/issues/185)). So I'm waiting for a new release of the testsuite to proceed further.
> 
> So I'm closing this MR for now.

It'wasn't **you** being cryptic, it's the test suite failure which is.

**Pull request closed without merging**
