### PR TITLE
[FEATURE] Add option to take extent from project map layer to QgsExtentGroupBox

### PR DESCRIPTION
**Pull request by nyalldawson**
This allows matching another layer's extent in the save vector/ raster layer dialog, among others

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , nice.

**Comment by nirvn** [comment]
@nyalldawson , there's a UI placement issue in the save as image dialog:
screenshot from 2017-06-01 09-16-08

**Comment by nyalldawson** [comment]
@nirvn Hmm, that's because the "original extent" button is missing in this context. Qt really needs some "flowing" layout options...

**Comment by nirvn** [comment]
@nyalldawson , what about regrouping original extent, map canvas extent, and layer extent under a single drop down list?

**Comment by nirvn** [comment]
We could have a gear-logo button located on upper right region of the widget, with a menu of actions to set extent to canvas/layer/original (and eventually drag on canvas action)

**Pull request merged**
