### PR TITLE
[processing] Union: fix output of features that do not instersect layer A

### PR DESCRIPTION
**Pull request by wonder-sk**
(forward ported from 2.18 - see original PR #4037)

Union algorithm had incorrect logic for output of geometries in layer B
that are partially intersected by layer A or not intersected at all.

Added processing unit test that should cover all cases.

I have added some TODOs to the code as the outputs may still misbehave
if intersection or difference operations return unexpected geometry types.

### CODE REVIEW

**Comment by wonder-sk** [comment]
@mkuhn Any idea why the processing test fails due to invalid CRS of expected layer? It worked fine in 2.18 branch...

https://dash.orfeo-toolbox.org/testDetails.php?test=53035171&build=262732

**Comment by wonder-sk** [comment]
With @nyalldawson 's hint to delete XSD and add GFS file (autogenerated by QGIS) I got past the CRS failure... now it fails on different order of features in resulting/expected layers.

https://dash.orfeo-toolbox.org/testDetails.php?test=53070110&build=262817

TODO: allow unordered comparison of features in processing tests

**Comment by ghtmtt** [comment]
@wonder-sk I ran some test and quite often I got the same issues you got:

https://travis-ci.org/qgis/QGIS/builds/196649370
https://travis-ci.org/qgis/QGIS/builds/201794772#L935

**Comment by gioman** [comment]
@wonder-sk Hi Martin! thanks for tackling this. I tested the patch on 2.18.4, which I assume (correct?) is already included, using (for example) http://hub.qgis.org/attachments/10743/Input_files.zip from one of the tickets about the Union issues. The result still contains duplicated/overlapping geometries, so it is still not ok unfortunately. 

cheers!

**Comment by gioman** [comment]
@wonder-sk sorry disregard my previous comment, I made confusion with the intersection. Still does not seems right (I always assume that 2.18.4 contains the patch). Test http://hub.qgis.org/attachments/6162/two_layers.tar.gz and compare with the expected result 

image

**Comment by alexbruy** [comment]
Looks like this can be closed, as union in master was refactored and improved

**Comment by wonder-sk** [comment]
Indeed - an improved version is on master now (#6859)

**Pull request closed without merging**
