### PR TITLE
Fixed confusing french translation, geometry checker plugin, not in T…

### PR DESCRIPTION
**Pull request by arx-it**
…ransifex

## Description
French translation of the Geometry Checker plugin is sometimes confusing. Here's a proposal for 2 form labels.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
@DelazJ any idea what's going on?

**Comment by arx-it** [comment]
What's wrong with my PR?

**Comment by m-kuhn** [comment]
The .ts file will be overwritten by the translations from transifex before the release if I am not mistaken.
So the question should be why it's not on transifex.

**Comment by arx-it** [comment]
Yes, I was afraid of that.

But I searched and the translation is not on transifex.

**Comment by DelazJ** [comment]
https://www.transifex.com/qgis/QGIS/translate/#fr/qgis-application/101333858?q=overlaps%20smaller

**Comment by arx-it** [comment]
Sorry I was searching for the french translation, but it has already been changed. This PR can be closed.

**Comment by DelazJ** [comment]
what is weird is that the texts you are fixing are not available in QGIS 3. They are from QGIS 2.18 although you are using an almost up to date master branch (whose latest commit on `fr` file was on may 31st).

@jef-n how/when is the i18n/ folder updated (and how is that the GUI is synced with transifex but not the i18n folder)? Thanks

**Comment by jef-n** [comment]
scripts/pull_ts.sh is run in the master nightlies and in scripts/release.pl on major & minor releases.

**Pull request closed without merging**
