### PR TITLE
[DbManager] Use the new authentication system (fixes #13841)

### LINKED ISSUE #13841: "Screen scaling" setting to control the screen size of things defined in points or mm
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [3783](https://issues.qgis.org/issues/3783)

Redmine category:map_canvas

---
With the new labelling engine (I have not tested with the old):
If the label font size is set in points (instead of map units), then on a typical monitor the labels are displayed in the map canvas at approximately the same size as they are printed on paper.  If I remember correctly (I'll check tomorrow), the same is true for vector symbols if their size is set in mm instead of map units.

Changing the DPI setting in the operation system does not affect the size (at least in Windows - perhaps someone could test in another operating system).  Presumably this means that QGIS (or maybe an underlying library such as QT) is using some "typical" value for screen DPI.  This is likely to be 72dpi or 91dpi or something.

You might think it would be good for the size to change depending on the DPI setting in the operating system, so that if this was set correctly then the labels and symbols would be exactly the same size on paper as on the screen.  BUT in reality this would be bad, for the same reason that the current behaviour is bad: _screen dpi is normally much lower than any printer output, so small labels and symbols which are easily legible on paper are not legible on the screen_.  

I think ideally QGIS should have its own setting to control the screen rendering size of labels and symbols (if they are not defined in map units).  I'm not sure what the best name for the setting would be - maybe something like "Screen scaling factor".  The units should be in DPI, so that if someone _does_ want things to be exactly the same height on paper as on the screen, they can simply set it to the actual DPI of their monitor.

### PR DESCRIPTION
**Pull request by SebDieBln**
DbManager was not updated to use the authentication system introduced with #2330 and thus left users
- still having to enter username/password
- accidentally reveal credentials when sharing projects or layer-definition-files

This PR fixes that.

### CODE REVIEW

**Comment by m-kuhn** [comment]
@dakcarto would you mind giving this a short review?

**Comment by SebDieBln** [comment]
I just noticed the ```bool expandAuthConfig=true``` also applies to ```QgsDataSourceURI.connectionInfo()```, which is also used in DbManager. I will add another commit to fix this, too.

**Comment by SebDieBln** [comment]
@dakcarto There is still a minor usability issue and I am not sure where to handle it:
If the user actually has to enter the master password while DbManager accesses a database, the focus is changed to the QGIS main window and the DbManager window seems to "disappear", because it is now in the background. Of course it is still accessible via its task bar button.
Should this be handled in DbManager or rather in the authentication manager because it may affect other plugins accessing databases as well?

**Comment by dakcarto** [comment]
Hi,

@SebDieBln Thanks for your work on this and taking the time to submit a PR! I will review this ASAP, probably today.

**Comment by SebDieBln** [comment]
@dakcarto I checked the calls to ```QgsDataSourceURI.connectionInfo()``` and they all need to have ```expandAuthConfig``` set to _True_, which is the default. However I added it to every call to clarify the intention.

**Comment by SebDieBln** [comment]
rebased this PR against master

**Comment by SebDieBln** [comment]
rebased this PR against master
@dakcarto Do you still have this on your list? :smile:

**Comment by luipir** [comment]
Hi @SebDieBln I've prepared for Boundless some dockers to simplify PKI postgres testing. You can find at this link:
https://github.com/luipir/Postgis-pki-datacontainers
I'll try to review the code.

**Comment by dakcarto** [comment]
@SebDieBln, @luipir will review this, as he is currently working in this area of the code, and will probably incorporate some of your work here. Thank you for your patience.

**Comment by SebDieBln** [comment]
@dakcarto, @luipir I'm glad this PR finally gets some attention after quite a long phase of silence :smile: 

Because this PR is a __bugfix__ and already __tagged for QGIS 2.14__ I assume we are not threatened by the upcoming feature freeze.

Note that all I did was basically adding a few `true`s at the right places to make _DbManager_ request the authentication data where needed and a few `false`s to indicate the deliberate use of the default value.

The _Postgis-pki-datacontainers_ sound interesting, although I don't see how they are related to this issue?

Please post here if there is anything I can do to help you review and merge this PR. And of course, if your work within _DbManager_ that @dakcarto is referring to already fixes this issue, feel free to close this PR as soon as your work is merged into master.

**Comment by luipir** [comment]
probably I'll cherry pick your patches... I already read your patch and it's fine, I just check if the url expansion is done in the correct place and not too early exposing user/pwd.

I shared my dockers if you where working on something related with pki... it is not related with this issue at all.

**Comment by SebDieBln** [comment]
> probably I'll cherry pick your patches... I already read your patch and it's fine, I just check if the url expansion is done in the correct place and not too early exposing user/pwd.

Yes, please! I literally got a headache when working this PR out, because there are so many levels of abstraction and the term _URI_ is used quite ambiguously, sometimes being a `QgsDataSourceURI`, sometimes being the output of `QgsDataSourceURI::uri()`.

>I shared my dockers if you where working on something related with pki.

The main advantage of the new authentication system for me is to avoid saving the password in projects and layer definition files and to be able to give personal database logins to my users.

**Comment by jef-n** [comment]
> Because this PR is a bugfix and already tagged for QGIS 2.14 I assume we are not threatened by the upcoming feature freeze.

If it was a feature the tag wouldn't matter (except the tagger should probably have gotten it in earlier and it probably should be retagged after it has missed the feature freeze).

**Comment by luipir** [comment]
Hi @SebDieBln just reviews and commented some necessary modification to the code

I tested and your patch it works also with PKI thanks to @dakcarto URI espansion.

for me can be merged after the little modifications I suggested

**Comment by SebDieBln** [comment]
Thanks for reviewing, I applied all the modifications you pointed out in SebDieBln/QGIS@0cf9d0807d1ecd4a0c727370c48723beb45bd25f.

> I tested and your patch it works also with PKI thanks to @dakcarto URI espansion.

Yes, this URI expansion really is a textbook example of transparently adding mighty functionality.

**Comment by lpirelli** [comment]
Hi @SebDieBln 

I've to ask you if I can cherry-pick your patches and include in a new pull request including also PKI auth on Postgres. 
Your patch is necessary to allow our pull request at work.

@dakcarto already cherry-piccked and integrated in our boundless branch https://github.com/boundlessgeo/QGIS/tree/postgis-pki

I did some other patch to db-manager to allow removing temporary certificates generated during connectionInfo expansion.

It was necessary this speed-up due the fact that 15/01 will be feature freeze and I wasn't able to wait for the this pull request be integrated in the master code.

let me know if it's ok for you to move all you patches in the next pull request. 

regards

**Comment by SebDieBln** [comment]
@luipir 
Thanks for asking.
It is totally ok for me if you incorporate my changes into your PR. Just link to your PR from here. And I would ask you to close this PR only after yours has been merged.

As long as DbManager 2.14 works with the new auth-system I am happy :smile:

**Comment by lpirelli** [comment]
@SebDieBln :)

here you can find the first release base of the next PR:
https://github.com/boundlessgeo/QGIS/tree/postgis-pki-pr

please start to check it to verify if there are some regressions with your test data. I did some simple test other with PKI also with basic auth and seems there are not regressions.

well probably this discussion will be moved in the next PR (tomorrow morning I suppose)

than you for sharing you work

**Comment by luipir** [comment]
@SebDieBln :)

here you can find the first release base of the next PR:
https://github.com/boundlessgeo/QGIS/tree/postgis-pki-pr

please start to check it to verify if there are some regressions with your test data. I did some simple test other with PKI also with basic auth and seems there are not regressions.

well probably this discussion will be moved in the next PR (tomorrow morning I suppose)

than you for sharing you work

**Comment by luipir** [comment]
Hi @SebDieBln 
Just created the PR that incliude your patches

https://github.com/qgis/QGIS/pull/2674

**Comment by SebDieBln** [comment]
Closing this PR since it has been incorporated into #2674, which is merged by now.
Thanks @dakcarto, @luipir

**Comment by luipir** [comment]
thanks to you @SebDieBln I would ask to test it deeply in your work environment to check if there are regressions on basic authentication.

**Pull request closed without merging**
