### PR TITLE
Allow saga algorithms to be run under SAGA 7.3, but with large warnings

### PR DESCRIPTION
**Pull request by nyalldawson**
Trying to unblock the stalemate with PROJ 6/GDAL 3 and the MacOS infrastructure, this PR adds the ability to run the SAGA algorithms under the new SAGA 7.3 LTR release. BUT..... show a huge obnoxious "NOT OFFICIALLY SUPPORTED" warning so that users know they are venturing into uncharted, not supported, dragon-filled territory.

Adding full support for SAGA 7.3 is going to be a painstaking, tedious, heart-breaking process (community, non QGIS-core-dev volunteers welcome to lead this effort!!!), but this should at least hopefully allow the mac builds to upgrade their dependencies without completely breaking SAGA support.

Ping @PeterPetrik @alexbruy

### CODE REVIEW

**Comment by lbartoletti** [comment]
cc @rhurlin for FreeBSD too

**Comment by rhurlin** [comment]
@lbartoletti: Thanks for cc'ing me

@nyalldawson: I like the approach to open against newer SAGA LTR version. But I am wondering, if we couldn't open it a bit wider, say '>= newest LTR version'. Then a (FreeBSD) user can also use other, newer than LTR SAGA versions, like e.g. the FreeBSD port system offers.

On FreeBSD, we allow to use newer SAGA versions with QGIS for quite some time now. Therefore, we patch the sources like this:

```
--- python/plugins/processing/algs/saga/SagaAlgorithmProvider.py.orig	2019-03-02 02:07:46 UTC
+++ python/plugins/processing/algs/saga/SagaAlgorithmProvider.py
@@ -82,7 +82,7 @@ class SagaAlgorithmProvider(QgsProcessingProvider):
 
     def canBeActivated(self):
         version = SagaUtils.getInstalledVersion(True)
-        if version is not None and version.startswith(REQUIRED_VERSION):
+        if version is not None and version >= REQUIRED_VERSION:
             return True
         return False
 
@@ -93,7 +93,7 @@ class SagaAlgorithmProvider(QgsProcessingProvider):
                                      self.tr('Processing'), Qgis.Critical)
             return
 
-        if not version.startswith(REQUIRED_VERSION):
+        if version < REQUIRED_VERSION:
             QgsMessageLog.logMessage(self.tr('Problem with SAGA installation: unsupported SAGA version (found: {}, required: {}).').format(version, REQUIRED_VERSION),
                                      self.tr('Processing'),
                                      Qgis.Critical)
```

**Comment by alexbruy** [comment]
Looks good to me (though IMHO it should be disabled/removed completely).

**Comment by nyalldawson** [comment]
@rhurlin 

> I like the approach to open against newer SAGA LTR version. But I am wondering, if we couldn't open it a bit wider, say '>= newest LTR version'. Then a (FreeBSD) user can also use other, newer than LTR SAGA versions, like e.g. the FreeBSD port system offers.

That's what we used to do, but it just led to a nightmare of maintenance effort (because SAGA api changes all the time, even within a single major release series). Accordingly we made the decision to only support SAGA LTR releases and nothing else...

**Comment by rhurlin** [comment]
@nyalldawson Of course, this is understandable. On FreeBSD, we can widen this as before, if wanted.

Many thanks for your efforts, really appreciated.

**Review by PeterPetrik — APPROVED** [review]
thanks for doing this

**Comment by gioman** [comment]
> Trying to unblock the stalemate with PROJ 6/GDAL 3 and the MacOS infrastructure, this PR adds the ability to run the SAGA algorithms under the new SAGA 7.3 LTR release. BUT..... show a huge obnoxious "NOT OFFICIALLY SUPPORTED" warning so that users know they are venturing into uncharted, not supported, dragon-filled territory.
> 
> Adding full support for SAGA 7.3 is going to be a painstaking, tedious, heart-breaking process (community, non QGIS-core-dev volunteers welcome to lead this effort!!!), but this should at least hopefully allow the mac builds to upgrade their dependencies without completely breaking SAGA support.

@nyalldawson thanks for this. I'm anyway a little confused by the whole SAGA situation. Was are the implications for QGIS in general (not only for macOS)? We must update the description files for the tools in order to work with SAGA ltr? @alexbruy

**Pull request merged**
