### PR TITLE
[quick] fix deprecated use of QApplication::desktopWidget()->screenGeometry()

### PR DESCRIPTION
**Pull request by 3nids**
This takes the first top level window and use it to get the screen.

The "perfect" approach would be to use a widget as argument in the method.

@PeterPetrik thoughts?

### CODE REVIEW

**Comment by PeterPetrik** [comment]
why we cannot use the "perfect" approach? 
let me ask @sklencar to comment

**Comment by sklencar** [comment]
Outputs from simple test on Macbook pro 15", where results of the new implementation has more precious results.
Old vs new implementation:
```
screen resolution: 1440x900 px
screen DPI: 111x111
screen size: 330x206 mm
screen density: 0.69375
```
```
screen resolution: 1440x900 px
screen DPI: 110.5x110.5 //-> correct value
screen size: 331x207 mm //-> correct value
screen density: 0.690625
```

**Review by PeterPetrik — APPROVED** [review]

**Comment by PeterPetrik** [comment]
@3nids what is the status of this PR? shall we merge it?

**Comment by 3nids** [comment]
yep!

**Comment by PeterPetrik** [comment]
feel free to merge when tests pass

**Comment by nyalldawson** [comment]
Closing manually because stale-bot seems to have gone on holiday

**Pull request closed without merging**
