### PR TITLE
[server] Implement LAYERFONTCOLOR and ITEMFONTCOLOR

### PR DESCRIPTION
**Pull request by elpaso**
cherry-picking commit dca0fb9026.

### CODE REVIEW

**Comment by rldhont** [comment]
@elpaso it seems that the merge has been done in the backport branch #9808 and not in release-3_6. I think you probably have to open a new PR to backport #9805 in release-3_6.

**Comment by elpaso** [comment]
@rldhont ok, let me check, I've done late yesterday evening and I could have messed it up, sorry for that.

**Comment by rldhont** [comment]
I have clean the backport branch #9808

**Comment by elpaso** [comment]
New PR: https://github.com/qgis/QGIS/pull/9820

**Pull request merged**
