### PR TITLE
Smarter Map Redraws [grant 2020]

### PR DESCRIPTION
**Pull request by PeterPetrik**
https://github.com/qgis/QGIS-Enhancement-Proposals/issues/181

- only for RasterLayers so far, should be easily extensible for other types
- there is developer define in QgsMapRendererParallelJob `SIMULATE_SLOW_RENDERER`, line 338, you can uncomment it to force very slow renderers (for testing)

general overview of the implementation: The `QgsMapLayerRenderer` has flag `mReadyToCompose`. To use the "smart map redraws" for the particular renderer, the flag must be set to `false` in the constructor and set to `true` once there is something to show to user (so the renderer actually drawn some data to resulting/destination image already). The rule now is that whenever the flag is set to `false`, the rendering job tries to fetch the cached image from the `QgsMapRenderingCache` for particular layer and transform it to the current drawn extent instead of showing QImage with all transparent pixels

Work funded by QGIS grant 2020.

### CODE REVIEW

**Comment by roya0045** [comment]
This makes me want to improve expression evaluation...

**Comment by nyalldawson** [comment]
@PeterPetrik 
This doesn't actually seem to have any effect for me -- see the screencast below. It doesn't show so well in the screencast, but even the pan operations results in a ~0.25 second white canvas flash for me

Peek 2021-01-13 12-10

**Comment by PeterPetrik** [comment]
> @PeterPetrik
> This doesn't actually seem to have any effect for me -- see the screencast below. It doesn't show so well in the screencast, but even the pan operations results in a ~0.25 second white canvas flash for me
> 
> Peek 2021-01-13 12-10

Screen Shot 2021-01-13 at 8 16 58

actually removed the `mReadyToCompose=false` from raster renderer contructor when doing "final" changes for official PR... will fix ASAP

**Comment by nyalldawson** [comment]
Ok, that's certainly MUCH nicer now! Great stuff!

A few suggestions:

1. I think we should implement this for vector layers too, by setting mReadyToCompose only after the first feature is rendered. I've tested and this helps with some semi-common situations like a inverted polygon using the shapeburst renderer, which can be rather slow to draw.
2. It's actually possible for us to have multiple rendered versions of a single layer covering different extents, because the "preview job" functionality in the canvas automatically draws neighbouring tiles after the main job finishes. If we allowed the render cache to store more than one image for a layer, then potentially we could draw ALL of these during the intermediate compositing. This would mean that zooming out would nicely show the data from the surrounding areas while the redraw occurs. What do you think?

**Comment by saberraz** [comment]
Before:
before

After:
After

**Review by wonder-sk — APPROVED** [review]

**Comment by PeterPetrik** [comment]
Best to thanks to QGIS grant scheme and all the QGIS sponsors :)

**Pull request merged**
