### PR TITLE
Allows to inspect and change the currently used expression of a virtual field

### PR DESCRIPTION
**Pull request by m-kuhn**
At the moment the comment field is used. I don't think there is a collision, as far as I know this field is read only and the content fetched from the provider.

Also added some unit tests for virtual fields

screenshot from 2015-03-24 11 42 41

### CODE REVIEW

**Comment by NathanW2** [comment]
What is the use case for using expressions in the comment field?

**Comment by m-kuhn** [comment]
It is rather "using the comment field to communicate the currently used expression of a virtual field" than "using expression in the comment field".
All in all, I just didn't want to add yet another column, that table's wide enough already.

**Comment by ccrook** [comment]
Could this be merged with #1932 which also relates the expression builder.  Currently the UI does not permit creating expression fields on layers which do not allow the creation of new fields in the provider.  #1932 is a one line fix to allow this to happen.

**Comment by m-kuhn** [comment]
@ccrook I think it's fine to treat them independently.

**Comment by m-kuhn** [comment]
http://hub.qgis.org/issues/11547
http://hub.qgis.org/issues/10994

**Comment by m-kuhn** [comment]
Manually merged in 264c0ec32a8a89b3ede6d5e6545b9537eb926445

**Pull request closed without merging**
