### PR TITLE
Add safeguard for -of option

### LINKED ISSUE #54122: Add safe guard around `-of` in gdal command for batch processing
### What is the bug or the crash?

https://github.com/qgis/QGIS/blob/2d41b378b57d26a9a412e2ed68ec3e16de9ccf65/python/plugins/processing/algs/gdal/warp.py#L229-L230

`QgsRasterFileWriter.driverForExtension()` can return an empty string if extension is not recognized (like `gtif` for GeoTiff file).

In that case, generated gdal command is broken as `-of` is followed by an unrecognized argument.

In single file process, it's not an issue as an error is raised earlier but in batch processing, the error is not raised.
Single file
image

Batch
```
Paramètres en entrée :
{"DATA_TYPE":0,"EXTRA":"","INPUT":"T:/22F123_Aussonnelle/4_TECHNIQUE/Hydrologie/Radar/livre_T77772_COMEPHORES_Toulouse/RR/2022010500_RR.gtif","MULTITHREADING":false,"NODATA":null,"OPTIONS":"","OUTPUT":"T:/22F123_Aussonnelle/4_TECHNIQUE/Hydrologie/Radar/livre_T77772_COMEPHORES_Toulouse/RR/2022010500_RRaaa.gtif","RESAMPLING":0,"SOURCE_CRS":null,"TARGET_CRS":null,"TARGET_EXTENT":null,"TARGET_EXTENT_CRS":null,"TARGET_RESOLUTION":null}

Commande GDAL :
gdalwarp -overwrite -r near -of T:/22F123_Aussonnelle/4_TECHNIQUE/Hydrologie/Radar/livre_T77772_COMEPHORES_Toulouse/RR/2022010500_RR.gtif T:/22F123_Aussonnelle/4_TECHNIQUE/Hydrologie/Radar/livre_T77772_COMEPHORES_Toulouse/RR/2022010500_RRaaa.gtif
Sortie de commande GDAL :
```
See gdal command is generated but `-of` is followed in this case by input filepath

### Steps to reproduce the issue

see above

### Versions

3.32.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

Fixes https://github.com/qgis/QGIS/issues/54122

### CODE REVIEW

**Comment by pblottiere** [comment]
Hello @nicogodet :hand:,

What do you think about this PR?

**Comment by alexbruy** [comment]
@pblottiere this should be done for all algorithms, not only for `warp`.

I can be wrong, but to me it seems that #54122 is about slightly different thing. When GDAL algorithms are executed from toolbox, selecting wrong suffix will result in a warning message **before** algorithm is executed. However in batch mode this will happen (even without this fix) only **after** batch execution is started, so you will lost all your changes and have to setup everything again from scratch.

**Comment by pblottiere** [comment]
> I can be wrong, but to me it seems that https://github.com/qgis/QGIS/issues/54122 is about slightly different thing. When GDAL algorithms are executed from toolbox, selecting wrong suffix will result in a warning message before algorithm is executed. However in batch mode this will happen (even without this fix) only after batch execution is started, so you will lost all your changes and have to setup everything again from scratch.

@alexbruy what do you think about https://github.com/qgis/QGIS/pull/54800/commits/5b163d0428d86ea6d750db86bff3c633dc35b633?

Let me know if I missed your point ^^.

**Comment by alexbruy** [comment]
@pblottiere sorry for the delay.

If I'm not wrong, it is enough to change `BatchPanel`, you can safely drop changes to algorithm.

**Comment by nicogodet** [comment]
> @pblottiere sorry for the delay.
> 
> If I'm not wrong, it is enough to change `BatchPanel`, you can safely drop changes to algorithm.

I just tried to run in python console `processing.run()`: no error but output file is never created

**Comment by pblottiere** [comment]
>> If I'm not wrong, it is enough to change BatchPanel, you can safely drop changes to algorithm.

> I just tried to run in python console processing.run(): no error but output file is never created

> safeguard should be added to each alg

Yes indeed :+1:.

**Review by nicogodet — APPROVED** [review]

**Comment by pblottiere** [comment]
I think this PR is ready to be merged.

Thanks for your inputs @nicogodet and @alexbruy :+1:

**Review by lbartoletti — APPROVED** [review]

**Pull request merged**
