### PR TITLE
Map layout context exp

### PR DESCRIPTION
**Pull request by roya0045**
## Description
This is another subset of my big PR. This part aims to expose the atlas expression context along with the layout map expression context when the latter is linked to the atlas.

This will be useful to filter elements by the atlas feature/name and the map extent in the legend (nyall's PR and eventually mine.)

### CODE REVIEW

**Comment by nyalldawson** [comment]
Are you sure this is needed? It should be getting added automatically by QgsPrintLayout::createExpressionContext, which is called in the map item parent classes' implementations of createExpressionContext

**Comment by roya0045** [comment]
> Are you sure this is needed? It should be getting added automatically by QgsPrintLayout::createExpressionContext, which is called in the map item parent classes' implementations of createExpressionContext

This is the best solution that I could find. Here is how the context are handled:
layoutmap (+ atlas) -> vectorLayer->symbol. ( I have altered the vectorlayer to accept another expression context to stack things  on, I think that this approach might benefit the rest of the code to combine expressioncontext but I'm biased about this.)

I could also use the printlayout in the layoutitemmap but that would also be redundant. I know that qgsprintlayout is directly related to the atlas but from what I can see the print layout does not get the map context and the vectorlayer would already provide a lot of duplicate elements that are also in the qgslayout expression context.

**Comment by roya0045** [comment]
To be more clear, if I wanted to filter the symbols by the current value in the atlas and/or by the extent of the map I would need these two scopes for maximal utility. Also they are more easily passed down to vectorlayer in the expressionbuilder.

Once again I'm biased. A trigger may be added if needed.

**Comment by nyalldawson** [comment]
You're misunderstanding me - the scope is already there. There's no need to readd it.

**Comment by roya0045** [comment]
> You're misunderstanding me - the scope is already there. There's no need to readd it.

From what I see it goes layoutitemmap->layoutitem->layoutobject->layout.

I don't see where the atlas is integrated in all this. Maybe I missed something.

What do you suggest, do you want me to close this PR and remove those change? import from the scope of QgsLayoutPrint instead of the atlas?

**Comment by nyalldawson** [comment]
QgsPrintLayout::createExpressionContext overrides QgsLayout createExpressionContext, and adds the atlas scope (if available)

**Comment by roya0045** [comment]
@nyalldawson in order to be able to obtain both the atlas and the layout map in the most efficient way possible, what scopes should I call?

 isn't more efficient to make the pointer to the atlas, then use the expression utility function or use the qgsprintlayout which has the same calls as qgslayoutitemmap?

I'm tired and juggling all the files and the branches is not helping.  An explicit suggestion would be welcome.

**Comment by nyalldawson** [comment]
@roya0045 my honest suggestion is you can close this PR -- what you're trying to do here is already done :wink: 

But my secondary suggestion - are you using an ide when you code locally? I'd suggest installing qt creator, as it makes tracking things like this easy. Here you could check the createExpressionContext() method in QgsLayoutItemMap, right click the call the to QgsLayoutItem::createExpressionContext() and select "follow", and then continue all the way back to QgsLayoutObject::createExpressionContext(). Following the layout->createExpressionContext() call there will give you a menu showing that there's two paths this call can take, depending on whether the layout is a QgsPrintLayout subclass (in which case createExpressionContext() is overridden). Following the chain to QgsPrintLayout::createExpressionContext() will show that the atlas scope is added there.

**Pull request closed without merging**
