### PR TITLE
 [processing] Use MultiPolygon as output wkb type for multi ring buffer (constant)

### PR DESCRIPTION
**Pull request by nirvn**
## Description
Fix multi/m/z wkb parts getting lost when running the multi ring buffer alg.

@nyalldawson , all good?

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Hmm how are you certain that a single part buffer corresponds to a single part output? That doesn't hold (e.g. with negative distances). It's also not possible to maintain z/m here -- geos buffer doesn't output these (and I'm not sure there's any meaning for them anyway -- the best you could do is take the nearest input vertices z/m value, but at best that's a very broad assumption, and at worst plain misleading!)

**Comment by nirvn** [comment]
@nyalldawson , so are you thinking we should simply have a fixed QgsWkbType::MultiPolygon  as output wkb? I'd be fine with that.

**Comment by nyalldawson** [comment]
Yeah I think that's safest.

**Comment by nirvn** [comment]
@nyalldawson , PR updated.

**Comment by nyalldawson** [comment]
Won't you also need to force multi the out geometry to match?

**Pull request merged**
