### PR TITLE
Fix srsDimension parsing in GML, fixes #15721

### PR DESCRIPTION
**Pull request by tcoupin**
## Description
Fix https://issues.qgis.org/issues/15721
Keep track about srsDimension 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by tcoupin** [comment]
I don't understand the fail...

**Comment by rldhont** [comment]
Does this fix has to be backported ?

**Review by rldhont — APPROVED** [review]

**Comment by tcoupin** [comment]
> Does this fix has to be backported ?

This problem is present since 2.16 so all of users who want IGNF data need to stay in previous LTR  2.14. So if this fix can be backported, it would be great!

**Comment by tcoupin** [comment]
Do you plan a backport and if yes when ?

**Comment by rldhont** [comment]
Done 21e3e8357abdb3ffa3db487feb7f44b4d9f8a00d

**Comment by tcoupin** [comment]
so fast :)

**Pull request merged**
