### PR TITLE
add official CSW services for Portugal

### PR DESCRIPTION
**Pull request by gioman**

### CODE REVIEW

**Comment by gioman** [comment]
assigned @tomkralidis

**Comment by tomkralidis** [comment]
Thanks @gioman!

**Comment by gioman** [comment]
@tomkralidis you welcome. I have been warned that the second URL I posted (Catálogo INSPIRE-PT (SNIG)) is a service that has been deactivated and merged with the fist one. So the second URL need to be removed. Thanks!

**Comment by tomkralidis** [comment]
@gioman thanks, done.

**Pull request merged**
