### PR TITLE
[db_manager] fix #12429 run only the selected query in the sql window

### PR DESCRIPTION
**Pull request by Gustry**
Fix running only the selected query when loading a query into the map canvas or saving it in a preset.
This PR fix http://hub.qgis.org/issues/12429

### CODE REVIEW

**Comment by strk** [comment]
@brushtyler since you're around maybe you want to look at this ? (and #2000 which is the backport to 2.8 branch)

**Comment by brushtyler** [comment]
The code looks good, but I cannot merge it now. I need to pick the right commit only, so I'll merge it this evening.

**Comment by brushtyler** [comment]
Merged in b1dd253fc5. Thanks Etienne.

**Comment by brushtyler** [comment]
Third commit manually merged in 08dd620b5

**Pull request closed without merging**
