### PR TITLE
QgsSpatiaLiteProvider changes for Spatialite 4.5.0

### PR DESCRIPTION
**Pull request by mj10777**
## Description
QgsSpatiaLiteProvider reorginised for Spatialite 4.5.0, RasterLite2 and Topology

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

This pull request will correct many known problems and prepare the QgsSpatiaLiteProvider to deal with the many changes in the upcoming Spatialite 4.5.0 with RasterLite2, Topology and SE/SLD Style support.

The present approach, to simply list TABLEs and VIEWs that contain Geometries is no longer practicable, since many of the Administration TABLEs also contain geometries which normally should never be displaced.

Also the interdependence between Layers (Vector and Raster) with Styles and other information contained in the Database, calls for a different approach to the problem, so that all of the capabilities being offered by Spatialite 4.5.0 can be fully utilized.

---

For this three new classes have introduced
* **SpatialiteDbInfo** 
   * a class that will contain all needed information about the Database
* **SpatialiteDbLayer**
   * a class that will contain all needed information about a specific Layer within the Database
* **QgsSpatiaLiteUtils**
   * with helper static function (see below)

**SpatialiteDbInfo**  will contain this list of all available **SpatialiteDbLayer**s
* and will make them available upon demand

---

**SpatialiteDbInfo** will be contained in the presently existing **QgsSqliteHandle** class
* with it's sharing capability

In a scenario, where 10-50 layers are being loaded from the same Database
* that Database is read only once and the collected information shared between the 10-50 layers

---
All classes within the QgsSpatiaLiteProvider access all needed information from **SpatialiteDbInfo** or **SpatialiteDbLayer** instead of storing them as member variable.

Instead of **mSqliteHandle** , **dbSqliteHandle()** is used, so that knowledge of the internal structure of **SpatialiteDbInfo** and **SpatialiteDbLayer** is not needed.

Otherwise the functionality of the QgsSpatiaLiteProvider, QgsSpatiaLiteFeatureIterator and QgsSpatiaLiteConnection have not changed, only the method on how they attain the needed information has.

These classes had contained many functions for the retrieval of information from the Database, some copies of others, which is now dealt with **once** in **SpatialiteDbInfo** and/or **SpatialiteDbLayer**.

All of these functions have been removed.
All static functions (10), that were used in QgsSpatiaLiteProvider, have been moved to a **QgsSpatiaLiteUtils** class. These were mainly functions for the calculation of object sizes or converting from one (internal spatialite specific) format to another.

Goal was to separate the Database and Provider functionality.
This should simplify future maintenance of both. 

---
Since **SpatialiteDbInfo** is separate from the QgsSpatiaLiteProvider class, it can be used for other tasks, such as
* is the file a **Sqlite3** container
* is the container supported by QGis through
   * **QgsSpatiaLiteProvider**
   * **QgsOgrProvider**
   * **QgsGdalProvider**

This would make it possible to be used within the
* Drag and Drop and Browser logic

It can be called in a way to only 'sniff' the Database, returning after determining which container type it is
* Spatialite (from version 2.4 to present)
* FdoOgr
* GeoPackage (Raster/Vector)
* MbTiles
* RasterLite1
* RasterLite2
* Topology

Since the **QgsOgrProvider** cannot (yet) recognize Spatialite Tables with more than 1 Geometry and since **Ogr** has no support for writable SpatialView's, it would be important that within the Drag and Drop/Browser logic the **QgsSpatiaLiteProvider** would be used as the default.

The 'Data Source Manager - Spatialite' has been adapted to use **SpatialiteDbInfo** and **SpatialiteDbLayer**, so that the structure of the different containers can be shown (more to that later).

Also **SpatialiteDbInfo** can submit the selected Layers as **QgsVectorLayer** or **QgsRasterLayer** with the proper Provider/Connection Uri's.

This would have the advantage, that for a **GeoPackage** source, both the Vector (**QgsOgrProvider**) and Raster (**QgsGdalProvider**) Layers could be added in 1 step.

---
For the User, the only noticeable change will be the 'Data Source Manager - Spatialite'.
The **QgsSpatiaLiteTableModel** (based on **QStandardItemModel**) will now show a TreeView

Here a sample showing a **GeoPackage** Database:

datasourcemanager gpkg select

Here you can see that there are 3 tree branches
* Vector
* Raster
* Non-Spatial [will always be the **last** branch]

so that the User can distinguish between the different types, collapsing what they don't want to see.

Inside the Non-Spatial group, there are also sub-groups, so that a search for Data-Tables, Views can be easily found (without the data beings displayed), since index-tables are in an extra group.

Since **SpatialiteDbInfo** must collect the Non-Spatial anyway, the CheckBox to turn this on/off has been hidden.

In the above Image ,the last selected Item is a Raster.
When selected, first any Raster, then Polygons will be submitted, since it seems that Rasters are rendered before any Vectors. Then Linestrings after which any Point will be submitted, so that the Polygons will be over the Rasters, the Linestrings over the Polygons and the Points over the Linestrings.

Here a view of the result from a Spatialite-Database that contains SE/SLD-Styles:

datasourcemanager styles select

Since **SpatialiteDbInfo** has collected all the needed information about existing Styles and **SpatialiteDbLayer** has retrieved the information which Style it should use,  **SpatialiteDbInfo** will call the **readSld** function of QgsVectorLayer before it is sent to QGis.

---
This pull request would be stage 1 of the planned changes. Stage 2 would be the implementation of the Drag and Drop and Browser logic, which should not take long to do.

Stage 3 and 4 could be done after an initial QGis 3.0 release.

Stage 3: change **QgsSpatiaLiteTableModel** from **QStandardItemModel** to a **QAbstractItemModel** which would be fine tuned to interact with **SpatialiteDbInfo** and **SpatialiteDbLayer**
* Alessandro Furieri (Sandro of Spatialite), has asked if 

> adding some ad hoc function allowing to drop or rename columns in the most painless way.

would be possible

Stage 4: creating a QgsRasterLite2 provider

Since both would be time consuming, these would then only done **after** an initial QGis 3.0 release.

---
Known problem: After a geometry has been added and saved to the Database: the geometry cannot be selected with the editing tools, the field attributes can bee seen and changed.

With a rebased version of Master (of about 2 weeks ago): after saving the newly created Geometry, that Geometry is not shown at all. With 2.18 everything works correctly.

The geometry shown in the 2nd image were all created after all changes in QgsSpatiaLiteProvider, QgsSpatiaLiteFeatureIterator and co. were made, so I believe that these changes can be considered stable.

---
Other changes that come to mind:
* the default values are now correctly shown when creating a new Geometry
* SpatialViews will use the default values of the base TABLE when the column names have not changed (which in a view is possible)
* full Date/DateTime support

---
cmake:
* **FindRasterLite2.cmake** has been added as well a logic in CMakeLists.txt to add it as an **optional** dependency.
   * this would be a pre-condition for a QgsRasterLite2 provider support

The only use of the RasterLite2-Api is needed for for a connection inside QgsSqliteHandle
* and has already been added.
Everything else for RasterLite2 will be Sql-based.

Also a **SPATIALITE_VERSION_GE_4_5_0** has been added in CMakeLists.txt and used where needed.

No other (intended) changes have been made.

---
No doubt I have forgotten something, but for now ...

### CODE REVIEW

**Comment by mj10777** [comment]
It is not clear why **sqlite3_db_readonly** fails, since travis uses 3.20.0 and the function exists  since Sqlite3 Version 3.7.11.

After updating cmake, my build is now running - but it will take some time until it gets to this point.

**Comment by mj10777** [comment]
@nyalldawson when can thereviewing for this start?

**Comment by nyalldawson** [comment]
> when can the reviewing for this start?

Reviewing is all totally voluntary - so as soon as someone has time they can devote to it

**Comment by mj10777** [comment]
Has a decision been made when QGIS 3 will be released?

**Comment by jef-n** [comment]
@mj10777  http://qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule

**Comment by mj10777** [comment]
Ah, November - some how i had the impression that it was planned for August/September.

**Comment by m-kuhn** [comment]
Hi @mj10777 the topics of this pull request look very interesting and is certainly an area where we need someone involved (unless we switch spatialite over to gdal).
I think there is just one single reason that it doesn't get more traction, and that's, that it's simply not possible to review 20k lines of added code and 6k of removed lines in a reasonable amount of time.

I would strongly suggest to split this up into smaller, digestible chunks.
Just as an example, start by doing only the update for spatialite. Or start by refactoring out the utilities class. But don't combine the two. Do one or two more iterations and then go for rasterlite in the end.

I'd really **love** to see this land!

**Comment by nyalldawson** [comment]
> I'd really love to see this land!

+1. FYI, having time to properly review and get these changes integrated was one of the reasons why freeze was pushed back another month. That's how much we value your work!

**Comment by mj10777** [comment]
This will be difficult, buts lets try to work out a concept.

1) Everything in **qgsspatialiteutils**.cpp and .h is (almost) independent from everything else
   * exception: it is designed to work from inside **QgsSqliteHandle** 

2) **QgsSqliteHandle** needs  **qgsspatialiteutils**.cpp and .h
   * internal there have been changes to service **qgsspatialiteutils**
   * static QgsSqliteHandle *openDb (which is the main function from outside classes)
      * has new, optional, parameters - so should not fail with the older classes

3) **QgsSpatiaLiteConnection** (inside the same file as **QgsSqliteHandle**)
   * works with **QgsSqliteHandle** and also  to service **qgsspatialiteutils**
   * but also should not fail with the older classes

----

4) The functionality of **QgsSpatiaLiteFeatureIterator** has not changed
   * only the way it retrieves its information from **QgsSpatiaLiteFeatureSource** has slightly changed

5) **QgsSpatiaLiteFeatureSource**
   * have been adapted to retrieved needed information from the adapted **QgsSpatiaLiteProvider**

6) **QgsSpatiaLiteProvider** is where the major changes have been made
   * the member vars for the portions that do not change
      * have been replaced with 'get' functions from **SpatialiteDbLayer**
   * the member vars deal with the sub-query/portion of a layer remain as is
   * the functions that retrieve the **basic** information from the database have been removed, because this information is being retrieved from **SpatialiteDbLayer**
   * new function to create/retrieve the connection and set the **SpatialiteDbLayer**
     * QgsSpatiaLiteProvider::setSqliteHandle
     * QgsSpatiaLiteProvider::setDbLayer
   * the functions that retrieve only the needed information, call the needed function from **SpatialiteDbLayer**
      * QgsSpatiaLiteProvider::addFeatures
      * QgsSpatiaLiteProvider::createAttributeIndex
      * QgsSpatiaLiteProvider::deleteFeatures
      * QgsSpatiaLiteProvider::truncate
      * QgsSpatiaLiteProvider::addAttributes
      * QgsSpatiaLiteProvider::changeAttributeValues
      * QgsSpatiaLiteProvider::changeGeometryValues
      * QgsSpatiaLiteProvider::capabilities
      * QgsSpatiaLiteProvider::defaultValue
      * QgsSpatiaLiteProvider::field
      * QgsSpatiaLiteProvider::fields
      * QgsSpatiaLiteProvider::featureCount
      * QgsSpatiaLiteProvider::wkbType
      * QgsSpatiaLiteProvider::extent
      * QgsSpatiaLiteProvider::updateExtents

   * unchanged functions since the results depend on the active (if any) mQuery and mSubsetString members
      * QgsSpatiaLiteProvider::minimumValue
      * QgsSpatiaLiteProvider::maximumValue
      * QgsSpatiaLiteProvider::uniqueValues
      * QgsSpatiaLiteProvider::uniqueStringsMatching
      * QgsSpatiaLiteProvider::checkQuery
      * QgsSpatiaLiteProvider::layerCount
      * QgsSpatiaLiteProvider::setSubsetString
      * QgsSpatiaLiteProvider::subsetString()

   * unchanged functions since they are very provider specific
      * QgsSpatiaLiteProvider::searchLayers
      * QgsSpatiaLiteProvider::discoverRelations
      * QgsSpatiaLiteProvider::crs()
      * QgsSpatiaLiteProvider::getFeatures
      * QgsSpatiaLiteProvider::storageType
      * QgsSpatiaLiteProvider::featureSource
      * QgsSpatiaLiteProvider::createEmptyLayer
      * QgsSpatiaLiteProvider::convertField
         * slightly adapted to support DATE/DATETIME and TIME fields
      * QgsSpatiaLiteProvider::setDbLayer
         * slightly adapted to support DATE/DATETIME and TIME fields

   * **QGISEXTERN** remain, with 1 exception, unchanged
      * QgsVectorLayerExporter::ExportError
      * deleteLayer
      * saveStyle
      * loadStyle
      * listStyles
      * getStyleById
      * cleanupProvider
      * createDb has been adapted to call
          * QgsSpatiaLiteUtils::createSpatialDatabase
              * which does this correctly, based on different version needs
          * **initializeSpatialMetadata** to be removed

   * all the spatialite specific static functions to determine blob sizes (like computeMultiWKB3Dsize) have been moved (1:1) to  **QgsSpatiaLiteUtils**

---

This should, at least, give a overview which may assist while looking through qgsspatialiteprovider.cpp.

**Comment by mj10777** [comment]
I am now attempting to build with only
* the new qgsspatialiteutils.* and the adapted qgsspatialiteconnection.*

It will take many hours before it gets to compiling the spatialite provider part.

**Comment by mj10777** [comment]
It would be useful if the cmake files
* **FindRasterLite2.cmake** and adaped **FindSpatiaLite.cmake**

and the main QGIS/CMakeLists.txt

could be reviewed, since they are the only 'external' changes needed.

**Comment by m-kuhn** [comment]
The cmake changes concerning spatialite look ok to me.

The rasterlite2 changes will need to be dealt with in a separate package. There is also a basic question outstanding if we should ship a provider for this if gdal already does that.

**Comment by mj10777** [comment]
RasterLite2 is a Spatialite project and a QRasterLite2Provider will provide the full functionality that the system will offer.

For the simple part of displaying the Rasters, QGdalProvider would work - but never for the full functionality. there is more to this than just displaying Rasters.

The changes in CMakeLists.txt, BTW, are for a **optional** support of RasterLite2 until the first version has been packaged.

**Comment by m-kuhn** [comment]
I guess the spatialite updates can be integrated without any of the rasterlite2 patches? If there is no hard requirement to bundle the two (and I assume there is not), please split them apart.

It's always good to split things

* it makes reviewing easier
* this in turn introduces less errors while reviewing
* it keeps things modular
* it avoids the risk that the complete work is lots just because one part is not acceptable

at the same time, there are 0 (zero) drawbacks

> For the simple part of displaying the Rasters, QGdalProvider will work - but never for the full functionality. there is more to this than just displaying Rasters.

That's very well possible, please give us a summary of what's in there "more than this". So an informed decision can be made. I don't think anyone has made up the opinion about this yet.
The other side of the story is, that it's more code to maintain and that (parts of) this code is already available somewhere else (in gdal).

There are two possibilities:

* bring up the question on the mailing list with arguments (short and to the point and without too many bullet points) to figure out beforehand if it's worth investing time into this
* make a separate pull request for a rasterlite2 provider with code already written. Be aware that there's a certain risk that it's not accepted though

**Comment by mj10777** [comment]
I have just completed the compiling of a version that would contain the above steps 1,2 and 3.

This is basically a greater part of the new code that could be reviewed.
It will take a while for the rest of the project to complete, only after which I can see if it runs.

The provider portions will not use the new code (steps 4, 5 and 6) plus QgsSpatiaLiteSourceSelect and QgsSpatiaLiteTableModel.   

This could then be step 1, which I could prepair tomorrow..

Step 2 would then be the changes in (steps 4, 5 and 6) plus QgsSpatiaLiteSourceSelect and QgsSpatiaLiteTableModel.

It will all **look the same as it does now**: a lot of code removed from QgsSpatiaLiteProvider and new code added.

**Comment by mj10777** [comment]
Theme RasterLite2:

The coding for RasterLitee is very minimal.

When a connection is made to spatialite 1 call is made to init spatialite the RL2 sql-functions.
When the connection is closed 1 call to reset it.

Those are the only 2 api-called needed and are in QgsSqliteHandle.

Otherwise there is 1 RL2-specific SQL-Query to retrieve and image for an area.

Everything else does not need the RasterLite2-API.

Style support is a part of the Spatialite SQL functionality with both share.

**Comment by mj10777** [comment]
A new pull request with the first part has been made, but I have my doubts as to whether these split up portions will simplify the reviewing. 

https://github.com/qgis/QGIS/pull/5146

**Pull request closed without merging**
