### PR TITLE
move PyQt compat folder to python/qgis

### PR DESCRIPTION
**Pull request by 3nids**
Following same idea than moving testing to qgis folder, this moves the PyQt compatibility package to qgis.PyQt.

@jef-n @m-kuhn ok to you?
would you prefer renaming PyQt to something else? or to lower case?

### CODE REVIEW

**Comment by m-kuhn** [comment]
In general I'm in favor of moving this to the qgis package.

I wonder if we can still fix that in 2.14 (which is not yet really LTR ;) ), it's an API change but having an API change from 2.12 > 2.14 and then again from 2.14 > 2.16 seems worse to me than fixing this up now in the hope that there is not much code using this imports out there yet.

In general, I wonder how this even worked now. Was there a PYTHONPATH mangling in place? Because apparently in standalone scripts `from PyQt import Something` was not working...

**Comment by 3nids** [comment]
+1 to backport to 2.14 before it's too late!!!!

**Comment by m-kuhn** [comment]
For 2.14 we can make an alias for the toplevel `PyQt` module.

**Comment by jef-n** [comment]
huh?  2.14 is feature frozen.  We don't support PyQt5 there, so there's not need for PyQt wrappers.   I thought the whole point of 2.16 was to have something between 2.14 that doesn't support PyQt5 and 3.0 that only supports PyQt5.

**Comment by m-kuhn** [comment]
The wrappers are there but not installed to dist-packages:

https://github.com/qgis/QGIS/tree/release-2_14/python/PyQt

Since it's not used by any of the code shipped with 2.14 there should be no troubles moving it wherever (even without alias).

Backporting the installation path fix would be nice IMO since it makes it easier to write compatible code for 2.14 (LTR).

**Comment by 3nids** [comment]
Also, if we see plugins using compatibility module, they'll be compatible with 2.14.

**Comment by m-kuhn** [comment]
https://github.com/3nids/QGIS/blob/move_compat_folder/python/gui/__init__.py#L26

**Comment by 3nids** [comment]
Not sure this is related, but when trying to compile UI files containing custom widgets, I get this error 

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/PyQt4/uic/port_v2/invoke.py", line 34, in invoke
    exit_status = driver.invoke()
  File "/usr/lib64/python2.7/site-packages/PyQt4/uic/driver.py", line 59, in invoke
    self._generate()
  File "/usr/lib64/python2.7/site-packages/PyQt4/uic/driver.py", line 98, in _generate
    self._opts.resource_suffix)
  File "/usr/lib64/python2.7/site-packages/PyQt4/uic/__init__.py", line 173, in compileUi
    winfo = compiler.UICompiler().compileUi(uifile, pyfile, from_imports, resource_suffix)
  File "/usr/lib64/python2.7/site-packages/PyQt4/uic/Compiler/compiler.py", line 55, in __init__
    CompilerCreatorPolicy())
  File "/usr/lib64/python2.7/site-packages/PyQt4/uic/uiparser.py", line 170, in __init__
    self.factory = QObjectCreator(creatorPolicy)
  File "/usr/lib64/python2.7/site-packages/PyQt4/uic/objcreator.py", line 94, in __init__
    modinfo = plugin_locals["moduleInformation"]()
  File "<string>", line 52, in moduleInformation
  File "/usr/share/qgis/python/qgis/__init__.py", line 26, in <module>
    from PyQt import QtCore
  File "/usr/share/qgis/python/PyQt/QtCore.py", line 28, in <module>
    sip.setapi(api, 2)
ValueError: API 'QDate' has already been set to version 1
```

**Comment by 3nids** [comment]
@jef-n only the move of the PyQt folder should be backported to 2.14 not actually using it in QGIS python files.

**Comment by m-kuhn** [comment]
Manually merged

**Pull request closed without merging**
