### PR TITLE
[server] Fix unused variable

### PR DESCRIPTION
**Pull request by m-kuhn**
Silences a build warning

### CODE REVIEW

**Comment by m-kuhn** [comment]
@dmarteau @elpaso (and potentially other server people), currently there is a build warning

```
In file included from ../src/server/qgsfilterrestorer.cpp:18:
../src/server/qgsfilterrestorer.h:75:29: warning: private field 'mAccessControl' is not used [-Wunused-private-field]
    const QgsAccessControl *mAccessControl = nullptr;
```
https://travis-ci.org/qgis/QGIS/jobs/324486415#L696-L698

which led me to think it's some leftover but now I realize that there's always this parameter specified in the constructor (see new warnings [in the last travis job](https://travis-ci.org/qgis/QGIS/builds/324620561?utm_source=github_status&utm_medium=notification)). Did I miss something obvious or can this be killed altogether?

**Comment by m-kuhn** [comment]
@elpaso @dmarteau does that look sane to you?
Apparently the `mAccessControl` variable in `QgsFilterRestorer` is never used and always passed in as a paramter. Not sure if you prefer to remove the `mAccessControl` member (as proposed in this PR) or remove the parameters and use the member instead.

**Comment by dmarteau** [comment]
@m-kuhn Yes, it seems that the mAccessControl member is not used anywhere. 

QgsFilterRestorer is just a holder for filter map that make sure the filters are is restored at end of scope and  all the job is done by the static members (and may be those static methods should be refactored at some point to be member of  QgsAccessControl).

Apart from this, I do not think you need to put #ifdef HAVE_SERVER_PYTHON_PLUGINS in  src/server/services/wms/qgswmsrenderer.h: QgsAccessControl has a  forward declaration in qgsserverinterface.h when HAVE_SERVER_PYTHON_PLUGINS is not defined and makes declaring a a ptr type QgsAccessControl* valid  even if there is no true implementation.  As far as I remember this was done to remove many of the  #ifdef directive that were spreading everywhere in the code.

**Comment by elpaso** [comment]
I think @sbrunner knows more about the question if the accesscontrol var is still needed and it misses the implementation or if it can be removed completely.

**Comment by m-kuhn** [comment]
>  and makes declaring a a ptr type QgsAccessControl* valid even if there is no true implementation

yes, it's completely valid and safe but it throws the only build warning we have. if you prefer, it can also be switched to a Q_UNUSED in the constructor. I guess this would also help.

**Comment by dmarteau** [comment]
yes, a Q_UNUSED should do the trick in the constructor. ( IMHO Dealing with #ifdef directive each time you call the contstructor is very tiedous at the end, so if we can keep them at the minimal level....)

**Comment by m-kuhn** [comment]
> IMHO Dealing with #ifdef directive each time you call the contstructor is very tiedous at the end, so if we can keep them at the minimal level....)

the constructor signature and hence the calls to it should stay unchanged with either solution

**Comment by m-kuhn** [comment]
Merging this as is, but if there's some trouble that new `#ifdef`'s have to be introduced, feel free to change it to a `Q_UNUSED` approach, no big deal for me. Thanks for all the feedbacks.

**Pull request merged**
