### PR TITLE
Node tool without click-click mode

### PR DESCRIPTION
**Pull request by mhugent**
Brings back used node-tool behaviour (but with vertex editor). Travis test

### CODE REVIEW

**Comment by nirvn** [comment]
@mhugent ah, what a relief that is. Glad the vertex editor is still there. I can confirm that selecting multiple nodes to either delete or move those in group works fine, snapping to.

I'm not sure if it's linked to this, but when I input a polygon, after the second node, I get a repeated "validation done" message box _as I input the nodes of the polygon_ (one message for each node). If that could happen only once, after the polygon is completed, that'd be great :smile:

**Comment by mhugent** [comment]
@nirvn: the validation is intentionally done after each node addition. As soon as your polygon is not valid, it will show you (before the whole polygon is finished).

**Comment by nirvn** [comment]
@mhugent ok, that's fine, then can we not have the message box appear each time a node is inserted? Maybe just show it if a problem occurs?

**Comment by mhugent** [comment]
In the node tool, the message comes in the status bar. Or do you mean the 'addFeature' tool? Yes, I agree that showing it only in case of error will be good.

**Comment by nirvn** [comment]
Over here, the message comes in the form of a canvas-overlayed message box with a blue background.

Steps to reproduce:
1. add a polygon memory layer 
2. click on the add polygon toolbar button
3. begin entering a polygon, add a bunch of nodes
4. on the third node, you'll see the blue background message bar appear, and it'll appear every time you enter a node from that point onwards until you finish creating your polygon

**Pull request merged**
