### PR TITLE
Do not deadlock when calling when calling GetLayerVisibility

### LINKED ISSUE #53956: QGis crashes when digitizing with snapping
### What is the bug or the crash?

When we open a project with activated snapping, it crashes when we want to start digitizing.(since Version 3.30; reproduced the crash with 3.32.0).
We noticed, that this is not a problem, when you start the project and the first move is drawing a line with the default settings (no zooming, not activating any other layer etc.). When the initial line is drawn you can work as used to. Otherwise it crashes, sometimes even without one starting to draw a new line.

### Steps to reproduce the issue

1. Get in a Project with alot of different layers and enabled snapping (all layers or with advanced settings.
2. Zoom in and drawing a line
3. Crash

### Versions

Python Stack Trace
Windows fatal exception: access violation

Windows fatal exception: access violation

Thread 0x00003448 (most recent call first):

Stack Trace

QgsExpression::referencedColumns :
QgsProperty::prepare :
QgsPropertyCollection::prepare :
QgsSymbolLayer::prepareExpressions :
QgsSymbol::startRender :
QgsRuleBasedRenderer::Rule::startRender :
QgsRuleBasedRenderer::Rule::startRender :
QgsRuleBasedRenderer::startRender :
QgsPointLocator::rebuildIndex :
QgsPointLocator::waitForIndexingFinished :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.30.1-'s-Hertogenbosch
QGIS code revision: 9035a01e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.3
Running against GDAL: 3.6.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

--------------------------------------------------------------------------------------------------------------------
Python Stack Trace
Windows fatal exception: access violation

Thread 0x00000494 (most recent call first):

Windows fatal exception: access violation

Thread 0x00000494 (most recent call first):

Stack Trace

QHashData::nextNode :
QgsPropertyCollection::prepare :
QgsSymbolLayer::prepareExpressions :
QgsSymbol::startRender :
QgsRuleBasedRenderer::Rule::startRender :
QgsRuleBasedRenderer::Rule::startRender :
QgsRuleBasedRenderer::startRender :
QgsPointLocator::rebuildIndex :
QgsPointLocator::waitForIndexingFinished :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.32.0-Lima
QGIS code revision: 311a8cb8a6
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

We are working with the advanced settings within snapping. 
We could also reproduce this crash when snapping on all layers. Never reproduced when only snapping on activated layer.
Tried to remove all Z and M values – still is crashing.

### PR DESCRIPTION
**Pull request by elpaso**
... from multiple threads.

Fix #53956

### CODE REVIEW

**Comment by elpaso** [comment]
@nyalldawson while I believe this patch is sound and valid, I am little concerned about the biggest picture.

This is deprecated https://github.com/qgis/QGIS/blob/master/src/core/expression/qgsexpressionutils.cpp#L55 but no alternative is suggested, it searches in the context's layerStore first but I couldn't find any call to QgsExpressionContextScope::addLayerStore and in practice there isn't any store in the tests I've run. Then it searches in the project instance with this comment https://github.com/qgis/QGIS/blob/master/src/core/expression/qgsexpressionutils.cpp#L119 but that's the code patch which is taken 100% of the times in the context of https://github.com/qgis/QGIS/issues/53956.

Also, QgsExpressionUtils::getMapLayer is deprecated but the "thread safe" functions like runMapLayerFunctionThreadSafe appear to use the very same Qt::BlockingQueuedConnection which is the root cause of the deadlocks.

I'm a little confused about what should be done to properly assure we can retrieve a layer instance from an expression in a thread safe way.

Maybe we should consider what we intend to do with the retrieved layer, in the context of GetLayerVisibility we just use its pointer address to retrieve cached visibility info from a local cache so there is no danger of any race condition.

**Comment by nyalldawson** [comment]
@elpaso 
>Also, QgsExpressionUtils::getMapLayer is deprecated but the "thread safe" functions like runMapLayerFunctionThreadSafe appear to use the very same Qt::BlockingQueuedConnection which is the root cause of the deadlocks.

What's the wider context here? Is the expression being evaluated on the main thread? Or if not, what's the main thread itself blocked on?

**Comment by elpaso** [comment]
> @elpaso
> 
> > Also, QgsExpressionUtils::getMapLayer is deprecated but the "thread safe" functions like runMapLayerFunctionThreadSafe appear to use the very same Qt::BlockingQueuedConnection which is the root cause of the deadlocks.
> 
> What's the wider context here? Is the expression being evaluated on the main thread? Or if not, what's the main thread itself blocked on?

Expressions for snapping point locator renderer test are all evaluated in separated threads that all get blocked by BlockingQueuedConnection, the main thread is blocked on  QgsTask::waitForFinished, see:

immagine

When I pause the program after about 2 seconds from the initial click I can see about 70 threads running.

**Comment by nyalldawson** [comment]
> Expressions for snapping point locator renderer test are all evaluated in separated threads that all get blocked by BlockingQueuedConnection, the main thread is blocked on QgsTask::waitForFinished, see:

Hmm, not simple to fix then. I'd probably try just chucking an ugly event loop in instead of that waitForFinished and see what happens.

**Comment by nyalldawson** [comment]
Or.... Thinking about this, should we just NOT snap if the results aren't ready so we aren't blocking at all?

**Comment by elpaso** [comment]
> Or.... Thinking about this, should we just NOT snap if the results aren't ready so we aren't blocking at all?

No, I think the current sequence of calls is correct, when you move the mouse on canvas after switching to digitizing mode the point locator kicks in and starts launching all the threads to collect the snapping locations.

Following your advice, this seems to work just fine:

```patch
--- a/src/core/qgspointlocator.cpp
+++ b/src/core/qgspointlocator.cpp
@@ -1008,7 +1008,14 @@ void QgsPointLocator::waitForIndexingFinished()
 {
   disconnect( mInitTask, &QgsPointLocatorInitTask::taskTerminated, this, &QgsPointLocator::onInitTaskFinished );
   disconnect( mInitTask, &QgsPointLocatorInitTask::taskCompleted, this, &QgsPointLocator::onInitTaskFinished );
-  mInitTask->waitForFinished();
+
+  const auto startTime { std::chrono::system_clock::now() };
+
+  // Same timeout of waitForFinished
+  while( mInitTask && mInitTask->isActive() && std::chrono::system_clock::now() - startTime < std::chrono::seconds( 30 ) )
+  {
+    qApp->processEvents();
+  }
```

It will probably crash if it times out but this is no different than it was without the patch.

I think we should merge this PR as it is because it fixes at least a few scenarios and provides a faster/safer implementation for the specific use case with no drawbacks.

The patch attached above fixes the general problem of running the locators in separate threads (which we cannot avoid) without deadlocks caused by function evaluations delegated to the main thread.

If you feel confident about the patch I can either make a separate PR or push it here.

**Comment by elpaso** [comment]
@nyalldawson took your advice and looking at the client code it seems that somehow `relaxed` wasn't passed to (only) some of the functions. 

This updated PR should fix all similar scenarios.

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
