### PR TITLE
Bump minimum Python version 3.6

### PR DESCRIPTION
**Pull request by m-kuhn**
See discussion in https://github.com/qgis/QGIS/pull/40913#issuecomment-757126568

### CODE REVIEW

**Comment by nyalldawson** [comment]
+1

**Comment by nyalldawson** [comment]
Thoughts about further bumping this to 3.6 so that we get f string support?

**Comment by m-kuhn** [comment]
I think you got write support on this branch?

**Comment by nyalldawson** [comment]
I was after your thoughts, not your code 😂

**Comment by m-kuhn** [comment]
Read my previous comment as a yes.
We'll "loose" debian stretch, but I'm of the opinion that those who need a superstabel system should also take a superstabel qgis. This change will land in ltr a year from now (earliest).

**Comment by m-kuhn** [comment]
It's currently stuck on the MXE build
@elpaso what's required to get a newer python version into this image?

**Comment by PeterPetrik** [comment]
python 3.7 is already in macOS packages

**Comment by m-kuhn** [comment]
Gentle ping @elpaso for a hint about how to update dependencies for mxe

**Comment by elpaso** [comment]
> Gentle ping @elpaso for a hint about how to update dependencies for mxe

There is no python support in QGIS MXE builds ...  I'll check why it fails.

**Comment by m-kuhn** [comment]
I guess it's for build deps (not runtime deps)

**Comment by elpaso** [comment]
@m-kuhn can you rebase? I've updated the MXE docker image and the build scripts.

**Comment by nyalldawson** [comment]
Unrelated test failure

**Pull request merged**
