### PR TITLE
Ensure that all symbol layer types correctly respect the symbol's opacity setting

### LINKED ISSUE #18022: Transparency of markers in marker line is neither applied nor stored
Author Name: **Anita Graser** (@anitagraser)
Original Redmine Issue: [9428](https://issues.qgis.org/issues/9428)
Affected QGIS version: 3.7(master)
Redmine category:gui
Assignee: Martin Dobias

---
The GUI for markers in a marker line has a transparency slider but the setting is not applied to the markers in the preview or in the map itself. The setting isn't stored either.

### PR DESCRIPTION
**Pull request by nyalldawson**
…even when the symbol layer has data defined colors set or involves sub symbols (e.g. marker line symbols)

A surprising number of symbol layer types totally ignored the symbol opacity setting!

Fixes #18022

### CODE REVIEW

**Review by nirvn — COMMENTED** [review]
Code looks good, great fix. A good friend of mine once said: test cases? :wink:

**Comment by nyalldawson** [comment]
@nirvn tests added

**Comment by nyalldawson** [comment]
(this bumps the test coverage of symbols a LOT - there was a lot of gaps in the existing tests!)

**Review by nirvn — APPROVED** [review]
Fantastic!

**Pull request merged**
