### PR TITLE
Add dependency on Geographiclib, add API for calculating geodesics

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR adds API to QgsDistanceArea which allows for calculation of geodesics between two points, respecting the ellipsoid settings for the QgsDistanceArea object.

Geographiclib is used to do the calculation here -- so it's added as a new dependency. In future we should replace some of our custom methods (ellipsoidal distance/area calculations) with the corresponding geographiclib calls for improved accuracy.

Additionally, I've added a method for automatically breaking the geodesic line at the 180 degree longitude line. We use a smart iterative approach here to calculate the (almost) exact latitude at which the geodesic segment actually crosses the date line, so the results should be nice and accurate regardless of the segmentation distance used.

### CODE REVIEW

**Comment by elpaso** [comment]
Did you check if https://github.com/qgis/QGIS/tree/master/ms-windows/mxe still works with the new dependency?

**Comment by rouault** [comment]
Is the new dependency needed ? PROJ already offers a geodesic.h header, that is a partial port of GeodesicLib (by its author), and has a geod_inverseline() function

**Comment by nyalldawson** [comment]
@rouault seems not, thanks. But I'm curious --- what's the long term goal with that duplication of functionality? Is one better maintained then the other? Will the functionality in one of the libraries eventually be phased out?

Part of my thinking here was that by adding the geographiclib dependency we could potentially take advantage of the other models for area calculation which it offers (but I haven't looked into that in depth yet).

**Comment by rouault** [comment]
> what's the long term goal with that duplication of functionality? Is one better maintained then the other? Will the functionality in one of the libraries eventually be phased out?

That's a question that @cffk  could potentially best answer than me

**Comment by cffk** [comment]
geodesic.h offers the same functionality for geodesic calculations as
the C++ library GeographicLib.  I am expecting to maintain this state of
affairs for the foreseeable future.  Thus if you're already depending on
PROJ, there's no need to include GeographicLib.  On the other hand,
GeographicLib does offer the ability to calculate the area of polygons
whose edges are rhumb lines and, in a future version, I want to allow
the polygons to have a mixture of geodesic and rhumb edges.

A comment about breaking lines at the international date line: is this
in fact necessary?  geodesic.h + GeographicLib both allow you to
generate points along a geodesic without any jumps in the longitude
(this is the LONG_UNROLL feature).  I planned for this feature to deal
with all issues of displaying geodesics nicely.

If you really need to compute the latitude at which a geodesic crosses
lon = 180, then this can be done with a couple of iterations of Newton's
method.  Let me know if this is needed.

**Comment by hamiltoncj** [comment]
I would say that the ability to break a line when it crosses lon=180 is
important for visual display. QGIS does not handle visually replicating
data across the 180 boundary and can produce some very undesirable visual
results when it does. I had implemented a line break using the
"Intersection of two paths given start points and bearings" algorithm from:

https://www.movable-type.co.uk/scripts/latlong.html

I am guessing that it uses spherical math so it is probably not as accurate
as we would like. I would very much like a geographiclib algorithm that
returns the latitude when a line crosses a certain longitude or simply the
point of intersection when two lines cross.

Calvin

**Comment by nyalldawson** [comment]
Thanks for the clarification @cffk  -- I'll update this PR to remove the geographiclib dependancy and use proj instead.

> A comment about breaking lines at the international date line: is this
in fact necessary? geodesic.h + GeographicLib both allow you to
generate points along a geodesic without any jumps in the longitude
(this is the LONG_UNROLL feature). I planned for this feature to deal
with all issues of displaying geodesics nicely.

Yes - as @hamiltoncj has pointed out, there's parts of QGIS which don't play nicely without a forced break at the date line. Even with the LONG_UNROLL feature, when QGIS projects the generated geodesic into another projection (e.g. for display) it results in a join spanning the globe at the date line. 

> If you really need to compute the latitude at which a geodesic crosses
lon = 180, then this can be done with a couple of iterations of Newton's
method. Let me know if this is needed.

That's more or less what I've done in latitudeGeodesicCrossesDateLine - although I found that if the original two points are very far apart then the algorithm converges quicker if we start with a simple binary search to narrow down the window. I think something like this would be nice to have available in geodesic.h -- if you think it's suitable I can make a PR for proj?

**Comment by cffk** [comment]
@nyalldawson addressing the issue of computing the intersection of a geodesic with a meridian...

My take on this is described in [Geodesics on an ellipsoid of revolution](https://arxiv.org/abs/1102.1215), Section 10, Problem 4.

Having solved the inverse geodesic problem, we know &phi;<sub>1</sub>, &lambda;<sub>1</sub> and &alpha;<sub>1</sub> and the goal is to determine &sigma;<sub>12</sub> which gives &lambda;<sub>2</sub> = 180&deg;.  We can apply Newton's method here, where the needed derivative d&lambda;<sub>12</sub>/d&sigma;<sub>12</sub> (with &phi;<sub>1</sub> and &alpha;<sub>1</sub> held constant) is given by Eq. (76).  This is all inexpensive to carry out since all the calculations can be done on a single geodesic line object.

However, even though this method will converge very fast, it will be simpler, in many cases, to use some simpler scheme.

I've avoided adding the solution of the general trigonometrical problems to GeographicLib (beyond the standard direct and inverse problems), because
* For some problems there will be 0, 1, or 2 solutions and providing a decent user interface to handle this is tricky;
* The methods outlined in Sec. 10 all presume that you can find an approximate solution so that Newton's method can be applied; this may not always be straightforward.
* Dealing with all the peculiar cases (e.g., a geodesic passing over the pole) is onerous.

**Comment by nyalldawson** [comment]
> However, you're
already making essentially the same approximation plotting the other
segments of the geodesic as straight lines. If you worry about the
discrepancy between these two crossing points, you should just break up
the whole line into shorter segments and again use linear
interpolation to treat the date line discontinuity. So I would argue
that computing the exact crossing point is unnecessary.

@cffk 

I (internally) debated this too when I was writing this PR, but in the end my thought process was:

- (ignoring date line effects) the QgsDistanceArea::geodesicLine method returns a list of points which are all exactly on the geodesic. Lines joining these points will only approximate the geodesic, but the vertices themselves will exactly represent the geodesic.
- This means that at a later stage we could come back and densify this geodesic linestring at a greater resolution -- adding in extra vertices which fall exactly on the original geodesic by calculating the geodesic between subsequent vertices and adding extra points on these.
- If we only approximate the latitude at the 180 degree break point, we're adding in extra vertices which aren't on the geodesic. It's no longer possible to further process this linestring using the assumption that all the vertices represent points on the geodesic.

For this reason I prefer the safer approach using the near-exact calculation. That way anyone calling the API (or using the tools which exposes it through the QGIS ui) can be confident that the resultant linestrings only contain vertices which fall on the geodesic.

(If we ever decided to add an option to **render** linestrings as geodesic lines "on the fly" in future then I agree that an approximation is fine, and we could add API for the approximation at that stage).

**Comment by cffk** [comment]
@nyalldawson 
> For this reason I prefer the safer approach using the near-exact calculation. That way anyone calling the API (or using the tools which exposes it through the QGIS ui) can be confident that the resultant linestrings only contain vertices which fall on the geodesic.

OK, fair enough!

**Pull request merged**
