### PR TITLE
Reorganize sequences of callout properties

### PR DESCRIPTION
**Pull request by DelazJ**
This PR groups callouts properties, first showing settings affecting the callout rendering and then its relation with the feature (mainly, `offset from feature` and `anchor point`). The logic behind is:
1. configure the look of the callout
2. configure how it relates with its origin, ie the label (label anchor point and its offset)
3. configure how it relates with the destination, ie the feature (feature anchor point and its offset)

This allows to have the common settings at the "same" place regardless the callout type, and makes documenting them easier, more linear (avoids readers/writers going back and forth to find explanation)

oldCalloutsCurved
newSimpleCallout
new_callout
(no strong opinion with moving the margins back to the bottom)

### CODE REVIEW

**Comment by Saijin-Naib** [comment]
I just want to say I love all the UI/UX work you've been doing.

**Comment by DelazJ** [comment]
Thanks @Saijin-Naib

**Comment by pblottiere** [comment]
@nirvn what do you think?

**Comment by DelazJ** [comment]
Curved and balloon callouts being features developed during this cycle, it could be nice we decide on the "harmonization" before the release, before they have more "audience".

**Comment by nirvn** [comment]
@DelazJ , nice work. The only thing I'm not feeling so great about is the disconnected offset from label / distance from feature settings. IMHO those two should be sitting next to one another whenever possible.

**Comment by DelazJ** [comment]
Hi @nirvn Sorry I forgot I had a pending and waiting for feedback PR.
> The only thing I'm not feeling so great about is the disconnected offset from label / distance from feature settings. IMHO those two should be sitting next to one another whenever possible.

IMHO it looked more important, when it comes to the relation between the connector and the feature (or the label), to know where on the feature (or the label) I want to snap the connector, and at which distance. Hence the couples `Offset from xxx/xxx anchor point`. So I tried to keep both worlds and got these

image

image

**Comment by DelazJ** [comment]
May I...?

**Comment by nirvn** [comment]
I don't have any objections on my end, my concern has been addressed. @nyalldawson , do you have any lingering objections?

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
