### PR TITLE
[layer tree] Avoid blurry icons on devices with a pixel ratio != 1

### PR DESCRIPTION
**Pull request by nirvn**
## Description

The layer tree model's scaleIconSize() function needs to take into account the device pixel ratio to produce properly sized icons in environments where Qt's high dpi scaling (i.e. AA_EnableHighDpiScaling) is switched on.

See before (left) vs. PR (rigth):
image

### CODE REVIEW

**Comment by elpaso** [comment]
@nirvn did you consider making a QgsApplication method for that, so that we can reuse it whenever we need to scale some icons? I mean: not only in the layer tree.

**Comment by nirvn** [comment]
@elpaso , that's a possibility -- @nyalldawson , thoughts?

**Comment by nyalldawson** [comment]
Is the smaller size of the point in the after screenshot correct? Does it match the canvas size now?

**Comment by nirvn** [comment]
@nyalldawson , yes it does

**Comment by m-kuhn** [comment]
Would we ideally use `layerTreeView->screen()->physicalDotsPerInch()` -- or is this not feasible because we are in the model?

**Comment by nirvn** [comment]
@m-kuhn , not possible from the model itself AFAIK.

**Comment by nyalldawson** [comment]
> @elpaso , that's a possibility -- @nyalldawson , thoughts?

Yes, that would be good.

There's already QgsGuiUtils::scaleIconSize, which is a near identical copy of this. Perhaps it's possible to call a QgsApplication method from the QgsGuiUtils method instead, so that we only have a single version of this conversion floating around...

**Comment by nirvn** [comment]
@nyalldawson , I can't call QgsGuiUtils from src/core though right?

**Comment by nyalldawson** [comment]
That's why I'm proposing moving the guts of the QgsGuiUtils function to QgsApplication

**Comment by nirvn** [comment]
Ah, got it. I shall proceed.

**Comment by nirvn** [comment]
@nyalldawson , done, all moved to QgsApplication::scaleIconSize

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@PeterPetrik @3nids can you please test on macos after this is merged and confirm that there's no regressions? I believe macos is the only other platform which defaults to a > 1 pixel ratio

**Comment by 3nids** [comment]
@nyalldawson from a first quick look, everything looks the same than before.

**Comment by 3nids** [comment]
not sure this is related but lately...
image

**Comment by nirvn** [comment]
I was worried it'd do that. Qt still so messy with hidpi handling. I'll commit a follow up PR to address issue.

**Comment by 3nids** [comment]
and also the data defined button…
image

**Pull request merged**
