### PR TITLE
Tidy installer_data.py and utils.py

### PR DESCRIPTION
**Pull request by cjmayo**
- Fix unused and missing imports.
- Only import configparser is needed for Python 3
- Unnecessary string u prefix for Python 3
- Comment typo

## Description
This is a bit of a mix of small things. Happy to split out if required.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by borysiasty** [comment]
In various materials for QGIS 2.x (e.g. [1]) it is said to import qgsfunction from qgis.utils, so it's kind of helper import. I'm not sure if we should drop it (and even if we can do it before 4.0). All the rest LGTM


[1] https://gis.stackexchange.com/questions/195880/register-custom-qgsfunction-in-pyqgis

**Comment by cjmayo** [comment]
Put qgsfunction back. Also expanded the typo fix to be "of which".

**Comment by nyalldawson** [comment]
Unrelated test failure, restarting...

**Comment by nyalldawson** [comment]
@borysiasty this look good to you?

**Comment by borysiasty** [comment]
Yes, LGTM except removing the qgsfunction import.

**Comment by borysiasty** [comment]
Oh yes, sorry, time to buy new glasses. Then LGTM.

**Pull request merged**
