### PR TITLE
[PostgreSQL] changeGeometryValues - combine SQL queries into chunks

### PR DESCRIPTION
**Pull request by MorriganR**
reworked PR #42601

### CODE REVIEW

**Comment by MorriganR** [comment]
TODO: if multi-column PK contains NULL and only geometry is changed - changes cannot be saved to PostgreSQL (bug in master).

Code:
https://github.com/qgis/QGIS/blob/754328cbd0a4e5251f03c444221988a7031f4cef/src/providers/postgres/qgspostgresprovider.cpp#L3221-L3225
generate SQL prepare statement `updatefeatures` like this:
`UPDATE table SET geom=geom_value WHERE id_1 = $1 AND id_2 = $2`
as a result:
`EXECUTE updatefeatures(1,NULL)`
does nothing...

**Comment by MorriganR** [comment]
At the moment, I know of three different methods for solving the problem related to NULL.
1) Refuse to use the Prepared Statement. Generate the SQL string as is, but use transform_null_equals.
https://www.postgresql.org/docs/current/runtime-config-compatible.html#RUNTIME-CONFIG-COMPATIBLE-CLIENTS
Like that:
`SET transform_null_equals = ON;`
`SELECT * FROM foobartable WHERE id1 = 1 AND id2 = NULL;`
the last line will be converted to
`SELECT * FROM foobartable WHERE id1 = 1 AND id2 IS NULL;`
on the DB server side.
<details><summary>Some SQL statement to play with this solution</summary>

```sql
-- DROP TABLE foobartable;
CREATE TEMP TABLE foobartable (lab integer, id1 integer, id2 integer);
INSERT INTO foobartable (lab, id1, id2) VALUES (42, 1, 1);
INSERT INTO foobartable (lab, id1, id2) VALUES (42, 1, NULL);
INSERT INTO foobartable (lab, id1, id2) VALUES (42, NULL, 1);
SELECT * FROM foobartable;

SET transform_null_equals = OFF;
SELECT * FROM foobartable WHERE id1 = 1 AND id2 = 1; -- 1 rows
SELECT * FROM foobartable WHERE id1 = 42 AND id2 = 42; -- 0 rows
SELECT * FROM foobartable WHERE id1 = 1 AND id2 = NULL; -- 0 rows
SELECT * FROM foobartable WHERE id1 = NULL AND id2 = 1; -- 0 rows

SET transform_null_equals = ON;
SELECT * FROM foobartable WHERE id1 = 1 AND id2 = 1; -- 1 rows
SELECT * FROM foobartable WHERE id1 = 42 AND id2 = 42; -- 0 rows
SELECT * FROM foobartable WHERE id1 = 1 AND id2 = NULL; -- 1 rows
SELECT * FROM foobartable WHERE id1 = NULL AND id2 = 1; -- 1 rows
```
</details>

2) Replace `=` in the prepared statement with `IS NOT DISTINCT FROM`
https://wiki.postgresql.org/wiki/Is_distinct_from
<details><summary>Some SQL statement to play with this solution</summary>

```sql
-- DROP TABLE foobartable;
CREATE TEMP TABLE foobartable (lab integer, id1 integer, id2 integer);
INSERT INTO foobartable (lab, id1, id2) VALUES (42, 1, 1);
INSERT INTO foobartable (lab, id1, id2) VALUES (42, 1, NULL);
INSERT INTO foobartable (lab, id1, id2) VALUES (42, NULL, 1);
SELECT * FROM foobartable;

-- DEALLOCATE foobarequal;
PREPARE foobarequal(int, int) AS SELECT * FROM foobartable WHERE id1 = $1 AND id2 = $2;
SET transform_null_equals = ON; -- does not work for prepared statement
EXECUTE foobarequal(1, 1); -- 1 rows
EXECUTE foobarequal(42, 42); -- 0 rows
EXECUTE foobarequal(1, NULL); -- 0 rows
EXECUTE foobarequal(NULL, 1); -- 0 rows

-- DEALLOCATE foobardisti;
PREPARE foobardisti(int, int) AS SELECT * FROM foobartable WHERE id1 is not distinct from $1 AND id2 is not distinct from $2;
EXECUTE foobardisti(1, 1); -- 1 rows
EXECUTE foobardisti(42, 42); -- 0 rows
EXECUTE foobardisti(1, NULL); -- 1 rows
EXECUTE foobardisti(NULL, 1); -- 1 rows
```
</details>

3) Analyze the presence of NULL in a multi-column PK and add an appropriate Prepared Statement as needed.
<details><summary>Some SQL statement to play with this solution</summary>

```sql
-- DROP TABLE foobartable;
CREATE TEMP TABLE foobartable (lab integer, id1 integer, id2 integer, id3 integer);
INSERT INTO foobartable (lab, id1, id2, id3) VALUES (42, 1, 1, 33);
INSERT INTO foobartable (lab, id1, id2, id3) VALUES (42, 1, NULL, 33);
INSERT INTO foobartable (lab, id1, id2, id3) VALUES (42, NULL, 1, 33);
SELECT * FROM foobartable;

-- DEALLOCATE foobar_0;DEALLOCATE foobar_1;DEALLOCATE foobar_2;DEALLOCATE foobar_4;DEALLOCATE foobar_3;DEALLOCATE foobar_7;
PREPARE foobar_0(int, int, int) AS SELECT * FROM foobartable WHERE id1 = $1 AND id2 = $2 AND id3 = $3;
PREPARE foobar_1(int, int, int) AS SELECT * FROM foobartable WHERE id1 IS NULL AND id2 = $2 AND id3 = $3;
PREPARE foobar_2(int, int, int) AS SELECT * FROM foobartable WHERE id1 = $1 AND id2 IS NULL AND id3 = $3;
PREPARE foobar_4(int, int, int) AS SELECT * FROM foobartable WHERE id1 = $1 AND id2 = $2 AND id3 IS NULL;
PREPARE foobar_3(int, int, int) AS SELECT * FROM foobartable WHERE id1 IS NULL AND id2 IS NULL AND id3 = $3;
-- ...
PREPARE foobar_7(int, int, int) AS SELECT * FROM foobartable WHERE id1 IS NULL AND id2 IS NULL AND id3 IS NULL;

-- (1, 1, 33) => 000 => foobar_0
EXECUTE foobar_0(1, 1, 33); -- 1 rows
-- (42, 42, 33) => 000 => foobar_0
EXECUTE foobar_0(42, 42, 33); -- 0 rows
-- (1, NULL, 33) => 010 => foobar_2
EXECUTE foobar_2(1, NULL, 33); -- 1 rows
-- (NULL, 1, 33) => 100 => foobar_1
EXECUTE foobar_1(NULL, 1, 33); -- 1 rows
-- (NULL, NULL, NULL) => 111 => foobar_7
EXECUTE foobar_7(NULL, NULL, NULL); -- 0 rows
```
</details>

I like the last, third option, but its implementation will be very verbose and incomprehensible.
Does anyone have any other ideas on this?

**Comment by MorriganR** [comment]
PR is ready for review

**Comment by espinafre** [comment]
I'd love to see this merged as well.

**Comment by MorriganR** [comment]
> I'd love to see this merged as well.

Maybe next year... :)
Waiting for #44267

**Pull request closed without merging**
