### PR TITLE
Fixes for 'Using perimeter (curved)' labels on polygon layers

### PR DESCRIPTION
**Pull request by fritsvanveen**
Sometimes a label is plotted upsidedown if always upright is specified and vice versa.

### CODE REVIEW

**Comment by fritsvanveen** [comment]
@nyalldawson Will you please look into this? I also added two issues concerning labels [https://hub.qgis.org/issues/15399](url) and [https://hub.qgis.org/issues/15400](url)

**Comment by nyalldawson** [comment]
@fritsvanveen nice work! 

Let's get this greenlit on the Travis. Here's what you'll need to do to start:

1. enable the "with_astyle" option in cmake and rebuild. This will allow you to use the scripts/prepare-commit.sh script, which automatically formats patches up to the QGIS standard and applies automated fixes. Travis checks that this script has been run and will flag any patches where it hasn't.

2. this script is normally run before committing changes (or automated using a pre-commit hook), so to fix the formatting retrospectively you'll need to run

```
scripts/astyle.sh src/core/pal/feature.cpp
scripts/astyle.sh src/core/pal/feature.h
scripts/astyle.sh src/core/pal/labelposition.cpp
```

Then commit the changes.

3. Push the new commit up to this branch to trigger a new test run on Travis.

Let me know if you have any questions - I'm happy to assist!

**Comment by nyalldawson** [comment]
@fritsvanveen also just a heads-up - i've got 2 pieces of work underway relating to perimeter labeling:
1. fix the "label must fit inside polygon" option when used with perimeter labeling
2. some tweaks to improve the label placement when using the non-curved perimeter labeling option

**Comment by fritsvanveen** [comment]
@nyalldawson I'm unhappy with the recursive call in FeaturePart::curvedPlacementAtOffset. It is not obvious that there won't be an endless loop. Shall I refactor that first?

**Comment by fritsvanveen** [comment]
@nyalldawson astyle doesn't work:
sh-3.1$ scripts/astyle.sh src/core/pal/feature.cpp
qgisstyle not found - please enable WITH_ASTYLE in cmake and build it
sh-3.1$
I enabled WITH_ASTYLE in CMakeCache.txt. I'm working with Visual Studio 2010 under Windows.
I did find and remedy some style problems in my code though.
Can you assist?

**Comment by jef-n** [comment]
Are you building the RelWithDebInfo configuration?

**Comment by fritsvanveen** [comment]
@jef-n Yes

**Comment by jef-n** [comment]
Then `scripts/RelWithDebInfo/qgisstyle` should exist when you build with `WITH_ASTYLE` enabled

**Comment by fritsvanveen** [comment]
Nope. Can we connect with Skype? Search for my name in Wijster.

**Comment by fritsvanveen** [comment]
@jef-n All I did was enable WITH_ASTYLE in CMakeCache.txt in my Build directory and do a rebuild all. Not sure if I must regenerate the project files. Should qgisstyle exist in the Build or the Source directory?

**Comment by jef-n** [comment]
scripts/RelWithDebInfo/qgisstyle in the source directory

**Comment by fritsvanveen** [comment]
@jef-n 
scripts

**Comment by jef-n** [comment]
did you try to touch the toplevel CMakeLists.txt and rebuild?

**Comment by fritsvanveen** [comment]
@jef-n It is building after I touched CMakeLists.txt. Have to go now. Txs for helping sofar, Jürgen!

**Comment by fritsvanveen** [comment]
@jef-n Much better now:
`sh-3.1$ scripts/astyle.sh src/core/pal/feature.cpp
autopep8 not found
dos2unix: converting file src/core/pal/feature.cpp.flip_modified to Unix format ...
formatted  src\core\pal\feature.cpp
scripts/astyle.sh: scripts/unify_includes.pl: /usr/bin/perl: bad interpreter: No such file or directory`
Looks like I have to install perl.
Is the missing autopep8 a problem?

**Pull request closed without merging**
