### PR TITLE
Support for now() in WFS filters

### PR DESCRIPTION
**Pull request by m-kuhn**
Enhance OGC filters with the following:

 * **Support for static functions**. Any function that returns a static result value will be evaluated on client side already. E.g. `to_lower('SOME_VALUE')`
 * **Support for date time literals**. Date and DateTime literals will be converted to ISODate format
 * Support for global ~and project~ variables in filters (would be nice to include layer too but that would mean passing around more context, and no, replacing `QgsProject::instance()` calls here is out of scope ;) )

Changes to expressions:

* ~**Tag `now()` as static** now() will then return a consistent value throughout expression evaluation (the time from prepare actually).~ **Add a test that checks if now() behaves static**

I can also add tests if someone can give me an advice for this.

### CODE REVIEW

**Comment by m-kuhn** [comment]
@rouault @wonder-sk @nyalldawson any reservations regarding `now()` being static or the way time/date is handled (mostly wondering about smart ideas concerning timezone handling that would need to be adjusted)

**Comment by wonder-sk** [comment]
No objection from me to make now() static, but please add a unit test for that (should be easy - prepare, evaluate, wait 1 sec, evaluate, compare).

I am a bit confused with the existing setIsStatic() calls - right now in the codebase I can see a bunch of setIsStatic( false) calls which I guess do nothing as functions are not static by default if I understand correctly (bool mIsStatic = false) ?

**Comment by wonder-sk** [comment]
I don't like the introduction of new QgsProject::instance() calls though. :scream:

I would suggest to either skip project variables or add them properly by passing QgsProject pointer. To me, every piece of code in qgis_core library using QgsProject::instance() is a source of bugs within QGIS server code...

**Comment by m-kuhn** [comment]
> No objection from me to make now() static, but please add a unit test for that (should be easy - prepare, evaluate, wait 1 sec, evaluate, compare).
>  I am a bit confused with the existing setIsStatic() calls - right now in the codebase I can see a bunch of setIsStatic( false) calls which I guess do nothing as functions are not static by default if I understand correctly (bool mIsStatic = false) ?

I did the test and was surprised to find that it was already static before.
The log is this: by default all functions are treated as static if all of their parameters are static. This behavior can be disabled with a `setIsStatic( false )` call.
I'm gonna remove this line and add the test.

**Comment by m-kuhn** [comment]
Thanks for the review @wonder-sk !
If anyone still has a note regarding timezone, please let me know, there's still some time before release.

**Pull request merged**
