### PR TITLE
ReadOnly vector layers, NonIdentifyableLayers

### PR DESCRIPTION
**Pull request by m-kuhn**
Vector Layers can already be set to readonly via API calls. There were two problems with this which are solved with this PR
- ReadOnly state is now persisted in the project file
- ReadOnly state can now be controlled from the project properties

Then there are some other changes for non-identifyable layers which previously have been managed by directly writing to the project. This is now centralized as a standarized API.

### CODE REVIEW

**Comment by m-kuhn** [comment]
screenshot from 2016-03-23 17-26-02

**Comment by DelazJ** [comment]
Thanks @m-kuhn 
I don't have skills to check your code so... Just want to ask if sorting the list by the checkboxes columns (Identifiable and Read-Only) does work. It uses to fail in previous release.
Something I miss in this kind of UI (it concerns also the snapping dialog) is a "Check All" box; a box (beside the column name?) that toggles the status of all the rows. Most of the times, you have just a few layers you need to set identifiable (or not). Having to (un)check one by one the rest of the layers is not that fun.
Sorry, I know that these comments better belong to issue report (http://hub.qgis.org/issues/14424 or
 http://hub.qgis.org/issues/14425)
Thanks again

**Comment by m-kuhn** [comment]
@DelazJ sorting is implemented now (and it's easier to implement sorting for checkbox tables in the future, so if you find other, raise a hand).
A check all checkbox would be really nice, but it's a bit more complex and I lack the time right now.

**Comment by DelazJ** [comment]
@m-kuhn thanks for this. Is sorting available also in Snapping dialog?
Looking forward for testing...

**Comment by m-kuhn** [comment]
Unfortunately the layer list there is a tree widget and tree widgets are implemented slightly different to table widgets.

**Comment by yjacolin** [comment]
@m-kuhn does the title's tab should be renamed?

**Comment by m-kuhn** [comment]
Inputs welcome

**Pull request closed without merging**
