### PR TITLE
[Plugin manager][needs-docs] Warning icons on the plugin list

### PR DESCRIPTION
**Pull request by borysiasty**
Mark experimental and deprecated plugins with a small flask/warning icon on the right side. 

after

Also the deprecation icon in the details page is changed to the same warning sign - otherwise it would look like that:

before

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Good initiative to mark them visually.
However, I am not sure if it's the right icon to use. To me, this means "there's something wrong, requires attention", e.g. a new security patch is out, should be upgraded.
Instead I would propose to make them grey, italics (move to bottom) to make them pop out less, not more.

**Comment by borysiasty** [comment]
@m-kuhn I'm not competent to discuss it as personally I'd be most happy to drop the obsolete and experimental statuses ;))

As far as I understand the deprecated plugin status, it means "you should uninstall this plugin if only possible", so maybe the icons should be displayed only for installed plugins? Anyway, I guess 99,9% of users won't enable deprecated plugins, so they won't see it.

More important is the experimental flask, as about half of the plugins available for 2.x has an experimental version (28% experimental only + 22% have both versions). There are two kind of users: those who din't enable experimentals, and those who did it, sometimes forced by a need for one particular plugin. And all the latter will see a flask by every second plugin. A bit crowdy, but not as alarming as the deprecated icon. And users now what plugin is considered stable.

I'm not sure if you meant to move also experimental plugins to bottom. It would move half of the list (including that one important plugin from the previous paragraph), while the user may expect they are sorted alphabetically. Furthermore, it won't work well with other sort options, now available by a right click. And I'd avoid messing with the fonts, especially for items not gathered together at the bottom (we even don't have many options in the color palette, if we don't want the text to disappear in other color schemes).

**Comment by borysiasty** [comment]
The travis fail is not related.

**Comment by m-kuhn** [comment]
I think we have an issue here with "Plugin is experimental" vs. "Plugin version is experimental". The same does not apply for deprecated, correct?

If yes, I'd propose to deprecated ones grey.

For experimental ones, it would be great if we could show those where the plugin is experimental (is there a definition for that?) as grey.

For those where the latest version is considered experimental / testing, it would make sense to activate this option per plugin (and not globally). A message on the plugin page: "There is a testing version available for this plugin, click here to enable test versions of this plugin [ ]" would be really nice.

**Comment by borysiasty** [comment]
@m-kuhn wrote:
> For those where the latest version is considered experimental / testing, it would make sense to activate this option per plugin (and not globally). A message on the plugin page: "There is a testing version available for this plugin, click here to enable test versions of this plugin [ ]" would be really nice.

Yes, it's the only an obvious long-term solution, but I won't manage to do it for 3.4.

For the list style, I've unfortunately no more time I can assign to this mini-topic, so let's see if there are any other opinions. If not, I'm postponing the font color and sort order for a bigger overhaul of the manager someday.

**Comment by m-kuhn** [comment]
Yes, I'd rather leave it as is currently. I think the font color for deprecated should be quite easy to do, no? That would already be really good if you'd find time for that!
All the rest can wait

**Comment by borysiasty** [comment]
@nyalldawson will you miss the flasks if we close the PR? :-)

**Comment by nyalldawson** [comment]
I'm happy to go with the group consensus!

**Comment by borysiasty** [comment]
Superseded by #7906.

**Pull request closed without merging**
