### PR TITLE
debian packaging: drop bullseye

### PR DESCRIPTION
**Pull request by jef-n**
qgis.g.info now uses G_get_projwkt / G_get_projsrid, which was introduced in GRASS 7.8.6, GRASS' version.h includes major and minor and bullseye only has 7.8.5.

### CODE REVIEW

**Comment by jef-n** [comment]
You mean not backport?  Yes. Only master is broken on bullseye, because of the qgis.g.info change (48bd2b73ccf18655aef9a966931e48b9a72b5855) in master.

**Comment by nyalldawson** [comment]
@jef-n it was backported here: https://github.com/qgis/QGIS/pull/58075

**Comment by jef-n** [comment]
> @jef-n it was backported here: #58075
 
The nightlies build the release branches.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@jef-n see https://github.com/qgis/QGIS/pull/58118

**Pull request merged**
