### PR TITLE
Enable build with PDAL by default

### PR DESCRIPTION
**Pull request by wonder-sk**
Point cloud support has been there in a couple of QGIS releases already and it would make sense to have the PDAL support built by default. Without PDAL, point cloud layer implementation is very limited, not allowing indexing and display of regular files like LAS/LAZ, and the Processing algorithms are not available either...

### CODE REVIEW

**Comment by nyalldawson** [comment]
Good move! Could we default to WITH_3D too? I don't see a good reason to default to disabling this

**Comment by nirvn** [comment]
@wonder-sk , nice! Should a note be added in INSTALL.md to mention absence of pdal on latest Ubuntu 22.10 and upcoming 23.04 somewhere?

**Comment by wonder-sk** [comment]
Cool, I have made WITH_3D = TRUE the default as well!

@nirvn good point regarding mention of missing Debian/Ubuntu packages for PDAL - as I was leaving the hackfest, @jef-n mentioned he may have sorted it somehow with the missing packages, just not sure yet was would be the solution, as I had to run to catch the plane :-)

**Review by uclaros — APPROVED** [review]
Sane defaults!

**Pull request merged**
