### PR TITLE
Addition of Helicopter svg marker

### PR DESCRIPTION
**Pull request by nikc22**
The organisation I work for operates helicopters and I've built this svg file to allow me to use this as a marker. I've named the file in the convention of other files and placed into the appropriate folder, while testing to ensure the marker can be colourised in the same way as other svg markers.

I'm adding this as others might benefit from the work I've done.

## Description

As this is not a code change and the addition of a single svg file, I've not run the pre-commit scripts.

### CODE REVIEW

**Comment by roya0045** [comment]
Might be a better fit for https://github.com/QGIS-Contribution/QGIS-ResourceSharing

**Comment by nyalldawson** [comment]
Looks good to me! Can you please tighten the document size so that it doesn't include the extra vertical padding?

**Review by nikc22 — COMMENTED** [review]
Updated to remove vertical padding

**Comment by nyalldawson** [comment]
Is the new version pushed? Github is still showing the padding:

image

**Review by nikc22 — COMMENTED** [review]
Try now, second attempt, changed the canvas size.

**Comment by nyalldawson** [comment]
Hmm - the GitHub preview still looks messed up here?

**Comment by m-kuhn** [comment]
@nikc22 it looks like some of the vertices on your drawing are negative values.
Have a look at the result here: https://github.com/qgis/QGIS/pull/37371/files?short_path=3994969#diff-39949693b138c42be4f9234b8b75e5e9

Would be very nice to integrate this !

**Comment by nyalldawson** [comment]
Superseded by https://github.com/qgis/QGIS/pull/37887

**Pull request closed without merging**
