### PR TITLE
Rework "show pinned labels" icon

### PR DESCRIPTION
**Pull request by nyalldawson**
The original icon had an unintended effect of always looking enabled
on some platforms (due to the solid blue background rectangle)

Previous:

image

New:

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nirvn ?

**Comment by nirvn** [comment]
Looks good. While we're trying to improve things here, could you add a separator between the 2nd and 3rd icon as well as the 4th and the 5th? It'll  regroup map tools vs toggles vs main styling dialogs together.

**Comment by nirvn** [comment]
@nyalldawson , BTW, the show unplaced label icon could be further simplified and only have the <abc| drawing in red, it's sit quite nicely next to the blue one.

**Comment by nyalldawson** [comment]
@nirvn is this what you had in mind?

image

**Comment by nirvn** [comment]
@nyalldawson , exactly that, much improved.

**Pull request merged**
