### PR TITLE
Poly2tri library update to fix crash with self-intersecting ring & fix random marker fill 

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR updates the poly2tri to catch up a number of fixes upstream, including a fix for self-intersecting rings crashing poly2tri. As a result, we can remove that check from the QgsTessellator class, which speeds things up and avoid having to skip those polygons when building 3D scenes.

I n doing so, we also end up fixing the random marker fill symbol layer failing with valid polygons having ring(s) touching the polygon outer boundaries, as reported in #46021.

Turns out time really does heal everything :wink:

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nirvn nice! Which upstream pr/commit fixes the intersecting ring issue?

**Comment by nirvn** [comment]
@nyalldawson , I don't know which one specifically. I was looking at its history of over the last year and saw a couple of commit messages that sounded like improvements on that front. Updated locally, ran tests (including the test case that was added to cover this crash) and everything ran smoothly. 

The test case covering the self interesting ring crashing was still crashing if I removed the check in our tessellatot class _prior to_ updating the library. After update, we're crash free.

**Comment by nyalldawson** [comment]
Ok, great!

Would be good to get @wonder-sk 's feedback here too

**Review by wonder-sk — APPROVED** [review]
Changes look good to me.

Just thinking - what happens now when there's a polygon with self-intersecting ring(s) - does the tessellation finish successfully, or will poly2tri throw an exception? In case of the latter, my thinking is that right now we only report a generic message "Triangulation failed. Skipping polygon…" - it may be good to actually unpack the underlying poly2tri exception message so that we get more information in case of failures.

**Comment by nirvn** [comment]
@wonder-sk , I tried a few _valid geometry_ with self-intersecting rings, they were showing in the 3D scenes fine.

**Pull request merged**
