### PR TITLE
[labeling] Improve curved placement on circular shapes 

### PR DESCRIPTION
**Pull request by nirvn**
This PR reworks how curved labels above and below lines are created to give us a much better rendered result.

Here's a before vs PR, look at the roundabout at the center of the canvas:
before_v_after

We used to merely _translate_ the curved label location instead of placing those on an offset path, which didn't play nice with... curves :wink: 

Big thanks to @nyalldawson for helping me push this through the finish line.

### CODE REVIEW

**Comment by roya0045** [comment]
@nirvn @nyalldawson thank you guys these reworks are appreciated! 💯 
 Is is planned at some point to fix old bugs such as with arabic text and the blocky text background?

**Comment by nirvn** [comment]
@roya0045 , by Arabic text, you mean supporting right-to-left rendering of text in curved placement?

**Comment by roya0045** [comment]
@nirvn yes I recall there were some long-standing issues with those type of text. Notably #21940

**Comment by nyalldawson** [comment]
Can I ask a favour here? The test images which use the null symbol renderer make checking the test image changes hard. Could you replace these with a solid black line single renderer ?

**Comment by nirvn** [comment]
This before vs. after CI control image does an even better job than my description at demonstrating the improvement:

image

**Comment by nyalldawson** [comment]
Ok, I've looked this over. The only concerns I have are the following test changes:
- expected_curved_hint_anchor_end.png: it looks like here the cost penalty for curvature isn't being correctly calculated, since the previous result had correctly shifted the label away from the curved portion to the straight one (the placement at end is just a hint in this case, so the result should be "place label as close to end as is nice")
- expected_curved_strict_anchor_end.png: this one definitely looks wrong -- it's a strict placement at end, so there's no room for ambiguity and the label must be placed at the exact end of the line
- expected_label_curved_negative_distance.png : something looks off here -- previously the label was rendered over the line, and now it's no longer centered
- expected_label_curved_overrun.png : something is a bit messy here -- previously the overrun was distributed nicely on either side of the line

Are you able to investigate these? My suspicion is that they mostly relate to incorrect cost calculation in these cases...

**Comment by nirvn** [comment]
Loop logic re-structured in order to take into account the total distance of offset curves too, which should give us proper start / center / end position etc.. I hopefully it'll take care of issues you've raised. Expecting most control images to require updating.

**Comment by nirvn** [comment]
@3nids , random question on our CI setup: ATM, it seems the tests are waiting for all builds to be over (i.e. 20.04, 20.10, 21.04) before the tests run, even though the tests only require one of these builds right now. Could that be improved?

E.g., right now, the build that's used to run the test, 20.04, was successful after 14min, but the tests haven't launched, waiting for 21.04 to finish building (1h30min, cache hasn't kicked in).

**Review by nyalldawson — APPROVED** [review]

**Comment by nirvn** [comment]
Tears of joy.
source

**Comment by nyalldawson** [comment]
Great work @nirvn!!

**Pull request merged**
