### PR TITLE
add GetMap FILTER test with multiple filters

### PR DESCRIPTION
**Pull request by tudorbarascu**
## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by tudorbarascu** [comment]
@pblottiere For some reason, in the test the odd parameters are ignored. E.g. IN (``"Country: \"name\" IN ( 'nowhere' , 'arctic' , 'anywhere' , 'eurasia' ``, the ``nowhere`` and ``anywhere`` parameters would not work in the test. Although the request made for a normal server works, in tests.. the odd ones get ignored for some reason. I had to put bogus countries to bypass that.

Also, I noticed that for WMS requests, the FILTER takes into account only the column name as it's in the data source, and not the QGIS column aliases. Is that how it should be?

**Comment by tudorbarascu** [comment]
@elpaso Any reason why the ``ENCODED_OUTPUT`` variable shouldn't be set by default?

**Comment by elpaso** [comment]
@tudorbarascu if that variable does what I think it does, the reason is that it was bloating travis output.

**Comment by tudorbarascu** [comment]
@elpaso Thanks for looking.

If the variable is set and the test fails, you can get the output image and create a mask.
If the test passes, there's no bloat.

https://github.com/qgis/QGIS/blob/0310c1d25334edef8abe9dd9f99f3d8ce935245b/tests/src/python/test_qgsserver.py:
```
        with open(os.path.join(tempfile.gettempdir(), image + "_result.png"), "rb") as rendered_file:
            encoded_rendered_file = base64.b64encode(rendered_file.read())
            if not os.environ.get('ENCODED_OUTPUT'):
                message = "Image is wrong\: rendered file %s/%s_result.png" % (tempfile.gettempdir(), image)
            else:
                message = "Image is wrong\n%s\nImage:\necho '%s' | base64 -d >%s/%s_result.png" % (
                    report, encoded_rendered_file.strip().decode('utf8'), tempfile.gettempdir(), image
                )
```

On the other hand, if the variable is not set and the test does fail, I didn't manage to see how to get the resulting image and make the mask. Is there a way except the output in base64?

So, the variable should exist as it doesn't bloat if the test passes, and the bloat is necessary otherwise to get the failed image and create the mask.

Thanks for reviewing. If I got it wrong, I'll rebase without the variable commit that I don't need anymore.

**Comment by elpaso** [comment]
@tudorbarascu I think you can get the images from the DASH url (the tiny url at the end of the failing job)

**Comment by pblottiere** [comment]
Hi @tudorbarascu,

> For some reason, in the test the odd parameters are ignored. E.g. IN ("Country: \"name\" IN ( 'nowhere' , 'arctic' , 'anywhere' , 'eurasia', the nowhere and anywhere parameters would not work in the test. Although the request made for a normal server works, in tests.. the odd ones get ignored for some reason. I had to put bogus countries to bypass that.

Sorry, I don't understand what you mean. Can you reformulate please? Because the result of the test with `FILTER=Country: \"name\" IN ( 'nowhere' , 'arctic' , 'anywhere' , 'eurasia' )` seems OK with Travis, so I probably missed something...

Moreover I tested the same filter with a "real" server and the result looks good too.

> Also, I noticed that for WMS requests, the FILTER takes into account only the column name as it's in the data source, and not the QGIS column aliases. Is that how it should be?

Indeed. Do you know if it's regression? Anyway, I think it'd be a good thing to be able to use aliases in this case. I come back soon with a PR about that, I let you know.

And as usual, thank you for your tests :+1:!

**Comment by tudorbarascu** [comment]
@pblottiere Thanks for reviewing.

For example, if I use in a "real" server the GetMap request six country names that actually exist and are in the extent of the request I see all those countries in the request, as it should be. But in the python test, using the same request, only half of the countries appear. E.g. county name in (firstname, secondname etc.), I only get the second, forth and six named countries, all the odd ones are ignored.
At first I thought I made a wrong test but the parameters outputted from the test look alright.
Travis is green because the ``nowhere`` and ``anywhere`` names don't exist in the dataset so the request request is good in the test and in the "real" server as I added bogus country names  (e.g. in the ``FILTER=Country: \"name\" IN ( 'nowhere' , 'arctic' , 'anywhere' , 'eurasia' ), `` only arctic and eurasia are in the dataset.

About the aliases, I think they never worked.

**Comment by tudorbarascu** [comment]
@pblottiere gentle ping

**Comment by pblottiere** [comment]
Hi @tudorbarascu,

> But in the python test, using the same request, only half of the countries appear. E.g. county name in (firstname, secondname etc.), I only get the second, forth and six named countries, all the odd ones are ignored.

I didn't succeed in reproducing your issue. It seems to work fine on my side, so I created a new PR (https://github.com/qgis/QGIS/pull/6718) with another unit test which should fail according to your comment. Let's see what happens with Travis :).

>> Also, I noticed that for WMS requests, the FILTER takes into account only the column name as it's in the data source, and not the QGIS column aliases. Is that how it should be?
> Anyway, I think it'd be a good thing to be able to use aliases in this case. I come back soon with a PR

I was too optimistic. It's not so simple because the content of the `FILTER` parameter is directly interpreted by the underlying data provider.

**Comment by pblottiere** [comment]
> Let's see what happens with Travis :)

@tudorbarascu Travis is green https://github.com/qgis/QGIS/pull/6718

**Comment by tudorbarascu** [comment]
Yep.. I see that now everything works.
I'm sure I didn't dream cause I've spent several hours trying to see the culprit and I replicated it under travis + the local test.
Out of curiosity, I'll rebuild the branch as it is but probably meanwhile someone changed something elsewhere that fixes everything.
I've rebased this. Sorry for the noise.
I just noticed these days the value relations don't get solved by the server anymore ( https://issues.qgis.org/issues/18518 ). Do you know if there's an option I can toggle on for this and that I missed or it's a regression?

**Comment by pblottiere** [comment]
> Yep.. I see that now everything works.
> I've rebased this. Sorry for the noise.

@tudorbarascu No worries, what matters is that your issue is fixed!

> I just noticed these days the value relations don't get solved by the server anymore ( https://issues.qgis.org/issues/18518 ). Do you know if there's an option I can toggle on for this and that I missed or it's a regression?

Not that I know of. Do you think that you can reproduce your issue in a PR just like this one?

And thank you for these new tests!

**Comment by tudorbarascu** [comment]
@pblottiere Sure! I'll make a PR with failing tests.Thanks for everything.

**Pull request merged**
