### PR TITLE
[FEATURE] Search for options in config dialogs

### PR DESCRIPTION
**Pull request by 3nids**
This adds a search bar for QgsOptionDialogBase dialogs (main QGIS options, vector layer options, etc).

Will publish a video demo asap.

Still need a bit of polish.

* [ ] project properties
* [ ] search in combos?, tree/table widget (e.g. advanced settings)?

### CODE REVIEW

**Comment by Gustry** [comment]
It looks great, thanks. Is there something for the Advanced Settings Editor to look for a specific key ?

**Comment by NathanW2** [comment]
Oh nice! I was only thinking the other day that we need something like this.

**Comment by 3nids** [comment]
@Gustry not yet. I am not really sure about this one since there is the disclaimer in front. An idea would be to make it enabled/disabled with a checkbox.

**Comment by 3nids** [comment]
here is the screencast

anim

**Comment by nirvn** [comment]
@3nids , nice! I'm not sure the placement of the search box is that great but I can't think of a better place ATM :) 

What about having it located to the right of the [ Help ] button?

**Comment by NathanW2** [comment]
That is bloody perfect.  Great work!

For a style maybe set all non matching widgets to grey and leave matching
as normal.  Just an idea to try.

**Comment by 3nids** [comment]
a hidden goal is to implement QgsOptionDialogBase for drag and drop designer forms, so we can search for field names

**Comment by 3nids** [comment]
@nirvn not sure. I kind of prefer the top position since it's more visible. But no strong opinion here

**Comment by NathanW2** [comment]
I like it where it is currently.  I think it makes sense there.  That is
what PyCharm has and it's pretty handy.

**Comment by nirvn** [comment]
@DelazJ , @NathanW2 , all good then.  :)

**Comment by DelazJ** [comment]
@3nids really nice!! I neither see a better placement.
Going further, what about an implementation in the Help menu so that we can search through all the application menus/tools/(plugins?)? e.g. Firefox or Adobe Indesign have such a search widget.

**Comment by timlinux** [comment]
This is fantastic!!! Thanks @3nids

**Comment by 3nids** [comment]
merging as is fir further testing

**Pull request merged**
