### PR TITLE
Drag&Drop support for GeoPackage layers

### PR DESCRIPTION
**Pull request by cedi4155476**
DBManager extensions:
- Drag&Drop support for GeoPackage layers
- Add SpatiaLite/GeoPackage file connection per Drag&Drop and from context menu
- Remove DB connections (context menu)

### CODE REVIEW

**Comment by brushtyler** [comment]
After this commit dropping tables/layers/files into DBManager tree doesn't work anymore...
I'm able to just add new SQLite/Geopackage connection per d&d.

BTW I disagree that d&d is the right way to add a new connection:
- it works for Sqlite like database only
- it becomes unclear what's the expected behaviour when dropping a file into DBManager (i.e. importing the layer into a database or adding a new connection?).

**Comment by brushtyler** [comment]
@mhugent IMHO we should partially revert this commit:
- keeping the "add/remove connection from context menu" feature (even if add connection is available for SQLite/Geopackage only),
- dropping the "add connection per drag&drop" feature (inconsistent behaviour)

Furthermore:
- the `isgpkg()` method in SLConnector class doesn't do the job, it executes `SELECT HasGeoPackage()` which succeded whether SL is built with GeoPackage support (unlike `SELECT CheckGeoPackageMetaData()` which checks whether a db has a GeoPackage layout). https://www.gaia-gis.it/fossil/libspatialite/wiki?name=4.2.0+functions#8

**Comment by pka** [comment]
Hi Giuseppe,
great to see you back working on DBManager!
The trigger for this PR was https://hub.qgis.org/issues/12897. @cedi4155476  implemented a new "GPKG" driver first, but realized that integrating GPKG support into the SpatiaLite driver needs far less code.
I think that dropping GPGK and SpatiaLite files into DBManager is a big improvement over adding new DB connections. It's wasn't intentional to loose the drop functionality into existing connections. @cedi4155476 can fix that.

**Comment by gioman** [comment]
Hi Pirmin, please also note that adding geopackage layers to canvas from DB Manager (and QGIS browser) do not work, and that al tables are listed as geometryless.

**Comment by brushtyler** [comment]
@pka: Hi Pirmin, thanks! :) Ok, I understand your point. 
Using the SL backend/driver was the right move to just display the GPKG content within DBManager and load geopackages layers, but to really support GPKG we should write a new DBManager backend/driver:
- almost all the queries must be changed as SL and GPKG databases have a different layout (although very similar, i.e. geometry_columns and spatial_ref_sys tables).
- also capabilities are different (e.g. we cannot load a query as layer when database is GPKG since this feature is implemented within the SL provider).

It is something we can move in the future, anyway.

@cedi4155476: I've already fixed the drop functionality (easy fix, I'm going to push the commit ASAP) and few other issues. I hope you can check if GPKG support still works as expected after those commits.

**Comment by brushtyler** [comment]
I guess we should disable any kind of editing on GPKG databases from DBManager by now, do you agree?

**Comment by cedi4155476** [comment]
Yes I also think it would be better if editing the GPKG databases is disabled because I've never added something there and I doubt that everything will work.

**Comment by pka** [comment]
@brushtyler: @cedi4155476 didn't implement anything for QGIS browser. But DnD from DB Manager to canvas was a main feature: What exactly does not work?
Side note: Dropping to the layer tree or canvas adds the GPGK layer with OGR driver.

**Comment by brushtyler** [comment]
@pka: gioman is talking about adding the layer to canvas by right clicking on the table -> context menu "Add to canvas". It was fixed in commit 03916d549.

@cedi4155476, @gioman: Please, could you check if it works as expected (no regressions)?
The GPKG support must be improved in the future, but currently we allow to display data and vectors. It may be enough in this moment.

**Comment by brushtyler** [comment]
@gioman: Note that QGIS browser still doesn't support GPKG

**Comment by cedi4155476** [comment]
The new Connection context menu doesn't work. If you activate it, it just gives "TypeError: addConnectionActionSlot() argument after * must be a sequence, not QModelIndex" back.
But the DnD seems to work.

**Comment by brushtyler** [comment]
@cedi4155476: thanks. Fixed in 80a13e3852.

**Pull request merged**
