### PR TITLE
[processing] Fix saga natural neighbor parameters

### PR DESCRIPTION
**Pull request by jascase901**
I believe it fixes this issue.
https://issues.qgis.org/issues/16604

## Description
natural neighbor gridding would fail because the interface had changed from SIBSON=true to METHOD = Linear, Sibson,or Non-Sibson. 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
CC @gioman

**Comment by luipir** [comment]
@m-kuhn @jascase901 please wait for @gioman, he's is on holidays

**Comment by alexbruy** [comment]
Looks like this should go to the 2.18 branch, not master. For master fix please wait for #5021

**Comment by gioman** [comment]
@jascase901 the patch is good but must be applied to both master and as also 2.18. Moreover the modules in SAGA ltr seems to have more parameters, if would be good to add them too

```
Usage: saga_cmd grid_gridding 3 [-SHAPES <str>] [-FIELD <str>] [-TARGET_DEFINITION <str>] [-TARGET_USER_SIZE <double>] [-TARGET_USER_XMIN <double>] [-TARGET_USER_XMAX <double>] [-TARGET_USER_YMIN <double>] [-TARGET_USER_YMAX <double>] [-TARGET_USER_FITS <str>] [-TARGET_TEMPLATE <str>] [-TARGET_OUT_GRID <str>] [-METHOD <str>] [-WEIGHT <double>]
  -SHAPES:<str>                 Points
        Shapes (input)
  -FIELD:<str>                  Attribute
        Table field
  -TARGET_DEFINITION:<str>      Target Grid System
        Choice
        Available Choices:
        [0] user defined
        [1] grid or grid system
        Default: 0
  -TARGET_USER_SIZE:<double>    Cellsize
        Floating point
        Minimum: 0.000000
        Default: 1.000000
  -TARGET_USER_XMIN:<double>    Left
        Floating point
        Default: 0.000000
  -TARGET_USER_XMAX:<double>    Right
        Floating point
        Default: 100.000000
  -TARGET_USER_YMIN:<double>    Bottom
        Floating point
        Default: 0.000000
  -TARGET_USER_YMAX:<double>    Top
        Floating point
        Default: 100.000000
  -TARGET_USER_FITS:<str>       Fit
        Choice
        Available Choices:
        [0] nodes
        [1] cells
        Default: 0
  -TARGET_TEMPLATE:<str>        Target System
        Grid (optional input)
  -TARGET_OUT_GRID:<str>        Target Grid
        Grid (output)
  -METHOD:<str>                 Method
        Choice
        Available Choices:
        [0] Linear
        [1] Sibson
        [2] Non-Sibsonian
        Default: 1
  -WEIGHT:<double>              Minimum Weight
        Floating point
        Maximum: 0.000000
        Default: 0.000000

```

**Comment by jascase901** [comment]
@gioman 
>> the patch is good but must be applied to both master and as also 2.18

Should I also do a pull request to 2.18?

>> Moreover the modules in SAGA ltr seems to have more parameters, if would be good to add them too

Of those parameters in the help text the only two that were missing are WEIGHT and TARGET_TEMPLATE. It looks like a lot more because this line handles 4 parameters 

`Extent TARGET_USER_XMIN TARGET_USER_XMAX TARGET_USER_YMIN TARGET_USER_YMAX`


I added the WEIGHT parameter in the last commit, but I am not sure what to do with TARGET_TEMPLATE. Target template is an optional parameter and I couldn't figure out how to add those from the python code I was reading.

**Comment by jascase901** [comment]
Also this may be a different issue but I noticed the cell size defaults to 1 in the help but 100 in qgis

**Comment by gioman** [comment]
> Should I also do a pull request to 2.18?

yes



> I added the WEIGHT parameter in the last commit, but I am not sure what to do with TARGET_TEMPLATE. Target template is an optional parameter and I couldn't figure out how to add those from the python code I was reading.

to make a raster input optional just add "|True" in the description file, example:

ParameterRaster|TARGET_TEMPLATE|Target System|True



> Also this may be a different issue but I noticed the cell size defaults to 1 in the help but 100 in qgis

This is on purpose: 100 is a safer value for raster analysis. At 1 (meter) if the user had a large enough raster input and forgot to change the resolution then the run took forever to run.

**Comment by nyalldawson** [comment]
#6940 supersedes this by rebasing on master and adapting to 3.0 changes.

**Pull request closed without merging**
