### PR TITLE
[ms-windows][Installer] Update sidebar image of ms-windows installer

### PR DESCRIPTION
**Pull request by jonnyforestGIS**
## Description

The aim of this pull request is to replace the old QGIS symbol in the sidebar of Windows installer. I did the following actions:

- I update the image and colours based on Visual Style Guide: [QGIS Visual Style Guide](https://qgis.org/en/site/getinvolved/styleguide.html?highlight=guide%20style#trueno-fonts);
- Add SVG template to future changes;
- Keep the old sidebar with name
change

### CODE REVIEW

**Comment by nyalldawson** [comment]
Why don't we drop the text too? It looks unprofessional, and if someone is already **installing** qgis we don't need to "sell" it to them! 😆

**Comment by jonnyforestGIS** [comment]
Hi @nyalldawson 😆 . I just follow what we already have. 🤣 If you want I can change remove the text and use the logo and the name.

**Comment by jonnyforestGIS** [comment]
@nyalldawson  
sidelogomaster1

**Comment by nyalldawson** [comment]
That looks much better!

**Comment by nyalldawson** [comment]
@nirvn are you happy with this?

**Comment by nirvn** [comment]
yep, unquestionably better.

**Comment by NathanW2** [comment]
Nice work!

**Comment by nyalldawson** [comment]
Unrelated test failure - pg raster test (ping @elpaso)

**Comment by elpaso** [comment]
I'll have a look.

**Pull request merged**
