### PR TITLE
Make non progress reporting tasks have undefined bars instead of 0%

### PR DESCRIPTION
**Pull request by mbernasocchi**
## Description
This changes the behavior for  non progress reporting tasks to have an undefined bars instead of 0%

Before:
image 5
image 3

After:
image

image

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by mbernasocchi** [comment]
Hi @nyalldawson that is a very small issue but it is a nice addition to the task manager. What do you think about the single task case (image 3)? should that also be a non progressing bar? I couldn't figure out why it shows 0% instead.

**Comment by m-kuhn** [comment]
Makes sense, regarding https://github.com/qgis/QGIS/pull/7295/files#diff-768aa864c4dbe49ee26b8ddfe062125aR84

**Comment by nyalldawson** [comment]
Yeah, I'll look today and see if I can figure out the main widget

**Comment by mbernasocchi** [comment]
@nyalldawson cool thanks

**Pull request merged**
