### PR TITLE
Improve split lines with lines

### PR DESCRIPTION
**Pull request by bstroebl**
Hi Matthias,
I hope this is the final PR. :-) 
I created the output gml files from the memory layers created by processing with "save layer as"

### CODE REVIEW

**Comment by bstroebl** [comment]
I was thinking about making it an optional parameter but I would not like to leave it as it was (I discovered the problem when creating the tests: each result data set had an additional line with almost zero length) because the user will get results that may be false and because the errors are too small to discover on the canvas will be unaware of them. So I as a user I would expect to have a valid dataset afterwards.
But can we change parameters now? Remember the problems we ran into when changing Dissolve's parameters.
Why did the tests fail? Is it connected to me preparing the expected results like I did?

**Comment by m-kuhn** [comment]
I think that this cleanup step just hides issues introduced by some other problems with the algorithm (just guessing, I did not look into it) and that if possible the root cause should be fixed instead. Also, the the threshold length for removal probably depends on the used CRS, an arbitrary 6 digits threshold may not be optimal for every dataset.

**Comment by bstroebl** [comment]
Matthias, I agree with the threshold and the CRS. However would you expect anybody is interested in a line with a length less than 0.00001 units? But we could make that be e.g. 0.01 mm all the time (regardless of the CRS used). 
The underlying algorithm is the api function `splitGeometry`. You should investigate what happens there. My guess (into the blue) is that the problem could be connected with the line being interpolated between its nodes and a certain point on it may have an irrational number as coordinate. The "error" lines always happen at the lines.5 feature.

**Comment by m-kuhn** [comment]
> would you expect anybody is interested in a line with a length less than 0.00001 units?

I do not think it's our job to tell people what they should be interested in ;)

**Comment by bstroebl** [comment]
> I do not think it's our job to tell people what they should be interested in ;)

right, but this is far less than anything being measurable in the field (1mm is about the highest accuracy currently possible). Software and technical accuracy are one thing but in case of GIS they are connected with the reality being mapped. Still I would prefer a parameter (with a suitable default) but I am reluctant to introduce it now because I fear that I have to roll it back later on because someone's models don't run anymore.

**Comment by m-kuhn** [comment]
How would an optional parameter affect someones model more than a hardcoded black magic step?

**Comment by m-kuhn** [comment]
Tests fail because of the parameter names. The algorithm expects `INPUT_A` and `INPUT_B`, the test defines INPUT and INPUT2. Was that produced by the test tool in the processing history?

**Comment by bstroebl** [comment]
> How would an optional parameter affect someones model more than a hardcoded black magic step?

The parameter and the hardcoded step are not connected. You do not like the hardcoded black magic step (I do not like it either but I can accept it for the reasons given). The hardcoded step does not affect someones model at all (technically speaking). An additional parameter does, doesn't it? If you guarantee that if the parameter is optional old models (without this parameter) will still run, I am going to add it.

**Comment by bstroebl** [comment]
> Tests fail because of the parameter names. The algorithm expects INPUT_A and INPUT_B, the test defines INPUT and INPUT2. Was that produced by the test tool in the processing history?

my  fault, will fix it

**Comment by m-kuhn** [comment]
Can you do the second test on layer split with layer (instead of layer2 split with layer2). That would have the benefit that we check if null geometries are not a problem for the first and the second parameter.

**Comment by bstroebl** [comment]
> Can you do the second test on layer split with layer (instead of layer2 split with layer2). That would have the benefit that we check if null geometries are not a problem for the first and the second parameter.

I certainly can, but the lines in layer _lines_ do not intersect. The result would be identical with _lines_, I don't understand where you expect null geometries.

**Comment by m-kuhn** [comment]
Seems I forgot to add that to the lines dataset. Will update...

**Comment by bstroebl** [comment]
Ah, there should be a null geometry in lines? I did not check, anyways we have that in test 1

**Comment by m-kuhn** [comment]
* There should be, but there wasn't, fixing now.
 * Test one tests for null geoms as first parameter but not as second parameter
 * It seems the broken line actually is made up of two exactly identical points. That looks to me like a problem in the splitGeometry method indeed. I wonder why it only surfaces on this particular case.

**Comment by bstroebl** [comment]
if I recall correctly (from yesterday) the points seem identical (x/y coordinates) but the line has a length > 0 (using QgsGeometry.length()) , therefore I introduced the threshold because comparing to 0 (zero) did not filter it out.

> I wonder why it only surfaces on this particular case.

It appears in test case 2, too.

**Comment by m-kuhn** [comment]
I would still prefer to have another metric. Something like check if the resulting line has only two points which are equal.

E.g.

```
diff --git a/python/plugins/processing/algs/qgis/SplitLinesWithLines.py b/python/plugins/processing/algs/qgis/SplitLinesWithLines.py
index 3383247..47488fa 100644
--- a/python/plugins/processing/algs/qgis/SplitLinesWithLines.py
+++ b/python/plugins/processing/algs/qgis/SplitLinesWithLines.py
@@ -124,17 +124,15 @@ class SplitLinesWithLines(GeoAlgorithm):
                                 else:
                                     outLines.append(inGeom)
                             else:
-                                outLines.append(inGeom)
+                                if len(inGeom.asPolyline()) > 2 or inGeom.asPolyline()[0] != inGeom.asPolyline()[1]:
+                                    outLines.append(inGeom)
 
                         inLines = outLines
 
 
             for aLine in inLines:
-                if round(aLine.length(), 6) > 0:
-                    # sometimes splitting results in lines of almost zero lenght,
-                    # we filter out anything with a lenght of less than 0.00001
-                    outFeat.setGeometry(aLine)
-                    writer.addFeature(outFeat)
+                outFeat.setGeometry(aLine)
+                writer.addFeature(outFeat)
 
             progress.setPercentage(int(current * total))

```

**Comment by bstroebl** [comment]
`inGeom.asPolyline()[0] != inGeom.asPolyline()[1]`
does the trick!
Will recode

**Comment by m-kuhn** [comment]
I would also leave the point count check in place. This prevents from removing the line if the first two points of a longer line accidentally are equal.

**Comment by bstroebl** [comment]
Yes, I will, I meant by checking if the points are identical we need not use the `length` method which gives results != 0 although the points are identical (how many digits are considered?)

**Comment by m-kuhn** [comment]
Didn't check, it's something in geos, I remember seeing something like 10e-13...

**Comment by bstroebl** [comment]
Matthias,
have you updated lines.gml? If I run splitlineswithlines against the current version the expected result will differ from an updated version with null geometry, won't it?

**Comment by m-kuhn** [comment]
Done now.

Do you know that you can just push to an existing branch and pull
request? This way at the end of a PR, there is a nice audit trail.

On 03/03/2016 10:50 AM, bstroebl wrote:
>
> Matthias,
> have you updated lines.gml? If I run splitlineswithlines against the
> current version the expected result will differ from an updated
> version with null geometry, won't it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qgis/QGIS/pull/2861#issuecomment-191682603>.
>

-- 
Matthias Kuhn
OPENGIS.ch - https://www.opengis.ch
Spatial • (Q)GIS • PostGIS • Open Source

**Comment by bstroebl** [comment]
I was aware of the branch but not of the PR (well I used to know but somehow forgot about it:)
On the other hand I deleted the last commit with the tests to remake it, what happens if I delete a commit?

**Comment by m-kuhn** [comment]
you cannot just `git push` but need to force `git push -f` and it will be all fine for github :)
Just do this only on pull requests and never on public branches.

**Comment by bstroebl** [comment]
ok, will keep in mind and try next time :-)

**Pull request closed without merging**
