### PR TITLE
Change resolution parameter defaults to floats

### PR DESCRIPTION
**Pull request by anitagraser**
Previously, the GUI wouldn't allow to enter float values

### CODE REVIEW

**Comment by m-kuhn** [comment]
@anitagraser Which part of the application does this affect? Can you give instructions how it can be tested?

**Comment by m-kuhn** [comment]
... it looks quite trivial. If you think it's safe to merge, please say so.

**Comment by anitagraser** [comment]
I tested it on my Windows machine, I think it's safe to assume that the behavior of this change is not OS dependent. You can test simply by running the tool from the Processing toolbox and trying to enter float values.

**Comment by m-kuhn** [comment]
Thanks @anitagraser

For the future, it makes it much easier to review and assign if you give some context hints (like processing, grass, resampling) I guess you know what I mean looking at your awesome gis.se activity

**Comment by anitagraser** [comment]
Sure, you mean in the PR text? Because the file name quite clearly gives the Processing context at least.

**Comment by m-kuhn** [comment]
Yes, the PR text. Reviewing PR's is not a very rewarding job and it's always good if it's visible from the title in the queue already who could be responsible. Checking the filename is two more clicks ;)

**Comment by anitagraser** [comment]
Understood :)

**Pull request merged**
