### PR TITLE
[bugfix] File downloader for identify dialog hyperlinks

### PR DESCRIPTION
**Pull request by elpaso**
fixes #14703

Include C++ and Python tests

### CODE REVIEW

**Comment by elpaso** [comment]
This PR will be back and forward ported

**Comment by m-kuhn** [comment]
Is this a bugfix or a feature? New classes always make me think it's a feature but feel free to convince me of the opposite ;)

Anyway, re forward porting: do you think that could be done within the taskmanager in 3.0?

**Comment by elpaso** [comment]
@m-kuhn this actually falls in the gray zone, that's why I asked before starting to work: https://lists.osgeo.org/pipermail/qgis-developer/2016-October/045584.html

I've not yet looked at the new task work, it might be a good candidate for a more complex browser-like download-manager style.

**Comment by nyalldawson** [comment]
@elpaso can you have a look at the QgsNetworkContentFetcher class - I suspect it should either be used here by QgsFileDownloader or the two should be merged together.

**Comment by elpaso** [comment]
@nyalldawson I had a look to that class before starting yet another implementation but my class is more focused on downloading (big) files instead of returning content as a buffer/string.
The test use case was the download of huge lidar files from a GetFeatureInfo HTML hyperlink but of course this would also work for small files.

BTW, I think that for 3.0 this class could be used with your new amazing task manager.

**Comment by nyalldawson** [comment]
> @nyalldawson I had a look to that class before starting yet another implementation but my class is more focused on downloading (big) files instead of returning content as a buffer/string.

Isn't there anyway to address both use cases? I'm just concerned that we're ending up with duplicate code here (handling of redirects). I've made this mistake in the past - when I initially implemented QgsNetworkContentFetcher (incidentally, i HATE the name of that!) I was unaware of the existing QgsHttpTransaction class which also had redirect handling. Now QgsHttpTransaction is basically dead (buried away in server, broken in qt5 and with no unit tests), but for a long time we had two duplicate methods handling this in different ways and most likely with different bugs/missing bits. We've got a great opportunity here to make the one-awesome-downloader class which addresses both use cases and is soaked in unit tests :) 

I'd also rather see this kind of thing happen in core and have the gui component solely relay  information rather than have any of the redirect/response handling logic in it.

And yes - stuff like this has been in my mind all along with the task manager work. Shouldn't be too far off now...

**Comment by elpaso** [comment]
@nyalldawson I totally agree that a generic downloader class for both cases would be nice to have and I'll give a second look to the use cases of the fetcher class when porting to master and see if my class can be adapted to those, but I'd leave the codec and other transformations of the payload to the caller. Do you think that using a temporay file would do?

**Pull request merged**
