### PR TITLE
Add dbmanager svg

### PR DESCRIPTION
**Pull request by pkinglinz**
dbmanmager svg to replace png

### CODE REVIEW

**Comment by nirvn** [comment]
@pkinglinz , nice, thanks for keeping up the effort. I would only suggest to reduce the width of the actually glyph to be 22px instead of 24px. We usually leave a 1px padding around 24px x 24px icons in the main toolbar.

**Comment by pkinglinz** [comment]
@nyalldawson currently contains two svg as need one in images/themes/default to be able to use getThemeIcon() to load the svg, and the second inside dbmanager for the references in the metadata.txt and resources.qrc. however the icon is not appearing in the plugins menu, I assume this is because it is not a png? is there a way to change the reference the metadata.txt to reference the svg in images/themes/default

I was also getting a message about a missing oswlib but assume this has nothing to do with the changes and is due to my setup somehow

**Comment by pkinglinz** [comment]
thanks @nirvn I will make that change tonight

**Comment by nirvn** [comment]
@pkinglinz , you can compress your SVG icon using this online website: https://jakearchibald.github.io/svgomg/ -- it'll result in a smaller file size, essentially acting as a micro-optimization in icon loading speed 😄

**Comment by nirvn** [comment]
@pkinglinz , thanks for your contribution.

**Comment by pkinglinz** [comment]
thanks again @nirvn

**Comment by strk** [comment]
Hey @pkinglinz  since you're at it, would you be up to design an icon for the TopoViewer DBManager plugin ? :)

**Pull request merged**
