### PR TITLE
Add warning - fix 27633

### PR DESCRIPTION
**Pull request by Djedouas**
## Description

Fix #27633 with a warning, according to [comment](https://github.com/qgis/QGIS/pull/48674#issuecomment-1179291713) from #48674

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'm not certain that this fix or the one in https://github.com/qgis/QGIS/pull/48674 is correct -- should the warning be shown if one layer has Z/m values and the other doesn't? (Currently it will be). What about if one layer is line and the other is circularstring? (again, currently it will be). 

I think possible the comparison here should be using QgsWkbTypes::geometryType( ... ) instead.

**Comment by Djedouas** [comment]
> should the warning be shown if one layer has Z/m values and the other doesn't?

I think so.

That's why it's only a warning. If Z or M is on the input or on the overlay layer it can lead to different result, and the warning is here to notify the user and bring it to his attention, so he knows what's he doing. That's why the warning is verbose, giving the information of the 2 geometry types.

**Comment by Djedouas** [comment]
up?

**Comment by Djedouas** [comment]
@nyalldawson what do you think?

**Comment by Djedouas** [comment]
up

**Pull request closed without merging**
