### PR TITLE
Fix searching within function tags

### LINKED ISSUE #44433: When searching in functions, string_to_array is always returned
### What is the bug or the crash?

When searching the functions in an expression editor, `string_to_array` is always on the results regardless of the search string.

### Steps to reproduce the issue

1. Add a vector layer
2. Use *select by expression*
3. Use the functions' *search* field and type anything
4. *string_to_array* is in the results!

### Versions

3cd62b3cbb on Debian Bullseye

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by uclaros**
## Description
@nyalldawson thanks for the guidance! `fromWildcard` static method is qt6 only so I used the QString constructor while checking that a valid expression is typed so there are no issues while typing in stuff like `[0-9]`

Fixes #44433

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nirvn haven't we upgraded other wildcard uses elsewhere?

**Comment by nirvn** [comment]
@nyalldawson , I remember us updating QRegExp that used the `setPatternSyntax( QRegExp::Wildcard );` but cant remember stumbling on a proxy model setFilterWildcard() usage. We should pay particular attention to those then. The Qt 6 doc added this second paragraph to the function documentation:

> This method will reset the regular expression options but respect case sensitivity.

**Comment by agiudiceandrea** [comment]
@uclaros anyway, while `setFilterWildcard()` internally sets a QRegExp in Qt < 6 (and thus `filterRegExp()` should be used to retrieve the filter in Qt < 6), it sets a QRegularExpression in Qt >= 6 so `filterRegularExpression()` could be used in Qt >= 6 without issues.

See https://github.com/qt/qtbase/commit/eb349930eee1ca8f31415dd2269a70d3dfd76257#diff-35536aff6ab7668bdf538b65b5c8f5fa32e81e5405996434c2cc5f59205729f1L2827-R2645

So a simple `#if QT_VERSION < ...` to conditionally use filterRegExp() or filterRegularExpression() may be enough.

**Comment by uclaros** [comment]
@agiudiceandrea is there a reason why not to use `filterRegularExpression()` for both qt5 and qt6?

**Comment by uclaros** [comment]
I mean combined with `setFilterRegularExpression` instead of `setFilterWildcard`

**Comment by agiudiceandrea** [comment]
> is there a reason why not to use `filterRegularExpression()` for both qt5 and qt6?

No, I don't think so.

**Comment by uclaros** [comment]
Qt 5.12 is already the minimum required version, so that's not an issue.

**Review by nyalldawson — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
@uclaros it seem it doesn't work as expected: it only does whole-word searches and no function is listed when the search string is deleted.

Before (at e17862df):

https://user-images.githubusercontent.com/16253859/129610739-899c4da6-5cc9-4cac-997e-8bc02c5930d9.mp4

After (at 2ab7d33):

https://user-images.githubusercontent.com/16253859/129610762-a618a014-9f1f-491a-9070-7d5dc297190e.mp4

**Comment by agiudiceandrea** [comment]
> it seem it doesn't work as expected

Fixed now with https://github.com/qgis/QGIS/pull/44716.

**Comment by uclaros** [comment]
Thanks! This worked on my build so maybe some qt version quirks caused it.

**Pull request merged**
