### PR TITLE
Send QgsDebugMsg errors to std::cerr instead of qDebug 

### PR DESCRIPTION
**Pull request by nyalldawson**
Since QgsDebugMsg should ONLY be used for errors, if we send them to std::cerr then they'll get correct color formatting
in terminals (e.g. helping with debug output when running tests)

### CODE REVIEW

**Comment by m-kuhn** [comment]
> Since QgsDebugMsg should ONLY be used for errors, if we send them to std::cerr then they'll get correct color formatting in terminals (e.g. helping with debug output when running tests)

And anything that's not a warning (?) / error QgsDebugMsgLevel?

**Comment by nyalldawson** [comment]
@m-kuhn 
> And anything that's not a warning (?) / error QgsDebugMsgLevel?

That stays unchanged and goes to qDebug.

My thinking is:

- QgsDebugMsg (goes to level 1): this is for ERRORS ONLY, goes to std:err
- QgsDebugMsgLevel( level > 1): for debugging, not shown by default, goes to qDebug()
- QgsDebugMsgLevel( level == 0): very special corner case for non-error messages, goes to qDebug(), always shown. Reserved exclusively for EXTREMELY RARE corner cases like the useful startup non-error output.

(That's how the current PR does things)

**Comment by m-kuhn** [comment]
> @m-kuhn
> 
> > And anything that's not a warning (?) / error QgsDebugMsgLevel?
> 
> That stays unchanged and goes to qDebug.
> 
> My thinking is:
> 
> * QgsDebugMsg (goes to level 1): this is for ERRORS ONLY, goes to std:err
> * QgsDebugMsgLevel( level > 1): for debugging, not shown by default, goes to qDebug()
> * QgsDebugMsgLevel( level == 0): very special corner case for non-error messages, goes to qDebug(), always shown. Reserved exclusively for EXTREMELY RARE corner cases like the useful startup non-error output.
> 
> (That's how the current PR does things)

Can we rename QgsDebugMsg to QgsErrorMsg?

**Comment by nyalldawson** [comment]
@m-kuhn 

> Can we rename QgsDebugMsg to QgsErrorMsg?

**Comment by nyalldawson** [comment]
@m-kuhn 

> Can we rename QgsDebugMsg to QgsErrorMsg?

Ideally, but I think we're some way off that right now. There's still thousands of uses of QgsDebugMsg which aren't error related.

**Comment by m-kuhn** [comment]
Shouldn't that be fixed first?

**Pull request closed without merging**
