### PR TITLE
[FEATURE][needs-docs][processing] Add algorithm "Insert (append) Features to Layer"

### PR DESCRIPTION
**Pull request by gacarrillor**
## Description
This PR adds a QGIS Processing algorithm to insert/append/copy&paste features from one vector layer into another existing vector layer. It is adapted from the [Paste from clipboard function from qgisapp.cpp](https://github.com/qgis/QGIS/blob/master/src/app/qgisapp.cpp#L8255)

The algorithm is mainly intended to serve as a subsequent step for Refactor Fields algorithm, since with the latter you cannot append features to an existing layer, but need to create a temporary refactored layer and then copy from the temporary layer to your target layer.

This is a simple model to illustrate the main use case:

pr_insertfeaturestolayer

However, the algotithm might apply to other use cases as well, such as copy & pasting selected features to another layer with the same field structure.

The insert (append) algorithm is a missing piece in a conventional ETL flow within QGIS. This algorithm fulfills such need.

## Checklist
- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
Hello @gacarrillor, thanks for this, for sure this was missing in QGIS. Also note that  QEP about writing in an existing layer using processing : https://github.com/qgis/QGIS-Enhancement-Proposals/issues/89.
Also note that I've started working on QgsVectorLayerUpdater : https://github.com/qgis/QGIS/pull/6588. I will try to get time to finish it soon.

**Comment by nyalldawson** [comment]
I wonder if this should be closed in favour of @arnaud-morvan's more generic approach. What do you think @arnaud-morvan ?

**Comment by gacarrillor** [comment]
Hi @arnaud-morvan, that's definitely the way to go. Thanks for your work and kindness! I'll close this and see how in the meantime we can use my algorithm within my organization and with our stakeholders. In this PR, I just wanted to share such work with other QGIS users.

**Comment by arnaud-morvan** [comment]
Yes QEP 89 is really more generic, but it is a lot of work and I do not really know when I will get time to finish it.

**Comment by gacarrillor** [comment]
@arnaud-morvan then, what do you think about merging this PR and including it in QGIS v3.2 while QEP 89 is done?

I think of QGIS users and what would be more appropriate for them. The "Load" in ETL workflows is really a must-have tool.

**Comment by nyalldawson** [comment]
@gacarrillor 

The issue is that the moment we add an algorithm to qgis core, it becomes part of the stable api and we cannot remove it when the alternative approach is implemented, without breaking scripts and models (and I REALLY want to avoid the situation we had in 2.x->3.0 where model compatibility was broken due to removal of algorithms). 

This is really great work though, and I'd hate to see this PR closed without further action. Have you considered instead adding this algorithm to a plugin based provider and publishing through the QGIS plugin repository? I think that would be a good approach here, because it would make the algorithm easily available to users while avoid later issues when @arnaud-morvan's work is complete.

**Comment by gacarrillor** [comment]
@nyalldawson That makes sense, I'll share the algorithm in a QGIS plugin.

**Pull request closed without merging**
