### PR TITLE
Move the scale lock button from the QgsStatusBarScaleWidget to QgsStatusBarMagnifierWidget

### PR DESCRIPTION
**Pull request by borysiasty**
The Magnifier Widget (as well as the Rotation Widget) is something I always disable (unless I need them of course) in order to de-clutter the status bar. Most users don't need them, while free space on the status bar is precious on non hi-res screens.

However, the scale lock button is a part of the scale widget, so it stays visible if the magnifier widget is hidden. If you accidentally click it and change the magnification, it's hard to find the 100% again. This PR moves the button from the Scale widget to the magnification widget in order to hide them together.

Before:
zrzut_20181024_212402

After:  
zrzut_20181024_212457

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Looks reasonable to me -- I also think the lock applies more to the magnifier widget then the scale widget.

**Comment by 3nids** [comment]
I'm -0 here. It's pretty useful to work at a constant scale. Even if you don't allow magnification.

**Comment by borysiasty** [comment]
@3nids 
> I'm -0 here. It's pretty useful to work at a constant scale. Even if you don't allow magnification.

Do you mean it's useful to lock the zoom (scale and magnification) completely? In this case I see another solution: the button can stay, but the magnification is locked if the magnifier widget is hidden.

**Comment by 3nids** [comment]
yes that's what I was thinking.
But I would not enforce this if I am the only one.

**Comment by borysiasty** [comment]
No problem, I like the fact it's much smaller change, and also not controversial (it's just disabling a hidden widget). Let's see if I manage to do it later today.

**Comment by borysiasty** [comment]
Ah, it's not so trivial to lock the scale and magnification together. The button only tells QgsMapCanvas to use magnification instead of scale, and the magnification widget only displays what QgsMapCanvas reports.

So if there are no more supporters for this PR, we can leave it as it was (for myself, I always can hide the button by a startup script). As a long-term solution, I imagine embedding the magnification level somehow into the scale widget (the same with the tile scale slider).

**Comment by 3nids** [comment]
As said I have not a strong opinion here.
If we cannot anyway lock both scale and magnification, it does not make sense to show the lock and not the magnification widget (as one would still be able to zoom by magnification).
so for me, feel free to merge.

**Pull request merged**
