### PR TITLE
[Plugin installer][needs-docs] Display notifications as an icon rather than a text

### PR DESCRIPTION
**Pull request by borysiasty**
As we all know, the status bar became too crowded. Especially plugin installer notifications *There is a new plugin available* and *There is a plugin update available* eat definitely too much space. See also https://lists.osgeo.org/pipermail/qgis-user/2017-December/041246.html

This PR replaces texts with icons, while the original text goes to the tooltip.

Before:
zrzut_20171226_210333

After:
zrzut_20171226_211405

On both screenshots the window length is 1280 px. All labels become readable (at least in English).

### CODE REVIEW

**Comment by m-kuhn** [comment]
Love it

**Comment by m-kuhn** [comment]
Maybe put it to the right, next to log messages, so we have the "notification corner" there?

**Comment by borysiasty** [comment]
Good idea, it would look like that (there is no additional margin on the right - what you can see is just my window decoration stuff - a placeholder for the resize handle or so):
zrzut_20171226_233032


I'm falling asleep, will commit it in the morning.

**Comment by nirvn** [comment]
Big +1

**Comment by nyalldawson** [comment]
Good move! Can we make the icon grayscale, to fit the rest of the status bar?

**Comment by borysiasty** [comment]
Desaturated. It's a bit bigger than other icons in the status bar, but it seems to be too complex to scale it down without blur, so for now I'd leave it as is. Anyway, it's a notification, so it can be more prominent ;) 

zrzut_20171227_225615

**Comment by nyalldawson** [comment]
@borysiasty 

Protip: push it and if the icon is an issue, I'm sure it'll eventually raise @nirvn's ire enough for him to fix ;)

**Comment by borysiasty** [comment]
Hopefully one day @nirvn will forgive me ;)

**Comment by slarosa** [comment]
Sorry if I am asking just after merging, but why not put the hyperlink text on a message bar information widget?

**Comment by borysiasty** [comment]
@slarosa, at that stage I only decided to compact the existing label. Now we can discuss switching to the message bar, but my personal answer is -1: 

I prefer to avoid pushing more notifications to the message bar on QGIS startup. Depending on your specific situation, you may already see a few notifications at once (a project from older qgis, macros in project, defective plugin X, defective plugin Y, probably some connection problems etc) what I find a bit annoying.

**Comment by slarosa** [comment]
@borysiasty true, you're right! statusbar icon fits better.

**Pull request merged**
