### PR TITLE
GRASS 7 STRDS sampling

### PR DESCRIPTION
**Pull request by ninsbl**
"Detect R installation" was included in an earlier PR, no idea how to exclude that fromthis PR (I am no devloper)...

I hope the extremly useful t.rast.what module can make it into QGIS 2.14 (it is sucessfully tested!) and that the author, Sören Gebbert has no objections against shipping this tool from GRASS 7.1...

### CODE REVIEW

**Comment by ninsbl** [comment]
@blazek Hi Radim, would you mind having a look at this?... 

In my institute we have some time series data in GRASS, where the t.rast.what modules would make that data much more easily accessible to users which are less experienced with GRASS. And point sampling is a very common task. So these tools can have a significant impact on the perception of FOSS GIS here....

**Comment by blazek** [comment]
So we are talking  about ce330a2?

- it is dangerous to include the module with the same name in qgis. I would prefer to rename it in qgis to t.rast.what.qgis.py and add each qgm module twice:
<grass name="t.rast.what.coordinates.qgis" version_min="7.0" version_max="7.0"/>
<grass name="t.rast.what.coordinates" version_min="7.1"/> etc.
  or maybe better, if you can wait for GRASS 7.1 (2.14 is LTR and it will be built in future with GRASS 7.1), add just <grass name="t.rast.what.coordinates" version_min="7.1"/> etc. and don't include t.rast.what.qgis.py at all

- if you decide to include t.rast.what.qgis.py, please indent first with scripts/prepare-commit.sh otherwise qgis_indentation test fails and Travis does not pass

- please separate the changes related to GRASS plugin (ce330a2) to an independent pull request, e.g. make a new clean branch from master and merge and modify ce330a2 in it and then create new pull request.

**Comment by ninsbl** [comment]
Thanks, I shall try that!

**Comment by ninsbl** [comment]
Replaced by: #3164

**Pull request closed without merging**
