### PR TITLE
enable custom help in python expressions

### PR DESCRIPTION
**Pull request by Gustry**
## Description

Plugins which are providing their own expressions will be able to give a custom help. This will be mainly used for translations in our case:

```
help_do_something = tr('Some translated help')

@qgsfunction(
    args='auto', group='My plugin', usesGeometry=False, referencedColumns=[], helpText=help_do_something)
def do_something(feature, parent):
    return 'foo'
```

If it's OK, I will backport this to 2.18

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

Work for DFAT
CC @timlinux

### CODE REVIEW

**Comment by m-kuhn** [comment]
Looks good to me,
Can you add or adapt a unit test for this?

Backporting sounds fine to me, it's an edge case but trivial enough

**Comment by Gustry** [comment]
Done @m-kuhn thanks for the review.

I just noticed I'm having issues running python tests in Pycharm. Is there some docs? I found only about CTests https://www.qgis.org/en/site/getinvolved/development/qgisdevelopersguide/unittesting.html
I got some:
```
src/core/qgsmessagelog.cpp: 33: (logMessage) [0ms] 2017-08-23T09:52:41 Python warning[1] warning:/usr/local/lib/python3.6/site-packages/qgis/core/__init__.py:113: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args = inspect.getargspec(function).args

traceback:  File "/Applications/PyCharm.app/Contents/helpers/pycharm/_jb_unittest_runner.py", line 35, in <module>
    main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 148, in createTests
    self.module)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/etienne/dev/cpp/QGIS/tests/src/python/test_qgsexpression.py", line 23, in <module>
    class TestQgsExpressionCustomFunctions(unittest.TestCase):
  File "/Users/etienne/dev/cpp/QGIS/tests/src/python/test_qgsexpression.py", line 30, in TestQgsExpressionCustomFunctions
    @qgsfunction(args="auto", group='testing', register=False)
  File "/usr/local/lib/python3.6/site-packages/qgis/core/__init__.py", line 158, in wrapper
    return register_function(func, args, group, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/qgis/core/__init__.py", line 113, in register_function
    args = inspect.getargspec(function).args
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 1068, in getargspec
    DeprecationWarning, stacklevel=2)

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/qgis/utils.py", line 196, in qgis_excepthook
    in_main_thread = QThread.currentThread() == QgsApplication.instance().thread()
AttributeError: 'NoneType' object has no attribute 'thread'

Original exception was:
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/_jb_unittest_runner.py", line 35, in <module>
    main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 141, in parseArgs
    self.createTests()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 148, in createTests
    self.module)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 219, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 219, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 213, in loadTestsFromName
    raise TypeError("don't know how to make test from: %s" % obj)
TypeError: don't know how to make test from: <qgis.core.register_function.<locals>.QgsExpressionFunction object at 0x109db31f8>

Process finished with exit code 1
Empty test suite.
```

**Comment by m-kuhn** [comment]
I managed to run them with configuring the test run environment with some additional env variables but never documented this completely.

**Comment by m-kuhn** [comment]
Thanks

**Pull request merged**
