### PR TITLE
[gui] refresh selection-related icons

### PR DESCRIPTION
**Pull request by nirvn**
A picture worth a thousand words (upper section is current master, lower section is showing this PR):
before-after

This PR vectorizes and refresh a number of toolbar icons, mostly to do with selection-related actions:
- The use of dotted and solid border lines has been standardized, whereas a dotted line should now only be seen in icons when representing a mouse movement
- The select by {rectangle, polygon, freehand, circle} icons have been refreshed to insure elements' colors and sizes are identical, as well as to make those better fit with the rest of the theme
- The deselect all icon has been updated and is now the same for the main window and the attribute table window
- The select all icon has been re-done to better fit in the overall theme; in the process, the cursor symbol removed as this action was not involving any mouse interaction
- The invert selection logo has also been re-created
- The attribute table's reload and filter icons have been changed to use the ones found on the main window

### CODE REVIEW

**Comment by nirvn** [comment]
Changes highlighted:
changes

**Comment by nyalldawson** [comment]
Fantastic work - I'll merge as soon as Travis gives the green light

**Comment by nyalldawson** [comment]
@nirvn This looks fantastic. Any chance you could update the composer select action icons to suit? Eg the old invert icon is used there, no select all icon, etc.

**Comment by nirvn** [comment]
@nyalldawson good catch; here it is https://github.com/nirvn/QGIS/commit/3ab899515fc2a71cfd43d385c8794fbbd5f85b06 

Can you cherry pick this, or prefer to go down the PR road?

**Comment by nyalldawson** [comment]
@nirvn done!

**Pull request merged**
