### PR TITLE
[FEATURE] Export vector layer with "human-readable" values from edit widgets

### PR DESCRIPTION
**Pull request by rouault**
This PR add the capability discussed in https://lists.osgeo.org/pipermail/qgis-developer/2016-April/042220.html to offer to the user an option to export the display value of some columns (coming typically from a value reference or reference relation widget) instead of the raw value.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@rouault 

A downside to this approach is that the representValue is only accessible to GUI/APP. Ie, we can't do nice things like automatically format the values in composer attribute tables, since that's in core. 

Any chance we can get this functionality moved up to reside in QgsVectorLayer so that it's more widely usable?

**Comment by rouault** [comment]
> Any chance we can get this functionality moved up to reside in QgsVectorLayer so that it's more widely usable?

I can't see how to do that given that QgsEditorWidgetRegistry and QgsEditorWidgetFactory are in gui.

**Comment by nyalldawson** [comment]
(Thinking out loud)... What about it:
- QgsVectorLayer maintains a list of FieldValueConverters for its fields
- QgsVectorLayer gets a `representativeValue( const QVariant& value, int fieldIdx )` function, which by default returns the value untouched if no FieldValueConverter is set for that field.
- The FieldValueConverter is set for a field automatically when its editor widget is set
Would that work?

Some other potential use cases which jump to mind:

- the "merge attributes of selected features" dialog currently uses a table of editor widgets as a workaround to show value relations, etc. But these widgets are effectively read only - they are editable, but the changes are ignored. Instead of a table of widgets all that really should be shown is a table of read-only text values, using the representative value.
- showing the representative value in the identify results panel rather than the raw value

(I'm sure there's *lots* more,

**Comment by rouault** [comment]
> The FieldValueConverter is set for a field automatically when its editor widget is set Would that work?

Maybe I've not understood well your idea, but I don't see how that would work. The editor widget is set to the layer with QgsEditFormConfig::setWidgetType( int fieldIdx, const QString& widgetType ). So it is really a string. As you cannot call from core QgsEditorWidgetRegistry::factory(const QString& widgetId), you're stuck to create a converter.

The gist of the convertion is done with just:
```
QString QgisAppFieldValueConverter::convert( int idx, const QVariant& value )
{
  QgsEditorWidgetFactory *factory = QgsEditorWidgetRegistry::instance()->factory( mLayer->editFormConfig()->widgetType( idx ) );
  if ( factory )
  {
    QgsEditorWidgetConfig cfg( mLayer->editFormConfig()->widgetConfig( idx ) );
    QString stringValue( factory->representValue( mLayer, idx, cfg, QVariant(), value ) );
    return stringValue;
  }
  return value.toString();
}
```
So perhaps moving that to a re-usable utility function somewhere in gui ? Potentially a static method of QgsEditorWidgetRegistry :  QString representativeValue( QgsVectorLayer* layer, const QVariant& value, int fieldIdx )

**Comment by nyalldawson** [comment]
> Maybe I've not understood well your idea, but I don't see how that would work. The editor widget is set to the layer with QgsEditFormConfig::setWidgetType( int fieldIdx, const QString& widgetType ). So it is really a string. As you cannot call from core QgsEditorWidgetRegistry::factory(const QString& widgetId), you're stuck to create a converter.

Hmmm... you're right, I'd missed something. @m-kuhn any ideas here?

> So perhaps moving that to a re-usable utility function somewhere in gui ? Potentially a static method of QgsEditorWidgetRegistry : QString representativeValue( QgsVectorLayer* layer, const QVariant& value, int fieldIdx )

Except that there's already one concrete use case where we need this in core (composer attribute tables), and I'd imagine there's probably a lot more.

For this reason I **really** don't want to see this functionality inaccessible to core.

**Comment by m-kuhn** [comment]
The point is that we are really mixing core and gui things here:

 * fields are a core concept
 * widgets are a gui concept

The part of the widget implementation which is responsible for converting to display representation should actually be moved to core. This can be done in a utility method which has knowledge about the widget types we ship with stock QGIS and their configuration. The downside of this is that it will not be able to handle 3rd party widgets (registering custom widgets is allowed - in gui: QgsEditorWidgetRegistry).

The alternative would be to configure the display string separately from the widget. E.g. an expression (which the widget can automatically set when it's being configured) but can also live by itself in non-gui apps. `QgsField::displayString()` could then make use of this.

**Comment by 3nids** [comment]
Sorry to jump that late in the conversation, but why not using joins for this?

Or is there another use case than the value relation or relation reference? I can't think of another one now.

**Comment by m-kuhn** [comment]
ValueMap is another one

**Comment by m-kuhn** [comment]
@rouault 

> Maybe I've not understood well your idea, but I don't see how that would work. The editor widget is set to the layer with QgsEditFormConfig::setWidgetType( int fieldIdx, const QString& widgetType ). So it is really a string.

You are right that it's not possible to automatically do this from within core.
Instead I guess that will need to be done in two places:

 * In the vector layer properties when the widget configuration is changed.
 * Fixup pre-2.16 project with a new `QgsProjectFileTransform` converter.

**Comment by rouault** [comment]
Hum, I'm afraid I'm lost in the suggestions and am probably not in the best position to implement them (I don't see why project format would be impacted in particular). They look like a bit broader issue than this PR actually tries to solve and I don't think that  any improvements in that area would impact significantly the code of this PR because I guess they would maintain the existing converter API. So can we decide if we are OK with this PR as it is currently ?

**Comment by m-kuhn** [comment]
> I don't see why project format would be impacted in particular

So far we save the widget in the project and deduce the displayed value from this. With the proposed change the display rule will be independent from the widget and hence saved separately. To update old projects gracefully the display rule needs to be estimated from the current approach.

------------------------

The converter approach is a good and flexible idea.
At the moment it looks to me that it is artificially limited in its possibilities:

 * It does not allow any other data type than string (could be easily fixed with a new method to determine the type of an index)
 * It does not allow appending extra fields as far as I can see. This prevents from adding things like a new autoincrement field. (Please correct me if this is wrong)

What do you think about these suggestions? I think with these implemented, it will really have an advantage over the other approach.

**Comment by rouault** [comment]
> With the proposed change the display rule will be independent from the widget and hence saved separately

OK, got it, but that implies the display rule can be expressed as an expression

> It does not allow any other data type than string (could be easily fixed with a new method to determine the type of an index)

Yes, that can be improved. Currently the widget converters only return strings (or at least we don't have a way to know), hence the default to string. I'll extend that

> It does not allow appending extra fields as far as I can see

Yes, but that's no longer a FieldValueConverter at that point if we deal with extra fields ;-) That would probably be deserve a new argument in writeAsVectorFormat() to describe the new field, and in a """FieldValueComputer""" interface where we possibly pass the whole feature.

**Comment by rouault** [comment]
@m-kuhn Does that look ready to merge for you with latest a123859feebc05f03b58699466ee205637bb5520 ?

**Comment by m-kuhn** [comment]
I'm still a bit confused by the params `attributesAsDisplayValues` and `fieldConverter`. The first one is very precise in its meaning (values will be exported as their displayed values) while the second one has a generic meaning (convert fields before saving).

The first one, while specified on a `core` method depends on a very specific `app` converter and hence is meaningless if used outside of the desktop application scope when the core library is used on its own.

I.e. I think it would be much cleaner to move all the logic from `QgsVectorFileWriter` to `FieldValueConverter` e.g. with a new method like `bool covertFieldValue( int idx )`. This would really allow other people to write their own `FieldValueConverter`'s without modifying `QgsVectorFileWriter`.

**Comment by rouault** [comment]
@m-kuhn Your suggestion indeeds make the code clearer and much simpler in QgsVectorFileWriter. I chose to just let the 2 methods in FieldValueConverter. The test to know if a field must be converted or not is better done by the implementation of the interface, and regarding naming there could have been some confusion between the method that indicates if the field must be converted and the converting method. Note: the PR failure is a network issue. Tests pass in my Travis account : https://travis-ci.org/rouault/Quantum-GIS/builds/129962204

**Comment by m-kuhn** [comment]
It looks good to me now.

**Pull request merged**
