### PR TITLE
Add ACCEPT_USE_OF_DEPRECATED_PROJ_API_H macro for proj_api.h to work …

### PR DESCRIPTION
**Pull request by fjperini**
also necessary in 3.6.1

### CODE REVIEW

**Comment by nyalldawson** [comment]
@fjperini when is this needed? Master builds ok for me on proj v6.

**Comment by fjperini** [comment]
@nyalldawson I needed to add those lines in macos to build 3.6.1

**Comment by nyalldawson** [comment]
Try a clean build -- they shouldn't be required, and aren't desired (I've been working through and removing all use of deprecated proj api, so I'm dead against new usage being introduced)

**Comment by fjperini** [comment]
When I built  (branch: release-3_6 / commit: 289f1372380baa5707c792316bc1356508098de8) it I did it with a clean installation, and it failed.

Perhaps recent changes no longer require it.

**Comment by nyalldawson** [comment]
Ah - it's because https://github.com/qgis/QGIS/commit/2a6629ef56946e3ee54f81571350c7a6b94e6339 and  https://github.com/qgis/QGIS/commit/a03658663f78437add03b5622858b1470e37cfe3 need backporting to 3.6

**Comment by 3nids** [comment]
done in #9702

**Comment by 3nids** [comment]
merged in 3.6.
this should be good now

**Pull request closed without merging**
