### PR TITLE
Correctly sort browser items

### PR DESCRIPTION
**Pull request by nyalldawson**
Implements a sort key for browser items, allowing them to be correctly sorted.

Without this the sort order for files in directories is random. I've also implemented @borysiasty 's fix from #5855 here too.

Fixes #17591

### CODE REVIEW

**Comment by borysiasty** [comment]
Nice! 

My only concern is the alphabetical order is even more random in terms of provider importance ;) Personally I'd like to have GeoPackage more prominent than the preceding ArcGIS, DB2 and even GeoNode. But an arbitrary imposed order may raise more problems than benefits, so I see two future improvements:

1. short-mid term: Extend the "Hide from browser" function for all top-level items
2. mid-long term: Allow drag'n'drop reordering.

**Review by elpaso — APPROVED** [review]
Now we can control the ordering which is good! 
But I agree that we should set a more sensible order for the root provider items.

**Comment by nyalldawson** [comment]
I debated this too... But in the end, isn't alphabetical a lot less random then any order we decide? At least for most users, an alphabetical list is easier to locate items in then an arbitrarily defined "importance" ordering.

**Comment by borysiasty** [comment]
Yes, it's why I said it may raise more problems than benefits. Personally I'd prefer:
1. Pull your PR now
2. Enable the possibility to hide any items soon (seems easy to do)
3. Implement drag'n'drop some day

**Comment by nirvn** [comment]
+1 for alphabetical on the short term, and +1 for drag'n drop re-ordering to leave users in control as a long term solution :)

**Comment by nyalldawson** [comment]
Ok, thanks!

**Pull request merged**
