### PR TITLE
Move AutoTransaction setting to project properties

### PR DESCRIPTION
**Pull request by m-kuhn**
Was in global app settings

### CODE REVIEW

**Comment by 3nids** [comment]
CMakeFiles/qgis_core.dir/qgsproject.cpp.o: In function `QgsProject::addToTransactionGroups(QList<QgsMapLayer*>)':
    qgsproject.cpp:(.text+0x72e8): undefined reference to `QgsProject::autoTransaction() const'
    collect2: error: ld returned 1 exit status
    src/core/CMakeFiles/qgis_core.dir/build.make:12304: recipe for target 'output/lib/libqgis_core.so.2.15.0' failed
    make[2]: *** [output/lib/libqgis_core.so.2.15.0] Error 1
    CMakeFiles/Makefile2:208: recipe for target 'src/core/CMakeFiles/qgis_core.dir/all' failed
    make[1]: *** [src/core/CMakeFiles/qgis_core.dir/all] Error 2
    Makefile:149: recipe for target 'all' failed
    make: *** [all] Error 2

`autoTransaction()` is not defined in `QgsProject` code

**Comment by m-kuhn** [comment]
@3nids sorry, rebase problem.
Should be fixed now

**Comment by 3nids** [comment]
this seems to work as expected, good job!

**Comment by m-kuhn** [comment]
Thanks @3nids

On 04/06/2016 12:05 PM, Denis Rouzaud wrote:
>
> this seems to work as expected, good job!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/qgis/QGIS/pull/2975#issuecomment-206280407>
>

-- 
Matthias Kuhn
OPENGIS.ch - https://www.opengis.ch
Spatial • (Q)GIS • PostGIS • Open Source

**Pull request closed without merging**
