### PR TITLE
Keep Metadata proccessing algorithm

### PR DESCRIPTION
**Pull request by matjash**
## Description
Adding new processing algorithm Keep Metadata.
This tool allows you to copy metadata from a source layer to a target layer. Metadata includes history, abstract, title, keywords... Optionally, it also copies symbology from the source layer to the target layer.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Hi @matjash ! Thanks for this contribution!

The policy now is that processing algorithms should be written in C++ instead of python. Are you able to port this?

**Comment by matjash** [comment]
So the ones that are written in python (qgis\python\plugins\processing\algs\qgis) are just waiting to be ported?
It is fairly simple algorithm, so maybe I could port it. But I am clueless how to integrate (compile?) it into qgis, to try if it would work. It would probably take me days for what I imagine should be an hour task. If you think its even worth it, i can try. Are there any simple enough guidelines?

**Comment by nyalldawson** [comment]
> So the ones that are written in python (qgis\python\plugins\processing\algs\qgis) are just waiting to be ported?

Exactly. Initially they were all python, we are aiming to move them all to c++. There's concrete speed, stability, and ease of maintenance reasons behind this move. 

> It is fairly simple algorithm, so maybe I could port it. But I am clueless how to integrate (compile?) it into qgis, to try if it would work. It would probably take me days for what I imagine should be an hour task. If you think its even worth it, i can try. Are there any simple enough guidelines?

Have a look at https://github.com/qgis/QGIS/pull/59332/commits/cfb9b8b21901c3ef790f260d5b3972ea0011bcee . That should give a good template you can copy and paste to handle the C++ build-ey things. The actual algorithm code will look quite similar to the python version.

Just reach out if you need further assistance !

**Comment by alexbruy** [comment]
Superseded by #59411.

**Comment by nyalldawson** [comment]
@matjash @alexbruy did the C++ port in https://github.com/qgis/QGIS/pull/59411. Thanks for the inspiration! 

If you want to give a shot at a C++ alg, there's some ideas in https://github.com/qgis/QGIS/pull/59411 . 👍

**Comment by matjash** [comment]
Great! It would take me ages to figure this out. Maybe for next idea :)

**Pull request closed without merging**
