### PR TITLE
Require python 3 and qt5

### PR DESCRIPTION
**Pull request by nyalldawson**
I think it's time to call it a day for Qt4. This PR makes Qt >= 5.5 and Python 3 mandatory.

Here's the bad news:
- ~~ArcGIS providers are disabled since they have not been ported to Qt5.~~ fixed by @manisandro 
- Some tests are disabled on Travis. Here's why:
  -  QgsServer was crashing on exit because it wasn't correctly exiting QgsApplication, which triggers a segfault in qsqldatabase because the auth manager hasn't been deleted. The QSqlDatabase crash is
    new in qt5, but qt's solution is that databases should be gracefully closed before exit. Adding a sQgsApplication->exitQgis() to ~QgsServer() avoids the crash, and gets the server access control test
    passing, but then it causes many crashes in tests like test_qgs_server.py test_multiple_servers (since we exit qgis multiple times). I can't think of a graceful way to handle this. Apart from testing I can't see why people would be creating QgsServer objects from python, so I've left the exitQgis in ~QgsServer()
    and have just blacklisted test_qgs_server.py.
  - The tests which rely on qgis_wrapped_server fail. This affects test_qgsserver_wfts.py and test_offline_editing_wfs.py. These tests should be ported over to use the same process as the label server tests (ie qgis_local_server.py), since that's more robust (ie doesn't expect port 8081 to be free) and cross platform friendly.....
  - .... expect that it's broken on python 3. I can't figure this one out. It seems to me that the process created at qgis_local_server.py:82 just continually crashes for some reason. I find it really hard to diagnose this - I'm not sure how to debug crashes which only occur through cgi.
  - the test which creates a local server - QgsComposerPicture is failing because the local server is not
    responding after the first request. My suspicion is something to do with http 1.1 and keep alives and the connection not being released so that the python server can server the next request. But I can't track
    whether this is a python 3 change or qt5 change which is causing it and how to fix.
  - there's also the tests which fail because of the infamous QVariant rounding bug on Qt < 5.7. Nothing we can do here except blacklist these and wait till we get 5.7 available on Travis.
  - OSX Travis builds are disabled. No big issue here - they've been broken for a long time because the required dependencies aren't available on Travis. Moving to Qt5 should make this easier to fix anyway, since it's actually supported and maintained by the homebrew community (unlike qt4)
- the good news: Qt5! Python3! No more living in the dark ages!

Why do I think this should be merged now? Well....
- work on qt5 transitition has stagnated a bit recently, because no one has been able to (or has the time) to fix these remaining issues, or because trying to fix them in a way which doesn't break Qt4/python2 is just too much work
- @m-kuhn and @jef-n have done fantastic work so far in preparing us for the transition and it should now be up to the wider community to diagnose and fix the remaining qt5 issues (especially these server related issues/Arc providers)

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson big +1 for me. The sooner this happens, the better.

**Comment by NathanW2** [comment]
+1 Sometimes you just have to rip off the band aid

On Tue, Sep 20, 2016 at 11:15 AM, Mathieu Pellerin <notifications@github.com

**Comment by wonder-sk** [comment]
Nice nice!

For QgsHttpTransaction we could even remove it from core library altogether (it is not used within QGIS app) and only leave it in QGIS server code. It is an ancient piece of API and it enforces synchronous HTTP requests (with active waiting) which is IMHO completely wrong.

**Comment by m-kuhn** [comment]
Good move, this should get some more people to move their build chain to Qt5 and discover additional issues.

CC @dakcarto (for mac os x builds)
CC @manisandro (for arcgis providers)

**Comment by jef-n** [comment]
Debian jessie has Qt5 5.3.2 (stretch 5.6.1).  Do we need Qt5 5.5?

**Comment by manisandro** [comment]
I'll look at having the ArcGIS rest port finished by next week.

**Comment by nyalldawson** [comment]
> Debian jessie has Qt5 5.3.2 (stretch 5.6.1). Do we need Qt5 5.5?

I'm not sure - i vaguely recall some reason for targeting this version but can't anything pertinent in the release notes. My question would be whether Debian stable users should/would/can expect to be using anything but the LTR release anyway..?

**Comment by jef-n** [comment]
At least they could expect packages for stable from qgis.org for years.

**Comment by m-kuhn** [comment]
Is there no ppa with a newer Qt5 version?

**Comment by jef-n** [comment]
Not that I know - and I'd expect all sorts of problems using a package like Qt that has myriads of reverse dependencies from a third party repository.

**Comment by m-kuhn** [comment]
We can allow compiling with anything newer than 5.0 but recommend Qt >= 5.7.
And revisit this topic whenever someone wants to use a method that's only available in a newer Qt version.

**Comment by 3nids** [comment]
Can't we make it 5.3 if it's the requirement?
I can't recall but I saw a few things useful in 5.2.

**Comment by nyalldawson** [comment]
Ok so 5.0? 5.3? I'll update this PR to suit.

Fingers crossed flatpak or snappy take off and we can set more up to date minimums in future...

**Comment by nyalldawson** [comment]
Ok - QgsHttpTransaction has been shuffled off to server.

**Comment by nyalldawson** [comment]
Actually can we go 5.3 minimum? I really wanted to use http://doc.qt.io/qt-5/qcolor.html#qPremultiply and http://doc.qt.io/qt-5/qcolor.html#qUnpremultiply which were introduced in 5.3. See https://github.com/qgis/qgis3.0_api/issues/32

**Comment by jef-n** [comment]
Hm, I thought jessie was the eldest we still build for - but trusty (LTR, EOL April 2019) is even at 5.2.   Couldn't we just use internal versions of qPremultiply and qUnpremultiply for Qt < 5.3?

**Comment by manisandro** [comment]
The ArcGIS provider Qt5 port was actually pretty trivial thanks to `QJsonObject::toVariantMap`, I've got the commit ready here [1] for as soon as this PR is merged.

[1] https://github.com/manisandro/QGIS/commit/8febcd1afb72368dcf73650fbfba84d87b480d5f

**Comment by nyalldawson** [comment]
@manisandro - fantastic! I've pulled your commit into this branch

**Comment by NathanW2** [comment]
Nice work.  Had to be done at some stage in the end so better to do it
early and we can resolve issues as we go.

**Comment by nyalldawson** [comment]
Ok, I've dropped the minimum Qt to 5.2 and restored the ifdefs which where present for > 5.2. I've merged for wider testing and to push this along.

**Comment by m-kuhn** [comment]
Thanks @nyalldawson, @manisandro and others helping with this!

**Comment by nyalldawson** [comment]
@m-kuhn and to you! (x1000!)

**Comment by elpaso** [comment]
@nyalldawson, a part for testing, that was the main reason why the bindings were written in the first place, there are some use cases for `QgsServer` instances in python in standalone scripts that can dynamically configure and even create server plugins and filters.
About using `QgsServer` in the server tests: the test server based on QgsServer` is just a few simple straightforward lines: very easy to understand and to maintain if compared with the old local server code.
What is the problem for port 8081 free? The port number can be configured and changed if necessary.

**Comment by elpaso** [comment]
@nyalldawson  I see your point in `test_multiple_servers` (if you meant that you don't see a use case for that I agree), I think that making the server a singleton would make sense. @mhugent what's your feeling about that?

**Comment by nyalldawson** [comment]
@elpaso what about if the static QgsApplication was removed from QgsServer, and instead QgsServer has a compulsory QgsApplication* in its constructor? Then a single application would be created before any servers and we could handle multiple concurrent QgsServer instances again?

**Comment by elpaso** [comment]
@nyalldawson I cannot really think of a use case for concurrent servers in the same script... all processing happens on `handle_request()` and there is no persistence in the class (as in any server since the web is idempotent in its essence). Multi-treading/processing would be handled by the web server tier in any case. But I'd be in favour of removing the static application (that is causing a lot of headaches). What would be the standard way for a standalone server in that case?
Something like the following?
```
from qgis.core import QgsApplication
QgsApplication.setPrefixPath("/usr", True)
qgs = QgsApplication(sys.argv, False)
qgs.initQgis()

server = QgsServer(qgs)
...
```

**Comment by nyalldawson** [comment]
Yes, that's exactly what I had in mind. Then it's up to the dev to pick when to gracefully exit the QgsApplication in their script. I don't particularly like having to manually delete the server to gracefully exit.

**Comment by m-kuhn** [comment]
Or instead have the server expect that there's a usable QgsApplication around.

Just like QWidgets do:

```
>>> from PyQt5.QtWidgets import QWidget
>>> QWidget()
QWidget: Must construct a QApplication before a QWidget
Aborted (core dumped)
```

**Pull request merged**
