### PR TITLE
[processing] restore and improve lines to pol / pol to lines algs

### PR DESCRIPTION
**Pull request by nirvn**
## Description
@nyalldawson , some more.

Note, I've improved the polygons to lines algorithm by having the algorithm return multi linestring features, which keeps association between multipart polygons (or polygons with rings). If users need a non-multi linestring output, multi to single part alg can be used.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Port looks good - you're on fire!

One thing I'm thinking - both these algs rely on the old asMultiPolyline/asPolyline/fromPolygon/methods. As well as being inefficient, they will also drop any Z/M/curves from the geometries. I think it would be nice for us to try to fix all possible algs to correctly handle z/m/curves for 3.0.

Good news is that it should be relatively straightforward to upgrade these two algorithms to the new geometry model - lines to polygons would just take the input QgsCurve geometry and set it as the exterior ring for a QgsSurface, and polygons to lines would create output QgsCurve geometries from the exterior ring and any interior rings directly.

**Comment by m-kuhn** [comment]
Great to see all these algs coming back (and I hope the test system and all the tests from @ghtmtt have helped to avoid some pitfalls)

> If users need a non-multi linestring output, multi to single part alg can be used.

How do we continue with such often required workflows?
I could imagine a couple of different approaches reaching from "trust the user knows what's right" over "add a section 'common post processing steps'" to more integrated approaches like a checkbox "force singlepart results" that will transparently send the results through another algorithm.

**Comment by nirvn** [comment]
@nyalldawson , both algorithms have now been updated to rely on new geometry model. 

_For the record, a significant part of the latest was provided by Nyall via google hangout. Thanks for the help._

**Comment by nyalldawson** [comment]
This looks good to me - do you consider it ready to go?

**Comment by nirvn** [comment]
@nyalldawson , yep.

**Pull request merged**
