### PR TITLE
fix namespaces are not documented [sipify]

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by nirvn** [comment]
@3nids , thanks.

**Comment by 3nids** [comment]
@nirvn I get a build error. I sent a mail to PyQt list to see if we can deal with it. I guess not. In such case, it's either without docstring for the namespace (its methods are still documented) or changing this to a class so we can document it.

**Comment by 3nids** [comment]
so, apparently we found another bug in SIP. It's too much of effort for me to try to fix it...

**Comment by nyalldawson** [comment]
So should we close this? Or comment the new code out and wait for sip support?

**Comment by 3nids** [comment]
I just have some changes that I'd like to commit in sipify to get ready for this. Will try to update asap.

**Comment by 3nids** [comment]
Just a sec

**Pull request closed without merging**
