### PR TITLE
Display the vertex tool (current layer) in Edit menu

### PR DESCRIPTION
**Pull request by DelazJ**
and with appropriate icon

### CODE REVIEW

**Comment by nirvn** [comment]
I'm getting slightly worried about the size of the edit menu, we need some restructuring there. That said, it's a bigger problem to tackle elsewhere.

Why only add the current layer mode to the menu?

**Comment by DelazJ** [comment]
> Why only add the current layer mode to the menu?

Because the other one is already available.

**Comment by nyalldawson** [comment]
Haven't we already had a similar discussion and decided not to add more to this menu until it's rearranged?

**Comment by nirvn** [comment]
@nyalldawson , right, we did. 

@DelazJ , let's wait until the Edit menu is restructured to add this then. Nobody's leading this restructuring effort, feel free to give it a try :)

**Comment by nyalldawson** [comment]
Closed pending an Edit menu rework

**Pull request closed without merging**
