### PR TITLE
Revert "Reduce pollution of system directories during test runs"

### PR DESCRIPTION
**Pull request by nyalldawson**
These changes result in segfaults when running Python tests from non-installed builds, which completely breaks my development workflow.

### CODE REVIEW

**Comment by nyalldawson** [comment]
FYI @strk, can you revise and then open a new PR for your changes.

**Review by nirvn — APPROVED** [review]

**Comment by strk** [comment]
Can you please file a ticket about the problem ? There are not enough detail shere, and I think CI runs python tests from non-installed builds, doesn't it ?

**Comment by lnicola** [comment]
An issue doesn't really make sense (since it's fixed now), but some details about the crash would be nice to see. Did anyone else encounter it?

**Comment by jef-n** [comment]
> An issue doesn't really make sense (since it's fixed now), but some details about the crash would be nice to see. Did anyone else encounter it?

I find it very offensive to revert commits at all - unless it clearly something that is a clearly lost cause that is totally wrong.  If something breaks that IMHO should be reported so it can be resolved - in a forward manner: give the committer a chance to fix his mess (or explain why it isn't one) or just fix it yourself.

In this case the CI apparently didn't even have a issue with that and I pretty sure that @strk also ran the tests locally.  So this sounds like a local issue to me - and it's not even clear what it actually was.

Hardwiring "/tmp" looks wrong - and on Windows it's at the very least unexpected (but we have numerous tests that have issues like that - but maybe the tests affected by this change are even blacklisted on Windows in the CI, because they wouldn't work there because of /tmp).   Everything that depends on "/tmp" is buggy and should be fixed.

I also wonder why this was approved without further information on what actually broke.

What about the issues that were fixed by the PRs the reverted commits were in?  Do those need to be reopened?

**Comment by nyalldawson** [comment]
@jef-n in this case there's clearly issues with the original PR -- as you've pointed out, it makes assumptions like "/tmp" existing, and there's also broken use of QString functions -- https://github.com/qgis/QGIS/pull/57606/files#diff-6c375f9b6dfff3afa9111b8162dcaa3e932b003e2a71c847f7ab9d31de12a37bR4185

It should not have been merged in its current state. And in the current state, it results in segfaults when running tests via ctest from the build folder (see below). I spent a good half hour trying to fix this before reverting, and that was half an hour of completely volunteer, unpaid time, before catching myself and realising "this is NOT **my** problem to fix".

```
nyall@nyall-framework:~/dev/build-qgis$ ctest -R GdalProvider\$ -V
UpdateCTestConfiguration  from :/home/nyall/dev/build-qgis/DartConfiguration.tcl
Parse Config file:/home/nyall/dev/build-qgis/DartConfiguration.tcl
 Add coverage exclude regular expressions.
 Add coverage exclude: /CMakeFiles/CMakeTmp/
UpdateCTestConfiguration  from :/home/nyall/dev/build-qgis/DartConfiguration.tcl
Parse Config file:/home/nyall/dev/build-qgis/DartConfiguration.tcl
Test project /home/nyall/dev/build-qgis
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added setup test logGitStatus required by fixture SOURCETREE
Added cleanup test checkGitStatus required by fixture SOURCETREE
Added 2 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start   1: logGitStatus

1: Test command: /home/nyall/dev/QGIS/scripts/chkgitstatus.sh "log"
1: Working Directory: /home/nyall/dev/build-qgis
1: Test timeout computed to be: 1500
1/3 Test   #1: logGitStatus .....................   Passed    0.05 sec
test 496
    Start 496: PyQgsGdalProvider

496: Test command: /usr/bin/cmake "-P" "/home/nyall/dev/build-qgis/tests/src/python/PyQgsGdalProvider.cmake"
496: Working Directory: /home/nyall/dev/build-qgis/tests/src/python
496: Environment variables: 
496:  TMPDIR=/home/nyall/dev/build-qgis/tmp
496:  QGIS_CUSTOM_CONFIG_PATH=/home/nyall/dev/build-qgis/tmp/config
496: Test timeout computed to be: 1500
496: export =
496: export PYTHONPATH=/home/nyall/dev/build-qgis/output/python:/home/nyall/dev/build-qgis/output/python/plugins:/home/nyall/dev/QGIS/tests/src/python:
496: -- Running  /usr/bin/python3.12 /home/nyall/dev/QGIS/tests/src/python/test_provider_gdal.py
496: src/core/providers/qgsproviderregistry.cpp:372 : (init) [339ms] Loaded 33 providers (OAPIF;WFS;arcgisfeatureserver;arcgismapserver;arcgisvectortileservice;cesiumtiles;copc;delimitedtext;ept;gdal;gpx;grass;grassraster;mbtilesvectortiles;mdal;memory;mesh_memory;mssql;ogr;pdal;postgres;postgresraster;sensorthings;spatialite;tiledscene;vectortile;virtual;virtualraster;vpc;vtpkvectortiles;wcs;wms;xyzvectortiles) 
496: QFile::remove: Empty or null file name
496: /usr/lib64/python3.12/site-packages/osgeo/gdal.py:312: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
496:   warnings.warn(
496: GDAL ERROR 1: Unable to compute a transformation between pixel/line and georeferenced coordinates for testInt8.tif. There is no affine transformation and no GCPs. Specify transformation option SRC_METHOD=NO_GEOTRANSFORM to bypass this check.
496: GDAL ERROR 1: Unable to compute a transformation between pixel/line and georeferenced coordinates for testInt8.tif. There is no affine transformation and no GCPs. Specify transformation option SRC_METHOD=NO_GEOTRANSFORM to bypass this check.
496: .....src/core/qgsmessagelog.cpp:39 : (logMessage) [121ms] 2024-06-27T12:57:07 WCS[1] Download of capabilities failed: Protocol "" is unknown
496: src/core/qgsmessagelog.cpp:39 : (logMessage) [0ms] 2024-06-27T12:57:07 WCS[1] Download of capabilities failed: Protocol "" is unknown
496: src/providers/wcs/qgswcscapabilities.cpp:326 : (describeCoverage) [0ms] coverage not found
496: .Could not create temporary copy
496: CMake Error at PyQgsGdalProvider.cmake:23 (message):
496:   Test failed: Subprocess aborted
```

This should NOT become **my** issue to fix just because the original PR was merged! The previous setup has worked for years without widespread issues, and I think it's entirely appropriate to require @strk to make sure their changes are working equally well before those changes are acceptable.

The 3 linked issues the original PR solved were all non user facing, non-critical issues. Yet a segfault on all python tests which completely BLOCKED me from working IS a critical issue, and again, not something that is MY responsibility to fix.

I only ever revert PRs rapidly when it's extreme circumstances, e.g. when there's a regression found and we're just hours before a release, or when there's breakage in the CI / tests like this and the work needs further refinement before it's should be included in master. It's not rejecting the work, it's sending it back for refinement so that it's fixed, for the betterment of QGIS users and other developers.

**Comment by strk** [comment]
On Wed, Jun 26, 2024 at 08:12:41PM -0700, Nyall Dawson wrote:
> @jef-n in this case there's clearly issues with the original PR -- as you've pointed out, it makes assumptions like "/tmp" existing, and there's also broken use of QString functions -- https://github.com/qgis/QGIS/pull/57606/files#diff-6c375f9b6dfff3afa9111b8162dcaa3e932b003e2a71c847f7ab9d31de12a37bR4185

Just for the record: my PR _removed_ the hard-coded "/tmp", didn't add it.

I've taken the effort of re-opening the 3 issues that were closed by
the original PR and filed a new PR to fix them again while handling
the problem found by Nyall and not found by CI (an issue about CI not
catching that issue might still be good).

Can you please review the new PR @jef-n @elpaso ?
https://github.com/qgis/QGIS/pull/57934

Nyall commented on it but his review are still lacking detail on what
he thinks is wrong (and CI is still green).

**Comment by nyalldawson** [comment]
@strk 

Try it yourself -- set the temp variable to something which doesn't exist, and QTemporaryFile will not work. Hence the segfaults. It's a complete accident that it works on ci, because the build folder is "/".

But I still disagree that this is a desirable change is any way. I see a self managed temp folder as a complete backwards step.

**Pull request merged**
