### PR TITLE
[dbmanager] add primary key to the view created by versioning plugin (fix #25888)

### LINKED ISSUE #25888: DB Manager Versioning: _current view lacks primary key
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [17992](https://issues.qgis.org/issues/17992)
Affected QGIS version: 3.3(master)
Redmine category:db_manager

---
The Versioning / Change logging automatically creates a view with the current elements. Unfortunately, in the view it is not included the `id_hist`, but only the `id`, which can be duplicated, e.g. in case of a split polygon.
As a consequence, the view cannot be loaded.
I suggest to simply add `id_hist` to the view.
The fix can be easily backported to 2.18.

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
Versioning plugin creates a view but does not include new primary key into it. As result view can not be added as a layer to QGIS. Fixes #25888

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by alexbruy** [comment]
@pcav may I ask you to test this fix?

**Comment by pcav** [comment]
Checked, the id column is included.
Thanks!

**Comment by alexbruy** [comment]
@pcav I know that column included, but does it works as expected for you? Does it fixes also #22026?

And please don't close PR again.

**Comment by pcav** [comment]
Yes, it works. Sorry for closing the PR, I assumed it was a ticket. Thanks.

**Pull request merged**
