### PR TITLE
Hint where to find select features method

### PR DESCRIPTION
**Pull request by m-kuhn**
## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

### CODE REVIEW

**Comment by Gustry** [comment]
Didn't you say to avoid new branch on the main repo ? :-)

**Comment by DelazJ** [comment]
> Didn't you say to avoid new branch on the main repo ? :-)

😄 Particularly when it triggers issue report creation in doc repo (not the case this time but https://github.com/qgis/QGIS-Documentation/issues/3243)

**Comment by 3nids** [comment]
and mostly when a change requires a sipify run!

**Comment by m-kuhn** [comment]
> Didn't you say to avoid new branch on the main repo ? :-)

Blame github that they won't let me choose a branch on my fork when using the online editor while I'm at a client side and want to do a quick fix.

> 😄 Particularly when it triggers issue report creation in doc repo (not the case this time but qgis/QGIS-Documentation#3243)

I didn't even notice. Sorry for that.

> and mostly when a change requires a sipify run!

file an upstream issue for that ;P

**Pull request merged**
