### PR TITLE
Enable advanced digitizing also for geographic CRS

### PR DESCRIPTION
**Pull request by wonder-sk**
This is useful if users want to enter lat/lon coordinates when digitizing

@3nids what do you think?

### CODE REVIEW

**Review by nyalldawson — COMMENTED** [review]
Isn't this a bit misleading for users? Ie the distance/angles won't be accurate (unless for some reason they are wanting them in degrees)

**Comment by 3nids** [comment]
What about just enabling coordinates input? I would avoid having something not mathematically correct in the so-called "Advanced digitizing"

**Comment by wonder-sk** [comment]
Yeah enabling X/Y input would be enough I guess - distances/angles would be indeed wrong... (I don't have a strong opinion here, just got a question about numeric entry of lat/long for new features from a user)

**Comment by 3nids** [comment]
maybe the node tool table would be more suited here?

**Comment by nyalldawson** [comment]
Just to clarify - I'm not against having this dock enabled in geographic CRSes, but I think it should be done by projecting the bearings/distances geographically and with consideration of the current ellipsoid, etc. But that's a fair chunk of work!

**Comment by wonder-sk** [comment]
Thought about node tool's table, however it is somehow impractical... 1. create a point somewhere, 2. switch to node tool, 3. select the point, 4. edit coordinates, 5. repeat ... but better than nothing :-) Let me just close this...

**Comment by 3nids** [comment]
that was fast ;)

for a specific use, a simple plugin which creates a new feature on the currently selected point layer by showing 2 line edits for coordinates.
or possibly doing this in core, but that would be redundant with the adv. digit. dock for non-geographic .

**Pull request closed without merging**
