### PR TITLE
[WFS] maxFeature vs. server limits, [WMS] use layers min/maxScaleDenominator, [ALL] use maxScaleDenominator when zoom to layer

### PR DESCRIPTION
**Pull request by tcoupin**
On Zoom In, current mGetExtent always contains the new window's extent.
Are we sure that all data has been loaded ? NO.

If the current number of features match the maxFeature parameter, we have to force redefinition of mGetExtent as the new window's extent (smallest).

If the current number of features is lower than the maxFeature parameter, nothing to do : we already have all the data.

### CODE REVIEW

**Comment by tcoupin** [comment]
2 new commits : 
- Use Min/MaxScaleDenominator from WMS GetCapabilities to limit Layer visibility
- if scale based visibility, use it when zoom to layer (stay under the limit)

**Comment by pcav** [comment]
@mhugent, @jef : this seems important stuff

**Comment by tcoupin** [comment]
Tell me if you need more details about the 3 features.

**Comment by tcoupin** [comment]
@pcav : do you mean @jef-n instead of @jef ?

**Comment by pcav** [comment]
Yes, thanks for clarifying.

**Comment by tcoupin** [comment]
Do you think it will be in next release ? The first feature can be very useful for me and my NMCA.

**Comment by m-kuhn** [comment]
@rouault were these features part of your recent WFS work?

Just cleaning up some old pull requests.

**Comment by rouault** [comment]
> @rouault were these features part of your recent WFS work?

Yes that should be already taken into account in my WFS work

**Comment by m-kuhn** [comment]
Thanks,
I'll close it 

@tcoupin thanks for your commitment and sorry that this took so long. Feel free to open any reminder and I promise it will be handled faster.

**Comment by tcoupin** [comment]
This pull request includes 3 features :
- [WFS] maxFeature vs. server limits
- [WMS] use layers min/maxScaleDenominator
- [ALL] use maxScaleDenominator when zoom to layer

Which are included in which release ?

**Pull request closed without merging**
