### PR TITLE
[Processing] GRASS7: Fix problem with Windows mbcs username and in/out filenames

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes two bugs for GRASS7 Processing:
- [#12657](https://hub.qgis.org/issues/12657)
- [#9425](https://hub.qgis.org/issues/9425)

There was an encoding problem for MS-Windows shell. Processing GRASS algorithms are producing a shell (.bat) file that plays all the GRASS commands (via exe binaries installed on the system). When username was using [mbcs characters](http://stackoverflow.com/questions/748965/what-is-a-multibyte-character-set) (MS-Windows doesn't use utf-8 for the filenames, at least on MS-Windows XP and 7), Processing was not able to retrieve the home directory. I have made changes to fix this (via expanduser and some encoding).

For the shell part, there was still an issue: MS Windows shell (cmd.exe) is used to launch the .bat file. But you have to use the same encoding in the .bat file than in the console. Of course, the charset depends on the locale installation of the OS. I have found a workaround to find the console charset before producing the .bat file and it works quite well.

I have also taken time to clean Grass7utils.py:
- use `with open(...) as` instead of `open(...)` (don't need close()).
- use unicode everywhere.
- use long strings instead of a succession of `file.write(...)`.
- use `os.path.join` instead of `dirname + os.sep + filename`.
- I have also fixed the CommanderWindow to make it works with an mbcs username.

I have made my tests on MS-Windows XP and 7 with an account with french accent (cp850 console page charset). Can someone try with another charset ("asian" ones for example) before merging this ? 

I think there will be a merging problem with #2871 but this is trivial to fix...

### CODE REVIEW

**Comment by fsdias** [comment]
@alexbruy @volaya

**Comment by alexbruy** [comment]
Maybe it makes sense to use with codecs.open() and specify output encoding?

Also think findWindowsCmdEncoding() function should go somewhere in the tools package (maybe in general) as it will be useful for other backends, e.g. R.

**Comment by medspx** [comment]
Ok, I think I'll move findWindowsCmdEncoding to tools system.py rather than in general.py because this is where you can find all the low-level system functions.

For codecs module, I tried to use it but faced a problem with universal newline: it seems that codecs don't have universal newline for writing in files. That means that you have to manually deal with \r\n when you are under MS-Windows. Using open and decode/encode doesn't have this problem.

**Comment by alexbruy** [comment]
Seems you can use io.open() which supports universal new lines and allows to specify encoding

**Comment by medspx** [comment]
Ok, I have moved findWindowsCmdEncoding in tools/system.py and used io.open (which just works).
I have made tests under MS Windows and it works. Please, don't merge it now because I am waiting for feedback from a user.

I will tell you when the PR will be ready to merge...

**Comment by volaya** [comment]
@medspx Any news on this? conflicts need to be solved, but if this is ready to merge,let us know so I can take care of it. Thanks!

**Comment by medspx** [comment]
Hello,

those modifications only fix problems for european users. I was in contact with an asian user, but I could not reproduce his bugs so it was very difficult to find the real cause of the problem (probably a different way to handle character encoding on MS-Windows asian versions). Furthermore, there is no unit tests for this and we all know that encoding problems are legion in Python. I think that this PR do not introduce new bugs but I can't confirm it.

I thought that it could also be fixed with a Python3 port of this part of processing but I am not ready yet to work on it (I'll have more time in a month).

I don't know what to do with this PR: close it and not merge it as it is not complete (and there is no tests) or try to merge it because it seems to solve some problems at least. What do you think ?

**Comment by m-kuhn** [comment]
Hey @medspx 

Now that QGIS master requires python 3 it might be a good point in time to revisit this issue.
Do you want to rebase it on top of master and open a new pull request?

**Comment by medspx** [comment]
Well, finally I think it is time to close this one. I'll try to pay attention to MS-Windows encoding for the next return of the GRASS7 algorithm provider in Processing...

**Comment by gioman** [comment]
@medspx why closing this? we still have 2.18 that soon will become LTR and stick around for a while, until 3.* will become LTR and this is not going to happen soon. This mean that this issue will still affect for a long the most important qgis release.

**Pull request closed without merging**
