### PR TITLE
Move vector styling to styles dock

### PR DESCRIPTION
**Pull request by NathanW2**
As part 2 of the map styles dock I will be moving all the vector style widgets into dock.

This PR include 2 major parts:
- Reworking some of the UI to be more dock friendly
- Connecting all the parts to be live

Still to do:
-  Add dialogs (expect colour picker) go into panels like labels
- Live rule based expressions (maybe)
- More UI reworking.

**Note:** This is a super early PR but would really like feedback and testing early if people have spare time.

image

image

image

As styles are applied live you can do cool stuff like this:

livehis

### CODE REVIEW

**Comment by pcav** [comment]
Thanks for your work, great stuff.
Please consider usability on small screens (1024*768). They are surprisingly still in use.

**Comment by gioman** [comment]
My experience is not the same. Small resolutions such as 1024x768 are virtually disappeared, and  modern small laptops have usually resolutions of 1280 and above. If you refer to http://hub.qgis.org/issues/7383 is probable is just about specific Linux DE, but not sure, no problems here on KDE, Cinnamon and Unity at 1024. Also no problems on Windows at the same resolution.

**Comment by NathanW2** [comment]
@pcav I will take note of that. Even if they are not as wide used as they used to be I would like to give a good experience on most setups.  A quick test this morning on 1024*768 seems to show it works pretty well in dock mode, the widget is also in a scroll area which helps if there is overflow.

**Comment by pcav** [comment]
Thanks Nathan.

**Comment by NathanW2** [comment]
@pcav are you able to build this branch to do some local testing for me if you get a chance?

**Comment by pcav** [comment]
Not shortly, sorry - too busy now.

**Comment by NathanW2** [comment]
No rush. Still work to do.

**Comment by NathanW2** [comment]
Manual merged in master

**Pull request closed without merging**
