### PR TITLE
Support filtering layout legends by multiple linked map items

### PR DESCRIPTION
**Pull request by nyalldawson**
Instead of limiting layout legend filtering to a single linked map, this change permits legends to be filtered instead by multiple linked maps. It is designed to accomodate the use case where a layout has multiple maps, potentially at different scales and showing different extents, and a single legend is required which includes all symbols visible across all the maps.

The UX has been designed to avoid changing the current user workflows, in that legends will still be linked to a single main map item. This map is used when determining the scale (and other map dependent properties) at which to render the legend's symbols. Checking the "Only show items inside linked maps" option will still automatically filter the legend by the content of the main linked maps. However, there's a new "..." options button next to the "Only show items inside linked maps" checkbox which allows users to select also other maps from their layout to consider when determining visible items:

image

image

Sponsored by City of Canning

### CODE REVIEW

**Comment by roya0045** [comment]
@nyalldawson I have two PR that were closed formely that improved the legend, I guess I would have to refactor some part of them for integration, I can update the branch used in #47099 and #41898 if you are working on those types of improvement at the moment.

**Comment by nyalldawson** [comment]
@roya0045 
>  I have two PR that were closed formely that improved the legend, I guess I would have to refactor some part of them for integration, I can update the branch used in #47099 and #41898 if you are working on those types of improvement at the moment

Thanks! #47099 is definitely made redundant by this pr -- I've also included a test here with rotated maps to ensure that the issue is fixed.

#41898 is a little trickier. The question I have is whether it's appropriate to consider raster layers when we aren't actually filtering the raster classes by visibility. I guess for some legend types this is ok (ie for graduated data), but for classified rasters then I think we should also be filtering the displayed classes by what's actually visible... And that's tricky 😁. It's definitely worth reviving that pr after the current series of legend work is merged, and we can move the discussion there...

**Comment by roya0045** [comment]
Well the second PR mostly sorts all layer type by their extent, so it shouldn't just apply to rasters, as of now any non-vector layer is going to be displayed in the legend even when it is out of view. I agree that nuancing per visible class of a raster might be a good improvement, but the gist is to purge anything out of view.

If we filter by visible class, the layer itself would be visible, even if partly.

**Review by nirvn — APPROVED** [review]
Really nice feature.

**Pull request merged**
