### PR TITLE
Fieldicon

### PR DESCRIPTION
**Pull request by 3nids**
superseeds #2513 

QgsMapLayerComboBox shows nice icons for different layer types (point, line, polygon, raster etc), but QgsFieldComboBox does not show such icons. This commit adds data type icons for QgsFieldComboBox.

I get a crash on exit in QiconPrivate destructor. Can someone tell me why?

### CODE REVIEW

**Comment by 3nids** [comment]
image

**Comment by slarosa** [comment]
great enhancement! could be usefull to create a new ```QgsFieldItem``` class for this stuff?? just wondering.

**Comment by 3nids** [comment]
@slarosa what would be the advantage? As far as I see it, that would be just for icons at start?

**Comment by slarosa** [comment]
i_dunno_man_by_jad0n-d8q65mc
....I just was wondering in order to know if this could be used somewhere else in the code.

BTW: no crash on exit for me!

**Comment by 3nids** [comment]
ok, thanks.
the crash on exit is when opening vector layer properties with qt5 build, nothing related to this commit...

**Comment by 3nids** [comment]
@alexbruy thanks for this!

**Pull request merged**
