### PR TITLE
bump to Qt 5.9 for the 3D

### PR DESCRIPTION
**Pull request by Gustry**
## Description

Based on the discussion here https://github.com/qgis/QGIS/pull/5203#discussion_r142319862 with @wonder-sk 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by elpaso** [comment]
@jef-n are you ok with this?

**Comment by jef-n** [comment]
@elpaso isn't 5.9 a requirement for 3D anyway?   So this is just a plain fix.

**Comment by wonder-sk** [comment]
Yeah... and it does not increase min. Qt5 version when building without 3D...

**Comment by elpaso** [comment]
@jef-n you are the packaging expert: if you're ok, I'm ok, I was just worried about availability of 5.9 on some linux distros

**Comment by Gustry** [comment]
@elpaso We couldn't compile QGIS with Qt 5.8 and 3D, this PR was only increasing QT minimum version when 3D is enabled.

**Comment by jef-n** [comment]
@elpaso packages with 3d are only built where 5.9 is available (ie. debian unstable & ubuntu artful)

**Pull request merged**
