### PR TITLE
Make console printing safe again

### PR DESCRIPTION
**Pull request by m-kuhn**
This leads to random crashes when using print

References #8343 https://issues.qgis.org/issues/8343

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
I think I'm -1 here. 

Sure processEvents is dangerous, but having the console "lock up" with zero feedback while an entire script runs is going to be very frustrating and very un user friendly.

**Comment by m-kuhn** [comment]
I know, that's why I even left it an option.
But I've seen more than one crash blaming the QGIS console for being unstable.

**Comment by nyalldawson** [comment]
This requirement is really badly supported by Qt IMO. Does a call to repaint the console instead of processEvents work? It appears as though that should be supported on all non-osx platforms, as it should repaint without queuing in the event loop (but still queues on osx). And I'd not consider losing the instant print results on osx alone a blocker ;)

**Comment by m-kuhn** [comment]
Wow, good catch!

**Comment by nyalldawson** [comment]
@m-kuhn did it work?

**Comment by m-kuhn** [comment]
On Fedora, yes :tada:

**Comment by nyalldawson** [comment]
Good enough for me! What about scrolling when multiple lines are printed, does that work without events?

**Comment by m-kuhn** [comment]
Nope. But cancelling the ongoing command also does not work (and never did ;) )

**Comment by shivareddyiirs** [comment]
Thanks for letting me know that print is not safe. 
I have overridden all my prints below: 

https://github.com/shivareddyiirs/QRealTime/commit/e06b14cc66a581d38089f4a8a1453f86f25e3258

**Comment by slarosa** [comment]
so osx users will have not longer feedbacks from console while script is running :-(

Any chance to do processEvents as an option?

**Comment by m-kuhn** [comment]
> so osx users will have not longer feedbacks from console while script is running :-(

Yes, and no crashes :stuck_out_tongue: 

> Any chance to do processEvents as an option?

Yes, if there's an explanation about the risks involved, that sounds good to me

**Comment by nyalldawson** [comment]
I'd say no option - we don't want an option which is effectively "make qgis fragile", anymore then we want plugins published which make qgis fragile.

I'd say just write a little "instantPrint" function which calls print and processEvents, and use it wherever it's safe for your script to do so.

**Comment by m-kuhn** [comment]
> I'd say no option - we don't want an option which is effectively "make qgis fragile", anymore then we want plugins published which make qgis fragile.

That's a quick U-turn after the -1 in the beginning ;)

> and use it wherever it's safe for your script to do so

Honestly, I don't think we can expect people to be able to judge this. I'd rather have it a QSettings only option that devs can enable on their osx machines if they feel adventurous, rather than something a osx dev introduces and infects all installation of their plugins.

**Pull request merged**
