### PR TITLE
Remove reference counting from  from OgrConnPool

### PR DESCRIPTION
**Pull request by strk**
Fixes http://hub.qgis.org/issues/14212

### CODE REVIEW

**Comment by strk** [comment]
@m-kuhn, @wonder-sk are you good with this ? I think lifetime managmement is already handled by QgsConnectionPool via acquire/release, so we don't need ref/unref, do you agree ?

**Comment by m-kuhn** [comment]
@manisandro what's your opinion?

**Comment by manisandro** [comment]
@jef-n introduced this to fix test failures on Windows (commit 4d681f03c64478918d8db8096b736bd055a56846 ). @jef-n your opinion?

**Comment by jef-n** [comment]
@manisandro might be a debugging leftover, not sure if it ever fired. But it shouldn't do any harm either. The actual fix was to remove the shape after QgsVectorFileWriter is destroyed.

**Comment by strk** [comment]
I think it may still harm to give the impression ownership is shared when in reality ownership is purely on the pool. Which commit had the fix, for reference ?

**Comment by strk** [comment]
Ah you meant the windows failure fix 4d681f03c64478918d8db8096b736bd055a56846, ok.
I'm rebasing to master and if it still works fine I'll push.

**Comment by jef-n** [comment]
What about ``QgsOgrConnPool::ref`` and ``::unref``?

**Comment by strk** [comment]
good catch, gone with next commit

**Comment by jef-n** [comment]
hm, essentially reverts 42137e4 from #2197   @manisandro

**Comment by strk** [comment]
PR #2197 was meant to fix http://hub.qgis.org/issues/13082

**Comment by strk** [comment]
"Removing a shape file layer doesn't close the file."

Isn't this by design, until the pooled connection gets closed due to timeout ?

**Comment by strk** [comment]
Ok, I've checked and the file is closed after timeout.
I'm not sure how long is the timeout and how to configure it, but I saw the file being closed after a while (with this PR included).

**Comment by strk** [comment]
The timeout is hard-coded as 60 seconds.
So can I  merge this up now ?

**Comment by jef-n** [comment]
So that means that the file is locked until the timer expires?   Bringing back [#11007](http://hub.qgis.org/issues/11007)?

**Comment by manisandro** [comment]
Yeah I'm a bit scared by this as well, the fact that users weren't able to delete the files after removing them from the layer tree was enough to triggere a 2.10.1 release if memory serves me right.

**Comment by strk** [comment]
Yes, by design. I guess we could make the base class take expiration time as a parameter, so that the Ogr connection pool might request immediate expiration.

**Comment by strk** [comment]
I'll look at how to override that timer, or even disable it.
But then, why are we using a Pool at all ?

**Comment by strk** [comment]
Should the centralized pool maybe have a method to "discard all pooled connections" ?

**Comment by manisandro** [comment]
The centralized method would be `QgsConnectionPool::invalidateConnections`. Any why are we pooling: because it speeds things up when if existing (read-only) handles can be re-used.

**Comment by strk** [comment]
Pooling speeds things up IFF we keep those files open. Are you saying we should threat differently read-write and read-only handles when it comes to pooling ?

**Comment by manisandro** [comment]
Only read-only connections are pooled, as soon as a dataset is altered, all read-only connections are invalidated.

**Comment by strk** [comment]
QgsOgrProvider::syncToDisc already calls ::invalidateConnections, so  [#11007](http://hub.qgis.org/issues/11007) should be still ok ?
Do you have any way to test that ?

**Comment by jef-n** [comment]
So the fix for [#11007](http://hub.qgis.org/issues/11007) might be to call ``open()`` after ``OGR_L_SyncToDisk``?

**Comment by manisandro** [comment]
For #11007 ideally you would close the handle when flagging the connection as invalid in `qgsConnectionPool_InvalidateConnection`. However, this can be dangerous since it is theoretically it is possible that an operation in another thread (i.e. rendering) is still using the connection when it is using invalidated - this is the reason that connections are only re-opened next time the connection from the pool is used. One would need a synchronization point which invalidates all connections, waits until none are used, and then closes the handles.

**Comment by strk** [comment]
wait, you mean ::invalidateConnection invalidates _acquired_ connection ?!
Why is it so ? Shouldn't "acquired" connection only be managed by whoever acquired them ?
The method in QgsConnectionPool is not documented (that's the real DANGER!)

**Comment by manisandro** [comment]
QgsConnectionPool::invalidateConnections (which is documented) is used to *flag* any open connections as invalid. He who acquired the connection does not know that some-one else modified the dataset, that's why the flagging is there.

**Comment by strk** [comment]
I see now (was looking at the version taking no argument, which is undocumented).
So it sounds all fine, existing handles see the old data and new handles see the new data, when connection is released, it won't be given back to anyone but closed.

What's left that is broken for  [#11007](http://hub.qgis.org/issues/11007) ?

**Comment by manisandro** [comment]
I think what can happen is that, allthough all connections are flagged as invalid, they are only actually closed when a new consumer acquires the respective connection. So if you do a write operation on the dataset, invalidate the connections, but don't i.e. trigger a rendering operation (which would have the rendering threads aquire connections from the pool), then the handles remain open, and this can cause locking issues under windows. (If my limited Windows knowledge is correct in that even read-only handles lock the file on the filesystem)

**Comment by manisandro** [comment]
Hmm, I actually can't think of a reason why I had the invalidate logic in `QgsConnectionPoolGroup::acquire` instead of in `QgsConnectionPoolGroup::release`, closing invalid connections there would make more sense, unless I'm forgetting something from the time I wrote the code...

**Comment by manisandro** [comment]
Something like 

https://github.com/manisandro/QGIS/commit/33876912b8088ae80a307de86384755aebd0c939

Perhaps a Windows user can check whether it makes any difference for #11007 ?

**Comment by manisandro** [comment]
@strk I've added another commit which makes invalidateConnections immediately destroy non-acquired connections:

https://github.com/manisandro/QGIS/commit/3115c2fe00be7d03bc519fb74aba40b9ca3540d8

From my test, it fixes issue #14212. Can you confirm?

So with this and the other commit mentioned above, I think it should also address the destructor ordering issue, since now all ogr handles should be closed by the time the provider is destroyed (if not, it would mean that a connection is still acquired when the provider is destroyed, which really should never happen).

**Comment by strk** [comment]
Destroy-on-release is fine with me, but I wouldn't take back the heap allocation of singleton.
The point is that by unless we heap-allocate there would never be any chance to control deinitialization order. I understand your commit ensures "invalidated" connections are removed at the time of exit, but what about still-hold connections ?

Your commit applied to master (commit:051253888810b06f6b055bfea57a7c6a009e3fdc) fixes the qgis_diagramtest crash but re-introduces the qgis_analyzertest crash here.

**Comment by strk** [comment]
@manisandro I added a reduced version of your patch in latest commit in this PR

**Comment by manisandro** [comment]
@strk I need to revist the reference counting issue, but at present I'm not convinced that the code can be dropped (i.e. see first commit of this PR).

As for my latest experiments: Do you see a scenario where connecitons can still be held when qgis exits? I need to experiment a bit, but right now I'm thinking this should not happen?

I'll look at qgis_analyzertest.

And heap allocation: agree, removing it is a temporary test to catch dangling connections.

**Comment by strk** [comment]
I can't really anticipate scenarios where connections are still held when qgis exits, but I'd prefer a WARNING much more than a crash if that ever happens.

**Comment by manisandro** [comment]
Well considering that that would mean that somebody is assuming that the ogr provider is still alive while it has since been destroyed, I guess crashes can happen in many other places also.

**Comment by manisandro** [comment]
But I think as soon as I reintroduce the heap allocated singleton, we'd have the double safety, right?

**Comment by strk** [comment]
The point of heap-allocation is that we _control_ how things are destroyed, so we _guarantee_ that OGR library is in a working state until all QGIS singletons are destroyed. I don't know now about what other dependencies are not being handled properly (ie: what else depends on the _provider_).

**Comment by nyalldawson** [comment]
Just wondering - is http://hub.qgis.org/issues/13061 also impacted by this issue?

**Comment by manisandro** [comment]
@strk Sure, I agree with you there, it is just to understand what open issues there are. From my point of view, fixing qgis_analyzertest and then reintroducing heap allocation, and then things should be good.

@nyalldawson I'll also look at that one

**Comment by strk** [comment]
@nyalldawson I guess so, can you reproduce that one ?

**Comment by nyalldawson** [comment]
I can, yes

**Comment by strk** [comment]
@nyalldawson could you update the ticket with the commit in which you can reproduce it, and maybe test it also with the code in this PR ?

**Comment by manisandro** [comment]
So the issue with qgis_analyzertest is that it did not free the allocated vector layers when cleaning up the test case, hence the providers were never destroyed and the connection pool handles not freed.

This https://github.com/manisandro/QGIS/commit/925e3b348a32e00d461e4c0141dff16dfcd99258 fixes this particular crash, but now I get crash on exit in a QgsMarkerSymbolV2 destructor called by __run_exit_handlers. Looks like another singleton issue.

**Comment by strk** [comment]
@manisandro could we focus on an issue at a time ? This PR is about removing the refcounting so that ownership of pooled connection is clearly assigned to the pooler rather than shared among users. Is this something that you see a problem with ?

**Comment by manisandro** [comment]
Yes I do, see the entire discussion in https://github.com/qgis/QGIS/pull/2197 why reference counting was introduced in the first place, in short, because

"Actually it can happen: it is possible to create a QgsVectorLayer, then request its featureSource() object and delete the vector layer. The feature source is still valid and can be used to fetch features. Think of it as a snapshot of vector data provider's state."

As already stated, the reason for introducing reference counting was to avoid the issue of users not being able to delete their datasets after removing the layer from the tree. And unless I missed something, I don't see this adressed in another way.

**Comment by strk** [comment]
It would help if the bug fixed by introducing refcounting was proved by an automated testcase.

The problem of being unable to "delete datasets after removing layer from tree" is due to an hard-coded timer of 60 seconds. If "featureSource" objects are still around, whether they do not release the connection or do not decrement the referencecount is irrelevant to the problem being analyzed.

**Comment by manisandro** [comment]
It is not irrelevant:
- An ogr layer backed layer is created: refcount 1
- Renering starts, lets say with one thread, i.e. one feature source: refcount 2
- The layer is removed while rendering is still in progress, provider is destroyed: refcount 1
- Rendering finishes: refcount 0, all handles are freed

Without refcounting, the connections held by the feature source would only expire after 60 seconds, meaning that the layer will be locked for that period of time.

Now, if someone manually creates a feature source and holds on to that beyond the destruction of the layer, then yes, the layer will still be locked, but that is perfectly okay.

**Comment by strk** [comment]
In your scenario, you confirm the only problem is the hard-coded 60 seconds timer.
If you want connections to immediately expire, don't use the Pool, or tweak the timer, or invalidate them right after use. There's no need to have _both_ a Pool and Refcount.

**Comment by strk** [comment]
maybe we should move this discussion on the mailing list ?

**Comment by manisandro** [comment]
Seriously, what's wrong with refcount?

The pool avoids that each feature source has to open a handle from scratch, which for some datasets can take some time. The timer is there as an automatic cleanup mechanism, but having a 0 delay or whatever tiny delay defeats the entire purpose of the connection pool.

So, what is the problem you are trying to solve? Refcounting worked well and I see no issues arising from it. The issues which were noticed so far were addressed in the other commits referenced in this post.

**Comment by strk** [comment]
I might be misunderstanding the refcount purpose. Doesn't it drop the connection when refcount goes down to 0 ? If so, how does the pool help ?

**Comment by strk** [comment]
It doesn't help that QgsOgrConnPoolGroup and QgsOgrConn public ref/unref methods are not documented.

**Comment by manisandro** [comment]
Sure, but the refcount only goes to 0 when
- The provider has been destroyed
- All feature sources have been destroyed

That only happens when the layer and all feature sources have been removed from qgis, so then there is no point in keeping the connections in the pool, right?

The simplest case where the pool helps is rendering:
- The layer is opened
- Rendering starts, a number of connections are created the first time
- Subsequent rendering operations use the *existing* connections, and hence rendering is faster

**Comment by strk** [comment]
Can it still happen that the pool destroys a connection while the provider or any feature source are still alive ? As that would mean "unref" method would be called against a deleted object (deleted by pool).

**Comment by manisandro** [comment]
Uhm but there is lots of syncronization logic in the connection pool code to avoid that?

**Comment by strk** [comment]
onConnectionExpired() does not seem to check any refcount. Are we betting on all those feature sources to complete their work within 60 seconds ?

**Comment by manisandro** [comment]
unref deletes the group if refcount == 0, and when the object is deleted, the signal is automatically disconnected.

**Comment by strk** [comment]
Would this be equivalent of using a different Pool for each different Provider, rather than the singleton ?
Ownership of such Pool could be shared among Provider and FeatureSource (via standard shared pointers, RAII ready).

**Comment by manisandro** [comment]
That would mean rearchitecturing the entire connection pool logic and you loose the potential benefit when multiple layers share the same datasource.

**Comment by strk** [comment]
Ok, I think now I've a clearer picture on the matter.

The refcount basically gives special powers to OgrProvider and OgrFeatureSource objects so that they have shared ownership on QgsConnectionPoolGroup objects in the singleton Pool.

This means no other objet but OgrProvider and OgrFeatureSource can count an an acquired ogr connection to be still available at release time (which would fail an assertion).

QgsOgrConnPool not being an _exported_ class this should be "okish" for client code, but being it public it could still potentially be dangerous for internal code, if use is not careful. Right now OgrProvider and OgrFeatureSource are the only users of that pool, so things do work.

Is the above correct ?

**Comment by manisandro** [comment]
Currently only the provider and the feature source use the pool, but any other party is free to use the connection pool as long as it participates in the refcounting. (This, yes, could be documented).

So basically whoever uses connections from the pool needs to participate in reference counting, and clearly acquire/release the connections as expected by the connection pool logic.

**Comment by strk** [comment]
BUT acquired connection do not hold a reference, and there's no RAII ensuring obtained references are properly dropped. This is the kind of complexity I'd rather avoid, if possible. QGIS is already known to be not-so-stable, in general, so any proper behaviour that could be enforced by design would be to be preferred (IMHO).

One idea could be for refcounts to be distributed under form of objects that decrement the refcount on their destruction. There would then be a single method added in OgrPool, being the method to obtain such object. Such method could at the same time remove the cleanup timer and basically transfer ownership of the PoolGroup to all the owners of the shared "lock". Acquiring a connection could then require presenting the "lock" object as a proof. Anyway, this is brainstorming and doesnt' really belong in this PR, which was just aimed at fixing http://hub.qgis.org/issues/14212

**Comment by strk** [comment]
Closing, as the actual bug was fixed by tweaking the deinitialization order

**Comment by manisandro** [comment]
The timeout is not specific to the ogr pool, but common to all connection pools, I suppose it was introduced to avoid keeping postgres connections open over time. And for the ogr pool it does not harm either.

Reference holding objects are a valid idea, question is how far you want to "pool-proof" the code. I.e. if a comsumer forgets to release an aquired connection and then unrefs the pool. Ultimately, there are always tons of ways to shoot yourself in the foot.

But to wrap up this discussion here: do I gather correctly that the actual issues spotted are adressed by my commits  https://github.com/manisandro/QGIS/commits/pool_invalidate_release ? If so, I'l polish that and make a pull request out of it.

**Comment by strk** [comment]
I could not reproduce the actual issue on current master so I assume it was fixed by the commit that controlled deinitialization order (postponing GDAL deinitialization to exitQgis time).

In any case, your commits in https://github.com/manisandro/QGIS/commits/pool_invalidate_release look good to me.

**Comment by manisandro** [comment]
okay thanks

**Pull request closed without merging**
