### PR TITLE
Rename visibility presets to map themes

### PR DESCRIPTION
**Pull request by m-kuhn**
Because it is not only more descriptive for what it does but also
sounds more interesting.

[needs-docs]

### CODE REVIEW

**Comment by nyalldawson** [comment]
+1
 
Don't forget the Api break documentation!

**Comment by m-kuhn** [comment]
Done

**Comment by nyalldawson** [comment]
Just an extra note - I'm in favour of this after demonstrating visibility presets to someone earlier this week. Half way through the demo when I started showing how the style presets are affected realised just how much the current name is!

**Comment by m-kuhn** [comment]
Exactly what I thought when I explained it to people this week.

**Comment by NathanW2** [comment]
Not merging?

**Comment by m-kuhn** [comment]
Merged :)

**Pull request closed without merging**
