### PR TITLE
Build C++ API documentation with inheritance graphs

### LINKED ISSUE #54990: C++ API: missing "Inheritance graph" image in classes docs
### What is the issue about the documentation?

image

Page URL: https://api.qgis.org/api/master/classQgsGeometry.html https://api.qgis.org/api/3.34/classQgsGeometry.html

### PR DESCRIPTION
**Pull request by DelazJ**
Fixes #54990 
This was broken because of deprecated options still available in the config file while using a more recent doxygen version. I also updated the doxygen version in the github action to match the one used to build the official docs (1.9.8)

image

### CODE REVIEW

**Comment by DelazJ** [comment]
This should be backported to 3.34 and the 3.34 docs regenerated. BTW, should we not have the docs updated at every release point instead of just creating it for x.y.0?

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Thanks, this was a valuable tool which has been sorely missed. I wish we could show these in the PyQGIS docs too. @3nids have you ever looked into this?

**Comment by nirvn** [comment]
@DelazJ , merci!

**Comment by DelazJ** [comment]
Je t'en prie, @nirvn!

**Pull request merged**
