### PR TITLE
Fixed bug zoom to layer to WMS layer

### PR DESCRIPTION
**Pull request by LukinovD**
Fixed bug zoom to layer to WMS layer

Not properly identified bounding box from WmsCapabilities

### CODE REVIEW

**Comment by nyalldawson** [comment]
@LukinovD have you got an example server where this is an issue? Or a link to a QGIS bug report?

**Comment by nyalldawson** [comment]
@m-kuhn what do you think? Safest to close without merging? Or take the risk and merge?

**Comment by m-kuhn** [comment]
@arnaud-morvan, didn't you recently push some similar fixes? While this was on server side it was about multiple bboxes, so maybe you know a bit more about the specs of multiple bounding boxes.

**Comment by nyalldawson** [comment]
Closing due to lack of feedback

**Pull request closed without merging**
