### PR TITLE
[processing] some other test for qgis

### PR DESCRIPTION
**Pull request by ghtmtt**
commit messages contain the related test and file

hoping travis does not complain

### CODE REVIEW

**Comment by ghtmtt** [comment]
@m-kuhn is it normal that tests call `iface`? The test fails if the coordinates are taken from the canvas:

https://travis-ci.org/qgis/QGIS/builds/197017249#L922
https://travis-ci.org/qgis/QGIS/builds/197017249#L945

**Comment by m-kuhn** [comment]
In general it's better to not depend on `iface`.

They can call `iface`, there is even a canvas created in `iface` if required. But the canvas will probably not be in the same state than yours at the time of creating the tests.

**Comment by m-kuhn** [comment]
I think is the proper solution: make the CRS a new parameter. That will make the algorithm also usable in standalone apps and in the future on things like server.

If there is still the need for iface in a test, have a look at the [code here](https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsblendmodes.py#L58).

**Comment by ghtmtt** [comment]
thanks Matthias.. I'll try your suggestions..
Only problem is that I have to run directly the test on travis from the PR, I'm always stuck on my local machine..

**Comment by m-kuhn** [comment]
> Only problem is that I have to run directly the test on travis from the PR, I'm always stuck on my local machine..

I just had the same problem and when I tried looking into it, it suddenly disappeared after adding a `print('debug')` statement at the top of the file `AlgorithmsTestBase.py` and removing it again...

Btw, I also updated my comment above. I'm not sure what exactly we can do to test "Random*" algorithms. Maybe with 0 precision on vertex comparison, but not sure.

**Comment by ghtmtt** [comment]
> Actually, the random point algorithm will need some other means to check, because its result layer is not reproducible (it's random :) ).

Matthias, you are right.. random test is random ;) I didn't think about that.. 

> What should be checked here is probably that it produces the proper amount of points and possibly that they are inside a BBox

Ok.. can directly deal I with this or should we manage a way to change the tests for those algorithms?

**Comment by ghtmtt** [comment]
> I just had the same problem and when I tried looking into it, it suddenly disappeared after adding a print('debug') statement at the top of the file AlgorithmsTestBase.py and removing it again...

tried but not working.. still freezing there.. in fact, adding `print('debug')` at the top of `AlgorithmsTestBase.py` does not print anything on the terminal...

**Comment by m-kuhn** [comment]
Try the following:


    # In the import section
    import sys

    # At some places
    print(' #### arrived at debug point number 1', file=sys.stderr)

Interesting will also be the following in the `for` loop in `test_algorithms`:

    print('### Test {}'.format(algtest['name'], file=sys.stderr))

**Comment by ghtmtt** [comment]
Thanks! I get this output will all the lines added:

```
4: !!! prefix path was requested, but it is not valid - we do not run from installed path !!!
4:  #### arrived at debug point number 1
```

so it seems it freezes when calling the class right? The for loop never starts..

**Comment by m-kuhn** [comment]
Insert some more debug points until you find the import or command that freezes.

**Comment by ghtmtt** [comment]
ok I added some other print statements and maybe it freeze here:

```
if 'expectedFailure' in defs:
            exec(('\n'.join(defs['expectedFailure'][:-1])), globals(), locals())
            expectFailure = eval(defs['expectedFailure'][-1])
            print(' #### arrived at debug point number 15', file=sys.stderr)
```

so the last command run seems to be:
```
expectFailure = False
print(' #### arrived at debug point number 14', file=sys.stderr)
```

all the other if and else till the `load_param` function are not executed

**Comment by m-kuhn** [comment]
What's the content of `defs['expectedFailure']` when it freezes?

**Comment by ghtmtt** [comment]
I only get this:

```
4: E #### arrived at debug point number 8
4:  #### arrived at debug point number 9
4:  #### arrived at debug point number 10
4:  #### arrived at debug point number 12   
4:  #### arrived at debug point number 13
4:  #### arrived at debug point number 14
```

where: 
```

        expectFailure = False
        print(' #### arrived at debug point number 14', file=sys.stderr)

        if 'expectedFailure' in defs:
            exec(('\n'.join(defs['expectedFailure'][:-1])), globals(), locals())
            expectFailure = eval(defs['expectedFailure'][-1])
            print(' #### arrived at debug point number 15', file=sys.stderr)
```

**Comment by m-kuhn** [comment]
if 'expectedFailure' in defs:
            print('\n'.join(defs['expectedFailure']), file=sys.stderr)
            exec(('\n'.join(defs['expectedFailure'][:-1])), globals(), locals())

**Comment by ghtmtt** [comment]
same output of above:

```
4: E #### arrived at debug point number 8
4:  #### arrived at debug point number 9
4:  #### arrived at debug point number 10
4:  #### arrived at debug point number 12   
4:  #### arrived at debug point number 13
4:  #### arrived at debug point number 14
```

**Comment by m-kuhn** [comment]
In this case the `if` branch is probably not triggering and you need to insert another print after the `if` block ends (or in an `else` if present)

**Comment by ghtmtt** [comment]
ok.. I added printing anywhere:
```
        if 'expectedFailure' in defs:
            print('\n'.join(defs['expectedFailure']), file=sys.stderr)
            exec(('\n'.join(defs['expectedFailure'][:-1])), globals(), locals())
            print(' #### arrived at debug point number 15', file=sys.stderr)

        print(' #### arrived at debug point number 16', file=sys.stderr)

        if expectFailure:
            try:
                print(' #### arrived at debug point number 17', file=sys.stderr)
                alg.execute()
                self.check_results(alg.getOutputValuesAsDictionary(), defs['params'], defs['results'])
                print(' #### arrived at debug point number 19', file=sys.stderr)
            except Exception:
                print(' #### arrived at debug point number 20', file=sys.stderr)
                pass
            else:
                print(' #### arrived at debug point number 21', file=sys.stderr)
                raise _UnexpectedSuccess




        else:
            print(' #### arrived at debug point number 22', file=sys.stderr)
            alg.execute()
            print(' #### arrived at debug point number 23', file=sys.stderr)
            self.check_results(alg.getOutputValuesAsDictionary(), defs['params'], defs['results'])
            print(' #### arrived at debug point number 24', file=sys.stderr)

        print(' #### arrived at debug point number 25', file=sys.stderr)
```

and I get this:

```
4: E #### arrived at debug point number 8
4:  #### arrived at debug point number 9
4:  #### arrived at debug point number 10
4:  #### arrived at debug point number 12   
4:  #### arrived at debug point number 13
4:  #### arrived at debug point number 14
4:  #### arrived at debug point number 16
4:  #### arrived at debug point number 22
```

**Comment by m-kuhn** [comment]
Well then, seems to be `alg.execute()` that is causing troubles...

Next step will be to check if it's a particular algorithm that fails (print `alg.name`) or some generic code in `python/plugins/core/GeoAlgorithm.py`

**Comment by ghtmtt** [comment]
Matthias, first steps here.. and some discovery..

I just commented the `yaml` list and made some cheke:

* clip freezes the test
* when I comment the whole file except for one of the last algorithms already merged in master (zonalstatistic, meancoordinates, etc), the test fails saying:

```
======================================================================
4: ERROR: __main__.TestQgisAlgorithms.test_algorithms (nose2.loader.LoadTestsFailure)
4: ----------------------------------------------------------------------
4: TypeError: exceptions must derive from BaseException
4: 
4: ----------------------------------------------------------------------
4: Ran 2 tests in 1.057s
4: 
4: FAILED (errors=1)
4: CMake Error at ProcessingQgisAlgorithmsTest.cmake:22 (MESSAGE):
4:   Test failed: 1
4: 
4: 
```

**Comment by m-kuhn** [comment]
Good job!

**Comment by ghtmtt** [comment]
not my credit ;) 
BTW, is that an error introduced by some *recent* commit? because that's pretty weird that from a day to another I cannot run local tests anymore..

**Comment by m-kuhn** [comment]
No idea... But it would be great if you could also add some debug statements inside the clip algorithm to check what exactly makes it freeze on your machine. That doesn't sound like sane behavior to me. And if you can tell people at the conference that you also fixed bugs, even better for you ;)

**Comment by ghtmtt** [comment]
eheh not a normal behavior at all!
and also very strange that on travis the tests run fine while I get these errors of above with correct algorithms and tests.

for the debugging, are you suggesting something in particular?

**Comment by m-kuhn** [comment]
Find out where it freezes

https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/qgis/Clip.py

**Comment by ghtmtt** [comment]
Ok I cannot fin d the error in clip alg yet..

For the second error I mention, that on my machine test fails while they go straight on travis.. 

https://github.com/qgis/QGIS/pull/4089#issuecomment-276630198

do you have some ideas?!

**Comment by m-kuhn** [comment]
Not sure, there is not much information to be seen in the output (line numbers, type names...)

**Comment by ghtmtt** [comment]
I rebased and fixed some conflicts.. For the moment I delete the random tests that fails because of the randomness of the algorithm ;)
If travis does not complain this PR is for Voronoi algorithm of QGIS core

**Comment by ghtmtt** [comment]
travis fails for another test not related with the ProcessingQGIS (6 - qgis_indentation (https://travis-ci.org/qgis/QGIS/builds/197577735#L1526)

could it be related to the rabasing and conflict fixing?

**Comment by ghtmtt** [comment]
ok.. maybe it is easier to create another cleaner PR. See #4099
Could we delete this PR?

**Comment by DelazJ** [comment]
@ghtmtt actually I think you could try `git rebase upstream/master` on your branch (see https://git-scm.com/docs/git-rebase) to clean and fix conflicts instead of using `git merge upstream/master` (assuming upstream is the name of the remote repository)

**Comment by ghtmtt** [comment]
@DelazJ thanks for the hint! I checked out the master branch, run `git pull upstream master` then checked out the other branch and run `git rebase master`.
You solution is faster right?

**Comment by DelazJ** [comment]
Yes but in your case, both master and other_branch are now based on upstream/master while my solution only updates other_branch.
Anyway, in both cases, your other_branch should be rebased and once pushed to github, only your commits would be listed and not previous commits from other devs as exposed in the current PR.

**Comment by ghtmtt** [comment]
Ok.. I think in this case rebase could not been performed so it creates a merging commit?

**Comment by DelazJ** [comment]
> I think in this case rebase could not been performed 

You mean you got a report about a possible conflict in a (some) file(s)? In this case, you need to open the concerned file(s) in your text editor and choose the chunk you want to keep (those you committed, I assume). https://help.github.com/articles/resolving-merge-conflicts-after-a-git-rebase/

**Pull request closed without merging**
