### PR TITLE
Convert the print function to be compatible with Python 3

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by sbrunner** [comment]
Just fixed unrelated style error :-)

**Comment by m-kuhn** [comment]
Did you pick a specific selection of python files to update or just some random ones?
Did you use a script to perform the update?

**Comment by sbrunner** [comment]
I think that I get all the files ...

For the first commit I do (as I write in the commit :-) ): `2to3 -fprint -wm .`
For all others I do them by hand :-)

Thanks :-)

**Comment by jef-n** [comment]
my approach is to change our python files, so that they still work with py2qt4 and can be automatically converted with scripts/2to3 to py3qt5.   Next step would be to change scripts/2to3 to migrated from py2qt4 to  py2qt4/py3qt5 - so that we can apply it to the main code and it works with both.

**Comment by sbrunner** [comment]
@jef-n I'm not sure to understand your comment, for me this pullrequest follows your approach and do just a step for the print...

**Comment by sbrunner** [comment]
@m-kuhn should I close this?

**Comment by m-kuhn** [comment]
It's probably harder to rebase this PR than to implement the missing things on the latest code.

**Pull request closed without merging**
