### PR TITLE
Further optimization to OriginalXmlProperties

### PR DESCRIPTION
**Pull request by nirvn**
## Description

@elpaso , as discussed in your OriginalXmlProperties optimization PR.

### CODE REVIEW

**Comment by elpaso** [comment]
After https://github.com/qgis/QGIS/pull/40500 this is not necessary anymore, I've run the speed tests and there is just a tiny difference (less than 20 ms on 15'253 ms of total time with more than 700 vector layers and rather complex symbology). 

If you want to go ahead anyway, then I would recommend to move the validity check to https://github.com/qgis/QGIS/pull/40506/files#diff-1ef9764fa0bcd5fabfbf51974955fec2940df478ac3c7f27bacd70bb6d194b0eR325

**Comment by nirvn** [comment]
@elpaso , moving the validity check to where? The hyperlink doesn't point to a specific line.

**Comment by elpaso** [comment]
> @elpaso , moving the validity check to where? The hyperlink doesn't point to a specific line.

Apparently linking to a specific line which is not shown by default is now broken on github, I meant line 325:


```
    if ( l )
```

**Comment by nirvn** [comment]
@elpaso , got it, better place indeed. Even though it isn't much of a gain, I'd be inclined to still commit it. Agreed? I'll update the PR.

**Comment by elpaso** [comment]
@nirvn honestly I'm not sure (I'm -0): I still think that even if we are not using it right now, having a copy of the original properties might be useful to restore the style to its initial state or for some plugins to manipulate the styles, I know that there are other ways to achieve the same goal (export the style, reload the project etc.). 

Also, the API docs say that 

```
Returns the XML properties of the original layer as they were when the layer
was first read from the project file. In case of new layers this is normally empty.
```

so, we are breaking the promise and the docs needs changed.

On the other hand we have a very small speed gain, probably not measurable in "normal" projects (less than 100 layers?).

**Comment by nirvn** [comment]
OK, since there's an established behavior through doc, I'll go with your -0 and close. 

For posterity: I'm surprised this avoidance of the DOM document creation didn't result in more of a speed boost. Good to know.

**Comment by nyalldawson** [comment]
Manually backported to https://github.com/qgis/QGIS/pull/40370

**Comment by nyalldawson** [comment]
Oops, not this one!

**Pull request closed without merging**
