### PR TITLE
Update issue link in Readme.md

### PR DESCRIPTION
**Pull request by ghtmtt**
## Description
Not big changes, just updates the link of the issue tracker in the Readme file that now is github

### CODE REVIEW

**Comment by m-kuhn** [comment]
@rduivenvoorde is this the new link or will issues.qgis.org be redirected or will there be a new alias for the URL?

**Comment by rduivenvoorde** [comment]
I do not know, I think that is an open question...

IF we redirect issues.qgis.org to https://github.com/qgis/QGIS/issues/ NOW already, then we loose google memory and the fact that we wanted a readonly issues.qgis.org around for some time..

So maybe best to keep pointing issues.qgis.org to the redmine machine, but put a redirect there to some page where we tell people that we moved and then redirect after 10 secs or so?

**Comment by Gustry** [comment]
Please keep the link for files which are hosted on issues.qgis.org, for instance this ticket: https://github.com/qgis/QGIS/issues/27894 the GIF is still hosted on issues.qgis.org.

@rduivenvoorde Is-it possible to add a header on a ticket detail URL such as https://issues.qgis.org/issues/21536 for mentioning that this repository is now archived and readonly?

**Comment by m-kuhn** [comment]
I agree we should keep the read only link to issues on issues.qgis.org for the foreseeable future. If such a header is possible, even better.

Some possibilities that should be compatible with the above solution and potentially make live easier:

 * Forward issues.qgis.org (the main page) to the new tracker
 * Have an alias tracker.qgis.org pointing to github
 * Or we just don't do any of these and start promoting https://github.com/qgis/QGIS/issues/ as the URL for the issue tracker

**Comment by m-kuhn** [comment]
Looks like this is best for now, thanks @ghtmtt

**Comment by DelazJ** [comment]
Should we also update https://qgis.org/en/site/getinvolved/development/bugreporting.html?

**Comment by ghtmtt** [comment]
@DelazJ well I think so :)

**Pull request merged**
