### PR TITLE
Made python initialization less verbose

### PR DESCRIPTION
**Pull request by carolinux**
The python initialization for when the server option was set and when not was pretty much the same thing copy pasted. I broke it down into more functions and saved about 80 lines of code. I also think that the two init functions where a bit out of sync, since the server init was importing the user's startup.py and the regular one not (unless there was a reason for that)

The git diff view is very confusing for reviewers - I'd look at the end file. But if the only difference between the server init was the interface init and the server init , then this PR correctly reuses the rest of the code.

### CODE REVIEW

**Comment by m-kuhn** [comment]
It would be good if @elpaso could give it a look. AFAIK he implemented the server python code.

**Comment by carolinux** [comment]
No, I think protected would make sense as well.

**Comment by elpaso** [comment]
Sorry, I have really no time to review the code right now. If it's not too late we can discuss it during the HF.

**Comment by m-kuhn** [comment]
@carolinux will you be at the HF?

In general I am in favor of consolidating duplicate code, I just want to be sure there are no unexpected side-effects. Could you update the PR so internal methods are not public and write some doxygen headers at least for public methods?

**Comment by carolinux** [comment]
What's the HF?
Yes, I will make the methods protected and write doxygen headers.

**Comment by m-kuhn** [comment]
The HF is the [QGIS hackfest/developer conference in Nødebo, DK](https://hub.qgis.org/wiki/quantum-gis/13_QGIS_Developer_Meeting_in_Copenhagen_2015). Definitely a nice meeting to attend if you want to get to know other QGIS developers!

**Comment by carolinux** [comment]
Yes, I will be there. :)

**Comment by m-kuhn** [comment]
@elpaso did you have the time to look at/discuss this at the HF?

**Comment by elpaso** [comment]
@m-kuhn yes (we discuss it) and in general it looks fine to me but I had/have no time to test it. I've been busy on the QGIS server refactoring. What I remember from that part of the code is that there might be some subtle minimal differences from the desktop initialisation code and the server initialisation code.

**Comment by timlinux** [comment]
Just bumping on this @carolinux can you get the tests passing again?

**Comment by carolinux** [comment]
@timlinux Seems to have been an arbitrary failure at the time it was pushed. Pleeease merge this, it's beginning to smell. :-p

**Comment by elpaso** [comment]
Merged with https://github.com/qgis/QGIS/issues/2233

**Pull request closed without merging**
