### PR TITLE
Backport Avoid "Failed to load file "/style.qss"" startup error

### PR DESCRIPTION
**Pull request by rldhont**
## Description

cherry-pick 374b75696d5f10fa3989410c422eec21167e845b

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
I can't remember the circumstances around this commit - is it just a warning? Or actually a bug? If it's just a warning I'd rather play it safe and avoid the change in our final 2.18 release.

**Comment by rldhont** [comment]
I found your fix, because I can't use QGIS 2.18 on my Ubuntu 18.04. I found that this fix was done in QGIS 3. Why not backports it for the final 2.18 to avoid an unnecessary warning ?

**Comment by nirvn** [comment]
A warning is harmless. Changing what's not broken might create unknown issues. I'd say living with a known harmless warning is better than an unknown :)

**Comment by rldhont** [comment]
@nirvn I agree but this warning has been removed in the new QGIS versions, so the harmless warning has been already removed...

**Comment by nyalldawson** [comment]
Mmm.. I'd rather a harmless warning then introducing the risk of potential regressions in the final 2.18 release.

**Comment by rldhont** [comment]
If it's a probable regression, there is a regression in QGIS 3,. I just cherry-pick the code of QGIS 3.4 the new LTR.

**Comment by nirvn** [comment]
@rldhont , QGIS 3 code is actively developed. If we would ever to find a regression, we'd push a fix for a subsequent release.

2.18 is about to reach its end of life, ie no more releases, no more opportunities to fix bugs.

**Comment by nyalldawson** [comment]
There's also the fact the the whole app initialisation changed substantially over 3.0 (and since), with the introduction of user profiles. It's quite possible there was other follow up commits which altered the behaviour here.

**Comment by m-kuhn** [comment]
I agree that for 2.18 in the current state of the product cycle only bugfixes with very low risk of side effects and high potential of improving usability and reliability are acceptable.

**Comment by nyalldawson** [comment]
I don't usually backport to 2.18 by default, only if a client requests it.

**Comment by rldhont** [comment]
Thanks for your answer, for my customers, the LTR is always the priority.

**Comment by nyalldawson** [comment]
Just to clarify -- obviously I'm usually happy for someone to take one of my fixes and do the work backporting it. I just think the timing is wrong for any fixes with any potential risk to be backported. And in this case, the risk far outweighs the reward (a harmless warning which has been thrown for years). If we had any more point releases planned then I'd have agreed.

**Comment by rldhont** [comment]
I understand. I have changed my computer 1 mounth ago and I have some trouble with QGIS 2.18 on my ubuntu (I can't use it, some segfault in QT4). Then I found your commit and I thought it can help so I propose this PR. I know that 2.18 is in its last points release but I will need to use it after its EOF.

**Comment by m-kuhn** [comment]
> I understand. I have changed my computer 1 mounth ago and I have some trouble with QGIS 2.18 on my ubuntu (I can't use it, some segfault in QT4).

Does this pull request fix a segfault?

**Comment by rldhont** [comment]
Not at all

**Pull request closed without merging**
