### PR TITLE
Update db manager and console png's

### PR DESCRIPTION
**Pull request by pkinglinz**
## Update db manager and console png's
Updated the dbmanager and main console png's with current qgis style svg's

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nirvn Can you take a look at this?

**Comment by m-kuhn** [comment]
Do you have a screenshot?

**Comment by pkinglinz** [comment]
I will get a screen shot tomorrow @m-kuhn

**Comment by nirvn** [comment]
@nyalldawson , @pkinglinz , I'll review this within the next 24 hours. Thanks.

**Comment by pkinglinz** [comment]
currently broken as neither dbmanager or buffer svg's displaying properly, will fix in the next couple of days

console

but here is the screen shot of the console icons

**Comment by m-kuhn** [comment]
Thanks, @Cracert do you have some feedback?

**Comment by pkinglinz** [comment]
dbmanager and python console at 24px from the plugin toolbar
dbmanager

**Comment by pkinglinz** [comment]
buffer.svg now displays, here is screen shot
buffer_svg
 the blue is different but matches blue used in other icons so would prefer to leave and update the other icons to match

still need to remove icons from original folders and double check there are no references to this location

**Review by nirvn — CHANGES_REQUESTED** [review]
@pkinglinz , I've had a look at your SVG icons. First, thanks for your effort here, it's most welcome, and hope we'll see much more from you 😄 

Your icons are looking great. That said, I've noticed that your SVGs rely on millimeter unit, which isn't ideal, and can prevent sharp icons. Could you update your icons and set the unit to pixel. Then, review all of your outlines to ensure it's set to a nice pixel number (e.g. 1px, not 0.999998px).

Some icons would also benefit from more precise node placement. For e.g., the console's show editor icon has nodes that don't perfectly align to the pixel grid. In Inkscape, once you set your SVG unit to pixel, you can use the node editor to adjust the position. Again, 14.5px is preferable to 14.512px. 

When that's fixed, we're ready to go. Can't wait for that new db manager icon to show up on my screen everyday 😉

**Comment by pkinglinz** [comment]
@nirvn thanks for the review and great advice will get onto it in the next few days :)

**Comment by Cracert** [comment]
@pkinglinz - great work!  
Please consider also optimization of SVG size. 

- [SVG Cleaner](https://github.com/RazrFalcon/svgcleaner-gui) or
- online [SVGOMG](https://jakearchibald.github.io/svgomg/)

**Comment by pkinglinz** [comment]
@nirvn @Cracert i have tried to optimize the db manager icon (dbmanager.svg), changed the units to pixels and rounded the units, could you have a look at the dbmanager icon again for me? thanks, its definitely appreciated

**Comment by nirvn** [comment]
@pkinglinz , could you resolve the conflicts indicated in this PR? I'll do a last review afterwards.

**Comment by nyalldawson** [comment]
Any chance of movement on this one? I'd love to reuse the new python console icon from this in the recent work done to show python scripts in the browser...

**Comment by p-e-king** [comment]
sorry ive been a bit slack finding time to allign the other icons, i could do a separate fork and pull just with the python console icons, but will have a look tomorrow and see how far i can get through them

**Comment by m-kuhn** [comment]
What's the status on this? Looking at the conflicts I suspect is has been superseded by other commits, but not sure if we can close it?

**Comment by pkinglinz** [comment]
@m-kuhn I'm going to slowly add the other icons as separate pull requests so have closed this one

**Comment by nyalldawson** [comment]
@pkinglinz @nirvn any chance we could cherry-pick these icons and commit? I'd hate to see these nice improvements go unmerged!

**Comment by p-e-king** [comment]
@nyalldawson i will definitely add these in, will try and sort it out during a couple of random days I have before xmas

**Pull request closed without merging**
