### PR TITLE
[WFS provider] Remove event loop in iterator causing crashes

### LINKED ISSUE #32913: Legend causing a crash
I use a WFS service. https://mapprod3.environment.nsw.gov.au/arcgis/services/Planning/EPI_Primary_Planning_Layers/MapServer/WFSServer?request=GetCapabilities&service=WFS 

It works fine until I go into my layout and add a legend. Once the legend is added - the file crashes. Everytime. 

Is it the WFS or QGIS causing the problem.

QGIS version
3.8.1-Zanzibar
QGIS code revision
dcd95cc648
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
2.4.1
Running against GDAL/OGR
2.4.1
Compiled against GEOS
3.7.2-CAPI-1.11.0
Running against GEOS
3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version
9.2.4
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
5.2.0
Running against PROJ
Rel. 5.2.0, September 15th, 2018
OS Version
Windows 10 (10.0)

Stack Trace

QRasterPaintEngine::transformChanged :
QPainter::translate :
QGraphicsScene::drawForeground :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
Qd OS versions**WidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidgetPrivate::syncBackingStore :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processExposeEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QWindowSystemInterface::flushWindowSystemEvents :
DispatchMessageW :
DispatchMessageW :
GetSystemMetrics :
KiUserCallbackDispatcher :
NtUserDispatchMessage :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

### PR DESCRIPTION
**Pull request by rouault**
Fixes #32913

Will need to be backported to 3.10 but will have to be done manually due to file renaming

### CODE REVIEW

**Comment by nirvn** [comment]
@rouault , thanks for tackling this one, loads of issues filled on this one over time.

**Comment by rouault** [comment]
The Windows failure seems to be completely unrelated
```
The following tests FAILED:
	164 - qgis_texteditwrapper (Failed)
```

**Comment by rouault** [comment]
> The Windows failure seems to be completely unrelated

confirmed. another PR https://github.com/qgis/QGIS/pull/34006 fails for the same reason

**Comment by luipir** [comment]
> confirmed. another PR #34006 fails for the same reason

IMHO wrong issue reference ?

**Comment by luipir** [comment]
> IMHO wrong issue reference ?

how! sorry is referred to CI

**Comment by roya0045** [comment]
I get the same error on one of my PR, its just pipeline having issues.

**Review by nyalldawson — APPROVED** [review]
Looks great to me!

**Pull request merged**
