### PR TITLE
Georeferencer fixes, pt 2

### PR DESCRIPTION
**Pull request by nyalldawson**
Follow up https://github.com/qgis/QGIS/pull/47141 

Supersedes https://github.com/qgis/QGIS/pull/46941

### CODE REVIEW

**Comment by roya0045** [comment]
I'm not sure how the changes of 46941 are integrated in this, as far as I understand the number of columns are the same, the main difference is that changing the value of the point in the table now changes the crs of the stored point and the values stored in the point.

The approach proposed in 46941 was to exposed the hidden values of the points, that way the user could maintain the stored coordinates in the intended crs and still change the initial or transformed values as needed. This would be needed if the stored values of the point are in a distinct crs than the output and would need a tweak( such as using known geographic coords on a map). Now the used would need to change the target crs for the whole widget to the ones of the points that need a change to 'expose' the values in the proper way and then give them the correct values before reverting back. I agree those cases may be rare, but I don't think the proposed changes make this convivial.

Wether that behavior is worth crowding up the table with two extra columns, I assumed we had enough room for it.

**Comment by gioman** [comment]
> but I'd value wider feedback (ping @gioman

agree.

**Comment by roya0045** [comment]
I'm fine with either, it's a tradeoff, my only worry was with multiple change in crs, was if the points could 'drift' . Hence why I wanted to keep the original coords and transform them, though this fear might be unfounded.

As for the output crs I think we could fit it at the bottom of the window.

**Comment by nyalldawson** [comment]
> my only worry was with multiple change in crs, was if the points could 'drift

That's indeed a valid concern! I think it's only an extreme corner case though -- it would only have an impact on results when:

1. A user is georeferencing something with high accuracy requirements
2. They enter some points in one crs (with high accuracy!)
3. They engage in multiple cycles of changing the target crs, and then modifying the destination coordinate (either manually in the table, or via the move point tool)

Step 3 is the big one here. If they don't do multiple cycles of change crs+move point, then there's only a single transform involved at the actual "run georeference" time.

I can't see this affecting real world use cases as a result, so that pushes me to the simpler interface/UX option.

**Pull request merged**
