### PR TITLE
force time to be UTC for mesh layer

### LINKED ISSUE #43242: Incorrect mesh layer visualisation with layout temporal range override
**Describe the bug**
I am using  a data defined override to set the temporal range of a map in a layout. The override for both the start and end is set based on fields in the atlas coverage layer (which are just datetime fields). When the temporal range is set this way the mesh layer in my project renders with the incorrect temporal range. Other temporally aware elements (e.g. vectors, layout labels with expressions) draw with the correct timestep. 

When the override is cleared (not just deactivated but cleared) and the temporal range is replaced with the same values the mesh draws with the correct temporal range. The mesh also draws correctly using the temporal controller in the main window. I have tested with GRIB and 2dm+XMDF meshes and the problem is present with both.

1. Main view - mesh (rainbow colors in background) displaying correctly
MainView

2. Temporal range set by expression - temporal range evaluates to correct range (seen to right of image) but mesh displays incorrectly, vectors / layout label drawing correctly
LayoutWithExpression

3. Temporal range set by values - mesh displays correctly
LayoutHardcoded

**How to Reproduce**
I can provide a dataset / project on request.

**QGIS and OS versions**

> QGIS version
> 3.18.3-Zürich
> QGIS code revision
> 735cc85be9
> Compiled against Qt
> 5.11.2
> Running against Qt
> 5.11.2
> Compiled against GDAL/OGR
> 3.1.4
> Running against GDAL/OGR
> 3.1.4
> Compiled against GEOS
> 3.8.1-CAPI-1.13.3
> Running against GEOS
> 3.8.1-CAPI-1.13.3
> Compiled against SQLite
> 3.29.0
> Running against SQLite
> 3.29.0
> PostgreSQL Client Version
> 11.5
> SpatiaLite Version
> 4.3.0
> QWT Version
> 6.1.3
> QScintilla2 Version
> 2.10.8
> Compiled against PROJ
> 6.3.2
> Running against PROJ
> Rel. 6.3.2, May 1st, 2020
> OS Version
> Windows 10 (10.0)
> Active python plugins
> db_manager; 
> MetaSearch; 
> processing
>

### PR DESCRIPTION
**Pull request by vcloarec**
Force the override time in the map layout properties to be UTC.
fix #43242 and make consistent the time specification of the override temporal range with the temporal range given by the date/time edit widget of the main canvas and of the layout properties.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Is it correct to overwrite/force the time spec in data defined? It looks to me like this should rather be done in the expression engine or data providers where there is more context about the interpretation for conversions.

(I haven't looked deeply into the time management code, so the following statement may be ignoring practices done throughout the qgis code base.)

**Comment by vcloarec** [comment]
@m-kuhn make me thinking about...
The aim was to make consistency between the UI widget for setting the time (time controller widget of the main map canvas and date/time edit of temporal range of the layout map item, time spec of this UI object are UTC) and the override result. This inconsistency leads to a time offset issue with mesh layer.
But maybe it is better to force this UTC spec at the mesh layer level (as the last commit), to prevent issue coming from elsewhere.
On the other hand, there still be the time specification inconsistency between UI widget and override result...

**Comment by vcloarec** [comment]
not stale

**Review by PeterPetrik — APPROVED** [review]

**Comment by PeterPetrik** [comment]
lets make it this way as a workaround for the release

**Pull request merged**
