### PR TITLE
[FEATURE] Style manager improvements

### PR DESCRIPTION
**Pull request by nyalldawson**
Some improvements to style manager:

- Adds the style manager action to the file toolbar. I know that we are trying to avoid adding new icons, but this one is rather important and I think it needs the improved discoverability which placing on a toolbar gains.

- Makes the style manager dialog non-modal. Now it acts just like the layout manager dialog -- clicking the action opens the dialog, or brings it to the front if it's already open.

### CODE REVIEW

**Comment by nirvn** [comment]
Non modal will require us to stress test situations when both the style dock and the style manager are opened. Out of memory from when I worked on improving the manager, I think the style dock's symbol widget list listens to signals to update its list, I think the reverse isn't working yet. Ie if you save (or edit via right click) a new symbol in the style dock, the manager might not update ATM.

**Comment by nyalldawson** [comment]
> Non modal will require us to stress test situations when both the style dock and the style manager are opened. Out of memory from when I worked on improving the manager, I think the style dock's symbol widget list listens to signals to update its list, I think the reverse isn't working yet. Ie if you save (or edit via right click) a new symbol in the style dock, the manager might not update ATM.

yes, that's fixed. There may still be other connections needed, but let's tackle them when identified. I couldn't find any in my tests at least.

**Comment by nirvn** [comment]
Code looks good.

This creates a bit of a visual confusion, whereas the style dock toggle button and the style manager button both share the same icon. Thoughts on this?

**Comment by nyalldawson** [comment]
> This creates a bit of a visual confusion, whereas the style dock toggle button and the style manager button both share the same icon. Thoughts on this?


We should make a reworked version for this dialog, I think. One that conveys better that it's a window.

**Pull request merged**
