### PR TITLE
fix edge search in mesh element tool

### PR DESCRIPTION
**Pull request by vcloarec**
In the mesh element editing tool, when searching for hovered edge, distance precision was too high when the map coordinate system is Geographic, leading to highlight wrong edges.
This PR fix this issue.
Thanks to @uclaros to have pointed this issue.

### CODE REVIEW

**Comment by uclaros** [comment]
`QgsPointXY::sqrDistToSegment()` is also used without an explicit epsilon in `QgsMeshLayer::closestEdge()`: https://github.com/qgis/QGIS/blob/763bb91f6b19b1ea7299e77f2aa954506d303764/src/core/mesh/qgsmeshlayer.cpp#L780-L793

I'm not exactly sure where this is used, but could it not cause a similar issue with geographic coordinates?

**Comment by vcloarec** [comment]
> but could it not cause a similar issue with geographic coordinates?

Yes, you are right!

**Comment by uclaros** [comment]
Should we also have a test for that?

**Review by uclaros — APPROVED** [review]
Nice!

**Pull request merged**
