### PR TITLE
[trivial][build system] Install PDF4QT files to CMAKE_INSTALL_???DIR

### PR DESCRIPTION
**Pull request by espinafre**
Some Linux distros encourage that libraries be installed to /usr/lib64 instead of /usr/lib; such is the case of Gentoo, there might be others. This is to ensure that the default lib install directory for PDF4QT (either lib or lib64 or something else) is selected by CMAKE itself. The PDF4QT_INSTALL_BIN_DIR_IMPL line was changed for consistency.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Can you upstream this change before opening it here?
I don't think we want to maintain a patched version?

**Comment by espinafre** [comment]
> Can you upstream this change before opening it here? I don't think we should maintain a patched version here. Maybe you can also avoid using this vendored version?

Sure, I'll try upstream first. Contacting them hadn't ocurred to me before, since this piece of code is in the QGIS tree.

I'm not sure what you mean by "using this vendored version". Are you referring to PDF4QT itself? TIA for the clarification.

**Comment by m-kuhn** [comment]
> Sure, I'll try upstream first. Contacting them hadn't ocurred to me before, since this piece of code is in the QGIS tree.

Thanks

> 
> I'm not sure what you mean by "using this vendored version". Are you referring to PDF4QT itself? TIA for the clarification.

Yes exactly, QGIS has a tradition of copying external code, something called "vendoring". Sometimes to make deploying dependencies easier, sometimes to adopt undermaintained libraries. In this case it was probably deployment.

**Comment by espinafre** [comment]
> > Sure, I'll try upstream first. Contacting them hadn't ocurred to me before, since this piece of code is in the QGIS tree.
> 
> Thanks
> 
> > I'm not sure what you mean by "using this vendored version". Are you referring to PDF4QT itself? TIA for the clarification.
> 
> Yes exactly, QGIS has a tradition of copying external code, something called "vendoring". Sometimes to make deploying dependencies easier, sometimes to adopt undermaintained libraries. In this case it was probably deployment, so if gentoo has that, better stick to that. There are many `WITH_INTERNAL_XXX` switches.

Now it is clear to me that you meant to use the distro's version instead of this one shipped with QGIS. Unfortunately Gentoo doesn't have PDF4QT in its repos, but there are other to make it work (it involves creative use of sed at build time :) ). I couldn't even build the standalone upstream version on my system, it has diverged from this version in QGIS.

Closing until we figure some other solution. Thanks again for your patience!

**Comment by nyalldawson** [comment]
@m-kuhn 
> this case it was probably deployment,

Actually it was because I had to patch back in qt5 support

**Comment by m-kuhn** [comment]
Thanks for clarification @nyalldawson 
In this case we can patch without waiting for upstream?

**Comment by nyalldawson** [comment]
@m-kuhn upstream are responsive, I'd like to see an attempt made to upstream first 👍

**Pull request closed without merging**
