### PR TITLE
[Server] Reactivate the capability to print selection with Server 3.4

### PR DESCRIPTION
**Pull request by rldhont**
## Description
The capability to print selection has been removed by the commit aaa7003 to
prevent accidental selections showing in exports from composer.

It is reactivated only for QGIS Server.

Fixes #13459 QGIS Server WMS GetPrint request don't respect SELECTION parameter

It's a forward porting of #7185

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by tudorbarascu** [comment]
@rldhont Do you also plan to add a test for this one?

**Comment by pblottiere** [comment]
> @rldhont Do you also plan to add a test for this one?

+1

**Comment by nyalldawson** [comment]
@rldhont 

From #7185

> A different approach is needed for 3.0 - this will need to become a new flag in the layout context

Can you take this approach please?

**Comment by pblottiere** [comment]
The code looks good, thanks @rldhont :+1:!

**Review by nyalldawson — CHANGES_REQUESTED** [review]
Please don't add these as methods to the QgsLayoutItemMap API - instead they should be added as a new flag to QgsLayoutRenderContext::Flag

**Comment by rldhont** [comment]
thanks @nyalldawson to point to me ` QgsLayoutRenderContext::Flag`
I'll update the code today for tomorrow.

And I'll add (or reactivate the test)

**Comment by pblottiere** [comment]
@nyalldawson OK, thanks for your input :).

**Comment by pblottiere** [comment]
> Please don't add these as methods to the QgsLayoutItemMap API - instead they should be added as a new flag to QgsLayoutRenderContext::Flag

@nyalldawson By the way, is there some kind of code documentation/comment about this topic?

**Comment by rldhont** [comment]
@nyalldawson I have updated the code to use `QgsLayoutRenderContext::Flag`

**Comment by nyalldawson** [comment]
Looks good!

**Comment by nyalldawson** [comment]
>  By the way, is there some kind of code documentation/comment about this topic?

Only what's in the dox. But it's following the same model as QgsRenderContext.

**Comment by rldhont** [comment]
@tudorbarascu and @pblottiere the test already exist but does not fail!

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
This is good to merge from my opinion. @pblottiere ?

**Comment by rldhont** [comment]
@nyalldawson the code seems good, but the test does not failed, selection has not been drawn.

@pblottiere I think the code has to be merged for 3.4.0, because it made some needed changes in layout. I investigate where the error comes from.

**Comment by pblottiere** [comment]
> I think the code has to be merged for 3.4.0, because it made some needed changes in layout. I investigate where the error comes from.

OK, but we should definitely come back to this later...

**Review by pblottiere — APPROVED** [review]

**Comment by rldhont** [comment]
@nyalldawson I found that layout render context flags are overwritten by export render context. So the draw selection flag has to be set at the export time!

**Comment by rldhont** [comment]
@nyalldawson I have updated the code and it works

**Comment by nyalldawson** [comment]
Looks good, but you better also set the flag for the svg output for consistency...

**Comment by nyalldawson** [comment]
I.e. around line 398

**Comment by rldhont** [comment]
@nyalldawson done

@pblottiere Can I merge before travis build ?

**Pull request merged**
