### PR TITLE
[processing] Allow saving outputs directly to SAP HANA databases

### PR DESCRIPTION
**Pull request by nyalldawson**
Given that SAP supports the connection api, this should just work

### CODE REVIEW

**Comment by nyalldawson** [comment]
@mrylov @stefanuhrig  I'm unable to test this -- can you give this a build and confirm whether it works?

The process looks something like this:

Peek 2021-01-28 10-18

However, I get a crash at the end of this screencast -- looks like  QgsHanaConnection::execute doesnt' gracefully handle the situation where mConnection is not available. Are you able to investigate this too?

**Comment by mrylov** [comment]
@nyalldawson, thanks. I'll look into the issue.

**Comment by mrylov** [comment]
@nyalldawson, all found issues have been fixed in #41263.

**Comment by nyalldawson** [comment]
Thanks @mrylov ! Can you confirm that saving direct to sap is working from processing and that this pr should be merged?

**Comment by mrylov** [comment]
@nyalldawson, I confirm, it is working.

**Comment by nyalldawson** [comment]
Thanks @mrylov !

**Comment by mrylov** [comment]
Thank you @nyalldawson!

**Pull request merged**
