### PR TITLE
Improved and semi automated bad layer handling

### PR DESCRIPTION
**Pull request by roya0045**
## Description
This PR aims to make handling bad layer less painful.

The basic gist is that layers are often clustered together and the current bad layer handler forces someone to change all the path.

The goal is to keep track of the basepaths associated with layers and propagate the same modification to all other layers sharing the exact same basepath.

This PR has not been tested yet.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
Nice improvement.

**Comment by roya0045** [comment]
> Nice improvement.

Thanks! I realized I made I made some mistakes in my eagerness ( not using a proper c++ IDE leads to overishgts). I just hope this workflow will work properly.

Currently the checks occurs in the main apply loop, they could be made in another loop just before to ensure that fixes at any point will happen to every similar basepath and not just the ones following the change. This would create two loops, I'm not sure its worth it. Any opinion on that @nirvn @nyalldawson  and anyone else?

**Comment by elpaso** [comment]
Can you please reformat the PR (use `astyle.sh` from the `scripts` directory), the diff is unreadable to me.

**Comment by roya0045** [comment]
> Can you please reformat the PR (use `astyle.sh` from the `scripts` directory), the diff is unreadable to me.

Yes I'm working on it ( I don't have the necessary access here ATM but I'll try to fix it manually). I have no clue why but enconding on the computers that I use tend to mess up cpp and h files, hence why I try to only use the web app.

**Comment by roya0045** [comment]
> Can you please reformat the PR (use `astyle.sh` from the `scripts` directory), the diff is unreadable to me.

In the diff settings you can hide whitespace changes to see the core of the changes.

I am trying everything I can, I even did a hex dump of my file and the one from source and the characters are exactly the same. I have no clue what might be causing this issue.

As for running astyle I am having too many troubles with cmake at the moment and fixing the cmake build would take me far too long.

If you wish you could take these changes and create a new PR from it.

**Comment by DelazJ** [comment]
@roya0045 Are you on Windows? IOW could this have to do with line endings (kind of CRLF vs LF configs)? I'm using the Github desktop program on windows and weeks ago I had to choose a related option that popped up (`autocrlf` setting?) and since I'm always fighting with file diffs showing all the file replaced when doing a simple change (at the end, i rely on the web app or issue report 😞 ).

**Comment by roya0045** [comment]
> @roya0045 Are you on Windows? IOW could this have to do with line endings (kind of CRLF vs LF configs)? I'm using the Github desktop program on windows and weeks ago I had to choose a related option that popped up (`autocrlf` setting?) and since I'm always fighting with file diffs showing all the file replaced when doing a simple change (at the end, i rely on the web app or issue report 😞 ).

Yes, windows and either Visual Studio Code or copy-paste seem to corrupt whitepace.

The workaround I found was to use notepadd++, and use edit->EOL Conversion-­> Unix.

I never had this problem before with my workflow but at least this is only two files and not my other PR.

@elpaso Things should be fine now.

**Comment by elpaso** [comment]
@roya0045 loos good now, thanks! 
Nice feature too.

**Comment by roya0045** [comment]
> @roya0045 loos good now, thanks!
> Nice feature too.

@elpaso As stated previously I can add a loop beforehand, but I think that by having the implementation this way may be more flexible than with the two pass approach, if the user knows that every changed basepath will be propagated to the layers below that had the same initial base path.

What do you think?

**Comment by elpaso** [comment]
> > @roya0045 loos good now, thanks!
> > Nice feature too.
> 
> @elpaso As stated previously I can add a loop beforehand, but I think that by having the implementation this way may be more flexible than with the two pass approach, if the user knows that every changed basepath will be propagated to the layers below that had the same initial base path.
> 
> What do you think?

I think it's fine like it is now, we may improve it later if needed.

Actually I have another use case in mind for the "bad layers" dialog but I'm not yet sure if the current implementation will fit: when loading a QLR that has some references to a missing layer, we should prompt the user with the "bad layer" dialog before the layer is created or the value-relation/relation-reference or value-map widgets may be broken without the user even being warned.

**Comment by roya0045** [comment]
> Actually I have another use case in mind for the "bad layers" dialog but I'm not yet sure if the current implementation will fit: when loading a QLR that has some references to a missing layer, we should prompt the user with the "bad layer" dialog before the layer is created or the value-relation/relation-reference or value-map widgets may be broken without the user even being warned.

So does that mean that I should alter my PR for that use case or was that simply a comment?

Thanks for the reply.

**Comment by elpaso** [comment]
It was just a comment: since you've been working on this code maybe you had some good ideas.

**Comment by roya0045** [comment]
@elpaso I'm not too familiar with how qlr are handled and their internal structure but I assume the simplest way would be to check the existance of the reference as the first step of the import, then use the bad layer handler to obtain the proper path and assign that value to the reference of the QLR. and save the fixed QLR as if two people use a qlr but don't have the data in the same path, this is more of an issue on the user side.

Though I would assume that the bad layer handler would only provide the proper path for the QLR and that the rest should be handled somewhere else.

**Comment by elpaso** [comment]
@roya0045 thanks for this improvement!

**Comment by roya0045** [comment]
@elpaso Thanks for the merge!

**Comment by SrNetoChan** [comment]
I am looking at documenting this. I can't find any reference to bad layers handling anyway. Would this be a good place to put it?

https://docs.qgis.org/3.10/en/docs/user_manual/introduction/project_files.html#working-with-project-files

Or maybe something in general tools?

**Comment by DelazJ** [comment]
@SrNetoChan https://docs.qgis.org/3.16/en/docs/user_manual/introduction/project_files.html#handling-broken-file-paths

**Comment by SrNetoChan** [comment]
@DelazJ I wonder why I didn't check testing.... Seems we can close this on, no?

**Comment by DelazJ** [comment]
> Seems we can close this on, no?

close what?

**Comment by SrNetoChan** [comment]
> > Seems we can close this on, no?
> 
> close what?

https://github.com/qgis/QGIS-Documentation/issues/3588

**Pull request merged**
