### PR TITLE
QgsJsonUtils: add a way to disable use of field formatters

### LINKED ISSUE #58861: QgsJsonExporter layer field with ValueMap
### What is the bug or the crash?

QgsJsonExporter with a vector layer having a field using ValueMap as  QgsEditorWidgetSetup export its description instead value.

[This test](https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsjsonutils.py#L727) show this behaviour. I think QgsJsonExporter by default it should export the value and give the opportunity to export the description.

### Steps to reproduce the issue

Check this test https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsjsonutils.py#L727

### Versions

QGIS version | 3.34.10-Prizren | QGIS code revision | 113de9e1134
Qt version | 5.15.8
Python version | 3.11.2
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PostgreSQL client version | 15.7 (Debian 15.7-0+deb12u1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.13.3
OS version | Debian GNU/Linux 12 (bookworm)

Active Python plugins
lizmap | 4.3.6
digiagriapp_qgis | 0.3.2
quick_map_services | 0.19.34
plugin_reloader | 0.9.4
QuickOSM | 2.2.3
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rouault**
Fixes #58861

### CODE REVIEW

**Comment by rouault** [comment]
The doxygen_layout_check failure is a false positive (there's no mix of deprecated and since in that documentation block. I guess it is confused by other blocks):
```
/home/runner/work/QGIS/QGIS/src/core/qgsjsonutils.h
371:     * \param useFieldFormatters Whether field formatters should be used \since QGIS 3.40
372:     * \note Not available in Python bindings

*** Docstring computation: \deprecated and \since should be placed at the end of command blocks
To fix it, you may want to run (multiple times) at the top level directory:
sed -i -r '$!N;s/^(\s*\*\s+\\(deprecated|since)[^\n]+)\n(\s*\*([^\/].*|$))/\3\n\1/;P;D' $(ag -c --noaffinity --file-search-regex '\.h$' --multiline '(\\(deprecated|since)[^\n]+\n)+\s*\*[^\/]' . | cut -d: -f1)
```

As I suck at regexs to fix that, can I just omit the since stuff, or maybe try to put it as a casual comment without the antislash?

**Comment by nyalldawson** [comment]
@rouault actually it's flagging what it's supposed to here. I can't recall if it's a sipify limitation or a sphinx issue, but method docstrings can only have one since OR deprecated annotation, and it must be the last line in the docstring. Just use "(since QGIS XX)" instead for inline since annotations, that's a quasi standard approach for this in qgis. 

> I suck at regexs 

😱 @rouault is mortal after all? 😂

**Comment by nyalldawson** [comment]
Ping @3nids , do you recall if that was a sipify limitation?

**Comment by rouault** [comment]
> Just use "(since QGIS XX)" instead for inline since annotations

that did the job. Thanks

> 😱 @rouault is mortal after all? 😂

My attempts at participating at @opengeospatial circles show me how mortal I am. I loose one life each time I try to.

**Comment by nyalldawson** [comment]
@rouault fwiw, I've found Claude.ai is actually really really good at regex generation and explanation

**Review by nyalldawson — APPROVED** [review]

**Comment by 3nids** [comment]
@nyalldawson not sure! It's in the Doxygen test so I would expect it to be related to Doxygen but the cpp docs built. The original PR is not very verbose https://github.com/qgis/QGIS/pull/7101 so I'd bet on sipify.

But that would be worth digging into this because sphinx seems to allow since for parameters https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded

That's actually quite valuable for the API docs.

**Pull request merged**
