### PR TITLE
Fix vertical labeling when rotation is 270°

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

See https://github.com/qgis/QGIS/issues/54598

The label cannot be put in this position on master when `Show upside-down labels`  is set to `never`:

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
This test mask doesn't look right -- it's negating the whole test

**Comment by pblottiere** [comment]
Hi @nyalldawson,

> This test mask doesn't look right -- it's negating the whole test

Yes you're right, I updated the control image instead. Let me know if it suits you better.

**Comment by nyalldawson** [comment]
@pblottiere I agree that the updated test image is arguably correct. But I'm slightly concerned about the risk of regressions here -- the logic with upside down label handling is extremely complex :scream: 

Could you add new tests with rotation +/- 1 degree off vertical so that we've got a test which still covers a similar use case as the existing one with vertical text?

**Comment by pblottiere** [comment]
>  But I'm slightly concerned about the risk of regressions here -- the logic with upside down label handling is extremely complex 😱

Yes I understand. I won't be surprised if this PR is finally not merged :).

> Could you add new tests with rotation +/- 1 degree off vertical so that we've got a test which still covers a similar use case as the existing one with vertical text? 

I'm taking a look.

**Comment by pblottiere** [comment]
Hello @nyalldawson,

CI is green :tada:. Let me know what you think :). Thanks!

**Pull request closed without merging**
