### PR TITLE
Move "Add circular string" tool button to advanced digitizing

### PR DESCRIPTION
**Pull request by m-kuhn**
It's not a basic digitizing tool

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by 3nids** [comment]
it's so mean!

**Comment by lbartoletti** [comment]
What about to put it with circles, ellipses and cie?

**Comment by m-kuhn** [comment]
> What about to put it with circles, ellipses and cie?

Good suggestion, updated.

**Comment by nirvn** [comment]
+1. We need to rename the toolbar to use a more inclusive label.

**Comment by m-kuhn** [comment]
@nirvn which toolbar?

**Comment by andreasneumann** [comment]
This is not user-friendly for someone who has to digitize curves.

I do not think it is a good move to move this tool to another toolbar.

People have to switch between straight-lines and curves a lot. If the two tools are in separate toolbars, this process becomes clunky.

Please rethink this decision!

**Comment by nirvn** [comment]
@m-kuhn , if we're to leave the curved line tool in the "regular shape digitizing toolbar", IMHO we'd need to rename that toolbar as the curved line tool != regular shape.

I'm happy to see this gone from the digitizing toolbar (it was the only tool that was line/polygon specific), hopefully it'll ultimately be the beginning of a bigger UI integration re-work for that feature. Maybe a keyboard shortcut could activate curves when digitizing a line or a polygon (when available), etc.

**Comment by nirvn** [comment]
@m-kuhn , what about renaming the toolbar to "Line & Polygon Digitizing Toolbar"?

**Comment by m-kuhn** [comment]
The other group of users to consider are those that never ever get in touch with curves and have this button by default.

Alternative ideas:

 * Integrate it in a dropdown with the straight add line tool and use the button to toggle mode when editing is active
 * Promote the use of keyboard shortcuts as proposed by @nirvn 
 * Only activate the tool when the data provider supports curves
 * Others?

I'll pass the naming question on to @lbartoletti

**Comment by andreasneumann** [comment]
@m-kuhn - the circular arc tool is also available for simple features - in that case it is automatically segmentized. Have you ever tried to digitize a roundabout or round corners in a large-scale map? Without the circular arc tool, the results would be very ugly!

It is a tool, however, that is primarily used in very large-scale maps (such as cadastral maps)

The shortcuts for switching between curved and straight lines would of course be most efficient. Perhaps such shortcuts exist, but aren't documented? Not sure ...

Dropdown buttons are ok when you don't have to use a tool often. But switching between straight and curved lines is something you do often during digitizing - so I don't think it is the best approach to put it in a dropdown button. In that case - if you really have to move this button - it would be better to have it in another toolbar.

**Comment by andreasneumann** [comment]
If you discuss about "simple" vs. "advanced" then I would remove the "Move Features" and "Copy and Move Features" out of the regular digitizing toolbar. This tool is primarily useful for point features, but not for linestrings and polygons.

**Comment by m-kuhn** [comment]
> Dropdown buttons are ok when you don't have to use a tool often. But switching between straight and curved lines is something you do often during digitizing.

Would that work:

* Not digitizing: show dropdown to choose which tool shall be used for new digitizing operations
* While digitizing: if in straight line mode show curve and vice versa to switch between the modes (no dropdown)

**Comment by andreasneumann** [comment]
That would be a good solution - but the shortcuts (if they don't exist yet) would also be good. And if both exist, they would need to make sure that the button and shortcut is in sync.

**Pull request merged**
