### PR TITLE
Fix snap geometries crash

### PR DESCRIPTION
**Pull request by wonder-sk**
A crash may happen when running the alg with 'snap to anchor nodes (single layer only)' behavior. It turns out that I made a mistake while porting the algorithm to std::sort - originally the sorting function used -1/0/+1 for comparison, while std::sort wants '<' operator returning true/false. Due to inconsistent results from the comparison function, std::sort would end up corrupting the array and memory even beyond the range, causing crashes.

Related to #29400 (but does not fix it)

### CODE REVIEW

**Comment by wonder-sk** [comment]
@nyalldawson at some point you have changed the lambda function for std::sort in qgsgeometrysnappersinglesource.cpp from taking arguments as const refs to taking them as values - I wonder what was the reason (it does not affect this fix at all, I am just curious why we would want to copy the values rather than pass them by refs - the objects are larger than a pointer size).

Unrelated thought regarding topological errors - would it make sense to give users some hints on what to do when experiencing topological errors? With union/intersection/etc between layers A and B this should be "the" way to fix all topo errors:
1. snap geometries of layer A (to each other) with some tolerance (e.g. 0.01m)
2. fix geometries of layer A (aka MakeValid)
3. snap geometries of layer B to layer A with some tolerance (ideally the same as in step 1)
4. fix geometries of layer B (aka MakeValid)

After this pre-processing things should go smoothly. The problem is that:
1. we currently do not have an algorithm for step 3 (the existing implementation in QgsGeometrySnapper allocates incredibly large amounts of memory, making my laptop swap out everything until OOM killer kills QGIS)
2. even if we had algorithm for step 3, it is still easy to get this process wrong - would it make sense to have a dedicated processing alg to do this preparation in one go? Something like "fix geometries for geometry overlay" - it would take just layer A, layer B and tolerance as parameters. Or is this really a niche problem and having a link into documentation on how to fix that would be enough?

**Comment by nyalldawson** [comment]
@wonder-sk 
> I am just curious why we would want to copy the values rather than pass them by refs - the objects are larger than a pointer size).

It was flagged by clazy, which uses a 16 byte threshold:
https://github.com/KDE/clazy/blob/master/docs/checks/README-function-args-by-ref.md

Not saying this is correct, but those KDAB guys certainly put my c++ skills to shame... so I tend to just follow their recommendations blindly!

> (the existing implementation in QgsGeometrySnapper allocates incredibly large amounts of memory, making my laptop swap out everything until OOM killer kills QGIS)

This is because QgsSnapIndex is :hankey: . It works ok with large tolerances, but decreasing the tolerance massively increases the size of the index. It needs to be junked and replaced with a better implementation or using libspatialindex instead.

**Comment by nyalldawson** [comment]
Oh, and I like 2. I think there's a good call for a "make layers topologically consistent" algorithm!

**Comment by gacarrillor** [comment]
> > (the existing implementation in QgsGeometrySnapper allocates incredibly large amounts of memory, making my laptop swap out everything until OOM killer kills QGIS)
> 
> This is because QgsSnapIndex is hankey . It works ok with large tolerances, but decreasing the tolerance massively increases the size of the index. It needs to be junked and replaced with a better implementation or using libspatialindex instead.

See https://github.com/qgis/QGIS/pull/42781
(Funded by [SwissTierras Colombia](https://github.com/SwissTierrasColombia))

**Pull request merged**
