### PR TITLE
Add option to disable ssl verification in the Metasearch plugin

### LINKED ISSUE #35476: Metasearch certificate error
**Describe the bug**

Metasearch does not work with this pyCSW service that has a valid cert:

```
Unknown Error: HTTPSConnectionPool(host='geocris2.cdema.org', port=443): 
Max retries exceeded with url: /catalog?service=CSW&version=2.0.2&request=GetCapabilities (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

**How to Reproduce**

Add the above service to Metasearch and try to request service info. 

**QGIS and OS versions**

QGIS version | 3.10.3-A Coruña | QGIS code revision | 0e1f846438
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS 10.15
Active python plugins | QgisModelBaker; SpreadsheetLayers; lrs; QuickOSM; VectorBender; quick_map_services; stac_browser; Discovery; qfieldsync; qchainage; OSMDownloader; parcel_plugin; lizmap; openlayers_plugin; Projestions; mmqgis; processing_circuitscape; mapswipetool_plugin; Mergin; travel_time_platform_plugin; nominatim_locator_filter; timemanager; processing; db_manager; MetaSearch

# Additional

Also note the bug tracker link for Metasearch to github, it's still set to redmine

### PR DESCRIPTION
**Pull request by Samweli**
The latest owslib which is used by Metasearch plugin has an option to switch off ssl verification (see https://github.com/geopython/OWSLib/pull/685), this work expose that option to the Metasearch plugin user.

Fixes https://github.com/qgis/QGIS/issues/35476

Screenshot
metasearch_ssl_fix

cc @gubuntu
cc @tomkralidis

### CODE REVIEW

**Comment by nyalldawson** [comment]
Won't this need a version check to avoid breakage with older versions?

**Comment by Samweli** [comment]
> Won't this need a version check to avoid breakage with older versions?

No, it won't need a version check. The owslib API hasn't changed.

**Comment by Samweli** [comment]
@nyalldawson is it okay to backport this to QGIS 3.10?

**Comment by nyalldawson** [comment]
>  is it okay to backport this to QGIS 3.10?

Yes, but with the one release delay to avoid regressions

**Comment by tomkralidis** [comment]
FYI OWSLib 0.20.0 (with @Samweli's fix) has been released.

**Review by nyalldawson — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
Samweli, please see https://github.com/qgis/QGIS/issues/37175 QGIS 3.13.0-Master "ImportError: cannot import name 'Authentication' from 'owslib.util'" on Windows

**Comment by Samweli** [comment]
> @Samweli, please see #37175 QGIS 3.13.0-Master "ImportError: cannot import name 'Authentication' from 'owslib.util'" on Windows

Ok @agiudiceandrea, thanks for pointing it out! I have provided a fix here https://github.com/qgis/QGIS/pull/37198

**Comment by agiudiceandrea** [comment]
OSWLib 0.20.0 now available on OSGeo4W https://trac.osgeo.org/osgeo4w/ticket/633

**Pull request merged**
