### PR TITLE
Add the grid frame MARGIN In the "Print Layout" map grid [FEATURE]

### PR DESCRIPTION
**Pull request by konst555**
## Description
Proposed changes.
In the "Print Layout" section when building a map grid, it is necessary to add the possibility of a frame shift relative to the map.
It will be very easy to form a different framework for drawing up maps.

What changed :

-    UI - add label "margin" and QgsDoubleSpinBox
-    "margin" - from 0 to 99 ( default -0)
-    Add corners for "zebra" and frame boarder.
    If you use the default offset to "0", there will be no changes from the current version. Only for "zebra" corners will be drawn more correctly.

Why it is very important to make this small change.
Now QGIS does not have the means to design a standard scale frame of nautical charts. It is not possible to make standard designs for topographic maps.
Some applications, such as ArcGIS or my plugin for QGIS - the geogrid, create static vector layers for the map sections. When making the proposed add-on, we can very easily create a dynamic design that will meet the requirements of the standards.

default

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
@konst555 I'm going to apply for a feature freeze exemption for this one -- I think it's still a candidate for merging post 3.4 feature freeze

**Comment by nyalldawson** [comment]
Not stale!

**Comment by nyalldawson** [comment]
Sorry - going to have to delay this until 3.6 and feature freeze is lifted.

**Comment by konst555** [comment]
Thank you for the message. This is bad news. I am currently working on a ship and cannot take part in the work on QGIS. I hope that by my return in January or April, my proposed changes will be included in QGIS. Thanks for the help.


>Понедельник,  8 октября 2018, 22:15 UTC от Nyall Dawson <notifications@github.com>:
>
>Sorry - going to have to delay this until 3.6 and feature freeze is lifted.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Konstantin Puzankov

**Comment by nyalldawson** [comment]
Merged -- thank you!

**Pull request closed without merging**
