### PR TITLE
[processing] By default, hide algorithms with known issues from toolbox

### PR DESCRIPTION
**Pull request by nyalldawson**
And add a Processing setting to allow these to be shown. When shown, they are highlighted in red with a tooltip explaining that the algorithm has known issues.

To be used whenever an algorithm has serious known issues which make it dangerous to use, and where we CANNOT fix the underlying issues (e.g. due to issues in 3rd party dependencies)

Mark SAGA difference and symmetric difference as having known issues in SAGA LTR version.

image

### CODE REVIEW

**Review by alexbruy — APPROVED** [review]
+1 for this

**Comment by nirvn** [comment]
Big +1 for this -- 

@nyalldawson , just so we get the ball rolling on this, as we discussed on google hangout, it'd be really good to have a similar behavior for 3rd party duplicate algorithms (for eg SAGA / GRASS's grid algorithms), whereas by default we would hide those, and if shown would be visually distinct (you mentioned semi-opaque text color).

**Comment by nyalldawson** [comment]
@nirvn

Yep, but let's do one tricky discussion at a time :)

**Comment by nirvn** [comment]
@nyalldawson , yep; BTW, I love the looks of your processing panel's toolbar :smile:

**Pull request merged**
