### PR TITLE
Add support for SIP v5 to the build system

### LINKED ISSUE #37542: Please switch from sip4 to sip5
As reported by Dmitry Shachnev in [Debian Bug #964132](https://bugs.debian.org/964132):
> Recently I have updated pyqt5 and related packages to use sip5 instead of
> sip4 for build. This is in experimental for now, but I want to upload it
> to unstable in a month or two.
>
> This change breaks PyQt5 extension ABI, so all packages build-depending on
> pyqt5-dev need to build with sip5 too.
>
> Quick migration guide:
>
> 1) Build-depend on python3-sipbuild(-dbg) and sip5-tools.
>
>    - Inspect pyproject.toml (if it exists) for additional dependencies, maybe
>      you will need also python3-pyqtbuild.
>
> 2) If your package has a project.py file, call sip-build to build it.
>    For separation of configure and build phases, pass --no-make to it.
>
> 3) If your package does not have a project.py file, but has a configure.py,
>    update that file to the latest version of the boilerplate (v2.16), which
>    you can find in the experimental version of qscintilla2 package.
>
>    (Qscintilla2's configure.py used to be a recommended way to build sip
>    projects.)
>
> 4) If your package called /usr/bin/sip directly, call /usr/bin/sip5 instead.
>
> 5) If your package had a runtime dependency on python3-sip or ${sip3:Depends},
>    depend on python3-pyqt5.sip instead. There is no analogue for dh_sip3
>    helper yet.
>
>    (Upstream now recommends each project to use its own private copy of sip.
>    In Debian, I recommend you to use pyqt5's copy which is python3-pyqt5.sip).
>
> 6) If you build a -dev package with .sip files, they are now installed into
>    a new location (in dist-packages). Also .toml files now should be present.
>
> You can see what I have done in pyqt5, pyqt5chart, pyqt5webengine and
> qscintilla2 packages in experimental (see the relevant commits in git).
>
> The official documentation for sip5 is available online [1] or in sip5-doc
> package. For help you can ask me or pyqt/sip mailing list [2] (subscription
> needed to post messages).
>
> Please stage your changes in experimental (or in a VCS) for now. They will
> need to be uploaded to unstable together with pyqt5.
>
> [1]: https://www.riverbankcomputing.com/static/Docs/sip/
> [2]: https://www.riverbankcomputing.com/mailman/listinfo/pyqt

### PR DESCRIPTION
**Pull request by mitya57**
This PR adds support for SIP v5 while keeping support for SIP v4. You can install the latest version of SIP by running `pip install --upgrade sip PyQt5`.

- In SIP v5, there is no more `sipconfig` module. In fact, `sipconfig` was [deprecated][1] since at least June 2014. There is a new sipbuild module, but it has a completely different API so I don't really use it here (for purposes other than detecting the version).
- `FindSIP.py` and `FindPyQt5.py` now use different code paths for SIP v4 and SIP v5.
- There is no more `sip.h` file (and thus also no `SIP_INCLUDE_DIR`). So I added a call to `sip-module` which generates `sip.h` in the current directory.

[1]: https://www.riverbankcomputing.com/pipermail/pyqt/2014-June/034430.html

Fixes #37542.

### CODE REVIEW

**Comment by nyalldawson** [comment]
This looks good to me. @m-kuhn any thoughts?

**Comment by m-kuhn** [comment]
My thought was, if it still builds and tests run through it should be fine :+1:

**Comment by lbartoletti** [comment]
can we backport it?

**Comment by lbartoletti** [comment]
Tested on my workstation thanks @mitya57

**Comment by mitya57** [comment]
@lbartoletti It can be backported, yes. I guess someone needs to add tags for the bot?

**Pull request merged**
