### PR TITLE
[processing] Remove useless qgis: algs descriptions and add missing ones

### PR DESCRIPTION
**Pull request by agiudiceandrea**
## Description

Removes some useless short help description of Python algorithms ported to C++ or no longer available or unified/split in new ones:
qgis:boundary, qgis:centroids, qgis:clip, qgis:createpointslayerfromtable, qgis:deleteholes, qgis:densifygeometriesgivenaninterval, qgis:dissolve, qgis:extractbyattribute, qgis:extractbyexpression, qgis:fixeddistancebuffer, qgis:frequencyanalysis, qgis:generatepointspixelcentroidsinsidepolygons, qgis:lineintersections, qgis:mergevectorlayers, qgis:minimalenclosingcircle, qgis:multiparttosingleparts, qgis:numberofuniquevaluesinclasses, qgis:polygoncentroids, qgis:polygonstolines, qgis:randompointsinsidepolygonsfixed, qgis:randompointsinsidepolygonsvariable, qgis:reprojectlayer, qgis:splitwithlines, qgis:tilesxyz

Adds some missing algorithms short help description (partially taken from the user manual alg description):
qgis:executesql, qgis:heatmapkerneldensityestimation, qgis:idwinterpolation, qgis:randompointsinsidepolygons, qgis:tilesxyzdirectory, qgis:tilesxyzmbtiles, qgis:tininterpolation

The qgis:rectanglesovalsdiamondsvariable, which is flagged as deprecated and not available in the processing toolbox, remains without a short help description (the description is also missing in the user manual, while it is available the one of native:rectanglesovalsdiamonds).

This PR needs to be backported.

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by DelazJ** [comment]
Thanks for the cleanup @agiudiceandrea. Let's backport at least to 3.22...
> The qgis:rectanglesovalsdiamondsvariable, which is flagged as deprecated and not available in the processing toolbox, remains without a short help description (the description is also missing in the user manual, while it is available the one of native:rectanglesovalsdiamonds).

I'm sorry I don't get the point here. Do you think deprecated and hidden alg should be documented (I'm asking from a user manual contributor pov)?

**Comment by agiudiceandrea** [comment]
> I'm sorry I don't get the point here. Do you think deprecated and hidden alg should be documented (I'm asking from a user manual contributor pov)?

The deprecated algs, as qgis:rectanglesovalsdiamondsvariable, are not available in the Processing Toolbox, while they are available in the Model Designer.
The short help description is only showed in the Processing Toolbox algs window, while it is not showed in the Model Designer algs window.
Anyway the the Model Designer algs window has an Help button which points to an online user manual help description (which, for some deprecated algs as qgis:rectanglesovalsdiamondsvariable, is missing).
So, it seems to me, for the GUI user needs, the deprecated algs should have an online user manual help description, while a short help description could be avoided.

**Comment by DelazJ** [comment]
> The short help description is only showed in the Processing Toolbox algs window, while it is not showed in the Model Designer algs window.

I think this is a feature we should add; sounds more helpful than sending user to the online manual for each alg they want to know if suitable for them.
> an online user manual help description (which, for some deprecated algs as qgis:rectanglesovalsdiamondsvariable, is missing).

This might be due to the algorithm not being in the "modeler tools" group. Hence easier to forget (algs that are not in toolbox are usually in the modeler group).
Should this alg be moved to that group? And is this alg still necessary given all the abilities of fields parametrizing in modeler? I see that there are data defined buttons in the not variable algorithm dialog.

**Comment by agiudiceandrea** [comment]
> Should this alg be moved to that group? And is this alg still necessary given all the abilities of fields parametrizing in modeler?

Good point.
Anyway, when @alexbruy ported the "Rectangle, ovals, diamonds" algorithm to C++ https://github.com/qgis/QGIS/pull/33794 he completely deleted the qgis:rectanglesovalsdiamondsfixed and leaved the qgis:rectanglesovalsdiamondsvariable (only flagging it as deprecated) to maintain API compatibility.

**Pull request merged**
