### PR TITLE
Fix Delimited Text provider types recognition from csvt

### LINKED ISSUE #46117: Opening CSV with CSVT file: file types not recognized
### What is the bug or the crash?

If the file types in the .csvt file are written with an upper-case first letter, [as prescribed by the OGR](https://gdal.org/drivers/vector/csv.html) driver, QGIS fails to correctly assign file types.

If all is written in lower case in .csvt file, it works fine. 

When directly dropping a CSV file with correct CSVT type definition into QGIS, field types are correctly recognized

### Steps to reproduce the issue

1. Create a test.csv file with the following data:
```
id,f1,f2,f3
01,0.3,0.8,1.4
12,0.2,78,13.4
```
2. create a test.csvt with one line as `"String","Real","Real","Real"`
3. Open Data source manager, delimited text and add the test.csv file
4. The first field type is not recognized correctly (Integer instead of String)

### Versions

Version de QGIS | 3.22.0-Białowieża | Révision du code | d9022691f1
-- | -- | -- | --
Version de Qt | 5.15.2
Version de Python | 3.9.5
Version de GDAL/OGR | 3.4.0
Version de Proj | 8.2.0
Version de la base de données du registre EPSG | v10.038 (2021-10-21)
Version de GEOS | 3.10.0-CAPI-1.16.0
Version de SQLite | 3.35.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | 13.0
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.3
Version de QScintilla2 | 2.11.5
Version de l'OS | Windows 10 Version 1809
  |   |   |  
Extensions Python actives
changeDataSource | 3.1
french_locator_filter | 1.0.0
geometry_paster | 0.1.1
Go2NextFeature3 | 2.00
profiletool | 4.1.8
SpreadsheetLayers | 2.0.1
StreetView | 3.2
valuetool | 3.0.14
ViewshedAnalysis | 1.7
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Seems to work fine in 3.16

### PR DESCRIPTION
**Pull request by agiudiceandrea**
## Description

Fixes a regression introduced by https://github.com/qgis/QGIS/commit/be1ba89063e525c54f49d81317af2b8f78db8e56 (https://github.com/qgis/QGIS/pull/42609) since 3.20.0, which prevents to correctly read the fields types of a csv layer file, if the csvt sidecar file contains the field types name non lowercase, when imported using Data Source Manager - Delimited Text dialog window.

This PR needs to be backported to the 3.22 branch.

Fixes https://github.com/qgis/QGIS/issues/46117.

### CODE REVIEW

**Review by elpaso — APPROVED** [review]
LGTM, thanks. 

Is there any chance to have a test?

**Comment by nirvn** [comment]
I was about to drop a "test pleaae" only to find @elpaso beat me to it :)

**Comment by elpaso** [comment]
> I was about to drop a "test pleaae" only to find @elpaso beat me to it :)

There is a broken one btw: https://github.com/qgis/QGIS/runs/4274192767?check_suite_focus=true#step:13:2592

**Comment by agiudiceandrea** [comment]
@elpaso test added.

The fixed bug had prevented another bug (the incorrectly parsing of the datetime/date/time fields types names in the csvt, which is fixed now), also related to the QRegEx->QRegularExpression change, to show up early in the tests.

Anyway, looking at the code, it seems to me there is another bug in the logic.
The csvt file is considered valid if it contains the following fields types names:` integer, real, double, long, longlong, int8, string, date, datetime, time`, but the `readCsvtFieldTypes()` function will return a list of fields types name which could only contain the following types names: `integer, real, double, string, datetime, date, time` thus discarding the `long, longlong, int8` types names.

This could lead to another possible incorrect parsing of the fields types names in the csvt file in the following scenario:

- csv file contains 5 fields: f1,f2,f3,f4,f5
- csvt file contains the fields types: integer,longlong,real,string,real

- `readCsvtFieldTypes()` will return a list containing only 4 fields types name: `{ "integer", "real", "string", "real" }`
- `scanFile()` will thus attribute the fields types to the fields names incorrectly:
f1 -> QVariant::Int
f2 -> QVariant::Double instead of QVariant::LongLong
f3 -> QVariant::String instead of QVariant::Double
f4 -> QVariant::Double instead of QVariant::String
f5 -> automatically detected instead of QVariant::Double

**Comment by agiudiceandrea** [comment]
@elpaso, consider also that double, long, longlong, int8 types are not listed among the recognized types in GDAL https://github.com/OSGeo/gdal/blob/c01cf7ef46875f65af85aef67c2a16fe73272624/ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp#L711-L732
I wonder why they were inserted in the regex https://github.com/qgis/QGIS/blob/a21530b89f6949820ccc364d5fce4112cd29b1c8/src/providers/delimitedtext/qgsdelimitedtextprovider.cpp#L226

**Comment by elpaso** [comment]
> @elpaso, consider also that double, long, longlong, int8 types are not listed among the recognized types in GDAL https://github.com/OSGeo/gdal/blob/c01cf7ef46875f65af85aef67c2a16fe73272624/ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp#L711-L732, https://gdal.org/drivers/vector/csv.html. I wonder why they were inserted in the regex
> 
> https://github.com/qgis/QGIS/blob/a21530b89f6949820ccc364d5fce4112cd29b1c8/src/providers/delimitedtext/qgsdelimitedtextprovider.cpp#L226

No clue :/ but I think it would be a good idea to accept them anyway and treat them as aliases for supported types.

**Pull request merged**
