### PR TITLE
[postgres] Fix estimated metadata queries fail for huge tables

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #​​2​​​​​​​​​​​​​​​​​​​​​​​​​1​​​​​​​​​​​​​​​​5​​​​​1​​​​7

### CODE REVIEW

**Comment by nyalldawson** [comment]
HEh @m-kuhn -- I broke your workflow with this PR message :wink:

**Comment by m-kuhn** [comment]
PR looks good.

I fail to see how you broke it, but if you did, please [make it an option](https://xkcd.com/1172/).

**Comment by nyalldawson** [comment]
Try and copy that issue number to hub and see what happens...

**Comment by m-kuhn** [comment]
It opens an issue about "Estimated Extent fails when rows exceed 32-bit signed integer max, issues slow ST_Extent query"

**Comment by nyalldawson** [comment]
Bah, your browser must be too smart to fall for my tricks

**Comment by m-kuhn** [comment]
Or my copy-paste-capabilities :muscle:

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
