### PR TITLE
Allow use of masks for unit test control images

### PR DESCRIPTION
**Pull request by nyalldawson**
(looking for feedback)

Since the dawn of time QGIS developers have been plagued by platform specific rendering differences screwing with the test suite (I assume). Then this PR comes riding in on a silver horse to save the day... (I hope). 

What I've done is implement mask images which set how the control image is matched. A mask image sets which pixels in the control image should be tested and an optional tolerance for each pixel. This is done via the colors in the mask image - white pixels are ignored, black must be an exact match, and gray levels represent the maximum color component deviation for that pixel.

This should replace the fragile anamoly images, in that a single control image with a suitable mask will not be suspectible to antialiasing differences, etc.

A new script (scripts/generate_test_mask_image.py) is included which either creates a new mask or modifies an existing mask to handle an acceptable rendered image.

Ultimately, masking along with multi render checks for specific platform differences should be flexible enough to meet our needs. I'm thinking we use the multi render checker for tests with an expected difference between platforms (eg font rendering/sizing differences), but not for different platform releases (eg precise/trusty - which has been done in the past to avoid antialiasing related failures).

Thoughts?

### CODE REVIEW

**Comment by nyalldawson** [comment]
I should add that the included atlas test masks fix the failing test under Windows. It will be trivial to add additional masks to allow all tests which are failing due to rendering differences if this approach is accepted.

**Comment by strk** [comment]
Great plan ! I'll have to test this, it is important that the script to update the mask gives the user a chance to review the change before committing it, and that usage of the script is suggested by the test failure report.

I'm still concerned about repository size (compared to check specific pixels) but having full images sounds easier for writing tests.

**Comment by strk** [comment]
so I gave your branch a build and tried to simulate an error by manually modifying an "expected" image. The test with the modified expected image failed (as expected). But now what ?
The generate_test_mask_image.py script (which is not executable, should it be?) wants 3 arguments. Could it be made to automatically figure them out based on test results ?

**Comment by m-kuhn** [comment]
Sounds like a good plan.

Does this mean that per reference image there will be one mask that is incrementally populated by the `generate_test_mask_image.py` script with the maximum deviation found so far?

I think as a rule of thumb, an image per platform sounds good. I am not sure though that this will hold in every case. It will boil down to common sense. "If the text is still readable with a mask applied, use a mask, if not, generate a new reference image".

**Comment by nyalldawson** [comment]
@m-kuhn that's correct. That was also my thinking with regard to whether platform specific images are required. I think in practice they will be rare and only needed for explicit text rendering tests.

Are you for if I proceed with this? If so, I'll add some docs on using the script and start adding masks..

**Comment by m-kuhn** [comment]
Absolutely. Actually, that was the way I originally expected anomaly images to work until I realized what they really do.

**Comment by nyalldawson** [comment]
I've merged it now (along with pt 1 of the mask image updates), but I'll leave this PR open until I've updated the coding doc to suit

**Comment by strk** [comment]
it would be nice to also show the mask in the report.
best if for each test there was a single table row, with columns: expected,mask,obtained,diff

**Comment by timlinux** [comment]
Thanks for this @nyalldawson

**Comment by m-kuhn** [comment]
Thanks a lot @nyalldawson

**Comment by m-kuhn** [comment]
@nyalldawson can this PR be closed? I think this functionality is already merged.

**Pull request closed without merging**
