### PR TITLE
[processing] improve handling of the HTML outputs in GRASS provider (fix #30609)

### LINKED ISSUE #30609: Processing v.report fails in QGIS 3.8 - "ERROR: v.report: Sorry, <html> is not a valid parameter"
The v.report processing algorithm fails in QGIS 3.8, like this:
````
…
C:\Users\alistair\Documents>g.region n=788490.5452753915 s=788418.2217753916 e=408156.5988251957 w=408080.77932519565
C:\Users\alistair\Documents>v.report map=vector_5d22d2c28045b9 option="area" units="meters" sort="asc" html=- --overwrite 1>"C:/Users/alistair/AppData/Roaming/QGIS/QGIS3/profiles/default/processing/outputs/report.html"
Reports geometry statistics for vector maps.
Usage:
v.report.py map=name [layer=string] option=string [units=string]
[sort=string] [--help] [--verbose] [--quiet] [--ui]
Flags:
Parameters:
map Name of vector map
layer Layer number or name
default: 1
option Value to calculate
options: area,length,coor
units Units
options: miles,feet,meters,kilometers,acres,hectares,percent
sort Sort the result
options: asc,desc
ERROR: v.report: Sorry, <html> is not a valid parameter
Execution of <C:\Users\alistair\AppData\Local\Temp\processing_a182ddbd6b9c4d0c8175eced73154d0b\grassdata\grass_batch_job.cmd> finished.
Cleaning up default sqlite database ...
Cleaning up temporary files...
Press any key to continue . . .
Execution completed in 5.54 seconds
Results:
{'html': 'C:/Users/alistair/AppData/Roaming/QGIS/QGIS3/profiles/default/processing/outputs/report.html'}

Loading resulting layers
Algorithm 'v.report' finished
HTML output has been generated by this algorithm.
Open the results dialog to check it.
````
This is on Windows.
It is a regression as it works in 2.18.x and 3.4.4
It seems to have been caused by https://github.com/qgis/QGIS/commit/b9f559ee0430e09d8e1a3b70e060155635080262

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
In the GRASS provider some tools have "fake" HTML outputs (when result is a tool stdout and it is redirected to the file, e.g. `v.report`, `r.coin`) and "real" HTML outputs (when tool has dedicated parameter for output, e.g. `v.net.salesman`). These cases need to be handled differently.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by nyalldawson — DISMISSED** [review]
Nice. There's a bunch of grass tests from 2.18 which are commented out - I tried looking at why a while back and it seemed related to outputs changing from html to txt and vice versa (no idea on the justification of why this was done). Possibly these are fixed by this pr and can be reactivated? Worth a check at least!

**Comment by alexbruy** [comment]
I have checked test and re-enabled these which does not require API break (changing parameter names). Also fixed broken `r.describe` algorithm.

**Comment by nyalldawson** [comment]
Nice, great work!

**Comment by alexbruy** [comment]
Travis failure is not related to this PR

**Pull request merged**
