### PR TITLE
Cherry-picking @aaime works on SLD to release-2_16

### PR DESCRIPTION
**Pull request by rldhont**

### CODE REVIEW

**Comment by elpaso** [comment]
@rldhont are you sure about the target branch? Shouldn't it be `master_2` ?

**Comment by rldhont** [comment]
Yes I'm sure, I have already merged in master_2
I opened this PR to made tests

**Comment by luipir** [comment]
is it 2.16 freeze?

**Comment by rldhont** [comment]
It is not a feature but a BIG bugfix on how QGIS build SLD.

**Comment by yjacolin** [comment]
no, but 2.16 is LTR :)

**Comment by rldhont** [comment]
I have backporting the work of @aaime in master_2 to backport it in 2.16 and 2.14
Because 2.14 is the LTR and needs this bugfix

**Comment by rldhont** [comment]
is someone opposed to the merge in release-2_16 ?

**Comment by nyalldawson** [comment]
I would definitely class this as a bug fix, so in my opinion it's suitable for backporting to all branches

**Comment by aaime** [comment]
Awesome! :-)

**Pull request merged**
