### PR TITLE
Port SAGA algs to new API (incomplete)

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR begins porting the SAGA algs to the new processing API.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Ok, I've taken this as far as I can. I can't get saga to run on my computer at all without segfaulting, regardless of the command used (or whether I use self compiled or Fedora provided packages). Someone with more interest in reviving the SAGA utils can take over from here ;)

**Comment by gioman** [comment]
> Ok, I've taken this as far as I can. I can't get saga to run on my computer at all without segfaulting, 

Hi Nyall, is QGIS segfaulting or the SAGA process launched by Processing? sure isn't just a SAGA issue on your box?

> Someone with more interest in reviving the SAGA utils can take over from here ;)

shipping qgis 3 without the arguably most important analsyis and geoprocessing component of Processing is not really an option, in my opinion. 

cheers!

**Comment by nyalldawson** [comment]
> SAGA issue on your box

Yes - not qgis here. I also get segfaults running saga directly.

> shipping qgis 3 without the arguably most important analsyis and geoprocessing component of Processing is not really an option, in my opinion

I agree, but someone else has to step up and lead this. I can't do anything more at this stage as I can't even test the algorithms (and they have no unit tests, so using Travis to test isn't an option either). I'm here to assist and make any changes to the core API which are required, but can't do this alone.

Any volunteers?

**Comment by gioman** [comment]
> as I can't even test the algorithms

I can help with that for sure.

**Comment by mach0** [comment]
Tested at least the "coordinates to points" algorithm with 300000 points - no failure so far.
Everything seems to work ok

**Comment by nyalldawson** [comment]
> Tested at least the "coordinates to points" algorithm with 300000 points - no failure so far.
Everything seems to work ok

Fantastic! Next step is to get some real tests committed in here. What you need to do is:

1. Load some of the reference test data files from python/plugins/processings/tests/testdata into QGIS.
2. Run a SAGA algorithm and make sure the result is saved into the folder python/plugins/processings/tests/testdata/expected/saga.
3. Check the Processing -> History window. Find the command which corresponds to your new test. Right click it, and select "create test". Copy that YAML content
4. Paste it into a new "saga_algorithm_tests.yaml" file under python/plugins/processing/tests/testdata
5. commit the yaml + new exepected data 

If you could repeat this with a selection of tests which cover using various data types (point/polygon/line), various input types (i.e. numeric parameters, string parameters, drop down selections, etc. Stick with vector tests for now.

Other tests required:
1. Test if non shapefile sources and destinations work correctly
2. Test the "split RGB bands" algorithm with a RGB raster file (in various source formats, e.g. tiff/...)

Many thanks!

**Comment by pcav** [comment]
Thanks Nyall. Could we post this on a more prominent place, so we can try to involve more testers?

**Comment by mach0** [comment]
Point 3: Check the Processing -> History window. Find the command which corresponds to your new test. Right click it, and select "create test". Copy that YAML content
Creates following error on my machine.. so there is a stop for me :(
(running your PR #5021  version of QGIS)

An error has occurred while executing Python code: 

ValueError: malformed node or string: 
Traceback (most recent call last):
  File "/home/macho/dev/cpp/build-QGISpr/output/python/plugins/processing/gui/HistoryDialog.py", line 128, in createTest
    TestTools.createTest(item.entry.text)
  File "/home/macho/dev/cpp/build-QGISpr/output/python/plugins/processing/gui/TestTools.py", line 140, in createTest
    alg_id, parameters = splitAlgIdAndParameters(text)
  File "/home/macho/dev/cpp/build-QGISpr/output/python/plugins/processing/gui/TestTools.py", line 134, in splitAlgIdAndParameters
    return m.group(1), ast.literal_eval(m.group(2))
  File "/usr/lib/python3.5/ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.5/ast.py", line 62, in _convert
    in zip(node.keys, node.values))
  File "/usr/lib/python3.5/ast.py", line 61, in 
    return dict((_convert(k), _convert(v)) for k, v
  File "/usr/lib/python3.5/ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: 


Python version: 3.5.4 (default, Aug 12 2017, 14:08:14) [GCC 7.1.0] 
QGIS version: 2.99.0-Master Master, b6cc025330

**Comment by nyalldawson** [comment]
@mach0 can you post the python string from the history console?

**Comment by mach0** [comment]
sure:
processing.run("saga:addcoordinatestopoints", {'INPUT':'/home/macho/dev/cpp/QGIS/python/plugins/processing/tests/testdata/points.gml','OUTPUT':QgsProcessingOutputLayerDefinition('/home/macho/dev/cpp/QGIS/python/plugins/processing/tests/testdata/expected/add_coordinates_to_points.gml')})

As most of the available test data is in gml I thought saving it as gml would be nice too

**Comment by ghtmtt** [comment]
hi guys.. as you now I've got some sponsor to enhance the tests of Processing. The difficulties faced could be hard to overpass even for an advanced uses. 

What about moving the existing instruction for the test in the QGIS website? Maybe there is more visible and it could be also easier to make the instructions more verbose

I'm available to do that

**Comment by mach0** [comment]
I'd rather wait until the "create test" works - at least for me :) Don't know why it's not working on my machine, but I hope this can be solved.

**Comment by alexbruy** [comment]
@nyalldawson sorry for late review, I was on vacations.

Code looks good to me. Regarding algorithms descriptions, I have started to work on script to generate them automatically. Will return to this work ASAP.

**Comment by nyalldawson** [comment]
> I'd rather wait until the "create test" works - at least for me :) Don't know why it's not working on my machine, but I hope this can be solved.

Can you try now? Should be fixed if you update this branch.

**Comment by mach0** [comment]
hmm - to me it looks like the very same error when i right-click and do a 'create test'
An error has occurred while executing Python code: 

ValueError: malformed node or string: 
Traceback (most recent call last):
  File "/home/macho/dev/cpp/build-QGISpr/output/python/plugins/processing/gui/HistoryDialog.py", line 128, in createTest
    TestTools.createTest(item.entry.text)
  File "/home/macho/dev/cpp/build-QGISpr/output/python/plugins/processing/gui/TestTools.py", line 141, in createTest
    alg_id, parameters = splitAlgIdAndParameters(text)
  File "/home/macho/dev/cpp/build-QGISpr/output/python/plugins/processing/gui/TestTools.py", line 135, in splitAlgIdAndParameters
    return m.group(1), ast.literal_eval(m.group(2))
  File "/usr/lib/python3.5/ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.5/ast.py", line 62, in _convert
    in zip(node.keys, node.values))
  File "/usr/lib/python3.5/ast.py", line 61, in 
    return dict((_convert(k), _convert(v)) for k, v
  File "/usr/lib/python3.5/ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: 

Python version: 3.5.4 (default, Aug 12 2017, 14:08:14) [GCC 7.1.0] 
QGIS version: 2.99.0-Master Master, f8f48e6ce8

processing.run("saga:addcoordinatestopoints", {'INPUT':'/home/macho/dev/cpp/QGIS/python/plugins/processing/tests/testdata/points.gml','OUTPUT':QgsProcessingOutputLayerDefinition('/home/macho/dev/cpp/QGIS/python/plugins/processing/tests/testdata/expected/add_coordinates_to_points.gml')})

**Comment by mach0** [comment]
maybe I should not try to save it as *.gml?

**Comment by nyalldawson** [comment]
Ah - rerun the test. The fix changed how it was logged in the history so you'll need a new entry.

**Comment by mach0** [comment]
I did rerun the test and choose the most recent one .. Will clean the history today and try it again.

**Comment by nyalldawson** [comment]
Got it - can you checkout the latest version of this PR?

**Comment by mach0** [comment]
ok - seems to work now .. but I assume the PR for tests should still be done agains master? or against this PR? ;)

**Comment by alexbruy** [comment]
> but I assume the PR for tests should still be done agains master?

It should be done against master, but will be merged after this PR

**Comment by nyalldawson** [comment]
Actually better if you push them to your branch on GitHub, and I'll cherry pick them onto here.

**Comment by ghtmtt** [comment]
sorry guys.. I checked out the PR on my computer, all the SAGA algorithms are there (working I'd say) but I get the same error of Werner when right clicking on the algorithm in the History Dialog (same algorithm).

**Comment by nyalldawson** [comment]
@ghtmtt can you post your current sha and the python string from the history console?

**Comment by ghtmtt** [comment]
@nyalldawson here it is:

```
An error has occurred while executing Python code: 

ValueError: malformed node or string: 
Traceback (most recent call last):
  File "/home/matteo/lavori/QGIS/build-qgis3/output/python/plugins/processing/gui/HistoryDialog.py", line 128, in createTest
    TestTools.createTest(item.entry.text)
  File "/home/matteo/lavori/QGIS/build-qgis3/output/python/plugins/processing/gui/TestTools.py", line 141, in createTest
    alg_id, parameters = splitAlgIdAndParameters(text)
  File "/home/matteo/lavori/QGIS/build-qgis3/output/python/plugins/processing/gui/TestTools.py", line 135, in splitAlgIdAndParameters
    return m.group(1), ast.literal_eval(m.group(2))
  File "/usr/lib/python3.5/ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.5/ast.py", line 62, in _convert
    in zip(node.keys, node.values))
  File "/usr/lib/python3.5/ast.py", line 61, in 
    return dict((_convert(k), _convert(v)) for k, v
  File "/usr/lib/python3.5/ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: 


Python version: 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609] 
QGIS version: 2.99.0-Master Master, 2530d9e 
```

And here what I did:

* compiled QGIS
* checked out locally this PR
* replace the `my_build_qgis3/output/python/plugins/processing` folder with the `processing` folder of the forked repo (so to have the SAGA algorithms available)
* load the tests data and run the `Add coordinates to point` algorithm and save the result in the `processing/tests/testdata/expected` folder
* I noticed that Processing saves the output only as `shp` (tests.shp, test.prj, test.dbf, test.shx and test.mshp) and does not load the result automatically in QGIS
* go in Processing -> History, right click -> Create Test (I cleaned the history before so it is the only algorithm in the list) and I get the error

Hope this can help

Thanks a lot for this

**Comment by nyalldawson** [comment]
Thanks @ghtmtt . What I really need is the string that's shown in the bottom of the history window before you try to create the test. It'll start with processing.runalg(...)

**Comment by ghtmtt** [comment]
ah ok.. sorry ;)

`processing.run("saga:addcoordinatestopoints", {'INPUT':'/home/matteo/lavori/QGIS/QGIS/python/plugins/processing/tests/testdata/points.gml','OUTPUT':QgsProcessingOutputLayerDefinition('/home/matteo/lavori/QGIS/QGIS/python/plugins/processing/tests/testdata/expected/saga')})`

**Comment by nyalldawson** [comment]
That looks a bit strange - the output layer is a folder instead of a filename. Do you know why this has happened?

**Comment by mach0** [comment]
thats exactly the same string I had ..  there is only the output without "ending" ..Are you sure you checked out the latest pull request from @nyalldawson ?

**Comment by ghtmtt** [comment]
@mach0 I checked out his PR:

```
git fetch upstream pull/5021/head:saga_processing
git checkout saga_processing
```

should I checkout something else?

**Comment by mach0** [comment]
Well - I usually do it like github suggest it - result should be the same.
git checkout -b nyalldawson-more_processing master
git pull git://github.com/nyalldawson/QGIS.git more_processing

**Comment by ghtmtt** [comment]
@nyalldawson ok it works now. Thanks @mach0 for the help ;)

**Comment by nyalldawson** [comment]
Superseded by #5155

**Pull request closed without merging**
