### PR TITLE
[BUGFIX][QGIS Server] GetFeatureInfo: Feature with no geometry is not…

### PR DESCRIPTION
**Pull request by rldhont**
… returned even if FILTER param is set

### CODE REVIEW

**Comment by rldhont** [comment]
@mhugent and @sbrunner can you review this PR ? thanks

**Comment by sbrunner** [comment]
The build ask for many naming changes:
https://dash.orfeo-toolbox.org/viewBuildError.php?buildid=248443
And I think that's good to address the @nyalldawson comment directly :-)
Also that's looks good to me :-)

**Comment by rldhont** [comment]
@sbrunner thanks, I'll fix it (I have wrote this for release-2_14)

I'll also update the code like @nyalldawson proposed

**Comment by rldhont** [comment]
@sbrunner @mhugent @elpaso can I merge and backport to release 2.14 ?

**Review by sbrunner — APPROVED** [review]

**Comment by sbrunner** [comment]
+1 for me :-)

**Comment by mhugent** [comment]
+1 for merge

**Pull request merged**
