### PR TITLE
2.18 Server: return empty image in GetLegendGraphis if no layer is there

### PR DESCRIPTION
**Pull request by mhugent**
Especially important for contextual legends. Otherwise the server returns nothing and the client receives an 'internal server error 500'

### CODE REVIEW

**Review by elpaso — APPROVED** [review]
thanks! IIRC there should be also an open issue on the tracker for this bug.

**Review by rldhont — CHANGES_REQUESTED** [review]
Can you add a test ?

**Comment by gioman** [comment]
@mhugent thanks for tackling this regression!

**Comment by mhugent** [comment]
@rldhont: no
Isn't it enough to port it to master?

**Pull request merged**
