### PR TITLE
Keep base units as default behavior (fix #15434)

### PR DESCRIPTION
**Pull request by DelazJ**
Fix http://hub.qgis.org/issues/15434

### CODE REVIEW

**Comment by nirvn** [comment]
Big +1

**Comment by m-kuhn** [comment]
This won't work.
You will have to edit qgsoptions.cpp, line 510 instead.

**Comment by DelazJ** [comment]
@m-kuhn You mean, changing it to `bool baseUnit = mSettings->value( "qgis/measure/keepbaseunit", true ).toBool()` ?

**Comment by m-kuhn** [comment]
Yes

**Comment by DelazJ** [comment]
fixed

**Comment by nyalldawson** [comment]
You'll also need to update all the other places this setting is accessed, ie:

- qgsmeasuredialog.cpp:252
- qgsmaptoolidentify.cpp:676 and 684

Big +1 from me though

Another tip - if you reword your commit message to "Keep base units as default behaviour (fix #15434)" then the ticket on hub will be autoclosed and linked to this commit

**Comment by DelazJ** [comment]
Thanks for the tip. I thought it was enough to add it in the PR (title or first message) as it works in QGIS-Documentation repository.

**Pull request merged**
