### PR TITLE
[FEATURE][locator] Add bookmark search to locator bar

### PR DESCRIPTION
**Pull request by klavspc**
Allows search for spatial bookmarks. Double clicking a search result will zoom to the bookmark.

Short video: https://www.youtube.com/watch?v=ymW4TU8QWy4

### CODE REVIEW

**Comment by Gustry** [comment]
I made a previous PR nearly related to the same feature: https://github.com/qgis/QGIS/pull/5306
It was on my roadmap to add the `goto bookmark` ;-)
I would be happy if can merge our work!

I made the PR just before the 3.0 feature freeze. I want to come back for 3.2

**Comment by nyalldawson** [comment]
@Gustry your new github avatar is wayyy too similar to Tim's ... i keep getting confused!

**Comment by nyalldawson** [comment]
Code looks good - (for public reference @klavspc and I have discussed the changes to the bookmarks themselves -- it's unfortunate that none of this code is available in the core api and available for use cases like this and plugins. But in the meantime I think the changes there are acceptable given the current state of the bookmark handling API.)

Some notes:
- Can you please add the "[FEATURE]" tag to the original commit message, and add the details of how this locator filter works inside the commit message itself? There's a hook in place which will auto-open a ticket for the documentation team, so the more detail available in the commit message the easier their job is.
- You need to set up your pre-commit hook to run scripts/prepare-commit.sh . This will apply the automatic code formatting scripts which are causing the CI failure.

Lovely work!

**Comment by klavspc** [comment]
@nyalldawson: Commits have been squashed with "[FEATURE]" title and details in description. Thanks for feedback and notes

**Comment by nyalldawson** [comment]
@klavspc Can you please resolve the conflicts here and then I'll merge?

**Comment by klavspc** [comment]
@nyalldawson Conflicts have been resolved

**Comment by nyalldawson** [comment]
Great work @klavspc !

**Pull request merged**
