### PR TITLE
Move widgets from Q(Double)SpinBox to Qgs(Double)SpinBox 

### PR DESCRIPTION
**Pull request by DelazJ**
based on https://github.com/qgis/QGIS/pull/38948#issuecomment-697958015. Anything else to do?

Couldn't find how to make some plugins and providers dialogs use it.

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]
You'll need to add `${CMAKE_SOURCE_DIR}/src/gui/editorwidgets` to 
https://github.com/qgis/QGIS/blob/1f7b710e00ff675c88d599eb20a6392b7931cb40/src/providers/grass/CMakeLists.txt#L13 to fix the mac build failure

**Comment by nyalldawson** [comment]
Lovely work!

**Comment by DelazJ** [comment]
The only remaining QSpinBox widgets are available in src/auth/oauth2/qgsauthoauth2edit.ui and src/ui/qgsarcgisvectortileconnectiondialog.ui. No idea where to include the widget to avoid build fail.

**Comment by nyalldawson** [comment]
@DelazJ I don't think it's possible to address the auth ones without a considerable (tricky) reworking of the auth providers.

**Comment by nyalldawson** [comment]
@DelazJ one consequence of this change is that many spin boxes are now showing clear buttons even when set to their initial default values. It's painful, but we should do a sweep of the buttons changed here and ensure that their clear value is correctly set to a reasonable default value...

**Comment by DelazJ** [comment]
Ok. I Will take a look...

**Pull request merged**
