### PR TITLE
Fix duplicated display of TopoGeometry PostGIS layers

### PR DESCRIPTION
**Pull request by strk**
See https://github.com/qgis/QGIS/issues/42551

### CODE REVIEW

**Comment by nyalldawson** [comment]
Can we have a test here?

**Comment by strk** [comment]
> Can we have a test here?

I'm trying to add one, but the `ctest -V -R PyQgsPostgresProvider` command, as documented on top of `tests/src/python/test_provider_postgres.py`, doesn't seem to be running any test, ideas why ?

**Comment by strk** [comment]
For some reason the `ctest` command now works for me

**Comment by strk** [comment]
I still wasn't able to write a test, but meanwhile I've also actually fixed the duplicated display of TopoGeometry columns, which happened only when not only looking in metadata tables.

**Comment by strk** [comment]
Trying to add a test for QgsPostgresConn::supportedLayers in tests/src/providers/testqgspostgresconn.cpp I got a segfault due to some mutex locking. I'm guessing there's some app initialization to be performed prior to be able to use that class ?

Stacktrace of the segfault:
```
Thread 1 "qgis_postgresco" received signal SIGSEGV, Segmentation fault.
0x00007ffff1a15f6b in QMutex::lock() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff1a15f6b in QMutex::lock() () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00005555555c71b3 in QMutexLocker::QMutexLocker(QBasicMutex*) ()
#2  0x00005555555f9cf1 in QMutexLocker::QMutexLocker(QRecursiveMutex*) ()
#3  0x00005555555eb297 in QgsPostgresConn::supportedLayers(QVector<QgsPostgresLayerProperty>&, bool, bool, bool, QString const&) ()
#4  0x00005555555875bc in TestQgsPostgresConn::supportedLayers() ()
```

**Comment by strk** [comment]
Stacktrace with debugging symbols on:
```
QFATAL : TestQgsPostgresConn::supportedLayers() ASSERT failure in QMutexLocker: "QMutex pointer is misaligned", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h, line 228
FAIL!  : TestQgsPostgresConn::supportedLayers() Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 7 passed, 1 failed, 0 skipped, 0 blacklisted, 0ms
********* Finished testing of TestQgsPostgresConn *********

Thread 1 "qgis_postgresco" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff13e6864 in __GI_abort () at abort.c:79
#2  0x00007ffff1885ba3 in QMessageLogger::fatal(char const*, ...) const () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff188501a in qt_assert_x(char const*, char const*, char const*, int) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00005555555ceeab in QMutexLocker::QMutexLocker (this=0x7fffffffce70, m=0x69) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h:228
#5  0x0000555555609ba3 in QMutexLocker::QMutexLocker (this=0x7fffffffce70, m=0x69) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h:238
#6  0x00005555555f6ff9 in QgsPostgresConn::supportedLayers (this=0x1, layers=..., searchGeometryColumnsOnly=false, searchPublicOnly=false, allowGeometrylessTables=false, schema=...)
    at /usr/local/src/qgis/qgis/src/wrong-topogeom-column-datatype/src/providers/postgres/qgspostgresconn.cpp:936
#7  0x0000555555588856 in TestQgsPostgresConn::supportedLayers (this=0x7fffffffd740)
    at /usr/local/src/qgis/qgis/src/wrong-topogeom-column-datatype/tests/src/providers/testqgspostgresconn.cpp:141
#8  0x00005555555857d1 in TestQgsPostgresConn::qt_static_metacall (_o=0x7fffffffd740, _c=QMetaObject::InvokeMetaMethod, _id=10, _a=0x7fffffffd0a0)
    at /usr/local/src/qgis/qgis/src/wrong-topogeom-column-datatype/build/tests/src/providers/qgis_postgresconntest_autogen/include/testqgspostgresconn.moc:116
#9  0x00007ffff1ab0966 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const () from /lib/x86_64-linux-gnu/libQt5Core.so.5                                                   
#10 0x00007ffff7f736e3 in ?? () from /lib/x86_64-linux-gnu/libQt5Test.so.5
#11 0x00007ffff7f73f8e in ?? () from /lib/x86_64-linux-gnu/libQt5Test.so.5
#12 0x00007ffff7f74641 in ?? () from /lib/x86_64-linux-gnu/libQt5Test.so.5
#13 0x00007ffff7f749ae in QTest::qRun() () from /lib/x86_64-linux-gnu/libQt5Test.so.5
#14 0x00007ffff7f74bb0 in QTest::qExec(QObject*, int, char**) () from /lib/x86_64-linux-gnu/libQt5Test.so.5
#15 0x000055555558562d in main (argc=1, argv=0x7fffffffd8b8) at /usr/local/src/qgis/qgis/src/wrong-topogeom-column-datatype/tests/src/providers/testqgspostgresconn.cpp:182
(gdb) 
```

**Comment by strk** [comment]
According to https://stackoverflow.com/questions/9458664/qthread-assert-failure-in-qmutexlocker-qmutex-pointer-is-misaligned the "QMutex pointer is misaligned" is about an initialization issue. Are the examples of proper ways to initialize the application for testing purposes ?

**Comment by strk** [comment]
Figured: I was not initializing the connection properly

**Comment by strk** [comment]
@nyalldawson test finally in place.
By reverting commit "Fix duplicated display of TopoGeometry layers" the test gives:
> FAIL!  : TestQgsPostgresConn::supportedLayers() Layer qgis_test.TopoLayer1.topogeom returned multiple times by supportedLayers

By reverting commit "Fix display of DataType extracted from layer registry" the test gives:
> FAIL!  : TestQgsPostgresConn::supportedLayers() Compared values are not the same

Now improving the test in case of failure to print more info.  Is harder than it looks...
https://embeddeduse.com/2019/08/05/qcompare-with-custom-qt-types/

**Comment by nyalldawson** [comment]
> Now improving the test in case of failure to print more info

Is that an enum? If so, it might be as simple as calling the Q_ENUM macro

**Comment by strk** [comment]
> > Now improving the test in case of failure to print more info
> 
> Is that an enum? If so, it might be as simple as calling the Q_ENUM macro

Yes, it's an enum, see my last commit, how would I call Q_ENUM ?

**Comment by strk** [comment]
NOTE the enum is not in  a class definition, and:
```
src/providers/postgres/qgspostgresconn.h:50:1: error: ‘friend’ used outside of class
   50 | Q_ENUM(QgsPostgresGeometryColumnType)
      | ^~~~~~
```

**Comment by nyalldawson** [comment]
Maybe follow https://forum.qt.io/topic/59869/q_enum-enum_name-works-with-only-enums-declared-inside-class-srsly and move it to a namespace?

**Comment by strk** [comment]
Uhm, annoying that CI "all but providers" test is running the postgresconn test :(
I understand it does work, before my added test, because the postgresconn unit test did NOT test anything related to actually connecting to the database, but does it make sense ?
@jef-n would you agree in skipping the whole test in CI for the "all-but-providers" is run ?

@nyalldawson I'd rather NOT change the header file if possible, my local .cpp implementation works, and adding a namespace is far from being "a simple as using Q_ENUM"...

**Comment by strk** [comment]
@nyalldawson what was that backports31608 label ?

**Comment by strk** [comment]
I saw you closed all backports, shall I backport manually ?

**Comment by nyalldawson** [comment]
@strk
>what was that backports31608 label ?

@m-kuhn and I are trialling a new approach to the LTR backports

**Comment by strk** [comment]
@nyalldawson let me know if you want me to backport manually, and if so to which branches

**Pull request merged**
