### PR TITLE
[needs-docs] Status bar icons; #45 in UIX

### PR DESCRIPTION
**Pull request by Cracert**
## Description
Status bar icons replacing text description. More details in discussion: https://github.com/qgis/qgis3_UIX_discussion/issues/45

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them

### CODE REVIEW

**Comment by timlinux** [comment]
Can you share a screenshot?

**Comment by Cracert** [comment]
Still working on too old OS and I didn't compiled it, so have no screenshot. Shame on me, but just lack of time. This PR contains only three SVG files. Here are PNG renders:

status_xy - coordinates

status_magnifier - magnifier

status_rotation - rotation

**Comment by nirvn** [comment]
While I agree the status bar is very crowded, I'm not 100% sure changing the text to a glyph works here. Right now, icons in the status bar are *all* linked to buttons. Changing the text to an icon could be confusing for new users (i.e. which icon is interactive, which one is simply descriptive of a widget next to it).

**Comment by Cracert** [comment]
Very good point @nirvn.  
What about leaving descriptive icons grey, while adding some colors to interactive icons?

**Comment by nirvn** [comment]
@Cracert , @nyalldawson , I'm closing this PR; there has been other suggestions / ideas raised to fix the status bar, it'll be good to do a broader brainstorm on way to move forward.

**Pull request closed without merging**
