### PR TITLE
[WIP Do not merge] [WFS provider] Revert to using singular TYPENAME keyword for WFS 2.0 DescribeFeatureType (fixes #18882)

### PR DESCRIPTION
**Pull request by rouault**
This reverts *partially* commit ccb4c80.

The plural form of TYPENAMES is non conformant for the DescribeFeatureType
request of WFS 2.0
The logic of ccb4c80 breaks conformant servers because they ignore the TYPENAMES parameter and thus return a DescribeFeatureType response covering all layers of the service, which can
be extremely time consuming.

Changes related to better geometry handling have been kept.

Add a GUI option to ask WFS 2.0 DescribeFeatureType to use non conformant TYPENAMES keyword (fixes #18882)

Following the revert of ccb4c80 done in 7511d1f, we add a manual option to let the user decide if they want to use the non conformant TYPENAMES keyword for DescribeFeatureType. As far as we know, there is no clean way of automating this that wouldn't have adverse consequences for conformant servers.

### CODE REVIEW

**Comment by elpaso** [comment]
LGTM, thanks for adding the config option.

**Comment by rouault** [comment]
@elpaso Are there public URLs of such servers that require TYPENAMES for DescribeFeatureType ?

**Comment by elpaso** [comment]
@rouault  I think it all started from https://issues.qgis.org/issues/17872

**Comment by rouault** [comment]
Interesting. curl "http://geoportal.samregion.ru/wfs12?SERVICE=WFS&REQUEST=DescribeFeatureType&TYPENAME=EC_1_132&VERSION=2.0.0" actually returns an Exception that typeNames is missing. So I guess that instead of cluttering the UI, I will just detect the exception and switch to TYPENAMES then

**Comment by rouault** [comment]
Superseded by https://github.com/qgis/QGIS/pull/7057

**Pull request closed without merging**
