### PR TITLE
Fixes relation reference widget several issues

### PR DESCRIPTION
**Pull request by troopa81**
# Description

This PR fixes various bug in relation reference widget combobox.
- A regression coming from PR #34355 (see this [comment](https://github.com/qgis/QGIS/pull/34355#issuecomment-593455667) ).
- https://github.com/qgis/QGIS/issues/34537 : Allow settings null in relation reference widget
  The default constructed QVariant when there is no selected values is invalid (type is QMetaType::UnknownType), which break [this](https://github.com/qgis/QGIS/blob/master/src/gui/qgsattributeform.cpp#L1039). 
- Thread access to shared memory ressource
- ComboBox entries populating

I removed the `updateIndex` method because it changes the current index even if doesn't need to. The strategy of which item to prefer between null and a possible entry is now done in `QgsFeatureFilterModel::updateCompleter`.

Once we agree on this PR, I will backport manually in 3.10 and 3.12 with #34355

### CODE REVIEW

**Comment by elpaso** [comment]
@troopa81 I'm sorry but I have no time to pull and build and test your branch right now but as long as you were able to reproduce the various issues and you are confident they are fixed I would suggest to merge it to master (that will make it quicker to test).

The required condition is that if after the merge there are still issues you will be able to jump back on them again quickly.

How does it sounds?

**Comment by troopa81** [comment]
@elpaso 

OK, let's merge on next monday (I'll ping you). I'm not available at the moment to fix possible regression.

FYI, CI fails because of rulebasedrenderer test, which I think has nothing to do with this PR.

**Comment by troopa81** [comment]
@elpaso Let's merge? I can wait for backport if you'd like to test in the days to come.

**Comment by elpaso** [comment]
@troopa81 I trust your confidence :) I'm not able to test it right now.

**Pull request merged**
