### PR TITLE
Relation reference widget: connect changed signal from embeded attrib…

### PR DESCRIPTION
**Pull request by mhugent**
The relation reference widget can show an embedded form (mReferencedAttributeForm) and this form can be editable. Unfortunately, it seems that QGIS is not notified about the changes if editing only this form (it however works, if other attributes are edited as well). Therefore such edits are not written and if the dialog is closed and reopened, the old values are still there.

Connecting the signal widgetValueChanged of the form solves the problem for me. However I'm not very familiar with this part of the code, do you think this is a good change or are there side effects?

### CODE REVIEW

**Comment by m-kuhn** [comment]
I think we need to be careful here, there is plenty of logic inside `QgsAttributeForm` for validation, updating default values etc that is bypassed if we hardwire a widget change to layer edits.

I believe saving should go through `save()` (or `saveWithDetails()`). @signedav and @domi4484 you have recently worked on things related to auto updating default values in child forms where the challenges/API in use was similar?

**Comment by mhugent** [comment]
> sorry, is this related also to N:M relations? #43992

I think this one is a different issue than #43992

**Comment by signedav** [comment]
Concerning the conceptional part: I think it's similar to the issues around this one https://github.com/qgis/QGIS/issues/41243 where it concerns the Relation Editor Widget instead and mainly virtual fields (what has been fixed later by https://github.com/qgis/QGIS/pull/46167). Anyway we noticed there the "issue" that apply-on-edit default values are not changed when the related feature changes, but as written here https://github.com/qgis/QGIS/issues/41243#issuecomment-861316615 we decided that it's not necessarily an "edit" on the current feature when the values of a referencing (or referenced) feature change. But this is of course debatable. I understand that on embedded forms users usually think it's the "same" feature they are editing...

Concerning code: Automatic updates of features / field values always could lead to performance issues, what does not mean, that it should not be done. Just to check clearly. As far as I see it in this case I guess it's not more dangerous than a change on the value on any other widget. But I can double check as soon as we agree on the concept.

**Comment by mhugent** [comment]
Thanks for your thoughts. I'm not sure this is the same issue. Or maybe it is , I'll try to explain the use-case.

I have three tables: 'anlagen', 'nutzungen' and 'konzessionen'. 'anlagen' is the table with geometry. 'nutzungen' has two foreign keys, one points to 'anlagen' and one to 'konzessionen'. There are no virtual fields in the tables. Setting all the table editable (transaction mode) and using the info-tool on 'anlagen', I get the following form:

edit_form2

When editing test_comment_konzessionen to something else , (without the signal/slot connection in the PR), the edits are not written to 'konzessionen', the pen on the layer 'konzessionen' stays the same color. If closing and reopening the dialog, the old value is still there.  However if any attribute of 'nutzungen' is edited, the edits to 'konzessionen' are saved. Also if the button left of the + is used and the value is edited in the popup-form, the edits are also fine.

I think this is confusing for users. If the embeded form is not supposed to be used for edits, it would be better to have the ui-elements grayed out.

**Comment by signedav** [comment]
So the embedded form does not update, even when you edit in there? Hm... I agree, that this is (1) not what I meant and (2) something that is supposed to be possible.

**Comment by signedav** [comment]
Still I wonder if there are no better approaches to fix it. It seems like a workaround. It doesn't looks dangerous but neither nice. Maybe I'll find the time to have another look.

**Comment by m-kuhn** [comment]
> I think this is confusing for users. If the embeded form is not supposed to be used for edits, it would be better to have the ui-elements grayed out.

I fully agree, this is not the "principle of least surprise"

How is this currently handled in the form view of the attribute table? This has the same requirements in terms of "there is no save button where the user actively confirms the changes".

**Pull request closed without merging**
