### PR TITLE
Try to reactivate tests for legend and json export

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

Unit tests are green on Arch. Let's take a look on Travis...

### CODE REVIEW

**Comment by nyalldawson** [comment]
Is the rendered result here correct? When I disabled the test the rendered result wasn't taking into account the opacity. Has it since been fixed?

**Comment by pblottiere** [comment]
> Is the rendered result here correct? When I disabled the test the rendered result wasn't taking into account the opacity. Has it since been fixed?

Yes it seems so. Here is what I got for the blue icon and the `0.5` opacity generated in `/tmp/point_layer_icon_blue_opacity.png` by `ctest`:

blue

Same results for the red and green icons.

**Comment by nyalldawson** [comment]
Hmm ok - guess something has fixed it in the meantime!

**Review by nyalldawson — APPROVED** [review]

**Comment by pblottiere** [comment]
> guess something has fixed it in the meantime!

Well, I'm curious to know if it's still happening on your environment (if you have time of course). Because I didn't see any bugfix related to that since you deactivated the test, so it could be a false positive.

**Pull request merged**
