### PR TITLE
Refactor annotations, add new annotation features + some other exciting stuff

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR refactors annotations. Instead of having everything implemented as QGraphicsItems handled by the QgsMapCanvas, we now have:

- QgsAnnotation: an abstract base class for annotations. Handles common annotation properties and rendering annotations to a QgsRenderContext. The text/svg and html QgsAnnotation subclasses are now in core, QgsFormAnnotation resides in gui (has a dependency on editor widgets).
- QgsAnnotationManager: attached to the project. Handles storage, writing and reading QgsAnnotations from XML.
- QgsMapCanvasAnnotationItem: a QgsMapCanvasItem subclass in which a QgsAnnotation is rendered. Handles moving and resizing the item to match it's associated QgsAnnotation's position and size changes.

This work has two motivations:
1. Composer directly renders QgsAnnotations - it no longer relies on the Qt graphics scene framework. This means I can finally break the last link between canvas and composer maps.
2. Annotations will work correctly in a multi canvas environment. A single QgsAnnotation can be displayed in multiple canvases, each with their own QgsMapCanvasAnnotationItems handling positioning the annotation correctly for that canvas (respecting canvas CRS and extent)

But while I was at it I couldn't help but add some stuff:
1. Annotations can have left/right/top/bottom margins set, making it possible to create nicer looking annotations with precisely placed contents
2. Annotations now use fill symbols to render the frame. This means gradients, shapebursts, paint effects, even data defined styling in atlas is possible with annotations
3. I've cleaned up the handling of associating annotations with layers. This was very confusing and opaque for users before. Now all annotation types can be associated with a layer (via the config dialog for the annotation), and the layer linked can also be cleared. Composer correctly handles syncing annotation visibility with the composer map layer set.
4. moving annotation reference points will respect project snapping settings

### CODE REVIEW

**Comment by nirvn** [comment]
Nyall, I don't understand, Christmas is still 11 months away... ;) great work! Being able to style annotations using symbology is huge.

**Comment by nyalldawson** [comment]
screenshot from 2017-01-30 15-44-54

**Comment by wonder-sk** [comment]
Awesome work! :tada: :tada: :tada: 

Just few comments:
- I think HTML annotations can be added to the registry also when webkit is not available - they will just not render correctly, but they could be still correctly loaded/saved
- as annotations can be related to map layers, there is again the issue with QgsProject::instance() and resolution of map layers from layer IDs. It may be good to use QgsMapLayerRef within annotations, do not resolve map layers from project singleton and have a new method resolveReferences(QgsProject*) that will turn layer IDs into layer objects. Right now I am doing something like that for vector joins and I can make annotations use the same pattern once this PR is merged
- another dependency on QgsProject is with reading/writing of paths to switch between relative and absolute ones. Maybe we would not need QgsProject there either and have something like QgsPathConvertor / QgsPathResolution (?) passed to readXml/writeXml - this would be useful in various other places like map layers or composition items. (something for a future PR, just gathering feedback on that idea :-) )

**Comment by wonder-sk** [comment]
Now we just need rounded corners for annotations :wink:

**Comment by nirvn** [comment]
Rounded corners achieved through geometry generator symbology? ;)

**Comment by nyalldawson** [comment]
> I think HTML annotations can be added to the registry also when webkit is not available - they will just not render correctly, but they could be still correctly loaded/saved

Good point, i'll fix this.

> as annotations can be related to map layers, there is again the issue with QgsProject::instance() and resolution of map layers from layer IDs. It may be good to use QgsMapLayerRef within annotations, do not resolve map layers from project singleton and have a new method resolveReferences(QgsProject*) that will turn layer IDs into layer objects. Right now I am doing something like that for vector joins and I can make annotations use the same pattern once this PR is merged

Right. Do I take your last sentence as a volunteer to do this change? ;)

> another dependency on QgsProject is with reading/writing of paths to switch between relative and absolute ones.

Every time I wrote QgsProject::instance() i died a little inside thinking of the extra work I was making for you. Sorry!

> Maybe we would not need QgsProject there either and have something like QgsPathConvertor / QgsPathResolution (?) passed to readXml/writeXml - this would be useful in various other places like map layers or composition items. (something for a future PR, just gathering feedback on that idea :-) )

Is it only the path resolution which is an issue here? I suspect there may be more lurking around. I'd lean toward just passing the project on every read/write xml call as a more future proof alternative.

> Now we just need rounded corners for annotations :wink:

agreed! Some time in future I'll make an QgsCallout abstract base class and some concept of "anchor points", with various callout styles in subclasses (speech bubbles, blocks with perpendicular callout lines, etc). Maybe in QGIS 4...

Another important thing to note:

I think in future we probably want to implement annotations as a labeling provider. This way labels could avoid the position of annotations, and there'd also no longer be a need for the QgsMapCanvasAnnotationItem item.  Interaction with annotations would follow the same pattern as labels. But this PR is at least a step toward that, and was also a whole lot less work then tackling this all at once.

**Comment by nirvn** [comment]
@nyalldawson , testing this PR is too much fun:
love

I did notice a drawing issue with offset > 0 outline: simplie line symbology:
peek 2017-01-30 13-58

It's no big deal as the artifacts go away when you refresh the canvas.

**Comment by nyalldawson** [comment]
@nirvn do you think the marker symbol should render below the annotation frame?

**Comment by nirvn** [comment]
@nyalldawson , yeah, that'd be preferable.

**Comment by nirvn** [comment]
@nyalldawson , actually, if you look at the first example, the market symbol (the explosion symbol) looks nicer when on top of the frame.

If it's not too hard, an option to pick ordering of marker and frame would be nice.

**Comment by wonder-sk** [comment]
> Right. Do I take your last sentence as a volunteer to do this change? ;)

Kind of... yes :-)

> Every time I wrote QgsProject::instance() i died a little inside thinking of the extra work I was making for you. Sorry!

Haha no worries!

> Is it only the path resolution which is an issue here? I suspect there may be more lurking around. I'd lean toward just passing the project on every read/write xml call as a more future proof alternative.

Yeah I think it is just path resolution... and there are also places where we need absolute/relative path resolution which are not related to project. In general I would like to avoid having dependencies on QgsProject unless necessary for various reasons, mainly to limit how far classes can actually reach outside of their territory :-)

> I think in future we probably want to implement annotations as a labeling provider.

Yeah that sounds like a very nice idea!

**Comment by nyalldawson** [comment]
@wonder-sk was your comments a +1 to merge? or would you like to fully review?

**Comment by wonder-sk** [comment]
Yeah it is +1 for me to merge!

**Pull request merged**
