### PR TITLE
[needs-docs] Move the install-plugin-from-ZIP menu action to the plug…

### PR DESCRIPTION
**Pull request by borysiasty**
Move the *Install plugin from ZIP* from menu action to the Plugin Manager button. 
Also add a spacer before the Settings item.

screenshot_20171016_012555

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script] before each commit

### CODE REVIEW

**Comment by NathanW2** [comment]
Nice.  That looks and makes a lot of sense. +1 form me.

**Comment by alexbruy** [comment]
Maybe replace button with file selector (lineedit + button) like in all other QGIS dialogs? This will be more consistent with the rest of UI

**Comment by nyalldawson** [comment]
> Maybe replace button with file selector (lineedit + button) like in all other QGIS dialogs? This will be more consistent with the rest of UI

I agree - this should use QgsFileWidget

**Comment by tomchadwin** [comment]
+1 for this with a file selector. Nice.

**Comment by borysiasty** [comment]
Thanks guys, here it is. The button is active if the path is a file.

screenshot_20171016_233703

**Comment by nyalldawson** [comment]
Perfect - now it'll support drag and dropped zips, which is a big plus for me

**Comment by NathanW2** [comment]
Graet work.  Merge it if others are happy.

**Comment by rduivenvoorde** [comment]
I'm happy with this :-)
Thanks @borysiasty 
@alexbruy what do you think?

**Comment by borysiasty** [comment]
Ok, seems everybody is happy.

**Pull request merged**
