### PR TITLE
When a new project is saved, "Project Home" does not appear in the browser panel

### LINKED ISSUE #33230: 'project home' not showing up in browser directly
After creating/saving a new project somewhere in a folder, the 'project home' in browser-panel should pop up, but it don't. Just after restarting the project (close and open), the 'project home' is displayed.

To reproduce:
1. Open QGIS
2. Save a empty Project (Save as / Save)
3. Look at the browser (no 'project home')
4. close the project
5. restart the project
6. look at the browser ('project home' is there!)

QGIS Version:

> 
> QGIS version | 3.10.0-A Coruña | QGIS code revision | 6c816b4204
> -- | -- | -- | --
> Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
> Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
> Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
> Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
> PostgreSQL Client Version | 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
> QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
> PROJ.4 Version | 493
> OS Version | Linux Mint 19.2
> Active python plugins | nominatim; quick_map_services; FreehandRasterGeoreferencer; searchlayers; SaxonyCadastralParcels; ArcheoCAD; QuickOSM; db_manager; MetaSearch; processing

### PR DESCRIPTION
**Pull request by suricactus**
When a new project is saved, "Project Home" does not appear in the browser panel

The bug is due to this changed behavior:
https://github.com/qgis/QGIS/blob/b02350e74d41368f71b20f10927fd175108c5f52/src/core/qgsproject.cpp#L2587-L2592

Fixes https://github.com/qgis/QGIS/issues/33230

### CODE REVIEW

**Comment by suricactus** [comment]
I believe this can be backported back to 3.10.

**Comment by suricactus** [comment]
I broke one of the tests for now, please ignore for now.

**Comment by suricactus** [comment]
Ready to merge.

**Comment by suricactus** [comment]
False fix, don't merge yet.

**Comment by suricactus** [comment]
Now should be fixed :)

**Comment by nyalldawson** [comment]
Thanks @suricactus !

**Pull request merged**
