### PR TITLE
Framework for context based expressions, version 2

### PR DESCRIPTION
**Pull request by nyalldawson**
(possibly supersedes #2181)

Version 2 of context based expressions, based on the feedback from #2181. 

@wonder-sk how's this look to you?

### CODE REVIEW

**Comment by nyalldawson** [comment]
note, obviously not mergeable yet due to tons of deprecated warnings and missing doc strings!

**Comment by NathanW2** [comment]
Note going with @variable for syntax?

**Comment by nyalldawson** [comment]
@NathanW2 that hasn't made the cut yet - it's on my list :) just want to get this foundational stuff sorted first...

**Comment by nyalldawson** [comment]
Added @variable shorthand, and layer scope methods. 

I've also ported a sample use of expressions over (2231532) to show how evaluation will work. First the whole context is built up from it's component scopes, then for each evaluation the feature is set for the topmost "feature" scope. There should be little performance hit this way (hopefully!)

**Comment by NathanW2** [comment]
\o/ win!

**Comment by NathanW2** [comment]
What is the status of this PR?  Still a work in progress?

**Comment by nyalldawson** [comment]
@NathanW2 getting closer, but still some work to do. A new version of this PR will be landing shortly...

**Comment by NathanW2** [comment]
No worries. I would like to use it in #2209 however I can just do the search replace for now and swap it later.  I still have other stuff in that PR anyway so no rush.

**Comment by nyalldawson** [comment]
Superseded by #2238

**Pull request closed without merging**
