### PR TITLE
Split self intersecting lines only on split points

### LINKED ISSUE #14070: Split Features tool: lines are split also at every self-intersection
Author Name: **jcnotter -** (jcnotter -)
Original Redmine Issue: [4087](https://issues.qgis.org/issues/4087)
Affected QGIS version: 3.7(master)
Redmine category:digitising

---
When you use this function to a location, it splits the polyline at each intersections on the polyline and you get a lot of polylines and not 2 as you want
Example : for separating the return track, you get many little tracks ...

---

- [temp.zip](https://issues.qgis.org/attachments/download/3342/temp.zip) (jcnotter -)
- [split.zip](https://issues.qgis.org/attachments/download/9117/split.zip) (Pedro Venâncio)

---

Related issue(s): #29256 (duplicates)
Redmine related issue(s): [21439](https://issues.qgis.org/issues/21439)

---

### LINKED ISSUE #27904: Split Tool "Bursts" linestring when used on complex linestring
Author Name: **Simon Dellis** (@sjdellis)
Original Redmine Issue: [20082](https://issues.qgis.org/issues/20082)
Affected QGIS version: 3.4.1
Redmine category:digitising

---
When using the Split tool on a complex linestring (lots of nodes) the linestring "bursts" into many segments. Attached is a sample shapefile that causes the issue and the result after using the split to once.

Simple line strings are not a problem.

Reproduced the problem on versions from 2.18.13 to 3.2.3 on Windows 10 Pro and Enterprise. The same file in Arc splits as expected.

Using the "Split with Lines" tool generates similar problems.

---

- [test.zip](https://issues.qgis.org/attachments/download/13479/test.zip) (Simon Dellis)
- [test-split.zip](https://issues.qgis.org/attachments/download/13480/test-split.zip) (Simon Dellis)

### LINKED ISSUE #35670: Split with lines - unexpected behaviour
**Describe the bug**
Split with Lines: when lines from input layer intersect lines from split layer at the exact same point, the operation is not performed.

**How to Reproduce**

1. Take [sample_data.zip](https://github.com/qgis/QGIS/files/4450964/sample_data.zip)
1. Add input_features.shp and split_feature.shp. input_features contains 3 lines, two of them intersects each other at the exact same point they intersec the split_feature  (FID= 0 and 2)
2. Click on Processing Toolbox > Vector Overlay > Split with lines
3. See unexpected behaviour --> input_features FID= 0 and 2 are not splitted by split_feature.

**QGIS and OS versions**
OS: Arch Linux x86_64
Kernel: 5.6.2-arch1-2
DE: GNOME (Wayland)

QGIS version | 3.12.0-București | QGIS code branch | Release QGIS code branch.3
Compiled against Qt | 5.14.1 | Running against Qt | 5.14.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.4
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Arch Linux
Active python plugins | QNEAT3; networks; SentinelHub; timeseriesviewerplugin; db_manager; MetaSearch; processing

### PR DESCRIPTION
**Pull request by uclaros**
## Description
When trying to split self intersecting lines (like a track log for example) using either a point or another line qgis also splits the line on each self intersection.
This bug is quite old, first time reported more than ten years ago (actually right now it is the oldest non-upstream bug in the queue!)

Fixes #14070 
Fixes #27904
Fixes #35670
Also fixes unreported bug: qgis crashes when trying to split a `CompoundCurve` by using a point on one of its vertices.

Adding some tests soon.

### CODE REVIEW

**Comment by gioman** [comment]
@uclaros thanks! would this also solve this?


https://user-images.githubusercontent.com/1951107/153645104-aabd9312-0e67-4209-bc25-0c367dc43c28.mp4


basically, with the multiline you can see in the cast, if you try to split at the intersection of lines the operation fails, and if you split above the intersection the operation works, but also split the line at the intersection, in a very unexpected way.

On similar scenarios I also experienced total loss of one of the resulting geometries.

**Comment by uclaros** [comment]
@gioman Probably yes, are those lines self-overlapping where the split happens? If you shared your line I could test!

**Comment by gioman** [comment]
> If you shared your line I could test!

@uclaros here it is!

[multiline.zip](https://github.com/qgis/QGIS/files/8051027/multiline.zip)

**Comment by uclaros** [comment]
Hmmm, I think your multiline doesn't split unexpectedly after all. If you do a `multiparts to singleparts` you'll see the logic: The intersection is only an endpoint or startpoint for the three parts of the multiline, that's why you can't split. Then by splitting higher, the upper branch gets properly split in two and both parts detach from the multiline into new features.

**Comment by nyalldawson** [comment]
Frozen till post 3.24.0 release

**Review by lbartoletti — APPROVED** [review]

**Comment by AdriNicolau** [comment]
Hi @uclaros, we will have this fix as a backport for the LTR version?

**Comment by uclaros** [comment]
> Hi @uclaros, we will have this fix as a backport for the LTR version?

@AdriNicolau With this being a really longstanding bug and the fix being a reimplementation of the split logic, I would say probably not...

**Pull request merged**
