### PR TITLE
[Server] The RFC 7946 GeoJSON specification recommends limiting coordinate precision to 6

### PR DESCRIPTION
**Pull request by rldhont**

### CODE REVIEW

**Comment by nyalldawson** [comment]
Looks good to me. I'm not sure about backporting though - couldn't this possibly affect existing scripts? (That said I doubt this class is used much by plugins!)

Also note to self - rename JSON -> Json

**Comment by rldhont** [comment]
Hi @nyalldawson, I need to backport to 2.18 to avoid the use of precision and force it to 6 in server.

**Comment by nyalldawson** [comment]
Could you just override the prec in qgswfsgetfeature.cpp whilst leaving the default value the same? (To clarify I'm fine with changing the default in master, it's just 2.18 I'm concerned about)

**Comment by rldhont** [comment]
OK, I will not do the same for 2.18.
But what about the RFC in 2.18 ?

**Comment by nyalldawson** [comment]
Actually.... On second thoughts... Just make the change. I don't think it'll have any real world impact given that it's unlikely anyone relies on this method for that kind of precision anyway.

**Review by nyalldawson — APPROVED** [review]

**Comment by rldhont** [comment]
@nyalldawson the spellcheck failed but can I merge ?

**Comment by nyalldawson** [comment]
Merge away... That error isn't related to your change!

**Comment by rldhont** [comment]
tahnks

**Pull request merged**
