### PR TITLE
Restore more processing algs

### PR DESCRIPTION
**Pull request by nyalldawson**
Brings back a bunch of algorithms, removes some duplicate ones.

Removed python algs are:
- Centroids
- Clip
- Dissolve
- Extract by attribute
- Extract by expression
- Multipart to singlepart
- Polygon centroids
- Reproject layer

(native c++ alternatives exist now)

Remove deprecated algorithms:

- Basic Stats for Numbers/String algs (replaced by generic
Basic Stats alg)
- Split Lines with Lines (replaced by generic Split with lines)
- Vector Grid Lines/Polygons (replaced by other create grid
algs)

### CODE REVIEW

**Comment by m-kuhn** [comment]
nice. I didn't check thoroughly, I just trust the tests.

I recently had a python exception div by 0 for an empty layer. A random caveat while working on this.

**Comment by nyalldawson** [comment]
> I recently had a python exception div by 0 for an empty layer. A random caveat while working on this.

I'll fix this :)

**Comment by nyalldawson** [comment]
@m-kuhn Fixed in  99cfb8f

**Comment by m-kuhn** [comment]
wheee thanks

**Pull request merged**
