### PR TITLE
Geopackage: browser homogenize

### PR DESCRIPTION
**Pull request by elpaso**
## Description

This PR fixes a couple of issues with the gpkg data items in the file browser that now use the geopackage specialized data items and adds the possibility to add/remove gpkg connections from the file browser.

Drag and drop from/to gpkg is now possible in the browser too.

gpkg-dataitems

### CODE REVIEW

**Comment by nyalldawson** [comment]
Nice improvements! Is adding gdb support now just a matter of adding that extension to the db extension check?

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Ok - it's a bit more involved then just adding those extensions. Can you cherry-pick 

https://github.com/nyalldawson/QGIS/commit/ae52b48a62a2955b6e079e8085b183d2655cc934
https://github.com/nyalldawson/QGIS/commit/7d39ab0805771e47d358944a22b5fa607a380128
https://github.com/nyalldawson/QGIS/commit/a0359d42c29a70beb12fec4f408321af1eca615a

from https://github.com/nyalldawson/QGIS/commits/boundlessgeo-browser_homogenize ?

These three commits unlock full support for browsing esri filegdb directories in the browser (crappy format though it is... it's still quite popular in Australia unfortunately!)

screenshot from 2017-09-19 10-02-12

**Comment by gioman** [comment]
This should fix this https://issues.qgis.org/issues/16091

**Comment by nyalldawson** [comment]
> This should fix this https://issues.qgis.org/issues/16091

Thanks - I had a feeling there was a ticket regarding it, but couldn't find it

**Pull request merged**
