### PR TITLE
fix HttpHeaders settings backward compatibility for OWS

### LINKED ISSUE #57499: WMS/WFS http headers not saved
### What is the bug or the crash?

A WMS connection is set with a http header 
image

After closing and reopening QGIS, header is gone.

### Steps to reproduce the issue

1. Create new WMS connection
2. URL : https://data.geopf.fr/private/wms-r?VERSION=1.3.0
3. In HTTP headers, advanced, add new key : `apikey` with value `ign_scan_ws`
4. Connect and you can add a layer.
5. Close QGIS
6. Open QGIS
7. Try to connect to previouly added connection
8. Error
9. If you edit, you can see header is gone.

### Versions

3.36.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 3nids**
fixes #57499

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nicogodet** [comment]
It does not fix the related issue

**Comment by nicogodet** [comment]
It seems that this PR creates `connections-wms` under `[qgis]` in QGIS3.ini while 3.36 or 3.34 does not.

**Comment by 3nids** [comment]
This is expected.
I think I found another issue https://github.com/qgis/QGIS/commit/d0d74652440c626b5192bf4eb3a981fb22826857#diff-ca7842e704765debda9335cfe95b6b273ec123c6a1e812ff7bc4d1d885d24e33L488
The settings group have been removed in this commit.

**Comment by 3nids** [comment]
next try

**Comment by 3nids** [comment]
@nicogodet I believe it's good this time!

**Comment by 3nids** [comment]
@nicogodet any chance to confirm it's fixed in master?

**Comment by nicogodet** [comment]
@3nids I confirm it's fixed (tested with Windows build in this PR). Nice !

**Comment by 3nids** [comment]
great thanks for the feedback!

**Pull request merged**
