### PR TITLE
Update the comparison implementation in voronoi.py (fixes #18219)

### PR DESCRIPTION
**Pull request by havatv**
## Description
New (after second commit): The cmp function introduced with the Python 2 -> 3 upgrade contained a greater than (>), but the __gt__ function was missing in Site and Halfedge.  I have changed cmp to only use less than (<), and have modified the __lt__ functions to return False in the last else.
Old: When "translating" the cmp function of Site and Halfedge to Python 3, the __gt__ function was forgotten.  It has been added.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Thanks for your hard work here!

I'd love to get a unit test in place protecting this situation. Are you comfortable adding one, or would you like some guidance?

**Comment by havatv** [comment]
I have no experience with unit tests, but I could provide a dataset that covers more cases than the existing one.
And sorry for changing so much in the latest commit - I found out that the __gt__ function could be avoided by changing the cmp function to only use < (less than).

**Comment by havatv** [comment]
I tried to add a test in pull request #7557.

**Comment by nyalldawson** [comment]
Thank you!

**Pull request merged**
