### PR TITLE
Fix profile creation and absence of tbl_srs in qgis.db

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR fixes related issues which leads to - among other things - a broken custom projections dialog.

Long story short, if QGIS starts and its root profiles directory is missing, it'll proceed forward with creating a default profile (and in doing so creating a profiles directory) via QDir().mkdir(). Turns out this doesn't work reliably when one needs to create *multiple* directories in the full path. We're fixing that by moving to QDir().mkpath().

This lingering issue was leading to the second problem being fixed here, whereas qgis.db was not copied properly upon profile creation when QDir().mkdir() failed. That caused an empty qgis.db to eventually be created, with the crucial tbl_srs and tbl_projection (as well as tbl_ellipsoid, which is not really a problem for GDAL > 2) missing.

Without tbl_srs, the custom projection dialog was missing. 

The second commit fixes that situation by creating a tbl_srs table when launching QGIS if we detect its missing from qgis.db.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [x] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , am I correct when thinking that the tbl_ellipsoid and tbl_projection tables are not used when QGIS is built against GDAL 3?

**Comment by nirvn** [comment]
The tbl_projection is also needed as it is part of the view used to show custom projections in the projection selector widget.

Note: the reason why I'm not merely overwrite qgis.db with the shipped default when tbl_srs and/or tbl_projection are missing is to avoid any user data already present in qgis.db (unlikely, but still).

**Comment by nirvn** [comment]
(Travis fails on an unrelated mesh test failure).

**Comment by nirvn** [comment]
@nyalldawson , good to merge?

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
