### PR TITLE
Show a warning when the move label tool cannot be used on a label

### PR DESCRIPTION
**Pull request by nyalldawson**
E.g. when a layer is set to store label x/y in a real field (not
an aux field), then that layer must be editable in order to move
labels in it. Otherwise the move operation fails, but users are
left no clue as to why the label can't be shifted...

(this one has confused/frustrated me for a long time, and I only just today worked out why i couldn't move some labels...!)

### CODE REVIEW

**Comment by nyalldawson** [comment]
Better approach pushed - we now automatically enable editing on the layer (when we can), and notify users that we did this via the message bar

**Comment by nirvn** [comment]
Excellent

**Comment by nirvn** [comment]
You'll need the same adjustments for the rotate tool.

**Comment by nyalldawson** [comment]
@nirvn done

**Review by nirvn — APPROVED** [review]

**Pull request merged**
