### PR TITLE
fix building on macos due to missing include of SpatialIndex.h

### PR DESCRIPTION
**Pull request by PeterPetrik**

### CODE REVIEW

**Comment by jef-n** [comment]
nightly still errors:
```
In file included from /Users/admin/qgis/builds/nightly/build/python/core/auto_generated/labeling/qgslabelsearchtree.sip:22:
In file included from /Users/admin/qgis/builds/nightly/qgis/src/core/labeling/qgslabelsearchtree.h:27:
/Users/admin/qgis/builds/nightly/qgis/src/core/qgsgenericspatialindex.h:30:10: fatal error: 'spatialindex/SpatialIndex.h' file not found
#include <spatialindex/SpatialIndex.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [python/CMakeFiles/python_module_qgis__core.dir/core/sip_corepart2.cpp.o] Error 1
```

**Comment by PeterPetrik** [comment]
obviously this is not merged, so when merged we will see ...

**Comment by nyalldawson** [comment]
Shouldn't that be the libspatialindex, not spatial it's?

**Comment by jef-n** [comment]
> Shouldn't that be the libspatialindex, not spatialite?

If there is only one problem - not sure about that.

**Comment by PeterPetrik** [comment]
I managed to compile it yesteday on the cloud machine, but maybe copied incorrectly my manual changes. let me see again

**Comment by PeterPetrik** [comment]
OK, this version should be good! critical part is to add spatialindex to python/CMakeLists.txt

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
