### PR TITLE
[needs-docs][processing] Use input layer data type for gdal algorithms when appropriate...

### PR DESCRIPTION
**Pull request by nirvn**
## Description
This PR changes the handling of data type for the following gdal algorithms:
- warp (i.e. reproject)
- translate (i.e. file format conversion)
- rearrange bands
- clip by extent/mask

For those algorithms, by default the data type will match that of the input layer.

The idea here is to have a default behavior that better matches expectations of users. For e.g., if someone reprojects a raster layer via the gdal warp algorithm, there's an expectation the data type will not change by default. It's especially true since we (not wrongly) hide the data type setting under a collapsed advanced settings section.

@nyalldawson , @alexbruy , all good with you?

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
(BTW, this is in part motivated by the numerous times when I was teaching users into using processing, and witnessing folks ending up with these enlarged >1gb raster files due to silent data type change from byte to float32.)

**Comment by nyalldawson** [comment]
Looks good to me! Can you add tests also for each modified algorithm with the output type parameter set to a different value?

**Comment by nirvn** [comment]
@nyalldawson , already part of the PR :).

**Comment by nyalldawson** [comment]
Ah I see... it's just the odd diff formatting throwing me off

**Comment by nirvn** [comment]
@alexbruy , if you don't have any objections, I'll merge this PR later this afternoon. Thanks.

**Pull request merged**
