### PR TITLE
Add rpm files to build Fedora/CentOS/RHEL packages

### PR DESCRIPTION
**Pull request by m-kuhn**
Add scripts to create .rpm packages.

### CODE REVIEW

**Comment by m-kuhn** [comment]
@jef-n 
Do you prefer to have the .sh script in the scripts directory?

Do you have any clue concerning the FindGRASS.cmake patch. Is there a reason why NO_DEFAULT_PATH is specified? (I just copied the patch from the Fedora package, no idea if it's necessary and/or good):
```
- FIND_LIBRARY(LIB_PATH NAMES grass_${LIB} PATHS ${G_PREFIX}/lib NO_DEFAULT_PATH)
+ FIND_LIBRARY(LIB_PATH NAMES grass_${LIB} PATHS ${G_PREFIX}/lib)
```

**Comment by jef-n** [comment]
Are the GRASS libraries in a different location than usual on fedora?   On Linux and Windows they are in the same hierachy like the other files.

**Comment by m-kuhn** [comment]
@jef-n They are apparently located in `/usr/lib{64}`

Volker Fröhlich answered with enlightening information, basically pointing out a comment in FindSpatialite where similar magic occurs:


```
# FIND_PATH and FIND_LIBRARY normally search standard locations
# before the specified paths. To search non-standard paths first,
# FIND_* is invoked first with specified paths and NO_DEFAULT_PATH
# and then again with no specified paths to search the default
# locations. When an earlier FIND_* succeeds, subsequent FIND_*s
# searching for the same item do nothing.
```
So I guess the most suitable solution will be to adapt this approach to FindGRASS and add two FIND_LIBRARY calls with/without NO_DEFAULT_PATH

**Comment by m-kuhn** [comment]
Manually merged in e12601ef7f3f1

**Comment by jef-n** [comment]
@m-kuhn NO_DEFAULT_PATH was recently added by @blazek.  It's used to find parallel installs of GRASS 6 and 7.

**Comment by blazek** [comment]
Sorry for not replying earlier, I was not at home few days. Thanks for the fix.

**Pull request merged**
