### PR TITLE
Fix for #39855 diminfo in inserted as string in mdsys query

### LINKED ISSUE #39855: [ORACLE] Can't import vector layer to oracle database
Using DB Manager to import a vector layer to a oracle database gives the following error:

```
Error 2
Creation of data source "TESTE22S"."LOTE" failed: 
Oracle error: Could not insert metadata.
SQL: ORA-00932: inconsistent datatypes: expected MDSYS.SDO_DIM_ARRAY got CHAR
Unable to execute statement
Error: INSERT INTO mdsys.user_sdo_geom_metadata(table_name,column_name,srid,diminfo) VALUES (:a,:bb,:bc,:bd)
```

My config:

```
QGIS version
3.10.11-A Coruña
QGIS code revision
d2171173e4
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
```

Any help are welcome. Thanks.

### PR DESCRIPTION
**Pull request by rduivenvoorde**
This fixes #39855 (when using the browser to load data in a database):

Oracle error: Could not insert metadata.
SQL: ORA-00932: inconsistent datatypes: expected MDSYS.SDO_DIM_ARRAY got CHAR
Unable to execute statement
Error: INSERT INTO mdsys.user_sdo_geom_metadata(table_name,column_name,srid,diminfo) VALUES (:a,:bb,:bc,:bd)

The commit from 2017:
https://github.com/qgis/QGIS/commit/fb409b59a9ab2e748372cf1b0e346cc24144ee7f
says 'using prepared statements', to be asked for in:
https://issues.qgis.org/issues/16251

Not sure if the drag and drop (code path) has ever worked with this.

There are other ways to fix this, for example here: 

https://github.com/rduivenvoorde/QGIS/blob/0d17a1c4f39bf2bff6c695904057af50705ec722/src/providers/oracle/qgsoracleprovider.cpp#L2760-L2764
The diminfo part is half part of the query, only the extent params come via statement variables.
So that could be an alternative implementation.

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Realizing myself now that this actually not a fix for #39855 itself, as importing a file via dbmanager is failing for other reasons now.
What IS possible with this fix is to drag/drop/load data from a file (or postgis) in the Browser.

**Comment by troopa81** [comment]
It looks fine. Thanks

Do you mind adding a test in `test_provider_oracle.py`? Just calling *createEmptyLayer* on QgsProviderMeta sould do just fine.

**Comment by troopa81** [comment]
And the CI issue is unrelated

**Comment by rduivenvoorde** [comment]
> It looks fine. Thanks
> 
> Do you mind adding a test in `test_provider_oracle.py`? Just calling _createEmptyLayer_ on QgsProviderMeta sould do just fine.

Will do

**Comment by rduivenvoorde** [comment]
Mmm, I fail to find how to create this empty layer in python
https://github.com/qgis/QGIS/blob/master/src/core/qgsproviderregistry.h#L142 states that there are no bindings
And I cannot find another way to test/do this. Any pointers somebody?

**Comment by troopa81** [comment]
> I fail to find how to create this empty layer in python
https://github.com/qgis/QGIS/blob/master/src/core/qgsproviderregistry.h#L142 states that there are no bindings
And I cannot find another way to test/do this. Any pointers somebody?

*createEmptyLayer* is called from the *QgsVectorLayerExporter* constructor, so I think it's one way to do this. Another one could be to just retrieve the *QgsProviderMetadata* thanks to the method *providerMetadata* on the registry and then called *createEmptyLayer*. 

First way seems to be the more immediate

**Comment by rduivenvoorde** [comment]
Sorry, messed up this one, thought to rebase... 
I have created the test.
Will create a new one.

**Comment by rduivenvoorde** [comment]
Closing this one. The clean PR is https://github.com/qgis/QGIS/pull/40107

**Pull request closed without merging**
