### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by Alexis-B**
## Description
Fix a typo in a docstring

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by Alexis-B** [comment]
@m-kuhn Thanks you're right, I saw the sip file but considered it was generated as it was in the `build` folder. I just forgot it could come from a *.in file

**Comment by m-kuhn** [comment]
Normally, the prepare-commit script will regenerate this file automatically if you set it up properly. (see link at the bottom of your first message)

**Comment by Alexis-B** [comment]
Hum... that's weird: I ran the `prepare-commit.sh` script, after commit (I admit) but before pushing, and git told me nothing was changed. But I'll automate this, promised.

**Comment by m-kuhn** [comment]
The scripts only runs for files that are uncommitted (there is also `scripts/astyle_all.sh` and `scripts/sipify_all.sh` but they are very slow compared to just the modified files)
It's best to setup the pre commit hook as described then you can almost forget about it.

**Comment by Alexis-B** [comment]
Got it

**Pull request merged**
