### PR TITLE
[needs-qa] Change /usr/bin/XX or /binXX to /usr/bin/env XX

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description
Since /usr/bin/perl, /usr/bin/python or /bin/bash are not "portable" I suggest to replace it to /usr/bin/env XX.
This requires a thorough check.

## Checklist
- [X] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [X] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [X] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
That's the kind of pull request which normally noone wants to take responsibility for because everything works right now and it could potentially break some scripts.
So it would be great if you could bring forward some good real world use cases as arguments that justify this move.

**Comment by lbartoletti** [comment]
Hello,

I do not obviously want to break everything, that's why I propose a thorough review. My message is indeed lacking explanations.

Why, I propose it?
I try to be able to compile (and contribute) from FreeBSD. I always sent my commits from a debian VM, but I noticed problems by trying a commit from FreeBSD. On *BSD (and maybe others), bash is not the default shell and is not in /bin but in /usr/local/bin just like perl and python. We have already made the modifications to compile on BSD, this proposal continues in this way with the hope to be able to contribute directly from BSD. Here is my real world use case.
Besides, there are already many scripts, using the portable shebang "/usr/bin/env".

For the flags after the shebang (unify_includes.pl and doxygen_space.pl), I noticed that Linux ( debian ) does not know how to interpret them that's why I removed them and include in the astyle.sh script.

If you agree in the initiative, there will be other modifications to be brought but I have to continue my tests, for example:
BSD can also use GNU tools for sed and split because the used options are not compatible with the BSD tools, except for egrep...

Regards.

**Comment by m-kuhn** [comment]
I see, sounds good to me, I'd be in for giving it a try. Would you also want to add it to the spellchecker to make it futureproof?

**Comment by lbartoletti** [comment]
Thanks. Yes, I will propose a complete commit to try soon.

**Comment by lbartoletti** [comment]
For python, I noticed (and read for other systems) that " /usr/bin/env python " can cause problems because python must be an alias for python2 or python3 or does not exist (my case for one of my installations...).
Also, the most portable is to add directly the version of python aka "/usr/bin/env python2" or "/usr/bin/env python3".

**Comment by lbartoletti** [comment]
Also, we could adapt the Shebangfix ([manual](https://www.freebsd.org/doc/en/books/porters-handbook/uses-shebangfix.html) [script](https://github.com/freebsd/freebsd-ports/blob/master/Mk/Uses/shebangfix.mk)) from FreeBSD in the scripts?
It will apply the "most compatible" practice in new scripts.

**Pull request closed without merging**
