### PR TITLE
[Fix] modeler skip defaults

### LINKED ISSUE #40907: TypeError: createProcessingParameters() got an unexpected keyword argument 'include_default'
See also:
https://github.com/qgis/QGIS/issues/40900

When using the 'Densify' algorithms (like by count or by interval) **in a model**, the following Python error shows up:

```
An error has occurred while executing Python code: 

TypeError: createProcessingParameters() got an unexpected keyword argument 'include_default' 
Traceback (most recent call last):
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/plugins/processing/modeler/ModelerDialog.py", line 146, in runModel
    self.model().setDesignerParameterValues(dlg.createProcessingParameters(include_default=False))
TypeError: createProcessingParameters() got an unexpected keyword argument 'include_default'


Python version: 3.9.1 (default, Dec  8 2020, 07:51:42) [GCC 10.2.0] 
QGIS version: 3.17.0-Master Master, 70aea49fc4 
```

Screenshot-20210108105741-1128x343

To Reproduce:

Create a fresh model, add the algorithm with a valid layer as input. Run the algorithm (still all fine), and then when you close the model run dialog this is shown.

With me only in Master, NOT in 3.16

QGIS version | 3.17.0-Master | QGIS code revision | 70aea49fc4
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.0 | Running against GDAL/OGR | 3.2.0
Compiled against GEOS | 3.9.0-CAPI-1.16.2 | Running against GEOS | 3.9.0-CAPI-1.16.2
Compiled against SQLite | 3.34.0 | Running against SQLite | 3.34.0
PostgreSQL Client Version | 13.1 (Debian 13.1-1+b1) | SpatiaLite Version | 5.0.0
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.6
Compiled against PROJ | 7.2.0 | Running against PROJ | Rel. 7.2.0, November 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid | This copy of QGIS writes debugging output.
Active python plugins | nominatim_locator_filter; pdokservicesplugin; b4udignl2; processing

### PR DESCRIPTION
**Pull request by roya0045**
## Description

Catch kwargs and does nothing with them if in the algorithm dialog and not in the parametr dialog.

Fixes #40907 

@rduivenvoorde can you do the change in AlgorithmDialog.py and confirm if all works fine?

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
> @rduivenvoorde can you do the change in AlgorithmDialog.py and confirm if all works fine?

Yep (only added that change), seems to not show the stacktrace anymore... 
(did not test all your other ( upcoming ;-) ) changes...

**Comment by roya0045** [comment]
@rduivenvoorde Yeah, I think I'll go for a isinstance check instead on the dialog, I just reused my previous branch but Nyall did some tweaks, I'll rebase and only add the change and test it localy too. Shouldn't take too now long all goes well.

**Comment by roya0045** [comment]
Ok isinstance does nothing as dlg is always an algorithm dialog at this point of the code, going for kwargs may be safer since that function only seems to be in two places. Though that is strange is that I can't get the crash on 3.16 with my modified modeler files... I'll change it again to kwargs for safety.

**Comment by roya0045** [comment]
@nyalldawson This is the safest and most reliable that I could come up with. I hope this is fine with you.

**Comment by roya0045** [comment]
@nyalldawson I'm not sure how important the issue but if my work rendered processing alg unusable I hope that you may find a few moments to review or merge this fix.

**Comment by nyalldawson** [comment]
This approach counteracts the original reason for the change -- skipping any default-set values :D 

Alternative PR at https://github.com/qgis/QGIS/pull/40950

**Comment by roya0045** [comment]
@nyalldawson I did a local test and it behaved fined, but maybe I didn't have all the changes on master.

**Pull request closed without merging**
