### PR TITLE
Fix interpolated line renderer exact inverted

### LINKED ISSUE #46371: start width > end width is ignored when using the "exact" color interpolation method
### What is the bug or the crash?

When applying the interpolated line symbol, with both varying width and varying color, if the start point's width value is greater than the end point's, the output with exact color interpolation method does not take it into account; the end point is always assigned the max width instead.

### Steps to reproduce the issue

In the screen cast, I'm trying to get big blue circle on the starting point (the one at the bottom). As you can see, contrarily to the other color methods (where the start point gets bigger size), the rendering with exact method does not change if I switch start and end values (the big circles are always near the end point)
interpolatedExact
 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.0-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.3 LTS
  |   |   |  
Active Python plugins
trackable_project_files | v1.2.2
MapsPrinter | 0.6
MemoryLayerSaver | 4.0.4
db_manager | 0.1.20
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #46371

### CODE REVIEW

**Comment by elpaso** [comment]
@DelazJ I'd appreciate if you could test this PR (and https://github.com/qgis/QGIS/pull/47174 too)

**Comment by DelazJ** [comment]
Ok @elpaso, but probably not before next week...

**Comment by elpaso** [comment]
@DelazJ Thank you for testing! I verified that the last issue you mention is not related with this PR (it was already there in before this PR), how do you feel about proceeding with this PR and file a separate bug for the last issue?

**Comment by DelazJ** [comment]
@elpaso Thanks for checking. Done in #47342

**Pull request merged**
