### PR TITLE
Processing tests

### PR DESCRIPTION
**Pull request by alexbruy**
Some housekeeping in GDAL/OGR provider + new test for native and GDAL algorithms

### CODE REVIEW

**Comment by alexbruy** [comment]
Hmm, locally I get only CRS-related failures for Processing GDAL test

**Comment by nyalldawson** [comment]
Try now that #3381 has been merged

**Comment by alexbruy** [comment]
Tests passed locally now, but still failing on Travis

**Comment by alexbruy** [comment]
@m-kuhn, @nyalldawson any ideas why I still have failures related to CRS? All Processing tests passed on my computer.

**Comment by m-kuhn** [comment]
@alexbruy can you remove the xsd files?
They should probably go to a .gitignore file.

**Comment by alexbruy** [comment]
Seems removing xsd files does not help

**Pull request closed without merging**
