### PR TITLE
Typo fix and list ordering in Processing Algs help

### PR DESCRIPTION
**Pull request by DelazJ**
Some typo fixes and reorder list of algorithms

### CODE REVIEW

**Comment by alexbruy** [comment]
There is no need to put algorithms in the alphabetic order

**Comment by Gustry** [comment]
It's easier to find them when it's ordering. (to notice which one are missing etc ...)

**Comment by DelazJ** [comment]
Indeed, an ordered list is really helpful when you need to find an algorithm description (especially to fill user manual in my case); Also, given the small number of algs I had to move, it looks like the list was already built on an ordering logic.

**Comment by DelazJ** [comment]
@alexbruy may I gently ping you? Travis fail seems to not have to do with the PR.
Thanks

**Pull request merged**
