### PR TITLE
Switch all signals in plugins to new-style

### PR DESCRIPTION
**Pull request by m-kuhn**
It's better style anyway and good to merge early in the dev cycle.

@jef-n , looks good to me (it's produced by your amazing unmodified script). Merge?

```
./scripts/2to3 -f signals -w python/plugins
```

### CODE REVIEW

**Comment by sbrunner** [comment]
Nice :-)

**Comment by jef-n** [comment]
does db_manager still work?   I had problems.  IIRC importVector is both a signal and a slot.

See #2823 more - but db_manager is still an open issue there too.  I guess it needs pyqtSignal/pyqtSlot.  Also not the special use of SIGNAL in GdalTools and fTools - that's probably not an issue as both are going to be replaced with processing (BTW filling the Vector menu with processing tools had to be reworked too - I was getting QObject instead of QMenu from children() when addMenu was used with QMenu instead of strings; ie. QMenu created from python instead of C++).

But a lot works there if you run 2to3 on the build directory in a Qt5 build...

**Comment by m-kuhn** [comment]
I haven't tested anything, I just had a quick look at the code.

Do the issues you listed look to you like something that can be sorted out with 2to3 or is it something we will have to fix manually anyway? In the latter case I'd just merge this now and then deal with anything that surfaces.

For the other fixer (pyqt) I'm still thinking about putting the PyQt module below qgis (`from qgis.PyQt import xxx`) which seems to be the cleaner approach.

**Comment by jef-n** [comment]
Yes, I think manual work.   BTW that's what I try to do on #2823 - do the manual changes on the tree so that Qt4 keeps working and Qt5 works after running 2to3.

**Comment by m-kuhn** [comment]
I've noticed that you are working on #2823, good stuff.

My feeling is that the signals are easier to do than the pyqt, and I think that in #2823 both changes are bundled. I'd propose to merge signals first and deal with any issues that surface and then tackle the PyQt one in a second step, once signal issues are ironed out.

**Comment by mbernasocchi** [comment]
Just for the sake of documenting things, when running qgis 2to3 on a plugin I encountered a tricky situation regarding signals.
see: http://www.opengis.ch/2016/09/11/updating-pyqt-signals-that-use-lambda-in-qgis-with-2to3/

**Comment by jef-n** [comment]
Sure, it doesn't handle everything - there was tricky stuff in GdalTools and fTools too.

**Pull request closed without merging**
