### PR TITLE
[FEATURE] Layer tree indicators for memory layers

### PR DESCRIPTION
**Pull request by nyalldawson**
Shows a memory layer icon in the layer tree for all memory layers, with a tooltip warning that the contents of the layer will be lost when closing the project.

Should help avoid data loss by users who don't realise that certain layers are temporary only.

(No screenshots until @nirvn gives me a nice icon ;) )

### CODE REVIEW

**Comment by nyalldawson** [comment]
Now with a nice icon thanks to @nirvn:

image

**Comment by Gustry** [comment]
Thanks. Related to https://issues.qgis.org/issues/19038

**Comment by nyalldawson** [comment]
Now activates the "make permanent" action when clicking on the indicator!

**Comment by NathanW2** [comment]
Heck yeah!

**Review by nirvn — APPROVED** [review]
Just tried this earlier today, fantastic UX improvement.

1+ to merge.

**Comment by nyalldawson** [comment]
Thanks for the review @nirvn!

**Comment by AlisterH** [comment]
Hi guys,
Maybe it isn't the done thing commenting here long after the merge, but I'm wondering - have you thought about whether the temporary files created by default by processing algorithms should be treated more like memory layers?

These nifty new features for memory layers are nice, but they seem inconsistent  when a memory layer is alongside a processing-created temporary file - those still look like any other (permanent) layer, even though they aren't really any more permanent than a memory layer.

> Should help avoid data loss by users who don't realise that certain layers are temporary only.

But doesn't the inconsistency actually _encourage_ data loss with temporary files from processing?!

**Comment by AlisterH** [comment]
Sorry, I thought I'd better also point out that people may _unintentionally_ create temporary output files when using processing tools.  

e.g. some of those dialogs have a lot of complex options - it is easy enough to fill most of them in, then go away to check on an option or something, then come back and just run it without realising that you haven't specified an output file.

**Comment by AlisterH** [comment]
> Thanks. Related to https://issues.qgis.org/issues/19038

Note this comment there, which you can say supports what I'm saying:

> It's exactly the same behavior with QGIS Processing creating temporary layers.

**Pull request merged**
