### PR TITLE
addVectorLayerPrivate(): fix loading of WFS layers

### LINKED ISSUE #39847: Adding WFS layers broken in master
In 3.16 I could add one of the layers (pick 'provincies' = smallest) from the following service via the WFS dialog, using the following service url:
```
https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wfs
```

In master this fails.

Trying the same via iface.addRasterLayer idem dito:
The following works in 3.16 and fails in master using the Python console:
```
iface.addVectorLayer(
"https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wfs?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&TYPENAME=bestuurlijkegrenzen:provincies&SRSNAME=EPSG:28992",
"wfs example",
"WFS")
```

### PR DESCRIPTION
**Pull request by rouault**
Fixes #39847. master only (related to 1132494fcb679e814857d5cf7fa4f1712b52f5e1)

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by rduivenvoorde** [comment]
@rouault @nyalldawson I've been looking into that one. But should the code in: https://github.com/qgis/QGIS/issues/39847#issuecomment-723158078 == implementing the encodeUri/decodeUri for the WfsProvider not work then?

**Comment by rduivenvoorde** [comment]
AND if https://github.com/qgis/QGIS/commit/1132494fcb679e814857d5cf7fa4f1712b52f5e1 causes so much problems, let's forget about this inbuild-uri-schema?

**Comment by nyalldawson** [comment]
@rduivenvoorde I think Even's fix is a good band aid here -- after all, we don't need to handle inbuilt URIs for any provider which doesn't work with local paths.

Ultimately we DO need all providers to fully support encode/decodeUri though, so we shouldn't abandon efforts to add this support to more providera!

**Comment by rduivenvoorde** [comment]
@nyalldawson what is the reasoning about going through the encode/decodeUri (instead through datasourceuri constructor)?
I see many ways to create a datasourceuri (via it's own constructor, via the provider-metadata decodeuri etc).

Is there some preferred way? Or is one way deprecated? As an below average coder I often fail to grasp idea's/systems/overview about certain code constructs/architectures, and a general overview would be helpful to me.

I'm currently trying to fix Oracle provider too. Which (besides other small things) suffers from this (I think)
The issue there is that there seem to be many different ways to load a layer, with (apparently, because they start working one by one...) different code paths:
- via the dialog (was working already)
- via the browser (was broken, now fixed in my branch)
- via the databasemanager (till broken)
I have troubles grasping the way QGIS loads data. Is there some docs/writings about that?

(maybe better create a PR of my work and discuss there?)

Sorry for being so 'asky'

**Comment by nyalldawson** [comment]
@rduivenvoorde 
> what is the reasoning about going through the encode/decodeUri (instead through datasourceuri constructor)?

Great question! In an idea world we wouldn't have this duplication. But as a bit of background:

- QgsDataSourceUri has been around for decades. But it has a lot of problems: it is very db/online focused in design and is a very forced fit for disk based sources, and the behavior for the different properties of QgsDataSourceUri vary greatly between different providers. As a result it's a very confusing class to work with, and a steady source of very subtle bugs and regressions.
- As a result of these ongoing problems, the encode/decodeUri methods were introduced as a way of stepping around the limitations and confusion of the QgsDataSourceUri API. Specifically they were originally introduced as a stable way of determining a file path for a layer which works across all the providers which work with disk based layers. But the streamlined handling it introduced has proved to be so much nicer to work with vs QgsDataSourceUri that we've seen it creep into other parts of QGIS too.

Perhaps for QGIS 4.0 we'll see QgsDataSourceUri deprecated and removed. But that's a long way away, and is honestly more API breakage then I'd like to see introduced in 4.0 (I'd rather 4.0 was more of a Qt 6 style "gentle" break). 

The short answer is that implementing encode/decodeUri SHOULD be done for all providers.

**Comment by rduivenvoorde** [comment]
Thanks for  your long anwer. That what I thought more or less. What about putting text like this in the header files or so (as an alternative for some kind of overview documentation)?
About QGIS 4.0: let's clean up :-). As codebase grows and grows, this kind of duplications makes it different for newcomers (or those with no former knowledge) to grasp the code architecture.

**Pull request merged**
