### PR TITLE
Add st_translate expression function

### PR DESCRIPTION
**Pull request by m-kuhn**
I think it's fine to merge.

Just wanted to get a feedback on the `st_` prefix.

There was a name collision with an expression I used for internationalization in one of my plugins...

### CODE REVIEW

**Comment by nyalldawson** [comment]
@m-kuhn I'd prefer just "translate", without the prefix. The format I've been following was to take PostGIS' function names, drop the st_ prefix, and seperate words with '_'. There's a couple of reasons for this:

- it's non-obvious to our (non-PostGIS) users. "make_point" is easier to understand then "st_makepoint". 
- 'st_' is a historic relic even for PostGIS!
- sometimes our behaviour doesn't exactly match PostGIS'. I think having a slightly different function name helps make it more obvious that the functions aren't always an exact duplicate of the same function from PostGIS

**Comment by m-kuhn** [comment]
@nyalldawson ok, that's what I wanted to hear :)
Good to merge?

**Comment by nyalldawson** [comment]
@m-kuhn yep! Little thing, but it might be worth mentioning in the help that x/y are in the same units as the  geometry's CRS. Grab the exact wording from buffer.

**Comment by m-kuhn** [comment]
Thanks, will do and merge

**Comment by m-kuhn** [comment]
Merged in 4b3083d9

**Pull request closed without merging**
