### PR TITLE
[processing] Fix incorrect GDAL raster calc sources for layers when the extent handling option is set

### PR DESCRIPTION
**Pull request by nyalldawson**
input_a source was always being overwritten by the last present value of input_b, input_c, etc

### CODE REVIEW

**Review by nirvn — APPROVED** [review]

**Comment by nicogodet** [comment]
@nyalldawson As I had this extent option, did you face an issue while using it that I would have missed ?

I agree on your changes that make the code easier to read.

**Comment by nicogodet** [comment]
extent option was added after 3.28 release

**Comment by nyalldawson** [comment]
@nicogodet 

> As I had this extent option, did you face an issue while using it that I would have missed ?

Yes -- when the extent setting was set, then the "layer" variable was always over written with the last layer set. Then later there was an assumption that "layer" referred to "input a", so the resultant command had the incorrect path for input a.

**Comment by nicogodet** [comment]
Oh yeah
The culprit line 255
https://github.com/qgis/QGIS/blob/e86dc5fab96a46b7ba16e01dde6d6ff522d87cb1/python/plugins/processing/algs/gdal/gdalcalc.py#L251-L260

My bad...

**Pull request merged**
