### PR TITLE
cpt-city version 2.24

### PR DESCRIPTION
**Pull request by JamesShaeffer**
## Description
Updating the cpt-city-qgis-min gradients with the latest version from http://soliton.vm.bytemark.co.uk/pub/cpt-city/

### CODE REVIEW

**Comment by nyalldawson** [comment]
@JamesShaeffer 

I **think** the files in https://github.com/JamesShaeffer/QGIS/tree/0d77de2db70fe0ce65fea16546f04be70e09cb13/resources/cpt-city-qgis-min/selections may need to be updated too. Do the new ramps show without this?

**Comment by JamesShaeffer** [comment]
Thought this was going to be a super quick one. Thanks for the catch. I'll work on updating those files.

**Comment by nyalldawson** [comment]
Thanks @JamesShaeffer !

The other important bit would be to do a scan over the COPYING.xml files and make sure we aren't including any we shouldn't be.

**Comment by JamesShaeffer** [comment]
@nyalldawson 

I've update the README-qgis file. Let me know if there is anything else.

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
