### PR TITLE
[qt6] ifdef hack which no longer works

### PR DESCRIPTION
**Pull request by m-kuhn**
No solution really, just getting the compiler to work

CC @nyalldawson

### CODE REVIEW

**Comment by nyalldawson** [comment]
This is going to break a lot of things 😱

**Comment by m-kuhn** [comment]
Looking at the discussion in [QTBUG-66185](https://bugreports.qt.io/browse/QTBUG-66185?focusedCommentId=389567&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel), it screams for a bigger refactoring. Or do you see a shortcut?

**Comment by nyalldawson** [comment]
I'll have to open a thread on the qt list for this. Please don't merge in the meantime.

**Comment by m-kuhn** [comment]
whatever helps to sort this out !

**Comment by nyalldawson** [comment]
Superseded by https://github.com/qgis/QGIS/pull/42563

**Pull request closed without merging**
