### PR TITLE
Make "Ctrl+Shift+A" shortcut to trigger "Deselect current layer" instead of  "Deselect all layers"

### PR DESCRIPTION
**Pull request by suricactus**
As I said in https://github.com/qgis/QGIS/pull/35085 , the "Ctrl+Shift+A" shortcut should be exactly the opposite of "Ctrl+A" to match user expectations.

### CODE REVIEW

**Comment by uclaros** [comment]
Shouldn't there still be a default shortcut for deselect from all layers? ctrl+alt+shift+A maybe?

**Comment by suricactus** [comment]
Users can always change their shortcuts. It is important to have sensible defaults, especially for newcomers.

**Comment by nyalldawson** [comment]
> Shouldn't there still be a default shortcut for deselect from all layers? ctrl+alt+shift+A maybe?

+1 to this -- I think its good to still offer an out-of-the-box standard shortcut for "deselect EVERYTHING"

**Comment by suricactus** [comment]
I've added a "Deselect All" shortcut, but `alt+shift+A`. Under Qt I have observed taht all the "ctrl+shift+alt+<Key>" does not work properly, or at least under Linux. I've just tried that and the shortcut never gets fired as "ctrl+shift+A" seems to steal it. 

So no "ctrl+shift+alt+A" even though Emacs guys would love this :)

**Comment by uclaros** [comment]
Alt+shift is a common shortcut to change keyboard input language causing most combinations of alt+shift+... to not be captured...

**Comment by suricactus** [comment]
Yes, I do suffer from the "Alt+Shift" fever too. Any other idea for combination is appreciated.

**Comment by uclaros** [comment]
How about ctrl+shift+A for deselect all from all layers, since some people may have got used to it and plain shift+A for deselect all from current?

**Comment by suricactus** [comment]
I disagree, `ctrl+<Key>` and `ctrl+shift+<Key>` should always do the opposite of each other. `ctrl+A` selects all features from the current layer, therefore `ctrl+shift+a` should not touch other layers. I have seen a few new users who get frustrated by this behavior. 
I admit it is a "breaking" change, but the new shortcut is safer that the previous one.
I just checked there are not "Alt+Shift+<Key>" shortcuts, so my idea is not an option.
What about "Ctrl+Alt+A", it seems free?

**Comment by nyalldawson** [comment]
Ctrl+Alt+A works for me!

**Comment by suricactus** [comment]
Can someone try to set custom shortcut with "Ctrl+Alt+A" before merging this and confirm it works. My KDE is stealing the shortcut and I cannot find where it goes :(

**Comment by suricactus** [comment]
Okay, found it! On KDE I find it the most useless global shortcut:
`Settings -> (Global) Shortcuts -> Kwin -> Activate Window Demanding Attention`

It works on KDE, XFCE and Windows 10. Ready for merge @nyalldawson .

**Comment by nyalldawson** [comment]
Thanks @suricactus !

**Comment by DelazJ** [comment]
Under Layout dialog, Edit menu, there's a "Deselect All" entry that uses the new icon but still points to the `ctrl+shift+a`. For consistency, should it not also be updated? master 3ad17e526b

**Comment by borysiasty** [comment]
As mentioned in the PR above, Ctrl+Alt = AltGr in windows (for some weird reason there isn't even any way to disable it), so it steals diacritical characters from some languages :( 

The simplest solution would be to just drop Ctrl+Alt+A and leave the good old action (deselect from all layers) without any shortcut. I found myself always using the toolbar button for it anyway.

**Pull request merged**
