### PR TITLE
Only insert segment snap points in the layer they belong

### PR DESCRIPTION
**Pull request by strk**
Fixes http://hub.qgis.org/issues/13952

### CODE REVIEW

**Comment by strk** [comment]
@gioman @saberraz @haubourg could you please test this ?

**Comment by saberraz** [comment]
Testing...

**Comment by saberraz** [comment]
Hi @strk 
I can confirm that your fix in your branch works fine with the projects attached to the bug. I will do some further tests, but this looks fine.
Example of the problem:
https://youtu.be/-EJGWYaByXE

Resolved with this fix:
https://youtu.be/9uGFvA3pJDw

**Comment by gioman** [comment]
@saberraz have you tried the other way as described here? http://hub.qgis.org/issues/13952#note-11 (snapping "branch" to "arc").

**Comment by saberraz** [comment]
@gioman that too works fine.

**Comment by strk** [comment]
Thanks for testing, I'm working on an automated testcase. Please also confirm 2.14 needs the fix.

**Comment by strk** [comment]
PS: travis failure is unrelated, but complains about missing documentation for a new member:
```
Missing members:
 QgsCapabilitiesCache.removeCapabilitiesDocument
```

**Comment by strk** [comment]
Pushed as 647ab4e947edec24b8babe51e188d95270275ea4

**Pull request closed without merging**
