### PR TITLE
Do not recurse when splitting geometries

### PR DESCRIPTION
**Pull request by strk**
References GH-49726

### CODE REVIEW

**Comment by strk** [comment]
\cc @coefficient1900 @elpaso @gioman

This is probably breaking lots of stuff as I guess someone intentionally made the algorithm recursive. Will dig more next week in git history and CI results (hoping no false negatives come out)

**Comment by roya0045** [comment]
> \cc @coefficient1900 @elpaso @gioman
> 
> This is probably breaking lots of stuff as I guess someone intentionally made the algorithm recursive. Will dig more next week in git history and CI results (hoping no false negatives come out)

If it can help, the cpp part that you change has been the same since the original port of the python alg to c++, the last python version was https://github.com/qgis/QGIS/blob/c41dca937c3dfd76186cd0d8178428a12ecc4bca/python/plugins/processing/algs/qgis/SplitWithLines.py

**Comment by uclaros** [comment]
@strk fyi #50279

**Comment by strk** [comment]
Closing in favour of #50279 (contains the same code but had better luck with CI)]

**Pull request closed without merging**
