### PR TITLE
Remove code paths for proj >= 6.0 < 6.3.1

### PR DESCRIPTION
**Pull request by nyalldawson**
We don't support building with these versions, because of critical bug fixes in 6.3.1 and later

### CODE REVIEW

**Comment by nirvn** [comment]
Backport?

**Comment by nyalldawson** [comment]
> Backport?

Will do when I backport the fallback stuff (3.10.4)

**Comment by nirvn** [comment]
@nyalldawson , great.

**Comment by nyalldawson** [comment]
Blocked by https://github.com/OSGeo/PROJ/issues/1942

**Pull request merged**
