### PR TITLE
Project version check

### PR DESCRIPTION
**Pull request by NathanW2**
Adds a check and warning when saving a non dev project with a dev build of QGIS.  On save the a new project file will be created with -dev on the end of the file name so that links to the old project don't break.

image

Why?

As people can, and we encourage for testing, run dev builds I think it's important that we protect the user's files from possible data changes that might render then broken in a release version.  in theory, the user should just create their own copy of the project but I think a bit of hand holding her is ok for added safty.

### CODE REVIEW

**Comment by nirvn** [comment]
@NathanW2 , I like this, but we need to offer the users a way to save without appending a "-dev" at the end.

**Comment by NathanW2** [comment]
@nirvn do we really want that though? You are free to rename after or do a save as with a new name. Once it's stamped as master it won't do this step again.

**Comment by nirvn** [comment]
@NathanW2 , yeah, I think it'd be more respectful to ultimately let the users decide. You could simply add an additional button in the warning box, something alond the lines of:

[ cancel ] [ save as is ] [ save as "-dev" ] (ignore the dump label :) )

**Comment by m-kuhn** [comment]
> [ cancel ] [ save as is ] [ save as "-dev" ] (ignore the dump label :) )

We definitely need a `[ just do it and don't ask ever again ]` option for us devs and for power users doing things consciously.

**Comment by NathanW2** [comment]
@m-kuhn how about a hidden settings option for it?  I don't really like exposing that to the UI because it could be bad given it's fire and forgot.

**Comment by m-kuhn** [comment]
I know some power users who use master in production (on various machines) because of not yet released features. Forcing them to suffix their project files with -dev or going around and change hidden options does both not sound very appealing to me.
I very much care for these users because they are the ones that sponsor new features.

**Comment by NathanW2** [comment]
So what options would we like:

- Cancel
- Overwrite
- Save As.. (This could just cancel this and trigger the save as dialog).
- [ ] Remember option

**Comment by m-kuhn** [comment]
How about a non-obtrusive message bar info `You have saved a project with a development release of QGIS. We have created a backup copy for you at "~/.../[your-project-name]-stable.qgs" to avoid any risk of data corruption.` (You get extra karma points if you reformulate this message avoiding the term data corruption).

**Comment by nirvn** [comment]
@m-kuhn , @NathanW2 , I like the idea of copying a stable version while still using the main file to save the project.

**Comment by NathanW2** [comment]
Issue is that will break the links e.g recent, list in 2.18

**Comment by NathanW2** [comment]
If we put it on the dialog then overwrite will only be asked once and then
remembered for every session. So it's the same thing.

**Comment by m-kuhn** [comment]
> Issue is that will break the links e.g recent, list in 2.18

If that's an issue we'll have to deal with projects silently saved with (stable) 3.0 and overwrite projects in a 2.18 recent list with a higher priority first.

**Comment by NathanW2** [comment]
In theory that is also an issue which I was going to originally solve with
this logic however Nyall suggested it be only for dev releases because most
people would update to release versions but have a higher chance of running
release + dev vs release + release.

In the end I do think we need something here but I'm open to ideas to stop
the someone "updating" their project and then unable to open it in a
release version. e.g you really shouldn't be using prod projects in dev
releases but that is your choice I'm just trying to protect the people who
don't know the risks.

**Comment by nyalldawson** [comment]
> I know some power users who use master in production (on various machines) because of not yet released features. Forcing them to suffix their project files with -dev or going around and change hidden options does both not sound very appealing to me.
I very much care for these users because they are the ones that sponsor new features.

Just a follow up on this comment -- it's very much these users who we are trying to protect with this change. Given that there's no gaurantee of project stability mid-dev-release, a project saved in current master *may* be TOTALLY unreadable in the final 3.2 release.

So it's nice to protect users from this.

**Comment by NathanW2** [comment]
Pretty much this really.  I know people who that as well (myself included)
but it's not ideal and we might break something on them and they will have
no way to know until it's too late. Really people should keep backups and I
guess really if they are running a dev version even in prod they really
really should be using something to track project changes but do they?

**Comment by m-kuhn** [comment]
> Given that there's no gaurantee of project stability mid-dev-release, a project saved in current master may be TOTALLY unreadable in the final 3.2 release.

... and with tomorrows master. I don't think we are protecting them if they rollout master on every machine. Unless we save the commit sha in every project and use that to trigger the message.

What about this:

* save in 3.0 or dev will trigger a backup copy `[name].2.18.qgs`
* 2.18 gets another patch that detects on project opening if it's saved with a newer version and in this case checks for this backup and proposes to open the backup instead

**Comment by NathanW2** [comment]
@m-kuhn seems like a more complicated way then just having the dialog with a overwrite or save as on it.  With a remember for future for those that know the risks.

**Comment by m-kuhn** [comment]
Sorry, I'm not yet completely sold on the idea :stuck_out_tongue_winking_eye:
Let's analyse this quickly so we don't forget something

**Pros Dialog**

* The original file is untouched
* Easy to implement
* Forces a user to decide what to do

**Cons Dialog**

* It's a modal dialog
* Once clicked away for good, we are back to risky behavior
* Doesn't help for main version upgrades or conflicts upgrading from one dev version to another

**Pros Auto-Backup**

* No modal dialog
* Backups are made unconditionally
* Integrates with regular updates (using newer non-dev versions in parallel)

**Cons Auto-Backup**

* More logic to implement - more complicated
* Creates files without asking the user (i.e. might be seen as clutter)
* Doesn't help for upgrading from one dev version to another

**Comment by m-kuhn** [comment]
@NathanW2 any feedback on the analysis above?

**Comment by NathanW2** [comment]
Close for now while we think of other ideas.

**Comment by m-kuhn** [comment]
ok, I'll do that and wait for some awesome new ideas :)

**Pull request closed without merging**
