### PR TITLE
Hide CRS widget on geomtype none on startup

### PR DESCRIPTION
**Pull request by elpaso**
See: https://github.com/qgis/QGIS-Documentation/pull/7158#issuecomment-983626223

### CODE REVIEW

**Comment by elpaso** [comment]
CC @DelazJ

**Review by nyalldawson — APPROVED** [review]

**Comment by DelazJ** [comment]
Thanks @elpaso

**Comment by elpaso** [comment]
no problem, I have no idea how I broke it but it looks good now.

**Comment by DelazJ** [comment]
Weirdly, I failed to replicate the issue yesterday with 16f353d (which should have had the issue).

**Comment by elpaso** [comment]
It was just an initialization problem, after changing the geom type option it worked fine.

**Pull request merged**
