### PR TITLE
[processing] fix crash in graphical modeler due to QList index invalidation

### PR DESCRIPTION
**Pull request by luipir**
## Description

Fixed crash in Processing Graphical Modeler due to index invalidation

### CODE REVIEW

**Comment by luipir** [comment]
No issue associated to this bug

**Comment by nyalldawson** [comment]
Have you got more information about how this issue is triggered? The same filtering code is used in QgsModelChildAlgorithmGraphicItem::linkPointCount, so I'm concerned that there's a deeper underlying bug at play here...

**Comment by luipir** [comment]
> Have you got more information about how this issue is triggered? The same filtering code is used in QgsModelChildAlgorithmGraphicItem::linkPointCount, so I'm concerned that there's a deeper underlying bug at play here...

I've a complex model (with submodels) that trigger this... and I'm wating to have permission to attach the model to allow replication :( but client is really slow sorry. It is a model opening correctly in 3.10 but crashing opening after 3.12 and I had time to debug only now when client decided to move all to the next LTR.

If they continue to be late are you interested to have the model shared privately? I do not like to notify issue in this way sorry...

**Comment by nyalldawson** [comment]
> If they continue to be late, are you interested to have the model shared privately? I do not like to notify issue in this way sorry...

Yes please!

**Comment by luipir** [comment]
[epyris.zip](https://github.com/qgis/QGIS/files/5290737/epyris.zip)

**Comment by luipir** [comment]
teh procedure is:
1) install plugin via zip and activate it (hopefully shoud work ;) ). All models and scripts should be installed into processing
2) try to open graphical modeler: Models->EPyRIS Severity Map->Severity map and perimeter generation
3) would crash at least with this configuration:

QGIS version | 3.15.0-Master | QGIS code revision | **e7e08fd504 !!!!! <- should be master, in my case I user this PR patch to avoid crash !!!!!**
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-1.pgdg18.04+1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS | This copy of QGIS writes debugging output.
Active python plugins | plugin_reloader; IPyConsole; pluginbuilder3; copernicushub; firstaid; epyris; db_manager; processing; MetaSearch

**Comment by nyalldawson** [comment]
@luipir 

https://github.com/qgis/QGIS/pull/39200 should fix the underlying issue

**Comment by luipir** [comment]
> #39200 should fix the underlying issue

great tnx

**Pull request closed without merging**
