### PR TITLE
test server rendering debian buster bug

### PR DESCRIPTION
**Pull request by tudorbarascu**
Adds a server test that's only present on Debian Testing/Buster (the problem is at least since 4 months ago).
See https://issues.qgis.org/issues/18988 
I couldn't replicate under Ubuntu bionic but I replicated on different Debian Buster machines.

ping @pblottiere

### CODE REVIEW

**Comment by m-kuhn** [comment]
There is no assert or control image in there, what's this test supposed to catch?

Only a minor note: add a reference to the ticket in the commit message, that will help to know in the future what this tets was introduced for.

**Comment by tudorbarascu** [comment]
@m-kuhn Thanks for looking. I had lost the control image while doing rebase. Added the issue no. in the commit message.

**Comment by nyalldawson** [comment]
@tudorbarascu The test mask here breaks this test -- because both text options are totally white, it means the test can pass if no label is shown at all. 

You'd be better off doing the multiple-reference image approach here, so that the result has to match one of the two possible images. See e.g. https://github.com/qgis/QGIS/tree/master/tests/testdata/control_images/annotations/expected_html_feature

**Comment by tudorbarascu** [comment]
@nyalldawson Thanks for the info! Will redo it!

**Comment by tudorbarascu** [comment]
@pblottiere As I know there were some mail problems with the bug tracker and maybe you didn't received the updates, I can always replicate now when activating multi-threading.

**Comment by pblottiere** [comment]
Hi @tudorbarascu,

Sorry I was mainly AFK these last 2 weeks. I'm taking a look today.

**Review by rldhont — APPROVED** [review]

**Comment by pblottiere** [comment]
Hi @tudorbarascu,

I managed to reproduce your issue on Debian Testing/Buster with the parallel rendering activated.

And actually, the server is hanging in [`getFeatureSource`](https://github.com/qgis/QGIS/blob/master/src/core/expression/qgsexpressionutils.h#L354-L380) method defined in `qgsexpressionutils.h`.

The next call is hanging forever:

```
QMetaObject::invokeMethod( qApp, getFeatureSource, Qt::BlockingQueuedConnection );
```

@m-kuhn I think you introduced this not so long ago. What could possibly go wrong? In Desktop mode,   
do you know how do we "leave" the blocked state?

BTW, I removed the `invokeMethod` to call `getFeatureSource` directly (just to try), and everything is rendered correctly.

**Comment by pblottiere** [comment]
Hi @m-kuhn,

Gentle ping about my question above :).

**Comment by m-kuhn** [comment]
oops, sorry I missed that.

There are two possibilities:

 * If this is called from the main thread, the feature source is acquired immediately and the code continues, no blocking involved
 * If this is called from a background thread, it is blocked and an event is sent to the main thread with a request to invoke this method. As soon as the main thread has had the time to take execute this method, the background thread continues.

I am not familiar enough with threading on the server. I assume the main thread is blocked there while the rendering happens and no events are processed in an event loop? Would it be possible to launch an event loop there during this time to have this kind of synchronized jobs working?

**Comment by pblottiere** [comment]
@m-kuhn 

> If this is called from a background thread, it is blocked and an event is sent to the main thread with a request to invoke this method. As soon as the main thread has had the time to take execute this method, the background thread continues.

Nice, I was suspecting a deadlock, and I think you just confirmed my suspicion :).

> Would it be possible to launch an event loop there during this time to have this kind of synchronized jobs working?

Surely it should be enough.

Thanks for the explanation Matthias :+1:

**Comment by tudorbarascu** [comment]
The problem that this test cached is fixed.
However, it only happened when Server multi-threading is on (on Travis it's not).
I wrote that test so that the CI ensures it doesn't happen again but of course it won't work if multithreading is disabled. Is there a reason why the Server multi-threading on Travis is off?

**Comment by rldhont** [comment]
@pblottiere can we keep this test ? And merge it ?

**Comment by rldhont** [comment]
@pblottiere you're welcome!

**Pull request merged**
