### PR TITLE
Fix 17365

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes https://issues.qgis.org/issues/17365

This commit fixes a possible crash when the vector layer renderer attempts to render a multipolygon containing a polygon without an exterior ring.

The underlying cause of the creation of this invalid geometry is deeper and resides in recent gdal releases, but this PR hardens the renderer and makes it more robust for handling bad geometries.

Additionally, it also adds an extra check to discard features from the ogr provider when iterating with a request containing a filter rect and a feature with empty geometry is encountered.

@rouault https://issues.qgis.org/issues/17365 contains a dataset which has regressed in newer gdal releases and which triggers the crash in QGIS, as some of the features returned by OGR from that layer contain a multipolygon with an empty polygon child.

### CODE REVIEW

**Comment by rouault** [comment]
> contains a dataset which has regressed in newer gdal releases

I don't think so. GDAL 2.2 will now return POLYGON EMPTY geometries for polygons for which it returned previously an invalid polygon (less than 4 points). The issue must be linked to the automatic promotion of polygon to multipolygon that has been added in the OGR provider recently, that must create a MULTIPOLYGON with that POLYGON EMPTY as member. This is admittedly a weird beast, not completely sure if it is valid in OGC world, but GDAL and PostGIS can read and generate such beasts.

**Comment by nyalldawson** [comment]
>  This is admittedly a weird beast, not completely sure if it is valid in OGC world, but GDAL and PostGIS can read and generate such beasts.

Mm, tricky. Not sure the best way to handle this in QGIS world. I'm tempted to at least extend QgsGeometry::isEmpty() so that a multipart geometry consisting only of empty geometries is considered empty. 

I'm curious about gdal's handling of this case with OGR_L_SetSpatialFilterRect. Is it a design decision that OGR_L_SetSpatialFilterRect is ignored for features with null or empty geometries? Or a bug?

**Comment by rouault** [comment]
> Is it a design decision that OGR_L_SetSpatialFilterRect is ignored for features with null or empty geometries? Or a bug?

I'd say this is not really well defined. The behaviour may change among drivers. For OGR PostGIS, I'd suspect that null or empty geometries will not pass the test. For non-DB based OGR drivers, the code explictly considers a null geometry to match the spatial filter. I'm not sure of the rationale for this. Dates back to 13 years ago: https://trac.osgeo.org/gdal/changeset/7191

And regarding empty geometries, hum this is more annoying. In the generic code, the envelope computed is 0,0,0,0, so the result of the spatial filter depends on the value of the spatial filter geometry. Sounds like a bug. An empty geometry should be dealt as a null geometry at the very least

**Comment by nirvn** [comment]
@nyalldawson , this PR makes the crash go away, thanks.

**Comment by rouault** [comment]
Note: I've raised this issue about OGR spatial filtering for null and empty geometries in https://lists.osgeo.org/pipermail/gdal-dev/2017-November/047578.html

**Pull request merged**
