### PR TITLE
Port crssync to proj6, avoid use of gdal csv files

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR ports crssync and the QGIS internal CRS database to use proj 6. I.e. instead of maintaining our own separate CRS db, we now populate the internal working db using Proj 6's database. It means QGIS now takes advantage of this shared resource, instead of the baggage of trying to handle updates and new CRS definitions ourselves. New definitions and fixes will become available as soon as they are added to stable Proj releases.

This means that (on proj 6 based builds), we should push any bugs relating to crs definitions back to the proj project, and let proj decide on the validity of CRS specific workarounds and exceptions. Potentially this opens a number of regressions, as QGIS custom crs db was full of odd entries with no history or justification for their presence. If regressions are encountered, they should be discussed on the proj mailing list now.

Specifically, this PR replaces the use of gdal csv files* with the proj6 crs database in order to populate our srs.db. We CANNOT remove srs.db without MAJOR api breakage, so this is the best we can do until 4.0. (And we'll need to evaluate any potential performance impact of removing the internal QGIS db before completely stripping it away in 4.0 in any case). 

Sponsored by ICSM

\* (which are gone in gdal 2.5, so we're gonna have to try to backport parts of this for 3.4. Or... just rips the csv files out of gdal source archive and use them for 3.4. That's my suggestion.)

### CODE REVIEW

**Comment by PeterPetrik** [comment]
🎉 thanks, looking forward for this on master so nighty builds on mac are working again :)

**Comment by timlinux** [comment]
> thanks, looking forward for this on master so nighty builds on mac are working again :)

That makes two of us!

**Comment by PeterPetrik** [comment]
@nyalldawson it looks like that unit tests are passing, only code layout is wrong... Is there anything blocking to merge this one to master if we fix code layout?

**Comment by nyalldawson** [comment]
> @PeterPetrik  it looks like that unit tests are passing, only code layout is wrong... Is there anything blocking to merge this one to master if we fix code layout?

Travis runs on proj v4, so none of this is actually being tested by Travis. Just need a bit more patience as I iron out the remaining questions with the proj team...

**Comment by PeterPetrik** [comment]
Ok, understand, keep the good job going. Only problem for me is that I am unable to review new PRs since I am not able to build master with proj6.

just to clarify: If your branch works OK for all tests with proj4 dep (on travis), why it cannot be merged? It will definitely wont be worse than not-building master...?

also: for 3.4 LTR would it be even safe to release QGIS on mac with proj6 dependency? Or you think we should invest few days of work to use proj4 on homebrew and its dependencies?

**Comment by nyalldawson** [comment]
@peterpetrik I honestly don't know what we should do for 3.4. 

When gdal 2.5/3.0 is released I think we could pull the CSV projection database from gdal 2.4 and update the crssync to use those. But I think we'd also need to update other code paths to handle some projection related API breaks.

To worst part will be if proj 7 is released during the lifetime of 3.4. if that happens, I think we'll just need to end 3.4 lyr support early. These changes are just way to intrusive to even consider backporting as a viable option.

**Comment by PeterPetrik** [comment]
Nyall, I am frankly not an expert in proj library and all the consequences for packaging, but I need to make sure that the QGIS Mac builds will be usable for users. The plan is that we will move to homebrew-based releases as official package once we sort out certificate for OSGEO with @jef-n Right now we are based on this proj library: https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/osgeo-proj.rb#L23

So the question is:
A) It is NOT safe to use proj 6.x to release QGIS 3.4, 3.6, 3.8 (3.10) library and we should change the homebrew formulas to use older proj version (which one? 4.x or 5.x?). This is potentially few days of work, not sure...  @fjperini do you know how much work is involved in this? 
B) It will be safe to use proj 6.x + gdal 2.5/3.0 to release QGIS 3.4, 3.6, 3.8 (3.10) and we need to just wait a week/2 weeks/month to get all things fixed.

Thanks for clarification

**Comment by timlinux** [comment]
> @PeterPetrik I honestly don't know what we should do for 3.4.

My opinion: Leave QGIS 3.4 on Proj 4 - it is a big change and seems like something to be tested in interim releases and go into the next LTR. Is there any pressing reason why it has to go into the LTR? Or is it more pragmatic - not wanting / being able to have two proj versions in OSGEO4W / OSGEO4M?

**Comment by PeterPetrik** [comment]
> Is there any pressing reason why it has to go into the LTR

yes, because homebrew is now all on proj6. To go back to proj4, we need to rework/rebuild all libs that uses proj.

**Comment by nyalldawson** [comment]
To clarify : we are fine with leaving 3.4 using proj 4 API, even under proj v 6. (And that's the right decision).

The risk is when proj v7 is released, because that's when all the v4 API is being completely removed. Past history has shown that homebrew is quite trigger-happy with upgrades like this, so there's a big chance they'll upgrade and break 3.4 compatibility.

Thats why I hope we can drop 3.4 support before proj v7 is released.

There's also going to be complications when gdal 3 (previously 2.5) is released shortly. That breaks some API in use by 3.4, and will break the crs db building entirely. And 3.0 release is imminent... 😮

**Comment by nyalldawson** [comment]
Ok, I think this is ready for merging now. There's still some test failures on the proj6 builds, but those look to be issues in proj itself rather then in this work.

(e.g. https://lists.osgeo.org/pipermail/proj/2019-May/008564.html , https://lists.osgeo.org/pipermail/proj/2019-May/008563.html )

**Merging will at least get us functional builds on proj6 again, but I cannot stress how STRONGLY I recommend that no-one tries to use this for real analytical work until the fallout from proj 6 is settled.** I suspect we'll be squashing follow up issues for quite some time to come, and there's a very real risk of misleading and inaccurate results from QGIS until this is done.

**Pull request merged**
