### PR TITLE
Add alias support for expression functions

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR standardises the naming of all internal functions to the lowercase with underscore convention. Currently function names are a mix of standards, including lowercase with no underscore, camel case, and lowercase with underscore. This results in unpredictable expression writing, and gives the impression that expressions functions have been developed in a very ad-hoc, unplanned way.

By adding aliases support to functions this PR allows for expressions using the old names to continue working without any breakage.

### CODE REVIEW

**Comment by nyalldawson** [comment]
As a note, this work is part of a larger project of cleaning up and extending expression support, leading to context-based evaluation of expressions.

**Comment by NathanW2** [comment]
Ohhh fancy

**Comment by m-kuhn** [comment]
Nice, +1 for a coherent function style.

**Comment by nyalldawson** [comment]
manually pushed

**Pull request closed without merging**
