### PR TITLE
Change acceptable missing doxygen from count to list

### PR DESCRIPTION
**Pull request by sbrunner**

### CODE REVIEW

**Comment by nyalldawson** [comment]
Really nice - this should be a lot easier to use now!

Just wondering, did you use a script to generate the missing doc list python file? If so it'd be handy to include so we can periodically cull the missing doc list.

**Comment by sbrunner** [comment]
@nyalldawson Thanks, I just add the way I use to generate the list :-)

**Comment by m-kuhn** [comment]
Manually merged.

Thank you very much!

**Comment by sbrunner** [comment]
Thanks :-)

**Pull request closed without merging**
