### PR TITLE
nix: add nix packaging files

### PR DESCRIPTION
**Pull request by imincik**
## Description

Add Nix packaging files to enable unique Nix features for this project.

This PR will be explained in my [QGIS User Conference talk](https://talks.osgeo.org/qgis-uc2024/talk/ZXNPXT/).

### CODE REVIEW

**Comment by nyalldawson** [comment]
Do these files have to be in the root directory? It'd be cleaner if they were in a subdirectory

**Comment by imincik** [comment]
> Do these files have to be in the root directory? It'd be cleaner if they were in a subdirectory

It is a Nix convention to have them in root directory, but I agree that it might look cleaner to have them in subdirectory. I can move them if people are interested in merging this PR.

**Comment by autra** [comment]
I'd be in favor of reopening this : it's very handy for nix users, because it allows to build+install qgis from any commits that contains a flake.nix, without ever worrying about compatibilities with system libs.

We can already install old versions from the set of  versions known by nixpkgs (for instance, to use qgis 2.18, I'd use `nix-shell -p qgis -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/f06d8e0bf4822788f93ed994c4a9e88bda3606c3.tar.gz`), but discoverability is not great and this would go a step further by allowing this on every commit, even unreleased one. 

I think it'd be very useful for dogfooding and testing, at least.

**Comment by timlinux** [comment]
@imincik @nyalldawson Following from our in-person discussion, would you be ok for us to re-open this PR and move things forward?

**Comment by nyalldawson** [comment]
@timlinux yes, fine for me. I can't re-open as the remote branch is deleted.

**Comment by imincik** [comment]
This PR is now replaced by https://github.com/qgis/QGIS/pull/62531 .

**Pull request closed without merging**
