### PR TITLE
move access to OS native interface to core

### PR DESCRIPTION
**Pull request by 3nids**
This is a proposal to move the whole access to native OS interface to QGIS core instead of gui.
The first use case is to fix the font color in the layer tree depending on the OS theme (dark vs light).

First discussion with @nyalldawson led to split the native into two classes and attach one to core and one to gui.

I finally preferred to stick to a single class:
* sake of clarity: everything is in one place both API wise and file wise
* sake of simplicity: less code to maintain
* the gui/core distinction does not really make sense to me here: we access some methods of the base OS. If we build something with core only (without gui), we might still want to be able to show notifications on desktop. 

Other simplification, I created a static method in QgsNative which directly call the correct implementation (OS specific) and returns it.

### CODE REVIEW

**Comment by 3nids** [comment]
I'll finish replace the elements in the code if this gets an agreement

**Comment by nyalldawson** [comment]
As discussed previously, I'm a -1 one here, sorry. In my view too much of the current QgsNative class is specifically GUI dependant functionality. A quick survey of the class:

GUI specific:
- currentAppActivateIgnoringOtherApps (window-specific action)
- showDesktopNotification (won't work on most platforms without a main window)
- showUndefinedApplicationProgress (won't work anywhere without a main window)
- setApplicationProgress (won't work anywhere without a main window)
- hideApplicationProgress (won't work anywhere without a main window)
- setApplicationBadgeCount (won't work anywhere without a main window)

Borderline, but mostly GUI operations:
- openFileExplorerAndSelectFile
- showFileProperties
- openTerminalAtPath

Borderline, but strong argument to have accessible from core:
- hasDarkTheme

Fine to move to core:
- usbStorageNotification

**Comment by m-kuhn** [comment]
> Borderline, but strong argument to have accessible from core:
>
>    hasDarkTheme

Can we inverse the logic here and set a/some property/ies on the tree or move the representation part (view /  delegate) doing this to GUI?

**Comment by 3nids** [comment]
ok, will come up later with the option for layer tree

**Comment by m-kuhn** [comment]
Probably no longer required after https://github.com/qgis/QGIS/pull/8729#event-2040907940

**Comment by nyalldawson** [comment]
Can we close? Let's get to a new record of open PRs!

**Comment by m-kuhn** [comment]
Looks like the source issue is resolved and this PR is not a nobrainer. I'll close it but feel free to reopen if there are new insights.

**Pull request closed without merging**
