### PR TITLE
Processing grass7 v voronoi skeleton

### PR DESCRIPTION
**Pull request by gioman**
Add a GRASS7 tool to compute skeletons of areas, using v.voronoi

### CODE REVIEW

**Comment by gioman** [comment]
@volaya @alexbruy

**Comment by nyalldawson** [comment]
@gioman Do you get usable results with this? If I input anything more than a single polygon I get nonsense. I think it's this upstream issue: https://trac.osgeo.org/grass/ticket/2670

**Comment by gioman** [comment]
@nyalldawson I also seen strange results, but also got good ones especially after generalizing the inputs with v.generalize.

**Comment by nyalldawson** [comment]
@gioman hmmm... that didn't work for me. If i run the features one-by-one I get decent results, it just seems like the grass routine is buggy with more than one input feature

**Pull request merged**
