### PR TITLE
[FEATURE] Postgres provider PKI authentication (plus fixes #13841)

### LINKED ISSUE #13841: "Screen scaling" setting to control the screen size of things defined in points or mm
Author Name: **Alister Hood** (@AlisterH)
Original Redmine Issue: [3783](https://issues.qgis.org/issues/3783)

Redmine category:map_canvas

---
With the new labelling engine (I have not tested with the old):
If the label font size is set in points (instead of map units), then on a typical monitor the labels are displayed in the map canvas at approximately the same size as they are printed on paper.  If I remember correctly (I'll check tomorrow), the same is true for vector symbols if their size is set in mm instead of map units.

Changing the DPI setting in the operation system does not affect the size (at least in Windows - perhaps someone could test in another operating system).  Presumably this means that QGIS (or maybe an underlying library such as QT) is using some "typical" value for screen DPI.  This is likely to be 72dpi or 91dpi or something.

You might think it would be good for the size to change depending on the DPI setting in the operating system, so that if this was set correctly then the labels and symbols would be exactly the same size on paper as on the screen.  BUT in reality this would be bad, for the same reason that the current behaviour is bad: _screen dpi is normally much lower than any printer output, so small labels and symbols which are easily legible on paper are not legible on the screen_.  

I think ideally QGIS should have its own setting to control the screen rendering size of labels and symbols (if they are not defined in map units).  I'm not sure what the best name for the setting would be - maybe something like "Screen scaling factor".  The units should be in DPI, so that if someone _does_ want things to be exactly the same height on paper as on the screen, they can simply set it to the actual DPI of their monitor.

### PR DESCRIPTION
**Pull request by luipir**
NEW FEATURE:  Connect to Postgres using PKI authentication based on QgsAuthManager.

DB_MANAGER python patches (fixes #13841)
These patches include cherry-picked patches get by @SebDieBln with the author's consensus [1]:
@SebDieBln's patches enable basic authentication in the db_manager using QgsAuthManager.
At these has been added PKI auth to postgis (committed with [db_manager] tag in the commit)

Developed by
       Boundless Spatial, Inc. [2]

[1] https://github.com/qgis/QGIS/pull/2473.
[2] http://www.boundlessgeo.com

### CODE REVIEW

**Comment by SebDieBln** [comment]
@luipir 
You could add the phrase _(fixes #13841)_ to the description or title of this PR so when it gets merged, the corresponding issue on the HUB is closed automatically.

**Comment by dakcarto** [comment]
Btw, I have reviewed this work by @luipir and @SebDieBln, internally at Boundless, and I think this is ready to merge.

+1

**Comment by luipir** [comment]
@SebDieBln updated

**Comment by nyalldawson** [comment]
@dakcarto any reason you haven't merged yet?

**Comment by dakcarto** [comment]
@nyalldawson no reason (other than work). will do now

**Pull request merged**
