### PR TITLE
run include-what-you-use on src/core/layertree

### PR DESCRIPTION
**Pull request by 3nids**
I gave a dry-run at https://github.com/include-what-you-use/include-what-you-use
Here is the result applied to src/core/layertree only.

Let's if it builds.
Opinions?

Only changes related to QGIS files are applied for now.

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'm from the "include only what you need to get the build to work" camp :smile:

**Comment by 3nids** [comment]
The idea was more to optimize the include to gain a bit of build time.

**Comment by m-kuhn** [comment]
> I'm from the "include only what you need to get the build to work" camp smile

Ideally, that's what this should do I guess.

**Comment by pblottiere** [comment]
Nice! Thanks @3nids :)

**Comment by 3nids** [comment]
maybe for the next hackfest.

leaving some notes to produce qgs changes only:
```
cd build
cmake -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="/Users/denis/opt/include-what-you-use/build/include-what-you-use;-Xiwyu;--mapping_file=/Users/denis/opt/include-what-you-use/qt5_4.imp;..." ../QGIS
ninja > iwyu.out
python3 ../../include-what-you-use/fix_includes.py --nosafe_headers --only_re 'src.core' < iwyu.out
cd ../QGIS
git diff > ../diff.orig
# do not remove non-Qgs changes, do no add non-Qgs changes
gsed -r '/^\+#include </d; s/^\-(#include <)/ \1/; /^\+class Q[A-Z]/d; s/^\-(class Q[A-Z])/ \1/; /^\+template.*class Q[A-Z]/d' ../diff.orig > ../diff.out
git reset --hard HEAD
git apply --recount ../diff.out
git commit -m "run include-what-you-use on src/core" --no-verify
```

**Comment by 3nids** [comment]
ping @troopa81 
it seems you're working on this. I had the plan to have a look again during this HF.

**Comment by troopa81** [comment]
@3nids Thank you for the notes, I didn't see this commit. 

- Why don't you take non-Qgs changes? and why only on core?
- Does it really speed up compilation?

I have done quite the same thing than the one you describe if your notes, but I found some errors (forgotten forward_decl, or still too much includes from what I remember). And I was planning to debug iwyu to understand and maybe correct the errors.

I will be happy to read your progress in this subject.

**Comment by 3nids** [comment]
> Why don't you take non-Qgs changes? and why only on core?

to have less changes, I mainly created PR to have a nice visual front-end.
I wanted to start progressively, changes are huge otherwise.

> Does it really speed up compilation?

no idea ;) didn't test yet, I'm not even sure it actually compiled with the result here.

**Pull request closed without merging**
