### PR TITLE
Support for NaN in text edit widget

### PR DESCRIPTION
**Pull request by m-kuhn**
If one currently snaps to a geometry with undefined z coordinate (`NaN`), and uses a default expression for an attribute `z($geometry)`, the text will be `nan` and QGIS will try to save the attribute as text nan, which won't work on a numeric field.

This will work around the issue by mapping `nan` to `NULL` in the text edit widget.

There would be alternative approaches like mapping nan to NULL at the end of `QgsExpression::evaluate()`.

### CODE REVIEW

**Review by lbartoletti — APPROVED** [review]

**Comment by m-kuhn** [comment]
@elpaso I'm always hesitant to test hacks

**Comment by elpaso** [comment]
I didn't know it was a hack :) 

My reason for asking was that the NULL/None/NaN/std::min/max/isEmpty() etc, handling in these widgets is "fragile" at best (when it's not broken already, see relation ref), I'd really like to see tests here or you hack won't survive long.

**Comment by m-kuhn** [comment]
I'm really not too fond of doing a test like this. I'd actually even be happy to not have my hack live for long. I could very well imagine a future implementation where nan is preserved and not mapped to null. Let me see if I can come up with something ...

**Comment by m-kuhn** [comment]
Hmmm... And what's wrong with relation ref that's worth noting here?

**Comment by m-kuhn** [comment]
Other approaches seem to be poorly backed by real world use cases. Let's stick to this one for now.

**Comment by m-kuhn** [comment]
@elpaso your review would be welcome

**Review by elpaso — APPROVED** [review]

**Pull request merged**
