### PR TITLE
Don't use system notification for auth messages

### PR DESCRIPTION
**Pull request by nyalldawson**
This mechanism was designed for use only by task manager, where extra logic is in place to avoid showing notifications for short duration operations.  Instead always use the more appropriate message bar here.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@elpaso Are you ok with this change? I've never had the wallet unlock ever taken enough time to warrant the demand of a system wide notification (on either Windows or Fedora). Have you ever known situations where the wallet retrieval is slow? (If so, we should use a QgsProxyProgressTask here, which will automatically fire the system notification in select situations).

**Comment by nirvn** [comment]
Makes sense.

Big +1 to establishing a rule whereas we limit the use of system notifications to tasks.

**Comment by elpaso** [comment]
I wouldn't be "religious" about who can use the system notifications systems and who cannot.

The rationale to use system notifications here was that retrieving a master password from the operating system storage is an operation that involves components that are outside the QGIS application and (at least on Linux) the system tray is the place where password management functions are accessible.

Additionally, the message bar is used for so many messages and we thought that password management operations would deserve much more attention, so this was not about the duration of the password retrieval operation (which is typically fast), but more drawing more more user attention to it.

So, unless there is a technical reason to limit the usage of notifications to tasks, I'm -1 here.

**Comment by nyalldawson** [comment]
> I wouldn't be "religious" about who can use the system notifications systems and who cannot.

Actually my main reason here is I'm worried about abuse of the system, which results in users getting annoyed with it or ignoring it. That's why there's careful logic in place with the task notification hookup to avoid showing it in certain circumstances. It's also the reason it was never exposed to public api - the danger of a plugin abusing it was just too high.

> The rationale to use system notifications here was that retrieving a master password from the operating system storage is an operation that involves components that are outside the QGIS application and (at least on Linux).

Wouldn't the same hold true for lots of things? Even just loading files involves components outside QGIS.

>  The message bar is used for so many messages and we thought that password management operations would deserve much more attention, so this was not about the duration of the password retrieval operation (which is typically fast), but it was about drawing more more user attention to it.

I guess my concern is that we don't even really need this message in most cases. If something went wrong, then yes, a user facing warning is valid. But all the time (for me at least!) this feature just works as expected (yay!) and the feedback (via notification or message bar) is just noise. It's a bit like saying "things worked as expected!". I only really want to be notified when things go wrong (hopefully never!), or when something has taken so long that I've flicked away from QGIS to work on some other task and I need to know that it's time to switch back.

**Comment by elpaso** [comment]
@nyalldawson I generally agree with your considerations, but when security is involved, a bit more of noise is IMHO welcome.

> Wouldn't the same hold true for lots of things? Even just loading files involves components outside QGIS.

The OS password manager is kind of atypical: it is not a low level I/O, it is more like another application integrated in the OS.
As I said, security is involved here and we thought it deserved the usage of system notifications.

We already discussed this topic at that time, and here we go again :(

But I will not fight further, if the original funders of this work think is an important feature perhaps they will.

**Comment by NathanW2** [comment]
I agree. Leave this one for the system notifications. IMO this one has a
valid use case for using it so the user knows what is happening.

**Pull request closed without merging**
