### PR TITLE
Add model for connections from a provider

### PR DESCRIPTION
**Pull request by nyalldawson**
Allows for easy creation of comboboxes/lists which list the registered connections for a specified data provider (the provider must implement the connections API, so postgres/gpkg/spatialite for now)

### CODE REVIEW

**Comment by nyalldawson** [comment]
Also includes a schema model now!

**Comment by nyalldawson** [comment]
And lastly with a table model too...

**Comment by nyalldawson** [comment]
A totally finally with a set of chainable widgets exposing this functionality.

As seen in action here:
Peek 2020-03-08 11-36

**Comment by nirvn** [comment]
That'll be useful for our create new gpkg/spatialite layer dialogs.

**Pull request merged**
