### PR TITLE
Add a iface method to directly set a specific GPS connection to connect to in the GPS Information panel

### PR DESCRIPTION
**Pull request by nyalldawson**
Allows for plugins to create subclasses of QgsGpsConnection and then hook these into the existing GPS panel widget

### CODE REVIEW

**Comment by m-kuhn** [comment]
Adding mock location?

**Comment by nyalldawson** [comment]
Yes - I have a need to "replay" a prerecorded log of nmea commands!

**Comment by m-kuhn** [comment]
sounds to me like this should be an api in core (not gui), but I don't know the whole gps code

**Comment by nyalldawson** [comment]
There's already a registry where general connections can be handled in core - what's missing is a way to set a specific connection to be used by the GPS panel (which lives in app). That's what this does -- allows you to programmatically set the connection vs having to make a user pick it.

**Comment by nyalldawson** [comment]
In general though I agree - there's a ton of useful stuff tied up specifically to the GPS panel widget which would be great to extract and move to reusable methods!

**Review by m-kuhn — APPROVED** [review]
Looks good to me

**Pull request merged**
