### PR TITLE
CI: stop accepting gitstatus checks failures from non-provider tests

### PR DESCRIPTION
**Pull request by strk**
See also GH-48904
Continuation of GH-52510 as that one was closed by stale bot and I don't seem to have the possibility of reopening it

It would be nice if stale bot would stay away from here

### CODE REVIEW

**Comment by strk** [comment]
Is there anything I can do to prevent stalebot from closing this PR ? Continuously replying to it makes a lot of noise for no reason.

**Comment by nyalldawson** [comment]
> there anything I can do to prevent stalebot from closing this PR ? Continuously replying to it makes a lot of noise for no reason.

Just let it close, and reopen when you're ready to resume the work. Doing otherwise is unfair to everyone else who has PRs ready for review as it dramatically decreases the likelihood that valid PRs will be found.

**Comment by strk** [comment]
The value for me to keep this open is that it is easier for me on next bugfixing iteration to get a list of things worth fixing rather than having to start from scratch and go again hunting for what needs to be done, especially if something is already done. It's a kind of agenda, can't we find a way for my need to not be a problem for the use cases you have in mind ? Can't I just set a label or a "draft" state for this PR to not get in your way ?

**Comment by strk** [comment]
I've marked it as a draft, hopefully this would reduce the fair problem you mentioned. If so, I suggest the stale bot leaves drafts alone

**Comment by strk** [comment]
Evidently StaleBot doesn't care about PRs being draft, it still wants to close them. Would you be ok with a PR to fix this problem and let Draft PR remain open @nyalldawson ?

**Comment by strk** [comment]
> Evidently StaleBot doesn't care about PRs being draft, it still wants to close them. Would you be ok with a PR to fix this problem and let Draft PR remain open @nyalldawson ?

I've filed https://github.com/qgis/QGIS/pull/56062 to do this

**Pull request closed without merging**
