### PR TITLE
Add scroll area to fix resizing in layer properties window

### PR DESCRIPTION
**Pull request by NEDJIMAbelgacem**
## Description
The layer properties window sometimes annoys user by being unable to resize to small size properly and for some smaller screen resolution that might end up occupying an unwanted part of the screen.
For example here is the smallest shrinking I could get before:
layer_properties
I added a scroll area around to make a scroll bar show up instead of refusing to shring further:
Screenshot from 2021-04-28 06-54-35
Each widget inside a tab in the layer properties window might have different size requirements which will make it difficult to try to fix the resizing issue for them one by one, I think the better solution is to just have a scroll area around the layer properties window content like I'm doing in this PR.

### CODE REVIEW

**Comment by uclaros** [comment]
I haven't tested this yet, but I'm not quite sure this is a good idea...
We should decide an absolute minimum dialog size, then properly make each tab conform to that. 

Related issue: #38134

**Comment by nirvn** [comment]
I'm not convinced about this. IMHO, much better to work on insuring the panels can shrink to an acceptable size instead of putting scroll bars. For e.g., in the screenshot above, if that really can't be sized down vertically, let's figure out which panels / widgets enforce such a tall vertical minimum size and deal with it.

I don't think we'll ever get as small as your second screenshot, but we shouldn't anyways ;)

**Comment by wonder-sk** [comment]
Agreed with @nirvn and @uclaros - moving the whole dialog into a scroll area looks like a big hammer - and it is not really going to fix the usability issue with form being too long.

As already stated, first it is better to see if there is any single embedded widget among the point cloud configuration widgets that makes the height too big. If there's nothing to fix there, the next step would be to add a QScrollArea, but only where it is really needed. You can take some inspiration e.g. from `src/ui/qgssymbolselectordialogbase.ui` where the scroll area only embeds QStackedWidget:

image

But here probably it will be enough to just fix the minimum vertical size of some widget(s)... It may just take a bit of time to find which widget is the cause :-)

**Comment by roya0045** [comment]
@wonder-sk IMO width is more of an issue than height. Though revising all the widget to set with element can be resized or not  (does the combo box for units need to remain this large, etc) will be a long process.

**Comment by wonder-sk** [comment]
@NEDJIMAbelgacem I have compiled your branch, there is an improvement, but there is still something making the layer styling dock widget too long - I can't make it shorter than this, meaning that I can't have it docked even when QGIS is full screen (or the status bar at the bottom gets pushed out of the screen. It could be that one of the sub-widgets has minimum height set too high...

image

**Comment by wonder-sk** [comment]
Actually it may be some weirdness of my window manager... trying the master version now, things seem to be working fine (scrollbar appearing as expected), there's just one case when resizing does not work correctly (undock layer style panel and dock it again - suddenly it has much bigger minimal height) and so it does not bother me anymore. So I am happy if we just close this PR...

**Pull request closed without merging**
