### PR TITLE
Fix #43834

### LINKED ISSUE #43834: Python console wrong character encoding
**Describe the bug**
Python script character encoding is based on something else than UTF-8. Tried every Windows 10 setting to change region/locale/encoding with no success.

**How to Reproduce**

Enter print('áéŐŰÍ') in the python script window and run the script. I wonder where cp1252 is coming from. Entering it in the console command line works though.

image

**QGIS and OS versions**

QGIS version
3.20.0-Odense
QGIS code revision
decaadbb31
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.0
PROJ version
8.0.1
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 1809

Active Python plugins
db_manager
MetaSearch
processing

### PR DESCRIPTION
**Pull request by jef-n**

### CODE REVIEW

**Comment by nicogodet** [comment]
Thanks @vstinner on IRC.

Btw, this should also fix #41601.

**Comment by nyalldawson** [comment]
@jef-n won't we need a solution which also helps with scripts run from outside of the qgis app?

**Comment by jef-n** [comment]
> @jef-n won't we need a solution which also helps with scripts run from outside of the qgis app?

I think that is addressed by setting `PYTHONUTF8=1` by default in OSGeo4W.

**Comment by nyalldawson** [comment]
@jef-n 
> I think that is addressed by setting PYTHONUTF8=1 by default in OSGeo4W.

Ah, so that change is being made too?

**Comment by jef-n** [comment]
building, testing and rebuilding MSIs for the last days…   I didn't yet manage to upload and publish anything before another issue popped up…    But perhaps this time…

**Comment by jef-n** [comment]
> Ah, so that change is being made too?

yes, that I even just uploaded to OSGeo4W.

**Comment by nyalldawson** [comment]
Big thanks @jef-n !

**Comment by nicogodet** [comment]
Tested OK on Master (3.21.0-44), 3.20.0-3 and 3.16.8-3 !

image

**Pull request closed without merging**
