### PR TITLE
Add me in Qgis map (new user)

### PR DESCRIPTION
**Pull request by All4Gis**
Add me in Qgis map (new user)

### CODE REVIEW

**Comment by m-kuhn** [comment]
Hi @All4Gis can you shortly outline the contributions you have done for QGIS so we can handle this pull request?
Thank you!

**Comment by All4Gis** [comment]
Hi.I'm contributed developing plugins,,and all are in my github,I giving training courses too,but I have never contributed in the Core. thanks

**Comment by m-kuhn** [comment]
@timlinux assigned to you

**Comment by m-kuhn** [comment]
@timlinux could you have a look at this?

**Comment by NathanW2** [comment]
I think this is map is mainly for core contributions right?

**Comment by timlinux** [comment]
I'm ok to merge this...we have e.g. Marco Bernasocchi in the list and a field indicating whether the entry is for core committer or not...

**Comment by luipir** [comment]
I agree with @NathanW2 ... I supposed was for core contributor (docs, translate, code, bug fix etc etc). As Marco Bernasocchi or myself, that we are "simply" contributors than committers.
Some people does not have any tag in the json description, but we know them really well, most of them are translators or bug testers (e.g. giovanni manghi) etc etc.

**Comment by gioman** [comment]
> most of them are translators or bug testers (e.g. giovanni manghi) etc etc.

if you count Processing I have contributed also some (not much of course) core code, adding and improving tools gdal/ogr based (and have plan to do more in this area, I'm just lacking time).

**Comment by All4Gis** [comment]
I think that any type of contribution is welcome and the title says "contributor.json", with the option of "committer" yes or no.

I think that implementing plugins, with new ideas, teaching courses and participate in the community as long as my time allows me, is also a contribution. Now, I'm thinking of translating documentation into Spanish.

I think that it is always interesting to talk about these things and the final decision is yours.

**Comment by gacarrillor** [comment]
I'm in favor of keeping this map for people who has contributed directly (e.g., commits, patches, PRs) to core, whether they have commit permissions or not (that's what **Commiter** is all about, isn't it?). 

In my opinion, QGIS trainers and plugin developers are more suitable for the [Community map](http://planet.qgis.org/community-map/). They are in fact contributing to QGIS community as a whole, but not directly to QGIS core. Core contributions (i.e., entering to this list) should remain as a very special milestone for any developer.

Does it make sense?

**Comment by DelazJ** [comment]
@All4Gis:
> Now, I'm thinking of translating documentation into Spanish.

You can use the special entry for that: [doc/Translators](https://github.com/qgis/QGIS/blob/master/doc/TRANSLATORS)

I also think that the contributor list should be kept for people who somehow directly participate to QGIS core. There's a doc/CONTRIBUTORS file which actually introduces:
>  The following people have submitted code, patches, graphics, comments,
 feedback, reviews and/or many other things that have aided the development of
 QGIS

How is this file different from doc/contributors.json file? And could those two lists be unified? 
Sorry to digress a bit but I think this PR should also be the occasion to clarify things.
Another thing that puzzles me is that there's also a doc/AUTHORS list:
* is it for committers? aren't they already in the contributors.json list (with a commit tag)?
* only committers of qgis/QGIS repo or all qgis [official repo](https://github.com/qgis): documentation, website, plugins (django), server....? (already asked in http://osgeo-org.1560.x6.nabble.com/Updating-contributors-json-td5275278.html)

And I agree with @gacarrillor that the community map may better fit contributors like plugin devs, trainers... those people that animate the community. Btw, it'd be nice to have it included in the About dialog (maybe more people (trainers/plugins devs) will then add themselves and we'll have a better picture of the dynamism of the community).

**Comment by nyalldawson** [comment]
Any consensus here? Can we make a call either way and help clean up the PR queue?

**Comment by 3nids** [comment]
I think the consensus is quite clear that contributors list is for core. 

+1 to close, but maybe things should be written a bit more clearly, and we could also provide a plugin authors map.

**Comment by All4Gis** [comment]
I agree with your decision if this list is only for core developers.

But I think we should be able to accept more people in the community, people who encourage collaborating and collaborate in another way. It is a good option to create another type of list etc ... like this map https://plugins.qgis.org/ Community-map /

**Pull request closed without merging**
