### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by timlinux**
## Description

First pass at rebranding with our new logo.

qgis

screen shot 2017-03-19 at 8 41 08 pm

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [X] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [X] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [X] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [X] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [X] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

# CC

@anitagraser @nirvn

### CODE REVIEW

**Comment by nyalldawson** [comment]
Whee! 

Can I suggest moving the .ai format file to the promotion repo instead?

**Comment by nyalldawson** [comment]
Also... Your recent project list makes me very curious!

**Comment by timlinux** [comment]
> Can I suggest moving the .ai format file to the promotion repo instead?

I think we can remove it completely - we already have the SVG master in promotion.

> Also... Your recent project list makes me very curious!

All I can say is [this](http://www.classicgaming.cc/classics/pac-man/files/sounds/pacman-death.zip) :-)

**Comment by nyalldawson** [comment]
> All I can say is this :-)

I take it that means you'll be filing a grant proposal to allow an "audio" renderer for QGIS symbology?

**Comment by sildeag** [comment]
I think the new logo looks a lot better without the old “Arrow”.  The “Pencil” look, however, does not convey GIS.  Google “GIS Logo”, click image tab,  and you’ll see what I mean.  Get rid of pencil and eraser, a little too dated, and replace it with a back slash “magnifying glass symbol” with a map or globe in the round shaped glass lens.

**Comment by nyalldawson** [comment]
@sildeag

This PR isn't seeking feedback on the new logo - that's already been voted on and accepted by the project voting members, following a period of review by a dedicated qgis design team.

Rather the PR is just about implementing the new logo in the app, so comments should related specifically to technical details regarding that.

**Comment by timlinux** [comment]
Hi @sildeag Thanks for your comments, however note that this is not the correct forum for debating the logo itself, only any technical issues relating to the replacement of the old logo in the code base and side effects it may introduce. The logo itself has already been through a community peer review and voting process. If you have any comments on the graphics etc. (bearing in mind the previous sentence I wrote), please contact @anitagraser .

Thanks

Tim

**Comment by m-kuhn** [comment]
Thanks @timlinux @anitagraser and everyone else involved. I really like it! Time for some fresh and new imagery :+1:

**Pull request merged**
