### PR TITLE
 Drop all composer classes from Python bindings

### PR DESCRIPTION
**Pull request by nyalldawson**
Bye bye

### CODE REVIEW

**Comment by luipir** [comment]
Hi @nyalldawson is it related to old classes respect the new composer rewrite?

**Comment by nyalldawson** [comment]
> Hi @nyalldawson is it related to old classes respect the new composer rewrite?

I don't understand, sorry?

**Comment by luipir** [comment]
sorry... reason to remove binding? I didn't follow the composer rewrite, and I can't figure out from the PR the reason to remove bindings.

**Comment by nyalldawson** [comment]
Ah yes - all these classes have been replaced by their layouts equivalent. E.g QgsLayout, QgsLayoutItem, etc. They are all redundant now, and will be dropped from core as soon as we've finalized the composer -> layouts converter.

**Comment by luipir** [comment]
tnx

**Pull request merged**
