### PR TITLE
MetaSearch: update startindex to items

### PR DESCRIPTION
**Pull request by tomkralidis**
## Description

OGC API - Features provides a convention/examples to use `offset` for items paging workflow.  OGC API - Records uses OGC API - Features as a building block.  We have used `startindex` in the MetaSearch client thus far (was used in WFS 2, for example).  Server implementations like [QGIS Server](https://github.com/qgis/QGIS/blob/master/src/server/services/wfs3/qgswfs3handlers.cpp#L788) have been using `offset`.  pygeoapi has [updated](https://github.com/geopython/pygeoapi/pull/864) their codebase to align with `offset` as well as [OWSLib](https://github.com/geopython/OWSLib/commit/16ba31af36d155d1a89007ead2792218dcbb4fa7) (which MetaSearch uses as a client).

Having said this, even though this is an OAFeat convention and `next`/`prev` link relations are opaque, it makes sense to update for convenience.

cc @rouault

### CODE REVIEW

**Review by rouault — COMMENTED** [review]
LGTM (but I'm not familiar with the MetaSearch plugin). A more bullet proof implementation would look in the OpenAPI document if offset is an advertized parameter.

**Comment by tomkralidis** [comment]
Good point @rouault.  One could also inspect the `prev`/`next` link relations.  Will look into for a future update/PR.

**Comment by rouault** [comment]
> One could also inspect the `prev`/`next` link relations

that would be the most interoperable way if you just need to browse through the results.  offset is only needed if you need to seek to a particular index.

**Comment by maxcollombin** [comment]
Shouldn't the `startindex` parameter also be replaced by `offset` here (L198) ? :

https://github.com/qgis/QGIS/blob/4539f276fa6b61d8f018e6f33deabcc8c3194d3e/python/plugins/MetaSearch/search_backend.py#L198

**Comment by tomkralidis** [comment]
> Shouldn't the `startindex` parameter also be replaced by `offset` here (L198) ? :

This should already be in this PR proper: https://github.com/tomkralidis/QGIS/blob/metasearch-offset/python/plugins/MetaSearch/search_backend.py#L201

**Comment by tomkralidis** [comment]
FYI CI tests fixed/now passing.

**Review by rouault — APPROVED** [review]

**Pull request merged**
