### PR TITLE
Extra options for Open Attribute Table 

### PR DESCRIPTION
**Pull request by raymondnijssen**
## Description

This adds 2 extra options for opening attribute tables: directly open with the *selected* items and with the *visible* (on map) items. I'm a bit in doubt if this should also work in the context menu.

Shortcuts for this already existed and are very handy when working with large datasets (a table with 5M records) but I noticed that hardly anyone knows those shortcuts. By putting them in the menu and toolbar I hope people will find these options more easily.

### CODE REVIEW

**Comment by raymondnijssen** [comment]
image

**Comment by rduivenvoorde** [comment]
Very nice! I was not even aware of these possible shortcuts!!
What I always did is to go to  Settings / Options / Data Sources / Attribute table behavior and set it there.
(sometimes with big tables, I have to kill QGIS (as it is trying to retrieve my 16miljon records from db or 8miljon from wfs and freezing...) first to be able to set it back to 'only visible'...)

One thing that I saw is that the 'General option' (The Top option) is actually the global behaviour you have set in the Settings.
So using the upper option I was thinking I was showing all items, but I kept seeing only visible ones (because of global setting)

Maybe add an extra option? 
- Open Attribute Table (As set in Settings)
- Open Attribute Table (Show all items)
- Open Attribute Table (Selected items)
- Open Attribute Table (Visible items)

Another observation (but that is probably just me): I could not find the 'open attribute table' button anymore (after it changed to the one with the little viewing glass (vergrootglas?))

**Comment by rduivenvoorde** [comment]
One other (non related) idea... what about also do this with the 'Open Project' icon: add the little dropdown to it with available Templates?

Screenshot-20210304163721-110x90

**Comment by raymondnijssen** [comment]
Thanks Richard! 
Maybe we should remove the entire option from settings, as you can now choose whenever you click the button? I think it's not a general setting anyway, as it depends a lot on your layer (size) which option to pick.

For the icon, I can imagine your problem. I really spend time on creating the best icons I could think of, but they are quite different in coloring and that's what your eyes are going for when searching for the old, famous attribute table option. Maybe the buttons should not swap, but have the 2 extra options in the drop down?

**Review by nyalldawson — COMMENTED** [review]
Code looks good to me! I think the "visible" icon needs a rework though, as it looks more like a "search attribute table" action to me. I think it should have some reflection of the map canvas in the icon instead.

**Comment by nyalldawson** [comment]
Good move!

On a related note - I would like to see a "open attribute table with first 100 rows" option sometime...

**Comment by uclaros** [comment]
> Maybe the buttons should not swap, but have the 2 extra options in the drop down?

Yes, that makes sense! We could also check for *shift* and *control* status when the attribute table is launched so that we can use shift-click and control-click on the (always shown) first icon in the drop down, or even on the layer's context menu!!!


> On a related note - I would like to see a "open attribute table with first 100 rows" option sometime...

Should we start collecting feature requirements somewhere for a revamped attribute table? When will be the time to replace the chewing gum with a more robust material?

**Comment by raymondnijssen** [comment]
I will make an icon with a table+eye. Please don't merge yet

**Comment by nyalldawson** [comment]
I'm going to go ahead and merge, and add the icon request to https://github.com/qgis/QGIS/projects/1

**Pull request merged**
