### PR TITLE
Improves datum transform selection. 

### PR DESCRIPTION
**Pull request by avlisad**
- Fixes issue with "Hide deprecated" check box
- Creates a score to sort multiple datum transform definitions
- Creates a entry on layers context menu to recall datum transform selection dialog
- Prevents multiple mouse clicks on "CRS status" icon on status bar
- Prevents settings update when project properties dialog is cancelled

### CODE REVIEW

**Comment by nyalldawson** [comment]
@avlisad sorry for the ridiculously long delay in this PR review - is this still an issue in current QGIS releases? Is there any chance you could rebase this PR against master?

**Comment by m-kuhn** [comment]
@wonder-sk @nyalldawson @3nids you discussed this in Nødebo if I am not mistaken. Can you shortly outline the plans?

**Comment by m-kuhn** [comment]
@nyalldawson @3nids considering your work on datum transform, can you check this PR for interesting pieces and cherry-pick these and close this PR?

**Comment by m-kuhn** [comment]
Looking at the list of conflicts and given the recent rework of context transform I think this can be closed.

If things remain to be done here, it's probably easier to start new work on top of master.

**Pull request closed without merging**
