### PR TITLE
Fix UI loading crash on Ubuntu. Refs #8760

### PR DESCRIPTION
**Pull request by ghost**
This commit is related to https://issues.qgis.org/issues/8760

Proposed fix resolves issue on my Ubuntu machine that leads to QGis crash when loading form from UI file.

Using `QUILoader::clearPluginPaths()` remove all hard-coded paths registered for plugins search. This avoid to use shared library `libqgis_customwidgets.so` by QGis with mismatched version to instantiate custom widgets (these custom widgets implementations are already defined in QGis dependencies).

### CODE REVIEW

**Comment by luipir** [comment]
is it a local installation problem? do you mind that this create side effects loading other plugins or other code that expect to use UI path?
I suppose it should not affect any other code, but I would say to do this modification only if we are sure that this issue is not a local installation problem.

**Comment by gioman** [comment]
> is it a local installation problem?

Hi Luigi, no is not a local issue. Is a long standing issue an all installations on Ubuntu.

**Comment by mhugo** [comment]
Yes, from what I understand, "UI plugins" (a.k.a. custom widgets) are only useful for Qt Designer. But they are loaded by QUiLoader by default and may lead to problems when different versions of these custom widgets (say 2.16 and 2.18) are installed on the same system.

**Comment by luipir** [comment]
@mhugo hmmmm... is it then a debian package post install problem?
BTW I superficially read https://issues.qgis.org/issues/8760 and I'm not against the PR, but IMHO is not the appropriate fix that seems more a packaging/installation error than a code error.

**Comment by m-kuhn** [comment]
Do promoted QGIS widgets (like QgsCollapsibleGroupBox) still work?

**Comment by nouanda** [comment]
@m-kuhn Yes custom widgets are still working in QGis.

Qt reports this warning in console:
`Warning: "QFormBuilder was unable to create a custom widget of the class 'QgsCollapsibleGroupBox'; defaulting to base class 'QGroupBox'."`

But instantiated widget is not the Qt base class `QGroupBox` ...

**Comment by nouanda** [comment]
@luipir I think it's more a Qt problem (that defines some hard-coded paths for plugins search in `QUILoader`) rather an installation problem.

We can imagine the case where another software deploy another plugin in the same way defining a custom widget with the same name.

By using default `QUILoader` paths we have no idea where Qt searches custom widgets plugins (except if we are listing these paths). By explicitly setting custom searching paths (here empty) we safely know that loaded plugins are expected shared libraries.

**Comment by m-kuhn** [comment]
The strange thing is, that when I tested it was a) only on Ubuntu b) caused by `geometry`-attributes for widgets in the .ui file.

Do you think this fix can somehow be related to that?

**Comment by nouanda** [comment]
I'm not sure it's related to your problem. But default paths defined by Qt seams to be platform dependent ; that can explain why only certains platforms are concerned by the problem.

**Comment by m-kuhn** [comment]
> But default paths defined by Qt seams to be platform dependent ; that can explain why only certains platforms are concerned by the problem.

In this case would it be nice to limit it to affected platforms only?
I'm a bit afraid that this fix here could have some unexpected side effects on platforms that work perfectly fine right now...

**Comment by luipir** [comment]
@m-kuhn I agree. Another check to do is it this fix is valid also for master of QT has solved this kind of issue

**Comment by nouanda** [comment]
**For note purpose:**

Qt 4.8.7 source code for `QUILoader` initiate these paths with all `QCoreApplication::libraryPaths()` - appending `/designer` for each path.

Qt application library paths are defined by these rules (from http://doc.qt.io/qt-4.8/qcoreapplication.html#libraryPaths):

> Qt provides default library paths, but they can also be set using a qt.conf file. Paths specified in this file will override default values.
> 
> This list will include the installation directory for plugins if it exists (the default installation directory for plugins is INSTALL/plugins, where INSTALL is the directory where Qt was installed). The directory of the application executable (NOT the working directory) is always added, as well as the colon separated entries of the QT_PLUGIN_PATH environment variable.

**Comment by m-kuhn** [comment]
On Fedora I also never experienced any problem.
All ui files that killed QGIS on several ubuntu versions where handled perfectly fine.

**Comment by m-kuhn** [comment]
Can we move this forward? It would be great if this issue could finally be fixed.

Would it be possible to test the following prior to merging this:

[ui.zip](https://github.com/qgis/QGIS/files/1128173/ui.zip)

* Test on your system
  * without the patch
    * project.ui should crash
    * project-sanitized.ui should not crash
  * with the patch
   * both do not crash

* Test on another Ubuntu System (affected by the original bug, @gioman can you do that?)
  * If project.ui crashes
  * project-sanitized.ui not crashes

The point is, I would really like to merge this but some evidence is needed that pull request really solves the original issue (or a similar, local issue). Plus I need some confirmation from someone else, that the attached demodataset is useful (I do not have an ubuntu machine at hand).

Thanks for the help, everyone.

**Comment by gioman** [comment]
> without the patch
> 
>     project.ui should crash
>     project-sanitized.ui should not crash

they both make my unpatched qgis 2.18.10 crash (Ubuntu 16.04). I could try with the patch, but not not during the week end.

**Comment by m-kuhn** [comment]
Thanks

> they both make my unpatched qgis 2.18.10 crash (Ubuntu 16.04)

Too bad I didn't upload the sanitized version 2 years ago

> I could try with the patch, but not not during the week end.

That would be much appreciated!

**Comment by nouanda** [comment]
@gioman Have you some QGis plugins for QtDdesigner installed in Qt plugins path ?
On my Ubuntu it's located in `/usr/lib/x86_64-linux-gnu/qt4/plugins/designer`.

Crash appears for me using QGis 2.18.10 because old QGis plugin for QtDesigner `libqgis_customwidgets.so.2.14.16` is installed in this location. Removing this file remove the crash for me.

Have you the same effect ?

**Comment by nouanda** [comment]
@m-kuhn Tested on my Ubuntu 16.04 with QGis 2.18.10:

No crash with `project.ui` ; even if I remove my patch. Your ui file doesn't define any custom widgets ? I have no custom widget for QGis in the file (and an undefined QRC file).

**Comment by m-kuhn** [comment]
I have not seen any evidence that https://issues.qgis.org/issues/8760 (origin of project.ui) is related to custom widgets yet.

I'm still trying to find out if this patch really targets 8760 or just something that looks similar.

Looking forward to test results from @gioman (or others who can test 8760).

**Comment by nouanda** [comment]
@m-kuhn This patch will only concern crash for ui file with custom widgets. It's not fully related to #8760.

**Comment by gioman** [comment]
@nouanda 

> @gioman Have you some QGis plugins for QtDdesigner installed in Qt plugins path ?
> On my Ubuntu it's located in /usr/lib/x86_64-linux-gnu/qt4/plugins/designer.
> 
> Crash appears for me using QGis 2.18.10 because old QGis plugin for QtDesigner libqgis_customwidgets.so.2.14.16 is installed in this location. Removing this file remove the crash for me.
> 
> Have you the same effect ?

```
giovanni@sibirica:~$ ls -al /usr/lib/x86_64-linux-gnu/qt4/plugins/designer
total 5608
drwxr-xr-x  2 root root    4096 Jun 25 11:02 .
drwxr-xr-x 17 root root    4096 Jul 19  2016 ..
-rw-r--r--  1 root root   35216 Mai 15 13:15 kde3supportwidgets.so
-rw-r--r--  1 root root   31120 Mai 15 13:15 kdedeprecated.so
-rw-r--r--  1 root root   27000 Mai 15 13:15 kdewebkitwidgets.so
-rw-r--r--  1 root root  342952 Mai 15 13:15 kdewidgets.so
-rw-r--r--  1 root root   27336 Jan 19  2016 libpyqt4.so
-rw-r--r--  1 root root   18848 Abr  5  2016 libqdeclarativeview.so
lrwxrwxrwx  1 root root      32 Jun 24 06:37 libqgis_customwidgets.so -> libqgis_customwidgets.so.2.18.10
-rw-r--r--  1 root root 4921424 Jun 24 06:39 libqgis_customwidgets.so.2.18.10
-rw-r--r--  1 root root  319088 Abr  5  2016 libqt3supportwidgets.so
```

anything here should I try to delete?

**Comment by nouanda** [comment]
@gioman 
Hum no, `libqgis_customwidgets.so` refers to the right version of QGis. The provided ui file doesn't contain custom widget ; so my patch doesn't refer to this problem (that I haven't on my Ubuntu).

**Comment by gioman** [comment]
> (that I haven't on my Ubuntu).

@nouanda how do you have installed your QGIS copy, by compiling or by using the qgis,org repositories? When I do tests I only use QGIS installed by normal users means, in this case the repositories (the one with the ubuntugis dependencies).

**Comment by nouanda** [comment]
@gioman 
I have installed QGis 2.14 by using qgis LTR repositories.
I'm using QGis 2.18 by compiling it & launch it without installation.

My Ubuntu machine is so in a "not normal" state.

**Comment by gioman** [comment]
> My Ubuntu machine is so in a "not normal" state.

@nouanda it would be interesting if you could try in clean system (like a VM) with ubuntu 2.18 just installed by qgis repo + ubuntugis and see if you still does not get the crash.

**Comment by nouanda** [comment]
@gioman I will install a clean Ubuntu VM & test with QGis 2.18 from repo. In which way are you loading ui file ? For my previous tests I load the file with a QGis Python plugin (but not a minimal Python plugin).

**Comment by gioman** [comment]
> In which way are you loading ui file ? For my previous tests I load the file with a QGis Python plugin (but not a minimal Python plugin).

@nouanda using the GUI: layer properties > fields > provide UI file > (select UI file) > ok > ok > identify a feature on map

**Comment by nouanda** [comment]
@gioman By loading ui file with your method I have the same results.

**Comment by gioman** [comment]
> same results

so, no crash?

**Comment by nouanda** [comment]
@gioman No crash with my version 2.18 (from source) during loading ui file but on exiting. I have crash with QGis 2.14 installed from repository. Crash appears when loading ui file from QUILoader from c++ (via layer properties ...), no with uic in Python (that was my previous method to load ui file - when I haven't crash)

**Pull request closed without merging**
