### PR TITLE
Allow relative links in composer labels

### PR DESCRIPTION
**Pull request by pvalsecc**
Now labels and HTML boxes can contain relative URLs. If we don't have
a base URL, the project file will be used as a base URL (closes #7236).

Remove the weird exception for the labels where the images where not
loaded (unless in in PDF or image mode). It was because of a supposedly
crash. The QgsComposerHtml didn't have this exception and nobody was
complaining about crashes there and after removing the exception no crash
is happening.

Fix a leak when rendering labels.

### CODE REVIEW

**Comment by nyalldawson** [comment]
> Remove the weird exception for the labels where the images where not
loaded (unless in in PDF or image mode). It was because of a supposedly
crash. The QgsComposerHtml didn't have this exception and nobody was
complaining about crashes there and after removing the exception no crash
is happening.

I could reproduce this consistently when editing the html source of a label. It's possible it's been fixed in more recent qt versions, but I would see it when the html img tag was only partially complete. Ie, start typing a <img src=" and you'd get the segfault.

**Comment by pvalsecc** [comment]
@nyalldawson,
What version of Qt do you use?
Did you try with my patch? Maybe it was crashing because of the missing delete.
Do you have a crash if you use an HTML box instead of a label?

**Comment by nyalldawson** [comment]
I've just tested with this branch, and I still see the crash. Here's how to reproduce:

1. start a new project
2. open a new composer, add a label
3. set the label to "render as html"
4. start typing in the source box ``
7. crash! (At least on linux with Qt 4.8.7)

The difference between this and the html item is that labels are updated immediately, so malformed and incomplete html is passed to the QWebPage to render. HTML items are only updated on request, which (mostly) prevents incomplete html from being rendered.

**Comment by pvalsecc** [comment]
@nyalldawson,

Thank! I was able to reproduce. Looks like Qt doesn't like having the HTML loading while painting. I've move the loading to another place (when the text is changed) and I cannot reproduce anymore.

Can you give it one more try with your setup and my new version?

**Comment by nyalldawson** [comment]
Looks good - nice work! This will make it much nicer to use :+1: 

contentChanged() will also need to be called by refreshExpressionContext() and the deprecated setExpressionContext() method, in case the content contains expressions which will change their values. 

Could you also add a test case for the relative path support?

**Comment by pvalsecc** [comment]
OK, @nyalldawson, your comments have been acted upon. Thanks for the testing.

**Comment by nyalldawson** [comment]
Merged - thank you!

**Pull request merged**
