### PR TITLE
add Q_PROPERTY for QgsCoordinateReferenceSytem::isGeographic and QgsGeometry::isNull

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by 3nids** [comment]
following discussion in #8667

**Review by m-kuhn — APPROVED** [review]

**Comment by nyalldawson** [comment]
Hey - I think this merge was premature. I think given @wonder-sk's concerns in #8667 it should have been left open long enough for him to comment. Can we revert until he can respond?

**Comment by m-kuhn** [comment]
Given the silence of @wonder-sk at the end of the discussion I doubted that there was much more to discuss. If this interpretation was wrong, please open a revert pull request @wonder-sk .

FWIW, I'm mostly concerned about consistency of read-only properties throughout the codebase and to follow Qt's lead (where applicable).

**Comment by wonder-sk** [comment]
Just for the record, I do not feel strongly about this, so if you guys are happy I am happy too :)

**Comment by 3nids** [comment]
I had no real strong opinion either, but the argument that Qt does it made be turncoat. 
🐑

**Pull request merged**
