### PR TITLE
[Tests][Server] WMS GetPrint a layout with legend anchored bottom right

### PR DESCRIPTION
**Pull request by rldhont**
## Description

Testing server WMS GetPrint with a layout in which the legend is anchored bottom right

### CODE REVIEW

**Comment by rldhont** [comment]
Try to fix https://github.com/qgis/QGIS/issues/35063

**Comment by rldhont** [comment]
It seems QGIS Server does not get the right layout...

**Comment by rldhont** [comment]
Check `referencePoint` and `resizeToContents`

**Comment by rldhont** [comment]
This PR adds a test that because of an issue in QGIS Server. It is waiting for a fix

**Comment by rldhont** [comment]
Still waiting for bugfixing

**Comment by nyalldawson** [comment]
@rldhont let's close for now, until you have the fix ready -- the PR queue is just getting out of hand and we need to clean up "wip" style requests from those actually ready for review

**Comment by rldhont** [comment]
@nyalldawson I have no clue why the `referencePoint` is reseted.

**Pull request closed without merging**
