### PR TITLE
[afs] Show URL link in layer metadata

### PR DESCRIPTION
**Pull request by nyalldawson**
Adds a new "URL" link in the layer's html metadata if a provider's decodeUri method returns a "uri" parameter.

Implemented for AFS provider, showing a link to the online service url for the layer.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nirvn?

**Comment by nirvn** [comment]
Nice. Would be worth doing for AMS provider too.

**Comment by nyalldawson** [comment]
> Nice. Would be worth doing for AMS provider too.

Ok, done

**Comment by nirvn** [comment]
Nice. +1 to merge whenever travis greens up.

**Comment by nirvn** [comment]
Actually, one bit missing: the QgsRasterLayer::htmlMetadata() function needs updating.

**Pull request merged**
