### PR TITLE
[processing] fix broken SAGA algorithms

### PR DESCRIPTION
**Pull request by ghtmtt**
## Description
Fixes 2 broken SAGA algorithms.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by ghtmtt** [comment]
BTW: is it worth to backport this fix?

**Comment by ghtmtt** [comment]
to optimistic with the tests ;) @m-kuhn any idea why is failing? 
https://travis-ci.org/qgis/QGIS/jobs/371952442#L1061 seems like the name of the raster is not managed correctly, but in the other tests it is treated correctly.. any hints?

**Comment by ghtmtt** [comment]
@m-kuhn @nyalldawson sorry to bother you guys.. I have no idea why the test is failing (it complains for the dem.tif file but the parameter is exactly the same of another running test). Should I remove this test and leave the fix?

**Comment by m-kuhn** [comment]
It seems it's looking for a field called `dem` in the output layer. This field is present in the expected result dataset you uploaded, but apparently not on the real result dataset.

Is this field useful/required (i.e. is it an issue with the algorithm if it's not there)?

I've pushed a commit that hopefully prints the available fields to get a bit more context on what's actually produced.
In any case, if the field is not valuable, it can be defined as skipped field in the yaml file.

**Comment by m-kuhn** [comment]
It says

> AssertionError: Field name 'dem' not found in Field names ['id', 'demtif']

Does this make sense for you?

**Comment by ghtmtt** [comment]
not really.. the algorithms copies the raster values to the point layer calling the new column `dem` (so the layer name) while the test is looking for the column `demtif` (layer path). Is the error related to the test and not to algorithm itself right?

**Comment by m-kuhn** [comment]
I guess your local SAGA installation calls the column `dem` while the SAGA on travis is calling the same column `demtif`.
I guess the values in this column are the interesting values produced by the algorithm? In this case it would be great not to skip it.
Can you create a comparison file with the column called `demtif`?

**Comment by ghtmtt** [comment]
> Can you create a comparison file with the column called demtif?

and pass this file to the test or what exactly do you mean?

**Comment by m-kuhn** [comment]
Yes, replace this file here https://github.com/qgis/QGIS/pull/6864/files#diff-c567084a3d3994247ea380ed25ffff49R46

**Comment by ghtmtt** [comment]
would it be easier to change the column name of the vector layer itself?

**Comment by m-kuhn** [comment]
of which vector layer?

**Comment by ghtmtt** [comment]
the output one.. if now travis is looking for the column `demtif` while the output layer (correctly created) has the column `dem`, changing the name of this last column to what travis is looking for should fix this issue.. or not... 🤔

**Comment by m-kuhn** [comment]
I think you are proposing the same that I also wanted to propose ;)

**Comment by ghtmtt** [comment]
ahah ok.. let's see what happens ;)

**Comment by ghtmtt** [comment]
yay! travis is happy ;) so this could be he trick also for other SAGA tests.. with your commits, if travis fails, the output should be more verbose and relatively easier to catch this traps.. ;)
thanks @m-kuhn, fell free to merge if you want! 

BTW: is it worth to backport it to 3.0?

**Pull request merged**
