### PR TITLE
Initial implementation of QgsCoordinateFormatter

### PR DESCRIPTION
**Pull request by nyalldawson**
(Not ready for merge)

I'm after thoughts/suggestions on this one. I've stripped the logic for formatting points as coordinates out of QgsPoint so that it can be more widely used, and to overcome shortcomings in the QgsPoint implementation.

See https://github.com/qgis/qgis3.0_api/issues/12 for the justification behind this.

Currently I'm after thoughts on the API for this new class. Is this approach suitable? 

Note that all the logic has been pulled out of the mature/well tested QgsPoint implementations, so there should be no need to review that.

### CODE REVIEW

**Comment by SebDieBln** [comment]
Nice!
Will it be possible for the user/plug-in writer to add new formats? We have some customers with very special (and uncommon) preferences of how their coordinates should be formatted in reports etc.

**Comment by nyalldawson** [comment]
@jef-n there seems to be an error in the indentation test, where it occasionally fails for no reason (eg this PR). My suspicion is that this is occurring when a non .cpp/.h/.py file is modified in a commit.

**Comment by nyalldawson** [comment]
@SebDieBln interesting, that's not a use case I've considered before. I'm wondering though if it's worth the complication of handling this for what seems to me to be quite a specialised request. Note that since 2.12 it's possible to use expressions to create custom coordinate formats for composer grids, and I'm unaware of anywhere else QGIS exports these coordinates (as opposed to just showing them in GUI).

**Comment by SebDieBln** [comment]
> quite a specialised request

No, please don't consider it a request. It was a question purely out of interest because if your answer would have been _yes_, it could have become an option for us in the future.

**Comment by jef-n** [comment]
@nyalldawson I don't see that the indentation test fails!?

**Comment by nyalldawson** [comment]
@jef-n sorry, got mixed up. It was on my repo that this same commit failed. See:

https://travis-ci.org/nyalldawson/QGIS/jobs/97194914

and 

http://dash.orfeo-toolbox.org/testDetails.php?test=35683712&build=211426

**Comment by jef-n** [comment]
Can you make sense of the after_script output in above job?   The TRAVIS_COMMIT_RANGE apparently was 2e49c516d859..48d4574b9e2b - not sure where 2e49c516d859 comes from.

**Comment by SebDieBln** [comment]
@jef-n I have the same issue, lots of them, so I was following with great interest. I figured the problem occurs when rebasing.
> not sure where 2e49c51 comes from

It comes from the [last build in @nyalldawson's branch](https://travis-ci.org/nyalldawson/QGIS/builds/97156730). After a rebase this commit is orphaned and not ```git clone```d to Travis. The TRAVIS_COMMIT_RANGE therefore is invalid.

Given the ```--depth=30``` option the problem should also occur when pushing more than 30 commits to a branch at once. I can test that. Tomorrow.

**Comment by nyalldawson** [comment]
> No, please don't consider it a request. It was a question purely out of interest because if your answer would have been yes, it could have become an option for us in the future.

@SebDieBln still, i'm interested in some more details (specifically, where the formatted coordinates are used in qgis which they would benefit from this custom formatting)

**Comment by SebDieBln** [comment]
> I'm interested in some more details

We currently use a python plugin to generate reports as PDF files. An essential part of the report are some screenshots of the QGIS map canvas with certain layers and features visible. Additionally there is a table that contains coordinates in the customers CRS and preferred format.
If we would use QGIS to create the table (in composer maybe?) it would be useful to have user-defined formats.

My thoughts were also based on the technology: If a class is used to transform coordinates from numbers to text, maybe it is not a big step to use an object and thus make it possible to create child classes to implement new formats.

But these are just thoughts and I really don't mean to distract you.

**Comment by SebDieBln** [comment]
> Given the `--depth=30` option the problem should also occur when pushing more than 30 commits to a branch at once.

And it does.

Have a look at [my testbranch](https://github.com/SebDieBln/QGIS/commits/TestTravis30commits). I pushed the first commit of this branch and then the remaining 34 commits in a second push.

Travis generated two builds:
* :white_check_mark: [Travis job for the first push](https://travis-ci.org/SebDieBln/QGIS/jobs/97443392)
* :x: [Travis job for the second push](https://travis-ci.org/SebDieBln/QGIS/jobs/97449750)

Note that the second job failed with a reference to my first commit SebDieBln@24280c694fc526a5ce32f5625a23a7e2c87fad12 in the branch:
```
Checking indentation in 24280c694fc5..ffa041263ea3
fatal: ambiguous argument '24280c694fc5..ffa041263ea3': unknown revision or path not in the working tree.
```

**Comment by nyalldawson** [comment]
> My thoughts were also based on the technology: If a class is used to transform coordinates from numbers to text, maybe it is not a big step to use an object and thus make it possible to create child classes to implement new formats.

I've been thinking about this - let me give this approach a shot and see how it works

**Comment by nyalldawson** [comment]
I'd like to merge this (ancient) PR before freeze. I'd still like to revisit this and implement a registry of custom coordinate formatters at some stage, but before 3.0 API is frozen I would very much like to get rid of the formatting methods from QgsPointXY. See https://github.com/qgis/qgis3.0_api/issues/12

Any objections?

**Comment by 3nids** [comment]
Indeed git depth was a bit short for code layout build on large pr.
Fixed in https://github.com/qgis/QGIS/commit/042f2cd3486bc7d99a9c9292cb593270e42efcd6

**Pull request merged**
