### PR TITLE
Test building QGIS on native MinGW-w64 (MSYS2)

### PR DESCRIPTION
**Pull request by MehdiChinoune**
## Description

Setup CI for test building QGIS on native Windows (MSYS2 MinGW-w64-UCRT64)

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
It seems like qgis wasn't updated to be compatible with Qwt 6.2
- Some declarations should be updated.
- QwtPolar is now part of qwt, searching for qwtpolar should be disabled if qwt>=6.2.0

**Comment by nyalldawson** [comment]
@MehdiChinoune this is great!

The 3 hour build time is a concern though -- is there any caching we can do here to cut that down?

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune this is great!
> 
> The 3 hour build time is a concern though -- is there any caching we can do here to cut that down?

ccache should help, but I don't have much experience with it.

**Comment by MehdiChinoune** [comment]
> The 3 hour build time is a concern though -- is there any caching we can do here to cut that down?

the previous run took about 5 hours, now with caching It takes about 45 minutes.

**Comment by nyalldawson** [comment]
Great! Let's give it a shot...

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@MehdiChinoune this workflow has started failing -- see eg https://github.com/qgis/QGIS/pull/52386 . Have you got any insights here?

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune this workflow has started failing -- see eg #52386 . Have you got any insights here?

For some reason the slashes were removed from paths, for example `srccoreCMakeFilesqgis_core.dirqgis_core_autogenmocs_compilation.cpp.obj` should be `src/core/CMakeFiles/qgis_core.dir/qgis_core_autogen/mocs_compilation.cpp.obj`

**Comment by MehdiChinoune** [comment]
Probably something to do with cache, cmake 3.26.1 started converting `\` to `/` with Ninja Generator in https://gitlab.kitware.com/cmake/cmake/-/commit/60132272302f106c996aa15a0c42cb3de9789a24
but I couldn't reproduce it locally, so somehow the cache is not compatible with the previous one.
Should be deleted I guess!

**Comment by MehdiChinoune** [comment]
My bad I was using cmake 3.26.0 not 3.26.1

**Comment by MehdiChinoune** [comment]
It's a cmake issue, I will try to revert that patch.

**Comment by MehdiChinoune** [comment]
@nyalldawson Feel free to delete it or disable it.

It's hard to make a minimal reproducer As there are many other huge projects that build successfully with latest CMake.

**Comment by MehdiChinoune** [comment]
issue reported https://gitlab.kitware.com/cmake/cmake/-/issues/24642

**Pull request merged**
