### PR TITLE
[server] Allow WMS GetFeatureInfo on root layer and groups

### PR DESCRIPTION
**Pull request by elpaso**
cherry-picking commit 0e8b90de44 from 3_6

### CODE REVIEW

**Comment by elpaso** [comment]
@pblottiere , @rldhont any objection to backport?

**Comment by pblottiere** [comment]
Thank you for unit tests exhaustiveness @elpaso!

**Review by pblottiere — APPROVED** [review]

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
No objection to backports

**Comment by elpaso** [comment]
@pblottiere @rldhont thank you for the review! 
I think we have a good coverage for GFI now, I'm afraid there is still a potential issue (if we don't catch it earlier), we could have a problem if the layer or group (short)name is duplicated.

**Comment by tudorbarascu** [comment]
Thanks @elpaso for this feature.
The server issue with short_name is already in redmine https://issues.qgis.org/issues/16317

**Pull request merged**
