### PR TITLE
Restore GDAL < 2.2 compatibility

### PR DESCRIPTION
**Pull request by podsvirov**
## Description

Fix small mistake from #39267.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Gdal < 2.2 is VERY old. You shouldn't be using that. Is there any reason you haven't updated?

**Comment by podsvirov** [comment]
> Gdal < 2.2 is VERY old. You shouldn't be using that. Is there any reason you haven't updated?

On the old platform, which I cannot replace, there is GDAL 2.1, but I managed to build QGIS 3.16 (2.18 was preinstalled) - this inaccuracy was already there and was the only error that prevented the build.

**Comment by rouault** [comment]
This patch as it is not going to be useful for master, as there's a CMake check testing GDAL >= 3.0 in FindGDAL. And I'm pretty sure there are other places in master that require GDAL >= 3.0, like the use of OAMS_TRADITIONAL_GIS_ORDER in src/core/qgsogrutils.cpp, and likely in other places. So your change is perhaps enough to keep QGIS 3.16 running, but definitely not master. You're free to maintain a fork of QGIS to work with older GDAL (that's the true power of open source software), but that's not material of interest for QGIS upstream as we've moved on for long.

**Comment by rouault** [comment]
And a more useful PR for here would be to remove that dead and broken code :-)

**Pull request closed without merging**
