### PR TITLE
Fix PyQt compat lib INSTALL path

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by nirvn** [comment]
@m-kuhn I've just tried it, it does fix the make install issue, thanks for the fast response.

**Comment by m-kuhn** [comment]
@nirvn where are the files (QtGui etc.) installed?

**Comment by nyalldawson** [comment]
@m-kuhn any idea why this work has killed the OSX Travis builds? Should we temporarily disable them?

**Comment by nirvn** [comment]
@m-kuhn {INSTALL_PREFIX}/share/qgis/python/PyQt

**Comment by m-kuhn** [comment]
@nirvn thanks, will merge

@nyalldawson no... I thought it was fixed but actually it's not. I'll check if I find reason.

**Pull request closed without merging**
