### PR TITLE
Server: catch datasource error for release-3_4

### PR DESCRIPTION
**Pull request by rldhont**
## Description
Manually cherry-picking #8922

If a datasource is not available (e.g. an external DB is temporarily down), QGIS Server currently silently draws the map without this information. For the desktop, this behaviour (render the map with the information available and writing a warning/error to the message log) is certainly what users want. For the server however this behaviour can lead to delivering invalid maps (e.g. public administration maps missing critical information).

Other servers (e.g. UMN) return exceptions if a layer is not available. Therefore this PR tries to propagate rendering / DB connection error message upwards to catch them in GetPrint and GetMap. It furthermore prevents caching of projects with missing datasources (a datasource may become available later on).

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by mhugent** [comment]
I don't know if it is a good idea to backport to 3.4. Because it affects a lot of files so the risk of introducing regressions is there (murphy's law usually happens in computer programs)

**Comment by rldhont** [comment]
Right, but without this fix, I think QGIS Server 3.4 is not usable.

**Comment by mhugent** [comment]
But QGIS Server has been used a long time ago without these changes. Well, I don't really have a strong opinion wether to backport or not. Just a gut feeling the changes are a bit too much for a bugfix release in a LTR.

**Comment by rldhont** [comment]
The problem with QGIS Server 3.4 is that it put in cache project with bad layers, and this is new in QGIS Server scope. So I need to handle bad layers and throw exceptions.

If no-one is ok for backporting all your work, I will backport only the bad layer handle part.

**Comment by mhugent** [comment]
Sounds good to me, +1 for backporting the bad layers part

**Comment by pblottiere** [comment]
Hi @rldhont,

> Well, I don't really have a strong opinion wether to backport or not. Just a gut feeling the changes are a bit too much for a bugfix release in a LTR.

+1

> I will backport only the bad layer handle part.

+1

**Comment by rldhont** [comment]
The backport with the bad layer handler has been done and has passed tests.

**Pull request closed without merging**
