### PR TITLE
Allow to edit empty shapefiles

### LINKED ISSUE #38834: Empty Temporary scratch layer made permanent is not editable.
**Issue**

After recording a weird behaviour with some layers, I have realised that when a new Temporary scratch layer is made permanent (as .shp) before adding to it any new feature or field, it becomes not editable. 
The new layer does not accept new features or new fields. Also, trying to use the Field calculator to create a new field, it appears the message _This layer does not support adding new provider fields. You can only add virtual fields._

Also removing and readding the layer to the project doesn't solve the problem.  

**How to Reproduce**

1. Create a new Temporary scratch layer (with any geometry type) without adding any field. 
2. Make it permanent as shapefile .shp clicking in the icon in the Layers Panel or using the voice in the menu.
3. Toggle off the editing mode.
4. Toggle on the editing mode.
5. The Add Feature icon it will be not selectable.
6. Open the Attribute Table: the add new Field icon is not selectable.
7. Open the Field Calculator: it will appear the message _This layer does not support adding new provider fields. You can only add virtual fields._

**QGIS and OS versions**

Tried on QGIS 3.10.10, 3.14.16 and dev 3.15 on Windows 8 and 10

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #38834

### CODE REVIEW

**Comment by nyalldawson** [comment]
Is there any context for this available from the git blame?

**Comment by elpaso** [comment]
it's from 2007 @jef-n , reference 

commit bf62b3969eb0dca937c0a8d8f934df361d508d58
Author: jef <jef@c8812cc2-4d05-0410-92ff-de0c093fc19c>, Mon Nov 19 22:20:38 2007 +0000 (13 anni fa)
Committer: jef <jef@c8812cc2-4d05-0410-92ff-de0c093fc19c>, Mon Nov 19 22:20:38 2007 +0000 (13 anni fa)
Precedes: final-1_8_0
Branches: <Expand>

negate write capabilities for shapefiles w/o attributes, fixes #803

git-svn-id: http://svn.osgeo.org/qgis/trunk@7612 c8812cc2-4d05-0410-92ff-de0c093fc19c

**Comment by nirvn** [comment]
#803 then: https://issues.qgis.org/issues/803

**Comment by elpaso** [comment]
I added a test and it doesn't crash on my machine (waiting for Travis), the fact that the issue is so old makes me think we should give it a try, but if is there any other test I could add I'm open for hints.

**Comment by nyalldawson** [comment]
Looking over the old ticket I strongly suspect this was a workaround to a gdal issue which has subsequently been fixed. I'm +1 to merge

**Comment by rouault** [comment]
I think it is safe to merge too. There have been fixes looong time ago in the OGR shapefile driver to handle no attribute situation, and the minimum GDAL version QGIS requires should be safe regarding that

**Comment by nyalldawson** [comment]
Unrelated test failure

**Pull request merged**
