### PR TITLE
[FEATURE] Port polylabel from javascript to QgsGeometry, add processing alg

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR implements a method in QgsGeometry and a processing algorithm to calculate the pole of inaccessibility for a surface, which is the most distant internal point from the boundary of the surface. This function uses the 'polylabel' algorithm (Vladimir Agafonkin, 2016), which is an iterative approach guaranteed to find the true pole of inaccessibility within a specified tolerance. More precise tolerances require more iterations and will take longer to calculate.

### CODE REVIEW

**Comment by nyalldawson** [comment]
More details https://github.com/mapbox/polylabel and https://www.mapbox.com/blog/polygon-center/

**Comment by nyalldawson** [comment]
TODO - expression function, and think about changing default polygon label placement to use this.

**Comment by nirvn** [comment]
Brilliant. It'd be great to also enable this for polygon's centroid marker symbology.

**Comment by alexbruy** [comment]
Processing part looks good for me.

**Pull request merged**
