### PR TITLE
[processing] area unit settings for raster layer unique values report algorithm

### PR DESCRIPTION
**Pull request by nirvn**
## Description
Last item on my to-do list for the raster layer unique values report algorithm: area unit type selection:
screenshot from 2017-10-10 14-54-00

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by nyalldawson — COMMENTED** [review]
I don't think this approach will work correctly - e.g. imagine a worldwide raster in WGS84 - using  QgsUnitTypes::fromUnitToUnitFactor will not convert correctly in this situation.

Unfortunately - you'd need to use QgsDistanceArea, and measure the area for the pixel geometry for each pixel, using the current project ellipsoid setting...

**Comment by nirvn** [comment]
@nyalldawson , yeah, I was thinking about this -- should we not offer this (users would simply have to reproject their rasters to a desired unit-based projection), or add a note in the algorithm short description mentioning that non-layer area unit might not be accurate with ellipsoid projected layers?

**Comment by nyalldawson** [comment]
I think that's dangerous. I suspect many users would blindly use the "metres" setting with a geographic input CRS, and just trust the numbers which come out.

As much as I hate to say it - if we're not going to measure the areas correctly, I think we should just leave the conversion to users to do manually from the values calculated in the layer CRS.

**Comment by nirvn** [comment]
@nyalldawson , OK.

**Pull request closed without merging**
