### PR TITLE
[processing] Make GDAL/OGR algorithms work with (input) memory layers

### PR DESCRIPTION
**Pull request by gacarrillor**
This PR adds the possibility to run GDAL and OGR Processing algorithms using memory layers as input. With this PR, when Processing gets input memory layers, it converts them to temporary Shapefiles (something it's already capable of) and executes GDAL/OGR commands with adjusted parameters. The key parameter was _layername_, which is now taken from the corresponding temporary Shapefile's basename.

All current GDAL/OGR Processing algorithms (almost 50) were tested. Some important notes:
- **ogr2ogrclip.py** This, to my knowledge, is the only algorithm that can get more than one memory layer as input: an input layer and a clip layer. Such clip layer (and its corresponding name) required special handling, namely, the parameter `-clipsrclayer` is given the name `memory_clip_layer` when a memory layer is used, so that we can deal with it separately in `GdalAlgorithm.processAlgorithm()`.
- When referring to a memory layer in "Creation options" parameters, the user needs to use `memory_layer` as layer name, for example:

```
     -dialect sqlite -sql "SELECT ST_Buffer( geometry , 20 ), * FROM 'memory_layer' "
     -dialect sqlite -sql 'SELECT ST_Buffer( geometry , 20 ), * FROM "memory_layer" '
     -dialect sqlite -sql "SELECT ST_Buffer( geometry , 20 ), * FROM \"memory_layer\" "
```
- Documentation should recommend using double quotes for identifiers (when needed by column and table names) and single quotes for values. (See http://trac.osgeo.org/gdal/wiki/rfc52_strict_sql_quoting) Since temporary file names may contain points, it's safer to use double quotes for the `memory_layer` table name (i.e., second and third options above).

[needs-docs]
Fix #14430

### CODE REVIEW

**Comment by volaya** [comment]
looks good to me. @alexbruy ?

**Comment by alexbruy** [comment]
I'm fine with it

**Comment by rouault** [comment]
> temporary Shapefiles

Why not a SQLite or Spatialite DB ? This would avoid issues with field name truncation, etc...

**Comment by gacarrillor** [comment]
I agree, field name truncation could occur and ruin processing work flows. But I didn't choose Shapefiles, I used the only Processing export format supported right now. See https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tools/dataobjects.py#L297-L307 for details.

Note that we will just need really minor changes to this PR once Processing gets support for SQLite-based exports.

**Comment by volaya** [comment]
That method exports to shapefile because it is the format that we assume all external apps will understand. Since this is for the particular case of GDAL, and GDAL supports others, you can have your own export routine and take advantage of that.

**Comment by gacarrillor** [comment]
Yes, I'm close to push another commit, but I'm still polishing some things.

**Comment by strk** [comment]
It would be great if you could provide automated tests for the algorithms

**Comment by gacarrillor** [comment]
Crazy what occurred to this PR. 
I've submitted a new one, much cleaner: https://github.com/qgis/QGIS/pull/3644

**Comment by gacarrillor** [comment]
Closing in favor of https://github.com/qgis/QGIS/pull/3644

**Pull request closed without merging**
