### PR TITLE
fix stroke Width sld import

### PR DESCRIPTION
**Pull request by tudorbarascu**
In relation with #19795, fixes sld import for marker that was ignoring stroke width. Will follow up with tests regarding the server side highlighting feature which uses SLD's. Upstream port of https://github.com/qgis/QGIS/pull/7945

### CODE REVIEW

**Comment by tudorbarascu** [comment]
For some reason I get "dash.orfeo-toolbox.org refused to connect." and I cannot catch from dash.. the travis generated image for now.

**Comment by nyalldawson** [comment]
@pblottiere can you look at this?

**Comment by tudorbarascu** [comment]
@pblottiere Until now, the SLD stroke width was only working for Polygons. Now it also works for Points. For SLD with lines ...  they don't appear in the output image at all.

**Comment by pblottiere** [comment]
Hi @tudorbarascu,

> Until now, the SLD stroke width was only working for Polygons. Now it also works for Points. 

Nice, thanks for fixing the issue!

> For SLD with lines ... they don't appear in the output image at all.

Do you have any idea why? Is it an issue in core also or in server this time?

**Comment by tudorbarascu** [comment]
For Point it was in core as before this pull you can replicate on Desktop for Point:
- export a point sld file with a specific stroke-width (30 pixels for example)
- looking at the sld file the stroke width gets exported
```
<se:SvgParameter name="stroke-width">30</se:SvgParameter>
```
- importing the sld file ignores the stroke-width to the default (PROBLEM)

For Line it works on Desktop so this time it's a server issue only.
On Desktop the only problem was that the width was ignored but on server you get nothing.
I'm still not up to the point where I can read C++ easily so it's a little bit cumbersome for me.
There are still disabled tests on the server which should be enabled when the bugs are fixed.
Thanks for reviewing.

**Comment by pblottiere** [comment]
@tudorbarascu 

> On Desktop the only problem was that the width was ignored but on server you get nothing.

Is there a disabled test for this specific issue with lines on server side?

> There are still disabled tests on the server which should be enabled when the bugs are fixed.

I'm going to start the bugfix work shortly and it will be my starting point :).

**Comment by tudorbarascu** [comment]
@pblottiere Yes, it's included in this pull request (which has two tests, one disabled for Line and one for Point)
If you'll work on the server side bug fixing there's https://issues.qgis.org/issues/18988 which has a demo project attach to reproduce the issue but I couldn't make a test because the bugs aren't fixed.

I suspect there's a way to use pyqgis on the Desktop side and create the "how it should render" image with the constraints of the GetMap request but I haven't investigated that yet.
If you have some pointers on this it would be really nice as I could write more disabled server tests.

Thanks a lot!

**Comment by pblottiere** [comment]
@tudorbarascu Travis is green. Do you want to add/update something or can I merge your work?

**Comment by tudorbarascu** [comment]
merge away!

**Comment by pblottiere** [comment]
Thanks @tudorbarascu

**Pull request merged**
