### PR TITLE
Geom checker fixes

### PR DESCRIPTION
**Pull request by manisandro**
Two geometry checker fixes.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@manisandro  Looks good!

BTW, Coverity has flagged a 4 other potential crashes in the plugin. Eg https://scan4.coverity.com/reports.htm#v11585/p10196/fileInstanceId=9882490&defectInstanceId=2170319&mergedDefectId=124524

Let me know if you don't have access to that page. I've tried sending an invitation to you to allow access, but not sure if it's worked.

**Comment by manisandro** [comment]
Hi @nyalldawson , I can't recall receiving an invitation. And the link above only ends up leading to the "My Projects", so I guess I'm not authorized to see the other page?

**Comment by nyalldawson** [comment]
@manisandro check the Gmail account you use to post on the dev list - there should be an invite waiting for you in there (maybe in spam). It was only sent today.

**Comment by manisandro** [comment]
@nyalldawson Hmm didn't receive anything afaics.

**Comment by nyalldawson** [comment]
@manisandro Odd.. can you try requesting access?

**Comment by manisandro** [comment]
Actually I'm already listed as member, and browsing manually to the list of defects works. So all fine, it's just the link you pasted above that for some reason does not work for me ;(

**Comment by nyalldawson** [comment]
That's odd... but glad to hear you can get access now!

**Pull request merged**
