### PR TITLE
Fix equality comparison when saving vertex tool edits

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes a comparison between feature id and feature geometry when saving vertex tool edits.

If I'm reading this right, I'm not sure how this even builds...

### CODE REVIEW

**Comment by nyalldawson** [comment]
@wonder-sk?

**Comment by wonder-sk** [comment]
That looks really scary! It turns out the `operator bool()` defined in QgsGeometry is to blame. From `bool` there is implicit conversion to `int`, so conversion to `long long` (aka `QgsFeatureId`) works as well. Now I am wondering if it is worth keeping the bool operator there as that allows us to do crazy things like `geom+3` which will happily take geom's internal pointer and add to it.

Good catch!

**Comment by nyalldawson** [comment]
I'm +1 to drop it. I think the main reason it was added was for pyqgis, so that existing code like

    if feature.geometry:

Would continue to work when we changed geometry from a pointer. But we can add it as a sip bool operator instead and regain the C++ type safety.

**Comment by 3nids** [comment]
@nyalldawson Do you plan to actually do the python operator? I think it is valuable and this might break existing code.

**Comment by nyalldawson** [comment]
@3nids it's already there and there's unit tests for it

**Comment by 3nids** [comment]
@nyalldawson sorry, thanks for the clarification!

**Pull request merged**
