### PR TITLE
Adds clang-format to pre-commit

### PR DESCRIPTION
**Pull request by 3nids**
Adds clang-format to pre-commit to non-sipified files (for the moment).
So half of the cpp files are handled by clang-format directly from pre-commit and the rest still handled through prepare_commit/astyle for now.

I tried to follow something close with clang-format, any comment/improvement to the config is welcome.

### CODE REVIEW

**Comment by 3nids** [comment]
looks like it's ready :)

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
LFG!

**Comment by 3nids** [comment]
So is this ok to discard the clang tidy errors and merge?

**Comment by nyalldawson** [comment]
@3nids 

> So is this ok to discard the clang tidy errors and merge?

They aren't related are they? I assumed they were just showing because these files were touched, not because they are new errors...

**Comment by 3nids** [comment]
That's how I see it too.

**Pull request merged**
