### PR TITLE
Add a flag argument to QgsFeatureSink::addFeatures, support fast feature insert

### PR DESCRIPTION
**Pull request by nyalldawson**
Flags can be used to control how features are added to the sink.

For now, there's only a single flag available - FastInsert. When FastInsert is set, faster inserts will be use at the cost of updating the passed features to reflect changes made at the provider.

This includes skipping the update of the passed feature IDs to match the resulting feature IDs for the feature within the data provider.

Individual sink subclasses may or may not choose to respect this flag, depending on whether or not skipping this update represents a significant speed boost for the operation.

QgsVectorLayer always ignores the flag - feature ids are required for the featureAdded signal to be correctly emitted, and it's expected that performance critical applications will add features directly to a data provider instead of via QgsVectorLayer's edit buffer.

Some providers have been updated to handle this flag, although I suspect we can further optimise them to better support fast insertion. E.g. the postgres provider should use "copy" insertions when FastInsert is flagged.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Relevant mailing list convo at http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Postgis-loading-using-COPY-instead-of-INSERTS-tt5320528.html

**Comment by pcav** [comment]
I rememeber @timlinux was very skeptical about submodules - comments welcome.

**Comment by pcav** [comment]
This would be very welcome. Anything we can do to make it happen?

**Comment by wonder-sk** [comment]
Hi Nyall - just curious - do you have any estimate how much faster is it compared to "slow" addition?

**Comment by nyalldawson** [comment]
> Hi Nyall - just curious - do you have any estimate how much faster is it compared to "slow" addition?

@wonder-sk 
I don't imagine the changes here would have a big impact yet (although possibly the changes I've made to the mssql/db2 providers may... I'm not familiar enough with those backends to know if there's a big hit with the current approach).

But postgres has the potential for a MASSIVE improvement. Currently we insert features one by one, waiting on each statement to finish. That's a lot of back and forth over the network - and on a slow connection, it's a killer. Today I was trying to insert 300000 features into a table using QGIS, and it was taking hours to just do a couple of thousand. OGR did it in about 10 minutes... 

Even if we don't switch to copies there'd still be massive improvements from using a single insert command with multiple rows when FastInsert is set, since it'd avoid the network round trip for every feature.

I definitely believe it's worth the added API complexity

**Comment by gioman** [comment]
> Today I was trying to insert 300000 features into a table using QGIS, and it was taking hours to just do a couple of thousand. OGR did it in about 10 minutes...

and that's why I added the Processing ogr based tool to import data in PostGIS almost 2 years ago ;)

**Comment by nyalldawson** [comment]
You could have done this approach 2 years ago... it's basically just a bunch of right clicking in qtcreator ;) But anyway, you've given me a good benchmark of what to beat... So we all benefit!

**Comment by nyalldawson** [comment]
Any objections?

**Pull request merged**
