### PR TITLE
rename QgsLayerTreeRegistryBridge.InsertionPoint.parent to group

### PR DESCRIPTION
**Pull request by 3nids**
because I find it confusing to do `insertionPoint.parent.insertLayer()`
better do `insertionPoint.group.insertLayer()`

### CODE REVIEW

**Comment by nirvn** [comment]
Is it an acceptable API break?

**Comment by 3nids** [comment]
Yes, it is since 3.10, I added this last week

**Comment by nirvn** [comment]
@3nids , hah, sorry :)

**Comment by 3nids** [comment]
you will rewrite twice by hand (on paper) the whole source code for not following the API closely enough!

**Pull request merged**
