### PR TITLE
Remove some unnecessary files in server

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

Partial fix of https://github.com/qgis/QGIS/issues/54423.

(as @m-kuhn already pointed out in https://github.com/qgis/QGIS-Documentation/issues/8475#issuecomment-1695089766, we should wait for QGIS4 to update the installation path to `CGIDIR`)

### CODE REVIEW

**Comment by m-kuhn** [comment]
@mhugent are you aware of reasons to keep these?

**Comment by dmarteau** [comment]
Yes, DummyService was only here for the sake of a bare exemple, it can be removed.

**Comment by pblottiere** [comment]
Hello @mhugent,

> @mhugent are you aware of reasons to keep these?

Do you have some input about these files?

Thanks.

**Comment by pblottiere** [comment]
Hello @elpaso. 

Can you give me your opinion on this PR please?

**Comment by elpaso** [comment]
> Hello @elpaso.
> 
> Can you give me your opinion on this PR please?

LGTM but those files are ancient history, I have no idea if they are still used.

**Comment by pblottiere** [comment]
> LGTM but those files are ancient history, I have no idea if they are still used.

@elpaso thanks for your quick response :). I'll wait for @mhugent input before merging then.

**Comment by pblottiere** [comment]
@mhugent :ping_pong:

**Comment by pblottiere** [comment]
@mhugent  :ping_pong:

**Review by nyalldawson — APPROVED** [review]
Let's merge. The files are always available in git history for resurrection if needed.

**Comment by pblottiere** [comment]
Thanks Nyall :tada: !

**Pull request merged**
