### PR TITLE
[needs-docs] Add annotations submenu to View menu

### PR DESCRIPTION
**Pull request by DelazJ**
Looks like they were missing...

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Good idea to add these to the menu. (They are rather unloved at the moment). But is the View menu the correct place for them? Given that they are map tools which edit the project, I'm not entirely sure. To me the View menu should be mostly full of actions which change the view only. Maybe the (super-crowded) Edit menu is a better place for them? (@nirvn?)

**Comment by nirvn** [comment]
That makes sense. Decorations are in the view menu, but it's partly because there's a visibility toggle in there.

Alternatively we could implement a show/hide annotations action (me wants :) ), which we put in an annotation submenu alongside other actions. The editing-specific ones would still be a bit odd there.

**Comment by nirvn** [comment]
For the record, that makes sense as in it makes sense to have those in the super crowded edit menu.

**Comment by DelazJ** [comment]
@nyalldawson @nirvn any decision? Thanks.

**Comment by nirvn** [comment]
I think we settled on adding it in the edit menu.

**Comment by DelazJ** [comment]
Any idea where that would be best placed? I can't find a logical (and smoother) place in the Edit menu. */me not convinced*

**Comment by nyalldawson** [comment]
@nirvn @DelazJ what's the status here? Still planning on addressing this or should we close?

**Comment by DelazJ** [comment]
Yes, still OK to finish it for 3.2 but i'm stuck at
> Any idea where that would be best placed? I can't find a logical (and smoother) place in the Edit menu.

**Comment by DelazJ** [comment]
@probot _would say:_
> Or, if you have any further questions, just ask! We love to help, and if there's anything the QGIS project can do to help push this PR forward  please let us know how we can assist.

IMO this shortcut goes to View menu but it seems that it should instead go to Edit menu. I gave it a look and honestly can't find a place it would make sense to me. Fail to see how it relates to the exposed tools. So If it has to go Edit menu, I need someone to tell me where exactly.
So QGIS project, can you help me 😄 ?

**Comment by nyalldawson** [comment]
I don't know what the QGIS project would say, but I'd say we should defer this until we can do a proper plan for rearranging the whole edit menu (which is a mess at the moment)...

**Comment by nirvn** [comment]
Looking at the positive feedback QGIS received  on social media regarding the reorganizing of the layer's right click menu and the project menu, +1 to spend time on proper reorganizing plan of these long menus.

**Pull request closed without merging**
