### PR TITLE
[GDAL provider] Workaround GDAL < 3.5.2 performance issue on VRT files of large rasters (fixes #49285)

### LINKED ISSUE #49285: Slow Opening created VRT file from ECW files for the first time
### What is the bug or the crash?

When we create a virtual raster from ECW files, QGIS takes a long time to load the virtual raster layer.

After some investigation, we found out the following stuff.

1. The issue happens on QGIS 3.16.8 and the next release (including, 3.18.x, 3.20.x, 3.22.x, and 3.26.x), but all is good on QGIS 3.16.7
2. QGIS 3.16.7 uses GDAL 3.1.4 and starting QGIS 3.16.8 it uses the GDAL version 3.3.0 or newer
3. I found out that starting on GDAL 3.2.0, it adds `OverviewList`, and when I remove this part, QGIS can load the virtual raster like before
4. Strangely, if don't remove that `OverviewList` and we manage to load to QGIS, the next time we open the virtual raster layer, there is no problem just like before. So, this issue only happens when we load vrt for the first time

### Steps to reproduce the issue

1. Download some ecw files and open them on QGIS. You can use ECW files from https://opendata.vancouver.ca/pages/2006-orthophoto-imagery-ecw/ for example
2. Open Raster -> Miscellaneous -> Build Virtual Raster
3. Select 2 or more ECW layers as the input
4. I use the following parameters, but it seems it also applies to different parameters:
    1. Resolution: average
    2. Allow projection difference: yes
    3. Add alpha....: yes
    4. Override: use EPSG 26910 for the layer from Vancouver above
    5. Resampling algorithm: nearest neighbor
5. You can save it as a temporal file or specific location, it works the same
6. Open output file: if you check it, QGIS will get the problem right after. If you don't check it you can load it later, and still get the same issue
7. If you managed to open it, close the layer or QGIS, then open it again, the problem is gone 

### Versions

I copied only from 3.26.0, but I use the same clean profile for other QGIS versions: 3.16.7, 3.16.8, 3.22.x, and 3.26.0 (and some versions in between)

Version:1.0
StartHTML:0000000107
EndHTML:0000007200
StartFragment:0000000127
EndFragment:0000007182

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.0
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 1511
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.0-Buenos Aires
QGIS code revision
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 1511

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99versions

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

- I only tested on Windows, since GDAl doesn't have an ECW provider on Ubuntu
- I tested quickly on another raster format (.tif), but it seems it works fine on both Windows or Ubuntu
- I found an old closed ticket https://github.com/qgis/QGIS/issues/26231 that is very similar, but the QGIS version is differentand

### PR DESCRIPTION
**Pull request by rouault**

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@rouault 

The test introduced here :

    assert 'OverviewList' in open(vrtfilename, 'rt').read()

fails for me on a GDAL 3.4.3 build. Do you have any insights into that?

**Comment by rouault** [comment]
> Do you have any insights into that?

not really. The OverviewList element is added since GDAL 3.2.0 per https://github.com/OSGeo/gdal/commit/4753e4af3bf1515029b376769db7c53b3466230f

What if you try on the command line "gdalbuildvrt out.vrt /path/to/landsat_4326.tif" ?

**Comment by nyalldawson** [comment]
@rouault 

> What if you try on the command line "gdalbuildvrt out.vrt /path/to/landsat_4326.tif" ?


Nope, no sign of OverviewList there!

```
<VRTDataset rasterXSize="3" rasterYSize="4">
  <SRS dataAxisToSRSAxisMapping="2,1">GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]</SRS>
  <GeoTransform>  1.7942776656861874e+01,  6.4253109104939199e-04,  0.0000000000000000e+00,  3.0231615816712921e+01,  0.0000000000000000e+00, -4.8366498497820487e-04</GeoTransform>
  <VRTRasterBand dataType="Byte" band="1">
    <NoDataValue>nan</NoDataValue>
    <ColorInterp>Gray</ColorInterp>
    <ComplexSource>
      <SourceFilename relativeToVRT="1">dev/QGIS/tests/testdata/landsat_4326.tif</SourceFilename>
      <SourceBand>1</SourceBand>
      <SourceProperties RasterXSize="3" RasterYSize="4" DataType="Byte" BlockXSize="3" BlockYSize="4" />
      <SrcRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <DstRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <NODATA>nan</NODATA>
    </ComplexSource>
  </VRTRasterBand>
  <VRTRasterBand dataType="Byte" band="2">
    <NoDataValue>nan</NoDataValue>
    <ComplexSource>
      <SourceFilename relativeToVRT="1">dev/QGIS/tests/testdata/landsat_4326.tif</SourceFilename>
      <SourceBand>2</SourceBand>
      <SourceProperties RasterXSize="3" RasterYSize="4" DataType="Byte" BlockXSize="3" BlockYSize="4" />
      <SrcRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <DstRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <NODATA>nan</NODATA>
    </ComplexSource>
  </VRTRasterBand>
  <VRTRasterBand dataType="Byte" band="3">
    <NoDataValue>nan</NoDataValue>
    <ComplexSource>
      <SourceFilename relativeToVRT="1">dev/QGIS/tests/testdata/landsat_4326.tif</SourceFilename>
      <SourceBand>3</SourceBand>
      <SourceProperties RasterXSize="3" RasterYSize="4" DataType="Byte" BlockXSize="3" BlockYSize="4" />
      <SrcRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <DstRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <NODATA>nan</NODATA>
    </ComplexSource>
  </VRTRasterBand>
  <VRTRasterBand dataType="Byte" band="4">
    <NoDataValue>nan</NoDataValue>
    <ComplexSource>
      <SourceFilename relativeToVRT="1">dev/QGIS/tests/testdata/landsat_4326.tif</SourceFilename>
      <SourceBand>4</SourceBand>
      <SourceProperties RasterXSize="3" RasterYSize="4" DataType="Byte" BlockXSize="3" BlockYSize="4" />
      <SrcRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <DstRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <NODATA>nan</NODATA>
    </ComplexSource>
  </VRTRasterBand>
  <VRTRasterBand dataType="Byte" band="5">
    <NoDataValue>nan</NoDataValue>
    <ComplexSource>
      <SourceFilename relativeToVRT="1">dev/QGIS/tests/testdata/landsat_4326.tif</SourceFilename>
      <SourceBand>5</SourceBand>
      <SourceProperties RasterXSize="3" RasterYSize="4" DataType="Byte" BlockXSize="3" BlockYSize="4" />
      <SrcRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <DstRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <NODATA>nan</NODATA>
    </ComplexSource>
  </VRTRasterBand>
  <VRTRasterBand dataType="Byte" band="6">
    <NoDataValue>nan</NoDataValue>
    <ComplexSource>
      <SourceFilename relativeToVRT="1">dev/QGIS/tests/testdata/landsat_4326.tif</SourceFilename>
      <SourceBand>6</SourceBand>
      <SourceProperties RasterXSize="3" RasterYSize="4" DataType="Byte" BlockXSize="3" BlockYSize="4" />
      <SrcRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <DstRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <NODATA>nan</NODATA>
    </ComplexSource>
  </VRTRasterBand>
  <VRTRasterBand dataType="Byte" band="7">
    <NoDataValue>nan</NoDataValue>
    <ComplexSource>
      <SourceFilename relativeToVRT="1">dev/QGIS/tests/testdata/landsat_4326.tif</SourceFilename>
      <SourceBand>7</SourceBand>
      <SourceProperties RasterXSize="3" RasterYSize="4" DataType="Byte" BlockXSize="3" BlockYSize="4" />
      <SrcRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <DstRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <NODATA>nan</NODATA>
    </ComplexSource>
  </VRTRasterBand>
  <VRTRasterBand dataType="Byte" band="8">
    <NoDataValue>nan</NoDataValue>
    <ComplexSource>
      <SourceFilename relativeToVRT="1">dev/QGIS/tests/testdata/landsat_4326.tif</SourceFilename>
      <SourceBand>8</SourceBand>
      <SourceProperties RasterXSize="3" RasterYSize="4" DataType="Byte" BlockXSize="3" BlockYSize="4" />
      <SrcRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <DstRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <NODATA>nan</NODATA>
    </ComplexSource>
  </VRTRasterBand>
  <VRTRasterBand dataType="Byte" band="9">
    <NoDataValue>nan</NoDataValue>
    <ComplexSource>
      <SourceFilename relativeToVRT="1">dev/QGIS/tests/testdata/landsat_4326.tif</SourceFilename>
      <SourceBand>9</SourceBand>
      <SourceProperties RasterXSize="3" RasterYSize="4" DataType="Byte" BlockXSize="3" BlockYSize="4" />
      <SrcRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <DstRect xOff="0" yOff="0" xSize="3" ySize="4" />
      <NODATA>nan</NODATA>
    </ComplexSource>
  </VRTRasterBand>
</VRTDataset>
```

**Comment by nyalldawson** [comment]
@rouault 

FWIW, I don't see any sign of OverviewList when I repeat using GDAL master either.

Digging into things, the first band overview count is always 0, so the logic in gdalbuildvrt_lib is never triggered. So I guess the pertinent question is why you're getting different results here..!

**Comment by rouault** [comment]
> FWIW, I don't see any sign of OverviewList when I repeat using GDAL master either.

me neither... The test was non working indeed. Sorry for this. Should be fixed with https://github.com/qgis/QGIS/pull/49686

**Pull request merged**
