### PR TITLE
Add configuration options to the attribute table

### PR DESCRIPTION
**Pull request by m-kuhn**
# Allow reordering and hiding columns

Original hiding code by @sbrunner 
# New attribute table column with a widget to trigger actions

A new widget is integrated that can be used to start (attribute) actions.
# Rename QgsAttributeAction to QgsActionManager

The original name was not representative for the scope of the class
and misleading at best.
The class manages actions for a given layer and it's not a single action
like the former name suggested.
There is a typedef introduced to keep it in the API until we can remove
it with QGIS 3.

@nyalldawson just before opening this pull request I noticed the class QgsMapLayerAction which is similar (or overlaps?) in its functionality to this class. Are there any plans to merge the two in QGIS 3. In this case renaming it now may be out of scope.

### CODE REVIEW

**Comment by m-kuhn** [comment]
@sbrunner happy to get some testing now

**Comment by sbrunner** [comment]
I don't succeed to build it ...
```[ 82%] Built target translations
[ 82%] Generating analysis/sip_analysispart0.cpp, analysis/sip_analysispart1.cpp, analysis/sip_analysispart2.cpp, analysis/sip_analysispart3.cpp

Scanning dependencies of target python_module_qgis__analysis
[ 82%] Building CXX object python/CMakeFiles/python_module_qgis__analysis.dir/analysis/sip_analysispart0.cpp.o
[ 82%] Building CXX object python/CMakeFiles/python_module_qgis__analysis.dir/analysis/sip_analysispart1.cpp.o
[ 82%] Building CXX object python/CMakeFiles/python_module_qgis__analysis.dir/analysis/sip_analysispart2.cpp.o
[ 82%] Building CXX object python/CMakeFiles/python_module_qgis__analysis.dir/analysis/sip_analysispart3.cpp.o
[ 82%] Linking CXX shared library ../output/python/qgis/_analysis.so
[ 82%] Built target python_module_qgis__analysis
[ 82%] Generating server/sip_serverpart0.cpp, server/sip_serverpart1.cpp, server/sip_serverpart2.cpp, server/sip_serverpart3.cpp

Scanning dependencies of target python_module_qgis__server
[ 82%] Building CXX object python/CMakeFiles/python_module_qgis__server.dir/server/sip_serverpart0.cpp.o
[ 83%] Building CXX object python/CMakeFiles/python_module_qgis__server.dir/server/sip_serverpart1.cpp.o
[ 83%] Building CXX object python/CMakeFiles/python_module_qgis__server.dir/server/sip_serverpart2.cpp.o
[ 83%] Building CXX object python/CMakeFiles/python_module_qgis__server.dir/server/sip_serverpart3.cpp.o
[ 83%] Linking CXX shared library ../output/python/qgis/_server.so
[ 83%] Built target python_module_qgis__server
[ 83%] Generating analysis/network/sip_networkanalysispart0.cpp, analysis/network/sip_networkanalysispart1.cpp, analysis/network/sip_networkanalysispart2.cpp, analysis/network/sip_networkanalysispart3.cpp

Scanning dependencies of target python_module_qgis__networkanalysis
[ 83%] Building CXX object python/CMakeFiles/python_module_qgis__networkanalysis.dir/analysis/network/sip_networkanalysispart0.cpp.o
[ 83%] Building CXX object python/CMakeFiles/python_module_qgis__networkanalysis.dir/analysis/network/sip_networkanalysispart1.cpp.o
[ 83%] Building CXX object python/CMakeFiles/python_module_qgis__networkanalysis.dir/analysis/network/sip_networkanalysispart2.cpp.o
[ 83%] Building CXX object python/CMakeFiles/python_module_qgis__networkanalysis.dir/analysis/network/sip_networkanalysispart3.cpp.o
[ 83%] Linking CXX shared library ../output/python/qgis/_networkanalysis.so
[ 83%] Built target python_module_qgis__networkanalysis
[ 83%] Generating gui/sip_guipart0.cpp, gui/sip_guipart1.cpp, gui/sip_guipart2.cpp, gui/sip_guipart3.cpp

sip: Unable to find file "Qsci/qscimod4.sip"
python/CMakeFiles/python_module_qgis__gui.dir/build.make:588 : la recette pour la cible « python/gui/sip_guipart0.cpp » a échouée
make[2]: *** [python/gui/sip_guipart0.cpp] Erreur 1
make[2]: *** Suppression du fichier « python/gui/sip_guipart0.cpp »
CMakeFiles/Makefile2:4960 : la recette pour la cible « python/CMakeFiles/python_module_qgis__gui.dir/all » a échouée
make[1]: *** [python/CMakeFiles/python_module_qgis__gui.dir/all] Erreur 2
Makefile:160 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2
```

Do you have an idea?

**Comment by jef-n** [comment]
pyqt4.qsci-dev not installed?

**Comment by sbrunner** [comment]
Effectively, thanks @jef-n :-)

**Comment by sbrunner** [comment]
- At first run I see a new column action, at first place... (what is it)
- I open the Filter table colum
- The column « [Action Wiget] » is at last and unchecked
- OK without any changes
- The Action column will not be visible anymore ...

Except the small issue that's look good :-), thanks

**Comment by m-kuhn** [comment]
> At first run I see a new column action, at first place... (what is it)

A widget for quickly triggering attribute actions. But it shouldn't be shown if not explicitly activated.

**Comment by sbrunner** [comment]
Excellent, this times it's working well :-)

**Pull request closed without merging**
