### PR TITLE
[server][getPrint] Use default extent instead of fail

### PR DESCRIPTION
**Pull request by TeoGoddet**
## Description
In QGIS server, there is a GetPrint request used to get composer layout outputs.

The extent parameter is now optional, if no extent is specified in the request, the extent from the layout map is used.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@elpaso @pblottiere what's your thoughts?

**Comment by rldhont** [comment]
@TeoGoddet thanks for contribution. Can you prepare some tests ?

Can you explain why, you want to put extent parameters optional for WMS GetPrint request ?

**Comment by rldhont** [comment]
After reflexion it can be usefull for overview maps

@TeoGoddet can you update your branch and add tests ?

**Comment by TeoGoddet** [comment]
reopen

**Pull request closed without merging**
