### PR TITLE
Convert geometry 2

### PR DESCRIPTION
**Pull request by mhugent**

### CODE REVIEW

**Comment by m-kuhn** [comment]
That looks a lot better now, thanks.

What happens if changes happen via QgsVectorLayerEditPassThrough? Or are directly written to the dataProvider?

I wonder if this could be even one step further towards the backend. This is mainly targetted at the postgres provider? Is it really a requirement for everything going through the edit buffer (regardless of the provider) to be converted? Doesn't this create obstacles if we wanted to improve mixed-type geometries support?

@rouault what's your idea as backend professional.

**Comment by mhugent** [comment]
>What happens if changes happen via QgsVectorLayerEditPassThrough?

True. But it can be modified and use outputGeometry() as well (needs to be changed from private to protected).

>Or are directly written to the dataProvider?

In that case, the client code is responsible itself to convert the geometry into a type accepted by the provider

>This is mainly targetted at the postgres provider?

I'm using it with the postgres provider, but it is also important for oracle spatial, mssql and probably others.

>Doesn't this create obstacles if we wanted to improve mixed-type geometries support?

In the case of mixed-type geometries, the provider could say he has unknown wkb type, so no conversion will take place. However, currently, the provider architecture and a lot of gui classes are not at all designed for mixed-type geometry support. So this is more something for the longer term.

And just to say it again, people working with curved geometries (e.g. with Swiss cadastral data) currently cannot digitize with the community version, because the db will reject their edits in most cases.

**Comment by m-kuhn** [comment]
I don't know the topic enough, just asking questions to be sure the approach is correct.

> I'm using it with the postgres provider, but it is also important for oracle spatial, mssql and probably others.

If this is a requirement for all of them, that would be one more reason to do this here. My original expectation was that postgis would (also?) handle the conversion automatically, that's why I'm not sure if it's just a postgis fixup or if it's a general purpose thing.

>> Or are directly written to the dataProvider?

> In that case, the client code is responsible itself to convert the geometry into a type accepted by the provider

That just adds a requirement for boilerplate code and a possible source of errors. If there's a good reason to do so, ok. But I think we can make life easier for plugin devs if we don't require this.

> And just to say it again, people working with curved geometries (e.g. with Swiss cadastral data) currently cannot digitize with the community version, because the db will reject their edits in most cases.

[Community version?](https://twitter.com/_mkuhn/status/722708427156418560)

**Comment by mhugent** [comment]
>If this is a requirement for all of them, that would be one more reason to do this here. My original >expectation was that postgis would (also?) handle the conversion automatically, that's why I'm not >sure if it's just a postgis fixup or if it's a general purpose thing.

I don't know oracle and mssql very well, just assuming that the concepts of type constraint is general to all spatial databases. Maybe @rouault  know more about it.
Postgres does not automatically convert and just throws an error.

**Comment by m-kuhn** [comment]
What is the drawback of doing it directly in the postgres provider?

**Comment by mhugent** [comment]
That you might have to do it in other providers as well.

**Comment by m-kuhn** [comment]
In this case it should be trivial to move the method to QgsVectorDataProvider and call it where required.

**Comment by mhugent** [comment]
Hm, I'm not sure. I can't think of a case where converting a geometry to the provider type is wrong. On the other  hand it is easy to forget a provider which needs geometry conversion. E.g. I forgot OGR, which also has a number of database types and supports curves as well.

**Comment by m-kuhn** [comment]
Hm, yes. On the other hand the risk of plugins writing directly to the dataprovider persists (and sometimes may only trigger in production) while provider-side adjustments would be a one-time thing to take care of (for those where it's really required). I imagine that OGR wants to implement this anyway so command-line-tools like ogr2ogr also can import into curved postgis tables. And either there or here we will probably also have to take care of the vector file writer.

**Comment by rouault** [comment]
Commit https://github.com/qgis/QGIS/pull/3031/commits/1ba2bc0fa9ab7f74cd1a62850ed76287922401c5 in https://github.com/qgis/QGIS/pull/3031 actually implements conversion in the OGR provider from the OGR geometry to the layer geometry type ! This was needed for GPKG that may have strong typing (I say "may" since strong typing is an option/extension enforced by triggers). Other OGR backends like spatialite, etc... have also strong typing. I'm not really well versed regarding Oracle or MSSQL constraints (perhaps @szekerest would know if MSSQL implements strict geometry type checking).

Without having a strong opinion on this, I'd be rather in favor of providers to do conversion when needed, since they are the ones who know the best when it must be done. But I can't think of a good reason for not doing it either. So perhaps the content of QgsVectorLayerEditBuffer::outputGeometry() could be moved as a utility method into the base provider class so that providers can call it when needed.
In OGR, there's a mixed approach on this. When I introduced curve support, I did want to be able to export a layer with curve geometries to any OGR backend that has write support, but not necessarily for curves. So I introduced a capability flag to advertize for curve support, and in the generic code, I implemented stroking to segmented geometries for drivers that do not advertize the capability flag. This was mainly to avoid editing the several dozains of existing backends.

**Comment by m-kuhn** [comment]
> This was needed for GPKG that may have strong typing

Is this really about *strong typing*? The way I understand it polygons are a subset of CurvePolygons and can safely be promoted. That's why I'm not sure if this is not just a postgis fixup and others will not just do this step implicitly in the backend (but as long as we didn't check your guess is as good as mine).

The opposite (CurvePolygon to Polygon) is a different story with the requirement to pre-process (segmentize) data. In this case I think having the edit buffer preserve curve information during an edit session on the one hand and having the provider raise warnings/errors if plugins try to store curves in unsupported types is a sane approach.

> But I can't think of a good reason for not doing it either.

+1, I think all of us are on the same page here. That's actually why I think it should be done in the provider because all geometries need to pass there* while the editbuffer is an optional gateway between maptool and backend.

* Except QgsVectorFileWriter. But that one needs special attention in every case - or we count on OGR to handle this.

**Comment by rouault** [comment]
> Is this really about strong typing? The way I understand it polygons are a subset of CurvePolygons and can safely be promoted
Actually, the checks in GPKG are more tolerant than with PostGIS. GPKG accepts a POLYGON in a CURVEPOLYGON layer (the checks follow the inheritance diagram http://www.geopackage.org/spec/#sfsql_intro ), but PostGIS no. For PostGIS you have to convert (which is a lossless operation) the POLYGON as a CURVEPOLYGON. However similarly to PostGIS, GPKG doesn't accept a POLYGON to be put in a MULTIPOLYGON layer, and the reverse...

> Except QgsVectorFileWriter. But that one needs special attention in every case - or we count on OGR to handle this.
OGR drivers generally do not implement geometry type conversion/promotion (except what I mentionned above regarding curve geometries being linearized for drivers not advertizing curve capability). Although that would be certainly something nice to do in situations when it is needed. People currently use the -nlt flag of ogr2ogr to instructs ogr2ogr to do the conversion.

**Comment by mhugent** [comment]
>The way I understand it polygons are a subset of CurvePolygons and can safely be promoted. That's >why I'm not sure if this is not just a postgis fixup and others will not just do this step implicitly in the >backend

Even if oracle or mssql accept e.g. Polygons in CurvePolygon layers (because a Polygon is also a CurvePolygon), there is still the thing with CompoundCurve, LineString and CircularString which needs type conversion.

>That's actually why I think it should be done in the provider because all geometries need to pass 
>there* while the editbuffer is an optional gateway between maptool and backend.

Ok, convinced. So convert_geometry_3 (hope that's the last)

**Comment by m-kuhn** [comment]
Thanks, this is really an important fix for curves (and we all know how Swiss officials like these :smile: )

> hope that's the last

I'm confident it is

**Comment by m-kuhn** [comment]
Thanks @mhugent 

If you find the time to write a test for it, that would be great.

**Pull request merged**
