### PR TITLE
parallel rendering enabled by default

### PR DESCRIPTION
**Pull request by 3nids**
I think it should be time to enable this by default!

### CODE REVIEW

**Comment by NathanW2** [comment]
Yes

**Comment by nyalldawson** [comment]
@3nids looks like I need to increase the timeouts on that action test

**Comment by 3nids** [comment]
@nyalldawson I wasn't expected this PR to have failing test. Waiting on your update to merge this?

**Comment by nyalldawson** [comment]
It's unrelated - just a intermittently failing test when the travis env is running slow

**Pull request merged**
