### PR TITLE
Improvements and fixes to advanced digitising dock

### PR DESCRIPTION
**Pull request by nyalldawson**
1. Allows updating constraints by changing the widget value whilst the constraint is locked. The previous behaviour was that the constraint had to be "relocked" if the user manually altered the constraint value in the text widgets (otherwise the change was ignored, but still confusingly shown in the widget). Now users can edit the constraint value after already locking the constraint.
2. Implements a "repeating" locking mode for constraints. When enabled, repeating locks are not automatically cleared when a new point is added. They are handy when the same constraint must be repeated for multiple points (eg adding vertices which are always 50 meters apart)

### CODE REVIEW

**Comment by 3nids** [comment]
Good ideas Nyall!

1. Perfect, works like a charm!

2.a What about using a single button with 2 actions for the locking mechanism? What do you think? Using one would make it default, so pressing enter would enable the preferred locking mechanism. 

2.b. I have problems using it. For instance, locking x in repeating mode from the beginning and adding a few points doesn't work. It seems points are added to the same exact location (first point).

**Comment by nyalldawson** [comment]
@3nids 2b should be fixed by 90d116c

**Comment by 3nids** [comment]
@nyalldawson perfect, it seems this bug was not your fault, thanks for fixing this!

**Comment by nyalldawson** [comment]
@3nids 

I've looked into alternative approach to the 2 button variant used here. Here's my verdict:
- we can't switch to an action group as that would require an API break (CadConstraint would require QActions instead of QToolButtons)
- I can't find any other software with a similar UX we can model off. The closest I can get is MS Office's (and LibreOffice's) format painter, where they use a double-click on the button to set it into locked mode. But I'm not a fan of this approach, as it's non-obvious for users (without reading documentation).

Have you got any thoughts for alternative UIs we could try? Or can I push this as-is for 2.16?

**Comment by 3nids** [comment]
As said, I wasn't that sure about this idea.
Fine for me to push as is!
Thanks a lot for this!

**Comment by nyalldawson** [comment]
Thanks!

**Pull request merged**
