### PR TITLE
Add segments to buffer in QgsGeometryAnalyzer (#15905)

### PR DESCRIPTION
**Pull request by havatv**
## Description
Suggest code changes to allow "segments to approximate" to be included in the buffer function of QgsGeometryAnalyzer (QGIS issue #15905 - https://hub.qgis.org/issues/15905).
Needs review by a developer, as I have no C++ experience.

## Checklist
Sorry, but I did not see this before I did the commit and pull request, but the changes are minimal and trivial, so I hope this is not a problem.  I have noted below the things I have not done properly.

I did not tag the commit with `[FEATURE]` in the commit message.
I have not been able to compile QGIS on my Ubuntu 14.04, so no unit tests have been run
New unit tests should not be necessary (if we trust geos)
I have not run the `scripts/prepare-commit.sh` script before the commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Hey, good to see this. This sounds like a very welcome change.
I have resolved the conflicts for you, so the unit tests can be run.

Just do a `git pull` when you are on the `buffersegments` branch, so you continue the work on the branch with the conflicts resolved.

**Comment by havatv** [comment]
The Travis check failed (`*** SIP file not up to date: core/qgsfeature.sip`). 
@m-kuhn, can you explain what the problem is?

**Comment by luipir** [comment]
@havatv seems not related with your PR, any idea @3nids if it depends on some sipify stuff?

**Comment by nyalldawson** [comment]
One thing to note - QgsGeometryAnalyzer most likely does not have long to live. When the processing->c++ refactoring is complete I can't see any reason to keep this class around, and lots of reasons not to (it's unmaintained, has no unit tests, is strongly tied to the gui)

**Comment by alexbruy** [comment]
This is not really useful, as those classes most likely will be removed in 3.0, see #4590

**Pull request closed without merging**
