### PR TITLE
Stop hardcoding "grass6" in GISRC path.

### LINKED ISSUE #30238: GRASS GISRC filename is hardcoded to GRASS 6
**Describe the bug**

When opening a GRASS mapset, the GISRC filename is hardcoded to `grassrc6`. 

**QGIS and OS versions**

I've tested this on 

- Windows: QGIS 3.4.8 and 3.6.3
- Linux: QGIS 3.4.8, 3.7

**Additional context**

This is the line that causes the issue: https://github.com/qgis/QGIS/blame/6051c7b4b656c2b17aac0a0a103b6fe1fe4e6dde/src/providers/grass/qgsgrass.cpp#L941

Obviously this is a minor issue, but I was trying to debug a GRASS issue on Windows and it made me think that QGIS was using GRASS 6 instead of 7.

I can make a pull request, but I am not sure what the filename should be (`grass` vs `grass7` etc)

### PR DESCRIPTION
**Pull request by pmav99**
Fixes #30238

### CODE REVIEW

**Comment by alexbruy** [comment]
@pmav99 seems there is another `grass6` occurences in the code, here https://github.com/qgis/QGIS/blob/master/src/providers/grass/qgsgrass.cpp#L941. From what I can see, it also should be changed as in GRASS 7, which is now used with QGIS, location of the global gisrc file is different.

Would you mind update it too?

**Review by alexbruy — COMMENTED** [review]
@pmav99 seems there is another grass6 occurences in the code, here https://github.com/qgis/QGIS/blob/master/src/providers/grass/qgsgrass.cpp#L941. From what I can see, it also should be changed as in GRASS 7, which is now used with QGIS, location of the global gisrc file is different.

Would you mind update it too?

**Comment by pmav99** [comment]
@alexbruy Not exactly. `~/.grassrc6` is a GRASS 6 specific file and I think that it is a global configuration file. QGIS reads `~/.grassrc6`, if it exists, and and copies each contents in the GISRC file that gets created. Renaming it doesn't make sense because there is no `~/grassrc` or `~/.grassrc7` file. If GRASS 6 is no longer supported, then we should completely remove the code that handles `~/.grassrc6`

**Comment by alexbruy** [comment]
I tend to disagree.

`~/.grass6rc` is a global configuration file for GRASS 6 and QGIS reads and applies settings from it. But GRASS 7 also has a global gisrc file and we should use it instead of the old global file from GRASS 6. Otherwise all GRASS settings which are defined in the global file won't be applied when using GRASS tools within QGIS. I'm pretty sure that this is not what our users will expect, especially taking into account that these global settings was used in older QGIS/GRASS versions.

**Comment by pmav99** [comment]
@gioman [mentionedt](https://github.com/qgis/QGIS/issues/30238#issuecomment-504427444) that  GRASS 6 is no longer supported. I don't really know if this is true or not. I guess you might still be able to get GRASS 6 support if you compile from source. BTW, I think that the GRASS devs no longer support 6.

Moreover, to the extend of my knowledge, even though `.grassrc6` is being parsed, `~/.grass7/rc` is being ignored. With the current implementation, if someone installs `GRASS 7` + happens to have a `~/.grassrc6` file he will be getting config options from `GRASS 6` --  even though he should not. 

All in all, I think that handling of the GRASS global configuration files files should like it should be discussed in a separate issue.

**Comment by alexbruy** [comment]
@pmav99 please read my previous comment more carefully. I don't say that GRASS 6 is used and we should read its global configuration file. My point is that we should now read global configuration of the **GRASS 7**. This is how it worked before with GRASS 6 and users rely on this functionality. We should keep backward compatibility at least until 4.0.

**Comment by pmav99** [comment]
@alexbruy I am only saying that the parsing of the global GRASS configuration file has nothing to do with hardcoded paths and that it needs to be discussed in a separate issue.

**Comment by pmav99** [comment]
@alexbruy I opened #30332

**Comment by m-kuhn** [comment]
Can we merge this and adjust the commit to "References" instead of "Fixes"?

**Pull request merged**
