### PR TITLE
Fix layout dpi should not update while typing

### LINKED ISSUE #56727: Do not update DPI of layout until field is left or the Enter key is pushed
### Feature description

The DPI of a layout is updated with every change in this field, so if I am changing the DPI from (for example) 300 to 250, the layout refreshes for each numeral entered, which in some cases makes a map unusable for several minutes. The behavior of this field should be like the scale fields (map and layout) where the scale is not updated until the field is clicked out of or the Enter key is pushed. 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fix #56727

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
I think it would be useful to backport this fix to 3.40 and 3.34, or at least to 3.40.

**Comment by nicogodet** [comment]
A timer could be nice instead of `editingFinished`

**Comment by nyalldawson** [comment]
> A timer could be nice instead of editingFinished

See https://github.com/qgis/QGIS/pull/59787 -- @YoannQDQ it should be trivial to change to that signal when https://github.com/qgis/QGIS/pull/59787 is merged

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Merging for now in order to get backports functional -- the timeout change can be addressed later

**Pull request merged**
