### PR TITLE
Fix spatialite FilterFid and FilterRect handling without primary key [WIP]

### PR DESCRIPTION
**Pull request by mhugo**
(fixes #15600)

## Description
When no primary key is defined, features returned have an id defined by an
autoincremented integer.

So we cannot use SQL filters because it would return a subset of
features and then an autoincremented id that does not correspond to
ids without filters.

FilterRect requests are fixed by requesting all the features and then
filtering them (not by SQL).

For FilterFid requests, we can use a nice hack by adding "LIMIT 1
OFFSET id" to the SQL.

### CODE REVIEW

**Comment by luipir** [comment]
@mhugo may you add tests for the fix?

**Comment by mhugo** [comment]
@luipir Yes thanks, tests added

**Comment by nyalldawson** [comment]
Just a warning - I only just noticed that the spatialite provider test is disabled on Travis. So better make sure this test works ok locally and not rely on the CI to pick it up...

**Comment by mhugo** [comment]
@nyalldawson Locally, I have one test that does not pass (not related to my changes): testVectorLayerUtilsCreateFeatureWithProviderDefaultLiteral. Is it why the test is disabled on travis ?

**Comment by nyalldawson** [comment]
@mhugo I see that too -- I suspect it's a result of https://github.com/qgis/QGIS/pull/8035, but this test wasn't updated like the others were as it didn't get picked up due to not running on Travis.

**Comment by mhugo** [comment]
@nyalldawson Thanks, I'll have a look

**Comment by mhugo** [comment]
@nyalldawson ok thanks to the PR you point me on, restoring the spatialite test seems easy, at least locally. Should I then enable it back on travis or were there something else ?

**Comment by nyalldawson** [comment]
I'm not sure - I can't recall why it was blacklisted. Better check the blacklist blame history and see if there's any clues

**Comment by mhugo** [comment]
git blame points to @m-kuhn :) Any memory of why the test was flaky ? It is not there anymore on https://dash.orfeo-toolbox.org/testDetails.php?test=63061783&build=297405 ...

**Comment by m-kuhn** [comment]
If I knew why it was flakey, I'd probably have fixed it or at least left a note ;)

Just re-enable and let's see if it does any better now. If not we'll either need to investigate or in the worst case kill it again.

**Comment by mhugo** [comment]
I meant If you remember which test failed.
Ok, let's bring it back then.

**Comment by nyalldawson** [comment]
> Travis cries about another test "offline_editing_wfs". I don't see it related ... :/

I think it must be related -- at least, wfs has the spatialite cache, so it could be that. Or it could be something in the offline plugin itself.... @m-kuhn ?

**Comment by m-kuhn** [comment]
@elpaso

**Comment by elpaso** [comment]
Yes, I wrote it, and I'm sorry that I don't know why it was blacklisted (besides the fact that it was randomly failing).

**Pull request closed without merging**
