### PR TITLE
CAD fix regression with units

### LINKED ISSUE #54501: Cant subtract or add angles since the degrees symbol has been added
### What is the bug or the crash?

Cant subtract/add angles now due to degree symbol getting in the way

### Steps to reproduce the issue

Try to draw angles by subtracting/adding the angle you get by a value, the degree symbol gets in the way which disrupts editing workflows, the symbol is OK but should be for display only and should not affect adding or subtracting or other operations. Would rather remove symbol if this blocks editing 
image

### Versions

dev version on purpose
QGIS code revision
6dde6ee503

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #54501

### CODE REVIEW

**Comment by elpaso** [comment]
@antoniolocandro can you please give this a try?

**Comment by elpaso** [comment]
@antoniolocandro thank you for the video but you are not testing this PR, grab the windows package here: https://github.com/qgis/QGIS/suites/16409674134/artifacts/937686802

**Comment by antoniolocandro** [comment]
I think I came too late to test, it solves one thing but in my case something odd happens is you use the shortcut for angle as shown in the screencast below, the angle is overwritten by the distance. I tested with the link to download the file not with latest master

https://github.com/qgis/QGIS/assets/4627073/a223197f-a934-45d9-9df7-bad9002eee57

**Comment by antoniolocandro** [comment]
Happens also in master I guess because it is the merged branch 
image
image

**Comment by elpaso** [comment]
@antoniolocandro thanks for checking, I'll have a look.

**Pull request merged**
