### PR TITLE
fix MSVC build

### PR DESCRIPTION
**Pull request by jef-n**
reverts fee62e4 and dff05dd and effectively reverting 3fb0f66 (followup #45348)

### CODE REVIEW

**Comment by nyalldawson** [comment]
-2. This will break scripts and is not the right solution here.

**Comment by jef-n** [comment]
> can you also revert [f2bb05a](https://github.com/qgis/QGIS/commit/f2bb05a3e28c56bc06fc0c16f061240b5e571674) which has become useless?

done - actually e3a77b9

**Review by nirvn — APPROVED** [review]

**Comment by nyalldawson** [comment]
Thanks @jef-n ! Can I ask what the plan is for handling this for 3.16?

**Comment by jef-n** [comment]
> Thanks @jef-n ! Can I ask what the plan is for handling this for 3.16?

old osgeo4w will continue as is and osgeo4w v2 will have updated patches using SIP6. Test building now with: https://gist.github.com/jef-n/e8914a67831798927a1ed4327d2ac62c - the src/qgis/ and src/qgis-rel-dev/ part will change once 3.22 is replaced by 3.20 as qgis in osgeo4w).

**Pull request merged**
