### PR TITLE
[Bugfix] Don't use QDialog.exec() for non-modal dialog 'ModelerDialog'

### PR DESCRIPTION
**Pull request by SebDieBln**
This PR shows the non-modal `ModelerDialog` without using `QDialog::exec()`, thereby avoiding unwanted side-effects like **opening multiple instances of the dialog**.
qgismultipleprocessingmodelerdialogs

@m-kuhn, @alexbruy 
See the discussion at 51ec2bfba6cd5eeb4bf10588d8b94ee30e7faa4a.

### CODE REVIEW

**Comment by slarosa** [comment]
Might this be applied also to the instance within the toolbox action?

**Comment by SebDieBln** [comment]
@m-kuhn I improved the wording. Note that you commented on the commit a808c15364e8d3e1c3dc4a7e12a409216979ea72, not the PR. So your comment will vanish in case I have to rebase :disappointed: 

@slarosa I am not sure what you mean by that. The toolbox is a `QDockWidget` and it is constructed only once and then shown or hidden. Should the `ModelerDialog` be closed when clicking the menu item again rather than activated?

**Comment by slarosa** [comment]
@SebDieBln I am referring to apply the same concept modeless to Model->Tools->Create new model within the toolbox in order to avoid the side effect you mentioned above.

**Comment by SebDieBln** [comment]
@slarosa Ah, yes. Sorry, I have never actually used the processing plugin.
It would be possible, but it would not have the desired effect. It would still leave users with two independent `ModelerDialog`s, one launched from the toolbox the other one launched from the menu. So additional work needs to be done to unify these two ways.
I will put some work into that, tomorrow.

**Comment by alexbruy** [comment]
Personally I don't think that opening multiple modeller windows is a side effect and bug. When you working with models frequently it is very useful to open existing model when working on another one, e.g. for check inputs/outputs, compare settings of the algorithms, etc.

@volaya can you look at this too?

**Comment by SebDieBln** [comment]
@alexbruy 
> Personally I don't think that opening multiple modeller windows is a side effect and bug.

:+1: Good point. Making this a true MDI seems consequent and useful. Showing the dialogs in the right way is the foundation for it.

> open existing model when working on another one

Opening the `ModelerDialog` for an existing model or opening it for a new model via the toolbox is still modal at the moment.

**Comment by volaya** [comment]
@SebDieBln I dont understand the purpose of the PR. You say "This PR shows the non-modal ModelerDialog without using QDialog::exec()". The dialog is actually modal, and there is a reason for that. If the dialog is not modal (apart from being able to open multiple dialogs), you can disable providers, remove models and do things that potentially can cause the modeler dialog to fail or to behave unexpectedly. So the dialog is modal to avoid all that interaction.

We can make it non-modal, but it would require adding more code to make the dialog aware of all those things, via signals/slots.

I wonder how you can open several instances of the modeler...I actually can't do it. Just tried opening the modeler from both the menu entry and the toolbox, and the modeler is modal and doesn't let me do anything outside its window...

**Comment by SebDieBln** [comment]
@volaya 
> I dont understand the purpose of the PR.

It has to be seen in combination with 51ec2bfba6cd5eeb4bf10588d8b94ee30e7faa4a, where the dialog, that is **opened from the menu**, was made modeless (have a look at the attached screenshot above) but still used `exec()`.

> The dialog is actually modal ..., 

After 51ec2bfba6cd5eeb4bf10588d8b94ee30e7faa4a the dialog **opened from the toolbox** was still modal, and that was what @slarosa referred to.

> ...and there is a reason for that.

Good point. So reverting the above mentioned commit, as @alexbruy did in 1858cc719cdbd8f20b15c72167dbcee698b9b340, seems appropriate.
Maybe it can be implemented as a new feature in the next version to be able to have multiple dialogs open at the same time. I fully support what @alexbruy said
> When working with models frequently it is very useful to open an existing model when working on another one.

I'm glad we discussed the matter and avoided potential regressions.

I close this PR. But if you like, you are welcome to cherry-pick my commit fixing some wording issues @m-kuhn pointed out.

**Pull request closed without merging**
