### PR TITLE
[processing] improve the modeler dialog UI and icons

### PR DESCRIPTION
**Pull request by nirvn**
@alexbruy , @volaya , @nyalldawson , This PR improves the modeler dialog by:
- using a proper toolbar instead of mini buttons to match other parts of QGIS (it'll also respect the size of the toolbar icons defined by the user in QGIS' settings window)
- show keyboard shortcuts in toolbar action tooltips
- create vector icons to replace PNG ones (export to python, edit help file, run modeler)

Before (left) vs. proposed (right):
untitled

I've also added labels for the model name and group name text boxes. It always confused me once text was filed with the gray tooltip gone.

### CODE REVIEW

**Comment by nirvn** [comment]
Processing's modeler is really starting to feel like an integral part of QGIS:
untitled

**Comment by nyalldawson** [comment]
@nirvn Nice! Do you think we should make this dialog a QMainWindow and gain the ability to drag toolbars around? I'd say definitely, except that Ubuntu's unity seems totally broken wrt qt apps with multiple QMainWindows (eg how composers suddenly stop responding).

But then, I don't think it's our place to hold qgis back because of one distro's bad decisions...

**Comment by nirvn** [comment]
@nyalldawson , good idea.

**Comment by nirvn** [comment]
@nyalldawson , commit updated, processing is now a QMainWindow. Proof of life:
untitled

**Comment by alexbruy** [comment]
Looks great. Thanks!

**Pull request merged**
