### PR TITLE
[FreeBSD] Update FindGRASS.cmake

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description
Since Grass 7.6 the path is /usr/local/grass7X where X is the minor version.

cc @rhurlin @neteler

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by lbartoletti** [comment]
Unrelated error

**Comment by lbartoletti** [comment]
Please, can someone merge it?

**Comment by neteler** [comment]
I have no rights but maybe @m-kuhn can do so?

**Comment by lbartoletti** [comment]
Thanks Nyall.

**Pull request merged**
