### PR TITLE
OAPIF: fix support of StringList fields

### LINKED ISSUE #33758: QGIS WFS / OGC API – Features not showing list typed attributes correctly
**Describe the bug**

QGIS WFS / OGC API – Features are not showing list typed attributes (in Identify Results) correctly. Instead of a list it returns NULL.

**How to Reproduce**

1. Add a WFS / OGC API – Features: `https://pta.spatineo-devops.com/sofp/?f=json`
2. Add Administrative units 4500k (sea area excluded) (2019) -layer
3. Use filter `"levelName" = 'maakunta'`
4. Select any polygon with Identify Features tool
5. Notice how upperLevelUnit and/or lowerLevelUnit are NULL
6. To verify the data is there add the same data as Vector Layer using Layer --> Add Layer --> Add Vector Layer... (file) with Vector Dataset(s) as `https://pta.spatineo-devops.com/sofp/collections/au_kansallinen_meri_4500k_wgs84/2019/items?f=json&levelName=maakunta&limit=100` --> Add
8. Select any polygon with Identify Features tool
9. Notice how upperLevelUnit and/or lowerLevelUnit has list data

(Any other API Features data will do if there is a list typed attributes.)

**QGIS and OS versions**

QGIS version
3.11.0-Master
QGIS code revision
12c410c3f4
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.0dev
Running against GDAL/OGR
3.1.0dev
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
7.0.0
Running against PROJ
Rel. 7.0.0, March 1st, 2020
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.
Active python plugins
buffer_clip; 
MetaSearch; 
pluginbuilder3; 
plugin_reloader; 
db_manager; 
processing

### PR DESCRIPTION
**Pull request by rouault**
Fixes #33758

### CODE REVIEW

**Comment by nyalldawson** [comment]
Lgtm. Are you working on qgis bug fixes currently? Because if so, there's a big issue in the wfs background feature iterator which is causing crashes (https://github.com/qgis/QGIS/issues/32913). It's caused by the use of an event loop in the iterator class, which isn't safe to do here when features are fetched on the main thread...

**Comment by rouault** [comment]
>  It's caused by the use of an event loop in the iterator class, which isn't safe to do here when features are fetched on the main thread.

Any idea how to address this ?

**Comment by nyalldawson** [comment]
It's not a simple change. I think you need to ensure the fetching always occurs on a background thread, and use a semaphore to block the iterator while it waits for incoming features from the fetching thread. (That's why I asked if you are doing a qgis bug fixing stint!)

**Comment by rouault** [comment]
> if you are doing a qgis bug fixing stint!

yes I'm in it. Thanks for the hints. I'll try to look at that. I think there were already similar fixes in the past in the network related code so perhaps I can find some inspiration from that

**Comment by nyalldawson** [comment]
Yes possibly you could adapt what's done in QgsBlockingNetworkRequest

**Pull request merged**
