### PR TITLE
disable inline on macOS release on clang12

### PR DESCRIPTION
**Pull request by PeterPetrik**
workaround for https://github.com/qgis/QGIS-Mac-Packager/issues/132 for the time being

### CODE REVIEW

**Comment by lbartoletti** [comment]
fyi @rhurlin if clang12 will be the default compiler on FreeBSD current

**Comment by lbartoletti** [comment]
@PeterPetrik For information, we have added [this line](https://github.com/qgis/QGIS/blob/master/src/core/CMakeLists.txt#L1701) months ago to be able to build QGIS on i386 (FreeBSD and OpenBSD IIRC)

**Comment by PeterPetrik** [comment]
thanks, let me investigate on Monday

**Comment by PeterPetrik** [comment]
this is my compilation line

```
/Library/Developer/CommandLineTools/usr/bin/clang++ \
  -DPROJ_VERSION_MAJOR=6 \
  -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050800 \
  -DQT_GUI_LIB -DQT_MACEXTRAS_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_FOREACH \
  -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_USE_QSTRINGBUILDER \
  -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DSIP_VERSION=0x04ffff \
  -DTEST_DATA_DIR="/Users/admin/qgis/builds/nightly/QGIS/tests/testdata" -DWITH_EPT -DWITH_QTWEBKIT \
  -D_HAVE_PTHREAD_ -Dqgis_core_EXPORTS -Isrc/core/qgis_core_autogen/include -I. \
  -I/Users/admin/qgis/builds/nightly/QGIS/external/poly2tri -I/Users/admin/qgis/builds/nightly/QGIS/src/core/providers/ept \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core -Isrc/core -I/Users/admin/qgis/builds/nightly/QGIS/src/core/3d \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/annotations -I/Users/admin/qgis/builds/nightly/QGIS/src/core/auth \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/browser -I/Users/admin/qgis/builds/nightly/QGIS/src/core/callouts \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/classification -I/Users/admin/qgis/builds/nightly/QGIS/src/core/diagram \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/dxf -I/Users/admin/qgis/builds/nightly/QGIS/src/core/editform \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/effects -I/Users/admin/qgis/builds/nightly/QGIS/src/core/expression \
  \-I/Users/admin/qgis/builds/nightly/QGIS/src/core/fieldformatter -I/Users/admin/qgis/builds/nightly/QGIS/src/core/geometry \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/geocms -I/Users/admin/qgis/builds/nightly/QGIS/src/core/geocms/geonode \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/geocoding -I/Users/admin/qgis/builds/nightly/QGIS/src/core/gps \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/labeling -I/Users/admin/qgis/builds/nightly/QGIS/src/core/layertree \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/layout -I/Users/admin/qgis/builds/nightly/QGIS/src/core/locator \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/maprenderer -I/Users/admin/qgis/builds/nightly/QGIS/src/core/mesh \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/metadata -I/Users/admin/qgis/builds/nightly/QGIS/src/core/network \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/numericformats -I/Users/admin/qgis/builds/nightly/QGIS/src/core/pal \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/pointcloud -I/Users/admin/qgis/builds/nightly/QGIS/src/core/processing \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/processing/models -I/Users/admin/qgis/builds/nightly/QGIS/src/core/proj \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/project -I/Users/admin/qgis/builds/nightly/QGIS/src/core/providers \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/providers/arcgis -I/Users/admin/qgis/builds/nightly/QGIS/src/core/providers/memory \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/providers/gdal -I/Users/admin/qgis/builds/nightly/QGIS/src/core/providers/ogr \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/providers/meshmemory -I/Users/admin/qgis/builds/nightly/QGIS/src/core/raster \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/renderer -I/Users/admin/qgis/builds/nightly/QGIS/src/core/scalebar \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/settings -I/Users/admin/qgis/builds/nightly/QGIS/src/core/symbology \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/textrenderer -I/Users/admin/qgis/builds/nightly/QGIS/src/core/validity \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/core/vector -I/Users/admin/qgis/builds/nightly/QGIS/src/core/vectortile \
  -I/Users/admin/qgis/builds/nightly/QGIS/external -I/Users/admin/qgis/builds/nightly/QGIS/external/nlohmann \
  -I/Users/admin/qgis/builds/nightly/QGIS/external/kdbush/include -I/Users/admin/qgis/builds/nightly/QGIS/external/nmea \
  -I/Users/admin/qgis/builds/nightly/QGIS/external/rtree/include -I/Users/admin/qgis/builds/nightly/QGIS/external/meshOptimizer \
  -I/Users/admin/qgis/builds/nightly/QGIS/src/native -Isrc/native -isystem /opt/QGIS/qgis-deps-0.8.0/stage/include \
  -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenCL.framework/Headers \
  -isystem /Users/admin/qgis/builds/nightly/QGIS/external/opencl-clhpp/include -iframework /opt/Qt/5.15.2/clang_64/lib \
  -isystem /opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -isystem /opt/Qt/5.15.2/clang_64/./mkspecs/macx-clang \
  -isystem /opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers \
  -isystem /opt/Qt/5.15.2/clang_64/lib/QtXml.framework/Headers -isystem /opt/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers \
  -isystem /opt/Qt/5.15.2/clang_64/lib/QtSvg.framework/Headers -isystem /opt/Qt/5.15.2/clang_64/lib/QtPrintSupport.framework/Headers \
  -isystem /opt/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -isystem /opt/Qt/5.15.2/clang_64/lib/QtSql.framework/Headers \
  -isystem /opt/Qt/5.15.2/clang_64/lib/QtConcurrent.framework/Headers -isystem /opt/QGIS/qgis-deps-0.8.0/stage/lib/qca-qt5.framework/Headers \
  -isystem /opt/QGIS/qgis-deps-0.8.0/stage/include/qt5keychain -isystem /opt/Qt/5.15.2/clang_64/lib/QtSerialPort.framework/Headers \
  -isystem /opt/QGIS/qgis-deps-0.8.0/stage/lib/libspatialite.dylib/Headers -isystem /opt/Qt/5.15.2/clang_64/lib/QtMacExtras.framework/Headers \
  -isystem /opt/QGIS/qgis-deps-0.8.0/stage/include/QtWebKitWidgets -isystem /opt/QGIS/qgis-deps-0.8.0/stage/include/QtWebKit \
  -isystem /opt/Qt/5.15.2/clang_64/lib/QtPositioning.framework/Headers -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing \
  -Wnon-virtual-dtor -Wno-redundant-move -Wno-return-type-c-linkage -Wno-overloaded-virtual -Wimplicit-fallthrough \
  -Qunused-arguments -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk \
  -mmacosx-version-min=10.13.0 -fPIC -fvisibility=hidden -F/opt/QGIS/qgis-deps-0.8.0/stage/lib -fPIC -std=gnu++17 \
  -MD -MT src/core/CMakeFiles/qgis_core.dir/proj/qgscoordinatereferencesystem.cpp.o \
  -MF src/core/CMakeFiles/qgis_core.dir/proj/qgscoordinatereferencesystem.cpp.o.d \
  -o src/core/CMakeFiles/qgis_core.dir/proj/qgscoordinatereferencesystem.cpp.o \
  -c /Users/admin/qgis/builds/nightly/QGIS/src/core/proj/qgscoordinatereferencesystem.cpp
```

for some reason I do not see the flag that disables inline... wondering why?

**Comment by rhurlin** [comment]
> fyi @rhurlin if clang12 will be the default compiler on FreeBSD current

Hi Loïc,
In my FreeBSD devel version 3.19.0, I have had build problems for some time now on boxes with **less than < 64 GB RAM (!)**, both amd64 and i386.

I tried the patch from PeterPetrik and it seems to solve this problem well. v3.19.0 now builds even with only 8 GB RAM :)

```
--- CMakeLists.txt.orig	2021-06-03 20:46:06 UTC
+++ CMakeLists.txt
@@ -669,6 +669,8 @@ endif()
 if (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
   set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Qunused-arguments")
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Qunused-arguments")
+  set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -fno-inline")
+  set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -fno-inline")
   set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Qunused-arguments")
   set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} -Qunused-arguments")
   set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Qunused-arguments")
```

So I would like to see a patch like this either included in my FreeBSD port or better yet, included in QGIS also for FreeBSD (besides macos) :)

**Comment by PeterPetrik** [comment]
AHA! https://cmake.org/cmake/help/latest/prop_sf/COMPILE_FLAGS.html

>> However, Xcode does not support per-config per-source settings, so expressions that depend on the build configuration are not allowed with that generator.

so `CMAKE_BUILD_TYPE MATCHES ....` is ignored on macOS

**Comment by PeterPetrik** [comment]
ok! looks like @nyalldawson in https://github.com/qgis/QGIS/commit/31d1df320a0395f070b702396854160d02778ef6 moved the file, but not updated the path the the file in the `set_source_files_properties` command, and CMake just ignores it?..!


@lbartoletti now I am wondering how it could worked last few week on FreeBSD, since the --inline-threashold=128 was not applied most probably

**Review by 3nids — APPROVED** [review]

**Comment by lbartoletti** [comment]
> now I am wondering how it could worked last few week on FreeBSD, since the --inline-threashold=128 was not applied most probably

Well, it was only necessary for i386 and FreeBSD doesn't build QGIS on i386 anymore (due to a missing dependency for qgis 3D IIRC).

**Comment by rhurlin** [comment]
> > now I am wondering how it could worked last few week on FreeBSD, since the --inline-threashold=128 was not applied most probably
> 
> Well, it was only necessary for i386 and FreeBSD doesn't build QGIS on i386 anymore (due to a missing dependency for qgis 3D IIRC).

Nope. As far as I can say, we did not have the problem because the **move to the proj dir** did not find its way in the release of 3.18.3.

The `inline patch` is valid on FreeBSD for all versions using the clang compiler ...

The FreeBSD port `graphics/qgis` additionally patches the sources by running the following target for i386:

```
post-patch:
# On i386, '-mllvm -inline-threshold=128' does not build under all circumstances
# See bugs 242557 and 241687.
.if ${OPSYS} == FreeBSD && ${ARCH} == "i386"
	@${REINPLACE_CMD} -e 's|"-mllvm -inline-threshold=128"|"-O1"|g' \
		${WRKSRC}/src/core/CMakeLists.txt
.endif
```

**Pull request merged**
