### PR TITLE
[postgresprovider] Determine geometry type and srid directly from column type

### PR DESCRIPTION
**Pull request by SebDieBln**
This PR adds a new way of determining the geometry type and srid for a layer by examining the actual type of the column returned from PostGIS.

Now even empty query layers without a requested geometry type/srid can be added as long as the geometry column is explicitly typed.
So this is a valid layer to add:

``` sql
SELECT
  t.id,
  ST_MakeLine(t.geom)::geometry(Linestring, 4326) AS geom_aggregate
FROM table AS t
WHERE
  t.id = some_non_existing_id
```

This PR uses the new method only as a last resort if everything else fails. But eventually it could be used as the default, replacing the lookups in _geometry_columns_ or _geography_columns_ because for every column mentioned there it would give the same result.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@SebDieBln can you add a test for this to tests/src/python/test_provider_postgres.py?

**Comment by jef-n** [comment]
and please use ``scripts/prepare-commit.sh``.

**Comment by SebDieBln** [comment]
@jef-n corrected the affected file, thanks for pointing that out to me!

**Comment by SebDieBln** [comment]
@nyalldawson I created the test you suggested. Note that it implicitly tests a few other things:
* using a composite key in a query a4124da2a95c30f8d9facfa701a092d1d73368aa
* adding an empty layer with a composite key 441f6f8cf1c5a500c3e898bfbcdff6757e6d8d73

**Pull request merged**
