### PR TITLE
Rename (and make safe) QgsGeometry::geometry()

### PR DESCRIPTION
**Pull request by nyalldawson**
Renames QgsGeometry::geometry as QgsGeometry::primitive() 

..Because feature.geometry().geometry() is confusing, and impossible to search for in python code (e.g. is input.geometry() a QgsGeometry or a QgsAbstractGeometry?)

But more importantantly: also adds a const version QgsGeometry::constPrimitive(). The non-const version is slow, since it now forces a detach to avoid corrupting geometries (since QgsGeometry is shared, it's not safe to directly access its primitive QgsAbstractGeometry and start messing with it without first detaching). This is a big risk in the 2.x API which could potentially corrupt feature geometries with unexpected outcomes.

Updates all uses to constPrimitive where possible.

I'll update the python code and api docs if this approach is acceptable.

**Open questions:**

Because sip casts the const away from pointers, it's entirely possible to mess things up via python. E.g.

```
g1 = QgsGeometry.fromWkt( 'Point (1 2 )' )
g2 = g1

g2.constPrimitive().setX(11) # only possible because const has been cast away by sip
g1.exportToWkt()  # 'Point(11, 2)'!!!!!

```
Is this an acceptable risk? I personally can't see any way around it..

### CODE REVIEW

**Comment by wonder-sk** [comment]
Great! The rename to "primitive" is a very good idea... not long ago @blazek was making jokes on how weird is the construct "feature.geometry().geometry()" :-)

About your open question about constPrimitive(), another option would be to just skip it for PyQt and only support primitive() in Python... not sure which option would be my preferred... Still in your Python example g1 and g2 are just two names for the same QgsGeometry object (equals operator does not make a copy) - not sure if a copy would make any difference there though.

**Comment by blazek** [comment]
No jokes how weird it is, I just find it slightly confusing, especially for newcomers. I welcome any change which distinguish methods returning different types. 

Is it primitive() really the best name? E.g. QgsGeometryCollection does not sound like a primitive. 

Does it mean that all plugins already ported to API 3 have to be upgraded?

**Comment by nyalldawson** [comment]
> Is it primitive() really the best name? E.g. QgsGeometryCollection does not sound like a primitive.

Got any other suggestions? I'm not sold on it, but couldn't think of a better alternative (but namings not my strong point..)

> Does it mean that all plugins already ported to API 3 have to be upgraded?

Yep, which is why I've said many many times that the right time to port to qgis 3 is after release

**Comment by blazek** [comment]
> Got any other suggestions? I'm not sold on it, but couldn't think of a better alternative (but namings not my strong point..)

No. Maybe abstractGeometry() according the type, but that is also bad because 'abstract' makes ony sense in relation with its subclasses. Finding good method/variable name is the most difficult in programming. Just shooting: data()? Certainly it is on you to decide.

**Comment by nyalldawson** [comment]
>  Just shooting: data()?

data()/constData() would certainly follow the Qt pattern, although it tends to convey a rather "low-level" feel to me. I guess get()/constGet() could also be an option (following c++ std).

 Otherwise I'm out of ideas. @m-kuhn @elpaso @NathanW2 @jef-n @3nids @alexbruy @dakcarto @nirvn @rouault  @mhugo / @ everyone else... any good ideas you want to throw in the mix?

**Comment by nyalldawson** [comment]
@wonder-sk 

> About your open question about constPrimitive(), another option would be to just skip it for PyQt and only support primitive() in Python... not sure which option would be my preferred... 

It might be a safer option, but certainly there'd be a performance hit if the const version isn't available. I'm thinking especially for processing algs here, esp. when used in a model (where the same shared geometries may be stored across multiple memory layers).

>Still in your Python example g1 and g2 are just two names for the same QgsGeometry object (equals operator does not make a copy) - not sure if a copy would make any difference there though.

Yep, sorry, bad example. But imagine that it's a lot more opaque, with the private geometry data being shared across memory layers/edit buffers/private python variables....

**Comment by m-kuhn** [comment]
+1, not many ideas for a name, maybe `raw()`?

What's the reason for the const-prefix?
Wouldn't it work to just use the following, especially since sip doesn't respect const'ness anyway?

```
const QgsAbstractGeometry* primitive() const;
QgsAbstractGeometry* primitive();
```

**Comment by nyalldawson** [comment]
> What's the reason for the const-prefix?
Wouldn't it work to just use the following, especially since sip doesn't respect const'ness anyway?

Basically for build safety. So that we can be guaranteed that the const version is used as much as possible (since c++ will always use the non-const version if it can)

**Comment by m-kuhn** [comment]
We are happy to require the use of `qgsAsConst` for range-based for loops on Qt Containers. Is there any difference here?

**Comment by nyalldawson** [comment]
As_const is a necessary evil... But here I'd prefer to explicit const getter, since it makes quick code reviews easier. Also, qt does this (eg QImage::constData, QList::constFirst,  QString::constData, etc...)

**Comment by nyalldawson** [comment]
Argh - forgot the other good reason. I still want to be able to use these methods from python without detaching.

**Comment by m-kuhn** [comment]
Ok, go ahead

**Comment by nyalldawson** [comment]
Any objections to get()/constGet()? I'd like to fix this up and get it merged before it's too much of a pain to rebase

**Comment by m-kuhn** [comment]
Sounds good, merge away

**Comment by NathanW2** [comment]
Sounds fine to me.

**Comment by wonder-sk** [comment]
Both data() and primitive() are fine with me. Let's make this happen :-)

**Comment by m-kuhn** [comment]
> Both data() and primitive() are fine with me. Let's make this happen :-)

I guess `get` is the proposal now (and `raw` would  be in the race as well ;) )

**Comment by blazek** [comment]
Choose whatever you think is best. `raw` sounds good, I like `raw` or `data`.

**Comment by nyalldawson** [comment]
Ok, let's go with a process of elimination. Contenders are:

- primitive
- raw
- data
- get


Everyone gets to veto one, the last contender wins.

I'm eliminating raw first up, leaving:

- primitive
- data
- get

**Comment by m-kuhn** [comment]
> I'm eliminating raw first up, leaving:
> 
> * primitive
> * data
> * get

And `primitive ` is gone, leaving:

* data
* get

**Comment by dakcarto** [comment]
@m-kuhn wrote:
> And primitive is gone, leaving:
> 
> data
> get

I like `data` for the reason Nyall indicated: "... would certainly follow the Qt pattern ...," but `get` is more indicative of the _action_ than semantically trying to further describe what's being 'got'.

So...
-0 for `data`
+0 for `get`

**Comment by nyalldawson** [comment]
@dakcarto thanks for your input! Would you mind changing your vote to a +/- 1 so we can lock the decision in?

**Comment by NathanW2** [comment]
+1 `get()`

**Comment by nyalldawson** [comment]
Thanks all - get/constGet is the winner! (with set(...) instead of setGeometry(..) )

**Comment by NathanW2** [comment]
Wait!? Can I change my vote?







....... nah all good

**Comment by landryb** [comment]
There's also a similar failure when WITH_GLOBE is enabled, i have a local patch i'm testing.

**Comment by m-kuhn** [comment]
@landryb hasn't this fixed with https://github.com/qgis/QGIS/commit/8b7fd5428f2d3eb6f4377a57f1f34f51fda3a951?

**Comment by landryb** [comment]
> @landryb hasn't this fixed with 8b7fd54?

right, probably :) was working on a git clone from some days ago.. and i have the same change locally.

**Comment by landryb** [comment]
And the WITH_3D build was fixed in 13ba57733

**Pull request merged**
