### PR TITLE
Force use of QgsUnitTypes::RenderMillimeters in QgsSymbol::bigSymbolP…

### PR DESCRIPTION
**Pull request by mj10777**
…QgsSymbol::bigSymbolPreviewImage.

## Description
QgsSymbol::bigSymbolPreviewImage does not render properly when OuputUnit is not set to RenderMillimeters

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ x] Commit messages are descriptive and explain the rationale for changes
- [ x] Commits which fix bugs include `fixes #16866` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

See https://issues.qgis.org/issues/16866 for detailed description.

The QgsUnitTypes::RenderUnit of the Layer is being used instead of QgsUnitTypes::RenderMillimeters.
The QgsDistanceArea being used is not based on the Layer being used.

Thus when this runs, MapUnits are assumed to be in Degrees, RenderMetersInMapUnits (a value given in Meters) is transformed into degrees. So for the given 5.1 Meters: 0.00000458141 is bing used - which cannot be seen.
This seems to also to effect Icons being shown for the 'Simple marker' and in the Layer Panel.

updatepreview all original

This solution is a bit of a Hack, for reasons given in issue 16866.
I can also not determine if there are any side effects.

My assumption is that since this function uses a fixed size for the image (100x100) that this is not the case.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Here's an alternative (better?) approach:

- add a QgsRenderContext* context argument to the function, defaulting to nullptr
- if set, the function uses that context instead of making a new one
- the symbol widgets where the preview are shown have access to the map canvas. You could take the extent and scale from the canvas and use these to construct a render context in the symbol widgets and pass this to the symbol preview creation function. Then the symbol preview will show what the symbol will look like given the current canvas map settings. That should fix this issue and make any map unit symbol setting work correctly in the preview.

Sound reasonable to you?

**Comment by mj10777** [comment]
At the first glance yes, at the second no.

Assuming that **bigSymbolPreviewImage** is only being used for this Dialog, where the created image has a fixed size, using QgsUnitTypes::RenderMillimeters for:
* renderPolyline, renderPolygon and renderPoint in QgsSymbol

when the **QgsFeature** parameter = **nullptr** of the 3 functions would replace the 'hack' and show the user what they need.
The preview and the Icon need only display the relation of the multiple Single Markers over each other to help adapt the setting.

There is also the problem for the Icon display, which I have not yet found (took 2 days to find this one).

For me, there is also the other problem, that I want to complete the radical changes to the **QgsSpatiaLiteProvider** since this should get into the first QGIS 3, the deadline of which is nearing (around the 1st of August I assume). So starting tomorrow I want to concentrate on that, hoping to get it complete by the end of the week.

**Comment by mj10777** [comment]
>> when the QgsFeature parameter = nullptr
This idea did not work since QgsMarkerSymbol::renderPoint (and the other functions) call other functions which use the value returned by outputUnit().

So resetting this value during the lifetime of **bigSymbolPreviewImage** seems to be the only solution.
I am now trying the same for **drawPreviewIcon** to see if that also renders correctly.
Yesterday I only changed the value given to the created QgsSymbolRenderContext.

So I don't think your suggestion would work since all the functions being called use the set value returned by outputUnit().

---
**drawPreviewIcon** seems to draw the icon for the 'Layer Panel', but not for the images that display the 'Single Markers'

drawpreviewicon

**Comment by mj10777** [comment]
It seems that when QgsSymbolSelectorWidget::updatePreview calls QgsSymbolLayerUtils::symbolLayerPreviewIcon with QgsUnitTypes::RenderMillimeters, the OutputUnit sent is not being used in QgsMarkerSymbolLayer::drawPreviewIcon.

When, for the lifetime of drawPreviewIcon, the OutputUnit for the class is set to that value
* everything renders correctly

restoring the original value upon completion. 

qgsmarkersymbollayer_drawpreviewicon

Since the underlining functions (such as renderPoint) do **not** receive a QgsSymbolRenderContext, it cannot extract the sent value using the value returned by. 

So as long as this remains this way, the hack must remain that during updatePreview, bigSymbolPreviewImage and drawPreviewIcon the corresponding class value must be reset and restored when compleated.

**Comment by daydinodakent** [comment]
I follow nightly edition of QGIS 2.99
There are three problems in showing point features as SVG file.
1- If you try to show point features as SVG marker and give any "Rotation Angle"
2- Make SVG marker settings in "MapUnit"/"Inches"/"Meters" (more than 1000 point symbols), [in "Milimeter"/"Pixels"/"Points" units there is no problem]
3- If you zoom in more than 1:25 to SVG symbol [in "Milimeter"/"Pixels/"Points" units there is no problem]
then QGIS stop working and close.

**Comment by m-kuhn** [comment]
Is this still an issue and does this fix still apply?

**Comment by mj10777** [comment]
>> Is this still an issue

yes, since the images do not render correctly in the preview.

metersatscale


>> does this fix still apply?

Hard to say, it was a long time ago.
This was more an attempt to analyse the cause, since this is not an area that I fulling understand.

**Comment by m-kuhn** [comment]
What's the meaning of "correctly" here?
As far as I understand there is no applicable size within this preview for anything but *render in mm*. Except maybe for using the current map scale to determine the size of symbols.

**Comment by mj10777** [comment]
Well, if that is the case, then there is (other than being very user unfriendly) no problem.

The 'hack', however, did bring a usable result.

**Comment by m-kuhn** [comment]
What does the hack do exactly? Just "cast" map units to millimeters and hope its result is in a range that gives usable results? Isn't it pure luck if this provides better or worse results than the current approach?

**Comment by mj10777** [comment]
If I remember this correctly, the big and small preview images are a fixed size.
Since the preview is only to assists the user in getting the impression of what the final result will look like, temporarily setting to millimeters seemed a practical, usable solution to the problem.

Not having the full background knowledge (i.e. not knowing if this could cause problems elsewhere or another method could be used) I termed this as a 'hack', so that someone with a better overview could determine if this a usable solution.

>>  Isn't it pure luck if this provides better or worse results than the current approach?
The present solution shows no results at all (is blank).
From the original images above, the bigSymbolPreviewImage shows a usable result (which is better than blank) ; the drawPreviewIcon less so (it should be round and not square).

Since the relation is the same, when combining the symbols, between millimeter/Meters or Map-Units, the result will be correct when all  symbols use Meters or Map-Units.

If one is millimeters and the others are Meters or Map-Units may well not be correct.
The only way to correct that would be to retrieve the present resolution and convert the Meters or Map-Units to millimeters. But that is may be an overkill.

If the preview is blank, the user may assume that it does not work.
Showing a near realistic result is better than showing nothing at all.

**Comment by nyalldawson** [comment]
I keep swinging back and forth between whether this is a good "short-term" fix or not. I'm fine with a moderately hacky fix here, because a real fix is very complex, but what I'm on the fence about is whether this fix might not make things worse in certain circumstances.

I can understand it works OK if the size in map units ≃ typical mm sizes, e.g. of the range .1 -> 10. But that's quite a limited range for map units, and is only going to work ok if symbols have been designed for large scale maps where symbol sizes are 1-10 meters in map units. The danger is that users with larger map unit sizes (typical for visualising buffers), say 100m, 1000m, and greater will result in preview symbols of ridiculous sizes, and there's a chance that these extreme sizes will slow the symbol generation dramatically (or worse, crash). I've seen this before when accidentally creating symbols with extreme line widths - qpainter just chokes on them and goes all unpredictable.

So maybe what we need in this PR is to also scan the symbol sizes and then scale them to a reasonable range while we are converting them to mm sizes. E.g. find the biggest /smallest size in map units for all symbol layers in the symbol, and then scale all the sizes using this range so that they fall into a reasonable (1-10 mm?) range.

Thoughts on this approach?

I'm also going to try and see today how other applications handle this situation to see if we can draw any inspiration from their approach...

**Comment by mj10777** [comment]
> So maybe what we need in this PR is to also scan the symbol sizes and then scale them to a reasonable range while we are converting them to mm sizes. E.g. find the biggest /smallest size in map units for all symbol layers in the symbol, and then scale all the sizes using this range so that they fall into a reasonable (1-10 mm?) range.

A final solution will most probably run along this line. 

On the assumption that a place can be found where all the symbols to be rendered as one is known, checking must be done to first determine the biggest in mm.

Assumption: there can be only 1 MapUnit type in such a group, since the Raster/Geometry can have only 1 MapUnit-Type.
* even if this was not the case, a common meter value could be used

When there is a mix of mm and MapUnits in the collection:
1) determine the biggest non-MapUnit size and store the mm-value and that value as MapUnit
2) determine the biggest MapUnit size (including the the value of 1) and store the mm-value
3) calculate a relation between the preview-image size and each Symbol, the largest being 100% - the others being <= the largest
4) call the rendering for each Symbol based on the calculated value

Otherwise: call as done now

**Comment by nyalldawson** [comment]
Ping @probot

**Pull request closed without merging**
