### PR TITLE
add shortcuts to browse feature list

### PR DESCRIPTION
**Pull request by 3nids**
following @nyalldawson request in #9992

I think there is now way to add them to the shortcut manager since there might be several attribute tables. Am I right?

### CODE REVIEW

**Comment by nirvn** [comment]
@3nids , thinking of this some more; you know what you could do here? Create "dummy" global shortcuts for this pair of actions, that does nothing but shows up in the customize shortcuts dialog. Then, when you add the actual shortcuts to the attribute table, use the shortcut definition linked to those dummy actions.

**Comment by 3nids** [comment]
@nirvn this sounds interesting, although there might be some issues:
* how to properly set the parent for the shortcut (you would need to reset the parent of the shortcut, but what if there is several tables, create copies of the shortuct?)
* would there be conflicts if we define several shortcuts with the same key sequence (which could happen)?
It's a bit late and need to think a bit more about it. But this should not retain from this PR to be merged in the meantime ;)

**Comment by nirvn** [comment]
@3nids , yeah, merge this away, and let's keep thinking about this :)

**Comment by 3nids** [comment]
do you think the shortcuts are well chosen?

**Comment by nirvn** [comment]
No objection on my side.

**Comment by nyalldawson** [comment]
> do you think the shortcuts are well chosen?

Does it clash with ctrl left+right when editing text in a widget?

**Comment by 3nids** [comment]
> Does it clash with ctrl left+right when editing text in a widget?

not on Mac at least, so I'd guess the same on other platforms

**Comment by 3nids** [comment]
I added global shortcuts.

* There is a conflict with CTRL+arrow which moves the map (still available with CTRL+ALT+arrow). So seems fine to me. Still available if there is no attribute table open.
* Does not work if several attribute dialogs are open. Re-work as soon as there is only 1 again.

So I'd be in favor or merging as is now.

**Comment by nyalldawson** [comment]
I'd be inclined to change the shortcut to something more specific, and leave the "high profile" cursor keys for critical functionality. To me something like  ctrl + alt + [ and ctrl alt ] would be more appropriate (and much less likely to clash)

**Comment by nyalldawson** [comment]
Please don't use Ctrl+Alt+arrows -- they are global shortcuts under linux for window management

**Comment by 3nids** [comment]
so...what do you propose? I'd keep the former CTRL+arrows. But open to ideas.

**Comment by nyalldawson** [comment]
I'd use [ and ] . Much less chance of clashes then trying to take over the cursor keys.

**Comment by nyalldawson** [comment]
(I mean ctrl + [, or Ctrl + Alt + [)

**Comment by 3nids** [comment]
ah, sorry.
Not sure about others, but that doesn't look nice on French and Swiss keyboards.

**Comment by nyalldawson** [comment]
{ ?

**Comment by 3nids** [comment]
hehe, sadly, these are very painful (ALT+5, 6, 8 or 9).
The only other approach is to use some letters, but it's gonna be hard too (so that it stays coherent across different keyboards).

**Comment by nyalldawson** [comment]
Well... i guess users can always override them if they particularly don't like how a sequence works on their own keyboard. But I'm still dead against overriding the cursor keys, it's just asking for issues.

**Comment by 3nids** [comment]
@nyalldawson ok, done
@nirvn I finally found the way to register the shortcuts globally (from qgisapp) and using them in the attribute table.

**Pull request merged**
