### PR TITLE
[FEATURE] API call to make geometries valid (port of ST_MakeValid)

### PR DESCRIPTION
**Pull request by wonder-sk**
This introduces QgsGeometry::makeValid() which will try to make a valid
geometry out of invalid one. This is more complicated method than just
doing a buffer with zero width, but it should not loose any vertices.

Finally we should have a reliable way in QGIS to fix bad geometries!

Ported the C code from lwgeom library to QGIS.

### CODE REVIEW

**Comment by gioman** [comment]
@wonder-sk many, many... many thanks!

**Comment by mach0** [comment]
wow - sounds awesome! top commit - can't wait to try it

**Comment by luipir** [comment]
@wonder-sk great work, how about all the complex unit tests of the lwgeom?
https://github.com/postgis/postgis/tree/svn-trunk/liblwgeom/cunit
ther is plan to port them too?

**Comment by nyalldawson** [comment]
Fantastic!!

From a really brief look at the code it converts to a GEOS geometry and does the bulk of the processing using GEOS calls. But most of these seem trivial - getting and manipulating parts of the geometry. Wouldn't we be better porting all these to directly use QGIS geometry methods too and avoid the need for the GEOS conversion (which drops z/m values)? At the least the docs should mention this limitation.

In any case this is great stuff to have directly available within API!

**Comment by wonder-sk** [comment]
@luipir other unit tests in liblwgeom are not relevant (only cu_clean.c is relevant from which I have used some tests and added some more).

@nyalldawson not sure if I understand the suggestion... how would we port it directly to QGIS geometry methods if we still need various GEOS methods like Polygonize, Union, Difference or Symmetrical Difference? We could use the QgsGeos class but that would force many back and forth translations between GEOS and QGIS representations...

Regarding dropping z/m values, I have just tested and does not drop Z values (just like ST_MakeValid docs say) but it drops M values. Will add that to the docs.

**Comment by nyalldawson** [comment]
@wonder-sk 

> not sure if I understand the suggestion... how would we port it directly to QGIS geometry methods if we still need various GEOS methods like Polygonize, Union, Difference or Symmetrical Difference? We could use the QgsGeos class but that would force many back and forth translations between GEOS and QGIS representations...

Ah, i missed those. I'd fast-forwarded through the guts of the make valid and only noticed a bunch of retrieval/create collection type geos calls.

Given that it drops m we just need to be careful that make valid is NEVER called without the user's knowledge. Ie - processing algorithms should never call this automatically and it should be a separate algorithm.

**Comment by wonder-sk** [comment]
> Given that it drops m we just need to be careful that make valid is NEVER called without the user's knowledge. Ie - processing algorithms should never call this automatically and it should be a separate algorithm.

Agreed! Normal algorithms should never try to validate geometries "just in case". I can imagine that GEOS-related processing algorithms may have a convenience option to validate geometries prior to further computation, but that should be opt-in only.

**Comment by nirvn** [comment]
@wonder-sk , throwing a random thought at you: should this function be used with geometries during the labelling process (which I think does try to make bad geometries valid to be able to label those)?

**Comment by wonder-sk** [comment]
> should this function be used with geometries during the labelling process (which I think does try to make bad geometries valid to be able to label those)?

I think we can stick with the existing simple solution to do a zero buffer to fix them for labeling. The zero buffer method may not fix the geometry completely correctly, but for labeling purposes that does not matter too much and it is fast. MakeValid is a more complex slower algorithm and it is IMHO better suited for processing where robustness is more important.

**Comment by wonder-sk** [comment]
By the way, this presentation briefly covers differences between using ST_MakeValid and ST_Buffer:
http://2010.foss4g.org/presentations/3369.pdf
(pages 14-20)

**Comment by SIGISLV** [comment]
This is huge ! Many many thanks

**Comment by Gustry** [comment]
Thanks a lot Martin. We will definitely use it ;-)

**Pull request merged**
