### PR TITLE
Comments in Processing Models

### PR DESCRIPTION
**Pull request by nyalldawson**
(includes https://github.com/qgis/QGIS/pull/34852)

This allows users to create comments attached to model components (inputs, algorithms or outputs). Comments are shown linked to the associated component, and can be freely moved around the model.

(will be more user-friendly when model components can also be resized :laughing: )

Peek 2020-03-04 16-27

 Funded by Fisel + König

### CODE REVIEW

**Comment by 3nids** [comment]
Nice!
Instead of putting the comment in another box, wouldn't it be possible to show it as collapsible item in the main box or as a tooltip?
Or is there a specific reason to do like this?

**Comment by nyalldawson** [comment]
> Or is there a specific reason to do like this?

Well, the designer is an inherently visual approach to workflows, so I wanted the comments to be immediately and always visible when viewing the model. Otherwise you'd still need to "hunt around" with the mouse to find specific parts of a model...

**Comment by 3nids** [comment]
I see your points.
Maybe a global toggle for comments would be interesting?

**Comment by nyalldawson** [comment]
> Maybe a global toggle for comments would be interesting?

that's a good idea, I'll see if I can squeeze that in

**Comment by olivierdalang** [comment]
What would be really nice too (but arguably that's another feature) would be some free named/commented boxes, allowing to better visually organise and comment whole sections of the algorithm.

A few images of inspiration (taken from Grasshopper, the nicest node based algorithm editor I know of) :

image
image
image

**Comment by nyalldawson** [comment]
That's hopefully coming soon too!

**Comment by nyalldawson** [comment]
@3nids I'll defer the "hide comments" action to a follow up PR -- it's definitely coming, but triggered a refactor of some other classes and I'd rather keep that work isolated

**Review by alexbruy — APPROVED** [review]

**Pull request merged**
