### PR TITLE
[needs-docs] Organize Layer properties tabs order

### PR DESCRIPTION
**Pull request by DelazJ**
Fix qgis/qgis3_UIX_discussion#51
This is an attempt to reorganize tabs order in the Layer properties dialog. Logic (if ever) for the sequencing is available in the aforementioned issue report.
For vector layer (before/after) - for information, 3D View is placed under Diagrams (not visible on screenshot because of qt5.5 use)
image

For raster layer (before/after) - trying to mimic vector sequencing
image

### CODE REVIEW

**Comment by timlinux** [comment]
That looks good to me @DelazJ

**Comment by nirvn** [comment]
Nice. One change needed IMO: in the raster layer dialog, histogram should be located_above_ rendering. When that's done, I have no issues seeing this merged.

**Comment by DelazJ** [comment]
@nirvn Done.

**Comment by nirvn** [comment]
@DelazJ , thanks, great work.

**Pull request merged**
