### PR TITLE
 Enable display of selection tools in Attribute toolbar

### PR DESCRIPTION
**Pull request by DelazJ**
when switching tools

Found this bug when tackling #5273. In the Attribute toolbar, when you select a tool from the drop-down containing the "select features by value" tool, the selected tool (e.g select features by expression...) doesn't replace the first one in the toolbar. Always that single icon is displayed.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by DelazJ** [comment]
From my test, it doesn't seem to save the last selected tool in the settings ie, the next time I open QGIS, it's still the "select by value" which is shown by default. Any hint is welcome...

Also, from https://github.com/qgis/QGIS/blob/master/src/app/qgisapp.cpp#L2324 anyone knows why the first two cases return the same value?

**Comment by nyalldawson** [comment]
> Also, from https://github.com/qgis/QGIS/blob/master/src/app/qgisapp.cpp#L2324 anyone knows why the first two cases return the same value?

Historic reasons - it's there from when the old "select single feature" tool was dropped, and the settings needed to migrate over to the select by rectangle tool. Guess it can be removed now that we are resetting settings anyway.

**Comment by DelazJ** [comment]
@nyalldawson does it simply a need to rewrite the case sequence (0-->3) to have it fixed? Or does it require adding some logic at some place?

**Comment by nyalldawson** [comment]
FYI - the reason behind the current behavior is that I thought (i guess wrongly) that the "select by form" action was much more likely to be used, and so should always be shown. If you think this logic is wrong then this PR looks acceptable to me!

**Comment by DelazJ** [comment]
I suspected something like that. Personally, I'm more used to the select by expression than by form (couldn't recall if i ever used it except for doc purpose, although it has more and easier features afaics). Anyway I think if someone often used one tool, with this PR, he'll always have that tool at the top so it won't hurt him/her.

**Pull request merged**
