### PR TITLE
[3D/shader] light.inc.frag: Use worldView parameter instead of worldEye

### PR DESCRIPTION
**Pull request by ptitjano**
The phongFunction used in `phongDataDefined.frag` uses the
worldPosition parameter. This parameter is then used in
adsModel. However, it turns out that eyePosition is used instead of
worldView. However, the result is correct because adsModel expects the
eyePosition.

This changes ensures that the worldView parameter is used in
phongFunction and adsModel. This way, it helps avoid any confusion and
this is also how these different functions are used in the QT3D source
code.

cc @wonder-sk @NEDJIMAbelgacem @benoitdm-oslandia

### CODE REVIEW

**Review by benoitdm-oslandia — APPROVED** [review]
Thanks @ptitjano

**Review by wonder-sk — COMMENTED** [review]
I am trying to wrap my head around the changes in this PR together with #49278 ... do I understand correctly these two port upstream changes from https://github.com/qt/qt3d/commit/fb0c9421b1e172833f3ac2166b9a39bd83a8b6ef where adsModel() has been refactored to take `worldView` vector instead of `eyePosition` ? It that only code refactoring (to bring it in line with qt3d) or is it supposed to fix shading in some cases?

In either case, if an input parameter of adsModel() has been modified, then I guess also instanced.frag shader should be adapted similarly to how data-defined phong shader has been updated?

**Comment by ptitjano** [comment]
> I am trying to wrap my head around the changes in this PR together with #49278 ... do I understand correctly these two port upstream changes from [qt/qt3d@fb0c942](https://github.com/qt/qt3d/commit/fb0c9421b1e172833f3ac2166b9a39bd83a8b6ef) where adsModel() has been refactored to take `worldView` vector instead of `eyePosition` ? It that only code refactoring (to bring it in line with qt3d) or is it supposed to fix shading in some cases?

I agree this is really confusing and my first failed PR added more confusion.
The phong material was correct before my changes and these changes should not change it. This is only some refactoring to bring it in line with qt3d. I have updated the commit message to explain it. 

> 
> In either case, if an input parameter of adsModel() has been modified, then I guess also instanced.frag shader should be adapted similarly to how data-defined phong shader has been updated?
Indeed, I had forgotten to make this change. This is now fixed. 

It makes me realize that `instanced.frag` does not have any related test. I'm gonna add one.

**Comment by ptitjano** [comment]
This is ready now.

**Review by wonder-sk — APPROVED** [review]
:+1:  and thanks for adding the test!

**Pull request merged**
