### PR TITLE
Developers Map: show more descriptive info

### PR DESCRIPTION
**Pull request by gacarrillor**
As a follow-up to the "Trusted Plugin/Trusted Author" [discussion](http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Reword-quot-Trusted-Plugin-quot-gt-quot-Trusted-Plugin-Author-quot-td5334047.html) and [PR](https://github.com/qgis/QGIS/pull/5272), the `Committer: No` in the developers map seems a bit selective for me, I don't know if other contributors feel the same.

What I propose is to change 

```
Commiter: Yes  -->   Status: Core committer
Commiter: No   -->   Status: Core contributor
```
committers

This is to avoid excluding people from a group and instead acknowledging (and letting others know) what a person means for the project.

Additionally, since the contributors.json file has a `GIT Nickname` property, this PR adds a link to each dev's GIT account.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks, looks good to me.
I would propose to drop the terms **Name**  and **Status** altogether. To me this looks like stating the obvious.

**Review by m-kuhn — APPROVED** [review]

**Comment by gacarrillor** [comment]
Agreed!

**Comment by DelazJ** [comment]
Nice improvement @gacarrillor it looks indeed more inclusive than previously.  
My "dream" is that instead of being coders only map, this becomes a Core contributors map ie all those people that are parts of QGIS Core (coders, translators, documenters, bug triager, repo maintainer... ). This may require to review the status above but i think It'll be a good place to show the diversity of the Core development, display more people and it'be more inclusive. It could be a nice tool to advocate for QGIS.

**Comment by NathanW2** [comment]
Nice work. Including everyone is a big plus for me.

**Comment by m-kuhn** [comment]
I totally agree, that this map should not only be for coders but for anyone doing important work. Let's start with this list you created (who would be listed as repo maintainer?). I think everyone will need to choose exactly one of the statuses and be listed for this. Or do you think it's required that contributors can be flagged with several ones?

**Comment by rduivenvoorde** [comment]
Just a note that we had(!) in plugins.qgis.org (somewhere @timlinux  do you remember) where people could add theirselves as user. When I recently downloaded the plugins database, there appears to be a rather big table with users + locations in it...

**Comment by DelazJ** [comment]
> who would be listed as repo maintainer?

@m-kuhn Anyone who loves github more than QGIS? ;) I realize that after i sent my message.
I was thinking about a multiple flag (maybe we can limit it to 2 or 3 and i guess that contributors will pick area(s) where they are/were the most active). Should we also keep committer vs "simple contributor" status ?

@rduivenvoorde you meant http://planet.qgis.org/community-map/? I consider that map as the one for the whole community: people teaching QGIS, creating plugins, using QGIS... but not necessarily contribute directly to the Core of the project. It shows who use and where QGIS is used throughout the world. 
Btw, As an active map it could be nice to move it to a more visible place (QGIS website?) and avoid it being hidden in our blog site, do some advertising (to get more people).

**Comment by gacarrillor** [comment]
So, what shall we do with this PR?

**Comment by DelazJ** [comment]
Unless someone steps up to implement the "core contributors" map, i'd say let's merge this. It's already one step forward...

**Comment by gacarrillor** [comment]
Can this be merged? :)

**Pull request merged**
