### PR TITLE
Because testing is nicer...

### PR DESCRIPTION
**Pull request by nirvn**
## Description

Trying to resurrect spatialite tests.

### CODE REVIEW

**Comment by elpaso** [comment]
Did you remove it from blacklist? .ci/travis/linux/scripts/test_flaky.txt

**Comment by nirvn** [comment]
@elpaso , doh!

**Comment by nirvn** [comment]
Green once, let's try again.

**Comment by nirvn** [comment]
So travis was green, but on my local machine I get the following assert:

```
496:  ### Tear Down Spatialite Provider Test Class
496: ASSERT: "i.value() == handle" in file /home/webmaster/dev/cpp/QGIS/src/providers/spatialite/qgsspatialiteconnection.cpp, line 747
496: CMake Error at PyQgsSpatialiteProvider.cmake:15 (MESSAGE):
496:   Test failed: Child aborted
496: 
496: 
1/1 Test #496: PyQgsSpatialiteProvider ..........***Failed    5.96 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   5.97 sec

The following tests FAILED:
	496 - PyQgsSpatialiteProvider (Failed)
```

**Comment by nirvn** [comment]
Looking at the file path of the db connection being closed and asserting, it's empty, i.e. a connection with no path provided.

**Comment by elpaso** [comment]
@nirvn I've no segfaults with ctest nor with direct invocation from python.

**Comment by elpaso** [comment]
Let's see if it behaves ....

**Pull request merged**
