### PR TITLE
[travis] Re-enable Auth-Postgres tests

### PR DESCRIPTION
**Pull request by elpaso**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Probably a compatibility issue with ubuntugis-unstable, I remember some conflicts with postgis there.

Do you actually need postgis? If it's only connecting to the server with auth, postgresql-server might be enough.

There is also a postgis inside ubuntugis-unstable, possibly that one works better https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable/+index?field.series_filter=xenial

**Comment by m-kuhn** [comment]
Probably a compatibility issue with ubuntugis-unstable, I remember some conflicts with postgis there.

Do you actually need postgis? If it's only connecting to the server with auth, postgresql-server might be enough.

There is also a postgis inside ubuntugis-unstable, possibly that one works better https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable/+index?field.series_filter=xenial

**Comment by elpaso** [comment]
@m-kuhn unfortunately postgis is needed, or we'd need to rewrite the tests.

**Comment by m-kuhn** [comment]
@elpaso did you try the ubuntugis postgis package?

**Comment by luipir** [comment]
working on adding postgis in the docker container

**Comment by luipir** [comment]
postgis is not a problem installing on .docker/dockerfile, but I receive the following error with libxine2 1.2.6 correctly installed... investigating

The following packages have unmet dependencies:
 libopenscenegraph100v5 : Depends: libxine2 (>= 1.2.0) but it is not going to be installed
ESC[91mE: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
ESC[0mThe command '/bin/sh -c apt-get update   && apt-get install -y software-properties-common   && add-apt-repository ppa:ubuntugis/ubuntugis-unstable   && apt-get update   && apt-get install -y     bison     ca-certificates     ccache     clang     cmake     curl     dh-python     flex     gdal-bin     git     graphviz     grass-dev     libexpat1-dev     libfcgi-dev     libgdal-dev     libgeos-dev     libg

**Comment by luipir** [comment]
fail in autoremove command

root@300aa5ae84f1:/# apt-get autoremove -y python3-pip python2.7
apt-get autoremove -y python3-pip python2.7
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libopenscenegraph100v5 : Depends: libxine2 (>= 1.2.0) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by luipir** [comment]
just doing only:
apt-get autoremove -y python3-pip 
avodi the error and successfully end build

**Comment by luipir** [comment]
I hope soperseed by https://github.com/qgis/QGIS/pull/5630

**Pull request closed without merging**
