### PR TITLE
[Processing] Processing cleanup

### PR DESCRIPTION
**Pull request by volaya**

### CODE REVIEW

**Comment by volaya** [comment]
@alexbruy can you check these to see if there is any potential issue?

@rldhont I think this should not have issues for QGIS server, but if you can check, it would be great

**Comment by alexbruy** [comment]
Looks good for me

**Comment by m-kuhn** [comment]
I guess all standalone scripts using processing will as of now need to "register" all algorithm providers by importing them (like [here](https://github.com/qgis/QGIS/pull/3067/commits/bb6e302c5dc8d7723b70f9d2a50b389adc8f49bb#diff-3dd5cecbe6aed076401f51b3e7de3589R39)).
Would it make sense to have a convenience method to do these import commands so we only have to maintain one list of "core" providers instead of maintaining it in every module where this bootstrap step is used?

**Comment by volaya** [comment]
@m-kuhn yes, you are right. I have changed it to do it that way, so as to avoid circular dependencies as before, but now the initialize() method is not complete without these import (it will work, but wont find provider objects if not initialized by importing them). Do you think that creating a separate module defaultproviders.py (or something like that), and putting a method in there that makes those import would be a good design option?

**Comment by m-kuhn** [comment]
Or do the imports directly inside `initialize`?

**Comment by volaya** [comment]
@m-kuhn if done inside initialize(), that will cause a circular dependency. The issue is in the modeler provider, which needs itself to import the Processing module, in order to have the list of algorithms and execute them in a model. Before this cleanup, this was solved by having that list cloned in a separate module, but that's what i want to avoid here.

An alternative solution, which much more work i guess, would be to have a separate class for handling the algorithm list (which could also have signals when new algorithms are added and the toolbox has to be updated), and being able to import it from Processing and all providers like the modeler one, which requires using it. I guess that sounds like a bigger change, mostly like something to consider maybe for the 3.0 migration

**Comment by m-kuhn** [comment]
> An alternative solution, which much more work i guess, would be to have a separate class for handling the algorithm list (which could also have signals when new algorithms are added and the toolbox has to be updated), and being able to import it from Processing and all providers like the modeler one, which requires using it. I guess that sounds like a bigger change, mostly like something to consider maybe for the 3.0 migration

Yeah, really nice idea... And I think the impact is smaller than the impact by this pull request.

**Comment by volaya** [comment]
Then we better close this PR, since that is much more work and I guess we are not ready to tackle it now

@alexbruy any comments?

**Comment by alexbruy** [comment]
Fine for me. Maybe we can look at this in Girona

**Pull request closed without merging**
