### PR TITLE
BACKPORT 3.10 Fix delimitedtext CSVs in virtual layers

### PR DESCRIPTION
**Pull request by suricactus**
See https://github.com/qgis/QGIS/pull/37164

### CODE REVIEW

**Comment by m-kuhn** [comment]
@nyalldawson are you ok with merging that into the next 3.10 release?

https://github.com/qgis/QGIS/pull/37164

**Comment by nyalldawson** [comment]
@m-kuhn it's lead to https://github.com/qgis/QGIS/issues/38163, so no, definitely not for merge!

**Comment by m-kuhn** [comment]
CC @suricactus

**Comment by nyalldawson** [comment]
Closing pending a improved fix

**Pull request closed without merging**
