### PR TITLE
Allow clicking hyperlinks in HTML text edit widget

### PR DESCRIPTION
**Pull request by m-kuhn**
So far links were highlighted but not click- and navigatable.

### CODE REVIEW

**Comment by elpaso** [comment]
IIRC there was a problem when clicking on an hyperlink that has a mime type which is not html or text. Can you please check if that also works? I remember that I had to implement a workaround for that in identify when displaying html links.

**Comment by m-kuhn** [comment]
Like a link to an image?

`<a href="https://qgis.org/en/_static/images/qgisorg_banner30.png?t=23feb2018">QGIS Logo</a>` works

**Comment by elpaso** [comment]
Sorry, I meant a link to something which cannot be represented in the HTML widget itself (like a zipfile or a PDF).

**Comment by m-kuhn** [comment]
`<a href="http://www.pdf995.com/samples/pdf.pdf">test</a>` works as well

**Comment by elpaso** [comment]
ok, thanks for checking, the case I was referring to was actually `QgsIdentifyResultsWebView` which is based on  different widget.

**Comment by m-kuhn** [comment]
Thanks for the review @elpaso

**Pull request merged**
