### PR TITLE
Fix offline editing with gpkg

### PR DESCRIPTION
**Pull request by m-kuhn**
Up to now, all features were written twice, once with QgsVectorFileWriter, once via addFeature in a subsequent loop. Now it is only done once in a loop, because the loop needs to be done anyway to create the lookup table

### CODE REVIEW

**Comment by m-kuhn** [comment]
Nononono, you are not gonna close that. It's important!!

**Comment by m-kuhn** [comment]
Dear stale bot, do you give me a bit more time?

**Comment by signedav** [comment]
I haven't investigated a lot here. Just debugged the test.
Here no features are given back on the test with GPKG https://github.com/qgis/QGIS/pull/7909/files#diff-b90acd3440b542a2fe75ccbc2d6da692R773 and so it cannot create the offline layer. With a random test on QGIS I didn't had the problem, but I haven't tested with the same data. 

Just for info. I could investigate more...

**Comment by signedav** [comment]
Another conclusion but without a solution yet:

On a GPKG the field "fid" is created - so in the case that the original layer do not contain an "fid"-field (or at least no numerous one like in the test-shp) the command `newLayer->addFeature( f )` fails. Because of this misbehavior before the tests have been successful. But now there are no features added anymore.

In the case of there is a "fid"-field, the `newLayer->addFeature( f )` works fine, before the data have been double in the end and with the current version it works perfectly.

**Comment by signedav** [comment]
One approach would be to create a "dummy" fid on the attributes copied into the new feature, in case there is no numerous fid. This would work fine.

But found another issue. In case there is an fid, it's values are copied to the first field. Even when it's not the first field. So the values are mixed up...

**Comment by signedav** [comment]
@m-kuhn should I close this PR and make a new one with my commits on top of yours, or how can I append my commits to this branch? I'm afraid I cannot push to your branch...

**Pull request merged**
