### PR TITLE
Fix Postgis Merge selected features regression: for 2.18 fixes #15741

### PR DESCRIPTION
**Pull request by luipir**
## Description
add a geometry compatibility check before apply all stages that compose the commitChange

Commit 8d70a51 allowed to raise a limitation of the:
QgsVectorLayerEditBuffer::commitChanges [2] class (see doc [3])
commitChanges is a multi staged commit task with a limitation, each
stage, if success, clean it's stage buffer => it can't be recovered if
one of the next stages fail.

This is exactly what happen in the issue. Merge Features is done doing:

- deleted features to merge
- add the new merged feature
- stage 2 will fail (due the fact that if postgis layer is linestring, the merged is multi type => incompatible). but failing the rollback
- (done aborting the editing session) rollback only the stage 2, because
- stage 1 was success and cleaned from editBuffer.

Solutions:
There is no a unique solution. These are the options:

1. revert or partially revert the above commit 8d70a51
2. don't clean the stage buffers, and do them only if no error is found (opening to other regressions)
3. refactor editing buffer (would make sense integrating QgsTransaction and QgsTransactionGroups where possible)... but IMHO out of the scope of a bug fix
4. Check geometry compatibility before to apply commit phases

this PR apply the simplest solution 4)

[1] https://issues.qgis.org/issues/15741
[2] https://github.com/qgis/QGIS/blob/release-2_18/src/core/qgsvectorlayereditbuffer.cpp#L292
[3] https://github.com/qgis/QGIS/blob/release-2_18/src/core/qgsvectorlayereditbuffer.h#L93

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by luipir** [comment]
travis error on unrelated tests with this PR like:
test_qgsrelationeditwidget
@m-kuhn any idea

**Comment by luipir** [comment]
May I ask @mhugent to give a review of this code. It's a revert of his PR.

**Comment by gioman** [comment]
can we please merge/review this so we can test if it fixes this annoying postgis editing issue?

**Comment by luipir** [comment]
@gioman discussion about merging is done in the 3.x PR
https://github.com/qgis/QGIS/pull/4604
btw still no news from @mhugent

**Comment by alexbruy** [comment]
@luipir can you rebase against master to make Travis happy?

**Comment by luipir** [comment]
@alexbruy sure

**Comment by luipir** [comment]
backported from 3.0 also all editbuffer tests

**Comment by alexbruy** [comment]
Travis failure is unrelated

**Pull request merged**
