### PR TITLE
[FEATURE] Add 'open directory' action to right click menu for folders in browser dock

### PR DESCRIPTION
**Pull request by nyalldawson**
Allows easy navigation to a folder shown in the dock by opening the OS' native file explorer at that location.

### CODE REVIEW

**Comment by NathanW2** [comment]
YES! Win!

Do you think could do the same for file-based layers in the layer tree?

**Comment by nyalldawson** [comment]
> Do you think could do the same for file-based layers in the layer tree?

Is there a generic way to determine if a layer is file based and retrieve it's filepath from uri?

**Comment by elpaso** [comment]
@nyalldawson not sure there is: that might be something delegated to the provider but I guess that for ogr/glda it could be quite dfficult unless the library has the methods to retrieve this information. 

But, in general I think that a lot of signals for add/remove/replace raster/vector layers could be squeezed into at most 4+1 CRUD (+ replace)  signals if we were passing around (and store into the base layer class) a more structured set of information about the layer source, instead of relying to a provider-specific and a bit patchy layer uri. The same information could be used to build the menu item you were talking about.

**Review by elpaso — APPROVED** [review]
Cool!

**Pull request merged**
