### PR TITLE
Bugfix gh33203 broken link on slash

### LINKED ISSUE #33203: QGISserver wfs3 dead link in breadcrumbs path
Setting up a small QGISserver demo here:

http://qgis.zuidt.nl/cgi-bin/qgis_mapserv.fcgi/wfs3/

If I 'browse' to 'cbsgemeenten2018 items as HTML' (dutch municipalities 2018 stats):

http://qgis.zuidt.nl/cgi-bin/qgis_mapserv.fcgi/wfs3/collections/cbsgemeenten2018/items.html?

And then click on the 'cbsgemeenten2018' link in the breadcrumbs in the top of that page, I end up here:

http://qgis.zuidt.nl/cgi-bin/qgis_mapserv.fcgi/wfs3/collections/cbsgemeenten2018/

telling me: 

`[{"code":"API not found error","description":"Collection was not found"}]`

I think it should go to 

http://qgis.zuidt.nl/cgi-bin/qgis_mapserv.fcgi/wfs3/collections/cbsgemeenten2018.html?

as I'm browsing html?

### PR DESCRIPTION
**Pull request by elpaso**
Fix #33203 and add some py doc samples

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
@elpaso thanks! Just deployed this version. But I think there is still something going wrong with the urls:

http://qgis.zuidt.nl/cgi-bin/qgis_mapserv.fcgi/wfs3/collections/cbsgemeenten2018/items.html

then click on cbsgemeenten2018 in the breadcrumbs

Link in browser then contains:

http://qgis.zuidt.nl/cgi-bin/qgis_mapserv.fcgi/wfs3/collections/cbsgemeenten2018/

BUT: if you now click "cbsgemeenten2018 items as HTML" in the Links-section in that page you will go to (not double slashes before items):

http://qgis.zuidt.nl/cgi-bin/qgis_mapserv.fcgi/wfs3/collections/cbsgemeenten2018//items.html?

which brings you to the landingpage, but with a 'wrong' (long) url?

**Comment by elpaso** [comment]
mmm yes, I know what's happening :( 
Not a big issue, I just need to make this URL mangling a little more robust.

**Comment by elpaso** [comment]
@rduivenvoorde  I checked the code and I see that I've already handled that case (double slashes) but I've also added a note about Qt versions: https://github.com/qgis/QGIS/blob/master/src/server/qgsserverogcapi.cpp#L72
What QT version are you building with?

**Comment by elpaso** [comment]
I fact, I cannot reproduce this issue with 5.11.2 (I'll test 5.13.2 tomorrow).

**Comment by rduivenvoorde** [comment]
> What QT version are you building with?

Qt 5.12.5 which is apparently in Debian testing

**Comment by elpaso** [comment]
I cannot reproduce it with 5.13.2 either :( 

As I mentioned, the double slashes are supposed to be collapsed into a single slash by `url.adjusted( QUrl::StripTrailingSlash | QUrl::NormalizePathSegments );` and a particular case was made for QT >= 5.13 because I already noticed that it wasn't working correctly.

If you can build an make a quick test, can you try to remove the `#if` check on  https://github.com/qgis/QGIS/blob/master/src/server/qgsserverogcapi.cpp#L72 and always run that piece of code, and remove lines 80-82 ?

**Comment by rduivenvoorde** [comment]
@elpaso see http://qgis.zuidt.nl/cgi-bin/qgis_mapserv.fcgi/wfs3/collections/cbsgemeenten2018/items.html?

I think this works for 5.12.5 too :-)

```
QUrl QgsServerOgcApi::sanitizeUrl( const QUrl &url )
{
  QUrl u { url.adjusted( QUrl::StripTrailingSlash | QUrl::NormalizePathSegments ) };
  while ( u.path().contains( QLatin1String( "//" ) ) )
  {
    u.setPath( u.path().replace( QLatin1String( "//" ), QChar( '/' ) ) );
  }
  return u;
}

```

**Comment by elpaso** [comment]
Ok, thanks for checking, I guess we can just leave this implementation and remove the `#if`. I don't feel too bad for the few CPU cycles that might be wasted.

**Pull request merged**
