### PR TITLE
PG raster: PR comments followup

### PR DESCRIPTION
**Pull request by elpaso**
Address PR comments followup https://github.com/qgis/QGIS/pull/33685

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Thanks!

**Comment by nyalldawson** [comment]
@elpaso the original pr has broken something on Travis - master builds timeout like https://travis-ci.org/qgis/QGIS/jobs/639945018 (which is blocking the cache from being updated, leading to progressively longer pr build times). (I have no idea why prs are building but not master!!)

**Comment by elpaso** [comment]
@nyalldawson I've no idea about what to do: remove the test? 
Actually looks like it's the testdata that create the issue when adding raster constraints.

**Comment by nyalldawson** [comment]
I'm lost -- it makes no sense that it works consistently for every pr but fails for master branch. @m-kuhn @3nids ??

**Pull request merged**
