### PR TITLE
Make it possible to skip memory layer check on project close

### PR DESCRIPTION
**Pull request by wonder-sk**
In QGIS 3.4 there is the new feature that warns users about a potential data loss
when closing a project that contains memory layers. It displays the warning:

> This project includes one or more temporary scratch layers.
> These layers are not saved to disk and their contents will be
> permanently lost. Are you sure you want to proceed?"

While this is useful in general, there are various cases when this warning
is unwanted. For example, when a plugin creates memory layers by extracting data
from some custom data format (and possibly also writes changes from temporary
layers back to the data storage). In such situations the warning is very confusing
for the users who are unaware of the internals.

This commit adds a custom property "skipMemoryLayersCheck" to map layers,
so if all temporary layers have this property set to non-zero value the warning
will not show up.

layer.setCustomProperty("skipMemoryLayersCheck", 1)

### CODE REVIEW

**Comment by wonder-sk** [comment]
Also seen on stack exchange:
https://gis.stackexchange.com/questions/298112/disable-warning-that-scratch-layer-isnt-saved

**Comment by m-kuhn** [comment]
Sounds good to me.
Should this be documented in the pyqgis developer cookbook (https://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/vector.html#memory-provider) or do you have a better idea?

**Comment by wonder-sk** [comment]
Yeah it should be documented somewhere, I just don't have a clear idea what would be the best place. Probably the QgsVectorLayer API docs in the "memory" provider section. The cookbook is unfortunately getting slightly outdated so I am a bit worried to have a mixture of old docs and new docs on one page.

**Comment by m-kuhn** [comment]
The "core" API also is better indexed in search results and bundled with the source code, so if there's a good place in there like directly on QgsVectorLayer, I'd also prefer that :+1:

**Pull request merged**
