### PR TITLE
Replace V2 in API

### PR DESCRIPTION
**Pull request by jef-n**
this adds scripts/replacev2.sh that replaces all symbols containing V2 with version w/o V2 if that doesn't already exists.

After that these "duplicates" still exist:

Classes:
QgsComposerAttributeTableColumnModelV2 vs QgsComposerAttributeTableColumnModel
QgsComposerAttributeTableCompareV2 vs QgsComposerAttributeTableCompare
QgsComposerAttributeTableV2 vs QgsComposerAttributeTable
QgsComposerTableSortColumnsProxyModelV2 vs QgsComposerTableSortColumnsProxyModel
QgsComposerTableV2 vs QgsComposerTable
QgsComposerTextTableV2 vs QgsComposerTextTable
QgsLegendModelV2 vs QgsLegendModel
QgsLegendSymbolListV2 vs QgsLegendSymbolList
QgsMultiPointV2 vs QgsMultiPoint
QgsMultiPolygonV2 vs QgsMultiPolygon
QgsPointV2 vs QgsPoint
QgsPolygonV2 vs QgsPolygon

Methods:
addComposerTableV2 vs addComposerTable
legendSymbolItemsV2 vs legendSymbolItems

### CODE REVIEW

**Comment by nyalldawson** [comment]
> QgsGradientFillSymbolLayerV2 vs QgsGradientFillSymbolLayer
> QgsShapeburstFillSymbolLayerV2 vs QgsShapeburstFillSymbolLayer
> QgsSimpleLineSymbolLayerV2 vs QgsSimpleLineSymbolLayer

Try after 70eec9f?

**Comment by nyalldawson** [comment]
> QgsFeatureRendererV2 vs QgsFeatureRenderer

should be fixed now

**Comment by nyalldawson** [comment]
> QgsColorDialogV2 vs QgsColorDialog

See #3361

**Comment by jef-n** [comment]
@m-kuhn any clue on why the PyQgsRelationEditWidget test fails (and the icon noise)?

**Comment by m-kuhn** [comment]
Maybe related to the change setSelectedFeatures -> selectById?
What's the reasoning for that change anyway?

**Comment by m-kuhn** [comment]
The icon noise could be caused by 7dd53025
Images are linked into the app, not the app library.

**Comment by jef-n** [comment]
setSelectedFeatures is deprecated  and `setSelectedFeatures(ids)`  did `selectByIds(ids, SetSelection)`, but `SetSelection` is default anyway.  But it seems `choose_linked_feature` is not fired at all.

**Comment by m-kuhn** [comment]
Ah, ok :)

Was there any change to modal dialogs?

**Comment by nyalldawson** [comment]
> Maybe related to the change setSelectedFeatures -> selectById?
What's the reasoning for that change anyway?

Consistency - now all the "select features" api calls are "selectBy...", and accept the selection behaviour argument to control if features are added/subtracted/intersected with a selection.

**Comment by m-kuhn** [comment]
When I open a postgis project with this branch, the "toggle edit" button stays disabled.
The test tries to click this button. That may explain things.

**Comment by jef-n** [comment]
Hi Matthias,

On Wed, 10. Aug 2016 at 01:38:14 -0700, Matthias Kuhn wrote:
> When I open a postgis project with this branch, the "toggle edit" button stays disabled.
> The test tries to click this button. That may explain things.

Yes it does.  Thanks.

**Pull request merged**
