### PR TITLE
Fix field precision on Field Calculator.

### PR DESCRIPTION
**Pull request by ghost**
This should fix bug [#5154](https://hub.qgis.org/issues/5154)...

### CODE REVIEW

**Comment by nyalldawson** [comment]
@medspx looks like you missed running the prepare-commit script over this and #2573 . That's what's tripped the Travis indentation test failure. 

Ping me if you need assistance getting this script to work or have questions about this!

**Comment by medspx** [comment]
@nyalldawson I am sorry but I think I have used the script before commit and push. Indeed, when I launch it on the branch it says: "nothing was modified".
I just launch it from the root of the source with ./scripts/prepare-commit.sh with no argument. What am I doing wrong ?

**Comment by nyalldawson** [comment]
Prepare_commit only applies to changes which aren't yet committed. There's 2 ways to fix this after making a commit:

1. Run scripts/astyle_all, which will fix spacing for ALL files. Commit those changes and rebase to squash those spacing fixes into your original commit

Or

2. Run `git reset --soft HEAD^` to undo the last commit (while keeping the changes), then run prepare_commit, then git commit the changes back in again

After either approach you'll need to force push the updated version to this branch.

**Comment by medspx** [comment]
@nyalldawson I've made a commit that should fix the indentation problem...

**Comment by gioman** [comment]
Hi, this will also solve this http://hub.qgis.org/issues/5546 ? cheers!

**Comment by medspx** [comment]
Ok, I am closing this pull request because PR #2682 have incorporated the code I have made and it is going further than this PR. A dev with commit rights should definitively merge PR #2682 as it is a bugfix...

**Pull request closed without merging**
