### PR TITLE
[Oracle] treat 3D geometry as Z geometry, not 25D

### PR DESCRIPTION
**Pull request by troopa81**
Supersedes #51069

Advertize 3D geometries as (Multi)PointZ/(Multi)LineStringZ/(Multi)PolygonZ not (Multi)Point25D/(Multi)LineString25D/(Multi)Polygon25D

**Sponsored by Metropole Européenne de Lille**

cc @Jean-Roc

### CODE REVIEW

**Comment by nyalldawson** [comment]
There aren't any tests which need uodating? That's surprising!

**Comment by troopa81** [comment]
> There aren't any tests which need updating? That's surprising! Do we have any Oracle 3d tests in place?

Tests rely on QgsGeometry wkt export to check if we have what we expect in base. So wkt exports are [always](https://github.com/qgis/QGIS/blob/master/src/core/geometry/qgsabstractgeometry.cpp#L185) like LineStringZ not LineString25D

**Comment by troopa81** [comment]
@nyalldawson Does it look mergeable to you?

**Comment by nyalldawson** [comment]
> Tests rely on QgsGeometry wkt export to check if we have what we expect in base

I think we need some general "load this layer, check it's wkb type" tests here too. Otherwise there's nothing protecting this change and someone could roll it back in future inadvertently...

**Comment by troopa81** [comment]
> I think we need some general "load this layer, check it's wkb type" tests here too. Otherwise there's nothing protecting this change and someone could roll it back in future inadvertently...

Agreed, those will come with #51378 once merged (I wait a few days more see if @jef-n have a different opinion). Then, I'll rebase and fix the test

**Comment by Jean-Roc** [comment]
Hi @troopa81, could you please check if this PR would work with a layer also subject to #51378 (CompoundCurve and 25D) ?

**Comment by troopa81** [comment]
> Hi @troopa81, could you please check if this PR would work with a layer also subject to https://github.com/qgis/QGIS/pull/51378 (CompoundCurve and 25D) ?

Yes, it would work. This PR have been rebased on master recently (and so, on the https://github.com/qgis/QGIS/pull/51378 PR) and reuse the test to check is the detected geometry type are correct. 

So 25D CompoundCurve would be treated as CompoundCurve Z and everything would be fine

**Comment by troopa81** [comment]
@nyalldawson There are tests now covering this PR, do you agree to merge?

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
