### PR TITLE
Revert "Remove set mShortName in QgsMapLayer constructor"

### PR DESCRIPTION
**Pull request by m-kuhn**
This reverts commit d4af38be9d02bdcfff0db9559de6610a8ef4c7a6.

### CODE REVIEW

**Comment by rldhont** [comment]
Hi @m-kuhn, Why do you want to revert this commit ? Did I do something wrong ?

**Comment by m-kuhn** [comment]
See the comment on the commit: https://github.com/qgis/QGIS/commit/d4af38be9d02bdcfff0db9559de6610a8ef4c7a6#commitcomment-17184221

**Comment by m-kuhn** [comment]
And looking at the first travis results the comment was right

**Comment by rldhont** [comment]
mShortName is just for QGIS Server. I'll take a look at pal labeling test, but I think there is no relation.

**Comment by m-kuhn** [comment]
Every test since this commit failed (master and 2.14) and only this pull request here is ok again.

**Comment by rldhont** [comment]
Ok, I'll fix the test_qgspallabeling_server.py that failed

**Comment by rldhont** [comment]
@m-kuhn I have to fixed the way shortName is stored in project and read in server.

**Comment by m-kuhn** [comment]
What do you think, should we revert the commit until this is ready or is it better to disable the pallabelingserver test? At the moment travis is just giving a red light to everything :(

**Comment by rldhont** [comment]
@m-kuhn I fixed it. Do I create a PR, or push it now ?

**Comment by rldhont** [comment]
@m-kuhn I have created a PR #3022 feel free to merge it after travis validation.

**Comment by rldhont** [comment]
I think this PR can be closed because PR #3022 has been merged

**Pull request closed without merging**
