### PR TITLE
Fix OTB icon which is not render into QGIS Processing

### LINKED ISSUE #37491: Missing OTB icon in QGIS processing configuration menu
**Describe the bug**

Missing OTB icon in QGIS processing configuration menu

**How to Reproduce**

See Screenshot_from_2020-06-04_11-38-01
 
OTB icon is missing although other provider have their icon.

**QGIS and OS versions**

QGIS 3.14 and Ubuntu 18.04

**Additional context**

### PR DESCRIPTION
**Pull request by savmickael**
## Description

Fix missing icon in qgis about OTB in Processing GUI.

I have add the icon as for other provider and reduce the size of the icon to be usable in the GUI.

I think it need to be backported to 3.10 and 3.14 due to its minor impact.

Fixes #37491

### CODE REVIEW

**Comment by savmickael** [comment]
do you need action from my side for the backport ?

**Comment by savmickael** [comment]
@nyalldawson I didn't see the PR related to backport, do you need that I write them or the qgis-bot will do them?

**Comment by nyalldawson** [comment]
Hm - it should usually do them, but it hasn't in this case. Can you manually backport please?

**Comment by savmickael** [comment]
done with #37707 and #37708

**Pull request merged**
