### PR TITLE
[Bugfix] QgsVectorLayer: Read SLD Labeling

### PR DESCRIPTION
**Pull request by rldhont**
## Description
The error was:
* QgsRenderer did not exclude SLD TextSymbolzer as a rendering configuration.
* QgsVectorLayer did not well detect SLD Text Symbolizer
* QgsVectorLayer did not well read SLD Labeling produced by QgsVectorLayer

The QgsOgcUtils and QgsSymbolLayerUtils classes have to be enhanced for a better homogenized capabilities.

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by rldhont** [comment]
Hi @m-kuhn and @nyalldawson can you take a look at the code ? thanks.

**Comment by luipir** [comment]
@aaime propably you can be interested in this PR
@rldhont IMHO unit tests would be a good addition

**Comment by rldhont** [comment]
@luipir @aaime are there any SLD tests?

**Comment by aaime** [comment]
Had a quick looks, I don't pretend to have understood everything in detail, but generally speaking it seems ok. 
@rldhont  yes, there are SLDs test, what you are looking for might be ``tests/src/python/test_qgssymbollayer_createsld.py``.

**Comment by rldhont** [comment]
@aaime @luipir tests ok

**Comment by rldhont** [comment]
@luipir @aaime any objections to merge ?

**Comment by luipir** [comment]
@rldhont sorry deadline today! I can't temporally check

**Comment by rldhont** [comment]
@sbrunner can you take a look at my code about SLD TextSymbolizer reader ?

**Comment by rldhont** [comment]
@luipir @luipir gentle ping for review, thanks

**Comment by nyalldawson** [comment]
Let's merge -- no-one seems available to provide the SLD domain specific expertise, so I'll trust you on this part!

**Comment by luipir** [comment]
tnx @nyalldawson ans sorry @rldhont for my late... was in my todo list (as other tests to do for other code) :/
I agree with your evaluation

**Pull request merged**
