### PR TITLE
[processing] Add PostGIS widget wrappers

### PR DESCRIPTION
**Pull request by arnaud-morvan**
Propose comboboxes for schema and table selection in postgis related algorithms.

For this I add possibility to set metadata['widget_wrapper'] as follow : 
```
metadata={
    'widget_wrapper': {
        'class': 'processing.gui.postgis_wrappers.PostgisSchemaWidgetWrapper',
        'connection_param': self.DATABASE}}
```
Additionnal parameters are passed to the ``wrapper.createWidget`` method.

Note that I also add a PostgisConnectionWidgetWrapper that retrieve connections list at dialog creation (old system with ParameterSelection was retreiving it at processing loading, so it was impossible to use new connections without reloading QGIS). Fix #13041 

And I change connection input from ParameterSelection to ParameterString so it take connection name instead of connection index as value.

### CODE REVIEW

**Comment by gioman** [comment]
@arnaud-morvan very cool, thanks!

**Comment by fsdias** [comment]
@volaya @alexbruy

**Comment by alexbruy** [comment]
This should fix https://hub.qgis.org/issues/13041

**Comment by arnaud-morvan** [comment]
Yes, good catch, I've added a fix label in description and a link to this PR in the ticket.

**Comment by arnaud-morvan** [comment]
I've made some changes in StringWidgetWrapper, and I also observe that most of wrappers set the default value in widget in createWidget method.
This is duplicated with the base WidgetWrapper class that already set it after widget creation using the self.setValue method (common way of setting a value in the widget).

**Comment by volaya** [comment]
this looks really good. Great work!

**Comment by arnaud-morvan** [comment]
If everyone is ok, could someone merge it ?

**Pull request merged**
