### PR TITLE
Adding support for GPS UDP Connections

### PR DESCRIPTION
**Pull request by jtornero**
QGIS now is able to get NMEA sentences broadcasted through UDP.

There are some aspects of the GPS code not clear to me, mainly in QgsQGPSDetector Class. This initial patch works as expected, anyway

Best regards

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nathanw2 what should we do with this PR? is there any value here? (I suspect the fix is still valid). If no one is reviewing, should we close?

**Comment by NathanW2** [comment]
Leave it with me. If it will merge ok I see no harm at the moment

**Comment by m-kuhn** [comment]
This pull request hasn't seen attention in a long time. Closing it for now.

Opening an updated version will be much appreciated.

**Comment by anbj** [comment]
Until QGIS supports this, one solution is to use ``gpsd`` to listen to the UDP broadcast and then connect QGIS to the ``gpsd`` instance. E.g. for a UDP broadcast on port 5000:

```
gpsd [options] udp://0.0.0.0:5000
```

**Pull request closed without merging**
