### PR TITLE
Mega API break - fix QgsFeature geometry getters/setters

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR refines the QgsFeature geometry getters/setters (plus related code changes to get QGIS compiling again). All pointer based methods have been removed.

Now we have only:

```
  void setGeometry( const QgsGeometry& geom )
```

and

```
  QgsGeometry geometry() const
```

Benefits include avoiding a whole lot of tricky pointer lifetime issues, potential memory leaks, and finally closing #777, which has survived for over 9 years!...

Impacts on PyQGIS code:
- no more need for the messy `g = QgsGeometry( feature.geometry() )` workaround, just use `g = feature.geometry()` instead
- IMPORTANT: you can no longer test whether a feature has geometry using `if f.geometry():`, since QgsFeature::geometry() will _always_ return an object. Instead, use `if not f.geometry().isEmpty():`, or preferably the new method `if not f.hasGeometry():`

### CODE REVIEW

**Comment by nyalldawson** [comment]
See also https://github.com/qgis/qgis3.0_api/issues/13

**Comment by nyalldawson** [comment]
@m-kuhn ... does a party = +1 ?

**Comment by m-kuhn** [comment]
+:100:

**Comment by wonder-sk** [comment]
YES!

By the way, for not being able to use ```if f.geometry():``` idiom - maybe that can be solved both for c++  and python by providing ```operator bool``` override in c++ and/or ```__nonzero__``` override in python?

**Comment by m-kuhn** [comment]
> and/or __nonzero__ override in python?

+1, `__bool__` for python 3.

**Comment by m-kuhn** [comment]
If there are no objections, better merge it fast or either you or others will be stuck with nasty merge conflicts.

**Comment by nyalldawson** [comment]
@m-kuhn hang on, working on a related change (QgsGeometry* -> QgsGeometry in QgsGeometry... phew!)

**Comment by nyalldawson** [comment]
> By the way, for not being able to use if f.geometry(): idiom - maybe that can be solved both for c++ and python by providing operator bool override in c++ and/or __nonzero__ override in python?

Good idea. I'll explore this after merge :)

**Comment by nyalldawson** [comment]
> Good idea. I'll explore this after merge :)

Actually screw it... i'll do it now. It'll make this easier anyway.

**Comment by nyalldawson** [comment]
Ok, bonus commit added. This follow up changes all QgsGeometry methods to return QgsGeometry values, not pointers. Result: Much less chance of leaks + crashes.

**Pull request merged**
