### PR TITLE
Selective masking vectorization

### PR DESCRIPTION
**Pull request by obrix**
The goal of this pull request is to merge the work done in the QGIS enhancement proposal [#186](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/186) around the subject of the vectorization of selective masking.

For a complete history and description of the solution that has been chosen and implemented please refer to the description of the QEP and the discussion that followed.

The implementation is based on the use of QPictures, QPainterPath and the clipping feature of Qt and the vector format available to allow an implementation of selective masking that does not force the rasterization of the objects on the map.

Here are a few examples of pdfs exports done with the qgis layout exporter : 

[test.pdf](https://github.com/qgis/QGIS/files/5268013/test.pdf)
test pdf

[test2_transparency.pdf](https://github.com/qgis/QGIS/files/5268017/test2_transparency.pdf)
test2_transparency pdf

[test_label.pdf](https://github.com/qgis/QGIS/files/5268021/test_label.pdf)
test_label pdf

[test_label2.pdf](https://github.com/qgis/QGIS/files/5268022/test_label2.pdf)
test_label2 pdf

Known issues : 

* To support some of the transparency effects that were available in the rasterized version of selective masking, some parts of the rendering process had to stay rasterized. This can lead to the appearance of pixelated area or graphical artefacts when an output vector map is zoomed in.

* Svg export is not supported. QSvgGenerator used by qgis does not support the clipping feature of svg, which is needed for masking. A possible workaround is to export to pdf and then use a third party tool such as inkscape to export to SVG.
* Some effects suche as outer glow effects on masks are not properly supported. The range of their effects are outside the limit of the masking symbol which do not play well with the way the composition do hard clips on symbol layers.

### CODE REVIEW

**Comment by haubourg** [comment]
@obrix there is one test failing, any idea?

**Comment by obrix** [comment]
@haubourg Yes I tried to fix it with my last commit without success. There is a small difference (some pixels) between one of the render generated by the CI and the render generated and saved on the repository as the target render. It makes the selective masking test fail. I'll look into it again soon.

**Comment by haubourg** [comment]
@nyalldawson do you think we can go to a merge here or is there more work to do?

**Comment by vpicavet** [comment]
Would someone be available to do a review for this soon ?

**Comment by strk** [comment]
I plan to review this shortly

**Comment by strk** [comment]
I've rebased this branch on top of the current develop. @obrix should I push my rebased branch to my fork and create a new PR to replace this one ?

**Comment by obrix** [comment]
> 
> 
> I've rebased this branch on top of the current develop. @obrix should I push my rebased branch to my fork and create a new PR to replace this one ?

Yes if you feel there is work to do on top of what's been done here and you want to do it, you can probably open a new PR : ) Thank you for looking into it.

**Comment by strk** [comment]
I've opened PR #43205 to replace this one. The only work done at this time has been rebasing to current master and resolving conflicts. I'm closing this one as depreacated by the latter.

**Pull request closed without merging**
