### PR TITLE
Add required dependencies' packages in the INSTALL file (small pull request)

### PR DESCRIPTION
**Pull request by mangelats**
## Description
Added 2 dependencies (`python3-owslib` and `python3-pygments`) to the list in `INSTALL` file so other people installing from master will already have them. I checked the packages' name in the different distributions.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by DelazJ** [comment]
@copying As mentioned in https://github.com/copying/QGIS/blob/097f847c73c0db57e7c1baa5018c38c1a65a028d/INSTALL#L77 you (also) have to make the changes in doc/INSTALL.t2t (in this case, linux.t2t) file

**Comment by copying** [comment]
Sorry about that. I read that a few months ago but didn't remember about it. Now it should be fixed.

**Comment by DelazJ** [comment]
No problem. You are not the first one. I think that Most of the contributors to this file have already fallen into that trap :)

**Comment by copying** [comment]
I'm closing the commit because, for some stupid reason, I requested the pull from my master. Also, I feel it won't get merged.
If anyone needs the packages names, it's not hard to find them.

One pull request less in the list :)

**Comment by jef-n** [comment]
@copying BTW the package list is updated by [scripts/scandeps.pl](/qgis/QGIS/blob/master/scripts/scandeps.pl)

**Comment by copying** [comment]
@jef-n Oh, OK. So it even makes more sense to close this pull request.

**Pull request closed without merging**
