### PR TITLE
[GUI] Remove italics and use monospaced font for expression fields in the attribute table. Related to issue #44638 

### PR DESCRIPTION
**Pull request by lanckmann**
## Description

This pull request modifies the display of expression fields in the attribute table in QGIS to replace the default italic font with a regular monospaced font. This improves readability and ensures visual consistency throughout the interface.

### Main Changes:
- Updated the `QgsFieldExpressionWidget::updateLineEditStyle()` method to disable the italic style and use a monospaced font.
- Addressed issue #44638 that reported readability challenges caused by italicized fonts in expression fields.

This improvement aims to make the expression fields easier to use by making the text clearer and consistent with other parts of the interface.

### Additional Notes:
- This PR has been built and tested successfully.
- No new unit tests were added, as the change mainly affects the user interface.

Please review these changes and let me know if you have any comments or suggestions for improvement.

### Screenshots

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
@lanckmann can you undo all the formatting changes here? There's a test on ci to ensure standard code formatting which will fail because of these changes

**Comment by lanckmann** [comment]
@nyalldawson  hey, I am still encountering the following error during  the build  "Windows Qt6 / build (windows) (pull_request)" step. The error message is as follows: "Error: EPERM: operation not permitted, stat 'C:\src\py-gpep517\src\v16-72079505dc.clean\test\integration\flit_core\testpkg'
It seems that there is a permission issue accessing the specified path, which is preventing the build from completing successfully.
Could you please help identify the cause of this problem or suggest possible solutions?

**Review by m-kuhn — APPROVED** [review]
Sounds like a good improvement

**Comment by nyalldawson** [comment]
@nirvn you had thoughts here, didn't you?

**Pull request merged**
