### PR TITLE
Return false on commit failure from QgsOgrProvider::changeGeometryValues

### LINKED ISSUE #32144: False success from ogr provider's committChanges
Spinoff of https://github.com/qgis/QGIS/pull/31980#issuecomment-538909172

Basically, this snippet of tests/src/python/test_provider_ogr_gpkg.py:

       # Commit changes
        cbk = ErrorReceiver()
        vl.dataProvider().raiseError.connect(cbk.receiveError)
        self.assertTrue(vl.commitChanges())
        self.assertIsNone(cbk.msg)

It passes the first assert (commitChanges( ) returns true) but does not pass the second (no error is printed).

### PR DESCRIPTION
**Pull request by strk**
Fixes #32144

### CODE REVIEW

**Review by rouault — APPROVED** [review]

**Comment by strk** [comment]
Now to think about a testcase to secure this fix. What's a good reason for ::changeGeometryValues to fail committing ? Change file permission _after_ opening it ? (I stumbled upon this issue while playing with `walForSqlite3` but it'd be better for a test to be immune from that setting, which has its problems)

**Comment by strk** [comment]
@rouault sorry I pushed another two changes handlng returns from commitTransaction, can you take another look ?

**Comment by rouault** [comment]
> can you take another look ?

look fine.

> What's a good reason for ::changeGeometryValues to fail committing ?

Good question. I just tried to delete a sqlite file when a transaction was opened, but the commit succeeded !!! (just playing with command line sqlite3). This was in default journaling mode (not WAL)

**Comment by rouault** [comment]
@strk Are you considering trying to add tests ? or should it be merged as it ?

**Comment by strk** [comment]
I'm out of ideas as per generating a testcase so I'd say let's merge as-is.
Rather, do you think this should be backported @rouault ?

**Comment by strk** [comment]
Well, marking for backport

**Comment by strk** [comment]
Manual backport for 3.4 branch is in https://github.com/qgis/QGIS/pull/32198

**Pull request merged**
