### PR TITLE
Correct install_name_tool paths for macos

### PR DESCRIPTION
**Pull request by jctull**
Correct install_name_tool paths for linking frameworks correctly and without throwing errors.

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by kyngchaos** [comment]
what errors are you getting?  the current code should work without errors, there are symlinks in the framework at each level to get to the correct binary file.  if you want to avoid symlinks, you need to use the actual version number folder that “current” points to.

**Review by dakcarto — COMMENTED** [review]
As William mentions, the existing code should work, and if the changes you suggest are needed they should include the actual major version component.

Please provide error description.

**Comment by jctull** [comment]
The problem was that the paths were not correct, so the frameworks were not being linked in the post-install command. This was installing trunk from source, so maybe something changed in 2.99 that breaks this link step. Not sure, just know that this fixed it for me.

**Comment by jctull** [comment]
Here is what happens on the 'make install' step when building trunk. It appears there are some additional paths that need to be corrected as well, but I have not tried to work through all of this yet:

-- Updating QGIS library paths...
-- Copying Qt frameworks...
ditto: can't get real path for source '/usr/local/Cellar/qt/5.9.2/plugins/codecs/libqcncodecs.dylib'
ditto: can't get real path for source '/usr/local/Cellar/qt/5.9.2/plugins/codecs/libqjpcodecs.dylib'
ditto: can't get real path for source '/usr/local/Cellar/qt/5.9.2/plugins/codecs/libqkrcodecs.dylib'
ditto: can't get real path for source '/usr/local/Cellar/qt/5.9.2/plugins/codecs/libqtwcodecs.dylib'
ditto: can't get real path for source '/usr/local/Cellar/qt/5.9.2/plugins/phonon_backend/libphonon_qt7.dylib'
-- Copying Qwt framework and updating library paths...
-- Found QCA plugin directory: /usr/local/Cellar/qca/2.1.3_1/lib/qca-qt5
-- Updating QCA plugins with QCA library path in /usr/local/Cellar/qca/2.1.3_1/lib/qca-qt5 ...
-- PYTHON_MODULE_PATHS to be searched:
--   /usr/local/Cellar/sip/4.19.5/lib/python3.6/site-packages
--   /usr/local/lib/python3.6/site-packages
-- Copying sip...
-- Copying PyQt...
--   PyQt4 module Qt.so not found
--   PyQt4 module QtCore.so not found
--   PyQt4 module QtGui.so not found
--   PyQt4 module phonon.so not found
--   PyQt4 module QtXml.so not found
--   PyQt4 module QtNetwork.so not found
--   PyQt4 module QtScript.so not found
--   PyQt4 module QtSvg.so not found
--   PyQt4 module QtSql.so not found
--   PyQt4 module QtWebKit.so not found
--   PyQt4 module QtXmlPatterns.so not found
--   PyQt4 module QtDBus.so not found
--   PyQt4 module QtMultimedia.so not found
--   PyQt4 module QtOpenGL.so not found
--   PyQt4 module QtTest.so not found
--   PyQt4 module Qsci.so not found
cp: /PyQt/uic: No such file or directory
ditto: can't get real path for source '/pylupdate4'
ditto: can't get real path for source '/pyrcc4'
sed: /pyuic4: No such file or directory
-- Updating Qt library paths...

**Comment by jctull** [comment]
Now running the bundle setting on 0, the library path updates worked fine. This is a different machine than I used the other day. I'll close this, though there do appear to be some issues to work through for bundling qt5, probably due to qt5 changes though.

**Pull request closed without merging**
