### PR TITLE
Stop polluting filesystem (replay)

### PR DESCRIPTION
**Pull request by strk**
This is a re-proposition of PR GH-57606 after all commits in that PR were [reverted](https://github.com/qgis/QGIS/pull/57606#issuecomment-2190287303)

This PR addresses the problem reported by @nyalldawson in https://github.com/qgis/QGIS/pull/57606#pullrequestreview-2143615942 (reportedly causing a segfault on his system)

### CODE REVIEW

**Review by nyalldawson — CHANGES_REQUESTED** [review]
This still has issues @strk. You don't check to see if that folder exists anywhere, neither is it ever cleaned up. You're trading proper operating system temporary file handling for storing everything in some custom location which is NEVER cleaned up.

**Comment by strk** [comment]
> This still has issues @strk. You don't check to see if that folder exists anywhere, neither is it ever cleaned up. You're trading proper operating system temporary file handling for storing everything in some custom location which is NEVER cleaned up.

Given CI is green, may I ask you to give more details about what fails ? Note I filed at least [14 tickets](https://github.com/qgis/QGIS/issues?q=is%3Aopen+is%3Aissue+label%3Atestsuite+author%3Astrk) about non-working testsuite when run locally but most of the times those issues are disregarded because "CI works!".  I'm happy to improve offline testsuite experience but I need more details about what is not working for you.

So: how exactly those missing checks break the run for you ? Could you see a way to encode those situations in the CI so I can get a red here instead of a green ?

**Comment by benoitdm-oslandia** [comment]
Hi, as we are building qgis on a mutliuser basis on the same big-cpu-ram server, we encounter issues with the mixed up of temp files in the /tmp. As our different users build different branches, we cannot use the same user for everyone. And tests fail due to conflicts on the files generated by tests owned by different users. 

Do you have some updates about the last remaining issues? Do some tests are still failing?

Regards

**Comment by strk** [comment]
It's a pity to close this PR only because neither @nyalldawson  nor me found the time yet to provide a test showing the problem reported by Nyall. The CI is green while we want it to be RED to show the problem. Wasn't there a way to ask stalebot to not get in the way ?

**Comment by strk** [comment]
> You don't check to see if that folder exists anywhere,

I believe the functions used to create temporary directory create the target if non-existing, wouldn't CI be red if this was not the case ?

> neither is it ever cleaned up.

This is already the case before this PR, the only difference is that all that mess is left in the system shared /tmp directory rather than in the build tree. I agree it is a problem but is a problem that needs to be addressed by each test leaving temp files behind (not all tests do).

>  You're trading proper operating system temporary file handling for storing everything in some custom location

It's the build directory, it is already used to store build artifacts. These temporary files are the same. I agree things could be further improved and it would be easy to wipe out the whole temporary directory at the end of the ctest run but as we're not talking about a problem introduced by this PR I'd rather merge the improvement and further improve later instead of letting this opposed by stalebot and letting it fade out.

**Comment by nyalldawson** [comment]
@strk you didn't actually fix any of the issues I've explicitly outlined.👎 I'm out of patience and time for dealing with this, and am muting this issue now. I'll leave to others to carefully review and confirm that my issues have been resolved before they take the response to merge.

**Comment by benoitdm-oslandia** [comment]
Hi @strk, to go forward on this issue I created a [PR](https://github.com/qgis/QGIS/pull/58457) (but I forgot to mention this PR in mine). I fixed some of the hardcoded '/tmp/' but I did not changed the CMake build. 

Now, it is possible to sandbox the test runs in a specific directory by modifying the `TMPDIR` env var.

Regards.

**Comment by benoitdm-oslandia** [comment]
linked to https://github.com/qgis/QGIS-Documentation/pull/9208

**Comment by benoitdm-oslandia** [comment]
sorry @strk as said above the hard-coded tmpdir were already fixed [here](https://github.com/qgis/QGIS/pull/58457).

**Comment by strk** [comment]
> sorry @strk as said above the hard-coded tmpdir were already fixed [here](https://github.com/qgis/QGIS/pull/58457).

Yeah, on a closer look I found that the left-over hard-coded /tmp/ are protected by debug macros, probably not worth fixing them at the moment.

What do you think about using the build dir to store the temporary files ? If we do so we may wipe out the directory at test start (as a fixture). I don't see two concurrent builds using the same build dir, which should also resolve your multi-user issue

**Comment by benoitdm-oslandia** [comment]
It seems it is better not to bother with the cmakelist ... so I started to prefix my command lines with `TMPDIR=/tmp/my_test_dir` to isolate my test runs. It is not as inconfortable as it looks and it does the job.

**Pull request closed without merging**
