### PR TITLE
[ui] Revamp the symbol selector preview / layer tree / buttons

### PR DESCRIPTION
**Pull request by nirvn**
## Description
This might be seen by a few as a mini revolution :wink: 

I've been thinking for a while now that a bit of moving around in the symbol selector UI could lead to a better UX. This PR is an attempt at that. 

Basically, the row of buttons (add layer, remove layer, lock color, duplicate, move up, move down) is relocated to the right of the layer tree widget and distributed vertically. This gives us 55 extra pixels (visualized in green highlight in the screenshot below), which is one extra preference row made visible for many symbol layer type. 

While reworking things, I've also moved the symbol preview to be at the left end of the symbol selector UI, which IMHO works better when "entering" into a symbol through the style panel or layer properties window, since most of us read from left to right. 

Before (left) vs. PR (right):
image

Thoughts? 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
I forgot one UI/UX point: the revamping also makes the up / down buttons vertically staked, which is visually much better.

**Comment by NathanW2** [comment]
How does it go when the panel is not a wide?

**Comment by wonder-sk** [comment]
Looking good to me... +1

**Comment by nirvn** [comment]
@NathanW2 , IMHO working just fine:
image

Bottom line here: the reorganized top portion doesn't have a minimum width that isn't the minimum width of other parts of the style panel (for e.g. layer rendering options).

**Comment by NathanW2** [comment]
Yep looks good.

**Comment by nyalldawson** [comment]
@nirvn 

One concern I have here is that I often find that nested symbols (even simple ones, like a marker line) result in the symbol tree extending quite wide and truncating a lot of content, even on the current list width. 

I think we could alleviate this (and also improve browser) by reducing Qt's default quite-wide nesting padding. I think we need to call setIndentation on the treeview using a (font-size-dependant) value which is much narrower, e.g. the width of a 1 or 2 "X" characters. Thoughts?

**Comment by nirvn** [comment]
@nyalldawson , sounds like something worth trying. 

I'll also update the ui file to change the preview widget to be of fixed width, that way increasing the width of the style panel will increase width of layer tree widget.

**Pull request merged**
