### PR TITLE
Because OK is neither spelled ok nor Ok

### PR DESCRIPTION
**Pull request by DelazJ**
refs https://github.com/qgis/qgis3_UIX_discussion/issues/19
I think I've caught all the OK in GUI (and more, especially in comment and doc string but most of the ok/Ok are used as parameter).

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by 3nids** [comment]
Have you tried to add it to spelling.dat? I think that it should handle case fixes.

**Comment by DelazJ** [comment]
no I didn't. I was afraid it complained about all the other ok or Ok occurrences which are functions values or variables. Do you mean I can add `ok:OK` and `Ok:OK` to spelling.dat?

**Comment by 3nids** [comment]
Indeed that would mean renaming also arguments which would be bad.
Another thing: should we worry about losing translations due to a minor change here? If yes, is there a workaround?

**Comment by DelazJ** [comment]
Given the few number of translation strings (<10) that are concerned, I wouldn't worry about losing them, honestly.

**Pull request merged**
