### PR TITLE
[Processing]Add gdal_retile.py and gdal2tiles.py algorithms

### PR DESCRIPTION
**Pull request by ghost**
This should fix [Redmine #3331](http://hub.qgis.org/issues/3331).

There is only a directory output for those two algorithms because they are producing lots of files as tiles.

### CODE REVIEW

**Comment by alexbruy** [comment]
Seems Retile algorithm does not allow to customize GDAL command, corresponding field is empty. Is it intentional or just missed?

**Comment by medspx** [comment]
@alexbruy 

I am sorry but I don't know what you mean by the customization of the GDAL command. Is it the "GDAL/OGR console call" ? If this is the case, as far as I can see, this QTextEdit is not editable in any of GDAL Processing algorithms...

The content of this QTextEdit only appears whenever all (well nearly all) non optional parameters are set (perhaps have I made a mistake in the parameters definition).

**Comment by alexbruy** [comment]
Yes, I mean "GDAL/OGR console call". Asked because gdal2tiles algorithm generates corresponding command, while with Retile algoroithm this textbox is empty

**Comment by volaya** [comment]
@alexbruy The issue is not in the algorithm, but in the GdalAlgorithmDialog class. It's caused by the multiple input raster parameter, which is not handled correctly. I will merge this and then fix that

thanks for your work @medspx !

**Pull request merged**
