### PR TITLE
add unit tests for sql injection

### PR DESCRIPTION
**Pull request by pblottiere**
The aim of this PR is to add some unit tests to check that requests with SQL injections are well rejected by the server. 

Injections currently tested:
- stacked queries
- time-based blind attack
- and-based blind attack
- union based attack
- unicode
- pattern matching

Requests tested:
- WMS / GetFeatureInfo / FILTER
- WMS / GetMap / SLD
- WFS / GetFeature / FILTER (EXP_FILTER)

For WMS tests, if the sanity check is deactivated (https://github.com/qgis/QGIS/blob/master/src/server/services/wms/qgswmsrenderer.cpp#L1850), most of these injections are working.

Let me know what you think and if you have more tests in mind.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Very nice!

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
Thanks @pblottiere

**Comment by pblottiere** [comment]
@rldhont Please do not merge yet, I have more tests to come.

Thank you

**Comment by m-kuhn** [comment]
Good job, thanks @pblottiere 

I'm wondering if someone has already considered to use QgsExpressions for filtering the request instead of setting a subset string. Wouldn't this inherently be safer and also more portable?

Or would that miss some required features like joins on other db tables?

**Comment by nyalldawson** [comment]
> I'm wondering if someone has already considered to use QgsExpressions for filtering the request instead of setting a subset string

Yep, me for one! I think though we probably need to keep the native filter support too. So I've been thinking of a switch to flick between QGIS expressions (the new default) and provider side filter...

**Comment by m-kuhn** [comment]
> Yep, me for one! I think though we probably need to keep the native filter support too. So I've been thinking of a switch to flick between QGIS expressions (the new default) and provider side filter...

sounds good, on server level, project level or even more fine-grained?

**Comment by nyalldawson** [comment]
Layer level. Although to clarify.... This is just thoughts, I've no plans at the moment to actually code this.

**Comment by pblottiere** [comment]
> I'm wondering if someone has already considered to use QgsExpressions for filtering the request instead of setting a subset string. 

I think QgsExpressions are already used in the WFS GetFeature request with the EXP_FILTER parameter (and with FILTER by converting XML in expressions). So, indeed it could probably be done within the WMS requests too...

> Wouldn't this inherently be safer and also more portable?

If the *compileExpression* setting is true, then expressions are resolved on database side,so it won't be safer. And if it's set to false, then everything would be resolved on server side, so it won't be very efficient...  However, I'm not very at ease with the internal functioning of QgsExpression, so I'm maybe saying is a nonsense here...

**Comment by rldhont** [comment]
Expression filter is not supported in WMS only in WFS.

**Comment by m-kuhn** [comment]
> If the compileExpression setting is true, then expressions are resolved on database side,so it won't be safer.

Only a subset of the SQL syntax is supported by expressions and even less compiled. But I think it's the subset which is 1. interesting for filtering and 2. doesn't allow malicious actions (because it doesn't modify data).

**Comment by pblottiere** [comment]
> Only a subset of the SQL syntax is supported by expressions and even less compiled. But I think it's the subset which is 1. interesting for filtering and 2. doesn't allow malicious actions (because it doesn't modify data).

OK, thank you for the explanation!

**Comment by rldhont** [comment]
@pblottiere can be merged ?

**Comment by pblottiere** [comment]
@rldhont I've just added some new tests based on pattern matching. I think this PR is ready to be merged.

**Pull request merged**
