### PR TITLE
Correct crash when read from ogr file in thread (QgsProcessing for instance)

### PR DESCRIPTION
**Pull request by troopa81**
## Description

Fixes [#20581](https://issues.qgis.org/issues/20581)

It corrects only the first part of the issue (the ogr file read, not the python print).

The problems is quite identical but the solution should be different. When a qgis processing algorithm open, read and close a qgsvectorlayer, it finished to kill a QTimer from its running thread but the QTimer belongs to main thread. When the timeout reach the 60 seconds it crashes. I just deleteLater the object who own the timer, so the destruction is made in the main thread.

The test is quite ugly (and has to wait for 60s timeout) but I don't know how to do better.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by elpaso** [comment]
@troopa81 did you try to make the test class a friend class of the connectionpool and connect to the timer to stop it? 
Not sure if you can access the connection pool from the layer->dataProvider() though.

**Comment by troopa81** [comment]
I push a correct proposal for the python print problem. I can try to write a test if you think the solution is OK

**Comment by troopa81** [comment]
@elpaso Not stoping it because it crashed on timeout but maybe I can change the interval with a friend method. I'll try

**Comment by troopa81** [comment]
@elpaso Actually, it was not possible to get the timer. To get the timer, we need to get the QgsOgrConnPool instance. But this one differs from the one use in the plugin libogrprovider.so and the one statically linked.

So, I replace the one minute wait with a handler on Qt warning message. Indeed, Qt prints out a message before it crashes because we try to stop the timer from another thread.

**Comment by nyalldawson** [comment]
@troopa81 
> To get the timer, we need to get the QgsOgrConnPool instance. But this one differs from the one use in the plugin libogrprovider.so and the one statically linked.

I've hit this in the past when wanting to add unit tests for this class. I think a possible approach here would be to add a method to QgsOgrProvider which returns the instance of the connection pool accessible to the provider, and use that instance in tests.

**Comment by nyalldawson** [comment]
Can I suggest that https://github.com/qgis/QGIS/pull/8988/commits/f12c9497992b8c6ab097755eccc1248f535de5e0 is pulled out into its own PR for separate discussion? I feel like there should have been more discussion/cheers regarding this commit, and i suspect that many devs are unaware of it as it's included in an unrelated PR.

**Comment by troopa81** [comment]
> I think a possible approach here would be to add a method to QgsOgrProvider which returns the instance of the connection pool accessible to the provider, and use that instance in tests.

A method that returns the instance from the singleton ? But it would be still two different instance (I tried to be sure). 

> Can I suggest that f12c949 is pulled out into its own PR for separate discussion? I feel like there should have been more discussion/cheers regarding this commit, and i suspect that many devs are unaware of it as it's included in an unrelated PR.

OK

**Comment by troopa81** [comment]
Python print problem : https://github.com/qgis/QGIS/pull/9019

**Pull request merged**
