### PR TITLE
[FEATURE] New processing algorithm "minimum bounding geometry"

### PR DESCRIPTION
**Pull request by nyalldawson**
This algorithm creates geometries which enclose the features from an input layer.

Numerous enclosing geometry types are supported, including bounding boxes (envelopes), oriented rectangles, circles and convex hulls.

Optionally, the features can be grouped by a field. If set, this causes the output layer to contain one feature per grouped value with a minimal geometry covering just the features with matching values.

This relates to discussion in https://github.com/qgis/QGIS/pull/5106:

>> @lbartoletti  Possible improvement:

>> Create a global processing tools for the minimum bounding geometry like ArcGis. Also, maybe all ?
>> these algorithms must be in the same category (Vector general or Vector geometry)?

> @nyalldawson
>What I've been thinking we should do is:

>Have separate algorithms for each of these bounding geometry methods which operate solely feature by feature. So a "minimum oriented rectangle", "minimum enclosing circle", "convex hull", "bounding boxes" algorithms. These can be QgsProcessingFeatureBasedAlgorithm subclasses, since they all would operate feature-by-feature (bringing the many potential future benefits of inheriting from QgsProcessingFeatureBasedAlgorithm).

> Have a single "minimum bounding geometry" algorithm. Like the ArcGIS alg, this would give a choice of the bounding geometry type (convex hull/rotated rect/enclosing circle/etc). There'd be an optional "group by field" setting too (if not set -> create minimum geometry for the whole layer, if set, create geometries for each group of matching features).

This is the first step to that plan - implementing the unified "minimum bounding geometry" algorithm. If accepted, I'll cleanup the other algs to remove the redundant options and make them QgsProcessingFeatureBasedAlgorithms.

### CODE REVIEW

**Comment by nirvn** [comment]
If you add non-oriented rectangles, you might be able to merge the vector / raster layer bounding box into one? If someone then needs a selected feature only option, he/she would go for the unified vector alg?

**Comment by nyalldawson** [comment]
> If you add non-oriented rectangles, you might be able to merge the vector / raster layer bounding box into one? If someone then needs a selected feature only option, he/she would go for the unified vector alg?

My thoughts exactly. And the non-oriented rectangles are there, they are just called "Envelope (Bounding Box)"

**Comment by nyalldawson** [comment]
> If you add non-oriented rectangles, you might be able to merge the vector / raster layer bounding box into one? If someone then needs a selected feature only option, he/she would go for the unified vector alg?

Ok, done

**Comment by lbartoletti** [comment]
Great!

When I wrote the algorithm for the OMBB I proposed to filter only by the minimum area. ArcGis also offers the minimum width. Maybe we can include it too?

**Comment by nyalldawson** [comment]
> @lbartoletti
> When I wrote the algorithm for the OMBB I proposed to filter only by the minimum area. ArcGis also offers the minimum width. Maybe we can include it too?

That should be trivial to add. (Add a new enum option to QgsGeometry with MinimumArea/MinimumWidth/(MinimumHeight?), Add it to the function signature and modify the line which checks if the new candidate is better). 

I wonder how often this option is used, but in any case it'd be good to have feature parity with ArcGIS' algorithm.

**Comment by nirvn** [comment]
@nyalldawson , just tested it, working really well.

**Comment by alexbruy** [comment]
Thanks!

**Pull request merged**
