### PR TITLE
[QgsQuick] Value relation widget

### PR DESCRIPTION
**Pull request by sklencar**
Added a widget for value relation field in QgsQuickFeatureForm.

### CODE REVIEW

**Comment by m-kuhn** [comment]
I wonder if it could be done by just having the configuration parsed a bit different but in the same widget. Did you think about this approach?

**Comment by sklencar** [comment]
Yes, I was thinking of having a generic combobox for both QgsQuickValueRelation and QgsQuickValueMap just with different configuration. It sounds better, so I will update the PR soon.

**Comment by elpaso** [comment]
Forgive the dumb question: will it support drill-down like the desktop counterpart?

**Comment by sklencar** [comment]
@elpaso It will not be supported at this point :/

**Pull request merged**
