### PR TITLE
Master32.spatialite provider

### PR DESCRIPTION
**Pull request by mj10777**
## Description
QgsSpatiaLiteProvider reorginised for Spatialite 4.5.0, RasterLite2 and Topology

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

This pull request will correct many known problems and prepare the QgsSpatiaLiteProvider to deal with the many changes in the upcoming Spatialite 4.5.0 with RasterLite2, Topology and SE/SLD Style support.

The present approach, to simply list TABLEs and VIEWs that contain Geometries is no longer practicable, since many of the Administration TABLEs also contain geometries which normally should never be displaced.

Also the interdependence between Layers (Vector and Raster) with Styles and other information contained in the Database, calls for a different approach to the problem, so that all of the capabilities being offered by Spatialite 4.5.0 can be fully utilized.

---

This is a re fractured version based on master of 2017-11-17, after the switch to spatialite 4.2.0.
When needed, a spatialite/rasterlite2 connection is started using the 'load_extension' logic of sqlite3, which has been supported since Spatialite 4.2.0. There is no needed for extra memory to be reserved for a Spatialite/RasterLite2 connections, since this all dealt with from within 'mod_spatialite/rasterlite2'.
The source dependency for RasterLite2 has been removed, since after  'mod_rasterlite2' only sql-queries are used.

Full implementation of **QgsLayerItem** for QgsBrowser has been added.

All needed information can be gathered **without** a Spatialite/Rasterlite2 connection, avoiding the problem of the maximum 64 connections allowed at one time.

For this to work correctly, i.e. avoiding double entries, code must be added to the gdal/ogr versions of **dataItem** to skip files supported by Spatialite/RasterLite2. A part of the process is to read the Magic-Header to determine if it is a sqlite3 file, but also if the Magic-Header is of a file type that is **not** supported by any Provider (such as executable's, libraries etc.) and therefore can be skipped by gdal/ogr.  The whole process becomes noticeably swifter.

Full implementation of **QgsLayerMetadata**, but due to a lack of support (at present) in **QgsDataProvider** cannot be read in by **QgsVectorLayer** and **QgsRasterLayer** during **setDataProvider**.

As an experiment, I added to **QgsDataProvider**:
*     QgsLayerMetadata mLayerMetadata;

with corresponding **setLayerMetadata** and **layermetadata()** and in the **setDataProvider** functions:  
* setMetadata( mDataProvider->layermetadata() );

All of the Metadata showed up properly both in the standard Layer-Properties as well as in the **QgsLayerItem** properties.

---
**spatialite_database_unique_ptr**
* is not used (everything needed is done in the **QgsSqliteHandle** class).

It is advised to switch to the **load_extension** logic, removing the need of **mSpatialiteContext** and
* spatialite_alloc_connection
* spatialite_init_ex

and later:
* spatialite_cleanup_ex

**Crucial** is, however, that **PRAGMA foreign_keys = 1** be executed **before** a spatialite connection is made, enabling Foreign Key constraints.

---

For this three new classes have introduced
* **SpatialiteDbInfo** 
   * a class that will contain all needed information about the Database
* **SpatialiteDbLayer**
   * a class that will contain all needed information about a specific Layer within the Database
* **QgsSpatiaLiteUtils**
   * with helper static function (see below)

**SpatialiteDbInfo**  will contain this list of all available **SpatialiteDbLayer**s
* and will make them available upon demand

---

**SpatialiteDbInfo** will be contained in the presently existing **QgsSqliteHandle** class
* with it's sharing capability

This portions of this pull request have been placed in **core/providers/spatialite**
* so that they may be made available everywhere where a spatialite connection is needed

In a scenario, where 10-50 layers are being loaded from the same Database
* that Database is read only once and the collected information shared between the 10-50 layers

---
All classes within the QgsSpatiaLiteProvider access all needed information from **SpatialiteDbInfo** or **SpatialiteDbLayer** are retrieved and stored as member variable.

Instead of **mSqliteHandle** , **dbSqliteHandle()** is used, so that knowledge of the internal structure of **SpatialiteDbInfo** and **SpatialiteDbLayer** is not needed.

Otherwise the functionality of the QgsSpatiaLiteProvider, QgsSpatiaLiteFeatureIterator and QgsSpatiaLiteConnection have not changed, only the method on how they attain the needed information has.

These classes had contained many functions for the retrieval of information from the Database, some copies of others, which is now dealt with **once** in **SpatialiteDbInfo** and/or **SpatialiteDbLayer**.

All of these functions have been removed.
All static functions (10), that were used in QgsSpatiaLiteProvider, have been moved to a **QgsSpatiaLiteUtils** class. These were mainly functions for the calculation of object sizes or converting from one (internal spatialite specific) format to another.

Goal was to separate the Database and Provider functionality.
This should simplify future maintenance of both. 

---
Since **SpatialiteDbInfo** is separate from the QgsSpatiaLiteProvider class, it can be used for other tasks, such as
* is the file a **Sqlite3** container
* is the container supported by QGis through
   * **QgsSpatiaLiteProvider**
   * **QgsOgrProvider**
   * **QgsGdalProvider**

This would make it possible to be used within the
* Drag and Drop and Browser logic

For 'Drag and Drop', this has been implemented in QgisApp::openLayer, where the QgsSpatiaLiteSourceSelect will be opened if the Droped files is a supported **Sqlite3** container and that there is more than 1 Layer. If only 1 Layer then it will be opened. Otherwise the function will continue as it does now.

It can be called in a way to only 'sniff' the Database, returning after determining which container type it is
* Spatialite (from version 2.4 to present)
* FdoOgr
* GeoPackage (Raster/Vector)
* MbTiles
* RasterLite1
* RasterLite2
* Topology

Since the **QgsOgrProvider** cannot (yet) recognize Spatialite Tables with more than 1 Geometry and since **Ogr** has no support for writable SpatialView's, it would be important that within the Drag and Drop/Browser logic the **QgsSpatiaLiteProvider** would be used as the default.

The 'Data Source Manager - Spatialite' has been adapted to use **SpatialiteDbInfo** and **SpatialiteDbLayer**, so that the structure of the different containers can be shown (more to that later).

Also **SpatialiteDbInfo** can submit the selected Layers as **QgsVectorLayer** or **QgsRasterLayer** with the proper Provider/Connection Uri's.

This would have the advantage, that for a **GeoPackage** source, both the Vector (**QgsOgrProvider**) and Raster (**QgsGdalProvider**) Layers could be added in 1 step.

---
For the User, the only noticeable change will be the 'Data Source Manager - Spatialite'.
The **QgsSpatiaLiteTableModel** (based on **QStandardItemModel**) will now show a TreeView

Here a sample showing a **GeoPackage** Database:

datasourcemanager gpkg select

Here you can see that there are 3 tree branches
* Vector
* Raster
* Non-Spatial [will always be the **last** branch]

so that the User can distinguish between the different types, collapsing what they don't want to see.

Inside the Non-Spatial group, there are also sub-groups, so that a search for Data-Tables, Views can be easily found (without the data beings displayed), since index-tables are in an extra group.

Since **SpatialiteDbInfo** must collect the Non-Spatial anyway, the CheckBox to turn this on/off has been hidden.

In the above Image ,the last selected Item is a Raster.
When selected, first any Raster, then Polygons will be submitted, since it seems that Rasters are rendered before any Vectors. Then Linestrings after which any Point will be submitted, so that the Polygons will be over the Rasters, the Linestrings over the Polygons and the Points over the Linestrings.

Here a view of the result from a Spatialite-Database that contains SE/SLD-Styles:

datasourcemanager styles select

Since **SpatialiteDbInfo** has collected all the needed information about existing Styles and **SpatialiteDbLayer** has retrieved the information which Style it should use,  **SpatialiteDbInfo** will call the **readSld** function of QgsVectorLayer before it is sent to QGis.

---
At some time the Browser logic should be adapted to utilize the capability of **SpatialiteDbInfo**  after an initial QGis 3.0 release.

Also the **QgsSpatiaLiteTableModel** from **QStandardItemModel** to a **QAbstractItemModel** which would be fine tuned to interact with **SpatialiteDbInfo** and **SpatialiteDbLayer**
* Alessandro Furieri (Sandro of Spatialite), has asked if 

> adding some ad hoc function allowing to drop or rename columns in the most painless way.

making the administration of a Database easier.

More work on the QgsRasterLite2 provider will be done during/after the initial release of RasterLite2.

---
Known problem: none.

The geometry shown in the 2nd image were all created after all changes in QgsSpatiaLiteProvider, QgsSpatiaLiteFeatureIterator and co. were made, so I believe that these changes can be considered stable.

---
Other changes that come to mind:
* the default values are now correctly shown when creating a new Geometry
* SpatialViews will use the default values of the base TABLE when the column names have not changed (which in a view is possible)
* full Date/DateTime support

---
Previous pull requests are redundant.
 https://github.com/qgis/QGIS/pull/5033
* already closed

 https://github.com/qgis/QGIS/pull/5146
* already closed

https://github.com/qgis/QGIS/pull/5487
* still open

---

### CODE REVIEW

**Comment by m-kuhn** [comment]
As indicated previously, a review is only possible for me if we have this split into the smallest possible parts. Suggestion goes towards a few line changes for compatibility first.

**Comment by mj10777** [comment]
> Suggestion goes towards a few line changes for compatibility first.
I assume these have not yet been made, since I don't see anything yet.

> As indicated previously,
From 28th. October :
>> To separate something in parts, without the other parts - will not compile and thus completely useless.
>> True, this would be completely useless.

**Comment by m-kuhn** [comment]
for reference, here is the full conversation

https://github.com/qgis/QGIS/pull/5487#issuecomment-340202307

**Comment by nyalldawson** [comment]
I'm still of the strong opinion that before any significant investment is made we need to first determine whether there's still a valid use case for non-ogr access to spatialite layers.

Until someone does a review into this and makes a compelling case that there's still a need for a dedicated provider, I just can't justify spending any time on the spatialite provider.

**Comment by luipir** [comment]
@nyalldawson I see

**Comment by nyalldawson** [comment]
Sorry, I fear my comment comes across much too harsh.

Basically, I'm seeing so many geopackage related improvements flooding into the ogr provider (and in ogr itself), and finding it myself wondering if we couldn't just save ourselves a bunch of maintenance work by just always relegating spatialite handling to ogr. Not to mention that then we'd gain all optimisations which are present/are added to ogr's driver...

**Comment by mj10777** [comment]
> I'm still of the strong opinion that before any significant investment is made we need to first determine whether there's still a valid use case for non-ogr access to spatialite layers.

1. Org (as supported presently implemented by ''QgsOgrProvider'') does not handle tables with more than 1 geometry correctly - that will become noticeable with gdal version 2.*
2. Ogr does not handle writable SpatialViews at all
3. With Spatialite 4.5 (together with RasterLite2 and Topology) will be more like a WMS/WFS System, which would be difficult to implement in full with Gdal/Ogr

The first 2 reasons are the reason why I started this at all, because without them working correctly I cannot get my work done in QGis.

The 3rd reason should be clear that a fine tuned support, for all aspects being offered, cannot be given with a system that is based on supporting as much/many formats as possible based on there common aspects.

These would be my reasons for keeping Spatialite support mainly with a Spatialite-Provider which can deal with all aspects of the project, not all of which can be dealt with with Gdal/Ogr.

**Comment by luipir** [comment]
@nyalldawson np :) I can see you point and I agree... as far as I can see the main reason to create the provider were
1) rasterlite management (now supported by GDAL) (see the @rouault message in dev list)
2) Support for view editing (now possible AFAIK in master)
3) support for mutli geom x layer (No idea if supported by ogr)
I agree that would be better to move the support to OGR for all OGR based sw instead of a QGIS specific one.

**Comment by mj10777** [comment]
>> My proposal is to create a parallel and alternative under test SpatialiteV2 provider as we did with new geometry engine, symbology and so on. Is it feasible?

Since the main Provider portion is a dll that QGis collects during startup, it could be possible to just rename the library in CMakeLists.txt and place that code in an extra directory.

**Comment by luipir** [comment]
@mj10777 tnx for the clarification. IMHO here seems more a rationalization problem. The QGIS project decided to remove all unused core core and plugins and processing providers. The rational is to avoid to remain with un-maintained core code, when there (potencially) the way to do a genral work on OGR.
Make sense to have conditional compilation adding a external git submodule? this of the external sumbodules has been already duiscussed but I don't remember if there were a decision about.

**Comment by mj10777** [comment]
OGR does not support writable SpatialViews, nor tables with more that 1 geometry (will list and display only the first).

RasterLite2 can be read, but without nodata and styles support.

Both just tested with a master and gdal version of 2 days ago.

**Comment by luipir** [comment]
@mj10777 yes sorry I misunderstood... I was talking that relations (created in qgis) can be editable

**Comment by mj10777** [comment]
>> I was talking that relations (created in qgis) can be editable

On the fly I cannot say since I have never used relations
* would need a practical sample to try it out

**Comment by mj10777** [comment]
> My proposal is to create a parallel and alternative under test SpatialiteV2 provider as we did with new geometry engine, symbology and so on. Is it feasible?

This is relatively easy to implement, without any class name changes.

1. rename new spatialite directory to **spatialite45**
2. rename (in CMakeLists.txt) from  **spatialiteprovider** to **spatialite45provider** (creating a **libspatialite45provider.so**
3. add **spatialite45** to provders/CMakeLists.txt
4. replace ProviderKey to **spatialite45** where used
5. Add in **qgisapp.cpp** and **qgisapp.ui** a second **mAction** for **SpatiaLite45Layer**

Existing projects (with providerKey="spatialite") would use the present Provider.
Projects (with providerKey="spatialite45") would use the new Provider.
Date Source Manager would then contain 2 'SpatiaLite" entries, the 2nd shown as 'SpatiaLIte 4.5'.
The Browser would also show the 2 'SpatiaLite' entries with the same results for the Connections.
Other Browser result would should show only 'SpatiaLite 4.5' results, since the present Provider supports only Connections.

Both **QgsSpatiaLiteSourceSelect** can be called and Layers selected
* the difference between the 2 can clearly be seen and thus compared

----
Images:
1. Data Source Manager with 'Spatialite' 
spatialite datasourcemanager

2. Data Source Manager with 'Spatialite45'  using QgsVectorLayer.readSld to render builtin Style
spatialite45 datasourcemanager

3. Data Source Manager with 'Spatialite45'  with RasterLite2
spatialite45 datasourcemanager rasterlite2

4. Properties with 'Spatialite' 
spatialite properties

5. Properties with 'Spatialite45' (with QgsLayerMetadata)
* assuming that **QgsDataProvider** receives a **mLayerMetadata** member that could be set during QgsVector/RasterLayer::setDataProvider
spatialite45 properties

----
So for a Test-Phase between a QGis 3.0 and 3.2 release, it is practical to include both versions of a Spatialite-Provider to test and compare.

**Comment by m-kuhn** [comment]
Having duplicate code with their own features, limitations and bugs is confusing for users, more work for devs and a no-go for me.

Honestly, I think there is a single path forward: this  needs to be split into several separate non intrusive changes. Step by step.

**Comment by nyalldawson** [comment]
Closing this PR - master has diverged to far to allow it to be usable.

As discussed, individual PRs with modular changes should be opened instead.

**Pull request closed without merging**
