### PR TITLE
use docker for building on Travis

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by m-kuhn** [comment]
It seems to work more reliably when we are executing ninja or make directly and not through ctest (who knows why...).

The main thing to be worried of: more noise in the build log.
As a side effect build failures and warnings are not sent to cdash but stay on travis, but I think that's acceptable.

If we follow this path, we should take the build step out of the travis.ctest file and only run tests within.

**Comment by m-kuhn** [comment]
Gave up?

**Comment by 3nids** [comment]
nope, using branch on main repo!

**Comment by m-kuhn** [comment]
The processing issues (`'33' != 33` etc) seem to be caused by a newer GDAL version https://trac.osgeo.org/gdal/ticket/7027#ticket

**Comment by 3nids** [comment]
great catch.
any idea of time frame for 2.2.2 release?

**Comment by m-kuhn** [comment]
> any idea of time frame for 2.2.2 release?

CC @rouault

**Pull request closed without merging**
