### PR TITLE
more Processing tests

### PR DESCRIPTION
**Pull request by ghtmtt**
added other Processing (qgis core) tests

### CODE REVIEW

**Comment by ghtmtt** [comment]
@m-kuhn @volaya 
Some tests failed if the result is in GML format, while they run fine if the result is GEOJSON. Could be any issues in future to save the results as GEOJSON instead of GML?

**Comment by m-kuhn** [comment]
I'd prefer to keep them in GML.
I originally planned to use GEOJSON but it is less strict about types and other content and therefore might not trigger on some regressions.

**Comment by ghtmtt** [comment]
The problem is that many tests fail (both locally and on travis) if the output is GML. I don't know exaclty the reason. 
The failed build in this PR (test the alg count weighted points in polygon) says, while with GEOJSON (and even shapefile there are no problem). So the main issue is to create many test (algorithms work fine) but cannot push because of GML type. Any hint for the reason?

```

======================================================================

FAIL: test_algorithms:144

'weighted count of points in polygon', {'results': {'OUTPUT': {'type': 'vector' (__main__.TestQgisAlgorithms)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/qgis/QGIS/python/plugins/processing/tests/AlgorithmsTestBase.py", line 120, in check_algorithm

    self.check_results(alg.getOutputValuesAsDictionary(), defs['results'])

  File "/home/travis/build/qgis/QGIS/python/plugins/processing/tests/AlgorithmsTestBase.py", line 212, in check_results

    self.assertLayersEqual(expected_lyr, result_lyr, compare=compare)

  File "/home/travis/build/qgis/QGIS/build/output/python/qgis/testing/__init__.py", line 149, in assertLayersEqual

    repr(attr_result)

AssertionError: 0 != 41 : Features 0/0 differ in attributes

 * Field1: COUNT (Integer)

 * Field2: COUNT (Integer)

 * 0 != 41
```

**Comment by m-kuhn** [comment]
Are you really sure the algorithm works fine?

Just from a quick look, in the algorithm results created on your computer, the count is 0 for polygon 0 (https://github.com/qgis/QGIS/pull/3876/commits/2fb2df2e0151fabb8a22143e77d35efc5e800ad6#diff-50f4807c65686299815b22845a542d9fR20), while I assume that 41 is the proper result (but please confirm, also w.r.t. NULL geometries).

So I guess the question should be why you get 0 with GML on your computer.

**Comment by ghtmtt** [comment]
> (but please confirm, also w.r.t. NULL geometries).

You are right Matthias, that was actually the problem. A point with NULL attributes outside the polygon boundaries. 
So, best is don't have NULL with GML... I didn't know about that restriction...

**Comment by m-kuhn** [comment]
> So, best is don't have NULL with GML...

I guess it's more a limitation of the current algorithm and not a limitation of GML. To my knowledge, GML fully supports NULL (geometries and attributes).

My recommendation would be: look what really goes wrong in the algorithm and fix it. Then add the test to make sure it stays fixed in the future. If this means that you cannot write tests for every single algorithm, no worries.
Better to have some algorithms rocksolid and covered with tests rather than having tests to control defective algorithms.

**Comment by m-kuhn** [comment]
Hmm... which version of gdal/ogr are you using?

**Comment by ghtmtt** [comment]
```
matteo@matteo-computer ~ $ gdalinfo --version
GDAL 1.11.3, released 2015/09/16
```

is that one?  ``libgdal20`` says 2.1.0

**Comment by m-kuhn** [comment]
ldd output/lib/libqgis_core.so | grep gdal

**Comment by ghtmtt** [comment]
`libgdal.so.1 => /usr/lib/libgdal.so.1 (0x00007f5412260000)`

**Comment by m-kuhn** [comment]
Not sure if it's the reason for this problem, but compile qgis against gdal2.

**Comment by ghtmtt** [comment]
no idea on how to do that.. :) should I compile also gdal by myself right?

**Comment by m-kuhn** [comment]
What about that libgdal20 you mentioned before?

**Comment by ghtmtt** [comment]
ah ok.. so just change the path of GDAL_LIBRARY in ccmake when compiling?

**Comment by m-kuhn** [comment]
There's also GDAL_INCLUDE_DIR

I think if you remove all the GDAL-stuff from CMakeCache.txt and then specify the `GDAL_CONFIG` executable for gdal2, that should set up everything properly for you.

**Comment by ghtmtt** [comment]
I got some compilation errors, but I think not related to gdal2. Anyway, I'll try with your suggestions and see if with gdal2 something changes.

```
[ 61%] Building CXX object src/app/CMakeFiles/qgis_app.dir/dwg/qgsdwgimporter.cpp.o
/home/matteo/lavori/QGIS/QGIS/src/app/dwg/qgsdwgimporter.cpp: In member function ‘void QgsDwgImporter::startTransaction()’:
/home/matteo/lavori/QGIS/QGIS/src/app/dwg/qgsdwgimporter.cpp:142:56: error: ‘GDALDatasetStartTransaction’ was not declared in this scope
   mInTransaction = GDALDatasetStartTransaction( mDs, 0 ) == OGRERR_NONE;
```

**Comment by ghtmtt** [comment]
Ok, I have QGIS compiled against gdal2. Still the same problem with GML files, so it seems that this is not a gdal version issue. 
For example, another strange behavior of GML is with the `add field to attribute table` test. I procuced GEOJSON and it works fine, but if the output is a GML no field is added. 
In this particular case (so algorithm works but not with a particular file format), is it better to consider the algorithm non working and not adding it to the test list, or not? 

Thanks @m-kuhn

**Comment by m-kuhn** [comment]
@ghtmtt the interesting thing is, that when executed on travis, the algorithm seems to work fine?

**Comment by ghtmtt** [comment]
actually no.. I mean on travis they run because they are GEOJSON and not GML

**Comment by m-kuhn** [comment]
actually yes, if you look at the test results from the gml tests (you [pasted them above](https://github.com/qgis/QGIS/pull/3876#issuecomment-267329004)) there is the result of 41 features counted in the polygon.

**Comment by m-kuhn** [comment]
Note: travis will also generate a .gml if your expected result dataset is gml.

**Comment by ghtmtt** [comment]
yes, there the issue was related to a NULL attribute in the table. 
Anyway, for what seems to be an issue right now is not related to the algorithms themselves, but with the file format output if GML (and thanks to your suggestion it seems that is not related to the gdal version)..

**Comment by m-kuhn** [comment]
As far as I can see, the same algorithm

 * when executed on travis with GML output it will  generate a sensible (correct?) result with the value 41
 * when generating the expected GML dataset on your computer, the result is 0

The question is: why does the very same algorithm with the very same output format generate a different file on your computer and on travis...

**Comment by nyalldawson** [comment]
I've fought and with and cursed GML a lot too. Here's some tips:
- try deleting the .GFS file and then reopening the GML in QGIS to regenerate it. This applies to both the test data and expected data.
- try manually editing the expected data to "fix" any duplicate IDs. Then set the id column to skip in the test config (look for other tests which do this). Then regenerate the GFS.

**Comment by ghtmtt** [comment]
@nyalldawson thanks for the tips!
I tried to delete the .GFS file of the points.gml test file, reopen it in QGIS and used again the algorithm **add field to attribute table**. Nothing happens, no field is added. 

> try manually editing the expected data to "fix" any duplicate IDs. Then set the id column to skip in the test config (look for other tests which do this). Then regenerate the GFS.

AFAICS some issues are just solved if the files does not have NULL values in the attribute table.

**Comment by m-kuhn** [comment]
> AFAICS some issues are just solved if the files does not have NULL values in the attribute table.

I would formulate that differently: some issues are just not discovered if there are no NULL values ;)
Take writing tests as an opportunity to discover and fix issues. Treat fixing issues in processing algorithms (proper handling of NULL values and geometries) as integral part of writing tests!

**Comment by ghtmtt** [comment]
@m-kuhn your point of view is interesting ;)

> Take writing tests as an opportunity to discover and fix issues

yep, that's one of the things I'd love to handle (compatibly with my poor developing skills ;) )

**Comment by m-kuhn** [comment]
Hehe, the idea is, that processing should be rocksolid one day.
That means, that if you feed it with any values or geometries (NULL, invalid...) it will produce meaningful output or warn you explicitly about problems.
What does it help if we have an algorithm that silently produces bogus results as soon as it's run with NULL geometries?
So the job of someone writing tests (your job ;) )is to find out

 * which algorithms produce proper results in all kind of scenarios and input values. for these, there should be tests added that make sure that these algorithms don't break when extending them in the future.
 * which algorithms don't run smoothly at all / don't run smoothly with certain input values etc. these algorithms should either be fixed (preferably, because you have the issue reproducible right at hand at this point) or if not possible, an issue should be opened so someone else can take care of that (if you make input data + parameters + (information about) expected output available that helps a lot!). For such algorithms NO tests should be added that check for their bogus behaviour.

There were also some recent discussions with @gioman regarding this recently.

**Comment by ghtmtt** [comment]
Yes, Processing rocksolid would be really great!

Anyway, I planned to test the algorithms with as many input they need and so for the same algorithm create many test.
Now the issue could be different. I mean what if an algorithm is ok, but as in this case, with a particular file format it has some troubles? 
I can test the same algorithm with all the different output formats (shp, gml ecc..), and if with 9 format is ok and if just 1 it is not? Should we consider this algorithm "valid" and add the test or don't add the test and open a ticket (or try to fix it)?

**Comment by m-kuhn** [comment]
> Anyway, I planned to test the algorithms with as many input they need and so for the same algorithm create many test.

That's a very good idea!

> Now the issue could be different. I mean what if an algorithm is ok, but as in this case, with a particular file format it has some troubles?

GeoJSON for example doesn't know about attribute types as far as I know. So they will be assigned based on the first feature. If there's a NULL value for an attribute `COUNT` in the first feature, the attribute type for the field `COUNT` will be string. And that's wrong. Therefore some tests might pass for some dubious reasons based on such behaviour.

That's why GML was chosen: it offers type safety and it is readable as a text file (in contrast to e.g. gpkg).

I think it would be best if

 * you collect all the tests which fail with GML in a separate branch
 * write down any of your thoughts somewhere, so we have a reference of under which conditions it worked and what exactly has gone wrong etc

This way we can inspect these issues somewhere down the road and see if it's an issue with the algorithm, with the vector file writer, with gdal, with the platform, a local issue for you...

After all, this algorithm produces different outputs on different platforms without any error message. This clearly indicates that the results are questionable and cannot be relied upon, so we shouldn't pretend that everything is ok by adding a test that just passes but we don't know why.

**Comment by ghtmtt** [comment]
> write down any of your thoughts somewhere, so we have a reference of under which conditions it worked and what exactly has gone wrong etc

OK this sounds reasonable. I can work on my local fork and creating, let's say 2 branches: `good_test` and `failed_test`. 
Algorithms will output GML and the results will be checked on that file format. 

If the algorithm works well (and the test runs) I'll add it to the `good_test` branch.

For the algorithms that for some kind of reason don't work (or test fails on my local machine) I'll put them in the `failed_test` branch. 
Together with all the failed tests (or wrong algorithms) I'll create a document (something like a google doc spreadsheet or something like that) will all he information on the failed test, let's say:

* algorithm name and parameters used
* file used to run the algorithm
* QGIS version (currently I'm compiling QGIS from master branch every day and I run it directly from the output)
* platform used (it will always be Linux Mint 18)
* information of the wrong output created (if created)

Sounds it good to proceed like that?

**Comment by m-kuhn** [comment]
> Sounds it good to proceed like that?

Perfect!

Just make sure that all the tests on the `good_test` do pass (travis does that check for you) and do produce sensible results (that's the tricky part). That will help to maintain the current quality.

The other `bad_test` branch will be very helpful to identify remaining problems and review the state of processing algorithms and as such is very valuable information!

**Comment by ghtmtt** [comment]
> Just make sure that all the tests on the good_test do pass (travis does that check for you) and do produce sensible results (that's the tricky part). That will help to maintain the current quality.

yep.. I will run them first locally and then push and create a PR. Trivial question, doing a PR is the only method to run travis right? I cannot run it on my fork or in other ways before making a PR.

**Comment by m-kuhn** [comment]
You can also enable travis for your own github repository https://travis-ci.org/ghtmtt/QGIS

**Comment by ghtmtt** [comment]
awesome, I didn't now that :) so I can build before making the PR.

Maybe, in the `failed_test` branch, I can create a `Info_test.md` file within the test folder where to put all the information instead of using another external spreadsheet

**Comment by ghtmtt** [comment]
I cleaned this PR with just the algorithms that run smoothly. 
So I can start with the discussed proposal on new branches (if travis doesn't complain ;) )

**Comment by ghtmtt** [comment]
@m-kuhn if you think is ok, we can merge this commit with the tests I left. I'll put the others in the separated branch discussed.

**Pull request merged**
