### PR TITLE
[ui] harmonize geonode icon color and size

### PR DESCRIPTION
**Pull request by nirvn**
## Description
This PR harmonize the geonode icon's size (24 x 24 px instead of 425 x 425 px) as well as its color.

Before vs. PR:
screenshot from 2017-12-14 15-55-53

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Nice, should the AFS icon also follow these colors?

**Comment by nirvn** [comment]
@m-kuhn , I'm not sure how we would improve those. A mini blue globe on top of a large globe isn't great 😉 I'm open to suggestions.

In the meantime, the geopackage icon is being harmonized.

**Comment by nirvn** [comment]
Manually merged.

**Comment by m-kuhn** [comment]
> @m-kuhn , I'm not sure how we would improve those. A mini blue globe on top of a large globe isn't great 😉 I'm open to suggestions.

My suggestion would be a mini blue globe on top of a large globe ;)

**Comment by nirvn** [comment]
@m-kuhn , what about simply using the ESRI logo in shades of blue? Would we infringe some copyright law or not?

**Comment by m-kuhn** [comment]
Isn't that what I was proposing?

**Comment by nirvn** [comment]
Sorry I meant getting rid of the large oval globe and only have one, the esri globe.

**Comment by m-kuhn** [comment]
That'd be twice the same? Or with some indicator that it's vector/raster data? And with an indicator that it's a web service?

**Comment by nirvn** [comment]
I was thinking of replacing small globe with a small vector / raster indicator.

But  the more we chat about it, the more I think we should simply stick to the two globes, and apply blue colors to the small one :)

**Pull request closed without merging**
