### PR TITLE
Tweak postgres queue size depending on requested geometry type

### PR DESCRIPTION
**Pull request by nyalldawson**
Since lines and polygons will be much larger rows to fetch then points or geometryless rows, a smaller queue size should be used for these requests.

Lowering the queue size keeps QGIS responsive when working with slow postgres connections where fetching 2000 records may take multiple seconds.

In one office I currently work at it's not uncommon for the initial rendering operation to take upwards of 10 seconds before anything is shown as a result of the slow speed of fetching 2000 records.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Attributes can also make rows quite heavy but their size (especially strings) is really hard to estimate.

Have you thought about caching the queue size from previous requests and using this as initial value?

**Comment by NathanW2** [comment]
This same thing might apply to SQL Server too right?

**Comment by jef-n** [comment]
Looks almost as arbitrary the initial default.  Timing the requests and adjusting them dynamically might be better.  But that won't help with the initial 10s - at least when the initial value is 2000.   Maybe we should just start with 1.  But timing might also vary with the set of requested attributes.

@NathanW2 if there's a queue it's in the qsql (same with oracle & db2).  AFAICS we just do next().

**Comment by nyalldawson** [comment]
Closing because the dynamic approach is much better

**Pull request closed without merging**
