### PR TITLE
Hidden layers bugfix

### PR DESCRIPTION
**Pull request by elpaso**
Followup to my recent work on hidden layers.

### CODE REVIEW

**Comment by elpaso** [comment]
@nirvn can you give this a try with your test project (and with no broken layers)?

**Comment by nirvn** [comment]
@elpaso , tested this PR. While I'm pretty sure all layers are back in the tree (yay), loading the above-attached project fails to properly restore expanded state of groups.

Also, I'm seeing vertical space glitches, e.g.:
image

**Comment by elpaso** [comment]
@nirvn it should be fixed now. Could you please have another look?

CC @borysiasty

**Comment by nirvn** [comment]
@elpaso , I'll give it a try first thing tomorrow. Thanks

**Comment by borysiasty** [comment]
Thanks a lot! Just tested my projects and everything seems to work fine now!

**Comment by elpaso** [comment]
@borysiasty thank you for the feedback, if you also have some embedded layers to test please do it!

**Comment by borysiasty** [comment]
I don't have much experience with embedded groups/layers, so as far I can test ad-hoc, they seem to work smoothly between 3.14 and your branch. Thanks!

**Comment by borysiasty** [comment]
I found another issue: mutually exclusive groups are not properly read from the project.

It seems it's about reading the project, because:
     
1. Create a mutually exclusive group with two layers -> works fine.
2. Close and open the project -> the group is broken (behaves like a normal group).
3. Uncheck and check the Mutually Exclusive Group checkbox again -> doesn't help.
4. Open that project in an older QGIS version -> works fine, so the project was properly saved.

**Comment by nirvn** [comment]
@elpaso , as with @borysiasty , the only regression I can spot now is the broken mutually exclusive group on project load. You're close to victory :)

**Comment by elpaso** [comment]
> @elpaso , as with @borysiasty , the only regression I can spot now is the broken mutually exclusive group on project load. You're close to victory :)

Believe me: it was an hard fight.

Anyway, it should be fixed now, thank you for the feedback!

**Comment by borysiasty** [comment]
Yes, works fine now! Big thanks! \o/

**Comment by nirvn** [comment]
Can't spot any regressions now. Good job.

**Pull request merged**
