### PR TITLE
Using of QgsVectorLayerUtils::createFeature on move and copy tool

### PR DESCRIPTION
**Pull request by signedav**
... and there the logic of unique not null fields (like primary keys) is used.

This would fix #20347

@3nids since you originally made that part in the move and copy tool. Do you see risks on this approach?

### CODE REVIEW

**Comment by lbartoletti** [comment]
@signedav I haven't tested it, but by reading the code, I think it will also solve https://issues.qgis.org/issues/19130

**Review by 3nids — APPROVED** [review]
the approach seems very sensible to me!

**Comment by signedav** [comment]
Yes @lbartoletti it fixes #19130 as well. Thanks.
Thanks @3nids and @m-kuhn

**Comment by m-kuhn** [comment]
Tested and works
Can you prepare a backport?

**Pull request merged**
