### PR TITLE
[feature][processing] Add a new user defined nodata parameter to native vectorize algorithms

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This PR adds a new advanced parameter to the pixel centroid to point and pixel to polygon algorithms allowing users to define a list of additional nodata values. The comma-separated list can mix individual numbers as well as ranges (defined as min-max, i.e. 10-15). This can come in super handy and at times avoids intermediary raster manipulation (which can be a PITA for large files)

In addition, the algorithm can not take in an empty string for the field name parameter, which dictates the algorithms to skip attribute creation (saving a fair amount of memory / filesize for large datasets). This is useful when vectorizing a raster where the value itself isn't relevant to the output (e.g. a binary 0/1 handling of raster values being sampled).

### CODE REVIEW

**Comment by nyalldawson** [comment]
I've no issue with the enhancements themselves, but I suspect @elpaso will have issues with the lack of localisation support here (and the problems associated with comma as separator).

In general though I think we do need a "multiple number" input type in processing which handles this situation properly, and eg allows for list values as data defined parameter values etc. There's even a 3 year old implementation of this here: https://github.com/nyalldawson/QGIS/commit/5c4d30a656d9f2287303d4a0525fc94d64744d62 😜

**Comment by nirvn** [comment]
@nyalldawson , OK, I'll work in a solution for localization here. 

It'd be nice to have a multiple numbers parameter in the future, but can't say I have the energy straight away to do that ATM so I propose we defer that point.

But to expand on that, I think we'd actually need some form of a multiple range parameter (and maybe accept that people would declare e.g. 3 to 3 to add a single NODATA value)

**Comment by nyalldawson** [comment]
> OK, I'll work in a solution for localization here.

> It'd be nice to have a multiple numbers parameter in the future, but can't say I have the energy straight away to do that ATM so I propose we defer that point.

It's tricky here, because as soon as we introduce proper multiple number support then this alg will need porting to that, and we'll have to ensure the API remains stable for this algorithm.

So any short term solution still needs to be designed in such a future proof way that we won't get burnt at that point and end up with a bunch of extra compatibility code/hacks.

**Comment by nyalldawson** [comment]
> But to expand on that, I think we'd actually need some form of a multiple range parameter (and maybe accept that people would declare e.g. 3 to 3 to add a single NODATA value)

I guess ideally -- but this algorithm already respects any user no data ranges set for the layer itself, so there's already a way users can handle this requirement.

(Ideally, I guess EVERY parameter type would have multi value/array support, including strings, date times, etc...!)

**Comment by nirvn** [comment]
@nyalldawson , on the user nodata stuff, that only works against a layer added onto a project and styled there. I added the parameter so we can have that option via qgis_process.

**Comment by nirvn** [comment]
I'll re-open when we have a way forward here.

**Pull request closed without merging**
