### PR TITLE
Fix point picking precision for point parameters in processing dialog

### PR DESCRIPTION
**Pull request by troopa81**
## Description

When user click on map to select a point for a point parameter in a qgis processing, position is converted to string with only 6 significant digits, which cause a lack of precision in the end. 

I just set the precision to 18 to be consistent with the past behavior (when code was in python)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by luipir** [comment]
@troopa81  what is the use case to look for so high precision?

**Comment by troopa81** [comment]
@luipir one thing disturbing is when you enable snapping to pick a specific point in a map. The difference between the point you pick and the real point could be significant.

**Comment by luipir** [comment]
> The difference between the point you pick and the real point could be significant.

I'm not expert in snapping tools, but I suppose there are snapping tolerance config parameters that allow you to manage low digits numeric precision.
IMHO 6 digits is 1meter/1.000.000 (in projected) that is already too much for any application... are you sure you need 18 digits to reach sub atomical precision?

**Comment by troopa81** [comment]
I don't much about snapping tools, but it look likes that when you snap a point, it copies the exact value of the point you target. The tolerance is just the *magnet* distance.  

In projected, when you pick a point you can get the value 6.68926e+06 instead of 6689255, which means you can get 5 meters precision errors. It ain't much but I think more digits will be a plus. 

I'm ok with you that 18 digits is too much, I just choose this arbitrary value to be consistent with python code (extent picker for instance) where you get 18 digits.

**Comment by nyalldawson** [comment]
Would an alternate solution be to set the maximum to 8 or 9 decimal places, but always avoid using scientific notation?

**Comment by troopa81** [comment]
@nyalldawson you're right. I forced the non-scientific notation (9cfaf10) and the default precision is 6 decimals which is enough even in projected.

**Review by nyalldawson — APPROVED** [review]

**Comment by luipir** [comment]
tnx @troopa81

**Pull request merged**
