### PR TITLE
[expression] Negative index support to point_n(), angle_at_vertex(), distance_to_vertex() functions

### PR DESCRIPTION
**Pull request by nirvn**
## Description
Because we all love negative index support.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Can you update the help accordingly?

**Comment by nirvn** [comment]
@nyalldawson , that's not a bad idea! :wink:

**Comment by DelazJ** [comment]
@nirvn see https://issues.qgis.org/issues/21284 (and related https://issues.qgis.org/issues/21282)

**Comment by nirvn** [comment]
@nyalldawson , function help ammended.

@DelazJ , negative index support added to angle_at_vertex() and distance_to_vertex() functions. We can't harmonize the index (1 vs 0 as starting point) until QGIS 4.0, let's keep that in mind when we cross that bridge.

**Pull request merged**
