### PR TITLE
Custom tab distances for labels

### PR DESCRIPTION
**Pull request by nyalldawson**
Allows setting a list of custom tab stop distances, instead of just a single distance

https://github.com/user-attachments/assets/db26602d-2e2e-4754-a593-853b26a8dc07

Sponsored by City of Freiburg im Breisgau

### CODE REVIEW

**Comment by uclaros** [comment]
Nice!!
What is the expected behavior when text does not fit within a tabstop?
For example something like
```python
        format = QgsTextFormat()
        format.setFont(getTestFont('bold'))
        format.setSize(20)
        format.setSizeUnit(QgsUnitTypes.RenderUnit.RenderPoints)
        format.setTabPositions([QgsTextFormat.Tab(20), QgsTextFormat.Tab(24)])  # if 4mm are enough to fit a single letter
        format.setTabStopDistanceUnit(Qgis.RenderUnit.Millimeters)
        self.assertTrue(self.checkRender(format,
                                         'text_tab_positions_fixed_size',
                                         text=['with\tmany\ttabs', 'a\tb\tc']))
```
where the second line's `b` would fit but the first line's `many` would not fit.

**Comment by nyalldawson** [comment]
@uclaros 

> What is the expected behavior when text does not fit within a tabstop?

It just runs over the tab stop, and the next tab character will advance to the next available tab stop past the current position. And if there's no remaining explicit tab stops, then all remaining tab characters are ignored

**Comment by uclaros** [comment]
Thanks, it makes sense! Maybe worth adding the test?

**Comment by nyalldawson** [comment]
@uclaros 
> Thanks, it makes sense! Maybe worth adding the test?

Ok, done

**Comment by DelazJ** [comment]
Hi,
I watched the screencast, and sorry for the noob question but, what would be the use case of this feature? IIUC it allows to add different tab spacing between words(?) within a label. But when would I want to do that? Any examples? Thanks.

**Comment by nyalldawson** [comment]
@DelazJ one cool use case is it allows the creation of table-like labels, because you can have multiline text with different "columns" of text lined up nicely.

**Comment by agiudiceandrea** [comment]
Please have a look at https://github.com/qgis/QGIS/issues/60003 and https://github.com/qgis/QGIS/issues/60004 related issue reports.

**Pull request merged**
