### PR TITLE
[bugfix] Fixes relation widget when switching between layer styles #16100

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

This PR fixes the relation widget when switching between layer styles (see https://issues.qgis.org/issues/16100).

Moreover, a unit test has been added to highlight the issue.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by pblottiere** [comment]
The build is failing due to a sip file not up to date. But I did not touch the corresponding header file.

So, I think that everything is green about  changes introduced by this PR.

**Comment by m-kuhn** [comment]
Thanks

**Comment by m-kuhn** [comment]
Backported to 2.18 c89ffe46c5f7404fc4a0fa9b48f6508e89d9e07f

**Comment by m-kuhn** [comment]
Oh, the issue is still open.
Looks like you need to write "Fix #16100" literally

**Pull request merged**
