### PR TITLE
[Plugin manager] [needs-docs] [FEATURE?] Add links to the plugin detai…

### PR DESCRIPTION
**Pull request by borysiasty**
Add links to the plugin details view to open the local directory of installed plugin and the download page/link of the available version (do not confuse with plugin homepage).

For the official Repo, it's the current version details page, but for other repositories it's just the download link as we don't know better endpoints.

zrzut_20180913_202217

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by borysiasty** [comment]
@rduivenvoorde it's for you :) 
Hopefully it's better than displaying the long uri broken in two lines of text.

**Review by elpaso — APPROVED** [review]
LGTM, the only thing I would probably change is the link to library shared object in case it is a c++ plugin. I don't think that makes sense to open the .so itself, maybe better to open the folder?

**Comment by borysiasty** [comment]
Ah thanks! Probably fixed now, compiling...

**Comment by rduivenvoorde** [comment]
@borysiasty nice! So now I can check what has happened with IPyConsole first before upgrading @elpaso plugin in his changelog: 

pr

Clean compile works here with fine here with me. Now we hope that everybody will create a multiline changelog in their metadata.txt :-)

I was wondering if the little 'link/download' icons not better be bleu text like the ones above it for the author, bug tracker and code repo. Something like: 
Installed version 3.4.0 <install directory>
Available version 3.5.0 <plugin site>

And about multil-ine urls/links, I do miss to SEE were I'm going to... In a browser I always look in the bottom to the url of a link. Would it be an idea to have the link as a tooltip here? Or is that too much?

**Comment by rduivenvoorde** [comment]
Ah, too late :(

**Comment by nyalldawson** [comment]
Just merge if it passes Travis - the pr was ready prior to freeze, it's just that Travis has a massive backlog.

**Comment by borysiasty** [comment]
Merged! @rduivenvoorde oh where were you when the mankind was in need? I guess there is no UI freeze today, so we can still tweak it, can't we?

**Comment by borysiasty** [comment]
@rduivenvoorde see #7908

**Pull request merged**
