### PR TITLE
[processing] Add missing resampling methods to GDAL warp.

### PR DESCRIPTION
**Pull request by radosuav**
## Description
Add missing resampling methods to GDAL warp. They are all available since at least GDAL 2.0.0.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by radosuav** [comment]
@volaya @alexbruy would it be possible to merge this PR and #6081 before the next 2.18 point release in 3 days? Thanks!

**Comment by nyalldawson** [comment]
@radosuav 

I've just had a look at this -- I don't believe it's suitable for inclusion in 2.18 as 2.18 has a minimum GDAL version of only 1.4, and processing options like this must be available consistently regardless of the GDAL version.

**Comment by radosuav** [comment]
Fair enough, although it's a pity to miss this useful functionality.

**Comment by rouault** [comment]
@nyalldawson Why not adding a GDAL version check to add the extra options when appropriate ? This wouldn't be very different than supporting GeoPackage or 64-bit integers that depend on which GDAL version is actually available.

**Comment by nyalldawson** [comment]
Closing for now - if a revised version which adds a gdal version check is added then it can be merged. Otherwise this functionality is available in 3.0+

**Pull request closed without merging**
