### PR TITLE
Singleton fixes

### PR DESCRIPTION
**Pull request by m-kuhn**
The template based approach was not cross-platform friendly. When cross-compiling for Android it caused a new instance of every singleton per shared library.

### CODE REVIEW

**Comment by m-kuhn** [comment]
This singleton mess is really a PITA.
I hope this fixes cross-platform (/compiler) issues and still does not crash on exit.

And while we're at it... STOP USING SINGLETONS!

**Comment by NathanW2** [comment]
STOP USING SINGLETONS!

:) down with singletons

**Comment by m-kuhn** [comment]
... All the cute little poor kittens ...

Did you know

**Comment by m-kuhn** [comment]
It looks like the main issue with crash-on-exit is that there's a dependency between `QgsMapLayerRegistry` and `QgsProviderRegistry` and between `QgsNetworkAccessManager` and `QApplication`.
Tests seem to run fine now. Restarting them once again to be sure that it wasn't caused by stellar constellation (aka. race condition).

**Comment by timlinux** [comment]
*sniff* - in the bad old days we liked using singletons :-P

**Comment by wonder-sk** [comment]
The question is - what else to use? :-) Singletons are not evil, they are just not that simple as they might look like :)

I have the impression that singletons in QGIS code are used only in cases where other solutions would be impractical...

Correct destruction of singletons is a bit of a problem... although doable with stuff like phoenix singletons or destruction managers, things get more complicated.

**Comment by m-kuhn** [comment]
They are practical until you see their limitations :)

QgsProject is the best example of something where there's no real reason to have only *one* in an application. And the map layer registry should be in the scope of a project.

Then there are some registries of which I think they could be implemented differently but I don't worry so much.

And then there are shared system resources like network related things which are ok to implement as singletons.

**Pull request closed without merging**
