### PR TITLE
Add a doxygen test to ensure all classes have a brief description

### PR DESCRIPTION
**Pull request by nyalldawson**
Forcing use of brief descriptions for classes themselves (as well as members) makes the code much more understandable... it's much quicker to get an idea of exactly what a class is for, rather than inferring this from the member docs.

### CODE REVIEW

**Comment by m-kuhn** [comment]
What happens if the main description itself is short enough to deserve the title brief?

**Comment by nyalldawson** [comment]
@m-kuhn I'm pretty sure that's not possible in doxygen. The brief description is the default - it uses the first paragraph of whatever description is entered.

**Comment by m-kuhn** [comment]
So basically, this forces a description - from which a brief always can be extracted?

**Comment by nyalldawson** [comment]
Exactly .... it forces a description to be entered for the class itself as well as the members.

**Comment by nyalldawson** [comment]
Eg - have a look through http://qgis.org/api/group__gui.html . The benefits of having a class description are quite evident!

**Comment by m-kuhn** [comment]
I see, fair enough

**Pull request merged**
