### PR TITLE
Feature #4273 and #3756

### PR DESCRIPTION
**Pull request by duncan-r**
Amended dialogs and classes for north arrow, copyright and scalebar decoration items.

Updates based on feature request #3756: using canvas percentage to locate items.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@duncan-r I've just given this a test - it works well, and the code looks good. My only reservation is that I'm wondering if setting the position as a % is the best approach. I'm thinking it would be better UX if the placement combo box was always active, and instead of having a % placement option instead change this to a "margin from edge" option which is always active. So eg you could set a placement to top-right, with a margin of 5%. In future this could be expanded to handle different margin units too, eg % or pixels. What do you think?

**Comment by duncan-r** [comment]
@nyalldawson Yep. That makes sense to me. I've updated the scalebar dialog in line with your comments (see below). Is this what you were thinking? If not let me know and I'll make some more changes. Once you're happy I'll amend the code and update the pull. 

I may add a couple of radio buttons in the future, above the inputs, for % and pixels as you suggest. I think at the moment I'll just get it working with the percentage option, so they have been left off for the time being.

scalebar_decoration

**Comment by nyalldawson** [comment]
@duncan-r yes, that's exactly what I had in mind. If unit choice was later added it should be done by adding a QgsUnitSelectionWidget to the right of the spin boxes. That would keep consistent behaviour with symbology and labeling.(don't consider that a requirement to get this current with merged though).

Incidentally, this has reminded me of something I hate about these decoration setting dialogs. The  most important setting - the check box for enabling the decoration - is hidden away at the bottom of the dialog. I think this should be reworked so that all other widgets sit inside a checkable group box for the decoration. This would mean they are all disabled if the decoration isn't switched on, which would be much more obvious and user friendly UX. We should probably fix this sometime too!

**Comment by duncan-r** [comment]
@nyalldawson I've amended the dialogs in line with your comments. I've also changed them around a bit so that all widgets are enabled/disabled by toggling the group box, as you suggested for the UX. This means they're a little different from the image I posted above.

Hopefully all is good now. If not let me know.

**Comment by nyalldawson** [comment]
@duncan-r looks great, a huge improvement! Thank you!

One minor changes required: don't forget to update the tab order of the dialogs when you move controls around or add new ones.

Some other things which might be nice to address (only if you feel like it):
- using QgsSpinBox instead of QSpinBox will add the handy "clear" buttons to the spin widgets, which would be nice to easily reset the margins. (It also allows simple math expressions to be entered into the spin box directly)
- I find the order of the positions in the comboboxes odd - I think this would work better alphabetical or top left, top right, bottom left, bottom right.

But these aren't essential changes, I'm happy to merge as is. Do you mind squashing all these commits down into a single one? Let me know if you need assistance with the git commands to do this.

**Comment by duncan-r** [comment]
Always the little things isn't it :). i'll get that sorted. I'm happy to update to QgsSpinBox and I'll check that the placement combo is all in order. I think that "top left, top right, bottom left, bottom right" makes more sense to me, so I'll go with that.

I've just realised that I haven't updated the qgsdecorationgriddialog to use a group box for enabling so I'll do that as well to maintain consistency with the others.

I'm assuming that it's safe to just use an interactive rebase on a pull request to get everything squashed? Unless there's a better/easier way to do it?

**Comment by nyalldawson** [comment]
@duncan-r 

> I'm assuming that it's safe to just use an interactive rebase on a pull request to get everything squashed? Unless there's a better/easier way to do it?

That's what I do - rebase and squash, then force push to overwrite the branch on github.

**Comment by duncan-r** [comment]
@nyalldawson Excellent. Every day's a school day! I created a new branch based on master, rebased and squashed all the commits and --force pushed up to my fork. Seems to have worked, hopefully (was simpler than I expected). 

I think I've addressed everything as discussed and hopefully all tests will pass.

Many thanks for all your help in getting it done and fixed up properly.

**Comment by nyalldawson** [comment]
Perfect - thank you! Great contribution :)

**Pull request merged**
