### PR TITLE
Update INSTALL

### PR DESCRIPTION
**Pull request by ghtmtt**
add qt5-default as missing dependency for the build on xenial

### CODE REVIEW

**Comment by 3nids** [comment]
At the beginning of the file: 

>  /!\ Note to document writers: This documented is generated from 
 doc/INSTALL.t2t - if you need to edit this document, be sure to edit that 
 file rather than the generated INSTALL document found in the root of the 
 source directory.

**Comment by ghtmtt** [comment]
@3nids I totally missed the file header and the instructions. I removed the string from INSTALL and added it in docs/linux.t2t

thanks for the feedback!

**Comment by nyalldawson** [comment]
Is this still needed? I don't think qt5-default should be required here. As per the qt5-package notes: "This package should not be used for building Debian packages"

**Comment by ghtmtt** [comment]
don't know if it is still needed.. when I wrote the file I had to add the package.. but dump this PR if it is useless

**Pull request closed without merging**
