### PR TITLE
Remove temporary qt6 downgrade, move to 6.5.1

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by nyalldawson** [comment]
Hmm odd, something else has changed in qt 6.5 which is breaking the QgsDoubleValidator tests...

**Comment by nyalldawson** [comment]
@agiudiceandrea looks like these failures relate to 7fbd26a79a49f

**Comment by agiudiceandrea** [comment]
@nyalldawson, I know. See https://bugreports.qt.io/browse/QTBUG-113443#comment-722903. The issue in Qt 6.5 will be allegedly fixed since Qt 6.5.2.

**Comment by nyalldawson** [comment]
Guess we'll wait for that release then 🙃

**Pull request closed without merging**
