### PR TITLE
Fixes 16712, SLD export of categorized style fails if attribute name conflicts with a built-in function name

### PR DESCRIPTION
**Pull request by aaime**
## Description
A style build on an "Area" attribute will conflict with the built-in area function and the export won't contain a proper OGC filter for the categories, but comments such as:

````
          <!--Parser Error: syntax error, unexpected GT, expecting '(' - Expression was: Area > 500 AND Area <= 1000-->
````

A solution is to quote the attribute.
## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by luipir** [comment]
+1

**Comment by aaime** [comment]
Anything else I should be doing to get this pull request merged?

**Review by luipir — APPROVED** [review]

**Comment by luipir** [comment]
@nyalldawson any opinion to avoid merging?

**Comment by nyalldawson** [comment]
I'm not experienced in sld, if you think it's good, merge away!

**Comment by luipir** [comment]
@nyalldawson I don't have commit right... that't the reas I ask to merge. tnx

**Comment by aaime** [comment]
Thank you both!

**Comment by aaime** [comment]
By the way, the original ticket is here, but I don't have rights to close it it seems: https://issues.qgis.org/issues/16712

**Comment by luipir** [comment]
it is closed automatically if you add "fixies #16712" in your commit

**Comment by aaime** [comment]
I thought I did, but it's missing the "#"

**Pull request merged**
