### PR TITLE
Adding messageBar() method to QgisInterface

### PR DESCRIPTION
**Pull request by gacarrillor**
There seem to be algorithms depending on QGIS GUI components, such as the field calculator algorithm. iface.messageBar() is called from processing.gui.MessageBarProgress, which in turn is used in processing.core.Processing when iface is not None. With the proposed change, algorithms such as field calculator can be run in standalone scripts. See http://gis.stackexchange.com/questions/130397/how-to-access-qgisfieldcalculator-from-external-script for a use case.

### CODE REVIEW

**Comment by NathanW2** [comment]
Are you sure this will fix it. This class is just for unit tests you haven't changed any production code

**Comment by gacarrillor** [comment]
It's for unit tests but it can be used for running processing algorithms in standalone scripts. messageBar() is missing in this class anyways, so any algorithm that requires it will throw errors when run out of QGIS. An example is Field Calculator, which I didn't find tests for.

**Comment by m-kuhn** [comment]
I don't mind adding this method to QgisInterface.
But I wonder if not a different approach for pushing status information from processing (with signals) should be preferred instead?

**Comment by gacarrillor** [comment]
There is a commit which disables calling Processing algorithms (namely those relying on `iface`) from a standalone script. I've asked @volaya about it: https://github.com/qgis/QGIS/commit/293ac607221ad176b5304cf9ca368c5a21fb2180#commitcomment-9524667 I'm closing this request until I get a response from him.

**Pull request closed without merging**
