### PR TITLE
[Doc] Update QgsMapLayer documentation

### PR DESCRIPTION
**Pull request by rldhont**
Add documentation string to 10 QgsMapLayer methods.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Always welcome :)

What does the [Test] prefix indicate?

**Comment by rldhont** [comment]
This pull-request is for enhance test and documentation, but the more impacted is test, it's why I apply [Test] prefix.

**Comment by m-kuhn** [comment]
I only see doc changes (and the lower doc threshold in the test)

**Comment by rldhont** [comment]
But I have some trouble with this test.

**Comment by m-kuhn** [comment]
After reading your mail, I understand.
There's nothing to fix with the test, just disable it on your local machine.

**Pull request merged**
