### PR TITLE
[sipify] support different since versions in C++ vs PyQGIS

### LINKED ISSUE #138: wrong version warning for qgis.core.QgsVectorLayer.fieldConfigurationFlags
This part of the documentation states _New in version 3.16._ but the [qgis.core.Qgis.FieldConfigurationFlag](https://qgis.org/pyqgis/master/core/Qgis.html#qgis.core.Qgis.FieldConfigurationFlag) it returns is _New in version 3.34._

the version warning should be _New in version 3.34._

Page URL: https://qgis.org/pyqgis/master/core/QgsVectorLayer.html#qgis.core.QgsVectorLayer.fieldConfigurationFlags

### PR DESCRIPTION
**Pull request by 3nids**
fixes https://github.com/qgis/pyqgis/issues/138

### CODE REVIEW

**Comment by Gustry** [comment]
LGTM
Thanks, this was somehow linked to a previous comment of mine.

Nice tweak in scripts/sipify.pl ;-)

**Comment by troopa81** [comment]
Why not simply modify the version to 3.34

I would say that official API is the Python one, and everything exposed in C++ but not in Python is considered non-stable API no?

Or something like you have proposed but the other way
```
 \since QGIS 3.34 (already exposed in C++ API since 3.16)
``` 

and sipify would strip off the parenthesis part.

**Comment by 3nids** [comment]
Thanks, good point @troopa81, I've updated accordingly.

**Review by troopa81 — APPROVED** [review]
Thanks @3nids

**Pull request merged**
