### PR TITLE
Do not generate a ogc:Filter where a ogc:Expression is expected. 

### PR DESCRIPTION
**Pull request by aaime**
Fixes #10076 and #11202

### CODE REVIEW

**Comment by elpaso** [comment]
Can you please fix the CI errors?
https://travis-ci.org/qgis/QGIS/jobs/150418578#L1085

**Comment by aaime** [comment]
Hi @elpaso sure, no problem. One question thought, I did not get those errors in my local build (but failures in compositing tests instead). Wondering if I'm missing some tools that would check indentation issues?

**Comment by elpaso** [comment]
Read the error message that I pointed to:

```
Tips to prevent and resolve:

* Enable WITH_ASTYLE in your cmake configuration to format C++ code

* Install autopep8 (>= 1.2.1) to format python code

* Use "scripts/astyle.sh file" to fix the now badly indented files

* Consider using scripts/prepare-commit.sh as pre-commit hook to avoid this

  in the future (ln -s ../../scripts/prepare-commit.sh .git/hooks/pre-commit) or

  run it manually before each commit.
```

**Comment by aaime** [comment]
Thanks a lot, I did not see it :-)

**Comment by aaime** [comment]
The build is finally green :-)

**Comment by elpaso** [comment]
Thanks for the fixes!

**Comment by aaime** [comment]
Awesome! 
Now, I see you already added the "needs backporting" tag, and indeed, I would l like to backport this fix for all active branches (e.g., the ones where you are cutting releases from). 
Is there any particular guide/convention I need to follow? 
Also, and sorry for the ignorance, what are the current active branches?

**Comment by elpaso** [comment]
The current active branches are:
- master_2 (current 2.x series)
- master (will be 3.0)
- release-2_14

I'm not sure you can do the backporting: people with commit rights can cherry-pick the commits, I did not have time yet but I'll try to do that before I leave for my summer holidays

**Comment by aaime** [comment]
Hi @elpaso I asked because I know this is not going a clean and simple cherry-pick, the class names have been changed in a backwards incompatible way while I was working on this fix (I had to actually change the code twice to make it compile). If needed, I can do more pull requests for the other branches.

**Comment by elpaso** [comment]
that would be awesome, thanks.

**Pull request merged**
