### PR TITLE
Delaz j symbolselector help show

### PR DESCRIPTION
**Pull request by elpaso**
See:  #5976

### CODE REVIEW

**Comment by DelazJ** [comment]
Thanks @elpaso

**Comment by elpaso** [comment]
@DelazJ thank **you**!

**Comment by DelazJ** [comment]
@elpaso I'm afraid this crashes the layer styling panel (c738bcf7) when using the categorized or grraduated style (click any symbol and boom). Works pretty well in the layer properties dialog. (Will also open a report when able to connect to issues repo). Any idea?
> QgsRasterHistogramWidget::applyHistoMin :
QStandardItemModel::data :
QModelIndex::data :
QStyledItemDelegate::initStyleOption :
QStyledItemDelegate::paint :
QTreeView::drawRow :
QTreeView::drawTree :
QTreeView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsLayoutItemMap::grids :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QMainWindow::event :
QgisApp::deletePart :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsLayoutItemMap::grids :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgisApp::deletePart :
BaseThreadInitThunk :
RtlUserThreadStart :

**Comment by elpaso** [comment]
@DelazJ I missed this, I'll have a look

**Pull request merged**
