### PR TITLE
fix GRASS7 v_cluster tool

### PR DESCRIPTION
**Pull request by gioman**
## Description
fix GRASS7 v_cluster tool. Reference: https://issues.qgis.org/issues/20154

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by luipir** [comment]
@gioman do you mind is possibile to add the test using the test generation framwork?

**Comment by nyalldawson** [comment]
>  do you mind is possibile to add the test using the test generation framwork?

It is -- see https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/testdata/grass7_algorithms_vector_tests.yaml

**Comment by nyalldawson** [comment]
I'm going to merge this in the meantime even without a test -- release is closing in and it's a trivial fix which should be in place even if @gioman doesn't get time to generate a test before release.

**Comment by gioman** [comment]
> @gioman do you mind is possibile to add the test using the test generation framwork?

@luipir I'm trying to understand how use that

**Pull request merged**
