### PR TITLE
[Server] Read and activate selection color

### PR DESCRIPTION
**Pull request by rldhont**
## Description
The selection color is read from QgsProject by QgsMapRenderer during the
rendering. So Server has to activate selection color by set color read from
project XML.

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rldhont** [comment]
@gioman @mdouchin I think this PR should interest you.

**Comment by andreasneumann** [comment]
Nice - I just recently needed this as well! I assume it also honors opacity of the selection color of the project - right?

**Comment by rldhont** [comment]
@andreasneumann yes, rgb and alpha are honors.

**Comment by pblottiere** [comment]
Thanks for this fix @rldhont, it looks good!

I'm so happy we don't have `QgsWMSProjectParser` in 3.x anymore ;).

**Pull request merged**
