### PR TITLE
[Processing] Add missing functionality to set R parameters as advanced.

### PR DESCRIPTION
**Pull request by radosuav**
## Description
To set a parameter as advanced you have to use “advanced” keyword in the input parameter description at the top of the R script. It can be used in combination with “optional” key word by separating them with comma and no spaces, i.e. “advanced,optional”.

So the following are correct:
##param_name=optional string
##param_name=optional,advanced string
##param_name=advanced,optional string
##param_name=advanced string
##param_name=string

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Is this a bugfix? Looks more like a feature to me...

**Comment by radosuav** [comment]
All/most of the other providers have functionality for setting parameters as advanced and it is also part of Processing core. So I would consider it an functionality omission bug in the R provider.

**Comment by nyalldawson** [comment]
I've been thinking on this one, in my opinion it's not suitable for inclusion in the stable LTR branch (which at this stage should only be seeing mission-critical bug fixes - it's already seeing too many regressions due to bad backports). But I'd like a second opinion here. @alexbruy ?

**Comment by alexbruy** [comment]
For me it looks like a new feature, not bugfix. This is not really critical functionality and personally I prefer to not include this into LTR to avoid possible issues.

**Comment by nyalldawson** [comment]
As discussed, this isn't suitable for inclusion in the stable LTR branch.

**Pull request closed without merging**
