### PR TITLE
QgsTriangle Fix draw (as polygon)

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description
Triangle wasn't drawn (using make_triangle). It's now fixed for polygon. Do you think that we have to add a draw method for linestring?

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [X] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [X] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [X] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
LGTM, but I don't understand the question about linestring.

**Comment by nyalldawson** [comment]
There's facility to unit test this - see https://github.com/qgis/QGIS/blob/master/tests/src/python/test_qgsgeometry.py#L4304

You could use this to test if any other subclasses need these methods implemented too.

**Comment by nyalldawson** [comment]
I'm curious QgsCurvePolygon::draw isn't working - from a quick glance it seems to be doing the same thing.

**Comment by lbartoletti** [comment]
Sorry, it works.
I was alerted by this [message](https://github.com/qgis/QGIS/pull/5298#issuecomment-334275216), but it's ok. I haven't checked before push it.

**Pull request closed without merging**
