### PR TITLE
Allow converting polygons with unclosed rings to GEOS

### PR DESCRIPTION
**Pull request by strk**
Forces ring close on conversion -- see http://hub.qgis.org/issues/13635

### CODE REVIEW

**Comment by nirvn** [comment]
This fix needs backporting to 2.14 before it becomes the next LTR.

**Comment by m-kuhn** [comment]
Good job!

**Comment by strk** [comment]
@nirvn see http://hub.qgis.org/issues/13635#note-19 and subsequent comment: 2.14 already seems to close those rings automatically, at some point. The issue still needs an automated testcase to fully understand which code paths are or aren't affected.

**Comment by strk** [comment]
The added test confirm that as of 2.14 non-closed polygons can still be identified (the test doesnt' test for "selected"). So the fix in this PR is only for master (2.15). I'm not sure there's any blocker issue to be fixed in 2.14 from http://hub.qgis.org/issues/13635 (ie: no regression I could find from 2.8 times)

**Comment by strk** [comment]
@slarosa can you confirm there's no regression in 2.14 from 2.8 ?

**Comment by strk** [comment]
squash-merged as b040410c5e321bfe15e7c35e29f62dbabb55bec8

**Pull request closed without merging**
