### PR TITLE
[Backport 3.12] Fix relation reference constraint when identifying a feature

### PR DESCRIPTION
**Pull request by troopa81**
## Description

Backport #34329 in release-3_12

### CODE REVIEW

**Review by m-kuhn — CHANGES_REQUESTED** [review]
This introduced a regression, see  https://github.com/qgis/QGIS/pull/34355#issuecomment-593455667

**Comment by troopa81** [comment]
> This introduced a regression, see #34355 (comment)

This PR is not related to this issue

**Comment by m-kuhn** [comment]
Do you have an idea where this regression was introduced?
I guess we should wait with backporting any changes on this widget until we found out what triggered it.
(CC @obrix)

**Comment by elpaso** [comment]
@m-kuhn , @troopa81 I didn't dig further but my debugger thinks (yes, it does :) that that the regression comes from https://github.com/qgis/QGIS/pull/34355/files#diff-bee409cb02c75d3272f877c88ea1e86eR291

**Comment by rouault** [comment]
@troopa81 Is it safe to merge ?

**Comment by troopa81** [comment]
@rouault IMHO Yes
 
@m-kuhn You requested changes but this backport is not related to #34355 but to #34329. Are you OK to merge?

**Review by rouault — APPROVED** [review]

**Comment by rouault** [comment]
I've just given but my approval, but can't still merge. so @m-kuhn must remove its veto ;-)

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
