### PR TITLE
New feature to the "Drop field(s)" algorithm

### PR DESCRIPTION
**Pull request by MrChebur**
## Description

Added a new parameter.
It allows you to delete all fields except the selected ones.
This feature can be very useful in the model builder as you cannot know all the field names before you start the processing.
Some details: https://gis.stackexchange.com/questions/375494/dropping-all-fields-exept-one-with-qgis-3-model-builder

EhmNlBpt5c

### CODE REVIEW

**Comment by pathmapper** [comment]
This PR closes https://github.com/qgis/QGIS/issues/39345.

**Comment by nyalldawson** [comment]
Great feature!

I'd prefer to see this exposed as a seperate tool to the existing "delete fields" algorithm. Ie. a "retain fields" algorithm. @alexbruy what do you think?

**Comment by uclaros** [comment]
I love this!
I suggest we change *Fields to drop* to *Select fields* and then have the type of action selectable with a combo box *Drop selected (default)* or *Keep selected*

**Comment by nyalldawson** [comment]
@MrChebur I've taken your work here and applied a modified version of it to  #40225 , where I've also ported both algorithms to c++ for speed and compile-time safety. Thanks for the inspiration!

**Pull request closed without merging**
