### PR TITLE
[BUGFIX] QgsGeometry exportToGeoJSON return 'null' for null Geometry

### PR DESCRIPTION
**Pull request by rldhont**
Needed for QGIS Server WFS

### CODE REVIEW

**Comment by m-kuhn** [comment]
looks good to me

**Comment by rldhont** [comment]
Can I merge, if travis is OK ?

**Comment by m-kuhn** [comment]
I think it conforms to the geojson specs, no?

**Comment by rldhont** [comment]
Yes it is. `null` is an accepted value.

**Comment by m-kuhn** [comment]
I'd say merge it

**Pull request merged**
