### PR TITLE
Travis: try container-based infrastructure

### PR DESCRIPTION
**Pull request by tomchadwin**
Triggered by sudo: false in .travis.yml

### CODE REVIEW

**Comment by tomchadwin** [comment]
Hadn't seen the .ci/travis shell scripts. We're a long way off doing with sudo.

**Comment by nyalldawson** [comment]
@tomchadwin unfortunately yes. There's issues filed with Travis to whitelist the various ppa dependencies we require, but no movement on them yet.

**Comment by tomchadwin** [comment]
Yes: I'm waiting for ubuntugis-unstable myself:

https://github.com/travis-ci/apt-source-whitelist/issues/38

Thanks for requesting it.

**Comment by m-kuhn** [comment]
I guess the worst part will be an old version of geos (I think we require at least 3.4 for GEOSNearestPoints_r) but the preinstalled postgis is linked against an older upstream version.

If that's gonna be replaced by a newer version, probably postgis will fail on us. We had to do some nasty tricks to use a non-upstream postgis version already on the sudo infrastructure.

My hope is now to be able to use a different geos version for QGIS than for server postgis.

**Pull request closed without merging**
