### PR TITLE
Reduce logging when no style is in DB

### PR DESCRIPTION
**Pull request by elpaso**
Move "No styles available on DB" messages to debug messages.

### CODE REVIEW

**Comment by elpaso** [comment]
CC @manisandro

**Comment by manisandro** [comment]
@elpaso LGTM

**Review by manisandro — APPROVED** [review]

**Comment by DelazJ** [comment]
Thanks @elpaso

**Comment by elpaso** [comment]
> Thanks @elpaso

np, I hope this helps with the doc tests.

**Comment by DelazJ** [comment]
I confirm that after two weeks, the docs repo is back to green (and no noise). Thanks again.

**Comment by DelazJ** [comment]
Need a backport for the 3.34 docs branch

**Pull request merged**
