### PR TITLE
Fix Threshold parameter for SAGA Watershed algorithm

### PR DESCRIPTION
**Pull request by luipir**
## Description
as described in http://www.saga-gis.org/saga_tool_doc/2.1.3/imagery_segmentation_0.html parameter can be Double not limited to Integer.

Fix inside the Geomove project [1] for Cartolab [2] (A Coruña University - Spain)

[1] http://cartolab.udc.es/geomove/
[2] http://cartolab.udc.es/cartoweb/

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with themInclude a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Thanks! Do you mind adding a unit test for this one? The only way we'll get a stable saga provider is to cover all these algs with individual tests

**Comment by luipir** [comment]
well I can add the test in test.yaml, but I'm not the best person to evaluate if the result is correct. My fix is only on parameter, so I can create the result for 0.5m and check that is really different from that with a 0 o 1m that is the value set if parameter is Integer.

**Comment by luipir** [comment]
that's why I didn't add the test... would be a test without a real deep evaluation that the result is correct. and I'm not sure to give the impression that a test can cover all possibile variation of the input parameters.

**Comment by nyalldawson** [comment]
I think it's still valuable to add, because it tests that processing can run the tool. We don't need to check the validity of the output - that's Saga's responsibility, not ours (in fact, you'll see that there's vector tests for saga with comments about invalid outputs... But again, we just need to test that the algorithm runs).

**Comment by luipir** [comment]
@nyalldawson added... btw I notices that with SAGA seems not possibile to specify output format differet to sdat or shp. Is it a known issue? I supposed the wrapper class would take care of data format conversion.

**Comment by luipir** [comment]
Just another note, I don't have a dataset where it's possibile to distinguish segmentation differencies due to thershold fracional value. A segmentation on a street level dem based on interploated point cloud data does not produce differences between x and x.5 thersholds

**Pull request merged**
