### PR TITLE
 Remove line breaks for a better python doc formatting 

### PR DESCRIPTION
**Pull request by DelazJ**
I don't know if this is the cleanest fix but i think it'll at least improve legibility of the parameters at https://qgis.org/pyqgis/master/core/Vector/QgsVectorFileWriter.html#qgis.core.QgsVectorFileWriter.writeAsVectorFormat

### CODE REVIEW

**Comment by nyalldawson** [comment]
I think this is already fixed by the indentation of the second parameter line - it's just that the docs still need updating after that fix. @3nids can you confirm?

**Comment by DelazJ** [comment]
hmmm `Last updated on 08:29 Apr 12, 2018.` doesn't seem to be a nice release date indeed! We should have an (daily) automatic build imho.

**Comment by nyalldawson** [comment]
Yeah I think this can be closed - I'm pretty certain the indentation is correct now

**Comment by 3nids** [comment]
yes, I gave it a try this is fixed.
I will push a new version as soon as I have fixed some internal issues here on my computer, hopefully by the HF.

The mechanism is in place to produce the docs on Travis, but due to the necessity of having sip 4.19.8+, I still failed to have a correct setup on Docker.
Will give it a try again soon.

**Comment by nyalldawson** [comment]
Indeed this is fixed in the new documentation build

**Comment by DelazJ** [comment]
Nice, @3nids.

**Pull request closed without merging**
