### PR TITLE
z factor handling fix for analysis' derivative filter & processing improvement

### PR DESCRIPTION
**Pull request by nirvn**
## Description
@nyalldawson , this PR fixes the Z factor handling in the analysis' derivative filter (from which hillshades and slopes are generated), as well as adjusting the minimum value for the Z factor in several processing algorithms.

Long story short, QGIS' processing can now create beautiful hillshades from NASA's SRTM DEMs.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Wow.... Wonder how long that's been broken for. My guess: as long as this class was around.

**Comment by nirvn** [comment]
@nyalldawson , that's what `git blame` says :).

**Comment by nirvn** [comment]
@nyalldawson , we probably want the analysis-specific commit backported to 2.18, don't we?

**Comment by nirvn** [comment]
Manually applied.

**Comment by nyalldawson** [comment]
Yes, backport please!

**Comment by nyalldawson** [comment]
Just a followup to this - do you mind adding a processing test for this with z factor <> 1? Given that the hillshade code has no direct unit tests, it seems safer to at least have a processing test guarding this.

**Pull request closed without merging**
