### PR TITLE
WMTS GetCapabilities and axis order (3.16 backport)

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

Backport of https://github.com/qgis/QGIS/pull/43280.

### CODE REVIEW

**Comment by rouault** [comment]
This backport with gazillions of commits looks wrong

**Comment by pblottiere** [comment]
> This backport with gazillions of commits looks wrong

Yep, Nyall force-pushed my branch :). I'll fix that.

**Comment by pblottiere** [comment]
>> This backport with gazillions of commits looks wrong

> Yep, Nyall force-pushed my branch :). I'll fix that.

Oh actually no, it's just the target branch which has been force pushed. Anyway, I just rebased .

**Comment by rldhont** [comment]
All tests are green ;-) thanks @pblottiere for the manual backport

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
Who can merge the backport to queued_ltr_backports?

**Pull request merged**
