### PR TITLE
Revert "fix and bring back scroll area into custom widgets"

### PR DESCRIPTION
**Pull request by nyalldawson**
This reverts commit 5dce8edb95fc2432dedcac3d860bd5d46b16a436.

The custom widget is still causing isseus - refs #18065

### CODE REVIEW

**Comment by nyalldawson** [comment]
@3nids ok to revert before release? Looks like this still has issues: https://issues.qgis.org/issues/18065

**Comment by nirvn** [comment]
Off the top of my head, I can remember at least half a dozen complaints about this on Twitter, mailing list, and redmine. It'd be ill advised to ship without the commit reverted.

**Comment by 3nids** [comment]
If this fixes an issue,yes.
But please leave the xml part in place as it was a least fixing part of the issue.

**Comment by nyalldawson** [comment]
> If this fixes an issue,yes.

Well, I've never been able to reproduce - so I can't confirm that. I'm just trying to see what we can do about the bug before release....

**Comment by nyalldawson** [comment]
> But please leave the xml part in place as it was a least fixing part of the issue.

Done

**Pull request merged**
