### PR TITLE
Default null size in size assistant

### PR DESCRIPTION
**Pull request by roya0045**
## Description

Just a quick PR proposing to set a default value of two for the NULL size in the data-defined size assistant. This should prevent other tickets such as #39882 

Changing the name of the variable might be a good idea too...

### CODE REVIEW

**Comment by nyalldawson** [comment]
The current zero value was by design -- if we default to anything else, then we risk creating misleading visualisations where a null value is easily mistaken for a valid value in the map. There was considerable discussion about this a number of years ago, and the decision made that hiding null points by default was the right move - basically better to hide these points and force the user to make informed choices as to ask appropriate null value instead of introducing  a dangerous default behaviour.

**Comment by nyalldawson** [comment]
Suffice to say, -1 to chance this setting

**Comment by roya0045** [comment]
@nyalldawson Good! In this case do you think there could be a way to separate the visuals from the rendered symbol? I'm thinking that using the minimal or median symbol size for representing the categories might be better than using the null value, especially if set to  to force the display of the other variable.

I just wasn't sure if there was a proper way to reder the symbols to represent how the other variable influenced the symbology.

going for a base value of 2 was a quick-fix. If you have a clue for forcing a rendering size on the symbol let me know, I'll try to look into it if I get enough free time.

**Comment by gioman** [comment]
> Suffice to say, -1 to chance this setting

@nyalldawson ok got it, but then we agree there is still a issue/bug such as https://github.com/qgis/QGIS/issues/39882 , correct?

**Comment by roya0045** [comment]
@gioman if you have the chance, could you validate if #39777 solves this issue, if so this would be great, otherwise a similar thing might be needed

**Comment by nyalldawson** [comment]
@gioman 
> ok got it, but then we agree there is still a issue/bug such as #39882 , correct?

Yes, but it's a very long standing issue -- https://github.com/qgis/QGIS/issues/19761. Basically legends don't work well with ANY data defined setting.

**Comment by gioman** [comment]
> @gioman if you have the chance, could you validate if #39777 solves this issue, if so this would be great, otherwise a similar thing might be needed

@roya0045 I tested the latest master and do not solves issues like https://github.com/qgis/QGIS/issues/39882

**Comment by gioman** [comment]
> @roya0045 I tested the latest master and do not solves issues like #39882

wait, I may have missing something.

**Comment by gioman** [comment]
> wait, I may have missing something.

no, that new config does not make any difference (in the context of issue like https://github.com/qgis/QGIS/issues/39882 )

**Comment by DelazJ** [comment]
>@gioman
> > ok got it, but then we agree there is still a issue/bug such as #39882 , correct?
 
> Yes, but it's a very long standing issue -- #19761. Basically legends don't work well with ANY data defined setting.

@nyalldawson, IMHO these are not the same issues. The older #19761 is about rendering data-defined values in layout (in a context of potential multiple combination of DD values on the properties), while the issue in #39882 is that the categorized parts of symbols are not rendered. They are not really DD properties since they could be simply generated using the value field.
I had reported this issue some time ago (#26926) and it seems it has got a fix by @elpaso in #7220

**Comment by roya0045** [comment]
Switching to draft, will try to find the best place to force the icon size to be not 0 when it is set to zero in the size assistant.

**Comment by roya0045** [comment]
Did some debugging, the symbol size attribute seems fine when passed in the legend, must be due to the transformer in the renderer? Would be hard to override anything unless the transformer knew it was for legend rather than the map...

**Pull request closed without merging**
