### PR TITLE
Update buttons in drag&drop relation editor widget

### LINKED ISSUE #43123: Widget parameters not persistent for relations in D&D designer
**Describe the bug**

When setting parameters for relations widget, the values *(show link button, add child feature, zoom to child feature, etc.)* are not kept after saving et reloading the project.

**How to Reproduce**

1. Consider having 2 tables (`parent` and `child`)
2. Create a relation between them (*Project - Propreties - Relations*)
3. Open propreties of `parent` layer and go to the *Attributes Form* panel
4. Select the relation (*Avalaible widgets - Relations*)
5. Uncheck all checkboxes *(show link button, add child feature, zoom to child feature, etc.)* [1]
6. OK
7. Save the project
8. Close and reload the project
8. Return to previous *Attributes Form* panel
9. Bug --> All checkboxes are checked [2]

For information, the checkboxes are fine after 7.

[1]
image

[2]
image

**QGIS and OS versions**

```
QGIS version
3.16.5-Hannover
QGIS code revision
58ba7c1ed6
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
actions_for_relations; 
geomapfish_locator; 
QuickOSM; 
quick_map_services; 
db_manager; 
processing
```

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #43123

### CODE REVIEW

**Comment by elpaso** [comment]
CC: @3nids @suricactus @signedav honestly I'm a little confused by the duplication of `buttons` as a member of `QgsAttributeEditorRelation` and as a config value of `RelationEditorConfiguration`, this PR seems to fix the issue but I'm happy to leave it to you for a proper fix, you have surely a better understanding of the recent changes, feel free to close this PR you think that there is a better solution.

**Comment by 3nids** [comment]
The buttons should be specific the relation editor config and not the widget config, I don't think this is the correct approach.
 We'll have a closer look and either merge this one or propose something else.
Thanks for this anyway!

**Comment by domi4484** [comment]
@elpaso @3nids I checked out this branch and I can still reproduce the bug.
If you uncheck "ALL" the checkboxes -> Apply -> reopen properties dialog -> all checkboxes checked. No need to close reopen qgis.
The explanation is that buttons flag get saved as string in the configuration. When all checkboxes are unchecked the string is empty, and by getting the flag value back `qgsFlagKeysToValue` returns the default value which is `AllButtons`.
But how can we solve this? We have to distinguish between empty string as "No config" and empty string as "No checkbox checked". Could we use something like this?
```c++
if(config.contains("buttons") == false)
  return AllButtons;
if(config.value("buttons").isEmpty())
  return NoButtons;
return qgsFlagKeysToValue(config.value("buttons"));
```

By quickly debugging this I could not understand why is the configuration somehow duplicated. I have just seen some comments like "pre QGIS 3.18 compatibility" in `QgsAttributeEditorRelation::loadConfiguration`. Maybe is the additional config there for compatibility reasons? I can give it a closer look tomorrow or wednesday...

**Comment by 3nids** [comment]
Good catch @domi4484, we can use a NoButton enum entry (as 0), and it solves the issue.

superseded by #43479

**Pull request closed without merging**
