### PR TITLE
Show "Untitled Project" in title bar for new unsaved projects, improve project dirtying

### PR DESCRIPTION
**Pull request by nyalldawson**
Also shows current profile name in title bar, if multiple profiles exist.

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
@nyalldawson Mmm, fail to see the changes after building this PR?

I do not have a * anymore in front of QGIS, and I fail to see 'untitled' when I start a new one?

Created a fresh profile. Am I missing something?

selection_331

The aa project in the images is an saved project in which I duplicated a layer and did some panning (so should be 'dirtied' I think)?
The front one is a fresh project.

**Comment by nyalldawson** [comment]
903c2af is from a different branch?

**Comment by rduivenvoorde** [comment]
Duh... sorry sorry, messing up my PR-installs :-(
Yep, working: 

selection_333

Thanks especially for the showing the profile \o/

What about your idea to not show [default] profile ?

Aren't the [ ] brackets too heavy?

**Comment by SrNetoChan** [comment]
I actually like the brackets. Makes it stand a bit more that curve ones.

**Comment by Gustry** [comment]
I think it looks good like this too.

> What about your idea to not show [default] profile ?

It shows the `[default]' because you have more than one profile. If you have only one profile, it won't be shown (AFAIK).

**Comment by nyalldawson** [comment]
> I actually like the brackets. Makes it stand a bit more that curve ones.

+1

> It shows the `[default]' because you have more than one profile. If you have only one profile, it won't be shown (AFAIK).

Correct - but I'll extend this so that it's NEVER shown for the default profile.

**Comment by nyalldawson** [comment]
> What about your idea to not show [default] profile ?

Done

**Comment by rduivenvoorde** [comment]
Thanks @nyalldawson !!

Ps, not going to compile this again... have reused my 'pr' directory for another pr now...
How do you handle working in all those branches (and rebuilding them....)?
I cannot switch branches without (almost) a full rebuild... Takes so much time/cpu-power to do all this switching....

**Comment by nyalldawson** [comment]
@rduivenvoorde

Looks into setting up ccache, which will speed up build times when switching between branches. I also use git work-tree to check out branches without switching my main source folder (and build folder) to the new branch.

**Pull request merged**
