### PR TITLE
[FEATURE] New simplify + smoothing expression functions

### PR DESCRIPTION
**Pull request by nyalldawson**
Exposes simplification and smoothing algorithms to expression engine, via:
- simplify(): applies Douglas-Peucker geometry simplification
- simplify_vw(): applies Visvalingam-Whyatt geometry simplification
- smooth(): smoothes a geometry

Carto tip: use smooth along with geometry generators to minimise the typical "GIS" noded look of rendered geometries!

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson, what about having an optional parameter in the simplify() function to choose the method/algorithm instead of creating extra functions (such as simplify_vw() ) for individual algorithms?

**Comment by nirvn** [comment]
BTW, yay for that! :) it'll be super useful when exporting to SVGs.

**Comment by nyalldawson** [comment]
@nirvn

> what about having an optional parameter in the simplify() function to choose the method/algorithm instead of creating extra functions (such as simplify_vw() )

Two reasons: 
1. I'm following the PostGIS approach with these two functions
2. I don't particularly like functions with named string arguments. They are a bit clumsy and fragile.

**Comment by nirvn** [comment]
Sounds good :)

**Comment by mhugo** [comment]
Thanks btw, great feature !

**Pull request merged**
