### PR TITLE
[FEATURE] QGIS - GeoNode Integration: Integrate with QGIS Browser Pan…

### PR DESCRIPTION
**Pull request by timlinux**
Please see https://github.com/qgis/QGIS/pull/4816 for an extended discussion about this feature. In this PR we will work to address the various concerns raised and provide the code in a way that is acceptable for those who have commented on #4816.

I promise this time I won't hit the merge button until we get some big 👍 's to merge :-)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Thanks @timlinux! Hope there's no hard feelings here :) I'll post an updated review asap.

**Comment by nyalldawson** [comment]
Closed and reopened to trigger updated doxygen test on Travis

**Comment by nyalldawson** [comment]
@3nids this is still passing the dox test... did you merge all your changes?

**Comment by 3nids** [comment]
Yep I did. Sorry, I won't be able to look at it today.

**Comment by 3nids** [comment]
It's like if there is only 1 new member coming in this PR.
When merging doxygen stuff yesterday:
screen shot 2017-08-07 at 09 51 43
and from this PR:
screen shot 2017-08-07 at 09 52 28

**Comment by timlinux** [comment]
@nyalldawson no worries! 😁

**Comment by timlinux** [comment]
@elpaso Hi. Have you had any more thoughts about implementing this as a provider? Are you still on the track of splitting the provider interface into two parts:

* the data provision interface
* the connection configuration UI / API

? Or do you propose that for now we just implement this as a provider with no capabilities? I'm still not sure how well this fits as a provider since it is more about discovering layers than providing them (it hands off the actual data provision to existing providers anyway).

@nyalldawson @m-kuhn could I also ask you if you could point us in a better direction if you are not happy with this stuff going in core/gui - bearing in mind that one of the key things we would like to deliver is the ability for 3rd party python plugins to be able to push / pull styles, metadata, data to and from a GeoNode instance with the framework we build here. For me that rules out implementing as a python plugin since I really don't like the idea of plugins that depend on other plugins to work.

Would it be helpful for moving the discussion forward if we step back and write a QEP explaining what the outcomes should be?

Thanks all for your inputs!

Regards

Tim

**Comment by m-kuhn** [comment]
Hi @timlinux, nice to see you follow up on this.
My concerns were mostly on code quality. API documentation, passing parameters by const references and putting code into the right modules. Have a look at the old pull request, I left a lot of comments in there that should help you sort things out.

About the idea of splitting things up, it sounds like it would nicely encapsulate code and prevent duplication of logic. At the same time I realize that there is also a certain risk of over-engineering and I also see that it's a bit of extra work for the use case you are targeting. I don't feel comfortable enough with the code and alternative server side components to comment on this topic.

**Comment by elpaso** [comment]
@timlinux I can only comment on the architecture. 

I'm still convinced that the GUI side of the provider should be decoupled, I actually have another use case for that: a single provider should be able to provide more than a single UI for configuring the data sources, WFS for instance already has two (one for XYZ and one for WMS) and I need a new entry for geopackage (that is handled by gdal and ogr).

I think that we should follow the same route taken by the browser tree root nodes ( that uses `QgsDataItemProvider` and `QgsDataItemProviderRegistry` ) by creating  new classes `QgsSourceSelectProvider` and `QgsSourceSelectProviderRegistry` .

See: https://www.qgis.org/api/classQgsDataItemProviderRegistry.html

A provider or a plugin (C++, Python etc.) will then be able to provide any number of source select interfaces (probably keyed in some way so that we can retrieve the right one by key in case we need it).

This would replace/extend the actual source select function `selectWidget`

Another possible approach (maybe simpler but I did not check all the implications) would be to refactor the `selectWidget` to return a list of instances/structs that would include for each item:
- the widget
- the label
- the svg icon for the unified dialog

I need to sketch this up a bit and I hope I will be able to work on that in the near future, but if you have any resources for starting now the work on this small refactoring I would be happy to help/review that.

Maybe we need a small QEP ....

**Comment by elpaso** [comment]
@timlinux I've started this: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/101

**Comment by nyalldawson** [comment]
Superseded by #5153

**Pull request closed without merging**
