### PR TITLE
Split Options Rendering tab into more contextual and less scarying pages

### PR DESCRIPTION
**Pull request by nyalldawson**
Supersedes https://github.com/qgis/QGIS/pull/49437 by instead moving the options into separate pages

image

image

image

Note: unlike in #49437 I've left the antialias setting in the general rendering page as this setting applies to more than just vector layers.

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , I like the revamp a lot. One thing, what about removing the checkbox for the [x] maximum cores to use for map rendering in favor of having a cleared state for the spin box with a 'all available core' placeholder text? I feel otherwise people might think that unchecked max. core means it'll be one core or something.

**Comment by DelazJ** [comment]
nice. And if we could do a bit of widgets alignment/resizing, it could be really great. #49437 tried to address those issues also.
Thanks @nyalldawson

**Comment by nyalldawson** [comment]
@DelazJ 
> nice. And if we could do a bit of widgets alignment/resizing, it could be really great. https://github.com/qgis/QGIS/pull/49437 tried to address those issues also.

Done

**Comment by nyalldawson** [comment]
@nirvn 

>  I like the revamp a lot. One thing, what about removing the checkbox for the [x] maximum cores to use for map rendering in favor of having a cleared state for the spin box with a 'all available core' placeholder text? I feel otherwise people might think that unchecked max. core means it'll be one core or something.

Done

**Review by nirvn — APPROVED** [review]

**Pull request merged**
