### PR TITLE
 Add an "interpretation" option for vector elevation profiles 

### LINKED ISSUE #48341: [profile tool] Add option to draw a line between points
### Feature description

When sampling a point layer, drawing a line between points could be useful.

image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
Choices are "individual features" (the default behavior) or "continuous surface". The new Continuous Surface option is designed for vector layers which represent a continuous elevation surface, e.g contour lines or surveyed elevation points. When selected, the elevation chart will be rendered as a surface instead of separate features by joining the sampled elevation results into a continuous line.

There's also the same option exposed as for raster and mesh layers where the appearance can be toggled from a single line to a "fill below" symbol.

Fixes https://github.com/qgis/QGIS/issues/48341

https://user-images.githubusercontent.com/1829991/166127120-79ae4c96-6728-4760-a57e-1420e2184358.mp4

### CODE REVIEW

**Comment by nicogodet** [comment]
I just noticed in your screencast that symbol in layer tree is not changed after switching to continuous surface.

Would it be possible to add the possibility to keep the point symbol in continuous surface ? It would help to know when it's real data and when it's interpolated data.

**Comment by Houska1** [comment]
Great feature add. Should the terminology be "interpolation" rather than "interpretation" though?

**Review by wonder-sk — APPROVED** [review]
Very cool.

**Comment by nyalldawson** [comment]
@Houska1 
> Should the terminology be "interpolation" rather than "interpretation" though?

It's not really "interpolation" though, and I want to avoid any misinterpretation that what's happening here is that the surface is being interpolated. (Eg. if the curve line is close to a feature but doesn't actually touch it then the height from that feature isn't considered in any way in the profile plot, unlike what you'd expect to see if some form of interpolation was actually occurring).

**Comment by nyalldawson** [comment]
@nicogodet 

> I just noticed in your screencast that symbol in layer tree is not changed after switching to continuous surface.

Fixed

> Would it be possible to add the possibility to keep the point symbol in continuous surface ? It would help to know when it's real data and when it's interpolated data.

Done

**Pull request merged**
