### PR TITLE
Use QDiffuseSpecularMaterial instead of QDiffuseMapMaterial on qt 5.10+ 

### PR DESCRIPTION
**Pull request by nyalldawson**
QDiffuseMapMaterial is deprecated

### CODE REVIEW

**Comment by nyalldawson** [comment]
@NEDJIMAbelgacem look ok to you?

**Comment by nyalldawson** [comment]
(theoretically QDiffuseSpecularMaterial gains us the ability to set a normal map and specular map -- but I've only succedeed in getting the specular map working. Normal maps seem to just result in a dark flat texture :confused: )

**Comment by NEDJIMAbelgacem** [comment]
> (theoretically QDiffuseSpecularMaterial gains us the ability to set a normal map and specular map -- but I've only succedeed in getting the specular map working. Normal maps seem to just result in a dark flat texture  )

That's most probably because the normal coordinates are not being passed to the vertex buffer in the tesselator and while debugging you can't know about that easily since the shader comes from Qt3D and not from QGIS.

**Comment by NEDJIMAbelgacem** [comment]
LGTM @nyalldawson !

**Pull request merged**
