### PR TITLE
Make inserting dynamic text easier for users

### PR DESCRIPTION
**Pull request by nyalldawson**
The new "Add Item" -> "Dynamic Text" menu contains a bunch of preset
handy dynamic text expressions which users can use to insert a label
automatically containing the corresponding expression. E.g.

Add Item -> Dynamic Text -> Layout Name

will insert a label containing the expression [% @layout_name %].

This raises discoverability and user-friendliness of inserting
dynamic labels

Peek 2021-01-11 12-27

### CODE REVIEW

**Comment by nirvn** [comment]
Nice refinement. In terms of UI, could we use the toolbar label item to add the menu ala add shape button:
image

I'd have the menu be something like:
```
Empty text item
----
Current date
Map Properties
Field
...
----
```

**Comment by nirvn** [comment]
(it'd mean that in the Add item's menu, you'd use the add label as a sub menu holder instead of adding a new dynamic text)

**Comment by nyalldawson** [comment]
@nirvn I considered that, but it adds an extra click to the common use case of inserting a non-dynamic text label, so I'm not a fan.

**Comment by nirvn** [comment]
@nyalldawson , yeah, I thought of that but I still think the UI/UX harmony benefit outweighs the cost (extra click) here.

**Comment by nirvn** [comment]
You could also do what gimp does these days which is auto open the menu when the mouse hovers the toolbar button. Then you avoid the extra click. It's a nice touch.

**Comment by nirvn** [comment]
@nyalldawson , thanks for the improvement on placement. Based on the little chat we had earlier highlighting the API limitations, I withdraw my UI/UX ask above, until QGIS 4.0! :wink:

**Pull request merged**
