### PR TITLE
rename auth methods and providers targets

### PR DESCRIPTION
**Pull request by 3nids**
so they are better spotable in the list:

image

### CODE REVIEW

**Comment by nirvn** [comment]
Wouldn't you then want to do the same for providers?

**Comment by nirvn** [comment]
@3nids , you'll need to rename some reg ex patterns in /src/ meant to find auth method et cie libraries.

**Comment by nirvn** [comment]
Around here for auth method: https://github.com/qgis/QGIS/blob/4ba34a4503f367e77578827d2781837b3d84adf4/src/core/auth/qgsauthmethodregistry.cpp#L61

I assume there's something similar for providers.

**Comment by 3nids** [comment]
> @3nids , should we update the search pattern used on windows to be slightly more restrictive here? 

no opinion here. ping @jef-n ?

**Review by nirvn — APPROVED** [review]

**Comment by jef-n** [comment]
How about subdirectories instead of prefixes?

**Pull request merged**
