### PR TITLE
Clang format

### PR DESCRIPTION
**Pull request by m-kuhn**
Just sending this for a test build (copy from qfield) , no time to embark on all the required cleanup right now ...

### CODE REVIEW

**Comment by m-kuhn** [comment]
sipify gives plenty of

```
! Sipify error in src/gui/ogr/qgsvectorlayersaveasdialog.h at line :: 41
! Unexpected content: enum should be followed by {
```

I didn't find a way to remove the linebreak after the enums.
@nyalldawson would that be an "easy" sipify fix?

**Comment by nyalldawson** [comment]
@m-kuhn try https://github.com/qgis/QGIS/commit/6fe6c9568081d12d305506046b5a2108f5946443

**Comment by m-kuhn** [comment]
Thanks, that solved the first series of problems.

The main problem I see right now is around `%SipCode`, as these tend to confuse the formatter.
I tried with `// clang-format off`, but this only disables rewriting a section but apparently doesn't prevent the formatter from being confused.

What did show some promising results is:

```
#ifdef SIP_RUN // SIP_COMMAND: %TypeCode
....
#endif // SIP_COMMAND: %End
```

but even with that indentation was a tiny bit off (and I just checked one problem in `qgsapplication.h`)

**Comment by nyalldawson** [comment]
@m-kuhn 

Does 

```
#ifndef__clang_analyzer__
#ifdef SIP_RUN
....
#endif
#endif
```

help?

**Comment by m-kuhn** [comment]
> @m-kuhn
> 
> Does
> 
> ```
> #ifndef __clang_analyzer__
> #ifdef SIP_RUN
> ....
> #endif
> #endif
> ```
> 
> help?

unfortunately not

**Pull request closed without merging**
