### PR TITLE
Add method to set QgsFeature geometry directly from QgsAbstractGeometry

### PR DESCRIPTION
**Pull request by nyalldawson**
Allows

    feat.setGeometry(QgsPoint(1,2))

instead of the more obscure

    feat.setGeometry(QgsGeometry(QgsPoint(1,2)))

### CODE REVIEW

**Comment by nirvn** [comment]
It's a nice shortcut. I however wonder whether it comes at the cost of making it harder for newcomers to understand the mechanics of QgsFeature <-> QgsGeometry <-> QgsAbstractGeometry.

I.e., if someone sees `feat.setGeometry(QgsPoint(1,2))`, he/she could expect that feat.geometry returns a QgsPoint, not a QgsGeometry.

**Comment by nyalldawson** [comment]
For reference: this came directly out of confusion during a PyQGIS workshop @Nathanw2 ran today. I can see your point though.

**Comment by nyalldawson** [comment]
What if I add a note to the dox that this is a shortcut for calling f.setGeometry(QgsGeometry(geometry))?

**Comment by nirvn** [comment]
@nyalldawson , yeah, the dox note would help. I'm osculating between -0 to +0.1 :wink: but my hesitation shouldn't be a blocker here. If you, @NathanW2 , and others feel comfortable, that's fine by me.

**Pull request merged**
