### PR TITLE
WIP: Enable multi-os builds for travis

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by michaelkirk** [comment]
Hi! I took a stab at this a while back too:

In case it's useful:
https://github.com/qgis/QGIS/compare/master...michaelkirk:feature/mac_os_on_travis

My problem at the time was that `brew install` was soooo slow that nothing was even close to finishing before travis ci killed the build.

**Comment by nyalldawson** [comment]
@michaelkirk thanks! very timely :) do you have a link to one of the travis outputs from your build?

**Comment by michaelkirk** [comment]
This was a while ago, so it's a bit hazy, but I'm happy to answer any questions. Brew install is where all the time is - I don't think I ever got to the point of actually building QGIS.

Here is an example of one job that timed out:
https://travis-ci.org/michaelkirk/QGIS/jobs/49247139

I tried various hacks on getting it to speed up, but never made much headway. I was also discouraged by the fact that so many osx tests were failing. So also in my branch was a way to mark tests in OSX as "known-to-be-failing" in hopes that we could start making forward progress with the test suite with the help of CI to ensure we weren't breaking *more* tests in the meanwhile.

Also note that there are 2 cpu's on the boxes travis provisions for mac testing. I never got so far as figuring out how to make sure they were utilized in brew.

**Comment by nyalldawson** [comment]
@michaelkirk I'm not sure if something's changed with the qgis brew, or if it's just upgrades to Travis, but I'm able to get the dependencies installed now and cmake is happy. Next step getting the build to start and tests to run...

BTW, all tests should be passing on OSX with master, so there shouldn't be any special handling needed there now.

**Comment by jef-n** [comment]
And I tried [appveyor](https://github.com/jef-n/QGIS/tree/appveyor) - but our build is too long to fit into their free slots (even with an extension to 1hr)

**Comment by m-kuhn** [comment]
Nice!

@jef-n where is the time lost in appveyor? also in dependency installation?
I noticed that appveyor provides good integration with nuget for dependencies (and deployment) so I wonder if that would speed it up.

**Comment by nyalldawson** [comment]
manually merged

**Comment by m-kuhn** [comment]
Sweeet!!!

**Comment by jef-n** [comment]
@m-kuhn cmake starts after about ~6min - that how long adding flex, poppler and doxygen to the preinstalled cygwin and downloading and extracting 221MB of osgeo4w packages  takes.     Int the last two minutes of the hour tests are run to 100/150.   The time between is spend on building...

**Comment by michaelkirk** [comment]
The successful build took 45 minutes to complete. Be aware that [travis kills builds at 50 ](http://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts) minutes. So if there is some variance where a test runs long, it might error out. But more important is to note that this will get worse as the test suite gets bigger/slower. We can get up to 120 minutes with a paid travis account.

Super happy to see CI for OSX, as I use osx half the time. Thanks @nyalldawson!

**Comment by michaelkirk** [comment]
Just, FYI:

**big spenders of CI time on osx:**
18 minutes: installing homebrew dependencies
3 minutes: running the tests
22 minutes: compiling*

*ci script took 25 minutes, including building and running tests, but tests reported 3 minute run time. I'm assuming the rest (22) is compilation.

**Comment by m-kuhn** [comment]
@jef-n

I don't even get that far. After 40 minutes it stops without finishing
the build. If you know how to get it faster or more build time I think
that disabling WITH_DESKTOP could help to at least get the library tests
to run.

**Comment by jef-n** [comment]
Yes, 40min is the default.  I asked for an extension and got 1h - but that's still not enough.  Unfortunately the log of the almost successful run got lost when I retried - which didn't get as far before - probably also depends on their load...

**Comment by m-kuhn** [comment]
If you still have this extension, could you try WITH_DESKTOP=OFF?

And we probably also could disable:

-D WITH_ASTYLE=FALSE
-D WITH_GLOBE=FALSE
-D WITH_TOUCH=FALSE
-D WITH_QWTPOLAR=FALSE

**Comment by nyalldawson** [comment]
@michaelkirk 
>I'm new to this, but wanted to double check that these are OK.
>e.g. sp_background_rect_w_offset_mask.png
>seems to be introducing some new artifacting. Is that normal?

Yes, all the test images with the _mask.png suffix determine a pixel tolerance against the actual reference images. So a white pixel in the mask means that the pixel's color won't be tested, a black color requires an exact match, and grey shades some tolerance in between. This is required due to the way different platforms have slight differences in rendering of shapes and text. Some of the updates in that commit are cutting it pretty close, but the actual skeleton of the labels in the mask are still black so they will still be correctly testing the placement of these labels. 

Those mask updates where required as I've previously never been able to get the labeling server tests to run locally to verify!

**Comment by nyalldawson** [comment]
@michaelkirk 
>The successful build took 45 minutes to complete. Be aware that travis kills builds at 50 minutes. So if there is some variance where a test runs long, it might error out. But more important is to note that this will get worse as the test suite gets bigger/slower. We can get up to 120 minutes with a paid travis account.

There's a few inefficiencies I think we can improve to shave down this build time. For instance, it looks like the brew install of qgis also installs postgis as a dependency. This isn't required - we just need the client library for QGIS and the Travis environment already has a working PostGIS install ready to go. In fact, the brew installed postgres seems to clash with the preinstalled one and meant I had to disable the postgres provider tests.

I'm not knowledgeable enough about OSX development or homebrew to fix this right now (OSX really isn't my thing - I'm just super-passionate about unit tests and code quality!), but this could be reevaluated if we start hitting the build limit.

>Super happy to see CI for OSX, as I use osx half the time. Thanks @nyalldawson!

Thanks in turn! Your groundwork definitely saved me a lot of time with this.

**Pull request closed without merging**
