### PR TITLE
Ctrl zoom

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR changes the shortcuts to swap to the zoom in/out tool to Ctrl+Alt +/-, and makes Ctrl + and Ctrl - trigger an immediate zoom in/out.

Having Ctrl +/- perform an immediate zoom in/out is standard across almost all apps with a zoom facility, so we should respect that same behavior.

This change also helps bring canvas and composer behavior closer together.

@anitagraser thoughts?

### CODE REVIEW

**Comment by NathanW2** [comment]
Big +1 for consistency though the application

**Comment by anitagraser** [comment]
+1 for consistency

It would be great if we could also achieve that for selection tool key
modifiers

**Comment by nyalldawson** [comment]
@anitagraser that was done in cd9f47ae45e4b664356588e6fb6c63c0b3c43aa7

**Comment by anitagraser** [comment]
​Thanks, great to know! I missed that :-)​

**Pull request merged**
