### PR TITLE
Fix handling of phong shader ambient color

### PR DESCRIPTION
**Pull request by nyalldawson**
This looks to be broken in upstream Qt too!

The consequence is that we get different shader behaviour after this fix depending on whether data defined coloring is enabled and we are using our shader, or data defined coloring is disabled and we are using qt's shader.

If this fix is correct, I'd propose that we work around the qt bug by avoiding QDiffuseSpecularMaterial and using a fixed downstream material instead..

### CODE REVIEW

**Comment by nyalldawson** [comment]
Alternative to https://github.com/qgis/QGIS/pull/55638

**Comment by nyalldawson** [comment]
Filed upstream as https://bugreports.qt.io/browse/QTBUG-120241 -- let's see what they say.

**Comment by nyalldawson** [comment]
Tests won't make much sense here until https://github.com/qgis/QGIS/pull/55654 is merged first...

**Comment by nyalldawson** [comment]
Ok, definitely looks like an upstream issue: https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-77665

**Comment by wonder-sk** [comment]
Agreed, this looks like the correct formula to me, and yeah we will need to provide our own "basic" phong material (fortunately we only need OpenGL shader, without GL ES or RHI variants).

On a slightly unrelated matter, I think ultimately it would be good if we get rid of the Phong material (and its variations), and only use PBR materials - the Phong shading is notoriously hard to set up for some good consistent looking results...

**Comment by nyalldawson** [comment]
> On a slightly unrelated matter, I think ultimately it would be good if we get rid of the Phong material (and its variations), and only use PBR materials - the Phong shading is notoriously hard to set up for some good consistent looking results...

That's my experience too. I think part of the issue is that the qt implementation has no way of setting the weights for the different factors, so eg the only way you can tone down the specular is by counterintuitively  setting a dark specular colour (and then you lose the saturation of the colour as a result). If we go for our own Phong shaders everywhere then I think we should add a control over these factors. 

... And maybe instead of using qt's metal rough material we just go for our own shader from day one 😉😂

**Pull request merged**
