### PR TITLE
Fix broken manual rotation anchor point setting via ctrl+click

### PR DESCRIPTION
**Pull request by nyalldawson**
Ctrl+clicking to set the manual rotation point had no effect, and the selected rotation point was always reset as soon as the rotation action started.

Apparently this has been broken for some time (confirmed broken since 3.4 at least!).

Also add tests.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@3nids can you take a look at this please?

**Comment by 3nids** [comment]
This was not broken for me:
If not feature was selected, you first click on the one you want to rotate, then ctrl+click to set anchor point.
If a feature (or more) is selected, you could ctrl+click directly.

In both cases, the anchor point works for me.

Your code looks good though, but I did not compile it yet.

**Comment by nyalldawson** [comment]
@3nids ahh - you're right. I didn't realise you had to set the point after starting rotation. I've confirmed this still works after this fix, and added a new unit test covering this behavior too.

**Comment by nyalldawson** [comment]
Manually backported to https://github.com/qgis/QGIS/pull/40712

**Comment by DelazJ** [comment]
@nyalldawson can you explain what's the new behavior you added? Worth documenting? Thanks.

**Comment by nyalldawson** [comment]
@DelazJ previously you could only set the anchor during the rotation operation (ie after clicking a feature). Now you can set it before starting the rotation. I'd recommend the documentation only describes the easier use case of setting the anchor point BEFORE the rotation.

**Comment by roya0045** [comment]
Did you want me to integrate those changes or you already have a commit lined up?

**Pull request merged**
