### PR TITLE
Try to reactivate msys2 workflow

### PR DESCRIPTION
**Pull request by pblottiere**
(follow up https://github.com/qgis/QGIS/pull/53803)

### CODE REVIEW

**Comment by MehdiChinoune** [comment]
Try passing `-DWITH_DRACO=OFF`, because there is no draco package for MSYS2 yet.
Draco was added in https://github.com/qgis/QGIS/commit/40ecc548d85c232e398e4cd799792d0ee2e3a966

**Comment by pblottiere** [comment]
Thanks for your input @MehdiChinoune :+1:

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@MehdiChinoune this msys2 workflow is taking upwards of 5 hours to complete -- that's too long to be usable :disappointed:  Do you have any ideas to speed it up so that we don't have to re-disable it?

**Comment by MehdiChinoune** [comment]
I see it takes less than an hour for many jobs https://github.com/qgis/QGIS/actions/workflows/mingw-w64-msys2.yml
Feel free to disable it.

**Pull request merged**
