### PR TITLE
Allow to use API without QgsApplication instance

### PR DESCRIPTION
**Pull request by 3nids**
Custom widgets could not be launched in designer since QgsApplication was not initialized.

This changes the creation of the members by grouping them in a structure to allow their creation at once. Hence, in all static getters, if there is no app instance, they are initialized and the proper one is returned.

kudos to @nyalldawson for the advices.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Not quite - I'd go for something more like https://github.com/nyalldawson/QGIS/commit/2144b6de756c54b82c0c4dc1141b3c11252d18ac

This approach ensures that the returned members are usable (the original commit here will always return a new member). 

So basically:
- if QgsApplication instance is available, use the members from that
- if not, check if a static ApplicationMembers is available, if so , use that
- if not , create a new static ApplicationMembers and use that

The unit tests in test_qgsnoapplication.py should be expanded to cover all these members and also the behaviour of getting/setting null representation when no QgsApplication instance is available.

**Comment by 3nids** [comment]
thanks a lot. Will do.

**Comment by 3nids** [comment]
done. There is still an issue with QgsDataItemProviderRegistry not being initiliaized (done in initQgis).

**Comment by nyalldawson** [comment]
Looks good to me. I'd appreciate a second opinion if there may be a better way to do this. @m-kuhn @wonder-sk?

**Comment by 3nids** [comment]
do you think its initialization should stay in `initQgis` or shall it be done in `ApplicationMembers` constructor?
if not, this means either:
* remove `mDataItemProviderRegistry` from `mApplicationMembers`
* return a `nullptr`

**Comment by wonder-sk** [comment]
The PR looks fine to me.

One thing worth looking at for QGIS 3.0 is how do we actually want people to use QgsApplication:
- if we move towards static methods in QgsApplication, should we get rid of non-static methods? (I see we have mostly moved away from non-static methods)
- do we need QgsApplication to be subclass of QApplication?
- there are too many way how tests / 3rd party apps can initialize QGIS libs (init() vs initQgis() vs creating QgsApplication instance) and configure paths (env vars vs setPrefixPath()). It may be good to settle on one and only correct way...

**Comment by 3nids** [comment]
Still crashing though, and no idea why I get a seg fault in the test. 

I agree the situation is not really clear with all these initializers. Do you think we can combine them all together?

**Comment by wonder-sk** [comment]
> I agree the situation is not really clear with all these initializers. Do you think we can combine them all together?

I think it is all fixable. I would suggest this approach:
- QgsApplication should not be derived from QApplication
- it should not be allowed to make instances of QgsApplication - all methods would be called as static methods
- move bits of functionality that currently require QgsAplication instance elsewhere (e.g. customization support, global variables)
- QgsApplication::init() would do all the init work - the only way to initialize core library. All config for init would be done through env variables if necessary. init() should be also better documented regarding how it actually works (what env vars are considered and in what order)
- setPrefixPath() should be removed - or just be a wrapper for setup of env variable
- QgsApplication could be actually renamed to something else, maybe QgsCore or similar

**Comment by 3nids** [comment]
Merging as is for a temporary fix for custom widgets.

**Pull request merged**
