### PR TITLE
API changes to QgsGeometry::isEmpty()/isNull()

### PR DESCRIPTION
**Pull request by nyalldawson**
Implements an easy QGIS3 api todo - see https://github.com/qgis/qgis3.0_api/issues/72

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'm also thinking QgsGeometry::isGeosEmpty should be removed. Theres no strong use case for it now and the geometry api is cluttered enough as is.

**Comment by wonder-sk** [comment]
:+1: 

If isGeosEmpty() and isEmpty() give exactly the same results, we can get rid of isGeosEmpty(). I am curious whether they are equivalent... it would probably require a check in GEOS sources. I have tried to find the exact definition of the "empty" predicate, but I have either didn't look well enough or the SQL/MM standard is not available for free :angry: 
http://www.iso.org/iso/home/store/catalogue_ics/catalogue_detail_ics.htm?csnumber=60343

**Comment by nyalldawson** [comment]
> If isGeosEmpty() and isEmpty() give exactly the same results, we can get rid of isGeosEmpty(). I am curious whether they are equivalent... it would probably require a check in GEOS sources.

Done, and they should be. The only difference between isEmpty and isGeosEmpty is that isGeosEmpty returns false for a null geometry. I believe this is wrong and confusing - it's easier for api users if a null goemetry also returns true to isEmpty so that a single check can be used (`if geom.isEmpty()` vs `if geom.isNull() or geom.isEmpty()`)

**Comment by nyalldawson** [comment]
Spell check keeps timing out, should be safe to merge anyway

**Pull request merged**
