### PR TITLE
[DbManager] Materialized views (fixes #13829, fixes #13697)

### PR DESCRIPTION
**Pull request by SebDieBln**
This PR makes DbManager aware of PostGIS materialized views, allowing to
- delete materialized views ([Redmine #13829](https://hub.qgis.org/issues/13829))
- run the command `REFRESH MATERIALIZED VIEW` ([Redmine #13697](https://hub.qgis.org/issues/13697))

### CODE REVIEW

**Comment by mach0** [comment]
@brushtyler dbmanager is your part isnt it?

**Comment by brushtyler** [comment]
@mach0 yes, it is.
@SebDieBln It looks good, I'm testing it right now.

**Comment by brushtyler** [comment]
@SebDieBln Good job, it works like a charm.
This commit include 2 parts: a fix (#13829) and a feature (that's what the ticket #13697 says)... and we are in feature freeze. Please, split this PR, otherwise I cannot merge it until the release.

**Comment by brushtyler** [comment]
Ok, I can just cherry-pick the right commits (I haven't seen it before).

**Comment by SebDieBln** [comment]
@brushtyler 
> and we are in feature freeze

True!

> I can just cherry-pick the right commits

So I understand I don't have to do anything, you pick the first three commits for the bugfix and the last one when 2.14 is out and then you close this PR. Correct?

**Comment by brushtyler** [comment]
> you pick the first three commits for the bugfix
Merged, thanks.

> and the last one when 2.14 is out and then you close this PR.
Yes, we must wait a while.

**Comment by SebDieBln** [comment]
Just linking to the cherrypicked commit for the bugfix: 560007846a4577767cf1f78d2e99a3a737be3331.

**Comment by nyalldawson** [comment]
Are we ok to merge this one now?

**Comment by SebDieBln** [comment]
> Are we ok to merge this one now?

:+1: from me (for cherry picking the last commit 5680908e15128759498dae7a89767919b6fea89c)

**Comment by m-kuhn** [comment]
Cherry-picked 5680908 before we miss yet another slot.
Thanks a lot @SebDieBln

**Pull request closed without merging**
