### PR TITLE
Avoid crash when saving edits after adding a geojson column

### LINKED ISSUE #51262: Crash when adding new field to geojson via feautre attribute table
## User Feedback

Adding a new field to a geosjon file via the table attribute viewer, then trying to save the edit.
Note that it still will work when adding fields via _layer properties_ --> _Fields_

image

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00089600 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QVariant::~QVariant :
QgsSQLiteExpressionCompiler::operator= :
QgsSQLiteExpressionCompiler::operator= :
QgsSQLiteExpressionCompiler::operator= :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsCachedFeatureWriterIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsAttributeTableModel::loadLayer :
QObject::qt_static_metacall :
QObject::qt_static_metacall :
QgsVectorLayer::emitDataChanged :
QObject::qt_static_metacall :
QgsPrecalculatedTextMetrics::count :
QgsVectorLayer::commitChanges :
QgsProject::commitChanges :
QgisApp::saveVectorLayerEdits :
QgisApp::saveEdits :
QgsAttributeTableDialog::mActionSaveEdits_triggered :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

### Steps to reproduce the issue

1. open QGIS
2. create scratch layer
3. create one feature
4. save scratch layer as geojson
5. open table attributes 
6. turn on editing for geojson layer
7. create new field
8. save edits

### Versions

**QGIS Info**
QGIS Version: 3.28.1-Firenze
QGIS code revision: fde3b8fbb8c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0
Running against GDAL: 3.6.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by domi4484**
This only avoids the crash by postponing `QgsAttributeTableModel::loadLayer` to the next event loop execution, when the OgrProvider is in a consistent state again. This fixes #51262, but an underlying issue remain, see also comment https://github.com/qgis/QGIS/issues/51262#issuecomment-1375325399

### CODE REVIEW

**Comment by nyalldawson** [comment]
@domi4484 from the issue, i see "At this point the feature iterator tries to get values for the new field which is (for a short time) not known to the provider" -- does this result in a crash? If so, that's something we should also fix... invalid fields in a iterator should just be ignored, not crash

**Comment by domi4484** [comment]
@nyalldawson you are right, I added a commit to avoid the crash in first place. Should I just ignore the invalid fields or also trace a warning message?

**Comment by nyalldawson** [comment]
> Should I just ignore the invalid fields or also trace a warning message

I'd add a QgsDebugMsg warning

**Comment by nyalldawson** [comment]
https://github.com/qgis/QGIS/pull/51494 is an alternative (cleaner) fix for the crash -- @domi4484 can you test that fix?

**Comment by domi4484** [comment]
@nyalldawson I tried out your fix and it works! I close this one

**Pull request closed without merging**
