### PR TITLE
add mac/development README

### PR DESCRIPTION
**Pull request by 3nids**
so we can archive deprecated homebrew-qgisdev repo

### CODE REVIEW

**Review by PeterPetrik — APPROVED** [review]

**Comment by timlinux** [comment]
Maybe we should also accompany this with a pointer from INSTALL to these notes otherwise I think most wont discover them easily?

**Comment by 3nids** [comment]
@timlinux done

**Comment by PeterPetrik** [comment]
would it be possible to fix the code style so we can merge it?

**Comment by 3nids** [comment]
I will not do much more here, let's merge it so we can archive the old repo.

**Comment by 3nids** [comment]
I will not do much more here, let's merge it so we can archive the old repo.

**Pull request merged**
