### PR TITLE
Assume URL already encoded in web view widget

### PR DESCRIPTION
**Pull request by m-kuhn**
Forward port of #6955

### CODE REVIEW

**Comment by m-kuhn** [comment]
@amaizr do you have any chance to verify that QGIS 3 suffers from the same problem and this commit fixes it?

**Comment by m-kuhn** [comment]
I couldn't cherry-pick the commit, logic for loading the pathname has changed and a different method (`setUrl()` vs `load()`) is used, that's what made me a bit suspicious. Anyway, let's merge.

**Comment by nyalldawson** [comment]
@m-kuhn agreed... Seeing this queue get up close to 60 again is stressing me out :cry:

**Comment by m-kuhn** [comment]
Subtract those which target 3.4 from this calculation ;)

**Pull request merged**
