### PR TITLE
Render axis for stacked bar diagram

### LINKED ISSUE #34915: [Diagrams] Stacked bars do not display the "Axis line symbol"
In layer properties > Diagrams, > stacked bars, the "show axis" under the rendering tab does not seem to render the axis line symbol in the map canvas
image
Note that it renders if I set the diagram type to "histogram".
I wonder if the setting is broken or should be hidden when in "stacked bars" mode...

QGIS 3.12.0 on Windows 10

### PR DESCRIPTION
**Pull request by dminor**
This adds support for rendering the axis on stacked bar diagrams if an axis has
been set. The implementation is based on the axis rendering for the histogram
diagram.

Fixes #34915

## Description

This adds rendering for the axis on stacked bar diagrams, based on the implementation of axis rendering for the histogram diagram. I tested it manually in the four orientations with and without bar spacing. In #34915 it is mentioned that this is important to identify negative values in a stacked bar diagram. When I went to test this, I noticed that negative values are not handled properly by stacked bar diagrams with or without the axis being displayed. Because this is my first contribution, I'd prefer to attempt to fix handling negative values as part of a separate pull request.

Changelog image:
stacked-axis

This feature was developed by Daniel Minor (https://github.com/dminor/).

### CODE REVIEW

**Comment by nyalldawson** [comment]
The code looks good, thanks for the contribution!

Can you add some unit tests for this, similar to https://github.com/qgis/QGIS/blob/master/tests/src/core/testqgsdiagram.cpp#L290

There's instructions at https://docs.qgis.org/3.10/en/docs/developers_guide/unittesting.html detailing the QGIS unit test setup and how to run/add tests. Just ping me if you need assistance with this!

**Comment by dminor** [comment]
Thanks for having a look! I'll add some tests.

**Review by nyalldawson — APPROVED** [review]
Great, looks perfect!

**Comment by m-kuhn** [comment]
Thanks a lot!

One last request, could you provide a screenshot and the entries for developer/sponsor or other things you want to appear in the changelog? You can edit the pull request text (top of this page) and add it to the end.

**Comment by dminor** [comment]
I've attached the screenshot. Thank you both for the quick feedback!

**Pull request merged**
