### PR TITLE
add Australian entries [srs.db]

### PR DESCRIPTION
**Pull request by nyalldawson**
via:

    insert into tbl_datum_transform VALUES (8447,100020,4283,7844,9615,
    GDA94_GDA2020_conformal_and_distortion.gsb', null, null, null, null,
    null, null, 'Conformal + Distortion: includes regional distortion',
    null,1,0,null);

### CODE REVIEW

**Comment by nyalldawson** [comment]
@wonder-sk I saw you'd made a similar change in https://github.com/qgis/QGIS/pull/8175 

Can I ask: how did you determine the correct "area of use code"?

**Comment by nyalldawson** [comment]
Ah - don't worry about that, I see you retrieve it from https://www.epsg-registry.org/ by searching for the coordinate transform code

**Comment by NathanW2** [comment]
Will you also add the other grid file entry here?

**Comment by nyalldawson** [comment]
@nathanw2 yep, this is more or less just public notes while I work on this.

**Comment by nyalldawson** [comment]
@nathanw2 now includes all 4 australian grids. I plan on backporting this to 3.4/3.6, to hold us over temporarily until the upcoming upgrade to proj6 API.

**Pull request merged**
