### PR TITLE
The providers plugin path can be changed in the applications.

### PR DESCRIPTION
**Pull request by gshegunov**
When the providers plugin path is changed in the application, re-initialize of the plugins is done.

### CODE REVIEW

**Comment by m-kuhn** [comment]
I don't think this can do much harm.
Out of interest, when is this required?

**Comment by gshegunov** [comment]
mProviders are cleaned up in clean(). Before init() is called clean().

When QgsAppication starts sets the providers, library paths and etc.

In my own application I have my plugin path that is different from the path
that is set in QgsAppication. When I change the path in application by void
QgsProviderRegistry::setLibraryDirectory( QDir const & path ) I have to
cleanup old staff and to load new one.

**Comment by wonder-sk** [comment]
Why not use just QgsApplication::setPluginPath() before initializing QgsApplication?

**Comment by gshegunov** [comment]
I need changing the plugin path on the fly, when the application is already
runs. The path to be choosen via dialog. Otherwise setPluginPath() is
useless – it sets only path without any other action.

**Comment by m-kuhn** [comment]
Currently it's thought to be an initialization step, but since I cannot see that it could lead to a regression and the only risk involved is that when used subsequently it may lead to undesired side-effects I think it would be safe to merge.

@wonder-sk ?

**Comment by m-kuhn** [comment]
Merged in 9fdab87056dd

**Pull request closed without merging**
