### PR TITLE
[Oracle] Restore Oracle CI

### PR DESCRIPTION
**Pull request by troopa81**
This PR uncomments Oracle docker image. 

In recent build, Oracle docker image is not started, and we timeout when we wait for Oracle database initialization. But still, the oracle tests succeeds !! 

DO NOT MERGE, I want to understand why the Oracle tests pass although the oracle database is not started.

cc @3nids 

Funded by Lille Metropole
cc @Jean-Roc

### CODE REVIEW

**Comment by 3nids** [comment]
This is indeed quite weird.
Have you find out why the test passed?

**Comment by troopa81** [comment]
@3nids No. For now, I try to restore the Oracle tests but it fails because of this

> failed to register layer: Error processing tar file(exit status 1): write /home/oracle/oradata/XE/system01.dbf: no space left on device

I try to increase the docker size the same way you did previously 0037aa05d00193f8a0575f64babc3288ba201fa9 but it 's still not working

**Comment by troopa81** [comment]
Looks like GH actions runners are [limited](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources) to 14 GB.

Oracle image size is around 10 GB, if you add this QGIS and all the dependencies, I'm pretty sure the overall size will be greater that 14 GB. 

I could: 
- try to make an Oracle image smaller (Not sure it's possible though)
- launch the oracle tests in an other GH action and grab the already compiled QGIS (without sources and other PG docker) from previous stage. Is it possible?

**Comment by 3nids** [comment]
> launch the oracle tests in an other GH action and grab the already compiled QGIS (without sources and other PG docker) from previous stage. Is it possible?

This is something I was thinking about, because we start to have many providers running. It might be interesting to have them running in parallel. That means commit and save the QGIS image in a artifact (without the sources) and use it in the following jobs. 
Do you have time/funding to investigate this?

**Comment by troopa81** [comment]
> This is something I was thinking about, because we start to have many providers running. It might be interesting to have them running in parallel. That means commit and save the QGIS image in a artifact (without the sources) and use it in the following jobs.

This looks interesting indeed.

> Do you have time/funding to investigate this?

I will be away next week but I hope to find time to work on this subject then.

**Comment by troopa81** [comment]
For the record, QGIS occupy 4.1 GB, there is 9 GB left, and Oracle is about 10 GB. So a solution with a QGIS binary only artifact sould solve the issue.

```
Run echo "Disk size"
Disk size
Filesystem      Size  Used Avail Use% Mounted on
udev            3.4G     0  3.4G   0% /dev
tmpfs           696M  680K  695M   1% /run
/dev/sdb1        84G   72G   12G  87% /
tmpfs           3.4G  8.0K  3.4G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.4G     0  3.4G   0% /sys/fs/cgroup
/dev/sdb15      105M  3.7M  101M   4% /boot/efi
/dev/sda1        14G  4.1G  9.0G  32% /mnt
```

**Comment by 3nids** [comment]
I think we found why the tests were passing and not failing https://github.com/qgis/QGIS/pull/41854

**Comment by troopa81** [comment]
> I think we found why the tests were passing and not failing #41854

Not sure to understand exactly why but indeed, the Oracle tests are failing now! 

I'm still working on a way to revive them, we can comment them in the meantime

**Pull request closed without merging**
