### PR TITLE
Enable composition mode for advanced drawing

### PR DESCRIPTION
**Pull request by NathanW2**
Makes the lines pop off the map more and not get lost in the background. Also adjusts the line size up to 1 as .7 it really small.

The current display of these lines is really hard to see and not very friendly IMO.  Very small and the colors get lost in all the map noise. 

PR turns on difference composition mode so it will handle the change in data under the line.

Looks like this against a green polygon:

image

vs what it currently looks like (have fun finding the green guide line in that)

image

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by NathanW2** [comment]
@nirvn @nyalldawson @3nids thoughts?

**Comment by nyalldawson** [comment]
I think you want to make sure that the painting is always done using QColor(127,127,127) with difference mode - that means it should *always* be visible, regardless of background.

**Comment by nyalldawson** [comment]
Another thing - I'd set the pen width to 0, and then call setCosmetic( true ) on it. That may help a bit with visibility too.

**Comment by nyalldawson** [comment]
It's a big improvement, so +1 from me!

**Comment by NathanW2** [comment]
> Another thing - I'd set the pen width to 0, and then call setCosmetic( true ) on it. That may help a bit with visibility too.

Didn't even know that was a thing so will do.

**Comment by NathanW2** [comment]
Update with most recent changes. 
image

**Comment by NathanW2** [comment]
Merging this as is currently as it's better then what we have.  More improvements needed in future to make the lines stand out more.

**Pull request merged**
