### PR TITLE
Other test for Processing

### PR DESCRIPTION
**Pull request by ghtmtt**
In the previous commit, I put gdal test in the qgis.yaml file. Now I corrected it and moved the gdal test in the correct yaml file

### CODE REVIEW

**Comment by m-kuhn** [comment]
I'm not sure saving shapefiles in a folder with .gml extension makes it a gml file ;)
Is there no possibility to force the algorithm to output something else, ogr should support (almost) all providers which qgis supports as well?

**Comment by ghtmtt** [comment]
S@*#t! I created the gml file and tested it and I re-run the algorithm without saving it as gml. My fault! Asap I will change the shp to gml 
Sorry for the noise

**Comment by ghtmtt** [comment]
nope.. not my fault.. I tested the same algorithm again and whatever output you choose (gm, geojson, kml) no file are created. Instead a folder named `ouput.gml` or `ouput.geojson`  ecc.. is created and inside it there are the shp files.

Not the expected behavior I'll say

**Comment by m-kuhn** [comment]
I guess I know why...

https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/gdal/polygonize.py#L68

And fortunately there is already a solution for this implemented, see https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/gdal/contour.py#L89

**Comment by nyalldawson** [comment]
What's the status with this PR? Is there still unmerged tests from this, or can we safely close?

**Pull request closed without merging**
