### PR TITLE
QtDBus linked to other Qt frameowrks, needs bundling

### PR DESCRIPTION
**Pull request by kyngchaos**
## Description

QtDBus is missing from Mac bundling.

### CODE REVIEW

**Review by 3nids — APPROVED** [review]

**Comment by kyngchaos** [comment]
CI failed for completely unrelated error, as far as I can tell.  This PR affects Mac bundling during make install, CI error in test 217 qgis_relationreferencewidget.

**Comment by roya0045** [comment]
> CI failed for completely unrelated error, as far as I can tell. This PR affects Mac bundling during make install, CI error in test 217 qgis_relationreferencewidget.

Yeah that test has been trouble for quite some time, should be fixed soon.

**Comment by kyngchaos** [comment]
Could someone manually backport this to 3.10 & 3.12?  I reset my fork after this PR was merged, not realizing that the backports still needed the reference to my fork.  I'm still trying to wrap my head around the more complex parts of this fork & PR way of working and I only ever did simple commit & push directly with git.

**Comment by 3nids** [comment]
now, since the commit has been merged to master:

```
git checkout release-3_10
git checkout -b pr3821-backport-310
git cherry-pick 989d0c68f646a9cc735f344968bdbe780b0083f2
(git mergetool if needed)
git push -u [YOUR_REMOTE] pr3821-backport-310
```

repeat for 3.12

**Comment by kyngchaos** [comment]
Do you mean checkout on my fork or on QGIS repo?  My fork is missing all new branches since I originally forked it years ago.

And, I assume that's a typo, the checkout and push should be pr34821?

But really, this is getting too messy for me.

**Pull request merged**
