### PR TITLE
[FEATURE] @geometry_part variable for symbol rendering

### PR DESCRIPTION
**Pull request by nyalldawson**
A bit like @geometry_part_num, but this contains just the _geometry_ for the currently rendered part. It's a shortcut instead of having to do `geometry_n($geometry, @geometry_part_num)`

### CODE REVIEW

**Comment by NathanW2** [comment]
Sweet.  Thanks

**Comment by nyalldawson** [comment]
Actually I've got second thoughts about this.... The geometry cloning is probably too expensive to always occur during rendering

**Comment by m-kuhn** [comment]
That's why I didn't do it this way. It will also affect the 98% of multipart renderings when you don't need to style parts individually.

**Comment by nyalldawson** [comment]
I think the right way to do this is using a context based function. Not for 2.14 though ;)

**Comment by NathanW2** [comment]
Yep. What is there currently works so that is fine.

**Comment by m-kuhn** [comment]
+1 for a function as a shortcut

**Comment by m-kuhn** [comment]
Should this be closed?

**Comment by nyalldawson** [comment]
No - leave it open and I'll rework for 2.16

**Comment by nyalldawson** [comment]
@m-kuhn @NathanW2 @nirvn I'm wondering now if @geometry_part_num should be set when a marker line with markers-at-vertices is used. This would allow z/m to be retrieved via `z_at($geometry, @geometry_part_num)`, a considerable improved on the alternative approach of a geometry generator using nodes_to_points, etc. 

The only hestitation is that overwriting this variable may cause issues if the actual geometry part number is required. So maybe @geometry_node_num is better in this situation. Thoughts?

**Comment by NathanW2** [comment]
That sounds good to me.  +1 to the name change.

**Comment by m-kuhn** [comment]
+1 for @geometry_node_num

**Comment by haubourg** [comment]
@nyalldawson  if you revive this PR at your hackfest, have a look at http://hub.qgis.org/issues/16484
there is something strange with using expressions like 
`z(point_n($geometry,@geometry_point_num))`
for rendering Z values of vertices.

**Comment by nyalldawson** [comment]
Non-trivial amount of work remaining

**Pull request closed without merging**
