### PR TITLE
OGR provider: feature count improvements

### PR DESCRIPTION
**Pull request by rouault**
- implement deferred feature count computation. This avoids computing the feature count at provider instantiation.
-  Add QgsDataProvider::ReadFlag::SkipFeatureCount and implement it in OGR provider to avoid featureCount() to be called

### CODE REVIEW

**Comment by nyalldawson** [comment]
> add a '|computeFeatureCount=false' uri option to disable feature count

Wouldn't this be better hooked into the existing "use estimated metadata" provider settings? That way it works the same as other providers

**Comment by rouault** [comment]
> Wouldn't this be better hooked into the existing "use estimated metadata" provider settings? That way it works the same as other providers

do you mean that if QgsDataProvider::ReadFlag::FlagTrustDataSource is set (or not set ?), then we would skip feature count computation ? That doesn't seem right to me as this is different semantics 

Or use QgsDataSourceUri::setUseEstimatedMetadata() / useEstimatedMetadata(), but for the same reason as above regarding the semantics, doesn't seem appropriate, and I'm not sure how OGR URI play with QgsDataSourceUri

Or add a new ReadFlag::SkipFeatureCount , and a corresponding QgsMapLayer::ReadFlag::SkipFeatureCount ?

**Comment by nyalldawson** [comment]
> Or add a new ReadFlag::SkipFeatureCount , and a corresponding QgsMapLayer::ReadFlag::SkipFeatureCount ?

I like this approach! Does it work for you?

**Comment by rouault** [comment]
> Does it work for you?

Yes, I've implemented it only at the provider level since this matched my need (plugin that must list sublayers, but where feature counting can be slow). At the layer level, I see that the ReadFlag is only taken readLayerXml() and not in the constructor of the layer.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
> plugin that must list sublayers, but where feature counting can be slow

(Thinking aloud) we need to rework how we handle sublayer retrieval -- the current API is quite poor because it forces you to create an unwanted initial layer just to determine the available sublayers (not to mention the horrible way you have to split the string to extract the data type/feature count!). We should move this into the provider metadata class and use a proper struct/class for returning the sub layer details...

**Pull request merged**
