### PR TITLE
[processing] fixes for batch processing interface

### PR DESCRIPTION
**Pull request by volaya**
## Description

While trying to work on #29822, I could not reproduce the setting for the error, since I found some new bugs in the batch processing interface. This PR fixes them.

I have removed the different way of creating the wrapper widget that was used for certain parameter types. It was causing some of those errors, and doesnt seem to be needed now. The create_wrapper method supports all those types as well, so it can be used as the only way of creating the corresponding wrapper.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
@alexbruy you only recently introduced this - can you take a look?

**Comment by alexbruy** [comment]
@volaya I changed that part to fix #29674. It seems that when multiple input parameter used to select files adding rows to the batch dialog does not work.

**Comment by volaya** [comment]
yes, looks like a recent change. But with those changes the batch interface is broken for me whenever there is a raster layer. Clicking on run or in the autofill options ends up in a exception. Looks like when calling the setCellWidget method, the wrappers[param.name()] value is not set, and adding that causes a different exception later. So I assumed that part could be removed. I tested, and it worked fine, but i was probably not trying the case described in that issue.

What do you suggest doing? i can revert the part that eliminates is instance() conditional, and try to fix the errors that it causes. Is that ok with you?

**Comment by alexbruy** [comment]
@volaya probably better to look why it does not work for multiple file input, as using widget factor is much nicer approach.  Do you want me to look into it or preffer to do it by yourself?

**Comment by volaya** [comment]
Let me then investigate a bit and see what I can do. I will update this PR and make sure that it doesnt break you fixes on #29674

**Comment by volaya** [comment]
@alexbruy Just tested, and it seems that, with this PR as it is, you can select multiple files for a raster or vector input, and it correctly places them in different rows. The issue that you mention, however, complains of that behaviour not working for file/folder input type. You do not seem to have addressed that in your PR.

Looks easy to fix, the error is in the FileWidgetWrapper class. However, it's marked as deprecated, so those fixes should be done to the new c++ class, not the Python one in wrappers.py.

@nyalldawson What do you suggest? I would say we can merge this PR, and then @alexbruy could take care of that c++ fix.

**Comment by alexbruy** [comment]
Hmm, I can select files and rows are correctly populated here.

**Comment by volaya** [comment]
mmm, not here. So if you create a model and add an input of type "File/folder" (not a layer), and then try to run that model in batch, you can select multiple files? I can only select one file in the file selector that appears for that parameter

**Comment by alexbruy** [comment]
Just tested with model too (previously I tested only normal algorithms):

- If model has file/folder input in the batch interface I can select multiple files and they will be added as separate rows.
- If model has multiple input parameter with "file" type in the batch interface I can select multiple files and they will be added as a single row, containing all selected files.

The same behaviour I see in the 2.18.

**Comment by volaya** [comment]
Maybe it's a OS issue. I am in Windows (The issue reporter as well) and I see what the issue mentions. But maybe in Linux the default for the file selection dialog is to allow multiple files to be selected?

**Comment by alexbruy** [comment]
Tested also on Windows using latest master from OSGeo4W and self-compiled from Git. Multiple files can be selected.

**Comment by alexbruy** [comment]
I have reverted these controversial commits and reopened #29674. Batch mode should be fully functional and users can use Nyall's autofil button to populate rows. We can return to the old 2.x style of populating rows later.

**Pull request closed without merging**
