### PR TITLE
Fix goto locator filter regression following CRS ordering work

### LINKED ISSUE #48153: GoTo locator broken in EPSG:4326?
### What is the bug or the crash?

Hi, trying to update https://github.com/qgis/QGIS/pull/46028/ to include some new code additions:

https://github.com/qgis/QGIS/commits/master/src/app/locator/qgsgotolocatorfilter.cpp
(@nirvn if I am right to respect crs ordering and other epsg:4326 related things?)

I thought to start from master again and add my code (had troubles merging)...

But: to me it looks like something is broken now?

The GoTo locator is not going to the right position anymore? At least not in a EPSG:4326 project

And using - signs in the numbers also creates havoc

### Steps to reproduce the issue

Create Fresh profile in QGIS master
(I have an US/english locale/setting)

Open a new map EPSG:4326 and add 'world' to it

Move over the map (and notice that in the Coordinate input, for example in The Netherlands (around lat 52 lon 5) indeed you now see 52.xx, 5.xx instead of 5.xx, 52,xx in earlier QGIS versions)

Now in the locator: type '52 5' (lat lon now)
You will see 'Go To 52*N 5*E (EPSG:4326 WGS84)' but the little flashing geometry shows somewhere around 0, 0 ?
(instead popping up in The Netherlands)

Another observation: type '-52 5'  (lat lon now)
And you will  see: 'Go To -52*N 5*E (EPSG:4326 WGS84)' but the little flashing geometry shows somewhere around 0, 0 ?
(is that possible? To go -52*N ?)

Now (using the world map is OK, only looking a little funny)
Change your project crs to EPSG:28992 (dutch national CRS)
And type: 150000  450000  (x,y)
You will see: 'Go To 150000E 450000N (Map CRS, EPSG:28992)'
The flashing geom is ok now, but should the E and N show in such crs's?

Doing the same in an older QGIS still works OK.

@nirvn in my PR I also added code to the GoTo locator, which made that if you ask for a coordinate OUTSIDE of the extent of a crs, that it is actually ignored/not shown, I think that is a good addition also?
Would it be an option, to first pull my PR and then fix the things you want to be fixed in the GoTo locator?

### Versions

Master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nirvn**
This PR fixes #48153. @rduivenvoorde , thanks for spotting the regression so fast.

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
@nirvn what do you think of my comment about showing N/W/E etc for non latlon coordinates? Or is that ‘fixed’ with this too? As an example, in NL we neber show coordinates with n/w when in our national crs epsg:28992.

**Comment by nirvn** [comment]
@rduivenvoorde , the reason why this was added was to provide an indicator of the crs ordering. The abbreviations follow the axis direction name. So while we're not used to see it, those align with the CRS definition and without those users would not know whether the first number is treated as X or Y.

**Comment by nirvn** [comment]
@rduivenvoorde , feel free to trigger a broader discussion to the mailing list.

**Comment by rduivenvoorde** [comment]
I will, now building for test, and so I can add some screenies here...

**Comment by rduivenvoorde** [comment]
Ok, national crs is working now.

Still not convinced about the nswe addition, showing the examples here with our national crs (28992):

The Copy Coordinate menu:

gnome-shell-screenshot-3br5c1

The GoTo locator results:

gnome-shell-screenshot-544ds5

It get's really messy when you start using minus signs in combination with nswe:
- you can search for '49s 15w' but locator will show: -49N -15E
So it will always (only show N and E ?)

Would it be a valid option to just show x:... y:... or y:... x:... ? Or is this geographically wrong?

(will now sent an email to the the list)

**Comment by nirvn** [comment]
@rduivenvoorde , thanks for triggering the discussion. While people are conversing, let's merge this fix).

**Comment by rduivenvoorde** [comment]
@nirvn fine for me, though I think the use of the minus sign messes up stuff...
But let's merge this.

**Comment by esnyder-rve** [comment]
For United States coordinate systems, it is customary to give coordinates in Northing/Easting order.

**Comment by rduivenvoorde** [comment]
> For United States coordinate systems, it is customary to give coordinates in Northing/Easting (Y/X) order.

@esnyder-rve but 'customary', does that mean people use both? 
And if so, how do they distinguish between two forms?
Or is it Always Y/X?
And last: showing it like  '11111E, 444444N ': does that look OK? Or would you prefer without E/N or use y/x or so?

**Review by 3nids — APPROVED** [review]

**Comment by esnyder-rve** [comment]
@rduivenvoorde it's pretty much just Northing/Easting (Y/X) order for coordinates. When the US created the it's State Planes, it was done in the order of Northing/Easting.
As for CRS's, anything State Plane (NAD27, NAD83) would be Northing/Easting (i.e. EPSG 3424 for New Jersey, EPSG 6565 for Pennsylvania South).

I would highly recommend showing the letters to remove any ambiguity as to what order it's in, so it would be 444444N, 111111E.

**Pull request merged**
