### PR TITLE
[feature][needs-docs] Master Password integration with OS password manager

### PR DESCRIPTION
**Pull request by elpaso**
## Description

This PR adds (optional) synchronization of the master password
with the OS password manager (AKA wallet/keychain).

A set of new menu items has been added in the options ->
authentication -> utilities to manage the new behavior.

Notifications are handled by the message bar unless the
password r/w operation is triggered from a modal dialog,
in this case the notifications will be routed through
the recently exposed QgisApp::showSystemNotification
that uses the OS tray notifications.

This new feature requires libqt5keychain, and was tested
with v. 0.5+

**An internal review of this PR has already been done by @dakcarto** 

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

## UX/UI changes

This PR introduce some small changes in the GUI:

**The user can opt-in and store the master password in the password manager**
password_helper2

**The user can enable/disable the integration, update and clear the stored password at any time**
password_helper4

### CODE REVIEW

**Comment by DelazJ** [comment]
@elpaso for the ui/ux consistency, any reason to not reuse the PassworLineEdit custom widget from https://github.com/qgis/QGIS/pull/4256?

**Comment by elpaso** [comment]
@DelazJ sure, nice idea!

But out of scope for this PR (that does not change the existing GUI for the credentials dialog except by **adding** the checkbox to opt-in for the password manager/keychain/wallet usage)

**Comment by dakcarto** [comment]
@DelazJ Updating all of authentication system widgets with `QgsPasswordLineEdit` is part of an auth system QEP I am putting together.

**Comment by elpaso** [comment]
@jef-n this commit introduces an hard dependency on qt5keychain library. See: https://packages.debian.org/jessie/qt5keychain-dev

**Comment by NathanW2** [comment]
I assume we don't have a something already built for this for Windows?

**Comment by elpaso** [comment]
@dakcarto has built and tested qt5keychain on windows and it works just fine, I'm sorry but I don't know if/where you can grab a pre-build binary for windows (I've never built it on windows), hopefully Larry does.

**Comment by Gustry** [comment]
And for MacOS, is there something? @dakcarto ?

**Comment by dakcarto** [comment]
@Gustry I can add it to https://github.com/OSGeo/homebrew-osgeo4mac/tree/master/Formula. There are already ones for Qt4 and Qt@5.7. Just forgot to update the latter for Qt 5.8.0. Will do that today. Really, it needs to be contributed upstream to https://github.com/Homebrew/homebrew-core

@NathanW2 We (Boundless) can temporarily post a binary to use with OSGeo4W for Qt 4 and 5, for drop-in install (.lib and .dll), until @jef-n has something ready.

Of note: the [QtKeychain library](https://github.com/frankosterfeld/qtkeychain) is very stable and tends to build with _zero_ problems. So, if you want to build it yourself, it is pretty easy.

**Comment by Gustry** [comment]
Great, I have qt 5.8.1. Let us know, thanks @dakcarto !

**Comment by dakcarto** [comment]
@Gustry the `qtkeychain` (with normal `qt5` dependency) has been pushed in latest commit to OSGeo4Mac, curently waiting on a Sierra bottle.

Now I remember why I have not set up a PR to Homebrew-core (still waiting on a newly tagged release):
https://github.com/frankosterfeld/qtkeychain/issues/98

Please add your voice to that issue, if you have the time, and you wish to see the `qtkeychain` formula in Homebrew-core asap. Thanks!

**Comment by dakcarto** [comment]
@NathanW2 until I have some binaries uploaded to use for testing, here is our Jenkins job [batch script for QtKeychain](https://gist.github.com/dakcarto/7d1173484b34f488657d77775665a8c4) on Win 64.

The `call "%~dp0\o4w-build-env-64.bat"` line is specific to our build server environ, but is not needed for a normal OSGeo4W build setup, and the rest should be pretty self explanatory for you.

It defaults to Qt4 (we are building for QGIS 2.14); so, you will need to add the `-DBUILD_WITH_QT4=OFF` command line definition as well.

**Comment by jef-n** [comment]
or use the OSGeo4W package.

**Comment by dakcarto** [comment]
@jef-n Nice! Thanks [for the new package](http://download.osgeo.org/osgeo4w/x86_64/release/qt5/qtkeychain-qt5/)!

**Comment by dakcarto** [comment]
@Gustry, `qtkeychain` formula now has Sierra bottle and the `qtkeychain` dependency has been added to `qgis3-dev` formula in https://github.com/qgis/homebrew-qgisdev

**Comment by elpaso** [comment]
Also great thanks to @m-kuhn for helping with pre-built qtkeychain in the osgeo4travis.

**Comment by Gustry** [comment]
Thanks it works @dakcarto!

**Pull request merged**
