### PR TITLE
Disable mingw action - The environment is broken for unknown reasons

### PR DESCRIPTION
**Pull request by nyalldawson**
A completely broken action is just plain noise. Disabling until someone has the skills/motivation to fix this.

### CODE REVIEW

**Comment by manisandro** [comment]
Note: feel free to point me to the failures when some occur and I'll investigate them.

**Comment by nyalldawson** [comment]
@manisandro thanks! It's odd, the build works fine for master still. I tried backporting the various cmake changes for python/proj and couldn't work out which ones are the magic changes which make master work and are missing from the 3.18/3.16 branches. If you've any insights, it would be greatly appreciated!

**Comment by manisandro** [comment]
This one:

    Fatal Python error: init_import_site: Failed to import the site module
    Python runtime state: initialized
    Traceback (most recent call last):
        File "/usr/x86_64-w64-mingw32/sys-root/mingw/lib/python3.9/site.py", line 73, in <module>
        import os
        File "/usr/x86_64-w64-mingw32/sys-root/mingw/lib/python3.9/os.py", line 29, in <module>
        from _collections_abc import _check_methods
        File "/usr/x86_64-w64-mingw32/sys-root/mingw/lib/python3.9/_collections_abc.py", line 416, in <module>
        class _CallableGenericAlias(GenericAlias):
    TypeError: type 'types.GenericAlias' is not an acceptable base type

is caused by mingw-python3 non being the same version as the native python3. It should be fixed by pulling a current fedora:rawhide docker image, resp. running dnf -y upgrade in the Dockerfile to update the packages which come with the base image.

**Comment by roya0045** [comment]
I'm just curious about something in regards to our build. Especially builds with artefact can take a lot of space, should some builds be run 'on-demand' or on releases to reduce our footprint on the infrastructure?

Don't get me wrong, I love mingw build (thanks again Sandro and Ales), but I used then sparringly as taking 900mb is heavy. Though I'm also not sure what is our artefact retention policy is.

**Pull request merged**
