### PR TITLE
(re)add the alpha option for the GDAL color relief tool

### PR DESCRIPTION
**Pull request by gioman**
## Description
This option was not ported when we got rid of the old GDAL tools core plugin.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] Did not drink while coding

### CODE REVIEW

**Comment by gioman** [comment]
@luipir Luigi will show me about adding tests today ;)

**Comment by nyalldawson** [comment]
+1, and +2 if you add tests :wink:

**Comment by gioman** [comment]
> +1, and +2 if you add tests

@nyalldawson yes, now I have no more excuses

**Comment by luipir** [comment]
> +1, and +2 if you add tests

I should say sorry to @gioman I wasn't able to help him during hackmeeting... I was able to open the laptop only at 7PM every day of the meeting!

**Comment by nyalldawson** [comment]
So what's the way forward here?

**Comment by luipir** [comment]
came on @gioman do these tests! (pressure pressure pressure ;) )

**Pull request closed without merging**
