### PR TITLE
[win] Use native desktop notifications for prettier notifications

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes ugly unbranded desktop notifications in windows

### CODE REVIEW

**Comment by NathanW2** [comment]
Got a pic?

**Comment by nyalldawson** [comment]
Before:

image

After:

image

**Comment by NathanW2** [comment]
NICE!

**Comment by nyalldawson** [comment]
@nathanw2

So happy if I merge?

**Comment by NathanW2** [comment]
Maybe remove the  .gitignore
<https://github.com/qgis/QGIS/pull/7548/files#diff-2>  files from checkin?

**Comment by nyalldawson** [comment]
@NathanW2 
> Maybe remove the  .gitignore

Done!

**Review by NathanW2 — APPROVED** [review]
Looks good.

**Pull request merged**
