### PR TITLE
Add Icon for "Select within distance" + add it to Vector -> Research Tools menu under "Select by location"

### PR DESCRIPTION
**Pull request by tudorbarascu**
The title sums it up. Did my best to create a good svg, hope it looks ok.

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
Ping @nirvn

**Comment by nirvn** [comment]
@tudorbarascu , nice effort. Few things:
- when you create icons, try as much as possible to have shapes align to the grid, which means insuring that a simple outline is 1px, and that individual nodes are mostly placed in the center of a 1px x 1px grid; that'll result in nicer renderings of the icon;
- In terms of colors, I think it'd make more sense to have the center feature use the feature-color (i.e. the green you can see with features in the advanced digitizing toolbar), and the bigger rectangle around it be the yellow-selection color (with probably a hard 1px solid yellow outline).

**Review by nirvn — CHANGES_REQUESTED** [review]
(see comment made a minute earlier)

**Comment by nirvn** [comment]
@tudorbarascu , much better. The SVG is still not quite aligned with the grid, e.g.:

image

The outline should fit within the 1px grid spacing:

image

Can you update the SVG? We'll merge after that.

**Comment by tudorbarascu** [comment]
> @tudorbarascu , much better. The SVG is still not quite aligned with the grid, e.g.:
> 
> image
> 
> The outline should fit within the 1px grid spacing:
> 
> image
> 
> Can you update the SVG? We'll merge after that.

Oh, not I understood. Done! Thanks a lot for reviewing!

**Comment by tudorbarascu** [comment]
Hmmm, I just build again to see how it looks in QGIS and the green part is not shown anymore although I can see it in inkscape and other tools. Looking into it.

**Comment by tudorbarascu** [comment]
@nirvn forced pushed. All is good now. Thank you
image

**Comment by tudorbarascu** [comment]
Hello. Is there a box/option that I can tick to show the changes were done as requested? Thank you.

**Comment by nirvn** [comment]
@tudorbarascu , my bad. Thanks for your contribution. Hope to see many more icons coming in the near future :)

**Review by nirvn — APPROVED** [review]

**Comment by tudorbarascu** [comment]
@nirvn Thanks a lot for reviewing! Hope to do contribute more.

**Comment by DelazJ** [comment]
@tudorbarascu would you know why I can't see this shortcut in my menu (master [210860bf45](https://github.com/qgis/QGIS/commit/210860bf45))
image

**Comment by tudorbarascu** [comment]
@DelazJ Curious. I don't have a Ubuntu 22 but I just checked and for master it's there on Windows 10, Fedora37 and Debian 11.

**Comment by tudorbarascu** [comment]
> On Master [f74d9dd1be](https://github.com/qgis/QGIS/commit/f74d9dd1be) on Win10, it appears in toolbar image
> 
> But not in Vector menu image

@nicogodet That's curious. I just checked in my Win10 VM and the master that I installed yesterday through osgeo4w is looking fine, I have the icons where there should be with https://github.com/qgis/QGIS/commit/e631771db7

**Comment by nicogodet** [comment]
In my existing profile, it doesn't appear but in a clean one created long time ago, it appears.
Existing profile 
image

Old but clean one
image

**Pull request merged**
