### PR TITLE
allow to define max number of results for some locator filters

### PR DESCRIPTION
**Pull request by 3nids**
this allows to define:
*  maximum number of results for active layer
* global maximum filter + per layer maximum numer of results of all layers features filter

### CODE REVIEW

**Comment by 3nids** [comment]
is this worth a FEATURE label?

**Comment by nyalldawson** [comment]
When would a user themselves need to configure this? (vs the filter implementation itself...)

**Comment by 3nids** [comment]
This has been a feature request here: #36701
Mainly, it's because some want to see all results rather than a subset.
I still think we should keep the numbers low by default (mainly looking at how recent online tools work: https://map.geo.admin.ch/ or google maps)

**Comment by nyalldawson** [comment]
Sorry -- misread the diff. I thought you where adding it for ALL locator filters, not particular ones!

**Comment by 3nids** [comment]
test is failing on push on this repo (then branch has been pushed here, sorry for this).
any objection?

**Pull request merged**
