### PR TITLE
 [postgres] Add a timeout for postgres connections 

### PR DESCRIPTION
**Pull request by nyalldawson**
Don't know if I'm the only one who gets driven mad by the infinite timeout for connecting to unavailable postgres servers... but this adds a configurable option to set a timeout for postgres provider, and defaults the timeout to 30 seconds.

### CODE REVIEW

**Review by luipir — APPROVED** [review]
Fine to have it configurable

**Review by luipir — APPROVED** [review]

**Review by luipir — COMMENTED** [review]
is it possible a 1" test using test db?

**Comment by nyalldawson** [comment]
> is it possible a 1" test using test db?

Let me see. The timeouts are in seconds, so the minimum can be 1 second.. and I suspect a 1 sec timeout will be too long for a reliable test (given that the test database is local on Travis).

**Comment by nyalldawson** [comment]
@luipir 

I can't see a reliable way to do this within a 1 second timeout. The only option I can think of is trying to connect to some external (perhaps non-existent) database, but I'm very reluctant to do that as the last thing we need is another flaky unit test...

**Comment by luipir** [comment]
@nyalldawson probably only mocking the DB call. I give a short look and I didn't find any pre-prepared package for mocking DB interfaces (linke for ssh)
So I agree, in this moment, it's not reliable test it on a real db instance. The only is to brutally use mock to overload the db call. but it generally produce a test hard to read and maintan.

**Comment by haubourg** [comment]
What about calling a sql query with QgsTransaction.ExecuteSQL() and put a `pg_sleep(5)` timer in that call?

See https://www.if-not-true-then-false.com/2010/postgresql-sleep-function-pg_sleep-postgres-delay-execution/

**Comment by luipir** [comment]
@haubourg not sure it is applicable
"connect_timeout
Maximum wait for connection, in seconds (write as a decimal integer string). Zero or not specified means wait indefinitely. It is not recommended to use a timeout of less than 2 seconds."
It should refer only to the connection setup => if pg_sleep is in execution the connection is already opened. Am I wrong?

**Comment by haubourg** [comment]
@luipir oh you are right, sorry for the noise

**Pull request merged**
