### PR TITLE
Fix non-optional band parameter should not need to be specified

### LINKED ISSUE #54370: qgis_process doesn't always assume the default value of an algorithm argument
### What is the bug or the crash?

At least one algorithm exists (see below) – maybe many more – where an argument that has a default value still needs to be passed explicitly for it to work, otherwise it errors with _'The following mandatory parameters were not specified: ....'_.

There are other algorithms where not passing default arguments just works (e.g. not passing the `DISTANCE` argument of `native:buffer`). Hence foregoing error is inconsistent behaviour.

### Steps to reproduce the issue

```bash
$ wget -q https://github.com/r-spatial/qgisprocess/raw/main/inst/longlake/longlake.tif
$ 
$ gdalinfo longlake.tif -nomd | tail -12
Band 1 Block=553x4 Type=Byte, ColorInterp=Red
  Min=25.000 Max=255.000 
  Minimum=25.000, Maximum=255.000, Mean=186.550, StdDev=25.493
  NoData Value=255
Band 2 Block=553x4 Type=Byte, ColorInterp=Green
  Min=74.000 Max=255.000 
  Minimum=74.000, Maximum=255.000, Mean=213.882, StdDev=13.690
  NoData Value=255
Band 3 Block=553x4 Type=Byte, ColorInterp=Blue
  Min=46.000 Max=255.000 
  Minimum=46.000, Maximum=255.000, Mean=188.777, StdDev=29.440
  NoData Value=255
$ 
$ myJSON=$(</dev/stdin)
{
  "inputs": {
    "INPUT": "longlake.tif",
    "BAND": 1
  }
}
$ 
$ echo "$myJSON" | qgis_process run native:rasterlayerstatistics - | tail -10
  "results": {
    "MAX": 253.0,
    "MEAN": 186.31545289003526,
    "MIN": 25.0,
    "RANGE": 228.0,
    "STD_DEV": 25.51306231112349,
    "SUM": 47168179.0,
    "SUM_OF_SQUARES": 164787284.61674687
  }
}$ 
$ 
$ myJSON=$(</dev/stdin)
{
  "inputs": {
    "INPUT": "longlake.tif"
  }
}
$ 
$ echo "$myJSON" | qgis_process run native:rasterlayerstatistics - | tail -10
ERROR: The following mandatory parameters were not specified

	BAND:	Band number
$ 
$ qgis_process help native:rasterlayerstatistics
Raster layer statistics (native:rasterlayerstatistics)

----------------
Description
----------------
This algorithm computes basic statistics from the values in a given band of the raster layer.

----------------
Arguments
----------------

INPUT: Input layer
	Argument type:	raster
	Acceptable values:
		- Path to a raster layer
BAND: Band number
	Default value:	1
	Argument type:	band
	Acceptable values:
		- Integer value representing an existing raster band number
OUTPUT_HTML_FILE: Statistics (optional)
	Argument type:	fileDestination
	Acceptable values:
		- Path for new file

----------------
Outputs
----------------

OUTPUT_HTML_FILE: <outputHtml>
	Statistics
MIN: <outputNumber>
	Minimum value
MAX: <outputNumber>
	Maximum value
RANGE: <outputNumber>
	Range
SUM: <outputNumber>
	Sum
MEAN: <outputNumber>
	Mean value
STD_DEV: <outputNumber>
	Standard deviation
SUM_OF_SQUARES: <outputNumber>
	Sum of the squares
```

### Versions

```
$ qgis_process --version
QGIS 3.32.2-Lima 'Lima' (c0b88339649)
QGIS code revision c0b88339649
Qt version 5.15.3
Python version 3.10.12
GDAL/OGR version 3.6.4
PROJ version 9.1.1
EPSG Registry database version v10.076 (2022-08-31)
GEOS version 3.11.1-CAPI-1.17.1
SQLite version 3.37.2
OS Linux Mint 21.2
```

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
when a non-null default value is set for the parameter

Fixes #54370

### CODE REVIEW

**Review by alexbruy — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
May also other parameter types be affected by the same issue (e.g. QgsProcessingParameterCrs or QgsProcessingParameterRange)?

**Comment by nyalldawson** [comment]
@agiudiceandrea 

> May also other parameter types be affected by the same issue (e.g. QgsProcessingParameterCrs or QgsProcessingParameterRange)?

possibly, yes

**Comment by agiudiceandrea** [comment]
I can confirm that e.g. QgsProcessingParameterCrs also shows the incorrect behaviour and thus various algorithms, for which a default value of a non optional QgsProcessingParameterCrs parameter is defined, are affected by the issue: pdal:assignprojection, pdal:reproject, native:addxyfields, native:assignprojection, native:dxfexport, native:createpointslayerfromtable, ...

**Comment by nyalldawson** [comment]
@agiudiceandrea should now be fixed for ALL parameter types

**Pull request merged**
