### PR TITLE
[BUGFIX][Processing] Add getParameterDescriptions to R, Model and Scr…

### PR DESCRIPTION
**Pull request by rldhont**
…ipt algo

### CODE REVIEW

**Comment by m-kuhn** [comment]
https://travis-ci.org/qgis/QGIS/jobs/133069588#L1511-L1517

Greetings from a couple of seats in front of you

**Comment by rldhont** [comment]
@m-kuhn I have applied prepare-commit.sh and the indentation problem comes from a part of the code I didn't add.
But I update my commit and hope to pass indentation test.
Regards

**Comment by m-kuhn** [comment]
Strange, but thanks anyway 👍

**Comment by rldhont** [comment]
thanks @volaya

**Pull request merged**
