### PR TITLE
 [snapping widget] add advanced config widget in toolbar fix #16596

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by nirvn** [comment]
@3nids , what about adding a drop down toolbar button that would show the advanced widget panel when clicking on it? It'd not be visible by default and replace the all layers / active layers pair of combo boxes.

ATM I'm worried ppl won't get that an item has been added in a menu that's not shown unless they click on the button they just clicked to activate that mode.

**Comment by 3nids** [comment]
that would be a new button?
That was my first idea: buttons shows up when selecting advanced mode. But I'm a bit concerned of the number of buttons.

**Comment by nirvn** [comment]
@3nids , yeah a new button. You don't have to be concerned about the number of buttons as that one would replace the two combo boxes that are hidden for the advanced mode.

**Comment by 3nids** [comment]
@nirvn thanks for the feedback.
indeed, I find it a bit nice like you proposed:

**Comment by nirvn** [comment]
IMHO much better. We'll probably need a better icon there, but the eye one is a good temporary one to begin with :)

**Pull request merged**
