### PR TITLE
add test for #53426

### PR DESCRIPTION
**Pull request by MorriganR**
The test 'monitors' the number of SQL queries when opening a simple QGIS project with simple PostGIS layers in a single thread.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Thanks again @MorriganR !

If the intention here is to prevent additional queries being added on layer load, I am thinking that a better test would be to use a QSignalSpy on QgsApplication.databaseQueryLog watching the queryStarted signal. That would allow us to test  the actual number of queries executed, and may prove to be more reliable then a time based test...

What do you think?

**Comment by MorriganR** [comment]
In my opinion, both approaches have the right to exist, although they are not without flaws.
The main, I hope not the only, advantage of the proposed algorithm is that it is already implemented :)

To implement the 'databaseQueryLog' approach, you will need to consider the following:
- not all SQL queries are logged. For example, in the log you will not find a request generated by this [code](https://github.com/qgis/QGIS/blob/b516163f05aa21c55c0eae3e27806270c9a39ad6/src/providers/postgres/qgspostgresconn.cpp#L2000-L2007).
- if you allow project initialization in several threads, the total number of SQL queries will increase, although the project initialization time will decrease...

The more tests, the better, and unstable ones can be mercilessly turned off.

**Comment by nyalldawson** [comment]
> For example, in the log you will not find a request generated by this code.

Hmm,  off topic but that code looks ripe for optimisation/removal. It seems from this comment that it could be replaced by a simple version check:
https://github.com/qgis/QGIS/blob/b516163f05aa21c55c0eae3e27806270c9a39ad6/src/providers/postgres/qgspostgresconn.cpp#L1984

**Comment by MorriganR** [comment]
considering that [7.3](https://www.postgresql.org/docs/7.3/sql-declare.html#:~:text=endian%22%20versus%20%22-,little,-%2Dendian%22) is very old, this code can simply be removed...
since [7.4](https://www.postgresql.org/docs/7.4/sql-declare.html#:~:text=the%20value%20(in-,big%2Dendian,-byte%20order).), big-endian is supported

https://github.com/MorriganR/QGIS/pull/92

**Review by nyalldawson — APPROVED** [review]

**Comment by troopa81** [comment]
The test is failing, see https://github.com/qgis/QGIS/actions/runs/28007896777/job/82913416096?pr=66483#step:13:310


> ======================================================================
> FAIL: testProjectOpenTime (__main__.TestPyQgsPostgresProviderLatency.testProjectOpenTime)
> open project, provider-parallel-loading = False
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/root/QGIS/tests/src/python/test_provider_postgres_latency.py", line 193, in testProjectOpenTime
>     self.assertTrue(
>     ~~~~~~~~~~~~~~~^
>         duration > dmin and duration < dmax,
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         error_string.format(dmin, dmax, duration),
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     )
>     ^
> AssertionError: False is not true : expected from 7.41s to 7.91s, got 8.06s
> HINT: set davg=8.06 to pass the test :)
> 
> 
> 

IMHO, it's not a good idea to rely on timing evaluation for unit testing, especially when it's run on CI.

@MorriganR Shall we make the test flaky ?

**Pull request merged**
