### PR TITLE
Rename QgsVectorLayer::selectedFeaturesIterator to getSelectedFeatures

### PR DESCRIPTION
**Pull request by nyalldawson**
It's more in line with QgsVectorLayer::getFeatures, hence a more discoverable API

### CODE REVIEW

**Comment by 3nids** [comment]
why not just `selectedFeatures` ?

**Comment by nyalldawson** [comment]
> why not just selectedFeatures ?

Well, i'd like consistency with getFeatures. So if that was renamed to just .features(), then yes!

**Comment by 3nids** [comment]
makes sense, I was just thinking of coherence with Qt which no get*. One way or the other is fine with me.

**Comment by nyalldawson** [comment]
@wonder-sk can probably clarify, but I suspect that getFeatures was named with "get" because it's not a simple accessor. It actually performs a "get", so the verb is fitting.

**Comment by Gustry** [comment]
In the same kind of change, can we uniform `exportToWkt`, `asWkt` in QgsRectangle, QgsGeometry ...?

**Comment by wonder-sk** [comment]
I think "getFeatures()" is just coming from the fact that before we used to have "getNextFeature()" calls. Personally I wouldn't mind to change it to just "features()"

**Comment by nyalldawson** [comment]
> why not just selectedFeatures ?

Turns out selectedFeatures() is already taken - it returns a list of selected features. I'll stick with the rename to getSelectedFeatures() instead.

**Pull request merged**
