### PR TITLE
Add test for DBManager's PostGIS connector and plugin

### PR DESCRIPTION
**Pull request by strk**
Only enabled when ENABLE_PGTEST is set
Includes test for dbname-less URI (ref #10600 ref #16625 ref #16626)

The test connects to the `qgis_test` database, or what the
QGIS_PGTEST_DB variable requests (as per tests/README.md)

A raster table is added to the test postgis setup script,
for use by this new test.

### CODE REVIEW

**Comment by strk** [comment]
The test fails due to psycopg2 getting `bytes` instead of `str` when `.connect()` is called.
The value passed to `.connect()` in the code is the result of a `unicode(xxx)` on which `.encode('utf-8')` is invoked. Is that a legit path or did the test unveal an hiding bug ?

**Comment by strk** [comment]
@luipir you seem to have refactored a bit that place in Jan 2016 with 5fb798e220498222509b308c9def56c3bed6f42e - do you have comments on the double-encoding ?

**Comment by strk** [comment]
@m-kuhn you added the `unicode()` call in 2015 with 9fc1b48bf3ff46c2210bdbbc4d9353033da66f6a - do you remember why it was needed ?

**Comment by luipir** [comment]
@strk checking now

**Comment by strk** [comment]
Dropping the .encode('utf-8') results in an infinite loop in the [quoteString function](https://github.com/qgis/QGIS/blob/release-2_18/python/plugins/db_manager/db_plugins/connector.py#L197-L205)

I guess it's due to `__iter__` being defined for the `unicode()` returned object type but not for `string` type, but I don't really know what I'm talking about (anyway that quoteString function is suspicious)

**Comment by luipir** [comment]
@strk no problem from my point of view. About quoteString, I don't know if it make sense to move to some standard httplib or pglib that have quoting methods

**Comment by strk** [comment]
@luipir can you understand the problem with `TypeError: argument 1 must be str, not bytes` ?

**Comment by strk** [comment]
master branch (where the same test passes) contains this code:
```
      def _connectionInfo(self):                                                  
        return str(self.uri().connectionInfo(True))   
```

While 2.18 brench (which fails here) contains:
```
    def _connectionInfo(self):                                                  
        return unicode(self.uri().connectionInfo(True))  
```

This is in python/plugins/db_manager/db_plugins/postgis/connector.py
Both Master and Release-2.18 are run on Travis via python3 - Release-2.18 (unicode...) is failing with psycopg2 expecting `str` and not `bytes`...

Is it safe to replace `unicode` function with `str` then ? Does `travis` check for python2 support at all ?
\cc @jef-n

**Comment by strk** [comment]
python2 seems to work fine on my machine:
```
2: -- Running /usr/bin/python2.7 /usr/src/qgis/qgis-2.18/python/plugins/db_manager/db_plugins/postgis/plugin_test.py 
...
1/1 Test #2: dbmanager-postgis-plugin .........   Passed    0.46 sec
```

**Comment by strk** [comment]
Gah with the last change I get what looks like being an unrelated failure:
```
FAIL: testDoAction (__main__.TestQgsActionManager)

test running action

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/qgis/QGIS/build/output/python/qgis/testing/__init__.py", line 219, in wrapper

    func(*args, **kwargs)

  File "/home/travis/build/qgis/QGIS/tests/src/python/test_qgsactionmanager.py", line 208, in testDoAction

    self.assertEqual(self.check_action_result(temp_file), 'test output')

AssertionError: '' != 'test output'

+ test output
```

In https://travis-ci.org/qgis/QGIS/jobs/240025470#L1209-L1221

**Comment by m-kuhn** [comment]
@strk 9fc1b48 was a roundhousekick to get rid of the countless encoding issues that would only surface on non-english systems. It was expected to cause collateral damage - and it did. No objection to change that from my side.

**Comment by m-kuhn** [comment]
The qt4 test runs with python 2, the qt5 test runs with python 3
QGIS 3 runs only python 3

**Comment by luipir** [comment]
@strk "problem with TypeError: argument 1 must be str, not bytes ?" how to reproduce the error?seems the plugin si working fine with your changes

**Comment by strk** [comment]
Thanks for testing, Travis is also happy now (it was the python2 run
failing) !

**Comment by strk** [comment]
It looks like Travis is failing after the merge, but in an unrelated test (unstable one?):
https://travis-ci.org/qgis/QGIS/jobs/240378064#L1128-L1140

**Pull request merged**
