### PR TITLE
Add macro for c++11 "override" keyword, when available

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR adds the ability to mark methods with an "OVERRIDE" keyword. On compatible build environments (with c++11 support, currently only supported for gcc >= 4.7) this will evaluate to the c++11 [override](http://en.cppreference.com/w/cpp/language/override) specifier. On non c++11 environments OVERRIDE does nothing, so the build does not break.

Why? Well, it's got the potential to avoid a lot of bugs where derived classes don't correctly match the signature for base classes. I've run into these in the past, and it's easy for bugs of this nature to be introduced. We should make it standard practice for derived classes to mark all overriden methods with "OVERRIDE" to avoid this. See the included sample in src/core/symbology-ng/qgsvectorcolorrampv2.h for how this is achieved.

Note: I couldn't get c++11 enabled for clang/travis, which is a shame, but we still have a sufficient number of developers who build using gcc>=4.7 to quickly catch these errors.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Updated version fixes Travis compatibility. I'm confident this is the best approach now. We can't take advantage of anything fancy like target_compile_features because the cmake version available in Ubuntu/Debian predates the inclusion of those features.

**Comment by m-kuhn** [comment]
Good initiative. That's one of the features I really like in C++11.

Would it be possible to use `SET(CMAKE_CXX_STANDARD 11)`?
As far as I understand, that would advise CMake to use the standard if available and fallback to 98 in case it is not. This way we will not have to introduce compiler switches for everything out there.

**Comment by nyalldawson** [comment]
@m-kuhn that was also added in cmake 3.1, which is too new for us to utilise...

**Comment by wonder-sk** [comment]
I would welcome C++11 in our code base as there are lots of new features that would make coding easier (did anyone mention ```auto```?)

With the current approach I see an issue that all new c++11 features need to be provided with macros or #ifdef-ed - that's where we loose a bit of c++11's beauty. Also, any code including our headers need to replicate the extra defines in order to fix build errors of 3rd party issue (not a big deal I guess).

My suggestion would be to switch to c++11 with QGIS 3 when we will do more "big" changes - including switch to Qt5, Python3 and maybe newer CMake. The switch to c++11 would be complete, not just partial to use few features. That would require update of compilers on some platforms (e.g. at least msvc2010 on windows).

**Comment by nyalldawson** [comment]
@wonder-sk does that mean you're not in favour of merging this? In my opinion it's still worthwhile given the huge protection it gives us against breakage. I'm fine with waiting until QGIS 3.0 for real adoption of c++11, but I think an exception should be made for this case.

**Comment by wonder-sk** [comment]
I am just not too excited about this particular way of adopting c++11 features - but there's nothing wrong with the patch :-) so no objections from me to merge it...

**Comment by m-kuhn** [comment]
@nyalldawson Too bad... There would be the option to wrap it in a CMAKE_VERSION switch. But that also adds some complexity again and would kill travis support... Good for me then.

**Pull request merged**
