### PR TITLE
Add vertical scrollbar to raster calculator dialog

### LINKED ISSUE #55140: Raster Calculator dialog box is too large in the vertical using QGIS 3.34 Prizren
### What is the bug or the crash?

The size of the dialog box GUI for Raster Calculator is too large in the vertical, not allowing a user to select the buttons on the bottom of the box for processing. 

### Steps to reproduce the issue

Go to Raster on menu toolbar;
Click on Raster Calculator;
Fill out fields;
Attempt to click on Run or Cancel button, but unable to reach them below the edge of the screen. 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd678812
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.4
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PostgreSQL client version | 15.4 (Ubuntu 15.4-0ubuntu0.23.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.13.3
OS version | Ubuntu 23.04
  |   |   |  
Active Python plugins
AttributeAssignment | 2.3
processing | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd678812](https://github.com/qgis/QGIS/commit/ffbdd678812)
Qt version
5.15.8
Python version
3.11.4
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.40.1
PostgreSQL client version
15.4 (Ubuntu 15.4-0ubuntu0.23.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.13.3
OS version
Ubuntu 23.04

Active Python plugins
AttributeAssignment
2.3
processing
2.12.99
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

screen

### PR DESCRIPTION
**Pull request by DelazJ**
fixes #55140 

https://github.com/qgis/QGIS/assets/7983394/88f3c0b8-255b-49c3-8855-dd631ce03d85

### CODE REVIEW

**Comment by DelazJ** [comment]
@agiudiceandrea Do you mean in order to collapse the "raster bands" and "result layer" frames? Technically, yes, it is possible but these groups provide the main options of the dialog so i'm not sure they should be ever hidden (and you'd most of the times need to collapse both to see the lower blocks expand). Also there is a splitter above the Operators group so people can still vertically reduce/augment the two parts

Unless I misunderstand your point...

**Comment by agiudiceandrea** [comment]
In the video I see that it is not possible to reduce the dialog window height more than this:
image
i.e. it seems not possible to drag the bottom of the dialog window further upper.

**Comment by DelazJ** [comment]
Because I set a minimal size of the dialog so that the top part is still fully visible (and 540px high should be compatible with most of the screens). And for the bottom part going upper see below (not my changes, the feature was already there)

https://github.com/qgis/QGIS/assets/7983394/a0a481e2-6e37-4512-9f25-57806fc5d0b9

**Comment by agiudiceandrea** [comment]
> Because I set a minimal size of the dialog so that the top part is still fully visible (and 540px high should be compatible with most of the screens).

OK!

**Comment by DelazJ** [comment]
This should be good @qgis-bot

**Comment by DelazJ** [comment]
still relevant IMHO @qgis-bot

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
