### PR TITLE
[hidpi] Fixed icon size and line height

### PR DESCRIPTION
**Pull request by elpaso**
in attribute list view

@m-kuhn need testing with normal screens, follows #2259

### CODE REVIEW

**Comment by m-kuhn** [comment]
Almost good!

The icon itself seems to be cropped top and left (the dotted border is
not visible there)

**Comment by elpaso** [comment]
mmm... I see it still not centerd but complete:

pisalistview2

**Comment by m-kuhn** [comment]
I assume it is an SVG scaling issue. We probably need to restrict icon sizes to multiples of the original size.

**Comment by elpaso** [comment]
Superseded by PR #2350

**Pull request closed without merging**
