### PR TITLE
Re-enable travis checks for build warnings

### PR DESCRIPTION
**Pull request by m-kuhn**
## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Hmm...

Just **re-enabling building with ctest**

 * Submits to dash (+)
 * Fails on warnings (+)
 * Link is broken, could probably be fixed (0)
 * Does not print warnings and build errors on travis (-)
 * Times sometimes out because no output received in 10 minutes (--)

**Running ctest with -VV**

 * Prints build errors and warnings on travis (+)
 * Prints the whole build log on travis (-)
 * Prints the whole test output, even successful on travis (--)
 * May get better with https://gitlab.kitware.com/cmake/cmake/issues/17731

**`-Werror`

 * Build outside ctest, like we have been doing for the last months
 * Should promote warnings to errors
 * Warnings only on travis (and not dash)
 * Probably required to make it an option (to be able to build with warnings locally while working on code)

**Comment by 3nids** [comment]
What we could do is bring the dash link as a comment. So instead of looking at Travis we would look on Dash. 
What do you think?

**Comment by m-kuhn** [comment]
I went for the last solution which works well.
Linking has always been a very fragile construct (I've never managed to get a reliable link to the dash results)

**Comment by m-kuhn** [comment]
Yes, the best would be to somehow count the warnings and then fail after the tests based on this count. I thought gccfilter could help but didn't get it to work in time.
So for no one will have to fix warnings before getting any test results.

**Pull request merged**
