### PR TITLE
Add atlas scopes to layer expression dialogs

### PR DESCRIPTION
**Pull request by roya0045**
## Description

As suggested in #40069 and some more.

First commit message was a brainfart, gotta have one per PR.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Have you tested this?

**Comment by roya0045** [comment]
@nyalldawson Yes, the variables appear in the dialog and the data previewed is correct in my test. I tested on lubuntu. I can also test the generated MXE if you want.

**Comment by roya0045** [comment]
@nyalldawson Had more time to test, values display in the dialog, and in the preview but scope seems missing at eval time. Forgot the scopes were separated.

**Comment by roya0045** [comment]
Closing for now, maybe not worth it since there will never realise in a layout context anyway. Though I can see the use of a virtual field in such context.

**Pull request closed without merging**
