### PR TITLE
use new settings API

### PR DESCRIPTION
**Pull request by 3nids**
@mhugent it seems the setting was never modifier. Is this expected?

### CODE REVIEW

**Comment by mhugent** [comment]
Thanks for changing the settings-call to the new new api

> @mhugent it seems the setting was never modifier. Is this expected?

Main use-case is that it can be set in the ini-File by admin. If the option is of broader interest, I'm happy adding it to the option dialog too.

**Comment by 3nids** [comment]
@mhugent  setting it in the ini file means it's read-only and is not very handy. 
I believe that if there is a setting it should indeed be added to gui. So, yes, it'd be great if you can add to gui too :)

**Comment by 3nids** [comment]
@mhugent can you approve this one in the mean time?

**Review by troopa81 — APPROVED** [review]

**Comment by 3nids** [comment]
@mhugent are you still planning to expose this new setting? cheers.

**Comment by mhugent** [comment]
> @mhugent are you still planning to expose this new setting? cheers.

Yes, I'm still planning to do this. Sorry for the delay.

**Pull request merged**
