### PR TITLE
fixes #13668 (Delete does not work in the Vertex Editor)

### PR DESCRIPTION
**Pull request by PeterPetrik**

### CODE REVIEW

**Comment by NathanW2** [comment]
First time contributor?

**Comment by PeterPetrik** [comment]
Yes, kind of :) Working in Lutra Consulting with Martin Dobias

**Comment by NathanW2** [comment]
Good stuff.  I see @nyalldawson has assigned him self for review so I will let him do it.

**Comment by nyalldawson** [comment]
Hi @PeterPetrik,

Thanks for sending this through (I was actually thinking of tackling it tomorrow, so it's good timing!). I'm not sure it's the right approach though - a much cleaner/safer way would be to implement removeRows in QgsNodeEditorModel . see http://doc.qt.io/qt-4.8/qabstractitemmodel.html#removeRows .

**Comment by PeterPetrik** [comment]
I do not understand fully how QgsNodeEditorModel::removeRows would simplify the code. It seems to me that with removeRows it would be harder to use existing functionality from QgsSelectedFeature (deleteSelectedVertexes)? Can you please explain in more details?

I just tried to reuse the existing working functionality from https://github.com/qgis/QGIS/blob/master/src/app/nodetool/qgsmaptoolnodetool.cpp#L653-L674 with minimal change to other parts of code

**Comment by PeterPetrik** [comment]
Hi @nyalldawson,

can I ask what is the progress with this PR and bug? It would be nice to have it fixed for the LTR. Thanks

**Comment by nyalldawson** [comment]
Manually merged - thank you!

**Pull request closed without merging**
