### PR TITLE
 [FEATURE] Add right click menu option to "open directory" to welcome page entries

### PR DESCRIPTION
**Pull request by nyalldawson**
Allows easy opening of the folder containing a project from the welcome page, e.g. to check if a newer version of the project is in the same folder.

Also speed up welcome page for network based projects.

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , implementing a right-click menu for welcome page items? Wouhou! I think you'd please the whole universe if you add a "remove from history" item there 😉

**Comment by lbartoletti** [comment]
In addition to what @nirvn proposes, can we delete the list of recent projects from the menu? 😉

**Comment by m-kuhn** [comment]
Nice feature, @nyalldawson 

> @nyalldawson , implementing a right-click menu for welcome page items? Wouhou! I think you'd please the whole universe if you add a "remove from history" item there :wink:

:+1: pull requests for this can use the priority queue 

> In addition to what @nirvn proposes, can we delete the list of recent projects from the menu? :wink:

Do you mean remove it from the projects menu? I use this quite often.

**Comment by nyalldawson** [comment]
> Wouhou! I think you'd please the whole universe if you add a "remove from history" item there 

Happy for someone else to do this (should be quite straightforward after this is merged), but there's 0 chance I can before freeze...

**Pull request merged**
