### PR TITLE
Added grass76 support

### PR DESCRIPTION
**Pull request by neteler**
Added grass76 support; search for newer versions first

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
I guess this needs backporting too?

**Comment by neteler** [comment]
> I guess this needs backporting too?

Yes please. Does it require a separate PR?

**Comment by m-kuhn** [comment]
It would be great if you could prepare one (or even one for 3.4 and one for 2.18?)

**Comment by sebastic** [comment]
`grass76` also needs to be added in `python/plugins/processing/algs/grass7/Grass7Utils.py`:
```diff
--- a/python/plugins/processing/algs/grass7/Grass7Utils.py
+++ b/python/plugins/processing/algs/grass7/Grass7Utils.py
@@ -84,7 +84,7 @@ class Grass7Utils:
         if Grass7Utils.grassPath() is None:
             return None
 
-        for command in ["grass74", "grass72", "grass71", "grass70", "grass"]:
+        for command in ["grass76", "grass74", "grass72", "grass71", "grass70", "grass"]:
             proc = subprocess.Popen(
                 ["{} -v".format(command)],
                 shell=True,
```

**Comment by neteler** [comment]
Ah, sorry for the oversight.
See new  PR #8908 (master), PR #8909 (release-2_18), PR #8910 (release-3_4)

**Pull request merged**
