### PR TITLE
Remove trusted status from Plugin Manager

### PR DESCRIPTION
**Pull request by DelazJ**
Discussion at http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Reword-quot-Trusted-Plugin-quot-gt-quot-Trusted-Plugin-Author-quot-td5334047.html

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]
Looks good to me code-wise

Can you comment on the functionality level about the mid-term goal.

Is the label expected to be replaced with something focussed on the author or is this the final state?

**Comment by DelazJ** [comment]
Afaics no decision has been taken in the discussion. Only proposals were made so i chose the one that looked better to me, unless someone comes with a clear and short label about trusted status (and even in that case i'm not sure this information is worth showing there; it's devs internal affairs). Unless there's a system that objectively classifies all plugin authors,  Imho we should avoid any label that could "segregate" plugin authors and instead focus on means to improve users' choice (the most suited plugin) :
- promote the voting system (with a tooltip?)
- show what's new when new version is available (to help user decide if it's worth updating)
- show download statistics (not the total of downloads, regardless the number of versions but either the mean, the maximum... )
- display user comments on plugins (QGIS4?)
... 
But maybe i'm already out of the scope of your question (and this PR)

**Comment by timlinux** [comment]
I'm OK with hiding it from end users but still having trusted authors as a mechanism for self approval of plugins on the backend. If that is your intent +1 from me.

**Comment by DelazJ** [comment]
Yes of course, we should keep the trusted mechanism in the backend. The intent of this PR is just to hide it from the users; it shouldn't do more...

**Comment by m-kuhn** [comment]
@timlinux do you think such a change is worth a public announcement?

**Comment by borysiasty** [comment]
+1 for removing the greens from 3.0
Especially that the trusted plugins are not always those heavy used, so users may be confused with such odd selection of 'recommended' plugins.

Please write or link any suggestions to the ML topic mentioned above or to  https://issues.qgis.org/issues/17349 - otherwise we'll get lost ;)

**Comment by DelazJ** [comment]
Given recent mails in psc list, i'd like to know the status of this pr. Thanks.

**Comment by m-kuhn** [comment]
Let's go ahead and merge, there's consensus that the current situation needs to change. We can then review better solutions as they are proposed. Thanks @DelazJ

**Comment by m-kuhn** [comment]
Merged

**Comment by m-kuhn** [comment]
I think this is worth being mentioned in the visual changelog, can we somewhere open an issue so we don't forget this?

@timlinux is there such a place?

**Comment by DelazJ** [comment]
Thanks @m-kuhn 
And i agree that some information/explanation should be  provided for the whole community.

**Comment by Gustry** [comment]
We can start editing the changelog. I added a new entry quickly: changelog.qgis.org/en/qgis/version/3.0.0/#remove-trusted-status-from-plugin-manager

**Comment by m-kuhn** [comment]
Thanks @Gustry 
Does that mean that this time we will not have an auto-compiled changelog from the commit history?

**Comment by jef-n** [comment]
@m-kuhn the visual changelog is not made from the commit log.

**Comment by m-kuhn** [comment]
@jef-n IIRC the initial import always was created (by @timlinux ?) by grepping for `[FEATURE]` tags

**Comment by DelazJ** [comment]
I couldn't find the reference but i think i've recently see a call from @timlinux for help to set up the changelog so a great part ofbthe work might not be automated...

**Pull request closed without merging**
