### PR TITLE
Typo and PEP8

### PR DESCRIPTION
**Pull request by Gustry**
After the great addition from @nyalldawson, I'm just fixing some PEP8 in the generated code

### CODE REVIEW

**Comment by Gustry** [comment]
Thanks for merging.
There are still some PEP8 errors in the generated code, but the other ones are harder to fix.

**Comment by nyalldawson** [comment]
@gustry got some examples?

**Comment by Gustry** [comment]
I just made #9067 for another one.

I was looking at https://github.com/qgis/QGIS/blob/master/tests/src/analysis/testqgsprocessing.cpp#L6986
It must be `DISSOLVE': False,` but when I changed, it updated some variable name at the same time. I didn't look deeper.

**Comment by nyalldawson** [comment]
@Gustry: see #9077

**Pull request merged**
