### PR TITLE
Fix marker rotation v2

### PR DESCRIPTION
**Pull request by nyalldawson**
Possibly supersedes #2234, also implements rotation of symbols for rule-based renderers

### CODE REVIEW

**Comment by m-kuhn** [comment]
@nyalldawson Why no quotation?

**Comment by nyalldawson** [comment]
@m-kuhn it breaks what this is trying to fix :P the output was passed to fieldNameIndex, which doesn't handle field names surrounded by quotes. It also matches the previous behaviour of the rotationField method.

**Comment by 3nids** [comment]
I suppose this won't be a candidate for backporting to 2.8/2.10?

**Comment by nyalldawson** [comment]
It will apply to 2.10, but not 2.8

**Comment by m-kuhn** [comment]
@nyalldawson But it won't work as expression for field names with spaces, this method should IMO primarily return a valid expression. If you want something to pass to fieldNameIndex you should rather call field() instead.

**Comment by nyalldawson** [comment]
I've manually pushed this branch to master... I'll leave the other PR open till we decide what to do with 2.10

**Pull request closed without merging**
