### PR TITLE
[FEATURE][welcome page] Add pin/unpin to list actions

### PR DESCRIPTION
**Pull request by nirvn**
## Description
It can be useful to "pin" project(s) to the recent projects list to insure those will never be purged. This PR implements that, and places pinned projects on top of the welcome page list upon QGIS launch. In addition, pinned items aren't counted as part of recent projects, keeping the recent project list's maximum of 10 items for non-pinned recent projects.

Screenshot:
screenshot from 2017-10-26 19-22-27

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by DelazJ** [comment]
@nirvn have you seen https://issues.qgis.org/issues/16394? 😄

**Comment by m-kuhn** [comment]
Unacceptable without an icon

pin

```
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="24" height="24" viewBox="0 0 24 24"><path d="M16,12V4H17V2H7V4H8V12L6,14V16H11.2V22H12.8V16H18V14L16,12Z" /></svg>
```

**Review by m-kuhn — CHANGES_REQUESTED** [review]
Unacceptable without an icon :stuck_out_tongue_closed_eyes: 

pin 


```
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="24" height="24" viewBox="0 0 24 24"><path d="M16,12V4H17V2H7V4H8V12L6,14V16H11.2V22H12.8V16H18V14L16,12Z" /></svg>
```

**Comment by timlinux** [comment]
nice stuff!

**Comment by nyalldawson** [comment]
Nice!!

And now that I've had some sleep... I'm wondering:

-  if the open directory option should also be done by making the project path a hyperlink in the list
- should we add a "clear all" option?
- we should add a date to that list (date of when the project was added to the recent list - i.e. last interaction with the project, not the file's modified date)
- I'm so disappointed we couldn't get https://github.com/qgis/QGIS-Enhancement-Proposals/issues/102 done for 3.0 :(

**Comment by nirvn** [comment]
@m-kuhn , implemented:
screenshot from 2017-10-27 10-03-19

**Pull request merged**
