### PR TITLE
Fix leaks in metal rough material

### PR DESCRIPTION
**Pull request by nyalldawson**
We need to explicitly parent all these objects to the material, as we only selectively add them to entities depending on the material settings. If we don't explicitly parent, then they won't all get added to entities and will ultimately leak...

### CODE REVIEW

**Comment by nyalldawson** [comment]
@wonder-sk look ok to you?

**Review by wonder-sk — APPROVED** [review]
It looks fine to me... But did you find any actual memory leaks? Because some time ago I was wondering about parenting of qt3d objects as well, and figured out that qt3d silently sets parents of "child" objects if none are set. See for example [QMaterial::setEffect](https://github.com/qt/qt3d/blob/aef0bd2ec708e13dbbb5dedf9d2deb7ff2acca2f/src/render/materialsystem/qmaterial.cpp#L204) or [QEffect::addParameter](https://github.com/qt/qt3d/blob/aef0bd2ec708e13dbbb5dedf9d2deb7ff2acca2f/src/render/materialsystem/qeffect.cpp#L159). This behavior is not documented of course :smile:

**Comment by nyalldawson** [comment]
@wonder-sk 
> It looks fine to me... But did you find any actual memory leaks?

Yes, running the gltfutils test under asan shows leaks.

> Because some time ago I was wondering about parenting of qt3d objects as well, and figured out that qt3d silently sets parents of "child" objects if none are set. See for example [QMaterial::setEffect](https://github.com/qt/qt3d/blob/aef0bd2ec708e13dbbb5dedf9d2deb7ff2acca2f/src/render/materialsystem/qmaterial.cpp#L204) or [QEffect::addParameter](https://github.com/qt/qt3d/blob/aef0bd2ec708e13dbbb5dedf9d2deb7ff2acca2f/src/render/materialsystem/qeffect.cpp#L159). This behavior is not documented of course 😄

Right, but in this case we are just creating the child objects but not always using them in calls to addParameter or setEffect.  Eg mAmbientOcclusionMapParameter is only added when setAmbientOcclusion is called with a texture value, otherwise we do nothing with it and it's just a unused but allocated object.

**Comment by wonder-sk** [comment]
> Right, but in this case we are just creating the child objects but not always using them in calls to addParameter or setEffect. Eg mAmbientOcclusionMapParameter is only added when setAmbientOcclusion is called with a texture value, otherwise we do nothing with it and it's just a unused but allocated object.

Ahh right, good point! :+1:

**Pull request merged**
