### PR TITLE
Fix r.grow.distance

### LINKED ISSUE #31048: r.grow.distance in the QGIS 3.8.1 with GRASS 7.6.1
Hello

There is the following bug in the r.grow.distance in the QGIS 3.8.1 with GRASS 7.6.1

If i try to use the r.grow.distance with the setting "Output distances in meters instead of map units" I get the error "ERROR: Output distance in meters for lat/lon is only possible with 'metric=geodesic'"

There are only 4 options for metrics euclidean,manhattan,squared,maximum.

**TO FIX IT**

Find the r.grow.distance.txt in the pc and add the geodesic like the following line

QgsProcessingParameterEnum|metric|Metric|euclidean;squared;maximum;manhattan;geodesic|False|0|True

### PR DESCRIPTION
**Pull request by dimitrisal**
Bug fix for ERROR: Output distance in meters for lat/lon is only possible with 'metric=geodesic'

Fix #31048

### CODE REVIEW

**Comment by dimitrisal** [comment]
Bug fix for ERROR: Output distance in meters for lat/lon is only possible with 'metric=geodesic'

**Comment by roya0045** [comment]
Bugfix for #31048

**Comment by m-kuhn** [comment]
@alexbruy does that look good to you?

**Review by alexbruy — APPROVED** [review]

**Comment by m-kuhn** [comment]
@alexbruy and everyone, backport to 3.8 only or 3.4 too?

**Comment by alexbruy** [comment]
@m-kuhn I would vote for backport to 3.8 and 3.4 as this is bugfix. If I'm not wrong 3.4 uses same GRASS version as 3.8 and master, so this shoiuld be safe.

**Comment by m-kuhn** [comment]
Perfect, I've opened both pull requests.
Thanks @dimitrisal @roya0045 and @alexbruy

**Pull request merged**
