### PR TITLE
QgsProperty is not virtual

### PR DESCRIPTION
**Pull request by m-kuhn**
Should allow to remove the vtable for QgsProperty (aka micro optimizing)

### CODE REVIEW

**Comment by nyalldawson** [comment]
Good luck with this -- I agree that it's technically correct, but I wasted a good day or so on this originally and couldn't find any solution to getting all the tests passing except for the virtual destructor 🤔 (and yes, it makes no sense)

**Comment by m-kuhn** [comment]
It's not about the compiler but the tests?
Let's see when mr travis is back on his feet then.

**Comment by nyalldawson** [comment]
Yep -- it's going back a number of years, but I think it was the only way to fix a test which round tripped QgsProperty values through QVariants

**Comment by m-kuhn** [comment]
@nyalldawson your call ...

**Comment by nyalldawson** [comment]
Hmmm - not sure.

Here's some historical context:

https://github.com/qgis/QGIS/commit/fa26b4573696a2f7983c9d6b6d92c08888b0d120#diff-025b397c13179c6d84074cee157c2dcc255a3a39282b46452eafa69817491b0b
https://github.com/qgis/QGIS/commit/858129ddd3072d633e0abd97e1a45fe880f4cfb2#diff-025b397c13179c6d84074cee157c2dcc255a3a39282b46452eafa69817491b0b
https://github.com/qgis/QGIS/commit/cb68c982b829ecf94b19f9b9a030a269e1c2239f#diff-025b397c13179c6d84074cee157c2dcc255a3a39282b46452eafa69817491b0b
https://github.com/qgis/QGIS/commit/2a8555e13eb9a0e6bc0a24502ddb034f1aa1a3ac#diff-025b397c13179c6d84074cee157c2dcc255a3a39282b46452eafa69817491b0b
https://github.com/qgis/QGIS/commit/3652fa7e2b3454cb6fecfdfed3697736cb3f3fab#diff-025b397c13179c6d84074cee157c2dcc255a3a39282b46452eafa69817491b0b

Previously it was triggering these failures: https://travis-ci.org/github/qgis/QGIS/jobs/225036233, so it does look like sip/qt has fixed the underlying issue somewhere in the meantime. I suggest we don't backport this though!

**Comment by m-kuhn** [comment]
Let's give it another try.
Master only
Finger on the revert button ...

**Pull request merged**
