### PR TITLE
Add api to allow QgsBlendModeComboBox to show clipping style blend modes

### PR DESCRIPTION
**Pull request by nyalldawson**
Suggestions needed for improved wording on the strings for the clipping modes!

### CODE REVIEW

**Comment by m-kuhn** [comment]
Seems hard to find a good and catchy short wording. What about a tooltip?

**Comment by nyalldawson** [comment]
>Seems hard to find a good and catchy short wording. 

Yeah, I'm struggling here. We could just go with the Qt naming, but even to me that's rather opaque and I always need to find an illustration to interpret them.

> What about a tooltip?

Unfortunately tooltips for items in comboboxes don't seem well supported across different platforms. I can add them, but from memory they'll only show for Windows.

Another option would be to try and make some icons which demonstrate these, to at least give some visual clue. @nirvn what do you think?

**Comment by nirvn** [comment]
Even an icon would be hard to decipher  --  maybe we just need to add an help button next to the combo box that directs people to a relevant HTML documentation (Qt or something we make ourselves).

**Review by nirvn — APPROVED** [review]

**Comment by nirvn** [comment]
In any case, I think we should defer a (needed) solution in a follow up PR.

**Pull request merged**
