### PR TITLE
Disable msys2 workflow

### PR DESCRIPTION
**Pull request by nyalldawson**
This is broken and requires changes to handle newer protobuf versions

### CODE REVIEW

**Comment by nyalldawson** [comment]
Refs #53773

**Comment by MehdiChinoune** [comment]
we patch qgis to build with latest protobuf https://github.com/msys2/MINGW-packages/blob/92d0f0f63f0f42760eae61a71be04d23ab6eb9e6/mingw-w64-qgis/005-fix-build-with-protobuf-23.patch
imported from Arch https://gitlab.archlinux.org/archlinux/packaging/packages/qgis/-/blob/94f9630063006f9e1876482f73764f50fee5531b/protobuf-23.patch

**Comment by MehdiChinoune** [comment]
Shouldn't MSYS2 re-enabled after https://github.com/qgis/QGIS/pull/53962

**Comment by MehdiChinoune** [comment]
@nyalldawson

**Pull request merged**
