### PR TITLE
[Processing] Union fix and test

### PR DESCRIPTION
**Pull request by ghtmtt**
## Description
Small fix for the Union algorithm and tests added

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by ghtmtt** [comment]
No idea why Travis fails on my fork. If this PR cannot be merged, if someone can take the super small patch for the Union algorithm and apply it.

@m-kuhn @nyalldawson could you have a super super quick look at it? In case we can drop the test and apply just the patch. Thanks

**Comment by luipir** [comment]
it's a timeout and the fail is not related with this PR. @m-kuhn lately you workd on some timeout travis issues. what could be the problem?

**Comment by ghtmtt** [comment]
@luipir thanks for the clarification. Travis fails also on my local fork, but not due to timeout, but for other reasons not related to the commit I guess (https://travis-ci.org/ghtmtt/QGIS/jobs/301896017#L651)

**Comment by luipir** [comment]
some commit is braking compilation. btw not related with yout PR. Seems fixed with ec9e87d6f464c76860b7713c6f4a269d56eefb8c try to fetch and merge your master

**Comment by ghtmtt** [comment]
or merged.. let's see. thanks @luipir in the meanwhile ;)

**Comment by Gustry** [comment]
@ghtmtt Was it working with your fork before in Travis? I've read on the ML that only the qgis/QGIS repo has an extra time for building to avoid timeout. Maybe I'm wrong.

**Comment by ghtmtt** [comment]
@Gustry was working time ago. I'm sure you are right that extra time is only on the main repo. BTW Travis on my fork is failing not for timeout but for other reasons.

**Comment by nyalldawson** [comment]
Manually merged - thanks!

**Pull request closed without merging**
