### PR TITLE
Disable message hook and import override at runtime

### PR DESCRIPTION
**Pull request by dmarteau**
The file qgisutils.py implements some hacks for handling plugins and display informations in the qgis environnement: they prove to be useful in the context of qgis desktop which is a more or less a controlled environment.

But in a headless situation in a normal python development environment, they bring more issues than those they try to solve:

- Override global behavior by installing custom hooks: in a headless environnement the should be controlled by the main application since qgis is intended to be used as a module.

The default implementation assumes that ui and gui elements are active and thus leads to undefined objects - see implementation of showException.

- Hack on builtin\_import: the current implementation directly temper with import at global scope: unfortunately the utils.py implementation is not reentrant and that leads to very nasty side effects: as an exemple, pytest environment has a lazy attribute loading mechanism on error that trigger an import when dereferencing some module attribute. This leads to infinite recursion when dereferencing __dict__.

These workaround do not always make sense in an headless environment, some should be refactorized so has not to use internal python import mecanisms.

As a quick fix to ease headless python application developpement, I suggests te disable some features with environment variables.
These variables will disable message hook and plugin unload capability at runtime.

From this we could think about a saner way to reeimplement these functionalities.

### CODE REVIEW

**Review by elpaso — APPROVED** [review]

**Comment by m-kuhn** [comment]
I like the idea.
Would it make sense to add these env variables when testing on travis?

**Comment by dmarteau** [comment]
@m-kuhn If you have issues with import overrides or error handler in Travis, yes. The only side effect is to disable plugins reloading capability.

**Comment by m-kuhn** [comment]
I guess so, I remember quite a few additional errors in python tests because no messagebar.
Could you add that here https://github.com/qgis/QGIS/blob/master/.docker/docker-compose.travis.yml

**Comment by dmarteau** [comment]
@m-kuhn I have updated the travis docker-compose.

**Review by m-kuhn — APPROVED** [review]
LGTM

**Comment by dmarteau** [comment]
@NathanW2 Any objections ?

**Comment by dmarteau** [comment]
@NathanW2  ping ?

**Comment by rldhont** [comment]
@NathanW2 if no objection, I will merge it today.

**Comment by NathanW2** [comment]
Sorry.  Good to merge.

**Pull request merged**
