### PR TITLE
New Icons for QGIS File Formats

### PR DESCRIPTION
**Pull request by SrNetoChan**
Added icons for QGIS file formats: QML, QGS, QLR and QPT. Also added specific icons for most common data file formats that could be viewed or edited in QGIS (some icons were already available in mac, but I have created new icons)

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@m-kuhn I have messed up with git on the other Pull request, so I have closed it. Can you please set the milestone for this as 1.4? Thanks

**Comment by SrNetoChan** [comment]
@m-kuhn Can I do anything about the failing test on travis?

**Comment by m-kuhn** [comment]
@SrNetoChan I restarted the tests. It was probably caused by an originally bad timing of running the tests (master was in a bad shape then).

**Comment by jef-n** [comment]
Seems to be a NOP except for OSX.

**Comment by SrNetoChan** [comment]
@jef-n Is there anything else that I can do to help Windows and Linux Packaging?

**Comment by m-kuhn** [comment]
Can we just merge this and leave it to the packagers to include it?

**Comment by Scimmia22** [comment]
jef-n, you can't expect everyone to be familiar with the pedantic rules of Debian packaging. This just makes the icons available.

**Comment by jef-n** [comment]
@Scimmia22 I was implying that it at least adds the icons to OSX.  Are you saying it doesn't even do that?

**Comment by Scimmia22** [comment]
I have no idea what it does for OSX. I'm simply saying that making the icons available is enough.

**Comment by jef-n** [comment]
@Scimmia22 for what?   We are in feature freeze so only bugfixes should currently go in.  Not sure if it's an (incomplete) feature, but it's clearly not a fix.

**Comment by Scimmia22** [comment]
@jef-n Feature freeze started 5 days ago, this was proposed long before that.
Nobody said it had to go in now, either.

**Comment by jef-n** [comment]
@Scimmia22 see https://lists.osgeo.org/pipermail/qgis-developer/2016-January/041006.html

**Comment by SrNetoChan** [comment]
@jef-n you are the responsible for the road map. Besides, you are the package manager for Windows and linux. Without your permission (and your help), this PR won't have any effect on users. So, I will have to respect your decision, and I sorry for trying to break the rules.

@mkuhn can you please set the milestone for a later version? Thanks

**Comment by NathanW2** [comment]
@SrNetoChan just bumped to 2.16 if that is alright with you.

**Changes required after feature freeze**: Updates to packages

**Comment by SrNetoChan** [comment]
Sure! Thanks.

**Pull request merged**
