### PR TITLE
fix duplicate point at the beginning of a digitized curve #39974

### LINKED ISSUE #39974: Unable to save created curved geometries
### Support for CurvePolygon, CompoundCurve and CircularString

To test the support for these primitive geometry types, I have used the wedge buffer tool. I've created a point and then a wedge buffer around it (in memory). The geometry (wkt) created is:
```
CurvePolygon (CompoundCurve (CircularString (-23776 205602, -23772 205603, -23768 205602),(-23768 205602, -23770 205598),CircularString (-23770 205598, -23772 205598, -23774 205598),(-23774 205598, -23776 205602)))
```
The following print screen show this setup.
wedge buffer

#### Store the geometry on the providers Postgis and Geopackage

By just dragging and drop, **I can store this wedge buffer using both the Geopackage and Postgis providers**. On both providers, the geometry is stored using this primitive geometries CurvePolygon, CompoundCurve and CircularString.

### Editing existing geometry works!

If I edit an existing geometry with `CurvePolygon` (change vertexes, for example) it can be saved back to the provider.

To reproduce:

1. Open a wedge buffer generated layer
2. Edit one geometry
3. Save the layer

Works both for Geopackage and Postgis.

### The problem

If I edit the layer and **create a new geometry using the curve tool**, I'm not able to store it. 

#### To reproduce using Geopackage

1. Create a layer in Geopackage, CurvePolygon type (or use and existent CurvePolygon with existent CurvePolygon geometries)
2. Create a feature, using the Curve tool
3. Save the layer

The provider return the error:
```
OGR error creating wkb for feature -29: Invalid curve: not enough points
```
#### To reproduce using Postgis

The same happens for the Postgis provider. 

1. Create a layer in Postgis, CurvePolygon type (or use and existent CurvePolygon with existent CurvePolygon geometries)
2. Create a feature, using the Curve tool
3. Save the layer

The error returned is:
```
  Provider errors:
      PostGIS error while adding features: ERROR:  LineString must have at least two points
    CONTEXT:  SQL function "st_geomfromwkb" statement 1
```
In the postgresql log, the error reported is:
```
LOG:  statement: BEGIN
ERROR:  LineString must have at least two points
CONTEXT:  SQL function "st_geomfromwkb" statement 1
STATEMENT:  INSERT INTO "public"."lotes_p_curve"("geom") VALUES (st_geomfromwkb($1::bytea,3763)) RETURNING "id"
statement: ROLLBACK
statement: DEALLOCATE addfeatures
(...)
```
### WKT of the created geometry

It fails to write the feature to the provider. But while it is in memory, and can check its wkt representation, with looks fine to me:
```
CurvePolygon (CompoundCurve ((-23798 205603),(-23798 205603, -23786 205603),CircularString (-23786 205603, -23790 205597, -23798 205595),(-23798 205595, -23798 205603)))
```
I'm using this tiny PyQGIS to dump the wkt representation:
```python
layer = iface.activeLayer()

for f in list(layer.getFeatures()):
    geom = f.geometry()
    print(geom.asWkt(0))
```
QGIS is able to parse this Wkt representation back to a geometry:
```python
c = QgsGeometry().fromWkt("CurvePolygon (CompoundCurve ((-23798 205603),(-23798 205603, -23786 205603),CircularString (-23786 205603, -23790 205597, -23798 205595),(-23798 205595, -23798 205603)))")
print(c)
print(QgsWkbTypes.displayString(c.wkbType()))
```
Result:
```
<QgsGeometry: CurvePolygon (CompoundCurve ((-23798 205603),(-23798 205603, -23786 205603),CircularString (-23786 205603, -23790 205597, -23798 205595),(-23798 205595, -23798 205603)))>
CurvePolygon
```

### QGIS version

QGIS version | 3.17.0-Master
Compiled against Qt | 5.12.8
Compiled against GDAL/OGR | 3.3.0dev-5a81e514d8-dirty
Compiled against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1
PostgreSQL Client Version | 13.0 (Ubuntu 13.0-1.pgdg20.04+1)
QWT Version | 6.1.4
Compiled against PROJ | 7.2.0

### PR DESCRIPTION
**Pull request by vcloarec**
fix #39974

### CODE REVIEW

**Comment by jgrocha** [comment]
Tested locally. Looks good to me.

**Comment by uclaros** [comment]
Is this simple functionality not covered by a unit test?

**Comment by jgrocha** [comment]
> Is this simple functionality not covered by a unit test?

### GUI based interaction

Digitizing is an edit operation. It is not easy to write unit tests for that. This has to be validated by a human.

Since we have a large user base, we hope that this kind of regressions are identified before release. That was not the case here.

### Improve geometry validation

Instead of a unit test, it would be possible to check the geometry validity captured by the editing operation. That would ensure that no invalid geometries would be around.

In this case, the default validation does not detect the problem (returns `[]`) neither the GEOS validation. We need to improve the validation.

```python
geom = QgsGeometry.fromWkt("CurvePolygon (CompoundCurve ((-23817 205627),(-23817 205627, -23815 205633),(-23815 205633, -23809 205632),CircularString (-23809 205632, -23807 205629, -23810 205624),(-23810 205624, -23817 205627)))")
print(geom.validateGeometry())
print(geom.isGeosValid())
```
```
[]
True
```

**Comment by vcloarec** [comment]
@uclaros : this was tested but this duplicate point passes through the test. Indeed, the test QCOMPARE the QgsGeometry, but, what I didn't see, it that, in back ground, equality for those test uses `QgsGeometry::isGeosEqual()`.
As geos does not support curve and curve are converted to line string to work with geos, this too much compound curve element was not detected.
Test is now improved.

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
