### PR TITLE
[processing] Transparently handle CRS for point parameters

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR implements recent changes that were done for extent parameters for the point parameter type. This allows selection of point parameters with a different CRS to a layer, etc.

@alexbruy I've also fixed what I think is a bug when the network analysis algs have a network layer in a different CRS to the map.

However, most of these algs seem broken to me. The shortest path ones work OK, but all the service area ones output nonsense (on master too). Do you have any idea what's happened here? I suspect some recent change has broken the network analysis classes.

FWIW, we should be able to reenable the processing network analysis tests when this is sorted, since the algs no longer rely on iface.

### CODE REVIEW

**Comment by alexbruy** [comment]
@nyalldawson I tested algs and they works for me. However, creating tests is not possible
```
ValueError: malformed node or string: 
Traceback (most recent call last):
  File "/tmp/build/qgis/output/python/plugins/processing/gui/HistoryDialog.py", line 128, in createTest
    TestTools.createTest(item.entry.text)
  File "/tmp/build/qgis/output/python/plugins/processing/gui/TestTools.py", line 143, in createTest
    alg_id, parameters = splitAlgIdAndParameters(text)
  File "/tmp/build/qgis/output/python/plugins/processing/gui/TestTools.py", line 137, in splitAlgIdAndParameters
    return m.group(1), ast.literal_eval(m.group(2))
  File "/usr/lib/python3.5/ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.5/ast.py", line 62, in _convert
    in zip(node.keys, node.values))
  File "/usr/lib/python3.5/ast.py", line 61, in 
    return dict((_convert(k), _convert(v)) for k, v
  File "/usr/lib/python3.5/ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: 
```
I think this is because definition of the point parameter in the Processing command has changed. 
```
processing.run("qgis:serviceareafrompoint", {'INPUT':'/devel/qgis/python/plugins/processing/tests/testdata/roads.gml','START_POINT':QgsReferencedPointXY( QgsPointXY( 1002219.97834469040390104, 6221693.02811403851956129 ), QgsCoordinateReferenceSystem( 'EPSG:32733' ) ),'STRATEGY':0,'TRAVEL_COST':700,'VALUE_FORWARD':'','VALUE_BACKWARD':'','VALUE_BOTH':'','DEFAULT_DIRECTION':2,'DEFAULT_SPEED':5,'TOLERANCE':0,'OUTPUT_POINTS':'memory:','OUTPUT_POLYGON':'memory:'})
```
Similar error thrown for algorithms which have extent parameter

**Comment by alexbruy** [comment]
Same error also with `QgsProcessingFeatureSourceDefinition`.

**Comment by alexbruy** [comment]
@nyalldawson can you take a look at this issue?

**Comment by nyalldawson** [comment]
@alexbruy should be fixed now, can you confirm?

**Comment by alexbruy** [comment]
@nyalldawson works fine now, thanks!

**Pull request merged**
