### PR TITLE
[processing] port SAGA to new API

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
This PR continues great work started by @nyalldawson in #5021. I've fixed several issues, namely:

- updated raster handling to match API changes
- fixed handling of numeric parameters (int vs. double)
- prepared infrastructure for tests

Probably there are more things to fix, but I'm not a big SAGA user. @gioman, @mach0 it would be great if you can help with adding test and identifying issues.

Also note that now SAGA provider does not perform any output coversion and store results only in the natively supported formats (`shp` for vectors, `sdat` for rasters).

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
@alexbruy is this waiting on me for anything?

**Comment by alexbruy** [comment]
@nyalldawson there is still a minor issue with results handling: we either need to convert them into QGIS-compatible format or limit outputs file filters only to formats supported by provider. IMHO second option is more preferable, because it allows user precisely control conversion process and there are a lot of tools to do this in QGIS. But I'm not a bit SAGA user. 

@gioman, @volaya any opinions?

**Comment by gioman** [comment]
> or limit outputs file filters only to formats supported by provider

does this apply only to rasters or also vectors?

**Comment by alexbruy** [comment]
> does this apply only to rasters or also vectors?

Depends on provider. For example, for GRASS both; if I'm not wrong SAGA outputs vectors as shapefiles.

**Comment by gioman** [comment]
> For example, for GRASS both

on master Processing/GRASS outputs are not passed anymore through v.out.ogr and r.out.gdal? Regardless I think that is SAGA raster outputs are in the native format is ok, they are well supported.

**Comment by alexbruy** [comment]
> Regardless I think that is SAGA raster outputs are in the native format is ok, they are well supported.

Thanks. So limiting filter only to supported formats is fine.

**Comment by alexbruy** [comment]
@nyalldawson what do you think about relying on driver names instead of extensions when determining supported formats? I mean methods like `supportedOutputRasterLayerExtensions`, `supportedOutputVectorLayerExtensions`.

**Comment by nyalldawson** [comment]
@alexbruy what's left to do on this (following the merge of https://github.com/qgis/QGIS/pull/5544)?

**Comment by alexbruy** [comment]
@nyalldawson just need to update PR and add couple of tests. Will do it ASAP.

**Comment by alexbruy** [comment]
@3nids is it possible to add SAGA to the docker used for testing?

**Comment by alexbruy** [comment]
@nyalldawson should be ready for merge. I have added two tests for SAGA provider and they pass locally. But as we don't have SAGA on Travis, they are disabled here.

Travis failure is not related to this PR.

**Comment by nirvn** [comment]
@alexbruy , @nyalldawson , there's something wrong with the ordering of the SAGA (and GRASS) groups, i.e. it's not in alphabetical order:
screenshot from 2017-11-10 16-40-37

**Comment by Gustry** [comment]
Good work!
I guess I first need to install SAGA, because the tree has some issue with the SAGA item:

screen shot 2017-11-10 at 10 48 40

screen shot 2017-11-10 at 10 47 28

**Comment by johanvdw** [comment]
@Gustry : you have an old version of saga (2.2.2). You should use 2.3.x

**Pull request merged**
