### PR TITLE
Json expression functions

### PR DESCRIPTION
**Pull request by m-kuhn**
The current JSON expression functions only work with maps. There is no reason for that.

This PR adjusts the current functions so they also work with arrays, raw string values and whatever QJson may support.

There are also 2 aliases `json_to_map` is now also available as `from_json` and `map_to_json` is now also available as `to_json`. ~I'm not a huge fan of the names, suggestions welcome.~

### CODE REVIEW

**Comment by m-kuhn** [comment]
Renamed the new aliases to be consistent with postgres: `from_json` and `to_json`

**Comment by nirvn** [comment]
I can't remember for sure but I think I added json_to_map et cie during this development cycle. I don't mind seeing those aliases go away to keep only from_json / to_json.

**Comment by Gustry** [comment]
`json_to_map` is in 3.4 already @nirvn

**Comment by m-kuhn** [comment]
Assigned to @nirvn as the author of the function

**Comment by nirvn** [comment]
@m-kuhn , all good stuff, merged :smile:

**Comment by m-kuhn** [comment]
Thanks @nirvn !

**Pull request merged**
