### PR TITLE
Set centroid as default placement for polygon diagramss

### PR DESCRIPTION
**Pull request by DelazJ**
Fix [#13435](https://issues.qgis.org/issues/13435)

### CODE REVIEW

**Comment by nyalldawson** [comment]
I think the rationale here is that the "around" mode gives more candidate positions -- the "centroid" mode only gives a single option, so it's more likely that diagrams will be in conflicting positions and not rendered.

But I don't have a strong opinion here.

**Comment by DelazJ** [comment]
Me neither. Just trying to clean the issues queue.
@pcav?

**Comment by pcav** [comment]
I still think centroid is better - try on polygons, when zooming out it is often difficult to see which polygon they refer to.
IMHO a partial sovrapposition for diagrams is acceptable, unlike labels, so there is less need tohave more positions available.
Thanks.

**Comment by DelazJ** [comment]
So, do we reject or merge (in both cases, the issue report should be closed)?

**Comment by nyalldawson** [comment]
We've got one +1 and two 0's, so let's merge

**Pull request merged**
