### PR TITLE
Adds clang-format to pre-commit to 3.40

### PR DESCRIPTION
**Pull request by 3nids**
manual backport of  #59664

run pre-commit on all files which was not done yet on this branch

### CODE REVIEW

**Comment by nyalldawson** [comment]
@3nids I'm not really sure what I'm supposed to be using to auto-format anymore. I understood that pre-commit should be formatting all files not exposed to sip, and astyle for the rest (for now). But I only see pre-commit format some files, and the rest are just unchanged (eg editing a .cpp file in src/raster)

**Comment by 3nids** [comment]
@nyalldawson have you done `pre-commmit install` (probably with -f if you had prepare_commit as a commit hook before)

https://github.com/qgis/QGIS-Documentation/blob/master/docs/developers_guide/git.rst#procedure

**Comment by uclaros** [comment]
@3nids Maybe it's worth posting what needs to be changed to the devs mailing list

**Comment by 3nids** [comment]
@uclaros done here https://www.mail-archive.com/qgis-developer@lists.osgeo.org/msg56429.html

**Review by m-kuhn — APPROVED** [review]

**Comment by nyalldawson** [comment]
@3nids 
> have you done pre-commmit install (probably with -f if you had prepare_commit as a commit hook before)

Yep. Something's definitely wonky -- try editing a cpp file in src/core, and neither scripts/prepare-commit.sh nor pre-commit run will apply any formatting change to it.

**Comment by 3nids** [comment]
@nyalldawson I was quite sure I tested this... fixed here https://github.com/qgis/QGIS/pull/59713/files?w=1

**Pull request merged**
