### PR TITLE
add setCurrentNode to qgslayertreeview

### LINKED ISSUE #47337: Add a method to pyqgis to set group as an active node in layer tree
### Feature description

Currently, there is a way to set a map layer as active layer programmatically `iface.setActiveLayer()` but there is no equivalent way of setting a group as an active node. There is this answer on SE 

https://gis.stackexchange.com/a/383321/142232

But this doesn't work if your group is a nested group.

This feature is useful if you are writing processing scripts that add layers to the currently selected node.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ViperMiniQ**
QgsLayerTreeView has a method (setCurrentLayer) for setting the QgsLayerNode as active in the tree by passing the layer to it.

There is no method for selecting groups the same way, even though the method setCurrentLayer finds the QgsLayerTreeNode and passes it to a function which selects the node.

2 new methods are added:

setCurrentNode - a general way of setting active nodes, which both setCurrentGroup and setCurrentLayer will call. Also, since a layerTreeView.selectedNodes() method returns selected nodes, it would make sense to have a method for selecting them as well.

setCurrentGroup - to have an exact way of setting active groups alongside active layers, even though maybe having setCurrentNode only would be ideal. Removing setCurrentLayer would not make sense now, so adding this as well.

Would close #47337

### CODE REVIEW

**Comment by nyalldawson** [comment]
I think we should drop the redundant setCurrentGroup method, just to keep the API from becoming cluttered. Otherwise +1

**Comment by ViperMiniQ** [comment]
Figured as much, wasn't sure.

Removed setCurrentGroup.

**Comment by nyalldawson** [comment]
@ViperMiniQ this looks good, it's just the failing code format checks which need fixing now

**Comment by nyalldawson** [comment]
Superseded by https://github.com/qgis/QGIS/pull/58822

**Pull request closed without merging**
