### PR TITLE
pyplugin_installer: add (minimum?) Qt6 compatibility

### PR DESCRIPTION
**Pull request by rouault**
I've the feeling that there should be a better fix... But at least this is the minimum set of fixes I found to be able to install the "first aid" plugin from a QT6 build

### CODE REVIEW

**Comment by nyalldawson** [comment]
@rouault I've got some (better?) fixes for these incoming, eg https://github.com/qgis/QGIS/pull/56016

**Comment by rouault** [comment]
> @rouault I've got some (better?) fixes for these incoming, eg #56016

This indeed enables to remove the hack related to Qt.KeyboardModifiers, but the other ones are still necessary. I've forced-pushed my branch with the remaining fixes needed, rebased on yours from #56016

**Comment by nyalldawson** [comment]
I'm also working on a more flexible fix for the setAttribute issue -- this one impacts a lot of Qt methods where enums can be extended from a user role.

**Comment by rouault** [comment]
closing as supersed per #56036

**Pull request closed without merging**
