### PR TITLE
make QgsGeometry::isNull Q_INVOKABLE

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by luipir** [comment]
@3nids please give an overview of the rationale why for this method only and not others

**Comment by m-kuhn** [comment]
Can you make it a Q_PROPERTY? I don't think it makes much difference apart from looking more QML'onic.

**Comment by 3nids** [comment]
@luipir cause I need it in QML...up to now, these methods have been made Q_INVOKABLE whenever required. 

@m-kuhn how do you see this working ? Changing`QgsGeometryPrivate` by making `geometry` a private member and force to go through setter/getter to be sure to keep the property up to date?

**Comment by m-kuhn** [comment]
I think a simple line like this should be enough:

```
Q_PROPERTY ( bool isNull READ isNull );
```

Notification is not possible anyway because it's not a QObject

**Comment by wonder-sk** [comment]
Yeah without NOTIFY I think there is a risk that the QML engine may cache the result and then return incorrect value afterwards.

I am wondering if it makes sense to have QgsQuickGeometry based on QObject that would wrap geometries and have all sorts of properties, signals, invokables...?

**Comment by 3nids** [comment]
> Yeah without NOTIFY I think there is a risk that the QML engine may cache the result and then return incorrect value afterwards

That sounds scary...do you have any reference for this or is it a wild guess ?

> I am wondering if it makes sense to have QgsQuickGeometry based on QObject that would wrap geometries and have all sorts of properties, signals, invokables...?

What advantage would it bring? Nicer calls from QML?

For our current case, I have no strong opinion here on what's best.
Can we decide on some guidelines: use Q_PROPERTY in any case or only for these having a NOTIFY ?

In the mean time, I'm gonna merge this one, that's an easy change later on (while still in this release cycle).

**Comment by wonder-sk** [comment]
> That sounds scary...do you have any reference for this or is it a wild guess ?

The caching thing was more of a wild guess :-) but the real thing is that if someone would use isNull in property binding, it would not work correctly. For example `visible: geom.isNull` would always stay in the visible state based on the isNull state on component load.

> What advantage would it bring? Nicer calls from QML?

Yeah more natural API when used from QML. Of course this will not scale well if one wants to work with great amount of geometry objects...

**Comment by m-kuhn** [comment]
> What advantage would it bring? Nicer calls from QML?

A managed geometry which can be shared among different models, controllers, views. Move a vertex -> update on all representations.
But maybe it could also be [something model-based](https://github.com/opengisch/QField/blob/master/src/core/vertexmodel.h) to give precise deltas of changed vertices. Models can also have an `isNull` property.

> Of course this will not scale well if one wants to work with great amount of geometry objects...

Yes, I think one should still be able to use classic QgsGeometry objects for storage and set them on a managed geometry for a given purpose (like vertex editing).

**Comment by m-kuhn** [comment]
@3nids ok to delete the branch?

**Comment by m-kuhn** [comment]
I'm voting again on moving this to `Q_PROPERTY`

 * Mostly because it's more QML style
 * `QgsRelation` uses the same style, no bad effects that I would know of so far
 * `Q_GADGET`s know the `Q_PROPERTY` system. By definition they cannot have a `NOTIFY` signal. If Qt devs would have seen this as a limitation they would not have introduced the `Q_PROPERTY` system on `Q_GADGET`s
 * If you use `isNull()` in a binding or `isNull` in a binding does not make a functional difference, it's evaluated at the same point in time
 * If you use `geomIsNull = geometry.isNull()` or `geomIsNull = geometry.isNull` in imperative code does not make a functional difference
 * We didn't care if clazy was complaining about `QgsRelation` so far

**Pull request merged**
