### PR TITLE
Fixing db_manager so that it can run sql with inline comments

### LINKED ISSUE #29089: Comments in SQL query in DB Manager breaks the query
Author Name: **Nikolay Lebedev** (Nikolay Lebedev)
Original Redmine Issue: [21271](https://issues.qgis.org/issues/21271)
Affected QGIS version: 3.5(master)
Redmine category:db_manager

---
SQL comments are highlighted in the editor, however they break SQL execution.
Easy to replicate: add a comment after SELECT clause before selected fields.

### PR DESCRIPTION
**Pull request by stev-0**
Fixes #29089

## Description
Allows the execution of SQL in db_manager with comments of the -- variety which are inline (not just at the beginning of a newline as before).

## Checklist
- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by Gustry** [comment]
Thanks for trying to fix this one.
Have a look the previous discussion #9183 about inline comments: https://github.com/qgis/QGIS/pull/9183#discussion_r257475195

**Comment by stev-0** [comment]
Thanks @Gustry. I did see that thread. As far as I can work out, the pull request that closed that bug initially (#29361 in github) was not quite complete, in that trailing comments still crashed the query, which is what this PR should fix.

**Comment by Gustry** [comment]
@stev-0 I'm talking about the comment https://github.com/qgis/QGIS/pull/9183#discussion_r257475195 That's why the pull request was a partial fix.

**Review by nyalldawson — CHANGES_REQUESTED** [review]
As @Gustry has pointed out, this breaks queries which use -- outside of comments, e.g. `field='c--d'`.

**Comment by stev-0** [comment]
Sorry, my bad, was on a phone when I looked at one of the comments and that didn't show up the earlier issues. I will have a look at a proper fix now.

**Comment by stev-0** [comment]
I think this is complete now and ready to be merged and does now ignore the string `--` in 'quotes' and "identifiers".

**Comment by stev-0** [comment]
Bump. I think this is good to go.

**Comment by Gustry** [comment]
@elpaso Does your refactoring in DBManager will handle this bug?

I think this fix still needs to land in 3.8 and 3.4. @stev-0 Can you provide some basic unit test? For checking that the parsing works well.

**Comment by stev-0** [comment]
Right, will add some now

**Comment by stev-0** [comment]
Tests as requested. I ended up refactoring the sql dialog code, as I was having a lot of trouble mocking out the gui functionality, so I put the parsing code outside the main class - not sure if that is a style no-no.

**Comment by Gustry** [comment]
Can this PR be backported to 3.8 and 3.4?
AFAIK, it was working fine in 2.18.

**Comment by nyalldawson** [comment]
I'm not confident enough in the stability of a regex solution here to backport to the LTR

**Pull request merged**
