### PR TITLE
Add LZW compression preset for tiff exports

### PR DESCRIPTION
**Pull request by nyalldawson**
The other existing presets are likely based on quite outdated information now. @rouault do you have any thoughts on whether these should be changed, or other new ones to add?

### CODE REVIEW

**Comment by rouault** [comment]
I would perhaps remove Packbits from the list. I'm not sure it is very useful compared to LZW or DEFLATE.

**Comment by nyalldawson** [comment]
@rouault 

I'm likely going on outdated info, but I thought PACKBITS was faster to read/write (while being bad at actually compressing), and LZW/DEFLATE were better compression but slower to read/write?

**Comment by rouault** [comment]
> thought PACKBITS was faster to read/write (while being bad at actually compressing)

that's very much likely true. But I'm not aware of PACKBITS being actively used in the wild. My impression is that people deliver either as uncompressed, or compressed with LZW/DEFLATE. My suggestion was just to avoid overwhelming users with too many choices

**Comment by nyalldawson** [comment]
I'm mostly curious because I **just** did a bunch of raster work and was using packbits as a file size/performance trade off 😂

**Comment by rouault** [comment]
> I'm mostly curious because I **just** did a bunch of raster work and was using packbits as a file size/performance trade off joy

oh well, then I know someone using it for actual work :-) I'm one of the less informed person of what actual users do (unless they report bugs :-))

**Comment by baswein** [comment]
I also use packbits for simple classified rasters.

**Comment by uclaros** [comment]
It would also be nice to have `PHOTOMETRIC=YCBCR` in jpegs as it gives the best compression for aerial imagery.
The existing `JPEG_QUALITY=75` is very lossy for a compression that's not that great.
I've extensively used  `-co COMPRESS=JPEG -co JPEG_QUALITY=99 -co PHOTOMETRIC=YCBCR` for storing orthophotos with no visible image quality degradation at a very good compression.

**Comment by andreasneumann** [comment]
> It would also be nice to have `PHOTOMETRIC=YCBCR` in jpegs as it gives the best compression for aerial imagery. The existing `JPEG_QUALITY=75` is very lossy for a compression that's not that great. I've extensively used `-co COMPRESS=JPEG -co JPEG_QUALITY=99 -co PHOTOMETRIC=YCBCR` for storing orthophotos with no visible image quality degradation at a very good compression.

I agree - I usually use the exact same settings for aerial images - with good results.

**Pull request closed without merging**
