### PR TITLE
Added new mime icons

### PR DESCRIPTION
**Pull request by SrNetoChan**
Added new mime icons for qgs, qml, qlr, qpt and others files extentions in SVG.

Not sure where else I need to tweak to make Operative Systems to assume the Icons for that file formats. Help is needed.

### CODE REVIEW

**Comment by Scimmia22** [comment]
The name "other_mime_icon.svg" is pretty generic. It would probably be better to name it more distinctively instead of having each OS integrator decide what to rename it to.

**Comment by SrNetoChan** [comment]
@Scimmia22 Currently mime_icon.PNG is used for all file formats related to QGIS. That Includes QGIS's qgs, qpt, qlr, qml and others like all formats of shapefile. My ideia for other_mime_icon.svg would be to replace those "others" non qgis files. The best name would in fact be mime_icon.svg, but in that case I should update or even delete the mime_icon.png file. What do you think?

Also, I'm not sure of all file formats currently using that Icon, otherwise we might think of creating  similar, yet distinct icons for each. Say shapefile, spatialite, tiff...

**Comment by Scimmia22** [comment]
SrNetoChan, there is no mime_icon.PNG. The current icon is called qgis-mime-icon.png.

**Comment by SrNetoChan** [comment]
@Scimmia22 Please suggest better names then. I will gladly change it.

**Comment by kyngchaos** [comment]
Mac icons need to be rasterized at different sizes and merged into a .icns format.  There are tools on OS X to create the icns file.  They also need to be registered in the OS X app Info.plist.  I see that that OS X has had icons for many common files for a long time, including the qgs document and qml, but not qlr or qpt.

**Comment by SrNetoChan** [comment]
@kyngchaos thank you. I will take care of that.

**Comment by SrNetoChan** [comment]
@Scimmia22 I think I have now understood what you meant. I will take change that. Thanks for the input.

**Comment by SrNetoChan** [comment]
I have messed up with git... not good. So I have closed this to make a proper pull request.

**Pull request closed without merging**
