### PR TITLE
Add histogram to ftools basics statistics

### PR DESCRIPTION
**Pull request by havatv**
I have added histogram to basic statistics.

I have updated frmVisual.ui to include a histogram canvas + controls (set number of bins, min.value, max.value, cumulative option).  Everything else should remain untouched.

I have updated doVisual.py with code to create and draw a histogram for the chosen variable.  I had to add a new parameter to the generic visual and visualThread method to pass histogram parameters (bins, min.value, max.value).  I used the second return parameter of visualThread for the generated histogram bins.  I have not added signals that would enable dynamic adjustment of the histogram to window size changes or checking/unchecking of the cumulative checkbox, but if this is a wanted feature, it should be trivial to add it.

In the process, I also included a check for NULL (QPyNullVariant) before using the attribute value.  This avoids a crash when running basic statistics on fields that have NULL values.

### CODE REVIEW

**Comment by havatv** [comment]
I have added an issue for this pull request: http://hub.qgis.org/issues/13553

**Comment by pcav** [comment]
@nyalldawson it would be great to add it

**Comment by alexbruy** [comment]
Why not user Qtw for histogram instead of own code?

**Comment by havatv** [comment]
@alexbruy, I have never used Qwt.  What would be the advantages of using Qwt for the histogram?
The current implementation should work OK, but if there are good reasons for using Qwt, I can try to reimplement it.
A reason for implementing the histogram from scratch is that it provides maximum flexibility.

**Comment by alexbruy** [comment]
Closing, as fTools plugin was removed

**Comment by havatv** [comment]
I found QEP 36. It says that all the functions that the ftools plugin currently provides in the _Vector_ menu shall be kept.  I guess that it means that also _Basic Statistics_ will be available in the future.

This pull request contains an implementation of a proposal to add a histogram to "Basic Statistics".  Moving the _Basic Statistics_ code / functionality to a new location in the code base, as proposed in QEP36, should not invalidate that proposal.

It is reasonable that the pull request as such is closed, but in my opinion it would have been nice if this was accompanied by a suggestion for how to proceed to get the proposed functionality included in the new version of _Basic Statistics_.

**Pull request closed without merging**
