### PR TITLE
Update test to reflect changes in proj library

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by rouault** [comment]
When PROJ 7 will be on track, this will change again (presumably one single package with all grids as GeoTIFF). So I'd suggest perhaps just checking that packageName and url are non-empty.

**Comment by nyalldawson** [comment]
> presumably one single package with all grids as GeoTIFF

Won't that be a huge download?

**Comment by rouault** [comment]
> Won't that be a huge download?

480 MB with the current content of https://github.com/OSGeo/proj-datumgrid-geotiff/ . People are confused by the multiple packages

**Comment by rouault** [comment]
> Won't that be a huge download?

The discussion about that is in https://github.com/OSGeo/proj-datumgrid/issues/74

**Pull request merged**
