### PR TITLE
Revert "Add test for pointcloud layers fetching and related permissions"

### PR DESCRIPTION
**Pull request by m-kuhn**
This reverts commit 30fe7484698046b588284ff5485115e70833a268.

Check to see if this fixes CI. @strk a different approach would be preferred.

### CODE REVIEW

**Comment by m-kuhn** [comment]
I'll merge this to have meaningful test results again.
It would be good to come up with a revert of this revert soon (and hopefully a future proof stable installation process for pointcloud).

**Comment by m-kuhn** [comment]
A failing build (for reference)
https://travis-ci.org/qgis/QGIS/jobs/650344373#L997-L998

**Comment by m-kuhn** [comment]
@nyalldawson the test was added master only. Are there problems on 3.10?

**Comment by nyalldawson** [comment]
@m-kuhn all 3.10 PRs are failing with a similar error, e.g. https://travis-ci.org/qgis/QGIS/jobs/651351557?utm_medium=notification&utm_source=github_status

**Comment by m-kuhn** [comment]
Oh, right. Must have been backported.

**Comment by m-kuhn** [comment]
https://github.com/qgis/QGIS/pull/34495

**Pull request merged**
