### PR TITLE
Update and add icons to dialog

### PR DESCRIPTION
**Pull request by DelazJ**
Raster Layer --> save as: I think these icons better fit the purposes than the current (before at left, after at right)
image

Vector layer --> save as: Move the "Add saved file to map" upper and insert a vertical spacer at the bottom  (before at left, after at right)
image

### CODE REVIEW

**Comment by nirvn** [comment]
@DelazJ , nice tweaks, lovely to see the [ + ] [ - ] buttons using our default pair of icons.

There's one little -1 for me in there, namely the import no data value from file icon. IMO, it'd be better to use the default Open icon (i.e. the folder) there, which would harmonize with another raster-related UI:
untitled

**Comment by nirvn** [comment]
@DelazJ , if you feel like adding a bit more work into this, it might be good to further harmonize the UI here by moving the side buttons of both the "create options" and "no data values" sections down below the list widget, and have all buttons be QPushButtons (instead of a mixture of QPushButtons and QToolButtons)

**Comment by DelazJ** [comment]
@nirvn. About buttons placement (top, right or bottom), wouldn't that increase the height of the dialog while there still is enough place in the width (not sure the Tablewidget content is long) . That said, it's a collapsible group so can be closed.
Btw, there's an UI issue reported https://github.com/qgis/qgis3_UIX_discussion/issues/18 in which your opinions are welcome 
Whatever, I Will fix according to your comments

Can anyone explain me why, despite buttons are added in the .ui file, this is overloaded by a setup configuration (in .cpp), adding again these icons? Thanks.

**Comment by nirvn** [comment]
@DelazJ , I think it makes sense to move it below the list.

**Comment by nirvn** [comment]
@DelazJ , it'd be great if we could push this through the finish line. 😄 -- you don't have to tackle the push vs tool button, but I'd appreciate if the import icon could be changed (mentioned above).

**Comment by DelazJ** [comment]
@nirvn here it's
image
I just wonder if the size policy of  the 2 groups of buttons should be the same considering that the "create options" buttons are part of another widget
image

**Comment by nirvn** [comment]
@DelazJ , I would have the [ + ] [ - ] [ Validate ] [ Help ] row not expend (i.e. add a horizontal spacer at the end to fill available space).

**Comment by DelazJ** [comment]
@nirvn, Done ( and for consistency, also did it for the [ + New ] [ - Remove ] [ Reset ] row )

**Comment by nirvn** [comment]
@DelazJ , great job.

**Comment by DelazJ** [comment]
Thanks

**Pull request merged**
