### PR TITLE
WMTS GetCapabilities and axis order

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

This PR supersedes https://github.com/qgis/QGIS/pull/41768. A unit test has been added and some minor changes have been made (cleaning).

### CODE REVIEW

**Comment by tudorbarascu** [comment]
@pblottiere Just tested your changes and it works! Thank you!

I noticed a bug: If I choose any group that has layers unchecked (not visible) in the project, this isn't respected in the WMTS output and all the layers show in the generated images

**Comment by rldhont** [comment]
> @pblottiere Just tested your changes and it works! Thank you!
> 
> I noticed a bug: If I choose any group that has layers unchecked (not visible) in the project, this isn't respected in the WMTS output and all the layers show in the generated images.
> 
> E.g. choosing the root of the project outputs all the layers.
> image
> 
> Should I open a new bug report, is this the expected behavior somehow?

@tudorbarascu it is not a bug, WMTS works like WMS. If you request the project in a WMS GetMap Request, you will get all the layers in the image.

In your case, it will be great to use a QGIS theme as a WMTS layer.

**Review by rldhont — APPROVED** [review]

**Comment by pblottiere** [comment]
> Just tested your changes and it works! Thank you!

Nice! Thanks for testing @tudorbarascu :+1:

**Comment by pblottiere** [comment]
Thanks for the review @rldhont.

**Pull request merged**
