### PR TITLE
[server] CRS position in GetCapabilities document

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

Followup https://github.com/qgis/QGIS/pull/6793.

When the Root Layer element doesn't have a `Title`, `Abstract` and `Name`, the `EX_GeographicBoundingBox` and `CRS` elements are inserted AFTER layers' definition in the GetCapabilities document.

However, according to OGC tests, these elements should always be BEFORE layers' definition in the XML document.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
@pblottiere can you merge and backport to release-3_0 ?

**Comment by nyalldawson** [comment]
This merge has started causing test failures on Travis - see https://travis-ci.org/qgis/QGIS/jobs/374124060

**Comment by rldhont** [comment]
@nyalldawson thanks!
It seems that this PR revert #6793. @pblottiere can you take a look ?

**Comment by pblottiere** [comment]
@rldhont 

> It seems that this PR revert #6793 

No it doesn't, it just fixes the CRS position when there's no `Abstract` or `Title` for the root layer.

> can you take a look ?

Yes I'm taking a look.

BTW, this PR was 7 days old and I think it should have been rebased before merging it (in order to avoid the current situation ;))... Can you ping me next time? Thanks :).

**Comment by rldhont** [comment]
@pblottiere I don't understand the issue! The code has not been changed and empty Abstract Title and Name are added !

**Comment by pblottiere** [comment]
@rldhont 

> I don't understand the issue! The code has not been changed and empty Abstract Title and Name are added !

Because https://github.com/qgis/QGIS/pull/6793 has not be backported yet. It will be done by the end of the day (I want to run OGC tests first).

**Pull request merged**
