### PR TITLE
Make Use filename as layer name option default to true (#12741)

### PR DESCRIPTION
**Pull request by giohappy**

### CODE REVIEW

**Comment by giohappy** [comment]
@volaya

**Comment by pcav** [comment]
Please do not merge - I do not agree with this.

**Comment by pcav** [comment]
The label is much more informative than the layer name. Having "OUTPUT.shp" several times will be confusing. See the work we have done for some backend to show more descriptive names.

**Comment by giohappy** [comment]
Probably this is not what I was saying on the ticket. What many ask me is to have in the TOC the same name as the file name they save the results to. E.g. "myclippedpolygon.shp" should be seen as "myclippedpolygon" within the TOC.

**Comment by pcav** [comment]
OK, so:
* if the user gives a custom file name, this should be used
* if not, the label should be used.
Right? This would sound good to me.

**Comment by giohappy** [comment]
Exactly

**Comment by pcav** [comment]
Afaict your patch does not address this, right?

**Comment by giohappy** [comment]
Oh, right Paolo. I thought this option affected only not temporary filenames. I see that some more line of code should be included to have a flag wether the output file is a temporary generated file or a path set by the user. I will close this PR and re open it in case I find the time to complete it.

**Pull request closed without merging**
