### PR TITLE
[3d] Allow configuration of interpolation method for animations

### PR DESCRIPTION
**Pull request by wonder-sk**
Adds a combo box that sets interpolation method for the whole animation.

One thing that's not very intuitive is that this makes the time non-linear: the timing of keyframes has to be interpolated, so e.g. keyframe at time 3 seconds out of 9 seconds will have time adjusted according to the easing curve - for OutQuint the keyframe will show up much earlier than at 3 seconds.

I am not yet convinced this is the right way forward (due to the un-intuitiveness of time shifts of keyframes), but here we go, I am looking forward for some feedback (ping @nirvn) :-)

### CODE REVIEW

**Comment by nyalldawson** [comment]
> One thing that's not very intuitive is that this makes the time non-linear: the timing of keyframes has to be interpolated, so e.g. keyframe at time 3 seconds out of 9 seconds will have time adjusted according to the easing curve - for OutQuint the keyframe will show up much earlier than at 3 seconds.

What's the reason behind this? Is it a qt thing?

**Comment by wonder-sk** [comment]
> What's the reason behind this? Is it a qt thing?

Not a Qt thing... it's about the how things are implemented here. Normally those easing curves are used to interpolate values in an interval between two keyframes. But here, we decide to apply the easing curve to the timeline of the whole animation - that's why we adjust keyframe times according to the "global" easing curve. Basically what we are doing is to make the time run according to the specified curve rather than going linear. If we wanted to keep the keyframes at the original timing, we would need to be able to figure out inverse of the easing function - e.g. for time = 3 seconds out of 9 second animation we would need to figure out for what input the easing curve returns 0.33. While this is possible to figure out for some easing curves, I am not sure if this is the way how we should go. I think in the end the shape of interpolation curves should be defined at each keyframe separately (instead of having "global" easing curve), but that will need extra effort to implement.

**Comment by nirvn** [comment]
@wonder-sk , sorry, I think I wasn't clear. What IMHO we need is for the setting to control interpolation time for each keyframe-to-keyframe transition. For e.g.

LINEAR:
linear

INOUTCUBIC:
curved

**Comment by nirvn** [comment]
@wonder-sk , great, you nailed it.

**Pull request merged**
