### PR TITLE
Only check server SSL certificate if requested

### LINKED ISSUE #30075: Inconsistent SSL certificate validity check using auth manager
Situation:
* Postgres server with SSL enabled and a self-signed certificate
* SSLMode=require in the QGIS connection

# Not using auth manager

QGIS successfully connects if username and password are correct

# Using auth manager basic auth

QGIS fails to connect with username and password, complaining about an "SSL error: certificate verify failed".

Screenshot from 2019-06-04 09-54-20

# Analysis

The QGIS Basic Auth Method expansion adds a "sslrootcert" part to the connection string which, in combination with the following note from [the postgres docs](https://www.postgresql.org/docs/9.1/libpq-ssl.html) trigger this behaviour.

> Note: For backwards compatibility with earlier versions of PostgreSQL, if a root CA file exists, the behavior of sslmode=require will be the same as that of verify-ca, meaning the server certificate is validated against the CA. Relying on this behavior is discouraged, and applications that need certificate validation should always use verify-ca or verify-full.

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #30075

Backport #30076

### CODE REVIEW

**Comment by luipir** [comment]
@m-kuhn why did you exclude tests in the backport?

**Comment by m-kuhn** [comment]
there is no docker-compose here

**Comment by luipir** [comment]
> there is no docker-compose here

I missed the infrastructure update... 3.4 test infrastructure is different from the master? is it something introduced and available only for at least 3.6?

**Review by elpaso — APPROVED** [review]

**Comment by m-kuhn** [comment]
I don't know. And I won't spend another day on infrastructure integration ;)

**Pull request merged**
