### PR TITLE
GDAL/OGR source select UX: add OGCAPI radio

### PR DESCRIPTION
**Pull request by elpaso**
Adds an entry for OGCAPI, in order to add
the endpoint without the need of OGCAPI: prefix.

image

image

### CODE REVIEW

**Comment by elpaso** [comment]
CC @doublebyte1

**Comment by doublebyte1** [comment]
> CC @doublebyte1

@elpaso  Great job! 👏🏽

**Comment by nirvn** [comment]
@elpaso , quick question: you didn't feel like adding an OGC API item in the protocol combobox? what's the rational there?

**Review by nirvn — APPROVED** [review]
Nothing wrong in the code change, just posted a question I'd like an answer to :)

**Comment by elpaso** [comment]
> @elpaso , quick question: you didn't feel like adding an OGC API item in the protocol combobox? what's the rational there?

Yeah, I thought about that, the fact is that in order to get the options filled, OGR requires an "OGCAPI:" prefix, I couldn't think of a way to go around that without an explicit option for OGC API. 

Also, I think OGC API is so important (or at least it will be as the XML family of protocols is deprecated) that it deserves an options.

**Pull request merged**
