### PR TITLE
[processing] test poly_from_extent

### PR DESCRIPTION
**Pull request by ghtmtt**
This PR replaces the #4082 due to conflicts during rebasing.

Just a single test added for processing, polygon from layer extent. Exactly the same file as the other PR so hopefully travis will not fail.

### CODE REVIEW

**Comment by ghtmtt** [comment]
@m-kuhn no idea why now the test fails due to some crs missing:

https://travis-ci.org/qgis/QGIS/builds/201794772#L935

while in the closed PR, same files, same yaml, same everything run fine:

https://github.com/qgis/QGIS/pull/4082
https://travis-ci.org/qgis/QGIS/builds/196664095#L885

**Comment by m-kuhn** [comment]
I don't know.
Either the files in this pull request changed or some related code in processing (or the algorithm) must have changed.

**Comment by ghtmtt** [comment]
@m-kuhn algorithm had a new parameter.. now fixed :)

**Comment by m-kuhn** [comment]
Thanks

**Pull request merged**
