### PR TITLE
add build test for Qt 5.15

### PR DESCRIPTION
**Pull request by t0b3**
check compilation on ubuntu:21.04 with Qt 5.15 to further improve code quality checks

### CODE REVIEW

**Comment by t0b3** [comment]
@nyalldawson do you think it would be good to test the build process against Qt 5.15? If so, this commit does it...

**Comment by nyalldawson** [comment]
@t0b3 this looks useful to me ! If you disable with_3d on the 5.15 build, then we should get a clean build on qt 5.15 without any deprecation warnings (fingers crossed), and then you could re-enable the warnings as failures flag. This would be VERY valuable, because then we'd have a guarantee that any new code coming in is qt 6.0 compatible! :+1: 

(@wonder-sk @vcloarec  not sure if you're aware of this already, but the QBufferDataGeneratorPtr used in the mesh 3d renderer
is deprecated and removed in qt 6. We need to port away from this to allow qt 6 based builds (it's the last remaining large blocker)

**Comment by vcloarec** [comment]
@nyalldawson
hmmm indeed ... Nothing in the doc...  but  I found this  https://www.mail-archive.com/interest@qt-project.org/msg34726.html
So, it seems we need our own thread...
I wonder if it is the opportunity to optimize the 3D mesh rendering with time varying... when is the dead line for qt6 based builds?

**Comment by nyalldawson** [comment]
@vcloarec yeah, I was pretty frustrated (once again) by the total and complete rubbishness of the qt3d docs in this regard...

There's no fixed timeline for qt6 support, but given upstream decision to end qt 5 with 5.15.2 (effectively, since the ltr patches.are only available now to paying customers) we're being forced to move sooner rather than later. 
My proposal is that we should support qt 5 and qt 6 based builds from as soon as someone gets a working qt 6 build going. The impact on plugins should be minimal if we don't accompany this by any PyQgis API breaks...

**Comment by t0b3** [comment]
@nyalldawson I changed `WERROR=TRUE` _(for all)_ and `WITH_3D=FALSE` _(Qt 5.15 only)_. Build succeeds now.

**Comment by nyalldawson** [comment]
Great! Can you rebase now? There was another pr merged in the meantime with more comprehensive q_foreach removal

**Comment by t0b3** [comment]
@nyalldawson rebased as requested

**Pull request merged**
