### PR TITLE
[processing][WIP] Fix management of QgsProcessingOutputLayerDefinition

### PR DESCRIPTION
**Pull request by luipir**
## Description
In some part of code there wasn't the management of the sink of QgsProcessingOutputLayerDefinition causing creating and passing null layers to child processes.

fix promoted inside GeoMove [1] project for Cartolab [2] (A Coruña university)

[1] http://cartolab.udc.es/geomove/
[2] http://cartolab.udc.es

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by luipir** [comment]
Still lack of unit test update

**Comment by luipir** [comment]
please @nyalldawson give a look... seems there were parts where QgsProcessingOutputLayerDefinition was not managed correctly. No idea if there others parts that have to be updated too.

**Comment by luipir** [comment]
@rudivs this last (I hope) path should close the round to fixing for processing, please give a try

**Comment by luipir** [comment]
not clear if backporting is necessary so near to the 3.4 release

**Comment by nyalldawson** [comment]
There's nothing left to backport for -- 3.2 is EOLed and there's not going to be a 3.2.4.

**Comment by nyalldawson** [comment]
Fix looks good!

**Comment by rudivs** [comment]
I tested with my models and got no errors. To be fair though, your previous fix already sorted out the issues that I'd come across, so I can only confirm that it still works.

**Comment by luipir** [comment]
I'll give you a model where a raster calculator was cascaded to a grass model reproducing the issue

**Comment by rudivs** [comment]
Thanks @luipir. If I know what scenarios reproduce the issue I can try to come up with other scenarios to test.

**Comment by luipir** [comment]
Attached [1] the model, It's not a generic model to reproduce the issue, but it's that I'm developing, simlified avoid the point clouds calculations.

the issue happen running the alg raster calculator "merge buffer and intersect"... I was able to avoid to use raster calculator for a simple reclassify, but in that case I would consider it a workaround respect fix the issue.
Just download and remove heading .txt extension to all attached files
[IdentifyCrossWalks_simplified.model3.txt](https://github.com/qgis/QGIS/files/2396814/IdentifyCrossWalks_simplified.model3.txt)

here two input rasters, just in case you want to run it

[clasificacionPasosPeatones_PNOA2010_versionRestrictiva.tif.txt](https://github.com/qgis/QGIS/files/2396817/clasificacionPasosPeatones_PNOA2010_versionRestrictiva.tif.txt)
[roughCrosswoalClassification.tif.txt](https://github.com/qgis/QGIS/files/2396819/roughCrosswoalClassification.tif.txt)

**Comment by luipir** [comment]
@nyalldawson I've difficulties creating test for modifications I did for QgsProcessingModelAlgorithm::variablesForChildAlgorithm, difficulties to create test + lack of time because I've to do analisys too.
Because some other colleagues are working on similar models and are affected by these issues and they use master via standard package installation (linux and win). **Is it possibile to merge and postpone the test creation later?** This would allow my colleagues to follow with their work (and do more tests), and me to continue to find a way to create the test.

p.s. I just added only one of the test for mods of parameterLayerList

**Comment by luipir** [comment]
here another model that fail with latest nightly qgis but does not fail with my patch on my compiled version
[Identify Sidewalks.model3.txt](https://github.com/qgis/QGIS/files/2402101/Identify.Sidewalks.model3.txt)

**Comment by nyalldawson** [comment]
Looks fine to me

**Pull request merged**
