### PR TITLE
qgs3dmapscene: remove unnecessary onRenderersChanged logic

### PR DESCRIPTION
**Pull request by ptitjano**
## Description

This logic is already handled by `onLayersChanged` and
`onLayerRenderer3DChanged`:

- `onLayersChanged` creates or remove an entity when a layer is added or removed
- `onLayerRenderer3DChanged` recreates an entity when a layer's renderer is changed

cc @benoitdm-oslandia @wonder-sk 

### 2023-02-27

- Removed the `renderers` storage logic in `Qgs3DMapSettings` this is never used as mentionned by @uclaros

### CODE REVIEW

**Review by benoitdm-oslandia — APPROVED** [review]
less deadcode!

**Comment by uclaros** [comment]
That seems like unreachable code, as the signal `Qgs3DMapSettings::renderersChanged` is never fired since `Qgs3DMapSettings::setRenderers()` is never called.
So I guess more leftover code should be removed from `Qgs3DMapSettings` (is _mRenderers_ even needed?)

**Comment by ptitjano** [comment]
> That seems like unreachable code, as the signal `Qgs3DMapSettings::renderersChanged` is never fired since `Qgs3DMapSettings::setRenderers()` is never called. So I guess more leftover code should be removed from `Qgs3DMapSettings` (is _mRenderers_ even needed?)

Thank you. You're right. I have removed this whole logic in a second commit. However, this does break the api because `Qgs3DMapSettings::setRenderers()` is exposed.

**Comment by ptitjano** [comment]
@uclaros @wonder-sk Could you take a look at it please?

**Review by wonder-sk — APPROVED** [review]
Thanks for this - yeah let's get rid of it. It is indeed an artifact from early times when we did not have 3D renderers assigned to map layers, they were external objects assigned using setRenderers(). The idea was that also some third party code may want to add custom 3D entities to the scene using setRenderers(), but that has not materialized (yet) anyway, and we would probably want some better API for that anyway...

**Pull request merged**
