### PR TITLE
Issue #16771: Crash when closing a project with layers in edition

### PR DESCRIPTION
**Pull request by ghost**
I'm trying to fix this issue: https://issues.qgis.org/issues/16771

When I try to reproduce the crash, the call of `QgsProject::clear()` will:

1. Clear all layers into tree, that will request effective layer deletion,
2. Clear all map layers, that have been previously destroyed.

First call will invoke a method that will request the same code of second call but in an asynchronous manner. So 2nd call is executed first & 1st call will be called after the 2nd has finished. This will explain why 2 dialogs are displayed. Cancelling the second dialog box will use an invalid pointer to deleted layer.

I have no crash if I remove the 2nd call - `removeAllMapLayers()` - supposing that deleting all layers into tree will remove all map layers too. Is this correct ?

### CODE REVIEW

**Comment by nyalldawson** [comment]
> I have no crash if I remove the 2nd call - removeAllMapLayers() - supposing that deleting all layers into tree will remove all map layers too. Is this correct ?

Unfortunately not - layers can exist in a project without being part of the layer tree (see arguments for addMapLayer)

The first deletion should be the one to go here...

**Comment by nouanda** [comment]
So can I only call `removeAllMapLayers()` ? This will remove project map layers. But will these deleted layers unregistered from tree view ?

**Comment by nyalldawson** [comment]
> This will remove project map layers. But will these deleted layers unregistered from tree view ?

Looks like it: https://github.com/qgis/QGIS/blob/master/src/core/layertree/qgslayertreelayer.cpp#L73

**Comment by nouanda** [comment]
I have updated patch by keeping `QgsProject::removeAllMapLayers()` when clearing a project ; but removing layers tree cleaning directly (tree has been cleaned by signal/slot call).

**Comment by nyalldawson** [comment]
Can you test:

1. Create a project with some layers AND some groups
2. Clear the project by clicking 'new'

Are the groups also removed without cleaning the tree? We might need the tree cleaning left in place, but moved after the layer removal....

**Comment by nouanda** [comment]
@nyalldawson: Yes, groups will not be cleared. So I restore tree cleaning but moving him after layers deletion.

**Comment by nyalldawson** [comment]
Ok great - let's see what Travis says and then I'll merge

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
