### PR TITLE
Improve cli of parse_dash_results

### PR DESCRIPTION
**Pull request by m-kuhn**
## Description

- Improves terminal output of parse_dash_results.
- Also makes the expected image folder detection more robust (for `expected_test` so far also `expected_test1` was detected)

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
In case you missed it, I've also got fixes for this script lined up in f878b7acad2a5ac37f28eacc499626bb165fb9eb

**Comment by m-kuhn** [comment]
I missed it but looks unrelated and painless :crossed_fingers:

**Comment by m-kuhn** [comment]
Should be fixed

**Comment by m-kuhn** [comment]
@nyalldawson thanks for those fixes, just checked them, very valuable :clap:

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
