### PR TITLE
Do not force verbose build in mingw build

### PR DESCRIPTION
**Pull request by strk**
Makes it very impractical to obtain useful information from CI, for example it took ~4 minutes of wait for @lnicola  to have firefox show some info in https://github.com/qgis/QGIS/actions/runs/6493640195/job/17634987561?pr=54923 (and the info was not even informative: just "write error: stdout"

### CODE REVIEW

**Comment by nyalldawson** [comment]
It's actually needed -- (although I agree that githubs presentation of the log is horrendous). Without verbose we only get a build failed message and no clues as to why it failed or how to fix...

**Comment by lnicola** [comment]
Are you sure? I don't remember having that issue with CMake. And we could still do a `make || make VERBOSE=1`.

**Comment by strk** [comment]
How about redirecting to a file and than only show the last few lines of it ? If it's a matter of timeout I guess I could craft a loop printing some lines from the log at regular intervals

**Comment by strk** [comment]
I guess another option would be using different steps in the workflow ?

**Comment by strk** [comment]
> It's actually needed -- (although I agree that githubs presentation of the log is horrendous). Without verbose we only get a build failed message and no clues as to why it failed or how to fix...

The experience we had was of getting no clue of what was happening despite that VERBOSE=1, see
https://github.com/qgis/QGIS/actions/runs/6493640195/job/17634987561?pr=54923

**Comment by lnicola** [comment]
What happens is that even without `VERBOSE=1`, you get to see what failed. Different project, but shouldn't matter:

```
[ 16%] Building CXX object CMakeFiles/pprepair.dir/FaceInfo.cpp.o
[ 33%] Building CXX object CMakeFiles/pprepair.dir/IOWorker.cpp.o
[ 50%] Building CXX object CMakeFiles/pprepair.dir/PlanarPartition.cpp.o
[ 66%] Building CXX object CMakeFiles/pprepair.dir/PolygonHandle.cpp.o
[ 83%] Building CXX object CMakeFiles/pprepair.dir/pprepair.cpp.o
~/pprepair/pprepair.cpp: In function ‘int main(int, const char**)’:
~/pprepair/pprepair.cpp:370:23: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
  370 |     if (outputResults == " a") {
      |         ~~~~~~~~~~~~~~^~~~~~~
make[2]: *** [CMakeFiles/pprepair.dir/build.make:132: CMakeFiles/pprepair.dir/pprepair.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/pprepair.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

So you get a nice, quiet build, but also details about the error. But you don't see the command that failed.

If you run `make VERBOSE=1` again, this happens:

```
/usr/bin/cmake -S~/pprepair -B~/pprepair/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start ~/pprepair/build/CMakeFiles ~/pprepair/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '~/pprepair/build'
make  -f CMakeFiles/pprepair.dir/build.make CMakeFiles/pprepair.dir/depend
make[2]: Entering directory '~/pprepair/build'
cd ~/pprepair/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" ~/pprepair ~/pprepair ~/pprepair/build ~/pprepair/build ~/pprepair/build/CMakeFiles/pprepair.dir/DependInfo.cmake "--color="
make[2]: Leaving directory '~/pprepair/build'
make  -f CMakeFiles/pprepair.dir/build.make CMakeFiles/pprepair.dir/build
make[2]: Entering directory '~/pprepair/build'
[ 16%] Building CXX object CMakeFiles/pprepair.dir/pprepair.cpp.o
/usr/bin/c++ -DCGAL_USE_GMPXX=1 -I~/pprepair/build -I/usr/include/gdal -O3 -DNDEBUG -std=gnu++17 -frounding-math -MD -MT CMakeFiles/pprepair.dir/pprepair.cpp.o -MF CMakeFiles/pprepair.dir/pprepair.cpp.o.d -o CMakeFiles/pprepair.dir/pprepair.cpp.o -c ~/pprepair/pprepair.cpp
~/pprepair/pprepair.cpp: In function ‘int main(int, const char**)’:
~/pprepair/pprepair.cpp:370:23: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
  370 |     if (outputResults == " a") {
      |         ~~~~~~~~~~~~~~^~~~~~~
make[2]: *** [CMakeFiles/pprepair.dir/build.make:132: CMakeFiles/pprepair.dir/pprepair.cpp.o] Error 1
make[2]: Leaving directory '~/pprepair/build'
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/pprepair.dir/all] Error 2
make[1]: Leaving directory '~/pprepair/build'
make: *** [Makefile:136: all] Error 2
```

Now you also get the compiler command line and error details, but no messy logs for the files that were already built. This is without using `tail`. And `tail` doesn't really help if you're using parallel builds. Some files can take minutes to build, and with `VERBOSE=1`, you'll have thousands of lines of logs from other compiler invocations.

Is `make || make VERBOSE=1` perfect? No, it doesn't help if the failure is related to a previous step, that ran successfully, but was incorrect for some other reasons. But at that point, 15 MB of logs are going to be very frustrating anyway.

**Comment by strk** [comment]
thanks for your tests @lnicola I would also add that verbosity can always be requested by the caller setting VERBOSE env variable, so the build.sh script has no reason to enforce that.

About parallelism, CI being already on a shared environment I doubt parallel jobs would really result in faster builds (but I could be wrong)

**Comment by lnicola** [comment]
> verbosity can always be requested by the caller setting VERBOSE env variable

Right, but we still need to decide if we want `VERBOSE=1` on CI or not. The caller has to pick.

> About parallelism, CI being already on a shared environment I doubt parallel jobs would really result in faster builds (but I could be wrong)

The Linux and Windows runners have 2 vCPUs and you can actually take advantage of them. The MacOS ones have 4 and they're substantially faster most of the times.

**Comment by strk** [comment]
Given the "stdout write error" we see, I think we reducing verbosity will help: GH-54932

**Review by elpaso — APPROVED** [review]
let's give this a try

**Pull request merged**
