### PR TITLE
Add missing dep

### LINKED ISSUE #32764: missing build dependency on qgswmssourceselectbase generated header ?
(extracted from https://github.com/qgis/QGIS/pull/31800#issuecomment-550200854)

I'm still seeing a semi-random build failure as reported in the first comment, building 3.10 release on OpenBSD. 
```
In file included from /usr/obj/ports/qgis-3.10.0/qgis-3.10.0/src/providers/wms/qgswmsdataitems.cpp:26:
/usr/obj/ports/qgis-3.10.0/qgis-3.10.0/src/providers/wms/qgswmssourceselect.h:20:10: fatal error: 'ui_qgswmssourceselectbase.h' file not found
#include "ui_qgswmssourceselectbase.h"

```
Could this be some fallout/side-effect from https://github.com/qgis/qgis/commit/635c1b54d8025ef2c02e5fecf1537ad5ac77f4d7#diff-17c63f5441b19b50cf0d99055932fb4c ? It's as if a dependency wasnt correctly declared somewhere... but only on the wms provider. I tried fiddling with the CMakeLists.txt file to no avail, and it seems the failure is random due to some random build ordering with ninja. Help appreciated.

### PR DESCRIPTION
**Pull request by m-kuhn**
Fix #32764

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by landryb** [comment]
Nice, will try this PR on OpenBSD soonish

**Comment by m-kuhn** [comment]
Thanks, I'll wait for your feedback before merging.

**Comment by lpechacek** [comment]
SUSE packages are baking at https://build.opensuse.org/package/show/home:LPechacek:qgis-issue-32764/qgis . As far as I can tell this fix resolves the issue. Previously oS Leap builds failed within the first five minutes. Now they proceed.

**Comment by m-kuhn** [comment]
Perfect. I added the backport label (so it should be in 3.10.1 as well), I'll merge once you indicate a fully successful build.

**Comment by landryb** [comment]
Well it seems it fixed the build issue for me here. Will try several builds in a row but that looks good :)

**Comment by lpechacek** [comment]
For the record, all builds which ran with `make -j8` previously failed. Now they pass. Thanks!

**Pull request merged**
