### PR TITLE
Add item in Help menu to open PyQGIS web page

### PR DESCRIPTION
**Pull request by DelazJ**
## Description

[Replace this with some text explaining the rationale and details about this pull request]

### CODE REVIEW

**Comment by nyalldawson** [comment]
@manisandro 

Looks like something broke in the mingw repos again :upside_down_face: Now we're getting an error during sipbuild:

```
sip-build.py: An internal error occurred...
2022-08-06T22:32:34.6297457Z Traceback (most recent call last):
2022-08-06T22:32:34.6297955Z   File "/usr/x86_64-w64-mingw32/bin/sip-build.py", line 33, in <module>
2022-08-06T22:32:34.6298472Z     sys.exit(load_entry_point('sip==6.6.2', 'console_scripts', 'sip-build')())
2022-08-06T22:32:34.6299058Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/tools/build.py", line 37, in main
2022-08-06T22:32:34.6302675Z     handle_exception(e)
2022-08-06T22:32:34.6303249Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/exceptions.py", line 81, in handle_exception
2022-08-06T22:32:34.6313410Z     raise e
2022-08-06T22:32:34.6314069Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/tools/build.py", line 34, in main
2022-08-06T22:32:34.6314394Z     project.build()
2022-08-06T22:32:34.6314903Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/project.py", line 244, in build
2022-08-06T22:32:34.6329010Z     self.builder.build()
2022-08-06T22:32:34.6329802Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/builder.py", line 48, in build
2022-08-06T22:32:34.6337914Z     self._generate_bindings()
2022-08-06T22:32:34.6338511Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/builder.py", line 277, in _generate_bindings
2022-08-06T22:32:34.6338892Z     buildable = bindings.generate()
2022-08-06T22:32:34.6339417Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/bindings.py", line 166, in generate
2022-08-06T22:32:34.6346356Z     spec, sip_files = parse(self.sip_file, SIP_VERSION, encoding,
2022-08-06T22:32:34.6347275Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/generator/parser/parser.py", line 35, in parse
2022-08-06T22:32:34.6350969Z     protected_is_public, include_dirs, strict).parse(sip_file)
2022-08-06T22:32:34.6351628Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/generator/parser/parser_manager.py", line 1507, in parse
2022-08-06T22:32:34.6366263Z     self._parser.parse(self._read(sip_file, raw_sip_file),
2022-08-06T22:32:34.6370237Z   File "/usr/x86_64-w64-mingw32/sys-root/mingw/lib/python3.10/site-packages/ply/yacc.py", line 331, in parse
2022-08-06T22:32:34.6370696Z     return self.parseopt(input, lexer, debug, tracking, tokenfunc)
2022-08-06T22:32:34.6371296Z   File "/usr/x86_64-w64-mingw32/sys-root/mingw/lib/python3.10/site-packages/ply/yacc.py", line 823, in parseopt
2022-08-06T22:32:34.6371640Z     p.callable(pslice)
2022-08-06T22:32:34.6372376Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/generator/parser/rules.py", line 3029, in p_typedef_decl
2022-08-06T22:32:34.6384358Z     instantiated = pm.instantiate_class_template(p, name_symbol,
2022-08-06T22:32:34.6388475Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/generator/parser/parser_manager.py", line 1480, in instantiate_class_template
2022-08-06T22:32:34.6388996Z     instantiate_class(p, symbol, fq_cpp_name, tmpl_names, proto_class,
2022-08-06T22:32:34.6390022Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py", line 131, in instantiate_class
2022-08-06T22:32:34.6393007Z     i_class.ctors = _instantiate_ctors(tmpl_names, proto_class, template,
2022-08-06T22:32:34.6394966Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py", line 235, in _instantiate_ctors
2022-08-06T22:32:34.6430745Z     i_ctor.py_signature = _instantiate_signature(proto_ctor.py_signature,
2022-08-06T22:32:34.6431549Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py", line 368, in _instantiate_signature
2022-08-06T22:32:34.6432039Z     i_arg = _instantiate_argument(proto_arg, proto_class, tmpl_names,
2022-08-06T22:32:34.6432698Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py", line 191, in _instantiate_argument
2022-08-06T22:32:34.6433157Z     i_arg.default_value = [_instantiate_value(v, expansions)
2022-08-06T22:32:34.6433795Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py", line 191, in <listcomp>
2022-08-06T22:32:34.6434241Z     i_arg.default_value = [_instantiate_value(v, expansions)
2022-08-06T22:32:34.6434874Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/generator/parser/instantiations.py", line 437, in _instantiate_value
2022-08-06T22:32:34.6435357Z     i_name = ScopedName.parse(template_string(proto_name, expansions))
2022-08-06T22:32:34.6436000Z   File "/usr/x86_64-w64-mingw32/lib/python3.10/site-packages/sipbuild/generator/templates.py", line 201, in template_string
2022-08-06T22:32:34.6436407Z     proto_str = proto_str.replace(name, value)
2022-08-06T22:32:34.6436905Z AttributeError: 'ScopedName' object has no attribute 'replace'
```

Looks like this issue caused by an upstream bug, which was later fixed in pyqt:

https://github.com/qgis/QGIS/issues/49214

I think the solution is updating pyqt to latest release.

**Comment by manisandro** [comment]
@nyalldawson sip-6.6.2, PyQt-builder-1.13.0 and pyqt5-sip-12.11.0 have since landed.

**Comment by agiudiceandrea** [comment]
> sip-6.6.2, PyQt-builder-1.13.0 and pyqt5-sip-12.11.0 have since landed.

Hi @manisandro, it seems the MingW64 build is still failing even with sip-6.6.2, PyQt-builder-1.13.0 and pyqt5-sip-12.11.0.

**Comment by manisandro** [comment]
@agiudiceandrea I could just successfully build 3.22 with this package set, so it's not a fundamental problem with the packages being broken.

**Comment by agiudiceandrea** [comment]
> I could just successfully build 3.22 with this package set, so it's not a fundamental problem with the packages being broken.

I see now that the needed fix is https://riverbankcomputing.com/hg/sip/rev/323d39a2d602 in sip 6.6.3 not yet released.

**Comment by manisandro** [comment]
I've backported the fix in mingw-sip-6.6.2-5.fc37 which is now building.

**Pull request merged**
