### PR TITLE
[feature] add expressions at the symbollist level

### PR DESCRIPTION
**Pull request by vmora**
Size and Rotation can be defined by an expression for all symbols
composing a marker Width can be defined by an expression for all symbols
composing a line

The line symbol layer as been refactored to avoid code duplication and
expose the offset and offset units in the base class. This refacto was
necessary for this feature to avoid unnecessary dynamic cast. Note that
the added functions in the base class where already defined in all child
classes.

Also sets the symbols layer ptr when cloning.

Added a widged for use in categorized/classified symbology gui to set
the expression if needed.

The offset is now set along with size to maintain the relative position
of symbols composing a marker.

An asistant, with preview, is accessible through the data defined button
to help the user define the size expression. Three methods are
available: Frannery, Area and Radius.

Note: breaking change in the symbolslist widget. The widget ctor now
takes the layer as a parameter, this is necessary for the assistant and
for the data-defined buttons. The widget is used only in one place and
although it's a change to the public interface, the likelyhood of
breaking plugins dependent on this widget seems low enought.

### CODE REVIEW

**Comment by vmora** [comment]
Note: this feature interacts with the default scaling method because an sqrt is applied when there is a size expression in a symbol.  So to experiment with the feature, change the scaling method to Diameter.

This feature is meant to replace the 'Advanced' menu options for scale and rotation, but those are not removed here.

**Comment by vmora** [comment]
ping @nyalldawson

**Comment by nyalldawson** [comment]
@vmora - sorry, bit behind at the moment. Will be after Easter before I can take a look at this.

**Comment by vmora** [comment]
replaced by #1987

**Pull request closed without merging**
