### PR TITLE
SLD parsing: handling ogc:Literal within CssParameter

### PR DESCRIPTION
**Pull request by jgrocha**
QGIS fails to load SLD files with valid SLD syntax that uses `<ogc:Literal>` to specify the value of a `<CssParameter>`. 

This works:
```<CssParameter name="stroke-width">2</CssParameter>```

This fails:
```
<CssParameter name="stroke-width">
	<ogc:Literal>2</ogc:Literal>
</CssParameter>
```
Both are valid SLD syntax.

To confirm this behavior, we can use the default data and styles used by Geoserver. Several default styles from Geoserver uses this `<ogc:Literal>` tag, and that's why so many styles are not parsed correctly.

Let's use the shapefile `geoserver/data/data/sf/streams.shp` and the style `geoserver/data/styles/simple_streams.sld` as an example. Those files can be downloaded from 
[simple_streams.zip](https://github.com/qgis/QGIS/files/706842/simple_streams.zip).

* The style uses `<ogc:Literal>` tags around `<CssParameter>` values.
* The style is valid according to the SLD definition.
```
xmlstarlet val -s http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd simple_streams.sld
simple_streams.sld - valid
```
* When the SLD style is loaded in QGIS, these values are not parsed and the default values are assumed instead.
The rendering on Geoserver is 
geoserver rendering of simple_streams
The render on QGIS (right now) is 
qgis rendering of simple_streams

Note: The `<ogc:Literal>` is properly handled when it appears in the context of a `Filter`. For example, the following SLD is already properly imported:

          <ogc:Filter>
            <ogc:PropertyIsBetween>
              <ogc:PropertyName>PERSONS</ogc:PropertyName>
              <ogc:LowerBoundary>
                <ogc:Literal>2000000</ogc:Literal>
              </ogc:LowerBoundary>
              <ogc:UpperBoundary>
                <ogc:Literal>4000000</ogc:Literal>
              </ogc:UpperBoundary>
            </ogc:PropertyIsBetween>
          </ogc:Filter>The problem 

The limitation is only when a value of a `<CssParameter>` parameter is surrounded by `<ogc:Literal>`.

To solve this issue, I've changed `QgsSymbolLayerUtils::getSvgParameterList` at `src/core/symbology-ng/qgssymbollayerutils.cpp`.

Instead of just get the value from the `firstChild()`, I add a test to check if there is an additional `<ogc:Literal>` `ElementNode`. So, the value can be or not be within a `<ogc:Literal>` tag.

The rendering on QGIS, after applying the changes proposed, is 
qgis rendering of simple_streams fixed

### CODE REVIEW

**Comment by jgrocha** [comment]
I've closed [#15422](https://hub.qgis.org/issues/15422) which seems related to this PR. The bug reported was based on an invalid SLD.

**Comment by rldhont** [comment]
Hi @jgrocha thanks for the PR
Can you update or provide tests ?

**Comment by luipir** [comment]
wonderful :)

some observation to have a feedback from people with more experience than me about SLD1.1. I wasn't able to find if ogc:Literal HAVE to be used only with ogc operators, or CAN be used everywhere. A lot of SLDs generated by QGIS use ogc:Literal to express tag parameter values (not only for CssParameter tag). In some cases there can be more than one tag parameter child (not necessarly the first child only).

I'm working to create a dataset for QGIS integration tests of the geoserver plugin. This dataset is inspired on unit test in test_qgssymbollayerv2_createsld.py introduced by @aaime .
This data set already shown QGIS problems to reimport sld generate from the same QGIS and some problems where related with ogc:Literal.

would be fine if @jgrocha can add a unit test, btw I don't think it's not strictly necessary because it is not a new feature but a bug fix. But having already test data, would be simple to create unit test in the same style as in  test_qgssymbollayerv2_createsld.py. e.g. read SLD, apply style and verify if applied style has correct css parameters.

**Comment by aaime** [comment]
Hi @luipir basically all CSSParameter/SVGParameter are mixed mode elements that can contain either a direct literal, or a full OGC Filter expression, for which <ogc:Literal> is the simplest incarnation (you can get fancier, refer an attribute, do basic math, and call functions).

I was trying out the GeoServer plugin and indeed I've noticed the same issue fixed in this pull request, along with wrong unit treatment, basically the import is assuming the units in SLD are mm while they simply cannot be, they should default to pixel instead (or rescaled to on screen mm instead).

**Comment by jgrocha** [comment]
Thanks @luipir and @aaime for the feedback. 

### Tests
I'm learning how to write a unit test for this. I have `tests/src/python/test_qgssymbollayer_createsld.py`on master, but not the `test_qgssymbollayerv2_createsld.py` you mentioned. Is this @aaime v2 test already on master?

I also don't think that a test is strictly necessary for this PR, but we will need several tests in the near future if we want to provide a better SLD support in QGIS. Right now, we are not able to write a SLD in QGIS an read it back and preserve the same style.

### CSSParameter/SVGParameter syntax
The CSSParameter/SVGParameter can be more complex, and that has to be addressed later, but for now, not handling the `<ogc:Literal>` is a limitation that prevents us to read very simple SLD. This simple PR will enable us to read many more Geoserver's SLD.

### Size units
The qgis-geoserver-plugin uses a fixed `SIZE_FACTOR = 4` to convert units from QGIS to Geoserver. It does make sense when exchanging SLD between QGIS and Geoserver to have some logic to convert units. Maybe the current logic can be improved.

My question is: when writing/reading SLD from QGIS, what kind of units should we use? In QGIS we can choose between Millimeter, Pixels and Map unit. We can assume that the units are in millimeters by default, or should we use the `uom` attribute, like in [Styling in real world units](http://geoserver.geo-solutions.it/edu/en/pretty_maps/style_uom.html)?

Right now, the supported units of measure are:

QGIS | Geoserver
--------|-------------
Pixel | Pixel
Millimeter | Meter
 X  | Foot
Map unit |  X

**Comment by rldhont** [comment]
@jgrocha `test_qgssymbollayerv2_createsld.py` is replaced by `test_qgssymbollayer_createsld.py` in master. You can probably create a `test_qgssymbollayer_readsld.py` file.

**Comment by luipir** [comment]
@jgrocha est_qgssymbollayerv2_createsld.py is in 2.14 branch... V2 renderer is the default renderer in qgis3 => renamed all V2 stuffs.
this is a good patch candidate to be backported to 2.14.

definetively we need loopback tests for SLD where possibile... for example categorised stuffs are always converted in rule based => there is no SLD format closed loop, but only rendering closed loop (harder to setup as test)

About size units (and more) I've created qgis projects and simple data sets... to find qgis/geoserver loopback problems... it's a preliminary work, I'm sharing int, but can change. The idea is to move all as integration tests for geoserver plugin.

**Comment by luipir** [comment]
@jgrocha just a note, @aaime SLDs seems based on Natural Earth data set ne_110m_admin_0_countries.shp
BTW his unit tests does not need real data working only at dom level and settingup symbol rederers directly

**Comment by luipir** [comment]
@jgrocha qgis projects for tests created  with 2.14LTR
https://github.com/luipir/sld-loopback-testdata

as you can see projects and paths reflect @aaime test name

**Comment by aaime** [comment]
Hi @jgrocha styling in on screen millimeters (the mm unit of qgis) simply does not exists in SLD, not even in GeoServer extensions. Real world units are "on ground" units instead.

**Comment by jgrocha** [comment]
Hi @rldhont,
I've added a new test `test_qgssymbollayer_readsld.py`. It parses an SLD with and without `CSSParameter` within `<ogc:Literal>` tags. Then we check if the style was properly applied.
The test fails for the current version. The test succeeds with this PR.

**Comment by luipir** [comment]
I suggest

1) label this PR to be backported (it is not a feature IMHO it's a bug fix)
2) merge as soon as possible because:
- I'm doing fix on reading back parameters as Rotation => I need a test file where to add tests 
- this would facilitate a reference platform where to add test for @aaime for his crowdsourced work on SLD1.1/Geoserver compatibility

**Comment by rldhont** [comment]
@luipir and @aaime do you think this PR can be merged ?
Who can review this code ?

**Review by luipir — CHANGES_REQUESTED** [review]
IMHO can be merged if there are the following simplifications in test_qgssymbollayer_readsld.py
1) change in test data set => two options
*) use already available test shapes instead of adding new one
or
*) because a real shape is not necessary layer can be build from memory layer (as in writesld.py test)

2) setUp(self) should be more generic. The rational is that I'm adding some more tests in this file that use different data and sld.

btw these are modification in the test style, and can be updated later. Because I need the test_qgssymbollayer_readsld.py available (to work on it) I suggest to merge and than we can simplify the test.

**Comment by jgrocha** [comment]
Thanks @luipir for your comments on the tests.
I've reviewed `test_qgssymbollayer_readsld.py` to address both your suggestions:
* removed the external shapefile and use a temporary layer. I've done that on a `createLayerWithOneLine` helper function that be be used in other tests.
* removed specific data and style dependencies from `setUp(self)`

**Comment by luipir** [comment]
tnx @jgrocha
@rldhont for me can be merged

**Comment by rldhont** [comment]
@luipir can you validate the PR ?

**Comment by rldhont** [comment]
@aaime can you validate the PR ?

**Comment by aaime** [comment]
@rldhont I won't be able to before the weekend... hopefully I'll remember to do that.

**Review by luipir — APPROVED** [review]

**Review by luipir — APPROVED** [review]

**Review by luipir — APPROVED** [review]

**Comment by luipir** [comment]
Hi @jgrocha and @rldhont
waiting for merge this PR to start with another PR that fix another SLD reimport problem (Rotation) and add related test in the file that will merged here.
@jgrocha in https://github.com/boundlessgeo/QGIS/commit/918df983e0b39cc8e90116f5b7a70abcdcb8c4c2
you can find how I managed test without using any test data file (inpired by  @aaime tests)

so... waiting for merge :)

**Comment by rldhont** [comment]
@luipir I'm waiting for @aaime approved to merge

**Comment by aaime** [comment]
@rldhont looks good to me, +1

**Pull request merged**
