### PR TITLE
Recursively read all sublayers in QgsAmsProvider

### PR DESCRIPTION
**Pull request by manisandro**
The current code assumes a single level of sublayers, but the sublayers can themselves also have sublayers. For example https://www.gis-daten.ch/svc/rest/services/ow_arv/lu_raummonitoring/MapServer

This will fix identify not identifying features in nested sublayers as well as the legend graphic not containing the portions of the nested sublayers.

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@manisandro any chance of a test for this one? Our ams provider is sadly lacking in test coverage right now...

**Comment by manisandro** [comment]
Any suggested template for such a provider test with a remote endpoint?

**Comment by nyalldawson** [comment]
@manisandro 

>  Any suggested template for such a provider test with a remote endpoint?

I'd suggest avoiding online ones and using file based urls instead, like the afs/wfs tests do. E.g  https://github.com/qgis/QGIS/blob/master/tests/src/python/test_provider_afs.py#L731

**Comment by nyalldawson** [comment]
... and https://github.com/qgis/QGIS/blob/14324b5a4f1c91601af9daf48eaaa53bf807bd9d/src/core/providers/arcgis/qgsarcgisrestquery.cpp#L247

**Pull request merged**
