### PR TITLE
[sipify] allow to define python operator in headers

### PR DESCRIPTION
**Pull request by 3nids**
sipify will take care of injecting them in python/{module}/__init__.py

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]
Nice!

**Comment by nyalldawson** [comment]
Nice work! Don't we have some others like this too? (QgsGeometry for one jumps to mind)

**Comment by m-kuhn** [comment]
Merge?

**Comment by m-kuhn** [comment]
Sounds good, or put the handwritten content into a separate file and merge them on build?

**Comment by 3nids** [comment]
@m-kuhn done, now sipify creates a python file when needed and cmake will merge it.

**Comment by m-kuhn** [comment]
Nice 🎉

**Pull request merged**
