### PR TITLE
[themes] Allow themes to style collapsible group box

### PR DESCRIPTION
**Pull request by nirvn**
## Description

This is possibly a fix to the infamous 3.16 options/raster dialog crash.

### CODE REVIEW

**Comment by nirvn** [comment]
@luipir , if you have a minute, can you try to see if this fixes the crashes on windows?

**Comment by luipir** [comment]
> @luipir , if you have a minute, can you try to see if this fixes the crashes on windows?

I do not have a windows compilation setup :(

**Comment by luipir** [comment]
> @luipir , if you have a minute, can you try to see if this fixes the crashes on windows?

BTW I can check on linux

**Comment by nirvn** [comment]
@luipir , oh good, if you had it crashing on linux, yes, please verify whether this fixes the crash on your linux machine.

**Comment by elpaso** [comment]
> > @luipir , if you have a minute, can you try to see if this fixes the crashes on windows?
> 
> I do not have a windows compilation setup :(

remember MXE builds for windows, you can use that for windows testing.

**Comment by nirvn** [comment]
@elpaso , not in this case as the MXE builds are running against qt 5.14 ( yay! ) whereas the crash occurs on older qt versions, including very old 5.9 served on osgeo4w.

**Comment by luipir** [comment]
still crash cherry-piking this PR into release_3_16

**Pull request closed without merging**
