### PR TITLE
Place labels next to their corresponding options in North Arrow decor…

### PR DESCRIPTION
**Pull request by DelazJ**
…ation

The "placement" and "Margin from edge" labels are currently inverted, hence 
image
instead of
image
Also fix tabstops

### CODE REVIEW

**Comment by DelazJ** [comment]
Also wonder if it should be outline or stroke...

**Comment by nyalldawson** [comment]
Should definitely be stroke.

But are these labels actually backward? The top one is the margin, and the second one is where it's placed..

**Comment by DelazJ** [comment]
you mean placement options should be above margin's, do you?

**Comment by nyalldawson** [comment]
Argh ignore me - I had your before/after pictures backward!

**Pull request merged**
