### PR TITLE
[Feature] Conditional styles for relation reference widget

### PR DESCRIPTION
**Pull request by m-kuhn**
In long-distance heating, there are some heat carrier fluids that really no longer should be used like Wodka.

This feature helps to properly communicate to the person in charge of digitizing that he should not assign one of the "inactive" heat carrier fluids new heatings.

As a side-effect, this flexible way of styling built for the attribute table once by @NathanW2 (good job by the way) is now available also in the relation reference widget.

Note: if you don't want to style the whole row in the attribute table, there is the alternative approach of styling a single field and define the "display expression" to only include this field. This can be used in combination with *virtual fields* for maximum flexibility.

peek 2017-03-03 16-49

### CODE REVIEW

**Comment by NathanW2** [comment]
Nice.  Does it support all the styling options?

**Comment by m-kuhn** [comment]
I guess so but I didn't try.

**Comment by NathanW2** [comment]
Good feature to me. Anything stopping the merge?

**Comment by m-kuhn** [comment]
Not at all, I just like to give people time to review. Will merge soon.

**Pull request merged**
