### PR TITLE
Mac Qt6 Builds

### PR DESCRIPTION
**Pull request by m-kuhn**
Work in progress

Build instructions

```sh
# install xcode command line tools --> check internet
# maybe needs an xcode-select or so too ?

# install vcpkg
. <(curl https://aka.ms/vcpkg-init.sh -L)
# install build requirements (install homebrew first if not yet done)
brew install git cmake flex bison automake autoconf libtool nasm ninja
# get code
git clone git@github.com:qgis/QGIS.git

# prepare env
export PATH=$(brew --prefix bison)/bin:$(brew --prefix flex)/bin:$(brew --prefix libtool)/bin:$PATH

# select your architecture here
TRIPLET=arm64-osx-dynamic-release
# TRIPLET=x64-osx-dynamic-release

cmake -S . \
      -G Ninja \
      -B build \
      -D WITH_VCPKG=ON \
      -D BUILD_WITH_QT6=ON \
      -D WITH_QTWEBKIT=OFF \
      -D WITH_BINDINGS=ON \
      -D QGIS_MACAPP_FRAMEWORK=OFF \
      -D VCPKG_TARGET_TRIPLET="$TRIPLET" \
      -D VCPKG_HOST_TRIPLET="$TRIPLET" \
      -D CREATE_MACOSX_BUNDLE=OFF

# build (use RelWithDebInfo if you want to debug)
cmake --build build --target Release
```

### CODE REVIEW

**Comment by m-kuhn** [comment]
Added a little quality of life improvement where this will report on library updates

**Comment by nyalldawson** [comment]
Should we drop the existing Mac workflow now? I can't see many benefits of retaining it since it's a build-only test, and this should nicely cover that. (Plus it'd release the road block preventing us upgrading the minimum python version).

**Comment by m-kuhn** [comment]
There are two things this doesn't currently cover:

- packaging / dmg
- qt5

A few other things in the category nice to have:

- grass
- saga
- other additional deps ?

**Comment by nyalldawson** [comment]
@m-kuhn 
> There are two things this doesn't currently cover:

> packaging / dmg

Unless I'm mistaken the current Mac build doesn't include these either, right?

> qt5

Valid point, but I don't think a qt5 build without tests or usable artifacts is very useful. 

> Saga

That's all been dropped from processing, there's no need to spend effort on packaging this. If someone wants Saga functionality they can use official saga Mac install process + the community saga plugin.

**Comment by nyalldawson** [comment]
> If we don't ship the product here for end users (qt5 and dmg) the python problem still persists, no?

Could the approach used here be easily adapted to also make a qt5 build?

**Comment by m-kuhn** [comment]
Yes, we've had success with that for kadas

**Review by nyalldawson — APPROVED** [review]

**Comment by 3nids** [comment]
If I'm not wrong the workflow is missing some build cache.
What would be the approach here? We merge this without the workflow part? or make it on demand?

**Comment by 3nids** [comment]
Also many thanks @m-kuhn for making compilation of QGIS so straightforward on macOS!!!

**Comment by m-kuhn** [comment]
I think we'll need to disable/tune other workflows before we can afford more build cache otherwise we'll overuse the cache. That was one of the reasons to mark it as "draft"
If this has benefit already without workflow (for mac devs) we can merge with the workflow disabled and start a new draft PR, your call @3nids

**Comment by 3nids** [comment]
let's merge it!

**Pull request merged**
