### PR TITLE
Add BWTA2017.gsb to srs.db

### PR DESCRIPTION
**Pull request by m-kuhn**
NTv2 grid available here:
https://www.lgl-bw.de/lgl-internet/web/sites/default/de/05_Geoinformation/Galerien/Dokumente/BWTA2017.zip

More information:
https://www.lgl-bw.de/lgl-internet/opencms/de/05_Geoinformation/Liegenschaftskataster/ETRS89-UTM/

```sql
INSERT INTO "tbl_datum_transform"
VALUES(NULL, 100017, "4314", "4258", "9615", "BWTA2017.gsb",
NULL, NULL, NULL, NULL, NULL, NULL, 
"Transformation for the German federal state of Baden-Wuerttemberg: Diese NTv2-Datei deckt das Gebiet von Baden-Wuerttemberg ab und ist daher ausschliesslich für die Transformation von Geo(fach)daten innerhalb von Baden-Wuerttemberg geeignet. Dieser Ansatz ist für Geo(fach)daten zu verwenden welche auf Basis der ALKIS Daten gefuehrt und erstellt werden.", 
"For applications requiring an accuracy of better than 1 metre.", 1, 0, 3339);
```

See also https://github.com/OSGeo/proj-datumgrid/issues/22

### CODE REVIEW

**Comment by nyalldawson** [comment]
Hmm... if you're adding this, I also want to add the Oceania grids. Which are about 100mb. Are we ok with this?

**Comment by m-kuhn** [comment]
The grid itself is 375 MB and not included in this pull request, this is just the entry, like https://github.com/qgis/QGIS/pull/1502.

The file itself is a pending issue in proj-datumgrid (see link above), I think in the future we want to have an easy way to download external resources like this upon request.

**Comment by nyalldawson** [comment]
> The grid itself is 375 MB and not included in this pull request, this is just the entry, like #1502.

Oh good - I thought we were along in these huge grids!

> The file itself is a pending issue in proj-datumgrid (see link above), I think in the future we want to have an easy way to download external resources like this upon request.

Yes please! This is a real blocker which could potentially prevent QGIS being adopted in organisations.

**Comment by m-kuhn** [comment]
So are we okay with adding additional entries in here?

> Yes please! This is a real blocker which could potentially prevent QGIS being adopted in organisations.

Argh, that would have been a nice grant proposal, just a bit too late. Possibly using [the content fetcher registry](https://github.com/qgis/QGIS/pull/6872) and enhancing it with a persistent storage.

**Comment by nyalldawson** [comment]
> Possibly using the content fetcher registry and enhancing it with a persistent storage.

Sounds perfect! Surely we can find a non-PSC backer for this, right?

**Comment by m-kuhn** [comment]
Correct, but it's a separate discussion, what's your opinion on merging this new entry.

@3nids what's your opinion on the more generic topic?

**Comment by nyalldawson** [comment]
So back on this discussion then... do we need to add these entries for every grid supported?

**Comment by m-kuhn** [comment]
What alternative approaches do we have?

**Comment by nyalldawson** [comment]
Sorry - my questions is coming from ignorance on the whole srs/datum database setup in qgis. I wish this was all documented somewhere... it's very much black magic.

**Comment by m-kuhn** [comment]
The main issue I see is that it's not managed in plain text format but in an sqlite blob. I'm extrapolating from #1502 that this is the way it's historically done.

**Comment by palmerj** [comment]
Maybe this is something that gdalbarn.com can address as part of the proj refactoring and sqlite database storage

**Comment by palmerj** [comment]
Having something that downloads the large source grids from url would be a good idea. Maybe on first usage of the srs in question...

**Comment by kbevers** [comment]
> Having something that downloads the large source grids from url would be a good idea. Maybe on first usage of the srs in question...

This is an interesting idea. For now I think it would make sense for QGIS to let users choose to install the regional proj-datumgrid packages they need. The packages are to be safe for redistribution. Regarding the BWTA2017 grid I am sure we will come to the conclusion that it can be included in the European package. The intention of the local authority seems to be in the right place, they've just made the unfortunate decision to make up their own license. Usually we can resolve these things.

On a longer term basis we could add a function to PROJ that offers the user a link for download of a particular grid that is needed for a specific transformation. QGIS and other applications can then take that URL and ask the user if she wants to download it. How does that sound?

**Comment by rouault** [comment]
> On a longer term basis we could add a function to PROJ that offers the user a link for download of a particular grid that is needed for a specific transformation. QGIS and other applications can then take that URL and ask the user if she wants to download it. How does that sound?

That was exactly my thought. In the future proj SRS database, we could have a table with known locations for the grids referenced.

**Comment by jef-n** [comment]
`$ bash scripts/dbdiff.sh  | sed -ne "s/^+[^+]/I/p"`
```sql
INSERT INTO tbl_datum_transform VALUES(NULL,100017,4314,4258,9615,'BWTA2017.gsb',NULL,NULL,NULL,NULL,NULL,NULL,'Transformation for the German federal state of Baden-Wuerttemberg: Diese NTv2-Datei deckt das Gebiet von Baden-Wuerttemberg ab und ist daher ausschliesslich für die Transformation von Geo(fach)daten innerhalb von Baden-Wuerttemberg geeignet. Dieser Ansatz ist für Geo(fach)daten zu verwenden welche auf Basis der ALKIS Daten gefuehrt und erstellt werden.','For applications requiring an accuracy of better than 1 metre.',1,0,'3339');
```

(proj-bwta2017 added to OSGeo4W - next to already existing proj-beta2007)

**Comment by jef-n** [comment]
@nyalldawson checkout https://download.osgeo.org/osgeo4w/x86_64/release/proj/proj-bwta2017/ (the x86 variants are hardlinked) and https://trac.osgeo.org/osgeo4w/wiki/PackagingInstructions 

Updating proj and proj-datumgrid is on my TODO list anyway - if you're not in a hurry I could include the rest of the grids (ie. proj-datumgrid-{europe,north-america,oceania}-1.0.tar.bz2) from https://download.osgeo.org/proj/.

**Comment by m-kuhn** [comment]
> (proj-bwta2017 added to OSGeo4W - next to already existing proj-beta2007)

Thanks @jef-n

**Comment by rdbath** [comment]
great to see that the QGIS 3.x version now has the srs.db-entry for the BWTA grid.
Will this also be backported into the QGIS 2.18.x-version?

**Comment by jef-n** [comment]
@rdbath done in 0f6d808b0cf293

**Comment by rdbath** [comment]
great, thanks @jef-n

**Pull request merged**
