### PR TITLE
Add warning for WFS feature count limit (multiple of 500)

### PR DESCRIPTION
**Pull request by tomtor**
Show a messagebar warning when an exact multiple of 500 features is retrieved

### CODE REVIEW

**Comment by m-kuhn** [comment]
There are a couple of problems with this.
The provider should be independent from app, so it should use some other way to signal problems than directly accessing the message bar or it will not be possible to use it from standalone apps or the server...
Then it is kind of unclear what the message wants to tell the user. If I would get it I would probably want to answer it "ok, so what?" ;)

I have discussed this with @raymondnijssen a couple of weeks back. I think this is a heuristic to determine if a WFS server may potentially be delivering an incomplete dataset.

Most important, are you sure that there are no better means to detect that?

And if not, I think there needs to be a better message to tell the user not only about the fact but also about the possible conclusions. Maybe offer some way to configure the threshold or disable the functionality.

**Comment by tomtor** [comment]
@m-kun Yes, it is an unsophisticated approach to detecting the delivery of an incomplete dataset, but there is no other reliable way.

Regarding the user perspective: currently some data is not shown and the user will never notice unless we notify him. The message could be altered to give the advice to zoom in, but that still leaves the technical issue, how do we notify the user in an elegant way if the message bar is not an option?

**Comment by raymondnijssen** [comment]
@tomtor I like this functionality and actually I proposed it in my 06/11/2015 update in this issue:
https://hub.qgis.org/issues/13117

So thanks for adding it, I have no functional objections. But I do understand m-kuhn's objections about the way you implemented it. So maybe you could somehow split GUI and Provider functionality?

Another problem is a bug in the WFS provider that makes your option of "zooming in further" not work. It is described in the same bug report mentioned above. This actually makes that the user can not do anything about it. The user will only know that information might be missing.

A last little enhancement tip: If the provider keeps the maximum number of received features in memory, it could only show warnings for "multiples of 500 features >maxNumFeaturesEverReceived" making it a bit smarter by unnecessarily disturbing the user less.

**Comment by tomtor** [comment]
@raymondnijssen I changed the implementation so that it just logs in the WFS Gui tab. I actually like this behavious perhaps even more because it is less obtrusive for an knowledgable user and it fixes m-kuhn's issue.

I also have a pull request which fixes the WFS provider and enables the "just fetch visible area" option for the WFS provider, so zooming in/panning on a WFS with fetch limit actually works for me now:

https://github.com/qgis/QGIS/pull/2511

**Comment by m-kuhn** [comment]
@tomtor looks much better now, thanks. What do you think about introducing a phrasing like "this indicates ..." or similar into the message to highlight the fact that it's a heuristic approach? Only a suggestion really.

**Comment by tomtor** [comment]
@m-kuhn You are right, I will think about a more indicative phrasing. Perhaps I will implement the max received in previous requests suggestion also. I assume that I need to squash the commits after the final commit and use push -f to update the request?

**Comment by m-kuhn** [comment]
Sounds good to me

**Comment by m-kuhn** [comment]
Hint: I never squash, I always use interactive rebase which is very flexible and at the same time synchronizes with the current upstream master

    git rebase -i master

**Comment by m-kuhn** [comment]
Merged in e9eb233e0a6b550672ae419381989189c7eef580
Thank you

**Pull request closed without merging**
