### PR TITLE
Master.spatialite provider

### PR DESCRIPTION
**Pull request by mj10777**
## Description
QgsSpatiaLiteProvider reorginised for Spatialite 4.5.0, RasterLite2 and Topology

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

This pull request will correct many known problems and prepare the QgsSpatiaLiteProvider to deal with the many changes in the upcoming Spatialite 4.5.0 with RasterLite2, Topology and SE/SLD Style support.

The present approach, to simply list TABLEs and VIEWs that contain Geometries is no longer practicable, since many of the Administration TABLEs also contain geometries which normally should never be displaced.

Also the interdependence between Layers (Vector and Raster) with Styles and other information contained in the Database, calls for a different approach to the problem, so that all of the capabilities being offered by Spatialite 4.5.0 can be fully utilized.

---

For this three new classes have introduced
* **SpatialiteDbInfo** 
   * a class that will contain all needed information about the Database
* **SpatialiteDbLayer**
   * a class that will contain all needed information about a specific Layer within the Database
* **QgsSpatiaLiteUtils**
   * with helper static function (see below)

**SpatialiteDbInfo**  will contain this list of all available **SpatialiteDbLayer**s
* and will make them available upon demand

---

**SpatialiteDbInfo** will be contained in the presently existing **QgsSqliteHandle** class
* with it's sharing capability

This portions of this pull request have been placed in **core/providers/spatialite**
* so that they may be made available everywhere where a spatialite connection is needed

Class **QgsSLConnect** in core has been removed, since the 3 static functions are available in the **QgsSqliteHandle** class.
* all classes that used **QgsSLConnect** have been adapted to use **QgsSqliteHandle** instead

In a scenario, where 10-50 layers are being loaded from the same Database
* that Database is read only once and the collected information shared between the 10-50 layers

---
All classes within the QgsSpatiaLiteProvider access all needed information from **SpatialiteDbInfo** or **SpatialiteDbLayer** instead of storing them as member variable.

Instead of **mSqliteHandle** , **dbSqliteHandle()** is used, so that knowledge of the internal structure of **SpatialiteDbInfo** and **SpatialiteDbLayer** is not needed.

Otherwise the functionality of the QgsSpatiaLiteProvider, QgsSpatiaLiteFeatureIterator and QgsSpatiaLiteConnection have not changed, only the method on how they attain the needed information has.

These classes had contained many functions for the retrieval of information from the Database, some copies of others, which is now dealt with **once** in **SpatialiteDbInfo** and/or **SpatialiteDbLayer**.

All of these functions have been removed.
All static functions (10), that were used in QgsSpatiaLiteProvider, have been moved to a **QgsSpatiaLiteUtils** class. These were mainly functions for the calculation of object sizes or converting from one (internal spatialite specific) format to another.

Goal was to separate the Database and Provider functionality.
This should simplify future maintenance of both. 

Since the classes contained in qgsspatialitedataitems.h/cpp are no longer used (since at least QGis 2.18), these files have been removed.

---
Since **SpatialiteDbInfo** is separate from the QgsSpatiaLiteProvider class, it can be used for other tasks, such as
* is the file a **Sqlite3** container
* is the container supported by QGis through
   * **QgsSpatiaLiteProvider**
   * **QgsOgrProvider**
   * **QgsGdalProvider**

This would make it possible to be used within the
* Drag and Drop and Browser logic

For 'Drag and Drop', this has been implemented in QgisApp::openLayer, where the QgsSpatiaLiteSourceSelect will be opened if the Droped files is a supported **Sqlite3** container and that there is more than 1 Layer. If only 1 Layer then it will be opened. Otherwise the function will continue as it does now.

It can be called in a way to only 'sniff' the Database, returning after determining which container type it is
* Spatialite (from version 2.4 to present)
* FdoOgr
* GeoPackage (Raster/Vector)
* MbTiles
* RasterLite1
* RasterLite2
* Topology

Since the **QgsOgrProvider** cannot (yet) recognize Spatialite Tables with more than 1 Geometry and since **Ogr** has no support for writable SpatialView's, it would be important that within the Drag and Drop/Browser logic the **QgsSpatiaLiteProvider** would be used as the default.

The 'Data Source Manager - Spatialite' has been adapted to use **SpatialiteDbInfo** and **SpatialiteDbLayer**, so that the structure of the different containers can be shown (more to that later).

Also **SpatialiteDbInfo** can submit the selected Layers as **QgsVectorLayer** or **QgsRasterLayer** with the proper Provider/Connection Uri's.

This would have the advantage, that for a **GeoPackage** source, both the Vector (**QgsOgrProvider**) and Raster (**QgsGdalProvider**) Layers could be added in 1 step.

---
For the User, the only noticeable change will be the 'Data Source Manager - Spatialite'.
The **QgsSpatiaLiteTableModel** (based on **QStandardItemModel**) will now show a TreeView

Here a sample showing a **GeoPackage** Database:

datasourcemanager gpkg select

Here you can see that there are 3 tree branches
* Vector
* Raster
* Non-Spatial [will always be the **last** branch]

so that the User can distinguish between the different types, collapsing what they don't want to see.

Inside the Non-Spatial group, there are also sub-groups, so that a search for Data-Tables, Views can be easily found (without the data beings displayed), since index-tables are in an extra group.

Since **SpatialiteDbInfo** must collect the Non-Spatial anyway, the CheckBox to turn this on/off has been hidden.

In the above Image ,the last selected Item is a Raster.
When selected, first any Raster, then Polygons will be submitted, since it seems that Rasters are rendered before any Vectors. Then Linestrings after which any Point will be submitted, so that the Polygons will be over the Rasters, the Linestrings over the Polygons and the Points over the Linestrings.

Here a view of the result from a Spatialite-Database that contains SE/SLD-Styles:

datasourcemanager styles select

Since **SpatialiteDbInfo** has collected all the needed information about existing Styles and **SpatialiteDbLayer** has retrieved the information which Style it should use,  **SpatialiteDbInfo** will call the **readSld** function of QgsVectorLayer before it is sent to QGis.

---
At some time the Browser logic should be adapted to utilize the capability of **SpatialiteDbInfo**  after an initial QGis 3.0 release.

Also the **QgsSpatiaLiteTableModel** from **QStandardItemModel** to a **QAbstractItemModel** which would be fine tuned to interact with **SpatialiteDbInfo** and **SpatialiteDbLayer**
* Alessandro Furieri (Sandro of Spatialite), has asked if 

> adding some ad hoc function allowing to drop or rename columns in the most painless way.

making the administration of a Database easier.

More work on the QgsRasterLite2 provider will be done during/after the initial release of RasterLite2.

---
Known problem: none.

The geometry shown in the 2nd image were all created after all changes in QgsSpatiaLiteProvider, QgsSpatiaLiteFeatureIterator and co. were made, so I believe that these changes can be considered stable.

---
Other changes that come to mind:
* the default values are now correctly shown when creating a new Geometry
* SpatialViews will use the default values of the base TABLE when the column names have not changed (which in a view is possible)
* full Date/DateTime support

---
cmake:
* **FindRasterLite2.cmake** has been added as well a logic in CMakeLists.txt to add it as an **optional** dependency.
   * this would be a pre-condition for a QgsRasterLite2 provider support

The only use of the RasterLite2-Api is needed for for a connection inside QgsSqliteHandle
* and has already been added.
Everything else for RasterLite2 is be Sql-based.

Also a **SPATIALITE_VERSION_GE_4_5_0** has been added in CMakeLists.txt and used where needed.

No other (intended) changes have been made.

---
Changes made in **QgsSpatiaLiteFeatureIterator** (around 2017-10-25) have been incorporated into this version.

---
Previous pull requests are redundant.
 https://github.com/qgis/QGIS/pull/5033
* already closed

https://github.com/qgis/QGIS/pull/5146
* still open

---
Since there is a backlog of pull request and the changes here are very extensive, I will write to Alessandro Furieri (Sandro of Spatialite) asking if he can invest the time to give a more thorough look a the Spatialite specific changes, which may assist in getting this into QGis 3 before the freeze take effect. But due to the present work being done, this many not be possible.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks for bringing this up again, @mj10777 

As stated in https://github.com/qgis/QGIS/pull/5146, this pull requests mixes several topics and will need to come in smaller chunks or it can not be reviewed.

Suggestions:

 * DataItem changes separate
 * RasterLite2 changes will need to come separate after
 * ConnectionPool changes separate
 * ...

Thanks a lot, I really hope we can bring some of these changes into 3.2

**Comment by mj10777** [comment]
>> DataItem changes separate
to delete the non-used files needs an extra pull request?
>> RasterLite2 changes will need to come separate after
this is a part of the whole, to separate it only put it back together makes no sense
>> ConnectionPool changes separate
without these change, nothing will work (no connection possible)

**Comment by m-kuhn** [comment]
To all your questions: separation should be done as much, not as little as possible. This is a general policy.

**Comment by mj10777** [comment]
This has already been separated once, where it could compile - but never be used
* nobody looked at it and thus was a wast of effort

To separate something in parts, without the other parts - will not compile and thus completely useless.

**Comment by m-kuhn** [comment]
> To separate something in parts, without the other parts - will not compile and thus completely useless.

True, this would be completely useless.

What if you open a separate pull request now with e.g. the dataitems change. I guess it would still compile and if it's really nowhere used (as stated above), should be a nobrainer. If yes, I'm sure someone will make the call and merge it.

**Comment by mj10777** [comment]
>> What if you open a separate pull request now with e.g. the dataitems change.

If you mean this:
>> Since the classes contained in qgsspatialitedataitems.h/cpp are no longer used (since at least QGis 2.18), these files have been removed.

There are no changes. These classes have not been used (as far as I can see) since at least 2.18.

**Comment by mj10777** [comment]
Theme: **qspatialite**
For the record, I have done nothing with **qspatialite**.
Since I don't use it (as most things that are python based), I have no opinion on this. 

There was a discussion about it on the spatialite forum (called 'pyspatialite needs a new maintainer'):
https://groups.google.com/forum/#!topic/spatialite-users/o0jUwMUqx_g

From my reading, the original maintainer (Loki) no longer maintains it:

>>  this has all been discussed in the pysptialite repository issues and here before, and is the reason I don’t maintain it any longer. 

In an answer from Bas (qlinux...@gmail.com)
>> So for what the qgis package is concerned we can drop the pyspatialite package when its switched from 2.14 to 2.18.

who later mentions Qgis 3.0.
So thoughts should be made about discontinuing **qspatialite**.

**Comment by m-kuhn** [comment]
> These classes have not been used (as far as I can see) since at least 2.18.

Perfect, can you do a pull request?

>  For the record, I have done nothing with qspatialite.

👍  qspatialite can very well (and will) be dealt with separately.

**Comment by mj10777** [comment]
>> Perfect, can you make a pull request?


that would be part of this pull request since I removed it from the **CMakeLists.txt** and did a **git rm** for both files.

**Comment by m-kuhn** [comment]
The process to remove the files is the right approach. It is however not the right approach to bundle it within this pull request.
Thank you for adjusting this!

**Comment by m-kuhn** [comment]
@mj10777 are you planning to create a new pull request for the removal of those files? I guess that could even make it into 3.0.

**Comment by mj10777** [comment]
No, since it is part of this one.
Since, I assume, **qspatialite** is to be removed, that could be done together since in both cases the **CMakeLists.txt** must be adapted.

**Comment by m-kuhn** [comment]
> qspatialite is to be removed

qspatialite has been removed already.

> no

let's see if someone else can pick up this pr, I'll redirect my attention towards others.

**Comment by jef-n** [comment]
On Wed, 01. Nov 2017 at 12:29:20 +0000, Matthias Kuhn wrote:
> > qspatialite is to be removed
 
> qspatialite has been removed already.

really?  qspatialite != pyspatialite

**Comment by mj10777** [comment]
The **qspatialite** I am talking about is in the directory of src/providers/spatialite
* and it looks as if it is still there

I believe (not sure) that there is something in python/ that has a reference to it

**Comment by jef-n** [comment]
Nope, `QSPATIALITE` is a `QtSql` driver (like `QSQLITE` just linked to and activating `spatialite`) - no link to python.  There might be python and/or C++ plugins depending on this (which can probably easily migrated to `QSQLITE` and and initial `load_extension`)

**Comment by m-kuhn** [comment]
> really?  qspatialite != pyspatialite

oops, misread that, my bad

**Comment by mj10777** [comment]
> Since the classes contained in qgsspatialitedataitems.h/cpp are no longer used (since at least QGis 2.18), these files have been removed.

I am having doubts about the validity of this statement, since it looks as if the used classes are part of the **QgsDataItem** logic, so may very well still be needed.

So these files **should not** be deleted for QGis 3.0!

**Pull request closed without merging**
