### PR TITLE
Project Templates fixes

### PR DESCRIPTION
**Pull request by nyalldawson**
Misc fixes to the new project template functionality

### CODE REVIEW

**Comment by nirvn** [comment]
Spotted another issue: drag and drop a dataset (shapefile, kml, whatever) onto the welcome page, it correctly loads the dataset but the panels aren't restored. You end up with a panel-less QGIS window.

**Comment by saberraz** [comment]
I should probably file a bug instead, but here is my 2c about template/welcome page:
Browser panel is the first place most of (new) users start their work in QGIS to add layers, open projects, etc. Not showing it, is a big regression imo.

**Comment by nirvn** [comment]
I'm also turned off by the absence of the browser upon launching the app; I don't think it should force us to U-turn on this, but it'll hopefully be a motivation to make sure the welcome page gets a nice set of improvements for 3.10 :)

**Comment by Gustry** [comment]
I also lost the browser when I started QGIS 3.9 for the first time. It was also a real miss for me. But now it's back so I'm not sure what I did to get the browser back automatically ...

**Comment by alexbruy** [comment]
There is also no way anymore to opt-out from the welcome page. It is displayed even if I choose "start with new project".

**Comment by nirvn** [comment]
@alexbruy , that's definitively a bug in need of being addressed :)

**Comment by m-kuhn** [comment]
Thanks for the fixes @nyalldawson 
For the other discussion, I wouldn't mind bringing back the panels. The implementation for hiding them is very brittle. Please open issues for whatever you find.

**Pull request merged**
