### PR TITLE
Fix QVariantMap mapping for Qt6 builds

### PR DESCRIPTION
**Pull request by nyalldawson**
Adds workarounds and conversion code to get QVariantMaps converting correctly under PyQt6 builds

### CODE REVIEW

**Comment by nyalldawson** [comment]
@troopa81 mind looking over this one?

**Review by troopa81 — COMMENTED** [review]
Could we just renamed `QVector<QVariantMap>` into `QList<QMap<QVariant>>` during sipify ?

I remember doing this at some point and that it was working, but I don't remember why I didn't keep it though...

This way it allows us to avoid the mappedtype in conversion.sip and rely on the one shipped by qpycore_qlist.sip

**Comment by nyalldawson** [comment]
> Could we just renamed QVector<QVariantMap> into QList<QMap<QVariant>> during sipify ?

Nope, that doesn't work (on SIP version 6.7.12, PyQt6 version 6.6.1) - it results in `sip-build: argument 2 of ctor 'QgsProfileIdentifyResults' has an unsupported type for a Python signature - provide a valid type, %MethodCode and a C++ signature
`

Removing the conversion code results in weird errors, like 
```
/usr/lib64/python3.12/site-packages/PyQt6/bindings/QtCore/qpycore_qlist.sip: In function ‘int convertTo_QList_0600QMap_0100QString_0100QVariant(PyObject*, void**, int*, PyObject*, void**)’:
/usr/lib64/python3.12/site-packages/PyQt6/bindings/QtCore/qpycore_qlist.sip:420: error: cannot convert ‘QList<std::pair<QString, QVariant> >*’ to ‘QList<QMap<QString, QVariant> >*’ in assignment
  420 |     *sipCppPtr = ql;
```

**Review by troopa81 — APPROVED** [review]

**Comment by troopa81** [comment]
> Nope, that doesn't work (on SIP version 6.7.12, PyQt6 version 6.6.1) -

OK, my bad. Let's proceed this way then.

**Comment by nyalldawson** [comment]
@troopa81 I'm curious if you have any thoughts / plans for handling QVariant::Type. I tried a few approaches to sip conversion code for QVariant::Type ↔️ QMetaType::Type , but sip won't apply the conversion when trying to call qgis functions with QVariant::Type arguments. 

So I'm wondering if we need to do something like add c++ methods for all the ones which use QVariant::Type and expose these only for Qt6 builds... (And then add python code to set eg QVariant.Int = QMetaType.Int)

**Comment by troopa81** [comment]
> @troopa81 I'm curious if you have any thoughts / plans for handling QVariant::Type. I tried a few approaches to sip conversion code for QVariant::Type ↔️ QMetaType::Type 

Yes, I my plan was to get rid of all QVariant::Type and try to make things work with conversions.sip. If it doesn't work, maybe use sipify to generate a wrapper method that does the conversion. But I didn't try anything yet.

> So I'm wondering if we need to do something like add c++ methods for all the ones which use QVariant::Type and expose these only for Qt6 builds... (And then add python code to set eg QVariant.Int = QMetaType.Int)

Ouch, if we have to go that way, that would be painful

**Pull request merged**
