### PR TITLE
Fix 'Move selected to top' breaks attribute table sorting

### PR DESCRIPTION
**Pull request by benwirf**
## Description

Recently I noticed that toggling the 'Move selected to top' action in the attribute table dialog, breaks any existing sort column and sort order; the sorting is always reset to ascending on the first column.

Looking at the code, it seems that the sort column and order was hard-coded to 0 and `Qt::AscendingOrder` respectively. The existing sort column and order is retrieved but not used:

Screenshot from 2024-09-29 16-56-50

Unless I'm missing something, shouldn't we be passing the `column` and `order` values to the `sort()` call?

Screencast before:

selected-to-top-bug-1

Screencast after proposed fix:

selected-to-top-bug-2

### CODE REVIEW

**Comment by nyalldawson** [comment]
Good catch! Looking through the git history, it seemed a bunch of cleanups have happened to this function over time which resulted in the current bug. 

Would you be able to extend the tests in TestQgsAttributeTable::testSelectedOnTop() to cover this fix too?

**Comment by benwirf** [comment]
No worries @nyalldawson, can do. I will have look after work.

**Comment by benwirf** [comment]
Tests added. I _think_ this is enough to adequately test the bug fix, but it's been a long day so hopefully I haven't made any blunders in checking the feature orders!

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Great work, thanks @benwirf !

**Comment by benwirf** [comment]
Thanks @nyalldawson! :-)

**Pull request merged**
