### PR TITLE
fix 3D directional light ui

### PR DESCRIPTION
**Pull request by vcloarec**
altitude was always applied with value of zero

### CODE REVIEW

**Comment by nyalldawson** [comment]
Do you think we should block altitudes <0 here? I've tried and can't obtain any usable results with upward angled lights, so I think they'll just lead to user confusion...

**Comment by vcloarec** [comment]
> Do you think we should block altitudes <0 here?

I had think about, but preferred let's negative value possible to allow user to have upward lights if he wants. I do not have strong opinion on this...

**Comment by nyalldawson** [comment]
What I mean is that upward lights don't seem to work in any way. They always result in a dark scene.

**Comment by vcloarec** [comment]
yes, true, except with vertical or quasi vertical triangles. Let's remove negative altitude values!

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
