### PR TITLE
fix msvc build

### PR DESCRIPTION
**Pull request by jef-n**

### CODE REVIEW

**Comment by rouault** [comment]
CC @wonder-sk : looks like those changes need to be upstreamed to https://github.com/PDAL/wrench

**Comment by jef-n** [comment]
> CC @wonder-sk : looks like those changes need to be upstreamed to https://github.com/PDAL/wrench

same for fd05823cfd8d0dab874ee265a9185d86da3447a7

**Review by wonder-sk — APPROVED** [review]
Thanks!

**Comment by wonder-sk** [comment]
I have upstreamed both #52348 and #52385 - thanks for notifying me!

**Pull request merged**
