### PR TITLE
sipify analysis raster

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by nirvn** [comment]
@3nids , you are on fire! Lovely to see the blacklist file melting away.

**Comment by 3nids** [comment]
should be done by the end of the day :)

**Comment by m-kuhn** [comment]
Are you bored with the presentations? ;)

**Comment by 3nids** [comment]
perl and sip are clearer to me than German...and I'm serious!

Le mer. 21 juin 2017 à 10:31, Matthias Kuhn <notifications@github.com> a
écrit :

**Pull request merged**
