### PR TITLE
[processing] attempt to fix failing test

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
Attempt to fix failing Processing test

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Awesome, thanks @alexbruy 🎉

**Comment by luipir** [comment]
Happy for the fix, but I should notice that running ProcessingToolTest locally fail for me (previously was fine)... 
ogr layer index seems works differently depending on something probably depending on gdal version? mine is 2.2.1 installed as packeg in ubuntu 16.04 (xenial... the same dist of travis)

2: Traceback (most recent call last):
2:   File "/home/ginetto/PROGRAMMING/QGIS/QGIS-2.18/python/plugins/processing/tests/ToolsTest.py", line 69, in testOgrLayerNameExtraction
2:     self.assertEqual(name, 'b')
2: AssertionError: 'a' != 'b'

**Comment by rouault** [comment]
Hum, is my understanding that GetLayerByIndex() is called on a OGR datasource that is a CSV directory ? (the same would hold for a directory of shapefiles) If so, it is super unreliable since it depends on the order into which the readdir() system call will return files. Getting layer by names should be used for that

**Comment by alexbruy** [comment]
IMHO, original author of the test should take a look and fix it in a more robust way or remove it to avoid failures in future.

**Comment by luipir** [comment]
AFAIU the test would check exactly the reliability of GetLayerByIndex call :/

**Comment by m-kuhn** [comment]
Totally agree, see https://github.com/qgis/QGIS/commit/9c4d1da4274a5266509f9a91d5c4fedf2b40be98#commitcomment-24245243

**Comment by m-kuhn** [comment]
CC @strk

**Pull request merged**
