### PR TITLE
QgsFields::fieldNameIndex also matches field alias

### PR DESCRIPTION
**Pull request by m-kuhn**
This method is also doing case insensitive "fuzzy" matching now, this
just adds yet another level of tolerance.
This changes the expressions to also take the alias into account if no
matches have been found.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Accepting aliases in expressions has been [discussed in the past](https://lists.osgeo.org/pipermail/qgis-developer/2014-September/034551.html) and mentioned as a [source of confusion](https://lists.osgeo.org/pipermail/qgis-developer/2016-August/044353.html). Just today I had to solve an "issue" caused by using an alias instead of the field name in an expression.

The only question is if we need a parameter (or a separate function) for this.
I think that two methods are enough:

 * indexFromName: If the precise name is known and performance is key
 * fieldNameIndex: If QGIS should try to find a field while being tolerant

(Note: I don't really like the two names but they are what's currently in use. Improvements welcome.)

**Comment by nyalldawson** [comment]
Looks good to me.

**Comment by wonder-sk** [comment]
One of the functions should really get renamed as their names look very similar, yet they do different things... How about something like "lookupField" for the one with extended functionality?

**Comment by m-kuhn** [comment]
Sounds good.

I have also removed `QgsVectorLayer::fieldNameIndex()` because it no longer matches the signature. Not sure if for simplicity of API we should reintroduce lookupField() and indexFromName() on QgsVectorLayer as well.

**Comment by wonder-sk** [comment]
Cool thanks!

**Comment by m-kuhn** [comment]
And while at it, why not moving QgsFields to qgsfields.h, longstanding plan on the bucketlist.

**Comment by m-kuhn** [comment]
I'm renaming also the following two methods:

* QgsVectorLayer::addAttributeAlias
* QgsVectorLayer::remAttributeAlias

@nyalldawson not sure I remember correctly, should the be called

* setAttributeAlias or setFieldAlias?
* removeAttributeAlias or removeFieldAlias?

**Comment by nyalldawson** [comment]
@m-kuhn Aren't we going "field" for something like this and only using attribute where it's the actual value of the field for a feature?

What do you think about removing the "removeAttributeAlias" method altogether, and instead setting an empty string to remove?

**Comment by m-kuhn** [comment]
That's what I had in mind as well. Will adjust to setFieldAlias.

Personally I don't mind having shorthands to keep the API as self-explanatory as possible and offering `removeFieldAlias()` sounds very intuitive to me.

**Comment by nyalldawson** [comment]
Bet you're glad to have that one merged and not have to deal with rebasing anymore!

**Pull request closed without merging**
