### PR TITLE
[FEATURE] added parameters to gps plugin to keep cursor still in static conditions

### PR DESCRIPTION
**Pull request by nyalldawson**
Supersedes https://github.com/qgis/QGIS/pull/5322

### CODE REVIEW

**Comment by jonnyforestGIS** [comment]
Hi @nyalldawson this is available in qgis-dev version for Windows? I can perform some tests of this new feature and give feedback. 

I have a Getac T800 with Win10 and an external GPS antenna in my work.
Regards,
João

**Comment by nyalldawson** [comment]
@jonnyforestGIS

Yes it's in the nightlies now

**Comment by jonnyforestGIS** [comment]
Hi @nyalldawson .
my test environment:
Tablet Getac T800
SO: Win10 Pro 64-bits

I test the GPS connection with the internal Port and a get this behavior:
** QGIS 3.3.0 master (rev d8b20e7441)**

- Auto-Detect - Connect but don't receive information
- Define the port of GPS (in my case COM2) - Failed Connection

**QGIS 3.2.1**
- Auto-Detect - Connect and receive information
- Define the port of GPS (in my case COM2) - Connect and receive information

**Comment by nyalldawson** [comment]
@jonnyforestGIS 

That's probably a result of https://github.com/qgis/QGIS/commit/212cffcab1c93f899b1acd81bda71f7d0fcd8ef8#diff-7442743cb7b7dadf7ba7bf808816ed60 

ping @jef-n

**Pull request merged**
