### PR TITLE
QgsCoordinateTransform: remove entries from cache when a thread exits (relates to #31762)

### PR DESCRIPTION
**Pull request by rouault**
The first commit comes from https://github.com/qgis/QGIS/pull/31848
This PR is for the second commit "QgsCoordinateTransform: remove entries from cache when a thread exits (relates to #31762)"

### CODE REVIEW

**Comment by nyalldawson** [comment]
@rouault any chance of a proj < 6 version too? I think given the severity of this issue it'd be justified...

**Comment by nirvn** [comment]
@rouault , great news, the crash is gone (on linux). I'll test on windows as soon as a nightly build is pushed which includes these fixes. I'm highly optimistic the crash on exit is a thing of the best. Yay!

**Comment by rouault** [comment]
> any chance of a proj < 6 version too? I think given the severity of this issue it'd be justified...

- The crasher fix is the first commit, and I've done PROJ < 6 and PROJ >= 6 code paths
- The second commit which is PROJ >= 6 doesn't fix crash, but a probably not so severe memory leak.

**Comment by nyalldawson** [comment]
Ok, fair enough! The sooner we make proj 6 a hard requirement the better anyway...

**Comment by nirvn** [comment]
Spent one day with a build containing this commit, nothing bad to report. Let's merge.

**Pull request merged**
