### PR TITLE
Project color follow ups

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes some bugs relating to use of project colors in symbols.

### CODE REVIEW

**Comment by nirvn** [comment]
Nice ones. Is the layout map item already refreshing its cache on project color change?

**Comment by nyalldawson** [comment]
No, good catch!

**Comment by nirvn** [comment]
This PR should be renamed to 'Making project colors a first class citizen' :wink:

**Comment by nyalldawson** [comment]
@nirvn fixed now

**Review by nirvn — APPROVED** [review]

**Pull request merged**
