### PR TITLE
show correct coordinates in status bar when projected CRS used and canvas units set to degrees (fix #12395)

### PR DESCRIPTION
**Pull request by alexbruy**
Seems toDegreesMinutesSeconds() method accepts only decimal degrees and fails when coordinates in meters (or other projected units). So we need to transform coordinates to geographic CRS before passing them to this method. Also it seems that this method misses handling of latitude ranges and corresponding wrapping

### CODE REVIEW

**Comment by nyalldawson** [comment]
@alexbruy the tests for QgsPoint::toDegreesMinutesSeconds() are pretty comprehensive - can you add tests for the latitude wrapping behaviour please?

**Comment by alexbruy** [comment]
Not sure if we really need wrapping for both coordinates, but current situation when longitude in DMS notation always limited to -180..180 range while latitude displayed "as is" is a bit confusing. Moreover, when one use decimal degrees both coordinates displayed "as is" and may have "wrong" value like (-245,-138).

Will add test now

**Comment by alexbruy** [comment]
Tests added

**Comment by nyalldawson** [comment]
manually merged in 803a0b9375217671fc625f3156533d693b5d1895 - thanks!

**Pull request closed without merging**
