### PR TITLE
[needs-docs] Move draw regular shape buttons to digitizing toolbar

### PR DESCRIPTION
**Pull request by DelazJ**
image

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
I'm not very hot to the idea of further crowding the basic editing toolbar with additional tools. I thought having a separate toolbar for these made sense, especially since those are polygon(and line?)- only tools.

**Comment by DelazJ** [comment]
Me neither am convinced by this proposal, given what it looks like. And while those are basic shapes, i'm not sure they are the ones we often produce in GIS. A dedicated toolbar makes sense to me. 
@lbartoletti @3nids ?

**Comment by lbartoletti** [comment]
It's a big toolbar. Maybe mov circular arc with the new draws tools? Moreover we have to add som new arc methods.
How do you feel with @3nids ?

**Comment by DelazJ** [comment]
News, here? I'm personally in favor of keeping 2 separate toolbars

**Comment by DelazJ** [comment]
Given the recent discussion on circular button placement I assume that keeping separate toolbars is the road we follow so i'm closing this one.

**Pull request closed without merging**
