### PR TITLE
 Don't reset mesh layer styling when changing data source for layer

### LINKED ISSUE #45391: Setting data source on a mesh layer resets the layer's style
### What is the bug or the crash?

When loading a project with a broken mesh layer data path, fixing this path results in the layer resetting to default style.

### Steps to reproduce the issue

1. load project with broken mesh layer path
2. fix path - style is lost

### Versions

all till 3.22

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
This breaks fixing mesh layer paths when restoring projects with
broken mesh layers -- fixing the path causes the existing style
to be lost.

Fixes #45391

### CODE REVIEW

**Comment by nyalldawson** [comment]
@vcloarec mind taking a look at this one?

**Review by PeterPetrik — APPROVED** [review]

**Comment by vcloarec** [comment]
give few time to look at.

**Comment by vcloarec** [comment]
@nyalldawson I have make some changes on a PR to your branch

**Comment by nyalldawson** [comment]
@vcloarec thanks! I've pulled in your changes now

**Review by vcloarec — APPROVED** [review]

**Pull request merged**
