### PR TITLE
Resurrect ability to run processing models

### PR DESCRIPTION
**Pull request by nyalldawson**
Brings back the ability to execute processing models

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , when adding a vector layer input in a new model, I get the following error:

```
TypeError: unorderable types: dict() > int() 
Traceback (most recent call last):
  File "/home/webmaster/apps/share/qgis/python/plugins/processing/modeler/ModelerDialog.py", line 503, in addInput
    self.addInputOfType(paramType)
  File "/home/webmaster/apps/share/qgis/python/plugins/processing/modeler/ModelerDialog.py", line 511, in addInputOfType
    pos = self.getPositionForParameterItem()
  File "/home/webmaster/apps/share/qgis/python/plugins/processing/modeler/ModelerDialog.py", line 525, in getPositionForParameterItem
    if len(self.model.parameterComponents() > 0):
TypeError: unorderable types: dict() > int()
```

**Comment by nyalldawson** [comment]
@nirvn thanks, fixed in https://github.com/qgis/QGIS/commit/df07772a5680306ecdd62a52451bd7aef520a5d5

**Comment by nirvn** [comment]
@nyalldawson , nice.

One more issue spotted: named output is broken:
screenshot from 2017-06-22 10-44-22

When naming an output and clicking on [ ok ], the output name is lost (see screenshot above showing a nameless output box).

**Comment by nirvn** [comment]
Also, if you right click on a pre-existing model to edit it, I get thrown an error trying to edit an algorithm:

```
RuntimeError: wrapped C/C++ object of type ModelerAlgorithm has been deleted 
Traceback (most recent call last):
  File "/home/webmaster/apps/share/qgis/python/plugins/processing/modeler/ModelerGraphicItem.py", line 160, in mouseDoubleClickEvent
    self.editElement()
  File "/home/webmaster/apps/share/qgis/python/plugins/processing/modeler/ModelerGraphicItem.py", line 209, in editElement
    dlg = ModelerParametersDialog(self.element.algorithm(), self.model, self.element.childId())
  File "/home/webmaster/apps/share/qgis/python/plugins/processing/modeler/ModelerParametersDialog.py", line 69, in __init__
    self.setupUi()
  File "/home/webmaster/apps/share/qgis/python/plugins/processing/modeler/ModelerParametersDialog.py", line 132, in setupUi
    wrapper = WidgetWrapperFactory.create_wrapper(param, self)
  File "/home/webmaster/apps/share/qgis/python/plugins/processing/gui/wrappers.py", line 1260, in create_wrapper
    return WidgetWrapperFactory.create_wrapper_from_class(param, dialog, row, col)
  File "/home/webmaster/apps/share/qgis/python/plugins/processing/gui/wrappers.py", line 1314, in create_wrapper_from_class
    return wrapper(param, dialog, row, col)
  File "/home/webmaster/apps/share/qgis/python/plugins/processing/gui/wrappers.py", line 154, in __init__
    self.widget = self.createWidget(**kwargs)
  File "/home/webmaster/apps/share/qgis/python/plugins/processing/gui/wrappers.py", line 820, in createWidget
    layers = self.dialog.getAvailableValuesOfType(QgsProcessingParameterFeatureSource, QgsProcessingOutputVectorLayer)
  File "/home/webmaster/apps/share/qgis/python/plugins/processing/modeler/ModelerParametersDialog.py", line 231, in getAvailableValuesOfType
    inputs = self.model.parameterComponents()
RuntimeError: wrapped C/C++ object of type ModelerAlgorithm has been deleted
```

*Steps to reproduce*
# Right click on a pre-existing model and click on the Edit model menu item
# Immediately save the model your editing (via the "save model" toolbar button)
# Double-click on an algorithm box to edit its parameter
# You'll get an error thrown at you, with the above-pasted stack

**Comment by nyalldawson** [comment]
> When naming an output and clicking on [ ok ], the output name is lost (see screenshot above showing a nameless output box).

@nirvn fixed in 24eb6fd

**Comment by nirvn** [comment]
@nyalldawson , indeed, output name fixed:
screenshot from 2017-06-23 11-30-53

I'm still seeing the `ModelerAlgorithm has been deleted` error after saving a model. Assuming your on top of that 😉

**Pull request merged**
