### PR TITLE
Fix crash when opening project properties

### PR DESCRIPTION
**Pull request by elpaso**
crashed only in debug mode because of checkPageWidgetNameMap

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
Backport?

**Comment by elpaso** [comment]
> Backport?

Not sure: when was  "Terrain" added?

**Comment by uclaros** [comment]
> Not sure: when was "Terrain" added?

This is 3.26 only

**Comment by elpaso** [comment]
unrelated test failure

**Pull request merged**
