### PR TITLE
[travis] Enable server tests

### PR DESCRIPTION
**Pull request by m-kuhn**
## Description

Server tests on travis have accidentally been disabled. This PR re-enables them.

### CODE REVIEW

**Comment by pblottiere** [comment]
@m-kuhn  Argh, there's some masks to update... How do you want to proceed? I can handle it next week if you want.

**Comment by m-kuhn** [comment]
My plan is to fix the easiest ones in here.
Proceed to merge as soon as possible to lock these in and then gradually re-enable whatever is missing. Any help with this will be greatly appreciated.

**Comment by m-kuhn** [comment]
So part 1 is done, apparently no big issues (phew).

@pblottiere have a look at the blacklist file, it points towards a failed job for WMS. FYI, you can also run the very same setup locally using docker-compose, might help to update images. Have a look at the .travis.yml file

@elpaso it's only the pg tests that are missing now, right? which packages do you need for this (postgresql-server, postgis as well...?) @3nids can you shortly help here how to integrate additional dependencies like this into the docker container in which the tests are running?

**Comment by 3nids** [comment]
Any new dependency should be added to https://github.com/qgis/QGIS/blob/master/.docker/Dockerfile. 
If we are in a PR, the image will be rebuilt on every Travis build. 
If on a branch on the upstream repo, the image will be pushed at each build (even if qgis fails to build) and hence will be reused. 
Si I would recommend working on a branch if Travis takes too much time, but it should be more than 5 minutes to rebuild the image. 
As a note, we're strictly speaking about the dependency container image here.

**Comment by elpaso** [comment]
I tried to add postgis and postgresql but the build fails with an unrelated error: https://travis-ci.org/qgis/QGIS/jobs/298396130#L5371
I'm now trying to build the docker deps locally for an easier debug but any help would be appreciated.

**Pull request merged**
