### PR TITLE
[argis provider] avoid afs crasher (fixes #17513)

### PR DESCRIPTION
**Pull request by nirvn**
## Description
@manisandro , this PR attempts to fix a crasher with the arcgis provider. I doubt I'm fixing this properly, I simply avoid hitting Q_ASSERT, which might have been there for a reason to begin with.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
@manisandro , the crasher I refer to is here: https://issues.qgis.org/issues/17513

**Comment by manisandro** [comment]
@nirvn I'll have a look, thanks

**Comment by nirvn** [comment]
@manisandro, thanks -- I've also noticed that upon refreshing a AFS layer's table attribute (using the table attribute's refresh button), I don't get all features all the time, and sometimes duplicates features are added twice (i.e. two rows).

**Comment by manisandro** [comment]
#5692

**Pull request closed without merging**
