### PR TITLE
[Processing] Three small fixes

### PR DESCRIPTION
**Pull request by radosuav**
1. Fixes the issue introduced in c58981fd5ede0c66dc0b4d9eb8f757126166374e when setting subset from canvas extent.
2. Use the default value of ParameterBoolean to set the initial Yes/No value in the drop down list in modeler parameter's dialog.
3. Allow providers to set the supported output raster and vector file extensions and use the default values if the provider doesn't have it's own selection. This was the behavior in previous versions of Processing but got changed somewhere along the way.

### CODE REVIEW

**Comment by volaya** [comment]
I like the fixes, thanks for them.

However, the idea of allowing providers to set the supported extension for the filter is not correct. It was wrong before, and that got changed to make it right. The thing is that the user should have all options in the file dialog. If the provider can only generate a given output file (that's what should be declaring in the correspodning function), Processing or the provider should convert it to a supported one.

the getFilter function could actually removed, it's just left there to avoid having to change the code that called it, but it should return the same list of extensions for a given output type (raster, vector...) no matter which provider is generating it.

**Comment by radosuav** [comment]
Hi and thanks for having a look. As I understand, the reason for limiting all the providers to the same supported extensions is to make it easier to combine algorithms from different providers in models and also to hide provider specific details from users (especially novice ones). I agree that this is the correct behavior for providers which come with Processing plugin out of the box (e.g. GRASS or OTB). 

However, this can be limiting for external providers. For example the "Processing BEAM and S1 Toolbox" plugin (which acts as a link between QGIS Processing and software for analyzing ESA satellite data) supports some formats which are not supported by Processing/GDAL and in some cases needs the output of one algorithm to be saved in a specific non-GDAL format (e.g. BEAM-DIMAP) to be used as input for the next algorithm. There might be similar cases with other providers that I am not aware of. 

I think that since those providers have to be installed as separate plugins their users can be considered more advanced and thus able to understand the reasons for having a non-standard extension. It is also then up to the plugin creators to explain those limitations to the users (e.g. see towards the bottom of this readme: https://github.com/TIGER-NET/Processing-GPF/blob/master/README.md)

**Comment by volaya** [comment]
If the algorithm generates a file format that is not supported by GDAL, then it will not be loaded into the QGIS project. Why not using a OutputFile type instead

If you declare it as OutputRaster, any algorithm that takes a raster should be able to use it...but it is not the case, which is confusing. I agree that we can warn users and expect them to use this correctly...but in my experience people dont read those warnings and instructions, and they will see a behaviour of Processing that doesn't make sense and fails, which is something to avoid.

In any case, you can edit the PR to remove that part, and I can merge the rest. And we continue discussing this change.

Thanks for your help and nice ediscussion!

**Comment by volaya** [comment]
As a quick suggestion for your case, you can override the function that returns the file filter in the Output Raster object (in your object instance I mean, not in the OutputRaster class), so it returns more files. That would cause that "peculiar" behaviour of your provider (even if not really correct and could casue confusion...), but there would be no need to modify the rest of the code (with your proposed change, we would have to change providers and other parts of the code)

**Comment by radosuav** [comment]
Should be ready to merge now. 

I'll try to address the behavior in the provider code. Thanks for the hint!

**Pull request merged**
