### PR TITLE
Add QgsDataProvider::ProviderOptions struct to data provider constructors 

### PR DESCRIPTION
**Pull request by nyalldawson**
This allows a way to pass generic settings to providers, e.g. passing a datum transform context for use in provider's constructors.

The current driver is to provide a way for map layers to set their data provider's transform context when constructing. This opens the way for map layers to be constructed with the correct transform context handling during the layer/data provider construction stage. This context isn't actually used by any providers (yet), nor is it correctly set for new layers (yet)... but this is a pre-requisite to correctly handling this.

But it also makes the api a bit more future proof, because the provider options struct can have additional members added at a later stage without breaking API. 

(It's important to land this before https://github.com/qgis/QGIS/pull/7012, which causes more of this API becomes locked into the frozen PyQGIS API.)

This relates to the discussion in https://github.com/qgis/QGIS/pull/6681, but does not replace that PR (which also concerns a method for updating the transform context for an existing layer/data provider)

### CODE REVIEW

**Review by elpaso — APPROVED** [review]
LGTM

**Comment by wonder-sk** [comment]
In principle I agree with the changes, my main concern is how do we later propagate changes to coordinate transform from project to data providers? I think we either need to pass the context wrapped in a QObject that would emit a signal when the context changes, or to have a setter in QgsDataProvider like Matthias suggested in #6681

**Comment by nyalldawson** [comment]
@wonder-sk yes this needs to go alongside the changes discussed in #6681, but they are both required (this one to allow use of the context within provider constructors, #6681 to allow updates to the context).

But this one needs to land before #7012, or we'll be blocked by the API contract. #6681 can be done safely at a later stage.

**Comment by wonder-sk** [comment]
What I meant is that if LayerOptions and ProviderOptions already contain QgsCoordinateTransformContext object, this sets the API contract and we won't be able to change the contents later to e.g. QPointer<QgsCoordinateTransformController> if we wanted to go that way. So if we are unsure yet about how we deal with the transform contexts, I would leave out the QgsCoordinateTransformContext from LayerOptions and ProviderOptions to keep this PR focused on the layer/provider constructor updates... But I do not have hard feelings about the current approach so feel free to merge.

**Comment by nyalldawson** [comment]
Ok, I'll drop the transform context members and just leave the empty structs. (The contexts aren't populated yet anyway)

**Pull request merged**
