### PR TITLE
Use proper typographic ellipsis "…" instead of "..."

### PR DESCRIPTION
**Pull request by nyalldawson**
Because: Attention to detail!!1!

### CODE REVIEW

**Comment by DelazJ** [comment]
You really did it :)
That said, unless you do the same thing for translated texts (and that I missed those files), I'm afraid you're breaking translation and it wouldn't worth the effort imho.

**Comment by nyalldawson** [comment]
What would be the correct approach to update the translations?

**Comment by luzpaz** [comment]
Do you also want all the commented code that have an elipsis to be changed as well?

**Comment by nyalldawson** [comment]
> Do you also want all the commented code that have an elipsis to be changed as well?

I figure "why not?". It makes it easier to search for any newly introduced "..." strings.

**Comment by m-kuhn** [comment]
> What would be the correct approach to update the translations?

Maybe like this?

```
tx pull
sed -i 's/\.\.\./…/g' i18n/*.ts
tx push -t
```

**Comment by nyalldawson** [comment]
Closing for now. Maybe we can revisit at a later stage.

**Pull request closed without merging**
