### PR TITLE
Add a classified 2d renderer for point clouds 

### PR DESCRIPTION
**Pull request by nyalldawson**
Allows styling 2d renders of point clouds by a classified attribute

Includes support for interactively switching between visible classes

Peek 2020-12-03 10-54

### CODE REVIEW

**Comment by nyalldawson** [comment]
@NEDJIMAbelgacem I've tried to keep this as re-usable as possible for a 3d renderer equivalent -- basically if you reuse QgsPointCloudCategory and the model from the renderer widget then the actual 3d specific widget component should be quite small

**Review by PeterPetrik — APPROVED** [review]
good stuff!

**Comment by NathanW2** [comment]
HOT DAMN!

**Comment by NEDJIMAbelgacem** [comment]
> @NEDJIMAbelgacem I've tried to keep this as re-usable as possible for a 3d renderer equivalent -- basically if you reuse QgsPointCloudCategory and the model from the renderer widget then the actual 3d specific widget component should be quite small

That's great!
I will try to get the other pull request merged and then split the color ramp rendering to graduated and categorized rendering as Martin suggested before.
I have some master's final year project work to do today and was in a trip all day the day before :'( Will try to get it merged ASAP

**Comment by nirvn** [comment]
@NEDJIMAbelgacem , tss tss tss, priorities. QGIS > master's final year... 😉

**Comment by NEDJIMAbelgacem** [comment]
> @NEDJIMAbelgacem , tss tss tss, priorities. QGIS > master's final year...

Haha my priorities are like that but I will get into troubles if I don't get something done on that final year side today :)

**Pull request merged**
