### PR TITLE
For discussion: bump minimum qt to 5.15

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR is a proposal to bump the minimum Qt version to 5.15. (The predominant motivation here is to simplify things and remove a bunch of dead code in order to aid the move to Qt 6.)

### CODE REVIEW

**Comment by m-kuhn** [comment]
I support the motivation behind this.
In qfield we've hit a bug introduced in 5.15 which prevents us from upgrading without breaking important functionality. I'd want to look into that when migrating to Qt 6 because there will be no more OS 5.15 releases. For this it would be great if we have qt6 passing all (core) tests by the time 5.14 is phased out here.

**Comment by uclaros** [comment]
Ubuntu 20.04lts is still on 5.12 and according to analytics.qgis.org it's the second most popular os. Should that play a role in this decision or is it time for a new second most popular os?

**Comment by nyalldawson** [comment]
@uclaros

It's a fair point, but 20.04 users can still use the 3.22 ltr release, and it's still supported. I say it's perfectly acceptable to require a user of an old ltr distro to use an ltr QGIS release.

**Comment by agiudiceandrea** [comment]
> Ubuntu 20.04lts is still on 5.12

@uclaros, the current minimum Qt version is 5.13 in master (https://github.com/qgis/QGIS/commit/4b8121990fb49373f2d91ed7853dc2a07a62ac3b), so QGIS 3.22 and 3.26 will be the last versions available in any case for Ubuntu 20.04 (https://github.com/qgis/QGIS-Website/commit/70b892272c194e6f37bc97108b0c70bf54b3dde9).

**Comment by uclaros** [comment]
@agiudiceandrea Since the 5.13 bump was merged there's no reason not to also bump to 5.15

Ubuntu 20.04 users will have to upgrade to the latest ltr on 2023 if they also want the latest qgis ltr

**Comment by wonder-sk** [comment]
It makes sense to me to bump the minimum version all the way to Qt 5.15 and not stick to Qt 5.13. The 5.15 release has been around for 2+ years now...

**Comment by nyalldawson** [comment]
Superseded by https://github.com/qgis/QGIS/pull/49994

**Pull request closed without merging**
