### PR TITLE
Enable WFS test and libSegFault

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by luipir** [comment]
+10000

**Comment by m-kuhn** [comment]
That should give some first hints
https://travis-ci.org/qgis/QGIS/builds/176419495#L1441-L1452

**Comment by elpaso** [comment]
@m-kuhn I cannot reproduce the issue locally. Can you?
The stacktrace doesn't seem related with the offline editing, if I underdstand that, it seems related with OGR provider or GDAL, but I guess that the memory corruption could be happened way before entering those libs. 
I don't really know how to debug that.

**Comment by rouault** [comment]
Smells a bit like https://hub.qgis.org/issues/15769 although not completely sure

In the stacktrace I also see /home/travis/virtualenv/python3.3.5/lib/python3.3/lib-dynload/atexit.cpython-33m.so(+0x1210)[0x7fdfdaae7210], so it seems that this is code run at process termination. Might potentially be a conflict between QGIS code doing OGR actions whereas the GDAL atexit handler has already run (see https://github.com/OSGeo/gdal/blob/trunk/gdal/gcore/gdaldllmain.cpp#L116.) I dislike this GDAL cleanup meachnism which cause various issues. You could test if it is related to that by defining GDAL_DESTROY=NO in the environment.

**Comment by m-kuhn** [comment]
just an assumption without even having looked at the code...

there's an ogr layer, created and owned by python. exitqgis was run already and the garbage collector kicks in at python cleanup...

are there layers which could be transferred to the registry or forced to be garbage collected before?

On November 16, 2016 6:17:45 PM GMT+01:00, Even Rouault <notifications@github.com> wrote:
>Smells a bit like https://hub.qgis.org/issues/15769 although not
>completely sure
>
>In the stacktrace I also see
>/home/travis/virtualenv/python3.3.5/lib/python3.3/lib-dynload/atexit.cpython-33m.so(+0x1210)[0x7fdfdaae7210],
>so it seems that this is code run at process termination. Might
>potentially be a conflict between QGIS code doing OGR actions whereas
>the GDAL atexit handler has already run (see
>https://github.com/OSGeo/gdal/blob/trunk/gdal/gcore/gdaldllmain.cpp#L116.)
>I dislike this GDAL cleanup meachnism which cause various issues. You
>could test if it is related to that by defining GDAL_DESTROY=NO in the
>environment.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/qgis/QGIS/pull/3774#issuecomment-261009826

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by elpaso** [comment]
@m-kuhn can you update this PR and try what @rouault suggested?

**Comment by m-kuhn** [comment]
I can do that.
I'm not sure if it's a good thing to enable this option since it will only fight symptoms and mask real issues. I.e. unclean shutdown of the app (crash on exit) for some reasons will no longer be reported.

Have you read my last comment? Any idea concerning that.

**Comment by elpaso** [comment]
@m-kuhn I was not saying to enable the GDAL_DESTROY=NO permanently, just the time to see if it has any effect.
I've had a quick look at the tests code, and I don't see any layer attached to the class or to the test instance, the layers should be created and destroyed at the beginning and at the end of each test (at least that what my intention), so they should be garbage collected on every `tearDown` as soon as they go out of scope. 
Of course I'd appreciate another pair of eyballs that could spot up my mistakes.

**Comment by m-kuhn** [comment]
So, from what I can tell.

For some reason `GDAL_DESTROY=NO` didn't change anything (see https://travis-ci.org/qgis/QGIS/builds/176630433)

Handing ownership of layers to C++ lets another crash appear in place of this one (see https://travis-ci.org/qgis/QGIS/builds/176627601).
I could reproduce this locally. Backtrace:
```
#0  0x00007fffec30287d in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () at /lib64/libQt5Core.so.5
#1  0x00007fffb3429fd0 in QDBusConnectionPrivate::closeConnection() () at /lib64/libQt5DBus.so.5
#2  0x00007fffb34168c2 in QDBusConnectionManager::run() () at /lib64/libQt5DBus.so.5
#3  0x00007fffec138a1a in QThreadPrivate::start(void*) () at /lib64/libQt5Core.so.5
#4  0x00007ffff76f36ca in start_thread () at /lib64/libpthread.so.0
#5  0x00007ffff6d1df6f in clone () at /lib64/libc.so.6
```

This looks like https://bugs.kde.org/show_bug.cgi?id=276214 which should be gone with Qt 5.7 which is currently blocked in https://github.com/qgis/QGIS/pull/3400. This all looks too weird to be true.

At list the libSegFault patch could be merged back.

**Comment by nyalldawson** [comment]
> This looks like a Qt/PyQt bug which should be gone with Qt 5.7 which is currently blocked in #3400. This all looks too weird to be true.

I hit that bug under Fedora 24. Was waiting a couple of weeks for 25 when I can finally kick Qt 5.6 to the kerb (where it belongs)...

**Comment by m-kuhn** [comment]
Argh, don't tell me... I have reproduced that under Fedora 25 with Qt 5.7. So it's NOT gone... Silly me.

**Comment by m-kuhn** [comment]
@elpaso what do you think we should do?

Merge 3796de0 and hope for this to be fixed in Qt 5.8?

**Comment by elpaso** [comment]
@m-kuhn  3796de0 also segfaults, right? 

Are you proposing to merge it and leave the test disabled?
I'm not sure that it's a good idea, unless we decide to enforce the use of a vector layer parented to the registry.
In other words, if you think that the usage of the vector layer in the test is not correct without the registry, then merge it, if not, it's better to leave the test as it is because it could help us to reproduce the problem.

BTW It could be useful if we could reproduce the segfault in another test on vector layers, without the offline stuff.

My concern is that if we ignore this bug it will bite us again in unpredictable ways.

I'm sorry I cannot help more in debugging this :(

**Comment by m-kuhn** [comment]
As far as I understand the problem so far (ignoring the additional segfault):

* ogr datasources are destroyed when no longer used
* layers keep references to providers and datasources
* as a consequence of the above two, with the last layer being destroyed, the last ogr datasource is released
* QgsApplication::exitQgis cleans up gdal/ogr
* deleting a layer after exitQgis causes segfaults
* qgis cleanup (which calls gdal cleanup) is registered with the python atexit handler
* layers which are owned by python get destroyed when python feels like collecting garbage

What we can do is:

* Hand over layer management to C++ (that's what this PR does)
* Automatically track layers (even if not added to the registry) and destroy them at the right point in time. This feels like duplicating the registry.
* Have `QgsGdalLibrary` object as member of `QgsApplication` that initializes and cleans up gdal/ogr and has a flag to determine if it's still available. Guard calls to ogr with a check for this flag.
* ... your idea?

**Comment by elpaso** [comment]
Do you think that this problem is specific to this particular test or is it something that could happen inside a QGIS plugin (or a standalone PyQGIS app)?

This test is tricky becuse the offline editing must in some way simulate different (in time) user sessions, I could keep references to the various layers used in the test, to prevent garbage collection, I'm not sure about how the WFS cache would play in this case though.

I'm also not sure that I understand completely the implications of the last solution you propose, but it seems like a nice way to solve the problem: delegate resource cleanup to the application exit handler, or do you feel that this will "leak" memory allocated for unused resources?

**Comment by m-kuhn** [comment]
In a standalone app, yes (that's what the test is).
In a plugin... Not sure, the python environment is probably cleaned up in a controlled way before QGIS is cleaned up (and if not it can likely be fixed).

> I could keep references to the various layers used in the test, to prevent garbage collection

They should be garbage collected, not prevented from being ;)

Not sure about number 3, I'd like to hear @rouault opinion first.

**Comment by m-kuhn** [comment]
@elpaso can you run the test with this patch on your system? Just to see if you get the same result and can reproduce the new segfault.

**Comment by elpaso** [comment]
@m-kuhn sure, do I need any particular cmake config to reproduce it?

**Comment by rouault** [comment]
> Have QgsGdalLibrary object as member of QgsApplication that initializes and cleans up gdal/ogr and has a flag to determine if it's still available. Guard calls to ogr with a check for this flag.

Sounds reasonable. I guess that would mean exiting early in QgsOgrProvider::~QgsOgrProvider()

(I'm still concerned about the order in which destructors might run. Imagine that libgdal.so is unloaded first, then the GDALDestroy() destructor function is called which cleanups any remaining datasource. If Python garbage collecting of remaining QgsVectorLayer happens now (that is before QGIS unloading), then we'll have the same issue. But GDAL_DESTROY=NO could be used to pervent that, if that ever happens. Yuck)

**Comment by m-kuhn** [comment]
> I guess that would mean exiting early in QgsOgrProvider::~QgsOgrProvider()

probably, yes

> Imagine that libgdal.so is unloaded first

Is there a risk that python will unload libraries before garbage collecting any leftover references or calling the atexit handler? I assumed this order of destruction - but without any evidence at all.

We could also set `GDAL_DESTROY=NO` and call `GDALDestroy()` in `QgsApplication::exitQgis()` if that helps to control the point in time?

**Comment by m-kuhn** [comment]
> @m-kuhn sure, do I need any particular cmake config to reproduce it?

No

**Comment by rouault** [comment]
> Is there a risk that python will unload libraries before garbage collecting any leftover references or calling the atexit handler? I assumed this order of destruction - but without any evidence at all.

My experience with GDAL alone is that the order of destruction doesn't seem to be logic. For example GDAL links against the HDF5 library, which itself has a destructor function. I've found sometimes that the HDF5 lib is unloaded before GDAL, which causes issue if the GDAL destructor has to close any remaining HDF5 dataset...

> We could also set GDAL_DESTROY=NO and call GDALDestroy() in QgsApplication::exitQgis() if that helps to control the point in time?
If GDALDestroy() is explicitly called, then GDAL_DESTROY=NO is not needed. GDALDestroy() is GDAL >= 2.0 only

**Comment by m-kuhn** [comment]
My thinking is, that if we manage to cleanup everything in a structured way, before the system starts to unload libraries, we should be on the safe side. And if the fix works only for GDAL 2.0 (which I would make a requirement for QGIS 3.0 anyway) it's totally worth it.

**Comment by elpaso** [comment]
@m-kuhn
```
0x0000000001252de0 in ?? ()
(gdb) bt
#0  0x0000000001252de0 in ?? ()
#1  0x00007fffc00b9b31 in QgsOgrProviderUtils::OGRDestroyWrapper (ogrDataSource=0x15447e0) at /home/ale/dev/QGIS/src/providers/ogr/qgsogrprovider.cpp:3138
#2  0x00007fffc00bcd21 in QgsOgrProvider::close (this=0x1487b30) at /home/ale/dev/QGIS/src/providers/ogr/qgsogrprovider.cpp:3615
#3  0x00007fffc00a225f in QgsOgrProvider::~QgsOgrProvider (this=0x1487b30, __in_chrg=<optimized out>)
    at /home/ale/dev/QGIS/src/providers/ogr/qgsogrprovider.cpp:439
#4  0x00007fffc00a234c in QgsOgrProvider::~QgsOgrProvider (this=0x1487b30, __in_chrg=<optimized out>)
    at /home/ale/dev/QGIS/src/providers/ogr/qgsogrprovider.cpp:440
#5  0x00007fffef84927f in QgsVectorLayer::~QgsVectorLayer (this=0x139a9f0, __in_chrg=<optimized out>) at /home/ale/dev/QGIS/src/core/qgsvectorlayer.cpp:178
#6  0x00007ffff108c9cc in sipQgsVectorLayer::~sipQgsVectorLayer (this=0x139a9f0, __in_chrg=<optimized out>)
    at /home/ale/dev/QGIS/qt5-build-local/python/core/sip_corepart2.cpp:102737
#7  0x00007ffff108ca08 in sipQgsVectorLayer::~sipQgsVectorLayer (this=0x139a9f0, __in_chrg=<optimized out>)
    at /home/ale/dev/QGIS/qt5-build-local/python/core/sip_corepart2.cpp:102740
#8  0x00007ffff527928b in QObjectPrivate::deleteChildren() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff5282b00 in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fffef6d5fd6 in QgsMapLayerRegistry::~QgsMapLayerRegistry (this=0x7ffff00a34c0 <QgsMapLayerRegistry::instance()::sInstance>, 
    __in_chrg=<optimized out>) at /home/ale/dev/QGIS/src/core/qgsmaplayerregistry.cpp:35
#11 0x00007ffff782aff8 in __run_exit_handlers (status=0, listp=0x7ffff7bb45f8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#12 0x00007ffff782b045 in __GI_exit (status=<optimized out>) at exit.c:104
#13 0x00000000005fef1f in Py_Exit ()
#14 0x00000000005ff00a in ?? ()
#15 0x00000000005ff076 in PyErr_PrintEx ()
#16 0x00000000005ffd39 in PyRun_SimpleFileExFlags ()
#17 0x000000000063f886 in Py_Main ()
#18 0x00000000004d00e1 in main ()

```

**Comment by m-kuhn** [comment]
Hrmpf, the QgsMapLayerRegistry is leaked anyway, that's why it's not working.

**Comment by elpaso** [comment]
@m-kuhn can we merge this so we don't loose coverage for the offline editing? 
BTW the destructor issue remains.

**Pull request merged**
