### PR TITLE
Add invalid geometry handling to QgsFeatureRequest/QgsVectorLayerFeatureIterator

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR copies the handling of invalid geometries from processing to QgsFeatureRequest/QgsVectorLayerFeatureIterator. It allows specifying the behaviour to follow when invalid geometries are encountered while iterating a layer.

An optional callback can be specified which is called when the iterator has been aborted as a result of encountering invalid geometries. I've used a callback here instead of a signal as I don't want to make QgsVectorLayerFeatureIterator a QObject.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Good and clean approach.

One thing I wonder is the callback, do you have a use-case in mind for this?

I ask because

 * it is (not yet) available in python (which is not a big deal after all you can also not specify the flag and manually check for validity in a script)
 * we won't be able to send this to the server

**Comment by nyalldawson** [comment]
> One thing I wonder is the callback, do you have a use-case in mind for this?

I need a way to detect that the iteration has aborted early due to an invalid geometry. I can't think of any other clean way to do this. I could possibly raise an exception, but that means that every bit of code iterating over features would need to catch this exception... Yuck.

It's going to be used by processing algorithms to trigger a user visible error message (c++ code).

**Comment by wonder-sk** [comment]
Maybe the callback could be done by having a simple interface - nested class in QgsFeatureRequest - with one pure virtual method as a callback. So who wants can implement that interface and pass such object to QgsFeatureRequest... this way the callack could be available also for pythonistas...?

**Comment by nyalldawson** [comment]
This: http://python.6.x6.nabble.com/Function-pointers-and-SIP-td1921924.html leads me to believe that it should be possible to expose the callback to python. Would that be acceptable?

**Comment by wonder-sk** [comment]
Sure that would be also possible, it would just need that extra %MethodCode implementation for SIP...

**Comment by m-kuhn** [comment]
Or there could be a status flag on the iterator (`Active`, `Closed`, `Aborted`)... That wouldn't require changes to the QgsFeatureRequest (with a slightly reduced functionality) or the feature iterator could be a QObject (but I don't really like this approach).

Anyway if you are going to write a %MethodCode generator for sipify / `std::function` , that's much appreciated :)

**Comment by nyalldawson** [comment]
> Hmm... the method should return reference to "our" feature request... but here the method creates a new instance of feature request...? Shouldn't we just do sipRes = sipCpp at the end?

Fixed, thanks

> Also, is it necessary to make a copy of QgsFeature for sipCallMethod? Can't we just pass &arg instead?

I tried this, but get a crash I can't resolve. It seems somewhere in the sipCallMethod internals the feature is deleted, so using a reference to the argument causes the feature to be incorrectly deleted.

**Comment by wonder-sk** [comment]
> It seems somewhere in the sipCallMethod internals the feature is deleted, so using a reference to the argument causes the feature to be incorrectly deleted.

I _think_ that's because the sipCallMethod call uses "N" specifier ("convert a new instance") instead of "D" specifier ("convert an instance") - see http://pyqt.sourceforge.net/Docs/sip4/c_api.html#c.sipBuildResult

**Comment by nyalldawson** [comment]
> I think that's because the sipCallMethod call uses "N" specifier ("convert a new instance") instead of "D" specifier ("convert an instance") - see http://pyqt.sourceforge.net/Docs/sip4/c_api.html#c.sipBuildResult

Thanks - that works. That'll teach me for copy and pasting code without fully understanding it !

**Comment by nyalldawson** [comment]
@wonder-sk good to merge now?

**Review by wonder-sk — APPROVED** [review]
Looks great - feel free to merge!

**Comment by nyalldawson** [comment]
Thanks!

**Comment by luipir** [comment]
make sense a:
QgsFeatureRequest::FixOnInvalid
and/or a callback that does not invalidate the iterator, e.g. trying to fix the geometry ?

**Comment by nyalldawson** [comment]
> make sense a:
QgsFeatureRequest::FixOnInvalid
and/or a callback that does not invalidate the iterator, e.g. trying to fix the geometry ?

sure - should be pretty trivial to add using QgsGeometry::makeValid...

**Comment by m-kuhn** [comment]
What do you think about using a feature pipeline for this?

Prepend algs to

* fix invalid features
* check and fail on invalid
* skip invalid
* fail on null
* skip null
* ...

This would create an "ad hoc submodel" for each layer based on its parameters. Using stock algs.

Theis would build on standard building blocks of processing (algs). Often used input algs can be added transparently based on params gor ease of use.

Main advantage is chainability (add multiple preprocessing steps) over a single callback fixup.

**Comment by luipir** [comment]
@m-kuhn exatly, I didn't want to over engineer, btw the idea was to embed in checkGeometry (or somewhere) a set of configurable "filter"/"checkers". I like your idea to have a combobox for predefined geometry checker. In this way the user is always able to control the behavior, but we can also set default behaviors for "not so skilled" users avoiding "strange" results in case of invalid geometries.

**Pull request merged**
