### PR TITLE
New bad layers icon for layers panel

### PR DESCRIPTION
**Pull request by SrNetoChan**
## Description
This changes the icon for bad layers in the Layers panel. Here's how it looks:

image

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by luipir** [comment]
IMHO better, but I leave the opinion to people more involved in UX

**Review by luipir — APPROVED** [review]

**Comment by nirvn** [comment]
+1, that was the vision for indicators.

**Comment by elpaso** [comment]
Thanks @SrNetoChan !

**Comment by nirvn** [comment]
Thinking about the layer icon for invalid layers, IMHO ideally it should reflect the layer type and use that default icon (ie raster, point, line, polygon icon). Beyond beautifying the look, it'd give a hint as to what type of data source needs linking).

**Comment by elpaso** [comment]
@nirvn that's not currently possible, because the geometry type of a bad layer is unknown, I must add some storage for the original type, it's on my TODO list.

**Pull request merged**
