### PR TITLE
add missing qt5 dependencies

### PR DESCRIPTION
**Pull request by tudorbarascu**
`undefined reference to `openpty'` fixed by installing `gnulib`
`sipAPI_core.h:11:17: fatal error: sip.h: No such file or directory`fixed
by installing `python3-sip-dev`

Actually, by installing `python3-sip-dev` the build doesn't hit any of the building errors.
So, `gnulib` is not a prerequisite although it may pop up to others.

@jef-n Thoughts?

### CODE REVIEW

**Comment by tudorbarascu** [comment]
Is this good to merge? I see that https://github.com/qgis/QGIS/commit/07c3801ee30ede9512ab7d399bee2a4bfce6ea34 and the follow-up commit are attending to the same thing (in the control files though).

**Comment by sbrunner** [comment]
+1 for me :-)

**Comment by m-kuhn** [comment]
@jef-n are these generated files?

**Comment by jef-n** [comment]
yes.  INSTALL and INSTALL.html are generated from the t2t files.  And the dependency lines in linux.t2t are updated by `scripts/scandeps.pl`

**Comment by m-kuhn** [comment]
@jef-n do you mind giving instructions to handle this pull request?

**Comment by jef-n** [comment]
@m-kuhn patience please.  The scripts would produce updates for distributions that don't have qca2 for qt5 (namely jessie and trusty).  Those should either go or qca2 should be added.  Hence I added qca2 to the experimenal repositories.   Now I just need to see if those work.   But the current nightly run won't pick those up as it's still busy with last night's updates in all four branches.   So I'll have to wait for the next one.

But of course this could be closed right away, but it can serve as reminder to run the scripts...

**Comment by m-kuhn** [comment]
Thanks for the detailed information.
Fine for me to keep it open as long as I know it's here on purpose and on your radar.

**Comment by jef-n** [comment]
superceeded by 52fc535c

**Pull request closed without merging**
