### PR TITLE
[processing] other gdal tests

### PR DESCRIPTION
**Pull request by ghtmtt**

### CODE REVIEW

**Comment by alexbruy** [comment]
It this a replacement for #3901?

**Comment by ghtmtt** [comment]
in a kind of a way yes. #3901 has some trouble with wrong gdal tests names and with the polygonize tool and the related gml output
so we can let that PR open for now just to let a trace of the gml output trouble
is that ok?

**Comment by alexbruy** [comment]
You can rebase, resolve conflicts and then force-push into the same branch. This way you don't need to create new PR when something changed during PR review.

I'm OK with having #3901 open if this helps.

**Comment by ghtmtt** [comment]
Yep, thanks Alex. I just meant to leave the PR for tracing other troubles in future. 
Thanks for merging!

**Pull request merged**
