### PR TITLE
new rampcolor called Qcolor

### PR DESCRIPTION
**Pull request by ambarja**
Hello everybody, I propose a new colour ramp called Qcolor with the colours of the QGIS logo.
Here is an example.
Qcolor
Captura de pantalla de 2022-02-21 22-39-57
Thanks

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nirvn thoughts?

**Comment by nirvn** [comment]
I'm not against the idea per say. But the ramp seems to visually "peak" in its middle part, not sure how usable the ramp would be on a day to day basis to do data visualization. You could always try to switch the orange and yellow part so it ends with yellow (which might be a better end color).

**Comment by ambarja** [comment]
Thank you very much for your time, this time I have tried to create a divergent ramp, where the yellow colour would be the central value, and at the extremes the strong colours like orange and green. Here is another example, where orange represents the high CO2 concentrations and yellow the intermediate values and green the low values.
co2

**Comment by nyalldawson** [comment]
@ambarja Like @nirvn, I do like the visual appearance of this ramp!

I think it's important to decide on the desired use of this ramp before proceeding further. If it's purely for artistic purposes then we have a different set of rules to follow vs if we intend this to be used for data visualisation purposes. Specifically, if it's designed as a data viz ramp then we have to be **extremely** careful about ensuring that the ramp isn't misleading and has a uniform variation in saturation/lightness throughout.

**Comment by ambarja** [comment]
My purpose is definitely more for data visualisation and of course I took into consideration the details of how to build a divergent ramp.
Maybe the colours are not popular as viridis or derivatives, but it was just an idea. :crying_cat_face:

**Comment by nyalldawson** [comment]
> My purpose is definitely more for data visualisation and of course I took into consideration the details of how to build a divergent ramp. Maybe the colours are not popular as viridis or derivatives, but it was just an idea. crying_cat_face

Hey no crying cat here :stuck_out_tongue: ! My comment definitely wasn't a rejection of this work, just a clarification so that we can review it properly!

**Comment by ambarja** [comment]
@nyalldawson @nirvn  I recently created a new shield or bagdes for qgis, maybe it should be in the main readme, but the bad point is that it is always updated manually.
You could still evaluate it, here to main source.
 - source : https://github.com/alexandresanlim/Badges4-README.md-Profile#-spatial-software-
 
Captura de pantalla de 2022-02-24 18-44-02

**Pull request closed without merging**
