### PR TITLE
Release 2 12

### PR DESCRIPTION
**Pull request by darshanhegde13**
Hi,

I have added Attributetable Unique values filtering functionality(Like You can see in Microsoft Excel), Please review the code and let me know any improvements are needed. Please find the code [here](https://github.com/darshanhegde13/qgisMyChanges/blob/master/src/gui/attributetable/qgsdualview.cpp)
filtering

### CODE REVIEW

**Comment by alexbruy** [comment]
Please, use master branch for your PR

**Comment by nyalldawson** [comment]
Neat feature! But something is very broken with this PR. I'd check out a new branch from master, and then cherry-pick your commits on top of that and open a new PR.

**Comment by darshanhegde13** [comment]
Hi nyalldawson,

I am new to QGIS, it's just an Idea, So let me know,weather the functionality is already exist or not? If not,I will improve this feature.

**Comment by nyalldawson** [comment]
@darshanhegde13 there's no similar functionality yet, but it looks very useful. That's why I'd suggest getting the PR sorted out. Then we'll help you get this in the right shape for merging.

**Comment by darshanhegde13** [comment]
Thank you nyalldawson, I am started working on this

**Comment by nyalldawson** [comment]
I'll close this PR for now. Please open a new one when the branch is sorted.

**Pull request closed without merging**
