### PR TITLE
[ogr] Read GPX elevation values as geometry Z values

### PR DESCRIPTION
**Pull request by nyalldawson**
@rouault mind taking a look at this? I noticed that elevation values weren't read by QGIS while investigating http://hub.qgis.org/issues/14702 and I believe this is the fix.

However, the WKB type of the geometries seems messed up, and I think it may be an OGR issue. See the comment https://github.com/qgis/QGIS/compare/master...nyalldawson:gpx_elev?expand=1#diff-a7986217f22008f8bf3a9b9f8a65060bR132

### CODE REVIEW

**Comment by rouault** [comment]
Your commit looks good to me.

Regarding the self.assertEqual(f.constGeometry().geometry().wkbType(), QgsWKBTypes.LineStringZ ) failed assertion, I guess testing against QgsWKBTypes.LineString25D will work. OGR_G_ExportToWkb() uses the code of the old 2.5D WKB extension proposal for [Multi]Point/[Multi]LineString/[Multi)Polygon, and not the later ISO codes. Since GDAL 2.0, OGR_G_ExportToIsoWkb() is available for that.

**Comment by nyalldawson** [comment]
@rouault OK - that fixes it. Thanks!

**Comment by nyalldawson** [comment]
@rouault BTW, got any clues on http://hub.qgis.org/issues/14702? Has something changed in that regard with GDAL?

**Comment by nyalldawson** [comment]
Manually merged as 4080aad0eef5d8ca78fdab2e3c4e3ce0815e6610

**Pull request closed without merging**
