### PR TITLE
[wip] Experiment with headless QGIS tests

### PR DESCRIPTION
**Pull request by elpaso**

### CODE REVIEW

**Comment by elpaso** [comment]
Lack of feedback, and I don't feel like insisting with the funder.

**Comment by luipir** [comment]
@elpaso what feedback was requested here?

**Comment by elpaso** [comment]
Long story short: I've sent an email to the dev list that probably didn't get through, I've re-sent it and it failed again, in the meantime the funder didn't seem like she wanted to proceed with this.
I'll cherry pick the tiny changes to the test scripts and commit to master. 
Btw, still waiting to the backport to be merged.

**Comment by wonder-sk** [comment]
@elpaso for the record that email from you got to dev list both times... (just nobody replied to it)

**Comment by elpaso** [comment]
@wonder-sk thanks for letting me know (I've got bounce back notifications both times), perhaps some more feedback would have helped to sell this task, but that was no big deal really. 
Btw my little experiment showed that running tests inside QGIS in CI is perfectly feasible and ready to roll if somebody needs it.

**Pull request closed without merging**
