### PR TITLE
Followup aa590b7, more tolerant progress matching

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Review by nicogodet — APPROVED** [review]

**Comment by nicogodet** [comment]
Even better and cleaner !

**Comment by nicogodet** [comment]
Any chance of backport ?
Not critical but nice to have on next LTR

**Comment by nyalldawson** [comment]
@nicogodet 

> Any chance of backport ?
Not critical but nice to have on next LTR

Can you open a PR **after** the next round of releases? I'm slightly concerned about risk of regression here.

**Comment by nicogodet** [comment]
Alright, it seems fair to me.
I push these on my local install, let's see if it breaks anything and I will open a PR before .4.

**Pull request merged**
