### PR TITLE
[LayoutLegend] Correctly fix position while painting

### LINKED ISSUE #37566: Legend in map atlas anchored to bottom left or bottom right will not correctly reposition in PDF
**Describe the bug**
In a map atlas, if I anchor a legend to either the bottom left of bottom right and if the legend is set to limit to the features to the current atlas item, it positions itself properly when I traverse the atlas manually, but when I output the atlas to a PDF or individual PDFs, the legend shifts seemingly at random. Sometimes if atlas items have many features in the legend, the legend will fall off the page or position itself higher on the page.

**How to Reproduce**
1. Create an atlas of villages within a county, with a legend containing names of parks using the county's tax parcels data. 

2. Place the legend at the bottom right of bottom left of the page. 

3. As you manually traverse the atlas, the top off the legend will reposition as needed to accommodate the list of parks. 

4. Output the atlas to a PDF or PDFs. If the first village has five parks and the next has ten, the list will fall off the page. If the next following village has three parks, there will be more space below the legend than there was in the first map. 

**QGIS and OS versions**
3.14 and earlier; Windows 10 Professional

**Additional context**
The only ways I can resolve this is position the legend at the top of the page or to output the PDFs individually as I traverse the atlas.

### PR DESCRIPTION
**Pull request by troopa81**
Follows https://github.com/qgis/QGIS/pull/49747 which stopped working after #52161 because, in the end adjustBoxSize() was called in the middle of painting and was modifying the item position. 

So we have to backup the old position early enough (at the very beginning of paint) so we can translate to this new position at the end of the paint method.

Fixes #37566 (Again)

### CODE REVIEW

**Comment by troopa81** [comment]
@nmb100 It should fix your layout legend positioning issue definitely this time

**Comment by nmb100** [comment]
Dear Julien

That will be wonderful. I eagerly await 3.40.0 to be released.

---
Regards,

Nigel Berjak
Please consider the environment before printing this email.

On 2024-09-19 09:54, Julien Cabieces wrote:

> @nmb100 [1] It should fix your layout legend positioning issue 
> definitely this time
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/nmb100
[2] https://github.com/qgis/QGIS/pull/58798#issuecomment-2360251179
[3]

**Comment by agiudiceandrea** [comment]
I wonder why the tests added in https://github.com/qgis/QGIS/pull/49747 didn't prevent the regression.

**Comment by troopa81** [comment]
> I wonder why the tests added with https://github.com/qgis/QGIS/pull/49747 didn't prevent the regression.

Yes, I also wondered. And the reason is because is because there were no filter (by map, expression, whatever) and so [adjustBoxSize](https://github.com/qgis/QGIS/blob/a2626a2a427afc5d139061e43ade0e62bafda8ad/src/core/layout/qgslayoutitemlegend.cpp#L61) was not called. And I have also to make 2 rendering because of [this](https://github.com/qgis/QGIS/blob/a2626a2a427afc5d139061e43ade0e62bafda8ad/src/core/layout/qgslayoutitemlegend.cpp#L280) which is initialized on the first rendering

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
