### PR TITLE
move ocispatial to external lib directory

### PR DESCRIPTION
**Pull request by 3nids**
see #6111

### CODE REVIEW

**Comment by nyalldawson** [comment]
@3nids 

I had to add ${CMAKE_SOURCE_DIR}/external to providers/oracle/CMakeLists.txt INCLUDE_DIRECTORIES, but with this change it compiled fine.

**Comment by jef-n** [comment]
ocispatial is modified - same for libdxfrw

**Comment by 3nids** [comment]
@jef-n any chance to get this changes merged upstream?

**Comment by jef-n** [comment]
ocispatial is a fork of oci - no idea if Qt is interested to merge.
libdxfrw upstream seems dead (you already tried a merge request)

**Comment by 3nids** [comment]
ok, so what do you think?
you prefer to keep them down where they "make sense" rather than in external?

**Comment by jef-n** [comment]
Yes, to me there's no need to move the stuff.

**Comment by m-kuhn** [comment]
This PR has not received any more attention in 3 months. Let's declare it dead until Frankenstein turns up.

**Pull request closed without merging**
