### PR TITLE
[server] Fix the Access control in the WMS groups

### PR DESCRIPTION
**Pull request by sbrunner**
## Description
- Fix the Access control in the WMS groups
- Reactivate the tests
- Split the tests in more then one file
- Add WMS groups tests

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Hi @sbrunner 
can you quickly comment on what has been fixed in the access control or link to an issue report?

**Comment by nyalldawson** [comment]
One thing I've noticed here is that WMS_GetLegendGraphic_Country.png uses a font which isn't the QGIS standard test font. This will need addressing or we'll run into issues with the tests on other platforms. I'd also suggest bumping the font size for this test a lot, and using the bold version of the test font too to minimise rendering differences across platforms.

**Comment by sbrunner** [comment]
@m-kuhn Fix the Access control in the WMS groups:
in the `qgswmsrenderer.cpp`
`layers` contains the real layers, and `params` the groups, then the if is always false we we call the service with a group.

**Comment by sbrunner** [comment]
@nyalldawson 
* Whats the QGIS standard test font, I see may deferent font used in the tests (Ubuntu, Noto, DejaVu, Liberation, MS shell)?
* What do you mean with « bumping the font size »?

**Comment by elpaso** [comment]
@sbrunner have a look here: https://docs.qgis.org/testing/en/docs/developers_guide/unittesting.html#id3
Basically, we ship a "QGIS" font “QGIS Vera Sans” for the purpose of testing.
By using a bigger font size you can reduce aliasing and other small rendering problems across platforms and OS versions.

**Comment by sbrunner** [comment]
Thanks @elpaso I will target that :-)

**Comment by sbrunner** [comment]
Font updated :-)

**Comment by nyalldawson** [comment]
@sbrunner 

Thanks, that's perfect!

**Comment by sbrunner** [comment]
@nyalldawson Thanks :-)

**Comment by pblottiere** [comment]
Hi @sbrunner,

> Fix the Access control in the WMS groups:
in the qgswmsrenderer.cpp layers contains the real layers, and params the groups, then the if is always false we we call the service with a group.

Nice, thanks for the fix! 

Actually, I think that groups should be better managed in renderer, and this PR is adding numerous unit tests which will be helpful in the future :).

**Review by pblottiere — APPROVED** [review]

**Comment by sbrunner** [comment]
Thanks @pblottiere :-)

**Pull request merged**
