### PR TITLE
Zoom to feature on a map when an attribute table row is double clicked

### PR DESCRIPTION
**Pull request by Samweli**
For https://github.com/qgis/QGIS/issues/29632

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nirvn what's your thoughts here? I'm personally concerned that intercepting the double click inside the cell would potentially break some of the edit widget behavior.

**Comment by nirvn** [comment]
I'm also sharing the same concern as Nyall raised here.

**Comment by nirvn** [comment]
Why not narrowing the behavior down to clicking or double click on the vertical header (i.e. 

[ 1 ]
[ 2 ]
[ 3 ]
etc.

)?

**Comment by gioman** [comment]
> Why not narrowing the behavior down to clicking or double click on the vertical header (i.e.

agree,

**Comment by Samweli** [comment]
> I'm also sharing the same concern as Nyall raised here.

Currently this feature doesn't work when layer is in edit mode.

**Comment by Samweli** [comment]
> Why not narrowing the behavior down to clicking or double click on the vertical header (i.e.
> 
> [ 1 ]
> [ 2 ]
> [ 3 ]
> etc.
> 
> )?

@nirvn @nyalldawson just updated the PR with @nirvn suggestion
Below a snippet on how it now works
using vertical header to zoom feature-2019-12-12 17-34

**Comment by elpaso** [comment]
Is there a tooltip or something that lets a user know about this behavior or is she supposed to learn it from the manual?
 If not on the header itself, it could be added to the toolbutton that trigges the same action on the selected feature.

**Comment by Samweli** [comment]
> Is there a tooltip or something that lets a user know about this behavior or is she supposed to learn it from the manual?
> If not on the header itself, it could be added to the toolbutton that trigges the same action on the selected feature.

Right @elpaso, what do you think would be the appropriate tooltip message? The toolbutton with the same action already has "**Zoom map to the selected rows (Ctrl+J)**".

**Comment by timlinux** [comment]
> Right @elpaso, what do you think would be the appropriate tooltip message? The toolbutton with the same action already has "Zoom map to the selected rows (Ctrl+J)".

How about "Zoom map to the selected rows (Ctrl+J) or double click the row header."

**Comment by timlinux** [comment]
Maybe we could also do:
image

Feature id: 4322 (double-click here to zoom to this feature)

**Comment by Samweli** [comment]
@timlinux Okay!

**Comment by Saijin-Naib** [comment]
Would this also trigger if we go down the table using the keyboard? I'd like that.

**Comment by nyalldawson** [comment]
@saijin-naib that's possible since 3.8: https://qgis.org/en/site/forusers/visualchangelog38/#feature-allow-browsing-feature-list

**Comment by 3nids** [comment]
Rather than introducing a double click, why not creating a standard qgis action zoom to which would be created for all geometry layers.
It would then be accessible on right click.
It sounds more intuitive to me.

**Comment by Samweli** [comment]
> Rather than introducing a double click, why not creating a standard qgis action zoom to which would be created for all geometry layers

What do you all think about this, should we have both functions, the context menu with a zoom action on the vertical row header (right click triggered ) and double click event on vertical row header? Or only one of these?

**Comment by Samweli** [comment]
> What do you all think about this, should we have both functions, the context menu with a zoom action on the vertical row header (right click triggered ) and double click event on vertical row header? Or only one of these?

@nirvn @nyalldawson

**Comment by roya0045** [comment]
Do you intend to have it enabled for edit mode? Most of the time when a user has to change some information, it is best if he can quickly see the feature and I think such a behaviour is better when editing.

**Comment by Samweli** [comment]
> Do you intend to have it enabled for edit mode?

I think it should be on both view and edit modes.

**Review by nirvn — COMMENTED** [review]
Looks good to me. I'd be fine merging this.

@3nids , are you ok?

**Comment by 3nids** [comment]
I am personaly -0 here:
* we already have a browsing mode when in form view
* double-click is not intuitive
* if we do need a browsing mode in the table view (vs form view), having it as an action would make it reusable in other places.

But if I'm the only here, I wouldn't mind having this merged.

**Pull request closed without merging**
