### PR TITLE
MXE build workflow

### PR DESCRIPTION
**Pull request by elpaso**
Cross build for windows using MXE and store artifact for testing.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Is there anything of use here? https://github.com/kadas-albireo/QGIS/commit/ce3862f23fbe1d26d509613a14e3e11ac09a0947

**Comment by elpaso** [comment]
> Is there anything of use here? [kadas-albireo@ce3862f](https://github.com/kadas-albireo/QGIS/commit/ce3862f23fbe1d26d509613a14e3e11ac09a0947)

Definitely!

**Comment by elpaso** [comment]
@nyalldawson I spend some time on the kadas-albireo cross build, the advantage is that it has Python but the problem is that it doesn't work :) 

It is also much slower, bigger and complex. 

I'd stick to MXE for now, but I'll make a PR with the work I've done on the the other build system.

**Comment by elpaso** [comment]
See also: https://github.com/qgis/QGIS/pull/33085

**Comment by elpaso** [comment]
Ok, let's see how this behaves, if it's too slow we can revert it.

**Pull request merged**
