### PR TITLE
Don't try to load HTML content when a layout is created in a background thread

### PR DESCRIPTION
**Pull request by nyalldawson**
The underlying QWebPage class used to render these can ONLY be used from the main thread. So we raise an error and render nothing to avoid crashes.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Ouch.
Talking about. Has there anything been going on on the QWebEngine front in the last 2 years?

**Comment by nyalldawson** [comment]
> Talking about. Has there anything been going on on the QWebEngine front in the last 2 years?

Nope, screw that. 

QtWebKit on the other hand, is being actively worked on...

see https://github.com/qtwebkit/qtwebkit

**Comment by nyalldawson** [comment]
@nirvn no, that's the reverse.

**Comment by nirvn** [comment]
Oh, then 🎉

**Pull request merged**
