### PR TITLE
Store URLs in QSettings

### PR DESCRIPTION
**Pull request by elpaso**
Make URLs overrideable through QSettings.
The idea is to eventually make all hardcoded URLs
and paths user-overrideable through a QSettings entry.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Have you seen https://github.com/qgis/QGIS/pull/3911? I think (parts of) this could be integrated with this system.

How will issues be handled if they are reported on different pages?

**Comment by elpaso** [comment]
Yes I saw that and talked to @alexbruy a few times about this. I don't think the two are related: the URLs that I'm addressing here are general and not contextual (only one is related to help system because it send the user to the user manual).

**Comment by alexbruy** [comment]
I think most of those URL are not related to generic help. The only one exception is "Help Contents" action from the "Help" menu and it is covered in #4023.

**Comment by m-kuhn** [comment]
I'm trying to understand the use case for this. I guess you are having your own issue tracker set up and are integrating it better into your ecosystem? In your case you are shipping custom binaries I think where you could easily patch such things? Or is this more for the case where QGIS is shipped with a customized interface and a single plugin for a specific purpose, where issues are rather sent to "MyAgricultureApp" than QGIS itself?

**Comment by elpaso** [comment]
The use case if for sysadmins in large organizations: they need to be able to customize the URLs, for example the want to use their own bug tracking system instead of letting the user use the hub.qgis.org.
The same for the user manual: the might want their user to use an internal portal that contains additinal/alternate material.

But, in general, I believe that we should try to not hardcode URLs inside the C++ code without leaving the possibility to change them, I'm working on QEP that will allow to provide defaults for the settings separately from the C++ code.

Regarding the custom builds: they are the last resource, you should not be forced to make new build only because you need changing an URL.

**Comment by m-kuhn** [comment]
So the structure will be something like this?

1. internal first level support (linked ticketing system)
2. where appropriate, issues will be forwarded upstream (be it a private qgis service provider or qgis.org)

**Comment by elpaso** [comment]
I really don't know, but you are probably right.
BTW,  my commit doesn't change anything in the current behavior of QGIS, it just adds the possibility to customize those URLs if you need to.

**Comment by m-kuhn** [comment]
Absolutely, nothing to argue on the technical level! I'm just trying to figure out what impact it has on the organisational level, workflows and where the workload will end under which conditions.

**Comment by elpaso** [comment]
My feeling is that it will reduce the load on volunteers in qgis.org because the firms that provide support for QGIS  act as a proxy and either fix bugs themselves and push upstream or hire a core dev to do that.

The important point is that, in order to prevent forking, QGIS must provide sufficient hooks for customization, expecially within large organizations that need to be able to configure/customize large deployments. But I think we are going the right route.

**Comment by m-kuhn** [comment]
You are probably right. Good work.

**Pull request merged**
