### PR TITLE
Allow to use WMS as static provider

### PR DESCRIPTION
**Pull request by PeterPetrik**
- created new ` virtual QWidget * QgsDataItemGuiProvider::createParamWidget( root, context )` as replacement of `QgsDataItem::paramWidget()` 
- added new CMAKE flag FORCE_STATIC_PROVIDERS to force all static providers only
- ported WMS provider

### CODE REVIEW

**Comment by nyalldawson** [comment]
Wouldn't QgsDataItemGuiProvider be a much better fit?

**Comment by PeterPetrik** [comment]
> Wouldn't QgsDataItemGuiProvider be a much better fit?

thanks, fixed

**Review by nyalldawson — APPROVED** [review]
New version looks great!

**Comment by nyalldawson** [comment]
Merge away...

**Pull request merged**
