### PR TITLE
Fix libgsl-dev => libgsl0-dev on Ubuntu

### PR DESCRIPTION
**Pull request by sbrunner**
See: http://packages.ubuntu.com/search?keywords=libgsl

### CODE REVIEW

**Comment by jef-n** [comment]
What's the problem?    libgsl0-dev was the old library name (pre-stretch/xenial) and libgsl-dev is the new one, but still provides libgsl0-dev.  Moreover INSTALL is not a source file - it's an output from doc/INSTALL.t2t, more precisely doc/linux.t2t and the package list is updated with scripts/scandeps.pl from the packaging information in the debian/ directory.  See 2cc83664

**Comment by sbrunner** [comment]
`libgsl-dev` (http://packages.ubuntu.com/search?keywords=libgsl-dev) exists only on xenial (and xenial isn't in the list), then for "old" releases we should use the name `libgsl0-dev`  (http://packages.ubuntu.com/search?keywords=libgsl0-dev)...

e.-g. on wily with `sudo apt-get install libgsl-dev` I get:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libgsl-dev
```

**Comment by sbrunner** [comment]
I just rebase to get the new xenial, by the way should ue remove the release `utopic`?

**Comment by jef-n** [comment]
done in b766ac1

**Comment by sbrunner** [comment]
Nice, thanks :-)

**Pull request closed without merging**
