### PR TITLE
move the logic of writing weak relations info away from QgsVectorLayer to QgsWeakRelation

### PR DESCRIPTION
**Pull request by 3nids**
and also use QgsRelation::writeXml to avoid an incomplete info if the relation code gets other attributes

### CODE REVIEW

**Review by elpaso — APPROVED** [review]
LGTM, I didn't check what https://github.com/qgis/QGIS/pull/38681/files#diff-a7da93edd7cd70922f2cdf20cf27c5c1R87 does but I guess it creates a `relation` element that we can get on the next line.

**Comment by 3nids** [comment]
>  it creates a relation element that we can get on the next line

yes, exactly.

Is this code tested somewhere?
I had a look in testqgsweakrelation.cpp, but there is no reading/writing of a project with broken layers. I couldn't find any other test.

**Comment by elpaso** [comment]
@3nids there are some tests here https://github.com/qgis/QGIS/pull/32487/files#diff-f924ee63dae157d08a6f66fc07eac90cR311 but I don't think they cover the XML serialization, just the resolution functionality.

**Comment by elpaso** [comment]
@3nids sorry, I meant this test link: https://github.com/qgis/QGIS/pull/33283/files#diff-095fa493f14d5c2ee03ea529640d700d the other one is more generic.

**Comment by 3nids** [comment]
Yes, indeed. thanks for the pointers.

**Pull request merged**
