### PR TITLE
Remove "duplicates" widgets of external resource 

### PR DESCRIPTION
**Pull request by DelazJ**
With the external resource widget (layer properties --> Fields --> Edit widget), the photo, filename and webview widgets became obsolete. To not puzzle the user, it'd be nice to remove them. This has somehow been mentioned at https://github.com/qgis/QGIS/pull/2589

This PR tries to do it but I'm not sure it's the way to do things: actually I removed references to these widgets but have no idea how a current project using them will behave in 3.0. Breaking API doesn't necessarily mean breaking projects at this "not easily noticeable" level, I guess. I have  no idea how to fix this side of the issue (if ever it's).

So if anyone can pick and improve the PR or show me the way i can go...

### CODE REVIEW

**Comment by m-kuhn** [comment]
I will probably have a look at that in the near future, including smooth migration of projects using photo or file widget to external resource widget.

**Comment by m-kuhn** [comment]
cc @3nids

**Comment by DelazJ** [comment]
Thanks @m-kuhn 
I'd be interested in the improvements you could do.

**Comment by DelazJ** [comment]
oups

**Comment by 3nids** [comment]
Yes I would like them to be removed too, but we need proper porting of existing project since it is easily doable. 
I would propose to wait for this to be complete before merging to avoid any project corruption. 
Now... I let you arrange who does what.

**Comment by 3nids** [comment]
superseded by #4074

**Comment by DelazJ** [comment]
Thanks @m-kuhn  and @3nids

**Pull request closed without merging**
