### PR TITLE
WIP: Add support for "options" in DatasourceURI

### PR DESCRIPTION
**Pull request by strk**
See #32832

### CODE REVIEW

**Comment by elpaso** [comment]
If you want to store it see:  https://github.com/qgis/QGIS/blob/master/src/providers/postgres/qgspostgresproviderconnection.cpp#L455

Also, add it to: https://github.com/qgis/QGIS/blob/master/src/providers/postgres/qgspostgresprovider.cpp#L5288

And feel free to deprecate `QgsDataSourceUri`: it the source of all kind of wrong assumptions and IMO it should not be in core unless completely rewritten to something like: "providerkey://provider specific uri here" and then the decode URI from provider metadata should be used.

Btw, aren't those "options" partly redundant? I mean, are you sure that they will not override other URI parameters? And if they do, which one is supposed to take precedence?

**Comment by jef-n** [comment]
I also think that this moves `QgsDataSourceUri` further in the wrong direction - there should be less provider(/postgres) specific stuff in it, instead of more.

**Comment by strk** [comment]
My current problem is writing a test for the fix in #32822

The test needs to use 2 different "roles" for the connection, but I'd like NOT to create a new user with login capabilities to do this. The only way I see to do so is to use PGOPTIONS to set a role which is different from the connection user, so there's no overlap.

Alternatively I could have the database setup script create a user, with a password, but this would mean exposing the target PostgreSQL cluster to a time window in which people can connect using the hard-coded username/password of the qgis test role...

**Comment by jef-n** [comment]
Why not remove all the `if`s that skip parameters and just let it fallthough to the `setParam`?

**Comment by strk** [comment]
> Why not remove all the `if`s that skip parameters and just let it fallthough to the `setParam`?

Could work, I'll try that in pr #32822 and see if it sticks

**Comment by strk** [comment]
Note, from Travis testing, that QgsDatasourceUri is not able to parse the escape sequence anyway:
```
../tests/src/core/testqgsdatasourceuri.cpp:144:37: error: unknown escape sequence '\ ' [-Werror,-Wunknown-escape-sequence]

      << "sql= table=\"\" options=-c\ role=guest "

                                    ^~
```

From https://travis-ci.org/qgis/QGIS/jobs/611410954#L467

So some work would be needed here anyway

**Comment by strk** [comment]
Removing the special handling for `options` still "eats" the options:
```
431: XXXX: creating connection with uridbname='qgis_test' sslmode=disable options=-c\ role=qgis_test_role
XXX ::tables got uri: dbname='qgis_test' port=5432 sslmode=disable
```

somewhere those options get lost, and I guess it's wherever some class (Uri itself?) tries to separate connection-oriented parts from other parts, to determine if a pre-existing connection exists

**Comment by strk** [comment]
Found the stripper: it is `QgsDataSourceUri::connectionInfo` who doesn't care about parameters, do you see that ?

In turn, QgsPostgresProviderConnection::QgsPostgresProviderConnection initializes the uri to whatever is returned from `QgsDataSourceUri::connectionInfo()` so that information is lost (which role to use)

**Comment by strk** [comment]
Ok I'm closing this PR as I see you want QgsDatasourceUri deprecated

**Pull request closed without merging**
