### PR TITLE
Try to clean all Graphical modeler references and replace by Model Designer

### PR DESCRIPTION
**Pull request by SrNetoChan**
## Description

It seems that the old name of the Model Designer was present in some places, including the Processing menu. This PR tries to clean that up. A documentation PR is on it's way too.

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by SrNetoChan** [comment]
What do I need to do here to pass the tests?

**Comment by alexbruy** [comment]
@SrNetoChan you need to run sipify.pl script for the affected file, something like
```
sipify.pl -s python/core/auto_generated/processing/models/qgsprocessingmodelcomponent.sip core/processing/models/qgsprocessingmodelcomponent.h
```

**Comment by Gustry** [comment]
@SrNetoChan Do you have the pre-commit hook for git setup ? https://github.com/qgis/QGIS/blob/master/scripts/prepare_commit.sh Or sometimes I run the script manually.

**Comment by SrNetoChan** [comment]
Seems that the linux build got out of space.

**Pull request merged**
