### PR TITLE
Temporal ux fixes

### PR DESCRIPTION
**Pull request by nyalldawson**
Accompanies https://github.com/qgis/QGIS/pull/43578, and adds nice clear explanatory text to the vector layer temporal properties pages to explicitly state that event time ranges are considered as start <= t < end

Before:

image

image

image

image

After:

image

image

image

image

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Is it an idea to add an old/new screenie of the situation?

**Review by nirvn — APPROVED** [review]
Looking good, merge at will!

**Comment by nyalldawson** [comment]
@rduivenvoorde 
> Is it an idea to add an old/new screenie of the situation?

I've added some to the PR message

**Comment by rduivenvoorde** [comment]
Thanks for the screenies. Some (late) comments (numbering the 'after' images from 1 to 4):

- wondering if it is clear enought in '1' that using a 'single field with Datetime' also is valid for instantaneous features. What about in the dropdown: 'Single field with Date/Time with fixed duration or no duration (instantaneous events)'
Because this is the option to use for twitter events or earthquackes (I think)?

- using 't' as symbol for 'map range'  is (to me) counter intuitive. 't' is often used for the time of the 'object of action'. Also t looks like a 'time stamp' while it is (always) a Time **Range**. So in all expressions like "xxxx < t < yyyy" what about using the term 'map temporal range' or 'time filter range'. Or use 'r' for range and make it clear in the texts by using "map temporal range ('r')"?

Thanks for this work

**Comment by nyalldawson** [comment]
@rduivenvoorde 

The other option would be to use the [ ...., ....  ) notation, e.g. "events will be treated as having a duration [Start field, End field) ".

But in the past their was strong argument against using this type of notation. From memory it's not a universal thing, and different locales use a different method of expressing this. I also don't think it's beginner friendly at all...

**Pull request merged**
