### PR TITLE
Fix v.rectify

### LINKED ISSUE #45149: v.rectify (Processing: GRASS provider) consistently fails with "Required parameter <output> not set"
### What is the bug or the crash?

The GRASS module v.rectify is not correctly wrapped/parsed/executed by the GRASS provider in Processing.

### Steps to reproduce the issue

1. Open Processing Toolbox.
2. Launch GRASS' "v.rectify"
3. Fill in minimal options: input layer and either a text file with four source/target points or the points themselves in the text field.
4. Run "v.rectify"

The tool will always quit with an error. Take a look at the GRASS console output:
The command line for "v.rectify" passed to GRASS GIS is missing the essential "output=" option, which causes the tool to throw an error: "Required parameter <output> not set".

I use these coordinates (plus "active flag") to transform from a local system with small coordinate ranges to UTM 37N (you can try that with any layer, although it would produce wrong results; the point here is that I can currently produce no result at all):

-637.240 580.860 432843.854 3823560.989 1
-962.079 1086.419 432522.788 3824068.656 1
-1369.031 837.071 432114.226 3823822.337 1
-1877.673 775.273 431605.364 3823764.216 1

### Versions

Tested with: QGIS 3.16 and 3.20, Windows 10 and Arch Linux (AMD64).

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I have tried both using "Inline control points" and reading points from a file (alternate options).
I have also checked the associated "description" file ("v.rectify.txt") used by the GRASS provider in Processing: It is fine, but misses the "group=" option (see below).

There are two things that make me suspicious:
1. GRASS' "v.rectify" has an additional "imagery type" input option ("group="), which is _not_ wrapped by Processing. Perhaps this messes up the parsing sequence of GRASS module options?
2. "v.rectify" has a weird "inline" option of type "string", which is used to enter control points directly into the UI. This _is wrapped correctly_ by Processing (and present in "v.rectify.txt"), and it is represented properly in the Processing UI for the tool. But I wonder if it throws of the parser that assembles the GRASS command line? I do notice that the "inline points" are _not present_ on the parsed GRASS command line, as produced by the Processing provider.

Currently, "v.rectify" is the only tool in QGIS that allows transformation of an existing vector layer by control points. Therefore, it is a pity that it does not run properly.

### PR DESCRIPTION
**Pull request by nicogodet**
## Description

2 issues were found in ext v_rectify.py:

- variable passed to `parameters` was `tempPoints` which is a variable used in with statement and correspond to a TextIOWrapper. `pointsName` is the variable that need to be pass to `parameters` as it is the temporary file path.
- `delOutputs` was `True` in `alg.processCommand()` and should not be `True` as user wants the results being added to QGIS.

fix #45149

### CODE REVIEW

**Review by lbartoletti — APPROVED** [review]

**Comment by nicogodet** [comment]
@lbartoletti I will add a test when @benducke provides all requested info.
I have no idea how this alg works 😃

**Comment by lbartoletti** [comment]
> @lbartoletti I will add a test when @benducke provides all requested info.
> I have no idea how this alg works smiley

Yes, I see your comment on the issue :)
No worries, if he doesn't give his data set, I'll come help you do it.

**Comment by benducke** [comment]
"v.rectify" performs affine transformation of vector layers. It computes the transformation parameters (scaling, rotation, translation) from a set of control points (corresponding source and target coordinates). It then applies these parametes and produces a transformed output layer.

The common use case for this is to transform high-precision survey data from a local x/y system (e.g. set up on a building site or for an engineering survey) into a spatial reference system that has a "proper" EPSG entry.

In addition, "v.rectify" does some clever things for 3D data: it constrains the transformation, so that the X, Y and Z axes will not be scaled independently, which prevents geometric skew for 3D data. This makes "v.rectify" pretty unique in the GIS world, and it is a very good thing to have this work in QGIS!

I have prepared a ZIP with sample data:

[v.rectify.sample.zip](https://github.com/qgis/QGIS/files/7211984/v.rectify.sample.zip)

This contains a very simple shapefile with just three 2D points in a local system.

The control points are in "v_rectify_local_utm37n.txt". Those are used to transform the points to their corresponding UTM 37N/WGS 84 (EPSG:32637) coordinates. In addition, there is a "1" at the end of each line, which tells "v.rectify" that these records are "active" (i.e. points to be included in computing the transformation).

The attribute fields in the shapefile tell you the local and corresponding UTM coordinates.

The options for "v.rectify" (as used by the Processing UI) are:
Name of input vector map: "3-local-points-for-transformation"
Name of input file with control points: "v_rectify_local_utm37n.txt"

(Leave all other options to defaults).

**Note:** the shapefile in the ZIP has no reference system information (no ".prj" file). This is intentional, since it is local data. If you run 'v.rectify' on this and create a temporary layer as output, then the temp layer will also have an invalid SRS. For some reason, QGIS (at least 3.20) won't show the point geometries, until you set the SRS of the temp output layer to something valid (in this case: EPSG:32637).

**Comment by nicogodet** [comment]
@lbartoletti Do you have an idea how to fix this ?

https://github.com/nicogodet/QGIS/runs/3702091701

**Comment by benducke** [comment]
Maybe the "inline_points" option is not correctly handled by the testing framework? It is a very exotic type of GRASS GIS option. I wouldn't be surprised if this was the first occurence of it in automated testing.

**Review by lbartoletti — APPROVED** [review]

**Comment by lbartoletti** [comment]
> @lbartoletti Do you have an idea how to fix this ?
> 
> https://github.com/nicogodet/QGIS/runs/3702091701

sorry for the late reply. LGTM

**Comment by nicogodet** [comment]
In fact, this kind of parameter is used in r. algs, like here:
https://github.com/qgis/QGIS/blob/77be95feac7391e58f6bd487f30e09ed8ed63651/python/plugins/grassprovider/tests/testdata/grass7_algorithms_raster_tests1.yaml#L757-L769

I don't know if this `grass7:r.category` test works as intended...

**Comment by benducke** [comment]
Hmmm, I don't think that the parameter which takes the classification rules for r.category ("textrules" in YAML or "rules" on the GRASS CLI is technically the same thing as the "inline_points" for v.rectify. r.category takes "rules" input from stdout. But "inline_points" is something really weird that is not exposed on the GRASS CLI. It seems to be only used by the GRASS wxWidgets GUI (Python). That is why "inline_points" is wrapped in Processing's "v_rectify.py", its value written to a temporary text file, and then passed to GRASS' v.rectify via the "points=" option, which takes a file as input ("inline_points" and "points=" are two alternatives to archieve the same thing). I think you should simplify the test for v.rectify by using "points=" and a file, instead of trying to parse the "inline_points" option. After all, in the Processing framework, "points=" is used for both cases.

**Pull request merged**
