### PR TITLE
Update embedded laz-perf to latest master

### PR DESCRIPTION
**Pull request by nyalldawson**
Adds support for laz 1.4

### CODE REVIEW

**Comment by nyalldawson** [comment]
Att @wonder-sk @hobu

**Comment by hobu** [comment]
Represents an API change. Maybe too late in the cycle to update.

**Comment by nyalldawson** [comment]
@hobu 

> Represents an API change. Maybe too late in the cycle to update. 

It's not an api change for QGIS though, so there's no issues on the QGIS side regarding that. I guess the more pertinent question is whether you feel the update would fix more issues than it would introduce?

**Comment by hobu** [comment]
I think we should wait one cycle to integrate it into QGIS. EPT/LAZ 1.4 isn't so much a thing yet and there is still some testing to do with the new laz-perf and PDAL.

**Comment by nyalldawson** [comment]
@hobu, ok, thanks for the insights!

**Pull request closed without merging**
