### PR TITLE
[processing] add date, datetime, time fields to memory output

### PR DESCRIPTION
**Pull request by nirvn**
This PR adds date ,datetime, and time field support to the memory vector writer.

@alexbruy , this fixes the issue I filed a few days ago  (http://hub.qgis.org/issues/14163). 

@nyalldawson , I don't have a postgis environment setup on my machine, so couldn't add the postgresql-specific field mapping.

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson any idea why the linux build failed on qgis_intendation? I have autopep8 installed, and it doesn't correct locally the intendation that makes the build fail.

**Comment by nyalldawson** [comment]
@jef-n thoughts? I'm seeing this a lot in the processing algorithm changes...

**Comment by volaya** [comment]
The change looks good. 

I am also seeing that issue, even with very minor changes in the code. The OSX tests pass, but not the linux ones, due to indentation. @alexbruy also mentioned that in another PR as well

**Comment by alexbruy** [comment]
I think we can ignore indentation test failure. I also have it often fail on Travis, while on my machine this test passed.

**Comment by jef-n** [comment]
@nyalldawson maybe a fix in autopep8?  I see that too with autopep8 0.9.1 (current in debian unstable). We install 1.2.1 in travis (lastest via pip)

**Comment by nyalldawson** [comment]
@jef-n ok, that worked fine - see cbe8cb7 . Thanks!

**Comment by nirvn** [comment]
@alexbruy , @volaya , can this be merged into master?

**Pull request merged**
