### PR TITLE
OGR data provider: use transactions when changing attributes and geometries (if possible) (#16216)

### PR DESCRIPTION
**Pull request by rouault**
This is a followup to  https://github.com/qgis/QGIS/pull/4175

### CODE REVIEW

**Comment by landam** [comment]
@rouault Thanks for new pull request...

**Comment by m-kuhn** [comment]
Thanks @rouault 

Is there any benefit in also adding this for add/deleteFeatures?

**Comment by rouault** [comment]
> Is there any benefit in also adding this for add/deleteFeatures?

Yes, added extra commit for that

**Comment by m-kuhn** [comment]
Thanks @landam @rouault @gioman 

What's your opinion, is it required to test this a couple of days on master or is it save to backport to 2.18 straight away?

**Comment by gioman** [comment]
> What's your opinion, is it required to test this a couple of days on master or is it save to backport to 2.18 straight away?

let me do a few tests on master first, I will get back to you asap.

**Comment by landam** [comment]
Would be nice to have it QGIS 2.18.5

**Pull request merged**
