### PR TITLE
Legend: optional text on top of symbols for vector layers

### PR DESCRIPTION
**Pull request by wonder-sk**
In some cases it is useful to add extra information to the symbols in the legend.

This work allows definition of additional labels in vector layer properties > Legend tab:

legend_text_on_symbol_config

This is how it then looks in the layer tree in the main window:

legend_text_on_symbol_layer_tree

And in the print layouts:

legend_text_on_symbol_print_layout

Developed for Arpa Piemonte (Dipartimento Tematico Geologia e Dissesto) within ERIKUS project.

### CODE REVIEW

**Comment by gioman** [comment]
ohhhh...

**Comment by nyalldawson** [comment]
(code looks good by the way!)

**Comment by NathanW2** [comment]
image

**Comment by wonder-sk** [comment]
Thanks for the reviews including one heavily breathing cat!

@nyalldawson I have added another button to quickly populate labels based on an expression. For style dock integration unfortunately I do not have energy (aka funding) right now...

**Comment by wonder-sk** [comment]
(build failed because of temporarily broken master)

**Pull request merged**
