### PR TITLE
fix: [Snyk] Security upgrade vue from 2.7.14 to 3.0.0

### PR DESCRIPTION
**Pull request by tygyh**
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JS-POSTCSS-5926692

## Description

Automated update by Snyk to fix a vulnerability in vue.

See [the generated PR](https://github.com/tygyh/QGIS/pull/1) for more details

### CODE REVIEW

**Comment by nyalldawson** [comment]
@elpaso is this legit? Looks suspicious to me...

**Comment by tygyh** [comment]
> Looks suspicious to me...

What about this is suspicious?

**Comment by elpaso** [comment]
It looks legit but it breaks the build: https://github.com/qgis/QGIS/actions/runs/10760791211/job/29844521868?pr=58608#step:10:6614

It probably needs manual adjustments.

**Comment by tygyh** [comment]
> It probably needs manual adjustments.

Is "It" in this case the pr or the build?

**Comment by elpaso** [comment]
> > It probably needs manual adjustments.
> 
> Is "It" in this case the pr or the build?

The PR needs changes in order to fix the build.

Also, you need to make sure that the generated JS code actually works after the updates (that should be done manually).

**Comment by tygyh** [comment]
I don't know where to find the ninja tests to figure out what is wrong

**Pull request closed without merging**
