### PR TITLE
Fix drag & drop for PG rasters in DB Manager

### PR DESCRIPTION
**Pull request by radosuav**

### CODE REVIEW

**Comment by pcav** [comment]
@brushtyler @strk

**Comment by strk** [comment]
works for me

**Comment by strk** [comment]
pushed as 27f1d9fb3ebb2445c7bec4350fd5b822d4d718e1

**Comment by strk** [comment]
and as cf60fcdd5fcacc487c12b497f68635927c745cfe in 2.8 branch

**Comment by strk** [comment]
Sorry, backport is ea447e78e4f121fb1ef2c83e4e45e727bd9d9f87

**Comment by brushtyler** [comment]
Sorry for this late reply.
IMHO it's crazy to use `re` just to do a char replacement in a string w/o any pattern... Anyway it works.

**Comment by strk** [comment]
Yeah, I also had that thought, but then I thought speed is better addressed _after_ testcases (which do not exist at all for DBManager, as far as I can tell).

**Pull request closed without merging**
