### PR TITLE
[processing] Union: fix output of features that do not instersect layer A

### PR DESCRIPTION
**Pull request by wonder-sk**
(PR for QGIS 2.18 - needs porting to 2.14 / master)

Union algorithm had incorrect logic for output of geometries in layer B
that are partially intersected by layer A or not intersected at all.

Added processing unit test that should cover all cases.

I have added some TODOs to the code as the outputs may still misbehave
if intersection or difference operations return unexpected geometry types.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Is this not an issue in master?

**Comment by wonder-sk** [comment]
> Is this not an issue in master?

It is an issue in master as well, but I was fixing it for 2.x first...

**Comment by m-kuhn** [comment]
CC @gioman

**Comment by gioman** [comment]
@m-kuhn @wonder-sk seens thanks (I get all the notifications)! Will give it a proper try when committed.

**Comment by Gustry** [comment]
Thanks @wonder-sk for the fix. We are gonna use your commit in inasafe. I will let you know if we have some other issues. I tried quickly your patch, it seems good for now.

**Pull request merged**
