### PR TITLE
Browser harmony

### PR DESCRIPTION
**Pull request by nirvn**
## Description
This PR harmonizes the browser panel icons by using grayscale across the folder, zip, db table, mesh, and raster icons.

A before vs. PR says it all:
image

@nyalldawson , how good is that? :wink: 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by elpaso** [comment]
Colors convey information, why don't give a color to the grey icons instead?
So that we can tell a vector from a raster from a DB with a blink of an eye?

**Comment by SrNetoChan** [comment]
I am afraid I agree with Alessandro. It may even look better more polished, but I am not sure it is more useful for the user. It makes it harder to differentiate each type of file.

Folders are also harder to identify.

**Comment by nyalldawson** [comment]
For me this is a step in the right direction -- the trend nowdays is to "symbolic" icon themes, which use colors very sparingly and which avoid taking away attention from the applications main content (the map), and which work correctly across light/dark themes.

The browser is so visually noisy at the moment that it just screams for attention.

**Comment by elpaso** [comment]
IMHO It's probably just a fad (like square icons everywhere) and anyway, the GUI I like the most reduce the visual noise through desaturation but they keep the colors in icons.

immagine

**Comment by elpaso** [comment]
Some interesting research: https://www.nngroup.com/articles/visual-indicators-differentiators/

**Comment by nirvn** [comment]
The main motivation here was well worded by @nyalldawson in his comment above. On top of what was said, IMHO, the arbitrary use of color for some data types (raster and mesh) and not for others (vector) is distracting, and a bit messy. 

@elpaso , while we're reducing the attention-grab, I don't think we're at a point where everything looks like a square :) 

@SrNetoChan , @elpaso , regarding the folder icon, if you guys feel it's too hard to distinguish (I assume you think it's too similar to the polygon), what about reverting the color invertion, and having folder dark-gray filed. Would that be a good middle-ground, agreeable approach?

**Comment by elpaso** [comment]
I disagree with the motivation, I mean I agree that the browser needs attention and can be improved and I like the new folder icons, but IMHO the way to make the browser better is to add/redesign colors (maybe desaturated) not to remove them.

Mine might just be the POV of a not-so-young person who starts to have some poor eyesight problems but I really notice the difference between the two images you posted: while in the current browser I can immediately spot the rasters without scanning the whole list, in the the new image I need much more focus on each element before my brain can actually decode the meaning of each item.  

But really, it's not about my poor eyesight, there is enough research evidence in the UX/UI field to prove it.

Btw, here is the full image:

immagine

**Comment by NathanW2** [comment]
Yeah I'm not sure I'm keen on no colour at all in the browser there because
it all blends together making it hard to tell what is what.  Makes it look
they are they a disabled tree entry.

I would like to see some more color in there as long as it's standard on
each platform and not based on each OS.

**Comment by SrNetoChan** [comment]
> @SrNetoChan , @elpaso , regarding the folder icon, if you guys feel it's too hard to distinguish (I assume you think it's too similar to the polygon), what about reverting the color invertion, and having folder dark-gray filed. Would that be a good middle-ground, agreeable approach?

Yes, I think that would work.

**Comment by nirvn** [comment]
@elpaso , here's some color back, slightly desaturated:
image

How is that?

**Comment by nirvn** [comment]
@SrNetoChan , I've tried reverting the folder's invert, but IMHO it's not working as well. I think we've achieved a good balance here by adding some de-saturated taints of blue to the vector icon, it helped differentiate that from the folder / zip / table icons. 

Thanks for the constructive comments here. I'll merge this when it's green, and work on follow up comments as you guys are enjoying the refreshed / improved look :)

**Pull request merged**
