### PR TITLE
Some processing features + fixes

### PR DESCRIPTION
**Pull request by nyalldawson**
Main thing this PR does is implement a new algorithm for merging connected linestrings. I haven't found a good way to do this using the existing providers + algorithms, so always have to resort to PostGIS' st_linemerge function. This new algorithm makes it possible to do this in processing.

I've also fixed a bug in multipart to singlepart, and added some tests.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Just added another feature - this lets you select multiple fields when using the dissolve algorithm. It's another thing which is almost impossible to do reliably using the existing provider algorithms.

@m-kuhn any idea on why the test is failing with a crs comparison? I can't see what I've done differently and it works locally

processing team: is there any way to disable parameters based on another parameter? I find it confusing that the dissolve field choice is enabled when "dissolve all" is selected. I often run a dissolve after picking a field, only to have forgotten this checkbox and need to repeat the operation...

**Comment by alexbruy** [comment]
@nyalldawson Processing does not allow to change (enable/diable) algorithm parameters on the fly. Currently the only possible solution is to split algorithm into two with different set of parameters.

**Comment by nyalldawson** [comment]
@alexbruy ok thanks- it'd be a nice ui enhancement to add at some stage :)

@m-kuhn gentle ping... Any idea on the crs issues?

**Comment by m-kuhn** [comment]
I remember I had some strange issues with CRS as well. I think it was related to some files (.xsd?) being checked in but that does not seem to be the case here...

**Comment by m-kuhn** [comment]
hold on... there are xsd files. Can you try to remove them?

**Comment by nyalldawson** [comment]
@m-kuhn So, turns out the xsd files *are* required. But in the end what worked was rewriting the gml using ogr2ogr. Not sure why, but it's fixed the test here.

**Comment by m-kuhn** [comment]
So the main thing ogr2ogr did was adding even more xsd files?

**Pull request merged**
