### PR TITLE
Default integers to QLongLong in expressions

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
CC @nyalldawson @wonder-sk

**Comment by nirvn** [comment]
@m-kuhn , looks good. I'll build n test tomorrow morning.

Looking at the code, I'm wondering whether the to_int() function should use the newly introduced getNativeIntValue(), that way we could force a int output if needed.

**Comment by m-kuhn** [comment]
I think the aim of the `to_int` function should mainly be to convert to an integer value in general (from string, double etc). If there's a good reason to have a function that converts to a 32 bit integer, we should call it accordingly `to_int32`.

**Comment by nirvn** [comment]
@m-kuhn , it doesn't work here.

`epoch('2017-01-01')` returns 1483203600000

`epoch('2017-01-01') - 1` returns 1439882879

**Comment by m-kuhn** [comment]
@nirvn sorry, better now?

There are also some epoch tests failing on my local machine. Any idea? Timezone

```
47: FAIL!  : TestQgsExpression::evaluation(epoch) Compared values are not the same
47:    Actual   (result.toLongLong())  : 1483225200000
47:    Expected (expected.toLongLong()): 1483203600000
47:    Loc: [/home/mku/dev/cpp/qgis/QGIS/tests/src/core/testqgsexpression.cpp(1120)]
47: FAIL!  : TestQgsExpression::evaluation(epoch) Compared values are not the same
47:    Actual   (result.toLongLong())  : 1483225200000
47:    Expected (expected.toLongLong()): 1483203600000
47:    Loc: [/home/mku/dev/cpp/qgis/QGIS/tests/src/core/testqgsexpression.cpp(1120)]
47: FAIL!  : TestQgsExpression::evaluation(epoch) Compared values are not the same
47:    Actual   (result.toLongLong())  : 1483225200000
47:    Expected (expected.toLongLong()): 1483203600000
47:    Loc: [/home/mku/dev/cpp/qgis/QGIS/tests/src/core/testqgsexpression.cpp(1120)]
47: FAIL!  : TestQgsExpression::evaluation(epoch) Compared values are not the same
47:    Actual   (result.toLongLong())  : 1483225200000
47:    Expected (expected.toLongLong()): 1483203600000

```

**Comment by nirvn** [comment]
@m-kuhn , yep, operations work fine now.

Re test failure, I'd assume it's a timezone issue too.

**Comment by m-kuhn** [comment]
Let's see if it's more robust with

    "epoch(to_datetime('2017-01-01T00:00:01+00:00'))"

**Comment by m-kuhn** [comment]
@3nids the spelling test times out, what would you recommend? Wait for #4180 ?

**Comment by 3nids** [comment]
@m-kuhn merged and I restarted the build

**Comment by nyalldawson** [comment]
This should fix http://hub.qgis.org/issues/10709, right?

**Comment by m-kuhn** [comment]
Not sure

Quote from http://hub.qgis.org/issues/10709#note-3

> It internally handles bigint as double

... this PR does nothing about doubles - but it would be worth testing if the issue is still present.

**Pull request merged**
