### PR TITLE
Geom checker fixes

### PR DESCRIPTION
**Pull request by manisandro**
Various fixes for geometry checker issues spotted over the past few months.

### CODE REVIEW

**Comment by manisandro** [comment]
Hi @nyalldawson , CI is reporting failures due to supposedly incorrect indentation, i.e.

    -  Q_FOREACH( const QgsGeometryCheckFactory* factory, QgsGeometryCheckFactoryRegistry::getCheckFactories() )
    +  Q_FOREACH ( const QgsGeometryCheckFactory* factory, QgsGeometryCheckFactoryRegistry::getCheckFactories() )

(notice the space after Q_FOREACH). If I apply those changes however, `scripts/prepare-commit.sh` reverts them. So which is correct?

**Comment by m-kuhn** [comment]
Do you have `WITH_ASTYLE` enabled in cmake?

**Comment by manisandro** [comment]
Aha, that explains it. Was using an old astyle build. Thanks!

**Comment by manisandro** [comment]
Uh now looks like the compiler itself is actually crashing?

**Comment by nyalldawson** [comment]
Damn... it's the same thing that https://github.com/qgis/QGIS/pull/2666 is hitting. Let me try something...

**Comment by nyalldawson** [comment]
@manisandro can you rebase and push? Should be fixed now.

**Comment by manisandro** [comment]
@nyalldawson Thanks, worked!

**Pull request merged**
