### PR TITLE
[needs-docs] Allow running Style from Project algorithm on a specific project file

### PR DESCRIPTION
**Pull request by nyalldawson**
Instead of forcing the algorithm to always use the current project, add an option parameter allowing users to run the algorithm on a specific project file instead.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@nirvn as discussed in the original PR

**Comment by nirvn** [comment]
Nice one.

**Comment by nyalldawson** [comment]
@nirvn is that an approval to merge?

**Comment by nirvn** [comment]
@nyalldawson , yep, go ahead! And thanks for all the style goodies :)

**Pull request merged**
