### PR TITLE
[processing] Fix qgis:singlepartstomultipart test

### PR DESCRIPTION
**Pull request by arnaud-morvan**
## Description
Fix qgis:singlepartstomultipart test on master

I've create the expected result by executing the test, I've manually opened the file and verified the result, it seems correct.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
@alexbruy : I hope this will fix CI on master, I've create the expected result by executing the test, I've manually opened the file and verified the result, it seems correct.

**Comment by arnaud-morvan** [comment]
@volaya @alexbruy : I've create a script to generate the tests results for aggregate algorithm. I work by executing the tests to generate the results and open the result in QGIS to manually verify that this is what I expect. Do you think we should commit such script to create / overwrite the processing test results.

**Comment by arnaud-morvan** [comment]
Travis return build warnings, but ProcessingQgisAlgorithmsTest pass.

**Comment by nyalldawson** [comment]
I'm merging this to get Travis back online. The test changes still need reviewing or a944f7c4c1010767abb811200686e327040c2d32 needs reverting, but in the meantime we need the tests functional again

**Comment by arnaud-morvan** [comment]
Also note that singleparttomultipart seems to be somewhere duplicated with dissolve, except that it does not combine the geometries, so this results in invalid polygons where two parts have intersections.
Combining could be set as boolean boolean to merge the two algorithms. In Aggregate, I've used combine to avoid returning invalid geometries.

**Comment by alexbruy** [comment]
> I work by executing the tests to generate the results and open the result in QGIS to manually verify that this is what I expect. Do you think we should commit such script to create / overwrite the processing test results.

@arnaud-morvan as I understand, we already use exactly the same approach for creating tests: you run algorithm, verify results and then paste generated test description to the corresponding YAML file.

**Comment by arnaud-morvan** [comment]
Yes, I've created an class that extends BaseAlgorithmTest that generate the tests results and directly overwrite the expected gml file. This method take filters on test name and/or algorithm name. In QGIS I've added the testdata folder as a favorite, so it is really easy to load the source and expected files.

**Comment by arnaud-morvan** [comment]
I do not have to open the dialog, enter the parameters, I just run a command in terminal, and I'm sure to have the same parameters and output file as the test itself.

**Comment by alexbruy** [comment]
I temporarily reverted a944f7c as test constantly fails on Travis while passing locally.

**Comment by arnaud-morvan** [comment]
Seems you should also revert 80c8875 with return id=NULL in same multipolygon as id=1

**Comment by alexbruy** [comment]
Hmm, as I can see there is no need in this, test passes now.

**Comment by arnaud-morvan** [comment]
Yes, I mistake, this is the real error from singleparttomultipart.

**Pull request merged**
