### PR TITLE
 Start moving processing algorithm dialog to c++ 

### PR DESCRIPTION
**Pull request by nyalldawson**
...in an attempt to avoid Python global interpreter locks which block the UI thread. Still a lot to do before this is successful...

### CODE REVIEW

**Comment by luipir** [comment]
Hi @nyalldawson I didn't investigated... in what cases the lock is raised. Is it a good strategy to move GUI parts (ok, just base class) to C++ just to avoid this side effects?

**Comment by nyalldawson** [comment]
@luipir
> I didn't investigated... in what cases the lock is raised. Is it a good strategy to move GUI parts (ok, just base class) to C++ just to avoid this side effects?

Actually, do make this work the whole class needs moving to c++, and we need to ensure that it's not called from Python code.

At the moment this is what is happening:
- python processing code creates and opens the python-based algorithm dialog
- the dialog fires up a python based algorithm, which is started in a background thread
- the python code in the background thread acquires the python global interpreter lock - at this stage all the python gui code is blocked, including the thread which launched the dialog... which is the main gui thread => ui locks until algorithm finishes and releases the global lock

To properly fix this we need to make sure that enough of the gui dialog/toolbox code is moved to c++ so that it's no longer going to block the ui thread while waiting for the lock release. There's still a significant amount of work required to do this :(

**Comment by NathanW2** [comment]
We could move this into C++ over the next couple of releases as it wouldn't
be a API break right?

**Comment by nyalldawson** [comment]
> We could move this into C++ over the next couple of releases as it wouldn't
be a API break right?

Exactly. I've also removed the gui related c++ classes from the docs and marked them as non stable, so we can tweak later. (Ideally they'd be totally private... but then the python processing code couldn't even use them :P )

**Comment by volaya** [comment]
What happens with algorithms written in python that do not use the default UI and have a custom one also written in python? will they have any problems?

**Comment by nyalldawson** [comment]
> What happens with algorithms written in python that do not use the default UI and have a custom one also written in python? will they have any problems?

Yes - until we get to the stage that the widget can be created by python but "owned" by c++. I think for 3.0 I'll add a flag to algorithms which are safe to run in background threads (i.e. the c++ ones), and only run these ones in the background. Others will run in the main thread in a modal dialog so there'll be no issues with python locks.

**Pull request merged**
