### PR TITLE
Fix Processing gdal/ogr tools problems with special chars: fixes #16250

### PR DESCRIPTION
**Pull request by luipir**
## Description
GDAL/OGR tools if run in processing raise ASCII decode error if file name has not ASCII codificable chars.
This patch fix this error reported in: https://issues.qgis.org/issues/16250

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by luipir** [comment]
This PR is only for 2.X. Travis fail on qgis 3.x due th use of unicode stuffs on strs. Travis is happy for 2.x version.
OSX fail is because lacko of brew formulas. A fail not dependent on this PR.

**Comment by luipir** [comment]
@alexbruy @nyalldawson can you review this... it's a simple patch for an annoying error for people using no US filename.

**Comment by alexbruy** [comment]
If I'm not wrong, from similar issue also suffer at least GRASS and SAGA providers. So better to have more generic fix for it.

**Comment by luipir** [comment]
I'll check

**Comment by gioman** [comment]
> If I'm not wrong, from similar issue also suffer at least GRASS and SAGA providers. So better to have more generic fix for it.

just checked, and it seems that there is an issue on Windows for GRASS when a special char is in the path, but is ok if is in the file name. Tested both SAGA and GRASS on Windows and Linux with filenames or paths containing special chars.

**Comment by luipir** [comment]
so... checking the issue for GRASS on win

**Comment by gioman** [comment]
after a further tests, GRASS on Window has also issues with special chars in file names.

**Comment by luipir** [comment]
on Grass/Win the limit is due to use of cmd.exe tu run the grass7_script.bat:
https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/grass7/Grass7Utils.py#L264
The script is correctly wrote with utf-8 chars but cmd.exe has a really limited support to utf-8 (chcp 65001).
a limited workaround limited to a specific encode is do the following command in the upper line:
command = ['chcp', '1252', '&&', 'cmd.exe', '/C ', Grass7Utils.grassScriptFilename()]

**Comment by luipir** [comment]
setting chcp to 65001 does not change any result, but using 1252 (https://msdn.microsoft.com/en-us/library/dd317756(VS.85).aspx) allow processing

**Comment by luipir** [comment]
probably the erro ris still present in qgis master too due the fact that this error is strictly related to cmd.exe limitations

**Comment by luipir** [comment]
investigating if its better to subprocess directly the bat file instead using cmd.exe /C

**Comment by luipir** [comment]
preparing an update of PR where it is possibuile to setup default codec for cmd.exe execution for all commands using subprocess in processing.
Seeting a general processing configuration parameter with the default code page that will be setup before running a cmd.exe command.

**Comment by luipir** [comment]
@alexbruy @gioman I added a generic way to setup CodePage for all widows commands.
CodePage can be set in ProcessingOptions (only when running on windows). Default is 1252 (WesternEurope) code page, btw it' is possibile to setup any kind of available encodings. Not all (most of them) are supported by Windows shell/cmd.
It would be up to the user to find the correct codepage where to run Processing scrips.
UTF-8 code page (e.g. 65001 as Widnow Code Page) is buggy, can be set but does not give any result.
I leaved CodePage configurale to allow other languages (e.g. indonesian, russions) to setup the correct one.

**Comment by luipir** [comment]
as usual fail on 3.0, but this PR is only for 2.18 where travis is happy

**Comment by luipir** [comment]
@alexbruy can you explain this similar PR https://github.com/qgis/QGIS/pull/4931 ?

**Comment by nyalldawson** [comment]
@luipir is this still needed?

**Comment by luipir** [comment]
IMHO I leave decision to @alexbruy. his PR is almost similar #4931... seems we are in a kind of deadlock. IMHO I can close. I also no idea if this PR is still valid or not.

**Comment by luipir** [comment]
tnx @nyalldawson for cleanup :)

**Pull request closed without merging**
