### PR TITLE
Add $vertices support in expression evaluator

### PR DESCRIPTION
**Pull request by strk**
@nyalldawson I see you recently marked those symbols as deprecated, could you please check I'm not walking on a dead road here ? Thank you.

### CODE REVIEW

**Comment by NathanW2** [comment]
IMO this be a function that takes a geometry.

**Comment by strk** [comment]
what do you mean @NathanW2 ?

**Comment by NathanW2** [comment]
Vertex_count($geometry)

**Comment by strk** [comment]
yes but why ? there's already an indirection in `fcnGeomVertices`

**Comment by NathanW2** [comment]
Because I would like to avoid global states and the function can be reused
with other geometry objects eg atlas geom

**Comment by strk** [comment]
Should it be a method of a class, like QgsDistanceArea is used for area, length and perimeter ? (btw, the length exctractor implementation `fncGeomLength` looks bogus as it uses the same method also used for area -- are there tests for those expressions?)

**Comment by NathanW2** [comment]
No I just mean the expression part should be a function not a variable. A
function like to_string etc

**Comment by strk** [comment]
ah, got it. like "centroid" or "bounds", ok, will look at it (and will try to find where to write the help)

**Comment by NathanW2** [comment]
Cheers

**Comment by strk** [comment]
I've added a  resources/function_help/json/num_points file but I don't see it used, how to enable it ?

**Comment by m-kuhn** [comment]
@strk I think the functions are ok. geometry->measure returns area for polygons and length for linestrings. The missing thing is only [documentation](https://github.com/qgis/QGIS/pull/2320)

**Comment by strk** [comment]
Ok, thanks.
Meanwhile I handled to see the help text by re-running cmake.
If everyone is happy I can squash-merge into master ("Ready for merge" label ?)

**Comment by m-kuhn** [comment]
I don't mind squashing in PR's. I actually like it :+1: 

Is it not possible to add this to https://github.com/strk/QGIS/blob/vertices/tests/src/core/testqgsexpression.cpp#L209 ? If in there we also have checks for dump / reload etc.

**Comment by strk** [comment]
I see no other example of a function that takes a geometry in `evaluation_data`.
Could `eval_geometry_calc` functions be also tedted for dump/reload instead ?
https://github.com/strk/QGIS/blob/vertices/tests/src/core/testqgsexpression.cpp#L858

**Comment by nyalldawson** [comment]
@strk nice work - thank you! 

re adding to evaluation data - i'd suggest something like num_points(geom_from_wkt('......')) . Should be nice and easy to test that way...

**Comment by strk** [comment]
I don't know what's wrong here, if I add:
```
      QTest::newRow( "num_points" ) << "num_points(geom_from_wkt('LINESTRING(0 0, 1 0)'))" << false << QVariant( 3 );
```

I get 3 failures (from the same line!):
```
FAIL!  : TestQgsExpression::evaluation(num_points) Compared values are not the same
   Loc: [/usr/src/qgis/qgis-master/tests/src/core/testqgsexpression.cpp(543)]
QDEBUG : TestQgsExpression::evaluation(num_points) got    instead of  int 
FAIL!  : TestQgsExpression::evaluation(num_points) Compared values are not the same
   Loc: [/usr/src/qgis/qgis-master/tests/src/core/testqgsexpression.cpp(543)]
QDEBUG : TestQgsExpression::evaluation(num_points) got    instead of  int 
FAIL!  : TestQgsExpression::evaluation(num_points) Compared values are not the same
   Loc: [/usr/src/qgis/qgis-master/tests/src/core/testqgsexpression.cpp(543)]
```

**Comment by nyalldawson** [comment]
@strk those errors look odd, but shouldn't the expected result be 2?

**Comment by strk** [comment]
Yes, should be 2, but I get the same error if I write 2. 
What does `got    instead of  int` mean ? Sounds like the expression result was a null ?

**Comment by strk** [comment]
Possibly related, but if I write that expression in the layer style widget, I still get 8 classes with different numbers, rather than always the numnber of points from that literal linestring. I guess there's something really wrong with the implementation (fetching geometry from "context" rather than from argument) ?

**Comment by strk** [comment]
Bingo, thanks for asking me to write more tests :)

**Comment by strk** [comment]
squash rebased for final review (also by travis)

**Comment by nyalldawson** [comment]
Looks good, feel free to merge if Travis agrees!

**Comment by strk** [comment]
in trunk as commit 55dbc041a8568238ba158cdb3ca6d2a25356ee79

**Pull request closed without merging**
