### PR TITLE
Fix #48329 PG source select set SQL

### LINKED ISSUE #48329: Data Source Manager Filter Bug
### What is the bug or the crash?

When you click 'open data source manager' button, try to set a 'filter', click 'ok', and then 'add' the added layer will not be filtered. It appears that after the latest update when you try to add a new filtered layer once you click Ok within the window the filter is wiped. This was not an issue on the previous version.

Caveat: The filters can be changed and successfully applied if you are manipulating an existing filtered layer already in your environment (added using an old version). The issue only occurs when trying to set a filter on a new layer.

### Steps to reproduce the issue

1. Open Data Source Manager
2. Find filterable layer, click 'Set Filter'
3. Enter a query/filter, click test 'shows accurate number of features
4. Click 'ok'
5. Click 'add'
6. The layer inserted into the environment no longer has the entered filter, seems to just disappear.

### Versions

3.24.2-Tisler

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by elpaso**
Fix #48329

### CODE REVIEW

**Review by troopa81 — COMMENTED** [review]
Looks good to me, but it should be the same for [MsSQL](https://github.com/qgis/QGIS/blob/master/src/providers/mssql/qgsmssqlsourceselect.cpp#L549) and [Oracle](https://github.com/qgis/QGIS/blob/master/src/providers/oracle/qgsoraclesourceselect.cpp#L496) no?

**Comment by elpaso** [comment]
I don't know, the issue was reported for postgres.

**Comment by elpaso** [comment]
Yes, it is broken for all providers since https://github.com/qgis/QGIS/commit/5f33b4f9b555cc32183f0c383c5f960ae74ac293

**Comment by elpaso** [comment]
@troopa81 all providers should be fixed now (except perhaps for hana, CC  @mrylov )

**Comment by mrylov** [comment]
@elpaso, thanks. I will take a look.

**Review by troopa81 — APPROVED** [review]
Thanks @elpaso

**Pull request merged**
