### PR TITLE
Make single symbol render properties widget similar to other

### PR DESCRIPTION
**Pull request by SrNetoChan**
- removed extra scroll (removed scroll area)
- added a small margin

**Before**
image

**Comparing with other renderers**
image

After
image

### CODE REVIEW

**Comment by SrNetoChan** [comment]
@nirvn Can I ask for your revision? I have talked about this before. Single Symbol renderer IMHO was very strange to use.

**Comment by SrNetoChan** [comment]
@nyalldawson I can revert that and try to fix the other renderers.

**Comment by SrNetoChan** [comment]
Also wanted to figure out a way of not wasting space below color.The space is because of markers and lines extra options, but looks bad.

**Comment by nyalldawson** [comment]
Another suggestion - I've "fixed" these margins multiple times before but the changes always get wiped out by Qt Designer. I'd suggest instead of fixing them in the UI file, you instead set the margins in code after the ui file is loaded. This will lock in these fixes and prevent anyone from wiping them out with future modifications to the forms...

**Comment by DelazJ** [comment]
> Also wanted to figure out a way of not wasting space below color.The space is because of markers and lines extra options, but looks bad.

Yes that one is not nce and space consuming and does not really follow [qgis dev rules](http://qgis.org/en/site/getinvolved/development/qgisdevelopersguide/hig.html) : "Widget stacks should be avoided if at all possible. They cause problems with layouts and inexplicable (to the user) resizing of dialogs to accommodate widgets that are not visible."
btw, it'd be nice to have #3945 reviewed because i'm afraid there's conflicts between the 2 PRs. Thanks

**Comment by SrNetoChan** [comment]
@nyalldawson 

@nyalldawson I noticed that Qt Designer changed a bunch of lines even that I only change the margins values

> I'd suggest instead of fixing them in the UI file, you instead set the margins in code after the ui file is loaded.

Not sure how to do that. Can you guide me in one form?

**Comment by nyalldawson** [comment]
Here's an example: https://github.com/qgis/QGIS/blob/0a63d1f2c2b028360a6ac1eaf8512f00524b3cec/src/app/qgsbookmarks.cpp#L45

After the setupUi() call just add:

    my_layout->setMargin(... )

(and maybe setContentsMargins depending on appearance). You can get the name of the layout (eg `my_layout` from designer.

**Comment by SrNetoChan** [comment]
@nyalldawson sorry to get back to this so late. I may need you assistance on this.

Not being a C++ developer (or a developer at all), how can I tell where this ui file is used?

Using grep I could tell that it was used in I found it being used `qgssymbolselectordialog.h`.

Then I searched for qgssymbolselectordialog.h and got a bunch more results. Must I search inside all those results for "my_layout" ?

Thanks!

**Comment by SrNetoChan** [comment]
@nyalldawson, @alexbruy PR solves the margins problem part that I was not able to do myself. Is it ok to merge this PR now?

**Comment by alexbruy** [comment]
Manually merged, including setting margins in code instead of .ui file

**Pull request closed without merging**
