### PR TITLE
Fixes a wrong dpi resolution in images exported from composer

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes #18132

Slightly revised version of https://github.com/qgis/QGIS/pull/6524, thanks to @agiudiceandrea

### CODE REVIEW

**Comment by nyalldawson** [comment]
@agiudiceandrea I've cherry-picked your fix here and slightly tweaked the logic so that a more accurate dpi match should be obtained. Thanks for your hard work here!

**Comment by agiudiceandrea** [comment]
Thank you @nyalldawson 
Do you think it will be merged it time for 2.18.18?

**Comment by agiudiceandrea** [comment]
Hi @nyalldawson
it seems the commits were not merged it time for 2.18.18. When you plan to merge them?

**Comment by agiudiceandrea** [comment]
Dear @nyalldawson 
as you can see, your commit doesn't pass some tests:

```
Test #267: PyQgsServer .............................***Failed
FAIL: test_wms_getprint_basic (__main__.TestQgsServer)
FAIL: test_wms_getprint_grid (__main__.TestQgsServer)
FAIL: test_wms_getprint_rotation (__main__.TestQgsServer)
FAIL: test_wms_getprint_scale (__main__.TestQgsServer)
FAIL: test_wms_getprint_selection (__main__.TestQgsServer)

Test image and result image for ___
Expected size: 3507 w x 2480 h (8697360 pixels)
Actual   size: 3508 w x 2480 h (8699840 pixels)

Expected image and result image for ___ are different dimensions - FAILING!
```

This is due to your modified dpi logic that change how image size is calculated as well as the dpi resolution.

So now the reference images are 1 pixel less wide then the tests result images. Moreover, reference images are 96 dpi, but tests result images are 300 dpi.

Could you please fix (replacing the reference images) this in order let your commit pass the tests, or reopen my original pull request that previously passed all the tests?

Thank you.

**Pull request closed without merging**
