### PR TITLE
[cmake] use single macro QGIS_ADD_TEST and modernize cmake code

### PR DESCRIPTION
**Pull request by 3nids**
all duplication of the macro have been removed
the test targets are now named test_[module]_[test-name] which helps to sort them in QGIS

### CODE REVIEW

**Comment by m-kuhn** [comment]
Very nice move!
Do we need the `core` prefix? I could imagine it makes it harder to use autocomplete to build or test.

**Comment by alexbruy** [comment]
If some naming convention introduced, probably it should be applied to plugin tests too, to make things consistent.

**Review by m-kuhn — APPROVED** [review]
Looks good.
Let's merge this soon to avoid conflicts. Any follow up on tests can be easily added later on.
Thanks

**Comment by elpaso** [comment]
@3nids nice move, but now Qt Creator shows all old (invalid) targets too, do you have any idea if it's possible to delete them automatically?

**Comment by 3nids** [comment]
cleaning should do the trick, no?

**Comment by elpaso** [comment]
I tried to clean and QT Creator keeps the old targets. They can be deleted by hand but they are hundreds ...

**Comment by 3nids** [comment]
clean the cmake configuration?

**Comment by elpaso** [comment]
I didn't try that because I'm afraid to loose all the tweaks I have done to the cmake config. I'll see if I can make a backup of .user.

**Comment by elpaso** [comment]
Running "Clear CMake configuration" didn't help either.

**Comment by 3nids** [comment]
not sure how, but they disappeared from my list.
A complete removal of the build folder would be the ultimate try ;)  If that doesn't work, there's something wrong!

**Pull request merged**
