### PR TITLE
[Qt5] Fix Qt5 build with override specifier

### PR DESCRIPTION
**Pull request by naihil**
QObject::connectNotify( const char \* ) in Qt4 changed to QObject::connectNotify( const QMetaMethod & ) in Qt5.

### CODE REVIEW

**Comment by naihil** [comment]
@m-kuhn Can you look at this?

**Comment by nyalldawson** [comment]
@naihil Why not just remove these methods? From the looks of it they were just implemented for debugging purposes, and it's safe to remove them. I'd rather remove them then have all the #ifs.

**Comment by naihil** [comment]
@nyalldawson Yeah, it would be better. Can you remove them?

**Comment by m-kuhn** [comment]
@nyalldawson That's the kind of things you want to find with the `override` keyword. Good job.

Fixed in 2e9cc1a4f

**Pull request closed without merging**
