### PR TITLE
[bug] Use a more realistic map extent to perform filtering in the layout legend.

### LINKED ISSUE #43050: Print layout legend "Only show items inside linked map" does not calculate correctly for rotated map.
Using QGIS 3.18.2 for windows 

When using the "only show items inside linked map" checkbox to only show visible items on the legend in a print layout, the items shown on the legend are not calculated correctly for rotated maps. It appears the items shown are calculated as they would appear if the map rotation were set to zero degrees.

Image below is a print composer with two identical maps with legends linked to them. One has a rotation of 90 degrees and does not show the correct items on the legend, and the other has a rotation of 0 degrees and shows the correct items. Files are attached.

image

[Test.zip](https://github.com/qgis/QGIS/files/6410063/Test.zip)

### PR DESCRIPTION
**Pull request by roya0045**
## Description

Fix #43050

The default behaviour sent a null geometry and triggered https://github.com/qgis/QGIS/blob/a4e4997e72c91ebeed9eb730d6b84616770ee31c/src/core/qgsmaphittest.cpp#L131

I think it would make more sense to have that as a backup instead of a 'valid' approach.

Though the current check is not perfect (seems to have some blindspot ) but its already an improvement.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Can you introduce a test too?

**Comment by roya0045** [comment]
> Can you introduce a test too?

I knew you'd ask ;) I'll see if I have the time today or over the weekend.

**Comment by roya0045** [comment]
Map was bigger than expected, but it works (the pale blue part is out of range of render).

**Comment by nyalldawson** [comment]
@roya0045 that test isn't working correctly -- I've tried running it with the fix disabled and it still passes

**Comment by roya0045** [comment]
@nyalldawson Thanks for the headsup, I tried to recreate my manual test, I'll try to find a better test, thanks!

**Comment by roya0045** [comment]
I've reworked the test, it should be reliable now, I plan on resubmitting this branch as a PR on my queue gets smaller.

**Pull request closed without merging**
