### PR TITLE
More explicite message when snapping fails

### PR DESCRIPTION
**Pull request by DelazJ**

### CODE REVIEW

**Comment by 3nids** [comment]
Isn't it too much text for a message?
I'm not sure I want to have such long text everytime.

**Comment by DelazJ** [comment]
@3nids This is almost what is stated when using the "Rotate Point Symbols". You can give it a try. and once you get it and know why it fails, I'm not sure you'll often get it.

**Comment by 3nids** [comment]
Well, the message is much longer, and I don't like it very much. I would rather be in favor of shrotening the other one. 
Also the level is CRITICAL in rotate point symbol, and I don't see any reason why (should be WARNING).

I am not the whole QGIS documentation should be written in message bars.

**Comment by 3nids** [comment]
any other opinion?

**Comment by NathanW2** [comment]
Yeah too long IMO.  Consider adding a Open Options button to the message
bar that opens the options dialog to the right tab instead of a long
message, and/or a More Info button.

The More Info could have a longer description on what is wrong and how to
fix it.

>> Also the level is CRITICAL in rotate point symbol, and I don't see any
reason why (should be WARNING).

Yeah CRITICAL is the wrong level for this kind of stuff. That should really
only be used when something bad can/has happened.

**Comment by m-kuhn** [comment]
How's this? "No snapping target found on layer [xxx] with a search radius of [yyy]. <link>Change search radius</link>."

**Comment by 3nids** [comment]
better to me.

**Comment by m-kuhn** [comment]
@DelazJ any progress on this?

**Comment by DelazJ** [comment]
@m-kuhn Sorry I am on something else so didn't have time to dig that. But I'm afraid my C++ skills (~ 0) are not yet sufficient to implement such fix. If someone else can take it... (I'd be interested in the fix code, however)

**Comment by m-kuhn** [comment]
Would be nice to have that but in this case that should be a feature request and not a pull request.

**Comment by DelazJ** [comment]
I open a feature request for it https://hub.qgis.org/issues/13864

**Pull request closed without merging**
