### PR TITLE
Delim text ui crs

### PR DESCRIPTION
**Pull request by ccrook**
## Description
Two commits to enhance the source UI for the delimited text provider to improve the user experience

* Added CRS selector to provider widget to improve workflow.  Otherwise adding layer can invoke CRS selection which adds extra dialog and step to process, and is clumsy
* Cleared the selected file after a layer is added (or at least after the addVectorLayer signal is emitted).  This makes it more obvious to the user that something has happened when the layer is added.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] ;Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] N/A New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

Note 1: commit adding CRS selection to delimited text source widget may require small documentation update.  Commit message was written and pushed before seeing request for [needs-docs] in message
Note: built on 16.04 for which astyle.sh does not work using default version of astyle - complains that it needs version 3.0 or greater.

### CODE REVIEW

**Comment by nirvn** [comment]
+1 to merge these fixes now.

The "select projection" dialog popping up is very bad UX (and can actually pop up twice under some circumstances). 

Nice job on fixing the focus ordering too.

**Comment by ccrook** [comment]
@nirvn Thanks for extraordinarily quick response Mathieu!  I was going to ask for confirmation from a dev before committing as haven't committed anything for a while, so appreciate your message.  Will await comletion of travis CI and then commit if OK (I don't think this impacts on any tests)

**Comment by nirvn** [comment]
@ccrook , BTW, it'd be nice to get rid of this horizontal spacer here: https://github.com/ccrook/Quantum-GIS/blob/25c4fe7c833c2dede6b7a748f7cb1fd8f0ba0c76/src/ui/qgsdelimitedtextsourceselectbase.ui#L121 , it's not needed, and reduces the horizontal space for the layer name text input.

**Comment by ccrook** [comment]
@nirvn Good observation thanks, it will be removed.

**Pull request merged**
