### PR TITLE
Be careful with requesting evaluated default values

### PR DESCRIPTION
**Pull request by m-kuhn**
We do not need a new evaluated value all the time

Fix #16545

### CODE REVIEW

**Comment by nyalldawson** [comment]
This isn't an issue on master anymore, is it?

**Comment by m-kuhn** [comment]
Not sure. Need to check

**Comment by nyalldawson** [comment]
> Not sure. Need to check

It shouldn't be. At least not if I did my job correctly :P

**Comment by m-kuhn** [comment]
The second one is only pg internals, that might need porting (and also is part of this effect)

**Comment by 3nids** [comment]
@m-kuhn I think this causes a nasty issue. In a plugin I am adding feature programmaticaly (in transaction mode) and the default never gets evaluated. Instead it tries to insert it as text (`generate_oid('xxxx')`).

**Comment by m-kuhn** [comment]
Could you write a test that demonstrates this behavior?
Would it make more sense to let the provider get a default value if an invalid QVariant() is specified and the form would take care of preparing the attributes like this when required?

**Comment by 3nids** [comment]
trying here #5377

**Comment by 3nids** [comment]
+1 to test for invalid qvariant and get the default value in such case

**Pull request merged**
