### PR TITLE
[processing] Drop unmainted saga provider from QGIS install

### PR DESCRIPTION
**Pull request by nyalldawson**
This provider has not been maintained and does not work with newer SAGA versions. Users are encouraged to use the 3rd-party "Processing Saga NextGen" plugin instead.

After many many years of discussion, it's time for the inbuilt provider to go!

### CODE REVIEW

**Comment by nicogodet** [comment]
Close https://github.com/qgis/QGIS-Enhancement-Proposals/issues/230 ?

**Review by alexbruy — APPROVED** [review]
Finally!

**Comment by alexbruy** [comment]
@nyalldawson should we also close all SAGA tickets now?

**Comment by nyalldawson** [comment]
@alexbruy good idea!

**Pull request merged**
