### PR TITLE
add missing QgsExpression import when exporting model as Python script

### PR DESCRIPTION
**Pull request by Gustry**
## Description

Same kind of issue https://github.com/qgis/QGIS/issues/32004
Related PR https://github.com/qgis/QGIS/pull/32057

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by rldhont** [comment]
Hi @Gustry, master is in hard freeze, can you manually backport to release-3_4 ?

**Comment by Gustry** [comment]
@rldhont No need to backport, it doesn't exist in 3.4.

I will fix the test.

**Comment by rldhont** [comment]
ok @Gustry thanks

**Comment by rldhont** [comment]
Needs backporting in 3.10.1

**Pull request merged**
