### PR TITLE
force reference time (current) to be UTC for mesh layer

### PR DESCRIPTION
**Pull request by vcloarec**
Force the reference time for mesh layer to be in UTC in any cases

### CODE REVIEW

**Comment by nyalldawson** [comment]
This will likely break the temporal controller, which assumes local times are used everywhere...

**Comment by vcloarec** [comment]
> This will likely break the temporal controller, which assumes local times are used everywhere...

hmmm, I believed it was UTC. I had seen in the temporal controler widget, the time specification is UTC :
https://github.com/qgis/QGIS/blob/5936249b722b514a741adb22ffab8639a943c4a6/src/ui/qgstemporalcontrollerwidgetbase.ui#L416

Maybe I miss something...

**Comment by nyalldawson** [comment]
Eh... this is getting too complex/confusing. I think we're going to have to "rip off the bandaid" and just move to always showing timezone information for datetime values everywhere, and then make sure the expression engine handles this correctly. Complicated... :(

**Comment by vcloarec** [comment]
I don't know exactly how other layers work with temporal, but for mesh layer, it is quite simple as time zone is not supported by MDAL. So whatever if local or UTC, as long as we know which one is it...  
For now and before this PR, for mesh layer, it seems everything is ok for now except when the reference time of the data is invalid and the the reference time is set to current date with time 00:00. As this time is set to local, there is an offset depending of the local time zone that some time leads to a rendering issue.
This PR only force this default time to avoid this issue and there isn't consequences for other part of QGIS.

**Comment by vcloarec** [comment]
@nyalldawson , Does this PR is really problematic?

**Comment by PeterPetrik** [comment]
If I understand it correctly...

1. time slider is in local time (implemented)
2. user should see time zone (not-implemented) everywhere where he sees time
3. data providers should give time to time controllers in local time (right now every provider does differently, mess?)

so if this is way forward, we should rework this PR so mesh data provider return time in local timezone? @nyalldawson

**Comment by vcloarec** [comment]
>     1. time slider is in local time (implemented)

For now, time slider seems to be in UTC... 
But, before QGIS could support time zone, can we implement it in local time? In other words, set the time edit in local specification could break anything for other layer format? If we can implement temporal controller to be local, this is a good point for mesh layer because we don't need anymore the workaround that consist to force the time to be in UTC.
What about a combo box to simply choose between UTC and local for the time slider?
In this case, for mesh layer, no offset if the temporal controller is set to local, and an offset depending of the time zone of the user if the temporal controller is set to UTC (because for MDAL, the time is supposed to be local).

**Comment by vcloarec** [comment]
not stale

**Comment by vcloarec** [comment]
@nyalldawson 
Can we do something for this?
Without that, formats that do not have native reference time have always displaying issue when just loaded : the datasets is not displayed or with the wrong dataset.
I understand that the choice between UTC or local can make troubles, but for mesh layer, we have to now which spec is it in the time controller to accord the date/time for the loaded mesh and avoiding offset between displayed time and dataset time.
If for now, time controller keep the UTC spec, we have to force the UTC for mesh layer.
It will be really good to have this issue fixed for the next 3.14 release.

**Comment by nyalldawson** [comment]
Ok - let's merge and deal with the fallout when it happens :)

**Comment by nyalldawson** [comment]
(can we skip the backport for now though?)

**Review by nyalldawson — APPROVED** [review]

**Comment by vcloarec** [comment]
> can we skip the backport for now though?

that is for the backport I insisted heavily...

**Pull request merged**
