### PR TITLE
[Server] WMS GetLegendGraphics refactoring

### PR DESCRIPTION
**Pull request by pblottiere**
## Description

The aim of this PR is to propose a cleaner version of the WMS GetLegendGraphics function defined in the server:

- QgsProject singleton is not used anymore
- XML parsers are not used either
- the temporary `getMapOld` method is removed

Moreover, some tests have been added.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Just looking at these test images - the fonts are very narrow, and will be subject to a lot of cross platform rendering differences. Can you bump up all the test font sizes a lot and use a bold font to avoid this? 

I also noticed that some of the mask images in server (including in this PR) look like they've become too permissive and I wonder if they are still testing what the unit test is designed to catch. Bumping up the font size across the board in the server tests and regenerating the mask images should fix this.

**Comment by pblottiere** [comment]
@nyalldawson Thanks for your advice! I updated images for GetLegendGraphics tests accordingly. I'll clean mask images for GetMap tests in a separate PR.

**Review by rldhont — APPROVED** [review]
thanks @pblottiere

**Comment by rldhont** [comment]
@pblottiere I have merged #4687 can you rebase to resolve conflicts ? Thanks

**Comment by pblottiere** [comment]
>  can you rebase to resolve conflicts ?

Done

**Comment by rldhont** [comment]
Thanks @pblottiere

**Pull request merged**
