### PR TITLE
load layers in parallel threads when opening project

### PR DESCRIPTION
**Pull request by vcloarec**
With this PR, QGIS loads layers that support it in parallel when loading a project.

Before this PR, all  layers of a project are loaded in the main thread, and a project with many remote layers could take a lot of time to load completely. 

With this PR layers that support parallel loading (GDAL and PostgreSQL providers, for now) will be loaded with different worker threads and project loading could be significantly accelerated.

If needed, this parallel loading can be deactived in the advanced settings.

image

### CODE REVIEW

**Comment by nyalldawson** [comment]
Nice!

Question: why do we need the new option here? Why not just make this always on by default?

**Comment by nirvn** [comment]
@vcloarec , I was coming in to comment on whether the option is needed or not but @nyalldawson beat me to it :)

**Comment by vcloarec** [comment]
@nyalldawson @nirvn well .. good question ... maybe there could be some case where it could create problems...

For example, during test with several COG layers in the same remote server, loading with only one thread was shorter that with one thread per layer. Investigating on it leads me to think that come from a overhead or a limitation of the server that had received several requests from the same client at the same time.

Not a big issue, but maybe other issue could happen. That why I think it is more careful to have it as option for now.

**Comment by nirvn** [comment]
Generally speaking I'm -1 for such an option. For one, it'll make it even more difficult to debug user issues as this adds a new behavior that might be on or off.

If there are issues with multi threaded project load, let's address those.

If this is not ready for prime time then I'd prefer a qsetting key that can be turned on or off in the advanced settings panel.

**Comment by nyalldawson** [comment]
> Not a big issue, but maybe other issue could happen. That why I think it is more careful to have it as option for now.

IMO we should either globally enable this or hide it behind a hidden qsettings key for now. I really don't think something like this should be a user visible setting.

We could add a hidden QSetting key, default it to on for now, and easily switch the default back to off for final 3.32 release if there's substantial issues/risk deemed at that time.

**Comment by pathmapper** [comment]
> We could add a hidden QSetting key, default it to on for now, and easily switch the default back to off for final 3.32 release if there's substantial issues/risk deemed at that time.

For QGIS Server such a key would have to be added manually to the used ini file, right?

**Comment by vcloarec** [comment]
Changes are done to have parallel loading by default and settings related are now id advanced settings : 

image

**Comment by vcloarec** [comment]
with default parallel loading, the parallel loading is going through all tests and issues are coming!
Good thing! Better to fix them now that after release.

So, first one, a deadlock happens with OGR provider related to the global mutex of OGR and another mutex. The last commit is a fix for this issue that seems to work, but, for now I am not convinced it is the proper way to fix it, I don't know enough OGR provider right now, I need to look deeper...

Second issue, it come from a field I know even less, QGIS server... I have also to look closer, but maybe the solution is to have a `Qgis::ProjectFlag::NotAllowParallelLayerLoading`  to not allow parallel loading for server.

**Comment by Gustry** [comment]
Thanks for this work.

> Second issue, it come from a field I know even less, QGIS server... I have also to look closer, but maybe the solution is to have a Qgis::ProjectFlag::NotAllowParallelLayerLoading to not allow parallel loading for server.

Maybe @dmarteau @elpaso or @rldhont have some ideas ?

**Comment by rldhont** [comment]
About QGIS Server, it seems that it does not wait for all layers loaded before it performs the request.

If loading layers in parallel speeds up the project loading, it will be great to have it in QGIS Server.

**Comment by vcloarec** [comment]
Almost all of the issues come from OGR provider. It seems that this provider has some problems with provider creation with parallel threads. I investigated on a case with GPKG driver, and there are some issues related to crs information or this error message `layer 'XXX' is not registered in gpkg_contents` when two thread try to create providers on the same GPKG file.

So for now, OGR support for parallel loading is not enabled anymore.

The last test fixed for QGIS server is related to QgsApplication that was not instantiated in the test.

**Comment by rouault** [comment]
> I investigated on a case with GPKG driver, and there are some issues related to crs information or this error message `layer 'XXX' is not registered in gpkg_contents` when two thread try to create providers on the same GPKG file.

It could potentially be related to all the global variables at top of qgsogrproviderutils.cpp which try to maximize the use of the same GDALDataset object when loading several layers from a same dataset. Normally they are mutex protected, but they're good candidates to investigate

**Review by wonder-sk — APPROVED** [review]
We have done two rounds of reviews of the code previously, with a fair amount of testing - I believe this should be good to go...

**Comment by dmarteau** [comment]
Is there some metrics about the loading time with/without the feature ?

**Comment by weca-theo** [comment]
I've downloaded 3.32 from: https://download.qgis.org/downloads/?C=M;O=D

Some early observations, albeit not on an ideal network, an on a VM with only 2 cores (4 threads max).
QGIS file (created in v3.22.8 LTR), with ~100 PostGIS layers:
-parallel loading OFF: 1min 20secs total load
-parallel loading ON, max 2 threads: 2min 20secs total load
-parallel loading ON, max 4 threads: 2min 20secs total load (seems to load quicker, but then struggles right at end).

I'll try again when network is more stable. I'll also try later on a machine with 4 cores (max 8 threads).

Also, shouldn't this setting default to the maximum **possible** thread use for the running machine? Otherwise this PR isn't being used to its full advantage, and each user has to manually dig into the options to increase the setting. I can't save this setting to the project file.

**Comment by vcloarec** [comment]
Hi,
This should be set by default to the "ideal thread count" (see https://doc.qt.io/qt-6/qthread.html#idealThreadCount).

To know this value from QGIS, you can use the Python console with `QThread.idealThreadCount()`
I could be interesting to know what is this value with a VM.

**Comment by weca-theo** [comment]
@vcloarec thanks, useful to know.
The VM ideal count is 2.
image

Why does this PR use 'ideal' instead of 'max' (if max even exists)? Given that project load is a theoretically short one-off process. Or is 'ideal' used to free up threads for whatever else is running on the machine at the time?

I'll continue my testing. Including a quick test taken just now:

-parallel loading ON, max 4 threads: 1min 10secs total load (the blue QGIS loading bar reaches 100% in 30 seconds, then the application hangs for a while with spinny mouse cursor, then boom- the map loads).

**Comment by weca-theo** [comment]
These parallel loading options were available back in QGIS 3.22.8 (at least!):
image

What's different this time around? I'm not sure I understand. I'm also not seeing any performance improvement (will post testing results later, QGIS file with 100 remote PostGIS layers, Azure).

**Comment by saberraz** [comment]
The one you are looking at is slightly older than 3.22, I think this has been there since 2.4 over the past 10 years :)
https://www.lutraconsulting.co.uk/projects/qgis-mtr/

**Comment by weca-theo** [comment]
> The one you are looking at is slightly older than 3.22, I think this has been there since 2.4 over the past 10 years :) https://www.lutraconsulting.co.uk/projects/qgis-mtr/

It's 3.22.8:
image
But my question is, what is different between >3.32 and <3.32? If the Options interface shows the same choices about parallel loading. It's not clear to me.

**Comment by weca-theo** [comment]
Back to 3.32.0 however, I'm not seeing any improvement on project load times. I've run a number of back to back tests on the same .qgz file, using QGIS 3.32.0. I've also added a couple of QGIS 3.22.8 tests for comparison:
image

90% of layers are sourced from a remote Azure PostgreSQL server.

**Comment by vcloarec** [comment]
> The variations in the graph for each scenario are likely due to network performance variations

If your network has performance variation when loading than one layer in parallel, maybe the lack of improvement come from here. There may be network congestion or network overload when several layers are loading in parallel.

To check how long is to load each layer you can look at the "Debugging/Development Tools" --> "Profiler"  --> "Project Load" category.

> But my question is, what is different between >3.32 and <3.32? If the Options interface shows the same choices about parallel loading. It's not clear to me.

Because you have settings in 3.32 version that you have opened (and changed settings?), settings are also shown with other version (settings are saved for all version of QGIS). But these settings will have no effect for version before 3.32.

**Comment by agiudiceandrea** [comment]
@vcloarec, have you seen the issue report https://github.com/qgis/QGIS/issues/53621?

**Comment by vcloarec** [comment]
@agiudiceandrea, OK, thanks to point it.
 Indeed, it seems there are some limitation for PostgreSQL connexion count in some cases. 
As there is one connection per thread and each PostgreSQL provider are created on a different thread that lead to have on connection per PostgreSQL layer. Right now, I don't see any simple way to fix this issue. 

@nyalldawson , it could be the "substential issue" that pushes to put this option off by default ? (see https://github.com/qgis/QGIS/pull/53069#issuecomment-1543267286).
(ping @wonder-sk)

**Comment by weca-theo** [comment]
> @agiudiceandrea, OK, thanks to point it. Indeed, it seems there are some limitation for PostgreSQL connexion count in some cases. As there is one connection per thread and each PostgreSQL provider are created on a different thread that lead to have on connection per PostgreSQL layer. Right now, I don't see any simple way to fix this issue.
> 
> @nyalldawson , it could be the "substential issue" that pushes to put this option off by default ? (see [#53069 (comment)](https://github.com/qgis/QGIS/pull/53069#issuecomment-1543267286)). (ping @wonder-sk)

could you include some logic in the code that, on project load, checks the PostgreSQL `max_connections` amount against the .qgz layer/PG provider count? ie. IF max_connections > (layer_count * n): parallel = True (or that kind of thing.). Although this would have to scale for the number of separate users connecting.

**Comment by gioman** [comment]
@vcloarec my personal test: large project with tens of PostGIS layers, old laptop (2 core, 4 threads). QGIS 3.32.0 on Windows 10

With this OFF

image

It takes about 3.5 minutes to load the project. The project has some missing layer, but after showing the "missing layer" dialog it does not take more than a few seconds for the project to be fully loaded and usable.

With the above ON

it takes about 7 minutes to get to the "missing layer" dialog and after that I waited up until about 20 minutes, then I realized that QGIS brought down to its knees my PostgreSQL instance.

Not sure this was meant to play this way.

**Comment by weca-theo** [comment]
@gioman 3.5 minutes to only load 'tens' of layers makes me think the layers or network are sub-optimal here. My tests were ~100 PostGIS layers hosted in Azure and connected to via a corporate VPN- my project took ~2mins to load (3.32.0).

**Comment by gioman** [comment]
> @gioman 3.5 minutes to only load 'tens' of layers makes me think the layers or network are sub-optimal here. My tests were ~100 PostGIS layers hosted in Azure and connected to via a corporate VPN- my project took ~2mins to load (3.32.0).

@weca-theo I said "tens" but are more like 200 (on a remote server, direct connection). Also I used a underpowered laptop on purpose to see if I could amplify even more the differences in loading speed. But of course it seems there is something wrong.

**Comment by vcloarec** [comment]
@gioman @weca-theo , here a fix for this issue: #53812. If you can test it, it would be wonderful.

**Comment by weca-theo** [comment]
> @gioman @weca-theo , here a fix for this issue: #53812. If you can test it, it would be wonderful.

Hi @vcloarec , sorry if this is a noob question, but do I need to wait for QGIS 3.32.1 to start testing? Or is the fixed backported into 3.32.0? If the latter, I can download the file again. Sorry, not sure how this all works.

**Comment by vcloarec** [comment]
@weca-theo 
The fix is not backported to 3.32.0. It will be available for QGIS 3.32.1. 
Waiting, solutions are : 
- compile yourself QGIS (from my branch now, or from the master branch when it will be merged)
- waiting the fix is merged to try with the nightly build

**Comment by weca-theo** [comment]
> @weca-theo The fix is not backported to 3.32.0. It will be available for QGIS 3.32.1. Waiting, solutions are :
> 
> * compile yourself QGIS (from my branch now, or from the master branch when it will be merged)
> * waiting the fix is merged to try with the nightly build

I haven't done either, but is this the process for installing a nightly build?:
https://wiki.tuflow.com/QGIS_Nightly_(Dev)_Build

I may not have time, but will let you know if I do. Perhaps @gioman can also test. :)

**Pull request merged**
