### PR TITLE
Allow 3.4 to build on Proj 6/GDAL 3.0

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR fixes the build of 3.4 LTR on newer Proj/GDAL library versions.

One big change is that we now have to package internal versions of the older gdal crs .csv files. These have been removed in GDAL 3.0, yet we depend on them for population of the internal QGIS srs database.

There may be further follow up changes required, but this gets QGIS building and the tests passing locally for me.

### CODE REVIEW

**Comment by saberraz** [comment]
Does this mean that the next 3.4.x version will be shipped with the new GDAL/Proj?

**Comment by nyalldawson** [comment]
@saberraz  Not sure, it just means it's possible to do so. But that choice is up to @jef-n.

My 2c - I'd rather play things safe and wait for at least another month.

**Comment by saberraz** [comment]
I'd prefer not to update those packages for the LTR.

**Comment by NathanW2** [comment]
Agree.  We should not move LTR with new 3rd party packages

**Comment by jef-n** [comment]
I think the files should only be installed if we build against GDAL3 - we want to be in sync with the local GDAL.

**Comment by jef-n** [comment]
> I'd prefer not to update those packages for the LTR.

For OSGeo4W there will only be one GDAL and one PROJ.  So either we switch for LTR and LR or we don't.

**Comment by NathanW2** [comment]
Oh that is a bugger because it makes it really tricky to have people test
these updates in master without not breaking LTR if something is wrong.

**Comment by nyalldawson** [comment]
I don't think we need to be too concerned with upgrading the LTR to proj 6 and gdal 3.0. The changes here are really quite minimal, since we still use the deprecated proj 4 API. 

I definitely think we WILL need to upgrade the LTR to gdal 3.0/proj 6.1 at some stage. The consequences of running outdated versions of these libraries and missing out on upstream fixes is too critical to do this.

I just think we should wait another month before doing this. That'll let us use the fast-moving platforms which have already upgraded as a test so that when we DO upgrade 3.8 and the LTR to 3.0/6.1 hopefully any regressions will already have been identified and fixed.

**Comment by nyalldawson** [comment]
@jef-n 

> I think the files should only be installed if we build against GDAL3 - we want to be in sync with the local GDAL.

Are you ok with them ALWAYS being installed to the resources folder, but only being used on gdal >= 3.0?

**Comment by rouault** [comment]
> For OSGeo4W there will only be one GDAL and one PROJ. So either we switch for LTR and LR or we don't.

In an ideal world, QGIS 3.4 would use GDAL 2.4 and PROJ 5.2 to minimize risks, and inconsistent behaviour where reprojections done by QGIS 3.4 using PROJ strings (which will lack towgs84 clause in a number of situation when used with GDAL 3.0) will give different (incorrect) results as reprojections done by GDAL 3/PROJ 6 with EPSG codes.
I guess your issue is that the infrastructure of OSGeo4W and/or build recipees of QGIS 3.4 for OSGeo4W are not ready for having different versions of GDAL and PROJ for QGIS 3.4 and QGIS 3.8 ? I do think it could be good for the QGIS project to fund the effort needed to be able to have different versions of the underlying libs used by QGIS. That might be of use for later similar situations as well.

That said, in the not ideal world, @nyalldawson approach is probably the best compromise if one absolutely needs to build QGIS 3.4 against GDAL 3

**Comment by nyalldawson** [comment]
Thanks @rouault !

The reality is that we won't always be able to dictate the library versions for 3.4. We can for osgeo4w, because we (well, @jef-n) controls that infrastructure, but there's many other platforms where we have no say in this. Including a bunch of wild-west ecosystems where people upgrade stuff just to see what other stuff they can break.... (\*cough\* homebrew \*cough\*).

We've still got at least 6 months left to support 3.4, so sooner or later we'll need to make it usable on the newer libraries, even if that means a bunch of short-term hacks and workarounds to make it work with this.

The only other option is dropping the LTR support early, but I don't think that's possible/a good idea.

**Comment by PeterPetrik** [comment]
for Mac installer, this could be solved by moving to conda instead of homebrew. However this is quite a work (let say in range of 1-2 weeks). For now we are stuck with homebrew and one version of the libraries for everything

**Comment by nyalldawson** [comment]
Any objections to merge?

**Review by PeterPetrik — APPROVED** [review]

**Comment by dakcarto** [comment]
@nyalldawson, thanks for your work on this, especially the backport!

@PeterPetrik, I am close to getting an OK from my employer (I think) to release all of my work on [OSGeo-Forge](https://github.com/osgeo-forge) for Windows and macOS. Much of this was/is in a private repo, excepting some recipes you see on OSGeo-Forge. This should help considerably with the `conda` dependencies effort, regardless of final packaging methodology.

Once all of that is released, or even before, I'd be willing to help with the migration of the bundled Mac Packager to `conda` dependencies.

**Comment by PeterPetrik** [comment]
@dakcarto thanks for update. Any help is highly appreciated, please ping me on peter.petrik@lutraconsulting.co.uk when you want to chat about the possible conversion to conda.

**Pull request merged**
