### PR TITLE
[gui/hidpi] vectorize advanced digitizing toolbar icons

### PR DESCRIPTION
**Pull request by nirvn**
Obligatory before vs. proposed screenshot:
untitled

While this is mostly about vectorizing bitmaps, one icon was significantly changed: the merge attribute action. The previous image made little sense (glue over a blue bar?!), hopefully this new proposal works better. @nyalldawson , that should make you happy :smile: 

This takes care of insuring all of QGIS' toolbars are using vector images. Wouhou!

### CODE REVIEW

**Comment by NathanW2** [comment]
Nice work.  I will merge later if someone else already hasn't.

**Comment by nirvn** [comment]
Guys, please don't merge right now, I'll finish the label toolbar (didn't realize some icons were still bitmaps) and add a commit.

**Comment by nirvn** [comment]
Guys, please don't merge right now, I'll finish the label toolbar (didn't realize some icons were still bitmaps) and add a commit.

**Comment by nirvn** [comment]
Label toolbar, before vs. proposed:
untitled

Ready to merge.

**Comment by nyalldawson** [comment]
@nirvn I can see what you're doing with the vertical alignment of the label, but does it look a bit odd for the first label icon?

**Comment by nirvn** [comment]
@nyalldawson it doesn't look odd to me when placed alongside other toolbars:
untitled

That said, I don't have strong feelings either way. If you think the above screenshot still bothers you, I can change it.

**Comment by nirvn** [comment]
@nyalldawson , seeing that screenshot did remind of that the highlight pined label icon needs pixel alignment. Doing now.

**Comment by nirvn** [comment]
Highlight pined label edit done; ready to merge (travis was green prior to retouching the SVG, safe to push).

**Pull request merged**
