### PR TITLE
Change vector layer data sources ONLY after applying all other settings in the layer properties dialog

### PR DESCRIPTION
**Pull request by nyalldawson**
Otherwise we run the risk that logic implemented when changing data source (eg changing the layer's renderer to a type compatible with the new data source) is obliterated when the outdated settings from the dialog are applied.

### CODE REVIEW

**Review by troopa81 — COMMENTED** [review]
But what happens with all the variable members (mBackupCrs, mMetadataFilled, mOriginalSubsetSql...) which would be modified according to the old datasource ?

Could it be possible to have a test ?

**Comment by nyalldawson** [comment]
> what happens with all the variable members (mBackupCrs, mMetadataFilled, mOriginalSubsetSql...) which would be modified according to the old datasource ?

Hmm. Maybe we should disable "apply" and only allow ok/cancel when changes are made to the source in this dialog. 

(That's not a new bug though, it's not changed by this commit)

**Comment by troopa81** [comment]
> Hmm. Maybe we should disable "apply" and only allow ok/cancel when changes are made to the source in this dialog.

Ok button calls "apply" method also

> (That's not a new bug though, it's not changed by this commit)

Until this commit, the code actually change the datasource then use/cache information (crs for instance) from the new modified layer. After the commit, code would cache/use information from old non modified datasource. 

Maybe I missing a point here but how it is not introducing a bug?

**Comment by nyalldawson** [comment]
@troopa81 

Ok, I've added a test (which demonstrates the original issue of the layer having a broken renderer because it uses the wrong symbol type for the new layer source), and also made a logic tweak to address your concern. Now if the source is changed in the source widget then we re-sync the dialog state to the layer's state after applying the new source to the layer. This ensures that the dialog is immediately updated with any settings replaced automatically by the source change, such as the field configuration and renderer settings.

(I've also added a new OGR file source widget allowing change of OGR file based layer paths which I used to test this new logic)

**Review by troopa81 — APPROVED** [review]
That looks good! LGTM

**Comment by agiudiceandrea** [comment]
Hi @nyalldawson, could it be this PR be the cause of the issue "QGIS 3.36 - Query Builder Filter Through Properties Does Not Work For Some Source Types" recently reported at https://github.com/qgis/QGIS/issues/56536?

**Pull request merged**
