### PR TITLE
Create Noth_Arrow_Alternative.svg

### PR DESCRIPTION
**Pull request by Cantalou15**
## Description
It's a proposition for an alternative to the defaut North Arrow with the new QGis Logo.

### CODE REVIEW

**Comment by timlinux** [comment]
Can you paste a preview here in the ticket so that it is easy for others to review? Thanks.

**Comment by mach0** [comment]
@timlinux you have to click on the svg and then, directly above the code on the right side .. there is a "View" button. That should do it (though a bit small - but you can zoom the browser)

**Comment by DelazJ** [comment]
There's a typo in the file name : No**R**th_Arrow_Alternative

**Comment by nyalldawson** [comment]
I think this would be a better candidate for distribution through the Resource Sharing Plugin, given that it's for a specific use case. @nirvn do you agree?

**Comment by nirvn** [comment]
IMHO, the proposed north arrow is too busy and not generic enough to be of use to a large number of users, therefore it's not well suited to be shipped by default. I agree with @nyalldawson , I think it'd be better offered via the resource sharing plugin.

**Pull request closed without merging**
