### PR TITLE
Improve night mapping icons and add night mapping (colour blind) theme.

### PR DESCRIPTION
**Pull request by AlisterH**
See discussion at #51706 and original issue at #49775

### CODE REVIEW

**Comment by AlisterH** [comment]
I don't believe any tests are required - the only existing tests involving the night mapping theme are in https://github.com/qgis/QGIS/blob/e2fa27e4a6be3f2f106738b00bea78ad9079facf/tests/src/python/test_qgscodeeditor.py, which is about testing the code editor, rather than the theme.

**Comment by AlisterH** [comment]
Screenshots:
image
image

**Comment by nirvn** [comment]
@AlisterH , this is getting better, but I'm really not convinced about using the green fill for unchecked checkbox and radiobox. That's also not necessary either right? The addition of a white check / dot is enough?

**Comment by nirvn** [comment]
The philosophy here is that green is used as an highlight, not a background color.

**Comment by AlisterH** [comment]
> @AlisterH , this is getting better, but I'm really not convinced about using the green fill for unchecked checkbox and radiobox. That's also not necessary either right? The addition of a white check / dot is enough?

Wait, what?  Are you talking about checked, or unchecked, or both?

You're not suggesting something like this?:
image

**Pull request closed without merging**
