### PR TITLE
Add a title to the raster resampling dialog

### PR DESCRIPTION
**Pull request by DelazJ**
A missing title. Any better wording?
raster_align_edit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Maybe drop the "Edit" part and call it "Raster resampling" or "Resample raster". (Assuming that the resampling starts when you click "Ok".)

**Comment by DelazJ** [comment]
No, the resampling doesn't begin. This dialog is about configuring (and adding) layers with some resampling method  in order to align them (see Raster menu --> Align rasters).

**Comment by m-kuhn** [comment]
I see... "Edit layer resampling configuration"?

**Comment by DelazJ** [comment]
What about "Configure Layer (or Raster? ) Resampling"? Shorter and avoid the use of "edit", given that the dialog is opened by both the "Add" and "Edit" buttons.

**Comment by m-kuhn** [comment]
Sounds also good.

**Comment by DelazJ** [comment]
Should be good to merge...

**Pull request merged**
