### PR TITLE
Allow resizing and moving columns in bad layer handler

### LINKED ISSUE #26920: Inability to resize columns in 'handle bad layers' dialogue box
Author Name: **Simon Dedman** (@simondedman)
Original Redmine Issue: [19090](https://issues.qgis.org/issues/19090)
Affected QGIS version: 3.0.3
Redmine category:gui

---
One can resize the handle bad layers box as a whole by dragging the edge, although double clicking the toolbar fills the screen vertically but not horizontally, peculiarly.
However one cannot resize the columns within the dialogue box, meaning it can be impossible to see the names of the layers. See attachment.

---

- [QGIS GUi handle bad layers bug.png](https://issues.qgis.org/attachments/download/12765/QGIS%20GUi%20handle%20bad%20layers%20bug.png) (Simon Dedman)

### PR DESCRIPTION
**Pull request by roya0045**
## Description

Fixes #26920

Enable interactive resize mode and allow moving columns in the bad layer handler QTableWidget.

### CODE REVIEW

**Comment by roya0045** [comment]
What's with the taskmanager test these days?

**Comment by roya0045** [comment]
@nyalldawson safe to merge?

**Comment by nyalldawson** [comment]
@roya0045 I'll build and test now... give me a sec

**Comment by roya0045** [comment]
@nyalldawson you can use my artefacts instead of bui;ding things to test my PRs.

**Comment by roya0045** [comment]
@nyalldawson  just in case : https://github.com/roya0045/QGIS_1/actions

**Pull request merged**
