### PR TITLE
Move classes representing GCP based transformations from app to analysis

### PR DESCRIPTION
**Pull request by nyalldawson**
And clean these up so that they are fit for inclusion in the stable public API.

This is the first step to exposing these useful transformations to different parts of QGIS for reuse, eg. for vector layer georeferencing (see https://github.com/qgis/QGIS/pull/41386), potential future processing algorithms, etc. (I've also done this refactoring with potential for moving the raster georefencing op to a background task in future!)

Also makes these transformations available for Python plugins and scripts to utilise.

~~Before merge I'd like to extend the tests and ensure that all transformation methods are covered by some form of tests.~~ Done!

Refs Natural resources Canada Contract: 3000720411

### CODE REVIEW

**Comment by nyalldawson** [comment]
@roya0045 
Here's part 1 -- when this is ready I'll then create an easy to use method to allow vector geometries to be transformed using these GCP based transformations

**Comment by roya0045** [comment]
@nyalldawson you weren't lying when you said soon!

**Comment by roya0045** [comment]
Depending on your follow-up I'll see if I should add an edit in place option, use opened layers and or even work on specific geometries. Though maybe that would be an option after everything. 

As these will be frozen, what is the best option to handle this, should I merge in my branch or rebase when unfrozen and then finish the wrapper?

**Comment by roya0045** [comment]
Would it be a good idea to simply expose the transform to use it on any geometries instead of doing one point at a time?

**Comment by nyalldawson** [comment]
@roya0045 
> Would it be a good idea to simply expose the transform to use it on any geometries instead of doing one point at a time?

That's the plan, just gotta get the fundamentals in place first...

**Comment by roya0045** [comment]
Ah good, I was curious to know if the work on this PR was done.

**Comment by nyalldawson** [comment]
@roya0045 

> Would it be a good idea to simply expose the transform to use it on any geometries instead of doing one point at a time?

Ok, checkout https://github.com/qgis/QGIS/pull/41404/commits/8033ee6b82f1dfbe1f39bb15ed129b5a867a810d -- there's now a simple method to transform a whole QgsGeometry using a GCP based transform.

**Comment by roya0045** [comment]
Neat! I'll wait until this is merged to integrate this in #41386

**Review by nirvn — APPROVED** [review]
Can't see anything wrong in there. Nice cleanup and test coverage addition too.

**Comment by nyalldawson** [comment]
Thanks @nirvn!

**Comment by roya0045** [comment]
> @roya0045
> Here's part 1 -- when this is ready I'll then create an easy to use method to allow vector geometries to be transformed using these GCP based transformations

To clarify, was there a follow-up planned or is it all in here?

**Comment by nyalldawson** [comment]
> To clarify, was there a follow-up planned or is it all in here?

That's done -- see 8033ee6

**Comment by roya0045** [comment]
Excellent, I'll look into it soon!

As a non-sequitur, would a feature relative grouper be a good alg to remove or group similar entities? I'm thinking that using the bounding box of a feature to transpose in a relative space to compare shapes (rescaling them or not). Though I'm not sure how useful this would be other than filter out similar shapes in a large dataset and group duplicate. Though shape comparison and all that may be the tough part and take memory.

**Pull request merged**
