### PR TITLE
QgsAttributeTableModel loadAttributes Fix #36790

### LINKED ISSUE #36790: QgsAttributeTableModel loadAttributes Error
**Describe the bug**
In debug mode, crashed when adding one field of vectorlayer

**How to Reproduce**

## In Debug Mode
1. Add a vectorlayer, sucn as shp or postgis
2.Go to "edit mode"
3.Open Attribute Table
4.Add one field and click "OK"
image

### PR DESCRIPTION
**Pull request by GISerliang**
## Description
Fixes #36790 
In debug mode, last row number less than first row number, so crashed when adding one field of vectorlayer

### CODE REVIEW

**Comment by nyalldawson** [comment]
Can you clarify how to reproduce this? I've tried following the instructions from https://github.com/qgis/QGIS/issues/36790 and can't trigger it

**Comment by GISerliang** [comment]
is it in debug mode when you tried?



hml8431386@163.com
 
From: Nyall Dawson
Date: 2020-06-02 10:19
To: qgis/QGIS
CC: GISerliang; Author
Subject: Re: [qgis/QGIS] QgsAttributeTableModel loadAttributes Fix #36790 (#36799)
Can you clarify how to reproduce this? I've tried following the instructions from #36790 and can't trigger it

**Comment by nyalldawson** [comment]
Yes - debug mode. And I can't work out what circumstances would lead up to the condition that you've caught.

**Comment by GISerliang** [comment]
It's really weird. I only opened attribute view and edit mode, then I added one field and saved in debug mode.
I don't know if I did something wrong



hml8431386@163.com
 
From: Nyall Dawson
Date: 2020-06-02 10:39
To: qgis/QGIS
CC: GISerliang; Author
Subject: Re: [qgis/QGIS] QgsAttributeTableModel loadAttributes Fix #36790 (#36799)
Yes - debug mode. And I can't work out what circumstances would lead up to the condition that you've caught.

**Pull request closed without merging**
