### PR TITLE
More version info in about screen, minor cleanups

### PR DESCRIPTION
**Pull request by nyalldawson**
- Don't show redundant compiled/running version strings if they are identical
- Show Proj EPSG database version
- Show Python version
- Fix capitalisation and other formatting

image

### CODE REVIEW

**Comment by nirvn** [comment]
Nice -- what about removing the bullets from the list of active plugins?

**Comment by nyalldawson** [comment]
I just added those, cos the current list with ";" suffixes is quite ugly...

**Comment by nirvn** [comment]
@nyalldawson , maybe add some styling like 

ul { padding: 0; margin: 0; list-style-type: none; }
li { padding: 0; margin: 0; }

**Comment by nirvn** [comment]
I don't mind the circle per say actually, it's just the weird padding/margin.

**Comment by nirvn** [comment]
Oh well, bye bye bullets. +1 to merge.

**Comment by uclaros** [comment]
Does it still paste nicely in github comments?

**Comment by Gustry** [comment]
Unfortunately, it was already broken apparently #42037
I raised the idea of having a proper button to get markdown in the clipboard a few months ago IIRC.

**Pull request merged**
