### PR TITLE
Make QgsDataSourceURI uri string parser skip invalid portions instead of skipping the entire string

### PR DESCRIPTION
**Pull request by manisandro**
Currently `QgsDataSourceURI` fails to parse uri strings such as

```
'PG: dbname=db_name host=hostname user=username password=passwd port=5432 mode=2 schema=public column=rast table=tablename'
```

the reason being the `PG:` which to the parser looks like a parameter name without a value. (Such uri strings are obtained for instance when adding a PG raster via DB Manager).

The commit changes the parser behaviour to just skip the invalid portions of the uri string, instead of skipping the entire string altogether.

Funded by Sourcepole

### CODE REVIEW

**Comment by nyalldawson** [comment]
@manisandro thanks! Can you include some unit tests with this?

**Comment by jef-n** [comment]
Um, why does it need to parse invalid strings?

**Comment by manisandro** [comment]
Such URIs are GDAL compatible URIs which are used to create the Raster Layer from the DB Manager (see [1], [2]).

[1] http://www.gdal.org/drv_pg.html
[2] https://github.com/qgis/QGIS/blob/master/python/plugins/db_manager/db_plugins/postgis/plugin.py#L282

**Comment by manisandro** [comment]
So finally I got around to implement a unit test...

**Comment by m-kuhn** [comment]
@jef-n Does that sound like a good explanation to you?

**Comment by m-kuhn** [comment]
Merged

**Pull request closed without merging**
