### PR TITLE
Server: Remove soap request handler

### PR DESCRIPTION
**Pull request by dmarteau**
Soap request handler is actually dead code, it should be removed from sources.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Removing ~1000 lines of old, untested code? Yes please!

**Comment by dmarteau** [comment]
It seems that check_spelling.sh choke trying to analyse removed files !

**Review by rldhont — APPROVED** [review]

**Comment by rldhont** [comment]
@mhugent can you review this PR ?

**Review by elpaso — APPROVED** [review]
+1

**Review by sbrunner — APPROVED** [review]

**Review by mhugo — COMMENTED** [review]
Like lots of code here, I don't clearly know if it is still used and maintained by people.
But since the feature seems well defined (I mean it is not a hack) and does not really hurt the global server architecture, I would say: wait a little before removing it, but if someone really uses it, some tests and documentations are definitely needed.
Besides, this is clearly a good case for a Python based service: it is mostly only string and XML manipulations, something where Python is more readable and not less inefficient than C++

**Comment by dmarteau** [comment]
@mhugo  clearly instanciation  of QgsSOAPRequestHandler was commented out and there is no reference to this code elsewhere. Once removed, it compiles and all tests are green (this code is clearly not tested). 
I don't see any reason to stick with that code in the server codebase, and the same question will arise sooner or later.  
If someone use this code then this is clearly not in the context of the current release of the QgsServer. Anyway:  if we delete it,  it will still exist in git history :-)

**Comment by mhugo** [comment]
Ah my bad ! I missed the line where its invocation was commented out !
+1, please kill it !

**Comment by rldhont** [comment]
@mhugent no objection to remove soap from QGIS Server for version 3.0 ?

**Comment by mhugent** [comment]
@rldhont: No problem, I don't have a project anymore which uses soap.

**Comment by rldhont** [comment]
@dmarteau can you rebase your branch to fix travis ?
And then I could merge your PR.

**Comment by dmarteau** [comment]
There is an issue with the command "./ci/travis/check_spelling.sh" which try to analyse removed files.

**Pull request merged**
