### PR TITLE
New modules for the GRASS plugin

### PR DESCRIPTION
**Pull request by ninsbl**
LiDAR, Imagery, and r/v.(un)pack modules added, fixed wrong parameter in t.shift
Would be nice if imagery groups could be supported as input type (like raster and vector).
I am planning to add a few more modules, but open this PR already now so you are aware of the process...

### CODE REVIEW

**Comment by ninsbl** [comment]
An overview over modules in or to be added to the GRASS plugin can be found here:
https://docs.google.com/spreadsheets/d/1xrxQ_GIAkEpfnC4IjlktMSWZCAGlvtFxjJaYq6TXWjM

However, I am not sure when I will be able to add more modules, so it would be nice if the modules above could make it into the upcoming release...

**Comment by blazek** [comment]
Do you mean 2.16 which should be released 08.07.2016?  Isn't it late to merge it now? I know it is just configuration and can be considered bug fix as well.

**Comment by ninsbl** [comment]
Yes, 2.16 would be nice. However, I see that it is indeed late to merge it now.
I am not at all offended if you choose not to merge.
The modules worked well in my installation on Win7, but I did not test other platforms...

So I leave that decision to you guys when you feel comfortable to merge...

**Comment by blazek** [comment]
I am not personally against merge to 2.16, but I'll be offline 1.-11.7. and I don't want to merge something which I cannot fix then before release.

**Comment by ninsbl** [comment]
Of course I fully understand! We take it later then...

**Pull request merged**
