### PR TITLE
Add (failing) test for malformed WKB parsing

### PR DESCRIPTION
**Pull request by strk**
The WKB parser can corrupt memory. This tests shows an example of such occurrence.
See http://hub.qgis.org/issues/12416

### CODE REVIEW

**Comment by jef-n** [comment]
see also https://github.com/jef-n/QGIS/tree/wkb-bounds-check (work in progress)

**Comment by strk** [comment]
I like the idea and was actually also doing something along those lines. My WIP:
https://github.com/strk/QGIS/tree/wkbptr-checking-strk

Shall I stop that work and wait for you to complete it ?

**Comment by strk** [comment]
Hub ticket: http://hub.qgis.org/issues/14182

**Comment by strk** [comment]
Note that the WKB input in this test was output by "toWkb" method of QgsGeometry.
I'm trying to reproduce this in the test for QgsMapToPixelGeometrySimplifier

**Comment by strk** [comment]
I've found a bug in the test itself, will push a fixed and rebased version

**Comment by strk** [comment]
Ok so the "fromWkb" does not error out on taking the weird collection. It doesn't even parse it but simply stores it somewhere. Closing this PR and will use this finding to complete the simplifier one

**Pull request closed without merging**
