### PR TITLE
QgsMapLayer, QgsVectorLayer, QgsRasterLayer const correct + cleanups

### PR DESCRIPTION
**Pull request by nyalldawson**
(This won't build, as it depends on #3291 )

This PR implements some clean ups for the various map layer classes. Changes include:
- removal of deprecated methods from QgsMapLayer
- make QgsVectorLayerEditBuffer const correct
- make a bunch of QgsVectorLayer methods const correct, including getFeatures() is now const (see https://github.com/qgis/qgis3.0_api/issues/48 )

With the exception of the removed deprecated members, these changes have minimal impact on PyQGIS code and are mostly motivated by the cleanups they will allow to core code. C++ plugins and custom layer types will be affected due to the modified virtual signatures.

### CODE REVIEW

**Comment by wonder-sk** [comment]
Great stuff Nyall... :+1: 

Just wondering - for the newly added methods - would it make sense to use the Qt convention for bool returning methods, e.g. ```isBlahBlah()``` or ```hasBlahBlah()``` - or does it sound cumbersome if the order of words is changed?  (e.g. ```featureIsAdded()``` to ```isFeatureAdded()```)

**Comment by nyalldawson** [comment]
> Just wondering - for the newly added methods - would it make sense to use the Qt convention for bool returning methods, e.g. isBlahBlah() or hasBlahBlah() - or does it sound cumbersome if the order of words is changed? (e.g. featureIsAdded() to isFeatureAdded())

+1 for better api wording! What about dropping the "feature" part... and just go "isAdded(...)"?

**Comment by wonder-sk** [comment]
> +1 for better api wording! What about dropping the "feature" part... and just go "isAdded(...)"?

That could also work. The "feature" part could be useful to distinguish the context if we decided to add something like "isFieldAdded" in the future, but I do not have a strong opinion on this :-)

**Comment by nyalldawson** [comment]
True. isFeatureAdded it is!

**Comment by nyalldawson** [comment]
Manually pushed with test fixes and renamed methods

**Pull request closed without merging**
