### PR TITLE
[BUG] Avoid trying to split a line with itself

### PR DESCRIPTION
**Pull request by bstroebl**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Could you add a test case for this algorithm?

**Comment by bstroebl** [comment]
Could you show me how to do it (or point me to a ressource)? :-)

**Comment by m-kuhn** [comment]
https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/README.md

**Comment by bstroebl** [comment]
Will open a new pull request with test

**Comment by m-kuhn** [comment]
@bstroebl you are aware that you can just push additional commits to this branch and the pull request will be updated?

**Pull request closed without merging**
