### PR TITLE
Update INSTALL.md: Add g++ dependency for Ubuntu

### PR DESCRIPTION
**Pull request by gacarrillor**
On a fresh Ubuntu (jammy) installation, and after following [GNU/Linux instructions to compile QGIS](https://github.com/qgis/QGIS/blob/master/INSTALL.md#3-building-on-gnulinux), I got a "g++ not found" error when running either `ccmake ..` or `ccmake -G Ninja ..`.

It was necessary to run `sudo apt-get install g++` to make the Ninja command run.

This has also happened to me with other Ubuntu versions.

Therefore, I'm suggesting adding `g++` to the main list of required dependencies (i.e., [section 3.3](https://github.com/qgis/QGIS/blob/master/INSTALL.md#33-install-build-dependencies)).

### CODE REVIEW

**Comment by nyalldawson** [comment]
How does this relate to https://github.com/qgis/QGIS/pull/52875 ?

**Comment by nicogodet** [comment]
@gacarrillor These APT commands are updated when running `./script/scandeps.pl` which reads `debian/control.in` file.
Thus they should not be changed manually

**Comment by gacarrillor** [comment]
> @gacarrillor These APT commands are updated when running `./script/scandeps.pl` which reads `debian/control.in` file.
> Thus they should not be changed manually

Thanks for the info. I was not aware of that.

In that case, we could add a sub-section indicating that we should run `sudo apt-get install g++` to have the compiler ready.


> How does this relate to https://github.com/qgis/QGIS/pull/52875 ?

The `build-essential` package is not necessary to compile QGIS on Ubuntu. It's enough to install `g++`.

On the other hand, `build-essential` is required for building a .deb package, but that's already well documented in section [3.10](https://github.com/qgis/QGIS/blob/master/INSTALL.md#310-building-debian-packages).

Nonetheless, if @jef-n suggests adding `build-essential` (as in https://github.com/qgis/QGIS/commit/bb4d23c0af64a4e750c0e1da151514a41fac0347), we can close this PR.

**Comment by nicogodet** [comment]
Fixed with bb4d23c

**Pull request closed without merging**
