### PR TITLE
Take tile_buffer parameter into consideration when rendering labels

### LINKED ISSUE #37945: Rendering of labels in WMS requests does not respect the tile_buffer parameter when the request have the parameter TILED= TRUE and a tile buffer is set in the project propertie
**Description**
The rendering of labels in WMS requests does not respect the tile_buffer parameter when the request have the parameter TILED= TRUE and a tile buffer is set in the project properties. This works for symbols, solved by @troopa81 and discussed here  #30071  . In this two adjacent images there is a clipped label up to the right in the lower. In the image directly north of this the part of the symbol for the point is rendered correctly even if it is outside the requested area but the label is not there. The symbols are the point features holding the label used just for illustrating the difference between symbols and labels.
bild
bild

**How to Reproduce**

1. Download data and project.
[demo_data.zip](https://github.com/qgis/QGIS/files/4965753/demo_data.zip)
2. Deploy on QGIS Server adjusting paths in the project to fit your environment.
3. Request WMS images from the server. Replace host to your host.
[http://path_to_your_qgis_server?MAP=tiled_label.qgs&TILED=TRUE&LAYERS=label_test&TRANSPARENT=true&SRS=EPSG%3A3008&FORMAT=image%2Fpng%3B%20mode%3D8bit&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=134186.78272,6211280.17408,147733.4784,6224826.86976&WIDTH=512&HEIGHT=512](http://path_to_your_qgis_server?MAP=tiled_label.qgs&TILED=TRUE&LAYERS=label_test&TRANSPARENT=true&SRS=EPSG%3A3008&FORMAT=image%2Fpng%3B%20mode%3D8bit&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=134186.78272,6211280.17408,147733.4784,6224826.86976&WIDTH=512&HEIGHT=512)
[http://path_to_your_qgis_server?MAP=tiled_label.qgs&TILED=TRUE&LAYERS=label_test&TRANSPARENT=true&SRS=EPSG%3A3008&FORMAT=image%2Fpng%3B%20mode%3D8bit&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=134186.78272,6224826.86976,147733.4784,6238373.56544&WIDTH=512&HEIGHT=512](http://path_to_your_qgis_server?MAP=tiled_label.qgs&TILED=TRUE&LAYERS=label_test&TRANSPARENT=true&SRS=EPSG%3A3008&FORMAT=image%2Fpng%3B%20mode%3D8bit&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=134186.78272,6224826.86976,147733.4784,6238373.56544&WIDTH=512&HEIGHT=512)

**QGIS and OS versions**
Tested on QGIS 3.10 Desktop and Server.

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #37945 : We need to update the extentGeom to be used when clipping in `QgsPalLayerSettings::prepare`

Even if it's not usefull for the fix, I updated also the Labeling Job extent to be consistent and to prevent possible later issues

cc @karl-magnus

### CODE REVIEW

**Review by nyalldawson — COMMENTED** [review]
Those mask images look odd to me -- why so much variation in the background colour? I'd also suggest bumping the font size and making them bold to make the test more robust.

**Comment by troopa81** [comment]
@nyalldawson I increased the font size and make it bold as you proposed and every thing works without mask. Thanks

**Comment by nyalldawson** [comment]
@troopa81 
> I increased the font size and make it bold as you proposed and every thing works without mask. Thanks

Thanks, that's much better!

**Review by rldhont — APPROVED** [review]

**Comment by troopa81** [comment]
@rldhont Is it OK to merge?

**Comment by rldhont** [comment]
@troopa81 yes approved

**Comment by troopa81** [comment]
@rldhont Could you merge it?

**Comment by troopa81** [comment]
Thanks @rldhont

**Comment by rldhont** [comment]
@troopa81 I have not changed the label to automatically create the backport to release-3_20.  Can you manually backport it ?

**Comment by troopa81** [comment]
@rldhont Thanks, I forgot about 3.20 merge. I added the label and it seem to work.

**Pull request merged**
