### PR TITLE
Processing editing in place: handle constraints

### LINKED ISSUE #31634: In place processing multipart to singleparts does not handle unique constraints
Provider errors are generated due to failure of UNIQUE constraint when you try to save after running Multipart to singleparts in a geopackage layer.

**How to Reproduce**

1.	Download and open a copy of ‘Multi_to_Singleparts_FID_Bug.qgz’ (zip attached below)
2.	Open the Attribute Table for the ‘Multi_to_Singleparts_FID_Bug’ layer.
3.	Select the multipart feature with FID value of 4.
4.	Ctrl + K
5.	“ef multipart to singleparts”
6.	Observe there are now 5 features selected in the attribute table with FID value of 4 (This is a bug).
7.	Undo, and the edit is successfully reversed.
8.	Repeat steps 3 to 6.
9.	Click ‘Save Layer Edits’
10.	Observe there are 6 Commit errors, including:

Could not commit changes to layer Multi_to_Singleparts_FID_Bug

Errors: SUCCESS: 1 feature(s) deleted.
  ERROR: 5 feature(s) not added.

  Provider errors:
      OGR error creating feature -8: failed to execute insert : UNIQUE constraint failed: Multi_to_Singleparts_FID_Bug.fid
      OGR error creating feature -9: failed to execute insert : UNIQUE constraint failed: Multi_to_Singleparts_FID_Bug.fid
      OGR error creating feature -10: failed to execute insert : UNIQUE constraint failed: Multi_to_Singleparts_FID_Bug.fid
      OGR error creating feature -11: failed to execute insert : UNIQUE constraint failed: Multi_to_Singleparts_FID_Bug.fid

11.	On the Map Canvas, marquee select the feature(s) at the south-west corner.
12.	In the attribute table, observe that the title bar reports 2 features selected, but there is only one feature selected in the table (bug in attribute table failing to update).
13.	Close and re-open the attribute table, and observe there are now 2 features selected out of 6 features with FID value of 4.
14.	Either ‘Undo’ or ‘Toggle Edit & Discard Changes’.
15.	Observe that 5 of the 6 FID value-4 features have been deleted, leaving only one remaining.

Workaround:
16.	Repeat steps 1 to 6
17.	In the attribute table, with the relevant features selected, change the FID value to null.
18.	Save Layer Edits.
19.	Observe that unique values have now been autogenerated.

**QGIS and OS versions**

QGIS 3.4.11 (LTR), 3.8.2, and 3.9 (nightly build)

[Multi_to_Singleparts_FID_Bug.zip](https://github.com/qgis/QGIS/files/3590496/Multi_to_Singleparts_FID_Bug.zip)

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #31634

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]

**Comment by SteveLowman** [comment]
With the backport failure, does it still need the manual backport?
I would do it if I knew what I was doing, so sorry for the ignorant question.
Just it would be good to know that the fix gets into the LTR.
Thanks for all the excellent work.

**Comment by m-kuhn** [comment]
Yes it needs a manual backport.
I am not sure how big the involved work will be.

**Comment by elpaso** [comment]
@m-kuhn @SteveLowman I'll look into the backport

**Comment by m-kuhn** [comment]
Thanks @elpaso

**Pull request merged**
