### PR TITLE
fix missing play/stop buttons on MacOS for mesh layer playback

### PR DESCRIPTION
**Pull request by PeterPetrik**
follow up of https://github.com/qgis/QGIS/pull/31875/files (@MarcusUrban )

on MacOS the system/qt icons (eg `QIcon::fromTheme( "media-playback-start" )`) are not present, so new buttons were blank.

added the icons directly to qgis to fix it (icons from [vlc](https://github.com/videolan/vlc/tree/fc641f2577de4f18a7b1991e57dd7f3919f5339b/modules/gui/qt/pixmaps), license GPLv2). in case we have better icons, feel free to replace them...

the new icons (svgs):

Screenshot 2019-11-09 at 10 08 19

Screenshot 2019-11-09 at 10 08 24

### CODE REVIEW

**Comment by nyalldawson** [comment]
In before @nirvn asks you to run these svgs through https://jakearchibald.github.io/svgomg/ 😜

**Comment by PeterPetrik** [comment]
hmm, very nice optimisation

**Comment by PeterPetrik** [comment]
rebased to fix broken sip on master

**Comment by PeterPetrik** [comment]
cannot be backported, this is new feature in 3.12

**Pull request merged**
