### PR TITLE
Fix out of bounds array access if nextVertex is called on empty geometry collection

### PR DESCRIPTION
**Pull request by manisandro**
Fixes a geometry checker crash reported in #13535.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Mind adding a quick regression test protecting against this too?

**Comment by manisandro** [comment]
Sure, something like 6e5e7e4?

**Comment by nyalldawson** [comment]
Does that test work? I can't see it calling nextVertex? In any case, I'd strongly suggest moving it to testqgsgeometry.cpp to avoid the need for creating a new cpp test file (which slows compilation down)

**Comment by manisandro** [comment]
Ok (yes,  the test works, because isEmpty uses nextVertex - the usage of isEmpty was what actually caused the crash in the geometry checker).

**Comment by nyalldawson** [comment]
Ah ok - i should have actually looked at the code ;)

**Comment by nyalldawson** [comment]
Thank you!

**Pull request merged**
