### PR TITLE
Add win32 native implementation, and new openFileExplorerAndSelectFile method to QgsNative

### PR DESCRIPTION
**Pull request by nyalldawson**
The new method opens the desktop file explorer at the folder containing path, and (if possible) scrolls to and pre-selects the file at path itself.

The default implementation just calls the QDesktopServices method to open the folder, without selecting the specified file, but on Windows it will automatically select the correct file.

Use this to automatically select the exported layout file when clicking the message bar success message in layouts (on Windows).

### CODE REVIEW

**Comment by nyalldawson** [comment]
peek 2018-07-31 15-38

**Comment by nyalldawson** [comment]
Note: if a motivated osx dev wanted to add support for this too, it's really quite straightforward. See https://stackoverflow.com/questions/7652928/launch-osx-finder-window-with-specific-files-selected

(*cough* @3nids *cough*)

**Comment by m-kuhn** [comment]
Sweet, might replace [this code](https://github.com/opengisch/qfieldsync/blob/master/qfieldsync/utils/file_utils.py#L69-L81)

**Comment by nyalldawson** [comment]
@m-kuhn qgis native isn't exposed to python yet, but I don't see any reason why it couldn't be

**Comment by m-kuhn** [comment]
The previous message can also be read as "hey look, there is also code that already does it for mac" ;)

**Comment by nyalldawson** [comment]
And this whole thread is a damnation on lack of standards on Linux ;)

**Comment by m-kuhn** [comment]
Don't remind me. I just successfully managed to push this journey of trying to write portable code to the back of my head.

**Pull request merged**
