### PR TITLE
Switch to F35 for mingw ci build

### PR DESCRIPTION
**Pull request by manisandro**
See #45966

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
@manisandro the commit seems to have been overwritten in this branch now...

**Comment by manisandro** [comment]
Yes, I was just testing whether reposync already happened - in the meantime, F35 deps are building, should be done by tomorrow, then I'll revisit this one.

**Comment by manisandro** [comment]
Actually I see that reposync happened - the mingw CI has passed dependency installation. So should be green checkmark again.

**Comment by nyalldawson** [comment]
So should we close this one?

**Comment by manisandro** [comment]
Lets do for now.

**Pull request closed without merging**
