### PR TITLE
Show python code sample in PyQGIS doc

### PR DESCRIPTION
**Pull request by DelazJ**
to adjust doc at https://qgis.org/pyqgis/master/core/QgsVectorLayer.html?highlight=code%20sample

### CODE REVIEW

**Comment by 3nids** [comment]
I think that we should rather show Python only in such case. Python code is show in Doxygen and I guess most C++ devs can translate the code.
But no strong opinion

**Comment by DelazJ** [comment]
I can remove the cpp ones if it's better. I saw #37553 and thought that the code was shown depending on the context and it was better to write both.

**Comment by 3nids** [comment]
yes, I was hesitating a bit.
In the other one, the one line is a bit less explicit to me.
But as said, no strong opinion. It might be worth having some stricter guidelines.

**Comment by 3nids** [comment]
(sorry, I didn't meant to close)

**Comment by nyalldawson** [comment]
I'm for removing the C++ examples and translating them all to python examples. I agree with @3nids that C++ devs will easily be able to translate python examples to C++ "on the fly".

Would be a nice little project to upgrade all code examples in the docs to python.

**Comment by 3nids** [comment]
superseded by #37642

**Pull request closed without merging**
