### PR TITLE
[3D] Add a terrain layer logic

### PR DESCRIPTION
**Pull request by ptitjano**
## Description

This way, the terrain is now handled as the other layers.

This is achieved with the two following changes:
- add QgsDummyLayer to handle technical layer (for example terrain).
- add QgsTerrainLayer3DRenderer to handle terrain layer.

With this change, this is now possible to remove `mSceneEntities` as
all the entities are now also saved in mLayerEntities.

cc @benoitdm-oslandia

### CODE REVIEW

**Comment by ptitjano** [comment]
@wonder-sk @uclaros Any thoughts?

**Comment by nyalldawson** [comment]
Honestly i don't think this is any cleaner then the current code. Eg I don't like the idea of a dummy layer -- either the terrain IS a layer and should have its own dedicated layer subclass or it's not.

**Comment by ptitjano** [comment]
> Honestly i don't think this is any cleaner then the current code. Eg I don't like the idea of a dummy layer -- either the terrain IS a layer and should have its own dedicated layer subclass or it's not.

Thanks for the comment. 

@benoitdm-oslandia and I have worked on it in order to solve some issues with the current implementation of the GPU memory limit which does not work correctly (https://github.com/qgis/QGIS/pull/54774#issuecomment-1740450433). We have a branch ready which solves those issues and this PR has been factored out from the branch. 

One of the reasons this does not correctly work is that the terrain behaves as some kind of special entity in the MapScene because it is not directly associated with a layer (for example `QgsMapScene` has to contain a Layer list and an entity list which is really strange) . As a result, it is not possible to correctly compute the gpu memory used by the terrain. 
I believe that is necessary to move to a logic where the terrain does not behave as a special entity. Do you have any idea how this could be achieved?

**Comment by nyalldawson** [comment]
>One of the reasons this does not correctly work is that the terrain behaves as some kind of special entity in the MapScene because it is not directly associated with a layer (for example QgsMapScene has to contain a Layer list and an entity list which is really strange) . As a result, it is not possible to correctly compute the gpu memory used by the terrain.  I believe that is necessary to move to a logic where the terrain does not behave as a special entity. Do you have any idea how this could be achieved?

What about flipping the logic and making the layers a scene entity instead?

**Comment by benoitdm-oslandia** [comment]
> What about flipping the logic and making the layers a scene entity instead?

Do you mean you want to have the `QgsMapLayer` class to inherit the `Qgs3DMapSceneEntity`?!? Can you explain a bit further please?

**Comment by wonder-sk** [comment]
@ptitjano sorry I am a bit lost. What is the actual problem you are trying to solve in this PR?

Is it that Qgs3DMapScene contains `mTerrain`, `mSceneEntities` and `mLayerEntities` - and you would prefer to have just one member variable for all those things? Or are there some other issues you would like to fix?

In the current state of the PR with the introduction of QgsDummyLayer, I do not really see how improves the code...

**Comment by nyalldawson** [comment]
> Do you mean you want to have the QgsMapLayer class to inherit the Qgs3DMapSceneEntity?!?

No, 100% no! :laughing: 

>  Can you explain a bit further please?

Looking further, it's already implemented in the way that I think makes sense. There's a container of generic entities `mSceneEntities` which is the MASTER list of entities in the scene, and contains both the layers AND the terrain. This one should just be used whenever you want to iterate over "objects" in the scene (layers + terrain). And then we only iterate over `mLayerEntities` when we specifically NEED map layer related objects.

**Comment by ptitjano** [comment]
> @ptitjano sorry I am a bit lost. What is the actual problem you are trying to solve in this PR?
> 
> Is it that Qgs3DMapScene contains `mTerrain`, `mSceneEntities` and `mLayerEntities` - and you would prefer to have just one member variable for all those things? Or are there some other issues you would like to fix?
> 
> In the current state of the PR with the introduction of QgsDummyLayer, I do not really see how improves the code...

Thanks for your comments @wonder-sk and @nyalldawson 

Right now, each entity is associated with one layer expect the terrain entity because it can come from rasters, mnt, meshes, multiple layers, etc.. 

In `Qgs3DMapScene` (and other parts of the 3d code), there is some specific code to deal with this special case. The main idea of this PR is to have a one layer equals one entity logic for the terrain by creating a `QgsDummyLayer`.

This way, this moves 2 logic out of `Qgs3DMapScene` : 
- the creation and deletion of the terrain is now in `QgsTerrainLayer3DRenderer`
- the pending jobs logic is simplified: there is now no specific code for the terrain

The removal of `mSceneEntities` is merely a nice side effect of this PR.   
I realize that introducing a `QgsDummyLayer` is somewhat controversial. It introduces a new layer in the core to deal with a special 3d case. Again, the main idea here is to have a terrain entity which behaves as the other ones. Maybe, it could be renamed `QgsTerrain3DLayer`?

**Pull request closed without merging**
