### PR TITLE
dev splash with avatars of most active committers

### PR DESCRIPTION
**Pull request by 3nids**
Due to covid, we don't get new dev splash screen :(

I made a mosaic with the github avatars of the 90 most active committers on main repo (this can be discussed if we want to add faces of the documentation team).

Thumbs up or down to say if you like it.

splash

### CODE REVIEW

**Comment by nyalldawson** [comment]
I like this idea!

I wonder how it would look if you applied a similar green (or other qgis brand colour) overlay over the collage, like we do for the stable release?

**Comment by j-lippmann** [comment]
I like the idea! ...and all other commiters in small letters around the avatar mosaic ?

**Comment by raymondnijssen** [comment]
That would look like this: 
image

**Comment by nirvn** [comment]
@3nids , great idea. +1 for green shading. I'd also consider changing color of the gray square to be QGIS-green with white text on top.

**Comment by nyalldawson** [comment]
@3nids another thought I had -- should we give the committers a chance to send in an alternate photo? (with a time deadline, of course! :laughing: ). There's a few missing avatars, and some pics I'd imagine contributors would like to replace with an actual photo of themselves (or vice versa!)

**Comment by nyalldawson** [comment]
@nirvn 
> great idea. +1 for green shading. 

I think I prefer the original colorful one to be honest ...

**Comment by 3nids** [comment]
here you go

place your alternate avatar at images/splash/dev-splash/alternate-avatars/[__GITHUB_USER__].png
and it will be placed in the mosaic.

splash

**Comment by 3nids** [comment]
with splashscreen message:

image

**Review by nirvn — APPROVED** [review]
Let's go for it! Nice one.

**Comment by mbernasocchi** [comment]
Fantastic! Thanks @3nids!

**Pull request merged**
