### PR TITLE
Fix incorrect annotation scaling when exporting layouts

### PR DESCRIPTION
**Pull request by nyalldawson**
Previously, annotation size and position always used pixel units. This
did not work well when exporting layouts, resulting in tiny annotations
(it also caused issues when moving projects between hidpi/non hidpi
displays).

Instead, use millimeters for annotation size and position so that the
appearance is consistent across displays and works correctly in layout
exports.

Add lots of unit tests covering this.

Fixes #18373

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , will that also fix exporting of annotation in high DPI via save [canvas] as image/PDF... ? I assume so. Woupidou.

**Comment by nyalldawson** [comment]
@nirvn yes, should do!

**Comment by nirvn** [comment]
@nyalldawson , testing now.

**Comment by nirvn** [comment]
Yep, perfectly sized high DPI image/PDF export of map canvas annotations. 

Skipped through the code, looking good.

**Pull request merged**
