### PR TITLE
Switch browser dock buttons to toolbar

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR switches the browser dock's button bar to a proper toolbar. Seeking feedback whether this change is desired, and if so I'll switch all the other dock widget's buttons across to toolbars...

### CODE REVIEW

**Comment by m-kuhn** [comment]
What are the most important pros/cons?

**Comment by nyalldawson** [comment]
I'm not aware of any cons. For reference, here's what the browser using a toolbar compared with the layers panel not using one looks like in OSX:
screen shot 2015-05-30 at 9 46 04 pm

**Comment by nyalldawson** [comment]
To be honest, there's still a heck of a lot of ugliness in QGIS running under OSX 10.10, but that's not fixable until we switch to Qt5 builds.

**Comment by nirvn** [comment]
I think you should go ahead and transform all the panels. On Linux and Windows - using the default theme - this commit will keep things visually identical. 

The fact is, ATM, the matching look is "accidental" and the day an OS' default theme decide to render tool buttons differently from toolbar buttons (as is the case with OS X), things risk being as ugly as OS X.

These top-row buttons are undoubtedly intended to be toolbar buttons of a given panel. Making the change just insures we use the proper QT UI semantic in this case.

**Comment by m-kuhn** [comment]
Looks good with the GTK+ and the plastique themes

**Comment by timlinux** [comment]
For reference here is a 'before' view so you can contrast it with @nyalldawson's pic above:

screen shot 2015-05-30 at 15 36 14

Switching to a toolbar will already be a big improvement.

**Comment by NathanW2** [comment]
+1 to use a toolbar

**Pull request merged**
