### PR TITLE
Add "persist layer metadata" checkbox to export vector file dialog

### PR DESCRIPTION
**Pull request by nyalldawson**
When checked (as it is by default), any layer metadata present in the
source layer will be copied and stored in the newly created destination
file.

So e.g. when right clicking a layer a project (or browser) with metadata
attached and exporting to a new format, this option will ensure that
the metadata is nicely transferred over to the newly created gpkg.

### CODE REVIEW

**Comment by roya0045** [comment]
For the enventual documentation. Are all writable vector formats supported by this?

**Comment by nyalldawson** [comment]
> Are all writable vector formats supported by this?

Yes, but any non-gpkg formats will resort to storing the metadata as a .qmd sidecar file

**Review by nirvn — APPROVED** [review]
Nice one.

**Comment by roya0045** [comment]
> > Are all writable vector formats supported by this?
> 
> Yes, but any non-gpkg formats will resort to storing the metadata as a .qmd sidecar file

Thank you, this is an important detail to have! On import will qgis always lookup for the associated qmd? Let's say I send someone a geojson with the qmd or a colleague uses a  file with and existing qmd, will it be loaded automatically? I couldn't find anything in the PR diff, maybe it was done earlier. 

I suspect this is a non-issue but does it behave well with files that contain multiple layer? Say in a spatialitte with 4 layers and only layer B and D have metadata in the qmd.

**Comment by nyalldawson** [comment]
@roya0045 
> On import will qgis always lookup for the associated qmd?

Yes, correct -- just like a qml file if there's a qmd file matching the base part of the file name it will be loaded automatically when the layer is loaded

> I suspect this is a non-issue but does it behave well with files that contain multiple layer? Say in a spatialitte with 4 layers and only layer B and D have metadata in the qmd.

No, it doesn't behave well :) For non-gpkg files the .qmd metadata will apply to all layers in the file. We need to address that differently depending on the actual format (Eg spatialite we can make a qgis_metadata table). But that's out of scope for now, I only needed gpkg metadata storage and don't use spatialite/etc myself!

**Comment by roya0045** [comment]
@nyalldawson Thanks for the clarifications!

**Pull request merged**
