### PR TITLE
Advertise that QGIS can open .qgz files

### LINKED ISSUE #39204: QGIS on macOS can save file in qgz-format, but won't open files in qgz format
Hello,

I hope this is the right place to post, I was confused about this phenomenon. Qgis 3.12 on Mac won't let me open qgz-files. They are greyed out during Open file-selection process.

### PR DESCRIPTION
**Pull request by grischard**
## Description

Advertise .qgz file support on macOS. Fixes ~~#39204~~ #42033.

Mac icon for qgz included.

This PR can also be backported to all currently maintained versions.

### CODE REVIEW

**Comment by grischard** [comment]
CC @SrNetoChan apparently you created https://github.com/qgis/QGIS/blob/master/images/icons/mac/qgs.icns . Would it please be possible to create a QGZ icon if you still have the source files?

**Comment by nyalldawson** [comment]
@PeterPetrik

**Review by PeterPetrik — APPROVED** [review]

**Comment by grischard** [comment]
Thank you all!

**Comment by grischard** [comment]
Oops, it looks like the qgz.icns file was empty. I'll create another PR...

**Pull request merged**
