### PR TITLE
Ensure that class \brief comes before \since

### PR DESCRIPTION
**Pull request by nyalldawson**
Otherwise it breaks the Python docstrings, which require the brief to come first

### CODE REVIEW

**Comment by nyalldawson** [comment]
@3nids another small fix for you

**Comment by nyalldawson** [comment]
This should fix up the messed up class description seen in https://qgis.org/pyqgis/3.0/analysis/Network/QgsNetworkStrategy.html

**Comment by nyalldawson** [comment]
The spacing fix should improve this situation:

image

**Comment by nyalldawson** [comment]
Thanks @3nids! How do new pyqgis doc builds get triggered?

**Comment by 3nids** [comment]
the doc will be triggered automatically (daily for master on tags for releases) but it is not activated yet since it uses dev version of SIP. 
I am waiting for next SIP release to integrate it into the procedure (Phil told me it should arrive next to Qt release, so shouldn't be too long!)

**Pull request merged**
