### PR TITLE
[FEATURE] [needs-docs] Allow filtering in QgsMessageLogViewer

### PR DESCRIPTION
**Pull request by mbernasocchi**
## Description
this PR adds the capability of filtering QgsMessageLogViewer logs by loglevel and by a message string filter

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contains sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by mbernasocchi** [comment]
@m-kuhn if you have a second could you let me know what you think of this

**Comment by NathanW2** [comment]
Can't use a table widget here as it blows memory and slows the application
down a ton.  Used to be a table widget and we swap to plain text to keep it
fast

**Comment by mbernasocchi** [comment]
@NathanW2 ok, I guessed that would be the possible issue. do you see an other way?

**Comment by m-kuhn** [comment]
QTableView instead of QTableWidget maybe?

**Comment by NathanW2** [comment]
I suspect it's the same issues. Just with loads of messages it's just heavy
on memory and slow.

**Comment by m-kuhn** [comment]
With a view it's up to you to implement a proper memory management. You could even attach a database for saving the messages.

**Comment by NathanW2** [comment]
If you think that will work then I'm ok with it just needs to be light and
fast when appending messages.  Attaching to a database might be a good idea
and saving a session ID along with the message so we can keep a full log
all the time.

**Comment by nyalldawson** [comment]
We could/should remove the tabs here as well, if we're allowing filtering by category.

**Comment by mbernasocchi** [comment]
@m-kuhn, @NathanW2 I can't say about perfotmance. C++ is way iver my head :)

@nyalldawson so adding a dynamic combo that lists the tag names? I like that

**Comment by m-kuhn** [comment]
> so adding a dynamic combo that lists the tag names

or an editable combobox. If you chose an entry it will write `tag: plugins` and full text filter if you write something like `Exception`, pretty much like github issue search ;)

**Comment by mbernasocchi** [comment]
thanks for all the feedback, will have a look at this in Nodebo

**Comment by NathanW2** [comment]
@mbernasocchi are you still keen to tackle this?

**Comment by mbernasocchi** [comment]
@NathanW2 I am, but not sure I'll find the time to get on this.

**Comment by mbernasocchi** [comment]
unfortunately you're correct

**Pull request closed without merging**
