### PR TITLE
Improve QGIS Server WMS GetCapabilities output

### LINKED ISSUE #35696: QGIS Server WMS 1.3.0 GetCapabilities: misplaced ContactPosition tag
**Describe the bug**

`<ContactPosition>` is not a member of `<ContactPersonPrimary>`.

The `GetCapabilities` document from QGIS Server returns:
```xml
   <ContactPersonPrimary>
    <ContactPerson>Gustavo</ContactPerson>
    <ContactOrganization>Geomaster</ContactOrganization>
    <ContactPosition>Manager</ContactPosition>
   </ContactPersonPrimary>
```
It should be:
```xml
   <ContactPersonPrimary>
    <ContactPerson>Gustavo</ContactPerson>
    <ContactOrganization>Geomaster</ContactOrganization>
   </ContactPersonPrimary>
   <ContactPosition>Manager</ContactPosition>
```

**OGC WMS specification**

[OGC WMS Specification](https://portal.ogc.org/files/?artifact_id=14416)

```xml
<element name="ContactInformation">
    <annotation>
        <documentation>
Information about a contact person for the service.
        </documentation>
    </annotation>
    <complexType>
        <sequence>
            <element ref="wms:ContactPersonPrimary" minOccurs="0"/>
            <element ref="wms:ContactPosition" minOccurs="0"/>
            <element ref="wms:ContactAddress" minOccurs="0"/>
            <element ref="wms:ContactVoiceTelephone" minOccurs="0"/>
            <element ref="wms:ContactFacsimileTelephone" minOccurs="0"/>
            <element ref="wms:ContactElectronicMailAddress" minOccurs="0"/>
        </sequence>
    </complexType>
</element>
```

**How to Reproduce**

- Publish a project
- Request the GetCapabilities document
- The return document can not be validated.

**Validation 1.3.0**

Validating on the web: http://inspire.ec.europa.eu/validator/

validator

Validating on the command line (example):
```bash
wget "http://gismar.eu/postgresql/sigram/public/instrumentos/cgi-bin/qgis_mapserv.fcgi?service=WMS&request=GetCapabilities&version=1.3.0" -O GetCapabilities.xml
StdInParse -v=always -n -s < GetCapabilities.xml
```
Error:
```
Error at (file stdin, line 17, char 27): element 'ContactPosition' is not allowed for content model '(ContactPerson,ContactOrganization)'
```

**Validation 1.1.1**

The same happens with version 1.1.1

Validating on the command line (example):
```bash
wget "http://gismar.eu/postgresql/sigram/public/instrumentos/cgi-bin/qgis_mapserv.fcgi?service=WMS&request=GetCapabilities&version=1.1.1." -O GetCapabilities111.xml
StdInParse -v=always -n -s < GetCapabilities111.xml
```
Error:
```
Error at (file stdin, line 17, char 27): element 'ContactPosition' is not allowed for content model '(ContactPerson,ContactOrganization)'
```
**QGIS and OS versions**

QGIS-Master

### PR DESCRIPTION
**Pull request by jgrocha**
## Description

This PR improves QGIS Server WMS GetCapabilities output.

Fixes #35696, #35701, #35717 and #35710

It also fixes the output when only one of `<ContactPerson>` or `<ContactOrganization>` is filled. If one is filled, both should be written to parent `<ContactPersonPrimary>`.

### If the title is missing

If Project → Properties → QGIS Server → Service Capabilities → Title is not filled by the user, there is no OWS Title. If this is the case, we use the project's title (Project → General → Project title). Only if project's title is not set, we use '<Title>untitled</Title>'.

### If the Person or Organization is missing

If both are missing from Project → Properties → QGIS Server → Service Capabilities , there is no problem. 
But if one of them is defined, we need both filled to create a valid `<ContactPersonPrimary>`. The other uses the _unknown_ default, like:
```xml
 <Service>
  <Name>WMS</Name>
  <Title>Antivirus</Title>
  <KeywordList>
   <Keyword vocabulary="ISO">infoMapAccessService</Keyword>
  </KeywordList>
  <OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http:" xlink:type="simple"/>
  <ContactInformation>
   <ContactPersonPrimary>
    <ContactPerson>Gustavo</ContactPerson>
    <ContactOrganization>unknown</ContactOrganization>
   </ContactPersonPrimary>
   <ContactPosition>Treinee</ContactPosition>
  </ContactInformation>
  <Fees>conditions unknown</Fees>
  <AccessConstraints>None</AccessConstraints>
 </Service>
```

### CODE REVIEW

**Comment by rldhont** [comment]
@pblottiere what do you think about ogc tests?

**Comment by pblottiere** [comment]
Hi @rldhont,

> what do you think about ogc tests?

I think I've to run these tests before merging this PR to avoid any unwelcome surprises :).
As soon as Travis is green, I'll take a look. Do not hesitate to ping me.

And thanks for your concern :+1:.

**Comment by jgrocha** [comment]
> Hi @rldhont,
> 
> > what do you think about ogc tests?
> 
> I think I've to run these tests before merging this PR to avoid any unwelcome surprises :).
> As soon as Travis is green, I'll take a look. Do not hesitate to ping me.
> 
> And thanks for your concern +1.

Thank you both @rldhont @pblottiere for looking to this PR. Your help is really appreciated. It would be awesome to have OGC tests running on top of QGIS Server.

_The TRAVIS will not change to green, unless someone changes the TRAVIS configuration. The error is not related to this PR (other OR are failing as well). I've already raised the concern about TRAVIS on dev's mailing list._

**Comment by elpaso** [comment]
> > Hi @rldhont,
> > > what do you think about ogc tests?
> > 
> > 
> > I think I've to run these tests before merging this PR to avoid any unwelcome surprises :).
> > As soon as Travis is green, I'll take a look. Do not hesitate to ping me.
> > And thanks for your concern +1.
> 
> Thank you both @rldhont @pblottiere for looking to this PR. Your help is really appreciated. It would be awesome to have OGC tests running on top of QGIS Server.
> 
> _The TRAVIS will not change to green, unless someone changes the TRAVIS configuration. The error is not related to this PR (other PR are failing as well). I've already raised the concern about TRAVIS on dev's mailing list._

... or until somebody close the PR and open it again :) 
The issue in travis was fixed yesterday.

**Comment by pblottiere** [comment]
> It would be awesome to have OGC tests running on top of QGIS Server.

+1. It's an ongoing investigation ;).

**Comment by pblottiere** [comment]
OGC tests are green :+1:

a

**Review by rldhont — APPROVED** [review]

**Pull request merged**
