### PR TITLE
[FEATURE][processing] Alpha channel for rasterize algorithm

### PR DESCRIPTION
**Pull request by Trashmonk**
Originally the background colour defaulted to white with no transparency for areas without vector data. I have added an alpha channel to the geotiff and set it zero (full transparency) for areas with no vector data. This could be optional, in case the user wants a solid background.

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks a lot, that looks like a great addition.
If you could add the parameter for the alpha channel, that would be great. It will increase the image size by 33% and is not required for all use cases (e.g. not required if it's the backmost layer).

There are some small code style changes also required, see [here](https://travis-ci.org/qgis/QGIS/jobs/319610378#L640-L680)

**Comment by Trashmonk** [comment]
Ok, so I have updated the script so the user has an option to turn transparency on or off. I also fixed the code style errors. This is the first time I have ever done a pull request, so sorry if I messed anything up.

**Comment by m-kuhn** [comment]
It's just some leftover spaces now. If you are working on Linux you can follow these instructions to get these things fixed automatically: https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis

On windows I have heard some people got it to run but don't know how, so I'd resort to manually make sure you don't have trailing spaces on the lines and are otherwise PEP 8 compliant ;)

**Comment by Trashmonk** [comment]
I have run prepare-commit.sh and it has removed all the leftover spaces. That should be it hopefully.

**Comment by m-kuhn** [comment]
Good job, thanks a lot :christmas_tree:

**Pull request merged**
