### PR TITLE
Cherry-picking @aaime works on SLD to release-2_14

### PR DESCRIPTION
**Pull request by rldhont**
This the backport of SLD fixing made by @aaime it also integrate other fixes from @rouault and @nyalldawson.
- Do not generate a ogc:Filter where a ogc:Expression is expected. #3366
- Emit valid SLD when mm are used as symbol unit #3414
- Export map level scale based dependencies in most vector symbology #3436
  And also:
- Fix first range when exporting graduated renderer to sld (fix #15212)
- Fixes #14119: Ensure the OGC filter XML expression contains the GML namespace references

### CODE REVIEW

**Comment by rouault** [comment]
No objection from me in backporting c547db6f4770f41119fc0fcbfabca4515a176c0e

**Comment by m-kuhn** [comment]
@rouault could you cherry-pick the ones you reviewed? Will be easier to go in smaller pieces than in a big package.

**Comment by rouault** [comment]
I'm not sure of the interaction of all commits, so if I just cherry-pick that one, that might break the build because of fixes in later commits, whereas if everyone agrees, then we just have to hit the Merge button.

**Comment by rldhont** [comment]
Hi @m-kuhn I can manually merge the @rouault one if you prefer!

**Comment by m-kuhn** [comment]
I thought they are quite independent?

**Comment by rldhont** [comment]
I need the @rouault commit to backport sld!

**Comment by rldhont** [comment]
I'll backport the @rouault commit and rebase this PR

**Comment by m-kuhn** [comment]
Looks good to me.
I wonder if you want to write "Added in QGIS 2.14.8" to avoid confusion.

**Comment by nyalldawson** [comment]
+1 to backport eb02d1715d7a0264701d8587854986c5e60d14ec

**Comment by rldhont** [comment]
eb02d17 backported

**Comment by rldhont** [comment]
Note added updated

**Comment by m-kuhn** [comment]
Thanks. Waiting for test results and then good to go!

**Comment by rldhont** [comment]
All tests are good!

**Pull request merged**
