### PR TITLE
[Bugfix] QPainter simplification (fixes #14301)

### PR DESCRIPTION
**Pull request by ahuarte47**
This pull moves the local "on-the-fly" simplification from the FeatureIterator class to just where the geometry is converted to be drawed for the current QPainter device.

It avoids that simplification changes the geometry fetched from vector data providers.

This pull fixes the issue [14301 - simplification makes geometry-based expression values (such as $area) vary for symbology and labels](http://hub.qgis.org/issues/14301).

### CODE REVIEW

**Comment by nirvn** [comment]
@ahuarte47 I'm very excited to see you undertaking this.

**Comment by strk** [comment]
+1

**Comment by nyalldawson** [comment]
Just so I understand this fully - this means  there's no longer server side simplification for postgres sources?

**Comment by ahuarte47** [comment]
No, the server side simplfication remains unchanged, only the local simplification is affected by this pull

**Comment by nirvn** [comment]
@ahuarte47 , @nyalldawson , does server-side simplification affect the geometry-based expression functions such as $area? I assume it does.

**Comment by ahuarte47** [comment]
Hi @nirvn, You are right, but it has not solution. If you have a postgis layer with $area expressions, you   only can use local simplification.

**Comment by 3nids** [comment]
Or if at some point expressions are sent back to the provider. Matthias,
does it seems feasible using expression server compiler ?

Le sam. 12 mars 2016 8:36 AM, Alvaro Huarte <notifications@github.com> a
écrit :

**Comment by m-kuhn** [comment]
> Or if at some point expressions are sent back to the provider. Matthias,
does it seems feasible using expression server compiler ?

Absolutely, that's definitely on my list

**Comment by nyalldawson** [comment]
@ahuarte47 I was thinking about this work yesterday, and have an idea. Given that this PR makes it so simplification is only applied right before rendering, what do you think about exposing a choice of simplication techniques to the user? I know we've already got a few algorithms floating around (eg the douglas peucker simplification and your other PR with the snap to grid experiment). What I'd love to see possible in QGIS one day would be the ability to dynamically simplify layers using the Visvalingam method (See https://github.com/mbloch/mapshaper/wiki/Simplification-Tips). It produces much more cartographically pleasing simplification over the Douglas-Peucker method, as the later preserves sharp corners while the Visvalingam method instead retains the overall shape of features and removes jagged spikes.

You can see this in action here http://www.mapshaper.org/ - this is the type of thing I would love to see in QGIS one day. Live, on-the-fly, topographically preserving simplification :)

But the first step could be allowing users to select from a choice of existing simplification methods for rendering.

**Comment by ahuarte47** [comment]
Hi Nyall, thanks for your review! the idea about exposing a choice of simplication techniques to the user is great. I can merge to this pull the SnapToGrid algorithm, and a new option in the related panel.

image


Do you agree?

**Comment by ahuarte47** [comment]
Hi @nyalldawson, I am experimenting with the Visvalingam algorithm. I have integrated two implementations[*], but I am a bit frustated. The code is very slow compared than current "distance" or "snaptogrid" options.

[*] Tested implementations:
https://github.com/shortsleeves/visvalingam_simplify/tree/master/src
https://github.com/mapnik/mapnik/blob/master/include/mapnik/simplify_converter.hpp

**Comment by ahuarte47** [comment]
Visvalingam implementation from liblwgeom works fine. I remove other experiments previously commented, Them are slower or they fail with some shapes tested.

**Comment by nirvn** [comment]
@ahuarte47 are you still planning on finishing this exciting PR during this development cycle?

**Comment by ahuarte47** [comment]
Hi @nirvn; I suppose that the code of this PR is finished. It is waiting a review of somebody with privileges to finally to merge if it is considered interesting.

**Comment by nirvn** [comment]
@ahuarte47 good to know :) it might be useful to get the travis build go green, that should help getting it reviewed. 

Thanks for your work on this.

**Comment by ahuarte47** [comment]
I see faling the TestQgsGeometryGeneratorSymbolLayerV2 test and doc-covergare tests.

**Comment by nirvn** [comment]
@nyalldawson , is the travis failure simply a case of updating the mask file, or does it indicate something wrong? If I do an eye comparison of the rendered and expected images, it seems there s virtually nothing changed, probably only some antialiased border pixels here and there.

**Comment by ahuarte47** [comment]
@nirvn. you are right. I am trying to execute these python tests from console to update the images. But I am not able to run properly. I use windows 10 + Visual studio 2015 + python 2.7, and I get many errors (arggg!). Sorry!

**Comment by m-kuhn** [comment]
I'd rather completely replace the reference image and not update the mask. The old image will probably no longer have any use after this has been merged.

Actually, this pull request should improve the situation for geometry generators since the effect of a simplified source geometry can be multiplied by operations such as buffering. On the other hand the result geometry can just as well profit from pre-rendering simplification.

**Comment by nirvn** [comment]
@m-kuhn you're right, makes sense.

It'd be great to commit this PR asap, it's the kind of (amazing) improvement that deserve as much testing prior to release as possible.

**Comment by ahuarte47** [comment]
If you agree, somebody could send me the new images rendered from these python tests to replace them as reference images. it would be helpful for me.

**Comment by m-kuhn** [comment]
If you download them from the test results? http://dash.orfeo-toolbox.org/testDetails.php?test=40524088&build=227101

**Comment by ahuarte47** [comment]
Oh! thank you very much!, my apologies, I didn't know that them were available.

**Comment by m-kuhn** [comment]
Just scroll all the way down on the travis page, there's a yellow link if the tests failed. (There are also some build warnings which you will need to fix to make travis pass)

**Comment by mdouchin** [comment]
Hi all. What about also proposing equivalent of RemoveRepeatedPoints used in PostgreSQL server side simplification (for postgis >= 2.2 ) See https://github.com/qgis/QGIS/pull/2410

**Comment by nirvn** [comment]
@ahuarte47 , yay, travis is green! :)

**Comment by ahuarte47** [comment]
:-) I can not run the python tests, but I translated some of them to a c version and at last the errors disappeared

**Comment by ahuarte47** [comment]
Hi @mdouchin, I think that this algorithm is equivalent to the current "distance algorithm" used by default in QGIS.

The source code in postgis:
https://github.com/postgis/postgis/blob/svn-trunk/liblwgeom/ptarray.c#L1416

Kind regards
Alvaro

**Comment by m-kuhn** [comment]
sorry to ask you for hard work

**Comment by ahuarte47** [comment]
Hi, I am in Girona now. This afternoon I will update my branch to resolve these conflicts.

**Comment by nyalldawson** [comment]
@ahuarte47 great! Let's sit down sometime and go through this together :)

**Comment by ahuarte47** [comment]
Great! I am excited with it :-) now I am in the CartoDB workshop but this afternoon I will go to the QGIS workshops, sure I will learn many features. And english! (argh! my apologies)

**Comment by nyalldawson** [comment]
@ahuarte47 one last question - what's the motivation behind removing the ogr provider side simplification?

**Comment by ahuarte47** [comment]
Extra code that does not imrove the default implementation. 
--------------------------------------------
El jue, 26/5/16, Nyall Dawson <notifications@github.com> escribió:

 Asunto: Re: [qgis/QGIS] [Bugfix] QPainter simplification (fixes #14301) (#2900)
 Para: "qgis/QGIS" <QGIS@noreply.github.com>
 CC: "Alvaro Huarte" <ahuarte47@yahoo.es>, "Mention" <mention@noreply.github.com>
 Fecha: jueves, 26 de mayo, 2016 14:14
 
 @ahuarte47 one last question - what's
 the motivation behind removing the ogr provider side
 simplification?
 
 ---

**Comment by ahuarte47** [comment]
Hi Nyall. A comment more. I decided to remove it in order to avoid to write similar code and IMHO simplify the wkb raw stream  is little faster than using the ogr classes and their methods to get the internal geometry.
--------------------------------------------
El jue, 26/5/16, Nyall Dawson <notifications@github.com> escribió:

 Asunto: Re: [qgis/QGIS] [Bugfix] QPainter simplification (fixes #14301) (#2900)
 Para: "qgis/QGIS" <QGIS@noreply.github.com>
 CC: "Alvaro Huarte" <ahuarte47@yahoo.es>, "Mention" <mention@noreply.github.com>
 Fecha: jueves, 26 de mayo, 2016 14:14
 
 @ahuarte47 one last question - what's
 the motivation behind removing the ogr provider side
 simplification?
 
 ---

**Comment by ahuarte47** [comment]
Thanks @nyalldawson!, still makes sense to define a geometry data cache (with the simplified wkb version, area or perimeter values...) in the QgsRenderContext or a new QgsFeatureRenderContext class with specific methods ?

This would optimize the geometric expressions and to avoid run simplification twice in labeling.

**Comment by nyalldawson** [comment]
I think QgsRenderContext makes sense. @wonder-sk @m-kuhn any objections?

**Comment by nyalldawson** [comment]
By the way, fantastic work here... thanks for your efforts with this!

**Comment by ahuarte47** [comment]
Thanks to all! I hope you have a great hackfest!

**Comment by m-kuhn** [comment]
Awesome, that's really cool. Yeah, QgsRenderContext is fine I think, that's where the geometly is stored now already. If possible I'd try to get away from WKB but whatever works best for now is fine.

**Pull request merged**
