### PR TITLE
[FEATURE] Cache labeling result to avoid unnecessary redraws when refreshing canvas

### PR DESCRIPTION
**Pull request by nyalldawson**
This change allows the labeling results to be cached to an image following a map render. If the cached label result image can be reused for the next render then it will be, avoiding the need to redraw all layers participating in the labeling problem and resolving the labeling solution.

Basically this means that canvas refreshes as a result of changes to any NON-LABELED layer are much faster.

* Changing a layer which is part of the labeling solution still requires all labeled layers to be completely redrawn. Similarly use of blend modes within label settings for any layer requires all labeled layers to be completely redrawn (since flattening of the label results to an image blocks blend modes applying correctly to underlying layers)

### CODE REVIEW

**Comment by nyalldawson** [comment]
Another benefit - if the cached labels are being reused, the labels will be drawn instantly instead of after all other layers are drawn. This means a slow-to-render, non-labeled layer will now be drawn progressively under the labels from the previous render.

**Comment by nyalldawson** [comment]
I should note - this was partly inspired by some previous work done by @mhugo !

@mhugo - unfortunately I couldn't get funding to implement all the features from your earlier work (eg... no label layers). So this just implements caching of a single labeling result in the canvas.

**Comment by timlinux** [comment]
👍 Great to see this coming to master, thanks @nyalldawson !

**Comment by timlinux** [comment]
👍 Great stuff thanks @nyalldawson !

**Comment by gioman** [comment]
@nyalldawson thanks! very important improvement!

**Review by wonder-sk — APPROVED** [review]
Looks great!

**Comment by nyalldawson** [comment]
Thanks @wonder-sk !

**Pull request merged**
