### PR TITLE
Release 2 18

### PR DESCRIPTION
**Pull request by cdavila**
## Description
Fix typo as requested at https://github.com/qgis/QGIS/pull/5786#discussion_r155934595

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by mach0** [comment]
branch has conflicts? and could you probably squash the commits to one single commmit?

**Comment by m-kuhn** [comment]
@cdavila can you git rebase on release-2_18 to fix conflicts? Let me know if you need assistance.

**Comment by cdavila** [comment]
It seems some of my local changes were not committed correctly and now are generating conflicts. I would thank any help to solve the problem, I'm quite lost with github

**Comment by m-kuhn** [comment]
The easiest would probably be to start on a new branch.

1. Copy the file i18n/qgis_es.ts somewhere
2. Checkout release-2_18
3. Create a new branch
4. Copy the file back
5. Review changes
6. Commit and open a new pull request

**Pull request closed without merging**
