### PR TITLE
Add an identify tool to elevation profile widget 

### PR DESCRIPTION
**Pull request by nyalldawson**
Allows identifying features in the chart via either a single click or click-and-drag rectangle. Results are shown in the standard identify results dock. Works for vector, raster, mesh and point cloud layers!

### CODE REVIEW

**Comment by nyalldawson** [comment]
For review purposes: there's ugliness here which I'm not particular proud of. The existing identify classes are a spaghetti mess API, and because the identify tool results classes are all in gui there's some gross hacks I've had to use (the same hacks as the 3d canvas identify tool is using too). The identify tool classes are screaming for a cleanup in general, but I can't do that here. 

Also -- identification of COPC results in a deadlock, as the local event loop in QgsRemoteCopcPointCloudIndex::nodeData is called on the main thread and causes additional UI events to be queued, ultimately resulting in the deadlock. That's unrelated to this PR, and I see the same deadlock occur when navigating 3d scenes with COPC sources. (Is it time for us to put a hard ban on QEventLoop use without a ` if ( QThread::currentThread() != QCoreApplication::thread() )` guard? I think so...!)

**Comment by nirvn** [comment]
Ouh, I'm exited at this one.

**Review by wonder-sk — APPROVED** [review]
Looks good to me!

**Comment by wonder-sk** [comment]
> The identify tool classes are screaming for a cleanup in general, but I can't do that here.

Agreed!

> Also -- identification of COPC results in a deadlock, as the local event loop in QgsRemoteCopcPointCloudIndex::nodeData is called on the main thread and causes additional UI events to be queued, ultimately resulting in the deadlock. That's unrelated to this PR, and I see the same deadlock occur when navigating 3d scenes with COPC sources.

There's a plan to fix these things after the feature freeze, right now we're trying to put the remaining features together...

> (Is it time for us to put a hard ban on QEventLoop use without a if ( QThread::currentThread() != QCoreApplication::thread() ) guard? I think so...!)

Good question. It would definitely make things more stable. We should also identify the existing cases of QEventLoop in main thread and try to solve them, which may be hard (things like WMS provider's constructor doing a GetCapabilities request and waiting for reply). As a part of this effort we would need to come up with API / implementation guidelines - such as never blocking main thread when we don't have things fully in control (e.g. in case of http requests)...

**Comment by nyalldawson** [comment]
@wonder-sk I've been wondering if we could do this as a temporary approach:

1. Subclass QEventLoop to QgsEventLoop
2. Add a check in QgsEventLoop constructor and qwarn if in main thread
3. Add code layout script to flag use of QEventLoop (with some "I really know this is safe" override comment you can put on a line)

**Comment by wonder-sk** [comment]
@nyalldawson yeah maybe that would be a good start...

**Pull request merged**
