### PR TITLE
SLD parsing: handling ogc:Literal within CssParameter - backport 2.14

### PR DESCRIPTION
**Pull request by rldhont**
Backport PR #3996 to release 2.14 via #4034

### CODE REVIEW

**Comment by rldhont** [comment]
Hi @jgrocha, @luipir, @aaime this is the second backport.

**Comment by luipir** [comment]
@rldhont any reason to wait for the merge? you were waiting for travis build?

**Comment by rldhont** [comment]
@luipir I'm waiting for 1 review

**Review by luipir — APPROVED** [review]

**Review by luipir — APPROVED** [review]

**Review by luipir — APPROVED** [review]

**Review by luipir — APPROVED** [review]

**Comment by luipir** [comment]
executed test locally and all works

**Pull request merged**
