### PR TITLE
[FEATURE] Variable width buffers

### PR DESCRIPTION
**Pull request by nyalldawson**
Here's a cleaned up version of a geometry experiment I was playing with a month or so ago.

Adds geometry methods to create variable width buffers, including tapered buffers (with a specified start and end diameter) and variable width buffers from line string m values.

Also adds processing algorithms which expose these methods to processing.

Some pretty pictures:

Tapered buffers:

tapered

Variable width by m:

varaible_widthb

variable

Acute angle handling:

acute

### CODE REVIEW

**Comment by m-kuhn** [comment]
I didn't look at the code, but the pics look really sexy :+1:

**Comment by andreasneumann** [comment]
Looks really cool - looking forward to playing with it!

**Comment by slarosa** [comment]
Wow!

**Comment by NathanW2** [comment]
Sexy as heck.

**Comment by nirvn** [comment]
@nyalldawson , nice, so happy to see you've push this through the finish line.

I was wondering whether we could use part of this code to improve the arrow symbol symbology to allow zig-zagging arrows (right now, arrows can only be formed of max. 3 nodes). Just throwing food for thoughts here :)

**Comment by nyalldawson** [comment]
@nirvn I had the same thought.

I'll leave it as an exercise for the reader :)

**Comment by timlinux** [comment]
WOW nice! Does it support different widths on the left and right side of the line?

**Pull request merged**
