### PR TITLE
[nodetool] chained add vertex at endpoint

### PR DESCRIPTION
**Pull request by olivierdalang**
## Description

This PR allows to digitize several points at once when extending a line using the node tool.
This removes the frustration of having to click on the small add vertex button each time.

node

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] (N/A) Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [X] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] (N/A) Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] (N/A) New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

edit : changed a test according to new behaviour, which now passes

### CODE REVIEW

**Comment by m-kuhn** [comment]
Much better than before where only a single point could be added at once :+1: 

What's your opinion @wonder-sk ?

**Comment by nirvn** [comment]
+1

**Comment by lbartoletti** [comment]
Well done 👍  I think this deserves a little addition to the doc.

**Comment by nyalldawson** [comment]
Big +1, this is a huge usability improvement!

**Comment by wonder-sk** [comment]
Nice addition - that will indeed make life easier!

**Comment by roya0045** [comment]
I can't recall but is there a way to undo the latest point by default in the tool, it is expected that the used might make a misclick or if they want to drag the map out of habit and click. 

Would it be difficult to also implement a method to delete the last point? (If such a thing is not already in).

**Comment by olivierdalang** [comment]
> I can't recall but is there a way to undo the latest point by default in the tool, it is expected that the used might make a misclick or if they want to drag the map out of habit and click.

Due to how the feature is implemented, it is already possible to cancel points using undo (ctrl+z).

**Comment by roya0045** [comment]
> > I can't recall but is there a way to undo the latest point by default in the tool, it is expected that the used might make a misclick or if they want to drag the map out of habit and click.
> 
> Due to how the feature is implemented, it is already possible to cancel points using undo (ctrl+z).

Great, I just wanted to make sure it was doable someway. Thanks for the info.

**Comment by m-kuhn** [comment]
Thanks everyone (especially @olivierdalang )
Merged for broader review

**Pull request merged**
