### PR TITLE
Fix Html annotation background

### LINKED ISSUE #50638: Allow HTML annotations to have transparent background
### Feature description

HTML annotations allow a bit of flexibility however they do not seem to allow a transparent background as the container in the back (white) can't be accessed via the interface

image

This is the code used
<body 
style="background:rgba(0,0,0,0)">
<p style="color:red;text-align:center; font-size: 40px">Honduras<br> is<br>  great</p>
</body>

I have set the rgba to (0,0,0,0) which I think should render the background transparent but leaves a white box
image

### Additional context

Tried in QGIS dev version to do this

### PR DESCRIPTION
**Pull request by YoannQDQ**
- Fixes #50638

## Description

The HTML annotation always paints a white background over the annotation frame.
Here's an example with a semi-tranparent black frame and light gray text:

html_annotation_before

This PR correctly set the QWebPage palette to make it transparent. Result:

html_annotation_after

### CODE REVIEW

**Comment by YoannQDQ** [comment]
Hi @nyalldawson, could you explain to me how the annotation test images (e.g _./testdata/control_images/annotations/expected_html_annotation/travis/expected_html_annotation.png_) were generated? They need to be updated, but since the PyQgsAnnotation fails locally on my machine (even before this PR), I'm a bit stuck.

**Comment by Gustry** [comment]
You can have the artifact from the test in your CI at the bottom : https://github.com/qgis/QGIS/actions/runs/4780093463?pr=52858 I guess it help ?

**Comment by nyalldawson** [comment]
@YoannQDQ 

See https://github.com/qgis/QGIS/pull/52888 -- if you rebase off that PR it will make it much easier for you

**Comment by nyalldawson** [comment]
@YoannQDQ looking at the reference image changes, setting masks would be more appropriate here. See https://docs.qgis.org/testing/en/docs/developers_guide/unittesting.html#comparing-images-for-rendering-tests for guidelines on how to do this. 
(In the long run this will make the tests more robust vs replacing the existing images)

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
