### PR TITLE
ensure python-requests is available in the build

### PR DESCRIPTION
**Pull request by tomkralidis**
This PR fixes http://hub.qgis.org/issues/15368 to ensure python-requests is included as part of the build with the following specifics:
- windows: use internal library
- debian: use system-wide library
- rpm: use system-wide library

@jef-n/others: not sure if I'm missing anything here on the build front.  I will backport to master_2 and release-2_16 once this PR is merged.

### CODE REVIEW

**Comment by elpaso** [comment]
Generally speaking, I try to use `QgsNetworkAccessManager` for all http calls from Python, this approach has the clear advantage that proxy settings are automatically applied and `QgsAuthConfig` authentication plugins can be applied to the network calls if the endpoints require authentication.

I understand that `requests` and `httplib*` are popular solution in the Python world but I wonder if we should try discourage their use in favour of  `QgsNetworkAccessManager`.

**Comment by tomkralidis** [comment]
@elpaso agreed. In this case OWSLib is the critical path.  OWSLib made the move to requests some time ago, and it's a required library.  It is way cheaper to use OWSLib and take the hit on requests compared to rewriting MetaSearch's CSW support.

**Comment by elpaso** [comment]
@tomkralidis ok, thanks for the explanation.

**Comment by tomkralidis** [comment]
@jef: let me know if this needs anything from me to make it into master_2 and release-2_16.

**Comment by jef-n** [comment]
osgeo4w was already addressed by [#15368](http://hub.qgis.org/issues/15368).
debian in master_2 in 750e60f and backported to release-2_16 in 3fed3cf

**Pull request merged**
