### PR TITLE
[Processing] Differencing '' and None in string parameter

### PR DESCRIPTION
**Pull request by rldhont**
## Description

This commit enhances:
* [processing] dont set default value in param string, when passed null value d911671b0669d3654d85954b52e38a9f5e952d4a
* [Processing] None is the default value for parameters also for string ac4d776af018a34b8f9e3d67647b5dbcf7c90bf3

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rldhont** [comment]
In **[processing] dont set default value in param string, when passed null value** d911671, for optionnal string parameter a NULL value is set to '' even if the value passed is None. In this case, if default value is None, the value is set to '' by the code.

In **[Processing] None is the default value for parameters also for string** ac4d776, the default _default value_ is reset to None.

In this commit, if a NULL value is passed, which can be None, '' or an empty array, and the parameter is optional, the value is set to None if the value passed is not an empty string ''.

**Comment by nyalldawson** [comment]
Does this fix an existing issue? I'm nervous about making changes like this in the stable branch -- there's almost zero unit tests protecting this code in 2.18 and big chance of unintended side effects.

**Comment by m-kuhn** [comment]
@rldhont can you point to an issue in the tracker which is solved by this?

**Comment by rldhont** [comment]
Here is the issue: https://issues.qgis.org/issues/18989

**Comment by rldhont** [comment]
@volaya @m-kuhn @nyalldawson any suggestions ?

**Comment by m-kuhn** [comment]
I think no-one wants to actually make the call mainly for two reasons:

 * This affects all providers to fix an isolated R issue (although it might be an issue for other providers as well)
 * Even within the R provider there is the potential that people wrote scripts (for current 2.18 versions) that are built on the assumption of the current behaviour and which might break the same way your scripts from 2.14 are broken now

Questions that come to my mind

 * Does the possibility to change this only for the R provider exist
 * Can you clarify on the risk to break scripts written for current 2.18 versions

**Comment by rldhont** [comment]
So, I prefer to revert **[Processing] None is the default value for parameters also for string** ac4d776 and considering that 2.18 breaks 2.14 scripts and scripts has to be updated to be compatible with 2.18.

**Comment by nyalldawson** [comment]
I guess my vote would be to revert ac4d776 too. I think that breaking working 2.18 scripts would be worse than breaking a script on 2.14 to 2.18 transition. And let's just all be thankful that 3.x soaks these parameters with unit tests :)

**Comment by nyalldawson** [comment]
@rldhont I've opened a PR for the reversion of ac4d776 at https://github.com/qgis/QGIS/pull/7271 . Should that supersede this PR?

**Comment by rldhont** [comment]
@nyalldawson thanks

**Pull request closed without merging**
