### PR TITLE
Raster renderer UI improvements

### PR DESCRIPTION
**Pull request by nirvn**
This PR adds a right-click menu for the singleband pseudo-color renderer and the paletted tree view widgets to modify the color and transparency of multiple items in a single shot:
untitled

In addition, users can now delete multiple rows.

### CODE REVIEW

**Comment by nirvn** [comment]
Not sure who to assign this to. It's pretty straight forward UI stuff.

**Comment by 3nids** [comment]
yourself ? ;)

wouldn't it better to have a button color so you would change directly and interactively?
i.e. select the lines, click on the button and change directly (since Nyall added transparency to it) ?

**Comment by nirvn** [comment]
@3nids , for single item color change, double clicking on the color opens the great color dialog, not sure it makes sense to implement a right-click color wheel in this case.

This right-click method is in line with the categorized, graduated, and rule-based renderers' UI too, which is a nice consistency bonus.

**Comment by 3nids** [comment]
fine with me.
I am just not a huge fan of the page changing at the moment (same for vector symbols).
I would rather prefer to have the bottom part of the dock dedicated to this (as we have enough vertical space).
But as you say, it's inline with current behavior.
So good to go to me.

**Pull request merged**
