### PR TITLE
native text justification

### PR DESCRIPTION
**Pull request by roya0045**
## Description

Offshoot from #41392

Allows text justification (regular and full justification) of formatted text.

Part of the code was simply migrated from qgslayouttable. The rest was made.

### CODE REVIEW

**Comment by roya0045** [comment]
Something is strange as the wrapping and check code is barely changed and it doesn't seem to work anymore. I suspect it has to do with the size units provided. Windows build is progressing. If I don't get anymore linkage error things should progress more smoothly.

**Comment by roya0045** [comment]
Ok finally sorted out this and solved my minor mistakes.

**Comment by roya0045** [comment]
Not stale. Review pending.

**Comment by roya0045** [comment]
Closing temporarily for rework

**Comment by roya0045** [comment]
Code's fine after all

**Comment by roya0045** [comment]
There is some wonkyness on windows to get the size.

**Comment by roya0045** [comment]
Table unit settings on windows are off (setting 1mm width give 2 or 3) That may explain the  weird results related to wrapping.

**Comment by roya0045** [comment]
@nyalldawson windows doesn't seem to need scaling, as opposed to linux. Is this normal? The textHeight/textWidth seem to behave differently on different platform. Windows provide the same units as the width and height properties of the box.

**Comment by roya0045** [comment]
Waiting for review.

**Comment by roya0045** [comment]
updated for conflict

**Comment by roya0045** [comment]
standby

**Comment by roya0045** [comment]
same old

**Comment by roya0045** [comment]
ok

**Comment by roya0045** [comment]
staying alive

**Comment by roya0045** [comment]
ok

**Comment by roya0045** [comment]
ok

**Comment by nyalldawson** [comment]
Superseded by https://github.com/qgis/QGIS/pull/46251

**Comment by roya0045** [comment]
> Superseded by #46251

So only text justification would need to be integrated? I recall there were some issues between windows and linux that required a workaround when checking width, do you know if this is properly handled too or maybe it was just and issue in my version.

**Comment by nyalldawson** [comment]
@roya0045 
> So only text justification would need to be integrated?

No, that's already all there. Nothing left to add to the text renderer, so you could resurrect the layout label PR now and only leave the changes to the label item itself.

> I recall there were some issues between windows and linux that required a workaround when checking width, do you know if this is properly handled too or maybe it was just and issue in my version.

I can't spot any issues :smile:

**Comment by roya0045** [comment]
@nyalldawson great thanks! Glad this is sorted out.

**Pull request closed without merging**
