### PR TITLE
Processing providers updates

### PR DESCRIPTION
**Pull request by alexbruy**
Some UI changes to Processing toolbox:
- Homogenize providers names
- Show backend version in the provider description where possible or make sense
- Rename GdalOgrProvider to GdalProvider

Left — before, right — after
compare

### CODE REVIEW

**Comment by alexbruy** [comment]
Build failed because of problems with spellcheker execution, so I think it is safe to merge.

**Comment by volaya** [comment]
Great idea! This looks perfect to me

**Comment by Gustry** [comment]
I wonder if it's a good idea to display the version number in the menu.
I don't think it's useful for a lot of people.

Is-not enough to have it somewhere else (in the QGIS about ?)

**Comment by alexbruy** [comment]
@Gustry most of the providers (GDAL, SAGA, GRASS, OTB) can be updated separately and they versions not listed in QGIS about dialog. Moreover, you can install multiple versions of OTB or SAGA and switch between them

**Pull request merged**
