### PR TITLE
OAuth2 authentication method plugin

### PR DESCRIPTION
**Pull request by dakcarto**
## Description

**OAuth2 authentication method plugin** for QGIS authentication system:
- Supports authentication code, implicit and resource owner grant flows
- Currently defaults to interacting with user's default external browser, though an embedded one could be crafted using `QWebEngineView` ([see caveats on embedded web clients](https://github.com/pipacs/o2/pull/81) for OAuth2 within a native application)
- Allows for preconfigured connections, optionally read from default locations
- Offers caching of access token beyond QGIS restarts (and with linking to `libqt5keychain` library, can securely do so via user's Wallet/Keychain/Password Manager).
- Save/load complicated OAuth2 configurations
- Has documentation written (needs a bit of updating before submission)

Work produced by [Boundless Spatial](https://github.com/boundlessgeo) and sponsored by [Monsanto Company](https://github.com/MonsantoCo).

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contains sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by dakcarto** [comment]
A bit of background on [DownloadO2.cmake](https://github.com/MonsantoCo/QGIS/blob/oauth2-plugin/src/auth/oauth2/cmake/DownloadO2.cmake):

This authentication plugin utilizes the [`o2` C++ library](https://github.com/pipacs/o2) for OAuth2 support. During development of the plugin, several fixes and features needed to be added to `o2` and have just recently been merged into its master branch. This means that (other than Homebrew and possibly OSGeo4W) there will be no `o2` library packages available on most (Linux) platforms, let alone one with the most recent changes.

Initially, I approached solving this by using CMake's [ExternalProject](https://cmake.org/cmake/help/v3.0/module/ExternalProject.html) support to build a static (or shared) library, but this led to cross-platform build and packaging issues.

I settled on instead using CMake's `file(DOWNLOAD ...` support to initiate or verify a download of the `o2` source code from github at an appropriate recent commit. This download happens during the CMake configure step, though placing a pre-downloaded archive of the commit, e.g. `o2-<commit hash>.tar.gz`, in the QGIS build directory root can be used in a no-internet setup.

Then, once the download archive is expanded, the relevant `o2` library's source code bits are added to the plugin's compilation sources, instead of linking the plugin to a built `o2` shared or static library. This approach ensures the latest code revision of `o2` and clean compilation on all major platforms, **without** the need to maintain the `o2` source code _within_ the QGIS source tree.

**Comment by dakcarto** [comment]
Here is the current [HTML-formatted output of documentation](http://boundlessgeo.github.io/QGIS-Documentation/output/html/en/docs/user_manual/auth_system/auth_workflows.html#oauth-2-0-workflows) (to be a separate PR to docs repo).

Authored by @dakcarto, @SrNetoChan and @elpaso, with excellent graphics by @SrNetoChan.

**Comment by elpaso** [comment]
@dakcarto can we merge this please?

**Comment by dakcarto** [comment]
Anyone have concerns about merging this? There is a small laundry list of things to update, with regards to tweaking this plugin, but those could be worked on once merged.

**Comment by jef-n** [comment]
To me that DOWNLOAD thing is a concern.  I'd prefer to use a internal copy.

**Comment by dakcarto** [comment]
@jef-n, an internal copy is a reasonable approach. I just didn't want more third-party code to have to be maintained in the QGIS source tree. I can reformat the CMake and source for the plugin to have an internal copy of the pertinent `o2` source files.

**Comment by 3nids** [comment]
When git source is available why not using git submodules rather than hard copy of source? It makes life much easier.

**Comment by jef-n** [comment]
@3nids known to work vs. unsure whether it works (ie. might break builds).

**Comment by 3nids** [comment]
@jef-n well, I wonder if it wouldn't be worth at some point to just do it, we have a few external lib that would make sense.

@dakcarto can you move the oauth library to `external` top directory?

**Comment by nyalldawson** [comment]
> When git source is available why not using git submodules rather than hard copy of source? It makes life much easier.

I'd very much like to see this happen. There's lots in QGIS source we could (should?) move to submodules - e.g. the libdxfrw code could live in qgis/libdxfrw and just be a submodule from qgis/QGIS. It'd be much cleaner and make it easier to sync these external libraries with their upstream (and feed our fixes back upstream too)

**Comment by pcav** [comment]
I rememeber @timlinux was very skeptical about submodules - comments welcome.

**Comment by dakcarto** [comment]
@pcav wrote:
> I rememeber @timlinux was very skeptical about submodules - comments welcome.

Yes, this is why I avoided using submodules. We use them extensively at Boundless, but for QGIS project this would introduce a new methodology of working with the source code that might require current build scripts on _all_ platforms to need adjustment, e.g. some extra `git` commands to update submodules, etc.

While submodules are no big deal for a small- to medium-sized team, they certainly might be for the QGIS project, where we might spend a bunch of time asking people if they have updated their submodules and pointing them to docs on how to do it.

+1 for working with submodules, but the above caveats are not to be ignored and should be fully discussed on the mailing list prior to introducing submodules.

**Comment by dakcarto** [comment]
@3nids wrote:
> @dakcarto can you move the oauth library to external top directory?

Note sure I understand you correctly. Do you mean in the source tree, or in the build directory? I'm assuming you mean source tree.

Not sure it should go in the main source tree. The `o2` library is specific to only this plugin, so should be isolated to it, I think. Also, building the plugin is optional in the CMake setup.

At Boundless, we build such authentication method and regular C++ plugins _outside_ of QGIS src tree and against an existing QGIS dev install. Compilation times are minimal, e.g. ~10-30 seconds, then:

https://github.com/boundlessgeo/qgis-oauth-cxxplugin/

Our PR here is essentially a port of that self-contained plugin source into the QGIS source tree. Not sure I see a need to distribute the plugin's source code beyond its subdirectory. Unless you mean to put such external code in a standardized `external` or `src/external` directory?

**Comment by 3nids** [comment]
For git, I guess we could use cmake to pull the submodules. That would solve concerns regarding breaking existing build infrastructure.

If we keep source in tree, I would indeed advise to put it in [external](https://github.com/qgis/QGIS/tree/master/external) directory. My intention is to move others there too (libdfrw, qwt-polar). It's not a problem if it's only built as part of a plugin to me. But it makes sense to group all external libs in there.

**Comment by dakcarto** [comment]
@3nids wrote:
> For git, I guess we could use cmake to pull the submodules. That would solve concerns regarding breaking existing build infrastructure.

That is a good solution.

Note, the CMake [ExternalProject module](https://cmake.org/cmake/help/v3.0/module/ExternalProject.html) works well for auto-pulling git repos already. I did run into issues using it previously (reason I moved to using the Download function), but that was before I just decided to include the `o2` library's source code directly into the OAuth2 plugin. I can adapt the plugin to this new code layout, though.

Orfeo Toolbox has excellent examples of using ExternalProject for its [SuperBuild of dependencies](https://github.com/orfeotoolbox/OTB/tree/develop/SuperBuild/CMake).

To some degree, I think ExternalProject can replace the role of git submodules as well.

> If we keep source in tree, I would indeed advise to put it in external directory. My intention is to move others there too (libdfrw, qwt-polar). It's not a problem if it's only built as part of a plugin to me. But it makes sense to group all external libs in there.

Ok. Makes sense to me as well. Isolating all of the submodules/ExternalProjects there (when/if it is decided to use them) also makes sense.

**Comment by m-kuhn** [comment]
@dakcarto is this pull request still alive?

**Comment by nyalldawson** [comment]
@m-kuhn I've been looking at this one too. I think as it stands I'd categorise it as "very valuable, significant investment, but non-trivial changes remaining". I think in these (very rare) cases it's the right move to leave the PR open and hope that someone adopts it. What do you think?

**Comment by m-kuhn** [comment]
@elpaso will the Qt5 route render this pull request obsolete?

**Comment by elpaso** [comment]
@m-kuhn yes, it would be a completely different approach (and it would not require any external lib like `o2`)

**Comment by m-kuhn** [comment]
In this case I'm inclined to close this pull request.

**Comment by nyalldawson** [comment]
I've pushed this branch to https://github.com/qgis/QGIS/tree/oauth2 so that it's available if someone wants to take on this work and rework to use the Qt5 approach.

But in the meantime, let's close this PR - it's clear from the discussion above that no-one is currently planning on taking it on and getting it merge-ready.

**Comment by dakcarto** [comment]
@nyalldawson, @elpaso, @m-kuhn,

Sorry, missed the initial notification on recent discussions 11 days ago.

My case for using this PR's code now instead of waiting for a port to Qt5's class:

* Boundless **just got continued funding** to finish this PR (11 days ago, actually). So, it will become active again.
* QT_MIN_VERSION is still at 5.2.0 (5.9.0 if WITH_3D) and the QOauth2 classes in Qt5 didn't land until 5.8. 5.7.1 is in Debian stretch (stable)
* QOauth2 classes support only Authorization Code and Resource Owner, not Implicit, grant flows (as far as I can tell). The O2 library is more robust in this regard, and offers a more complete OAuth2 API. 
* Relevant work done here will be backported to the open source version for QGIS 2.
* Most of the work is done, with minimal work needed to complete PR (compared to refactoring for QOauth2 classes).

Lastly, this plugin (QGIS 2 version) was part of an OGC testbed, whereby Andreas Matheus extended it to overcome the base insecurity of using Authorization Code grant flow within the context of QGIS, by adding support for dynamic client registration:
http://docs.opengeospatial.org/per/17-021.html#_dynamic_client_registration_rfc_7591

The work done by Andreas Matheus should be included in this code base. I am unsure if his work can readily be supported by the native QOauth2 classes.

I propose reopening this PR and completing the work herein, then when someone has the time, porting it over to use the native QOauth2 classes in Qt5, when possible.

**Comment by luipir** [comment]
welcome back @dakcarto

**Comment by nyalldawson** [comment]
Yes, a HUGE welcome back @dakcarto! You've been missed here :)

I don't think anyone would block a resurrection of this work. It was closed mostly because no-one (at the time) was going to take it on and get it merge ready.

I suggest reopening when you're ready for a re-review.

> QT_MIN_VERSION is still at 5.2.0 (5.9.0 if WITH_3D) and the QOauth2 classes in Qt5 didn't land until 5.8. 5.7.1 is in Debian stretch (stable)

That should actually be 5.5 - master won't build with anything less.

**Comment by elpaso** [comment]
@dakcarto a warm welcome back! We've missed you for real! 

Happy to see this work resurrected.

**Pull request closed without merging**
