### PR TITLE
[processing] split GRASS r.sun algorithm into two (fix #21637)

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
r.sun has two opeartional modes which are mutually exclusive, using them together makes algorithm unusable. Also required parameter for one of the modes is missed from the description file. This PR splits r.sun algorithm into two separate tools, similarly to some other modules and also adds missed "time" parameter.

Fixes https://issues.qgis.org/issues/21637. Tests updated accordingly.

Marked for backporting to LTR, as it fixes broken algorithm.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by luipir** [comment]
this that trevis tests differs from the local tests when generated happend in other PRs too.
https://github.com/qgis/QGIS/pull/9774
not sure is this can be the source of the problem here or simply the tests are malformed

**Comment by alexbruy** [comment]
@luipir tests are correct, seems hashes on my local machine and on Travis are different.

**Comment by luipir** [comment]
> @luipir tests are correct, seems hashes on my local machine and on Travis are dif

that's strange

**Comment by nyalldawson** [comment]
> @luipir tests are correct, seems hashes on my local machine and on Travis are different.

This isn't uncommon -- small differences in gdal/proj/grass versions, and angle of the sun in relation to stonehenge on the 3rd last equinox from the next full moon seem to impact the results we see on Travis. At best these hash tests are just a protection against the algorithm totally breaking (ie. throwing an exception), and are really just an indicator that "something has changed". Responsibility lies with the committer/reviewer to ensure that the change is correct...

**Comment by alexbruy** [comment]
any objections to merge and backport to LTR?

**Comment by luipir** [comment]
> any objections to merge and backport to LTR?

oki for me... what's happend now with traveis? just a rerun solved? probably depend of solar activity ;)

**Pull request merged**
