### PR TITLE
Update v.neighbors

### PR DESCRIPTION
**Pull request by PedroVenancio**
Additional options for GRASS v.neighbors aggregate statistics.

## Description

GRASS v.neighbors (Neighborhood analysis tool for vector point maps) in QGIS, only have the default `count` method for aggregate statistics.

This PR adds the `sum`, `average`, `median`, `mode`, `minimum`, `maximum`, `range`, `stddev`, `variance`, `diversity` options, based on GRASS manual: https://grass.osgeo.org/grass82/manuals/v.neighbors.html

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
Hi @PedroVenancio, on some systems, like Ubuntu 22.04LTS and macOS, QGIS still uses GRASS 7.8. Will the algorithm also work on such systems?

**Comment by PedroVenancio** [comment]
Hi @agiudiceandrea 
Good point, these new functions were introduced by this commit from May 2020: https://github.com/OSGeo/grass/commit/00d12a775c627db1c8dd41563ed228c6330bec6c
But they were only pointed to 8.0.0RC1. 

Also, they are not in 7.8 manual https://grass.osgeo.org/grass78/manuals/v.neighbors.html 

Can you please check what is the behaviour using v.neighbors with the new aggregate methods on GRASS 7.8?

**Comment by agiudiceandrea** [comment]
@PedroVenancio, the modified algorithm works with GRASS 7.8 if the `method` parameter is set to `count` and the `points_column` parameter is not set. It obviously doesn't work and it outputs various error messages if the `method` parameter is set to a value other than `count` and / or the `points_column` parameter is set to a layer field name. The user doesn't have any clear hint on what's going wrong.

I'm concerned that this situation (GRASS algorithms working or not working depending on the GRASS version installed) may lead to same mess of the SAGA processing provider (which eventually was removed from QGIS).

**Comment by PedroVenancio** [comment]
Hi @agiudiceandrea 
> I'm concerned that this situation (GRASS algorithms working or not working depending on the GRASS version installed) may lead to same mess of the SAGA processing provider (which eventually was removed from QGIS).

Yes, I understand. Anyway, this change is only on master branch, and so it will not change the QGIS version shipped with Ubuntu 22.04LTS (3.22.4) along with GRASS 7.8.7. On another side, GRASS 8.2.1 is the current stable release, replacing 7.8.7. 

> the modified algorithm works with GRASS 7.8 if the method parameter is set to count and the points_column parameter is not set. It obviously doesn't work and it outputs various error messages if the method parameter is set to a value other than count and / or the points_column parameter is set to a layer field name.

I believe that, at least, it will not break models or scripts created using only `count` method. 

SAGA was a more complicated issue, with changes even between minor releases. But I don't know, what do you think @nyalldawson ?

**Comment by agiudiceandrea** [comment]
> the QGIS version shipped with Ubuntu 22.04LTS (3.22.4)

Currently, both QGIS 3.30 and QGIS 3.28 are available in the qgis.org repositories for Ubuntu 22.04, and I presume also QGIS 3.32 and next versions will be available unless the minimum version of some dependencies needed to buil QGIS will be increased to a version greater than that available on Ubuntu 22.04.

**Pull request merged**
