### PR TITLE
Remove `pending` prefixes from QgsVectorLayer methods

### PR DESCRIPTION
**Pull request by m-kuhn**
pendingFields() is not very intuitive and leads to confusion for (new) developers. The name `fields()` is straightforward and even shorter to write.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Ah yeah, and since `QgsFields` is implicitly shared it returns by value instead of const reference.

**Comment by nyalldawson** [comment]
@m-kuhn +1 from me, the name "pendingFields" has always confused me.

**Comment by jef-n** [comment]
what about the other ``pending``s introduced in 43278d7

**Comment by m-kuhn** [comment]
@jef-n never noticed them before. I added them as well now.

`featureCount()` was already used as name for a method that would return the provider feature count. I guess it's fine to replace that one with a method that corrects the provider number with the deleted and added features in the current edit session.

**Comment by elpaso** [comment]
@m-kuhn when merged, please make sure that the documentation in python cookbook examples is also updated.

**Pull request closed without merging**
