### PR TITLE
[processing] fix long-standing encoding issues in Processing

### PR DESCRIPTION
**Pull request by alexbruy**
- create GRASS and SAGA cripts using command-line encoding
 - export layers with non-ASCII names into intermediate files to avoid
encoding issues
 - construct commands as unicode strings

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by alexbruy** [comment]
Travis failed on Python3. This is expected and can be ignored, as this fix targeted to 2.18 with Python 2.

**Comment by luipir** [comment]
this solution differ from https://github.com/qgis/QGIS/pull/4906 for:
1) a more complete unicode modification (agree)
2) porting to formatting string in python3 style (agree)
3) just write batch scripts using the correct encoding

as far as I checked, the point 3 is not enough in window env. because the cmd.exe context execution need to setup cope page before execution of the batch file.

what is your experience @alexbruy ? btw, seems that both solution solve running scripts in at least wester europe code chars... can you tests with east-europe chars?

**Comment by alexbruy** [comment]
@luipir, I tested this code with different files and path and it works fine even if different encodings used in the same alg simultaneously.

**Comment by luipir** [comment]
@alexbruy tis does it means that https://github.com/qgis/QGIS/pull/4906 is not necessary? Ifo I can close it.

Whould be fine to have some experience from more charsets

**Pull request closed without merging**
