### PR TITLE
Execute ln command with GNU compatible options in install phase

### PR DESCRIPTION
**Pull request by dmarteau**
On some OSX macport installation, GNU commands may be used in favor
    of native commands and 'make install' fail with
         'ln: invalid option -- 'h'"

    As BSD ln support the GNU -n option as an equivalent of the -h option
    it should be preferred over the specific BSD option.

### CODE REVIEW

**Comment by rldhont** [comment]
Hi @telwertowski you probably can review this PR, isn't it ?

**Comment by telwertowski** [comment]
I don't use either brew or macports. For native macOS ln, -h and -n are the same (at least for 10.9 - 10.12) so I vote +1 for using GNU flags whenever both are available. @dakcarto should also check this just in case brew isn't using native ln.

**Review by dakcarto — APPROVED** [review]
Indeed, `man ln`:
```
-n    Same as -h, for compatibility with other ln implementations.
```

I see no issue in committing this change.

**Comment by dakcarto** [comment]
@telwertowski wrote:
> @dakcarto should also check this just in case brew isn't using native ln.

Thanks for the heads up. It is using the standard `ln`. 

Just checked with:
```
$ brew sh
Your shell has been configured to use Homebrew's build environment;
this should help you build stuff. Notably though, the system versions of
gem and pip will ignore our configuration and insist on using the
environment they were built under (mostly). Sadly, scons will also
ignore our configuration.
When done, type `exit'.

$ which ln
/bin/ln
```

**Pull request merged**
