### PR TITLE
[QgsAuthManager] Protect all methods that do SQL queries with mutex (fixes #16966)

### PR DESCRIPTION
**Pull request by rouault**
@rduivenvoorde You might have a try. This fixes crashes for me

### CODE REVIEW

**Review by elpaso — APPROVED** [review]
LGTM, btw I'm also working on auth manager refactoring that among other issues will address thread safety.

**Comment by elpaso** [comment]
See also https://github.com/qgis/QGIS/pull/5644 for thread safe authentication methods (that might be accessed by multiple threads at the same time)

**Comment by rouault** [comment]
> LGTM, btw I'm also working on auth manager refactoring that among other issues will address thread safety.

Should I commit that, or will that cause more pain than good to you ?

**Comment by elpaso** [comment]
Please go ahead, your help is more than welcome. The mutexes on the QgsAuthManager were on my TODO list but I'm currently working on another part of the auth system, I just wanted to let you know that I'll be working on auth system for the upcoming sprints and thread safety is on my list (please share your thoughs/suggestions if you have any others).

**Comment by dakcarto** [comment]
Thanks, @rouault!

**Pull request merged**
