### PR TITLE
added buffer tests

### PR DESCRIPTION
**Pull request by anitagraser**

### CODE REVIEW

**Comment by anitagraser** [comment]
Mhm, no convenient way to upload the expected result files ...

> Uploads are disabled.
> File uploads require push access to this repository.

**Comment by anitagraser** [comment]
Result files are at
https://dl.dropboxusercontent.com/u/42637169/buffer_polys.gml
https://dl.dropboxusercontent.com/u/42637169/buffer_polys_dissolve.gml

**Comment by alexbruy** [comment]
You can add these files to your commit and update PR

**Comment by anitagraser** [comment]
I'm aware of that. I was hoping all steps could be handled via the github web interface so I don't have to fight git ...

**Pull request closed without merging**
