### PR TITLE
Call QgsComposer::restoreComposerMapStates in QgsComposer::paintEvent, not in showEvent 

### PR DESCRIPTION
**Pull request by manisandro**
The previous strategy did not work reliably when using certain window managers, openbox for one.

Funded by Sourcepole QGIS Enterprise

### CODE REVIEW

**Comment by nyalldawson** [comment]
Thanks - I'll test and merge this after release.

**Comment by nyalldawson** [comment]
@manisandro sorry about the delay reviewing this, it slipped my mind. The fix works, but I'm worried it's a bit expensive to call for every changeEvent. Since we only need to call restoreComposerMapStates() once, a private bool could be added to flag whether or not this has already been called. What do you think?

**Comment by manisandro** [comment]
I don't expect the performance penalty to be measurable really, the actual `restoreComposerMapStates` is only called on a `WindowStateChange` event if the window was previously minimized. Hence most of the time the only added cost is an additional comparison in the case switch, and possibly one more comparison to detect whether the windows was previously minimized. And even then, the penalty of calling `restoreComposerMapStates` is pretty small (speaking in typical overheads of a GUI application).

**Comment by nyalldawson** [comment]
@manisandro fair enough. Do you think it's worth adding a "if mMapsToRestore.isEmpty() return;" to the start of restoreComposerMapStates?

**Comment by manisandro** [comment]
Shouldn't harm :)

**Comment by nyalldawson** [comment]
@manisandro Thanks! I've manually pushed a slightly modified version of this (added some comments and tweaked some of the ifdefs).

**Pull request closed without merging**
