### PR TITLE
3.16.4 queued backports

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by nyalldawson** [comment]
@troopa81 The backports of your oracle new table fixes have caused test failures here -- see eg https://travis-ci.org/github/qgis/QGIS/builds/754192332

Is there a pre-requisite backport missing from 3.16, or should I drop these backports?

**Comment by troopa81** [comment]
@nyalldawson I think it's because #40107 has not been backported. I'm currently recompiling things in 3.16, I'll come back to you as soon as I'm sure of what's need to be done.

**Comment by troopa81** [comment]
@nyalldawson I confirm, #40107 is missing. It works if you ckerry-pick  #40107 and  #40890 (in that order). I tried it on current release-3_16.

**Comment by nyalldawson** [comment]
Thanks @troopa81 ! I've done that now -- let's see what Travis says!

**Pull request merged**
