### PR TITLE
Fix missing last timestep in certain temporal controller scenario's

### PR DESCRIPTION
**Pull request by rduivenvoorde**
Working with small dataset of say 3 timeframes it appeared to me that it was not possible to reach the last timeframe, see #48942. Loading a netcdf with 3 time(instances) in it, QGIS failed to show the last one. 
First thought to fix this in mdal provider: https://github.com/qgis/QGIS/pull/49283 but then it appeared vector data (with instantaneous events) was also having the issue.

The solution I propose here is to actually always add the extra frame in the controller.
This has as drawback that when working with events having a duration >0 or with events having a begin and end time, there will be one frame too much (so an empty frame with no data on the end, testable with testdata below).
But I think that is better then loosing a frame with data... 

To test, unzip the zip (data + python code) and run the python in the python console.
It will load a csv (with 3 temporal scenario's) and one tiny netcdf (with 3 timesteps, see ncinfo and ncdump), all in same position and time:
[temporal_tests.zip](https://github.com/qgis/QGIS/files/11304584/temporal_tests.zip)

In current master you will be able to just run 2 frames, with this PR you will have 3

Screenshot from 2023-04-23 20-57-51

### CODE REVIEW

**Comment by elpaso** [comment]
Hi, see:
https://github.com/qgis/QGIS/actions/runs/4783049274/jobs/8506333147?pr=52857#step:8:186

you can use: static_cast<int>( mNavigationObject->totalFrameCount() )

**Comment by nyalldawson** [comment]
Please don't merge before I can review -- I'm not personally a fan of always having an empty frame at the end of animations. It'll really break the looping functionality ☹️

**Comment by rduivenvoorde** [comment]
> Hi, see: https://github.com/qgis/QGIS/actions/runs/4783049274/jobs/8506333147?pr=52857#step:8:186
> 
> you can use: static_cast( mNavigationObject->totalFrameCount() )



> Please don't merge before I can review -- I'm not personally a fan of always having an empty frame at the end of animations. It'll really break the looping functionality frowning_face

@nyalldawson I know, but current situation is also not working. But I'm very aware of all the different types of events that data can have. And it really depends on the kind of events you are looking at. When working with data like in the example zip, you will NOT have an empty frame. It all depends on the set of configurations/data of the layers.

For what I saw, the 'framecount' does not take (the per layer individually configured) including/excluding the endtime into account. And this worked for events with a certain duration, but with instantanous events (duration is zero) like the ones in my example, it fails to 'see' the last data point.

Only real good solution I can think of is to go over all layers (and the temporal providers) and check the real temporal extent (so taking the including/excluding limits into account).

Another 'solution' could be to always add a silent 1 millisecond to the last timeframe (when constructing the temporal filter). That would then include the last time point... but will also NOT be exactly correct (as in the texts we tell to NOT include the end time)...

Please let me know if you need info or example data or other input

**Comment by rduivenvoorde** [comment]
@nyalldawson I think I found a better solution. Will probably forget about this PR...?

Actual issue is that we sometimes have to take the end of all timeframes into account for total frame count (most notably when working with instant events, OR with events with a duration BUT have 'including end'... mmm not even sure about this one...), and sometimes we do NOT need to take this full end into account (when the events have a duration, do they will be catched anyway in the last timestep).

One way to solve this is to add a microsecond to the end when calculating the `QgsTemporalNavigationObject::totalFrameCount()` at
https://github.com/qgis/QGIS/blob/master/src/core/qgstemporalnavigationobject.cpp#L327
This will NOT show anywhere in gui, but it will make you will always have the last time-instance included (at least for the calculation of the frameCount), which is GOOD!
It works here, I will probably do another PR and add a test to check the difference between the framecounts of instant events and events with duration... Then your animation loop is still OK :-)

Another (more difficult) way to solve this would be to change code in
`QgsTemporalControllerWidget::updateTemporalExtent()`  (https://github.com/qgis/QGIS/blob/master/src/gui/qgstemporalcontrollerwidget.cpp#L292-L294)
to decide if we should take the end into account of not...

NOTE: I think the isTimeInstant-check is actually not right there, it is only checking the delta of start and end (of the QgsTemporalControllerWidget....) which (I think) is NEVER the case???

NOTE2: Is this check https://github.com/qgis/QGIS/blob/master/src/gui/qgstemporalcontrollerwidget.cpp#L425  in `QgsTemporalControllerWidget::onLayersAdded( const QList<QgsMapLayer *> &layers )`  not wrong? It makes that ONLY at the first layer(s) added this `mNavigationObject->setAvailableTemporalRanges` is updated/set ?

**Comment by rduivenvoorde** [comment]
Maybe a better idea: https://github.com/rduivenvoorde/QGIS/commit/2f35b1af4de57b866043cd48e818df9ed5500567

**Pull request closed without merging**
