### PR TITLE
Add Report a Bug to the Help menu to assist in creating bug reports

### PR DESCRIPTION
**Pull request by mach0**
Signed-off-by: Werner Macho werner.macho@gmail.com
report

### CODE REVIEW

**Comment by slarosa** [comment]
I am not sure if this is good for all users. To submit a bug it is necessary to have an osgeo id. Could we think something to submit directly an issue from QGIS UI? e.g. by using github API I don't know if it may be done with redmine API though.

I know this means switch the bug tracker from redmine  to github but I think it is time we should to consider such a migrating.


(Happy Hackfesting to all)

**Comment by mach0** [comment]
There will be some discussion today about redmine and issue/bugtracker anyway. And it would be easy to just change that URL inside the code after probably moving the bugtracker to somewhere else. But I am against "automated" bugreporting. There should be at least some small barrier (login somewhere should be enough) to only get really reasonable bugreportings.

**Comment by mach0** [comment]
And as additional information I was inspired by (beside Richard and Raymond) the projects:
[blender] (http://www.blender.org/)
[inkscape] (https://inkscape.org)
[JOSM (the openstreetmap editor)] (https://josm.openstreetmap.de/)
[Libreoffice - with Send feedback] (http://www.libreoffice.org)
[Qt Creator] (http://www.qt.io/)
All software I use regular - with some big projects amongst them ..

**Comment by slarosa** [comment]
@mach0 mine was just to open a little discussion about it
I thought many novice users may be intimidated to submit issue and the automation of the process directly from application could be a solution to this.

I don't have a concrete proposal, but I thought to something like a UI form and user fill the relevant parts. In this sense we can think to add two small text box in order to allow inserting user and password if necessary.

BTW, I am not against to merge this, and I would suggest to change the URL to [Bugs, Features and Issues](http://qgis.org/en/site/getinvolved/development/index.html#bugs-features-and-issues)

**Comment by m-kuhn** [comment]
How would you provide login information (for github or osgeo)? Would you add the possibility to create a new account from within the application?

**Comment by mach0** [comment]
First of all I just want to give an easy way to find the correct page to report issues/bugs .. 
To wherever the URL is pointing to in the end (could be easily adjusted when things change) I would find it useful to directly have it in the application ..

**Comment by m-kuhn** [comment]
We should probably look at this holistic and not just as a button.
Keeping the entry barrier low is fine, but we won't do ourselves a favor if we make it too easy.

People who open an issue should IMO:

 * receive basic information about reports (i.e. search for duplicates first, which information to provide, more? Should be kept short.) OR have a very clever reporting tool that asks the right questions and searches previous issues to suggest duplicates (more effort to implement).
 * have an account on the tracker in question (redmine/github...)

What is the target group who should use this button? People who already have an account and already have the information will no longer require this menu item, so it's targeted at first-time reporters?

**Comment by mach0** [comment]
I dont see it like that .. I often see myself searching for the correct URL to report a bug .. And therefor this button would help to always find it when I need it (if something is not working).
As some posts above I stated that a lot of open source tools have a button like that directly accessible in the menu - and I think it is there for the same purposes.
Though I have to say that with different target pages - some go directly to the issue/bug page - some point to a helping page first. 
The thing is - that wherever we point to in the end the menu entry is not there yet - And I think it does not harm in any way - but rather help to find the bugreporting quicker..
We can always change the URL we point to later.

**Comment by m-kuhn** [comment]
Experience shows that things tend not to change a lot once merged ;)

What do you think about pointing here:
https://qgis.org/en/site/getinvolved/development/index.html#bugs-features-and-issues

**Comment by mach0** [comment]
:) It depends .. I've heard something about moving to github or gitlab anyway - so my point is that currently it does not matter where it points to (once merged I will take care about pointing to the new pages anyway) .. but probably it makes it easier at least for some to report a bug

**Comment by m-kuhn** [comment]
If we point to the page I proposed you will only have to update the docs and not this link. Plus the information about what needs to be considered when reporting issues is there (although it could be a bit shorter IMHO). Is there any reason you would NOT like to point to the proposed page?

**Comment by mach0** [comment]
no reason - feel free to change the URL .. or shall I do it?

**Comment by m-kuhn** [comment]
I can't edit your PR and I prefer to get your ok since it was your idea.
What do you think about using the term "issue" or "bugs and features" instead of "bugs"?

**Comment by mach0** [comment]
You mean changing the menu entry "Report a Bug" to "Report an Issue/Feature" ..
Gnah - that sounds a bit odd to me .. but I would be ok with "Report an Issue" 
Considering that all the other opensource tools I mentioned above all have "Report a Bug" ;)

**Comment by m-kuhn** [comment]
"Report an issue" sounds good to me.

**Comment by mach0** [comment]
done ;)

**Comment by m-kuhn** [comment]
Did you intend to change the link as well?

**Comment by mach0** [comment]
*lol* hups .. :)

**Comment by m-kuhn** [comment]
You can add a `tr()` around it

**Comment by mach0** [comment]
and now there is the point where I'd like to squash commits - which cannot be done online .. :( Or at least I cannot find it ..

**Comment by m-kuhn** [comment]
Probably not possible online, but I can do before merge

**Comment by mach0** [comment]
ok

**Comment by m-kuhn** [comment]
Merged in 79616fd8d8285b4eb93adafdfcb97a3e429b832e

**Pull request closed without merging**
