### PR TITLE
[Processing] Small modeler fixes

### PR DESCRIPTION
**Pull request by radosuav**
The second commit should fix http://hub.qgis.org/issues/13034

### CODE REVIEW

**Comment by gioman** [comment]
assigned @volaya @alexbruy

**Comment by slarosa** [comment]
@radosuav  testing your branch...

commit 9db23a6:
I see something wrong when drawing the collapse/expand icon for the output box. The icon is drawn over the box of the algorithm. The most of my models are saved with collapsed output  description so the statement ```if not self.element.outputsFolded:``` is always False and returns a ```QPointF(0, 0)```.

How can I reproduce the issue? I read the bug tracker but I cannot reproduce the exception.

commit 539ba21:
This looks good and works for me.

**Comment by radosuav** [comment]
Thanks @slarosa for testing the commits. Indeed 9db23a6 was not the best fix :)

The issue occurs when you set an algorithm with no outputs (e.g. "Read image information" from OTB) as a parent of another algorithm. In the modeller you can see that no line is drawn between the parent and child algorithms and if you have Python console open you can also see the exception. Commit 9db23a6 fixed this issue because outputsFolded is set to true even if there are no outputs but that was not a good way to do this and introduced the problem that you mention.

The new commit should fix it properly.

**Comment by slarosa** [comment]
thanks for the fix @radosuav, manually merged in master branch.

**Pull request closed without merging**
