### PR TITLE
Set default resampling for SAGA io_gdal to Nearest Neighbor

### LINKED ISSUE #35687: add grid values to points gives wrong results
**Describe the bug**

I used from the processing toolbox the 'add grid values to points' function with as resampling option 'nearest neighbor', and with as input a point layer and a raster layer with integer values. The resulting column with raster values shows decimal numbers, not the exact integer raster value. When I run the function in SAGA directly, the column contains the exact raster values.

**QGIS and OS versions**

3.12.1 on Windows (installed with Osgeo4W

**Additional context**

Log of function

----
C:\OSGEO4~1\bin>call saga_cmd shapes_grid "Add Grid Values to Points"
-SHAPES "C:/Users/brp/AppData/Local/Temp/processing_wjqTfe/6601327d6d9a43199caeead18a394363/SHAPES.shp"
-GRIDS "C:/Users/brp/AppData/Local/Temp/processing_wjqTfe/6207aad29fad45aa94554d79463c8593/bio12.sgrd"
-RESAMPLING 0 -RESULT
"C:/Users/brp/AppData/Local/Temp/processing_wjqTfe/306d704010524140aed1ef0e445fc93a/RESULT.shp"
____________________________

SAGA Version: 2.3.2 (64 bit)
____________________________
library path: C:\OSGEO4~1\apps\saga-ltr\modules\
library name: shapes_grid
library : Grid Tools
tool : Add Grid Values to Points
author : O.Conrad (c) 2003
processors : 8 [8]
________________________

Load shapes: C:/Users/brp/AppData/Local/Temp/processing_wjqTfe/6601327d6d9a43199caeead18a394363/SHAPES.shp...

Load grid: C:/Users/brp/AppData/Local/Temp/processing_wjqTfe/6207aad29fad45aa94554d79463c8593/bio12.sgrd...

Parameters
Points: SHAPES
Grids: 1 object (bio12)
Result: Result
Resampling: Nearest Neighbour

### PR DESCRIPTION
**Pull request by gioman**
As discussed here https://github.com/qgis/QGIS/issues/35687 we the default resampling for SAGA io_gdal operations to Nearest Neighbor.

Fixes https://github.com/qgis/QGIS/issues/35687

### CODE REVIEW

**Comment by nyalldawson** [comment]
Ouch -- you've got quite a few test results to update here before we can merge!

**Comment by gioman** [comment]
> Ouch -- you've got quite a few test results to update here before we can merge!

@nyalldawson yes sure.

**Comment by gioman** [comment]
> Ouch -- you've got quite a few test results to update here before we can merge!

@nyalldawson done.

Not sure if the "RGB composite" had to be tested (not sure if it uses io_gdal) but anyway it was not possible because of https://github.com/qgis/QGIS/issues/35770 (because of this bug the test shouldn't have failed?).

**Comment by gioman** [comment]
I'm really not sure why some tests are failing

https://travis-ci.org/github/qgis/QGIS/jobs/674898401#L6373

any hint would be appreciated.

**Comment by alexbruy** [comment]
@gioman looks like field names are generated differently `demtif`instead of `dem`. Also there are some precision errors (rounding?).

But I only looked at the Travis logs and did not run tools by myself locally.

**Comment by gioman** [comment]
> looks like field names are generated differently `demtif`instead of `dem`

@alexbruy I saw that, it is my fault? Maybe I didn't run the tool (and then generated the test) as expected?

> Also there are some precision errors (rounding?).

see also this, I'm really not sure what could be the cause.

**Comment by roya0045** [comment]
What is stranger to me is the segfault in the tests. The test results can be changed but the segfault will be an issue for users.

**Comment by gioman** [comment]
> What is stranger to me is the segfault in the tests. The test results can be changed but the segfault will be an issue for users.

ummm... anyway I'm a bit lost about what I should do to fix the tests.

**Comment by alexbruy** [comment]
@gioman can you try to run any of the failing tools and check if new output is the same as the old one? I mean field names, values etc.

**Comment by gioman** [comment]
Not stale.

**Comment by nyalldawson** [comment]
@gioman this looks stale to me -- can we close until you have time to address the failures?

**Comment by gioman** [comment]
> @gioman this looks stale to me -- can we close until you have time to address the failures?

@nyalldawson not stale, kids at home, lockdown, saturday/sunday.

**Pull request closed without merging**
