### PR TITLE
Remove updateRecentProjectsVisibility()

### LINKED ISSUE #33718: Missing Recent Projects on Start up v3.10
Since QGIS 3.10 the recent projects tab on the start up screen has disappeared for me. 

image

I have experienced this on all versions of 3.10 I have tried. including the latest nightly builds. 

The start screen now has a Project Templates tab instead. Is this intentional or do I have to check a box somewhere to get recent projects to return?

Version 3.8 still has the recent project tab on my machine. 

Running QGIS 3.10 on Windows 10

### PR DESCRIPTION
**Pull request by tomtor**
## Description

because the current implementation has GUI issues (see referenced issue discussion).

Fixes: https://github.com/qgis/QGIS/issues/33718

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'm reluctant to just remove something which works under some circumstances. Was it impossible to fix the open issue alone?

**Comment by tomtor** [comment]
> I'm reluctant to just remove something which works under some circumstances.

When or why would we try to hide the "Recent Projects" list?
1) On the first start of QGIS by a new user which has no recent projects, to give the "News" section some more space.
2) ???

The list will normally never be empty again, and trying to hide the list in the very rare event that the user removes the last entry with a right mouse click, makes no functional sense. It's confusing for the user and leaves the GUI in a damaged state. That could be fixed by adding more code, but IMO that makes no sense and that part of the code should be removed anyway.

That leaves 1). If we really want to hide the "Recent Projects" on the rare "first start of QGIS" event, then "First Start" should be the conceptual trigger, not an empty "Recent Project" collection.

I think hiding such an important GUI element as the "Recent Project" list on the first start is conceptually wrong and we should just make it smaller if it is too big (https://github.com/qgis/QGIS/pull/40682/commits/fb339addfdc495e77b838aecf475a676b5186a97}

> Was it impossible to fix the open issue alone?

Maybe, but IMO hiding the "Recent Project" list is conceptually flawed.

**Comment by tomtor** [comment]
@nyalldawson Can we resume this discussion?

**Comment by nyalldawson** [comment]
Ok, let's go with the removal of the visibility toggle. But regarding the second commit - 25% is too small for the default size of this column. Here's what it looks like on my laptop:

image

Could we go with 40/60% instead?

**Comment by kad-vijlbc** [comment]
> Could we go with 40/60% instead?

@nyalldawson Sure, I changed the ratio to 40/60 for the second commit.

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
