### PR TITLE
Fix QtWebKit automagic

### PR DESCRIPTION
**Pull request by a17r**
qgis currently still links against QtWebkit if installed, even if `WITH_QTWEBKIT=OFF`.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Nice, does that resolve the debian issues with crashes when plugins use webkit when QGIS has been built without it?

**Comment by a17r** [comment]
I don't know about those crashes, but when they are caused by underlinking surely someone would have noticed by now. ;)

**Comment by m-kuhn** [comment]
Is there something solved with this patch or is it just "enforcing good practice" (which is also nice, just asking out of curiosity).

**Comment by m-kuhn** [comment]
Merged in af73eea363072818dd4d30d5c2a643897c5daf7c and f9a064310a633a3746069998e0b396b420c3f1cb

Thank you

**Pull request closed without merging**
