### PR TITLE
Remove suspicious signal handler installed by commit 4f18701d

### PR DESCRIPTION
**Pull request by strk**
This commit apparently allows setting a maxScale > 100000 in layer
visibility which is otherwise limited to a max value of 100000.

I don't know yet why this happens.
See https://issues.qgis.org/issues/15463

### CODE REVIEW

**Comment by strk** [comment]
Commit 4f18701d introduced the regression fixed by this PR, so a review from @pvalsecc (and @m-kuhn who merged the corresponding PR with bd3fd748f1e170c8aeb20fbc4f40966f70d33c5b) would be welcome

**Comment by strk** [comment]
as this change basically also removes the fixup of min scale > max scale, it needs to be worked on more.
btw, Travis passing shows the feature in #2863 did not come with proper tests (or they would fail now)

**Comment by strk** [comment]
Ok I've found a way to retain the min/max check while also fixing the initial limitation.
The initial limitation is due to this block of code in the QgsScaleRangeWidget constructor:
```
  // add start, add comprehension of scales by settings fake ordered values     
  mMinimumScaleWidget->setScale( 1.0 / 100000 );                                
  mMaximumScaleWidget->setScale( 1.0 / 1000 );     
```

I dunno why those fake values would be needed, but in any case if the scaleChanged handler setting MinScale on the MaximumScaleWidget is in effect, then the denominator bigger than 100000 gets trimmed down. Moving the connection *after* those setScale calls fixes both worlds.

**Comment by strk** [comment]
Closing as I found a better way to fix the original bug.

**Comment by jef-n** [comment]
Superceeded by #4613

**Pull request closed without merging**
