### PR TITLE
[needs-docs][feature] New button for empty the composer table

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description
Add a button to empty a composer table. Useful when you have a table with a lot of columns and you want only a few.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [X] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [X] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [X] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [X] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by DelazJ** [comment]
I'd suggest `Clear` for the button name. But how about instead enable multiselection of the rows and hence allow multiple deletions at once?

**Comment by lbartoletti** [comment]
I have no opinion on the subject. Just too lazy to click on - remove button for each row :)

**Comment by lbartoletti** [comment]
@DelazJ done for both suggestions.

**Comment by nyalldawson** [comment]
Looks good to me - can you fix the indentation please?

**Comment by DelazJ** [comment]
Thank you @lbartoletti.
Btw the tag for docs is [needs-docs] (2 ˋsˋ) though i wonder if [feature] better suits in this case

**Comment by lbartoletti** [comment]
@DelazJ is it OK for you?
Thanks.

**Comment by DelazJ** [comment]
@lbartoletti thanks for the change. 
And sorry to overload the fix… do/should the up and down moves also handle the multi selection?

**Comment by lbartoletti** [comment]
@DelazJ Normally, it's ok with 938c8d4

**Comment by DelazJ** [comment]
Merci

**Pull request merged**
