### PR TITLE
Project refactoring - part I

### PR DESCRIPTION
**Pull request by wonder-sk**
Large amount of changes here, but nothing super exciting here yet. Interesting bits:
- QgsMapLayerRegistry merged into QgsProject
- QgsMapSettings, QgsComposerMap switched from layer IDs to weak pointers with QPointer
- started to remove QgsProject::instance()->addMapLayers(...) where not necessary in tests
- QgsMapThemeCollection simplified the theme storage and API and switched to weak pointers

### CODE REVIEW

**Comment by nyalldawson** [comment]
Looks great! Love it

**Comment by wonder-sk** [comment]
Thanks for the review! I will add the unit tests and merge...

**Comment by nyalldawson** [comment]
Really exciting stuff... Qgis 3 is going to be fantastic!

**Comment by m-kuhn** [comment]
Nice job, @wonder-sk !
Thanks for tackling this :tada:

**Comment by mhugo** [comment]
Great ! Thanks !

**Pull request merged**
