### PR TITLE
[DbManager] New button to define a sql-filter when adding a query-based layer

### PR DESCRIPTION
**Pull request by SebDieBln**
This PR allows the user to define a sql-filter for a query-based layer while editing the query. Thus, it offers the same functionality as the _Add Postgis Layer_ dialog, where the user can also define a filter prior to adding a layer.

### CODE REVIEW

**Comment by SebDieBln** [comment]
I just rebased this PR against master.

**Comment by brushtyler** [comment]
Merged, thanks! 
Just for info, you forgot to delete the layer passed to querybuilder, fixed in c4dcb7b81.

**Comment by brushtyler** [comment]
From: https://github.com/qgis/QGIS/commit/c4dcb7b812422a85e81a842be5fcd9595364ebd9#commitcomment-14671379

SebDieBln --
>The idea was to use the already defined filter first, if it works. I often have the situation where an unfiltered query gives an invalid layer because of duplicate keys, different geometry types or something else.

brushtyler --
I do not understand how to set the filter the first time if your layer is invalid.

SebDieBln --
The usual trick is to make it valid by adding a LIMIT 0, then defining the filter and removing the LIMIT 0 again. At the moment I have to do this in the project/layer-definition XML file.
(Since PR #2458 any empty query can be made a valid layer, too.)

**Comment by brushtyler** [comment]
> The usual trick is to make it valid by adding a LIMIT 0, then defining the filter and removing the LIMIT 0 again.
That's not clear, we should display a message if anyone clicks on the `Set Filter` btn while the layer is invalid, maybe suggesting to add LIMIT 0 to make the query valid before retrying.

> At the moment I have to do this in the project/layer-definition XML file. (Since PR #2458 any empty query can be made a valid layer, too.)
Does it work with any DB vector layer too or PG layers only?

>The idea was to use the already defined filter first, if it works.
Wouldn't be better to use the filtered layer as second attempt?

**Comment by SebDieBln** [comment]
> That's not clear, we should display a message if anyone clicks on the Set Filter btn while the layer is invalid, maybe suggesting to add LIMIT 0 to make the query valid before retrying.

I agree. Maybe the suggestion should not include LIMIT 0, as this is not valid syntax for Oracle. And a message when the user tries to add an invalid layer to the canvas would be good, too.

> Does it work with any DB vector layer too or PG layers only?

I don't know. I only use PostgreSQL.

> Wouldn't be better to use the filtered layer as second attempt?

Interesting. I did not think of that. For the user it should make no difference. Maybe some performance issue if the query results in many features but the filter would reduce them to only a few?

**Pull request merged**
