### PR TITLE
[postgres] respect empty FilterFids list

### PR DESCRIPTION
**Pull request by m-kuhn**
Considering this statement:

    layer.getFeatures(QgsFeatureRequest().setFilterFids([]))

this resulted in an iteration over the whole postgres source.
Internally, this happened implicitly when iterating over a layer with
an active edit buffer but no edited features. In such a scenario, we are
now **much!!** faster.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Is there an existing feature source test covering this situation?

**Comment by nyalldawson** [comment]
Nice catch by the way!

**Comment by nyalldawson** [comment]
Ok, there is an exciting test in place.

**Comment by m-kuhn** [comment]
Actually I'm not even sure about the claim that the provider iterator will actually *return* all these features, it will at least just request them.

E.g. for spatialite (#5439) there is no difference in the functionality, only in the performance. So for a test it might be required to mock a database driver, something I don't currently feel like a lot ;)

**Comment by nyalldawson** [comment]
Sorry, you misunderstood me - I meant just to confirm that empty fids request results in no features returned for all providers (as opposed to returning all features). (And there's one already doing that anyway). I'm not expecting you to test the actual provider internals :)

**Comment by m-kuhn** [comment]
While this test wouldn't hurt, I guess it would fail to identify the current situation, because `QgsAbstractFeatureIterator::nextFeature` is an additional guard for this.

**Comment by nyalldawson** [comment]
In summary: ignore me, carry on doing your good work :)

**Comment by m-kuhn** [comment]
Trying to make a QComboBox and a QCompleter do stuff they were not designed for. Working against the framework is always fun :tada:

**Comment by m-kuhn** [comment]
Speeds up rendering of a transaction enabled postgres project here by a factor of almost 2!

**Comment by nyalldawson** [comment]
MERGE!

**Pull request merged**
