### PR TITLE
[opencl] Support for platforms > 1.1

### PR DESCRIPTION
**Pull request by elpaso**
Be nice to @rduivenvoorde and support OpenCL > 1.1 :)

Seriously: this should be tested on multiple O.S. and hardware devices (both CPUs and GPUs)

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
Building ...

**Comment by rduivenvoorde** [comment]
Yesss:

opencl

I did get some compile warnings:

```
[673/4233] Building CXX object src/core/CMakeFiles/qgis_core.dir/raster/qgshillshaderenderer.cpp.o
In file included from /usr/include/CL/cl.h:36,
                 from /usr/include/CL/opencl.h:47,
                 from /usr/include/CL/cl2.hpp:506,
                 from ../src/core/qgsopenclutils.h:25,
                 from ../src/core/raster/qgshillshaderenderer.cpp:33:
/usr/include/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
[737/4233] Building CXX object src/core/CMakeFiles/qgis_core.dir/qgsopenclutils.cpp.o
In file included from /usr/include/CL/cl.h:36,
                 from /usr/include/CL/opencl.h:47,
                 from /usr/include/CL/cl2.hpp:506,
                 from ../src/core/qgsopenclutils.h:25,
                 from ../src/core/qgsopenclutils.cpp:16:
/usr/include/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
[1083/4233] Building CXX object src/core/CMakeFiles/qgis_core.dir/moc_qgsopenclutils.cpp.o
In file included from /usr/include/CL/cl.h:36,
                 from /usr/include/CL/opencl.h:47,
                 from /usr/include/CL/cl2.hpp:506,
                 from src/core/../../../src/core/qgsopenclutils.h:25,
                 from src/core/moc_qgsopenclutils.cpp:9:
/usr/include/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")

[1333/4233] Building CXX object src/analysis/CMakeFiles/qgis_analysis.dir/raster/qgsninecellfilter.cpp.o
In file included from /usr/include/CL/cl.h:36,
                 from /usr/include/CL/opencl.h:47,
                 from /usr/include/CL/cl2.hpp:506,
                 from ../src/core/qgsopenclutils.h:25,
                 from ../src/analysis/raster/qgsninecellfilter.cpp:27:
/usr/include/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
```

Now I need to think about a proper test/data to prove that OpenCL is indeed much faster :-)

Thanks Ale!

**Comment by elpaso** [comment]
@rduivenvoorde  try with a DEM and:
- hillshare rendererr
- any 9cell algorithm: slope, aspect etc.

**Comment by rduivenvoorde** [comment]
Ok, downloaded this dem: http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_int/i69bn1.tif.zip (he, we do not have that much height here in NL, this is the 'hilly' part of NL :-) )

Unzipped and loaded the tiff/dem, and then ran Hillshade alg on it:
- without opencl: 20 seconds (and some heat as fan's are starting up)
- WITH opencl: 6.5 seconds   

Nice!

**Comment by elpaso** [comment]
> Ok, downloaded this dem: http://geodata.nationaalgeoregister.nl/ahn2/extract/ahn2_05m_int/i69bn1.tif.zip (he, we do not have that much height here in NL, this is the 'hilly' part of NL :-) )
> 
> Unzipped and loaded the tiff/dem, and then ran Hillshade alg on it:
> 
>     * without opencl: 20 seconds (and some heat as fan's are starting up)
> 
>     * WITH opencl: 6.5 seconds
> 
> 
> Nice!

I've just uploaded some small changes, I'd appreciate if you could re-test and see if it still works.

**Comment by rduivenvoorde** [comment]
Fetched that commit and rebuilded (so not a full fresh build, can do if you want...).
Hillshade and Slope still working from me. I get the following warnings now:

```
[10/86] Building CXX object src/core/C...qgis_core.dir/moc_qgsopenclutils.cpp.o
In file included from src/core/../../../src/core/qgsopenclutils.h:26,
                 from src/core/moc_qgsopenclutils.cpp:9:
/usr/include/CL/cl2.hpp:446:124: note: #pragma message: cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200
 # pragma message("cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200")
                                                                                                                            ^
[11/86] Building CXX object src/core/C...les/qgis_core.dir/qgsopenclutils.cpp.o
In file included from ../src/core/qgsopenclutils.h:26,
                 from ../src/core/qgsopenclutils.cpp:16:
/usr/include/CL/cl2.hpp:446:124: note: #pragma message: cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200
 # pragma message("cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200")
                                                                                                                            ^
[12/86] Building CXX object src/core/C....dir/raster/qgshillshaderenderer.cpp.o
In file included from ../src/core/qgsopenclutils.h:26,
                 from ../src/core/raster/qgshillshaderenderer.cpp:33:
/usr/include/CL/cl2.hpp:446:124: note: #pragma message: cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200
 # pragma message("cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200")
                                                                                                                            ^
[24/86] Building CXX object src/analysis/CMakeFiles/qgis_analysis.dir/raster/qgsninecellfilter.cpp.o
In file included from ../src/core/qgsopenclutils.h:26,
                 from ../src/analysis/raster/qgsninecellfilter.cpp:27:
/usr/include/CL/cl2.hpp:446:124: note: #pragma message: cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200
 # pragma message("cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200")
                                                                                                                            ^
[79/86] Building CXX object src/app/CMakeFiles/qgis_app.dir/qgsoptions.cpp.o
In file included from ../src/core/qgsopenclutils.h:26,
                 from ../src/app/qgsoptions.cpp:56:
/usr/include/CL/cl2.hpp:446:124: note: #pragma message: cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200
 # pragma message("cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200")
                                                                                                                            ^
[80/86] Building CXX object src/app/CMakeFiles/qgis_app.dir/qgisapp.cpp.o
In file included from ../src/core/qgsopenclutils.h:26,
                 from ../src/app/qgisapp.cpp:107:
/usr/include/CL/cl2.hpp:446:124: note: #pragma message: cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200
 # pragma message("cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200")
                                                                                                                            ^
[84/86] Building CXX object src/app/CMakeFiles/qgis.dir/main.cpp.o
In file included from ../src/core/qgsopenclutils.h:26,
                 from ../src/app/main.cpp:107:
/usr/include/CL/cl2.hpp:446:124: note: #pragma message: cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200
 # pragma message("cl2.hpp: CL_HPP_TARGET_OPENCL_VERSION is not a valid value (100, 110, 120 or 200). It will be set to 200")
```

**Comment by elpaso** [comment]
I'll fix that, thanks for checking, the problem is that those defines are not really well documented ...

**Comment by elpaso** [comment]
mmm it might be that on debian the headers are a bit old: https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl_version.h#L43

**Pull request merged**
