### PR TITLE
[processing] Try directly interpreting string as CRS first

### LINKED ISSUE #57494: qgis_process with algorithms using a CRS: error and a faulty message
### What is the bug or the crash?

An error is reported while requesting help or while running an algorithm with a `crs` type argument.

- For `qgis_process help`, the ERRORs only occur when the argument has a default value.
- In `qgis_process run`:
  - the ERRORs come up
  - however the process does execute successfully
  - there's also a faulty message `Using non-preferred coordinate operation between  and EPSG:4326` (see example below). Note the irrelevant `EPSG:4326` (it's probably taking that from the default value), since in the example the source and target CRS just use the `OSGB_1936` datum.

### Steps to reproduce the issue

```bash
$ qgis_process help native:reprojectlayer 1> /dev/null 
ERROR: Status 2: File EPSG:4326 could not be found
ERROR: Status 2: File EPSG:4326 could not be found
$ 
$ qgis_process help native:creategrid 1> /dev/null
ERROR: Status 2: File ProjectCrs could not be found
ERROR: Status 2: File ProjectCrs could not be found
$
$ # no default value here:
$ qgis_process help grass:v.proj 1> /dev/null
```

```bash
$ wget -q https://github.com/r-spatial/sf/raw/main/inst/gpkg/b_pump.gpkg
$ 
$ gdalsrsinfo b_pump.gpkg -o wkt2_2019 | head -3

PROJCRS["Transverse_Mercator",
    BASEGEOGCRS["GCS_OSGB 1936",
$ 
$ qgis_process run native:reprojectlayer --INPUT=b_pump.gpkg --TARGET_CRS='EPSG:4277' --OUTPUT=out.gpkg                

----------------
Inputs
----------------

INPUT:	b_pump.gpkg
OUTPUT:	out.gpkg
TARGET_CRS:	EPSG:4277


Using non-preferred coordinate operation between  and EPSG:4326. Using +proj=pipeline +step +inv +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.999601 +x_0=400000 +y_0=-100000 +ellps=airy +step +proj=push +v_3 +step +proj=cart +ellps=airy +step +proj=helmert +x=446.448 +y=-125.157 +z=542.06 +rx=0.15 +ry=0.247 +rz=0.842 +s=-20.489 +convention=position_vector +step +inv +proj=cart +ellps=WGS84 +step +proj=pop +v_3 +step +proj=unitconvert +xy_in=rad +xy_out=deg, preferred +proj=pipeline +step +inv +proj=tmerc +lat_0=49 +lon_0=-2 +k=0.999601 +x_0=400000 +y_0=-100000 +ellps=airy +step +proj=hgridshift +grids=uk_os_OSTN15_NTv2_OSGBtoETRS.tif +step +proj=unitconvert +xy_in=rad +xy_out=deg.
ERROR: Status 2: File EPSG:4277 could not be found
ERROR: Status 2: File EPSG:4277 could not be found

----------------
Results
----------------

OUTPUT:	out.gpkg
$ 
$ ls out.gpkg
out.gpkg
$ 
$ gdalsrsinfo out.gpkg -o wkt2_2019 | head -3

GEOGCRS["OSGB36",
    DATUM["Ordnance Survey of Great Britain 1936",
```

### Versions

```
$ qgis_process --version
QGIS 3.36.3-Maidenhead 'Maidenhead' (2df9655469b)
QGIS code revision 2df9655469b
Qt version 5.15.3
Python version 3.10.12
GDAL/OGR version 3.8.4
PROJ version 9.3.1
EPSG Registry database version v10.098 (2023-11-24)
GEOS version 3.12.1-CAPI-1.18.1
SQLite version 3.37.2
OS Linux Mint 21.3
```

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nyalldawson**
...before falling back to alternatives like treating it as a map layer

Fixes #57494

### CODE REVIEW

**Review by troopa81 — COMMENTED** [review]
Do you mind adding tests?

**Comment by nyalldawson** [comment]
@troopa81 

> Do you mind adding tests?

I tried, but it's not possible (without unreasonable effort) -- there's already tests covering the functionality here, it's just the order of evaluation which has changed.

**Review by troopa81 — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
@nyalldawson it seems to me the issue still occurs for some algorithm even using QGIS 3.37.0-Master https://github.com/qgis/QGIS/commit/b2a8801d76 : `native:creategrid`, `native:createconstantrasterlayer`, `native:randompointsinextent`, `qgis:regularpoints`, `native:createrandomuniformrasterlayer`, ...

**Comment by nyalldawson** [comment]
@agiudiceandrea 

What command are you using to get them?

**Comment by agiudiceandrea** [comment]
@nyalldawson on an OSGeo4W Shell:

```
C:\OSGeo4W_V2_8>qgis_process-qgis-dev --version
QGIS 3.37.0-Master 'Master' (b2a8801d76)
QGIS code revision b2a8801d76
Qt version 5.15.13
Python version 3.12.3
Compiled against GDAL/OGR 3.10.0dev-39cad318b2
Running against GDAL/OGR 3.10.0dev-12dab86ca2
PROJ version 9.4.0
EPSG Registry database version v11.004 (2024-02-24)
GEOS version 3.12.1-CAPI-1.18.1
SQLite version 3.45.1
OS Windows 10 Version 1903
This copy of QGIS writes debugging output.

C:\OSGeo4W_V2_8>qgis_process-qgis-dev help native:creategrid 2>&1
Create grid (native:creategrid)

----------------
Description
----------------
This algorithm creates a vector layer with a grid covering a given extent. Elements in the grid can be points, lines or polygons. The size and/or placement of each element in the grid is defined using a horizontal and vertical spacing. The CRS of the output layer must be defined. The grid extent and the spacing values must be expressed in the coordinates and units of this CRS. The top-left point (minX, maxY) is used as the reference point. That means that, at that point, an element is guaranteed to be placed. Unless the width and height of the selected extent is a multiple of the selected spacing, that is not true for the other points that define that extent.

----------------
Arguments
----------------

TYPE: Grid type
        Default value:  0
        Argument type:  enum
        Available values:
                - 0: Point
                - 1: Line
                - 2: Rectangle (Polygon)
                - 3: Diamond (Polygon)
                - 4: Hexagon (Polygon)
        Acceptable values:
                - Number of selected option, e.g. '1'
                - Comma separated list of options, e.g. '1,3'
EXTENT: Grid extent
        Argument type:  extent
        Acceptable values:
                - A comma delimited string of x min, x max, y min, y max. E.g. '4,10,101,105'
                - Path to a layer. The extent of the layer is used.
HSPACING: Horizontal spacing
        Default value:  1
        Argument type:  distance
        Acceptable values:
                - A numeric value
                - field:FIELD_NAME to use a data defined value taken from the FIELD_NAME field
                - expression:SOME EXPRESSION to use a data defined value calculated using a custom QGIS expression
VSPACING: Vertical spacing
        Default value:  1
        Argument type:  distance
        Acceptable values:
                - A numeric value
                - field:FIELD_NAME to use a data defined value taken from the FIELD_NAME field
                - expression:SOME EXPRESSION to use a data defined value calculated using a custom QGIS expression
HOVERLAY: Horizontal overlay
        Default value:  0
        Argument type:  distance
        Acceptable values:
                - A numeric value
                - field:FIELD_NAME to use a data defined value taken from the FIELD_NAME field
                - expression:SOME EXPRESSION to use a data defined value calculated using a custom QGIS expression
VOVERLAY: Vertical overlay
        Default value:  0
        Argument type:  distance
        Acceptable values:
                - A numeric value
                - field:FIELD_NAME to use a data defined value taken from the FIELD_NAME field
                - expression:SOME EXPRESSION to use a data defined value calculated using a custom QGIS expression
CRS: Grid CRS
ERROR: Status 2: File ProjectCrs could not be found
ERROR: Status 2: File ProjectCrs could not be found
        Default value:  ProjectCrs
        Argument type:  crs
        Acceptable values:
                - CRS as an auth ID (e.g. 'EPSG:3111')
                - CRS as a PROJ4 string (e.g. 'PROJ4:à')
                - CRS as a WKT string (e.g. 'WKT:à')
                - Path to a layer. The CRS of the layer is used.
OUTPUT: Grid
        Argument type:  sink
        Acceptable values:
                - Path for new vector layer

----------------
Outputs
----------------

OUTPUT: <outputVector>
        Grid
```

The issue is due to the fact that such algorithms have the string "ProjectCrs" as default value for a CRS parameter, but such string is not a valid QgsCoordinateReferenceSystem.
See https://github.com/qgis/QGIS/blob/0c41c22343ded7c6b6a7be0d382477128e837bd9/src/core/processing/qgsprocessingutils.cpp#L674-L676

**Comment by nyalldawson** [comment]
@agiudiceandrea fixed in https://github.com/qgis/QGIS/pull/57576

**Pull request merged**
