### PR TITLE
Changing Colors icon in the Option dialog

### PR DESCRIPTION
**Pull request by stra2da**
My attempt was to change the Colors icon in the Option dialog to make it clearer these are the palette shown when chosing color for vector layers
options

### CODE REVIEW

**Comment by nirvn** [comment]
Nice  one. I'd add a bit of padding, the icon seems oversized alongside the others.

A few more icons would benefit from some love (the gdal one being the worse).

**Comment by stra2da** [comment]
I've used the mlColorSwatches.svg and changed a little bit to simplify it and to make it bigger (I used the  Symbology.svg as base dimension, but in in my case the height is a little bit taller, I agree it need a little bit of padding ). 
I think we can also use the mlColorSwatches.svg but it's smaller and it is placed in another folder, so, in this case I've two questions:
Should I changed it to make it bigger? and 
Have I to copy it in the ..\default\propertyicons folder or use it as it it is and only change the path in the .qrc and .ui files?

**Comment by nirvn** [comment]
I think you'll have to use a unique icon here. We can't enlarge mColorSwatches.svg, and we can't use that icon otherwise the outlines look way too large (been there, done that ;) ).

I'm +1 to merge when the new icon has padding added. Please don't forget to compress the finalized SVG too (simple online solution: https://jakearchibald.github.io/svgomg/ )

**Comment by stra2da** [comment]
Done, now the vertical padding is the same of themap_tools.svg (just above it) and the SVG is symplified. Just waiting for Travis :)

**Comment by nirvn** [comment]
@stra2da , thanks for your contribution.

**Pull request merged**
