### PR TITLE
make night mapping UI theme usable for color blind people

### LINKED ISSUE #49775: Using "night mode", all checkbox checks are invisible ?
### What is the bug or the crash?

Using "night mode", all checkbox checks are invisible. In QGIS settings, in plugins, anywhere they appear. No way to tell if they are checked or not, without changing the mode and restarting QGIS. 

Checkbox bug

### Steps to reproduce the issue

Choose Dark mode: 
Settings -> Options -> General -> Application -> UI Theme -> Night Mapping

Restart. Look at any dialog that includes a checkbox...

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
Mergin
2022.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Sorry, I don't get the details of which versions are supported. Do I need a newer one? It takes hours to download one here...

### PR DESCRIPTION
**Pull request by AlisterH**
change checkbox and radio button icons so that night mapping UI theme is usable for colour blind people (fixes #49775)

### CODE REVIEW

**Comment by DelazJ** [comment]
Looks like github is unable to preview your icons (even when browsing the folder, they do not display)

image

**Comment by AlisterH** [comment]
Github is incabable of previewing the originals too.

**Comment by nirvn** [comment]
I'll have a look at it this tomorrow.

**Comment by nirvn** [comment]
@AlisterH , I've looked at the SVGs, and I feel like the proposed change could be improved. The tweaked checked SVGs are a bit confusing, they are looking more like the reflection of a "focused/highlight" state rather than a checked state. 

We could simply add an inner square for checkboxes and circle for radioboxes as checked state?

**Comment by AlisterH** [comment]
Yeah, I would have done that but I couldn't figure out what to do with qcheckbox-intermediary that would make sense.  I'll use ticks and a dash like the other set of icons; just need to make sure the colours make sense in all the states.

**Comment by AlisterH** [comment]
I've made a new set of icons with clear checkmarks.

**Comment by AlisterH** [comment]
Bumping; are you able to look at it again @nirvn?

**Comment by nirvn** [comment]
@AlisterH , it's on my to do list, not forgotten :)

**Comment by AlisterH** [comment]
Just bumping so it doesn't get closed.

**Comment by nirvn** [comment]
@AlisterH , it's getting there :) can you please remove the 1 pixel white border from the checkbox and radio box widgets, it'd make things blend in much better.

Once the 1px border is out, we can merge. Thanks

**Comment by AlisterH** [comment]
Please reconsider - these colour combinations 
1. are logical (all "enabled" icons are white and green, all "disabled" icons are a less visually prominent dark and light grey)
2. look good, and 
3. the white borders help colour blind people to distinguish between "unchecked" and "unchecked-disabled" state.
image

If I remove the white borders then
- the main problem is that if I keep the light backgrounds for the "disabled" icons, then to colour blind people the "enabled" icons won't be more visually prominent than the "disabled" icons.
If I also keep the dark borders for the "disabled" icons then the inconsistency (border or no border) is arbitrary and looks weird.
image
- if I use green borders for the "disabled" icons, with a darker grey fill, then it kind of makes sense, but 
    - the "checked-disabled" icons have three colours, which is a bit weird, and 
    - the checkmarks aren't very legible because they don't contrast enough with the main fill, even if I make them black.
image
image
-   If I use green borders for the "disabled" icons, keeping the light grey fill to preserve contrast with the checkmarks, then the "unchecked-disabled" icons still have 3 colours and are at least as visually prominent as the "unchecked" icons i.e. we have arrived back at the first bullet point above.
image
image

**Comment by AlisterH** [comment]
Here are the icons in the second to last screenshot, which I think is the next best option: [2nd best option.zip](https://github.com/qgis/QGIS/files/11156264/2nd.best.option.zip)

**Comment by AlisterH** [comment]
any further comments?

**Comment by nirvn** [comment]
@AlisterH , let's go for the 2nd best options.zip files, we can adjust afterwards in separate PRs.

**Comment by AlisterH** [comment]
I really think that isn't good enough for colour blind people, so I've had another go.  I think this is a better compromise:
image

**Comment by nirvn** [comment]
@AlisterH , the only thing I find really bad for _non colour blind_ people here is that disabled controls have green color (which == active really).

Could we have light gray border there too, e.g.:
image

**Comment by AlisterH** [comment]
That's no good again - unless we bring the white borders back.  If we do then it is very good:
image

**Comment by nirvn** [comment]
@AlisterH , OK, I'm now wondering whether we just need to have two separate night mapping theme. Maybe Night mapping (color blind) or something.

**Comment by nirvn** [comment]
This is what it looks like ATM with your latest commit:
image

I feel like the radio/check boxes are popping up way too much (looks like they all have an ongoing "focus" on).

**Comment by AlisterH** [comment]
> @AlisterH , OK, I'm now wondering whether we just need to have two separate night mapping theme. Maybe Night mapping (color blind) or something.

I've opened a new pull request doing that.

**Pull request closed without merging**
