### PR TITLE
Update untwine to fix builds for macOS < 10.15

### PR DESCRIPTION
**Pull request by wonder-sk**
Update to the latest upstream changes in untwine to fix macos:
https://github.com/hobuinc/untwine/tree/qgis

Refs https://github.com/qgis/QGIS-Mac-Packager/issues/148
Refs https://github.com/qgis/QGIS/pull/48583

### CODE REVIEW

**Comment by 3nids** [comment]
thanks for the quick followup @wonder-sk

**Comment by hobu** [comment]
> You should just be able to call the function in PDAL on OSX if you want. 

PDAL 2.4.0 has the same issue. The QGIS team is still able to use 2.3.0 and hasn't moved forward. I just monkey patched Untwine to get them going. 

We are going to need some resources if making PDAL 2.x work all the way back to OSX 10.13 is a requirement. It was a big relief for us to be able to switch to C++17, and we aren't excited to back up on it.

**Comment by abellgithub** [comment]
But you don't need the fixed code for OSX. The fixed code is only relevant on Windows, so calling pdal::FileUtils::directoryList() on OSX should always be good.

**Comment by hobu** [comment]
> calling pdal::FileUtils::directoryList() on OSX should always be good.

PDAL 2.4.x uses `directory_iterator` from `<filesystem>`, which isn't available for the older OSX compilation target. PDAL 2.3 was using its own internal copy of boost to implement `FileUtils::directorylist`, so it didn't previously have the issue.

https://github.com/PDAL/PDAL/blob/master/pdal/util/FileUtils.cpp#L233

I pushed some copypasta to fix the Epf.cpp listing too on the `qgis` Untwine branch @wonder-sk

**Review by uclaros — APPROVED** [review]
Not sure how mac version support works in qgis, but it would probably be nice to have some way to remind us to remove the patchwork when we no longer support 10.13.

**Pull request merged**
