### PR TITLE
Add Help button and some fixes to automated placement widget

### PR DESCRIPTION
**Pull request by DelazJ**
Remove the checkbox label on two lines that does not ease translation (context?) and a bit ugly
current
image
proposed (from qt)
image

### CODE REVIEW

**Comment by DelazJ** [comment]
The Help button points to label properties chapter but there's no section for this dialog, yet. If someone could help to understand what these options mean (i could see impacts of some), how the priority is (regarding some of the placement/rendering tabs options) or point to an easy to understand doc, i'd be glad to write about in the User manual

**Comment by nyalldawson** [comment]
I can (somewhat) help:

- Draw text as outlines: controls whether text labels are drawn (and exported) as either proper text objects OR as paths only. If they are exported as text objects then they can be edited in external applications (e.g. Inkscape) as normal text. BUT -- the side effect is that the rendering quality is decreased, AND there's issues with rendering when certain text settings like buffers are in place. That's why drawing as outlines is recommended. Note that when exporting a layout to svg there's actual an override for this setting - so you can leave the project rendering as outlines but for a svg export export the labels as text.

- show partial labels: controls whether labels which fall partially outside of the map extent should be rendered. If checked, these labels will be shown (when there's no way to place them fully within the visible area). If unchecked then partial visible labels will be skipped.

- "show all labels..." - this one is pretty self explanatory

- "show candidates" - controls whether boxes should be drawn on the map showing all the candidates generated for label placement. Like the label says, it's useful only for debugging and testing the effect different labeling settings have.

- the number of candidates controls set how many label placement candidates should be generated for each feature type. The more candidates generated, the better the labeling will be - but at a cost of rendering speed. Smaller number of candidates results in less labels placed but faster redraws.

- "search method": I don't believe anyone in the world understands what these settings do.

**Comment by haubourg** [comment]
Can't explain better here. 
As for the label algorithms, the guys mentioned here might know about these :
image
and there is a dedicated website for PAL http://pal.heig-vd.ch/

**Comment by DelazJ** [comment]
Thanks @nyalldawson 
> "show all labels..." - this one is pretty self explanatory

If I'm not wrong, It's the same item as the (per layer) one in the rendering tab, right. There's no override nor conflict, right?

> the number of candidates controls set how many label placement candidates should be generated for each feature type. The more candidates generated, the better the labeling will be - but at a cost of rendering speed. Smaller number of candidates results in less labels placed but faster redraws.

It's a sub-item of the search method, isn't it?
> "search method": I don't believe anyone in the world understands what these settings do.

I love this one.
Thanks @haubourg for the precision. Following the provided and interesting link, I found [this page](http://pal.heig-vd.ch/index.php?page=existing-integrations) with a wiki link to what could be the first implementation in QGIS (not accessible - https://github.com/qgis/QGIS/wikiLabel_Placement_GSoC_2009).
If ever I found more time, will investigate further (though I wonder if it's worth explaining subtleties of these different methods).

**Pull request merged**
