### PR TITLE
Fix unreported crash when an empty scale is in the settings

### PR DESCRIPTION
**Pull request by elpaso**

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
Hi @elpaso, please see also https://github.com/qgis/QGIS/issues/52383#issuecomment-1494507595 and https://github.com/qgis/QGIS/issues/52383#issuecomment-1494879487.

**Comment by elpaso** [comment]
> Hi @elpaso, please see also [#52383 (comment)](https://github.com/qgis/QGIS/issues/52383#issuecomment-1494507595) and [#52383 (comment)](https://github.com/qgis/QGIS/issues/52383#issuecomment-1494879487).

Thanks, I actually saw #52383, the crash I'm fixing here does not fix that issue, but it might have the same cause. The way settings are stored now has changed from previous versions and there are some incompatibilities and bugs that need to be addressed.

**Review by 3nids — APPROVED** [review]

**Comment by 3nids** [comment]
sorry I thought it was merged already!

**Comment by agiudiceandrea** [comment]
@elpaso @3nids shouldn't this PR be backported to release-3_30 branch to avoid the crash in the next 3.30 version?

**Pull request merged**
