### PR TITLE
Spatialite provider transactions

### PR DESCRIPTION
**Pull request by elpaso**
Transactions implementation for the native spatialite provider

Funded by: **ARPA Piemonte**

### CODE REVIEW

**Review by nyalldawson — COMMENTED** [review]
Lgtm (with the usual caveat that the larger transactions API is not completely thread safe. This pr follows the convention of the other transaction supported providers)

Are you aware that spatialite itself is on "death notice"? https://lists.osgeo.org/pipermail/qgis-developer/2020-March/060770.html

**Comment by elpaso** [comment]
> Lgtm (with the usual caveat that the larger transactions API is not completely thread safe. This pr follows the convention of the other transaction supported providers)
> 
> Are you aware that spatialite itself is on "death notice"? https://lists.osgeo.org/pipermail/qgis-developer/2020-March/060770.html

I didn't know, but I cannot say I'm particularly surprised (or sorry). 
I guess we have to wait and see if anyone will continue to develop the library.

**Comment by SilvioGrosso** [comment]
Hello everyone,

Sorry to barge in...

Alessandro Furieri, the main developer of SpatiaLite, has been completely "silent" these past months on the SpatiaLite Google groups.

Here is the link to a post where he was asked about the future of SpatiaLite development (to which he has never replied...):
https://groups.google.com/forum/#!topic/spatialite-users/RZPDuFfPhzs

I suppose Alessandro has some "health-issue" or has decided to stop working on SpatiaLite...
In the long past, he was quite responsive on the Google group, which is no longer the case...

**Comment by rouault** [comment]
> has decided to stop working on SpatiaLite...

Not completely true: there was a commit by him just yesterday: https://www.gaia-gis.it/fossil/libspatialite/timeline . I had an email exchange with him a few weeks ago and he was super busy with other duties but hoped to be able to continue Spatialite development.

**Comment by nyalldawson** [comment]
I wonder if funding is his issue. I think we could/should put out a "call for support" via the QGIS news feed. I think given the widespread use of spatialite databases, and the likelihood that there's organisations out there which are entirely reliant on them, we should be able to find sponsors for a maintenance effort.  (If so, it might be a good opportunity to also fund the spatialite project moving to a modern git-based workflow which is more inviting to other contributors,...)

**Comment by nirvn** [comment]
@nyalldawson , +1 to all of that, it'd be a real shame to see spatialite die out.

**Pull request merged**
