### PR TITLE
[ogr] Fix very slow feature requests when filter string set

### PR DESCRIPTION
**Pull request by nyalldawson**
Follow up 217e7006 - the extra logic in fetchFeatureWithId is not required, because OGR_L_GetFeature works correctly with the feature IDs generated using the original fid column. This avoids the very slow iteration over all layer features to find matching features when a FilterFids request is made.

### CODE REVIEW

**Comment by nirvn** [comment]
Brilliant work nailing this regression.

**Comment by nyalldawson** [comment]
Don't break out the :balloon: yet - let's see if @rouault can verify that this fix is valid

**Comment by nirvn** [comment]
Oh, I purchased thousands of those already. I'll wait for your queue to cut the strings.

**Comment by rouault** [comment]
Hum, I'm not sure this is alway correct. That will depend on the OGR driver. For shapefiles (or any non-SQL based driver) that will work. For GPKG, as well. But if you take a SQLite/Spatialite database, that will fail. This could happen to other SQL based drivers (the GPKG one has some internal logic to be able to retrieve the origin row number, when possible)

For example
```
$ ogrinfo poly.db  -sql "select eas_id, ogc_fid as orig_fid from poly where eas_id = 170"
INFO: Open of `poly.db'
      using driver `SQLite' successful.

Layer name: SELECT
Geometry: None
Feature Count: 1
Layer SRS WKT:
(unknown)
eas_id: Integer64 (0.0)
orig_fid: Integer (0.0)
OGRFeature(SELECT):0
  eas_id (Integer64) = 170
  orig_fid (Integer) = 10
```

The OGR FID is going to be 0 (on the SQL result layer), but QGIS will use orig_fid = 10 to assign its feature id. If you request OGR_L_GetFeature(10) on that SQL layer you will get the 11th result of the SQL layer.

So a fix that would work would be to request the origin OGR layer (before applying a SQL filter), but you'd have to keep it and subset the fields to those requested.

Quicker alternative in term of coding: use the OGR_L_GetFeature() alternative first and check if the OGR_F_GetFID() == value of the last field when mOrigFidAdded. If not, go to the slow loop.

**Comment by nyalldawson** [comment]
Do you mean the check at https://github.com/qgis/QGIS/blob/master/src/providers/ogr/qgsogrprovider.cpp#L3839 ? That's the only way I can see  fields being dropped here.

**Comment by rouault** [comment]
> Do you mean the check at https://github.com/qgis/QGIS/blob/master/src/providers/ogr/qgsogrprovider.cpp#L3839 ? That's the only way I can see fields being dropped here.

Ah, sorry I was confused. The subsetString in the non-SELECT case is just a WHERE clause, so indeed if mOrigFidAdded is true, all fields of the original OGR layer are there + the final orig_fid column.

**Comment by nyalldawson** [comment]
@rouault 

How's c526fba6b0993fe69ed7acd4e1cefcc3ef416a26 look to you now?

**Comment by nyalldawson** [comment]
@rouault while your eyes are on the qgis codebase, can you identify any potential issues with this new approach?

**Comment by nyalldawson** [comment]
I found one issue here - if the actual layer contains a real field orig_ogc_fid, then things go all over the place. But that seems to be the case on master too. And unfortunately, there's lots of things which can result in this field being saved into data sets - e.g. filtering a layer in qgis, then saving the result to a file.

**Comment by nirvn** [comment]
@nyalldawson , all good here. Iterating through selected features on filtered layer is blazingly fast, attribute table displays properly and its show selected features only mode doesn't freeze, the identity tool works perfectly. Great job.

**Comment by nirvn** [comment]
🎈
🎈
🎈
✂️
Yay!

**Pull request merged**
