### PR TITLE
Appveyor test build

### PR DESCRIPTION
**Pull request by nyalldawson**
PR for testing an Appveyor build (not expected to pass due to build timeout)

### CODE REVIEW

**Comment by nyalldawson** [comment]
@SebDieBln ignore the Appveyor failure - it's a WIP

**Comment by SebDieBln** [comment]
:+1: for testing the build process on Windows (from a Windows user :wink:)

**Comment by nyalldawson** [comment]
Note - appveyor have been contacted to see if there's any changes they can make so that these builds complete in time.

**Comment by nyalldawson** [comment]
Appveyor have temporarily upgraded us to a Pro O/S account - let's see how this latest build goes...

**Comment by nyalldawson** [comment]
@jef-n Ok, so it's building and running the tests now. Some failures, but nothing serious. I'm not sure though whether it's building use 2 cores - is there something we'd need to change in the scripts to get this to work?

TODO:
- get everything to pass
- find someone to pay for this ;)
- enable sql server test
- check into all those warnings

**Comment by m-kuhn** [comment]
@nyalldawson any chance this will ever be resurrected?

**Comment by nyalldawson** [comment]
Don't think so - for a while I could get it to run under the time limit, but then we started exceeding it again and I can't find any shortcuts to help.

**Pull request closed without merging**
