### PR TITLE
Add more copy/paste symbol actions

### PR DESCRIPTION
**Pull request by nyalldawson**
Adds a few more copy and paste symbol actions in the GUI, allowing for easier transfer of symbols between parts of QGIS

### CODE REVIEW

**Review by nirvn — APPROVED** [review]
Nice work.

**Comment by DelazJ** [comment]
@nyalldawson does this relate to #29627?

**Comment by nyalldawson** [comment]
Yes, it fixes that

**Comment by RudiU** [comment]
That would be a nice and welcome feature, but as of 3.8.2 it isn't working yet as a fix to #29627

**Comment by nyalldawson** [comment]
@RudiU not all fixes are applied to stable branches. We only do it where it's deemed safe to do so.

**Pull request merged**
