### PR TITLE
First part of QEP 35: WFS provider enhancements

### PR DESCRIPTION
**Pull request by rouault**
This is the first part of the implementation of https://github.com/qgis/QGIS-Enhancement-Proposals/issues/53

Improvements:
- Version autodetection
- On-disk caching of downloaded features
- Background download and progressive rendering
- WFS 1.1 and 2.0 support
- WFS 2.0 GetFeature paging
- Add provider tests

Fixes:
- #10106: Panning a non-cached WFS layer causes selection to change
- #9444: WFS client not requesting new features when not-cached
- #14156: WFS non cached: infinite flashing
- #9450 : New WFS connection option - Max number of features returned
- #14122: Implement WFS 2.0 client provider (partial. no joins or stored queries)

### CODE REVIEW

**Comment by jef-n** [comment]
Nice work.

**Comment by m-kuhn** [comment]
Just noticed this crash in the WFS test, no idea if it's related or not:
https://travis-ci.org/qgis/QGIS/jobs/121411964#L1003

```
194/196 Test #193: PyQgsWFSProvider ........................***Failed   11.06 sec
export LD_LIBRARY_PATH=NOTFOUND:/Users/travis/build/qgis/QGIS/build/output/lib:
export PYTHONPATH=/Users/travis/build/qgis/QGIS/build/output/python/:/Users/travis/build/qgis/QGIS/build/output/python/plugins:/Users/travis/build/qgis/QGIS/tests/src/python:
-- Running /usr/local/bin/python2.7 /Users/travis/build/qgis/QGIS/tests/src/python/test_provider_wfs.py 
Running from build directory!
- source directory: /Users/travis/build/qgis/QGIS
- output directory of the build: /Users/travis/build/qgis/QGIS/build/output
!!! prefix path was requested, but it is not valid - we do not run from installed path !!!
Application state:
QGIS_PREFIX_PATH env var:		/Users/travis/build/qgis/QGIS/build/output
Prefix:		
Plugin Path:		/Users/travis/build/qgis/QGIS/build/output/../PlugIns/qgis
Package Data Path:	/Users/travis/build/qgis/QGIS
Active Theme Name:	
Active Theme Path:	/Users/travis/.qgis2///themes//icons/
Default Theme Path:	:/images/themes/default/
SVG Search Paths:	/Users/travis
		/Users/travis/build/qgis/QGIS/images/svg/
		/Users/travis/.qgis2//svg/
User DB Path:	/Users/travis/build/qgis/QGIS/resources/qgis.db
Auth DB Path:	/Users/travis/.qgis2//qgis-auth.db
Python(38140,0x7fff755ef310) malloc: *** error for object 0x7fc1fd0e61a0: double free
*** set a breakpoint in malloc_error_break to debug
CMake Error at PyQgsWFSProvider.cmake:22 (MESSAGE):
  Test failed: Child aborted

```

**Comment by rouault** [comment]
Hum, that is likely related. I see it happens on the Mac worker. And the issue isn't 100% reproducable since previous builds didn't trigger it. Might be related to a threading issue. I did run the test under Valgrind on Linux (just tried again) and it didn't exhibit any issue. And I don't have a Mac, so not sure how to help on that. A stack-trace would be a beginning.

**Comment by m-kuhn** [comment]
Was hoping you could make an educated guess, sorry I don't have any more hints.

**Comment by rouault** [comment]
I investigated on this issue by tuning a special Travis conf to run the WFS tests in a loop. https://travis-ci.org/rouault/Quantum-GIS/builds/121680454 ran successfully for 300 iterations before reaching the timeout limit of Travis. I also found a Mac OS X Maverick 10.9 VM version where I did a build as close as possible as Travis and couldn't hit a segfault when running the tests. Nothing suspicious with Valgrind neither. And the good news is that the WFS provider works properly in QGIS GUI.

**Comment by m-kuhn** [comment]
Thanks for looking into it. Hmm... The only other suspicion is that it could be affected by tests running in parallel. We run two jobs at the same time

```
        Start 193: PyQgsWFSProvider
192/196 Test #190: PyQgsVirtualLayerProvider ...............   Passed   11.68 sec
        Start 194: PyQgsLogger
193/196 Test #194: PyQgsLogger .............................   Passed    0.32 sec
        Start 195: PyQgsPalLabelingServer
194/196 Test #193: PyQgsWFSProvider ........................***Failed   11.06 sec
```

Maybe it was somehow influenced by the virtual layer provider or logger test.

**Comment by elpaso** [comment]
Maybe unrelated,  but can you please check if the following helps? 
This seems to fix https://hub.qgis.org/issues/14010 in master
```
/src/providers/wfs/qgswfsprovider.cpp

-  return new QgsWFSFeatureIterator( new QgsWFSFeatureSource( this ), true, request );
+  return QgsFeatureIterator( new QgsWFSFeatureIterator( new QgsWFSFeatureSource( this ), true, request ) );
```

**Comment by rouault** [comment]
@elpaso I'm not sure how that could help given that the issue we discuss is hard to reproduce. Your issue seems to be different at first sight, and I've just tested on Linux & Windows with current master and cannot reproduce a crash with the offline editing. Your change seems harmful though (although I'm not clear why that would help since  QgsFeatureIterator( QgsAbstractFeatureIterator* iter ) constructor should be called implictly without it), and other providers have similar patterns, so you could submit a PR with it.

**Comment by rouault** [comment]
@m-kuhn Running tests in parallel was indeed the key to increase the likehood of the failure ! Just because of different scheduling. I've submitted a PR with the fix I finally came with : https://github.com/qgis/QGIS/pull/2984 , which turns out to be a problem not in the WFS code... Finally happy to have a solution before the weekend to an issue that made me busdy during the last 24 hours :-)

**Comment by JuergenWeichand** [comment]
@rouault thank you very much for this enhancements. It is great to see the native WFS 1.1 and WFS 2.0 support in QGIS. The implemented paging mechanism is very helpful. I made some further testing and discovered the following issues.

#### Missing namespace declaration in the GetFeature request
In the GetFeature request the namespace declaration is missing. This will result in ServiceExceptions with some kind of WFS server. Please add the `namespaces` parameter. Example `namespaces=xmlns(bvv,http://www.geodaten.bayern.de)`.

#### Encoding issue in the fes filter
Querying the type `bvv:lkr_ex` (http://geoserv.weichand.de:8080/geoserver/wfs) with the filter `"bez_krs"='Ingolstadt'` is returning one feature. But the filter `"bez_krs"='München'` does fail. 

####  Better exception handling if the WFS server is providing complex features
I've also did some testing with WFS 2.0 Server providing complex features which are not supported. 

In the first case, the QGIS WFS provider is not able to parse the complex schema structure and returns the following message `DescribeFeatureType failed for url  srsname='EPSG:4326' typename='ad:Address' url='http://demo.deegree.org/inspire-workspace/services/wfs' version='2.0.0' table="" sql=: failed retrieving attributes from schema`.

In the second case, the layer is containing null values and is non spatial. 
http://services.cuzk.cz/wfs/inspire-cp-wfs.asp

Is there way to throw a message like `Complex features are not supported yet` ?

**Comment by rouault** [comment]
@JuergenWeichand 

> Missing namespace declaration in the GetFeature request

According to the WFS spec, namespaces is supposed to be optional. Can you point to servers that need it ? Could be worth a dedicated ticket.

> Encoding issue in the fes filter

This seems to be a defect of the WFS server. I have the same issue with the OGR WFS client.

Spied with wireshark, here's the request sent by QGIS :
http://geoserv.weichand.de:8080/geoserver/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=bvv:lkr_ex&FILTER=%3Cfes:Filter%20xmlns:fes%3D%22http://www.opengis.net/fes/2.0%22%3E%0A%20%3Cfes:PropertyIsEqualTo%3E%0A%20%20%3Cfes:ValueReference%3Ebez_krs%3C/fes:ValueReference%3E%0A%20%20%3Cfes:Literal%3EM%C3%BCnchen%3C/fes:Literal%3E%0A%20%3C/fes:PropertyIsEqualTo%3E%0A%3C/fes:Filter%3E%0A

München is properly escaped as M%C3%BCnchen (\xC3 \xBC is the proper UTF-8 representation of ü)

> Better exception handling if the WFS server is providing complex features

Could you open a ticket about that ? The 2 cases are different. In the first case (http://demo.deegree.org/inspire-workspace/services/wfs), this is due to the response doc being a reference to others, which would require resolving them, to indeed discover that they are complex feature. In the second case, the parser of DescribeFeatureType might be improved to deal more sensibly with that : it doesn't support multiple types being defined in the response.

**Comment by JuergenWeichand** [comment]
> Missing namespace declaration in the GetFeature (and DescribeFeatureType) request 

I've think it's optional because you can have requests which don't require the additional namespace declaration, e. g. using stored queries (no `typenames` parameter).
http://geoserv.weichand.de:8080/geoserver/wfs?service=WFS&request=GetFeature&version=2.0.0&StoredQuery_ID=bboxQuery&x1=4466856&y1=5346319&x2=4466980&y2=5346396

The examples in the WFS 2.0 spec are using the `namespaces` parameter if the typename contains a prefix (e. g. B.8.2.1). I received this requirement very early after releasing the first experimental version of the [WFS 2.0 Client Plugin](https://plugins.qgis.org/plugins/wfsclient/). 

> Encoding issue in the fes filter

Yes you're right. Verified using MapServer 7.
http://geoserv.weichand.de/cgi-bin/test-mapserver7.cgi

> Better exception handling if the WFS server is providing complex features

I will open the tickets.

**Pull request merged**
