### PR TITLE
Drop V2 suffix on all geometry classes

### PR DESCRIPTION
**Pull request by m-kuhn**
References https://github.com/qgis/qgis3.0_api/issues/11

This finally brings back a consistent state in naming within the geometry API

Renames
=======

| QGIS 2             | QGIS 3             |
|--------------------|--------------------|
| QgsPolygon         | QgsPolygonXY       |
| QgsMultiPoint      | QgsMultiPointXY    |
| QgsMultiPolyline   | QgsMultiPolylineXY |
| QgsMultiPolygon    | QgsMultiPolygonXY  |
| QgsPolygonV2       | QgsPolygon         |
| QgsMultiPointV2    | QgsMultiPoint      |
| QgsMultiPolylineV2 | QgsMultiPolyline   |
| QgsMultiPolygonV2  | QgsMultiPolygon    |

### CODE REVIEW

**Comment by NathanW2** [comment]
+1

**Comment by m-kuhn** [comment]
@nyalldawson 

any idea what this is:

```
======================================================================
ERROR: testTaskFromFunctionFinishedWithVal (__main__.TestQgsTaskManager)
test that task from function can have callback finished function and is passed result values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/QGIS/tests/src/python/test_qgstaskmanager.py", line 231, in testTaskFromFunctionFinishedWithVal
    self.assertEqual(finished_single_value_result.value, 5)
AttributeError: 'function' object has no attribute 'value'
----------------------------------------------------------------------
```

https://travis-ci.org/qgis/QGIS/jobs/294566074#L795-L804

Just seen this the first time (after restarting the job for a different failure). And to be hones, I've got no idea how that code works and how that ever succeeded. A method and a local variable with the same name and an assignment to it to pass back a value... Need to finally get a python book apparently :D

**Comment by nyalldawson** [comment]
> Just seen this the first time (after restarting the job for a different failure). And to be honest, I've got no idea how that code works and how that ever succeeded. A method and a local variable with the same name and an assignment to it to pass back a value... Need to finally get a python book apparently 

There's a duplicate line there. But basically it's storing the passed value as a property on the function so that we can later test if that function was called and what value was passed to it. Global variables would also work here, but this keeps the test self-contained.

**Comment by nyalldawson** [comment]
Lovely work here!

Can I suggest a related rename? c4f3832af28  renamed QgsGeometry::fromPolyline to QgsGeometry::fromPolylineXY. I think we should do this for all these methods if we're renaming the related classes. E.g. fromMultiPoint -> fromMultiPointXY, fromPolygon -> fromPolygonXY, etc. Then we've got scope to later in 3.x readd new fromMultiPoint/fromPolygon etc which operate on QgsPoint.

**Comment by m-kuhn** [comment]
> There's a duplicate line there. But basically it's storing the passed value as a property on the function so that we can later test if that function was called and what value was passed to it. Global variables would also work here, but this keeps the test self-contained.

Thanks. In the end, I figured it out which led me to propose #5495 which should make things even more self-contained.

**Comment by NathanW2** [comment]
NIce work. Thanks.

**Pull request merged**
