### PR TITLE
CI: Restore MSYS2/MinGW-w64 and move it to Qt6

### PR DESCRIPTION
**Pull request by MehdiChinoune**
## Description

Re-enable MSYS2/MinGW-w64 job but with Qt6.

### CODE REVIEW

**Comment by nyalldawson** [comment]
I'm -1 to introducing another ci build, UNLESS we can drop one of the existing ones or it's extremely high priority. There's just so many long running jobs here already. 🫤

**Comment by MehdiChinoune** [comment]
> I'm -1 to introducing another ci build, UNLESS we can drop one of the existing ones or it's extremely high priority. There's just so many long running jobs here already. 🫤

I dropped MINGW64 (Fedora) job.

**Comment by nyalldawson** [comment]
@MehdiChinoune but why is this job more useful then the mingw one? As far as I see it:

- the mingw one provides a nicely packaged build ready for users to test
- the mingw build uses qt5, which is still the official supported qt version for qgis
- this msys build is now qt6 and duplicates the other qt 6 one, but that one also provides the useful SDK

So of the 3 windows builds, the msys2 one seems least useful to me...

**Comment by nicogodet** [comment]
Qt5 builds is still relevant as migration to Qt6 is not completely done yet (I reported a crash on qt6 which doesn't happen in qt5).
Previous job built an artifact to easily test a PR.
-1

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune but why is this job more useful then the mingw one? As far as I see it:
> 
> * the mingw one provides a nicely packaged build ready for users to test
> * the mingw build uses qt5, which is still the official supported qt version for qgis

So, let's keep it
> * this msys build is now qt6 and duplicates the other qt 6 one, but that one also provides the useful SDK
> 
> So of the 3 windows builds, the msys2 one seems least useful to me...

So you don't want to test MinGW-w64 + Qt6?

You know that MinGW is different than MSVC!

**Pull request closed without merging**
