### PR TITLE
Processing multiselect delete columns

### PR DESCRIPTION
**Pull request by mbernasocchi**
this is the follow up of PR #3167. I kept those separated because I do not know if the change in delete columns is desired or not.
@volaya if not desired, just close this PR and look at #3167

### CODE REVIEW

**Comment by nyalldawson** [comment]
@mbernasocchi what's the status here? I think it'd be useful to have the ability to delete multiple columns, so I'd like to see this move forward...

**Comment by nyalldawson** [comment]
@mbernasocchi gentle ping - is there a reason you haven't merged this?

**Comment by mbernasocchi** [comment]
hi @nyalldawson, yes originally, because I the desired or not question was unanswered, now lack of time. And I've push rights only on android stuff, so if you like this, please merge it.

**Comment by nyalldawson** [comment]
@mbernasocchi seems like most of this has already been merged. I've addressed the rest in https://github.com/qgis/QGIS/commit/3c51a93f6a3bceace0ad1dbf8779f17a78193361

**Pull request closed without merging**
