### PR TITLE
Plugin dependencies optional support

### PR DESCRIPTION
**Pull request by elpaso**
## Description

Implementation of QEP 132: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/132

plugin-dependencies

**Funded by: GISCE-TI S.L.**

## Details

A new optional metadata `plugin_dependencies` was added, the format is a comma separated list of PIP-like plugin names (with optional version):

```
plugin_dependencies=GeoCoding,IPyConsole==1.9,DoesNotExist
```
the example above  will require:
- any version of `GeoCoding`
- version 1.9 of `IPyConsole`
- any version of `DoesNotExist`

When a plugin is installed, the metadata is parsed and the user is prompted with a dialog listing the dependencies, the user can choose what to do with the dependencies:
- install
- upgrade/downgrade
- do nothing

### CODE REVIEW

**Comment by nyalldawson** [comment]
Looking good to me!

From the QEP, I wonder what your thoughts are regarding this comment: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/132#issuecomment-460136324 ? I'd like to get some guidelines/docs in place on how API should be handled for plugins here, before we widely expose this functionality as supported and plugins start to rely on potentially non-stable api from other plugins.

I'm concerned it's potentially a little rude for plugins to start treating other's work as stable API, and be imposing external restrictions on what someone else can do in future with their own work. E.g. I wouldn't want to see **anyone** using any part of my Processing provider plugins as stable API if they are accessing the Python classes directly (and not using the standard Processing API to run the algorithms ). For these plugins everything on the Python side is "private" and subject to change. But without a way to indicate this to other plugin developers the situation could get quite messy.

**Comment by elpaso** [comment]
@nyalldawson yeah, I read your comment, but I don't know what to say: I think that there is no way we can enforce an API in plugins, this is totally in plugin developers hands and there is nothing we can do.

When we started thinking to this functionality, the use cases were:

### plugin as a shared library 
a company that produced many plugins wants to install some common code as a plugin, all company's plugins will have a dependency on the "common library plugin".
In that case is the company itself that manages the API: no problems

### plugin as a meta-plugin
someone wants to create a meta-plugin which install a set of other plugins
In that case we have not any API cross-usage: no problems

### leecher plugin (pass me the term)
A plugin relies on an API of another plugin produced by another developer.
In that case the plugin author can pin the version of the other plugin he wants to install: no API problems here

So, the only case in which we would have an issue is if (in the latter case) the "leecher" plugin does not specify a version for the other plugin.

**Comment by nyalldawson** [comment]
> @nyalldawson yeah, I read your comment, but I don't know what to say: I think that there is no way we can enforce an API in plugins, this is totally in plugin developers hands and there is nothing we can do.

Right, I totally get that. But I think we could have some guidelines for developers here still. That's why I think we could do something like asking plugins to put "stable" api into a particular namespace.

It's a matter of:
1. deciding on what good practice should be
2. documenting it
3. hoping people follow it :wink: 

we can do 1 & 2, 3 we have no control over

> A plugin relies on an API of another plugin produced by another developer.
In that case the plugin author can pin the version of the other plugin he wants to install: no API problems here

From my understanding the dependencies are installed just like normal plugins, right? Does this mean if a plugin installs a dependency with a pinned version, the user can never upgrade that particular plugin?

**Comment by elpaso** [comment]
> > @nyalldawson yeah, I read your comment, but I don't know what to say: I think that there is no way we can enforce an API in plugins, this is totally in plugin developers hands and there is nothing we can do.
> 
> Right, I totally get that. But I think we could have some guidelines for developers here still. That's why I think we could do something like asking plugins to put "stable" api into a particular namespace.
> 
> It's a matter of:
> 
>     1. deciding on what good practice should be
> 
>     2. documenting it
> 
>     3. hoping people follow it wink
> 
> 
> we can do 1 & 2, 3 we have no control over
> 

I don't know, should we really do (and spend out time on) that? 
I might be wrong when I think the use case is very limited (in other words I cannot really think of one).
Do you have any example of an existing plugin that provides an API used by others?

> > A plugin relies on an API of another plugin produced by another developer.
> > In that case the plugin author can pin the version of the other plugin he wants to install: no API problems here
> 
> From my understanding the dependencies are installed just like normal plugins, right? 

Yes.

> Does this mean if a plugin installs a dependency with a pinned version, the user can never upgrade that particular plugin?

No, nothing is enforced here and nothing is automatic: the check is only done during plugin installation or upgrade and the user will be presented with the dependency dialog. 

The current implementation is not smart enough to consider conflicts between plugins (say that plugin A requires version 1 of plugin B and plugin C requires version 2 of plugin B).

**Comment by luipir** [comment]
> Do you have any example of an existing plugin that provides an API used by others?
> 
> > >

in 2.x there where many using OpenLayer APIs... or people using MMQGIS prcessing methods. 
BTW I understand nyall possibile problems, but shoud we take care or do a strict quality control of the plugins?


> the user can never upgrade that particular plugin?

what about a trigger/notify plugin upgrade in the plugin registry? each depending plugin can listen uninstal or update of specified plugin (through QgsPluginRegistry) and do dependency check again notifying the user in case of incompatibilities.

BTW I agree with @elpaso the risk is low and can be documented

just my 2c

**Comment by m-kuhn** [comment]
>  Do you have any example of an existing plugin that provides an API used by others?

The QGIS ModelBaker plugin is used by LADM COL (and there might be others to come)

**Comment by elpaso** [comment]
Ok, if that's a use case we can come up with an official recommendation, I'm totally fine with that.

But what I don't understand is if it does have any impact on this PR.

**Comment by m-kuhn** [comment]
> But what I don't understand is if it does have any impact on this PR.

Not really from what I can see

Did you think about pip integration too? Would that be compatible with this approach?

**Comment by luipir** [comment]
> Would that be compatible with this approach?

seems the PR manage inter-plugin dependencies. Not is related with dependeincies with base libraries. IMHO does not overlap with other pip dependency controls that can be added in other PRs.

**Comment by elpaso** [comment]
@m-kuhn I've been thinking about python libraries dependencies too, I think we may add `python_dependencies` metadata tag in the future but the implications are IMHO very different: when I looked into that one of the blockers was that pip did not provide a stable API to use it as a library, additionally we would have to deal with system packages.

Something that would worth exploring is kind-of per-plugin virtual env, but I don't really know if that is feasible or not, we do have a single interpreter instance after all.

**Comment by m-kuhn** [comment]
> pip did not provide a stable API to use it as a library

ouch.
might be worth adding a wrapper to some of the key-API.

> Something that would worth exploring is kind-of per-plugin virtual env

I think that's going to be impossible to accomplish, as long as there is a single interpreter. And sandboxing the interpreter is a) very complex and b) breaks inter-plugin communication...

**Comment by nyalldawson** [comment]
> Ok, if that's a use case we can come up with an official recommendation, I'm totally fine with that. But what I don't understand is if it does have any impact on this PR.

It doesn't have any impact on the content of this PR, just the timing. I'm pushing for us to have the discussion and decide on some recommended approaches (which we can then document) to accompany this, so that we can push people in the right direction when we officially expose support for dependencies. If we try to do this after, I'm afraid it will be too late.

So to kick start: Here's my original proposal from the QEP, which I still stand by:

@NathanW2 recently added the decorator support for Processing by adding his new API to the `qgis.processing` module -- so users have to go `from qgis.processing import ...`. I very much like this separation, and think we should do this more. So anything from `qgis.*` is stable API, anything outside (like `from processing.whatever`) is NOT STABLE and importing is at users own risk.

Perhaps this could be considered here. Plugins which want to expose some form to "public" stable api could inject them into a `qgis.3rdparty` or `qgis.plugins` module, and in doing so make a public declaration that they won't remove or break that API. E.g.

    from qgis.plugins.QuickWkt import quick_wkt_parser

is stable API, but

    from QuickWkt.gui.dialogs.SomeDialog import SomeDialog

is not, and other plugins which do this are doing so at their own risk.

Would this be acceptable to everyone?

**Comment by elpaso** [comment]
> So to kick start: Here's my original proposal from the QEP, which I still stand by:
> 
> @NathanW2 recently added the decorator support for Processing by adding his new API to the `qgis.processing` module -- so users have to go `from qgis.processing import ...`. I very much like this separation, and think we should do this more. So anything from `qgis.*` is stable API, anything outside (like `from processing.whatever`) is NOT STABLE and importing is at users own risk.
> 
> Perhaps this could be considered here. Plugins which want to expose some form to "public" stable api could inject them into a `qgis.3rdparty` or `qgis.plugins` module, and in doing so make a public declaration that they won't remove or break that API. E.g.
> 
> ```
> from qgis.plugins.QuickWkt import quick_wkt_parser
> ```
> 
> is stable API, but
> 
> ```
> from QuickWkt.gui.dialogs.SomeDialog import SomeDialog
> ```
> 
> is not, and other plugins which do this are doing so at their own risk.
> 
> Would this be acceptable to everyone?

Absolutely yes!

**Comment by luipir** [comment]
> Would this be acceptable to everyone?

+1

**Comment by nyalldawson** [comment]
Ok, I've made https://github.com/qgis/QGIS/pull/9633 which provides a qgis.plugins container for stable 3rd party api to be patched into

**Comment by tomchadwin** [comment]
Really liking this - Vector Tiles Reader doesn't expose an API, but I do call one of its functions. If I could persuade them to register it with `qgis.plugins` (@mnboos, @sfkeller), the whole thing would become much less brittle.

**Comment by mnboos** [comment]
@tomchadwin What do you mean by

> register it with `qgis.plugins`

**Comment by tomchadwin** [comment]
@mnboos Will open an issue on the VTR repo.

**Comment by m-kuhn** [comment]
Hmm... How are classes with stable API to be exposed/imported?

**Comment by luipir** [comment]
> Hmm... How are classes with stable API to be exposed/imported?

as proposed by @nyalldawson in other PR https://github.com/qgis/QGIS/pull/9633

**Comment by m-kuhn** [comment]
@elpaso I'm having troubles installing plugins from zip file, is that related to the dependency work?

```
Traceback (most recent call last):
  File "", line 1, in 
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/pyplugin_installer/installer.py", line 611, in installFromZipFile
    self.processDependencies(pluginName)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/pyplugin_installer/installer.py", line 642, in processDependencies
    to_install, to_upgrade, not_found = find_dependencies(plugin_id)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/pyplugin_installer/plugindependencies.py", line 68, in find_dependencies
    plugin_deps = __get_plugin_deps(plugin_id)
  File "/home/mkuhn/dev/qgis/build-QGIS-Desktop-Debug/output/python/pyplugin_installer/plugindependencies.py", line 32, in __get_plugin_deps
    parser = plugins_metadata_parser[plugin_id]
KeyError: 'stable_project_files'
```

**Pull request merged**
