### PR TITLE
[API] QgsGeometryUtils: refacto and fix multiple cartesian distance

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description

Refactor QgsGeometryUtils to separate "basic" methods from those involving QGIS
composite types.
By "basic" methods, we refer to those that only require doubles or (qgs)vectors.
These methods are now encapsulated in their dedicated classes and can be called
from anywhere to prevent duplications in certain methods (in particular Cartesian distance calculation).
To maintain API compatibility, all methods are also accessible in QgsGeometryUtils
which acts as a pass-through to QgsGeometryUtilsBase.

Note: I made this "discovery" while preparing a PR where I thought I could use an existing distance function, but I was compelled to add a new method, sqrDistance, to the code. This PR will serve for my next one.

### CODE REVIEW

**Comment by lbartoletti** [comment]
https://github.com/qgis/QGIS/actions/runs/6585775825/job/17899001732?pr=55000 is not related to my PR. I'll fix it in another PR to not mixup commits.

**Review by benoitdm-oslandia — APPROVED** [review]
LGTM

**Review by troopa81 — COMMENTED** [review]
It looks like a good idea to separate basic method from the one using QGIS type but it makes declaration/definition and documentation redundant. Why not make QgsGeometryUtils inheriting QgsGeometryUtilsBase ?

**Comment by troopa81** [comment]
> https://github.com/qgis/QGIS/actions/runs/6585775825/job/17899001732?pr=55000 is not related to my PR. I'll fix it in another PR to not mixup commits.

I would rather prefer that we fix those before either in this PR or in another one and rebase this work upon it. There is actual real issue IMHO.

**Comment by nyalldawson** [comment]
> Why not make QgsGeometryUtils inheriting QgsGeometryUtilsBase ?

It's all static methods anyway, what would inheritance gain us?

**Comment by troopa81** [comment]
> It's all static methods anyway, what would inheritance gain us?

Yes, indeed... So why not using a namespace instead ?

**Comment by nyalldawson** [comment]
@troopa81 

> Yes, indeed... So why not using a namespace instead ?

It doesn't play well with sip -- we get better docstring support via classes with static members.

**Comment by troopa81** [comment]
> It doesn't play well with sip -- we get better docstring support via classes with static members.

I was afraid you'd say that... so ok, let's go this way

@lbartoletti Shall we not deprecate those method and make them SIP available in QgsGeometryUtilsBase ?

**Comment by lbartoletti** [comment]
> > It doesn't play well with sip -- we get better docstring support via classes with static members.
> 
> I was afraid you'd say that... so ok, let's go this way
> 
> @lbartoletti Shall we not deprecate those method and make them SIP available in QgsGeometryUtilsBase ?

@troopa81 QgsGeometryUtilsBase "sipifyed"

I don't think we should deprecate these methods, since they are widely used.

**Comment by lbartoletti** [comment]
@troopa81 [49447f8](https://github.com/qgis/QGIS/pull/55000/commits/49447f82238cd12adce3493dfcc5e2ffd161cee8) and [76e7526](https://github.com/qgis/QGIS/pull/55000/commits/76e75268129255ef6b19d965dc18599b91fc37ef) are the two commits that deprecate the base methods moved to QgsGeometryUtilsBase and that are still present in QgsGeometryUtils. I'll leave it up to you to decide whether to keep these commits or not.

**Review by troopa81 — APPROVED** [review]

**Pull request merged**
