### PR TITLE
Add a startup tip on VRT files (fix Redmine #4346)

### PR DESCRIPTION
**Pull request by ghost**
This should fix [#4346](https://hub.qgis.org/issues/4346)...

### CODE REVIEW

**Comment by medspx** [comment]
@nyalldawson Ok, I've fixed the indentation problem (and added the good git hook to not make it happen again)...

**Comment by m-kuhn** [comment]
Seems there are still indentation problems...

Can you run

    ./scripts/astyle.sh src/app/qgstipfactory.cpp
    git add src/app/qgstipfactory.cpp
    git commit
    git push

(or use git `commit --amend` and force push if you feel confident about it)

**Comment by medspx** [comment]
According to Travis logs, the indentation problem seems to be on python/plugins/processing/gui/ExtentSelectionPanel.py and python/plugins/processing/modeler/ModelerParametersDialog.py.

**Comment by m-kuhn** [comment]
hmmm... rerunning :)

**Comment by m-kuhn** [comment]
No idea why these files are constantly triggering failures in this unrelated PR.
Merged in 88d3b9fc812bfcc7e7bcf09865f7f18725541fc5
and files fixed in 80de178d9efdfdac6ef42d23cc44500dba0e243f

Thank you!

**Pull request closed without merging**
