### PR TITLE
Automatically translate layer data from ESRI Filegeodatabases to QGIS layer metadata

### PR DESCRIPTION
**Pull request by nyalldawson**
Translate as much as possible of the original ESRI metadata across to the QGIS metadata, so that it's immediately available for
use by users after loading a .gdb file.

Sponsored by North Road / SLYR

### CODE REVIEW

**Comment by pblottiere** [comment]
Code looks good to me :+1:

**Comment by Saijin-Naib** [comment]
Nyall... NYALL.

Oh, how I thank you.

**Comment by nyalldawson** [comment]
> Oh, how I thank you.

😁 Testing of this would be highly appreciated -- the esri schema doesn't map super-cleanly to the qgis schema, so there's a chance some important parts won't translate yet. I'd love more real world testing and bug reports if you find any potential improvements!

**Comment by roya0045** [comment]
@Saijin-Naib for easy testing I recommend the mingw artefact.

**Pull request merged**
