### PR TITLE
Fix map canvas preview

### PR DESCRIPTION
**Pull request by m-kuhn**
Followup 8e200767e

### CODE REVIEW

**Comment by nirvn** [comment]
@m-kuhn , OK, I'm testing this out. The preview now shows up on all sides / corners -- that said, I can definitively spot a *significant* performance regression now (which isn't linked to this PR per say, just the preview stuff in general).

Using a multi-gb raster, if I drag the canvas while preview tiles aren't all rendered (i.e. in the process of being rendered), it takes *forever* for the canvas' view to redraw. Same thing goes for zooming in / out. If it's not the case already, panning and/or zooming the canvas should immediately stop any preview rendering, as to not impact access to large rasters (and other large datasets, assuming large vector datasets will suffer from same issue).

**Comment by nirvn** [comment]
It's a real issue in terms of perceived UX responsiveness. If I drag the canvas around when all preview tiles have been rendered, the canvas renders in <1sec. If I drag canvas while preview tiles are still rendering, the canvas renders in >3sec.

**Comment by vpicavet** [comment]
Hi, does latest fixes by @m-kuhn solve rendering lags reported by @nirvn ? Is the canvas preview feature considered stable now ?
@m-kuhn did you do some testing with QGEP to know if it helps on performance problems ? ( see https://github.com/QGEP/QGEP/issues/308 )

**Comment by m-kuhn** [comment]
@vpicavet it might make them less perceptible but doesn't actually "solve" any of it

**Pull request merged**
