### PR TITLE
[OGR] Add workaround for OGRSQL not recognizing the column name returned by OGR_L_GetFIDColumn

### PR DESCRIPTION
**Pull request by manisandro**
2.18 backport of #5224

### CODE REVIEW

**Comment by luipir** [comment]
@manisandro as far as I understand test:
265 - PyQgsServer (Failed)
started to fail since this merge. Was merged with a failing test? is the test related with this PR?

**Comment by manisandro** [comment]
@luipir I'm pretty sure it was green when I merged it, but since there is now a red X besides the commit I'm not actually sure what happened. In any event, yes it is related, the test needs to be updated. But the failure should have actually appeared already after 54653e4a5bca5e20f51cc680dd3335ce1b120057, since that is the commit that added the orig_ogc_fid field.. I'll update the test.

**Comment by luipir** [comment]
tnx @manisandro

**Comment by luipir** [comment]
@manisandro news?

**Comment by manisandro** [comment]
@elpaso Working on it

**Comment by manisandro** [comment]
@elpaso Part of #5251

**Pull request merged**
