### PR TITLE
Test readme typos

### PR DESCRIPTION
**Pull request by HughKelley**
## Description

Very minimal commit fixing a typo I noticed in the testing readme. 
`-DENABLE_TESTS=ON` to `-D ENABLE_TEST=ON` 

Hopefully easy to review and approve. Just working through the project standards and hoping to contribute more meaningfully in the future. 

Thanks!

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thank you for opening a pull request.

Technically both work (with and without space after the `-D`), historically, QGIS uses spaceless more often, but I think with space is more readable.
Could you align some remaining ones in INSTALL.md (toplevel dir) as well, to make sure that we at least have it conisistently inside .md files?

Thanks again and looking forward to more contributions !

**Review by m-kuhn — APPROVED** [review]

**Comment by HughKelley** [comment]
Added, interesting, I had no idea about this but read [this](https://unix.stackexchange.com/questions/292232/why-can-spaces-between-options-and-parameters-be-omitted) and understand. 

Now that I went looking for that usage it's fairly extensive, for example in 

https://github.com/qgis/QGIS/blame/c5c8d1ff8cb6164ad7b113f118253e22158d0b0b/debian/rules#L81

and  

https://github.com/qgis/QGIS/blob/c5c8d1ff8cb6164ad7b113f118253e22158d0b0b/.github/workflows/mingw-w64-msys2.yml#L81 

these are all spaced though

https://github.com/qgis/QGIS/blob/c5c8d1ff8cb6164ad7b113f118253e22158d0b0b/ms-windows/osgeo4w/package.cmd#L116

https://github.com/qgis/QGIS/blob/c5c8d1ff8cb6164ad7b113f118253e22158d0b0b/ms-windows/osgeo4w/package-nightly.cmd#L115

Helpful to bring everything I can find to one standard or more trouble than it's worth?

**Comment by m-kuhn** [comment]
I would say we leave it at public facing docs for now (.md), changing it also in scripts adds noise to `git blame`.
If you want to get started with QGIS development, I'd instead focus on picking an easy bug to tackle.

**Comment by HughKelley** [comment]
sounds good, thanks very much!

**Pull request merged**
