### PR TITLE
[attributetable] Fix "Move selection to top": for 2.18 regression fixes #15803

### LINKED ISSUE #15803: Preview in expression builder not always showing
Author Name: **Paolo Cavallini** (@pcav)
Original Redmine Issue: [6616](https://issues.qgis.org/issues/6616)
Affected QGIS version: 3.0.0
Redmine category:gui

---
The preview in the field calculator expression builder is often missing. This happens because the expression text is evaluated against the first feature in the layer. If the expression doesn't evaluate for the first feature there will be no text. 

Thanks Nathan for the explanation.

### PR DESCRIPTION
**Pull request by luipir**
the reason that sortColumn() normally was set to it's initial value -1 in:
QSortFilterProxyModel but, somewere in qgis code (probably in the init
of QgsMapLayerProxyModel)  already set a sortColumn => the normal flow
skip default call to sort(0) during first open or during trigger of selectOnTop pushButton

### CODE REVIEW

**Comment by m-kuhn** [comment]
Does that also affect master?

**Comment by luipir** [comment]
Sorry @m-kuhn I missed you question... I tested on mater and this fix does not work for master, But I hadn't time to investigate more on master.
Checking again (now in Essen) just to be sure

**Comment by luipir** [comment]
The initial SortOrder value is sortOrder() return value is 1797221327 => it does not apply any sort

**Comment by luipir** [comment]
@m-kuhn fix applied to qgis3 too in https://github.com/qgis/QGIS/pull/4442

**Comment by luipir** [comment]
Fix "Move selection to top" in attribute table. The origin of the problem is due the fact that sortOrder is undefined enetring in selectionOnTop. I wasn't able to find why it is undefined albeit the base class constructor set it as Ascending.

**Comment by luipir** [comment]
I'm supposing (just speculation) this would is the same reason for these issues:
https://hub.qgis.org/issues/15976
http://hub.qgis.org/issues/15974

**Comment by luipir** [comment]
@m-kuhn leaved input control and added value check in QgsAttributeTableConfig

**Pull request merged**
