### PR TITLE
[processing] If supported, use memory layers instead of shapefiles

### PR DESCRIPTION
**Pull request by nyalldawson**
...when writing to a temporary result

Avoids truncation of field names and other format specific limitations. I can't see any downsides to this approach - files stored in temp folders are only temporary anyway.

### CODE REVIEW

**Comment by nirvn** [comment]
Wa-hou!

**Comment by m-kuhn** [comment]
Memory usage?

**Comment by nyalldawson** [comment]
Memory is cheap... loosing field names is painful

**Comment by m-kuhn** [comment]
Crashes when performing algorithms caused by lack of memory or because of huge datasets is worse than losing field names.
I think it would be good to have the possibility to opt out (... possibly to a format like geopackage ...). Or is that possible anyway?

**Comment by nyalldawson** [comment]
That's already possible. By default processing sets to save the output to a "temporary file", which is a shapefile in the temp folder. This changes that default for QGIS native algorithms to use a memory layer. There's still the option to save to any of format, PostGIS, spatialite, etc.

Anyway, if the memory provider will crash with large layers then that should be addressed separately

**Comment by m-kuhn** [comment]
Ok for me then.

I have never experienced any crashes, it was just an assumption what could happen when you run out of memory and swap.

**Pull request merged**
