### PR TITLE
Always use primary key of type map

### LINKED ISSUE #14262: Making url's in WMS Query response clickable
Author Name: **Tim Couwelier** (Tim Couwelier)
Original Redmine Issue: [4325](https://issues.qgis.org/issues/4325)

Redmine category:web_services_clients/wms

---
In follow-up of this thread on the QGis forums (http://forum.qgis.org/viewtopic.php?f=2&t=9317&sid=5685153a6922412e5102f781eb1bd81f)

Some WMS servers give responses through the info tool that hold url information.
Whereas on user created vector datasets, one can make this possible through 'Actions', this is not possible for WMS layers.

This could be an enhancement to the information tool.

PS: I do hope I put this up in the right spot, as this is a first for me.

### PR DESCRIPTION
**Pull request by strk**
Fixes editing of features with negative int identifier
Closes http://hub.qgis.org/issues/14262

### CODE REVIEW

**Comment by strk** [comment]
I was thinking that since we have an int64 to express the FID, we might still use a direct mapping for int4 (32bit) and int2 (16bit) by adding 2^32 to the database value, so to ensure the resulting value is always positive. We would then still need to use the mapping for an int64 input (unless we want to preflight to find out if it's all positives, which we'd better not for big tables). Worth the trouble ? What do you think @jef-n ?

**Comment by m-kuhn** [comment]
Isn't the mapping more demanding in terms of memory and CPU? So it would be good to skip the mapping and continue using int whenever possible. So your proposal with only mapping int64 sounds good to me.

**Comment by strk** [comment]
I don't think the cost of mapping would be noticeable. Once you start using tables with million of records I'm sure there are a lot more problems than doing a lookup in a QHash. Performances can be compared by using as the primary key of a table with many rows either an integer or a (say) string type.

**Comment by m-kuhn** [comment]
I'm pretty sure this issue is also related to using maps https://hub.qgis.org/issues/14196

I'd rather use a simple deterministic approach than a lookup. It's failureproof and easy on resources, maps should be a last resort.

**Comment by strk** [comment]
Chances are the lookup code is just broken.
By always using lookup it either always work or never work,
while if we maintain two distinct mechanisms, it's harder to maintain
both.

I know having both could be easier to CPU, but do we have the
resources to maintain both ? Are there tests for both ?

Which reminds me, the bug this PR is aimed at fixing still doesn't
have an automated testcase to show the problem.

**Comment by m-kuhn** [comment]
Indexes on positive integers have proven stable. Your approach for negative indexes with bitshifting sounds trivial and stable.

I don't think there's a good reason for switching everything to maps which are less stable and have a negative impact on memory and cpu.

**Comment by strk** [comment]
But I guess you do see reasons to _support_ maps, or don't you ?
We _are_ providing map-based lookups, and not telling the user
anything about that. Can't the user pick any value type for primary key
with using a map ?

The issue you pointed me at suggests me exactly that: map support
exists but is partially broken.

Then why not disabling maps completely, of fixing it once for all ?

Doing the shifting would add a third mechanism, so we'd have to
maintain:

    1. DB pkey value
    2. shifted DB pkey value
    3. mapped DB pkey value

At the moment I don't have time (aka funds) to implement that
additional mechanism, but I know for sure that support for _any_
postgis table out there using an integer primary key would be
currently broken.

Incidentally, I've just rebased the branch to master, but my local
"make check" ends with 17 tests failed out of 207, none of which gives
clear message about what the failure was.

**Comment by m-kuhn** [comment]
> But I guess you do see reasons to _support_ maps, or don't you ?

If there is no other way I don't see a reason why not

> The issue you pointed me at suggests me exactly that: map support
exists but is partially broken.

Probably yes. Probably only in server based on concurrency issues. Probably it works in most other cases.

> Then why not disabling maps completely, of fixing it once for all ?

We shouldn't disable it because it seems to work in most scenarios.
I don't see a reason why it should not be fixed.

> At the moment I don't have time (aka funds) to implement that
additional mechanism, but I know for sure that support for _any_
postgis table out there using an integer primary key would be
currently broken.

It seems there are problems currently. It also seems like there are working things currently ("_any_
postgis table out there using an integer primary key would be currently broken" is a bit of an overstatement). And it seems it is very likely that new problems are introduced with this PR.
Under these conditions I think we should stick to the current situation with known problems over fixing known problems at the expense of new problems.

> Incidentally, I've just rebased the branch to master, but my local
"make check" ends with 17 tests failed out of 207, none of which gives
clear message about what the failure was.

Then it looks like you and I have not put enough time into making the tests pass on every platform and failure messages verbose enough :)

**Comment by strk** [comment]
On Tue, Apr 26, 2016 at 07:37:58AM -0700, Matthias Kuhn wrote:

> Then it looks like you and I have not put enough time into making the tests pass on every platform and failure messages verbose enough :)

True. Sorry for the frustration-based outburst.

Feel free to close this or mark as in-progress or whatever signals
there's no need to take action until something changes.

**Comment by strk** [comment]
@m-kuhn an implementation of offset idea is in #3036 but right after creating the PR I realized it would still leave tables with signed values in an int64 primary key broken, which means again we should get back to this to fix that, leaving very few cases of non-Map implementation.

**Comment by jef-n** [comment]
Maybe the server implies that the feature ids are persistent and they aren't in case of map.  The map is built from the features in order of retrieval.  Each new key tuple produces a new feature id.   The map is in the provider and so each vector layer is tied to it's provider.  Maybe it's an issue with the layer cache in the server

**Comment by m-kuhn** [comment]
Thanks @strk 

@jef-n probably something like this. Would you switch everything to maps if this issue is ironed out?

**Comment by jef-n** [comment]
@m-kuhn no - why use a map to produce a different integer from an integer?  There's probably stuff out there that implies that feature id and a attribute value match.   So I'd also prefer handling negative values separately, int64 with a map and keep the rest as is.

**Comment by m-kuhn** [comment]
In this case I will close this one in favor of #3036

**Pull request closed without merging**
