### PR TITLE
[processing] restore union algorithm

### PR DESCRIPTION
**Pull request by nirvn**
## Description
@nyalldawson , one more. 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by gioman** [comment]
@nirvn @nyalldawson of course many thanks for the effort on Processing, this is really much appreciated. I have of course a question to make (pardon me be very boring on this matter) about the tools like union, difference, intersect, etc. We know that in QGIS 2.* these tools have issues... like producing -basically silently- wrong results when geometries are not completely clean (but there are also issues with ok geometries, like the intersection tool creating duplicated polygons)... is this being addressed while porting to qgis 3?

**Comment by nyalldawson** [comment]
@gioman I agree that this is the perfect opportunity to make sure these algorithms are rock solid. Do you have corresponding bug reports for the issues with union?

**Review by nyalldawson — COMMENTED** [review]
Port looks good to me!

**Comment by Gustry** [comment]
@wonder-sk made some work beginning of 2017, AFAIK, there are still some issues.
I found this PR on 2.18, I'm not sure it has been backported on master: https://github.com/qgis/QGIS/pull/4037

**Comment by wonder-sk** [comment]
Indeed, I think I have forgotten to forward port my fixes from 2.18 to 3.0.

Even with my fix from #4037 there is one pending question related to various geometry processing algorithms: what to do when some geometries on the output do not have the expected geometry type? (e.g. intersection of two polygon layers should result in polygons, however if we have two polygons with that share an edge we get a linestring geometry - or if they share a corner we get a point)

I would say that we need two modes:
- default mode: ignore incorrect parts of output geometries and just log that it happened so the user knows
-.advanced mode: it would output geometry collection type and so it would not omit anything

**Comment by alexbruy** [comment]
I know, I'm late with this, but IMHO better to not only restore algorithms but also add unit-test for them

**Comment by alexbruy** [comment]
@nyalldawson I did very quick search in bugtracker and here some issues:
- union and intersection https://issues.qgis.org/issues/15962
- intersection https://issues.qgis.org/issues/14504
- difference https://issues.qgis.org/issues/13368
- line intersection https://issues.qgis.org/issues/10039
- voronoi polygons https://issues.qgis.org/issues/8002
Maybe @gioman can also add something

**Comment by nirvn** [comment]
@wonder-sk , FYI, I haven't forward ported your improvement(s) on the union alg. Stating on the record to avoid confusion 😄

**Pull request merged**
