### PR TITLE
Fix "add tab or group container" dialog resizing

### PR DESCRIPTION
**Pull request by DelazJ**
Use gridLayout instead of formLayout
Before 
image
After
image

### CODE REVIEW

**Comment by nyalldawson** [comment]
@DelazJ what do you think about a bigger cleanup of this dialog? It doesn't follow qgis conventions well...

I'm thinking of avoid the "sentence" wording and widget layout and replacing with

"Name" (or "label"?) [............]

"Container type"
[O] Tab
[ ] Group box in container [......]

Number of columns (or "column count"?) [.....]

**Comment by DelazJ** [comment]
@nyalldawson Something like this?
image
Or do you think "container type" should be a simple label with slightly offset options

**Comment by nyalldawson** [comment]
@DelazJ 
that's a considerable improvement!

> Or do you think "container type" should be a simple label with slightly offset options

I like your screenshot better

**Comment by DelazJ** [comment]
OK. Done!

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
