### PR TITLE
Raise a Python OwnershipException when trying to /Transfer/

### PR DESCRIPTION
**Pull request by nyalldawson**
an object which is already owned by some other c++ object

Try 2...

### CODE REVIEW

**Comment by nyalldawson** [comment]
@m-kuhn @wonder-sk @3nids @elpaso

I've no luck confirming this approach with upstream, can you see any potential issues with it? (Like all sip work, it's just random keyboard bashing until something compiles 🙃)

**Comment by 3nids** [comment]
I had a look to the code and as far as I can tell it looks good to me.
If we tend to reuse this, it would be nice to have a macro or use sipify to generate the code, since there seems to be only 2 variables (message and convert class).

**Comment by nyalldawson** [comment]
> If we tend to reuse this, it would be nice to have a macro or use sipify to generate the code, since there seems to be only 2 variables (message and convert class).

I agree. Ideally, I'd partner this with a change in the c++ api to use a unique_ptr argument....

**Comment by elpaso** [comment]
As far as I understand looks good, I'm looking forward to see how you'll handle unique_ptr, I thought about that in the past but I couldn't find a way to handle them with SIP.

**Pull request closed without merging**
