### PR TITLE
Initialize a style group upon creation instead of upon renaming (fixes #14050)

### PR DESCRIPTION
**Pull request by SebDieBln**
When creating a style group within the `QgsStyleV2ManagerDialog` the group needs to be initialized by a call to `QgsStyleV2::addGroup()`.
This call was made within `QgsStyleV2ManagerDialog::groupRenamed()` instead of `QgsStyleV2ManagerDialog::addGroup()`. So until a group was renamed it remained in an un-initialized and thus un-usable state.

This PR calls `QgsStyleV2::addGroup()` from within `QgsStyleV2ManagerDialog::addGroup()`.

While moving the initialization code from `groupRenamed()` to `addGroup()` I cleaned it up and deduplicated where appropriate.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Does this relate to #14050?

**Comment by SebDieBln** [comment]
> Does this relate to #14050?

Yes. It fixes it. :wink: 

And in case you mean #14049: No, it does not.
But I am investigating that at the moment, too.

**Comment by nyalldawson** [comment]
Oops... Missed that part of the PR title :p

**Comment by SebDieBln** [comment]
FYI: [#14049](http://hub.qgis.org/issues/14049) will be fixed by #2629.

By the way: Is there a plan to deal with the ambiguity of the #-numbers?

**Comment by nyalldawson** [comment]
@SebDieBln nice work as usual! 

> By the way: Is there a plan to deal with the ambiguity of the #-numbers?
Eventually we hope to move the issue tracking to github too, which will fix this. In the meantime I usually just put the full link to the issue on hub.

**Pull request merged**
