### PR TITLE
Fix db manager sql query

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #21353

### CODE REVIEW

**Review by Gustry — APPROVED** [review]
Oh no sorry. I wonder how this error could come here. PyCharm is smart to put some warnings, autocompletion and I tried the code. (apparently not loading a layer in the final commit)

**Comment by luipir** [comment]
Does it need backport I suppose?

**Comment by nyalldawson** [comment]
*insert snarky remark about this not being possible if we ported to C++ here* 😉

**Comment by elpaso** [comment]
@luipir yes, backport is required

**Comment by elpaso** [comment]
@Gustry can you take care of the backports please?

**Comment by Gustry** [comment]
Yes I can

**Pull request merged**
