### PR TITLE
[Processing] More grass7 unit tests and their fixes...

### PR DESCRIPTION
**Pull request by ghost**
Here are about 90 unit tests for Processing Grass7 (rasters) algorithms.
What has been done:
- Split tests into two files (for the moment): one for imagery, the other for rasters.
- Modify blacklist for qt5/Python3 travis.
- When you make tests, you find bugs and I have included the fixes into this PR (because tests and fixes are directly related: I have found the bugs by creating the tests).
- As I am really lazy, I have improved graphical tests generation a bit in order to better handle  output files and input parameters. Futhermore, I have made generated test text ready for direct cut'n paste to yaml test file.

@volaya , @alexbruy , @m-kuhn I think that this is ready to merge before release...

### CODE REVIEW

**Comment by m-kuhn** [comment]
You are awesome!

**Comment by nyalldawson** [comment]
@medspx wow, fantastic work! 

Any chance you could get the tests working on the osx builds too? We want to reenable the osx CI testing and this is one thing blocking it. See:

http://dash.orfeo-toolbox.org/testDetails.php?test=42976784&build=234760

And

http://dash.orfeo-toolbox.org/testDetails.php?test=42976785&build=234760

**Comment by m-kuhn** [comment]
I think the mac problem is related to homebrew/packaging.

    AttributeError: 'NoneType' object has no attribute 'ReadAsArray'

indicates that the python gdal module seems to be missing

@dakcarto do you have a hint?

**Comment by timlinux** [comment]
Brilliant!

**Comment by gioman** [comment]
@medspx really many thanks for this effort!

**Comment by medspx** [comment]
@m-kuhn The osx problem is perhaps not related to gdal but simply because the raster files can't be retrieved (leading to an empty gdal object) ?

**Comment by m-kuhn** [comment]
yeah, I figured that out as well (was confused by local osx problems with python).
I was trying to update the deps https://github.com/qgis/QGIS/pull/3240 but unsuccessful so far...

**Pull request merged**
