### PR TITLE
Fix zoom out map tool (fix #12242)

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by nyalldawson** [comment]
@strk look ok to you?

**Comment by strk** [comment]
What's the problem with zoom out exactly ? How to reproduce it ?
Do we have any testcase for these kind of interactions ?

**Comment by gioman** [comment]
If you the zoom out tool by clicking and dragging (instead of just clicking) it zooms in.

**Comment by strk** [comment]
Thanks. Yes, the patch is ok to me (tested). Do we have automated tests for zoom in/out interactions ?

**Comment by strk** [comment]
There seem to be one, worth adding a test there to go with the patch:
https://github.com/qgis/QGIS/blob/master/tests/src/gui/testqgsmaptoolzoom.cpp

**Comment by strk** [comment]
hub ticket: http://hub.qgis.org/issues/12242 (for easy access)

**Comment by nyalldawson** [comment]
manually merged - I tried (and failed) to implement a test for test, so pushing the fix without it

**Pull request closed without merging**
