### PR TITLE
Do not delete the clear action (and don't crash)

### PR DESCRIPTION
**Pull request by elpaso**
Fix #20180 - Tracing with Offset produces QGIS Crash

The crash was deep inside Qt and I couldn't really debug it,
the solution I'm proposing looks way too easy, but
apparently it just works.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Actually this causes a regression and will bring back the "double" clear buttons. I can't think of any alternatives... :S

**Comment by elpaso** [comment]
I didn't see any double clear button, how do I reproduce it?
Btw, without this patch there is a consistent crash.

**Comment by nyalldawson** [comment]
For reference this is reverting fb5caa7a0f944788119b3429efb8f017964c5443

**Comment by nyalldawson** [comment]
I can't find an alternative -- I'd say just remove the clear button from this one particular widget, and send silent curses to Qt.

**Pull request merged**
