### PR TITLE
QgsTreeWidgetItem

### PR DESCRIPTION
**Pull request by nyalldawson**
This API break removes the broken QgsNumericSortTreeWidgetItem class (after all... it has a massive TODO saying "make it work"!) with QgsTreeWidgetItem. QgsTreeWidgetItem supports numeric sorting, plus extra features like the ability to specify a custom sort value or forcing a particular item to always sort on top.

The old QgsTreeWidgetItem class (which also derives from QObject) has been made a QgsTreeWidgetItem subclass - "QgsTreeWidgetItemObject". Suggestions for better naming are welcome!

This change likely has minimal impact on existing PyQGIS code, as I suspect these classes are not widely used (QgsNumericSortTreeWidgetItem because it's broken, and the old QgsTreeWidgetItem because it was only introduced in 2.16).

### CODE REVIEW

**Comment by wonder-sk** [comment]
Hi Nyall - good stuff...

I am thinking if we really need ```QgsTreeWidgetItemObject``` - it seems the extra signal was just a workaround in early Qt 4.x versions, since Qt 4.5 there is protected method ```QTreeWidgetItem::emitDataChanged()``` that should do the job.

Further down the road it would be great to get rid of ```QgsTreeWidgetItem``` too and instead have proper model/view approach where it was used before - but I understand that's a longer way to go :-)

**Comment by nyalldawson** [comment]
> I am thinking if we really need QgsTreeWidgetItemObject - it seems the extra signal was just a workaround in early Qt 4.x versions, since Qt 4.5 there is protected method QTreeWidgetItem::emitDataChanged() that should do the job.

I'd love to remove it, but I don't see how emitDataChanged() helps here. The original commit https://github.com/qgis/QGIS/commit/6c46b09c7547eb31243f8fb5e36c2dc22d85d11e introduced it as itemChanged() was firing too often. Wouldn't manually calling emitDataChanged() make the situation even worse?

> Further down the road it would be great to get rid of QgsTreeWidgetItem too and instead have proper model/view approach where it was used before - but I understand that's a longer way to go :-)

Thats... not a job I'd volunteer for ;)

**Comment by wonder-sk** [comment]
> I'd love to remove it, but I don't see how emitDataChanged() helps here. The original commit 6c46b09 introduced it as itemChanged() was firing too often.

Oh I see - I misunderstood the context why it was there - please ignore my comments :-)

> Thats... not a job I'd volunteer for ;)

I totally understand :-)

**Comment by nyalldawson** [comment]
Any objections if I merge?

**Comment by nyalldawson** [comment]
Merged in 39b3e721bb8ead993d87b927f10af5fbfc184e8b

**Pull request closed without merging**
