### PR TITLE
Stub test for QgsMapToPixelGeometrySimplifier

### PR DESCRIPTION
**Pull request by strk**
See #12416

### CODE REVIEW

**Comment by strk** [comment]
I'll want to add a test directly calling the WKB version to check for http://hub.qgis.org/issues/12416, before this is merged

**Comment by nyalldawson** [comment]
@strk great to see... this are of code desperately needs some unit tests to handle all the corner cases. I'd love to fix the bad simplification we get at global scales (when the features all collapse to rectangles), but I've always been concerned about causing additional regressions by hacking on this code.

**Comment by strk** [comment]
Yeah.
Unfortunately it isn't even easy to tell what the actually expected
result should be as it's weird. You can see that a linestring with
4 vertices within a total length < 10 and a 5th reaching length 20
is NOT simplified to a single segment but still retains 4 vertices,
and I cannot figure why would anyone rely on this behavior.

The expectancy in that test at the moment is only that the length
of the segment reduces (lowering expectances to avoid regressions
while enhancing the code too...

**Comment by nyalldawson** [comment]
@strk have you seen https://github.com/qgis/QGIS/pull/2483 ? Maybe it's worth pulling that in and replacing the existing simplifier?

**Comment by strk** [comment]
I'm now trying to reproduce the _obtaining_ of the broken WKB from the simplifier, as it uses "toWkb" method of QgsGeometry, but we saw that the returned WKB is _not_ accepted by the corresponding "fromWkb" method of QgsGeometry, so there must be something else going on in between that breaks the WKB on output. See #2722

**Comment by strk** [comment]
@nyalldawson my focus now is on tests and bug fixes, not enhancements.
I'm not even convinced about the benefits of doing simplification directly on the WKB representation...

**Comment by ahuarte47** [comment]
Hi @strk and @nyalldawson, in order to test results, I would like move the simplification to just when the geometry is prepared to draw in the QPainter device.

See:
https://github.com/qgis/QGIS/blob/master/src/core/symbology-ng/qgssymbolv2.cpp#L139
https://github.com/qgis/QGIS/blob/master/src/core/symbology-ng/qgssymbolv2.cpp#L190

This would avoid errors caused from invalid simplified geometries. All qgis code would work with the original geometry (spatial operations, feature expressions, labeling), and finally the geometry will be simplified just when it is converted to the QPolygonF object to paint. For labeling, in order to maintain performance, more work can be necessary to calculate the centroid from a simplified copy of the orginal geometry.

This pull https://github.com/qgis/QGIS/pull/2802 is a first step to remove duplicate code.

I can create a PR to test, do you prefer this approach?
Alvaro

**Comment by nyalldawson** [comment]
@ahuarte47 I like the idea in general - it would also help to address http://hub.qgis.org/issues/14301 . However, I'm concerned about the impact on labelling. Simplification gives a huge boost to the label rendering and I'd hate to see this go. I'm not sure if you've looked at the labeling pal code, but it does some obscure things with the geometries to generate candidates and it's not going to be trivial to modify these...

**Comment by ahuarte47** [comment]
Yes, this approach would help to address all issues related with to simplify the original geometries (invalid simplification and changing geometry-based expression values). About labeling, I would like to change how the centroid is calculated, it would work with a temporal simplified version of the original geometry.

I will search time to implement it, then we can test performance, do you agree?

NOTE:
I consider that https://github.com/qgis/QGIS/pull/2802 will merged? It removes duplicate code where the simplification should take place.

**Comment by ahuarte47** [comment]
Hi, I am developing a new pull with this approach:
https://github.com/qgis/QGIS/compare/master...ahuarte47:Issue_QPainterSimplification

The point is a new QgsConstWkbSimplifierPtr class that overrides QgsConstWkbPtr to simplify the PointF stream to paint. I get similar performance than current simplification (separate issue is the labeling).

For labeling, the simplification needs to run again :-(. I have studied it and the code calls a couple of times the costly IsGeoValid function to check the GEOS-definition. What do you think about to replace the use of GEOS by some hard-coded functions to calculate centroids... and to avoid this bottleneck?

**Comment by ahuarte47** [comment]
Hi, I released a new [pull](https://github.com/qgis/QGIS/pull/2900) with it.

**Pull request merged**
