### PR TITLE
Use a layerId instance of a layer in the access control interface

### PR DESCRIPTION
**Pull request by sbrunner**
Should fix http://hub.qgis.org/issues/13919

### CODE REVIEW

**Comment by m-kuhn** [comment]
Would it work to pass the filter expression directly to the QgsRenderContext instead of a filter provider?

The current approach makes sense if it is required to change the filter during a rendering process. I do not think that this is what it was designed for.

So I would propose to implement a `setFilterExpression(QgsExpression e)` or an `addFilterExpression(QgsExpression e)` on `QgsVectorLayerRenderer` instead of this approach. This fix would also solve the original issue plus result in a cleaner API.

@sbrunner do you think this makes sense or is there a requirement to have a reference to the featurefilterprovider from within the rendering process?

**Comment by m-kuhn** [comment]
@sbrunner any feedback on the comments?

**Comment by sbrunner** [comment]
I see your comment but I didn't takes time to have a look ...

**Comment by sbrunner** [comment]
> Would it work to pass the filter expression directly to the QgsRenderContext instead of a filter provider

No it wouldn't works because the filter is related to the layer.

> an addFilterExpression(QgsExpression e) on QgsVectorLayerRenderer instead of this approach. This fix would also solve the original issue plus result in a cleaner API.

That mean that we should set the filter on all the layers (we should be able to limit to queried layer) on all server call ... I'm not sure that better but it's a possible implementation.

**Comment by andreasneumann** [comment]
I will test over Christmas. I am currently very busy - trying to finish projects before the end of the year.

**Comment by nyalldawson** [comment]
@sbrunner (off topic), but do you have any ideas on why the access control test consistently fails on the Debian nightlies? Eg see http://dash.orfeo-toolbox.org/viewTest.php?onlyfailed&buildid=211966

**Comment by sbrunner** [comment]
@nyalldawson For me it's relay strange, the error message is "Error reading the project file"...

Just some questions:
* How is this report generated?
* Can it be wrong file access on the host who run the tests?

I also just rebase my branch :-)

**Comment by sbrunner** [comment]
No more needed ...

**Pull request closed without merging**
