### PR TITLE
[processing] don't set any default value for optional NODATA parameter in GDAL rastrize algorithm (fix #39752).

### LINKED ISSUE #39752: Set -a_nodata parameter of GDAL Rasterize to 'Not set'
Rasterize (vector to raster) algorithm has the -a_nodata parameter set to 0.0 by default:

https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/gdal/rasterize.py#L102

https://docs.qgis.org/3.10/en/docs/user_manual/processing_algs/gdal/vectorconversion.html#rasterize-vector-to-raster

However, being an optional parameter, I think the default should be 'Not set', just like in gdal_rasterize when it is run without -a_nodata parameter explicitly declared.

This is just because many times the vector to raster conversion has zero as a valid value, and the conversion makes it, by default, a NODATA value.

### PR DESCRIPTION
**Pull request by alexbruy**
## Description
NODATA parameter by default set to 0 and as result taken into account when GDAL command-line generated. This can lead to 
avoid unexpected conversion of valid values to nodata values.

With "Not set" by default users can apply NODATA only when needed.

Fixes #39752.

### CODE REVIEW

**Comment by alexbruy** [comment]
@nyalldawson I think here we are in the same situation as with yours #40223. Even though here NODATA is optional, it has a value and some scripts may rely on its wrong old behaviour.

**Comment by nyalldawson** [comment]
@alexbruy I agree. Are you happy with the approach implemented in the other pr for handling this?

**Comment by alexbruy** [comment]
@nyalldawson yes, I like that approach. Will update this PR when yours will be merged.

**Comment by alexbruy** [comment]
@nyalldawson PR updated to utilise new default override approach.

**Pull request merged**
