### PR TITLE
Call build_artifact_comment.yml only for PRs

### PR DESCRIPTION
**Pull request by 3nids**
This will avoid false negative workflow failures

### CODE REVIEW

**Review by m-kuhn — APPROVED** [review]
confirmed in external repo, according to @3nids

**Comment by nyalldawson** [comment]
This actually breaks the workflow -- see https://github.com/qgis/QGIS/pull/59555 .

**Comment by 3nids** [comment]
This workflow would have fail before because there is no zip available since it's on the 3.34 release branch which has no win Qt6 builds.
We can fine tune more by blacklisting some branches.

**Comment by nyalldawson** [comment]
@3nids it's missing the test failure report, that's what I'm wanting

**Comment by 3nids** [comment]
@nyalldawson the test failure is brought by the other workflow (https://github.com/qgis/QGIS/blob/master/.github/workflows/write_failure_comment.yml) which I didn't touch and I don't think they depend on each other. Or am I missing something?
Anyway, we can revert if you think that helps.

**Pull request merged**
