### PR TITLE
Set labeling widgets to horizontally expand

### PR DESCRIPTION
**Pull request by DelazJ**
It will be consistent with diagram and symbology widgets (combobox, spinbox and textbox) behavior
Before vs After screenshots

image

image

image

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Got a before/after for comparison?

**Comment by m-kuhn** [comment]
Nice. Is the *pizel size-base visibility* button left less wide on purpose.

**Comment by DelazJ** [comment]
No i didn't notice it. Most of the time, checkboxes DD button are just placed beside the checkbox they relate to and not aligned at the right of the dialog. But often the checkbox label is not that long so I guess I can right aligned this one.

**Comment by m-kuhn** [comment]
Should it look like the *Apply label text substitutes* one?

**Comment by DelazJ** [comment]
It could! There's also the "Discourage labels from covering features" option; something like below?
image

(maybe for checkboxes other than first level ones, we could rule that if its label's length > dialog width/2, we right align the DD button. Else we place a horizontal spacer at the right of the row)

**Comment by DelazJ** [comment]
A gentle ping... if ever something remains to do here. Thanks

**Pull request merged**
