### PR TITLE
Fix misbehaving tooltips/click of layer tree indicators in some styles

### PR DESCRIPTION
**Pull request by wonder-sk**
I had this problem on linux (KDE) and I think @nyalldawson has seen it on Windows (but not on Gnome)

### CODE REVIEW

**Comment by wonder-sk** [comment]
> Also... this looks like one of those 2 line fixes which cost half a day in extreme frustration!

Exactly that kind of fix! :-)

**Comment by wonder-sk** [comment]
Hmm something's going wrong with GitHub-Travis communication - no build status shown here although Travis has already finished the build (green) - https://travis-ci.org/qgis/QGIS/builds/426891392

**Comment by nyalldawson** [comment]
> Hmm something's going wrong with GitHub-Travis communication - no build status shown here although Travis has already finished the build (green) - https://travis-ci.org/qgis/QGIS/builds/426891392

I've seen this happen once or twice before, and it usually gets fixed within an hour or 2. I say just merge away!

**Comment by nyalldawson** [comment]
Confirmed fixed on Windows--thanks!

**Pull request merged**
