### PR TITLE
Fixed timing/dangling pointer error in delimited text provider

### PR DESCRIPTION
**Pull request by carolinux**
Hello! I debugged the following problem in QGIS in the delimited text provider and have a suggested fix for it:

The QgsDelimitedTextFeatureSource has a copy of the subsetExpression in the QgsDelimitedProvider. It can happen that the object in the provider gets freed and reallocated without the feature source getting updated in time, if the subset expression changes very fast. I looked though the issues in hub.qgis.org but nobody else had noticed this problem. This is reasonable, because for the problem to happen you need to have a kindof big text file and also have some script that changes the subsetString quite rapidly. I recompiled QGIS with my changes and the problem is gone. 

My fix uses the address of the pointer as the object that is passed to the feature source. This means that the changes are immediately visible to the feature source. I also modified the provider to first set the mSubsetExpression to the new one and then free the old object, but this was not the main problem.

I am available to do modifications on this PR if you have comments.

The original stacktrace is here:

```
[New Thread 0x7fff53fff700 (LWP 5690)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff60eea700 (LWP 5676)]
0x00007ffff41c1835 in QgsExpression::evaluate(QgsFeature const*) () from /usr/lib/libqgis_core.so.2.6.1
(gdb) up
#1  0x00007fff73990b58 in QgsDelimitedTextFeatureIterator::nextFeatureInternal(QgsFeature&) () from /usr/lib/qgis/plugins/libdelimitedtextprovider.so
(gdb) up
#2  0x00007fff73990dc3 in QgsDelimitedTextFeatureIterator::fetchFeature(QgsFeature&) () from /usr/lib/qgis/plugins/libdelimitedtextprovider.so
(gdb) up
#3  0x00007ffff41e904d in QgsAbstractFeatureIterator::nextFeature(QgsFeature&) () from /usr/lib/libqgis_core.so.2.6.1
(gdb) up
#4  0x00007ffff433a7c9 in QgsVectorLayerFeatureIterator::fetchFeature(QgsFeature&) () from /usr/lib/libqgis_core.so.2.6.1
(gdb) up
#5  0x00007ffff41e904d in QgsAbstractFeatureIterator::nextFeature(QgsFeature&) () from /usr/lib/libqgis_core.so.2.6.1
(gdb) up
#6  0x00007ffff434456d in QgsVectorLayerRenderer::drawRendererV2(QgsFeatureIterator&) () from /usr/lib/libqgis_core.so.2.6.1
(gdb) up
#7  0x00007ffff434558d in QgsVectorLayerRenderer::render() () from /usr/lib/libqgis_core.so.2.6.1
(gdb) up
#8  0x00007ffff4259213 in QgsMapRendererCustomPainterJob::doRender() () from /usr/lib/libqgis_core.so.2.6.1
(gdb) up
#9  0x00007ffff4259279 in QgsMapRendererCustomPainterJob::staticRender(QgsMapRendererCustomPainterJob*) () from /usr/lib/libqgis_core.so.2.6.1
(gdb) up
#10 0x00007ffff425a49b in QtConcurrent::RunFunctionTask<void>::run() () from /usr/lib/libqgis_core.so.2.6.1
(gdb) up
#11 0x00007ffff2ee1fee in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
```

### CODE REVIEW

**Comment by m-kuhn** [comment]
Would it also be possible to solve this with a QSharedPointer? http://doc.qt.io/qt-5/qsharedpointer.html
I just find it much more readable :-)

**Comment by carolinux** [comment]
will give it a shot

**Comment by carolinux** [comment]
Are you sure this can work? The problem is not that the pointer is addressed concurrently, but that the second class accesses a pointer that has already been freed by the second class. I tried to replace it with a QSharedPointer, but then I  got segmentation faults when trying to free it in the first class.  

For me the pointer to pointer has clearer semantics, even though it's a bit uglier to look at.

**Comment by carolinux** [comment]
I added a commit with what I tried with QSharedPointer. If I'm doing something wrong, please tell me. Otherwise we can just merge the 1st commit.

**Comment by wonder-sk** [comment]
Actually I think the QgsDelimitedTextFeatureSource class should have its own copy of the expression - not a pointer or pointer to pointer. Otherwise the feature source is affected by intermediate changes to the provider, which should not happen, because in such case the iterator would not return consistent results.

**Comment by carolinux** [comment]
Yep, this also makes sense!

**Comment by carolinux** [comment]
Heh, we can't copy QgsExpressions..
```
/home/carolinux/Projects/QGIS/src/providers/delimitedtext/../../core/qgsexpression.h:685:21: error: ‘QgsExpression::QgsExpression(const QgsExpression&)’ is private
     Q_DISABLE_COPY( QgsExpression )  // for now - until we have proper copy constructor / implicit sharing
```

**Comment by m-kuhn** [comment]
`QgsExpression( expression->expression() );` should work

**Comment by carolinux** [comment]
should work now

**Comment by carolinux** [comment]
comments?

**Comment by ccrook** [comment]
@carolinux I've commited a different solution, as I think this may have a memory leak with the new QgsExpressions it is creating, and also be slower as it is parsing the expression for every feature rather than using the already parsed expression.  I've put my alternative solution in as commit 308bbb66bdf31345b893cb87aabe6fd9220148c2.  What do you think?  Brilliant work tracking down this bug!

**Comment by carolinux** [comment]
Yes, this fixed the bug and is quite simpler. You are right about the memory leak of course.

**Pull request closed without merging**
