### PR TITLE
do not always use the -c flag to export vectors from GRASS

### PR DESCRIPTION
**Pull request by gioman**
## Description
While exporting GRASS vectors to a simple features format using v.out.ogr now the "-c" flag is always used, and this is not expected as it can lead to wrong/unexpected results (see below):

https://grass.osgeo.org/grass74/manuals/v.out.ogr.html

_"-c =  Also export features without category (not labeled). Otherwise only features with category are exported."_

And later:

_"By default, islands will appear as holes inside surrounding areas. To export polygons with holes into, e.g., a Esri Shapefile, and make the holes appear as filled areas, the flag -c has to be used."_

but we don't want this (at least as default and without option to choose not use this flag). Example:

buffer with the "-c" flag:

screenshot_20181105_124642

and without:

screenshot_20181105_124635

This patch add the "-c" flag as optional among the advanced export parameters.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Interesting -- do you know when the -c flag was added to QGIS? It'd be good to verify that it wasn't added as a fix to another issue which may cause a regression here.

**Comment by gioman** [comment]
@nyalldawson @luipir would you mind reopen this. Next week I should be able also to backport it.

**Comment by luipir** [comment]
reopen as requested @gioman

**Comment by gioman** [comment]
> reopened as requested @gioman

@luipir thanks.

**Comment by luipir** [comment]
@gioman I'll leave it closed if you do not fix tests (seems) affected by this PR

**Comment by gioman** [comment]
@luipir reopen please? I promise I will give this PRs the proper treatment (i.e. tests) in Coruña.

**Comment by nyalldawson** [comment]
@gioman can we close this PR, and then make a new one after Girona and you've had a chance to fix the existing tests? I'd like to keep the PR queue as short as possible to aid with speedy reviews, and if this one is still a couple of months away I'd prefer to close it for now, and revisit when you're ready to complete the work.

**Comment by gioman** [comment]
@nyalldawson this must be fixed in time for the next ltr, so before Coruña. I will work on it next week along with https://issues.qgis.org/issues/19472

**Pull request closed without merging**
