### PR TITLE
QgsMapRendererCache improvements

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR adds support for QgsMapRendererCache cache images to be dependent on either no layers or multiple layers. In some cases the render result for a layer may depend on more than one layer.

This changes QgsMapRendererCache to use "cache keys" instead of layer ids to identify images within the cache. When setting an image inside the cache, a new list parameter is used to specify all layers on which
that image depends.

I've also added unit tests for the class, and tweaked the api to make protected members private as the class is not intended to be subclassed.

### CODE REVIEW

**Comment by NathanW2** [comment]
Oh fancy. Nice work.

**Comment by NathanW2** [comment]
Render times for the render god!

**Review by wonder-sk — COMMENTED** [review]
hi @nyalldawson - nice stuff

Few questions:
- what is the main driver for dependencies on multiple layers? :-)
- do you have a use case of having cached images not dependent on any layers? If not, I thought we could generate cacheKeys automatically...
- do we need to care about the order of dependent layers? (i.e. if their order has changed, we still need to invalidate the cache?)

In terms of implementation, in setCacheImage() I would just suggest to use layer pointers to dependent layers rather than layer IDs (cleaner API and internally the storage uses QPointer anyway).

Btw. renderer cache is somewhere on the top of my list to get rid of QgsProject::instance() and I will be looking into that soon...

**Comment by nyalldawson** [comment]
> what is the main driver for dependencies on multiple layers? :-)

Caching an image of the labeling results - coming soon

> do you have a use case of having cached images not dependent on any layers? If not, I thought we could generate cacheKeys automatically...

Not really... but I do have a use case for setting my own cache key (`static const QString LABEL_CACHE_ID = QStringLiteral( "_labels_" );`)

> do we need to care about the order of dependent layers? (i.e. if their order has changed, we still need to invalidate the cache?)

I don't!

> In terms of implementation, in setCacheImage() I would just suggest to use layer pointers to dependent layers rather than layer IDs (cleaner API and internally the storage uses QPointer anyway).

ok, will do!

**Comment by nyalldawson** [comment]
> In terms of implementation, in setCacheImage() I would just suggest to use layer pointers to dependent layers rather than layer IDs (cleaner API and internally the storage uses QPointer anyway).
> Btw. renderer cache is somewhere on the top of my list to get rid of QgsProject::instance() and I will be looking into that soon...

Done - also no more QgsProject use here

**Review by wonder-sk — APPROVED** [review]
QgsProject is gone - awesome! :-)

I think the use of QPointer<X> as a key for QHash/QSet is a bit dangerous construct because it it not immutable, but I am happy to address it later myself (e.g. using dump pointer + listening to willBeDeleted()). See https://git.merproject.org/mer-core/qtbase/commit/3b9629e8bdbf23bb793c88f967b2cfe2b8256278?view=parallel

**Comment by nyalldawson** [comment]
> I think the use of QPointer as a key for QHash/QSet is a bit dangerous construct because it it not immutable, but I am happy to address it later myself (e.g. using dump pointer + listening to willBeDeleted()). 

I *think* it's safe here because we actually don't care if the layers get removed in the meantime. We're just using the sets to detect whether we need to disconnect/connect from a layer - and we'll never be doing that if the layer is gone anyway.

But your point still stands!

**Comment by wonder-sk** [comment]
> I think it's safe here because we actually don't care if the layers get removed in the meantime. We're just using the sets to detect whether we need to disconnect/connect from a layer - and we'll never be doing that if the layer is gone anyway.

True - I was mainly concerned about possible internal corruption of the hash table... will check later.

**Comment by nyalldawson** [comment]
@wonder-sk am I right in concluding that everywhere we store a layer id to later reference a layer should instead be swapped to a QPointer to the layer?

**Comment by wonder-sk** [comment]
> am I right in concluding that everywhere we store a layer id to later reference a layer should instead be swapped to a QPointer to the layer?

That's correct. This will make us more independent from QgsProject. It just gets a bit tricky when layers should be keys in QHash or QMap - as we have seen above :)

**Pull request merged**
