### PR TITLE
Port of WMTS preview / XYZ tiles to QGIS 2.x

### PR DESCRIPTION
**Pull request by wonder-sk**
...with no API breaks

### CODE REVIEW

**Comment by nyalldawson** [comment]
Wow... impressive!

**Comment by NathanW2** [comment]
Heck yeah!

**Comment by nyalldawson** [comment]
@wonder-sk I think part of 23909a123ac34b68d0e9e7163fceda1e440753c9 was omitted from this PR. Was that intentional? I'm seeing lots of crashes when rendering is cancelled on master_2 and I suspect it's the same issue as that commit addressed (unfortunately I'm only getting them at a workplace with locked down Windows builds and no means of debugging).

**Comment by nyalldawson** [comment]
Follow up - I backported the missing part in https://github.com/qgis/QGIS/commit/dfeb663c39bf87bf5f99da5363fb3c9796e06394 . Let me know if there's an issue with that!

**Comment by wonder-sk** [comment]
Oops... That was not intentional - I think when backporting I have initially missed one commit, which lead to few conflicts. I have reviewed the backported code, but that one must have slipped... thanks for the fix!

**Pull request merged**
