### PR TITLE
QgsFeatureListComboBox nullRepresentation instead of hardcoded "NULL"

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #19901 - Relation Reference Widget: Representation for NULL values is not respected

### CODE REVIEW

**Comment by elpaso** [comment]
@m-kuhn can you please have a look? 
The test was never added to CMakeList and there were some TODOs left.

**Comment by m-kuhn** [comment]
Looks good to me.

I still do not completely understand if the null representation is intended as human readable string or as a magic value (which needs to be configurable because there's a risk of collision with real values).

I was assuming the latter so far because for representation we can just use the default translation engine in QGIS and I don't see why it needs to be translated, that's why I deliberately left it out here. Maybe some people just don't like the string `null`. But then I wonder if an option is the right approach to fix this.

**Comment by elpaso** [comment]
@m-kuhn thanks for the review, according to the documentation
```
    /**
     * This string is used to represent the value `NULL` throughout QGIS.
     *
     * In general, when passing values around, prefer to use a null QVariant
     * `QVariant( field.type() )` or `QVariant( QVariant::Int )`. This value
     * should only be used in the final presentation step when showing values
     * in a widget or sending it to a web browser.
     */
    static QString nullRepresentation();
```
I believe that this string has to be used for presentation only, to show the null value to the user, internally we should use a null QVariant and then delegate to the providers how to really convert this value to something meaningful for their particular storage.

There are actually users who prefer to see a blank widget instead of `NULL`, while this makes virtually impossible to distinguish a (speaking SQL now) `NULL` from an empty string, I'm afraid this choice comes from the fact that when you focus in a text widget that has a `NULL` inside, you need to delete the `NULL` string before typing anything, but this is a separate issue.

**Comment by m-kuhn** [comment]
> There are actually users who prefer to see a blank widget instead of NULL, while this makes virtually impossible to distinguish a (speaking SQL now) NULL from an empty string, I'm afraid this choice comes from the fact that when you focus in a text widget that has a NULL inside, you need to delete the NULL string before typing anything, but this is a separate issue.

That's exactly my point, just with a slightly different approach. An isolated issue was escalated to an option which now has to be respected also in places where this issue is not present.

**Pull request merged**
