### PR TITLE
fixed wrong item order in add field dialog, causing wrong focused widget

### PR DESCRIPTION
**Pull request by uclaros**
## Description
When opening the Add Field dialog (New field ctrl+W) the focused widget is the OK button instead of the Name field (first widget in Tab Order) requiring the user to use the mouse to select the name field or press tab until the name field is selected. 
This functionality was not intended but caused by the weird layout item ordering in the ui file (maybe a QT bug?).
The diff looks more complicated than it actually is, it only puts the `<item row=...> ... </item>` blocks in ascending order, which fixes the bug.
I guess this could also be backported.

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes

- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them

- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [x] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by nyalldawson** [comment]
Instead of rearranging the xml (which is fragile, because it's likely to regress as soon as someone edits the form), a better solution would be to explicitly set the focused widget in the dialog code.

E.g. adding something like

    mTypeName->setFocus();

to the end of QgsAddAttrDialog::QgsAddAttrDialog in qgsaddattrdialog.cpp should work.

**Comment by nyalldawson** [comment]
Sorry, that should have been `mNameEdit->setFocus();`

**Comment by uclaros** [comment]
That's what I thought to do at first, but after checking a few dialog constructors saw that the norm is to rely on the .ui file taborder for the initial focus. Then I figured why this dialog was misbehaving and ended up with this. I think that either qtdesigner should not output scrambled layout item order, or that the scrambled order should not matter, as it does not matter on other forms, but those are qt's issues, not qgis'.
Anyway, I could do both for completeness sake, but then should we explicitly define focus on other constructors too just in case their forms are edited and qt misbehaves?

**Comment by nyalldawson** [comment]
> should we explicitly define focus on other constructors too

Yes -- I think it's a good move. Apart from avoiding accidental breakage if qt designer silently moves things around, it also would cause a compilation failure if someone removes the widget. And then they'd have to think about what the logical default widget should be and fix things right then in order to get compilation working...

**Comment by uclaros** [comment]
OK, I'm commiting this now and I'll try to gather dialogs that need explicit setFocus when I got time and issue a PR.

**Comment by nyalldawson** [comment]
Thanks!

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
