### PR TITLE
[symbology] Improve rendering of selected SVG markers

### PR DESCRIPTION
**Pull request by nirvn**
## Description

A picture worth a thousand words:
image

### CODE REVIEW

**Review by nyalldawson — COMMENTED** [review]
One thing that I don't think is taken into account here is data defined paths. If I had marker with the default path having fill param, but a couple of features having an override to a non-parameterised svg, then by my understanding of this change we won't see the selected state for those features.

I'd suggest we handle this simply by detecting if data defined path is set, and if so, then just use the old approach of the yellow highlight box...

**Comment by nirvn** [comment]
What about rasterizing & using the image operation when data defined path is detected? I'd prefer that over the rectangle.

**Comment by nyalldawson** [comment]
That works too!

**Comment by nirvn** [comment]
@nyalldawson , comments addressed.

**Review by nyalldawson — APPROVED** [review]
Let's give it a try!

**Pull request merged**
