### PR TITLE
Range widget: Remove null representator during editing

### PR DESCRIPTION
**Pull request by signedav**
It has been anoying to have the null representator as text in the SpinBox althoug the SpinBox does not accept strings. When clicking on it, you where in the middle of the null representator text.

Getting focus (by mouse) on null:
getting_focus_on_null

Getting focus (by mouse) on value:
getting_focus_on_value

Since the QSpinBox only accepts numeric values except the `SpecialValueText` the sollution has to be with `SpecialValueText`.

Now it does clear the field on mouseClick and gets the value back on leaving. Here we don't have the problem that the field could contain empty strings as values and we need to make a difference to NULL.
getting_focus_new

If this approach is okay, I will seperate the `QgsSpinBoxLineEdit` to seperate files and add some testings.

- [x] Seperating Files
- [ ] Testing

This fixes #20153

PS. When the TextEdit widget is multiline, then it doesn't make the selection (because it's no QgsFilterLineEdit). Do you agree, that the same implementation (like in single line TextEdit widget) would make sence here?

### CODE REVIEW

**Comment by luipir** [comment]
@m-kuhn I'll give a try

**Comment by luipir** [comment]
hmmmm... stange build (I build the complete branch without cherry-picking), I created a point layer where no point are shown after adding them! btw it's not the focus of the PR.

regarding the PR, I can see that Text field is erased because is automatically selected (if NULL) and when the user start to write NULL is removed, BUT if the user do doubleclick, the NULL string remain as part of the text. BTW can be acceptable!
The same happen with SpinBoxes, but, because of they are integer (or float) the NULL string create and invalid number and the value is reset to NULL when the focus change.
@signedav try to navigate and change values using tab+arrows, the behavious is different than changing focus with mouse.

**Comment by nyalldawson** [comment]
Better add some unit tests for these changes --- these classes are super-fragile and there's a lot of complex logic in them.

I'm still inclined to think a better long-term solution would be to completely remove the special value text and just paint the "null" string on top of the widget (in the paintEvent) when it's set to a null value.

**Comment by signedav** [comment]
Thanks for the feedback @luipir 

> regarding the PR, I can see that Text field is erased because is automatically selected (if NULL) and when the user start to write NULL is removed, BUT if the user do doubleclick, the NULL string remain as part of the text. BTW can be acceptable!

I just had it in the gifs to demonstrate the difference to the text-edits. Text-edits itself are not part of this PR but of #8114 instead. Because you need to make a difference between empty string and NULL. That's why you should be able to edit it to "NULL" (and go into the string by double click). But because you need to do that rarely and mostly just want to fill up with values, I made the automatic select all on getting focus. But I agree that here is potential to improve. But lets focus on the Spinbox.

> The same happens with SpinBoxes, but, because of they are integer (or float) the NULL string create and invalid number and the value is reset to NULL when the focus change.

Exactly. But on clicking in it it does not select the NULL-string, but it empties the field.

> try to navigate and change values using tab+arrows, the behavious is different than changing focus with mouse.

You are right. I would have to implement the emptiing for the getting focus by tab as well.

Beside I will check out the idea of @nyalldawson - I would like not to misuse the SpecialValue and use a kind of a placeholder text...

**Comment by signedav** [comment]
The behavior is now, that on getting focus (no matter if tab or mouse click) the text changes from "NULL" (NullRepresentation) to "". On leaving the field, it changes back to "NULL". Like showed in the GIF above. Can you check again @luipir ?

I added some tests @nyalldawson - I like the idea just to paint the placeholder on top, but I would like to head for it another time and keep at least this improvement for the moment.

**Comment by luipir** [comment]
> The behavior is now, that on getting focus (no matter if tab or mouse click) the text changes from "NULL" (NullRepresentation) to ""

not confirmed in... for text, remain NULL and can be edited at the end of NULL strin gif user double click. In resume, nothing seems changed.
ps. sorry for my slowness, I'm in hardware works these days.

**Comment by luipir** [comment]
btw, I'm not a user used to insert data, For me can be merged. I would ask better to some power user used to insert data. The issue that I find could be so minor that it does not justify more fix work.

**Comment by signedav** [comment]
Thanks for the feedback @luipir

> for text, remain NULL and can be edited at the end of NULL strin gif user double click. In resume, nothing seems changed.

Yes. This PR only changes the behaviour of the spinbox and not of the text edit. On the text edit the behaviour is like you described and implemented in #8114.

Because you need to make a difference between empty string and NULL, you should be able to edit it to "NULL" (and go into the string by double click) or delete NULL and store as an empty string.

**Pull request merged**
