### PR TITLE
Switch 3D render policy from "Always" to "On Demand"

### LINKED ISSUE #25390: QGIS 3D uses a lot of CPU even when idle
Author Name: **Klas Karlsson** (@klakar)
Original Redmine Issue: [17493](https://issues.qgis.org/issues/17493)
Affected QGIS version: master
Redmine category:3d

---
As soon as I open a 3D window, my fans in the computer winds up. Even if i do nothing more, they stay on, and CPU load increase a lot.

As soon as I close the 3D window, CPU load returns to normal.

This is not a "crashing" issue, or a "freezing" issue. It's just annoying that it can "steal" this much resources just by opening a window in QGIS.

It doesn't seem to matter what layers are active or involved, resources spike no matter what.

Tested on Windows10 and Linux (Manjaro)

### PR DESCRIPTION
**Pull request by wonder-sk**
Fixes #25390

The on demand policy lowers the load quite significantly (top on my laptop show the %cpu went from ~300% to ~50% when the 3D scene is idle).

Previously when I tried to enable the on demand policy in Qt 5.9.0, things were not getting any better, but it seems things got fixed later in Qt 5.9.5: https://bugreports.qt.io/browse/QTBUG-55109

I have not found any negative effects in my testing - but we should do some more extensive tests before backporting to 3.18 and 3.16.

### CODE REVIEW

**Comment by nyalldawson** [comment]
cool!

**Comment by roya0045** [comment]
Neat! Thanks for the fix!

**Comment by wonder-sk** [comment]
This just needs fixing render captures in auto-tests... not completely stale :-)

**Comment by NEDJIMAbelgacem** [comment]
Hi @wonder-sk 
I think we need to switch back to RenderPolicy::Always whenever we need to do a screen capture.
Can you cherrypick from https://github.com/NEDJIMAbelgacem/QGIS/commit/a225666ce4436c015af0458392250842a0a8e2f1 ?

**Comment by wonder-sk** [comment]
Thanks @NEDJIMAbelgacem for finishing this!

**Pull request merged**
