### PR TITLE
Don't force promote point layers to multipoint when running clipping/subtraction style algorithms

### PR DESCRIPTION
**Pull request by nyalldawson**
There's no way a point can become multipoint as a result of a clip or subtraction

### CODE REVIEW

**Review by rouault — APPROVED** [review]

**Comment by agiudiceandrea** [comment]
@nyalldawson, it seems to me the "Native CLIP function" https://github.com/qgis/QGIS/issues/49456 may be related to this PR.

**Comment by nyalldawson** [comment]
@agiudiceandrea is the clip resulting in an empty multipoint?

**Comment by Jrm-Bghn** [comment]
@nyalldawson there is no layer written in the output, not even an empty multipoint layer.

**Comment by agiudiceandrea** [comment]
> @agiudiceandrea is the clip resulting in an empty multipoint?

@nyalldawson, no. With QGIS 3.22.9/3.26.1, the Clip results in an empty Point (Shape Type: 1) Shapefile layer recognised by QGIS as "Point (Point)". The resulting empty layer is not automatically added to the map after the algorithm runs.
With QGIS 3.22.0, the Clip results in a MultiPoint (Shape Type: 8), recognised by QGIS as "Point (MultiPoint)", containing the clipped points.
The Clip algorithm input layer is a Point (Shape Type: 1) Shapefile layer ("Point (Point)").



> there is no layer written in the output, not even an empty multipoint layer.

@Jrm-Bghn, are you sure? The layer is not automatically added to the map, but it is actually created.

**Comment by agiudiceandrea** [comment]
@nyalldawson, it seems to me the issue is due to the fact that the Clip algorithm uses the `QgsOverlayUtils::sanitizeIntersectionResult` function https://github.com/qgis/QGIS/blob/e593fde4dc2a35a28a0ca95c0490a0414847c17d/src/analysis/processing/qgsalgorithmclip.cpp#L211-L212 which always returns a multi-part geometry https://github.com/qgis/QGIS/blob/e593fde4dc2a35a28a0ca95c0490a0414847c17d/src/analysis/processing/qgsoverlayutils.cpp#L77-L79 converting the input clipped Point geometries to MultiPoint geometries which cannot be written to a Point Shapefile layer.

**Comment by agiudiceandrea** [comment]
Hi @nyalldawson, any news about the issue https://github.com/qgis/QGIS/issues/49456?

**Pull request merged**
