### PR TITLE
Fix dragging 3D view with mouse when camera is far

### PR DESCRIPTION
**Pull request by wonder-sk**
Before, when looking at a greater area (e.g. spanning 200km or more),
dragging 3D view with left mouse button would not work at all. Only
when zoomed in more it would start working again.

This was cause by unproject() method in Qt having tolerance against division
by zero very high. Lowering the tolerance by few magnitudes fixed the problem (1e-5 to 1e-10)

cc @nirvn

### CODE REVIEW

**Comment by Gustry** [comment]
@wonder-sk For me, it seems the reverse, the camera is always far, I can't zoom in but I can pan the 3D canvas.
screen shot 2017-10-12 at 19 41 26

I used this great dummy layer: https://github.com/inasafe/inasafe/blob/develop/safe/test/data/gisv4/exposure/buildings.geojson

Any idea? Thanks

**Comment by wonder-sk** [comment]
Hi @Gustry that's a separate issue - the 3D view currently does not work well when project CRS is unprojected lat/lon like WGS 84. Just set project's CRS to a projected CRS that has meters/feet as map units (e.g. web mercator) and it should work...

**Comment by Gustry** [comment]
Hum, sorry, I was pretty I did it before. Maybe another dataset. Thanks

**Comment by nirvn** [comment]
Thanks a bunch. Gone are the days of undocked 3D view panels to pan with the keyboard!

**Comment by nirvn** [comment]
@wonder-sk , just tested now, I confirm it fixes the stated issue.

**Pull request merged**
