### PR TITLE
Enable travis tests for osx

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by dakcarto** [comment]
@m-kuhn Nice! Btw, I was planning on a `qgis3-travis` formula in [qgis/homebrew-qgisdev](https://github.com/qgis/homebrew-qgisdev), which would allow us to run CTest within the formula, and potentially bottle the result (if needed, like for separating the build from the CTest run to overcome timeouts, etc... maybe, could be tricky).

Also, this would allow us to locally test the exact same formula that Travis is using, prior to deploying it to the Travis setup.

The only small glitch I see is how to pass excluded tests into the formula, though it should be doable via a `--with-key=value` option parameter, like would be needed to specify the checked-out branch.

For example, the whole Travis setup (minus some Homebrew uninstalls due to Travis defaults) would basically be reduced to:

```
brew install qgis/qgisdev/qgis3-travis \
--with-branch=<somebranch> \
[--with-test --with-excluded-tests=<somelist>] \
[--with-bottle]
```

Anyhow, something to experiment with, as running tests within the Homebrew build environment is more efficient and less error prone, I believe.

**Comment by dakcarto** [comment]
Btw, I was waiting until we have a stable `qgis3-dev` before embarking on a `qgis3-travis` formula, which I think is reasonable to start now.

**Comment by m-kuhn** [comment]
I think one thing is the CI testing part: test each push and each pull request. This will need to be done on this repository.

What your idea here is is more inline with continuous delivery, correct? For this we could build the nightly bottles from the homebrew repository with a cron job (if a after_success bottle deployment is too expensive).

**Comment by dakcarto** [comment]
@m-kuhn wrote
> What your idea here is is more inline with continuous delivery, correct? For this we could build the nightly bottles from the homebrew repository with a cron job (if a after_success bottle deployment is too expensive).

Actually, both. The main intent is to run tests (CI, a `qgis3-travis` formula), the second would be to bottle (CD), probably using a [Travis "cron" job](https://docs.travis-ci.com/user/cron-jobs/) for nightlies. Granted, the `qgis3-dev` formula may be a better candidate for CD.

**Comment by m-kuhn** [comment]
I think I understand now.
In qgis/QGIS, there should be only minimal logic to trigger a Formula build from within qgis/homebrew-qgisdev? With the advantage that it would be possibile to trigger the same setup locally.

What I wonder

 * will this require a second download of the git repo (after all, the complete source is already on the machine by the time the travis scripts start)?
 * how easy will it be to test new dependencies from within a pull request? right now you can just add an additional `brew install` directive directly within a pr.

**Comment by dakcarto** [comment]
@m-kuhn wrote
> will this require a second download of the git repo (after all, the complete source is already on the machine by the time the travis scripts start)?

There are several workarounds available for bypassing a download that I have used in the past. One is to use a [dummy download package](https://github.com/OSGeo/homebrew-osgeo4mac/blob/master/Formula/ecwjp2-sdk.rb#L22) that installs a single file (so no errors are thrown). Then, simply symlink into the brew `buildpath` the local directory you need to work with. This is how I now work with proprietary packages that one needs to login and download first, before installing the formula. This is also how "vendored" resources are downloaded and built within a master build directory, albeit without the symlinking. 

> how easy will it be to test new dependencies from within a pull request? right now you can just add an additional brew install directive directly within a pr.

Hmm. That's an interesting advantage with the current setup that I have not considered. Seems that as long as `brew update` is run initially, then not again (and auto-update turned off), whatever one `brew install`s after that, but prior to running `qgis3-travis` _should_ be roughly the same (since any duplicate dependencies would have already been met).

Another, probably better, option is to _not_ host the `qgis3-travis` formula at qgis/homebrew-qgisdev, but instead have it within the source tree at `<qgis-src>/ci/travis/osx/qgis-travis.rb`, allowing its editing to be done with a main QGIS repo PR as well. Then, install it via a local URL instead (see SPECIFYING FORMULAE section of `man brew`). The disadvantage of installing from a URL is that the formula doesn't get updated from Homebrew, but this is a moot point for how the formula is used.

**Comment by m-kuhn** [comment]
> Another, probably better, option is to not host the qgis3-travis formula at qgis/homebrew-qgisdev, but instead have it within the source tree at <qgis-src>/ci/travis/osx/qgis-travis.rb, allowing its editing to be done with a main QGIS repo PR as well.

This sounds like an interesting approach. I am just not enough into the whole homebrew concepts to do it, but if you want to jump in, it's more than welcome!

> Then, install it via a local URL instead (see SPECIFYING FORMULAE section of man brew). The disadvantage of installing from a URL is that the formula doesn't get updated from Homebrew, but this is a moot point for how the formula is used.

What's the reason we need to install it? Can we not run the tests from the build dir? Or is it for bottling?

By the way, I am currently experiencing timeouts
https://github.com/m-kuhn/QGIS/pull/47 :
https://travis-ci.org/m-kuhn/QGIS/builds/190067690

I recently had contact with the travis team and it might be possible to increase the build times, which could potentially also help us to deploy packaged versions. In combination with ccache that could be a nice solution.

**Comment by dakcarto** [comment]
@m-kuhn wrote
> What's the reason we need to install it? Can we not run the tests from the build dir? Or is it for bottling?

Sorry, that's a 'brew install' not a 'make install'. There is no 'brew build' sub command, so any build and test steps need to be inside the 'def install' method, regardless of whether anything ever gets installed.

After some more thought, I really think that any deployment should be part of qgis3-dev crib job, not as part of standard Travis CI for the main repo.

**Pull request closed without merging**
