### PR TITLE
enhance the GetFeatureInfo response with the option to configure it usin...

### PR DESCRIPTION
**Pull request by aperi2007**
...g a css (see the qgis_getfeatureinfo_response.css) for add a logo or configure the rendering of tables.
sample_response

### CODE REVIEW

**Comment by strk** [comment]
is this branch still useful ?

**Comment by aperi2007** [comment]
I don't know.
Certainly this patch is useful and us and it is used in our qgis-server instance. I apply it constantly on every new internal version of qgis-server that we adopt.
But see-ing the time elapsed of this pull I guess it could be reasonably close as rejected.

**Comment by m-kuhn** [comment]
I like the idea and replacing hardcoded style information with CSS is definitely nice anyway.
The main point was about the hardcoded path to the CSS file as far as I can see.
Would it be possible to adapt that?

**Comment by elpaso** [comment]
I'm not sure that having style information inside the core is a good idea. CSS (inline or href'ed to an external file) can be easily added with a QGIS server plugin, see for example: http://www.itopen.it/qgis-server-getfeatureinfo-with-style/

**Comment by elpaso** [comment]
BTW, having templates for the response might be good. But this can also be achieved through python plugins.

**Comment by m-kuhn** [comment]
Can the CSS classes easily be added externally without reparsing the HTML? Wouldn't it be nice to have these available as "styling hooks" out of the box?
Should python be a requirement for styling?

**Comment by elpaso** [comment]
If we are going to place this in the core, I would rather prefer full templating (mapserver-like). Also keep in mind that templating can also be done client-side (like QWC does). 
I don't see this feature as a priority, because there are right now many other ways to reach the same goal, but I'm not against it if somebody is willing to develop it. Of course I've no problem at all with using python plugins for this kind of output processing ;-)

**Comment by m-kuhn** [comment]
Can we make a point here.
Which parts of this PR are acceptable, what needs to be done and what does not have any chances of getting accepted.

 * Classifying HTML entities: seems to be good even for client side styling to me.
 * Linking external CSS files: is there a way to integrate this in an acceptable manner or not?

**Comment by elpaso** [comment]
As long as you have a single table, you don't need any class to style it, it will probably go into an (I)FRAME and it will catch the CSS rules without conflicts.
IMHO this PR has to be rejected completely, hardcoding a CSS and distributing it is not the way to go.
If (and I'm not convinced it worths) you really want to add styles-support in the getfeatureinfo HTML response you should probably add some config options to the OWS per-layer configuration for adding an href or a code block for custom inline CSS, or both.
Or even better, add a templating system to fully configure the HTML response.
If there is such demand and you/someone is willing to implement it, a QEP might be the right place to discuss a proposal.

**Comment by m-kuhn** [comment]
@mhugent you haven't been active on this pull request for over a year. I assume you are quite busy. Would you like to give it a final review or do you prefer to hand over the lead for this pull request to @elpaso ?

**Comment by elpaso** [comment]
Trying to summarise:
The purpose of this PR was to add (CSS) style to GetFeatureInfo response, which is a good thing.
This is desired and can be achieved right now with a simple Python plugin, the drawback is that this is not easily configurable from a GUI (a simple desktop plugin would do it quite easily though) and that it does require a few lines of programming and python plugin support on the server.

This requirement could be fulfilled in several ways (not mutually exclusive):
* add a line edit field for an external CSS to every OWS layer
* add a text input area for inline CSS to every OWS layer
* add a full templating system for the response (UNM Mapserver-like), here too, we could have a filesystem-based  template with configuration through convention (filename), a `QFileDialog` or an inline text-area or both

Please note that the CSS configuration could be per-project or per-layer (or both, with the latter being an override for the project-wise configuration).

To discuss what is the best approach for this new feature I would suggest to create a QEP with one or more proposed implementation and decide together what would be the best approach for QGIS.

If there are any organizations willing to sponsor this development, they would be of course more than welcome.

Thanks to @aperi2007 for bringing up this topic: feel free to open a QEP to further discuss this.

**Pull request closed without merging**
