### PR TITLE
[FEATURE] Allow layers to be automatically refreshed at a specified interval

### PR DESCRIPTION
**Pull request by nyalldawson**
This allows users to set a timer interval in layer properties for individual layers. These layers will be automatically refreshed at a matching interval.

Canvas updates are deferred in order to avoid refreshing multiple times if more than one layer has an auto update interval set.

Additionally, logic has been added to skip any auto redraws of the canvas while the canvas is already being redrawn. This avoids issues caused by setting a layer auto refresh to a shorter time than is required to redraw the canvas.

### CODE REVIEW

**Comment by nirvn** [comment]
Nice. Time to resurrect your game-in-QGIS contest! :)

**Comment by nyalldawson** [comment]
Video demo: https://www.youtube.com/watch?v=TQTfpiyUwXk&feature=youtu.be

**Comment by nirvn** [comment]
@nyalldawson , cool video -- I'm thinking automatic refresh + control through @wonder-sk 's legend widget feature, that'd be pretty cool. 

Live display on QGIS of animal through GPS collars in protected areas... endless possibilities :)

**Comment by timlinux** [comment]
👍 Great stuff thanks @nyalldawson !

**Comment by nyalldawson** [comment]
Just added unit tests covering this. The QgsMapCanvas unit tests make me feel ill... but honestly I can't find any other way to reliably test this behaviour :'(.

**Pull request merged**
