### PR TITLE
adding WITH_CLANG_TIDY, so you can build without it even if installed

### PR DESCRIPTION
**Pull request by rduivenvoorde**
## Description
As soon as you have clang-tidy installed, your build will become MUCH much slower, and you will have a lot of warnings like:

`[  4%] Building CXX object src/core/CMakeFiles/qgis_core.dir/composer/qgscomposermapitem.cpp.o
/usr/lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h:102:3: error: support for type '__float128' is not yet implemented [clang-diagnostic-error]
  abs(__float128 __x)
  ^
/usr/lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h:102:18: error: support for type '__float128' is not yet implemented [clang-diagnostic-error]
  abs(__float128 __x)`

So: there is no way to speed up your build then uninstalling clang-tidy again.

This flag WITH_CLANG_TIDY defaults to False so you can choose to build with or without it.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rduivenvoorde** [comment]
The above patch is (I think) cleaner then one which was proposed by @m-kuhn. 
His proposal on irc was:

```
####################################################
# clang-tidy
SET (WITH_CLANG_TIDY FALSE CACHE BOOL "Use Clang tidy")
IF (WITH_CORE)
  FIND_PROGRAM(
    CLANG_TIDY_EXE
    NAMES "clang-tidy"
    DOC "Path to clang-tidy executable"
    )
  IF(NOT CLANG_TIDY_EXE)
    MESSAGE(STATUS "clang-tidy not found.")
  ELSE(NOT CLANG_TIDY_EXE)
    MESSAGE(STATUS "clang-tidy found: ${CLANG_TIDY_EXE}")
    IF(WITH_CLANG_TIDY)
      SET(DO_CLANG_TIDY "${CLANG_TIDY_EXE}" "-checks=*,-clang-analyzer-alpha.*,-cppcoreguidelines*,-readability-implicit-bool-cast,-llvm-include-order,-cert-err58-cpp,-modernize-pass-by-value,-google-readability-braces-around-statements,-modernize>
    ENDIF(WITH_CLANG_TIDY)
  ENDIF(NOT CLANG_TIDY_EXE)
ENDIF (WITH_CORE)

#############################################################
```

IF for one or other reason this is better, let me know I'll do another PR and drop this one

**Comment by m-kuhn** [comment]
@rduivenvoorde your version looks better than the one I proposed.
I guess you tested this and it works for you?
If yes, let's merge

**Comment by rduivenvoorde** [comment]
@m-kuhn Yep, tested. Will merge when all checks are done.

**Comment by m-kuhn** [comment]
@rduivenvoorde FYI, the code_layout test was broken for a different reason, that's fixed already.

**Comment by nyalldawson** [comment]
Well, you CAN just clear the clang-tidy path. That's what I do.

**Comment by m-kuhn** [comment]
What I like about it is, that it's opt-in and doesn't just depend on things being around or not.
What I would like to see is MARK_AS_ADVANCED.

**Comment by rduivenvoorde** [comment]
Argh, added advanced, then tried to squash and push, an got in git problems...

Will close this one and do one again...

**Pull request closed without merging**
