### PR TITLE
Don't show system notifications for short tasks

### PR DESCRIPTION
**Pull request by nyalldawson**
Too annoying! Otherwise we spam notifications for very short tasks like layer feature count updating.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Oops can't backport this one...

**Comment by nirvn** [comment]
+1 , that's most welcome. Feature count notifications popping up were irritating.

10sec is a good threshold. Good to merge.

**Comment by nirvn** [comment]
Having second thoughts on this 10sec value. Could we lower it to 5sec to start with and see how that goes?

**Comment by Gustry** [comment]
That's much better in the DB Manager for some simple SELECT queries.

**Comment by nyalldawson** [comment]
@nirvn 

> Having second thoughts on this 10sec value. Could we lower it to 5sec to start with and see how that goes?

Done

**Comment by nirvn** [comment]
@nyalldawson , thanks.

**Comment by nyalldawson** [comment]
Unrelated test failure (grrr Travis is super sensitive lately!)

**Pull request merged**
