### PR TITLE
Distance within bug 45352

### PR DESCRIPTION
**Pull request by strk**
Supersedes #46429 -- continuation of #45384 (rebased to current master branch)

### CODE REVIEW

**Comment by strk** [comment]
@nyalldawson in this PR I've added testing for both same CRS and different CRS. I'm passing the distance in TARGET layer units (10 when the target is in 3857 CRS, 1e-6 when target is in 4326 CRS).

With these parameters my test still works without your commit, internally performing these transformations:

When the target is in 4326:
```
src/core/qgsfeatureiterator.cpp:144 : (updateRequestToSourceCrs) [0ms] DistanceWithin params in TargetCRS: dist=9e-05 geom=LineString (0 0, 0.00898315284119522 0.00898315280439165)
src/core/qgsfeatureiterator.cpp:152 : (updateRequestToSourceCrs) [0ms] DistanceWithin params in SourceCRS: dist=10.0188 geom=LineString (0 0, 1000.00000000000011369 999.99999999983197085)
```

When the target is in 3857:
```
src/core/qgsfeatureiterator.cpp:144 : (updateRequestToSourceCrs) [0ms] DistanceWithin params in TargetCRS: dist=10 geom=LineString (0 0, 1000 1000)
src/core/qgsfeatureiterator.cpp:152 : (updateRequestToSourceCrs) [0ms] DistanceWithin params in SourceCRS: dist=8.98315e-05 geom=LineString (0 0, 0.00898315284119521 0.00898315280439165)
```

Can you think of a way to prove the automatic transformation wrong ?

**Comment by strk** [comment]
Part of the problem highlighted by @nyalldawson is also in the user expectation. When a user wants to extract features which are "within" a given distance, she doesn't really specify how to compute those distances. Should spheroid distance be used ? Or cartesian/flat one ? Empirically I found that the units passed to the algorithm for the "distance" value are in the *target* layer units,  is there any way in the GUI to specify the user wants different units ? And how is a conversion done in that case ?

**Comment by strk** [comment]
@nyalldawson I've pushed a test using a very long target line defined in srid=3857 (pseudo webmercator) with a reference which falls at about 5 meters from it. It might be what we are after but it's not even easy to tell what the user wants in that case. I'm letting it fail for now to later check if your commit in #46429 changes the results, but I'm not even sure it does.

Here is how QGIS renders the "SRID=3857" target (line) and reference (point) layers when using the different map projections:

Using 3857 map projection:
map-rendered-3857

Using 4326 map projection:
map-rendered-4326

In the test I'm finding that running ExtractWithinDistance fetching the target in 3856 CRS and the reference in 4326 CRS, and specifying 10 as the distance (the algorithm considers the distance as being expressed in _target_ CRS) results in the line NOT being returned.

**Comment by strk** [comment]
Nyall it looks like your commit does fix the test which otherwise fails here. I'll wait for CI to complete to show the failure and then push your commit here \o/

**Comment by m-kuhn** [comment]
@strk I'd prefer to choose myself where I want to review.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Manually backported in https://github.com/qgis/QGIS/pull/47076

**Comment by strk** [comment]
Thanks @nyalldawson -- do #47076 require review/approval ? I see it queues multiple changes

**Pull request merged**
