### PR TITLE
Move info bar creation before welcome page (fixes crash on start)

### PR DESCRIPTION
**Pull request by wonder-sk**
Welcome page creates QgsTemplateProjectsModel which adds a file watcher which triggers a Qt warning which tried to use null info bar.

### CODE REVIEW

**Comment by nirvn** [comment]
That PR is great which makes me happy :wink:

**Comment by nirvn** [comment]
@wonder-sk , are you also planning to deal with the qt warning itself?

**Comment by wonder-sk** [comment]
@nirvn not planning to deal with the warnings now... it's a bunch of warnings as templates model tries to watch project template directories which do not exist.

**Comment by m-kuhn** [comment]
Several paths or only the one in the user profile folder?

```
mFileSystemWatcher.addPath( templateDirName );
```

**Comment by wonder-sk** [comment]
Multiple paths:
- /var/lib/snapd/desktop/QGIS/QGIS3/project_templates
- /usr/share/QGIS/QGIS3/project_templates
- /usr/local/share/QGIS/QGIS3/project_templates
- /usr/share/plasma/QGIS/QGIS3/project_templates
- /home/martin/.local/share/QGIS/QGIS3/project_templates

I can't see the warnings properly because they get paged out by lots of python deprecation warnings from metasearch plugin, and the GUI looks like this:
image

**Comment by nyalldawson** [comment]
Good, my plan to make these warnings truely obnoxious has definitely played out!

**Comment by nirvn** [comment]
:smiling_imp:

**Comment by m-kuhn** [comment]
Thanks, I hope #31666 (aka # 31:smiling_imp: ) will iron out the issue.

**Pull request merged**
