### PR TITLE
Expose a new QgsMapSettings::visiblePolygon method

### PR DESCRIPTION
**Pull request by strk**
Centralizes code to return a possible rotated map area boundaries

### CODE REVIEW

**Comment by strk** [comment]
\cc @wonder-sk

**Comment by wonder-sk** [comment]
Are you sure the calculation is not off by one pixel? (the right-most pixel has x coordinate width()-1).

Also worth adding to visibleExtent() docs that in case of rotated map it is just bounding box of visiblePolygon

**Comment by strk** [comment]
Uhm, I'm not sure about the off-by-one. Indeed the code lacks a testcase. I was also thinking that visibleExtent could be implemeted in terms of visiblePolygon (taking it's boundary) and mVisibleExtent could be removed...

**Comment by strk** [comment]
Pushed testcase. QgsMapSettings did not have one before this.

**Comment by strk** [comment]
And latest commit reimplements visibleExtent in terms of visiblePolygon, and documents the fact.
Can you think of any problem that might arise from the off-by-one issue you mentioned ?
Note that in presence of rotation the direction to grow canvas pixel coordinates would not be straightforward.

**Comment by strk** [comment]
Argh, latest commit fails travis. But works locally.
Unfortunately Travis doesn't show the actual value to compare to the obtained one:
https://travis-ci.org/qgis/QGIS/builds/49723401#L1185
I'm guessing it's some rounding issue

**Comment by strk** [comment]
So, the test  expects QgsMapRenderer::extent() to return:
```8.3263598326359833,10 : 21.6736401673640167,20```
right after calling ```setExtent(10,10,20,20)``` onto it.

This is because the QgsMapRenderer, evidently, has a different aspect ratio as size. But the test itself is NOT initializing the size, so the whole test looks very suspicious to me.

**Comment by strk** [comment]
The (default?) size of the QgsMapRenderer is 638x478 -- odd if it is a default, isn't it ?

**Comment by strk** [comment]
Would you agree about setting the output size explicitly rather than relying on a default ?
(I could not find where that number comes from yet)

**Comment by strk** [comment]
Here's the verbose output:
```
Actual  8.3193277310924358,9.9999999999999982 : 21.6806722689075642,20.0
Expect 8.3193277310924358,10.000000000000000 : 21.6806722689075642,20.0
```

Clearly a rounding issue... https://travis-ci.org/qgis/QGIS/builds/49771814#L1186-L1187

**Comment by strk** [comment]
MapCanvas::sizeHint() returns 640x480, so 638x478 must be something qgis codebase does internally (strip one pixel per side?).

**Comment by strk** [comment]
With the commit above I've sized the canvas to have an aspect ratio of 0.8 (650x520). Let's see what happens.

**Comment by strk** [comment]
didn't help: https://travis-ci.org/qgis/QGIS/builds/49779724#L1185-L1186

Well I'm going to revert the reimplementation of ::visibleExtent, after all that's not important at this stage. I don't think the failure reveals the off-by-one error you were concerned about, right @wonder-sk  ?

**Comment by nyalldawson** [comment]
@strk Rather than using QCOMPARE on the rectangles themselves, you could use QVERIFY( qgsDoubleNear( r1.left, r2.left) ) instead (etc for right, top & bottom). That would handle the rounding issues. Or better yet add an equality operator to QgsRectangle which tests the left/right/top/bottom using qgsDoubleNear and you'd then be able to safely use QCOMPARE on them. 

scripts/prepare_commit.sh should be run over this change too - some of the whitespace copied/pasted from QgsDecorationGrid looks wrong. 

I also +1 @wonder-sk 's comment - the calculations look off by 1.

**Comment by strk** [comment]
Could you provide a testcase that would show the "off-by-one" issue when changing the implementation of visibleExtent ? I could not see such a big discrepancy with existing tests, maybe there's none ?

**Comment by strk** [comment]
about off-by-one, the "visible extent" (or "visible polygon") includes whole pixels, so it must be at the left side of the left pixel and at the right side of the right pixel (and similarly for top/bottom ones). So I think the code is correct in using width and height for the coordinates

**Comment by strk** [comment]
I've rebased the change against master and re-run prepare-commit.sh (no change)

**Pull request merged**
