### PR TITLE
[3d] Update camera near and far planes using other chunked entities

### PR DESCRIPTION
**Pull request by wonder-sk**
Until now we were only considering terrain entity when adjusting
near and far planes of the camera. But that can cause unwanted clipping
of other entities. This will also use other entities in addition
to the terrain entity.

This fixes the issue with point cloud data getting clipped prematurely
as camera zooms in closer.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Should we backport this to 3.16 too?

**Comment by wonder-sk** [comment]
> Should we backport this to 3.16 too?

We could, but there is a small chance of unwanted behaviors from this, as it is a bit delicate piece of the code, so I would probably skip backport to avoid breaking something.

**Comment by nyalldawson** [comment]
This has certainly helped a lot with the clipping issues I previously saw, thanks

I think there's still an issue in the terrain tile clipping though -- using this branch I'm frequently able to get the situation where a terrain tile disappears while other entities from the same region are visible:

image

(using the data in the test/3d folder) 

image

or with a flat terrain:

image

**Comment by nirvn** [comment]
@wonder-sk , @nyalldawson , I'm also seeing the same glitches locally. For e.g., just now:
Peek 2020-11-27 14-26
_The GIF starts showing a erroneously missing tile at the upper-left corner, then pans a bit to make it show up, then later the GIF shows another tile gone missing_

It could be a red herring, but for what it's worth, I've started witnessing this when I updated to Qt 5.14.

**Comment by wonder-sk** [comment]
Yeah I am aware of the issue with terrain tiles getting culled too early - it's a separate issue from this one though. I will try to investigate it - I am seeing it sometimes as well (I was just too lazy to get to the bottom of it). For some reason bounding boxes of terrain tiles get incorrectly recognized as being outside of the view frustum...

> using this branch I'm frequently able to get the situation where a terrain tile disappears while other entities from the same region are visible

@nyalldawson do you mean that in this branch that problem got even worse or is it the same as in master (or 3.16) ?

@nirvn what you are getting is I believe an instance of the same problem that Nyall talks about. It should not be dependent on Qt version, because this culling of tiles based on frustum is done in QGIS code. To verify that, you can try disabling early exit from QgsChunkedEntity::update() due to the return value from Qgs3DUtils::isCullable().

**Comment by nirvn** [comment]
@wonder-sk , I can still see glitches when I disable the early exit. E.g.:
image

**Comment by wonder-sk** [comment]
@nirvn Hmm then in your case it could be indeed a Qt problem... I am on Qt 5.12, before Qt 5.9 and I don't remember seeing such a case when there would be one missing tile surrounded by tiles that are present. One other source of trouble in theory could be Qt's frustum culling that we enable by default - see mFrustumCulling in QgsShadowRenderingFrameGraph. Can you try to disable it and see if that helps? (If you enable skybox rendering, that should disable the Qt's frustum culling, without having to comment out things in code.)

**Comment by nirvn** [comment]
@wonder-sk , do you have a panoramic skybox file to share? Everytime I've tried to activate skybox, QGIS dies.

**Comment by nirvn** [comment]
Got it working with distinct faces. Still ended up with missing tiles:
image

**Comment by nyalldawson** [comment]
@wonder-sk 

>do you mean that in this branch that problem got even worse or is it the same as in master (or 3.16) ?

I think it's marginally better with this pr, so this is definitely a step in the right direction!

**Comment by wonder-sk** [comment]
@nirvn Really strange... I don't know what to suggest right now - it would be good to observe what are the conditions in order to get that behavior - is it dependent on terrain type (flat / dem ?) - is it dependent on terrain texture resolution or any other parameter related to terrain - does it happen also with other chunked entities (vectors, point clouds) - ...

@nyalldawson ok to merge it then?

**Comment by nyalldawson** [comment]
Yes!

**Pull request merged**
