### PR TITLE
Fix some leaks and errors in sip conversions

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by wonder-sk** [comment]
Looking good. The fact that PyDict_SetItem() does not take ownership while the same method for list/tuple does is very confusing...

This does not fix the Mother of all leaks from https://github.com/qgis/QGIS/pull/6186 yet, does it?

**Comment by nyalldawson** [comment]
> The fact that PyDict_SetItem() does not take ownership while the same method for list/tuple does is very confusing

Agreed! Not sure what the rationale is there...

It doesn't fix the MOAL unfortunately. That's caused by something in the MethodCode for QgsAttributes. Oddly, that code hasn't changed since 2.18 and I don't see the leak there. Can you confirm the leak on your build?

**Comment by wonder-sk** [comment]
> That's caused by something in the MethodCode for QgsAttributes. Oddly, that code hasn't changed since 2.18 and I don't see the leak there. Can you confirm the leak on your build?

I can confirm I see a leak when calling f.attributes() many times. It seems it has something to do with NULL value conversion - ordinary string/int values do not seem to leak...

**Comment by nyalldawson** [comment]
> I can confirm I see a leak when calling f.attributes() many times. It seems it has something to do with NULL value conversion - ordinary string/int values do not seem to leak...

Good catch! But I can't see anything there which could explain... The MethodCode for converting Python lists back to QgsAttributes has some odd null handling, but that shouldn't affect the C++ -> python conversion.

**Pull request merged**
