### PR TITLE
Fix null pointer error

### PR DESCRIPTION
**Pull request by giohappy**
@nyalldawson

### CODE REVIEW

**Comment by NathanW2** [comment]
Make sure you use "fix #issue" in the commit message

**Comment by giohappy** [comment]
Ah yes... I have to hard reset to amend the message.

**Comment by NathanW2** [comment]
Git commit --amend

**Comment by giohappy** [comment]
Mmm, I will close this and reopen it. Amend doesn't clean history. It works until one doesn't push the commits...

**Pull request closed without merging**
