### PR TITLE
Fix dual view form view ghost features

### LINKED ISSUE #43477: Attribute table in form view can display "ghost" attributes
Open an attribute table in **form view**
In bottom left menu, filter the table with the "Show selected features".
You should have 0 feature listed on the left, but the right panel shows attributes of a feature.
Peek 01-06-2021 02-48

### PR DESCRIPTION
**Pull request by elpaso**
Fixes #43477

### CODE REVIEW

**Comment by nyalldawson** [comment]
Won't this also block users from using the form to change the filter parameters? (via the "Select filter via form" button in the toolbar)

**Comment by elpaso** [comment]
> Won't this also block users from using the form to change the filter parameters? (via the "Select filter via form" button in the toolbar). I think you'll also need to handle changing the form visibility when the filter form mode is enabled/disabled too

Good catch, I'll check that.

**Comment by elpaso** [comment]
> Won't this also block users from using the form to change the filter parameters? (via the "Select filter via form" button in the toolbar). I think you'll also need to handle changing the form visibility when the filter form mode is enabled/disabled too

Ok, fixed. One could argue that if the model has 0 rows there is nothing to filter/search and showing the form won't be of much use but I agree that it's a better UX to show the form anyway.

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
>  One could argue that if the model has 0 rows there is nothing to filter/search and showing the form won't be of much use but I agree that it's a better UX to show the form anyway.

It's more that if i search for a value which doesn't exist then the table will be filtered down to zero rows, and I'd have no way to modify the filter (via form) to correct the search term...

**Pull request merged**
