### PR TITLE
[Processing] Update for OTB V5

### PR DESCRIPTION
**Pull request by amondot**
These commits contain updates for :
- XML description files for OTB V5.0
- HTML doc for OTB V5.0
- Update white and black list  for OTBApplications xml and html files creation
- Add particular cases for creating and loading xml files
- Update of OTBHelper.py for a match with updates of processing
- Global improvement (removing unused code)

### CODE REVIEW

**Comment by pcav** [comment]
@volaya @alexbruy seems useful stuff

**Comment by volaya** [comment]
Looks great to me but i have questions:

Is OTB 5 available everywhere and well tested? If we merge this, we lose support for older versions. We are not doing as in the case of saga, supporting multiple versions, so in this case we are forcing users to update to OTB 5. I like the idea, but only if that is a stable versions and everyone will be able to switch to it easily and without issues.

Can you comment on that @amondot?

**Comment by gioman** [comment]
@volaya is available in both ubuntugis and osgeo4w repos.

**Comment by julienmalik** [comment]
The need for management of several versions was reported in hub.qgis.org/issues/5470

In OTB we still do not have a simple --version, but it is doable. When launching an otb app without parameters, the app prints its doc, and in the doc the version can be found and extracted.


```
> otbcli_BandMath

ERROR: Waiting for at least one parameter...
This is the BandMath application, version 5.0.0
Perform a mathematical operation on monoband images

Complete documentation: http://www.orfeo-toolbox.org/Applications/BandMath.html

Parameters: 
        -progress <boolean>        Report progress 
MISSING -il       <string list>    Input image list  (mandatory)
MISSING -out      <string> [pixel] Output Image  [pixel=uint8/uint16/int16/uint32/int32/float/double] (default value is float) (mandatory)
        -ram      <int32>          Available RAM (Mb)  (optional, off by default, default value is 128)
MISSING -exp      <string>         Expression  (mandatory)
        -inxml    <string>         Load otb application from xml file  (optional, off by default)

Examples: 
otbcli_BandMath -il verySmallFSATSW_r.tif verySmallFSATSW_nir.tif verySmallFSATSW.tif -out apTvUtBandMathOutput.tif -exp "cos(im1b1)+im2b1*im3b1-im3b2+ndvi(im3b3, im3b4)"
```


This should work for version 4 and 5.

After that is implemented, having different sets of descriptors files in separated dirs, per version, would be wise to cope with the different release cycles of QGIS and OTB.

**Comment by volaya** [comment]
I merged this already. It needed some tweaks because they were conflicts (due to indentation fixes mostly)

@gioman If OTB5 this is already in osgeo4w, can you change the dependency, so when it is installed along with QGIS it installs 5 an not a previous verison? thanks!

**Comment by gioman** [comment]
@volaya as far as I can see in osgeo4w the default OTB version installed is already the 5.

**Pull request closed without merging**
