### PR TITLE
[OGR] Add workaround for OGRSQL not recognizing the column name returned by OGR_L_GetFIDColumn

### PR DESCRIPTION
**Pull request by manisandro**
Fixes regression where a subset string set on a FileGDB layer would always result in an invalid layer.

See https://lists.osgeo.org/pipermail/qgis-developer/2017-September/049802.html

### CODE REVIEW

**Comment by nyalldawson** [comment]
Thanks @manisandro!

**Review by rouault — APPROVED** [review]

**Comment by manisandro** [comment]
Hmm afaict the failures are not related to this commit, resp. I get the failures also when locally reverting the commit. Is there a way to tell which where a failure was introduced by the commit without manual bisecting?

**Comment by nyalldawson** [comment]
@manisandro

Ignore the wms server failure - that's being discussed here: https://github.com/qgis/QGIS/pull/4959#issuecomment-330838658

But the shapefile test failure is new and related to this change

**Comment by manisandro** [comment]
@nyalldawson Hmm I see the exact same failure with current vanilla master 

    $ ctest -V -R PyQgsShapefileProvider
    UpdateCTestConfiguration  from :/home/sandro/Documents/Devel/QGIS/qgis-master/build/DartConfiguration.tcl
    Parse Config file:/home/sandro/Documents/Devel/QGIS/qgis-master/build/DartConfiguration.tcl
    Add coverage exclude regular expressions.
    Add coverage exclude: /CMakeFiles/CMakeTmp/
    Add coverage exclude: .*/Testing/Utilities/.*
    Add coverage exclude: .*/Utilities/.*
    Add coverage exclude: .*/Code/Wrappers/SWIG/otbApplicationPYTHON_wrap.*
    Add coverage exclude: .*/Code/Wrappers/SWIG/otbApplicationJAVA_wrap.*
    SetCTestConfiguration:CMakeCommand:/usr/bin/cmake
    UpdateCTestConfiguration  from :/home/sandro/.Data/Documents/Devel/QGIS/qgis-master/build/DartConfiguration.tcl
    Parse Config file:/home/sandro/.Data/Documents/Devel/QGIS/qgis-master/build/DartConfiguration.tcl
    Test project /home/sandro/.Data/Documents/Devel/QGIS/qgis-master/build
    Constructing a list of tests
    Done constructing a list of tests
    Updating test list for fixtures
    Added 0 tests to meet fixture requirements
    Checking test dependency graph...
    Checking test dependency graph end
    test 300
        Start 300: PyQgsShapefileProvider

    300: Test command: /usr/bin/cmake "-P" "/home/sandro/.Data/Documents/Devel/QGIS/qgis-master/build/tests/src/python/PyQgsShapefileProvider.cmake"
    300: Test timeout computed to be: 1500
    300: export LD_LIBRARY_PATH=NOTFOUND:/home/sandro/.Data/Documents/Devel/QGIS/qgis-master/build/output/lib:
    300: export PYTHONPATH=/home/sandro/.Data/Documents/Devel/QGIS/qgis-master/build/output/python/:/home/sandro/.Data/Documents/Devel/QGIS/qgis-master/build/output/python/plugins:/home/sandro/Documents/Devel/QGIS/qgis-master/tests/src/python:
    300: -- Running  /usr/bin/python3 /home/sandro/Documents/Devel/QGIS/qgis-master/tests/src/python/test_provider_shapefile.py 
    300: !!! prefix path was requested, but it is not valid - we do not run from installed path !!!
    300: .................FERROR 1: Type mismatch or improper type of arguments to IN operator.
    300: ERROR 1: Type mismatch or improper type of arguments to IN operator.
    300: ERROR 1: Type mismatch or improper type of arguments to IN operator.
    300: ERROR 1: Type mismatch or improper type of arguments to IN operator.
    300: .ERROR 1: Attempt to read shape with feature id (-99999999) out of available range.
    300: .ERROR 1: Attempt to read shape with feature id (-102) out of available range.
    300: ERROR 1: Attempt to read shape with feature id (-101) out of available range.
    300: ERROR 1: Attempt to read shape with feature id (-104) out of available range.
    300: ERROR 1: Attempt to read shape with feature id (-103) out of available range.
    300: .........ERROR 1: Use of field function MAX() on string field name illegal.
    300: .ERROR 1: Use of field function MAX() on string field name illegal.
    300: .ERROR 1: Use of field function MIN() on string field name illegal.
    300: .ERROR 1: Use of field function MIN() on string field name illegal.
    300: ........ERROR 6: DeleteFeature : unsupported operation on a read-only datasource.
    300: ./home/sandro/Documents/Devel/QGIS/qgis-master/tests/src/python/test_provider_shapefile.py:502: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/tmp4a6nftni/shapefile.shp'>
    300:   del f_shp
    300: /home/sandro/Documents/Devel/QGIS/qgis-master/tests/src/python/test_provider_shapefile.py:503: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/tmp4a6nftni/shapefile.shx'>
    300:   del f_shx
    300: /home/sandro/Documents/Devel/QGIS/qgis-master/tests/src/python/test_provider_shapefile.py:504: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/tmp4a6nftni/shapefile.dbf'>
    300:   del f_dbf
    300: ..........
    300: ======================================================================
    300: FAIL: testGetFeaturesDestinationCrs (__main__.TestPyQgsShapefileProvider)
    300: ----------------------------------------------------------------------
    300: Traceback (most recent call last):
    300:   File "/home/sandro/Documents/Devel/QGIS/qgis-master/tests/src/python/featuresourcetestbase.py", line 540, in testGetFeaturesDestinationCrs
    300:     self.assertFalse(features)
    300: AssertionError: [<qgis._core.QgsFeature object at 0x7f6372c30288>, <qgis._core.QgsFeature object at 0x7f6372c30828>, <qgis._core.QgsFeature object at 0x7f6372c30708>, <qgis._core.QgsFeature object at 0x7f6372c30438>, <qgis._core.QgsFeature object at 0x7f6372c301f8>] is not false
    300: 
    300: ----------------------------------------------------------------------
    300: Ran 51 tests in 0.349s
    300: 
    300: FAILED (failures=1)
    300: Application state:
    300: QGIS_PREFIX_PATH env var:          /home/sandro/.Data/Documents/Devel/QGIS/qgis-master/build/output
    300: Prefix:
    300: Plugin Path:               /home/sandro/.Data/Documents/Devel/QGIS/qgis-master/build/output/lib/qgis/plugins
    300: Package Data Path: /home/sandro/Documents/Devel/QGIS/qgis-master
    300: Active Theme Name:
    300: Active Theme Path: /home/sandro/.local/share/test_provider_shapefile.py/profiles/default//themes//icons/
    300: Default Theme Path:        :/images/themes/default/
    300: SVG Search Paths:  /home/sandro/Documents/Devel/QGIS/qgis-master/images/svg/
    300:            /home/sandro/.local/share/test_provider_shapefile.py/profiles/default/svg/
    300: User DB Path:      /home/sandro/Documents/Devel/QGIS/qgis-master/resources/qgis.db
    300: Auth DB Path:      /home/sandro/.local/share/test_provider_shapefile.py/profiles/default/qgis-auth.db
    300: 
    300: OGR(1): Unbalanced call to leaveUpdateMode() w.r.t. enterUpdateMode()
    300: OGR(1): Data source is invalid ()
    300: OGR(1): Cannot reopen datasource /tmp/tmpfzdr5il_/shapefile.shp|layerid=0 in update mode
    300: OGR(1): Data source is invalid ()
    300: OGR(1): Cannot reopen datasource /tmp/tmpfzdr5il_/shapefile.shp|layerid=0 in update mode
    300: CMake Error at PyQgsShapefileProvider.cmake:15 (MESSAGE):
    300:   Test failed: 1
    300: 
    300: 
    1/1 Test #300: PyQgsShapefileProvider ...........***Failed    1.20 sec

    0% tests passed, 1 tests failed out of 1

    Total Test time (real) =   1.22 sec

    The following tests FAILED:
            300 - PyQgsShapefileProvider (Failed)

**Comment by nyalldawson** [comment]
@manisandro I get that failure locally too, but it's not an issue on master in the travis environment (I suspect there's some gdal related change which requires that test to be updated). But it's a different failure here:


https://dash.orfeo-toolbox.org/testDetails.php?test=61164102&build=291458

```

======================================================================
FAIL: testMaxValue (__main__.TestPyQgsShapefileProvider)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/qgis/QGIS/tests/src/python/providertestbase.py", line 279, in testMaxValue
    self.assertEqual(max_value, 300)
AssertionError: 3 != 300

======================================================================
FAIL: testMinValue (__main__.TestPyQgsShapefileProvider)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/qgis/QGIS/tests/src/python/providertestbase.py", line 269, in testMinValue
    self.assertEqual(min_value, 200)
AssertionError: 2 != 200

======================================================================
FAIL: testUnique (__main__.TestPyQgsShapefileProvider)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/qgis/QGIS/tests/src/python/providertestbase.py", line 296, in testUnique
    self.assertEqual(set(values), set([200, 300]))
AssertionError: Items in the first set but not the second:
2
3
Items in the second set but not the first:
200
300

======================================================================
FAIL: testUniqueStringsMatching (__main__.TestPyQgsShapefileProvider)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/qgis/QGIS/tests/src/python/providertestbase.py", line 315, in testUniqueStringsMatching
    self.assertEqual(set(values), set(['Pear', 'Apple']))
AssertionError: Items in the second set but not the first:
'Apple'
'Pear'
```

**Pull request merged**
