### PR TITLE
Remove the 'stale' label upon unstaling with commits

### LINKED ISSUE #50822: stale bot does not remove the stale label upon PR sync (push of new commits)
### What is the bug or the crash?

The stale bot doesn't see push of new commits in a branch associated to a PR as a sign of activity, and so it does not remove the stale label.

### Steps to reproduce the issue

File a pull request, wait for stale bot to mark it as stale, push new commits to it

### Versions

N/A

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DelazJ**
~~If I correctly understood the [actions/stale description](https://github.com/actions/stale#close-stale-issues-and-prs) and particularly the [labels-to-remove-when-unstale](https://github.com/actions/stale#labels-to-remove-when-unstale) option, this should be enough to trigger removal of the label for PR and issue. We shouldn't need a specific unstale.yml action. Or did I overlook something?~~
Fixes #50822

### CODE REVIEW

**Comment by nicogodet** [comment]
By removing unstaling workflow, it will break the instant unstale on comment.
Stable bot is only triggered once an hour.

An alternative would be to add trigger `on:` for commit in unstaling.yml
refs:

- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment

**Comment by DelazJ** [comment]
@nicogodet That was my plan until I checked why the stale action would not properly unstale.
The [remove-stale-when-updated](https://github.com/actions/stale#remove-stale-when-updated) option, true by default, states
> Automatically remove the stale label when the issues or the pull requests are updated (based on [GitHub issue](https://docs.github.com/en/rest/reference/issues) field updated_at) or commented.

Does that not mean it is triggered when the event happens (ignoring any scheduling)? That said, I'm not an expert of these mechanisms...

**Comment by DelazJ** [comment]
Went back to the initial plan. The remove-stale-when-updated only removes the label at the next run of the bot, a day after. Not ideal for people that would like an immediate effect (and I don't get the logic in delaying the change but...)

**Comment by DelazJ** [comment]
\- Hey bot, if I say this is not stale, would you also remove the `stale` label?...
\-  no
\- no? Ah right! we need this PR to get merged beforehand... but, then, you can no more tell me this one is stale!
\- ...

**Comment by DelazJ** [comment]
Ah... You lied to me, bot. Comments work but not commits.

**Comment by DelazJ** [comment]
Should still be good, bot

**Comment by DelazJ** [comment]
I think this one is good to merge

**Review by strk — APPROVED** [review]
I'm sorry I've missed this. Please ping me next time you're on the battlefield against bots!

**Pull request merged**
