### PR TITLE
[ux]  Use model for symbol list view in symbol panel

### PR DESCRIPTION
**Pull request by nyalldawson**
Fixes hi-dpi issues in the symbol selector, reuses style model for less code duplication, more use of unit-tested code.

### CODE REVIEW

**Comment by nyalldawson** [comment]
The icons need improving here, but this PR adds a new "icon/list" view switch in the selector:

peek 2018-09-13 17-48

**Comment by nirvn** [comment]
Nice. What's the "_A" icon?

**Comment by nyalldawson** [comment]
You mean the label? It's the selected symbol

**Comment by nirvn** [comment]
Ahh, sorry, got it.

**Pull request merged**
