### PR TITLE
Processing tests

### PR DESCRIPTION
**Pull request by ghtmtt**
## Description
More Processing test for the QGIS core provider

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by ghtmtt** [comment]
travis does not complain anymore but I had to turn off 2 tests:

* https://github.com/qgis/QGIS/pull/4259/commits/8232ee17599afd70db8eb9e0a56b2fb67c5a0cd6#diff-6adbb8b7f5ba14326f83ce9b6eb72bc5R2350 because the iface cannot be run during the tests. However, in the test I just added some default coordinates, so why the test is looking for iface?
* https://github.com/qgis/QGIS/pull/4259/commits/47ce4ba769580ec1702be87904451ac783f427b3#diff-6adbb8b7f5ba14326f83ce9b6eb72bc5L2458 because of an invalid predicate (disjoin) that I haven't used in the test (used predicates are intersect and within)

@m-kuhn any idea why the fail? Thanks!

**Comment by m-kuhn** [comment]
I guess the point test should take the CRS of the output layer and not the one of the mapCanvas.

See here
https://travis-ci.org/qgis/QGIS/jobs/211067649#L744-L746

Can you fix that?

For the other one, I recently found that there is no handling for Multi-values available for the yaml tests so far. I assume it's the same for "Selection" parameters, or do you know if there is an algorithm with a "Selection" parameter successfully tested already?

**Comment by ghtmtt** [comment]
I tried to fix the regular point by adding `CRS: EPSG:4326` under the output, is this the right way?

> For the other one, I recently found that there is no handling for Multi-values available for the yaml tests so far. I assume it's the same for "Selection" parameters, or do you know if there is an algorithm with a "Selection" parameter successfully tested already?

actually no.. I don't think there are tests with something like the *predicate* and so a multi selection...

**Comment by m-kuhn** [comment]
@ghtmtt yeah, I think that is the correct approach. But this will need to be added as a new parameter `crs` to the algorithm itself.
This will allow using the algorithm in tests and standalone apps.
The tricky part is, that we don't make it more complicated for users in QGIS itself. So the param should be set to the canvas CRS by default when running the algorithm from within QGIS.

@alexbruy what do you think about adding a new "magic" default value `Processing:ProjectCrs` which evaluates to `QgsProject::instance().crs()` and can be specified as default value by an algorithm in the parameter definition while allowing to manually override the parameter in tests/standalone apps?

**Comment by alexbruy** [comment]
> @alexbruy what do you think about adding a new "magic" default value Processing:ProjectCrs which evaluates to QgsProject::instance().crs() and can be specified as default value by an algorithm in the parameter definition while allowing to manually override the parameter in tests/standalone apps?

Sounds good for me.

**Comment by m-kuhn** [comment]
@alexbruy Can you have a look at the changes I pushed here

@ghtmtt Can you `git pull` before continuing the work on this branch and apply the changes I did to the RegularPoints algorithm also to `RandomPointsExtent`, `VectorGridLines`, `VectorGridPolygons` (not sure about the other algorithms that reference iface).

**Comment by alexbruy** [comment]
@m-kuhn looks good for me.

**Review by alexbruy — APPROVED** [review]

**Comment by ghtmtt** [comment]
@m-kuhn @alexbruy  thanks for the work and the review. I pulled the changes, so should I add the `CRS: EPSG:4326` parameter also to the other test you listed?

**Comment by ghtmtt** [comment]
@m-kuhn ok done for `RandomPointsExtent` but for the other 2 algos (`VectorGridLines` and `VectorGridPolygons`) I have a serious doubt since yesterday (so I'm really happy that you pointed out them here).

In Processing I can see 2 algorithms:

* Create grid (lines) (callable via python with `qgis:creategridlines`)
* Create grid (polygons) (callable via python with `qgis:creategridpolygons`)

both already have the CRS parameter.

But by making the tests yesterday, I found out that there a 2 similar and hidden algorithms (by hidden I mean that you cannot see them in Processing but you can call them via python) that are:

`qgis:vectorgridlines`
`qgis:vectorgridpolygons`

both don't have the CRS parameter but they do exactly the same thing as the other 2 algorithms. 
Question is, can we get rid of these 2?

**Comment by m-kuhn** [comment]
Nice, good job!

can you add a test for RandomPointsExtent and then we can merge this I would say.

Not sure about the other tests either. They were disabled in 772b7694032f6f7337e7e159ccb467010b2a8fa9 @nyalldawson , any idea?

**Comment by alexbruy** [comment]
These algs were disabled because new algorithms were added more robust, with better performance and clean code. Old algs were disabled to keep existing scripts and models working. Personally I think we can safely delete them, as QGIS 3.0 will break API anyway. So it is right time to cleanup Processing too.

**Comment by ghtmtt** [comment]
wait.. I remember that I already tried to make a test for the random point, but the test always failed because it creates (random) points that were (of course!) different from the points of the expected layer. 
With this new parameter the test will compare just the extent or will try to match the points?

**Comment by m-kuhn** [comment]
Hmm... not sure if it's possible with the current yaml system, but comparing the number of points would already be a good smoke test (to detect exceptions etc.).

**Comment by ghtmtt** [comment]
ok, I'll try to add the test and see if it runs

**Comment by ghtmtt** [comment]
while for `ExtractByLocation` test cannot run right?

**Comment by ghtmtt** [comment]
@m-kuhn as I thought, the test is trying to match the *in-place* created random points with the existing one and it fails.. some other ideas?

**Comment by m-kuhn** [comment]
Maybe if you make the bbox for the random points smaller than the accepted tolerance in the geometries?

**Comment by Gustry** [comment]
> Old algs were disabled to keep existing scripts and models working. Personally I think we can safely delete them, as QGIS 3.0 will break API anyway. 

An API break, it's for developers. It doesn't impact users.
But if we remove some algs, we will break models from users. I think this is something bad. We should at least check that a python exception is not raised for instance and the user can display the old model and update deprecated algorithms.

**Comment by m-kuhn** [comment]
Should we treat model designers and project maintainers as users or as developers?

I think if we want to get rid of legacy, now is the time.
At the same time, any initiative to make the migration process as smooth as possible is highly appreciated (the alternative will often be "upgrading was too hard, so we sticked to 2.18" in reality).

Is it possible to replace these algorithms with some "dummy algorithms" that have no logic but a text or message box that says "The algorithm xyz is no longer supported. Please use algorithm abc instead."?

**Comment by ghtmtt** [comment]
nope, it fails again. I would say to ignore the test for this algorithm for now so we can merge this PR. Opinions?

**Comment by m-kuhn** [comment]
Sure, sounds good.

**Comment by m-kuhn** [comment]
Wait, last try... If you don't add any OUTPUT in the yaml, what happens?

**Comment by ghtmtt** [comment]
should I remove all the lines below `results` (results line included?)

**Comment by m-kuhn** [comment]
Maybe something like this... Not sure

    results: {}

**Comment by ghtmtt** [comment]
@m-kuhn seems working! With this workaround, do you think it would be possible to add also tests for other *not testable* algorithms, like all the selection one that don't produce any real output?

Thanks for the trick!

**Comment by alexbruy** [comment]
IMHO better to add real tests. For example, such algs can be tested using models or scripts (e.g. select and the save selected). #4268 should help with this.

**Comment by ghtmtt** [comment]
so you mean just create a new script with these algorithm, no output, but the test checks if the provider runs right? that's great! thanks!

**Comment by m-kuhn** [comment]
Is it possible to call algorithm from scripts - and then perform some `assert`s on the layer?
That would be even better.

**Comment by alexbruy** [comment]
> so you mean just create a new script with these algorithm, no output, but the test checks if the provider runs right

No. I explained this a bit more [here](https://github.com/qgis/QGIS/pull/4268#issuecomment-287088685)

**Comment by ghtmtt** [comment]
Understood now, thanks!

**Comment by ghtmtt** [comment]
@m-kuhn do you think we can merge this PR as it is right now (with the random points in extent test) or should I remove it, merge the PR without this test and in future make test with the @alexbruy new test method?

**Comment by m-kuhn** [comment]
Can you remove the expected output of this test (random_points_extent.gfs etc), ready to merge for me then.

**Comment by ghtmtt** [comment]
right, forgot the useless layers.. ;) done!

**Comment by Gustry** [comment]
Model designers are users, not coders. I think we shouldn't break existing models, or they will be very disappointed to lose their existing models, without being able to open it (except installing 2.18)
I agree, it's time to remove legacy things before qgis 3 is out.

> Is it possible to replace these algorithms with some "dummy algorithms" that have no logic but a text or message box that says "The algorithm xyz is no longer supported. Please use algorithm abc instead."?

This would be the best IMHO.

**Comment by m-kuhn** [comment]
Yes, the best thing is not to break anything. At the same time we need to get rid of legacy code that we no longer want to maintain to simplify the code base. Therefore

 * remove legacy where newer and better things are available to get rid of duplicate code to maintain. don't sacrifice functionality for this.

From my point of view the migration path for everyone - users, project maintainers, modelers and developers is:

 * auto-migrate where possible (projects, configuration, models ...)
 * provide tools to migrate (code, projects,configuration, models ...)
 * give good hints where not possible
 * document leftovers and caveats

**Comment by m-kuhn** [comment]
Thanks @ghtmtt very good job!

**Pull request merged**
