### PR TITLE
Correctly handle GDAL drivers which support BOTH raster and vector layers in the GDAL driver list in options dialog

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
Thanks @nyalldawson, this will fix #53734.

**Comment by agiudiceandrea** [comment]
@nyalldawson, it looks like it is not actually possible to "skip", e.g., the OpenFileGDB Raster but not "skip" the OpenFileGDB Vector or viceversa.
It seems also there are same glitches:

1) initial situation: the OpenFileGDB driver checkboxes in both the Raster and Vector tabs are checked
- if you uncheck the OpenFileGDB driver checkbox in the Raster tab, the OpenFileGDB driver checkbox in the Vector tab remains checked; after you close and reopen QGIS, then the OpenFileGDB driver checkboxes in both the Raster and the Vector tabs are unchecked.
2) now, the OpenFileGDB driver checkboxes in both the Raster tab and the Vector tab are unchecked
- if you check the OpenFileGDB driver checkbox only in the Raster tab or only in the Vector tab; after you close and reopen QGIS, then the OpenFileGDB driver checkboxes remains unchecked in both the Raster and the Vector tabs.

**Comment by nyalldawson** [comment]
@agiudiceandrea it's not possible to selectively disable only the raster or vector portion of a driver. It's all or nothing.
The best we could do is force sync the equivalent check boxes....

**Comment by nyalldawson** [comment]
> The best we could do is force sync the equivalent check boxes....

@agiudiceandrea That's done now

**Comment by nyalldawson** [comment]
> Another approach would be to add a third tab dedicated to the drivers with both vector and raster capabilities

Or alternatively condensing both lists into a single unified one?

**Comment by agiudiceandrea** [comment]
> Or alternatively condensing both lists into a single unified one?

The Raster drivers tab has an additional group of widget for the raster drivers options: may having vector and raster and vector+raster drivers together may get confusing as to which driver you can set these options for? Maybe adding a column with values like Raster, Vector and Raster+Vector or similar would help. But, would such GUI change be backportable to 3.28? QGIS 3.28 is also affected by the issue (it is not possible to skip e.g. the OpenFileGDB driver).

**Comment by nyalldawson** [comment]
> The Raster drivers tab has an additional group of widget for the raster drivers options: may having vector and raster and vector+raster drivers together may get confusing as to which driver you can set these options for? Maybe adding a column with values like Raster, Vector and Raster+Vector or similar would help. 

Yeah, I think my ideal rework would remove the tabs, have a single unified (and filterable!) list, and be arranged like:

```
+ Raster Driver Options +
| xxx  |

+ Drivers +

list .... filter box
```

> But, would such GUI change be backportable to 3.28? QGIS 3.28 is also affected by the issue (it is not possible to skip e.g. the OpenFileGDB driver).

No. But we could just merge this as is first, and then rework after for 3.34 only...

**Review by nirvn — APPROVED** [review]

**Pull request merged**
