### PR TITLE
QgsSettings housekeeping

### PR DESCRIPTION
**Pull request by elpaso**
Removed leading slash from keys
replaced mixed/upper case "Qgis" with "qgis"

### CODE REVIEW

**Comment by nyalldawson** [comment]
Looks good!

Just wondering... what do we need the qgis prefix for? Could it potentially be dropped?

**Comment by elpaso** [comment]
@nyalldawson `qgis` can be dropped but I think that the next wise move would be use the `QgsSettings::Section` optional argument to `vlue` and `setValue` to automatically add a namespace and  classify all setting keys in the appropriate section `gui` `core` `plugins` `server` etc. etc.

**Comment by 3nids** [comment]
Some thoughts here...

### Classification 

I think sections won't be enough to classify the settings, as we have subsections in many many settings.
What do you suggest here? 

* A custom optional string argument for subsection?
* The declaration of all possible subsections in QgsSettings?
* Forcing a single level and increase the number of section?
* Forcing a single level and stick with it?

I just think we should either offer full flexibility (write section and sub-section as you like) or a rigid frame you'll have to stick to. 

*******

### Naming

I think `Scope` is a better phrasing than `Section`.  It's also what is used by Qt. 
Can a native English speaker confirm? @nyalldawson @NathanW2 @dakcarto ?

*******

### Slash 

On the side, I tend to dislike the removal of first slash. I think it's more clear that we are classifying them with first slash:
`/my_category/my_setting` is clearer to me than 'my_category/my_setting` which I see it as a whole (one complete name). But that depend on the previous point I suppose

**Comment by elpaso** [comment]
@3nids , thanks for your feed-back!

The idea (originally from @NathanW2) was to namespace the keys to bring some order, for example a setting for a core class would be stored in the core section (with the `core/` prefix), a setting for the gui part would be stored  in the gui section (with the `gui/` prefix) and so on.

Note: this would be just the prefix, you are not limited in any way regarding sub sections.
Also, the sections are already used for many keys, but they are not consistent.

I think we just need a Section for each main code section (Core, Gui, App, Misc, Plugins and maybe Auth).

At the end we would end up with a nice settings key structure like:
```
core/whatever/your/key
gui/whatever/your/key
etc ..
```

About naming and slashes, I tried to stick to Qt terminology and conventions that call the main section a "section" and suggests to not use slashes in keys (they are ignored in any case), see http://doc.qt.io/qt-5/qsettings.html#section-and-key-syntax , moreover, all examples in QT do not use a leading slash.

> Section and Key Syntax

Setting keys can contain any Unicode characters. The Windows registry and INI files use case-insensitive keys, whereas the CFPreferences API on macOS and iOS uses case-sensitive keys. To avoid portability problems, follow these simple rules:

- Always refer to the same key using the same case. For example, if you refer to a key as "text fonts" in one place in your code, don't refer to it as "Text Fonts" somewhere else.
-   Avoid key names that are identical except for the case. For example, if you have a key called "MainWindow", don't try to save another key as "mainwindow".
-  Do not use slashes ('/' and '\') in section or key names; the backslash character is used to separate sub keys (see below). On windows '\' are converted by QSettings to '/', which makes them identical.

**Comment by elpaso** [comment]
Refining my answer, in the ini file, the first part of a key, before the first (not-leading) slash, is called a "section" (enclosed in brackets):

```
$ grep '\[' .config/QGIS/QGIS2.conf 
[General]
[locale]
[PythonPlugins]
[Qgis]
[ckan_browser]
[GeoGig]
[ResourceSharing]
[UI]
[QgsCollapsibleGroupBox]
[gps]
[browser]
[Windows]
[browser2]
[Projections]
[QgsVariableEditorTree]
[Section]
[Composer]
[ComposerUI]
[svg]
[DB_Manager]
[Processing]
[Plugins]
[Master%20Password%20Helper]
[WPS]
[firstaid]
[Map]
[WPS-lastConnection]
[proxy]
[cache]
[Raster]
[variables]
[colors]
```
My proposal is to use the `QgsSettings::Section` to have the main sections reflect the main code directories:

```
$ tree -L 1 -d dev/QGIS/src 
dev/QGIS/src
├── analysis
├── app
├── astyle
├── auth
├── browser
├── core
├── crssync
├── customwidgets
├── gui
├── helpviewer
├── plugins
├── providers
├── python
├── server
├── test
└── ui
```

we probably don't need all of them, the following should be enough:

```
$ tree -L 1 -d dev/QGIS/src 
dev/QGIS/src
├── app
├── auth
├── core
├── gui
├── plugins
├── providers
├── server
└── misc <-- catch all
```

So, in the ini file the sections would become:

```
[app]
[auth]
[core]
[gui]
[plugins]
[providers]
[server]
[misc]
```

@3nids I see your point, IMO we should try to find a good compromise for the number of sections, keeping them in sync with code main directories make it easier to understand where the setting comes from and it's also easy for a developer to know in which section the setting should be placed.

**Comment by 3nids** [comment]
@elpaso Thanks a lot for the explanation and reference to Qt doc. That seems quite good to me this way!

That made me just thinking that it could be worth adding a test to check that all calls use the same default values and do not mix the case. That could be done in the static Travis tests (spelling + indentation).

**Comment by elpaso** [comment]
@3nids I'm sorry, but I'm not sure I get what you mean (possibly I misunderstood it) but IMO, if we refactor all the code under `src/` to use the optional `Section` in the getters and setters of `QgsSettings`, the prefix(`qgis/`, `gui/`, `core/` etc.) will be automatically inserted by `QgsSettings` and it will be spelled exactly as we (in the API) decide it to be: the is no need to check it. BTW, this refactoring would be quite a lot of work (we can try with some `sed`, `perl` regexp magic but I'm not sure we will not need some manual work).

But if we don't use the `Section` additional argument, then yes, a check would be very useful.

In any event we should make a decision about using or not using the `Section`, if we decide to don't use the `Section` we should remove it from `QgsSettings`: it would  be just dead code.

But honestly, I cannot see any argument against using `Section` and I see some advantages: that by using `Section` we will gently "prevent" (without really enforcing it) the users to invent their own original or misspelled prefixes.

**Comment by 3nids** [comment]
no, I want to keep the Section part, it is great.

If we have mixed case settings, I was just thinking that we could check that we are not using different cases for the same setting across the code.
But the most important part to me is the default value coherence.
Indeed this require some fine tuned regex, but it should be feasible.

**Comment by elpaso** [comment]
oh, yes, definitely, if we can check that a setting key is not spelled differently in different parts of the code that would be great!

My forced all lowercase initial implementation was a nice try to solve this problem, but I understand that it needed larger refactorings.

**Pull request merged**
