### PR TITLE
[processing][feature] load R scripts from file

### PR DESCRIPTION
**Pull request by ghtmtt**
## Description
This PR adds the chance to load R script file from local folders (exactly the same as for python scripts). Together with the Rscripts an additional check looks for `rsx.help` help files and they exist they will automatically copied in the Processing script folder. 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by ghtmtt** [comment]
Just one thing I cannot solve: I placed the `svg` file into the ` images/themes/default` but I cannot see it in Processing. Should I add it somewhere else?
@volaya @alexbruy could you have a quick look at it? 

Thanks!

**Comment by alexbruy** [comment]
Better to unify existing "Add script" function instead of creating two almost identical. Also note that we plan to remove R provider from core Processing.

**Comment by ghtmtt** [comment]
Do you really plan to remove R from core? So it will no more R available in QGIS?

**Comment by gioman** [comment]
> Do you really plan to remove R from core? So it will no more R available in QGIS?

as other providers will be available as plugin.

**Comment by ghtmtt** [comment]
ah ok.. but all the existing R tools will be still available right?

**Review by alexbruy — CHANGES_REQUESTED** [review]
I'd suggest to unify existing "Add script" function instead of creating two almost identical.

**Comment by ghtmtt** [comment]
Ok I can try do do something.. don't now exactly how to deal in the same script with 2 providers (especially if one of them will not be in Processing by default)

**Comment by volaya** [comment]
If the R provider is going to be take away, then you can probably leave the code like this, as a more independent thing, even if it replicates code in core. OR, in a cleaner way, try to extend the corresponding core classes and override only a part of it.

**Comment by ghtmtt** [comment]
@volaya ok then.. I you all are ok, we can leave the code as it is: if R is going to be a "standalone" plugin then maybe combining this feature in the same file is not so good (@alexbruy what do you think?)

Thanks for the feedback!

BTW: I still cannot see the icon in Processing.. some hints?

**Comment by volaya** [comment]
Yes, I think it can be ok like that.

Regarding the icon, not sure if you need to do something else than just adding it to the theme folder. But, since this provider it's going to be taken out, maybe it's better to put the icon in the processing folder, so it can them be easily removed

**Comment by ghtmtt** [comment]
@volaya ok fine, thanks! for the icon, do you have some suggestions for a specific folder where to put it? directly in `processing/algs/r`?

**Comment by alexbruy** [comment]
Closing as R provider now removed from core

**Comment by pcav** [comment]
Where can this patch be applied then? I'd like not to miss it.

**Pull request closed without merging**
