### PR TITLE
Show message when stack trace can't be generated from  missing symbols

### PR DESCRIPTION
**Pull request by NathanW2**
Updates to the crash handler to not show the stack trace when the symbols can't be loaded. When symbols aren't loaded the stack trace is pretty much useless and misleading meaning people think it's caused by something it really isn't.

Other tweaks in this PR include:

- Fixing the wording to move from "Crashed" to "unexpectedly ended" as it's less aggressive 
- Fixed spacing in the message wording
- Added some more help text

image

In future, I would like to make this dialog also fetch the symbols in the background if they are not found but that is out of scope for this PR.

Should also hopefully be good for a backport into 3.4

### CODE REVIEW

**Comment by nirvn** [comment]
Nice, nice! So happy the stack trace is not showing instead of throwing wrong calls.

Only comment: can you make sure all the sentences end with a dot, and that the dot isn't part of any hyperlink? 

Glad we have you back coding! ;)

**Comment by nirvn** [comment]
Oh, and moving the ascii emoji away from the headline? Yay!

**Comment by NathanW2** [comment]
> Nice, nice! So happy the stack trace is not showing instead of throwing wrong calls.
> 
> Only comment: can you make sure all the sentences end with a dot, and that the dot isn't part of any hyperlink?
> 
> Glad we have you back coding! ;)

Good to be back :)

Added the dots.

**Comment by nirvn** [comment]
One missing, the sentence that starts with "Include as much info as possible..." needs a dot. Also, maybe use information instead of info there, looks a bit cleaner.

**Comment by nirvn** [comment]
Looking good; I think we need to backport this to 3.4, to improve bug reporting.

**Comment by NathanW2** [comment]
All good to merge @nirvn?

**Review by nirvn — APPROVED** [review]
Yep, go ahead.

**Comment by Gustry** [comment]
Nice.

Side question @NathanW2 is-it possible to make the crash ID clickable too (opening the web browser)? And maybe we can ask people first to check if there is another ticket open before to create a new one?

**Comment by NathanW2** [comment]
There is a PR already for that I am pretty sure. It should be ok to merge
from last time I looked

**Comment by Gustry** [comment]
Yes, it was me ;-) And it has been merged.
It was for the crash report when it's on github. But I don't think the link will open on the QGIS application? I can't try. Maybe if we should ask our users to check first if there is a ticket in this dialog.

Sorry, I didn't try what I did as I don't have windows.

**Comment by NathanW2** [comment]
Ahh sorry was on my phone so didn't even look. Yeah I can have a look and
see what I can do here

**Pull request merged**
