### PR TITLE
Update tsstat.pl and added Flag for Sardinian Language

### PR DESCRIPTION
**Pull request by ValPinnaSardinia**
I have added the Translators List and the Country Flag for Sardinian Language

### CODE REVIEW

**Comment by i-s-o** [comment]
FYI master branch (nightly build as of yesterday) is complaining about the missing sc.svg (because this PR is not ported to master?):
`2020-11-10T10:46:41     CRITICAL    Qt : Cannot open file ':/images/flags/sc.svg', because: No such file or directory`

**Comment by jef-n** [comment]
This PR is against the release-3_16 branch.

**Comment by ValPinnaSardinia** [comment]
I think that the missing reference in the file i18n/CMakeLists.txt is one of the reasons why the flag is not working.

**Comment by agiudiceandrea** [comment]
@i-s-o, see https://github.com/qgis/QGIS/pull/40083

**Pull request merged**
