### PR TITLE
Wire in resampler in raster save

### PR DESCRIPTION
**Pull request by whatnick**
## Description
Resample rasters during save as. 

Towards fixing #15686

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks for this proposal, sounds like a good thing to do.

In order to proceed with this, can you setup your [pre-commit hook](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md) and rebase to fix merge conflicts?

**Comment by whatnick** [comment]
Thanks I will rebase. Perhaps there should be instructions for windows devs
since "ln" is not really a standard option here.

**Comment by m-kuhn** [comment]
Not sure if these instructions exist, as far as I know most developers work on Linux. If you find a solution on Windows, it would be great if you could share a quick outline of the process.

**Comment by NathanW2** [comment]
Generally you need to run cgywin because the scripts assume a Linux style
setup e.g needs perl, ls, git etc

**Comment by whatnick** [comment]
I have rebased will see if my mingw env/git bash can handle the pre-commit hooks

**Comment by whatnick** [comment]
Windows pre-commit hook procedures updated to function in git-bash https://github.com/qgis/QGIS/pull/5622

**Comment by timlinux** [comment]
Wow the diff is huge - maybe your recommit is adding windows linefeeds?

**Comment by whatnick** [comment]
Yes pre-commit hook decided to relinefeed everything :( Worth abandoning
and redoing I suppose.

**Comment by whatnick** [comment]
Amended to #5667

**Comment by nyalldawson** [comment]
Shouldn't you either be:

1. Asleep
Or
2. On a plane heading to the conference already? 

;)

**Pull request closed without merging**
