### PR TITLE
Update list to include missing dependecies in Ubuntu Artful

### PR DESCRIPTION
**Pull request by juusechec**
This is related with solve of issues https://issues.qgis.org/issues/17371 and https://issues.qgis.org/issues/17373

## Description
Solve of issues 17371 and 17373 related with compilation and execute of qgis upstream release.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by jef-n** [comment]
INSTALL is a output file.  Superceeded by e9d2fd676

**Comment by jef-n** [comment]
It's already closed!? ;)

**Comment by juusechec** [comment]
Thanks!

**Comment by juusechec** [comment]
I'm seeing that you only includes qt5-default, and the packages "python3-owslib python3-jinja2 python3-pygments" isn't necesary?

**Comment by jef-n** [comment]
well, not required to build or for tests - just to run.  Who would have time to actually run qgis ;)

**Pull request closed without merging**
