### PR TITLE
Better backwards compatibility for old snapping code

### PR DESCRIPTION
**Pull request by mhugent**
Travis test

### CODE REVIEW

**Comment by 3nids** [comment]
@mhugent I see in the node tool that you enabled the snapping  (mSnapOnPress = true) but you still use the old snapping class.
In such case, the snapping is called twice, the old on being much slower.
It would be nice to remove calling to the old classes.

From what I understand, QgsMapAdvancedDigitizing/QgsMapMouseEvent which would allow to snap to the current layer, is this correct?

I can add the missing part if needed.

**Comment by mhugent** [comment]
@3nids: Oh, saw your comment just now.
True, it would be nicer using only the snapping of the advanced digitizing class. Is there a snapToCurrentLayer function somewhere in the advanced digitizing classes that can be used by the node tool?

My short term workaround was to fix the backward compatibility with the old snapping (the missing backward compatibility is an API break in the 2.x versions btw).

**Comment by 3nids** [comment]
yeah the merge crossed my message ;)

indeed this fixes the API break, which is good.

Indeed there is nothing yet such as snaptocurrentlayer.
I will see if I can integrate this, and we can update the node tool later on.

**Comment by mhugent** [comment]
>I will see if I can integrate this, and we can update the node tool later on.
Cool, thanks!

**Pull request merged**
