### PR TITLE
Fix Save for external ressource dialog RelativeStorage config parameter

### LINKED ISSUE #44799: Regression attachment widget can't set "Relative paths"
### What is the bug or the crash?

In the attachment widget configuration the state of the checkbox "Relative paths" it is not remembered.
@troopa81 Maybe introduced there b1fa33386f23a40c1863369a836db03510295b2a?

Peek 2021-08-23 10-32

### Steps to reproduce the issue

1. Create a layer with a text field
2. In layer properties choose "Attachment" for the text field
3. Check "Relative paths" checkbox
4. Close/reopen layer properties
5. Checkbox is not set anymore

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.21.0-Master | QGIS code revision | f9b18e453d
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.8.10
GDAL/OGR version | 3.3.0
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.5
PostgreSQL client version | 13.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.6
QScintilla2 version | 2.11.6
OS version | openSUSE Tumbleweed
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins | plugin_reloaderquick_map_servicesshlocatordocument_management_systemQgisModelBakerfirstaidprocessingsagaprovidergrassproviderMetaSearchdb_manager

</body></html>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by troopa81**
Fixes #44799 : When clicking on "ok" button, `mRelativeGroupBox` is not visible because its parent is not visible anymore. This PR changes the condition so it works all the time

### CODE REVIEW

**Review by domi4484 — APPROVED** [review]

**Comment by domi4484** [comment]
https://github.com/qgis/QGIS/blob/543831d236489a77c4e1725368c6295f9ff3d031/src/gui/editorwidgets/qgsexternalresourceconfigdlg.cpp#L181 here `isVisible` is also used as condition. Is that not a little dangerous to? would it maybe be better to use the combo box index instead?
btw. thank you for the fix!

**Comment by troopa81** [comment]
> here isVisible is also used as condition. Is that not a little dangerous to? would it maybe be better to use the combo box index instead?

Yes, you're right. Done

**Comment by nyalldawson** [comment]
@troopa81 
> here isVisible is also used as condition. Is that not a little dangerous to? would it maybe be better to use the combo box index instead?

Just to expand on this -- we've had issues when people have used isVisible() for this kind of thing before because that will always be FALSE when the dialog is saving properties as a result of it being closed!

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
(it'd be valuable to do a scan on other uses of isVisible throughout the codebase to see if other widget properties are using this too!)

**Pull request merged**
