### PR TITLE
Update qgis-hackfests.qml with pineapples

### PR DESCRIPTION
**Pull request by mari-s4e**
Added pineapples on pizzas in hackfests layer

### CODE REVIEW

**Comment by saberraz** [comment]
As a HF organiser who only served pizzas to the participants, I totally approve this PR. If anyone gets offended, they can contact me directly.

**Comment by m-kuhn** [comment]
Thank you for supporting the community with enough vitamins 🍍🍍🍍

**Review by m-kuhn — APPROVED** [review]

**Comment by mbernasocchi** [comment]
> As a HF organiser who only served pizzas to the participants, I totally approve this PR. If anyone gets offended, they can contact me directly.

@saberraz you might be forgetting you also served triangle sandwiches :)

**Comment by saberraz** [comment]
Next time, I will upgrade it to Fish & Chips :)

**Comment by raymondnijssen** [comment]
Looking forward to next time!!

**Comment by mbernasocchi** [comment]
Since a PR needs information for the documentation team ;) 
image

**Pull request merged**
