### PR TITLE
[FEATURE]: New geometry classes (take 2)

### PR DESCRIPTION
**Pull request by mhugent**
Test pull request to trigger travis build / test

### CODE REVIEW

**Comment by mhugent** [comment]
Merged this now to avoid another rebase.
The failure of the provider tests is in most cases related to wkt formatting. Will go through them after the feature freeze

**Comment by nyalldawson** [comment]
@mhugent Can you clarify something for me -I'm trying to determine whether the geometry classes are now implicitly shared via QgsGeometryData, or whether this is still a work in progress? I'm also curious as to why you didn't utilise QSharedData for QgsGeometryData and have a QExplicitlySharedDataPointer for the private member?

**Comment by mhugent** [comment]
@nyalldawson: the implicitely sharing of QgsGeometry is not completely finished yet. Hugo has already pointed me to the Qt shared pointer classes in the QEP. It is my next task after fixing the unit tests.

**Comment by nyalldawson** [comment]
@mhugent sounds great - I wasn't sure if you'd run into an issue with the Qt classes which was preventing their use.

**Comment by m-kuhn** [comment]
@mhugent great, looking forward to that!

* Does this work already include (parts of) circular arc support for PostGIS?
* Will you be able to write some API documentation so travis will be green again?

**Comment by m-kuhn** [comment]
@mhugent The SpatialiteProvider test has not been running in the past due to the missing pyspatialite library. I just installed the missing dependency on master and it is failing since. When running it against the last commit before this merge the test completed successfully. It would be great if you could check if this is a side-effect of this merge.

**Comment by m-kuhn** [comment]
@mhugent 

Could you have a look at the failing tests, especially the spatialite one which says "we should have 4 features after 2 split" hence I assume it's related to this.
Some API documentation would also be very good.
It would be great to have a code base that passes the test suite again soon!

Thank you very much!

**Comment by nirvn** [comment]
@mhugent I think this commit led to a serious regression, described here http://hub.qgis.org/issues/12836

**Comment by gioman** [comment]
what about http://hub.qgis.org/issues/12838 ? I'm getting here consistently on master since this commit (or another one nearby), but I don't see anyone else complaining about it.

**Comment by mhugent** [comment]
@nyalldawson : I looked into QSharedDataPointer / QEplicitelySharedDataPointer. One thing where I'm not sure is how to avoid an unnecessary geometry copy in detach() if I know the geometry will be completely replaced directly after. Currently, I'm using QgsGeometry::detach( false ) for that. I see that you have used a workaround in QgsFeature::setGeometry, but I wonder if there is a standard way to do that using the Qt shared pointer classes.

**Comment by nyalldawson** [comment]
@mhugent Something along these lines could work:

- add a bool "detachClonesGeom" to QgsGeometryData
- in the copy constructor for QgsGeometryData check the value of detachClonesGeom - if it's false then the geometry isn't copied, and this flag could be reset to true so that the next detach operation works correctly.
- before calling detach when a geom clone isn't required, just set  detachClonesGeom to false

How's that sound? Some other questions re implicit sharing and the new geometry engine:
- QgsGeometryData should be renamed to QgsGeometryPrivate (to match the pattern for the existing implicitly shared classes in QGIS and Qt) before it gets locked into stable API.
- Why not include mWkb, mWkbSize and mGeos in QgsGeometryPrivate? They'll all be equal for shared geometries, so it makes sense to avoid recalculating these if another QgsGeometry sharing the same private data has already done so.
- I think that QgsGeometryCollectionV2 should be overriding segmentize to return segmentized copies of all the geometries contained in the collection. This should fix segmentizing of a collection which consists of both curved/non-curved geometries...

**Comment by mhugent** [comment]
@nyalldawson
>Something along these lines could work ... How's that sound?

Hm, then I prefer to use the current handwritten QgsGeometry::detach method instead of workaround + QSharedData. The handwritten method is more flexible, that's probably the reason why also many Qt classes internally follow that approach.

 >QgsGeometryData should be renamed to QgsGeometryPrivate (to match the pattern for the >existing implicitly shared classes in QGIS and Qt) before it gets locked into stable API. 

agreed for the renaming ( the private part should not appear in the API )

>Why not include mWkb, mWkbSize and mGeos in QgsGeometryPrivate?

It has pros and cons. The detach takes longer if wkb/geos have to be copied as well. We cannot know if they will be used afterwards, so I don't have a strong opinion on wether to include those or not.

>I think that QgsGeometryCollectionV2 should be overriding segmentize to return segmentized >copies of all the geometries contained in the collection. This should fix segmentizing of a collection >which consists of both curved/non-curved geometries...

True, thanks for the hint.

**Comment by nyalldawson** [comment]
@mhugent thanks for the explanations, they all seem like good choices. Last question - what's the plan for QgsGeometry? Will it be staying around, or deprecated and removed? I'm trying to determine whether it's safe for me to use the implicit sharing of QgsGeometry to solve a tricky problem or whether this will cause issues later if QgsGeometry is deprecated and QgsAbstractGeometryV2 is not implicitly shared...

**Comment by mhugent** [comment]
@nyalldawson: the idea is that QgsGeometry is for old code and new code should use QgsAbstractGeometryV2. I'd like to remove QgsGeometry  in version 3 (will be difficult however as it is used in so many places).

**Comment by m-kuhn** [comment]
>> Why not include mWkb, mWkbSize and mGeos in QgsGeometryPrivate?
>
> It has pros and cons. The detach takes longer if wkb/geos have to be copied as well. We cannot know if they will be used afterwards, so I don't have a strong opinion on wether to include those or not.

The mWkb and mGeos are mainly caches, so the GeosGeom and Wkb do not need to be recalculated repeatedly because it is so costly, if I am not mistaken?

If this assumption is correct, in case they are not detached, they need to be recalculated and I assume that this is a more expensive operation than doing a copy at detach time. Then the main question is, how probable is it that they will be recalculated for the copied geomtry again? @mhugent you probably know how often these are required after working so much on the geometry engine.

For mWkb would it make sense to consider using a QByteArray instead of an unsigned* pointer, so it would be implicitly shared already by itself and a detach could happen quite fast.

**Comment by mhugent** [comment]
mWkb / mGeos were originally just meant for compatibility to keep the old QgsGeometry::asWkb() and geos Methods running.

But if we are looking for performance in 2.10, it will be best to copy on detach and to store the wkb when passed to QgsGeometry::fromWkb(), which is currently not done. Then there is a performance advantage for the standard case (fetch wkb from provider, get it for rendering) with mWkb copied in detach. In this usage, the new QgsAbstractGeometryV2 is not used at all for rendering (snif), so it is sort of fallback to old geometry behaviour. But for 2.10 it will be ok. In 2.12, it will be different (QgsAbstractGeometryV2::draw will be used).

Regarding QByteArray: the mWkb / mGeos is really something to go away with time, so I'd just include the pointer into GeometryPrivate and leave it as is.

**Comment by m-kuhn** [comment]
Thinking about it again... The geometry should only be detached when it's being changed. An in this case the caches will be invalidated anyway soon after the detach. So it does not make much sense to copy it on detach.

But it does make sense to keep it shared in shallow copies.
Does that make sense?

> Regarding QByteArray: the mWkb / mGeos is really something to go away with time, so I'd just include the pointer into GeometryPrivate and leave it as is. 

Who has the ownership of this pointer?

**Comment by mhugent** [comment]
Yes, it makes no sense to copy them. Furthermore, in a normal rendering workflow ( geometry rendering and labeling), the detach copy is not used.
But it makes sense to store the wkb pointer (QgsGeometryPrivate has ownership)

**Comment by m-kuhn** [comment]
Maybe I am missing a point.
But if a detach happens, QgsGeometryPrivate will be copied and if the pointer is copied without copying the data behind there will be two QgsGeometryPrivate instances assuming ownership.

**Comment by mhugent** [comment]
If a detach happens, a new instance QgsGeometryPrivate will be created in case several QgsGeometry are pointing to it. And the wkb pointer of the new instance will be set to 0, so there is no problem with ownership.

**Comment by m-kuhn** [comment]
That sounds good, thanks for the clarification.

**Comment by nyalldawson** [comment]
@mhugent I've been thinking about this, and have come to the conclusion that QgsGeometry should be kept around as a geometry "container". Here's my rationale:
- it's already implicitly shared (thanks!), so most of the work is already done
- in order for us to take advantage of implicit sharing of geometries, we need an instantiable class for geometries. A stripped back QgsGeometry which acts just as a container for the QgsAbstractGeometryV2 (via QgsGeometryPrivate) would work for this.

**Pull request merged**
