### PR TITLE
Rework QgsNetworkAccessManager::requestAboutToBeCreated() to be thread safe

### PR DESCRIPTION
**Pull request by nyalldawson**
... and encapsulate more useful request information

An alternative approach to #8907

### CODE REVIEW

**Review by elpaso — APPROVED** [review]

**Comment by rduivenvoorde** [comment]
@nyalldawson @elpaso  is this still supposed to work for network requests in different threads?

I've compiled this PR (and now compiling master), but with my plugin (and connecting both requestAboutToBeCreated and requestCreated with the same signature I had, I had crashes when connecting to for example a wfs like:

https://geodata.nationaalgeoregister.nl/bestuurlijkegrenzen/wfs?request=GetCapabilities&service=wfs&version=2.0.0

When I do NOT connect to the requestAboutToBeCreated but ONLY to requestCreated, I get errors like this in the Qt tab: 

> QObject: Cannot create children for a parent that is in a different thread.
>              (Parent is QgsWFSFeatureIterator(0x7fb9fc0c9b10), parent's thread is QThread(0x55e4e7157860), current thread is QThread(0x7fb9ec001fd0)

If I connect to request_about_to_be_created(request_params) signature I see I receive an Operation object. So apparently not connecting to the right signal?

Should I add some signature via annotations? I tried `@pyqtSlot(QgsNetworkRequestParameters)`
Or am I missing sip bindings?

**Comment by nyalldawson** [comment]
Does 

    QgsNetworkAccessManager.instance().requestAboutToBeCreated[QgsNetworkRequestParameters].connect(...) 

Work?

See https://stackoverflow.com/a/11178796/1861260

**Comment by rduivenvoorde** [comment]
YES, thanks. Then I connect to the right signature and get a QgsNetworkRequestParameters back \o/

Note that using the other notation:
`@pyqtSlot(QgsNetworkRequestParameters)`
I get the following error, as if that signature is not yet known:

`TypeError: decorated slot has no signature compatible with requestAboutToBeCreated(QNetworkAccessManager::Operation,QNetworkRequest,QIODevice*) `

I still see the different thread Warnings when using a WFS (and only WFS):

```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QgsWFSFeatureIterator(0x7fb9fc0c9b10), parent's thread is QThread(0x55e4e7157860), current thread is QThread(0x7fb9ec001fd0)
```

Which if I remember were remove with this part (from elpaso) of the old pr:
`qRegisterMetaType<QNetworkAccessManager::Operation>( "QNetworkAccessManager::Operation" );
` 
but I'm not 100% of that...

Sometimes if I only load the above WFS (layer 'provincies') and want to stop QGIS I see ?

gnome-shell-screenshot-to83vz

And it is hard to stop QGIS then..
After getting some ows services, and closing QGIS is stop is showing a crash (LWP?)

Another observation: when you undock the messages window (have it floating around), and click on a link, that link is beautifully opened in the browser, BUT the messages window is then closed?

Sorry for this messy reports...

**Comment by rduivenvoorde** [comment]
I'm not really sure, but in my old plugin I connected to 4 signals:
- requestAboutToBeCreated (QGIS)
- requestCreated (also QGIS I think)
- requestTimedOut (?)
- finished (Qt http://doc.qt.io/qt-5/qnetworkaccessmanager.html#signals)

If I do this now, I only can connect to (for example) the finished of the main thread isn't it?
So currently (please correct me if wrong), only the requestAboutToBeCreated(QgsNetworkRequestParameters) is safe and working in QGIS. 
IF we want (eg in the future DebugWindow) show the reply of a request when finished (or the MimeType/header of the reply) we have to add this?
If so, should I add some lines of warning/doc to the code then?

**Comment by nyalldawson** [comment]
@rduivenvoorde see #8952 . I haven't done anything with requestCreated, as I cannot see any valid use case for that signal which isn't addressed by requestAboutToBeCreated (it's basically identical).

**Comment by nyalldawson** [comment]
@rduivenvoorde 

> I still see the different thread Warnings when using a WFS (and only WFS):

Could possibly be related to the timeout handling. I've seen this issue too in the past. It's unrelated to this work.

Stats task is also unrelated, and should be filed as an issue.

**Pull request merged**
