### PR TITLE
Don't use invalid xml values as attribute names

### PR DESCRIPTION
**Pull request by m-kuhn**
Fixes #14136

### CODE REVIEW

**Comment by m-kuhn** [comment]
@SebDieBln what do you think?

**Comment by SebDieBln** [comment]
Yes, that will do the job. Nice!

How do you feel (in general, not as part of this PR) about [`QDomImplementation::ReturnNullNode`](http://doc.qt.io/qt-4.8/qdomimplementation.html#InvalidDataPolicy-enum)? _Fail fast?_

**Comment by m-kuhn** [comment]
> How do you feel (in general, not as part of this PR) about QDomImplementation::ReturnNullNode? Fail fast?

I like it. But I'm afraid of introducing it so close to a release. Probably something to merge just after the feature freeze is lifted. If we make good experiences we can still backport it to a patch release.

**Comment by SebDieBln** [comment]
> I like it. But I'm afraid of introducing it so close to a release.

Of course, I just wanted to spread the idea of using it sometime in the future.

**Pull request merged**
