### PR TITLE
Use pg initialization script from Travis

### PR DESCRIPTION
**Pull request by strk**

### CODE REVIEW

**Comment by strk** [comment]
I hadn't seen the osx version use the PG initialization scripts, does it mean OSX does not test PostGIS at all ?

**Comment by strk** [comment]
btw, it would actually be good to use this script as part of "make check", when no "qgis_test" is found (and when ENABLE_PGTEST is set)

**Comment by strk** [comment]
So it turns out the data files are dumps from a PostgreSQL > 9.1 and as such not supported by Travis.
Interesting, isnt' it ? :)

One option would be re-generating those dumps from a 9.1 database (such dumps should be compatible wiht any later version).

Another option would be keeping those datafiles simpler, manually tweaking them.

**Comment by m-kuhn** [comment]
Yeah, simplifying them sounds good.

**Comment by strk** [comment]
Rebase-pushed as 034b5c0be5703e1e039476ba0b4932cc1da7db23 and bfcf92f728fa374deb2f5f01f2dbfe7de0c14040

**Pull request closed without merging**
