### PR TITLE
[Travis] bump Qt to 5.9 

### PR DESCRIPTION
**Pull request by 3nids**
* bump Qt to 5.9 and SIP to 4.19.7 by using coming Bionic as base Docker image for dependencies
* automatically build QGIS Docker image on cron jobs

### CODE REVIEW

**Comment by nirvn** [comment]
@3nids , it seems this PR has created an issue with ccache, travis dies after >1 hour without having completed a build.

**Comment by 3nids** [comment]
@nirvn this didn't change anything to ccache. As far as I understand it, the cache is not valid anymore because we use a new base OS (bionic). But what is strange is that it was builiding fine in its own branch but not in master anymore.
What would be needed is to copy the cache before it times out so we can restart the build with the cache.
@m-kuhn any idea here?

**Comment by 3nids** [comment]
@nirvn https://github.com/qgis/QGIS/pull/6488
Let's see how it goes! Credits to @m-kuhn in Macos builds

**Comment by 3nids** [comment]
@nirvn now Travis will stop the build in Time to save the cache!

**Pull request merged**
