### PR TITLE
[Server] Handle bad layers at QGIS project laoding and throw exception

### PR DESCRIPTION
**Pull request by rldhont**
## Description
This commit return exceptions if a layer is not available like other servers (e.g. UMN) and prevents caching of projects with missing datasources (a datasource may become available later on).

It is part of #8922 _Server: catch datasource error_ and probably replacing  #9990 _Server: catch datasource error for release-3_4_

## Checklist

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rldhont** [comment]
@mhugent @elpaso @pblottiere are you agree with this change for release-3_4 ?

**Review by mhugent — APPROVED** [review]

**Comment by rldhont** [comment]
Thanks @mhugent

**Comment by dassau** [comment]
Hi, I would like to discuss this change again, because from my perspective it is a problem to stop a complete qgis project from loading if "only" one layer is not available. An Example: In many webgis projects we integrate lots of external services and often one or some of them are not accessible for several reasons (typical situation at least in Germany). These layers of course provide information but are not as important to make the complete webgis project unusable and our customers always complain and prefer to have all other availabe layers visible and skip the bad one for a while. I understand the reasons described in https://github.com/qgis/QGIS/pull/8922 but think that the situation was better before - so is there a chance to revert this commit for the future?

**Comment by elpaso** [comment]
@dassau I see your point, perhaps it might better be optional: flag a layer with "required" or something like that to make sure we get an exception if the layer is missing but be tolerant to missing layers in the general case.

**Comment by gioman** [comment]
@dassau thanks Otto for raising this discussion. This change is in fact biting a lot of users that are unaware of it.

**Comment by mdouchin** [comment]
What about a environment variable to have a global behaviour and let the admin sys choose what is best suited for the local context. For example `QGIS_SERVER_ALL_LAYERS_REQUIRED`, default to True.
This way there would be no need to change the behaviour layer per layer, nor project per project, but only once for the server.

**Comment by elpaso** [comment]
@mdouchin that's also an (much simpler) option, it depends on the granularity level you need. I have no strong opinions here.

**Comment by dassau** [comment]
Thanks for your quick relies and I agree, it would be nice to make it configurable, since both situations have their advantages and disadvantages, so admins can decide...

**Comment by dassau** [comment]
Hi, what would be the next step to have such an option in QGIS 3.10.x ? I won't be able to implement it myself.

**Comment by elpaso** [comment]
@dassau I think that you have the usual options: https://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis/

**Comment by dassau** [comment]
@elpaso who in your opinion would be the right person to contact to have it changed as a paid job?

**Comment by pblottiere** [comment]
Hi @dassau,

> who in your opinion would be the right person to contact to have it changed as a paid job?

I think you can contact @elpaso himself. He's very involved in QGIS Server development.

**Comment by elpaso** [comment]
@dassau yes, we (QCooperative.net) could definitely help, but there are quite a few other very active developers on the server that you could contact (if I omit anyone please don't be offended, it wasn't intentional), these come to my mind:
- @rldhont for 3liz
- @haubourg (as a contact for Oslandia)

Any other active QGIS core developer would be skilled enough for this task too but it's impossible to mention them all, there is a list of QGIS friendly companies here: https://www.qgis.org/en/site/forusers/commercial_support.html?highlight=commercial#core-contributors but not all of them have core developers in their staff.

**Comment by elpaso** [comment]
I'm working on it!

**Pull request merged**
