### PR TITLE
[processing] Add QGIS 3d provider

### PR DESCRIPTION
**Pull request by nyalldawson**
Adds a new QGIS processing provider for 3d algorithms, available only when QGIS is built WITH_3D

Currently includes only a single algorithm for tesselating geometries, which exposes the functionality of QgsTesselator to processing.

Like the native c++ algorithm provider, algorithms in the 3d provider are transparently merged with the other QGIS providers (i.e. they aren't separated into their own group)

While trying to diagnose bugs in the 3d view I thought it would be much easier to visually see what the tesselator is doing if we had an algorithm like this available. So aside from being useful in itself, it'll also be very valuable for bug tracking.

E.g. - the following tesselated polygon is quite clearly broken!!

untitled

(WKT is

```Polygon ((497748.82712168345460668 7050890.38225104287266731, 497749.00319719384424388 7050890.85545397642999887, 497749.49840956681873649 7050891.20760499779134989, 497749.96611014130758122 7050891.32865691091865301, 497750.42830835608765483 7050891.40018758736550808, 497751.28117410949198529 7050891.2351167956367135, 497751.83141007949598134 7050891.14157668128609657, 497752.33212481217924505 7050890.95999881066381931, 497752.67327111354097724 7050890.76191386207938194, 497752.85484898363938555 7050890.481293517164886, 497753.01441741490270942 7050890.16215665452182293, 497753.11896224919473752 7050889.79900091420859098, 497753.20700000441865996 7050889.38082157727330923, 497753.22900944319553673 7050889.05618235468864441, 497753.25652124168118462 7050888.64900773763656616, 497753.09695281041786075 7050888.24183311965316534, 497752.99791033583460376 7050887.97771985363215208, 497752.86585370305692777 7050887.78513726405799389, 497752.48068852402502671 7050887.62006647326052189, 497752.18356110027525574 7050887.55403815675526857, 497751.62232041091192514 7050887.54303343780338764, 497751.23715523193823174 7050887.6310711931437254, 497750.84648769325576723 7050888.47293222695589066, 497750.868497132032644 7050888.88010684493929148, 497750.67591454257490113 7050889.32579798065125942, 497750.48883431276772171 7050889.73847495764493942, 497750.2742422844748944 7050890.0301000215113163, 497749.86706766672432423 7050890.14564957562834024, 497749.3278364161378704 7050890.14014721568673849, 497749.03621135203866288 7050890.14014721568673849, 497748.95917831623228267 7050890.16215665452182293, 497748.82712168345460668 7050890.38225104287266731))```

### CODE REVIEW

**Comment by nyalldawson** [comment]
Actually - all good. The bad tesselation was due to not setting the origin for the tesselation correctly. That's fixed now and the outputs look good.

**Review by wonder-sk — COMMENTED** [review]
Great idea!

Looks good to me. I have just one note - it seems tessellation is spelled with double L...

**Comment by nyalldawson** [comment]
> Looks good to me. I have just one note - it seems tessellation is spelled with double L...

Oops. Fixed and added to spell checker. Seems I'm not the only one who's made this mistake!

**Comment by nyalldawson** [comment]
Test failure is unrelated - caused by a doxygen change on Travis

**Pull request merged**
