### PR TITLE
[Bugfix] [Processing] Catch some python errors in batch mode

### PR DESCRIPTION
**Pull request by Gustry**
# Problem

If the user clicks on "cancel" or if the JSON file is not valid, a python exception was raised.

I've updated an error message in the modeler too.
# CC

@volaya @alexbruy

### CODE REVIEW

**Comment by Gustry** [comment]
Can someone relaunch the linux build ? Thanks

**Comment by Gustry** [comment]
@volaya and @alexbruy Is there any reason why is not going to be merged for 2.14 in a few hours ?

**Comment by volaya** [comment]
looks good to me. Sorry that i did not review it before

**Comment by Gustry** [comment]
Thanks @volaya 
@luipir This fix was related to some GUI tools (after a click on the save button) so  I don't think there is any problem about the MessageBox.

**Pull request merged**
