### PR TITLE
Windows Qt6 builds based on vcpkg

### PR DESCRIPTION
**Pull request by m-kuhn**
## Description

Refs https://github.com/qgis/QGIS-Enhancement-Proposals/issues/292
Continues https://github.com/qgis/QGIS/pull/57414

This adds windows builds with Qt6, based on vcpkg dependencies.

The features `WITH_BINDINGS`, `WITH_3D` and `WITH_GUI` are supported and appropriately enable or disable building the required dependencies. Feature dependencies for server, opencl and quick are prepared but not yet wired.

Python support is consumed from https://github.com/open-vcpkg/python-registry/ . This is currently focused on shipping python dependencies that contain native code (dll's). Other dependencies can be installed using pip.

It is currently based on Qt 6.7.2

This also disables the mingw msys2 build, to reduce the CI infrastructure footprint. The other mingw builds which provide testable qt5 builds are still produced.

TODO:

- [x] write ~README~ INSTALL.md

### CODE REVIEW

**Review by nyalldawson — APPROVED** [review]

**Comment by nicogodet** [comment]
I tried the output build, I had to manually install numpy, urllib3, markupsafe and requests with pip to have a qgis without error at opening on a fresh profile.

I encounter some crashes (I tried to reproduce https://github.com/qgis/QGIS/issues/53806 and it crashes when trying to set output path at opening expression dialog).

**Comment by m-kuhn** [comment]
Thank you @nicogodet 

Regarding the python dependencies, I'm planning to come up with a follow up pull request to take care of these. I'm right now in the process of doing a mass update of python libs here https://github.com/open-vcpkg/python-registry/pull/42

Regarding the crash, I'm not (yet) able to tell where this comes from. Qt6 support is still experimental and I think we'll want to keep these things in new issues which can be treated in the following months while stabilizing Qt6 support.

**Comment by nicogodet** [comment]
@m-kuhn crash reported here https://github.com/qgis/QGIS/issues/59003

**Comment by m-kuhn** [comment]
I'll proceed and merge this and follow up with a pull request to improve the python situation

**Comment by MehdiChinoune** [comment]
I think cross-building on Fedora/mingw-w64 should be disabled instead of native building on MSYS2/mingw-w64.

**Comment by m-kuhn** [comment]
@MehdiChinoune no strong opinion on my side. I was just preserving the build that was published as pull request comments. Should we switch this to MSYS2/mingw-w64 (and if yes, what's better about it)?

**Comment by tsmcgrath** [comment]
@nicogodet See this comment for getting the freeze repro to run:
https://github.com/qgis/QGIS/issues/53806#issuecomment-2381336137

**Comment by agiudiceandrea** [comment]
Hi @m-kuhn, I've started to use the Windows Qt6 builds in order to test bugs/fixes in PRs for Qt6. It looks like it has issues with CRS handling: it doesn't recognise the layers' CRS...

image


See, instead, the mingw64 build:

image

**Pull request merged**
