### PR TITLE
Make QgsCoordinateTransform implicitly shared, no longer a QObject

### PR DESCRIPTION
**Pull request by nyalldawson**
Phew... this was a bit painful. Anyway, this PR makes QgsCoordinateTransform objects implicitly shared (woooo!) and no longer QObjects (bigger woooo!). See https://github.com/qgis/qgis3.0_api/issues/46

There was no code in core using the signals/slots associated with QgsCoordinateTransform, and little reason to keep the class a QObject. Making it not a QObject simplifies code and allows QgsCoordinateTransform objects to be easily copied and passed around without complication. And now that they're implicitly shared, it's inexpensive to do so.

This breaks any code which relies on the signal from QgsCoordinateTransform (I suspect no one is using this), and using the slots in connections (again, I suspect no-one would be doing this). 

I'm going to follow this up with a cleanup of the  QgsCoordinateTransform api, and removal of all QgsCoordinateTransform\* and QgsCoordinateTransform::clone use.

### CODE REVIEW

**Comment by nyalldawson** [comment]
I've pushed some follow up API breaks:

- clone() has been removed, direct copies should be used instead
- isInitialised() has been renamed to isValid()
- theCRS parameter in setSourceCrs has been renamed to 'crs'
- setDestCRS() has been renamed to setDestinationCrs() for consistency
- destCRS() has been renamed to destinationCrs() for consistency
- theSource, theDest, theSourceSrsId, theDestSrsId, theSourceWkt,
theDestWkt, theSourceCRSType parameters in the QgsCoordinateTransform
constructors have been renamed to source, destination, sourceSrsId,
destinationSrsId, sourceWkt, destinationWkt, sourceCrsType respectively
- 'p' argument in transform() has been renamed to 'point', 'theRect' to
'rectangle', 'poly' to 'polygon'
- setDestCRSID has been removed, use setDestinationCrs() instead
- 'theNode', 'theDoc' parameters in readXML and writeXML have been
renamed to 'node' and 'document' respectively
- readXML() and writeXML() have been renamed to readXml() and writeXml()
for consistency

Additionally ALL use of QgsCoordinateTransform pointers have been replaced with references or copies. This strengthens code and removes some tricky ownership handling. It also potentially fixes leaks (at least one I identified in server).

**Comment by wonder-sk** [comment]
:thumbsup: Excellent stuff!

**Comment by nyalldawson** [comment]
@wonder-sk is that a +1 to "merge as is"? No changes you'd like to see?

**Comment by wonder-sk** [comment]
Yeah looks good as is - feel free to merge

**Comment by m-kuhn** [comment]
Sounds all good to me!

**Comment by nyalldawson** [comment]
Thanks!

**Comment by m-kuhn** [comment]
> Thanks!

Thanks to you!!

**Pull request merged**
