### PR TITLE
Update GxGSV - NMEA 4.10

### PR DESCRIPTION
**Pull request by bettellam**
In NMEA version 4.10, there is an additional parameter in the GxGSV message: signal_id.
Small update of the NMEA parse.

### CODE REVIEW

**Comment by nyalldawson** [comment]
@bettellam 
> In NMEA version 4.10

Where do you source these changes? I've struggled to find a good, up-to-date site for this specification...

**Comment by bettellam** [comment]
> @bettellam
> 
> > In NMEA version 4.10
> 
> Where do you source these changes? I've struggled to find a good, up-to-date site for this specification...

@nyalldawson 
https://gpsd.gitlab.io/gpsd/NMEA.html#_gsv_satellites_in_view
See the note in the paragraph.
This also applies to GPGSA.
Currently `satinUse` and `satinView` are calculated improperly for receivers that output NMEA 4.10.
GPGSA and GPGSV report satellite ID in reference to the signal_id
(currently double satellite ID are ignored/deleted)

I would like to bring another change to GPGGA to align `quality` and `qualityIndicator `to the values ​​expressed by GPRMC

**Comment by bettellam** [comment]
image

**Comment by bettellam** [comment]
@nyalldawson  I think a future code review will be needed for calculating satinUse satinView and plot-signal and plot-satinView graphs

**Comment by bettellam** [comment]
I rewrite the pull request

**Pull request closed without merging**
