### PR TITLE
Use a monospaced font in console command history list

### PR DESCRIPTION
**Pull request by nyalldawson**

### CODE REVIEW

**Comment by nirvn** [comment]
Good idea. Did you need the color scheme import in there too?

**Comment by nyalldawson** [comment]
> Did you need the color scheme import in there too?

It would be nice, but I'm not sure how to do this in a list widget. (Trying to use the code editor as a delegate will be far too expensive)

**Comment by nirvn** [comment]
I see, so the import is aspirational in nature ;) it'd be nice indeed but if too costly maybe not worth it. Monospace is a nice touch either way.

**Comment by nyalldawson** [comment]
The import is already there... I just messed with the formatting of it :laughing:

**Review by nirvn — APPROVED** [review]

**Pull request merged**
