### PR TITLE
Add title case conversion to QgsStringUtils, use to fix processing HIG violations

### PR DESCRIPTION
**Pull request by nyalldawson**
This adds a super-basic title case conversion method to QgsStringUtils. It's not a full grammar parser (which is needed if you want real title case conversion!), but good enough for simple use cases.

Here I've used it to fix some HIG violations in Processing menus. Since algorithm display names are sentence case, we need to convert them to title case when they are shown in menus and for dialog titles (or risk the wrath of the HIG gods).

I've also taken the opportunity to fix another plugin HIG issue with the menu - which is that many core plugins create single-item submenus. E.g. Raster -> Georeferencer -> Georeferencer. This is a HIG violation, and these items should be top-level instead (e.g. just Raster -> Georeferencer).

### CODE REVIEW

**Comment by nirvn** [comment]
@nyalldawson , nice stuff. 

I was thinking last night, it'd be nice for processing to sort the sub-menu items (based on their actual translated names) after populating those. Could this be done?

**Comment by nirvn** [comment]
And big +1 for commit fe0bb6c.

**Comment by nyalldawson** [comment]
> I was thinking last night, it'd be nice for processing to sort the sub-menu items (based on their actual translated names) after populating those. Could this be done?

Should be possible - but I'll leave that to a follow up work

**Comment by nirvn** [comment]
@nyalldawson , just compiled this branch, it's a very nice improvement. One more part of processing which just ended feeling foreign to QGIS' UI/UX :wink:

**Comment by nyalldawson** [comment]
Thanks for the confirmation @nirvn!

**Pull request merged**
