### PR TITLE
Fix virtual fields that use functions requiring all attributes

### PR DESCRIPTION
**Pull request by 3nids**
the requested fields to evaluate the virtual field where not fetched if only the virtual field was requested at the request creation

### CODE REVIEW

**Review by troopa81 — APPROVED** [review]
Looks good to me. Thanks!

**Comment by m-kuhn** [comment]
I'd love to have a review by someone here.

Short problem statement.
A virtual fields obviously cannot depend on "itself", this will lead to an infinite recursion.
So we detected so far always if it's itself in "referencedFields()", however, if it's definition contains a method that requires all attributes (like `eval` or others), it would also report itself, be detected as recursive and return NULL always.

So this PR updates the code to not check for recursive dependencies (because there is no way we can always check that on prepare time, it's simply impossible).
And instead add a thread local recursion guard which is triggered when we have more than 255 nested feature iterators open.

**Comment by troopa81** [comment]
> if it's definition contains a method that requires all attributes (like eval or others), it would also report itself, be detected as recursive and return NULL always.

I cannot reproduce what you're describing here with current master. I try it with a simple layer containing two fields `a`, and `b`, and try to create a virtual field `c` with the expression `eval('a+b')` and it works. 

What is your issue use case? Is it when you have reference to other attribute layer (with get_feature for instance)?

**Comment by m-kuhn** [comment]
Try `eval('a')`

**Comment by m-kuhn** [comment]
It will already work, if the required attributes are requested for some reason (e.g. in the attribute table, the feature will be requested fully populated, and the expression succeeds.

Try running the following code on your sample layer:

```
request = QgsFeatureRequest()
request.setSubsetOfAttributes(['c'], layer.fields())
feature = next(layer.getFeatures(request))
feature['c']
```

**Comment by troopa81** [comment]
OK, I think I understand, thanks. 

Wouldn't be possible to keep track of the "computed field call stack" in the thread storage to detect circular reference, instead of just keeping an int and stopping at 255 ?

We could push the current evaluated fieldIndex in a QStack in the thread storage. Before preparing expression, we check that it's not already in the stack. It should work with case like "test2 = sum(test2)"

**Comment by m-kuhn** [comment]
This would need to be a combination of layer and field (index or name). This is probably a good idea for debugging purpose.

**Comment by m-kuhn** [comment]
Actually, it's not even related to the field any more. It's just checking that we do not have more than max stack depth (255) features being fetched nested. We have no handle there as to what (or which field) caused this.

I was thinking about throwing an exception, but suddenly have "fetchFeature" throwing an exception seems risky.

**Comment by troopa81** [comment]
> This would need to be a combination of layer and field (index or name)

Yes, indeed

> Actually, it's not even related to the field any more. We have no handle there as to what (or which field) caused this.

Why is that ? As we evaluate complex expression, we always go through `prepareField` method so we know the field and layer evaluated for the current stack. No?

**Comment by m-kuhn** [comment]
See https://github.com/qgis/QGIS/pull/30972#issuecomment-531386574

> So this PR updates the code to not check for recursive dependencies (because there is **no way we can always check that on prepare time**, it's simply impossible).

With the latest commit, most recursions will be detected at evaluation time, in which case it will report the layers. If the recursion is already detected at prepare time, it will report the field as well. Does this look good to you?

**Comment by troopa81** [comment]
I give it a try to better understand the issue. 

I think the guard in prepareExpression is never used. The localStorage is always empty, because prepareExpression always finish (and pop locatStorage data) without calling itself recursively directly or indirectly. And so, as you said, it's not possible to do any check on prepare time.

The fix doesn't work because I fail to acquire ogr connection in QgsConnectionPool while calling recursively fetchFeature.

I was thinking about [this](https://github.com/troopa81/QGIS/blob/test_fix_recursive_expression/src/core/qgsvectorlayerfeatureiterator.cpp#L436) to solve the issue and prevent the use of the number 255. It seems to work, but I tested it poorly. It raise an error message with expression like with `test2=sum(test2)` and `test2=eval('sum(test2)')`.

Hope it helps.

**Comment by m-kuhn** [comment]
> I think the guard in prepareExpression is never used. The localStorage is always empty, because prepareExpression always finish (and pop locatStorage data) without calling itself recursively directly or indirectly. And so, as you said, it's not possible to do any check on prepare time.

Wouldn't it be possible that the nested prepare expressions prepares yet another iterator, recursively?

https://github.com/qgis/QGIS/pull/30972/files#diff-d2d2d088f36a3991d43cc9b57101bf5fR723

> The fix doesn't work because I fail to acquire ogr connection in QgsConnectionPool while calling recursively fetchFeature.

Can you elaborate on what's wrong here?

My idea was
 * to be more generic than just virtual fields and catch *any* infinite recursion (but right now I fail to come up with a scenario apart from virtual fields, so that might be a non issue)
 * to not disable recursion completely, and just block infinite recursion. Just like python etc do:

```
>>> def a():
>>>     return a()
>>> 
>>> a()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in a
  File "<stdin>", line 2, in a
  File "<stdin>", line 2, in a
  [Previous line repeated 996 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by troopa81** [comment]
> Wouldn't it be possible that the nested prepare expressions prepares yet another iterator, recursively?

I would say no. I take a quick look and it doesn't seem that any `prepare` expression node method use QgsVectorLayerIterator. And it will be odd that you call an iterator while you are preparing an expression. But, I can't be sure, maybe it's better to check.

> Can you elaborate on what's wrong here?

I made a test with a GeoPackage file and the condition `test2=sum(test2)` and it stops [here](https://github.com/troopa81/QGIS/blob/test_fix_recursive_expression/src/core/qgsconnectionpool.h#L110). 

My guess is that every time a QgsVectorLayerIterator is created (recursively) it tries to acquire an OGR connection to the file. But the connection is limited and so the acquire method waits until a connection will be released which won't happen because we are in the recursive loop. The guard limit (255) must be below the connection limit and won't break the recursive loop.

> My idea was  to be more generic

Yes, why not. It has the advantage to catch all scenarios even the one I can't imagine now. On the other hand, if it's less generic, we are able to stop the recursion sooner and display a more specific message ("There is a recursion on test2 field" for instance). 

I'm ok with both ways, just need to deal with the blocking acquire connection issue if you pick the generic ways.

**Comment by m-kuhn** [comment]
Thanks everyone for the help and reviews

**Pull request merged**
