### PR TITLE
Make network authentication request handling thread safe

### PR DESCRIPTION
**Pull request by nyalldawson**
...avoid races and crashes when auth requests occur in non-main thread

Like the recent SSL error handling, this commit abstracts out the network authentication handling into a thread safe approach.

I also need to do this for the proxy authentication handling -- but I can't find any way to actually TRIGGER that. Does anyone have an example proxy server which causes the authentication request to show?

### CODE REVIEW

**Comment by nyalldawson** [comment]
Ouch - so this has revealed an existing deadlock in the WFS provider when an authentication request is fired off (and likely when SSL errors are encountered too)...

**Comment by nyalldawson** [comment]
Ok, I **********think******** this fixes everything, and makes network requests properly thread safe when authentication requests are fired.

* Except for proxy authentication, but that seems totally broken at the moment anyway. I'll look into this after this PR is merged.

This fix also allowed resurrection of the blocking network request API from earlier in 3.6.

**Comment by nyalldawson** [comment]
@nirvn would you mind testing this? You seem to be able to stress these providers out and identify regressions quickly! :smile: 

@wonder-sk can I get your expert eyes on this one too?

**Comment by nyalldawson** [comment]
@nirvn what say we merge this one now? I'm confident given our stress testing from today that things are working well.

**Comment by nirvn** [comment]
@nyalldawson , I agree, go ahead.

**Pull request merged**
