### PR TITLE
Shorten pull request template

### PR DESCRIPTION
**Pull request by m-kuhn**
## Description

This shortens the pull request template.

Let's assume that most people will not be able to rewrite their git history, so for giving hints for commit messages it's too late and some things are better specified on PR level than on commit level anyway. Some commit message related suggestions are left for educational reasons.

## Checklist

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `Fixes #11111` at the bottom of the commit message
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit
- [ ] I have evaluated whether it is appropriate for this PR to be backported, backport requests are left as label or comment

### CODE REVIEW

**Comment by m-kuhn** [comment]
CC @DelazJ

**Comment by DelazJ** [comment]
LGTM. Simpler, with just the necessary. Thanks.
I guess it preludes your grant proposal.

**Comment by m-kuhn** [comment]
Thanks for the feedback @DelazJ 
It wasn't triggered by the grant proposal, but while working on this PR I realized that there's a connection.

**Comment by nirvn** [comment]
@m-kuhn , somewhat related: while I had no issue with adding the backport checkboxes per say, seeing live has me wondering whether we should remove them.

The issue has to do with it meaning an less than 100% check count when looking at PRs through the list. Makes it more difficult to spot which PRs have required steps missing.

An alternative checkbox could be [x] I have evaluated whether it is appropriate for this PR to be backported. Rely on labels for actual requests.

**Comment by m-kuhn** [comment]
@nirvn good point which expands to a more generic requirement of having the checkboxes being formulated in a way they are applicable to every single pull request.

**Pull request merged**
