### PR TITLE
Geometry Checker and Geometry Snapper plugins

### PR DESCRIPTION
**Pull request by manisandro**
This commit adds the geometry cleaning plugins, initially presented at the Hackfest in Denmark (see also second part of [1]).

Due to the fact that GEOS does not expose its precision reducer functionality in the C API, these plugins make QGIS require the C++ GEOS API.

This is a pretty fresh port of the version using the old geometry core, and despite initial testing looking good, it is not as thoroughly tested in the wild as our previous version. But I'd like to propose it now to have this available in QGIS 2.12 (having announced that target here and there).

Funded by Canton Solothurn / Sourcepole QGIS Enterprise

[1] https://drive.google.com/file/d/0B46kztqdEkOHOWJOSWJ4QXk4ZFk/view

### CODE REVIEW

**Comment by nyalldawson** [comment]
@manisandro not sure if you're signed up for Travis notifcations, but there's a number of build failures and warnings with this PR - see http://dash.orfeo-toolbox.org/viewBuildError.php?buildid=199243 and http://dash.orfeo-toolbox.org/viewBuildError.php?type=1&buildid=199243

**Comment by manisandro** [comment]
@nyalldawson Expected I'm afraid, since the C++ API of geos is required. I've added a commit to make it optional, though the tools are then more likely to stumble on precision related issues in the geometry.

**Comment by nyalldawson** [comment]
@manisandro why not add the new dependency to the ci/travis/linux/before_install.sh script?

**Comment by manisandro** [comment]
Cause I didn't realize it was that simple... Done.

**Comment by gioman** [comment]
Very important addition. Right now we have two different geometry/topology checker tools (one in the vector menu, a python tool, and the topology checker (c++) plugin), that usually return inconsistent and even wrong results, and no one to actually fix them (at least without using external tools GRASS v.clean). The tools would work also without C++ API of geos?

**Comment by manisandro** [comment]
They do (a1d1e32), but I don't recommend it: when fixing errors involves performing analysis operations (intersections, differences, etc), if the reduced precision mode is not available, small spikes often tend to appear where intersections / differences are performed, or unions fails because the geometries are incorrectly seen as disjoint.

**Comment by manisandro** [comment]
@nyalldawson Do I see correctly that the check failure is caused by warnings in the code? How can I see which warnings were emitted?

**Comment by nyalldawson** [comment]
@manisandro the Travis build log and test results are submitted to dash:
http://dash.orfeo-toolbox.org/index.php?project=QGIS

There's a link in the Travis log to the specific build results, but it's usually easiest just to look at the recent builds for one with your branch name. There'll be 2, one for OSX and one for Linux. In this case the linux build warnings are shown at:
http://dash.orfeo-toolbox.org/viewBuildError.php?type=1&buildid=199418

And the failing tests on OSX at http://dash.orfeo-toolbox.org/viewTest.php?onlyfailed&buildid=199420.

It's likely when the Linux warnings are fixed that your changes will then trip the documentation coverage test , as you've added public/protected members without doxygen strings. So that'll need to be addressed too before Travis will greenlight this.

**Comment by manisandro** [comment]
One test which is failing is the centroid of a self-intersecting polygon: `POLYGON((0 0, 0 2, 2 -0.1, 2 2.1, 0 0))`. To determine why the result changed, one would need to dig into GEOS to determine what effect reduced precision has on centroid computations, however I wonder whether centroids of such geometries is really something we should be testing? Also considering [1]: "Sorry but by contract you can't expect valid answers for invalid polygons. "

[1] http://trac.osgeo.org/geos/ticket/596

**Comment by nyalldawson** [comment]
> One test which is failing is the centroid of a self-intersecting polygon: POLYGON((0 0, 0 2, 2 -0.1, 2 2.1, 0 0)). To determine why the result changed, one would need to dig into GEOS to determine what effect reduced precision has on centroid computations, however I wonder whether centroids of such geometries is really something we should be testing? 

Probably not. My only concern would be if there's regressions in labeling - eg if labeling the centroid of a self-intersecting polygon fails. That's the only time I can think where calculating the centroid of an invalid polygon would still need to work OK. Are you able to test this?

I still haven't had a chance to build & test this, but I'm wondering... why implement as a c++ plugin? The trend at the moment is moving away from these core c++ plugins to having the feature fully integrated into the analysis + app libraries. For instance, see how the recent align rasters tool has been implemented: https://github.com/qgis/QGIS/commit/1409f08576751f02ff84bb6ec95c13dd16e3a786 and https://github.com/qgis/QGIS/commit/7bdbbb84cd56b620d94aba8e84c4d6dcbe25ab3c

It's a better approach as it allows tighter integration within QGIS and is less confusing to users.

**Comment by manisandro** [comment]
I have no problems with having it in the analysis library: I suppose the correct location would then be `src/analysis/vector/{geometry_checker,geometry_snapper}`?

As for the centroid: pal does its own centroid computation in `PointSet::getCentroid`, so it should not actually be influenced by the changes in `QgsGeos`.

**Comment by gioman** [comment]
> They do (a1d1e32), but I don't recommend it:

@manisandro @strk what we can do to make it happen sooner than later?

**Comment by manisandro** [comment]
@gioman What are you referring to with "it"?

**Comment by strk** [comment]
I'm planning to work on including @manisandro 's precision reduction extension to the GEOS C-API around November.

**Comment by gioman** [comment]
@manisandro 

> What are you referring to with "it"?

have this (very important) tools in qgis master

@manisandro @strk nice to know, thanks!

**Comment by manisandro** [comment]
@strk Great news, thanks!

@gioman I'd like to see it merged as soon as possible. Given @strk's intentions, question is whether to merge it with CPP support or not. One approach would be to merge it with CPP support and guard my GEOS C-API extension with something analogous to `#if GEOS_VER <= 3.5.0`, but still leave it optional, to allow the additional dependency to be avoided.

**Comment by pka** [comment]
@nyalldawson Any chance to merge this plugin before feature freeze?

**Comment by nyalldawson** [comment]
@pka @manisandro I don't know enough about the workings of geos to feel confident merging this myself. Perhaps @strk can give an indication if the geos related changes are safe to merge?

**Comment by pka** [comment]
@nyalldawson Normally I would ask @mhugent to merge, but he is still travelling in Korea...
There are no changes in GEOS, but the PR is using GEOS precision functionality exposed in the C++ API only. This is an issue for packaging, but as @strk indicates, it should be available via C API once. Apart from a code review it is essential that more people test this PR via nightly build to find any issues caused by potential side effects of the geometry core changes. @manisandro will be available to fix issues or revert the PR if necessary.

**Comment by mhugent** [comment]
Merged. Yes, it is important this pr goes in before feature freeze. Luckily, we are 7 hours ahead here :-)

**Pull request merged**
