### PR TITLE
fix 3D datadefined ui

### PR DESCRIPTION
**Pull request by vcloarec**
related to https://github.com/qgis/QGIS/pull/39683#issuecomment-727085919

### CODE REVIEW

**Comment by nyalldawson** [comment]
Looks good to me -- thanks!

**Comment by vcloarec** [comment]
I found another UI issue:
1- override properties for some colors
2- change to Realistic Textured (Phong)
3- change one color
4- come back to CAD or Realistic
--> data defined override are gone...

I think it comes from here : https://github.com/qgis/QGIS/blob/92254413cc69a520a4e120fc76b908ddef1cc6ea/src/app/3d/qgsmaterialwidget.cpp#L125

As the widget does not have QgsPropertyOverrideButton , the data defined expression are lost...

It is also the case with Realistic <--> CAD. If a color properties is not present in the changed material, the data defined expression is lost.

**Comment by vcloarec** [comment]
> I found another UI issue:

fixed.
@nyalldawson , are you of with that : https://github.com/qgis/QGIS/pull/40038/commits/d2d4c2cc761f9aa72706f19cd14b6bc06ee9da28

**Review by nyalldawson — APPROVED** [review]

**Comment by nyalldawson** [comment]
Thanks Vincent!

**Pull request merged**
