### PR TITLE
Backport and enhance fix export raster as GPKG

### PR DESCRIPTION
**Pull request by elpaso**
Fixes redmine 20848  gh #28667

Now checks the existence of a vector file with same
name, this should also fix the original issue.

- With test
- Requires forward port

### CODE REVIEW

**Comment by elpaso** [comment]
@borysiasty this should also fix your original issue.

**Comment by elpaso** [comment]
@m-kuhn can you please approve this one so that I can forward port?

**Comment by m-kuhn** [comment]
@elpaso the link to the fixed issue points to a closed ticket. Is this an old redmine number?

**Comment by elpaso** [comment]
Yes: https://issues.qgis.org/issues/20848

**Comment by m-kuhn** [comment]
Can you fix it in the comment?

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
