### PR TITLE
Avoid symbol cropping in legend

### PR DESCRIPTION
**Pull request by vmora**
Also add a member function to know the minimum icon size.

@wonder-sk according to @nyalldawson , this one is for you. Enjoy :)

### CODE REVIEW

**Comment by vmora** [comment]
ping @wonder-sk

**Comment by wonder-sk** [comment]
What is the relationship between this PR and #1987 ? This one looks like a subset of the other...?

I am not sure I completely understand the new "center" argument in cropTransparent() ... are there cases where centering is not wanted?

**Comment by vmora** [comment]
@nyalldawson asked that I split #1987 to have this part reviewed by @wonder-sk 

Cropping transparent area of an image can be of general use, centering leave transparent area, so I kept the function name and added the argument.

**Comment by wonder-sk** [comment]
Cool - I think the code looks good. I am just still trying to wrap my head around the new "center" thing... I still fail to understand what is the meaning of dx,dy ... looking into it now

**Comment by wonder-sk** [comment]
So if I understand correctly, if the center of the cropped image is not aligned with the original image, the  "center" argument will preserve this asymmetry. Is that correct?

**Comment by vmora** [comment]
Yes, that's it

**Comment by vmora** [comment]
which, said like that seem a bit counterintuitive.

**Comment by wonder-sk** [comment]
ok let's merge it as is, later we could rename the argument (and add more comments) to make it easier to understand what it actually does

**Pull request merged**
