### PR TITLE
[OGR provider/askUserForOGRSublayers] Use layername= instead of layerid= when no ambiguity

### PR DESCRIPTION
**Pull request by rouault**
When composing URI, use layer names if layer names are unique. This will
be more stable in case the datasource get layers added/removed (for example for
GeoPackage)

### CODE REVIEW

**Comment by gioman** [comment]
Is this issue https://issues.qgis.org/issues/16135 somehow related to this PR?

**Comment by rouault** [comment]
@gioman Yes this is related. Just changed the commit message to reflect it

@wonder-sk @SrNetoChan @strk Guys, apparently you were involved in layername vs layerid changes in the OGR provider. Can you see any problem with the above PR ? I think it should be safe: for datasets that have unique layer names, use layer names. Otherwise fallback to layer ids. Layer ids are less stable than layer names, so they should only be used as a last resort.

**Comment by wonder-sk** [comment]
Looks good to me. Ideally it would be great if OGR could always provide unique layer names - not sure how feasible that is though...

**Comment by SrNetoChan** [comment]
Hi @rouault, I don't think I was involved in any in layername vs layerid changes in the OGR provider.

**Comment by rouault** [comment]
Oops wrong Alexander. I meant @alexbruy :-)

**Comment by alexbruy** [comment]
Looks good to me

**Comment by agiudiceandrea** [comment]
Hi @rouault, it seems the "layerid= instead of layername=" bug is still / again present for FileGeoDataBase layer imported in QGIS 3 projects through the Browser panel (but not through the Data Source Manager). See https://issues.qgis.org/issues/19885#note-11

Has this fix been broken somehow or was that case not addressed by this fix?

**Comment by agiudiceandrea** [comment]
Great! Thank you.

**Pull request merged**
