### PR TITLE
Rework Select by Location algorithm

### PR DESCRIPTION
**Pull request by nyalldawson**
Changes:

- handle different CRS transparently

- don't build a spatial index on the selection layer. Instead only use feature requests to fetch features which are within the desired bounds, and rely on the presence of an appropriate spatial index at the provider's backend. Otherwise, we force every user of this algorithm to have a full iteration of the source table, regardless of how large the table is. That means that trying to select a set of addresses which fall within a specific locality from a table which contains the addresses for a whole state will FORCE every address in the state to be initially read before any calculation begins. With this change only those features within the bounding box of the selected localities will ever be fetched from the provider, resulting in huge speed improvements for the algorithm.

- use prepared geometries for the spatial relation tests. This dramatically speeds up the algorithm in the case where the intersection layer features cover multiple features from the 'selection' layer.

- Add a 'select within current selection' mode

- Optimise feature requests for efficiency (especially with respect to the 'disjoint' selection mode)

A quick test with selecting 300k points from ~3 million point layer (admittedly 'best case' scenario for these improvements):

qgis 2.x: 3 mins 10 seconds
this PR: 2.5 seconds

TODO:

The precision option in the algorithm is quite broken (has been forever - it's not a regression). I believe this option was put in place to allow selecting features which are within the set precision tolerance of the other features (e.g. selecting features which intersect another layer, but allow up to 100m difference). The method used to do this (rounding coordinates to the nearest 100m interval) doesn't work, because there's no guarantee that two values <100 would round to the same nearest 100. E.g. Point( 40,0 ) and Point( 110, 0 ) would round to Point (0, 0) and Point(100,0) - while they are < 100 different, they don't snap to the same result.

End result is that the precision option is broken in QGIS. We need to work out what to do with this.

One option would be to buffer the input features by the precision amount. E.g. take the selected localities, buffer them out 100m, then find all the addresses which fall inside these buffered features. That would work for intersects and disjoint tests, but I'm not sure it has any real meaning for the other tests like 'overlaps','crosses','within', etc. I think in this case the precision should be ignored for these predicates (and noted in the algorithm documentation).

But I'm open for other ideas!

### CODE REVIEW

**Review by alexbruy — APPROVED** [review]
Looks good to me. Great work!

**Comment by nyalldawson** [comment]
Thanks @alexbruy. Got any thoughts about the precision issue?

**Comment by nirvn** [comment]
@nyalldawson , I'd go for buffering the input features for now. It'll already dramatically improve that option.

**Comment by alexbruy** [comment]
I think @arnaud-morvan is the right person to ask about how precision should work. If I'm not wrong he added this parameter some time ago

**Comment by m-kuhn** [comment]
What happens if network latency is not optimal (i.e. requests are sent to a non-local server)?

**Comment by nyalldawson** [comment]
I don't think that will be an issue. Most of the time when someone runs this alg they will be trying to detect a smaller subset from a layer based on the relationship with a lesser number of features. It makes sense to optimise for that use case.

The other situation (selecting small number of features from a layer when comparing to a large set of related features - think selecting a couple of points which are inside a country wide River polygon layer) could be optimised I agree. But in this case there's still no regression caused by this PR, as the original code is also firing off an individual request for every feature in the related layer.

**Comment by giohappy** [comment]
The tolerance parameter is confusing to the end user. I always have to say to NOT use it in my courses. Also, as Nyall says, it's implementation doesn't do what commonlt a user would imagine: relax, in the geometrical sense, the predicates. It just snaps the geom coordinates, and it doesn't make sense in this context.
Buffering would be a misleading implementation for "tolerance": spatial relations would be altered, Also the geometrical artifacts coming from buffer operations would add an extra "grey zone" to the interpretation of the relate outputs.
For all these reasons (+ its slowness!) I vote for removal.

**Comment by m-kuhn** [comment]
> But in this case there's still no regression caused by this PR, as the original code is also firing off an individual request for every feature in the related layer.

In this case, no objections. Go ahead

**Comment by nyalldawson** [comment]
I've now ported the Extract/Select by Location algorithms to c++ in order to maximise the speed of these critical algorithms.

**Comment by alexbruy** [comment]
Should we remove Spatial Query plugin then? It duplicates Select by location algorithm. Also I'm not sure about Extract by Location algorithm, it can be reproduced by combining Select by Location and Save selected features.

**Comment by nirvn** [comment]
Algoritm combination -> shipping simple models by default in Q3.0 to lower maintenance of algorithms that can be replaced by models?

**Comment by nyalldawson** [comment]
Personally I'm ok with having the various select by/extract by combinations (there's also by expression and by attribute). In this case at least the code is nearly all shared.

Arguments for keeping them:
- slightly easier for users then doing the save step manually or creating their own models containing this step
- it's much much easier to make unit tests for the Extract By algs (none of the Select By algs are unit tested)
- they work better/more reliably in models, and don't mess with a user's layer selections

**Comment by nyalldawson** [comment]
Also +1 million to removing the Spatial Query plugin. I'll just need to make sure there's nothing else that plugin does first

**Comment by Gustry** [comment]
> Algorithm combination -> shipping simple models by default in Q3.0 to lower maintenance of algorithms that can be replaced by models?

This would be nice. Having for an instance an algorithm to Select features which`Are within a distance of X` would very nice instead of having to create a intermediate layers with buffers. Arcgis is doing : http://desktop.arcgis.com/en/arcmap/10.3/map/working-with-layers/using-select-by-location.htm

**Comment by nyalldawson** [comment]
> Also +1 million to removing the Spatial Query plugin. I'll just need to make sure there's nothing else that plugin does first

I'll defer this until a follow up PR, so that it can be discussed on its own merits

**Comment by nyalldawson** [comment]
> This would be nice. Having for an instance an algorithm to Select features whichAre within a distance of X would very nice instead of having to create a intermediate layers with buffers

We've discussed this, but its difficult because that option only makes sense for some predicates. We'd first need to add support for disabling/enabling processing options based on the values of other parameters in order for this setting not to be misleading. So that needs to be deferred to some future date when this support is in place...

**Comment by nyalldawson** [comment]
@alexbruy I consider ready for merge now, if we decide to keep the Extract By... algorithms. If not, I'd still merge this and then bring up the discussion to drop the extract algs on the list for wider discussion.

**Comment by alexbruy** [comment]
On second thought, I agree that having "Extract by..." algorithms are good. +1 to merge

**Comment by nyalldawson** [comment]
Great - only one QGIS alg left to go now!

**Pull request merged**
