### PR TITLE
Try to fix crash on GEOS 3.8.1 when empty coordinate sequence is returned

### LINKED ISSUE #35526: QGIS Desktop and Server crash on labeling of postgresql layer with many  points next to eachother
**Describe the bug**

It's been a week since I noticed server crashes and I spent the whole day trying to reproduce.
Manage to corner the bugger, finally.

Basically, on a points layer (with many many features next to eachother), if labeling is started than QGIS crashes.

**How to Reproduce**

1. restore the [points.zip](https://github.com/qgis/QGIS/files/4425290/points.zip) dump, start a QGIS project (3844 EPSG), add the data + start the labeling on the column "z"

``psql -U postgres yourdatabase -f points.dump``

2. Pan around the data.. crash

I tried checking if there was something wrong with the data but nothing (St_isvalid(geom) all return true.

I exported the data to geopackage and l cannot replicate -> labeling works fine.

I tried bisecting to the culprit but I couldn't find it as going further back than December QGIS doesn't build anymore due to new libraries.

I can replicate on:
- Debian Testing (bullseye)..different on different machines, master build from source + going back a lot; Desktop + Server without plugins
- Debian Testing - QGIS LTR 3.4.10, packages from qgis.org

I cannot replicate on Ubuntu 20 QGIS(LTR) pointing to the same datasource.
Will try to build with older libraries (proj .. and so on.. and get back here).
I changed from PostgreSQL 11 to 12, same result.

 **QGIS and OS versions**

**Additional context**

QGIS Master build from source, QGIS 3.10.4 and QGIS 3.12.1 from QGIS packages

QGIS version | 3.13.0-Master | QGIS code revision | 53075848ce
-- | -- | -- | --
Compiled against Qt | 5.12.5 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Debian 12.2-4) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid

QGIS version | 3.12.1-București | QGIS code revision | 121cc00ff0
-- | -- | -- | --
Compiled against Qt | 5.12.5 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Debian 12.2-1+b1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid
Active python plugins | pluginbuilder3; qgepplugin; plugin_reloader; scriptrunner3; trackable_project_files; db_manager; processing

QGIS version | 3.10.4-A Coruña | QGIS code revision | 10bc9f2ff2
-- | -- | -- | --
Compiled against Qt | 5.12.5 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Debian 12.2-1+b1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid
Active python plugins | pluginbuilder3; qgepplugin; plugin_reloader; scriptrunner3; trackable_project_files; db_manager; processing

### LINKED ISSUE #35719: SIGSEGV in GEOSCoordSeq_getXYZ_r / QGis 3.10 - 3.12
SIGSEGV after loading a file in QGis 3.10 (Debian) and 3.12 (from qgis.org's Debian repo)

**How to Reproduce**

- Open QGis
- Open file
- QGis crashes when I attempt to slide the map

**QGIS and OS versions**

I first add the issue with 3.10 from Debian/testing so upgraded to QGis latest but same issue.

QGIS version | 3.12.1-București | QGIS code revision | 121cc00ff0
-- | -- | -- | --
Compiled against Qt | 5.12.5 | Running against Qt | 5.12.5
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.2 (Debian 12.2-1+b1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 7.0.0 | Running against PROJ | Rel. 7.0.0, March 1st, 2020
OS Version | Debian GNU/Linux bullseye/sid
Active python plugins | processing; db_manager; MetaSearch

**Additional context**

Trace collected with GDB

```
#0  0x00007ffff014ccbd in GEOSCoordSeq_getXYZ_r () from /lib/x86_64-linux-gnu/libgeos_c.so.1
#1  0x00007ffff4a2ea8a in QgsGeos::coordSeqPoint(GEOSCoordSeq_t const*, int, bool, bool) () from /lib/libqgis_core.so.3.12.1
#2  0x00007ffff4a306e6 in QgsGeos::fromGeos(GEOSGeom_t const*) () from /lib/libqgis_core.so.3.12.1
#3  0x00007ffff4a355ab in QgsGeos::overlay(QgsAbstractGeometry const*, QgsGeos::Overlay, QString*) const ()   from /lib/libqgis_core.so.3.12.1
#4  0x00007ffff4a35798 in QgsGeos::intersection(QgsAbstractGeometry const*, QString*) const () from /lib/libqgis_core.so.3.12.1
#5  0x00007ffff4a14461 in QgsGeometry::intersection(QgsGeometry const&) const () from /lib/libqgis_core.so.3.12.1
#6  0x00007ffff49c1d1a in QgsPalLabeling::prepareGeometry(QgsGeometry const&, QgsRenderContext&, QgsCoordinateTransform const&, QgsGeometry const&, bool) () from /lib/libqgis_core.so.3.12.1
#7  0x00007ffff49cb70e in QgsPalLayerSettings::registerFeature(QgsFeature const&, QgsRenderContext&, QgsLabelFeature**, QgsGeometry, QgsSymbol const*) () from /lib/libqgis_core.so.3.12.1
#8  0x00007ffff49ddb10 in QgsVectorLayerLabelProvider::registerFeature(QgsFeature const&, QgsRenderContext&, QgsGeometry const&, QgsSymbol const*) () from /lib/libqgis_core.so.3.12.1
#9  0x00007ffff49d5d04 in QgsRuleBasedLabeling::Rule::registerFeature(QgsFeature const&, QgsRenderContext&, QMap<QgsRuleBasedLabeling::Rule*, QgsVectorLayerLabelProvider*>&, QgsGeometry const&, QgsSymbol const*) () from /lib/libqgis_core.so.3.12.1
#10 0x00007ffff49d5c28 in QgsRuleBasedLabeling::Rule::registerFeature(QgsFeature const&, QgsRenderContext&, QMap<QgsRuleBasedLabeling::Rule*, QgsVectorLayerLabelProvider*>&, QgsGeometry const&, QgsSymbol const*) () from /lib/libqgis_core.so.3.12.1
#11 0x00007ffff47c6238 in ?? () from /lib/libqgis_core.so.3.12.1
#12 0x00007ffff47c7871 in ?? () from /lib/libqgis_core.so.3.12.1
#13 0x00007ffff45fdaed in QgsMapRendererParallelJob::renderLayerStatic(LayerRenderJob&) () from /lib/libqgis_core.so.3.12.1
#14 0x00007ffff4600fa6 in ?? () from /lib/libqgis_core.so.3.12.1
#15 0x00007ffff46013c8 in ?? () from /lib/libqgis_core.so.3.12.1
#16 0x00007ffff05bea25 in QtConcurrent::ThreadEngineBase::run() () from /lib/x86_64-linux-gnu/libQt5Concurrent.so.5
#17 0x00007fffed403cf2 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007fffed400872 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007fffece39f27 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#20 0x00007fffecf512ef in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

I'm happy to help troubleshoot by running more tests, … as requested.

### PR DESCRIPTION
**Pull request by nyalldawson**
for a point geometry

Fixes #35719, fixes #35526

### CODE REVIEW

**Comment by tudorbarascu** [comment]
Confirm it fixes! Thank you!

**Comment by nyalldawson** [comment]
Thanks for the test @tudorbarascu !

**Comment by rduivenvoorde** [comment]
@nyalldawson Thanks!!

**Comment by agiudiceandrea** [comment]
Hi @nyalldawson, using the latest QGIS 3.13.0-Master (8b61e24e96) on Windows, with GEOS
3.8.1-CAPI-1.13.3 it seems to me there's an inconsistency:

`QgsGeometry.fromWkt('Polygon ((0 0, 1 1, 1 0, 0 0))').intersection(QgsGeometry.fromWkt('Point (42 0)'))`
returns **<QgsGeometry: null>**

while
`QgsGeometry.fromWkt('Polygon ((0 0, 1 1, 1 0, 0 0))').intersection(QgsGeometry.fromWkt('LineString (42 0, 43 0)'))`
returns **<QgsGeometry:   LineString EMPTY>**
and
`QgsGeometry.fromWkt('Polygon ((0 0, 1 1, 1 0, 0 0))').intersection(QgsGeometry.fromWkt('Polygon ((42 0, 43 1, 43 0, 42 0))'))`
returns **<QgsGeometry:   Polygon EMPTY>**


Intersection | POINT | LINESTRING | POLYGON
-- | -- | -- | --
QgsGeometry | <QgsGeometry: null> | <QgsGeometry:   LineString EMPTY> | <QgsGeometry:   Polygon EMPTY>
shapely wkt | POINT EMPTY | LINESTRING EMPTY | POLYGON EMPTY

**Comment by nyalldawson** [comment]
@agiudiceandrea thanks, see https://github.com/qgis/QGIS/pull/35882

**Pull request merged**
