### PR TITLE
Start removing proj < 6 support

### PR DESCRIPTION
**Pull request by nyalldawson**
Refs https://github.com/qgis/QGIS-Enhancement-Proposals/issues/197

This is thousands and thousands of lines of complex, unsupported code

### CODE REVIEW

**Comment by nyalldawson** [comment]
@m-kuhn @3nids what's required to update Travis to use proj 6/gdal 3? Can we build on a newer Ubuntu release?

**Comment by nirvn** [comment]
Good move.

**Comment by m-kuhn** [comment]
> @m-kuhn @3nids what's required to update Travis to use proj 6/gdal 3? Can we build on a newer Ubuntu release?

Enable tests on the Qt 5.14 github workflow, that already builds on a newer ubuntu version, just doesn't run any tests.

**Comment by nyalldawson** [comment]
Blocked by https://github.com/qgis/QGIS/pull/39815

**Pull request closed without merging**
