### PR TITLE
Mesh editing: Select mesh element by polygon

### PR DESCRIPTION
**Pull request by vcloarec**
In the scope of mesh editing, this PR allows the user to select mesh element by drawing a polygon.
Each vertex of the polygon is digitize by left click, right click validates the polygon and selects mesh elements (faces and vertices). Backspace key allows the user to remove last vertex, and Escape key allows to come back to the normal digitizing mode.

Two behavior modes :
Default behavior:  all touched (partially included element) will be selected (green rubber band)
Alt Modifier: only totally included elements will be selected (blue rubber band).

selectByPolygon

### CODE REVIEW

**Comment by nyalldawson** [comment]
Nice!!

> If the polygon start from left to right, all touched (partially included element) will be selected (green rubber band)
If the polygon start from right to left, only totally included elements will be selected (blue rubber band).

This isn't standard qgis behaviour -- rather we use modifier keys for this purpose:

- default to "touching/intersects mode"
- alt + drag = "only features completely within"

**Comment by vcloarec** [comment]
> This isn't standard qgis behaviour -- rather we use modifier keys for this purpose:

hmmm, so I have also to change the behavior of selecting by dragging a box... (https://github.com/qgis/QGIS/pull/44037#issue-682857605)

**Comment by nyalldawson** [comment]
> hmmm, so I have also to change the behavior of selecting by dragging a box... (#44037 (comment))

I think it would be good to do that -- it definitely helps user experience if we keep consistent shortcuts like this

**Comment by vcloarec** [comment]
> This isn't standard qgis behaviour -- rather we use modifier keys for this purpose:
> 
>     * default to "touching/intersects mode"
> 
>     * alt + drag = "only features completely within"

done (PR comment and GIF updated).

**Review by PeterPetrik — APPROVED** [review]

**Pull request merged**
