### PR TITLE
add cmake QGIS_MACAPP_FRAMEWORK option to disable .app building on OSX

### PR DESCRIPTION
**Pull request by gillins**
## Description

Conda (https://docs.conda.io/en/latest/ - and probably other package managers) expect that an install uses the normal 'Unix' directory structure. QGIS on OSX however creates a .app layout meaning that QGIS doesn't work with conda.

This PR adds an new option to cmake on OSX that allows the user to disable the .app layout and creates something similar to what happens on Linux. The default is the old behaviour (create a .app). This PR has been adapted from https://github.com/conda-forge/qgis-feedstock.

Not sure if there is a better way to do this - happy to hear from QGIS developers. Would this option be useful on OSX anyway so developers can easily create binaries that just run without installing the .app?

### CODE REVIEW

**Comment by nyalldawson** [comment]
Dammit I'd only JUST got the list of pull requests down to a single page for the first time in years! :angry: You couldn't have given me just 10 minutes to enjoy this? 

But seriously... @PeterPetrik can you look over this?

**Review by PeterPetrik — APPROVED** [review]
looks good

**Comment by gillins** [comment]
Thanks @nyalldawson ! I have a few more small packaging fixes from conda-forge - are you happy if I submit them as separate PR's?

**Comment by PeterPetrik** [comment]
sounds good @gillins

**Pull request merged**
