### PR TITLE
Add tooltip to file selector widget

### PR DESCRIPTION
**Pull request by DelazJ**
Backports #30206 

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Is there a risk of UX impact on translated versions by introducing additional (unlikely to be translated) strings?

**Comment by DelazJ** [comment]
Looking to the about page, only German who have 100% of translation, so it won't hurt many people and we know that @jef-n perfectly handles translation backport (he knows what to do for this one now :smile: 
And I'm sure that the overhead of reading English is lower than wondering why you can't save your file. And send a message to lists.

**Comment by m-kuhn** [comment]
Fair enough :+1: 
Sidenote, did someone ever look into the "branch" possibilities of transifex to manage translations for the LTR?

**Review by m-kuhn — APPROVED** [review]

**Comment by DelazJ** [comment]
> Sidenote, did someone ever look into the "branch" possibilities of transifex to manage translations for the LTR?

I think this is a true limitation for translation. And the issue has been raised a couple of times in lists (eg http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Translation-of-QGIS-ltr-and-QGIS-master-td5398470.html) with unfortunately no feedback :cry:

**Comment by m-kuhn** [comment]
Did you look into the [branching possibilities of transifex](https://docs.transifex.com/client/push#section-pushing-branch-specific-files)? I have no experience with it but I'm sure if someone reads up on it and comes forward with a good proposal no one will object.

**Comment by DelazJ** [comment]
Interesting reading. Thought branching was an Enterprise feature.
Might be worth mentioning in the list discussion, and expect... Thanks for finding.

**Pull request merged**
