### PR TITLE
Gdal algorithms can now be canceled, support progress reports

### PR DESCRIPTION
**Pull request by nyalldawson**
This PR ports execution of GDAL algorithms to the new QgsBlockingProcess class, and adds support for responsive termination of the process and for capturing progress reports:

Peek 2021-01-05 12-25

I'm sure I'm not the only one who's accidentally messed up the parameters of a GDAL algorithm and ended up with one or more endless GDAL algorithms running in the background of a QGIS session! :rofl: 

There's likely to be some fallout from this, so I'll keep on eye on the issue tracker and I'm prepared to revert if we can't get it in shape prior to release. But if we DO get it working nicely, then we should use the same process for running GRASS, SAGA and OTB algorithms too...

### CODE REVIEW

**Review by alexbruy — APPROVED** [review]

**Comment by gioman** [comment]
> There's likely to be some fallout from this, so I'll keep on eye on the issue tracker and I'm prepared to revert if we can't get it in shape prior to release. But if we DO get it working nicely, then we should use the same process for running GRASS, SAGA and OTB algorithms too...

@nyalldawson huge. Let me know if you want me do some specific manual testing.

**Comment by nyalldawson** [comment]
@gioman thanks! My biggest concern is that the new process uses a slightly different escaping mechanism for quotes vs the old one (""" vs \"). I've tested on Linux and win and it seems to be working ok, but have no way to test on macos. The easiest way to test this is with the buffer algorithm.

Aside from that, my only other concern is with the specific path /environment setup done on windows/Mac. Again, I've checked on windows and it looks ok, but not all windows systems are the same 😝. I'd love wider testing of the algorithms which use python based gdal tools to test this.

But mostly I think we'll just have to watch the tracker for incoming issues submitted by users...

**Comment by gioman** [comment]
> @gioman thanks! My biggest concern is that the new process uses a slightly different escaping mechanism for quotes vs the old one (""" vs "). I've tested on Linux and win and it seems to be working ok, but have no way to test on macos. The easiest way to test this is with the buffer algorithm.
> 
> Aside from that, my only other concern is with the specific path /environment setup done on windows/Mac. Again, I've checked on windows and it looks ok, but not all windows systems are the same stuck_out_tongue_closed_eyes. I'd love wider testing of the algorithms which use python based gdal tools to test this.
> 
> But mostly I think we'll just have to watch the tracker for incoming issues submitted by users...

@nyalldawson I will do the testing on qgis.org's mac mini :)

**Comment by gioman** [comment]
>  I'd love wider testing of the algorithms which use python based gdal tools to test this.

@nyalldawson works fine on QGIS master on macOS Catalina. I tested with gdal_polygonize and gdaldem

> The easiest way to test this is with the buffer algorithm.

worked fine too.

**Comment by nyalldawson** [comment]
@gioman thanks for the testing/feedback -- that's certainly encouraging results!

**Pull request merged**
