### PR TITLE
Add count to QgsAlgorithmRasterStatistics

### PR DESCRIPTION
**Pull request by atlight**
## Description

It's obvious to users that the count is being calculated internally (it's needed to calculate the mean), so why not present it to the user directly?

### CODE REVIEW

**Comment by atlight** [comment]
Simply awaiting a review here, I think.

**Comment by atlight** [comment]
> we will be happy to help you proceed with this pull request

Good to know!

**Comment by atlight** [comment]
@nyalldawson I see you have reviewed many recent PRs. Can you assist here?

**Comment by atlight** [comment]
> The QGIS project highly values your contribution

I'm starting to doubt the truth in this statement. Unfortunately the auto-message doesn't suggest what I should do in the event no reviewers notice the change...

**Review by rouault — APPROVED** [review]

**Comment by rouault** [comment]
@atlight I've giving it a local try and works fine as expected. Sorry for the delay in reviewing. QGIS receives a high flow in contributions and it is difficult to keep up with the pace!

**Comment by atlight** [comment]
Thanks @rouault !

**Pull request merged**
