### PR TITLE
[processing] Allow aggregate functions in modeler: Fixes #17300

### PR DESCRIPTION
**Pull request by luipir**
## Description
Add out layer to registry before its update.
Useful only in case of use waterfall aggregate functions because they get layer from registry basing on layer scope.
as in https://github.com/qgis/QGIS/blob/release-2_18/src/core/qgsexpression.cpp#L790
LayesScope does not have any direct reference to the layer object, so it has to be get from registry.
This does not allow to use concatenated aggregate functions in Processing modeller, because Processing does noto add any layer to registry during calculation.

The most generic fix would involve the scope adding directly the reference to the layer. BTW this does not accect 3.0 qgis, so probably a so wider change is not in the scope of the 2.18 branch.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by luipir** [comment]
@alexbruy @volaya pelase give a look to this fix

**Comment by fpsampayo** [comment]
I have tried these changes and they solve the [17300](https://issues.qgis.org/issues/17300) issue.
Nice work @luipir!

**Comment by luipir** [comment]
wating for merge... all tests passed and users checked it works

**Comment by luipir** [comment]
again @alexbruy @volaya there are architectural problems to review ando/or merge this PR?

**Comment by volaya** [comment]
Looks perfect and safe for me, so +1 to merge.

Great job, @luipir!

**Comment by nyalldawson** [comment]
@luipir don't you have commit rights to merge?

**Comment by luipir** [comment]
@nyalldawson no, nor to assign issue, reviewers or tag issue :/

**Comment by luipir** [comment]
tnx @strk :)

**Pull request merged**
