### PR TITLE
Python console

### PR DESCRIPTION
**Pull request by timlinux**
## Description

Fix issues with python console settings dialog:

* Use a side tabbed paradigm like other settings dialogs
* fix scrolling on overflow which is broken on OS X

I tried to copy the settings format from other dialogs but can't use  the C++ base class in python I think.

Needs some better icons on the side.....

licecap

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nyalldawson** [comment]
Hey Tim,

I've been thinking of moving this options dialog into the main options dialog (like how processing is now). For that to work we'd need to keep the tabs though, or reorganise in some other non-panel based way (or we'd have odd nested panels). What do you think?

**Comment by timlinux** [comment]
hi @nyalldawson 

Yeah having one settings panel to rule them all would be better. We have the slightly emergent issue that things are getting hard to discover there (e.g. processing is hidden by default and on Mac there isn't really much hint that you can scroll the tab list):

licecap

I know we have the search bar but that is not going to be a good way to discover general options. If we add python console settings there is is also going to be hidden by default. Maybe we need to opt for smaller icons on the left or something.....

**Comment by DelazJ** [comment]
what about reordering features in the tab panel? People are likely interested by Processing tab than Locale's... Advanced tab e.g. because of its warning could be at the lowest level.

**Comment by timlinux** [comment]
Hi @DelazJ you good idea - would you like to propose a standard order? We could try to use logic like most newbie friendly things at the top, most power user at the bottom... what do others think?

**Comment by nyalldawson** [comment]
> (e.g. processing is hidden by default and on Mac there isn't really much hint that you can scroll the tab list)

File that upstream - I think it's a bug in the OSX visual style ;) (incidentally, I've encountered this same issue in apps packaged with OSX itself!)

But seriously, I think we'd be better served with dropping down the icon size here (to 16x16 - there's really no need for the oversize icons), and then switching to a tree view so that console settings could be grouped together without the need for tabs. Something like how pycharm does it:

image

**Comment by NathanW2** [comment]
+1 for doing what PyCharm has done.

**Comment by nirvn** [comment]
@nyalldawson , or , we could consider dropping the icons altogether. That'd reduce the number of icons we have to maintain. 

Plus, while the original idea was to be able to show only icons when reducing width of the gray area, that never really worked well (state restoration broken). Moreover, now that we have search boxes at the top, smallest width still shows some text.

**Comment by NathanW2** [comment]
I would be ok to drop the icons here I think.

**Comment by nirvn** [comment]
While we're brainstorming, we could move the GDAL panel to be a sub-section to the Data Source. 

And to go back to what @DelazJ raised above, big +1 to re-order things. I've been bugged by the fact that the Advanced section is located above Processing. Let's make the ordering more intuitive.

**Comment by timlinux** [comment]
All the suggestions above sound good. The icons are a bit of a hodgepodge of styles any way....

**Comment by pcav** [comment]
Agreed on:
* dropping icons
* rearranging menu order
* putting them on a tree.
All very nice improvements.
Thanks.

**Comment by 3nids** [comment]
I like a lot the ideas here and agree with the list above.
Is anyone taking the lead on this, this almost a complete rewrite of the dialog base class?

**Comment by rduivenvoorde** [comment]
I like the tree, though not sure if that becomes too technical for non techy users....

I like to add that every 'leave' in the tree should then have some labels or metadata (like Pycharm), so it is easy to search for something. Note that these labels also have to be translatable then...
Or does pycharm search over ALL strings in the dialogs?

**Comment by timlinux** [comment]
@nyalldawson @DelazJ  @NathanW2 @3nids @pcav @rduivenvoorde 👍 

If it is ok with you I would like to merge this PR first for these reasons:

* the current settings UI is severely broken in MacOS
* this code is done and fixes the immediate issue
* I agree with the comments above but I am not sure when / if I will get time to work on them and I think what I have here represents an improvement until we have something better in place.

Any objections?

**Comment by NathanW2** [comment]
Merge it.

**Pull request merged**
