### PR TITLE
QgsVectorFilewriter skip default null options

### PR DESCRIPTION
**Pull request by m-kuhn**
Don't specify dataset options which have null default values. Setting
these as empty strings might introduce a different behavior than
expected.

For example not creating an xsd companion file for GML.

## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by rouault** [comment]
I can see a number of other QLatin1String( "" ) occurrences for default values. I guess they should receive the same fix.

**Comment by m-kuhn** [comment]
@rouault I added some more.
Sidenote: I remember a discussion about querying these options from ogr, are we there yet?

**Comment by m-kuhn** [comment]
Actually for the other ones (SetOption) it was already correctly handled before, still I think this makes code cleaner.

**Comment by rouault** [comment]
> Sidenote: I remember a discussion about querying these options from ogr, are we there yet?

They are discoverable (baring drivers which wouldn't have been updated yet). 

ogrinfo --format sqlite

One aspect I'm not sure how to handle is the internationalization of the help message (or even the English version in OGR being generally more compact than in QGIS)

**Comment by m-kuhn** [comment]
> One aspect I'm not sure how to handle is the internationalization of the help message

We could do something similar to how expression help is handled (where a script generates cpp code to inject into the translation files if I'm not wrong) https://github.com/qgis/QGIS/tree/master/resources/function_help/json
We would just need another script to generate the resources from the latest gdal version and run that regularly.

> (or even the English version in OGR being generally more compact than in QGIS)

I guess we better focus on maintaining one version upstream with descriptive texts.

**Comment by m-kuhn** [comment]
@rouault the new test results indicate that the CRS is now different. I noticed that while there's a xsd generated now, there's no more gfs. Do you have any idea what's going on?

**Comment by rouault** [comment]
> the new test results indicate that the CRS is now different. I noticed that while there's a xsd generated now, there's no more gfs. Do you have any idea what's going on?

Ah forgot about this. This is expected. A .xsd doesn't capture SRS information, and when the OGR GML driver find the .xsd it doesn't do a preliminary pass to guess it. .gfs is only generated when no .xsd can be found. So you're probably stuck with compiling your own GDAL if you can't wait 2.2.2

**Comment by m-kuhn** [comment]
Waiting a few weeks is not an issue, luckily travis is working again.

What I wonder is the proper way to generate GML files, gfs or xsd?

**Comment by m-kuhn** [comment]
@rouault what's the proper way to behave for processing (and other QGIS utilities) when creating gpkg's in your opinion, .gfs or .xsd?

**Comment by rouault** [comment]
You meant GML right, not gpkg ? For internal use in QGIS, gfs is fine (you'll the SRS info in it, contrary to xsd). For external use, as gfs is a GDAL-only thing, producing a .xsd is really the right thing to do (I suspect a number of readers might be unable to process a gml file without its companion xsd)

**Comment by m-kuhn** [comment]
Ok, so we'll need to check how to make processing behave differently when used in tests compared to when used in production. So far we didn't produce a xsd in production I think.

I must admit I'm only halfway convinced by the solution, I think tests are more valuable if close to production. Is there a good reason to not use both, gfs and xsd if present?

**Comment by rouault** [comment]
> so we'll need to check how to make processing behave differently when used in tests compared to when used in production
XSD are fine. It is just if tests need to check SRS that you're going to get into trouble. What you could for tests is delete the .xsd, so on reading OGR will generate a .gfs

> Is there a good reason to not use both, gfs and xsd if present?
Yes, they contain very similar information. So you'd have to decide which one is used for what.

**Comment by m-kuhn** [comment]
> > so we'll need to check how to make processing behave differently when used in tests compared to when used in production
>
> XSD are fine. It is just if tests need to check SRS that you're going to get into trouble. What you could for tests is delete the .xsd, so on reading OGR will generate a .gfs

Can I read this as "XSD are fine except for the lack of SRS information"?

> > Is there a good reason to not use both, gfs and xsd if present?
> 
> Yes, they contain very similar information. So you'd have to decide which one is used for what.

I probably lack some historic context here, I assume gfs was introduced because xsd information wasn't sufficient?

Anyway, the current situation is that xsd is preferred over gfs, so I assume reading only missing information (like SRS) from gfs is the logical evolution?

**Comment by rouault** [comment]
> Can I read this as "XSD are fine except for the lack of SRS information"?

Yes. .gfs also contain some synthetic information like feature count and spatial extent (the .gfs file is used only if its timestamp is >= the one of the .gml)
XSD are fine when OGR can make sense of them. It can always read XSD it has generated, but XSD can contain very complex structures the GML driver will not understand. In that case it ignores the XSD and fallbacks to guessing the structure from the .gml content and generates a .gfs

> I assume gfs was introduced because xsd information wasn't sufficient?

Not really. .gfs was introduced when .xsd is missing (in case someone just brings a gml without its companion xsd), or when the driver cannot understand the .xsd. The serialization of the .gfs is to make later re-opening faster (otherwise you'd have to do a preliminary fullscan of the .gml file each time you open it, and gml files of several GB exist)

> the current situation is that xsd is preferred over gfs, so I assume reading only missing information (like SRS) from gfs is the logical evolution?

If you have both a .gfs and .xsd, the .gfs is used and the .xsd is ignored. Currently this can happen only  if OGR cannot understand the .xsd, and thus at a prior opening has generated a .gfs

**Comment by m-kuhn** [comment]
> If you have both a .gfs and .xsd, the .gfs is used and the .xsd is ignored. Currently this can happen only if OGR cannot understand the .xsd, and thus at a prior opening has generated a .gfs

What's the drawback of always creating a gfs when writing or readin gml files, regardless xsd presence and structure complexity?

**Comment by rouault** [comment]
> What's the drawback of always creating a gfs when writing or readin gml files, regardless xsd presence and structure complexity?

Duplication of information, confusion, etc... The .gfs is a kind of last resort solution

**Comment by m-kuhn** [comment]
> Duplication of information, confusion, etc... The .gfs is a kind of last resort solution

... with added value that improve interpretation of data and performance (I guess since it can avoid a scan for feature count and extent)

**Comment by m-kuhn** [comment]
I see that the solution is also not perfect. Is there no way to store the SRS information in a standard way outside the gfs?

**Comment by rouault** [comment]
> Is there no way to store the SRS information in a standard way outside the gfs?

No. A standard GML exchange is the .gml + the various xsd (or pointers to the xsd in schemaLocation)

In case of a single layer, the GML driver could be potentially "smarter" and use the first SRS it finds in the file, assuming that it will be consistently used through all the records (which it does in particular cases like when it sees the GML is a WFS GetFeature response, which should have consistant SRS for all the records). But potentially each GML feature can have a different SRS.

**Comment by m-kuhn** [comment]
> In case of a single layer, the GML driver could be potentially "smarter" and use the first SRS it finds in the file, assuming that it will be consistently used through all the records (which it does in particular cases like when it sees the GML is a WFS GetFeature response, which should have consistant SRS for all the records). But potentially each GML feature can have a different SRS.

Would you prefer that over an opt-in solution to create an xsd (for portability) and gfs (for maximum gdal functionality) side-by-side?

**Comment by rouault** [comment]
> Would you prefer that over an opt-in solution to create an xsd (for portability) and gfs (for maximum gdal functionality) side-by-side?

Which problem are we trying to solve: processing tests, right ? If so, won't it be possible to simply destroy the .xsd file after OGR has finished written the .gml file ? Then, the .gfs file will be regenerated next time the .gml file is opened (with the caveats of wrong type checking. Which can actually happen besides the bug I fixed in trunk/2.2 branch. For example if you have a String field whose content for all features is a integer value, the .gfs will guess a Integer type)

I'd be middly enthousiastic about a solution that would generate both .xsd + .gfs, because we don't really want to promote .gfs use publicly. This is mostly a GDAL internal thing. If we chose that road, a new code path to generate a reliable .gfs would be needed (to avoid the wrong type guessing I mentionned)

Regarding making the driver be able to report a CRS when opening a .gml file with only a .xsd, I guess we could make it the default behaviour, with an open option to disable that behaviour in the rare cases where that wouldn't be appropriate, and if encountering CRS mixes, we would throw a warning so that users are aware of it, potentially trying to reproject from the geometry CRS to the layer CRS if doable.

**Comment by m-kuhn** [comment]
> Which problem are we trying to solve: processing tests, right ?

They will solve themselves by waiting for the next patch release of GDAL leaving this PR unmerged.

What I'm trying to find right now is "the right thing to produce with a default configuration". At the moment this is .gml + .gfs which apparently isn't appropriate.

Changing this behavior will break tests and require workarounds for tests to work again which make me think that there's something wrong somewhere deeper down in the stack and my preferred solution would be to assess this.

> Regarding making the driver be able to report a CRS when opening a .gml file with only a .xsd, I guess we could make it the default behaviour, with an open option to disable that behaviour in the rare cases where that wouldn't be appropriate, and if encountering CRS mixes, we would throw a warning so that users are aware of it, potentially trying to reproject from the geometry CRS to the layer CRS if doable.

Having an option (opt-in or opt-out) to force a layer to provide features in a stable and announced CRS sounds good to me :+1:

**Comment by rouault** [comment]
> At the moment this is .gml + .gfs which apparently isn't appropriate.

This is OK for QGIS internal/testing use (gfs won't likely disappear in a future GDAL version, actually they are used in GDAL configuration files to tune a few country-specific GML schemas). But I think that would confuse users if there's an explicit option to opt-in/opt-out for gfs.

> Having an option (opt-in or opt-out) to force a layer to provide features in a stable and announced CRS sounds good to me

Can you file a ticket in GDAL trac about that ?

**Comment by m-kuhn** [comment]
Thanks, I tried to summarize it here https://trac.osgeo.org/gdal/ticket/7035#ticket

**Comment by rouault** [comment]
My comment of https://trac.osgeo.org/gdal/ticket/7035
```
Hum actually looking closer at the code, I realize this is already implemented since GDAL 2.0...

You have to provide the FORCE_SRS_DETECTION=YES open option. e.g with -oo FORCE_SRS_DETECTION=YES with ogrinfo / ogr2ogr, or with GDALOpenEx()
```

**Comment by m-kuhn** [comment]
> You have to provide the FORCE_SRS_DETECTION=YES open option. e.g with -oo FORCE_SRS_DETECTION=YES with ogrinfo / ogr2ogr, or with GDALOpenEx()

Nice, what happens if this option is set and an xsd is present?

**Comment by rouault** [comment]
> what happens if this option is set and an xsd is present?

It does detect the SDK. It was added mostly for this case where the .xsd is present. I've tested it successfully.

**Comment by m-kuhn** [comment]
Of course, silly me, sorry

**Comment by m-kuhn** [comment]
> You have to provide the FORCE_SRS_DETECTION=YES open option. e.g with -oo FORCE_SRS_DETECTION=YES with ogrinfo / ogr2ogr, or with GDALOpenEx()

This would mean to rewrite [the method QgsOgrProvider::OGROpenWrapper](https://github.com/qgis/QGIS/blob/master/src/providers/ogr/qgsogrprovider.cpp#L3166-L3177) and all calls to it because the parameters changed quite fundamentally, and then conditionally supply the `FORCE_SRS_DETECTION=YES` option if the file extension is `.gml` or the gml driver is forced, correct?

**Comment by rouault** [comment]
> This would mean to rewrite the method QgsOgrProvider::OGROpenWrapper and all calls to it because the parameters changed quite fundamentally, and then conditionally supply the FORCE_SRS_DETECTION=YES option if the file extension is .gml or the gml driver is forced, correct?

Yes, we would need to replace all calls to OGROpen() by GDALOpenEx(), OGR_DS_Destroy() by GDALClose(), and all other calls to OGR_DS_xxxx by GDALDatasetxxxx. And OGRDataSourceH by GADLDatasetH and OGRSFDriverH by GDALDriverH. This should be rather mechanical.
This shouldn't change fundamentally the way  QgsOgrProvider::OGROpenWrapper() is called. I can give it a try.
Then we should have the base infrastructure to provide open options for other drivers

**Comment by rouault** [comment]
> That sounds great.

Just submitted as https://github.com/qgis/QGIS/pull/5206

> I somehow thought the GDALOpenEx API would take (lists of) strings as parameters instead of structures

It does. See https://github.com/qgis/QGIS/pull/5206/commits/0003cfdfc46a8a489bcd0b6de277529791ec9f68

**Review by rouault — APPROVED** [review]

**Comment by m-kuhn** [comment]
Summary:

* Line intersection tests fixed, because input fields are detected as strings and due to the new .xsd-enforced type-safety, the resulting fields should also be interpreted as strings (and no longer detected to be integer).
* The python field calculator algorithm actually messed up terribly with types, bug fixed

@rouault Does the gfs vs. xsd also affect geometry types?

```
======================================================================
FAIL: test_algorithms:69
'Single sided buffer multiline (bevel)', {'name': 'Single sided buffer multilin (__main__.TestQgisAlgorithms)
----------------------------------------------------------------------
[.. snip ..]
AssertionError: 'MultiPolygon (((5 1, 3 1, 3 2, 5 2, 5 1)),((5 1, 5.02418426103647 2.41477927063 [truncated]... != 'Polygon ((5 1, 3 1, 3 2, 5 2, 5 1),(5 1, 5.02418426103647 2.4147792706334, 6.02 [truncated]...
- MultiPolygon (((5 1, 3 1, 3 2, 5 2, 5 1)),((5 1, 5.02418426103647 2.4147792706334, 6.02403819033747 2.39768775047441, 5.999853929301 0.98290847984101, 5 1)))
? -----        -                         -   -                                                                                                                -
+ Polygon ((5 1, 3 1, 3 2, 5 2, 5 1),(5 1, 5.02418426103647 2.4147792706334, 6.02403819033747 2.39768775047441, 5.999853929301 0.98290847984101, 5 1))
 : Features 2/2 differ in geometry: 
 MultiPolygon (((5 1, 3 1, 3 2, 5 2, 5 1)),((5 1, 5.02418426103647 2.4147792706334, 6.02403819033747 2.39768775047441, 5.999853929301 0.98290847984101, 5 1)))
 vs 
 Polygon ((5 1, 3 1, 3 2, 5 2, 5 1),(5 1, 5.02418426103647 2.4147792706334, 6.02403819033747 2.39768775047441, 5.999853929301 0.98290847984101, 5 1))
```

**Comment by m-kuhn** [comment]
Manual comparison of the layers' geometries did not reveal any perceptible difference.

**Comment by rouault** [comment]
> Does the gfs vs. xsd also affect geometry types?

Yes, it might. If there's a .xsd that declares a gml:MultiPolygonPropertyType (or a union of gml:PolygonPropertyType and gml:MultiPolygonPropertyType), then all polygons will be promoted to multipolygons. If there's no .xsd, when guessing the geometry type, if all geometries are polygons, then the .gfs will advertize this type. So you could get a different with a .gml containing only polygons, but the OGR layer has been created with a MultiPolygon type

I could reproduce it with the following script:
```
from osgeo import ogr
ds = ogr.GetDriverByName('GML').CreateDataSource('test.gml')
lyr = ds.CreateLayer('test', geom_type = ogr.wkbMultiPolygon)
f = ogr.Feature(lyr.GetLayerDefn())
f.SetGeometry(ogr.CreateGeometryFromWkt('POLYGON((0 0,0 1,1 1,0 0))'))
lyr.CreateFeature(f)
```
This creates a .xsd that advertize MultiPolygon, but the .gml contains a gml:Polygon (the OGR GML writer should probably issue a warning or promote to multipolygon). When reading it with the .xsd, the layer geometry type and the geometry of the feature are multipolygons. If dealing the .xsd, they are polygons

**Comment by m-kuhn** [comment]
In this case it should be fine to just replace the control files for the processing tests here like done in the latest commits.
We now just compare promoted (`ST_Multi`-style) layers instead of mixed-type layers. Results can be considered equal for this case.

**Pull request merged**
