### PR TITLE
have CMake find Python library on Windows

### PR DESCRIPTION
**Pull request by SebDieBln**
Since #1527 CMake does not detect the Python library on windows (all dependencies from OSgeo4W). This PR fixes that by partly reverting the commit.

@jarl-dk Could you please verify this does not break your originally intended functionality? It was an Ubuntu issue and I only have Windows here :disappointed:

### CODE REVIEW

**Comment by m-kuhn** [comment]
There is still #1528 open for a long time. Is this somehow related?

**Comment by SebDieBln** [comment]
Yes it is as it fixes this issue, too - at least for my setup:
* Win7pro64
* CMake 3.0.2
* SDK 7.1
* QtCreator 3.5.0
* all dependencies via OSgeo4W

The key appears to be ```PATHS ${PYTHON_PREFIX}/lib ${PYTHON_PREFIX}/libs)``` which is added by this PR and by @jarl-dk's #1528 as well.

**Comment by michaelkirk** [comment]
Since this is a windows specific fix, for a problem that was, apparently, introduced by someone fixing building on linux, the code would be more self documenting if you put this change within an "IF WINDOWS" block. 

That way, a future linux developer would be less likely to change it without verifying it doesn't break windows.

**Comment by SebDieBln** [comment]
I changed this PR to incorporate @michaelkirk's suggestion. Now for non-Windows setups everything stays the same.
Note that the variable to check for a Windows system is [WIN32](https://cmake.org/cmake/help/v3.0/variable/WIN32.html), regardless of the system actually being 32bit or 64bit.

Still, I'd rather have #1528 merged than this one.

**Comment by m-kuhn** [comment]
> Still, I'd rather have #1528 merged than this one.

So should this one be closed then?
Can you comment on the other one to raise awareness?

**Comment by SebDieBln** [comment]
> So should this one be closed then?

Yes, but I would ask to wait until #1528 is merged to avoid this PR being closed and the other one still being stalled.

> Can you comment on the other one to raise awareness?

I just did.

**Comment by SebDieBln** [comment]
@m-kuhn Since #1528 seems stalled, how about merging this as a first step? #1528 will still be mergeable and appears to be only relevant for Linux, while this PR is only for the Windows guys.

**Comment by m-kuhn** [comment]
I have no problems with merging this if I am convinced that it solves an issue and doesn't do any damage.

But since I am not a windows user and I wonder why nobody else runs into this problem (or do they).

@jef-n would you mind having a short look if this looks sensible to you?

**Comment by SebDieBln** [comment]
I would like to quote @dakcarto's [comment on the original #1527](https://github.com/qgis/QGIS/pull/1527#issuecomment-51361880):
> It seems odd that we would go through the trouble of locating and defining PYTHON_PREFIX, then not use it at all in PATHS for searching for the lib.

**Comment by jef-n** [comment]
Lets see...  package(-nightly).cmd sets explicitly anyway.

**Pull request merged**
