### PR TITLE
PointLocator fix for disabled snapping

### PR DESCRIPTION
**Pull request by MorriganR**
There is no point in doing anything to snap to visible objects if snapping is disabled for the entire project.

### CODE REVIEW

**Comment by troopa81** [comment]
Is there no way to deal with this in QgsSnappingUtils or QgsMapCanvasSnappingUtils ? It seems to me that it would be more appropriate than QgsPointLocator which is low level class.

> There is no point in doing anything to snap to visible objects if snapping is disabled for the entire project.

I'm not sure to understand, but IIRC if you disable snapping for the entire project you would not create and use QgsPointLocaltor at all. Could you describe what the issue is?

**Comment by uclaros** [comment]
Also, QgsPointLocator is used on the vertex tool, regardless of snapping settings.

**Comment by MorriganR** [comment]
> @troopa81  Could you describe what the issue is?

before:

https://user-images.githubusercontent.com/31573086/113764075-26784d80-9723-11eb-87c4-389c1d49973f.mp4

after:

https://user-images.githubusercontent.com/31573086/113764159-460f7600-9723-11eb-9c70-471f899dbe92.mp4

in both tests the network latency between QGIS and PostGIS is 50ms.

**Comment by troopa81** [comment]
@MorriganR OK, so when you rotate or translate a bunch of geometries, the index rebuilt all snapping information for those geometries, which make sense.

In your PR I understand you just remove the rendering part when snap_invisibile_feature is false, this is where you gain performance, isn't it . But if the snap_invisible_feature is false, the render context should be null and not rendered (see [snappingutils](https://github.com/qgis/QGIS/blob/master/src/core/qgssnappingutils.cpp#L485) ). 

If it's not the case, that's maybe where the issue come from.

**Pull request closed without merging**
