### PR TITLE
[ui] When the color ramp shader widget list of values has been customized, maintain those values when modifying the color ramp

### LINKED ISSUE #30345: Cannot change single band raster color ramp while maintening current classes
**Describe the bug**

Similar to this previous issue  #25001, I still encounter weird behavior when dealing with single band raster pseudocolor classification, making the widget near unusable. Actually, trying to apply a new color ramp always trigger an unwanted reclassification. 

**How to Reproduce**

Load a single band raster into qgis, in style panel and pseudocolor mode, add some classes then switch the color ramp, a new classification is automaticcaly computed

autorreclass_issue

As I said in #25001, IMHO **automatic classification should only happen if the user explicitly want it** by clicking on the **intended classify button**.

**QGIS and OS versions**

QGIS 3.6 Linux 64

### PR DESCRIPTION
**Pull request by nirvn**
## Description
This PR fixes #30345 , whereas a customized list of values in the color ramp shader widget would be overwritten when modifying the color ramp.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [x] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [x] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [x] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and contain sufficient information in the commit message to be documented
- [x] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTING.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by nirvn** [comment]
Alternative approach coming in.

**Comment by nyalldawson** [comment]
Nice... does this also fix the broken auto label functionality?

**Comment by nirvn** [comment]
@nyalldawson , do you have an issue # for this broken auto label feature?

**Comment by nyalldawson** [comment]
@nirvn I don't think it's been filed - but the functionality is completely broken, it does nothing at all

**Comment by nirvn** [comment]
@nyalldawson , OK, alternative fix force pushed, I'd appreciate a quick review (nothing complicated). I'll look into the auto label stuff in a different PR.

**Comment by nyalldawson** [comment]
LGTM

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
