### PR TITLE
[geometry validation] Various bugfixes and improvements

### PR DESCRIPTION
**Pull request by m-kuhn**
Backports the following pull requests

- #9546
- #9504
- #9495
- #9493
- #9328
- #9322
- #9316
- #9308
- #9307
- #9299
- #9298
- #9295

### CODE REVIEW

**Comment by m-kuhn** [comment]
A speedy review and ok from someone would be much appreciated to have some time to test before the next patch release.
This considerably improves stability and usability but there's always a risk of issues, so some testing time would be nice.

**Review by nyalldawson — APPROVED** [review]
+1

**Comment by nyalldawson** [comment]
I'm happy to see this merged -- the changes are almost entirely confined to the geometry checking code and are little/no risk outside of this feature. So if they improve the stability and performance of geometry checking, I think they should be merged.

**Comment by m-kuhn** [comment]
Thanks Nyall, there are some people ready to test this before release!

**Pull request merged**
