### PR TITLE
Optimise expression context storage/retrieval of features

### PR DESCRIPTION
**Pull request by nyalldawson**
Shortcuts storage and retrieval of the associated feature by not storing them in the variable hash and incurring the QHash insert/lookup costs.

Shaves ~10% rendering time off a 1 million point layer

### CODE REVIEW

**Comment by wonder-sk** [comment]
Nice! What do you think about making QgsFeature live directly in QgsExpressionContext rather than in QgsExpressionContextScope?

**Comment by nyalldawson** [comment]
> What do you think about making QgsFeature live directly in QgsExpressionContext rather than in QgsExpressionContextScope?

Well, I *thought* about it. There's 2 reasons I didn't go that way:

1. I'm not sure if any code relies on overriding the feature in a temporary scope. I have a vague feeling that some of the geometry generator/25d code may do this.

2. I don't think there's a substantial cost to iterating over the scopes and finding the first with a feature now. Worst case is you're going to have a maximum of 6-10 scopes to loop over and call the bool accessor hasFeature for each. It's not likely to be a bottleneck anymore.

**Comment by m-kuhn** [comment]
> I'm not sure if any code relies on overriding the feature in a temporary scope. I have a vague feeling that some of the geometry generator/25d code may do this.

Yes, geometry generator is based on this.

Should there also be a `removeFeature()` method or `setFeature()` check for feature validity?

    void setFeature( const QgsFeature& feature ) { mHasFeature = feature.isValid(); mFeature = feature; }

**Comment by nyalldawson** [comment]
> Should there also be a removeFeature() method or setFeature() check for feature validity?

I also tried initially using the feature validity check instead of the separate bool member, but the issue here is that the valid flag cannot be relied on alone as a indication of whether a feature has been set or not. E.g. I  had test failures after making that change. I think the issue stems from QgsFeature defaulting to isValid false, so code like:

    f = QgsFeature()
    f.setGeometry( ... )
    f.setAttributes(. ...)
    scope.setFeature( f )

Would incorrectly ignore the feature because it's still flagged as not valid. There's still many parts of the code which create features without setting the validity flag (fortunately provider created features are safe here).

I probably should add a removeFeature method though, since that's impossible otherwise...

**Comment by m-kuhn** [comment]
Could we set the feature to valid as soon as `setGeometry()` or `setAttributes()` is called?

**Comment by nyalldawson** [comment]
@m-kuhn I'll move the feature validity discussion over to the api talk: https://github.com/qgis/qgis3.0_api/issues/75

**Pull request merged**
