### PR TITLE
 [mssql][needs-docs] Add connection setting to ignore invalid geometry handling

### PR DESCRIPTION
**Pull request by nyalldawson**
Sets whether the connection should skip all handling of records with
invalid geometry, which are slow and costly.

This speeds up the provider, however, if any invalid geometries
are present in a table then the result is unpredictable and may
include missing records. Only check this option if you are certain
that all geometries present in the database are valid, and any newly
added geometries or tables will also be valid!

Why would we want this? Well, SQL Server invalid geometry handling
is AWEFUL. A seriously lame, data mangling and corrupting
piece of s***. Use Postgres instead. But if you can't, then you
can at least choose to use your layers at full speed, if you
can take the responsibility that a SINGLE invalid geometry
hiding somewhere in the table will result in a whole bunch
of missing (valid) features.

SQL server is at fault here, not us. There's nothing we (or
GDAL, or MapServer, or GeoServer, or anyone else) can do
to fix this.

Suffice to say, this option is off by default, as we're better
to have a slow provider which actually shows all features.

Fixes #15752

/Rant over

I've also forward ported some fixes from 2.18 which I forgot to include in 3.0. Because.... I forgot.

### CODE REVIEW

**Comment by nyalldawson** [comment]
Looks like this: (the new "Skip invalid geometry handling" check box)

image

**Comment by nyalldawson** [comment]
@NathanW2 over to you...... sorry!

**Comment by NathanW2** [comment]
I'm ok with this.  I agree it's really not a ideal thing when it comes to SQL Server and has hit me many times in the past.

**Comment by NathanW2** [comment]
I haven't been able to test what happens on SQL Server 2016 as they rewrote all the geometry stuff in native C so maybe it's better there.

**Comment by nyalldawson** [comment]
> I haven't been able to test what happens on SQL Server 2016 as they rewrote all the geometry stuff in native C so maybe it's better there.

Nope - same with 2017

**Comment by NathanW2** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by NathanW2** [comment]
OK in that case +1 for these changes thanks.

**Pull request merged**
