### PR TITLE
Updated instructions on building QGIS master under MSVC 2015

### PR DESCRIPTION
**Pull request by idanmiara**
## Description
I've updated the docs instructions for building QGIS master under MSVC 2015 with the kind help of Jürgen.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by luipir** [comment]
@imiara can you add a significant description of the PR?

**Comment by luipir** [comment]
@jef-n can you check the WIN build procedure proposed? I'm not used to build on win (I did only using qtcreator), so I can't evaluate the proposed procedure.

**Comment by luipir** [comment]
probably also @dakcarto is interested to evaluate these steps

**Comment by imiara** [comment]
Jürgen instructed me on how to compile QGIS master with MSVC 2015. I've
updated the instructions accordingly as they were not up to date.
Is that pull request ready to merge or should I do anyting else?

I could also add later python debugging instructions using pycharm or
eclipse (thanks, Luigi Pirelli), where would be the appropriate place for
these instructions?

**Comment by luipir** [comment]
@imiara IMHO best place to add Python plugin debug in in http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/ide_debugging.html that belog to the following repo:
https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/pyqgis_developer_cookbook/ide_debugging.rst

**Comment by imiara** [comment]
Is there anything else that needs to be done for this PR to get merged?

**Review by luipir — APPROVED** [review]

**Review by luipir — APPROVED** [review]

**Comment by luipir** [comment]
better to approve and merge and leave other to check if there are errors in the proposed readme. I'm not used in Win compilation, so I can't check. I hope @jef-n or @dakcarto can merge.

**Comment by luipir** [comment]
just a note, build fail is not dependent by this PR but by a fail of processing test. This PR just change a readme. IMHO can be merged

**Comment by luipir** [comment]
@imiara can you rebase to trigger again compilation? the fail wasn't related with you pr but a fail in build infrastructure

**Comment by whatnick** [comment]
Doing a win64 build under MSVC 2015. Will keep an eye on this one.

**Comment by luipir** [comment]
as suggested by @nyalldawson in #5276, @NathanW2 can you give a review of the procedure described in this document?

**Comment by luipir** [comment]
@whatnick please give a review of the procedure

**Comment by whatnick** [comment]
I am going through the build process currently and will submit a review
tomorrow.

**Review by whatnick — CHANGES_REQUESTED** [review]
There are some caveats around Python installs, the .sln should be opened from the osgeo4w-dev commandline to select the right version of Python instead of the filesystem. In case there are multiple versions of Python on the system.

**Comment by whatnick** [comment]
No upto date paths and missing DLL's generate the errors here: https://pastebin.com/S3dmB0vh and Python components fail to build. Should have Osgeo4W path fixes to address this.

**Comment by luipir** [comment]
@whatnick AFAIK, all the builds assumes they are using the OSGeo4W python install.

**Comment by whatnick** [comment]
In my dev machine I have multiple Python versions and have to make a conscious choice to make sure the right one is used. It is specific to my environment but may occur in others. Also after the Qgis binaries are built they need to be added to the PATH for python projects to build.

**Comment by luipir** [comment]
right but in OSGeo4W env PYTHONHOME have to be point to the OSGeo4W python interpreter. Strange that it is not set. di d you run build setup inside a OSGeo4W environment?

**Comment by jef-n** [comment]
call qt5_env.bat & call py3_env.bat (like package-nightly.cmd - which also has other relevant bits).

**Comment by NathanW2** [comment]
Generally, you should be using the environment setup using OSGeo4w, That
will have all the paths set correctly and not need anything else extra
changed.

If you build with Qt Creator you can set the environment in there per build
kit which really helps.

**Comment by whatnick** [comment]
I have verified this procedure for an MSVC 2015 build and it works nicely. The only other stage I had to perform was adding the directory where Qgis binaries were produced into the path for python components to build. I use RelwithDebinfo as my default build profile and it might be small wrinkle related to this.

**Comment by m-kuhn** [comment]
Can this pull request somehow be moved forward?
Encouraging more windows devs by giving accurate information is a noble move.

**Comment by luipir** [comment]
probably need to be diffused in dev list

**Comment by nyalldawson** [comment]
I think we should merge. It's an improvement on the current docs, and can be refined later by atomic changes.

**Comment by luipir** [comment]
@nyalldawson I strongly agree. I assumed is safe to merge and already manually tested

**Comment by luipir** [comment]
@imiara may you resolve conflicts before merge?

**Comment by m-kuhn** [comment]
I reverted to the current master version for the conflicting parts. Let's merge like this. If anyone sees added value in the additional text which is missing out now (for reference, it concerns the paragraph here https://github.com/qgis/QGIS/pull/4990/commits/23c7b29dc0c5b79d57fb32c17f934d45c2875c86#diff-5179b713006607983431b49a55e63466R40), please open this in a new pull request.

**Comment by nyalldawson** [comment]
+1 to merge as is, and refine iteratively

**Comment by Codym48** [comment]
@jef-n, @NathanW2, @idanmiara, @whatnick, are you all still developing QGIS on Windows with Visual Studio 2015 Community edition? I'm about to go through this process for the first time and am willing to help update the Windows documentation.

**Comment by m-kuhn** [comment]
Maybe not "all", but some do still.
Review and feedback welcome!

**Comment by whatnick** [comment]
I haven't touched it for a while but interested to know your experience.

**Comment by jef-n** [comment]
> are you all still developing QGIS on Windows with Visual Studio 2015 Community edition?

2015 is still used to build the QGIS packages.

**Comment by Codym48** [comment]
I think it got it working - feedback over in #36212

**Pull request merged**
