### PR TITLE
Fix qgsfeature equality handling of null geometries and restore in sip bindings

### PR DESCRIPTION
**Pull request by nyalldawson**
These were (accidentally?) ommited in https://github.com/qgis/QGIS/commit/9050cc14d4c83de4b4ed44499ba73f5b70660044, and then incorrectly marked as sip_skip when sipify was first introduced as a result

### CODE REVIEW

**Comment by nyalldawson** [comment]
@m-kuhn 

If you can remember 6 years ago, can you confirm that the missing bindings from https://github.com/qgis/QGIS/commit/9050cc14d4c83de4b4ed44499ba73f5b70660044 were just an oversight and not a deliberate omission?

**Comment by m-kuhn** [comment]
95% an oversight

**Review by m-kuhn — APPROVED** [review]

**Comment by nyalldawson** [comment]
> 95% an oversight

I like those odds :sweat_smile:

**Comment by agiudiceandrea** [comment]
Hi @nyalldawson, it seems to me the issue reported at https://github.com/qgis/QGIS/issues/49932 "QgsFeature in Python isn't hashable anymore" may be a side effect of this PR.
I've checked that the issue occurs at 26eaa24934d3dc23654419d7e0c372e969e0f6e0 while it doesn't occur at d6a9d7b2ad9bb3d5a23d2e98e96fbf937b60b3ca.

**Pull request merged**
