### PR TITLE
Enable UNITY_BUILD=ON on qgis_core (37% to 50% faster builds), qgis_gui (50% faster builds), qgis_analysis (3.7x faster)

### PR DESCRIPTION
**Pull request by rouault**
On top of PR #59667 

Besides much faster compilation time, we also get massive reduction of the size of build artifacts !!!

That said UNITY_BUILD tend to be fragile. To debate if we want to enable them conditionally or not

* On Ubuntu 22.04, QT5, debug builds

With just precompiled qgis.h header:

```bash
$ time make -j12 qgis_core
real	6m3.472s
user	59m3.835s
sys	5m22.424s

$ du -c src/core | tail -n 1
2137448	total

$ ll ./output/lib/libqgis_core.so.3.41.0 
-rwxr-xr-x 1 root root 598395456 Nov 30 00:56 ./output/lib/libqgis_core.so.3.41.0*
```

vs with UNITY_BUILD, *37% faster*:

```bash
$ time make -j12 qgis_core
real	3m45.263s
user	24m3.530s
sys	1m48.078s

$ du -c src/core | tail -n 1
944580	total

$ ll ./output/lib/libqgis_core.so.3.41.0 
-rwxr-xr-x 1 root root 278469184 Nov 30 03:35 ./output/lib/libqgis_core.so.3.41.0*
```

* On Fedora:rawhide, QT6, debug builds

With just precompiled qgis.h header:

```bash
$ time ninja qgis_core
real	10m35.657s
user	97m51.161s
sys	7m59.564s

$ du -c src/core | tail -n 1
3028420	total

$ ll ./output/lib/libqgis_core.so.3.41.0 
-rwxr-xr-x 1 root root 825732184 Nov 30 00:38 ./output/lib/libqgis_core.so.3.41.0
```

vs with UNITY_BUILD, *50% faster*:

```bash
$ time ninja qgis_core
real	5m13.791s
user	41m42.880s
sys	3m8.986s

$ du -c src/core | tail -n 1
1333320	total

$ ll ./output/lib/libqgis_core.so.3.41.0 
-rwxr-xr-x 1 root root 389392736 Nov 30 03:05 ./output/lib/libqgis_core.so.3.41.0
```

### CODE REVIEW

**Comment by nyalldawson** [comment]
My gut feeling is this should be conditional, defaulting to off but on for ci. But I'm interested in other's thoughts!

**Comment by m-kuhn** [comment]
Interesting.
I don't have experience with this.

> My gut feeling is this should be conditional, defaulting to off but on for ci.

I agree, from a short read about the topic there's a risk of semantic changes (dangerous for release) and incremental builds may even suffer performance wise (?)

As we do a lot of ccache for tests too, I wonder about the real effect there, is that still 37-50% faster?

**Comment by rouault** [comment]
> I don't have experience with this.

I've done that for GDAL and PROJ. Part of our CI use unity builds, part regular builds. The default is *not* unity builds, out of caution. I initially hit bugs, most of them caught at compilation time, a few residual ones by test suite (I've a memory of one that was really tricky to track down. It turned out to be due to code that relied on inherently undefined behavior, and with a unity build, the optimizer used that to optimize away the wrong code... https://github.com/OSGeo/gdal/commit/7104ec651abdff1b98f0849708ed1322653e10b5). So I'm inclined to make it conditioned by ``option(ENABLE_UNITY_BUILDS "Enable Unity builds (EXPERIMENTAL. Not recommended for production builds)" OFF)`` for QGIS

> As we do a lot of ccache for tests too, I wonder about the real effect there, is that still 37-50% faster?

That's a good question. It will depend on the content of pull requests. Typically a unity build reduces the number of compilation units by 8 or so. So if you have a pull request that touches only one .cpp file, at least 7 others will also be rebuilt. So that's something like going from a 1 second incremental build time to 8 seconds, considering all other are ccached. Not a big deal for CI purposes... But that might be a big deal for a developer wanting to quickly iterate during development and if struggling with some compilation errors (like fighting with templates, etc...)
Other CI use cases might be qgis.h being modified and causing a full rebuild, in that case that's going to be a clear win. My feeling is that in average it should be beneficial.
In non CI use cases, using unity builds might be beneficial for a moderately active QGIS developer or enthusiast user that doesn't develop frequently but "git pull && ninja" once a week to keep track. Updating every week generally pull changes that causes a full rebuild.

**Comment by m-kuhn** [comment]
Sounds reasonable :+1:

**Comment by rouault** [comment]
I've pushed extra changes:
- introducing ENABLE_UNITY_BUILDS CMake variable, and defaulting it to OFF
- using it in src/core/CMakeLists.txt
- making the few needed changes to enable qgis_gui unity builds, and enabling qgis_gui unity builds if ENABLE_UNITY_BUILDS

For qgis_gui, unity builds for qt5 are 60% faster (from 5m 45s clock time down to 2m 12s, and 53m30s total cpu time down to 18m 8s)

**Comment by m-kuhn** [comment]
I'd love to see the impact on the windows-qt6 builds (MSVC is notoriously slow)

**Comment by rouault** [comment]
fedora:rawhide, qt6, qgis_gui, unity: real 6m30, user 45m20s, sys 5m1s
fedora:rawhide, qt6, qgis_gui, regular: real 12m48, user 108m33, sys 10m36s

ubuntu:22.04, qt5, qgis_analysis, unity: real 0m42s, user 5m39s, sys 0m26s
ubuntu:22.04, qt5, qgis_analysis, regular: real 2m37s, user 26m25, sys 2m18s

> I'd love to see the impact on the windows-qt6 builds

I've enabled it for windows-qt6 as well and the results are quite spectacular!
- master: 3h 13m
- PR 59667 (precompiled headers): 2h 2m
- this PR (precompiled headers + unity builds for core, gui and analysis): 1h 24m

>  (MSVC is notoriously slow)

has clang for Windows been considered? It has the same C/C++ ABI as MSVC: https://clang.llvm.org/docs/MSVCCompatibility.html.

**Comment by m-kuhn** [comment]
> I've enabled it for windows-qt6 as well and the results are quite spectacular!
> 
> * master: 3h 13m
> * PR 59667 (precompiled headers): 2h 2m
> * this PR (precompiled headers + unity builds for core, gui and analysis): 1h 24m

Wow! 🐝💨

> > (MSVC is notoriously slow)
> 
> has clang for Windows been considered? It has the same C/C++ ABI as MSVC: https://clang.llvm.org/docs/MSVCCompatibility.html

I've used it in the past and it performed better. I had troubles in other scenarios. I don't recall the details unfortunately, but it might be worth another try.

**Comment by m-kuhn** [comment]
@rouault I enabled ccache for testing reasons, I hope you don't mind

**Review by nyalldawson — APPROVED** [review]

**Comment by m-kuhn** [comment]
Rebuild with ccache: 67m

**Comment by rouault** [comment]
> Win Rebuild with ccache: 67m

I found a master windows-qt6 build (https://github.com/qgis/QGIS/actions/runs/12070745214/job/33660951496) done by auto sipify which was 48 minute long, with following ccache stats:
```
Cacheable calls:   3162 / 3240 (97.59%)
    Hits:            2994 / 3162 (94.69%)
      Direct:        2819 / 2994 (94.15%)
      Preprocessed:   175 / 2994 ( 5.85%)
    Misses:           168 / 3162 ( 5.31%)
  Uncacheable calls:   78 / 3240 ( 2.41%)
  Local storage:
    Cache size (GB):  1.0 /  1.0 (99.86%)
    Cleanups:          33
    Hits:            2994 / 3162 (94.69%)
    Misses:           168 / 3162 ( 5.31%)
 ```
 
 and the latest build of this PR:
 ```
   Cacheable calls:   669 / 1090 (61.38%)
    Hits:            661 /  669 (98.80%)
      Direct:        567 /  661 (85.78%)
      Preprocessed:   94 /  661 (14.22%)
    Misses:            8 /  669 ( 1.20%)
  Uncacheable calls: 421 / 1090 (38.62%)
  Local storage:
    Cache size (GB): 0.2 /  1.0 (16.08%)
    Hits:            661 /  669 (98.80%)
    Misses:            8 /  669 ( 1.20%)
```

So for some reason unity builds would reduce the number of cacheable calls. The good and bad news is that it isn't a Windows specific behavior. I unfortunately reproduce that on ubuntu:22.04 I get a 0% cache hit when rebuilding qgis_core...

**Comment by rouault** [comment]
hum trying on ubuntu 22.04, the bad news is that the incompatibility with ccache isn't related to unity builds but with the precompiled headers. We have propably merged #59667 too soon.
The good news is that I've fixed it finding in the ccache manual (https://ccache.dev/manual/4.10.2.html#_precompiled_headers),  that you need to run "ccache --set-config sloppiness=pch_defines,time_macros". I confirm this works fine now with unity_builds on my system. I've added a commit for that

**Comment by rouault** [comment]
windows-qt6 build: first run 71 minutes, re-run 72 minutes with 65% cache it and 92% cacheable calls
build 22.04 qt5: first run 35 minutes, re-run in 33 minutes with a 78% ccache hit and 78% cacheable calls (I should have noted the one in the first run...)
build 39 qt6 : first run 1h 2minute, second in 1h 3 with also a 78% ccache hit and 78% cacheable calls

That said, on fedora:rawhide qt6, qgis_core builds with precompiled headers (independently of whather unity builds are enabled) do not trigger any ccache hits when wiping off build/src/core, in particular when removing the .gch precompiled header. It seems that its regeneration makes it to be considered as something non cacheable. Not sure if the issue is relate to the version of cmake, ccache, qt6, g++ or something else, compared to ubuntu 22.04 where things work just perfectly.

I'm not sure what conclusion to draw from that. For developer use cases, where you don't normally wipe off your build directory, even the issue with fedora:rawhide qt6 shouldn't be much a practical issue. But for CI builds this is more annoying.
So in the current situation, for QT6 builds we should probably disable pre-compiled headers on CI (unity builds themselves are fine)

**Comment by nyalldawson** [comment]
@rouault does it help if you crank up the ccache max size? I've always found the default (on fedora at least) to be much too small

**Comment by nyalldawson** [comment]
@rouault 
> That said, on fedora:rawhide qt6, qgis_core builds with precompiled headers (independently of whather unity builds are enabled) do not trigger any ccache hits when wiping off build/src/core, in particular when removing the .gch precompiled header. It seems that its regeneration makes it to be considered as something non cacheable. Not sure if the issue is relate to the version of cmake, ccache, qt6, g++ or something else, compared to ubuntu 22.04 where things work just perfectly.

I just tested F41, qt5 build and I get a 100% hit rate (after the ccache config change) after a build folder wipe-and-rebuild:

```
Cacheable calls:   4274 /  4854 (88.05%)
  Hits:            4274 /  4274 (100.0%)
    Direct:        4182 /  4274 (97.85%)
    Preprocessed:    92 /  4274 ( 2.15%)
  Misses:             0 /  4274 ( 0.00%)
Uncacheable calls:  580 /  4854 (11.95%)
Local storage:
  Cache size (GB):  3.1 / 100.0 ( 3.10%)
  Hits:            4274 /  4274 (100.0%)
  Misses:             0 /  4274 ( 0.00%)
```

For F41, qt6 build:

```
Cacheable calls:   4010 /  4564 (87.86%)
  Hits:            3396 /  4010 (84.69%)
    Direct:        3292 /  3396 (96.94%)
    Preprocessed:   104 /  3396 ( 3.06%)
  Misses:           614 /  4010 (15.31%)
Uncacheable calls:  554 /  4564 (12.14%)
Local storage:
  Cache size (GB):  6.3 / 100.0 ( 6.26%)
  Hits:            3396 /  4010 (84.69%)
  Misses:           614 /  4010 (15.31%)
```

**Comment by rouault** [comment]
ok, I finally figured out the magic needed to make ccache works properly on fedora:rawhide with QT6 and /usr/bin/c++ being the compiler which ccache doesn't understand out-of-the-box to be g++, which requires to set a ccache config item.  Let's see if the changes also help for Windows Qt6...

**Comment by rouault** [comment]
I found https://github.com/ccache/ccache/issues/1383 which indicates that there's no point in enabling precompiled headers with the combo MSVC + ccache, so I've aded a commit to disable them in that situation

**Comment by rouault** [comment]
I think this PR is now ready for merge:

windows-qt6, (almost) cold cache build, 1h16 (https://github.com/qgis/QGIS/actions/runs/12112392447/job/33765756353?pr=59669)
```
  Cacheable calls:   1007 / 1085 (92.81%)
    Hits:             661 / 1007 (65.64%)
      Direct:         567 /  661 (85.78%)
      Preprocessed:    94 /  661 (14.22%)
    Misses:           346 / 1007 (34.36%)
  Uncacheable calls:   78 / 1085 ( 7.19%)
  Local storage:
    Cache size (GB):  0.7 /  1.0 (73.11%)
    Hits:             661 / 1007 (65.64%)
    Misses:           346 / 1007 (34.36%)
```

windows-qt6, hot run, 38 m (https://github.com/qgis/QGIS/actions/runs/12112392447/job/33767720112?pr=59669)
```
  Cacheable calls:   1007 / 1085 (92.81%)
    Hits:             995 / 1007 (98.81%)
      Direct:         893 /  995 (89.75%)
      Preprocessed:   102 /  995 (10.25%)
    Misses:            12 / 1007 ( 1.19%)
  Uncacheable calls:   78 / 1085 ( 7.19%)
  Local storage:
    Cache size (GB):  0.8 /  1.0 (75.35%)
    Hits:             995 / 1007 (98.81%)
    Misses:            12 / 1007 ( 1.19%)
```

**Review by m-kuhn — APPROVED** [review]
Excellent job, thanks !

**Review by nyalldawson — APPROVED** [review]

**Pull request merged**
