### PR TITLE
[processing] Update OGR tools

### PR DESCRIPTION
**Pull request by om-henners**
I've made two modifications to the processing OGR tools:
- In the ogrinfo tool I've added the ability to turn off summary output as a boolean option (it's enabled by default).
- In the ogr2ogr SQL tool I've fixed the input path quoting, and added the abilty to select a SQL dialect via a dropdown menu (as an optional argument - default is still no dialect).

Note that these tools to change the arguments for these tools so scripts using them may be incompatible with the updated version. That said, the current SQL execution didn't work at all due to the extra quotes, so I believe that won't be an issue.

### CODE REVIEW

**Comment by gioman** [comment]
assigned @volaya @alexbruy

**Comment by alexbruy** [comment]
We are in the feature freeze now and this PR breaks Processing API. If I'm not wrong, we agreed that such changes should be avoided during normal release cycle, API changes will go to the next major version of QGIS.

@volaya correct me if I'm wrong.

**Comment by om-henners** [comment]
Makes sense. Would you like me to submit a separte pull for just the 4c1e056 by itself as the actual bugfix in the OGRSQL?

**Comment by fsdias** [comment]
@om-henners yes, please issue a separate pull request for the bug fix

**Pull request merged**
