### PR TITLE
Enable clazy on travis

### PR DESCRIPTION
**Pull request by m-kuhn**
No idea if this actually works
But it's worth a try I guess

### CODE REVIEW

**Comment by m-kuhn** [comment]
@nyalldawson clazy is up and running. I'll let you select the set of tests to run if you don't mind.

**Comment by nyalldawson** [comment]
(fingers crossed!)

**Comment by nyalldawson** [comment]
FWIW, here's my earlier attempt: https://github.com/nyalldawson/QGIS/commits/codequality

It predated all the current docker based testing infrastrucutre though, so likely not much use there...

**Comment by m-kuhn** [comment]
you know one set of warnings we can enable without triggering errors?

**Comment by nyalldawson** [comment]
connect-3arg-lambda

If that one is thrown then it's a crash waiting to happen

**Comment by nyalldawson** [comment]
Not bad.... https://travis-ci.org/qgis/QGIS/jobs/606887917?utm_medium=notification&utm_source=github_status

**Comment by nyalldawson** [comment]
Try 2...

**Comment by m-kuhn** [comment]
@nyalldawson cherry-picked #32614

**Comment by m-kuhn** [comment]
@elpaso do you think this is a problem here? https://travis-ci.org/qgis/QGIS/jobs/607255223#L696-L704

https://github.com/KDE/clazy/blob/master/docs/checks/README-lambda-unique-connection.md

**Review by nyalldawson — APPROVED** [review]
Let's merge!!

**Pull request merged**
