### PR TITLE
[locator] Fix lack of locale awareness for DMS coordinates

### PR DESCRIPTION
**Pull request by nirvn**
## Description

Because in parts of the world, this is valid `6°26'55,7" 44°53'0,2"`.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks!
Should that be a fallback from the C locale (or is it already)?
I'm quite sure French people also get C locale strings?
not sure germans will be amused finding a point interpreted as thousands separator.

**Comment by nirvn** [comment]
@m-kuhn , there's already a fallback to C locale in the regular expression string. Because we're dealing with lat lon coordinates, we never get numbers that are greater than 180, and therefore never need a thousand separator. This allows us to have _one_ expression to cover both a locale-specific decimal point character as well as the C locale dot character as fallback.

**Comment by m-kuhn** [comment]
Goid to know 👍

What happens in German to `6°26'55.756" 44°53'0.645"`?

**Comment by nirvn** [comment]
@m-kuhn , it'll handle the dot as the decimal separator as Germans would expect :)

**Review by m-kuhn — APPROVED** [review]

**Pull request merged**
