### PR TITLE
server tests for GetFeatureinfo different widget values

### PR DESCRIPTION
**Pull request by tudorbarascu**
Follow-up from https://github.com/qgis/QGIS/pull/6450 discussion

QGIS Server tests to insure Server GetFeatureInfo request output the different widget correct values

@pblottiere I commented out the failing tests so that it's merge-able. Thank you.

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [x] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [x] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by tudorbarascu** [comment]
@pblottiere The tests are ready. Still have some ideas for more tests but will came later on.

**Comment by tudorbarascu** [comment]
I believe this can safely be merged as it adds a working test + some disabled ones as there are some regressions in QGIS Server.

**Comment by elpaso** [comment]
@tudorbarascu LGTM thanks!

I'd only recommend to uncomment the commented tests and add an expected failure decorator `@unittest.expectedFailure` keeping the comment that explains why they are an expected failure for now.

**Comment by tudorbarascu** [comment]
@elpaso Thanks!

**Pull request merged**
