### PR TITLE
Rework map touch tool

### PR DESCRIPTION
**Pull request by nyalldawson**
Qt5 allows runtime detection of touch devices. This commit reworks the current touch map tool by pulling its behavior into the normal pan tool when a touch device is detected.

It avoids the need for a separate map tool for touch interaction, and also avoids having this tool always appear on the Windows builds (regardless of the presence of a touch device)

### CODE REVIEW

**Comment by nirvn** [comment]
Nice. Glad to see touch support integrated with the pan tool.

**Comment by nyalldawson** [comment]
@mbernasocchi looks like you originally added this tool - any opinions on this change? @m-kuhn any impact on the android/qfield work?

**Comment by m-kuhn** [comment]
The map tool touch was something I was hoping to merge with the pan tool for a long time already. It won't have any effect on qfield, we will need to check with QGIS for Android (the main target of the original development if I am not mistaken).

One thing I'm wondering is, if it would be worth integrating it with the map canvas directly. Or does pinching while digitizing work already? I can imagine this would be handy (just like the mouse wheel or panning with shift works at the moment).

Thanks.

**Comment by nyalldawson** [comment]
> Or does pinching while digitizing work already?

Possibly. I actually don't have any devices handy that I can test this with, which is why I took a safe(?) approach here and just copied the existing code.

Can I leave this with you to test for Android and confirm that it's safe to merge?

**Comment by mbernasocchi** [comment]
Great.
iirc pincing on a touchpad on a laptop is also working like a touch device. A fairly common touch device for testing :)

On 13 February 2017 10:30:12 CET, Nyall Dawson <notifications@github.com> wrote:
>> Or does pinching while digitizing work already?
>
>Possibly. I actually don't have any devices handy that I can test this
>with, which is why I took a safe(?) approach here and just copied the
>existing code.
>
>Can I leave this with you to test for Android and confirm that it's
>safe to merge?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/qgis/QGIS/pull/4138#issuecomment-279335048

-- 
Marco Bernasocchi (mobile).
OPENGIS.ch - berna.io - 27summits.ch

**Comment by m-kuhn** [comment]
I just tested on Android.
One thing that is still missing is live update with a cached scaled/translated image of the map while pinching. This really should be a must-have IMO.

**Comment by nyalldawson** [comment]
@m-kuhn does the current touch tool do that?

**Comment by m-kuhn** [comment]
Ah no, I thought so, but I must have been remembering QField.

**Comment by m-kuhn** [comment]
Thanks @nyalldawson !

**Pull request merged**
