### PR TITLE
QgsRasterBandComboBox

### PR DESCRIPTION
**Pull request by nyalldawson**
There's a lot of duplicate code relating to creating and handling combo boxes showing available raster bands. This PR creates a new QgsRasterBandComboBox subclass designed to consolidate all this code into a single class.

Additionally, new logic has been added to set the combo box as disabled whenever the raster has a only a single band (better UX in my opinion, given that the widget cannot be used and has no effect in this situation)

### CODE REVIEW

**Comment by nirvn** [comment]
Nice one.

**Review by 3nids — APPROVED** [review]
Great, I had a python library for that, glad to see this in core.
Not mandatory but would be nice to add the custom widget for it too.

**Comment by nirvn** [comment]
Thinking about this PR again, I'm not 100% sure we should deactivate the combo box when only one band is present. It might confuse users. I.e., how to differentiate whether a combo box is disabled because the overarching function linked to it isn't enabled, vs. disabled because it has only one band?

**Comment by nyalldawson** [comment]
> Great, I had a python library for that, glad to see this in core.

@3nids got anything else in your library which would be of value to add here?

> Not mandatory but would be nice to add the custom widget for it too.

Will do

**Comment by 3nids** [comment]
It was quite basic, everything seems to be here :)
I tend to agree with Mathieu but no strong opinion

**Pull request merged**
