### PR TITLE
add qscintilla to cmakelists

### PR DESCRIPTION
**Pull request by Gustry**
To build on mac, we need this line
Is-it possible to backport to 2.16 ?

### CODE REVIEW

**Comment by manisandro** [comment]
@Gustry What error do you get without that line?

**Comment by Gustry** [comment]
@manisandro I got
```
/Users/etienne/compil/QGIS/src/providers/arcgisrest/../../gui/qgscodeeditor.h:22:10: fatal error: 'Qsci/qsciapis.h' file not found
#include <Qsci/qsciapis.h>
         ^
15 warnings and 1 error generated.
make[2]: *** [src/providers/arcgisrest/CMakeFiles/arcgismapserverprovider.dir/qgsamssourceselect.cpp.o] Error 1
make[1]: *** [src/providers/arcgisrest/CMakeFiles/arcgismapserverprovider.dir/all] Error 2
make: *** [all] Error 2
16:50:13: The process "/usr/local/Cellar/cmake/3.6.0/bin/cmake" exited with code 2.
Error while building/deploying project qgis2.99.0 (kit: QGIS Build kit)
When executing step "Make"
16:50:13: Elapsed time: 00:31.
```

**Comment by manisandro** [comment]
@Gustry Ah looks like the dependency originates from the query builder used in the source select dialog.

**Comment by Gustry** [comment]
Should I do the same PR for 2.16 @manisandro ?

**Comment by manisandro** [comment]
@Gustry Already cherry-picked [1], thanks.

[1] https://github.com/qgis/QGIS/commit/b09eef180a688ee0eb9bf4c930b7f479bebf5918

**Pull request merged**
