### PR TITLE
Mac bundling fixes

### PR DESCRIPTION
**Pull request by kyngchaos**
## Description

A collection of bundling fixes for macOS.

### CODE REVIEW

**Comment by kyngchaos** [comment]
Notes
- checking for Qt codecs plugin folder fails because codecs does not exist in Qt 5
- qgis_quick installed in wrong location - install must come after setting properties to get the correct Mac properties, including install location
- take care of install_name_tool changes for quick components
- installed-Qt path is added to rpath for Qgis binaries, cmake handles stripping this rpath out automatically for project binaries but not for bundled binaries, ie Qt itself, this leads to Qgis trying to load plugins from the installed Qt instead of the bundled Qt, causing a crash

**Comment by kyngchaos** [comment]
Argh, another travis failure not related to PR fixes.  test 586:

CMake Error at PyQgsOfflineEditingWFS.cmake:15 (MESSAGE):
5102  Test failed: 124

**Comment by kyngchaos** [comment]
I'm confused - top of pull request says 5 commits merged, comment says only 1 commit merged (one with check mark). I didn't notice the discrepancy and added a  label and only the one merge was added to the backport.

**Comment by nyalldawson** [comment]
Ah - sorry. I did a squash merge to avoid issues... I just forgot about it :o I've reopened the backport

**Comment by kyngchaos** [comment]
and this pull request is closed and I don't see any way to reopen it to make sure the other commits are merged.

**Comment by kyngchaos** [comment]
ok, it looks like all the commits merged here.  how can I make sure they make it to the backport?  I want to also backport to 3.12 (I started with adding 3.10 to make sure it worked).

**Comment by nyalldawson** [comment]
Check the diff in the backport PR

**Pull request merged**
