### PR TITLE
Use nullptr instead of 0 or NULL

### PR DESCRIPTION
**Pull request by nyalldawson**
Following up 320c696, this commit uses clang-modernize to replace all 0/NULL pointer values with nullptr.

### CODE REVIEW

**Comment by NathanW2** [comment]
`nullptr` is just better?

**Comment by nyalldawson** [comment]
It's the way of the future - see http://stackoverflow.com/questions/20509734/null-vs-nullptr-why-was-it-replaced

basically it's correctly typed, so a function with an overload taking a pointer argument and one taking an integer will correctly call the pointer version when `nullptr` is used, rather than the int version if `0` or `NULL` is used.

**Comment by NathanW2** [comment]
Good move

**Comment by nyalldawson** [comment]
Manually merged

**Pull request closed without merging**
