### PR TITLE
[WIP] [processing] Add useCheckBoxes option to SelectionWidgetWrapper

### PR DESCRIPTION
**Pull request by arnaud-morvan**
## Description

This allow to show radioboxes / checkboxes intead of combobox/  lineedit + button.
This is configurable for each algorithm thought `ParameterSelection` `metadata` parameter.
It is also possible to choose the number of columns.
This is not applied in case of the `BatchDialog`.

Note that this is just an option and only the algorithms with specific metadata are affected, for all the others, nothing change, the default stay the same.

### In simple selection mode:

Before:
image

After:
image

### In multiple selection mode:

Before:
```
self.addParameter(ParameterSelection(
            self.PREDICATE,
            self.tr('Geometric predicate'),
            self.predicates,
            multiple=True))
```
image

After:
```
self.addParameter(ParameterSelection(
            self.PREDICATE,
            self.tr('Geometric predicate'),
            self.predicates,
            multiple=True,
            metadata={
                'widget_wrapper': {
                    'class': 'processing.gui.wrappers.SelectionWidgetWrapper',
                    'useCheckBoxes': True,
                    'columns': 2}}))
```

image

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [x] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
@alexbruy @volaya : Could you have a look if you have some time.

**Comment by arnaud-morvan** [comment]
Hello, what about merging this ?

**Comment by nyalldawson** [comment]
Can we hold off on this for a bit longer? I'm about to dump another massive refactoring part of the processing -> c++ work and it directly affects parameter and widgets.

**Comment by arnaud-morvan** [comment]
Yes, this is just a small UI improvement, so I will probably discover your refactoring while rebasing this.

**Comment by m-kuhn** [comment]
@arnaud-morvan / @nyalldawson I think the time to refactor should be fine now?

**Comment by nyalldawson** [comment]
Superseded by #5171

**Pull request closed without merging**
