### PR TITLE
Test on postgres 10 and postgis 2.4

### PR DESCRIPTION
**Pull request by m-kuhn**
## Description
Include a few sentences describing the overall goals for this PR (pull request). If applicable also add screenshots.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [ ] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [ ] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks @timlinux

**Comment by timlinux** [comment]
Pleasure :-) Thanks for testing against PG 10 now!

**Comment by timlinux** [comment]
Ouch - seems there is a problem with my docker build - it actually has pg 9.6 - I am busy fixing the 10 build - will let you know here when it works.

**Comment by m-kuhn** [comment]
No worries from my side, I just wanted to have a quick check for any easily discoverable issues. I don't mind too much if we have the ci tests on one or the other (actually it's probably better to stick to the old version to not use any new features that 80% of the environments don't support).

**Comment by timlinux** [comment]
By the way my docker build is fixed and should properly deliver you a working PostGIS 10 install - if you are still interested in pursuing this PR please go ahead and test again.

**Pull request closed without merging**
